### PR TITLE
Pallet Supersig - Milestone 2

### PR DESCRIPTION
**Pull request by decentration**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/959

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @decentration, thanks a lot for the delivery. I started the evaluation, I'll post my notes the next week!

**Comment by decentration** [comment]
hey @0xCaso awesome, look forward.

**Comment by 0xCaso** [comment]
Here I am, I leave you the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pallet_supersig_2_0xCaso.md). Let me know if you have any questions!

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Here I am, I leave you the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pallet_supersig_2_0xCaso.md). Let me know if you have any questions!

**Comment by decentration** [comment]
> Here I am, I leave you the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pallet_supersig_2_0xCaso.md). Let me know if you have any questions!

Fantastic, let me go through your points... : )

**Comment by decentration** [comment]
Great feedback @0xCaso thank you. 

**0c**
- Medium ✅ ah yes, sorry if that slowed you down, the pesky Medium platform is prone to mess up the formatting, but that's fixed now. 
- RPC tests, great catch will add those in for Milestone 3 (feedback and improvements milestone), which will follow this review as its 95% done as well. 
- Testing `leaveSupersig` and `deleteSupersig`:

`leaveSupersig` is very simple, if you are a member you just select your account,  go to supersig > leaveSupersig, and select the supersig account you would like to leave and that should be good. 

`deleteSupersig`, needs to be a proposal, so you need to wrap a deleteSupersig call within a submitCall function:
-  first select your account, then go to supersig > submitCall, 
- then select the supersig you would like to propose to delete, 
- then you go to select supersig > deleteSupersig,
- then you need to vote for it by going to supersig > approveCall (do not wrap it in a submitCall). and make sure >51% of members vote for it, so that the call will be executed.

**Substrate module: pallet_supersig**
> The functionalities should work, I just noted one thing: if I try to perform a tx with a Supersig through a member, and it's not funded, after the proposal passes the tx fails, but there is no way to see the failure. This because the last voting, which makes the proposal pass, gets through (and it's visible from the UI), but then the tx itself fails and the UI won't show it (neither in the Network page). Is there a way to let this see to the user?

Yes, this is a well considered scenario, it is true that failed calls do not show an error or log an event that shows that the vote passed but the call itself was not a success. This will also be added in for Milestone 3. Hopefully you can review m3 too,  because we've added some very nice and usable and visual interactions for voting. 

Let me know if you have any other queries, if not we can wrap this up and I will submit m3 in the coming days.

**Review by 0xCaso — APPROVED** [review]
Thanks a lot for the answers @decentration!

I managed to test the two functions, for some reason `leaveSupersig` didn't work yesterday but I think (i've read now the error) it was because the only remaining member was leaving it (in that case, one needs to use `deleteSupersig`). Maybe you could add a note in the docs for the next milestone to clarify this, but it's pretty logic!

For the other adjustments thanks! And yes, I can definitely evaluate also the next milestone, so I can see the progress :)

**Review by Noc2 — APPROVED** [review]

**Comment by decentration** [comment]
Fab thanks @0xCaso, I will indeed update the supersig wiki with that detail. And have just changed the error message from `InvalidNumberOfMembers`, to `MustHaveAtLeastOneMemberToDelete`, which will be available on the next release, once we deal with some bug fixes brought on by `polkadot-v0.9.37`. All the best 👍

**Comment by decentration** [comment]
@0xCaso Oh, the company is registered in a no VAT jurisdiction, which is why it’s not on the invoice.

**Comment by 0xCaso** [comment]
> @0xCaso Oh, the company is registered in a no VAT jurisdiction, which is why it’s not on the invoice.

Yes sorry, I was meaning to put the VAT amount to 0 ;)

**Comment by decentration** [comment]
That is resubmitted now @0xCaso

**Comment by 0xCaso** [comment]
> That is resubmitted now @0xCaso

Perfect thanks, I forwarded it internally. The payment should take place within 14 days!

**Comment by decentration** [comment]
3rd time’s a charm @0xCaso

**Comment by 0xCaso** [comment]
I think there is still written "Milestone 3 - Supersig UI completion" instead of "Milestone 2 - Supersig UI completion" 😬

**Comment by decentration** [comment]
Oh my goodness! Sorry about that. Ok this one should be correct. Thanks for your patience.

**Comment by 0xCaso** [comment]
No worries and thanks! This time it should be perfect

**Comment by RouvenP** [comment]
hi @decentration we transferred the payment today.

**Comment by decentration** [comment]
Hey @RouvenP, received and thank you.

**Pull request merged**
