### PR TITLE
Dotly Milestone 1.md

### PR DESCRIPTION
**Pull request by justmert**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] This pull request is being made by the same account as the accepted application.
- [X] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [X] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1784

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @justmert I updated the PR to include the original application pull request. Someone will take a look shortly.

**Comment by keeganquigley** [comment]
Apologies for the delay @justmert we have a bit of a backlog and some folks are out on holiday for a couple days this week, but someone will look at it soon.

**Comment by dsm-w3f** [comment]
@justmert thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotly_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by tolgayayci** [comment]
Hey @dsm-w3f, did you have a chance to look at my responses?

**Comment by dsm-w3f** [comment]
@justmert thank you for the improvements and fixes. I think we still having problems in some parts of the application. Please see the details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotly_1_dsm-w3f.md). Let me know when I can continue this evaluation. The ideal situation is to fix and improve all points mentioned in the evaluation document before requesting a new evaluation round.

**Comment by dsm-w3f** [comment]
@justmert thank you for the milestone delivery. I'm still having one problem with the frontend of the application. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotly_1_dsm-w3f.md) for details. Let me know when I can check it again to finish this evaluation.

**Comment by dsm-w3f** [comment]
@justmert thank you for the improvements and fixes. The problem mentioned was fixed but now we have another one. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotly_1_dsm-w3f.md) for details. We are almost finishing this evaluation. Let me know when I can check it again.

**Comment by dsm-w3f** [comment]
@justmert thank you for the improvements and fixes. The milestone is approved. Please submit the invoice using the form in the message below. After that, the payment should take place within two weeks. Great job!

**Pull request merged**
