### PR TITLE
Universaldot.me Phase 2 Milestone 1

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/927

### CODE REVIEW

**Comment by shierve** [comment]
Hi @JosephKnecht-lab , I made an [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/125fb4fd1c39775fcd71d2752175a9f6547fc7bd/evaluations/universaldot.me_1_shierve.md) of your delivery.

I included some small errors I found. It would also be nice if there was a way to test the tensorflow model integration. Take a look and let me know what you think.

**Comment by alxs** [comment]
Hey @JosephKnecht-lab, thanks a lot for the delivery. A few things from my side:

- Could you license the IPFS design document under a permissive license too? A CC license would probably work best.
- Could you submit an amendment to modify the scope of milestone 2, since you say you will not integrate with IPFS through a pallet, but deliverable 1 describes a "Substrate pallet Integration with IPFS."
- I haven't looked at the Tensorflow integration in extensive detail yet, but I see you only provide the [models](https://github.com/UniversalDot/tensorflow) and this minimal [front-end integration](https://github.com/UniversalDot/front-end/pull/11/files). I'm not sure this corresponds to the [integration](https://github.com/UniversalDot/documents/blob/master/designs/architecture/Tensorflow.drawio.png) you said you intended to deliver when you applied. If it doesn't, please submit an amendment.
- Deliverable 0e., as described in your application, should be "a wiki document that explains what was developed and how users can interact with the functionality."
- Deliverable 3 also included a redesign of the DAO pallet.
- Could you please provide some details on the revamping of the Profile, Task and DAO pallets you carried out as part of milestone 1 and the functionality you added?

**Comment by JosephKnecht-lab** [comment]
Hi @alxs. I have updated the document based on your feedback and the feedback from @shierve. The rest of your comments are addressed below.

- New [IPFS Document](https://drive.google.com/file/d/11BNKzUyglGspm0Vy9ggfOp1iNAKQmpeq/view?usp=sharing ) licensed under CC. 

- Regarding the amendments to milestone 2, we are willing to amend the application. However, since things can change in the next 3 months, we will do the amendment at a later date but before submitting the evaluation for milestone 2. Hope this is fine with you? 

- We do have a tensorflow serving instance serving the model through docker as described in the image. The model is available and can be queried on this [endpoint](http://109.235.70.27:8501/v1/models/model). We have created an initial integration that allows us to send queries to the model from the react app. Is there anything specific that is missing from the [diagram](https://github.com/UniversalDot/documents/blob/master/designs/architecture/Tensorflow.drawio.png)?  

- In terms of the revamping of the functionality, we have added additional characteristics to the model as described in the initial proposal and shown in the [release notes](https://github.com/UniversalDot/universal-dot-node/releases/tag/v0.7.0). Also, for all pallets we have converted most of the Vec<u8>, to BoundedVec<, Limit> implementation. We have expanded the unit tests and benchmarks as well. For each pallet improvements, you can read more information below.
**Profile** : Adding ability to remove a profile. Also adding additional metadata such as `availability_hours`, `additional_information`, `tasks_completed`.
**Task**: Upgraded the [state machine](https://github.com/UniversalDot/documents/blob/master/designs/architecture/ProcessDesign.drawio.png) for tasks. Tasks  can `expire` with OnInitiilze deadline check, and these tasks can be later `revived`. Tasks can also be `updated`, `deleted` and `rejected` with feedback from the initiator. We have refactored the escrow functionality to use [Reservable](https://github.com/UniversalDot/universal-dot-node/issues/59) currency. 
**Dao**: We can now transfer ownership of a Dao to a different account by using a new [did](https://github.com/UniversalDot/universal-dot-node/blob/universal-develop/pallets/did/src/lib.rs) pallet. We can create new org_id per organization based on the hash. We have synched the [Vision to organization](https://github.com/UniversalDot/universal-dot-node/issues/68) and also created a possibility for a task to be linked directly to an organization rather than be added to the organization later.
NOTE: There is more functionality that we have implemented but not referenced above. For a complete list, you can check the completed issue [page](https://github.com/UniversalDot/universal-dot-node/issues?q=is%3Aissue+is%3Aclosed). We have also added a new [grant](https://github.com/UniversalDot/universal-dot-node/tree/universal-develop/pallets/grant) pallet which initially wasn't planned in scope.

**Comment by takahser** [comment]
Hi @JosephKnecht-lab. After a thorough review of your delivery, I'm afraid we've decided to reject the milestone and terminate the grant agreement in accordance with our [Terms & Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md). Below is a list of reasons behind this decision.

Deliverables that don't meet the specification:

- Deliverable 4, the IPFS Design Document, does not describe the integration of Substrate with IPFS; instead, it describes using IPFS in your project.
- The rest of the work you describe for the DAO pallet ("We can create new org_id per organization based on the hash. We have synched the Vision to organization and also created a possibility for a task to be linked directly to an organization rather than be added to the organization later.") does not amount to a "complete redesign and implementation" as described in the application, especially for a $50k milestone.

Plagiarism:

- Pages 5-10 of the IPFS Design Document are copied 1:1 from the [IPFS Architecture Overview](https://github.com/ipfs/specs/blob/main/ARCHITECTURE.md#1-ipfs-and-the-merkle-dag). Even though you cite this document in your sources, copying 5 pages is still plagiarism.
- The new [did](https://github.com/UniversalDot/universal-dot-node/blob/universal-develop/pallets/did/src/lib.rs) pallet you cite in your previous comment as work that you carried out is minimally adapted from Nuchain's [did](https://github.com/nusantarachain/nuchain/blob/develop/frame/did/src/lib.rs) pallet with the license stripped out.

Note that for the first set of issues, we'd normally have asked you to submit an amendment. However, we take plagiarism and the right of other teams to their intellectual property very seriously, hence as described in our [guidelines](https://github.com/w3f/Grants-Program#guidelines) submitting others' work without attribution leads to immediate termination.

Nevertheless, we would like to thank you for your interest in the grants program and for your contributions to the ecosystem. You're also welcome to apply for further grants in the future, though please note that the committee will likely take the current termination into account.

**Comment by JosephKnecht-lab** [comment]
Hi @takahser,

Thank you for the evaluation. 

Regarding your comments on plagiarism: 

- The IPFS Architecture Overview was meant to give a general overview to a broad audience that is not familiar with IPFS. I have cited the source of the information in the references which is typical for academic settings. There was no intent for plagiarism.
- In the comment above, I stated that we are _using_ a did pallet, not that we have implemented that pallet ourselves. In the lib.rs file, we have kept the reference comment as created by NuChain. One of our developers has removed the initial license, and I have reverted it the latest [commit](https://github.com/UniversalDot/universal-dot-node/commit/501285383ed5c9f24b7064f9a54148a7a96d0b66). 

Although we have put months of work into this delivery, we have no other recourse but to accept your verdict. 

Thank you for your evaluation again, and we hope you accept the [grant pallet](https://github.com/UniversalDot/universal-dot-node/tree/universal-develop/pallets/grant) as a token of our gratitude for the work you are doing.

**Pull request closed without merging**
