### PR TITLE
Rubeus Keeper stage 2 MS1 delivery

### PR DESCRIPTION
**Pull request by dsrdrk11a**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the DOT(Statemint) payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1361

### CODE REVIEW

**Comment by keeganquigley** [comment]
@dsrdrk11a Hi again, thanks for the submission. Everything is looking good. The tests are passing, smart contracts compile and deploy correctly, and the extension works nicely!

The only thing I'm confused about is that in your "notes tab" tutorial video, you are able to hide your password so that it doesn't display the plain text. In the client version I am using, I don't seem to have that ability. Are you working off of a different branch in the video? Or am I missing something? Thanks!

**Comment by keeganquigley** [comment]
UPDATE: I spoke too soon, I figured out how to do it. Your milestone has been accepted, and here you can find my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rubeus_keeper_st2_1_keeganquigley.md). Thanks and looking forward to the next milestone.

**Comment by fededubbi** [comment]
Good morning,

I noticed that your invoice reports a wrong invoice date (02.02.2022), i assume this should be 02.02.2023.
Could you please update it and resend?

Many thanks,
Federica Dubbini

**Comment by dsrdrk11a** [comment]
Thank you, @keeganquigley for your review! Heading to the 2nd MS!

@fededubbi thanks for correction. I've just uploaded a new invoice in the same form

**Comment by fededubbi** [comment]
Hi @dsrdrk11a, 
sorry i noticed that another previous invoice has the same invoice number of this one.
Can you please change it and resend?

Many thanks,
Federica Dubbini

**Comment by dsrdrk11a** [comment]
@fededubbi done! Sorry for that )

**Pull request merged**
