### PR TITLE
Rv kmir milestone 2

### PR DESCRIPTION
**Pull request by ehildenb**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1422 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by ehildenb** [comment]
One caveat, is the invoice requested payment in USDC.

**Comment by dsm-w3f** [comment]
@ehildenb thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by yanliu18** [comment]
@dsm-w3f thanks for the evaluation comments, there are three issues to be addressed:
1. conflicts in lock file: [fixed](https://github.com/runtimeverification/mir-semantics/commit/230a24738bc9642293126a66d8d497f8c241209e). Sorry for that.
2. explanation of failed tests: the 84 failed cases contains syntax that are tricky to implement in our underlying verification framework. Considering such syntax are rarely appearing in normal rust programs and will not prevent us for implementing the operational semantics in the next step, we put them aside for future work. 
3. `kmir parse` faile to run due to `kbuild directory does not exits problem: 
    - In a docker container, I could reproduce the error. (We didn't test the commands in a docker container before). it seems to have problems, an [issue](https://github.com/runtimeverification/pyk/issues/456) has been submitted to investigate this problem.
    - Without docker, it should be working though there could some issues. Would you share with me your local k version? And would you try `make build` before `poetry install`? 

Thank you.

**Comment by dsm-w3f** [comment]
@ehildenb and @yanliu18 thank you for the answers and fixes. I still have problems running the commands. I added the requested information to the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md) and asked some others there. Would be nice to provide a demo video to show how to properly run the system or to fix the docker issue. Let me know when I can continue this evaluation.

**Comment by keeganquigley** [comment]
Pinging @yanliu18 @ehildenb

**Comment by yanliu18** [comment]
@keeganquigley Sorry for the delayed reply that I was on sick leave. I am now back on the issue.

@dsm-w3f We will aim to fix the issue. I can certainly make a video demo the execution without a dock container. Do you neeed it? 

Thank you.

**Comment by dsm-w3f** [comment]
@yanliu18 Yes, I need this demo to continue the evaluation since I'm having problems to run the system. I was not able to run kmir parse with or without docker. Please refer to the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md) for details.

**Comment by yanliu18** [comment]
> @yanliu18 Yes, I need this demo to continue the evaluation since I'm having problems to run the system. I was not able to run kmir parse with or without docker. Please refer to the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md) for details.

@dsm-w3f the `kbuild not found` issue should be fixed with the latest commit. Shall we try again with the docker environment.
I'll summarise the steps here (A more detailed version can be found with the provided links to our instruction documents):

Clone the repo with submodules and switch to the branch for evaluation.
```
git clone --recurse-submodules git@github.com:runtimeverification/mir-semantics.git
cd mir-semantics
git checkout milestone2-deliverable
```
Build and start the docker
```
sudo docker build . --build-arg K_COMMIT=$(cat ./deps/k_release) --tag mir-semantics:$(cat ./deps/k_release)
sudo docker run --name mir-semantics --rm -it -u user --workdir /home/user mir-semantics:$(cat ./deps/k_release)
cd kmir
```
run tests on parsing function
```
make test-integration
```
> There are 84 tests failed. Please refer to previous comments for explanation.

Parse MIR files using `kmir parse` executable, an exemplar command is provided.
```
poetry shell # to make kmir and kbuild availible without having to type "poetry run"
kmir --help   # to list available commands
kmir parse --definition-dir $(kbuild which llvm) src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir 
kmir parse --definition-dir $(kbuild which llvm) src/tests/integration/test-data/handwritten-mir/execution/assert-true.mir --output pretty           # to show the parsing result in a neat form
```
Please let me know if there is further problems (I will provide a demo video if this fix is not working). Thank you!

**Comment by dsm-w3f** [comment]
@yanliu18 thank you for the answer. I ran again and now it worked. Just a small adjustment in the documentation, I needed to run the `make build` command to work. See the details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv-kmir_2_dsm-w3f.md). The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by yanliu18** [comment]
@dsm-w3f many thanks. I'll update the documentation to include the `make build` step.

**Comment by RouvenP** [comment]
hi @ehildenb @yanliu18 we transferred the payment today.

**Comment by yanliu18** [comment]
> hi @ehildenb @yanliu18 we transferred the payment today.

Noted with thanks.

**Pull request merged**
