### PR TITLE
subdao-network_milestone_1

### PR DESCRIPTION
**Pull request by WannaM**
* subdao-network_milestone_1

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by WannaM** [comment]
Hi, there is a failure in PR checks, but no clues about what is the root cause.
Here are the logs
```
1s
1
Run ./.github/actions/validate_pr
2
  with:
3
    targetRepoOwner: w3f
4
    targetRepo: Open-Grants-Program
5
    prLink: https://github.com/w3f/Open-Grants-Program/pull/90
6
    author: WannaM
7
Author is WannaM
8
Error: Cannot read property '0' of null
```

**Comment by mmagician** [comment]
I'm putting this temporarily on hold due to parallel participation in the [hackathon](https://github.com/ParityAsia/hackathon-2021-spring/). The hackathon organisers will contact you regarding further steps.

**Comment by WannaM** [comment]
@semuelle  Seems the checks have problems.  The check of author fails all the time. I donot know what's the problem. Could you help?

```
Run ./.github/actions/validate_pr
2
  with:
3
    targetRepoOwner: w3f
4
    targetRepo: Open-Grants-Program
5
    prLink: https://github.com/w3f/Open-Grants-Program/pull/90
6
    author: WannaM
7
Author is WannaM
8
Error: Cannot read property '0' of null
```

**Comment by semuelle** [comment]
Hi @WannaM, this check is just for our internal bookkeeping, and the issue is with the code, not your delivery. Thanks for checking, though.

**Comment by semuelle** [comment]
Hi @WannaM, I have completed the evaluation of your milestone for now. You can find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/ed18b6127883d82a355c57e02eadb02274ca04b0/evaluations/subdao_1_semuelle.md). 

The article and tutorial are basically the same, so it would be great if you could replace one of them. I'd suggest replacing the tutorial with a technical walkthrough. Also, I wasn't able to deploy the contracts. Could you test your workflow with the latest polkadotjs UI?

**Comment by WannaM** [comment]
> Hi @WannaM, the node and contracts repositories are missing licenses. Can you fix that, please?

License files added. Thank you!

**Comment by WannaM** [comment]
> Hi @WannaM, I have completed the evaluation of your milestone for now. You can find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/ed18b6127883d82a355c57e02eadb02274ca04b0/evaluations/subdao_1_semuelle.md).
> 
> The article and tutorial are basically the same, so it would be great if you could replace one of them. I'd suggest replacing the tutorial with a technical walkthrough. Also, I wasn't able to deploy the contracts. Could you test your workflow with the latest polkadotjs UI?

Thanks for the advice. Let us replace a new doc for the tutorial.  

Regarding deploy contracts, which version of `polkadot js apps`  are you using?  The substrate node is only compatible with the `pokadot js ui` provided in docker image, due to compatible problem.

**Comment by semuelle** [comment]
> License files added. Thank you!

Not to be pedantic, but someone deleted the license file from the contracts repo again.

**Comment by semuelle** [comment]
I tried the latest version of polkadotjs as well as the version depicted in your [tutorial](https://github.com/SubDAO-Network/docs/tree/main/tutorial).

> The substrate node is only compatible with the `pokadot js ui` provided in docker image, due to compatible problem.

Can you explain what those compatibility problems are and what you did you solve them?

**Comment by WannaM** [comment]
> > License files added. Thank you!
> 
> Not to be pedantic, but someone deleted the license file from the contracts repo again.

I'm so sorry for this. Some one of our team deleted the license file by mistake. Re-added now.

**Comment by WannaM** [comment]
> I tried the latest version of polkadotjs as well as the version depicted in your [tutorial](https://github.com/SubDAO-Network/docs/tree/main/tutorial).
> 
> > The substrate node is only compatible with the `pokadot js ui` provided in docker image, due to compatible problem.
> 
> Can you explain what those compatibility problems are and what you did you solve them?

We just stay with the old version due to some changes in `polkadot js api`. 

Could you share the error info when you deploy contracts using the version depicted in  [tutorial](https://github.com/SubDAO-Network/docs/tree/main/tutorial) ?

**Comment by semuelle** [comment]
> Could you share the error info when you deploy contracts using the version depicted in [tutorial](https://github.com/SubDAO-Network/docs/tree/main/tutorial) ?

As mentioned [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/ed18b6127883d82a355c57e02eadb02274ca04b0/evaluations/subdao_1_semuelle.md#general-notes).

**Comment by semuelle** [comment]
I am unable to build the polkadotjs apps in your docker container. Perhaps you can provide a tutorial on how to set it up? Or better yet, fix the incompatibilities to the current apps version?

**Comment by WannaM** [comment]
> I am unable to build the polkadotjs apps in your docker container. Perhaps you can provide a tutorial on how to set it up? Or better yet, fix the incompatibilities to the current apps version?

The `docs` is updated. Could you try it?

**Comment by semuelle** [comment]
Hi @WannaM. I was eventually able to deploy all contracts, run the frontend and create a DAO. However, there are several critical issues I would like to ask you to address. 

1. Your `docker-compose.yml` serves the `subdao-frontend` from a folder that doesn't exist on a port that is not documented anywhere (or incorrectly documented) . 

```
ports:
      - "9856:9856"
    command: bash -c "cd / && serve -p 9856 subdao_frontend"
``` 

2. The frontend falls back to a generic error page when a transaction fails. It also doesn't catch any illegal inputs, such as when no template is chosen.

3. Most of your code, most notably the contracts, have little to no inline documentation. 

4. The websocket address and main contract address are hardcoded in your frontend. Since I wasn't able to use the dockerized frontend, I had to find and replace them to deploy a DAO.

5. The frontend is not very clear in its description of inputs. Does the list of tokens at step 4 refer to who receives the tokens? And the second input how many they receive?

**Comment by WannaM** [comment]
> Hi @WannaM. I was eventually able to deploy all contracts, run the frontend and create a DAO. However, there are several critical issues I would like to ask you to address.
> 
> 1. Your `docker-compose.yml` serves the `subdao-frontend` from a folder that doesn't exist on a port that is not documented anywhere (or incorrectly documented) .
> 
> ```
> ports:
>       - "9856:9856"
>     command: bash -c "cd / && serve -p 9856 subdao_frontend"
> ```
> 

This part should be removed.  The file is updated.  

> 1. The frontend falls back to a generic error page when a transaction fails. It also doesn't catch any illegal inputs, such as when no template is chosen.

Already fixed in the new version. Please update the code.  

> 2. Most of your code, most notably the contracts, have little to no inline documentation.

That's true, within this milestone we focus on functionalities, documentation will be added when everything runs smooth.  

> 3. The websocket address and main contract address are hardcoded in your frontend. Since I wasn't able to use the dockerized frontend, I had to find and replace them to deploy a DAO.

The related doc is updated.   

> 4. The frontend is not very clear in its description of inputs. Does the list of tokens at step 4 refer to who receives the tokens? And the second input how many they receive?

We add a new doc about how to use it.  The new UI/UX design of subdao frontend is on the way. It will be released in a later version.  

@semuelle  Thank you for your great effort! You did great work to help us improve the whole project. We reviewed all the documents with the whole team. Hope everything goes fine when you try to use SubDAO. If you meet any issue of using SubDAO, we can provide a video to show how to use it rather than this [doc.](https://github.com/SubDAO-Network/docs/tree/main/usage)

**Comment by semuelle** [comment]
Thanks for following up on my feedback, @WannaM. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/56a2d46a5091905548d8d01a42313ba04e4cd49a/evaluations/subdao_1_semuelle.md) and your milestone is hereby accepted. :tada: 

Overall, as you could see in my notes, I quite liked the functionality and the frontend, and most of the issues I had were fixed. [Some](https://github.com/SubDAO-Network/subDAO-contracts/blame/main/vault/lib.rs#L318-L357) of your code could use some cleaning, but nothing a linter couldn't fix. It is not explicitly mentioned in your application, but for the sake of future users and the community, I would like to ask you to add some inline documentation, at least on the smart contracts in the near future. 

I will forward your invoice for processing.

**Comment by WannaM** [comment]
> Thanks for following up on my feedback, @WannaM. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/56a2d46a5091905548d8d01a42313ba04e4cd49a/evaluations/subdao_1_semuelle.md) and your milestone is hereby accepted. 🎉
> 
> Overall, as you could see in my notes, I quite liked the functionality and the frontend, and most of the issues I had were fixed. [Some](https://github.com/SubDAO-Network/subDAO-contracts/blame/main/vault/lib.rs#L318-L357) of your code could use some cleaning, but nothing a linter couldn't fix. It is not explicitly mentioned in your application, but for the sake of future users and the community, I would like to ask you to add some inline documentation, at least on the smart contracts in the near future.
> 
> I will forward your invoice for processing.

Thank you very much!!

**Comment by RouvenP** [comment]
hi @WannaM we sent a test transaction of 0.001 BTC. Could you confirm if received?

**Comment by RouvenP** [comment]
hi @WannaM did you receive the test transaction?

**Pull request merged**
