### PR TITLE
IPFS utilities milestone 2

### PR DESCRIPTION
**Pull request by dobschal**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1187

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @dobschal. We will look into it as soon as possible.

**Comment by randombishop** [comment]
Hi @dobschal 
Thanks for this delivery. 
Starting evaluation today and will get back to you soon with feedback.

**Comment by randombishop** [comment]
Hey @dobschal!

In previous delivery's [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ipfs_utilities_1_randombishop.md), I had noted that:
 
```The docs don't show how to run the tests, I had to manually guess and go into the features folders and run cargo test```


I still can't find a testing guide in current version, can you please provide one?

**Comment by dobschal** [comment]
Hey @randombishop ,
thanks for your message. I added a hint on how to run the tests to the documentation:
https://github.com/TDSoftware/substrate-ipfs/blob/milestone-2/docs/IPFS.md

The documentation is also linked in the main readme file.

To execute the unit tests, just run the following command:
```bash
cargo test --package pallet-tds-ipfs-core
```
and
```bash
cargo test --package pallet-tds-ipfs
```

Thanks!

**Comment by randombishop** [comment]
Also @dobschal where can I find and test the deliverable `2. Web3 Client Extension`?

**Comment by dobschal** [comment]
Hey @randombishop ,

I adjusted the delivery links.

The client example can be found here:
https://github.com/TDSoftware/substrate-ipfs-example-ui

**Comment by randombishop** [comment]
Hey @dobschal !
Happy to accept your delivery.
My evaluation can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ipfs_utilities_2_randombishop.md).
Also forwarded your invoice, please allow up to 2 weeks for processing.
Thank you!

**Comment by RouvenP** [comment]
hi @dobschal we transferred the payment today.

**Pull request merged**
