### PR TITLE
Submit Polket-ToEarnFun Milestone 1  Delivery

### PR DESCRIPTION
**Pull request by zhiquan911**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1177

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @zhiquan911! Thanks a lot for the delivery. I'm starting the evaluation, and I'll reach out if I need your help.

**Comment by 0xCaso** [comment]
I'm following the gitbook guide you've provided to run the mobile app.

When I'm trying to import the mnemonic passphrase, I press "Continue" but the app runs into this error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'api' has not been initialized.
#0      WalletSDK.api (package:polkawallet_sdk/polkawallet_sdk.dart)
#1      _MnemonicRestoreWalletState._validateMnemonic (package:toearnfun_flutter_app/pages/wallet/import/mnemonic.dart:220:41)
#2      _MnemonicRestoreWalletState.buttonView.<anonymous closure> (package:toearnfun_flutter_app/pages/wallet/import/mnemonic.dart:163:35)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#16     _invoke1 (dart:ui/hooks.dart:167:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```
Also, is there a way to make the app communicate with the local node (of the chain) I'm running?

**Review by 0xCaso — COMMENTED** [review]
I'm following the gitbook guide you've provided to run the mobile app:
- I've run the app with `flutter run lib/main_dev.dart`;
- I've selected macOS (desktop) as device (Chrome (web) doesn't work).

When I'm trying to import the mnemonic passphrase, I press "Continue" but the app runs into this error:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'api' has not been initialized.
#0      WalletSDK.api (package:polkawallet_sdk/polkawallet_sdk.dart)
#1      _MnemonicRestoreWalletState._validateMnemonic (package:toearnfun_flutter_app/pages/wallet/import/mnemonic.dart:220:41)
#2      _MnemonicRestoreWalletState.buttonView.<anonymous closure> (package:toearnfun_flutter_app/pages/wallet/import/mnemonic.dart:163:35)
#3      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:276:7)
#8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:163:27)
#9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:464:20)
#10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#11     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#12     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#13     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#16     _invoke1 (dart:ui/hooks.dart:167:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```
Also, is there a way to make the app communicate with the local node (of the chain) I'm running?

**Comment by zhiquan911** [comment]
@0xCaso 
At Milestone 1, we currently only implement Android, so Chrome (web) is not yet supported.
You should be fine to use the `Android emulator` to run it.

In order to meet the requirements of running the app on the local node, I added some operation steps to the document. Please give it a try.

https://polketio.gitbook.io/toearnfun/guides/how-to-run-toearnfun-app#run-app-on-local-node-option

**Comment by 0xCaso** [comment]
Thanks a lot @zhiquan911, everything is clear. By the way, when I run the app in the emulator, I get the following error:
```
I/flutter ( 5572): CONSOLE MESSAGE: 2023-01-05 16:20:20          API-WS: disconnected from ws://localhost:9944: 1006:: Abnormal Closure
```
This is the endpoint I'm using: `'endpoint': 'ws://localhost:9944'`.
Also, I can connect to the chain from PolkadotJS App so don't know why the emulator can't.

**Comment by zhiquan911** [comment]
@0xCaso 
Use `'endpoint': 'ws://10.0.2.2:9944'`, you can connect to the local node.

image

The address 127.0.0.1 on your development machine corresponds to the emulator's loopback interface. To access services running on your development machine loopback interface, use the special address 10.0.2.2 instead.

https://developer.android.com/studio/run/emulator-networking

**Review by 0xCaso — COMMENTED** [review]
Thanks again @zhiquan911, my fault, I didn't understand I had to leave the address provided in the gitbook. Maybe it would be great to add a note there saying that the address `ws://10.0.2.2:9944` is correct (and not to put `localhost`).

By the way, I tested all the things of the guide, so I'll publish my evaluation soon :)

**Comment by zhiquan911** [comment]
Thank you for supporting my project.

**Comment by 0xCaso** [comment]
One last thing, I can't start the node using the Dockerfile you provided. This is the error I got:
```
error: failed to run custom build command for `polket-runtime v0.1.0 (/var/www/polket/runtime/testnet)`

Caused by:
  process didn't exit successfully: `/var/www/polket/target/release/build/polket-runtime-47a33f2217b5ed30/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!
```
It's weird because there is the installation command for the toolchain in the Dockerfile;
I also tried to change
```
RUN rustup toolchain install nightly-2022-08-30
RUN rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-30
RUN cargo build --locked --release
```
to
```
RUN rustup target install wasm32-unknown-unknown --toolchain nightly-2022-08-30
RUN rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-30
RUN cargo build
```
but didn't solve the issue.

**Comment by zhiquan911** [comment]
@0xCaso 
Thanks for helping me discover this issue.
The strange thing is that I have been using the `github action` to publish the docker image, and there is no error.

https://github.com/polketio/polket-node/actions/workflows/build-publish-image.yml

**Comment by 0xCaso** [comment]
Yea I see... this is actually weird. So do you reproduce the error locally?

**Comment by zhiquan911** [comment]
I tried running the build dockerfile on my local machine and it was successful.
I'm not very professional about docker either, I doubt if you have an old version of `paritytech/ci-linux:production` locally, it doesn't have a `.local` directory?
And I am using a new version now, the new version already has a `.local` directory?

This my dockerfile building logs.

```log
chance@chanceMac polket-node % docker build -t polketnode:abc .
[+] Building 1337.4s (18/18) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                             0.1s
 => => transferring dockerfile: 1.71kB                                                                                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                0.0s
 => => transferring context: 34B                                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/paritytech/ci-linux:production                                                                                                                                                        3.9s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                                                  3.9s
 => [auth] paritytech/ci-linux:pull token for registry-1.docker.io                                                                                                                                                               0.0s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                                                                                                                                    0.0s
 => [builder 1/6] FROM docker.io/paritytech/ci-linux:production@sha256:05ece6bd39131e35868babf911d19b7b570134d47b0455076ab162b233ed4157                                                                                        226.5s
 => => resolve docker.io/paritytech/ci-linux:production@sha256:05ece6bd39131e35868babf911d19b7b570134d47b0455076ab162b233ed4157                                                                                                  0.0s
 => => sha256:ed5fa3a1537de916b8df9cca1ab672e646efe5ad1f6c1ba64e175e0c007a7e95 559.57MB / 559.57MB                                                                                                                             189.0s
 => => sha256:05ece6bd39131e35868babf911d19b7b570134d47b0455076ab162b233ed4157 1.17kB / 1.17kB                                                                                                                                   0.0s
 => => sha256:d58348cfa6055a016f7633cb8afe01c7148a54a596d38950343a08e3b160f30c 9.63kB / 9.63kB                                                                                                                                   0.0s
 => => sha256:6eab20599fab240a56b06125a77b4921dd39662d3b9f9008da7306531772a1d0 27.14MB / 27.14MB                                                                                                                                10.3s
 => => sha256:d6128b48bf3655e0cfe6ff23648b7bbaf53bf3e16117f5028890f4d03ffdd3f3 388.97MB / 388.97MB                                                                                                                             116.5s
 => => extracting sha256:6eab20599fab240a56b06125a77b4921dd39662d3b9f9008da7306531772a1d0                                                                                                                                        1.5s
 => => sha256:b0e01bc921d096ac47bd8eed348238be90605997505e970629ac89b082ef21c5 1.02MB / 1.02MB                                                                                                                                  16.2s
 => => extracting sha256:ed5fa3a1537de916b8df9cca1ab672e646efe5ad1f6c1ba64e175e0c007a7e95                                                                                                                                       22.2s
 => => extracting sha256:d6128b48bf3655e0cfe6ff23648b7bbaf53bf3e16117f5028890f4d03ffdd3f3                                                                                                                                       14.2s
 => => extracting sha256:b0e01bc921d096ac47bd8eed348238be90605997505e970629ac89b082ef21c5                                                                                                                                        0.1s
 => [stage-1 1/4] FROM docker.io/library/ubuntu:20.04@sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb                                                                                                   16.5s
 => => resolve docker.io/library/ubuntu:20.04@sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb                                                                                                            0.0s
 => => sha256:d5447fc01ae62c20beffbfa50bc51b2797f9d7ebae031b8c2245b5be8ff1c75b 1.46kB / 1.46kB                                                                                                                                   0.0s
 => => sha256:846c0b181fff0c667d9444f8378e8fcfa13116da8d308bf21673f7e4bea8d580 28.58MB / 28.58MB                                                                                                                                15.1s
 => => sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb 1.42kB / 1.42kB                                                                                                                                   0.0s
 => => sha256:8eb87f3d6c9f2feee114ff0eff93ea9dfd20b294df0a0353bd6a4abf403336fe 529B / 529B                                                                                                                                       0.0s
 => => extracting sha256:846c0b181fff0c667d9444f8378e8fcfa13116da8d308bf21673f7e4bea8d580                                                                                                                                        1.2s
 => [internal] load build context                                                                                                                                                                                                0.3s
 => => transferring context: 3.85MB                                                                                                                                                                                              0.2s
 => [builder 2/6] WORKDIR /polket-node                                                                                                                                                                                           1.3s
 => [builder 3/6] COPY . .                                                                                                                                                                                                       0.3s
 => [builder 4/6] RUN rustup toolchain install nightly-2022-08-30                                                                                                                                                               43.6s
 => [builder 5/6] RUN rustup target add wasm32-unknown-unknown --toolchain nightly-2022-08-30                                                                                                                                    7.6s
 => [builder 6/6] RUN cargo build --locked --release                                                                                                                                                                          1051.9s
 => [stage-1 2/4] COPY --from=builder /polket-node/target/release/polket-node /usr/local/bin                                                                                                                                     0.3s
 => [stage-1 3/4] RUN useradd -m -u 1000 -U -s /bin/sh -d /node-dev node-dev &&     mkdir -p /chain-data /node-dev/.local/share &&     chown -R node-dev:node-dev /chain-data &&     ln -s /chain-data /node-dev/.local/share/p  0.3s
 => [stage-1 4/4] COPY ./specs/testnet.json /specs                                                                                                                                                                               0.0s
 => exporting to image                                                                                                                                                                                                           0.3s
 => => exporting layers                                                                                                                                                                                                          0.3s
 => => writing image sha256:7c161ba3826fe1c0c08448f895716c33e199e9d13722b11d5c21136e0f38caef                                                                                                                                     0.0s
 => => naming to docker.io/library/polketnode:abc                                                                                                                                                                                0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
chance@chanceMac polket-node % docker images ls
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
chance@chanceMac polket-node % docker image ls
REPOSITORY             TAG       IMAGE ID       CREATED        SIZE
polketnode             abc       7c161ba3826f   14 hours ago   150MB

```

**Comment by zhiquan911** [comment]
I will also add lines of code to the dockerfile to ensure that everyone can run successfully.
```docker
RUN mkdir .local
```

**Comment by 0xCaso** [comment]
Thanks for the changing. I tried to delete my `.local` dir to re-try the build and it still fails (can't find the dir), so apparently including it in the Dockerfile it's useless.

I guess it's a misconfiguration problem on my end, cause the build works on your end and on GitHub actions; also it shouldn't be a big problem as I managed to run the application without the docker (as you basically just have to start a local node).

I'm publishing the evaluation soon!

**Review by 0xCaso — COMMENTED** [review]
Thanks for the changing. I tried to delete my `.local` dir to re-try the build and it still fails (can't find the dir), so apparently including it in the Dockerfile it's useless.

I guess it's a misconfiguration problem on my end, cause the build works on your end and on GitHub actions; also it shouldn't be a big problem as I managed to run the application without the docker (as you basically just have to start a local node).

I'm publishing the evaluation soon!

**Review by 0xCaso — APPROVED** [review]
We approved your delivery @zhiquan911, thanks a lot for the cooperation! You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polket_toearnfun_1_0xCaso.md), I left some notes you can read.

**Comment by 0xCaso** [comment]
@zhiquan911 could you please resend the invoice with:
- our company info
- VAT amount: 0

Also recently we changed our guidelines, and I would ask you if it's possible to change USDT on Ethereum as payment method to another option choosable from [here](https://github.com/w3f/Grants-Program#pencil-process) (so if you want to stay with Ethereum you should change it to USDC or DAI)

Let me know if there are any problems, thanks again.

**Comment by zhiquan911** [comment]
> 
I have refilled the invoice and added the information you need.
We prefer to accept USDC on Ethereum.

Finally, thanks for your evaluation suggestion. Your efficiency is really high, so that we can get the grants so quickly.

**Comment by 0xCaso** [comment]
Really glad to read that! And thanks a lot for the new submission.
I've forwarded the new invoice to the Finance team, so please allow up to 14 days for the payment.

**Comment by RouvenP** [comment]
hi @zhiquan911 we transferred the payment today.

**Pull request merged**
