### PR TITLE
Polkadot Contract Wizard M1

### PR DESCRIPTION
**Pull request by alongoni**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1413

### CODE REVIEW

**Comment by alongoni** [comment]
> Thanks for the delivery @alongoni . However, can you please look into these docker errors that I'm getting on `docker-compose --env-file .docker/dev.docker.env up`
> 
> ```
> polkasc_web | yarn run v1.22.19
> polkasc_web | $ next dev
> polkasc_web | ready - started server on 0.0.0.0:3000, url: http://localhost:3000
> polkasc_web | [Error: EACCES: permission denied, open '/home/app/.next/package.json'] {
> polkasc_web |   errno: -13,
> polkasc_web |   code: 'EACCES',
> polkasc_web |   syscall: 'open',
> polkasc_web |   path: '/home/app/.next/package.json'
> polkasc_web | }
> polkasc_web | error Command failed with exit code 1.
> polkasc_web | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> polkasc_web exited with code 1
> ```
> 
> Thanks :)

Hi @Ali-Usama, we detected an issue with docker. We'll be working on that fix so you can test our dapp. Thanks for your patience.

**Comment by Ali-Usama** [comment]
Thanks for the quick fixes @0xLucca . Great work for this milestone, and I've updated my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/823).

**Comment by semuelle** [comment]
Hi @alongoni & @0xLucca. I have reviewed your milestone and @Ali-Usama's evaluation. I made some small changes to the [evaluation sheet](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot_contract_wizard-1-ali-usama.md) but agree with the verdict and approve your delivery. Congratulations. 

I have forwarded your invoice for processing. Looking forward to your next milestone!

**Comment by 0xLucca** [comment]
Hi @semuelle 

Thank you for reviewing the milestone and sharing your feedback with us. We are thrilled to hear that you approve our delivery and appreciate the time you took to asses it.

We will continue to work diligently on the next deliverable and strive to exceed the expectations.

Furthermore, we acknowledge the recommendations provided by @Ali-Usama  and assure you that we will address them in the upcoming milestone to ensure the best possible outcome.

**Comment by alongoni** [comment]
> hi @0xLucca we transferred the payment today.

Thanks @RouvenP I'll communicate the team about it.

**Pull request merged**
