### PR TITLE
Qrucial DAO Evaluation

### PR DESCRIPTION
**Pull request by Ali-Usama**
# External Evaluation

The delivery is as per the application and all the features mentioned are working fine. However, a detailed evaluation and some suggestions are attached to the evaluation file.

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/989

### CODE REVIEW

**Review by semuelle — APPROVED** [review]
Thanks for the evaluation, @Ali-Usama. I agree, nice work here.

Someone will be in touch regarding your reward soon.

**Comment by sixTheDave** [comment]
Thank you @semuelle and @Ali-Usama! We added the suggestions to our future plan list.

**Comment by RouvenP** [comment]
hi @Ali-Usama we transferred the payment

**Comment by sixTheDave** [comment]
> hi @Ali-Usama we transferred the payment

We received it with Crypto CTF OÜ, thank you everyone.

**Pull request merged**
