### PR TITLE
Melodot milestone 4

### PR DESCRIPTION
**Pull request by DarkingLee**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1804

### CODE REVIEW

**Comment by semuelle** [comment]
Hey @DarkingLee. Thanks for the delivery. I am going through the deliverables and everything's going very smoothly so far. However, I can't run the e2e tests as there is no `./target/release/e2e` (see `Makefile`). Did I miss some step?

**Comment by DarkingLee** [comment]
hi, @semuelle , I missed a build command, you need to first run `make build-light` , I have updated the test documentation.

**Comment by semuelle** [comment]
Hey @DarkingLee. I'm afraid that didn't to the trick:

```sh
 ~/melodot/melodot | on w3f ...................................................................... at 13:57:39 
> make build-default
cargo build --release -p melodot-node -p melodot-runtime
   Compiling melodot-runtime v0.0.1 (/home/melodot/runtime)
   Compiling melo-das-rpc v0.0.1 (/home/melodot/crates/das-rpc)
   Compiling melodot-node v0.0.1 (/home/melodot/node)
    Finished release [optimized] target(s) in 3m 38s
 ~/melodot/melodot | on w3f ........................................................ took 3m 39s | at 14:01:19 
> make build-farmer
cargo build --release -p melodot-farmer-client
   Compiling melodot-runtime v0.0.1 (/home/melodot/runtime)
   Compiling melo-das-rpc v0.0.1 (/home/melodot/crates/das-rpc)
   Compiling meloxt v0.0.1 (/home/melodot/crates/meloxt)
   Compiling melodot-farmer-client v0.0.1 (/home/melodot/farmer)
    Finished release [optimized] target(s) in 2m 37s
 ~/melodot/melodot | on w3f ........................................................ took 2m 37s | at 14:04:08 
> make build-light
cargo build --release -p melodot-light-client -p melodot-light-client-e2e
   Compiling melodot-light-client-e2e v0.0.1 (/home/melodot/light/e2e)
   Compiling melodot-light-client v0.0.1 (/home/melodot/light)
    Finished release [optimized] target(s) in 34.68s
 ~/melodot/melodot | on w3f ........................................................... took 35s | at 14:04:47 
> make e2e
./target/release/e2e
make: ./target/release/e2e: No such file or directory
make: *** [Makefile:40: e2e] Error 127
```

**Comment by DarkingLee** [comment]
hi @semuelle I'm very sorry, I made a mistake. I had changed the node name but forgot about it. I should add it to the Action. You need to pull the repository again, no need to compile again.

**Comment by DarkingLee** [comment]
hi @semuelle , Sorry, my mistake, you should run `make build-meloxt` , which will build the e2e. I have updated the test documentation.

**Comment by semuelle** [comment]
Thanks for the quick responses, @DarkingLee. I am happy to report that everything worked and that your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/melodot_4_semuelle.md). 

Since this is your last milestone, I want to wish you best of luck with the project. All your deliverables were received very well, so I hope you will continue working on it and make it a success!

**Comment by DarkingLee** [comment]
hi @semuelle , Thank you very much, we will continue to move forward!

**Pull request merged**
