### PR TITLE
Faucet milestone delivery #1

### PR DESCRIPTION
**Pull request by karooolis**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1099.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @karooolis! Thanks for the deliveries, and sorry for the late response!

I'm beginning the evaluation: I managed to run the application locally, and the ```.env``` configuration process is a little challenging. Could you please provide a minimum of help to set everything up locally inside the docs? 

For example, I created a Twitter API app and GitHub API app, but just the GitHub authentication works, so I must missing something for the Twitter auth; also, I imagine the mnemonic must be of a non-empty wallet, could you explain please also how to fill inside the Substrate environment?

A guide for the ```.env``` configuration would simplify the evaluation (e2e tests have to be run), but most importantly the integration for other projects.

Lastly, I cannot authenticate inside the [demo](https://sybil-resistant-substrate-faucet.vercel.app/) you provided (either Twitter or GitHub).

I will start to write the evaluation document ASAP, so I can include these and more comments (you can already work on the mentioned things)

**Comment by karooolis** [comment]
Hi Matteo, thanks for the clear initial feedback! You may now try to login with GitHub, will address Twitter auth and other points the following day. Talking about the wallet, indeed it must be non-empty. However, I'm not sure about the generation + filling with test tokens part. I'd say it's up to the faucet owner to fill the wallet and obtain the tokens for the faucet, so that's outside of the project scope.

**Comment by 0xCaso** [comment]
Thanks for the answer!

For the local configuration, how did you set up your test faucet? Are you using Substrate? Because I could reproduce your setup in order to test everything, to make things easier.

**Comment by karooolis** [comment]
@0xCaso I improved the docs for [configuration variables](https://github.com/karooolis/sybil-resistant-substrate-faucet#configuration), and also [local node setup that can be used for testing](https://github.com/karooolis/sybil-resistant-substrate-faucet#local-blockchain-setup). Open to further feedback!

**Comment by 0xCaso** [comment]
Hi @karooolis! I created the evaluation document, you can see it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/28fbc243885ef6d74f439299d1464677768a9f89/evaluations/faucet_1_0xCaso.md) :)
As you can see, I requested some little changes, but overall your submission is almost perfect.

**Comment by dsm-w3f** [comment]
@karooolis thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Faucet_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by 0xCaso** [comment]
Hi @dsm-w3f, should I delete my PR?

**Comment by Noc2** [comment]
> here

Thanks for your external evaluation. Please create PR to merge your evaluation. It’s actually better to have multiple evaluations of the same delivery.

**Comment by 0xCaso** [comment]
> Thanks for your external evaluation. Please create PR to merge your evaluation. It’s actually better to have multiple evaluations of the same delivery.

Thank you David, that makes sense! It's already opened: https://github.com/w3f/Grant-Milestone-Delivery/pull/585

**Comment by karooolis** [comment]
Hi @dsm-w3f and thanks for the detailed feedback! I have made the changes, specifically:

- Provided a fully configured `.env.sample` file that works out-of-the-box.
- Improved Twitter setup description, and added link to official Twitter docs on how to obtain Twitter OAuth1.0 credentials.
- Added warning that all env variables are mandatory to run the system.
- Added JSDocs to all functions & classes.
- Added comprehensive test suite.
- Now take into consideration if wallet address has been used for claiming tokens.
- Now also use user's email to check if user has already claimed funds.
- Fixed ESLint errors & added pre-commit hook for code style, formatting and type checks.
- Fixed GitHub authentication refresh issue.
- Improved documentation to include `npm` instructions.
- Locked installation to only be available with compatible `node` and `npm` versions.

**Comment by 0xCaso** [comment]
Hi @karooolis, thank you for the changes! I've updated my evaluation document [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/fc9e414386f38623b8d9b53ea5fa2ea3149ac223/evaluations/faucet_1_0xCaso.md).

**Comment by karooolis** [comment]
Thanks @0xCaso and @dsm-w3f for feedback. The problem was related to authentication problem while doing E2E testing, got it fixed!

**Comment by dsm-w3f** [comment]
@karooolis The e2e test is still failing for me. I tried to debug and the JWT generated for authentication is invalid. Maybe the fields from the fixture and JWTPayload type are not matching. The JWT generated for me is in the code block below, you can inspect it using https://jwt.io/.  Let me know if I need something to bypass this problem since it seems to be working for you and Mateo. 
```
eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..t0TiOnbb5tNgOYJ9.no79Fa2PdSBjzks9dN8kO_IO8sgtzbLjQs_W7TjpxX-A4xHY_HOxrAxJkQ2voZBZVxEiJ-Ly6qkD_RgKuxyQuobgQpLEMw-vER4lz6G6VwNGRsJ7FIEwUxstx-Ht_8Fgp_XdUawP-n3wNBSFTDtVbw-uehUXQCGAnAwbPljLD7A3leo6l0gWEy-VAYDQSeIUsmaWR684Dd2mM0MMzmVjsAGHsw7ErAea_5szkYfSnNHOaK__8QjHo8CBIx7vqkh4_k4.Ibyu4oSbpyM8BSOcvoDQjQ
```

**Comment by karooolis** [comment]
@dsm-w3f Sincere apologies, getting around auth looks to be slightly capricious. Turns out, the cookie expired on October 12th, my oversight. I set the expiration date to 2140, now all seems to look good 🤞

**Comment by dsm-w3f** [comment]
@karooolis thank you for the changes. The tests are now passing and the evaluation is approved. Thank you @0xCaso for the external evaluation in this delivery. I'll handle the internal procedures to pay you both.

**Review by Noc2 — APPROVED** [review]

**Comment by dsm-w3f** [comment]
@karooolis the Ethereum addresses from the contract and invoice are different. For safety reasons, they should always match. You will need to update the contract or the invoice.

**Comment by karooolis** [comment]
@dsm-w3f Got it, just resubmitted the invoice 👌

**Comment by dsm-w3f** [comment]
@karooolis your invoice was forwarded internally and the payment should take place within two weeks (could happen before). @0xCaso your payment information also was forwarded and should take place with the same deadline (also could happen before that). Thank you guys, great work!

**Pull request merged**
