### PR TITLE
Signac Grant milestone delivery 2

### PR DESCRIPTION
**Pull request by hskang9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1044

### CODE REVIEW

**Comment by hskang9** [comment]
@cruikshankss are you still assigned for this delivery?

**Comment by hskang9** [comment]
Any updates on the delivery?

**Comment by alxs** [comment]
Hi @hskang9, sorry for the prolonged wait - we currently have a long backlog of milestone deliveries. I think @semuelle will take a look at yours as soon as possible.

**Comment by semuelle** [comment]
Hi @hskang9. I am working on the evaluation of your milestone. Two issues so far:

1. Could you add a description to the testing guide how I can test the code of signac itself, not its use? I see `nx test` referenced in the package.json, so I assume it's fairly easy.
2. How do I submit change suggestions to your documentation? I see a [signac doc in your repo](https://github.com/standardweb3/docs/tree/main/developing/tools/signac), but it's a placeholder referencing an unrelated repository.

**Comment by hskang9** [comment]
1. **The length of the command does not decide the difficulty of implementation of the test code**.  Current test codes are for e2e/generator tests for nxink, and signac command tests are being blocked by the fact that executing tests faces a deadlock in callback between inquirer choice and printing output with other CLI E2E test libraries. Can you also elaborate on the difference between "code of Signac" and "its use" after going through contribution guide [here](https://github.com/standardweb3/signac/blob/main/CONTRIBUTING.md#understand-framework-structure)? The test code is now fixed adjusting to cargo-contract.  
2.  In order to remove duplicate effort on explaining Signac, the documentation scrapes README in the signac repo. I left instruction on the placeholder readme of the doc.

**Comment by semuelle** [comment]
> Can you also elaborate on the difference between "code of Signac" and "its use" after going through contribution guide [here](https://github.com/standardweb3/signac/blob/main/CONTRIBUTING.md?rgh-link-date=2022-10-20T07%3A03%3A47Z#understand-framework-structure)? 

Sorry if my phrasing was unclear. What I mean is that your testing guide explains how to *use* signac, but what I would like to see are instructions how to run the unit tests or integration tests you have implemented.

**Comment by hskang9** [comment]
Oh for unit tests, I think you can run yarn test or nx test to test out nxink for now. For Signac general command manager, e2e test is being built.

**Comment by hskang9** [comment]
ok I cleaned up my mess [here](https://github.com/standardweb3/signac/blob/d05ebcb36c35accf3db26324e5aac72b82cb2699/packages/init/src/index.ts#L11).

**Comment by semuelle** [comment]
Thanks for the update, @hskang9. The scripts are working now. 

The test instructions are also very helpful, and I see that you already integrated them in the contribution guide. However, when I try to run the tests, I always get the same error message (independent of what directory I run it from and which package I want to test). I checked, and there are no `jest.config.js` files in any of the packages. Is there something I'm missing?

```
❯ npx nx test add-contract

> nx run add-contract:test 
Can't find a root directory while resolving a config file path.
Provided path to resolve: /home/user/signac/signac/packages/add-contract/jest.config.js
cwd: /home/user/signac/signac/packages
```

**Comment by hskang9** [comment]
So here is another annoying thing about nx when moving from lerna.... Nx only works when your current working directory is on project root. so in your case, you have to run `yarn test` inside the directory or set your current working directory to project root then execute `npx nx test add-contract`.

**Comment by hskang9** [comment]
@semuelle if you are writing tests in `add-contract`, can you share the code with PR? I would gladly add your contribution and add your name in the readme contributor section.

**Comment by semuelle** [comment]
> So here is another annoying thing about nx when moving from lerna.... Nx only works when your current working directory is on project root, because it thinks each package directory should belong to workspace as a whole. so in your case, I think you have to run `yarn test` inside the directory or set your current working directory to project root then execute `npx nx test add-contract`. Signac is trying to solve this to set current working directory when setting up the task by getting root dirctory with `signac.config.js` file like [here](https://github.com/standardweb3/signac/blob/bfbc88a384440414bda09a1ed16f59f512f0a017/packages/build/src/index.ts#L51). You can get support in this slack CS link [here](https://join.slack.com/t/nrwlcommunity/shared_invite/zt-1ifl6st51-hRNIPmhlva6xkR9z_UFDNA), and often see me complaining about Nx.

Could you verify test your test instructions on a clean machine and then share the steps you took, including OS, version numbers, etc.? I tried running the tests from the package directories and from the project directory. I had several error messages about different packages missing and paths not being found. These instructions should be easy to follow for others as well.

**Comment by hskang9** [comment]
Ah then you did not run yarn on the packages... ok I should include add command `yarn bootstrap` before testing the code.

**Comment by hskang9** [comment]
Also, how much **idiotproofness** of the guide are we expecting for the guide to be? Testing each module and developing on top of it actually requires skillset of:
- Setting up jest test env 
- Understanding Nx environment 
- Installing Node.js
**Are we just discussing on simply executing the tests in this repo without even going through any required skillset** or improvement for official contribution guide?

**Comment by semuelle** [comment]
> **Are we just discussing on simply executing the tests in this repo without even going through any required skillset** or **improvement for the official contribution guide for the one who can actually contribute to the project**?

We are not expecting a grantee to walk others through the whole ecosystem, but depending on the toolchain it's helpful to include how to set up the tools required to run the tests in your repository. If that is too complicated, it's always possible to link to an outside source. Personally, I have reviewed, used or tested plenty of node projects, but to my knowledge have never used nx. So any instructions required to set up nx to run your tests or project would be helpful. 

And I can report that `yarn bootstrap` seems to have done the trick, because I can now run the tests from both the root directory as well as the individual packages.

**Comment by hskang9** [comment]
ok now it is done, you can run `yarn test` to test all projects.

**Comment by semuelle** [comment]
Hey @hskang9. Many thanks for the update. I appreciate that you built a separate test script and the updates to the testing guide. 
Your milestone is hereby accepted. I will forward your invoice for processing. 

Overall, I am impressed with the project. Please keep us in the loop about its future development. And feel free to reach out to our [Grants-PR team](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) if you would like help getting the word out.

**Comment by semuelle** [comment]
I'd be happy to check it out!

**Comment by hskang9** [comment]
hey @meldien, sorry my bad on mistake. I incremented the invoice number and submitted a new form. please check.

**Comment by hskang9** [comment]
@meldien I submitted new form, and could not see payment processed. Is there a problem again?

**Comment by meldien** [comment]
@hskang9 apologies for the late response. 
The invoice is approved and should be paid next week. We will inform you after the payment is done.

**Pull request merged**
