### PR TITLE
Cyclops milestone 1

### PR DESCRIPTION
**Pull request by ArthurHoeke**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1549

### CODE REVIEW

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Thanks a lot for the delivery, I'm evaluating the milestone.

I know the tests don't do anything particular (obviously), but if I run them I get the following error:
```
Error: ../../services/coingecko/coingecko.service.spec.ts:3:34 - error TS2307: Cannot find module './coingecko/coingecko.service' or its corresponding type declarations.
```
Also, the logs tell
```
Chrome 110.0.0.0 (Mac OS 10.15.7): Executed 0 of 0 SUCCESS (0.001 secs / 0 secs)
TOTAL: 0 SUCCESS
```
Does this mean that they don't get executed?

**Comment by ArthurHoeke** [comment]
> 

Thanks for starting the evaluation! I have pushed a fix to the master branch, there was an incorrect path to the coingecko service, though the service indeed does not have any functionality in this phase yet.

**Comment by 0xCaso** [comment]
Yes, thanks a lot, I wanted to point it out so the testing for the next milestone should be straightforward.

**Comment by 0xCaso** [comment]
Some tests still fail btw (text from Google Chrome output):
```
10 specs, 4 failures, randomized with seed [45638](http://localhost:9876/context.html?seed=45638)
[Spec List](http://localhost:9876/#) | Failures

[AppComponent](http://localhost:9876/context.html?spec=AppComponent) > [should render title](http://localhost:9876/context.html?spec=AppComponent%20should%20render%20title)
Expected undefined to contain 'cyclops app is running!'.

[LoginComponent](http://localhost:9876/context.html?spec=LoginComponent) > [should create](http://localhost:9876/context.html?spec=LoginComponent%20should%20create)
Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'button' (used in the 'LoginComponent' component template).
1. If 'button' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

[DashboardComponent](http://localhost:9876/context.html?spec=DashboardComponent) > [should create](http://localhost:9876/context.html?spec=DashboardComponent%20should%20create)
Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'a' (used in the 'DashboardComponent' component template).
1. If 'a' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

[SettingsComponent](http://localhost:9876/context.html?spec=SettingsComponent) > [should create](http://localhost:9876/context.html?spec=SettingsComponent%20should%20create)
Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'a' (used in the 'SettingsComponent' component template).
1. If 'a' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
```
6/10 are passing. I know they're not really relevant, but I'm asking for the reason [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/776#issuecomment-1451781061).

**Comment by ArthurHoeke** [comment]
> Some tests still fail btw (text from Google Chrome output):
> 
> ```
> 10 specs, 4 failures, randomized with seed [45638](http://localhost:9876/context.html?seed=45638)
> [Spec List](http://localhost:9876/#) | Failures
> 
> [AppComponent](http://localhost:9876/context.html?spec=AppComponent) > [should render title](http://localhost:9876/context.html?spec=AppComponent%20should%20render%20title)
> Expected undefined to contain 'cyclops app is running!'.
> 
> [LoginComponent](http://localhost:9876/context.html?spec=LoginComponent) > [should create](http://localhost:9876/context.html?spec=LoginComponent%20should%20create)
> Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'button' (used in the 'LoginComponent' component template).
> 1. If 'button' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
> 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> 
> [DashboardComponent](http://localhost:9876/context.html?spec=DashboardComponent) > [should create](http://localhost:9876/context.html?spec=DashboardComponent%20should%20create)
> Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'a' (used in the 'DashboardComponent' component template).
> 1. If 'a' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
> 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> 
> [SettingsComponent](http://localhost:9876/context.html?spec=SettingsComponent) > [should create](http://localhost:9876/context.html?spec=SettingsComponent%20should%20create)
> Error: NG0303: Can't bind to 'routerLink' since it isn't a known property of 'a' (used in the 'SettingsComponent' component template).
> 1. If 'a' is an Angular component and it has the 'routerLink' input, then verify that it is a part of an @NgModule where this component is declared.
> 2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
> ```
> 
> 6/10 are passing. I know they're not really relevant, but I'm asking for the reason [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/776#issuecomment-1451781061).

Pushed an update to master a couple minutes ago👍

**Comment by 0xCaso** [comment]
> Pushed an update to master a couple minutes ago👍

Thanks again, didn't see it! Now everything works

**Comment by 0xCaso** [comment]
I have one last question: what's the purpose of the `SMTP` section in the `Settings` page?

**Comment by ArthurHoeke** [comment]
> I have one last question: what's the purpose of the `SMTP` section in the `Settings` page?

Validators will receive e-mail notifications to inform them of any critical events that may happen, in order for these e-mails to be sent out the back-end will require SMTP details. I'm still not entirely sure if I want these SMTP and API credentials to be adjustable via the front-end, though for now I've added the container.

**Review by 0xCaso — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
I was checking your invoice. Could you please resend it with the name of your company instead of "UndefinedCompany"? The rest should be perfect.

**Comment by ArthurHoeke** [comment]
> I was checking your invoice. Could you please resend it with the name of your company instead of "UndefinedCompany"? The rest should be perfect.

Sorry my bad, I've got two registered companies one being UndefinedCompany and the other decentraDOT. I've submitted an updated invoice.

**Comment by 0xCaso** [comment]
> Sorry my bad, I've got two registered companies one being UndefinedCompany and the other decentraDOT. I've submitted an updated invoice.

I was doubting "UndefinedCompany" wasn't an error and was the actual name ;) but that explains well haha
Thanks, and no problems!

**Comment by fededubbi** [comment]
Hi @ArthurHoeke,

I noticed that on your invoice there is a VAT amount, but this should be 0.
Can you please update the invoice and resend it?

Many thanks,
Federica

**Comment by ArthurHoeke** [comment]
> Hi @ArthurHoeke,
> 
> I noticed that on your invoice there is a VAT amount, but this should be 0. Can you please update the invoice and resend it?
> 
> Many thanks, Federica

Sorry I'm not too sure how VAT works between two European countries. Do you handle VAT payment entirely? I've sent an updated PDF with 0% VAT. Phase 2 invoice will be smooth at least!

**Comment by RouvenP** [comment]
hi @ArthurHoeke we transferred the payment today.

**Pull request merged**
