### PR TITLE
XCM SDK M2

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1199

### CODE REVIEW

**Comment by 0xslipk** [comment]
latest version [v0.1.0-rc.1](https://www.npmjs.com/package/xcm-sdk/v/0.1.0-rc.1)

**Comment by 0xslipk** [comment]
> latest version [v0.1.0-rc.1](https://www.npmjs.com/package/xcm-sdk/v/0.1.0-rc.1)

latest version [0.1.0-rc.2](https://www.npmjs.com/package/xcm-sdk/v/0.1.0-rc.2)

**Comment by 0xslipk** [comment]
> Hi @0xslipk thanks for this delivery. Starting the evaluation today, will get back to you with feedback in next days...

Awesome.

**Comment by 0xslipk** [comment]
> * xcm-sdk

Hi @randombishop 

This is because you are installing the latest version (M1 release) and currently the M2 is a release candidate version.

So, in order to test the M2 features you need to install it like this `npm i -g xcm-sdk@0.1.0-rc.2`

image


**NOTE**: As soon this PR is merged, We are gonna release M2 as latest version.

**Comment by randombishop** [comment]
Thank you, it works as expected now!

**Comment by randombishop** [comment]
Hi @0xslipk !

Happy to inform you that this delivery was accepted.

You can find my evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_2_randombishop.md

Forwarded your invoice, please allow up to 2 weeks for processing.

Cheers!

**Comment by 0xslipk** [comment]
> Hi @0xslipk !
> 
> Happy to inform you that this delivery was accepted.
> 
> You can find my evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_2_randombishop.md
> 
> Forwarded your invoice, please allow up to 2 weeks for processing.
> 
> Cheers!

Hi @randombishop 

Thank you so much for taking the time to review our delivery.

Best!

**Pull request merged**
