### PR TITLE
Typink M1

### PR DESCRIPTION
**Pull request by sinzii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2420

### CODE REVIEW

**Comment by sinzii** [comment]
Hey everyone, we've just add e2e tests for a `typink` hooks on zombienet to test out the hooks in a real running network. We're running both [unit tests](https://github.com/dedotdev/typink/actions/workflows/run-tests.yml?query=branch%3Aw3f-delivery-m1) & [e2e tests](https://github.com/dedotdev/typink/actions/workflows/zombienet-tests.yml?query=branch%3Aw3f-delivery-m1) on GH actions to verify the status.

If you want to run e2e tests on your local environment, please follow the [instruction here](https://github.com/dedotdev/typink/tree/w3f-delivery-m1/e2e/zombienet#e2e-tests-via-zombienet) to run it. Let us know if you run into any issue or feedback. Thanks!

**Comment by sinzii** [comment]
Hey @semuelle, please let us know if there's any updates or blockers in the evaluating process this delivery, thank you!

**Comment by semuelle** [comment]
Sorry for the delay, @sinzii. I was planning to finish the review before the holidays, but it got a bit hectic. I'll review it asap.

**Review by semuelle — APPROVED** [review]
Hi @sinzii. I already finished reviewing everything and I'm happy to report that your milestone is accepted. Congrats and nice work!

You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typink_1_semuelle.md).

**Comment by sinzii** [comment]
Awesome, thank you @semuelle! I've also submitted the invoice form!

**Comment by sinzii** [comment]
Hi @RouvenP, we intented to receive the first milestone fully in DOT (50%), so that why I submitted only one invoice for DOT. I can submit another one for USDC, but it should be 0 USDC, is that necessary? Thanks!

**Comment by RouvenP** [comment]
got it, thanks for clarifying! That's fine with us, then no separate invoices are needed. Please note that the DOT will be vesting linearly over two years, as specified in the T&C. I'm just mentioning this to make sure expectations are aligned.

**Comment by sinzii** [comment]
Thanks @RouvenP! We're aware of that, that's why we want to receive the DOT first to start the vesting as soon as possible.

**Comment by RouvenP** [comment]
Makes sense, thanks for confirming - we just sent the payment @sinzii

**Pull request merged**
