### PR TITLE
Add 2nd milestone delivery description

### PR DESCRIPTION
**Pull request by krzysztof-jelski**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Krzysztof, thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
Hi @krzysztof-jelski. I started to look into your [delivery](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-desktop-app_2_Noc2.md) and everything, which you delivered, looks good. But we need to update the original contract. Could you create an PR to the open grants repo to amend the [contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/polkadot-desktop-app.md) accordingly?

**Comment by AxisRebellious** [comment]
@krzysztof-jelski #126 
Duplicate of #

- [ ] 

- 

> ### _`[](url)`_

**Comment by krzysztof-jelski** [comment]
@Noc2 PR created: https://github.com/w3f/Open-Grants-Program/pull/388. Waiting for your feedback.

**Comment by Noc2** [comment]
Given the amendment, I’m happy to tell you that the milestone is a pass. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-desktop-app_2_Noc2.md). I will now forward the invoice internally.

**Pull request merged**
