### PR TITLE
Create Asylum milestone 3 delivery application

### PR DESCRIPTION
**Pull request by YaremenkoM**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1000

### CODE REVIEW

**Comment by YaremenkoM** [comment]
Hi!

We're happy to deliver our third milestone and looking forward to your review!
Will be glad to help you with anything if needed.

**Comment by takahser** [comment]
@YaremenkoM thanks for your delivery! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until your delivery is evaluated. Nevertheless, we're going to take a look at it as soon as we can.

**Comment by YaremenkoM** [comment]
Got you!

Looking forward 😌

**Comment by sventime** [comment]
> @YaremenkoM thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/asylum_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

@dsm-w3f  Thank you for the detailed review! 

About Standalone mode in Unity SDK, did you try to clone Asylum Unity SDK Example with all submodules? I see docs might be confusing, we'll improve it.

Another question is about the Code Quality section: `cargo clippy`  doesn't give us such a result you get. Maybe we're missing some special flags or configs for Clippy. Could you please share how you run Static Analysis tools within our pallets?

The last question is about UI tests. I see a lot of sense in covering connection-library with jest tests, but what about Creator Studio app? What kind of tests and coverage rate do you expect to see there (unit, integration, e2e)? From my point of view the best solution is to have Cypress e2e tests with a couple of sanity test scenarios, like in the Testing Guide. And couple of unit tests for rare algorithmic functions we're using within project.

Also, can we reach you somehow via the Element channel for other clarifying questions?
Thank you!

**Comment by dsm-w3f** [comment]
@sventime thank you for your questions. If you have any other doubt, you can reach me in this thread.  

> About Standalone mode in Unity SDK, did you try to clone Asylum Unity SDK Example with all submodules? I see docs might be confusing, we'll improve it.

I just cloned the repository as stated in the documentation. If some additional step is needed to get all submodules, please explain in the docs. 



> Another question is about the Code Quality section: `cargo clippy` doesn't give us such a result you get. Could you please share which Clippy parameters you're using?

I used the command bellow in the root of asylum-item-nft project.
 
`cargo +nightly clippy`



> The last question is about UI tests. I see a lot of sense in covering connection-library with jest tests, but what about Creator Studio app? What kind of tests and coverage rate do you expect to see there (unit, integration, e2e)? From my point of view the best solution is to have Cypress e2e tests with a couple of sanity test scenarios, like in the Testing Guide. And couple of unit tests for rare algorithmic functions we're using within project.

I think you can go forward with your approach and justify why you used that on the delivery. We usually ask for unit and integration tests [as stated in our delivery guideline](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md) but other approaches like e2e is acceptable as well. Regarding coverage, there is no specific percentage required in our guideline, however usually test coverage tools (and common sense as well) classify less 50% of coverage as low, 50% to 79% as medium, and 80% or more as a good coverage. You can deliver the percentage that make sense for your project, just remember to justify the decisions made if they are not commonly acceptable. Also remember that stakeholders usually expect high quality software and all information regarding the grant evaluation will be public available. 


> Also, can we reach you somehow via the Element channel for other clarifying questions?

For transparency reasons, let's maintain this conversation public. We can continue using this channel to answer any doubt or question that you have. 



> P.S.: what code coverage is appropriate for Unity SDK automated tests?

Same answer than UI question.

**Comment by sventime** [comment]
Hi @dsm-w3f!

So we finished polishing our delivery, and I'll go through all your comments and our updates:
1. The first big update is that we combined all our documentation consisting of different parts (UI, Node, Unity SDK, standards) in one single place: [https://docs.asylum.space](https://docs.asylum.space).
We traversed all documents and made them more clear and up-to-date. We updated all links in the current PR to new documentation.

2. We published a tech article about Asylum on Medium: [Asylum — the one to unite all spaces into a Metaverse](https://medium.com/@AsylumMeta/asylum-the-one-to-unite-all-spaces-into-a-metaverse-129cd989e76e)

3. About the blockers during your review:
 - The issue you faced during testing Creator Studio might be happening because of `@polkadot/api` version conflicts. I fixed the concrete version in package.json, and the problem is gone. But you have to remove `node_modules` or run `yarn clean` from `asylum-ui` root.
Also we made steps for data reseeding more clear: [Docker Setup: Reseed Data](https://docs.asylum.space/asylum-ui/creator-studio/installation-docker#reseed-storage), and polished all our tutorials (please check it [Tutorials: Configure Patterns](https://docs.asylum.space/tutorials/testing-guide-patterns))
- We refined our Unity SDK docs: [Unity SDK](https://docs.asylum.space/unity-sdk/overview) and made Asylum Unity SDK Example as simple as possible in installation. Please check the [Installation: Quick Install](https://docs.asylum.space/unity-sdk/installation#quick-install). To test Play Mode, WebGL, and standalone builds, please check this section: [Build & Run](https://docs.asylum.space/category/build--run)

4. About Code Quality:
  4.1 asylum-item-nft (Rust Node)
   - Automated tests coverage generally increased:
            Asylum blueprints coverage: 78.63% => 85.29%
            Asylum Off-chain Minter coverage: 8.7% => 70.37%, but all methods and error paths were covered
            Asylum Spaces coverage: 85.29% => 92.31%
    - fixed clippy warnings
    - documentation fixed

    4.2 Asylum-ui (front-end)
    - implemented cypress tests for Creator Studio: see [Run E2E Cypress tests](https://docs.asylum.space/asylum-ui/creator-studio/testing#run-e2e-cypress-tests)
    - implemented jest integration tests for connection-library with 84%% coverage: see [Run Jest Unit tests](https://docs.asylum.space/asylum-ui/creator-studio/testing#run-e2e-cypress-tests)
    - fixed eslint issues: run `yarn lint` from `asylum-ui` root folder
   - added in-code documentation for connection-library and creator-studio
   - added storybook support for creator-studio: [Run Storybook](https://docs.asylum.space/asylum-ui/creator-studio/storybook)
  
    4.3 Asylum-unity-sdk (Unity)
    - added automated tests: see [Unity SDK: Testing](https://docs.asylum.space/unity-sdk/testing)
   - added in-code documentation for classes

Looking forward to the next review iteration!
Thank you!

**Comment by YaremenkoM** [comment]
Hey @dsm-w3f !

Hope for your review as soon as possible, as approving the delivery of the third milestone is a very important step on our timeline! 😊

**Comment by dsm-w3f** [comment]
@sventime and @YaremenkoM thank you for the improvements. The tutorial is much better now. There are significant improvements in tests and docker as well. We are almost done with the evaluation. The only part that I'm having problems is running e2e tests. The installation of Polkadot.js in the browser controlled by cypress is a requirement to run the tests and there is no instruction on how to do that in the tutorial. I tested using Chrome on Linux. Even installing Polkadot.js on Chrome it is not available when running with Cypress. There are either some typescript compilation errors in the UI when using docker. Some tests are not passing in Unity SDK due to a timeout but this could be something in my machine because the tests are taking a long time to run. All remaining parts are good and very well done. The evaluation document was updated with details. Let me know when I could check again these latest parts to finish this evaluation.

**Comment by sventime** [comment]
Hi @dsm-w3f, thank you for the detailed review and your feedback.

I will go step by step again:

1. About E2E tests. It's impossible to install Polkadot{.js} in a Cypress environment; that's why there is a separate UI container, which runs Creator Studio in `test` mode (env variable `REACT_APP_NODE_ENV = test` is responsible for it). In this mode, the step of connecting to the extension will be skipped, and the user will auto login with `REACT_APP_MINTER_MNEMONIC` after clicking `connect wallet`.
According to your screenshots, I assume that Cypress is running against Creator Studio in normal mode, where Polkadot{.js} step is available. There are possibles reasons:
- `asylum-ui/packages/creator-studio/.env.test.local` was not created or has invalid content (check step 2 [Run E2E Cypress tests](https://docs.asylum.space/asylum-ui/creator-studio/testing))
- port `3000` of `localhost` was occupied by another instance of Creator Studio, and web app in test mode was not started (in step 4 of [Run E2E Cypress tests](https://docs.asylum.space/asylum-ui/creator-studio/testing) we suggest to remove previously set up the container and run `yarn docker:test:up`, or you can just stop `asylum-ui` container and start `asylum-ui-test`)

  We updated documentation and added notes about Polkadot{.js} and test mode in step 2, and also mentioned the issue with port 3000 in [Docker setup](https://docs.asylum.space/asylum-ui/creator-studio/installation-docker)

2. About Unity SDK test. Good catch! The problem was in tests, which are being expected for particular items on the node. I updated step 2 of [Run tests in Unity project](https://docs.asylum.space/unity-sdk/testing) to reseed node with items or just run the docker container in test mode `yarn docker:test:up`, which executes the current seed script for testing purposes.

3. Eslint warnings and errors in `asylum-ui`. We found that our eslint config in `connection-library` was not correctly configured, so we didn't see the warnings and errors you received. We updated configs and fixed errors: now `yarn lint` in the root folder completes without warnings. Please pull the latest main to see these changes.

I hope these updates will help to finalize delivery. Looking forward to your feedback!

**Comment by dsm-w3f** [comment]
@sventime and @YaremenkoM we are all good now. The delivery was approved and the evaluation document updated. I let a hint on how to fix the remaining eslint errors in the evaluation documents. Thank you for the delivery, great work!

**Review by Noc2 — APPROVED** [review]
I'm happy to confirm that the milestone is approved and I will merge the PR.

**Pull request merged**
