### PR TITLE
Interstellar-Network-Milestone_M4

### PR DESCRIPTION
**Pull request by nashjl**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x]This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/734 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
@nashjl Thanks for your delivery! It might be a bit before someone evaluates your milestone as we are backlogged, but someone will look at it soon.

**Comment by nashjl** [comment]
> @nashjl Thanks for your delivery! It might be a bit before someone evaluates your milestone as we are backlogged, but rest assured that we will look at it soon.

@keeganquigley, Ok thanks we understand an stay tuned!

**Comment by alxs** [comment]
@nashjl thank you for your patience and for the delivery also from my side. A couple of things:

- Could you also provide an article for this milestone? The link in the delivery file points to that for milestone 3. In case no one has pointed it out before, you can send it to grantsPR@web3.foundation (ideally add grants@web3.foundation in cc) for proofreading and cross-promotion.
- The [instructions](https://github.com/Interstellar-Network/integritee-worker#build-and-run) to run `integritee-worker` failed for me with the following error:
  ```
  /bin/sh: 1: file: not found
  make: *** No rule to make target '/opt/intel/sgxsdk/bin/x64/sgx_edger8r', needed by 'enclave-runtime/Enclave_t.c'.  Stop.
  ```
  While `cargo test` failed with the following output: [cargo test.txt](https://github.com/w3f/Grant-Milestone-Delivery/files/9870675/cargo.test.txt). Could you provide instructions to install the missing libraries?
 - When running `substrate-offchain-worker-demo` with the provided [command](https://github.com/Interstellar-Network/substrate-offchain-worker-demo#run), I still get "[ocw-garble] nothing to do, returning..." and "[ocw-circuits] nothing to do, returning..." in the logs.

**Comment by alxs** [comment]
Hi @nathanprat, thank you for the quick answer. I'm happy to confirm that the docker-compose approach following the tutorial worked. However, as you guessed, I would also like to be able to run the tests etc. Could you maybe provide another Dockerfile that runs them, as well as `cargo tarpaulin` if possible? I saw you have CI in place in some of your repositories so alternatively, feel free to just link to a successful run.

If the installation of the SDK is as messy as you say, I agree that ideally I wouldn't need to install it and all the dependencies, but as a last resort we do have a dedicated test box and it is also an option.

**Comment by nathanprat** [comment]
Hi @alxs,

I have not used `tarpaulin` so I can't be sure it is going to work.
See the table below for results.
Note that most of the complexity of the code is in C++(lib_circuits/lib_garble repos) so even if it worked, it would not tell you much (for that you can run `ctest` and a C++ code coverage tool).

| Repo        | Language          |  cargo-tarpaulin
| :-------------: |:-------------:| :-------------:|
| [lib_circuits](https://github.com/Interstellar-Network/lib_circuits)     | C++ | N/A
| [api_circuits](https://github.com/Interstellar-Network/api_circuits)      | Rust      | FAIL; `ERROR cargo_tarpaulin: Failed to run tests: A segfault occurred while executing tests` Possibly b/c of this exe is linked with system-wide libraries? |  $12 |
| [lib_garble](https://github.com/Interstellar-Network/lib_garble) | C++      | N/A |
| [api_garble](https://github.com/Interstellar-Network/api_garble) | Rust      |    `80.33% coverage, 1074/1337 lines covered` |
| [integritee-node](https://github.com/Interstellar-Network/integritee-node) | Rust | `1.34% coverage, 19/1414 lines covered` b/c the tests only cover our pallets, but the repo contains the whole integritee's sources |
| [integritee-worker](https://github.com/Interstellar-Network/integritee-worker) | Rust+SGX      |    N/A b/c of Intel SGX? |
| [pallets](https://github.com/Interstellar-Network/pallets) | N/A      |    No CI, integrated in integritee-node/integritee-worker as submodule |

For local tests, excluding `integritee-worker` repo, the rest should compile and run `cargo test` locally if you have a dev machine with the basics(C++ toolchain, CMake, Make/Ninja).
You can check the CI workflow in each repo for required dependencies; typically there is an `apt-get` and/or a `wget`.
**IMPORTANT** a bunch of dependencies are also installed via `uses`(at least IPFS).

For `integritee-worker`: the CI uses `rust.yml` to compile, which is based on those: https://github.com/apache/incubator-teaclave-sgx-sdk/tree/master/dockerfile.
That being said, I don't think tarpaulin and SGX would play nice.


I also tried to link the CI raw logs ([example](https://pipelines.actions.githubusercontent.com/serviceHosts/d80bd81f-1495-4c6d-8da6-23e3be76cd51/_apis/pipelines/1/runs/17/signedlogcontent/2?urlExpires=2022-10-31T09%3A16%3A12.2556514Z&urlSigningMethod=HMACV1&urlSignature=skEOVIm5mzZLNdPjiMmAZZnlnNIk7AI8r%2BQxPWy2yog%3D)) but that does not work b/c the URL is only valid for a minute...
Do you have another idea on how to do it? (except downloading and reuploading a bunch of zipped logs)

**Comment by alxs** [comment]
@nathanprat thank you so much for the detailed report! That looks great, I confirm that the tests run in the other repositories and given the level of detail you provide, I'm happy to make an exception and accept the ones in `integritee-worker` without running them myself.

My only remaining doubts are regarding documentation. On the one hand the question of the article I mentioned previously, but on the other hand deliverable 0b. also describes "a basic tutorial that explains how a user can manage garbled circuit cid in pallets with a transaction validation use case example in TEE environment with SubstraTEE." Do you have anything like this?

**Comment by nathanprat** [comment]
For `integritee-worker`, you can definitely run the tests yourself if you follow `rust.yml`. But you must run the exe directly **not** using `cargo test`.

For `0b` indeed this is indeed not really clear, sorry about that.  It was written before we had a clear idea of TEE/integritee, and what exactly the ported pallets would be.
Essentially this milestone 4 is the previous one, but a few pallets ported to TEE. Which is why we skipped the whole "client part" b/c that requires installing a app(Android) setting the whole ssh forwarding etc which is:
- a bit complicated (cf [M3 demo guide](https://book.interstellar.gg/M3_demo_tutorial.html#3-install-the-wallet-app-ie-apk-file-on-an-android-device-or-an-emulator))
- a bit pointless b/c the client code has not changed

> a basic tutorial that explains how a user can manage garbled circuit cid in pallets with a transaction validation use case example in TEE environment with SubstraTEE

That being said, the script `demo_interstellar.sh` used in [M4 Demo Tutorial](https://book.interstellar.gg/M4_demo_tutorial.html#m4-demo-tutorial) is calling `api_garble` behind-the-scene, and in turn that is storing a "circuit" in IPFS.
We simply avoid exposing the internals to a client, but you can definetely retrieve the IPFS hash from the podman logs, then download the file and manually run the circuit via a cli in `lib_garble` repo(or using the docker from `M3`).
I can whip up something to walk you through it if you want? But I need to point out that the repo `api_garble/lib_garble` has not really changed since the previous milestone so the "client part"(ie running the circuit locally) so that will look like the M3 demo.

**Comment by nashjl** [comment]
@alxs sorry for the delay in my response. Thanks for pointing it out. The article link for M4 is fixed now. It includes a little update to our not yet officially published [article](https://medium.com/@jlleleu/b4003a64e927).

 Appreciate your suggestion regarding cross-promotion with grantsPR! We're currently still in stealth mode and want to wait until we get all the resources needed to launch an end-to-end MVP solution before publishing anything officially. 
 
 We want the MVP to focus on the Polkadot/Kusama ecosystem and include an iOS client in addition to Android. As suggested by the W3F grants team, we're working on a follow-up grant on this end alongside active conversations with potential investors and partners. 
 
 Once confortable with ressources/funding, we definitely aim to leverage the W3FPR in the following phases.

**Comment by alxs** [comment]
@nathanprat thanks for clarifying. That's fine, I'd say there's no need to bend over backwards to meet the boilerplate descriptions for the mandatory deliverables if it doesn't make sense.

@nashjl thanks, but I still can't access the article, it is probably private. Note that the application describes a separate article with each milestone, but as far as we're concerned it's only really mandatory with the last one.

If you have any more significant changes in the future, please remember to submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Comment by nashjl** [comment]
@alxs thanks for your message.

The link is supposed to be public. We double-checked and did not find any issues. Could you try the following link : https://medium.com/@jlleleu/web3-foundation-and-interstellar-protocol-b4003a64e927 

Let us know if it works for you.

**Comment by alxs** [comment]
Thanks @nashjl! I apologise, the previous link also works but one must log in to Medium, which for some reason I'm not able to do in my usual browser.

With this, I'm happy to let you know that the milestone is accepted! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/interstellar_4_alxs.md). I'll notify the finance team to pay out your invoice. As usual, please allow for up to two weeks for processing.

**Comment by nashjl** [comment]
@alxs sure, does it work for you to include it in reference as a footnote? 
- We are not using this address.

We already had a discussion with Melanie regarding how the payment should be processed in EUR (not a swift transfer in USD) and adjusted our latest invoice accordingly.

**Comment by alxs** [comment]
@nashjl fine by me.

**Comment by nashjl** [comment]
> @nashjl fine by me.

@alxs updated invoice submitted

**Pull request merged**
