### PR TITLE
Rubeus Keeper Stage 2 M2

### PR DESCRIPTION
**Pull request by dsrdrk11a**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the Statemint payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1361/

### CODE REVIEW

**Comment by keeganquigley** [comment]
@dsrdrk11a thanks for the delivery! I have finished my evaluation and you can find it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rubeus_keeper_st2_2_keeganquigley.md). Just a couple questions:

- I'm not finding any unit tests since the last delivery. Was wondering if you had written any for the password generator or autofill functions? 
- I'm not finding an invoice for this milestone. Do you know if one was submitted and can you please submit if not?

Thanks!

**Comment by dsrdrk11a** [comment]
Hello, @keeganquigley 
Yes, I've submitted the invoice in the invoice form and re-submitted it right now just in case.
For the unit tests - we agreed on deleting the Cypress tests, when applied for this grant, and left only unit tests in the contract. In the 2nd milestone the contract wasn't changed, so no new tests here.

**Comment by keeganquigley** [comment]
Ah thanks @dsrdrk11a I see it now, I'm not sure why it wasn't showing up originally. Thanks for reminding me about the agreement on the tests. I am happy to pass this milestone, and congrats on the completion of the grant. I have forwarded your invoice for payment.

**Comment by dsrdrk11a** [comment]
@keeganquigley great to hear that! Thank you!

**Comment by RouvenP** [comment]
hi @dsrdrk11a we transferred the payment today.

**Pull request merged**
