### PR TITLE
dorafactory multisig delivery milestone 1

### PR DESCRIPTION
**Pull request by tinydjp**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/711

### CODE REVIEW

**Comment by tinydjp** [comment]
Hi team, hope it's not late to submit out delivery. In our application we filled 1 month * 2 FTE, suppose it's 2 month duration, if NOT, please accept my sincere apology. We did encounter some unexpected challenges, but we almost made it. Please take your time to review, thanks!
BTW, how can I fix the cicd errors. First time to submit delivery.

**Comment by semuelle** [comment]
Hi @tinydjp. Thanks for the delivery. We will look into it as soon as possible. We currently have a bit of a backlog, so please give us a week or two to get back to you.

No worries about the delay. We ask teams to roughly keep to the proposed timeline, but delays of a few weeks are completely normal and we have no desire to rush anyone. Also don't worry about the CICD, that's just for internal bookkeeping.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the delivery. I started to look into it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dora-factory-multisig_1_Noc2.md). Could you take a look at it? At the moment my biggest concerns are:

- If I try to create a transaction it just forwards me to https://polkadot.js.org/apps! However the contract says: “2) Initiate, sign, and confirm transactions”
- Only a single test, in general it would be nice to have more unit test

**Comment by tinydjp** [comment]
> Thanks for the delivery. I started to look into it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dora-factory-multisig_1_Noc2.md). Could you take a look at it? At the moment my biggest concerns are:
> 
> * If I try to create a transaction it just forwards me to https://polkadot.js.org/apps! However the contract says: “2) Initiate, sign, and confirm transactions”
> * Only a single test, in general it would be nice to have more unit test

Hi @Noc2 thanks for your quick response, for the documentation evaluation seems something missing, for others I'll check and fix.

**Comment by tinydjp** [comment]
Hi @Noc2, would you please check again, I've just updated a patch.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Most of the issues are fixed now. However, I wasn’t able to confirm the multisig transaction with a second account via the UI. Could you look into this? Potentially you could also update the test guide: https://github.com/DoraFactory/dorafactory-multisig/blob/main/docs/test-guide.md Also it would be nice if the UI stores the call data, but that’s just a suggestion.

**Comment by tinydjp** [comment]
> Thanks for the update. Most of the issues are fixed now. However, I wasn’t able to confirm the multisig transaction with a second account via the UI. Could you look into this? Potentially you could also update the test guide: https://github.com/DoraFactory/dorafactory-multisig/blob/main/docs/test-guide.md Also it would be nice if the UI stores the call data, but that’s just a suggestion.

May I know how to reproduce the errors? Well, I think store the transactions  may be better, it contain more information.

**Comment by Noc2** [comment]
It’s not really an error. Simply once I initiate a transaction with for example a 2 out of 2 multisig, I don’t know how to confirm the transaction with the second account via the UI.

**Comment by tinydjp** [comment]
> It’s not really an error. Simply once I initiate a transaction with for example a 2 out of 2 multisig, I don’t know how to confirm the transaction with the second account via the UI.

ok, interesting scenario, I did not think of this condition. Let me improve somehow

**Comment by tinydjp** [comment]
Hi @Noc2,  I made some enhancement for your case. In the old version, the wallets only remain the latest owner if wallet address is the same. Now it'll remain all records. I think [step 8 in the test-guide](https://github.com/DoraFactory/dorafactory-multisig/blob/main/docs/test-guide.md) can help you finish the whole test process.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to tell you that the milestone is a pass and I will forward your invoice internally. However, the UI certainly still can be improved. For example the logout/login feature didn’t work for me and I had to recreate the same multisig. It would be nice if you kept working on it.

**Comment by Noc2** [comment]
@tinydjp Could you send us another invoice that also contains your real world address, our address and the payment amount? Thanks

**Comment by tinydjp** [comment]
> Thanks for the update. I’m happy to tell you that the milestone is a pass and I will forward your invoice internally. However, the UI certainly still can be improved. For example the logout/login feature didn’t work for me and I had to recreate the same multisig. It would be nice if you kept working on it.

Yes, there're a few details to be improved indeed, as it's in MVP stage, we choose to browsers'  local storage to store the account data. In the future, these data should be stored on cloud or some servers, we'll make statement for data storage issues.

**Comment by tinydjp** [comment]
> @tinydjp Could you send us another invoice that also contains your real world address, our address and the payment amount? Thanks

Sorry for the inconvenience, can I just update the google form in our checklist or send you by email?

**Comment by Noc2** [comment]
> > @tinydjp Could you send us another invoice that also contains your real world address, our address and the payment amount? Thanks
> 
> Sorry for the inconvenience, can I just update the google form in our checklist or send you by email?

Np. Feel free to upload a new invoice via the google form.

**Comment by tinydjp** [comment]
Hi @Noc2 , we just updated the invoice file, please help check, thanks!

**Comment by Noc2** [comment]
Perfect. I just forwarded the invoice internally.

**Comment by fededubbi** [comment]
Good morning,

I just noticed that on the invoice the amount is wrong, should be 10k, could you please change it?
Also on the invoice is missing our address:

Baarerstrasse 14,
6300, Zug.

Could you please add it?

Many thanks,
Regards,

Federica Dubbini

**Comment by tinydjp** [comment]
Hi @fededubbi , sorry for the typos, amendment finished, please help check, thanks!

**Comment by fededubbi** [comment]
Hi,

Can you please send the correct invoice to this email address?

invoices@web3.foundation.

Many thanks,
Federica Dubbini

**Comment by tinydjp** [comment]
> Hi,
> 
> Can you please send the correct invoice to this email address?
> 
> [invoices@web3.foundation](mailto:invoices@web3.foundation).
> 
> Many thanks, Federica Dubbini

Sent

**Comment by RouvenP** [comment]
hi @tinydjp we transferred the payment today. Thanks!

**Pull request merged**
