### PR TITLE
OpenBrush Milestone 7

### PR DESCRIPTION
**Pull request by coreggon11**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/921 (accepted)
Updates to the application:
https://github.com/w3f/Grants-Program/pull/1149
https://github.com/w3f/Grants-Program/pull/1237
https://github.com/w3f/Grants-Program/pull/1366

Please note, that this is not the same account that opened the original PR, as Toma is not a part of 727.ventures anymore,  but updates to this PR were made by this account and approved by the original account.

### CODE REVIEW

**Comment by takahser** [comment]
Hey @coreggon11 
Thanks for your delivery. I'll have a look shortly. I'll keep you posted on the progress.

**Review by takahser — CHANGES_REQUESTED** [review]
@coreggon11 regarding 8b., you'll have to make it public in order to get this delivery approved. I'm quoting our [guidelines](https://github.com/w3f/Grants-Program/tree/d518465d7c54c18dae544ddeae7b47e9a3c0c864#guidelines):

> All code produced as part of a grant must be open-sourced, and it must also not rely on closed-source software for full functionality.

**Review by takahser — CHANGES_REQUESTED** [review]
@coreggon11 also, you seem to not have provided any guide on how to test your delivery. Feel free to add it.
You can find my intermediary evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/openbrush_7_takahser.md).

**Comment by coreggon11** [comment]
Hi @takahser , thanks for reply!

You can test openbrush contracts with `npm run test` to run integration tests (note that you need to run the latest (v 0.23) substrate-contracts-node prior to this), and `RUSTFLAGS="-D warnings" cargo +nightly test --workspace --features test-all -- --test-threads=10` to run the unit tests (this repo: https://github.com/727-Ventures/openbrush-contracts). These tests also include the `PSP22Pallet` tests, which test the communication of the smart contract with the `pallet-assets` via the chain extension.

You can also test the chain-extension generation with `cargo test --workspace --features ink-std` (test ink! part of the chain extension) and `cargo test --workspace --features substrate-std` (test the substrate part of the chain extension) in this repo: https://github.com/727-Ventures/obce

The flow of transition between pallet and contract is described in the readme provided, the readme explains what this standard achieves (standardize assets from `pallet-assets`) and how one can create PSP22 smart contracts base on the assets from `pallet-assets`. The medium post we created also describes cross-chain asset transfer, so it can also be used as a guide on how to transfer `PSP22Pallet` based tokens between chains which don't support smart contracts but do support `pallet-assets`.

I will update the delivery report to contain this info

**Review by takahser — APPROVED** [review]
@coreggon11 thanks for your support today, finally we've resolved all the outstanding issues! I'm happy to accept this delivery, you can find my [evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/openbrush_7_takahser.md).

**Comment by RouvenP** [comment]
hi @coreggon11 we just transferred the payment.

**Comment by coreggon11** [comment]
@RouvenP hi, thanks for the information

**Pull request merged**
