### PR TITLE
SubGame_Network_m2 Milestone2 Delivery.

### PR DESCRIPTION
**Pull request by xtony77**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/593](https://github.com/w3f/Grants-Program/pull/593)

### CODE REVIEW

**Comment by Noc2** [comment]
I quickly started to look into your delivery. The first thing I noticed was that I can not access the mockups: https://www.figma.com/file/7ZUQSuAfNrrmq5s3LSIFik/SubGame?node-id=3649%3A62086 
Also here some additional feedback:

- The image in your tutorial still shows the lorem ipsum text
- The documentation seems to be missing. You currently simply link to the application. Ideally the documentation should be available with in your github/website, so that others can find it and use it.  
- When I try to run docker-compose up, I get the error in my [initial evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SubGame_Network_m2_1_Noc2.md).
- Also I get an error when I try to run the front-end. [see evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SubGame_Network_m2_1_Noc2.md)
- When I try to compile the unit test of your lease pallet, I also get an error, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SubGame_Network_m2_1_Noc2.md)

**Comment by xtony77** [comment]
# SubGame m2 Reply

We made some corrections to these errors:
- (0b.)Documentation:
Yes, the application shows our project in detail, and the user tutorial will be placed in "2c."
Add link: https://github.com/SubGame-Network/SubGameModule
        
- (0c.& 1a.)Testing Guide : 
During our test, the results were all normal. Can you tell us what you did? The results of our test are attached, thanks~
```
> cargo test
   Compiling subgame-runtime v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/runtime)
   Compiling pallet-subgame-assets v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/assets)
   Compiling pallet-nft v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/nft)
   Compiling pallet-lease v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/lease)
   Compiling pallet-bridge v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/bridge)
   Compiling pallet-swap v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/swap)
   Compiling pallet-stake-nft v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/stake-nft)
   Compiling pallet-demogame v3.0.0 (/Users/momacbookpro2018/Project/rust/now_subgame-network/pallets/demogame)

...

     Finished test [unoptimized + debuginfo] target(s) in 1m 25s
     Running unittests (target/debug/deps/pallet_bridge-2c6d085f2d7ce68f)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/pallet_chips-3c34e400a988e6f8)

running 6 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::redemption_failded_when_never_bought_chips ... ok
test tests::buy_chips_failed_when_not_enough_money ... ok
test tests::redemption_all_chips ... ok
test tests::buy_chips ... ok
test tests::redemption_failded_when_chips_is_not_enough ... ok

test result: ok. 6 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests (target/debug/deps/pallet_demogame-51e89ee664b73195)

running 3 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::demo_error_permission ... ok
test tests::demo ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running unittests (target/debug/deps/pallet_gamecenter-496e39311ba2ccb8)

running 3 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::bet ... ok
test tests::create_game ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests (target/debug/deps/pallet_gametemplates-897616e1d5d9cc08)

running 3 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::create_template ... ok
test tests::create_template_failded_when_permission_denied ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests (target/debug/deps/pallet_gametemplates_guess_hash-2425101470b79aed)

running 4 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::create_game ... ok
test tests::bet ... ok
test tests::draw ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

     Running unittests (target/debug/deps/pallet_lease-1908aed36d68846a)

running 4 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::add_pallet ... ok
test tests::set_authority ... ok
test tests::check_authority ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/pallet_nft-68fb6fc2098c1308)

running 13 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::mint_err_non_admin ... ok
test tests::burn_err_not_exist ... ok
test tests::mint_err_dupe ... ok
test tests::burn_err_not_owner ... ok
test tests::mint ... ok
test tests::mint_err_max_user ... ok
test tests::burn ... ok
test tests::transfer_err_not_exist ... ok
test tests::mint_err_max ... ok
test tests::transfer ... ok
test tests::transfer_err_not_owner ... ok
test tests::transfer_err_max_user ... ok

test result: ok. 13 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running unittests (target/debug/deps/pallet_stake-4bed72a029d1fca5)

running 12 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::sign_up_account_format_is_wrong ... ok
test tests::stake_user_not_exists ... ok
test tests::sign_up ... ok
test tests::delete_user ... ok
test tests::stake ... ok
test tests::sign_up_exists ... ok
test tests::unlock ... ok
test tests::import_stake ... ok
test tests::unlock_not_owner ... ok
test tests::unlock_money_not_enough ... ok
test tests::withdraw ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.03s

     Running unittests (target/debug/deps/pallet_stake_nft-6cbc1b6626914ef5)

running 5 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::add_program ... ok
test tests::add_program_error_exist ... ok
test tests::stake ... ok
test tests::stake_expired ... ok

test result: ok. 5 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

     Running unittests (target/debug/deps/pallet_subgame_assets-7def25d19f0fe7bb)

running 23 tests
test tests::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::burning_asset_balance_with_positive_balance_should_work ... ok
test tests::basic_minting_should_work ... ok
test tests::burning_asset_balance_with_zero_balance_should_not_work ... ok
test tests::destroy_with_bad_witness_should_not_work ... ok
test tests::destroy_with_non_zombies_should_not_work ... ok
test tests::dezombifying_should_work ... ok
test tests::max_zombies_should_work ... ok
test tests::querying_total_supply_should_work ... ok
test tests::origin_guards_should_work ... ok
test tests::lifecycle_should_work ... ok
test tests::min_balance_should_work ... ok
test tests::set_team_should_work ... ok
test tests::resetting_max_zombies_should_work ... ok
test tests::set_metadata_should_work ... ok
test tests::transfer_owner_should_work ... ok
test tests::transferring_amount_below_available_balance_should_work ... ok
test tests::transferring_less_than_one_unit_should_not_work ... ok
test tests::transferring_frozen_asset_should_not_work ... ok
test tests::transferring_amount_more_than_available_balance_should_not_work ... ok
test tests::transferring_frozen_user_should_not_work ... ok
test tests::transferring_to_frozen_account_should_work ... ok
test tests::transferring_more_units_than_total_supply_should_not_work ... ok

test result: ok. 23 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests (target/debug/deps/pallet_swap-c2380a493fddb427)

running 12 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::create_pool2 ... ok
test tests::add_liquidity4 ... ok
test tests::add_liquidity3 ... ok
test tests::remove_liquidity ... ok
test tests::add_liquidity ... ok
test tests::create_pool_lp_check ... ok
test tests::create_pool ... ok
test tests::add_liquidity2 ... ok
test tests::swap2 ... ok
test tests::remove_liquidity_too_many ... ok
test tests::swap ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

     Running unittests (target/debug/deps/subgame-fd9ecfa8df023865)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/subgame-42b7de80163d9d77)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests (target/debug/deps/subgame_runtime-b2e55bd81fab038b)

running 3 tests
test __pallet_staking_reward_curve_test_module::reward_curve_piece_count ... ok
test __construct_runtime_integrity_test::runtime_integrity_tests ... ok
test __pallet_staking_reward_curve_test_module::reward_curve_precision ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.52s

   Doc-tests pallet-gametemplates-guess-hash
...
```
- (1c.)pallet-nft : 
We have revised the narrative. 
https://github.com/SubGame-Network/subgame-network/tree/develop/pallets/nft

- (2a.)Front End : 
Has been corrected.
- (2b.)UI mock-ups : 
The permissions have been changed to everyone can view. You can view it now.

- (2c.)Tutorial : 
Image with lorem ipsum is because some content can be customized for users.

- (2d.)Docker : 
Has been corrected.

**Review by Noc2 — APPROVED** [review]
Thanks for the update and sorry for the late reply. I’m happy to tell you that the milestone is a pass.

**Comment by Noc2** [comment]
Probably at the end of this week. The invoice usually takes care of the payments on fridays.

**Pull request merged**
