### PR TITLE
Plus: Polkadot js Plus extension, Milestone 1

### PR DESCRIPTION
**Pull request by Nick-1979**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/778

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @Nick-1979. We'll look into it as soon as possible

**Comment by cruikshankss** [comment]
Good day, @Nick-1979! 

My name is Ashley and I work as a Technical Grants Evaluator at W3F. Thank you for your milestone 1 delivery! 

I have installed the Plus plugin on Chrome and successfully connected my account! I can see the proper balance; I was also able to run & pass your unit tests, thank you!

I am confused on how to add the "Westend genesis & info" & rebuild from source. I am relatively new to the Polkadot ecosystem, so please forgive me. I cannot find these files in your codebase:

```
@polkadot/networks/genesis.js
@substrate/ss58-registry/index.js
```

Am I supposed to find these files in your codebase? Where are these files located?

Once I know, then I can add the westend genesis & info. Thank you!

**Comment by Nick-1979** [comment]
Hi Ashley,

Some Polkadot packages do not  support Westend hence some tweaks are needed to add Westend to the supported chains .

The files to add westend are located in "**node_modules**' folder, which can be found in the root of the project (after that yarn has installed modules).


1. add the following Westend genesis to ".**/node_modules/@polkadot/networks/genesis.js**"

`westend:['0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e']
`


2a. add the following Westend network information to "**./node_modules/@substrate/ss58-registry/index.js**" 

`{ "prefix": 42, "network": "westend", "displayName": "Westend", "symbols": [ "WND" ], "decimals": [ 12 ], "standardAccount": "*25519", "website": "https://polkadot.network" })`


2b. **In case that you can not find "@substrate"** folder in node modules (because it is added in the latest update of @polkadot package) you can add the following to  "**./node_modules/@polkadot/networks/ substrate.js**" instead as mentioned in the project readme file (https://github.com/Nick-1979/polkadot-Js-Plus-extension#to-test-on-westend). 

`{ decimals: [12], displayName: 'Westend', network: 'westend', prefix: 42, standardAccount: '*25519', symbols: ['WND'], website: 'https://polkadot.network' }`


The **most convenient way** to try the Westend is the compiled extension which is already available on Firefox addons page (https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-plus-extension/).


If there are any other questions/issues I would be happy to answer/help.


Thank you,  

Kami

**Comment by cruikshankss** [comment]
Hi Kami,

Thank you so much for your message. I've responded to it in [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/395) of your milestone. 

I've accepted your milestone and forwarded your invoice. 

It was a pleasure reviewing your project.

Sincerely,
Ashley

**Comment by RouvenP** [comment]
hi @Nick-1979 we transferred the payment today. Thanks!

**Pull request merged**
