### PR TITLE
Stone Index M1

### PR DESCRIPTION
**Pull request by calvinzhou-rockx**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @calvinzhou-rockx. We will look into it as soon as possible.

**Comment by calvinzhou-rockx** [comment]
> Thank you for the delivery @calvinzhou-rockx. We will look into it as soon as possible.

@alxs  There was an error in auto-check as the PR link was not provided, so I put it here: https://github.com/w3f/Open-Grants-Program/pull/190, thanks

**Comment by Noc2** [comment]
@calvinzhou-rockx  Thanks again for submitting the PR. I quickly started to look into your delivery [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stone-index-on-substrate_1_Noc2.md). However, I couldn’t find the documentation, a testing guide or an article as well as the UI. Could provide links to these deliverables and also update this PR accordingly. Thanks!

**Comment by calvinzhou-rockx** [comment]
Hi @Noc2 , thanks for the input, and we realized there were some miscommunications here and we have some internal issues on the UI side, we have to delay the deliverables of UI and Tutorials for some days, appreciate your understanding

**Comment by Noc2** [comment]
@calvinzhou-rockx  Thanks for the update. Please ping me here, once you are ready.

**Comment by Noc2** [comment]
Hi @calvinzhou-rockx. I just wanted to ask you about your current status. Any updates here?

**Comment by calvinzhou-rockx** [comment]
> Hi @calvinzhou-rockx. I just wanted to ask you about your current status. Any updates here?

Hi @Noc2 , thanks for checking but we're still working on the UI part

**Comment by calvinzhou-rockx** [comment]
@Noc2 I submitted a PR in your evaluation form 2 days ago, but it might be the wrong channel, can you advise what to do for the new deliverables for your evaluation? Thanks

**Comment by Noc2** [comment]
@calvinzhou-rockx Where did you submit the PR? Could you provide a link? There is no other PR open from you to this repo. But usually it’s better to just update this PR.

**Comment by calvinzhou-rockx** [comment]
Hi @Noc2 , sorry, I realised the previous PR was raised to the evaluation form which was wrong
I updated this PR and please take a look, thanks

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for updating the PR. I will take another look at it, but you still don’t list all the deliverables of your contract: https://github.com/w3f/Grants-Program/blob/master/applications/stone-index-on-substrate.md#milestone-1----liquid-staked-dot-token and the license links for example point to a completely different repo: https://github.com/gbctech/starks-node or a page which is no longer available: https://github.com/gbctech/starks-node/blob/master/frame/distaff-vm/LICENSE. It would be nice if you could update this.

**Comment by Noc2** [comment]
I also just updated the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stone-index-on-substrate_1_Noc2.md). Feel free to take another look at it. The UI currently doesn’t work for me.

**Comment by calvinzhou-rockx** [comment]
> I also just updated the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stone-index-on-substrate_1_Noc2.md). Feel free to take another look at it. The UI currently doesn’t work for me.

Hi @Noc2 , did you run the https://github.com/stonedefi/stoneindex-node in your ENV? 

For the license, I already updated both to Apache v2, thanks

**Comment by Noc2** [comment]
@calvinzhou-rockx Yes, with `cargo run -- --dev` according to the [readme](https://github.com/stonedefi/stone-index-substrate-ui/blob/master/README.md). Otherwise the console error would also complain about the failed websocket connection and not “cannot construct unknown type Asset”

**Comment by calvinzhou-rockx** [comment]
> @calvinzhou-rockx Yes, with `cargo run -- --dev` according to the [readme](https://github.com/stonedefi/stone-index-substrate-ui/blob/master/README.md). Otherwise the console error would also complain about the failed websocket connection and not “cannot construct unknown type Asset”

Hi @Noc2, sorry that was due to the wrong instruction in the README of UI 
We corrected the instruction already to build the substrate node in your local env.
Alternatively, you can also use the docker image created by my teammate for your convenience, note that the docker account is a temp account under him(RaphaelYu)
Thanks

**Comment by Noc2** [comment]
@calvinzhou-rockx Thanks for the response. Based on it, I found the issue and opened a [PR to your repo](https://github.com/stonedefi/stone-index-substrate-ui/pull/1). Now I’m able to run the front-end and connect it to the node. However, I’m unable to buy an index after I created one according to [your tutorial](https://github.com/stonedefi/stone-index-substrate-ui/blob/master/tutorial/Tutorial.md#user-to-buy-a-new-index). The balance continues to show 0 (even if the UI shows it was successful), but the browser console shows the following error: “ {"ApplyExtrinsic":1}: system.ExtrinsicFailed:: [{"Module":{"index":9,"error":1}},{"weight":100010000,"class":"Normal","paysFee":"Yes"}]”.

When I try to buy the same index via polkadot.js/apps. I get the following error message: “stoneIndex.InsufficientAssetBalance”.

**Comment by Noc2** [comment]
> Thanks for updating the PR. I will take another look at it, but you still don’t list all the deliverables of your contract: https://github.com/w3f/Grants-Program/blob/master/applications/stone-index-on-substrate.md#milestone-1----liquid-staked-dot-token and the license links for example point to a completely different repo: https://github.com/gbctech/starks-node or a page which is no longer available: https://github.com/gbctech/starks-node/blob/master/frame/distaff-vm/LICENSE. It would be nice if you could update this.

Also could you still update the delivery documentation?

**Comment by calvinzhou-rockx** [comment]
> @calvinzhou-rockx Thanks for the response. Based on it, I found the issue and opened a [PR to your repo](https://github.com/stonedefi/stone-index-substrate-ui/pull/1). Now I’m able to run the front-end and connect it to the node. However, I’m unable to buy an index after I created one according to [your tutorial](https://github.com/stonedefi/stone-index-substrate-ui/blob/master/tutorial/Tutorial.md#user-to-buy-a-new-index). The balance continues to show 0 (even if the UI shows it was successful), but the browser console shows the following error: “ {"ApplyExtrinsic":1}: system.ExtrinsicFailed:: [{"Module":{"index":9,"error":1}},{"weight":100010000,"class":"Normal","paysFee":"Yes"}]”.
> 
> When I try to buy the same index via polkadot.js/apps. I get the following error message: “stoneIndex.InsufficientAssetBalance”.

@Noc2 thanks for that and the PR has been approved and merged 

For the InsufficientAssetBalance error, there was a bug in the initial balance script and fixed, please try again, thanks!

**Comment by calvinzhou-rockx** [comment]
> > Thanks for updating the PR. I will take another look at it, but you still don’t list all the deliverables of your contract: https://github.com/w3f/Grants-Program/blob/master/applications/stone-index-on-substrate.md#milestone-1----liquid-staked-dot-token and the license links for example point to a completely different repo: https://github.com/gbctech/starks-node or a page which is no longer available: https://github.com/gbctech/starks-node/blob/master/frame/distaff-vm/LICENSE. It would be nice if you could update this.
> 
> Also could you still update the delivery documentation?

OK, I misunderstood the question previously, and now the license file is fixed

**Comment by Noc2** [comment]
Thanks for the update. But now you link to the license file of the milestone delivery repo and not your actual repository that contains the code. Obviously our delivery repository contains an apache license. Also your table still doesn’t list all of the deliveries in your contract: https://github.com/w3f/Grants-Program/blob/master/applications/stone-index-on-substrate.md#milestone-1----liquid-staked-dot-token Furthermore it would be nice if you could try to resolve all the warnings of the frontend and add a few tests. Additionally the UI let’s you update the index, but there doesn’t seem to be any on-chain logic for actually updating the index: 
https://github.com/stonedefi/stoneindex-node/blob/master/pallets/stone-index/src/lib.rs  How is this implemented?

Also it seems you reused Logan Saether’s code, which is published under the  GPL-3.0 License, without any attribution. That’s something we usually take really seriously and is reason for us to terminate the grant. Could you please comment on this? 

- https://github.com/stonedefi/stoneindex-node/blob/bca42fb9eb1a6fe2dc1706bd1a0f91e528aa9bb7/pallets/swaps/src/lib.rs 
- https://github.com/lsaether/pallet-swaps/blob/45a65a1488250581e861175a8d7370ea6e11fa38/src/lib.rs

**Comment by calvinzhou-rockx** [comment]
@Noc2 thanks for the reminder, the code is meant for demo purpose only and we're working on this urgently to split out these piece of code from the main project
Will keep you posted on those items

**Comment by calvinzhou-rockx** [comment]
> Thanks for the update. But now you link to the license file of the milestone delivery repo and not your actual repository that contains the code. Obviously our delivery repository contains an apache license. Also your table still doesn’t list all of the deliveries in your contract: https://github.com/w3f/Grants-Program/blob/master/applications/stone-index-on-substrate.md#milestone-1----liquid-staked-dot-token Furthermore it would be nice if you could try to resolve all the warnings of the frontend and add a few tests. Additionally the UI let’s you update the index, but there doesn’t seem to be any on-chain logic for actually updating the index:
> https://github.com/stonedefi/stoneindex-node/blob/master/pallets/stone-index/src/lib.rs How is this implemented?
> 
> Also it seems you reused Logan Saether’s code, which is published under the GPL-3.0 License, without any attribution. That’s something we usually take really seriously and is reason for us to terminate the grant. Could you please comment on this?
> 
> * https://github.com/stonedefi/stoneindex-node/blob/bca42fb9eb1a6fe2dc1706bd1a0f91e528aa9bb7/pallets/swaps/src/lib.rs
> * https://github.com/lsaether/pallet-swaps/blob/45a65a1488250581e861175a8d7370ea6e11fa38/src/lib.rs

Hi @Noc2 , sorry for dragging this long, the team was working hard to patch those items you pointed out plus more testing and documents, the other major change is the substrate v3 upgrade, that my teammate did a through code refactor, and here are a summary for those changes:
* The demo app is completely taken out in a separate repo: https://github.com/stonedefi/stone-index-swaps-integration-demo.  This resolves the concern of license conflicts and make the project code much more clear
* The substrate index code is now on substrate v3 
* Resolved most of the warning in UI code and added certain unit test code
* Update the license link
* The UI code is also updated with bug fixes and enhancement 
* Added all missing documents in deliverables table

Please take a look and let me know if anything, there will be another medium article posted by our marketing guy once we reach the final stage of this grant program, hence it's not in the table yet  

Thanks

**Comment by mmagician** [comment]
@calvinzhou-rockx Thanks for posting an update. I will review it hopefully in the coming days.

**Comment by mmagician** [comment]
I've done my share of the evaluation to follow up on @Noc2's. Please find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/66425cec38b7f17f7b0a88c62ab3b194cf41ce5e/evaluations/stone-index-on-substrate_1_mmagician.md), there are still a few outstanding issues. Let me know once you've addressed these please.

**Comment by calvinzhou-rockx** [comment]
@mmagician Thanks for the input, and please allow us sometime to get back to you

**Comment by calvinzhou-rockx** [comment]
> I've done my share of the evaluation to follow up on @Noc2's. Please find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/66425cec38b7f17f7b0a88c62ab3b194cf41ce5e/evaluations/stone-index-on-substrate_1_mmagician.md), there are still a few outstanding issues. Let me know once you've addressed these please.

Hi @mmagician , my teammates already fixed the #1 and #3 and submitted, please check again 

For #2, looks like the demo link in [evaluation form](https://github.com/w3f/Grant-Milestone-Delivery/blob/66425cec38b7f17f7b0a88c62ab3b194cf41ce5e/evaluations/stone-index-on-substrate_1_mmagician.md) was outdated, and should be [stone-index-swaps-integration-demo](https://github.com/stonedefi/stone-index-swaps-integration-demo)

It's a bit tricky about #2 that we have spent quite some time to discuss , also want to check with you:

- This code is something we demo how will it can integrate with stone index in code level only and not functional, which brings the key point here: 
- Remember when we submit the [proposal](https://github.com/w3f/Grants-Program/pull/190), you asked us to reduce the module to 1, and 1 milestone only. So we didn't have sufficient budget to complete a production ready product within this first milestone. Please advise on this 

Thanks

**Comment by mmagician** [comment]
@calvinzhou-rockx If you read our discussion carefully, you will see that I have asked about the [integration of an existing DEX](https://github.com/w3f/Grants-Program/pull/190#issuecomment-764740807), rather than developing your own module:
> Rather than building your own DEX module, perhaps you could utilise one of the existing ones? 

Which is exactly what you agreed on and included in your list of deliverables.

I'm not asking you to deliver production ready code here. But there's a big difference between showcasing that the functional integration of the DEX module works (basically an MVP) and production ready code. 

Regarding my second point:
> How will you run your application in production? Currently you cannot use your fork of substrate-node-template since it doesn't contain the DEX. Do you have a separate repo somewhere where you're hosting both your stone-index pallet as well as the DEX integration within one runtime?

Again I am not asking for a ready app, but rather for you to provide a path for moving forward and to see how you want to architect your project.

**Comment by mmagician** [comment]
@calvinzhou-rockx This milestone evaluation has been going on for more than 3 months now and we've encountered numerous issues as commented above. Normally we would already terminate your Grant as per our [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md#10--term-and-termination) due to failure to meet the timeline, but we agreed to give you time until the end of the week to resolve the outstanding issues and deliver the grant in full.

**Comment by calvinzhou-rockx** [comment]
> @calvinzhou-rockx This milestone evaluation has been going on for more than 3 months now and we've encountered numerous issues as commented above. Normally we would already terminate your Grant as per our [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md#10--term-and-termination) due to failure to meet the timeline, but we agreed to give you time until the end of the week to resolve the outstanding issues and deliver the grant in full.

Hi @mmagician , sorry for the late response, we had multiple discussions and code works committed into the [DEX bridge repo](https://github.com/stonedefi/stone-index-swaps-integration-demo), allow us some time to wrap up the document, and I'll update you here later, thanks

**Comment by calvinzhou-rockx** [comment]
> > @calvinzhou-rockx This milestone evaluation has been going on for more than 3 months now and we've encountered numerous issues as commented above. Normally we would already terminate your Grant as per our [Terms and Conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T&Cs.md#10--term-and-termination) due to failure to meet the timeline, but we agreed to give you time until the end of the week to resolve the outstanding issues and deliver the grant in full.
> 
> Hi @mmagician , sorry for the late response, we had multiple discussions and code works committed into the [DEX bridge repo](https://github.com/stonedefi/stone-index-swaps-integration-demo), allow us some time to wrap up the document, and I'll update you here later, thanks

@mmagician The document is updated in the repo (README.md)[https://github.com/stonedefi/stone-index-swaps-integration-demo/blob/master/README.md], please take a look. This is to address your first point and your concern is valid, to solve the above issue, we created this bridge pallet to bridge stone-index with [Pallet-swap](https://github.com/stonedefi/pallet-swaps)

Regarding to your 2nd point:
>> How will you run your application in production? Currently you cannot use your fork of substrate-node-template since it >> doesn't contain the DEX. Do you have a separate repo somewhere where you're hosting both your stone-index pallet as >> well as the DEX integration within one runtime?
With DEX bridge runtime, the stone-index can integrate with Pallet-swap functions listed in the doc.
So it is more production ready within the proposed Grant program from stone-index perspective. 
Please let us know if you have any further question, and we are here to ensure the grant program can complete by this week, thanks!

**Pull request merged**
