### PR TITLE
Calamar milestone 3 delivery

### PR DESCRIPTION
**Pull request by uiii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1163

### CODE REVIEW

**Comment by uiii** [comment]
Hi guys, I understand you might have too much work these days, but may I ask you when I can expect the evaluation?

**Comment by semuelle** [comment]
Hey @uiii, sorry for the wait. I'll discuss this with @PieWol, who wanted to do the evaluation. I think this would still be the best option as most of the grants team is ooo for the holidays, but I'll get back to you with more info asap.

**Comment by PieWol** [comment]
Hey @uiii ,
here is the link to my external evaluation [PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1090). I have two aspects that hinder this delivery for approval. Looking forward to your response to the issues I raised.

**Comment by uiii** [comment]
Hi @PieWol, merry Christmas and thanks for the evaluation, here is my response to the issues:

1) Show related runtime metadata in item's detail

I agree that metadata docs in spec 100001 is not so helpful, but parsing it and linking to the relevant sources it out of the scope of the current milestone. We just display what is present in the spec's metadata. As you can see, the `polkadot-js` documentation shows the same: https://polkadot.js.org/docs/polkadot/extrinsics#balances

image

We can improve it in the future, but right know I don't have a strightforward solution.

2) building and testing output

Critical vulnerabilities are in `webpack` and `@babel/travers` package, there are the transitive dependencies of `react-scripts` and we use the latest version.

3) trying to run locally with "npm start" as given in the readme

I cannot reproduce the error. I tried Windows cmd and also WSL. Which OS do you use? Try to update to the latest NodeJs version (LTS 20.x).

**Comment by PieWol** [comment]
Hey @uiii, I have been busy for the holidays. 

regarding 3. I'm using node v21.2.0 on Mac with ARM. I will try the latest LTS version as you suggested and get back to you. 
For the metadata issue I would like to wait for feedback by @semuelle . 

Hope you had a wonderful Christmas.

**Comment by uiii** [comment]
Hi @PieWol,
you can also try the docker option, it should work on every platform.

Thanks, enjoy Christmas too.

**Comment by PieWol** [comment]
hey @uiii ,
I managed to get it working by removing the package lock and reinstalling all packages again. To profit from the standardization I used the docker image for testing. All 174 tests passed.

```
% npm run test                          

> calamar@0.1.0 test
> playwright test


Running 174 tests using 1 worker
  174 passed (4.3m)
```

Furthermore I thought about the metadata issue I complained about. Given that you are supporting so many networks I get it, that it's not in the scope of this grant to individually care for any metadata deviation. 

With the tests passing and the metadata issue being outside of the scope of this grant, I see this as accepted.

**Review by semuelle — APPROVED** [review]
Hey @uiii. I have verified the evaluation. I didn't have any issues with testing locally. I also noticed that the Polkadot data is a couple of days old, but I assume you have good reasons to fix this asap. One minor issue I would suggest to change is to make the tooltip when hovering over the extrinsic name clickable also. I kept clicking the text, not realizing that the icon is clickable only. Also, linking to a search of the extrinsic name from the extrinsic name isn't quite intuitive. 

In any case, your milestone is hereby accepted (see evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/calamar_m3_PieWol.md)). Congrats on completing the grant and best of luck going forward!

**Comment by uiii** [comment]
Thank you, the invoice is sent.

**Comment by RouvenP** [comment]
hi @uiii we just sent the payment

**Pull request merged**
