### PR TITLE
Add validated_streams-milestone_1.md

### PR DESCRIPTION
**Pull request by bojidar-bg**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1437 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @bojidar-bg someone will take a look at it shortly.

**Comment by bojidar-bg** [comment]
@semuelle Well... curious, it worked on my machine XD Fixed, the path in the docker-compose file was wrong. It is possible that you either did not tag the docker image correctly or had an older version of docker-compose installed, since it never tried rebuilding the image on our end; but in either case, just running the script without having an image built beforehand ought to be enough now. :smiley: Sorry for the hassle!

**Comment by semuelle** [comment]
You are probably right, my docker-compose version is quite old. 
No problem at all. I'll pick this up on Monday.

**Review by semuelle — APPROVED** [review]
Hey @bojidar-bg. Thanks for the help. I am happy to report that your milestone is approved. Great job, [no notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/validated-streams_1_semuelle.md). :)

I have forwarded your invoice for processing.

**Comment by bojidar-bg** [comment]
Aw! Thanks! :blush: Glad to know there weren't any blockers on the M1 delivery; we shall start working on M2 now! (:

Feel free to ping me if you need anything in the interim (:

**Comment by RouvenP** [comment]
hi @bojidar-bg we transferred the payment today.

**Pull request merged**
