### PR TITLE
Add Faucet bot milestone delivery.

### PR DESCRIPTION
**Pull request by StringNick**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1758

### CODE REVIEW

**Comment by Whisker17** [comment]
Hey @StringNick! I will make an external evaluation later, just create a draft PR #942 now. I will ping you when I finish it.

**Comment by Whisker17** [comment]
Hi @StringNick , I've looked briefly at your documentation and it seems to be missing the `test`, `variables`, and `environments` sections you've labeled, is there something missing from the documentation?

**Comment by Whisker17** [comment]
`docker-compose -up -d` should be `docker-compose up -d`

**Comment by StringNick** [comment]
@Whisker17 
> Hi @StringNick , I've looked briefly at your documentation and it seems to be missing the `test`, `variables`, and `environments` sections you've mentioned, is there something missing from the documentation?

yes I loose commit I suppose, sorry. I will fix testing section, variables seciton is available, I will recheck links.
> docker-compose -up -d should be docker-compose up -d
Will fix it too.

**Comment by StringNick** [comment]
@Whisker17 Hi, I hope I fix everything, If u have any question how to add matrix/discord bot credentials write it.

**Comment by Whisker17** [comment]
Hey @StringNick, thanks for your update, I just had a test for your docker-compose and found something wrong with the bot.
image
You can see from this screenshot, the bot panics because of the refusion of connecting to the substrate node.

**Comment by StringNick** [comment]
@Whisker17, I faced this problem today, its because substrate start-up time is too long, u need wait when substrate fully started and than start a bot, I can write it in README

**Comment by StringNick** [comment]
> > @Whisker17, I faced this problem today, its because substrate start-up time is too long, u need wait when substrate fully started and than start a bot, I can write it in README
> 
> What do you mean _fully started_? Blocks fully synchronized? I just tried to run the bot compiled locally, and the substrate was also syncing blocks, but still panic. image

If it's screenshot from local, I saw address ws://substrate:9944, it's used only in docker compose, I can record a video guide, if I trying locally change address in config.toml

**Comment by Whisker17** [comment]
Oh @StringNick that will be awesome! Appreciate your work, btw, could you also add some guides for the faucet guides of discord and matrix, thank you!

**Comment by StringNick** [comment]
I wrote it in header, for discord many guides with video, just create a bot, generate token, add bot to channel.
For matrix is more easy, create an account, using for example this link `https://app.element.io/#/register`, invite this account to channel where u want receive drip, provide credentials to `config.toml` (login/password).
Video of start-up docker-compose demo with request drip through matrix: `https://drive.google.com/file/d/1GvGX4HkIEtjziAam_xP8pZh6A2o1yI_f/view?usp=sharing`

**Comment by Whisker17** [comment]
Hey @StringNick , just have a try and the substrate node works well, but the bot service still can't work, it panics all the time.
image

**Comment by StringNick** [comment]
In ur logs he can't connect, maybe it's something with ur docker network? Can u ping substrate in docker container (from redis service for example) or telnet it in container, because it's strange

**Comment by Whisker17** [comment]
seems nothing wrong with the connection between redis and substrate node.
image

**Comment by Whisker17** [comment]
> 

my discord username is `xcwh1sker`, feel free to leave msg.

**Comment by keeganquigley** [comment]
Thanks @StringNick for the delivery and @Whisker17 for the evaluation. Still looking it over but in the meantime, can you update the [license file](https://github.com/StringNick/sybil-resistant-chat-bot-substrate-faucet/blob/main/LICENSE#L189) to replace boilerplate with your copyright date and owner name? Thanks!

**Comment by keeganquigley** [comment]
@StringNick your [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/faucet_bot_whisker.md) has been passed and I was able to reproduce the results. I agree the docs could be a bit better as they are sparse and I had to fumble around with getting the go modules installed and getting Docker compose file to work. Once the license file change is implemented I will merge the milestone.

Overall great job!

**Comment by StringNick** [comment]
@Whisker17 @keeganquigley Thank you for reviewing, I pushed updated license.
I will try to create a new milestone where I will improve docs, add e2e tests (its a little bit harder than unit here) and add new platforms.

**Comment by keeganquigley** [comment]
Thanks @StringNick congrats on completing the grant. I will forward your invoice for processing.

**Comment by keeganquigley** [comment]
@StringNick Actually I am not seeing the W3F VAT ID on your invoice. Can you update the invoice to include it and resubmit? If you need it you can find it here: https://web3.foundation/legal-disclosures/

Thanks!

**Comment by StringNick** [comment]
@keeganquigley VAT ID is Tax number I wrote it, check in bottom of invoice

**Comment by keeganquigley** [comment]
Hi @StringNick I'm not sure what you mean, as the tax number shown is not the same as the VAT no. that is listed [here](https://web3.foundation/legal-disclosures/). It should match the one that starts with "CHE"

Please check again, thank you.

**Comment by StringNick** [comment]
> Hi @StringNick I'm not sure what you mean, as the tax number shown is not the same as the VAT no. that is listed [here](https://web3.foundation/legal-disclosures/). It should match the one that starts with "CHE"
> 
> Please check again, thank you.

yes I named it wrong, vat number in Serbia is just 9 numbers, CHE is only for Switzerland? (code country is only in EU?)

**Comment by keeganquigley** [comment]
@StringNick okay thanks good to know for Serbia. However, the Web3 Foundation VAT ID should also be present, which starts with CHE. You can include this below the Serbia one.

**Comment by StringNick** [comment]
> @StringNick okay thanks good to know for Serbia. However, the Web3 Foundation VAT ID should also be present, which starts with CHE. You can include this below the Serbia one.

Sorry we have misunderstanding, I fixed invoice and sent it

**Comment by keeganquigley** [comment]
Thanks @StringNick much appreciated. I have forwarded the new invoice for processing.

**Pull request merged**
