### PR TITLE
KSM-embeddable-tip-or-donate-button

### PR DESCRIPTION
**Pull request by edisinovcic**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by aleixosk** [comment]
Hey, I will be reviewing this over the weekend.

**Comment by aleixosk** [comment]
Many thanks for your patience and for the delivery of both milestones. I've submitted an evaluation of the two [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/84).

Special kudos for the UI work, the widget looks slick.

**Comment by Noc2** [comment]
Sorry for the late reply. Your milestone is officially accepted and I will forward the invoice internally. You can find the accepted milestone evaluation by @aleixosk [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/84).

**Comment by RouvenP** [comment]
hi @edisinovcic we just sent a test transaction. Could you please confirm if received?

**Comment by edisinovcic** [comment]
> hi @edisinovcic we just sent a test transaction. Could you please confirm if received?

Yes, it's been received.

**Comment by edisinovcic** [comment]
@RouvenP you can proceed with the rest when ready.

**Comment by edisinovcic** [comment]
@RouvenP let me know when you will be ready to send a transaction. :)

**Comment by RouvenP** [comment]
hi @edisinovcic apologies for the delay - the transaction should go through today. will let you know as soon as done.

**Comment by RouvenP** [comment]
@edisinovcic we sent the remainder.

**Comment by edisinovcic** [comment]
> @edisinovcic we sent the remainder.

I see it as receiving. Tnx

**Pull request merged**
