### PR TITLE
Slothunter milestone 2

### PR DESCRIPTION
**Pull request by AurevoirXavier**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1531 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@AurevoirXavier thank you for the milestone delivery. It worked very well. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/slothunter_2_dsm-w3f.md) for details. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by fededubbi** [comment]
Hi @AurevoirXavier,

I noticed that our name on the invoice is incorrect.
Our correct name is:

Web 3.0 Technologies Stiftung.
Could you please update and resend?

Many thanks,
Federica

**Comment by AurevoirXavier** [comment]
> Hi @AurevoirXavier,
> 
> I noticed that our name on the invoice is incorrect. Our correct name is:
> 
> Web 3.0 Technologies Stiftung. Could you please update and resend?
> 
> Many thanks, Federica

Stiftung or Foundation?

**Comment by fededubbi** [comment]
Hi @AurevoirXavier,

Both work.

Many thanks,
Federica

**Pull request merged**
