### PR TITLE
Sirato Substrate phase 3 milestone 1 delivery

### PR DESCRIPTION
**Pull request by conor10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1608

### CODE REVIEW

**Comment by Ali-Usama** [comment]
Thank you for the delivery, @conor10 . However, I'm facing some issues during testing:
1. I was unable to install dependencies using `npm`:

```
$ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-json-view@1.21.3
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!   peer react@">= 16.8.5" from @datepicker-react/hooks@2.8.4
npm ERR!   node_modules/@datepicker-react/hooks
npm ERR!     @datepicker-react/hooks@"^2.8.4" from @datepicker-react/styled@2.8.4
npm ERR!     node_modules/@datepicker-react/styled
npm ERR!       @datepicker-react/styled@"^2.8.4" from the root project
npm ERR!   20 more (@datepicker-react/styled, @headlessui/react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
npm ERR! node_modules/react-json-view
npm ERR!   react-json-view@"latest" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0 || ^16.3.0 || ^15.5.4" from react-json-view@1.21.3
npm ERR!   node_modules/react-json-view
npm ERR!     react-json-view@"latest" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

2. While testing through `yarn`, some of the test suites were failing:
```
$ yarn test

Test Suites: 43 failed, 25 passed, 68 total
Tests:       98 passed, 98 total
Snapshots:   0 total
Time:        37.113 s
Ran all test suites.
```
Can you please look into these? 
Thanks

**Comment by abhijeetbhagat** [comment]
@Ali-Usama can you please try `npm i --force` instead to force install the deps?

**Comment by keeganquigley** [comment]
Hi @conor10 @abhijeetbhagat could you also please add the name of copyright owner & date into the bottom of the [license file](https://github.com/web3labs/epirus-substrate/blob/main/LICENSE#L189)? Thanks!

**Comment by abhijeetbhagat** [comment]
@keeganquigley done!

**Comment by keeganquigley** [comment]
Thanks @abhijeetbhagat looks good. The milestone is hereby accepted. Here is the final [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/894), which was done by an external evaluator. Congrats on completing the grant!

**Comment by semuelle** [comment]
Hey @conor10 & @abhijeetbhagat, your grant application lists an Ethereum address and no currency for payment, but your invoice contains only bank details. You have to either [amend the grant agreement and send us an email](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#name-of-your-project) with your bank details, or send a new invoice. Thanks!

**Comment by conor10** [comment]
I've amended the agreement via the following [PR](https://github.com/w3f/Grants-Program/pull/1828).

The payment details for fiat are on the invoice that was submitted previously. This is the same format as what we provided for previous payments.

**Pull request merged**
