### PR TITLE
dotmog milestone 3

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is being made by the same account as the accepted application. 
- [X] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by darkfriend77** [comment]
Hey @Noc2 ,
will add the license file and commit the wallet example and update the readme file.

**Comment by darkfriend77** [comment]
Okay,
 - added reference to other examples in SubstrateNetApi
 - added License information to Unity3DExample
 - added wallet example https://github.com/dotmog/SubstrateUnityWalletSimple

**Comment by Noc2** [comment]
@darkfriend77 Thanks for fixing everything. The milestone is a pass. I will forward your invoice internally and let me know once I should take another look at your milestone 2 submission: https://github.com/w3f/Grant-Milestone-Delivery/pull/161

**Comment by RouvenP** [comment]
hi @darkfriend77 we transferred the payment for M3 today.

**Pull request merged**
