### PR TITLE
Create inkscope-fuzzer-2.md

### PR DESCRIPTION
**Pull request by feliam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2155

### CODE REVIEW

**Comment by dsm-w3f** [comment]
Hi, we'll evaluate this milestone delivery.

**Comment by dsm-w3f** [comment]
@feliam Thank you for the milestone delivery. The first version of the evaluation is available in [this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/1181). Please take a look and provide proper answers and fixes. After that, let me know to continue this evaluation.

**Comment by 0xLucca** [comment]
@dsm-w3f Hey! Thanks for the feedback, we have left some comments in your PR. 

We have addressed all the issues mentioned in your evaluation and implemented the necessary fixes in the following branch: [m2-review-fixes](https://github.com/inkscopexyz/inkscope-fuzzer/tree/m2-review-fixes).

We will wait for your review before merging these changes and creating a new release.

**Comment by dsm-w3f** [comment]
[@0xLucca](https://github.com/0xLucca) thank you for the answers and fixes. Some problems were fixed and others remain. Please take a look at the [evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1181) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by dsm-w3f** [comment]
@0xLucca thank you for the improvements and fixes. I updated the evaluation document and the milestone is approved from my side. Great job! The W3F should review the evaluation soon.

**Comment by 0xLucca** [comment]
@dsm-w3f Thanks! We really appreciate the positive feedback. Looking forward to the W3F's review.

**Comment by 0xLucca** [comment]
@keeganquigley Thanks for the support throughout this project. We're grateful for the opportunity.
@dsm-w3f  Thank you as well for taking the time to thoroughly evaluate our work. It helped us improve the deliverable.

The team has worked hard on this, and we're excited to build upon this foundation moving forward. Thanks again to both of you!

**Comment by RouvenP** [comment]
hi @feliam we sent the payment last Friday

**Pull request merged**
