### PR TITLE
Social Recovery Wallet - Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by n13**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1001](https://github.com/w3f/Grants-Program/pull/1001)
```https://github.com/w3f/Grants-Program/pull/1001```

### CODE REVIEW

**Comment by takahser** [comment]
@n13 thanks for your delivery, I'll take a look at it soon.

**Comment by takahser** [comment]
@n13 thanks, I was successfully able to test your scenario and recover the account using a 2/3 guardian majority.

I only have two points:
1. After initiating the recovery and opening the app using the guarded account I noticed the popup indicating that somebody started the recovery process with the option, to abort it, which is nice. However, when I closed the app and re-opened it, I didn't see any indication anymore. Is there any way to stop the recovery process after ignoring the initial popup?
2. Typo in the _Recover Account_ screen: "You account" instead of "Your account":


I'll have a look at the code next and be back with more feedback soon.

**Comment by n13** [comment]
1. The popup happens whenever the user refreshes their balance 

There is probably better ways to do this 

2. Noted will fix

**Review by takahser — CHANGES_REQUESTED** [review]
@n13 could you investigate the issue with the disappearing popup when one's account is being recovered? See my previous [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/602#issuecomment-1287057043) any the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_2_takahser.md).

> There is probably better ways to do this

Are you planning to do something about this? Were you able to reproduce the issue?

Also, feel free to look at my comments regarding the [automated testing](https://github.com/w3f/Grant-Milestone-Delivery/blob/2df2d9ab05d062c97683a01bdf7b187e3fdd483d/evaluations/social-recovery-wallet_2_takahser.md#testing-feedback).

**Comment by n13** [comment]
> @n13 could you investigate the issue with the disappearing popup when one's account is being recovered? See my previous [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/602#issuecomment-1287057043) any the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_2_takahser.md).
> 
> > There is probably better ways to do this
> 
> Are you planning to do something about this? Were you able to reproduce the issue?
> 
> Also, feel free to look at my comments regarding the [automated testing](https://github.com/w3f/Grant-Milestone-Delivery/blob/2df2d9ab05d062c97683a01bdf7b187e3fdd483d/evaluations/social-recovery-wallet_2_takahser.md#testing-feedback).
> 
> Apart from that, your delivery looks fine. 👍 Also, I took a look at your code, nothing to complain there:)

Yes, I will fix it. 

I was able to reproduce the bug as follows

- lost account logs in, sees huge dialog. 
- Dialog has only one button - there's no way to dismiss this dialog except to close the recovery 
- If user does not dismiss the dialog but instead quit the app - which legitimately can always happen, power out, who knows - and then reloads the app, the dialog does not show!
- If the user then refreshes balance manually - pulling down for refresh on the token card - then the dialog shows again

This is surprising, but that's why it's a bug ;) 

The idea was whenever we fetch balance, we also check for the recovery. 

For testing - docker does a lot of caching and the output looks different based on what was cached. 

I did a clean run - somehow all caches were gone, I think because I uninstalled Docker and reinstalled it - and the log was very long. 

Some of these tests shouldn't be in old, I will remove the old folder. 

Attaching the very end of the docker output

#24 0.661 This will generate a JSON format file containing all messages that 
#24 0.661 need to be translated.
#24 0.681 Running "flutter pub get" in hashed-wallet...                      23.1s
#24 36.69 00:00 +0: /home/user/hashed-wallet/test/time_remaining_timer_test.dart: test time remaining
#24 37.01 00:00 +1: /home/user/hashed-wallet/test/account_service_test.dart: Test loadAccounts saveAccounts
#24 37.03 00:00 +2: /home/user/hashed-wallet/test/account_service_test.dart: Test createAccount
#24 37.03 00:00 +3: /home/user/hashed-wallet/test/account_service_test.dart: Test getPrivateKeys, savePrivateKeys
#24 37.20 00:00 +4: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 45 should return 45
#24 37.21 00:00 +5: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 8, should return 8
#24 37.21 00:00 +6: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: "", should return "" 
#24 37.21 00:00 +7: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 69.9 should return 69.9
#24 37.22 00:00 +8: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 69, should return 69.
#24 37.22 00:00 +9: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 69.. should return 69.
#24 37.22 00:00 +10: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 458,4 should return 458.4
#24 37.22 00:00 +11: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 453,343,343.676, should return 453343343.676
#24 37.22 00:00 +12: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 453,343,343.676 should return 453343343.676 
#24 37.23 00:00 +13: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 453.343.343,676 should return 453343343.676 
#24 37.23 00:00 +14: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 46..474,38493.3627,384 should return 46474384933627.384 
#24 37.23 00:00 +15: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: "345,,,," , should return "345." 
#24 37.23 00:00 +16: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 8746..474,38493.3627,384 should return 8746474384933627.384
#24 37.23 00:00 +17: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 843.384, should return 843.384
#24 37.24 00:00 +18: /home/user/hashed-wallet/test/old/utils/user_input_number_formatter_test.dart: Input: 843.384. should return 843.384
#24 37.67 00:00 +19: /home/user/hashed-wallet/test/old/utils/mnemonic_test.dart: mnemonic decode mnemonic
#24 37.70 mnemonic: rival-dance-tuition-mask-advance
#24 37.70 secret: 05b831ec4da04725af7e5b577c531260cdf6dc4282ada2ec75a3582bc844f720
#24 37.70 secret2: 05b831ec4da04725af7e5b577c531260cdf6dc4282ada2ec75a3582bc844f720
#24 37.70 00:01 +20: /home/user/hashed-wallet/test/old/utils/mnemonic_test.dart: Seeds Global Passport Mnemonic Convert words from Seeds Global Passport
#24 37.85 00:01 +21: /home/user/hashed-wallet/test/old/utils/mnemonic_test.dart: Seeds Global Passport Mnemonic Convert words from Seeds Global Passport
#24 38.08 00:01 +22: All tests passed!

**Comment by n13** [comment]
Delivered build 7 with recovery popup fixed (see video)

Made a code change to make sure we always check for recovery whenever we check for balance. 

That was the original intention but not what the code was doing. 

Tested on simulator and device.

https://user-images.githubusercontent.com/65412/197348173-55dccd09-4024-420c-846d-1692cacf5522.mov

2. Also fixed the typo.

**Review by takahser — APPROVED** [review]
@n13 thanks for fixing the bugs and the test output.
It looks good now, I accepted your delivery. You can see my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_2_takahser.md).

**Comment by n13** [comment]
Thanks for the approval! 

I will take the comments into account. 

1. Ideally all links inside the above table should include the commit hash, which was used for testing the delivery. 
2. It should also be checked if the software is published under the correct open-source license. There should be a link to the GH LICENCE file. (i.e. https://github.com/hypha-dao/hashed-wallet/blob/main/LICENSE )

**Comment by RouvenP** [comment]
hi @n13 we transferred the payment today.

**Pull request merged**
