### PR TITLE
add Universaldot.me M1 eval

### PR DESCRIPTION
**Pull request by shierve**
Added evaluation of [Milestone 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/560) for Universaldot.me

### CODE REVIEW

**Comment by JosephKnecht-lab** [comment]
Thank you @shierve for the evaluation. We like your attention to detail and some of the suggestions. Below you can find my response to your comments. 

> **0a. License**
> We have updated the missing information in the license.https://github.com/UniversalDot/front-end/blob/develop/LICENSE.md 
> 
> **0b. Documentation**
> We have fixed the typos. 
> We have added links on the homepage of the docs page. https://github.com/UniversalDot/udot-wiki/pull/11 
> Thank you for the suggestions. 
> We have left some sections empty because some parts of the front-end are still moving, so the documentation for them will change. 
> The empty sections are there to remind us what we have to include in the final release. 
> 
> **0c. Testing guide**
> I have created a story to check the issue with the failing test. https://github.com/UniversalDot/universal-dot-node/pull/88#issuecomment-1241871216 
> 
> **0d. Docker**
> Can you pull and run the latest development image from our docker hub? I have tested that it works on Mac M1.
> `docker pull universaldot/node:develop`
> And run the image with:
>  `docker run -it --rm -p 9944:9944 universaldot/node:develop`
> 
> **2. Tensorflow Integration**
> Currently, the front-end only makes a request and receives a response from tensorlfow serving instance which was the initial plan for the integration. I like the idea for having integration test for this, so I will add it as a task to be implemented. Thank you
> https://github.com/UniversalDot/front-end/issues/24  
> **4. IPFS design document**
> Yes. You are correct. We will NOT integrate with IPFS through a pallet but rather only store CID inside substrate.

**Comment by shierve** [comment]
Hi @JosephKnecht-lab , sorry for the delay.
I tested the docker image and this one is working properly. 
About the failing test, I see that the fix was merged but it seems I get a different fail now. See if you can resolve it and I will give the thumbs up.

```bash
warning: function `create_organisation` is never used
  --> pallets/task/src/benchmarking.rs:68:4
   |
68 | fn create_organisation<T: Config>() -> T::Hash 
   |    ^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `pallet-task` (lib test) generated 1 warning
    Finished test [unoptimized + debuginfo] target(s) in 6.12s
     Running unittests src/lib.rs (/Users/shierve/Code/W3F/universal-dot-node/target/debug/deps/pallet_task-106f07073db5e1b0)

running 47 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::assign_task_to_current_owner ... ok
test tests::block_time_is_added_when_task_is_updated ... ok
test tests::check_balance_after_update_task ... ok
test tests::balance_check_after_task_deletion ... ok
test tests::accepted_task_is_added_to_completed_task_for_volunteer ... ok
test tests::check_balance_after_complete_task ... ok
test tests::decrease_task_count_when_accepting_task ... ok
test tests::create_new_task ... ok
test tests::completing_tasks_assigns_new_current_owner ... ok
test tests::feedback_is_given_when_task_is_rejected ... ok
test tests::fund_transfer_on_create_task ... ok
test tests::increase_profile_reputation_when_task_completed ... ok
test tests::increase_task_count_when_creating_task ... ok
test tests::increase_task_count_when_creating_two_tasks ... ok
test tests::only_add_reputation_when_task_has_been_accepted ... ok
test tests::only_started_task_can_be_completed ... ok
test tests::only_creator_accepts_task ... ok
test tests::start_tasks_assigns_new_current_owner ... ok
test tests::start_tasks_assigns_task_to_volunteer ... ok
test tests::task_can_be_removed_by_owner ... ok
test tests::task_can_be_removed_only_when_status_is_created ... ok
test tests::task_can_be_rejected_by_creator ... ok
test tests::task_can_be_updated_after_it_is_created ... ok
test tests::task_can_be_updated_only_by_one_who_created_it ... ok
test tests::task_can_be_updated_only_after_it_has_been_created ... ok
test tests::task_can_only_be_finished_by_the_user_who_started_it ... ok
test tests::task_can_only_be_started_once ... ok
test tests::tasks_are_moved_to_expiry ... ok
test tests::test_create_insufficient_funds_to_reserve ... ok
test tests::test_create_two_tasks_insufficient_balance ... ok
test tests::test_multiple_tasks_and_reserve_amounts ... ok
test tests::delete_task_after_deadline ... ok
test tests::cant_own_more_tasks_than_max_tasks ... ok
test tests::dying_tasks_are_removed_after_grace_period ... ok
test tests::test_update_insufficient_funds_to_reserve ... ok
test benchmarking::benchmark_tests::test_benchmarks ... FAILED
test tests::the_volunteer_is_different_from_task_creator ... ok
test tests::update_task_updates_block_expiry_with_different_deadline ... ok
test tests::verify_inputs_outputs_to_tasks ... ok
test tests::when_task_is_accepted_ownership_is_cleared ... ok
test tests::volunteer_gets_paid_on_task_completion ... ok
test tests::tasks_are_moved_to_dying_after_expiry ... ok
test tests::test_expired_task_revival_status ... ok
test tests::test_only_initiator_can_revive ... ok
test tests::test_revival_swaps_task_from_dying_to_expired ... ok
test tests::test_revive_task_with_invalid_new_deadline ... ok

failures:

---- benchmarking::benchmark_tests::test_benchmarks stdout ----
failing benchmark tests:
revive_task: "NoPermissionToRevive"
thread 'benchmarking::benchmark_tests::test_benchmarks' panicked at 'assertion failed: !anything_failed', pallets/task/src/benchmarking.rs:340:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    benchmarking::benchmark_tests::test_benchmarks

test result: FAILED. 46 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s

error: test failed, to rerun pass '--lib'
```

**Comment by JosephKnecht-lab** [comment]
> I tested the docker image and this one is working properly.

Great! 
> About the failing test, I see that the fix was merged but it seems I get a different fail now. See if you can resolve it and I will give the thumbs up.

Yes. We are working towards the second milestone already. We have fixed the failing test. To ensure that we don't miss failing benchmark tests, we have added benchmarking tests to our CI pipeline. https://github.com/UniversalDot/universal-dot-node/pull/98 

@shierve Thank you again for the evaluation. We are also looking for beta users that would be interested and improving the usability of the app. If you are interested, let's connect.

**Comment by shierve** [comment]
thanks @JosephKnecht-lab, the tests are passing for me now.
I updated the status to accepted. You could also consider creating a separate branch for each milestone containing the working code for the evaluation, this way you wouldn't need to worry about breaking things working towards the next milestone.

**Comment by shierve** [comment]
@alxs I've followed the same naming as the proposals themselves. It seems like the first proposal was under universaldot-me with '-'. And so the name of my evaluation is different. But I could name it universaldot.me#2_1_shierve.md if you prefer? I added a Kusama address to the file.

**Comment by alxs** [comment]
Thanks. Yes, I think that would be clearer.

**Comment by shierve** [comment]
@alxs done

**Comment by RouvenP** [comment]
hi @JosephKnecht-lab we transferred the KSM

**Comment by JosephKnecht-lab** [comment]
I think the KSM was meant for @shierve.

**Comment by Noc2** [comment]
@shierve Just to confirm, we pinged the wrong person here. You should have received the KSM.

**Pull request merged**
