### PR TITLE
Deliver DelightfulDOT M2

### PR DESCRIPTION
**Pull request by sinzii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1907

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @sinzii ,
glad to see the delivery come in :)
I see that you have used zombienet tests but in the testing guide those tests are not described or shown how those can be run. Please add those details to your testing guide.

**Comment by sinzii** [comment]
Hi @PieWol, thank you for taking a look!

For the zombienet tests, we're currently running & verifying the tests via GH Actions, and you can verify the test status here on [GH Workflow](https://github.com/dedotdev/dedot/actions/workflows/zombienet-tests.yml) & [workflow setup](https://github.com/dedotdev/dedot/blob/main/.github/workflows/zombienet-tests.yml).

If you're interested in verifying the tests on local devices, I've justed pushed a `Dockerfile` to help running the tests locally. Please pull the latest commit on branch [w3f-delivery/m2](https://github.com/dedotdev/dedot/tree/w3f-delivery/m2) and run the following command:
```shell
 docker build -t dedot-zombienet --progress=plain --platform linux/amd64 --file=./zombienet-tests/Dockerfile --target=test .
```

Please notes that it might take a while for it to download all the necessary executables before running the tests. If you're on a good internet connection it would not take too long.

Let me know how it goes when you run the test. Thanks!

**Comment by PieWol** [comment]
Hey @sinzii ,
thank you very much for the addition of the dockerfile. All tests worked 👍.

Please have a look at my evalution [here ](https://github.com/w3f/Grant-Milestone-Delivery/pull/1153/files?short_path=48743a0#diff-48743a02ad33b71bc8c66c981512f3bb9f690eb7e0f01e3d4742645aa628b743). The only thing thats I couldn't find right now is the migration guide from polkadot/api to dedot. Please provide a link for this too. 

Otherwise well done 🎉

**Comment by sinzii** [comment]
@PieWol My bad for missing that part. I've just pushed the [migration guide](https://github.com/dedotdev/dedot/tree/w3f-delivery/m2?tab=readme-ov-file#migration-from-polkadotapi-to-dedot), and included it in delivery PR.

Let me know if you have any other questions!

**Comment by PieWol** [comment]
Awesome, thanks for the quick response. I have updated my evaluation and once a team member has reviewed it this milestone will be accepted 🎉 @sinzii

**Review by semuelle — APPROVED** [review]
The evaluation (https://github.com/w3f/Grant-Milestone-Delivery/pull/1153) is merged, your milestone is accepted, @sinzii. Congrats.

**Comment by RouvenP** [comment]
hi @sinzii we just sent the payment

**Comment by sinzii** [comment]
Awesome, thank you @PieWol & @semuelle for your reviews of the delivery & thank you @RouvenP, we've received the fund!

**Pull request merged**
