### PR TITLE
Fair Squares m-1 delivery

### PR DESCRIPTION
**Pull request by ilhanu**
FS Milestone Delivery filled in template

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/971

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the delivery and sorry for the late reply. Could you already take a look at https://github.com/w3f/Grant-Milestone-Delivery/pull/494, but Lucas is also taking a look at your delivery.

**Comment by ilhanu** [comment]
We are on the changes requested, great job reviewing it!

**Comment by ilhanu** [comment]
@diogosmendonca thank you for your thorough review.

- The typos, missing words and clarification have been adjusted in the tutorial and the article docs.
- Regarding the roles pallet, just allowing one role per account is set because we don't know yet the effects of allowing multiple roles on the usage of the application. Currently allowing one role per account simplifies the usage and isolates an issue to just one account.  We definitely want to achieve this in the future, but it needs more testing and uncover the potential conflicts of interest. So in a further stage of our project we can trial this and exhaust the possibilities of conflicts of roles and interests with other users.. This is not a part of the planned milestones. 
- The approval of a role by yourself is expected at this point we have specified this in [milestone-1 scope](https://github.com/w3f/Grants-Program/blob/master/applications/fair_squares.md#milestone-1--implement-module-roles-fund-and-role-verifiers). In the future this should be the the housing-council call to bring in other role verfier in the system. Right now it uses the sudo-key as expected.
- The `has_withdrawn` boolean is a parameter that will used when the housing-fund selects investors for a specific asset. It will be assigned a weight in [milestone-3](https://github.com/w3f/Grants-Program/blob/master/applications/fair_squares.md#milestone-3---bidding-mechanism), as a sign of loyalty to the fund. It will allow users who have been loyal to be higher ranked with respect to the other rules of the selection algorithm. When you withdraw all your funds it will still report true. 
- The testing strategy was only set on the pallets we have created for this milestone. We won't be testing the node software or the runtime. Please also see the comments by @lucasvanmol in the [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fair-squares_1_lucasvanmol.md#general-notes). We tried to maintain coverage above 70% even though this was not mentioned in our grant proposal. The housing-fund lib.rs has close to 92% coverage and the lib.rs of the roles-pallet has 73%.  We are also using tarpaulin in github actions the reports end-up in [Codecov.io](https://app.codecov.io/gh/Fair-Squares/fair-squares)
  - We did write additional parts of a test cover fully the has_withdrawn test, to increase the coverage. But the coverage test is failing now as we had already advanced in the main repo, and the testing/code coverage is [failing](https://github.com/Fair-Squares/fair-squares/pull/93)  as we had removed the share storage for the housing_fund. Hope this is ok, otherwise we have to merge the main repo into `m1*` branch

@lucasvanmol thanks for your encouraging words, we have added inline comments to the `Event` enum.

## changes

[m1 (tag) to branch m1-evaluation](https://github.com/Fair-Squares/fair-squares/compare/m1...m1-evaluation?expand=1)



Looking forward to your further feedback or approval.

**Comment by diogosmendonca** [comment]
@ilhanu 
 - Typos ok, just when you edited the first one you added the "the" two times.
 - Question regarding one role per user, ok.
 - Approval by yourself, ok for now, in the future will be a council.
 - has_withdraw, ok.
 - Coverage being ok is a matter of requirements. As far as I know, in the [Milestone Delivery Guideline](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md) there is no specification for minimum coverage for automated unit tests. In this way, the tests presented meets the requirement and are ok. However, is well known that untested parts of software represent a high risk of having defects. In the roles pallet, there are some error paths and the block that creates the role Service uncovered by unit tests. This probably is not a risk for this milestone but please consider improving unit test coverage before delivering a production version of the software since blockchain projects that operate funds are critical software.

**Comment by ilhanu** [comment]
@diogosmendonca 

Agreed on the criticalness of the software, we have a slow and safe pathway defined for the node software and operations. Our first and foremost goal is achieve results with experimentation and trials. 

We have seen projects defining their own coverage percentage ranging from 50-80% and teams not specifying the coverage at all. We have internally agreed on 70% of the pallet code should be covered with unit-tests.

**Comment by ilhanu** [comment]
@lucasvanmol 

We just ran `cargo clippt --fix` very useful.  Tests, checks and builds are still successful. the commit is to be found [here](https://github.com/Fair-Squares/fair-squares/pull/93/commits/22caf6be53c26d94b0ed603a1d6ee958df773d61). We have excluded the `node/src` changes, just accepted our own pallets for now. 

After running the above command it still gives 4 warnings about `warning: methods called new usually return Self` in the `structs.rs` file. We will have to look deeper into this. 

We will add this to future milestones and/or github actions workflow. Thanks!

**Comment by RouvenP** [comment]
hi @ilhanu we transferred the payment today. Thanks!

**Comment by ilhanu** [comment]
@RouvenP Thanks it was distributed among the team-members!

**Pull request merged**
