### PR TITLE
ink! analyzer milestone 4 (#1615)

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1615 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@davidsemakula thank you for the milestone delivery and @Ali-Usama thanks for the external evaluation. The delivery looks good to me. I tested the IDE plugin and seem pretty good. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by davidsemakula** [comment]
@RouvenP just checking in since it's about 2 weeks now 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula I forgot to notify you - we already [transferred the KSM](https://kusama.subscan.io/account/Eexv1mKLiCidz2gGh6vfowtXgSSc7mvD4xEb2ji998W4DPs?tab=transfer). Thanks for following up

**Comment by davidsemakula** [comment]
Hi @RouvenP
I think there's some confusion 🙂 - I believe the KSM would be for the [external evaluator](https://github.com/w3f/Grant-Milestone-Delivery/pull/958). 
I'm the grantee, so I'm inquiring about the payment for the delivered milestone NOT the external evaluation 🙂.
Thanks!

**Comment by RouvenP** [comment]
Of course, apologies for the confusion - let me check with my team and I'll get back to you asap!

**Comment by RouvenP** [comment]
Hi @davidsemakula we just transferred the payment. Apologies for the delay!

**Comment by davidsemakula** [comment]
Hi @RouvenP .. no problem!🙂 I've received the payment, thanks!

**Pull request merged**
