### PR TITLE
DIA Bridgestate Milestone 1

### PR DESCRIPTION
**Pull request by kaythxbye**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1611 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @kaythxbye someone will look at it shortly. In the meantime, none of the provided links are working. Can you check the broken links and update them? Thanks!

**Comment by kaythxbye** [comment]
@keeganquigley Thanks for the update! The links lead to a private repo (which after the whole project is done will be public of course). We will add the relevant reviewers to the repo, can you provide us with their github handles so that we can add their accounts?

**Comment by keeganquigley** [comment]
Thanks @kaythxbye you can go ahead and add me as I will do the evaluation. Thanks!

**Comment by keeganquigley** [comment]
Thanks @kaythxbye much appreciated. Please note the issues below:

1. Your license file currently contains the default template text for copyright year and owner. Can you please fix this?

2. Currently the unit tests are failing with the following error:
```rust
cargo +nightly clippy
    Updating crates.io index
error: failed to get `frame-support` as a dependency of package `pallet-collateral-reader v0.1.0 (/Users/keeganquigley/bridgestate-ocw)`

Caused by:
  failed to load source for dependency `frame-support`

Caused by:
  Unable to update /Users/keeganquigley/support

Caused by:
  failed to read `/Users/keeganquigley/support/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

3. When running the command `git clone git@github.com:nnn-gif/substrate-node.git` I get a permission denied (publickey) error:
```rust
Cloning into 'substrate-node'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I can clone it normally with `git clone https://github.com/nnn-gif/substrate-node.git` but cargo test still generates dependency errors:
```rust
cargo test
error: failed to load manifest for workspace member `/Users/keeganquigley/substrate-node/bin/node-template/node`

Caused by:
  failed to load manifest for dependency `frame-benchmarking`

Caused by:
  failed to load manifest for dependency `frame-support`

Caused by:
  failed to load manifest for dependency `sp-api`

Caused by:
  failed to load manifest for dependency `sp-core`

Caused by:
  failed to load manifest for dependency `sp-runtime-interface`

Caused by:
  failed to load manifest for dependency `sp-io`

Caused by:
  failed to load manifest for dependency `sp-state-machine`

Caused by:
  failed to load manifest for dependency `sp-trie`

Caused by:
  failed to load manifest for dependency `sp-runtime`

Caused by:
  failed to load manifest for dependency `substrate-test-runtime-client`

Caused by:
  failed to load manifest for dependency `sc-block-builder`

Caused by:
  failed to load manifest for dependency `sc-client-api`

Caused by:
  failed to load manifest for dependency `sc-executor`

Caused by:
  failed to load manifest for dependency `substrate-test-runtime`

Caused by:
  failed to load manifest for dependency `pallet-babe`

Caused by:
  failed to load manifest for dependency `frame-election-provider-support`

Caused by:
  failed to load manifest for dependency `sp-npos-elections`

Caused by:
  failed to load manifest for dependency `substrate-test-utils`

Caused by:
  failed to load manifest for dependency `sc-service`

Caused by:
  failed to load manifest for dependency `sc-client-db`

Caused by:
  failed to load manifest for dependency `kitchensink-runtime`

Caused by:
  failed to load manifest for dependency `pallet-collateral-reader`

Caused by:
  failed to read `/Users/keeganquigley/substrate-node/frame/collateral-reader/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I tried with both macbook`stable-aarch64-apple-darwin (default)
rustc 1.69.0 (84c898d65 2023-04-16)` as well as Ubuntu 20.04 `stable-x86_64-unknown-linux-gnu (default)
rustc 1.69.0 (84c898d65 2023-04-16)`toolchains. Should I be using an older version?

4. `https://github.com/nnn-gif/substrate-node.git` is a fork of entire `substrate` instead of just the substrate-node-template repo. Is there a reason you didn't use the sample node template? Or a Docker image to quickly spin up the node and test the pallet with Polkadot-JS is also fine.

5. Can you also tell me which repos are specific to the grant?

**Comment by kaythxbye** [comment]
Hi @keeganquigley thanks for the feedback. We have compiled a list of answers that should hopefully help you:

Re 1.): We will fix the license file shortly, thank you for pointing it out

Re 2,3.) Once you have taken the clone from https://github.com/nnn-gif/substrate-node.git, run `git submodule update --init --recursive`
and run `cargo test` from `substrate-node/frame/collateral-reader` directory

Re 4.) The repository github.com:nnn-gif/substrate-node/ contains the example for running the pallet

Re 5.) The repo for this grant delivery is https://github.com/diadata-org/bridgestate-ocw, which contains only off-pallet code

**Comment by weakpasscode** [comment]
@keeganquigley It should run on MacBook  Apple ARM64 chip,

Run it from substrate-node

````
 substrate-node git:(master) ✗ cargo run -- --dev 
````

can you check the rust toolchain version, 

output of rustup show


````
  substrate-node git:(master) ✗ rustup show                                                                                                                                       
Default host: aarch64-apple-darwin
rustup home:  /Users/nnn/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2021-11-04-aarch64-apple-darwin
nightly-2022-11-02-aarch64-apple-darwin
nightly-2022-11-15-aarch64-apple-darwin
nightly-2022-12-15-aarch64-apple-darwin
nightly-2023-03-14-aarch64-apple-darwin
nightly-2023-04-03-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-2023-04-03-aarch64-apple-darwin (default)
rustc 1.70.0-nightly (3a8a131e9 2023-04-02)


````


For docker build, I was getting same error exit code: 137,  I cleared some space in my system which fixed that.

**Comment by nnn-gif** [comment]
@keeganquigley It should run on MacBook  Apple ARM64 chip,

Run it from substrate-node

````
 substrate-node git:(master) ✗ cargo run -- --dev 
````

can you check the rust toolchain version, 

output of rustup show


````
  substrate-node git:(master) ✗ rustup show                                                                                                                                       
Default host: aarch64-apple-darwin
rustup home:  /Users/nnn/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2021-11-04-aarch64-apple-darwin
nightly-2022-11-02-aarch64-apple-darwin
nightly-2022-11-15-aarch64-apple-darwin
nightly-2022-12-15-aarch64-apple-darwin
nightly-2023-03-14-aarch64-apple-darwin
nightly-2023-04-03-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-2023-04-03-aarch64-apple-darwin (default)
rustc 1.70.0-nightly (3a8a131e9 2023-04-02)


````


For docker build, I was getting same error exit code: 137,  I cleared some space in my system which fixed that.

**Comment by keeganquigley** [comment]
Thanks for the tip @nnn-gif I tried switching to that exact toolchain.I'm running it from `substrate-node` as you are showing, but still no luck. Now it gives me this:
```rust
error: failed to run custom build command for `node-template-runtime v4.0.0-dev (/Users/keeganquigley/substrate-node/bin/node-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/keeganquigley/substrate-node/target/release/build/node-template-runtime-4236d63b597cd1e1/build-script-build` (exit status: 1)
  --- stderr
  Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/var/folders/6_/b7tdvp0d6h779ktj0h92w5km0000gn/T/.tmpjZAv2N)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed
    = help: consider downloading the target with `rustup target add wasm32-unknown-unknown`
    = help: consider building the standard library from source with `cargo build -Zbuild-std`

  error: cannot find macro `println` in this scope
   --> src/main.rs:3:5
    |
  3 |                 println!("{}", env!("RUSTC_VERSION"));
    |                 ^^^^^^^

  error: requires `sized` lang_item

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test` (bin "wasm-test") due to 3 previous errors
  ------------------------------------------------------------
```

**Comment by nnn-gif** [comment]
can you share output of this command

rustup show

**Comment by keeganquigley** [comment]
Yep here it is:
```rust
Default host: aarch64-apple-darwin
rustup home:  /Users/keeganquigley/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-02-20-aarch64-apple-darwin
nightly-2022-03-14-aarch64-apple-darwin
nightly-2022-06-20-aarch64-apple-darwin
nightly-2022-06-30-aarch64-apple-darwin
nightly-2022-08-30-aarch64-apple-darwin
nightly-2022-09-08-aarch64-apple-darwin
nightly-2023-04-03-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

active toolchain
----------------

nightly-2023-04-03-aarch64-apple-darwin (default)
rustc 1.70.0-nightly (3a8a131e9 2023-04-02)
```
Although now I'm realizing that it is doing this with the current `substrate-node-template` as well.

**Comment by nnn-gif** [comment]
why these are missing in your rustup show


installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

**Comment by keeganquigley** [comment]
Thanks for your help @nnn-gif I do have that when I use the `+nightly` tag:
```rust
Default host: aarch64-apple-darwin
rustup home:  /Users/keeganquigley/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin
nightly-2022-02-20-aarch64-apple-darwin
nightly-2022-03-14-aarch64-apple-darwin
nightly-2022-06-20-aarch64-apple-darwin
nightly-2022-06-30-aarch64-apple-darwin
nightly-2022-08-30-aarch64-apple-darwin
nightly-2022-09-08-aarch64-apple-darwin
nightly-2023-04-03-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

nightly-aarch64-apple-darwin (overridden by +toolchain on the command line)
rustc 1.72.0-nightly (498553fc0 2023-05-29)
```
However it appears that this issue is on Parity's side and not on your own, and I'm currently working on filing an issue, so I'm willing to bypass it for this milestone. The pallet code and tests look good, therefore the milestone is accepted, and you can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/bridgestate_1_keeganquigley.md). Note my comments regarding Docker and the unused variable warnings.

To proceed in merging the milestone, please see my latest comments in the private DIA Matrix chat.

**Comment by keeganquigley** [comment]
Thanks again @nnn-gif I have hereby accepted the milestone. I will forward your invoice internally for processing.

**Comment by fededubbi** [comment]
Hi @nnn-gif,

I noticed that you inserted 2 different addresses in the application.
Which one is the correct one?

0xC13233bd20a7FcB1d7c2394AdE4857b778382264
0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48

Many thanks,
Federica

**Comment by kaythxbye** [comment]
Hi Federica,

0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 is the ERC20 token address of USDC, so please DO NOT send any funds to this address. Rather use this as the payment token.
Please send the funds to this address: 0xC13233bd20a7FcB1d7c2394AdE4857b778382264
Can you make a test transaction with a small amount first for us to confirm?

Best
Samuel

**Comment by fededubbi** [comment]
Hi @kaythxbye,

Sure i can do that.
Let me know once received.

Many thanks,
Federica

**Comment by kaythxbye** [comment]
Hi @fededubbi can you share the transaction ID of the test transaction?
Thank you!

**Comment by fededubbi** [comment]
Hi @kaythxbye,

When it will be processed i will send it to you.
That would be early next week.

Many thanks,
Federica

**Comment by keeganquigley** [comment]
@kaythxbye USDC could actually be sent to either address, but 0xC13233bd20a7FcB1d7c2394AdE4857b778382264 is the one that matches the application :)

**Comment by RouvenP** [comment]
hi @kaythxbye we just sent a test transaction: [0xC13233bd20a7FcB1d7c2394AdE4857b778382264](https://etherscan.io/address/0xC13233bd20a7FcB1d7c2394AdE4857b778382264) - could you kindly confirm whether you received it? Thanks

**Comment by fededubbi** [comment]
Hi @kaythxbye, can you please confirm you received the test transaction?

Many thanks,
Federica

**Comment by RouvenP** [comment]
hi @kaythxbye following up here. Could you confirm receipt of the test transaction?

**Comment by kaythxbye** [comment]
@RouvenP sorry for the delay, will check it and come back here.

**Comment by kaythxbye** [comment]
@RouvenP @fededubbi Just got confirmation that it was well received, we can proceed with the process :-)

**Comment by RouvenP** [comment]
thanks for getting back to us @kaythxbye. We just transferred the payment

**Pull request merged**
