### PR TITLE
cryptex milestone 2

### PR DESCRIPTION
**Pull request by driemworks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1660

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@driemworks thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_2_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by driemworks** [comment]
@dsm-w3f thanks for the quick feedback! I've resolved all the issues in the evaluation document. To summarize:

- Docker: Only substrate is dockerized. The SDK can be used as either a typescript lib (wasm build) or module (rust), so there's nothing to run in a container with that alone. Similarly, the typescript wrapper (etf.js) has no docker image either. You can find both packages in npm [here](https://www.npmjs.com/search?q=%40ideallabs). I can add a dockerfile for the `etf.js/examples` if you'd like.

- Substrate Issues: [resolved](https://github.com/ideal-lab5/substrate/commit/1c69a092b6409081a7af4131b555a02f2776d54a)

- ETF-SDK: 
    1. [cleaned up test imports/params](https://github.com/ideal-lab5/etf-sdk/commit/2c606149eb3c5c9a1caaa6d3bdf698335cf278572)
    2. No need to deploy anything here. If you'd like to locally verify that the latest build works rather than relying on the [package in npm](https://www.npmjs.com/package/@ideallabs/etf-sdk) you can build from the api  directory with `wasm-pack build --target web`, then you just need to change the imports in etf.js [here](https://github.com/ideal-lab5/etf.js/blob/0c422055a4f3f7dc3bdb0ac4334fdaa39c1ca524/package.json#L11C10-L11C10).

- etf.js
    1. [fixed that test, a rounding issue](https://github.com/ideal-lab5/etf.js/commit/9bd6639f56323b08dfdf1ffd38b33e267b414632)
    2. I added a temporary fix to the example to get rid of the source map warning [here](https://github.com/ideal-lab5/etf.js/commit/0c422055a4f3f7dc3bdb0ac4334fdaa39c1ca524). We'll properly address that when we build out the 'real' use case in the next milestone.

**Comment by dsm-w3f** [comment]
@driemworks thank you for the answers and fixes. I tried again and I still have some doubts and problems. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_2_dsm-w3f.md). Let me know when I can continue the evaluation.

**Comment by driemworks** [comment]
- regarding benchmarks + tests in substrate: 
    - are you able to run `cargo test --package pallet-etf --features runtime-benchmarks`?
    - I'm not sure of the errors you're seeing, but I believe they're things that already exist within substrate. The pallet-timestamp and election-provider errors that are logged seem intentional (tests with error logs have named like `enters_emergency_phase_after_forcing_before_elect` and `on_new_session_doesnt_start_new_set_if_schedule_change_failed `). I'll look into those to verify. The errors logs in `correct_beefy_payload ` is unexpected, but we would not have impacted that and our fork is somewhat outdated at this point, so perhaps they'll be resolved when we sync with the latest (soon). 
- regarding etf.js:
    - you can also generate the dist folder by running `tsc` from the root dir
    - 😢 apologies about that test, it is resolved 100% now. 
    - *technically* the example does run everything locally, because it's running a smoldot light client in you browser. You can connect with a full node like [this](https://ideal-lab5.github.io/etf_js.html#full-node): run a full node locally, then change the example [here](https://github.com/ideal-lab5/etf.js/blob/8ccb6c2f1c12800065227118e542d645d12ecbdf/examples/src/App.js#L25) to pass the host and port and set the init flag to false. e.g. 
    ``` javascript
      const distanceBasedSlotScheduler = new DistanceBasedSlotScheduler();
      let api = new Etf(distanceBasedSlotScheduler, "0.0.0.0", 9944);
      await api.init(false);
    ```
    It's possible but I don't believe it's practical to run a bootnode locally and test with the smoldot light client because smoldot has some TLS requirements (when we attempted we received a `protocol not supported` over an insecure connection) but I can share logs or access to the hosted bootnode (in AWS) if desired.

**Comment by dsm-w3f** [comment]
@driemworks thank you for the improvements and fixes. I was able to test more parts locally but not all the system. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_2_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by driemworks** [comment]
> The smoldot fork is working, but I don't know how to add and run with local chain 127.0.0.1:9944

There are basically two ways to run everything:
1. run smoldot in the browser with a hosted bootnode
2. locally run a full node optionally connected to a hosted bootnode.
and of course if you're running a hosted bootnode, you can add both full and light client peers

The first way is what exists in the etf.js/examples app, which syncs with the etf0 bootnode. For the second approach, where you want to use a locally running node instead of a smoldot light client, you'd have to make the change like in my last comment (replace lines 25 and 26 [here ](https://github.com/ideal-lab5/etf.js/blob/8ccb6c2f1c12800065227118e542d645d12ecbdf/examples/src/App.js#L25)). You _won't_ be able to connect the smoldot client with a locally running full node I believe (correct me if wrong, but smoldot doesn't support insecure connections so it's possible but you'd need to set up a secure connection between local full node and smoldot). I attempted previously by updating the chainspec to point to a locally running bootnode but receive `protocol not supported` and the lc can't make a connection.

You could run the full node a couple of ways, either as its own validator on its own chain, starting at block zero, or else get the chainspec [here](https://raw.githubusercontent.com/ideal-lab5/etf.js/main/src/etfTestSpecRaw.json) to sync with the etf0 bootnode. If you connect with the light client right now it might take a minute or two to sync.

If you're available for a call we can probably clear everything up.

**Comment by dsm-w3f** [comment]
@driemworks thank you for the answer. I tried to test it again locally using Smoldot and didn't work, but as worked with the full node, I think maybe there is some detail that I'm missing. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_2_dsm-w3f.md) for details. I also noticed that the evaluation branch was not updated with some changes that I need to make to run the code, for example, the merge conflicts in the code. I expect that the user could just follow the instructions in the Readme files and run the application. Please make sure that the documentation and code incorporate the changes needed to allow that. There is no need for a meeting, the documentation should be enough to run the system.

Also pinging [@burdges](https://github.com/burdges), to see if he could take a look at the cryptography part of this milestone delivery since he was actively involved in the discussions of the [grant application](https://github.com/w3f/Grants-Program/pull/1660).

**Comment by driemworks** [comment]
> I started the smoldot using npm install; npm start in ./wasm-node/javascript.

You don't need to do this actually, etf.js starts the light client in the browser. You should be able to just pull the latest main branch and run the example following the readme. There was a problem with the event emitter's visibility that is resolved that was preventing the latest slot from being dispatched to the react app.  

I removed the /dist folder from git, since it should be built from the root directory anyway (using `tsc`).

**Comment by dsm-w3f** [comment]
@driemworks thank you for the answer. I tried and the main branch is more stable than the other one passed before. For now, I will wait for feedback of the research team regarding the cryptography part. This could take one or two weeks to complete.

**Comment by driemworks** [comment]
@dsm-w3f sounds good. I'm available via matrix as well (@driemworks:matrix.io) to provide any further context regarding the cryptography aspects of the codebase (which somewhat fall out of the scope of the testing docs we provided).

**Comment by burdges** [comment]
It sounds like you've a bigger vec than you'd like?  https://github.com/ideal-lab5/etf-sdk/blob/main/crypto/src/ibe/fullident.rs#L20

I've now forgotten exactly what you wanted to do, but assuming you wanted a threshold scheme, then you can have the user do Lagrange interpolation between the `g_id`s, no?

**Comment by driemworks** [comment]
Thanks! That seems much more optimal. Instead of performing IBE encryption ala FullIdent, we just perform this key exchange and don't need to store/transport the larger IBE ciphertexts. There is no MAC currently, it just ignores invalid keys right now. We'll plan to make both of these alterations in the next milestone.

**Comment by burdges** [comment]
You're almost still performing one "encryption" per upcoming block for the MACs, but they only require 16 bytes each.  It's the u[i] parts of the cyphertexts which take up 48 bytes each, so you need like `54 * n + f * (n-k)` bytes where `f` is the symmetric key field size.

It's likely fine if f is only 128 bits, because what would collision attacks achieve?  That's not a proof though, just a guess.

**Comment by driemworks** [comment]
> It's likely FullIdent contains a MAC of some sort, not sure. 

The decryption function uses the first param of the ciphertext to authenticate (checks if U == rP, in G2) so sort of a MAC, but it's 96 bytes per ciphertext and each ciphertext ends up being 160 bytes (using sha256), so it's larger than the above for n > 2 as long as k is large enough?

**Comment by dsm-w3f** [comment]
@driemworks thank you for the answers and @burdges thanks for the review. I agree that these optimizations can be handled later. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Pull request merged**
