### PR TITLE
Create ScoutCoinFabrik-2.md

### PR DESCRIPTION
**Pull request by valeriacaracciolo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1666 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for delivery @valeriacaracciolo someone will take a look at it in the next few days.

**Comment by valeriacaracciolo** [comment]
Awesome, thank you Keegan for your reply

Best,

**Comment by semuelle** [comment]
Hi @valeriacaracciolo, could you please have a look at the evaluation posted in [this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/914) and comment on (or fix) the issues addressed there?

**Comment by keeganquigley** [comment]
Thanks very much @valeriacaracciolo, your [external evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ScoutCoinFabrik_2_dastansam.md) has been accepted and therefore the milestone has been passed. Congrats on completing the grant. I agree that you've done some great research, the tool is nice to use, and you have very extensive docs and tests which will hopefully be of great help to devs when it comes to security.

**Comment by valeriacaracciolo** [comment]
Thank you Keegan and thanks to the entire Web3 grants team. Always a pleasure working with you guys 🫶We are cooking something new, so I hope to talk to you soon!Best,On Jul 12, 2023, at 2:14 AM, Keegan | W3F ***@***.***> wrote:﻿
Thanks very much @valeriacaracciolo, your external evaluation has been accepted and therefore the milestone has been passed. Congrats on completing the grant. I agree that you've done some great research, the tool is nice to use, and you have very extensive docs and tests which will hopefully be of great help to devs when it comes to security.

**Pull request merged**
