### PR TITLE
Interstellar-Network-milestone_5

### PR DESCRIPTION
**Pull request by nashjl**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request:  https://github.com/w3f/Grants-Program/pull/1354

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @nashjl, thanks for the delivery. Someone of the team will take care of it asap.

**Comment by nashjl** [comment]
> Hi @nashjl, thanks for the delivery. Someone of the team will take care of it asap.

Hi @0xCaso thanks for your message. we stay tuned!

**Comment by semuelle** [comment]
Hi @nashjl. Thanks for your patience as I am working through all your documentation and code. I am currently working through your testing documentation, and when I try to run `cargo test` on the `api_circuits` project, and I am getting the following error. Is the API testing page not up-to-date, or am I missing something?

```sh
 cargo test
   Compiling lib-circuits-wrapper v0.1.0 (/xxx/interstellar/api_circuits/lib_circuits_wrapper)
error: failed to run custom build command for `lib-circuits-wrapper v0.1.0 (/xxx/interstellar/api_circuits/lib_circuits_wrapper)`

Caused by:
  process didn't exit successfully: `/xxx/interstellar/api_circuits/target/debug/build/lib-circuits-wrapper-55beffbfcb908ed8/build-script-build` (exit status: 101)

[...]

  --- stderr

  CMake Error at deps/lib_circuits/deps/abc.cmake:8 (find_library):
    Could not find ABC_LIBRARY using the following names: abc
  Call Stack (most recent call first):
    deps/lib_circuits/CMakeLists.txt:26 (include)
    CMakeLists.txt:12 (include)

  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.49/src/lib.rs:1104:5
```

**Comment by nathanprat** [comment]
Hello,

Ah sorry, I keep forgetting about the READMEs...
Those are indeed not kept up-to-date.

For `api_circuits`(and pretty much same with our other repos) you need some prerequisites. 
On the top of my head:
- C/C++ build essentials
- cmake
- ninja/make
- protobuf binaries
- IPFS server (docker is fine) [only to run the tests, not compiling but I guess that's your goal]

And `api_circuits` also requires two `.deb`. Which OS are you using?
Because if not Ubuntu/Debian then we may have an issue. [I could still recompile in another package as long as it supported by CMake]

You can check the CI's `yml` in `.github/workflows` for the 100% guaranteed working list. 

PS: why are you testing `api_garble`? This is not part of this milestone. It was replaced by `lib-garble-rs`.

**Comment by semuelle** [comment]
Hi @nashjl. Thanks for the info. I wanted to be thorough as this is your last milestone. Anyway, I got the node and the app in the M5 evaluation doc working. I am going to finish the evaluation tomorrow. I only noticed two things: first, the app crashes after every transaction (negligible) and second, I see a `Transaction done` toast in the emulator, but I don't see any events or balance changes on the node. I can't tell if it's because I entered the wrong code or something else. Any idea?

**Comment by nathanprat** [comment]
Great!

Yes, the UX is sub-par...
Technically, it is not (at least _should not_) be crashing. It is just calling `activity.finish()` after the correct number of inputs is entered and therefore the app closes.

Unfortunately, the `integritee-worker` and `node` blockchain are essentially separated, so you can not check the results using the front-end. The only option to check the TX result for now is the logs...
You should see a `TxPass` or `TxFail` in compose's logs.

**Comment by semuelle** [comment]
Hey @nathanprat. I did indeed find the transaction validation results in the logs. Thanks. Your milestone is hereby accepted; see evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/interstellar_5_semuelle.md#L17).

I have forwarded your invoice for processing. Congratulations on finishing the grant. Looking forward to your future developments!

**Comment by nashjl** [comment]
Thanks a lot @semuelle. We are eager to continue working on the project with the W3f Grant team !

**Comment by RouvenP** [comment]
hi @nashjl we transferred the payment today.

**Comment by nashjl** [comment]
> hi @nashjl we transferred the payment today.

Hi @RouvenP, we did not receive the payment. Could you please check on your side and let us know.
Thanks

**Comment by RouvenP** [comment]
hi @nashjl please see the transaction [here](https://etherscan.io/tx/0xa7cbd2494af14ea0161b5c0a46f2779ebcb0344dc3dac7428d99a277ad77e25d) - could you check again? Thanks!

**Comment by RouvenP** [comment]
hi @nashjl please see the transaction hash [here](https://etherscan.io/tx/0xa7cbd2494af14ea0161b5c0a46f2779ebcb0344dc3dac7428d99a277ad77e25d) - could you check again?

**Comment by nashjl** [comment]
Hi @RouvenP, thank you. We were expecting a fiat payment with a wire transfer to our bank account as you did for all the previous milestones.

**Comment by RouvenP** [comment]
hi @nashjl right, apologies, we missed that. Would you prefer receiving this payment in fiat as well or are you fine with ETH?

**Comment by nashjl** [comment]
Hi @RouvenP, I apologize for the delay in my response, as we mentioned earlier to the W3F, we are not using the address provided in the invoice. Therefore, we are currently in the process of setting up a company exchange account to facilitate the transfer of funds to fiat. We appreciate your understanding and kindly ask for your patience while we complete this process. We will keep you informed of any progress and expect the process to be completed as soon as possible.

If the process does not take too long, we would be happy to accept the ETH that was sent previously. However, if the process takes longer than expected, we would greatly appreciate it if we could revert the ETH transaction and receive the payment in fiat, as specified in the invoice.

**Comment by RouvenP** [comment]
hi @nashjl absolutely, that's fine. Please let us know once you know how you'd like to proceed.

**Comment by nashjl** [comment]
Hi @RouvenP we have received the funds on our exchange account!

**Pull request merged**
