### PR TITLE
Open Grant #268 Quadratic Funding Pallet Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by chrisli30**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by chrisli30** [comment]
Is the Github Action failure _Google Sheet Update_ normal? Is it my fault? 😢

**Comment by semuelle** [comment]
Hi Chris, thanks for the delivery. We will look into it as soon as possible.
The check is just for internal bookkeeping, nothing to worry about.

**Comment by chrisli30** [comment]
> Hi Chris, thanks for the delivery. We will look into it as soon as possible.
> The check is just for internal bookkeeping, nothing to worry about.

Okay, thanks Sebastian. If you need a quick answer, the best way is to ask in our Discord https://discord.gg/7W9UDvsbwh
Otherwise, I will respond here during PDT working hours.

**Comment by chrisli30** [comment]
@semuelle, did you get a chance to take a look at the delivery. Do you have any questions?

Below is the web UI being developed for the M2 delivery. I'm pasting it here to give you some visual idea of the app.
image

**Comment by semuelle** [comment]
Hi Chris, we have a bit of a backlog with regard to evaluations, so it might take another two or three days until someone gets to it.

**Comment by Noc2** [comment]
@chrisli30 Sorry for the late reply here. The UI looks really nice. I started to look into your delivery (see my initial [notes here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/quadratic-funding_1_Noc2.md)). In general it looks good, but I have few smaller comments: 

- It seems that currently everything is stored on-chain without a limit, see: https://github.com/OAK-Foundation/quadratic-funding-pallet/blob/bb2a5248bac7a8b6ef21e570f0942c0db40c8e6b/pallets/open-grant/src/lib.rs#L206. You could also consider changing the weights calculation for this, see for example: https://github.com/paritytech/substrate/blob/0bda86540d44b09da6f1ea6656f3f52d5447db81/frame/identity/src/lib.rs#L592 
- tic-funding-test repo has no license
- Why didn’t you use rust unit tests?
- Appeal doesn't seem to be [implemented](https://github.com/OAK-Foundation/quadratic-funding-pallet/blob/master/pallets/open-grant/src/lib.rs), which was mentioned in the original contract

**Comment by chrisli30** [comment]
David, thanks for taking a look! We have been addressing your feedback, but got a question here.

> * It seems that currently everything is stored on-chain without a limit
My understanding is that in order to be aligned with the weight format in identity pallet, we need to two things.
1. Benchmarking the functions in our pallet, and
2. Run the benchmark CLI to generate the weights.rs file and weight tags above each function

Is that correct?

> * tic-funding-test repo has no license
Fixed, added Apache 2.0. https://github.com/OAK-Foundation/quadratic-funding-test/commit/8ab2428a886c5c9423fb8eb6407c84f7715ba1e3

> * Why didn’t you use rust unit tests?
We wanted to do both dev and test in parallel so we can complete the milestones in 2 months time, so I made a decision to have our Javascript QA to write tests since he needs to get familiar with the RPC interface for web app development. Do you feel necessary to write unit tests in Rust? If yes, do you think if we can create a small open grant for it?

> * Appeal doesn't seem to be [implemented](https://github.com/OAK-Foundation/quadratic-funding-pallet/blob/master/pallets/open-grant/src/lib.rs), which was mentioned in the original contract
Yes, as we gave more thought about the functionalities during development, we changed the original plan a little. There turned out to be more functions than we planned, however the Appeal function got cut. Reason being that there are only two steps to which the public could appeal against, the grant selection before round start and the grant cancellation during a round. In both case, we decide that a project shouldn't slow down the whole round with appeals, and can always retry in the next round. Therefore, the flow is more smooth without the appeal. 

The original
image

The actual
image

**Comment by Noc2** [comment]
Thanks for the update. In general, the milestone is [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/quadratic-funding_1_Noc2.md) and I will forward your invoice internally. 

But It would be nice if you could move the delivery to a separate repo (rather than a fork), so that it's easier for others to follow your work and potentially to contribute to it. Regarding unit tests in Rust, I don’t think we would sign a new grant for this. It’s not mandatory to implement unit tests specifically in Rust, but in general it makes sense and you might want to consider doing this anyway for security reasons. Also it allows you to [test your benchmarks](https://github.com/paritytech/substrate/tree/master/frame/benchmarking#testing-benchmarks). Regarding weights, you probably should take a look at the following: https://www.youtube.com/watch?v=Qa6sTyUqgek as well as the [readme](https://github.com/paritytech/substrate/blob/master/frame/benchmarking/README.md) and the [knowledgebase](https://substrate.dev/docs/en/knowledgebase/runtime/benchmarking). But be aware of the following issue https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/771. It might be easier to initially just limit the upload size.

**Comment by chrisli30** [comment]
> Thanks for the update. In general, the milestone is [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/quadratic-funding_1_Noc2.md) and I will forward your invoice internally.
> 
> But It would be nice if you could move the delivery to a separate repo (rather than a fork), so that it's easier for others to follow your work and potentially to contribute to it. Regarding unit tests in Rust, I don’t think we would sign a new grant for this. It’s not mandatory to implement unit tests specifically in Rust, but in general it makes sense and you might want to consider doing this anyway for security reasons. Also it allows you to [test your benchmarks](https://github.com/paritytech/substrate/tree/master/frame/benchmarking#testing-benchmarks). Regarding weights, you probably should take a look at the following: https://www.youtube.com/watch?v=Qa6sTyUqgek as well as the [readme](https://github.com/paritytech/substrate/blob/master/frame/benchmarking/README.md) and the [knowledgebase](https://substrate.dev/docs/en/knowledgebase/runtime/benchmarking). But be aware of the following issue [substrate-developer-hub/substrate-developer-hub.github.io#771](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/771).

Awesome, thanks David @Noc2 for your time! We are almost done with the benchmarking. I will at you to take a look at the PR once submitted.

The announcement article has been proofread and passed. Is there anything else required before we publish it?

**Comment by fededubbi** [comment]
Good morning,

Could you please add the company address on the invoice?
You can send to this email address the updated invoice: invoices@web3.foundation.

Many thanks,
Regards,

Federica Dubbini

**Comment by Noc2** [comment]
> The announcement article has been proofread and passed. Is there anything else required before we publish it?

Best to double check with grantspr. It might make sense to coordinate the announcement.

**Comment by chrisli30** [comment]
> [invoices@web3.foundation](mailto:invoices@web3.foundation).

Federica,

I updated the invoice with address and sent it to invoices@web3.foundation. Please see if there's any other questions.

Thanks!

**Comment by chrisli30** [comment]
> > The announcement article has been proofread and passed. Is there anything else required before we publish it?
> 
> Best to double check with grantspr. It might make sense to coordinate the announcement.

Got it, David. Sure.

We've created another PR for the benchmarking. Could you take a look at this file and see if it's as expected?
https://github.com/OAK-Foundation/quadratic-funding-pallet/blob/92e624a8b85c920c10993177332d849942f0eab9/pallets/quadratic-funding/src/lib.rs#L245

The whole benchmarking PR is quite large, as shown here.
https://github.com/OAK-Foundation/quadratic-funding-pallet/pull/1

Many thanks!

**Pull request merged**
