### PR TITLE
Eiger Polkadot Native Storage: Milestone 1

### PR DESCRIPTION
**Pull request by dtuzi**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [ ] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1888 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@dtuzi thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Eiger_Storage_on_Polkadot_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by kylegranger** [comment]
@dsm-w3f @keeganquigley @dtuzi
Just adding a further clarification.  The changes pushed 30 Oct. to https://github.com/eigerco/polkadot-native-storage addressed these issues from `Evaluation V1`.
- Documentation
- Docker
- Testing
- Unit and integration testing
  - RPC testing
  - XCM testing
- Benchmark

The evaluation may continue.

**Comment by keeganquigley** [comment]
Thanks @dtuzi @kylegranger it's looking good now. All issues have been resolved, and you can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Eiger_Storage_on_Polkadot_1_dsm-w3f.md). Congrats and looking forward to seeing the next iteration! I also scheduled a call per our chat.

**Comment by keeganquigley** [comment]
It looks like some of the GH actions have failed due to a missing **Total Cost** section in the application, so I will post below.

Please fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform?usp=pp_url&entry.1070766548=https://github.com/w3f/Grant-Milestone-Delivery/pull/1032) in order to initiate the payment process. Thank you!

**Pull request merged**
