### PR TITLE
Haskell Web3 milestone 2

### PR DESCRIPTION
**Pull request by akru**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @akru. Thanks for the delivery of another milestone and sorry for the delay regarding your last delivery. I will look into both as soon as possible (definitely within the next few days).

**Comment by akru** [comment]
@Noc2 Thank you, David! No problem!

**Comment by Noc2** [comment]
I started with the evaluation, but I think the changing of the license file is causing some issues with the examples, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hs-web3_2_Noc2.md#general-notes). Could you take a look at it or tell me how I can easily resolve this?

**Comment by akru** [comment]
Ah, yes, thank you @Noc2 for the report, fixed in https://github.com/airalab/hs-web3/commit/ff38be7bd40ddd5315b1ffbe842bd87bad45f232,
I've just move `BSD3` license as default LICENSE file because it covers most of the code, Apache-2.0 license covers code tagged in source code headers license string, for example here: https://github.com/airalab/hs-web3/blob/master/src/Codec/Scale.hs#L6

**Comment by Noc2** [comment]
Sorry. Stack for some reason used some old files even though I checked out the latest version. I’m not used to haskell yet (although stack is actually quite similar to cargo). Btw. I couldn’t find the implementation for tuples.

**Comment by akru** [comment]
@Noc2 yes, stack is pretty close to cargo, and LTS in stack is pretty convenient.

Tuple instances implemented using templates here: https://github.com/airalab/hs-web3/blob/master/src/Codec/Scale/TH.hs#L24
Typles in Haskell are same as production type structures, we can use default generic instance.

**Comment by Noc2** [comment]
Thanks for pointing this out. I’m happy to tell you that the milestone is a pass and will forward the invoice.

**Pull request merged**
