### PR TITLE
Substrate MolochDAO v1 Delivery added

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @zhangjiannan. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @zhangjiannan, 
I am trying to test the Moloch DAO locally, but building fails with the following error. I'm guessing this is due to differing nightlies? Which rust toolchain version are you using?

```
error: The format for this attribute cannot be parsed. Correct format: `#[display(fmt = "...")]`
  --> /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/authorities.rs:37:4
   |
37 |     #[display("Invalid authority set, either empty or with an authority weight set to 0.")]
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: the method `to_string` exists for enum `authorities::Error<sp_blockchain::Error>`, but its trait bounds were not satisfied
    --> /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/environment.rs:1190:33
     |
1190 |         ).map_err(|e| Error::Safety(e.to_string()))?;
     |                                       ^^^^^^^^^ method cannot be called on `authorities::Error<sp_blockchain::Error>` due to unsatisfied trait bounds
     | 
    ::: /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/authorities.rs:36:1
     |
36   | pub enum Error<E> {
     | -----------------
     | |
     | method `to_string` not found for this
     | doesn't satisfy `_: std::fmt::Display`
     | doesn't satisfy `authorities::Error<sp_blockchain::Error>: ToString`
     |
     = note: the following trait bounds were not satisfied:
             `authorities::Error<sp_blockchain::Error>: std::fmt::Display`
             which is required by `authorities::Error<sp_blockchain::Error>: ToString`

error[E0599]: the method `to_string` exists for enum `authorities::Error<sp_blockchain::Error>`, but its trait bounds were not satisfied
   --> /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/import.rs:334:49
    |
334 |             ).map_err(|e| ConsensusError::ClientImport(e.to_string()))?;
    |                                                          ^^^^^^^^^ method cannot be called on `authorities::Error<sp_blockchain::Error>` due to unsatisfied trait bounds
    | 
   ::: /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/authorities.rs:36:1
    |
36  | pub enum Error<E> {
    | -----------------
    | |
    | method `to_string` not found for this
    | doesn't satisfy `_: std::fmt::Display`
    | doesn't satisfy `authorities::Error<sp_blockchain::Error>: ToString`
    |
    = note: the following trait bounds were not satisfied:
            `authorities::Error<sp_blockchain::Error>: std::fmt::Display`
            which is required by `authorities::Error<sp_blockchain::Error>: ToString`

error[E0599]: the method `to_string` exists for enum `authorities::Error<sp_blockchain::Error>`, but its trait bounds were not satisfied
   --> /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/import.rs:374:50
    |
374 |                     .map_err(|e| ConsensusError::ClientImport(e.to_string()))
    |                                                                 ^^^^^^^^^ method cannot be called on `authorities::Error<sp_blockchain::Error>` due to unsatisfied trait bounds
    | 
   ::: /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/authorities.rs:36:1
    |
36  | pub enum Error<E> {
    | -----------------
    | |
    | method `to_string` not found for this
    | doesn't satisfy `_: std::fmt::Display`
    | doesn't satisfy `authorities::Error<sp_blockchain::Error>: ToString`
    |
    = note: the following trait bounds were not satisfied:
            `authorities::Error<sp_blockchain::Error>: std::fmt::Display`
            which is required by `authorities::Error<sp_blockchain::Error>: ToString`

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `sc-finality-grandpa`
```

**Comment by tinydjp** [comment]
Hi  @semuelle, I believe this is a bug of parity, I reported this in their element channel. I'm afraid you have to edit the source file in your repo.  For example `vi /hme/.cargo/registry/src/github.com-1ecc6299db9ec823/sc-finality-grandpa-0.8.1/src/authorities.rs`,  and then replace line 37 code with following
`#[display(fmt = "Invalid authority set, either empty or with an authority weight set to 0.")]`. Then you should be able to compile. 
BTW, my successful nightly version is  nightly-2020-10-05
```
rustup install nightly-2020-10-05
rustup target add wasm32-unknown-unknown --toolchain nightly-2020-10-05
cargo +nightly-2020-10-05 build --release
```

**Comment by semuelle** [comment]
Thanks for following up on the build issue, @tinydjp. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/f606491f64aa8c522600d8f6f481ba3064905606/evaluations/molochDAO_1_semuelle.md) and your milestone is hereby accepted. :tada: 

The only thing I would like to point out is that the grant agreement states that the unit tests will `ensure robustness`, which I don't consider covered by the three unit tests. If you could expand the tests for the next milestone, that'd be great.

I will forward your invoice for processing.

**Comment by semuelle** [comment]
@zhangjiannan @tinydjp It seems your invoice is over 10,000, rather than 1,000 DAI. Could you submit a corrected one?

**Comment by zhangjiannan** [comment]
Hi @semuelle we will update the invoice soon, thanks for letting us know!

**Comment by zhangjiannan** [comment]
@semuelle Thanks for the evaluation! When we wrote the test, we found that it was relatively difficult to write unit tests for MolochDAO, because the state machine is pretty complicated, and it takes actions before calling most of the functions. So we decided to focus on the test guide instead of unit test. If you have any suggestions about how we can improve the test for this milestone and the next milestone, please let us know.

**Comment by semuelle** [comment]
> we found that it was relatively difficult to write unit tests for MolochDAO, because the state machine is pretty complicated, and it takes actions before calling most of the functions. If you have any suggestions about how we can improve the test for this milestone and the next milestone, please let us know.

Generally, I would expect calls to verify that any transaction fails when the parameters or roles are off, or they are done in the wrong sequence or before the voting/grace period have ended. That should be straightforward to implement. Beyond that, I don't see any tests for `abort`, `ragequit` and `update_delegate`.

**Comment by RouvenP** [comment]
hi @zhangjiannan we transferred the payment.

**Comment by zhangjiannan** [comment]
@semuelle thanks for the feedback! We will follow the guideline and add full tests in V2 implementation.

**Comment by zhangjiannan** [comment]
@RouvenP thanks!

**Pull request merged**
