### PR TITLE
SkyePass Milestone 0 Delivery

### PR DESCRIPTION
**Pull request by RoyTimes**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [X] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
        (OR ETH address for DAI as provided)
- [X] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by RoyTimes** [comment]
@Noc2 just a friendly reminder to check if there are any updates?

**Comment by mmagician** [comment]
@RoyTimes Yes I started to look at your delivery. In the upcoming days I'll ping you in case I have any questions.

**Comment by mmagician** [comment]
I'm putting this temporarily on hold due to parallel participation in the [hackathon](https://github.com/ParityAsia/hackathon-2021-spring/). The hackathon organisers will contact you regarding further steps.

**Comment by mmagician** [comment]
Below you'll find feedback on the current state of your project:

### Vault burning
- only the owner can burn? why not members? can ownership be transferred?

### Storage
Wouldn't it be easier to store a map of Vaults instead?
e.g.
```
pub struct SkyePassVault {
    vault_owner: AccountId>,
    vault_operators: AccountId,
    vault_metadata: String
}
```

and then

```
pub struct Vaults {
    StorageHashMap<VaultId, SkyePassVault>
}
```

This way, you have the logic of `next_vaultid` decoupled from the storage of vaults
This is just my initial though when I saw your code. Since I am not part of your team, I can't know the design process that went into this, but I would like to ask you to explain your choices please to better understand the needs and future plans of your project. Design of your data structures is surely going to affect your development process further down the line.

### Canvas node
canvas instructions seem to be wrong. My setup was:
- latest canvas node
- unaltered redspot.config.ts

And I was able to run `yarn test` just fine. When I adapted my config as per your instructions, I was getting errors complaining about MultiAddress!

If I were to build the contract myself, however (`npx redspot build`) & upload the `.json` and `.wasm` via the Canvas UI, I get MultiAddress errors as before.

Could you investigate the two above issues please?

### Tests
I'm no typescript expert, but I believe you have duplicated code in some places:
e.g. line 292 & 294 -> the result surely must be the same, no? Same for 285 & 287, 317 & 320 and more

Also, rather than checking for `.to.not.emit(contract, "MemembershipGranted")`, is there a way to check if an error is thrown?

Normally I would ask teams to write unit tests directly in ink!, but you seemed to cover both integration and unit tests extensively in TS, which is fine (especially that your grant contract didn't specify how you'd test). Well done there!

### Misc
LICENSE missing for the UX app

**Comment by RoyTimes** [comment]
@mmagician Thanks for the feedback. I'm traveling and very sick under weather. I think you can expect me to resolve your feedbacks by next Friday. 

A brief response for now: 
1. only owner can burn vaults is by design. Intention is straight forwards: I think owners deserve more power over the vault. I'm happy to hear if you (or anyone else) have other opinions. It's a open source project and opinions from the community matters a lot for us. 

2. On `storage`: I never wrote Rust before this project and your proposal sounds good to me. I'll investigate and adopt accordingly. 
3. Canvas Node: most likely canvas node updated but I have not updated locally. My bad, but it should be an easy fix. Will fix it soon. 
4. Test: `duplicated code` - Indeed, to my defense: I was thinking the testing step-by-steply and the first occurrence belongs to the earlier processing and the later one belong to the later processing. Regardlessly, sorry that it causes confusion for your reading, will remove the duplicated lines. As for catching error, I have tried but Redspot does not seem to include such functionality. I can definitely check back. It's been a few weeks, they might have added that kind of error catching. Testing not covered in contract is not by design, because I did not have a very good idea of how to do testing back then. Haha. I'm glad that you find the test coverage good. 
 
5. UX license: easy fix. Will do.

**Comment by mmagician** [comment]
@RoyTimes Thanks for the update. Take your time and I wish you a speedy recovery!

**Comment by RoyTimes** [comment]
Hi @mmagician I have pushed some updates. 

Here, a more detailed address to all your feedbacks:

## Burn vaults
like I said earlier, I believe only allowing owners to burn vaults makes more sense to me. Feel free to push back : )

## Storage
I guess there are some concerns I got with adopting your suggestion here: mostly, because `vault_operators` is not one single account but it's a list of all members who have write access to a vault. Tbh, I re-wrote the smart contract 3 times just to find out a good way of implementing this right. I probably had spent more time on `vault_operators` than all of my other work on `skyepass-vault` combined. 

For now, it is structured as an `HashMap<(VaultId, OperatorId), ()>` - `Map`(which is actually a `Set`). To have a `pub struct SkyePassVault` with all info of **one** vault inside, I'd be forced to use an `Vec` and mess with `PackedLayout` & `SpreadLayout` for having a `Vec` inside another `HashMap`.  

Documentations of `Storage Layout` are not aiding my understanding well enough: both on execution performance and on storage performance that is gonna directly affect storage rent. I might be overthinking this, but lots of changes on the `contract pallet` are under discussion and spending too much time on this seems to be fixing a running car.

Let me know your thought. Correct me if I'm wrong. If I'm not terribly wrong, I would suggest us re-visiting this on our next milestone delivery. 

One extra thing about `next_vaultid`, it is not coupled with `SkyePassVault` itself, it's a global self-incremental value that is assigned to each new vault created as a UUID. Similar to how NFTs are IDed and minted. It has nothing to do with linking a vault to the next vault as a `next` pointer in a linked list. I'm also open to suggestion if there is a better way to do so. 

## Canvas Node
Canvas Node was updated at https://github.com/paritytech/canvas-node/commit/4de483008452447b99535947594a4efbb45e87bc that affect the `types` definition. I updated my local canvas node to `canvas 0.1.0-385c4cc-x86_64-macos` under tag `v0.1.5`. It's working as how you described your local env now. I have updated the README reflecting this. 

One extra things is that PatractLabs renamed `patract` to `jupiter` to match the name of their testnet. I have made some updated on this in the README as well. 

## Testing
Duplications deleted. 

There is still, unfortunately, no support on checking errors yet. I have proposed https://github.com/patractlabs/redspot/issues/78 to the `redspot` team. Ideally, they can provide me feedbacks that point me to the right way of doing so, or the `redspot` team can make updates to it. I have never worked with `mocha` or `chai` extensions before. To the worst case, I'm okay with picking up how to extend `chai` and spending a weekend and adding-in the functionality as a PR to `redspot` myself.

As for `skyepass-vault` the only thing remains is that the Error types cannot be correctly examined. For `.to.not.emit(contract, "MemembershipGranted")`, it should be replaced to check if `Error::AccessDenied` is returned. Let me know if you are OK with leaving this bug like that for Milestone 0, while I work with `redspot` to either find or implement it into `@redspot/chai` 

## UX Licensing 
Fixed.

**Comment by mmagician** [comment]
@RoyTimes That's great, I'll review your changes this week!

**Comment by mmagician** [comment]
@RoyTimes I've got a few more concerns regarding your milestone 0:

1. No validation of metadata on the smart contract side, it's just a string and users can place anything there

2. Safety checks missing (on client side, but also see previous point regarding smart contracts):
    1. publicPieceCount > quorum ?
    2. publicPieceCount + members.length + owner.isNotNull == pieces
    3. quorum <= pieces

3. Metadata class has a metadata attribute, a bit confusing.

4. Some of the data fields are repeated within Metadata class top level and `metadata` (lowercase): `pieces`, `quorum`, `owner`

5. No error handling (e.g. on upload to IPFS or DB saving) 

6. The check for recover seems wrong: `if (this.encryptionSchema.quorum <= 1 + this.encryptionSchema.publicPieceCount) {...}`

in your examples this works, since you always set quorum = 2, and publicPieceCount = 1, so for a single retriever. But what if I have a quorum = 3, publicPieceCount = 1, and I control two private keys that I wish to use to decrypt the remaining shares? Your method does not currently support this functionality as far as I can tell. 

I see that in your deliverables for milestone 0 you do mention `simplest 4/2 schema` - which I assume will be expanded upon later? I just wonder how you're going to handle asynchronous requests from the members for decrypting the shares - presumably this needs to be stored somewhere temporarily?

In the [PR](https://github.com/skyekiwi/skyepass-vault/pull/4) I created to remove the unused code I missed a more important issue, which, I believe, is that your intention was to actually use the code, but the Metadata is never actually updated (as your Metadata object doesn't know about the change to encryptionSchema)

Let me know if you have any questions :)

**Comment by RoyTimes** [comment]
@mmagician 

Brief response: 
1. Can't believe I forgot this. 
2. & 6. I'll go through all conditions checking for one more time. 
3. & 4. `metadata` is some implementation legacy trash: I think I can pretty much remove this field. 

**IPFS & DB Error Handling** - 🤦 Yes. Working on it. 


And for:
> in your examples this works, since you always set quorum = 2, and publicPieceCount = 1, so for a single retriever. But what if I have a quorum = 3, publicPieceCount = 1, and I control two private keys that I wish to use to decrypt the remaining shares? Your method does not currently support this functionality as far as I can tell.

No, I don't think I will support that for a while. I don't think it's necessary for a user to control two private keys for the same vault. However, this will be useful when a vault requires two users to decrypt w/private keys at the same time. I am thinking about some kinda [Signal](https://singla.org) whisper protocol to communicate. It is far ahead on our roadmap :)

> I see that in your deliverables for milestone 0 you do mention simplest 4/2 schema - which I assume will be expanded upon later? I just wonder how you're going to handle asynchronous requests from the members for decrypting the shares - presumably this needs to be stored somewhere temporarily?

Not sure if I understand what you mean by async request by members. Updating a vault is not frequent and we have a nonce management system to reduce conflicts when updating. OR if you mean if a vault needs to be decrypted by multiple members at the same time, it is discussed above. As for the recovered vaults, it will be stored locally encrypted (this is the part not fully implemented yet and I have been working on it these days).

> In the PR I created to remove the unused code I missed a more important issue, which, I believe, is that your intention was to actually use the code, but the Metadata is never actually updated (as your Metadata object doesn't know about the change to encryptionSchema)

🤦  I'm embarrassed. This is some dumb mistake. 



Either way, my apologies for making funny bugs. I'll provide a detailed update by this Friday.

**Comment by mmagician** [comment]
@RoyTimes 
> I don't think it's necessary for a user to control two private keys for the same vault. However, this will be useful when a vault requires two users to decrypt w/private keys at the same time. 

Yes,I meant the latter (though actually at the level of implementation they will be equivalent as far as I can imagine)

I'll be looking forward to your updates. Take your time to polish the code :)

**Comment by RoyTimes** [comment]
@mmagician 

> Yes,I meant the latter (though actually at the level of implementation they will be equivalent as far as I can imagine)

Hmmm.... It's a matter of user experience. What will the interface actually look like? My imagination would be member1 will have a `waiting for another member to decrypt ....` kinda msg, while when the other decrypt, the other piece is gonna sent via encryption through an ephemeral keypair. I guess that's the reason for me to not overthink this too much. 

Update Log:
- Smart Contract: `vaultCreation` & `updateMetadata` now checks if the `string.len()` is 46. Even though we do not check if the string is a CID but this should be enough to prevent attacks. 
- Smart Contract Testing: add/change test-cases for the change on `metadata` described above
- Smart Contract Testing: handling `Errors` emitted by the contract according to the discussion in https://github.com/patractlabs/redspot/issues/78 
- Metadata Handler: get rid of the confusing `metadata` field
- Metadata Handler: add comments for every condition statements in the file
- Metadata Handler: add a method to update `encryptionSchema`
- Metadata Handler: add a condition in constructor to check if `quorum > pieces`
- Metadata Handler: not adding a condition in constructor to check if `publicPieceCount > quorum`, I think creating a public vault shall be allowed.
- IPFS Wrapper: throws `new Error('IPFS Failure')` when interactions w/IPFS somehow fails 
- DB Wrapper: throws errors now when write/update/read fails by `Error('database error')`
- E2E Test: updated the `encryptionSchema` for sharing with an extra user 🤦 

Some Notes:
- DB Error Handling Test: I really have no idea how DB writes or read can fail. So I did not create any test cases for them. Unless somehow the user does not give permission for the program to read local files.  
- IPFS Error Handling test: Similar to Error testing for DB. No unit test added.
- IPFS upcoming changes: we are integrating Crust Network to replace the infura IPFS section. Not covered in the original contract but will delivered as a feature for milestone 1. So I won't care too much of the current IPFS error catching tests. 
- Metadata Nonce Mgmt: for `generate, upload metadata & recover from metadata with a privatekey`, it's a confusion part. So, I have created a diagram to demonstrate how `nonce` and `last_cid` are managed. Hope it helps. 
Nonce (1)

**Comment by mmagician** [comment]
Thanks for the fixes. I've left a few last comments directly on your commit: https://github.com/skyekiwi/skyepass-vault/commit/4bf0636d9ea2836226fd8ccfd90ab83f3774cd2c

**Comment by mmagician** [comment]
Lastly, one of the unit tests fails with `AssertionError: expected undefined to equal 'MetadataNotValid'`

**Comment by RoyTimes** [comment]
Update Log:
- add in methods desc of error throwing for `DB` & `IPFS`
- smart contract: introduce `const IPFS_CID_LEN: usize = 46;` I'm new to rust, so please let me know if I'm doing this right. 

Notes:
- Metadata: replied on your comments - I do not think there is anything wrong with it. 
- unit test failure: all tests passed on my side. Please let me know what's your environment and which test case is failing. I suspect it has something to do with `str.len()` because different encoding schema by different OS?

**Comment by mmagician** [comment]
Here's the error msg:
```
  18 passing (9m)
  1 failing

  1) SkyePassVault Smart Contract
       queries & updates a metadata of a vault:
     AssertionError: expected undefined to equal 'MetadataNotValid'
```
I'm on MacOS. The tests used to work during the previous builds. I'm using cargo-contracts 0.10.0

**Comment by mmagician** [comment]
@RoyTimes Thanks for a detailed explanation. 
> delete the target and artifacts folders and re-run the test

That did the trick. Now all the tests pass :)
Feel free to clean up the master branch now and then I'd be happy to proceed with accepting the milestone!

**Comment by RoyTimes** [comment]
@mmagician Done. Last commit reverted.

**Comment by mmagician** [comment]
Congratulations on completing the first (0th!) milestone. You'll find the full evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/147). Good luck with the next one!

**Comment by mmagician** [comment]
@RoyTimes Could you please submit an updated invoice, to account for the [discount that we applied](https://github.com/w3f/Open-Grants-Program/pull/325) for hackathon participation?

**Comment by RoyTimes** [comment]
@mmagician Done. $7,980 -> $6,480

**Pull request merged**
