### PR TITLE
MangoSale_Milestone_2

### PR DESCRIPTION
**Pull request by Mangoboxlabs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1400< please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @Mangoboxlabs you can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_2_keeganquigley.md).

There is a lot of Solidity-style [NatSpec](https://docs.soliditylang.org/en/develop/natspec-format.html#natspec) comments in your code. As far as I'm aware, NatSpec and Doxygen formatting isn't compatible with Rust. Instead Rust uses [rustdoc](https://doc.rust-lang.org/book/ch14-02-publishing-to-crates-io.html?highlight=rustdoc#making-useful-documentation-comments) via `cargo doc`. Is there a reason you have included these? I've never seen them in ink! contracts before.

**Comment by Mangoboxlabs** [comment]
@keeganquigley  Thank you for your answer. We have made modifications based on your question. Please retrieve the latest code and try again.

**Comment by keeganquigley** [comment]
Thanks for the changes @Mangoboxlabs please see my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_2_keeganquigley.md) for further issues and let me know if you are able to provide fixes. Thank you.

**Comment by Mangoboxlabs** [comment]
@keeganquigley  Thank you very much for your reply. We have resolved the front-end issue. Please pull the latest code and try again. Regarding the issue of compilation failure, you need to install [binaryen](https://github.com/WebAssembly/binaryen). You can install it through the following methods.

* npm install -g binaryen
* Debian/Ubuntu: apt-get install binaryen                                                       
* Homebrew: brew install binaryen                                                               
* Arch Linux: pacman -S binaryen                                                                
* Windows: binary releases at https://github.com/WebAssembly/binaryen/releases

Alternatively, by compiling and installing

```
cd /opt/   //can be any directory
sudo git clone https://github.com/WebAssembly/binaryen.git
cd ./binaryen
sudo cmake . && sudo make  
./bin/wasm-opt --version
cd /usr/local/bin
ln -s /opt/binaryen/bin/wasm-opt wasm-opt
wasm-opt --version 
```
As for what you said, our cargo contract version is too old because our project was developed a long time ago, and considering the cost, we have not yet upgraded to the new version.

**Comment by keeganquigley** [comment]
Thanks for the changes @Mangoboxlabs much appreciated. I have updated my [eval accordingly](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_2_keeganquigley.md). I'm able to sign the transaction with my test account, but there are now two additional UI tests that fail. I think this is happening because the inital createToken test doesn't complete due to a lack of funds in the test wallet. I understand how to send funds from Alice on a local testnet and on the live testnet, but how can I add funds to the account for the Docker version since there is no node running? Thanks for your help.

**Comment by Mangoboxlabs** [comment]
@keeganquigley Thank you for your answer. We have already explained in the document how to obtain gas, which is [local](https://github.com/Mangoboxlabs/MangoSaleV2/tree/main/frontend#gas) and [online ](https://github.com/Mangoboxlabs/MangoSaleV2/tree/main/frontend#gas-1).
After connecting to the node, select the Account tab, then select any account and click Send to send it to your designated address.

At the same time, we have also optimized the testing content. Please pull the latest code for testing.

**Comment by keeganquigley** [comment]
Thanks @Mangoboxlabs I was able to get it working now; I was reading the instructions wrong. I was confused because "Way 2" is [listed twice](https://github.com/Mangoboxlabs/MangoSaleV2/tree/main/frontend#way-2-local-node-test) for both methods and I wasn't sure if I still needed to connect to a node. I think the instructions could still be made more clear.

An even better way to test would be to package it using Docker Compose to spin up 3 containers simultaneously: a contracts-node with the correct params, the front-end, and the cypress e2e tests.  Regardless, I was able to get it up and running and test all the contract functions manually and with e2e tests. Therefore I'm happy to pass this milestone, nice work!

**Comment by Mangoboxlabs** [comment]
Hi, @keeganquigley , any update on payment? Thanks~

**Comment by keeganquigley** [comment]
Hi @Mangoboxlabs thanks for inquiring. I am checking internally with the operations team and I will get back to you.

**Comment by keeganquigley** [comment]
Hi again @Mangoboxlabs I checked with the team and the invoice will be paid on Friday. Let us know if you don't receive it after the 15th. Thank you!

**Comment by Mangoboxlabs** [comment]
@keeganquigley   Thank you very much for your help.

**Pull request merged**
