### PR TITLE
Create Substats-Milestone_3.md

### PR DESCRIPTION
**Pull request by heipowerman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1509

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @heipowerman, thanks for the delivery! I started the evaluation and I'll get back to you soon.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Here I am, [this](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/substats_3_0xCaso.md) is the evaluation. Let me know if you have any questions about it!

**Comment by 0xCaso** [comment]
@heipowerman any news?

**Comment by heipowerman** [comment]
@0xCaso Thanks for your suggestions. [This](https://github.com/CESSProject/substats/blob/master/documents/milestone3-reply-1.md) is the feedback for the evaluation. 
I hope the above is useful to you.

**Review by 0xCaso — APPROVED** [review]
Thanks a lot!

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
Thanks again @heipowerman, I just forwarded the invoice internally. As you know, the payment should happen within 14 days.

**Pull request merged**
