### PR TITLE
Add Epirus Substrate Explorer Milestone 1

### PR DESCRIPTION
**Pull request by conor10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. _<- DOT address provided_
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/965

### CODE REVIEW

**Comment by lucasvanmol** [comment]
Thank you @conor10 for the delivery! I'm looking into it now.

On a quick note, the address specified in your application is the polkadot address `1c3tzkJnXffpJnjWXmNwvyKKVTkY5QFCHBDATV3EDvg8e17`, could you clarify if this means you wish to be paid in aUSD on the Acala network? In which case the equivalent address on Acala would be [`21UeUvALdSQwNtqNZrZciwdZnLth5uhT5giXKHv3rmsYwpM8`](https://polkadot.subscan.io/tools/format_transform?input=1c3tzkJnXffpJnjWXmNwvyKKVTkY5QFCHBDATV3EDvg8e17&type=Acala).

**Comment by conor10** [comment]
Hi @lucasvanmol, if the payment is in a stablecoin (I'd presumed it was in DOT), USDC on ETH is preferred. 

If this is the case, please use the USDC address 0xc905c448db9942c662fcb1680f3ecfcd0592409c on Ethereum.

**Comment by lucasvanmol** [comment]
Yep, payments are made in either [BTC, USDT, USDC, DAI or aUSD](https://github.com/w3f/Grants-Program#pencil-process). Could you please submit a pull request to https://github.com/w3f/Grants-Program in order to update the application document with this address? Once accepted, you can also fill in the invoice form again with the updated information.

**Comment by conor10** [comment]
Thanks @lucasvanmol, I've just done both of these tasks.

**Comment by lucasvanmol** [comment]
Thank you for that, @conor10, and thank you for the great delivery! I've accepted it and you can see my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/epirus-substrate-explorer_1_lucasvanmol.md). I'll forward your invoice internally for payment.

**Comment by RouvenP** [comment]
hi @conor10 we transferred the payment today.

**Comment by conor10** [comment]
Thanks, funds received.

**Pull request merged**
