### PR TITLE
Create Sandox_st1_ms1_delivery.md

### PR DESCRIPTION
**Pull request by TradeLinkEstonia**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the Statemint account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1694

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia tank you for the milestone delivery and thanks @dastansam for the evaluation. I think the evaluation looks good. The application works well as presented in the demo video. However, seem that some compiling errors are not being handled. Please see the example below, the + operator is missing and the application does not show the error, which is handled by the browser console. Is it simple to fix this case?

image

Firefox:
image

Chrome:
image

**Comment by TradeLinkEstonia** [comment]
Hello, @dsm-w3f , @dastansam 
We have added executable permissions to `build.sh` and added `dist` to `.gitignore`
Also, we have reviewed and fixed the error handling mechanism, so now all syntax errors should be handled.
image_2023-07-17_13-19-30

**Comment by dastansam** [comment]
from my side, it lgtm @dsm-w3f

**Comment by TradeLinkEstonia** [comment]
Hello, team!
We'd like to proceed with the next Milestone. Is it everything ok here on this stage?

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the improvements and fixes. I tested again and now it is working. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by TradeLinkEstonia** [comment]
Hello, @dsm-w3f  Diogo! We are in full swing for the delivery of the second milestone in a few weeks. Could you, please, help me to figure out the payment status for the delivered one?

**Comment by meldien** [comment]
@TradeLinkEstonia payment will be executed in the next 3 days. 
Stay you updated.
Best wishes,
Melanie

**Comment by TradeLinkEstonia** [comment]
> @TradeLinkEstonia transfer done

Received! Thank you! Looking forward for the next delivery!

**Pull request merged**
