### PR TITLE
add quadratic funding pallet milestone-1

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by zhangjiannan** [comment]
How can I pass the checks?

**Comment by semuelle** [comment]
The check is just a bot writing your delivery data into a database. No need to worry about it.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the delivery. I started to look into it and have a few questions/requests: 

- Could you update the readme? It’s currently just the original readme of the substrate-node-template and doesn’t contain any information about your document or a testing guide, [see](https://github.com/w3f/Open-Grants-Program/blob/master/applications/dorahacks-quadratic-funding.md#milestone-1----implement-quadratic-funding-pallet)
- Your current pallet has a few unused variables, functions, etc. Could you clean this up? 
- You should ensure that the name has a limited size: https://github.com/zhangjiannan/QFgrant/blob/main/pallets/quadratic-funding/src/lib.rs#L186 
- It would be nice if you could provide inline documentation for all the functions. 
- How do I start a round? I only found end_round: https://github.com/zhangjiannan/QFgrant/blob/199b61301975653adb3dda8e53a36c3ccab85503/pallets/quadratic-funding/src/lib.rs#L161

**Comment by zhangjiannan** [comment]
@Noc2 thanks for your feedback. We have made changes in the repo.

- updated readme
- updated unit tests in test.rs
- fixed warnings and glitches
- provided in-line documentation
- added start_round function and now the pallet supports multiple rounds

**Comment by Noc2** [comment]
Sorry for the late response. This looks much better. Just a quick follow-up: Could you still provide a small testing guide or tutorial? I quickly tried to play with it via the extrinsics tab of polkadot.js, but for example didn’t immediately know how the Admin set up works (or which accounts I need to use to start a round).  And could you point me to line in the code that calculates the matched amounts or payment to each project based on quadratic funding? (You can find a python implementation here: https://github.com/gitcoinco/quadratic-funding)

**Comment by zhangjiannan** [comment]
@Noc2 Thanks for feedback. We are not exactly following GitCoin's approach, we are mostly migrating a decentralized version of quadratic funding grant currently running on HackerLink (see BSC Grant Round-1 https://hackerlink.io/en/Grant/BSC/Round/1/detail), and the algorithm follows Vitalik's original paper (https://vitalik.ca/general/2019/12/07/quadratic.html). The fund distribution happens within fn end_round(), and it's based on each project's support area within a round. We will provide more documentation and in-line comments to help navigate shortly.

**Comment by mmagician** [comment]
I'm putting this temporarily on hold due to parallel participation in the [hackathon](https://github.com/ParityAsia/hackathon-2021-spring/). The hackathon organisers will contact you regarding further steps.

**Comment by Noc2** [comment]
@zhangjiannan Any update on this. Should I take another look at the delivery

**Comment by zhangjiannan** [comment]
Hi @Noc2 we have developed a frontend and integrated into HackerLink. I will share a demo video to help better understand the pallet soon.

**Comment by Noc2** [comment]
@zhangjiannan I just took another quick look at it. Looks good, could you also integrate the json for polkadot.js into the testing guide: https://github.com/zhangjiannan/QFgrant/blob/main/doc/test-guide.md

**Comment by zhangjiannan** [comment]
Hi @Noc2 the json has been added to decode round and project . We deployed a node for testing, you can access it using custom endpoint wss://dao.tophacker.com.

**Comment by Noc2** [comment]
I’m happy to tell you that the milestone is a pass. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dorahacks-quadratic-funding_1_Noc2.md). However, I noticed that the payment address on the invoice is different from the original contract. Could you either amend the payment address of the [contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/dorahacks-quadratic-funding.md) or send us a new invoice?

**Comment by Noc2** [comment]
@zhangjiannan The invoice team just paid you, see https://etherscan.io/tx/0x81b8bbc0a1531a0a4d880c6a59aafb055bc2c2e16daf9f8aa5da66bf7b609a00

**Pull request merged**
