### PR TITLE
Ares Protocol milestone 1

### PR DESCRIPTION
**Pull request by jiyilanzhou**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery of the milestone. We will look into it as soon as possible.

**Comment by Noc2** [comment]
I started to look into your delivery. You can find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ares_protocol_1_Noc2.md). However, it doesn’t seem like you are using an [off-chain worker](https://substrate.dev/docs/en/knowledgebase/runtime/off-chain-workers), like you originally said in the application. The documentation also doesn’t contain any example on how to use the pallet and there doesn’t seem to be a “"golang implement scanner and provider". Additionally could you add an open source license to the repository. The default license of our contracts is Apache 2.

**Comment by jiyilanzhou** [comment]
> I started to look into your delivery. You can find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ares_protocol_1_Noc2.md). However, it doesn’t seem like you are using an [off-chain worker](https://substrate.dev/docs/en/knowledgebase/runtime/off-chain-workers), like you originally said in the application. The documentation also doesn’t contain any example on how to use the pallet and there doesn’t seem to be a “"golang implement scanner and provider". Additionally could you add an open source license to the repository. The default license of our contracts is Apache 2.

Thank you for reply.
* Due to Milestone 1 no list use off-chain worker, so I did not implement the method that used off-chain worker,, future realization oracle users of paralchain will use off-chain woker sending offline transaction to ARES protocol.

* I have updated the readme documentation and add a [vedio](https://www.youtube.com/watch?v=l6q8R5F7abM&t=2s)

* Due to it needs interact with the front end，so  I use javascript implement scanner and provider.  If not satisfied,  I can use golang to implement those.

* I've added Apache License.

**Comment by jiyilanzhou** [comment]
* I already use off-chain woker summit  warehouse api price to on chain，which in `pallet-ocw` pallet.
* Added a UI display to query history data，vedio link [here](https://www.youtube.com/watch?v=HlYhsHFKzJw)

**Comment by Noc2** [comment]
Sorry for the late reply. I looked into your delivery again and I still have a few questions/comments:

- Could you also mention in the readme that you have to run make init first?  
- Could you integrate the videos also into the readme? 
- Could you update the inline comments in the [offchain worker pallet](https://github.com/aresprotocols/ares-module/blob/main/substrate-node-template/pallets/pallet-ocw/src/lib.rs)?
- Could you create a PR to amend the [original contract](https://github.com/aresprotocols/ares-module/blob/main/substrate-node-template/pallets/pallet-ocw/src/lib.rs). For examples, replace golang with js, integrate videos and the front-end into the deliveries.

**Comment by jiyilanzhou** [comment]
> Sorry for the late reply. I looked into your delivery again and I still have a few questions/comments:
> 
> * Could you also mention in the readme that you have to run make init first?
> * Could you integrate the videos also into the readme?
> * Could you update the inline comments in the [offchain worker pallet](https://github.com/aresprotocols/ares-module/blob/main/substrate-node-template/pallets/pallet-ocw/src/lib.rs)?
> * Could you create a PR to amend the [original contract](https://github.com/aresprotocols/ares-module/blob/main/substrate-node-template/pallets/pallet-ocw/src/lib.rs). For examples, replace golang with js, integrate videos and the front-end into the deliveries.

Thank you for reply.

* I aleady explained the steps of the demonstration.
* Integrate the videos into the readme.
* Added some notes to `offchain worker pallet`, and support on chain price aggregate
* Add a [PR](https://github.com/w3f/Open-Grants-Program/pull/176).

**Comment by Noc2** [comment]
Thanks for the fixes. I just commented on your [amendment](https://github.com/w3f/Open-Grants-Program/pull/176).

**Comment by jiyilanzhou** [comment]
Thank you very much, [PR](https://github.com/w3f/Open-Grants-Program/pull/176) has been merged.

**Comment by Noc2** [comment]
I just took another quick look at your delivery and tried to run the [tests](https://github.com/aresprotocols/ares-module/tree/main/substrate-node-template/pallets/pallet-ares/src), but I’m getting the following errors:
```
error[E0412]: cannot find type `BlockNumber` in this scope
  --> pallets/pallet-ares/src/mock.rs:56:31
   |
56 |     pub const AggregateInterval: BlockNumber = 15;
   |                                  ^^^^^^^^^^^ not found in this scope

warning: unused imports: `assert_noop`, `assert_ok`
 --> pallets/pallet-ares/src/tests.rs:3:21
  |
3 | use frame_support::{assert_ok, assert_noop};
  |                     ^^^^^^^^^  ^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `Decode`, `Encode`
 --> pallets/pallet-ares/src/tests.rs:4:13
  |
4 | use codec::{Decode, Encode};
  |             ^^^^^^  ^^^^^^

error[E0061]: this function takes 4 arguments but 3 arguments were supplied
   --> pallets/pallet-ares/src/tests.rs:29:11
    |
29  |           assert!(AresModule::register_aggregator(Origin::signed(1),"btc/eth".into(),"alice".into()).is_ok(),);
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ----------------- ---------------- -------------- supplied 3 arguments
    |                   |
    |                   expected 4 arguments
    | 
   ::: pallets/pallet-ares/src/lib.rs:140:1
    |
140 | / decl_module! {
141 | |     pub struct Module<T: Trait> for enum Call where origin: T::Origin {
142 | |         // Errors must be initialized if they are used by the pallet.
143 | |         type Error = Error<T>;
...   |
292 | |     }
293 | | }
    | |_- defined here

error: aborting due to 2 previous errors; 2 warnings emitted
```

**Comment by jiyilanzhou** [comment]
Sorry,  due to recently added some pallet and off chain code,  which causes the test cases not updated in time.

I already fix all error.

**Comment by Noc2** [comment]
Thanks for fixing everything. I’m happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ares_protocol_1_Noc2.md) and I will forward your invoice internally.

**Comment by Noc2** [comment]
Quick question did you already fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSeZUWVZjrSGUKO38E4_gf2Amd_0QT-HAW0-8wXmI7m54Bggrw/viewform)? I couldn't find your invoice. Feel free to also send it to me directly: david@web3.foundation

**Comment by jiyilanzhou** [comment]
> Quick question did you already fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSeZUWVZjrSGUKO38E4_gf2Amd_0QT-HAW0-8wXmI7m54Bggrw/viewform)? I couldn't find your invoice. Feel free to also send it to me directly: [david@web3.foundation](mailto:david@web3.foundation)

Thank you，I aleady update it.  Let me know if have any questions.

**Comment by Noc2** [comment]
Thanks. I just forwarded the invoice internally.

**Comment by jiyilanzhou** [comment]
Thank you for evaluation,
We will take your comments and feedback into account and continue to enrich, optimize the project, Moving on next milestone.

**Comment by RouvenP** [comment]
hi @jiyilanzhou we just sent a test transaction. Could you please confirm if received?

**Comment by jiyilanzhou** [comment]
Hi @RouvenP thanks for the test transaction, I confirm that I have received 0.001 in the test trasnsaction.

**Comment by RouvenP** [comment]
@jiyilanzhou thanks for confirming. we sent the payment

**Comment by jiyilanzhou** [comment]
@RouvenP Thank you, I has already receive it.  Can we make a announcement to public?

**Pull request merged**
