### PR TITLE
External evaluation of Sirato milestone 1

### PR DESCRIPTION
**Pull request by dastansam**
In general, it's well-documented and majority of the instructions are clear. Code is well written and structured. There are only few minor issues that could be easily addressed.

Milestone Delivery PR: #892 
Application PR: https://github.com/w3f/Grants-Program/pull/1608

### CODE REVIEW

**Comment by keeganquigley** [comment]
Awesome @dastansam thanks for the thorough evaluation! The only thing I noticed was a minor license file fix. Everything else looks great.

Before accepting, could you update the evaluation status to "accepted"? After that I'll merge it. Thanks!

**Comment by dastansam** [comment]
I changed the status to `Accepted` @keeganquigley, cheers!

**Comment by keeganquigley** [comment]
Thanks @dastansam I will forward your KSM address for payment.

**Comment by RouvenP** [comment]
hi @dastansam we just transferred the KSM

**Pull request merged**
