### PR TITLE
Ink-Pallet-Benchmarking-Milestone_1

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1457

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @Nikhil-Desai-Talentica. We will look into it as soon as possible.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @Nikhil-Desai-Talentica. Sorry for the wait.
I am happy to report that most of your deliverables are already crossed off (notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/4e281ae8a28aa19180e59adadbbde3dd5d4d0f29/evaluations/ink-pallet-benchmarking_1_semuelle.md). Two small requests:

1. The article currently looks somewhat bleak. Could you add sample output of your code (feel free to use those from my eval notes above), two sentences about the interpretation of the results in the graph, and a brief summary of how to use it with a link to your repo?
2. Deliverable 0b is supposed to include a "live demo". I'm not sure what this refers to, but perhaps you could do a video walkthrough?

**Comment by Nikhil-Desai-Talentica** [comment]
Hi Sebastian, I understand that you're all overloaded with reviewing a lot of PRs. I thank you for your time and valuable feedback. I appreciate your suggestions and have incorporated them.
1. I have added a label to the y-axis in the chart and also a couple of screenshots showing the command and it's output. I have also added a usage section in the README that lists out the command and have explained the same in the article.
2. I have recorded a video of how to benchmark a pallet and an Ink! smartcontract. I have provided links to it, both in the article and the milestone submission template.
Have a great day!

**Comment by semuelle** [comment]
Thanks for the updates, @Nikhil-Desai-Talentica. I am happy to report that your milestone is accepted. Congratulations! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-pallet-benchmarking_1_semuelle.md).
As a final comment, I would recommend that you replace the terminal screenshots in the article with just the text output for publication; the images don't scale well and the output is currently hard to read. I would also recommend to put the contents of or at least a link to the article and the video into your README.

Regarding payment: I noticed that you did not provide a payment address in your application. For us to be able to verify the invoice, you would need to submit an amendment to [your application](https://github.com/w3f/Grants-Program/blob/91338239ba14cee4af1fd916efc38eb4f1edde08/applications/ink-pallet-benchmarking.md?plain=1#L4) with the payment address from the invoice and the currency you are asking for.

**Comment by Nikhil-Desai-Talentica** [comment]
Hi Sebastian, thanks for accepting this. I will happily incorporate your suggestions.

Regarding payment: Is is okay if I just open a new PR just adding the payment address or is there any other preferred way?

**Comment by semuelle** [comment]
> Regarding payment: Is is okay if I just open a new PR just adding the payment address or is there any other preferred way?

Yep, that's the preferred way.

**Comment by RouvenP** [comment]
hi @Nikhil-Desai-Talentica we transferred the payment today.

**Pull request merged**
