### PR TITLE
Create ces_data_store_2.md

### PR DESCRIPTION
**Pull request by swowk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/855

### CODE REVIEW

**Comment by swowk** [comment]
hi, waiting for your response, thank you. @Noc2

**Comment by takahser** [comment]
Thank you for the delivery, @swowk! We will look into it as soon as possible.

**Comment by ZoettaVerse** [comment]
Hi @takahser ! Have you had time to review our checklist? Looking forward to your feedback!

**Comment by takahser** [comment]
@swowk @ZoettaVerse unfortunately, nobody in our team has had the time to take a look, yet. Currently, we have a large backlog and are trying to get back to our grantees as soon as we can.
Please allow for some more time, we'll get back to you as soon as possible and I'd like to apologize for any inconvenience.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. I started to look into your delivery today. I have one question so far: When I run yarn test it runs all the tests, but I'm not sure it runs any tests specific to your code. At least I couldn’t find it. Could you point me to where you implemented your tests?

**Comment by swowk** [comment]
> Sorry for the delay here. I started to look into your delivery today. I have one question so far: When I run yarn test it runs all the tests, but I'm not sure it runs any tests specific to your code. At least I couldn’t find it. Could you point me to where you implemented your tests?

We apologize for such oversight that we forgot to push the test related code to the remote repo, it has now been resubmitted, please check. Also, thanks for your PR, we will pay more attention to the documentation details in the future.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply and adding the tests. I quickly tried to run them in a freshly cloned repo, but two of them failed, see https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ces_data_store_2_Noc2.md#general-notes Could you take a look at it?

**Comment by swowk** [comment]
Hi, sorry again for this error. In fact, after testing, we found that the error is caused by the network is not smooth, and now it has been optimized, please check.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to tell you that the milestone is a pass and I will forward your invoice internally.

**Comment by bytestocker** [comment]
@Noc2 Sorry, we haven't received the payment yet. Can you help us ask about the payment for this task？

**Comment by Noc2** [comment]
Thanks for chasing us, I will double check with the operations team.

**Comment by fededubbi** [comment]
Hi @bytestocker,

The invoices have been paid on 06.07.2022.
Please see tx hash below: 0xc586f34e7976c5c5b026a9e0975e6873ea9b89264ad85afae3ab87c8774319f1.

Many thanks,
Federica

**Pull request merged**
