### PR TITLE
Zenlink: deliver DEX Smart Contract

### PR DESCRIPTION
**Pull request by v-van**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @v-van,
I can generate the `erc20` and `exchange` contracts, but not the `factory`:

```
sudo docker run --rm -v "$PWD":/build -w /build zenlinkpro/dex:zenlink_contract_builder cargo +nightly-2020-10-06-x86_64-unknown-linux-gnu contract generate-metadata
ERROR: Error invoking `cargo metadata`

Caused by:
    Error during execution of `cargo metadata`: error: failed to read `/exchange/Cargo.toml`
    
    Caused by:
      No such file or directory (os error 2)
```

Can you advise?

**Comment by ByteRui** [comment]
The reason is factory project depend on the exchange project. So we can run the command in factroy project parent folder.
sudo docker run --rm -v "$PWD":/build **-w /build/factory** zenlinkpro/dex:zenlink_contract_builder cargo +nightly-2020-10-06-x86_64-unknown-linux-gnu contract build

**Comment by semuelle** [comment]
Could you please provide access to the tutorial doc? I sent a request through Google Docs yesterday.

**Comment by semuelle** [comment]
Please have a look at my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/156fc5747c067d3f1c9c1624f2eb70286b3a0573/evaluations/zenlink-dex_1_semuelle.md). The work is really good, there are just two deliverables that are missing or inaccessible. 

Let me know if you have any issues or questions.

**Comment by v-van** [comment]
> Could you please provide access to the tutorial doc? I sent a request through Google Docs yesterday.

Sorry, I didn't receive any access requests. Would you like to send me your google account? I will add you to the reviews.

**Comment by ByteRui** [comment]
> Please have a look at my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/156fc5747c067d3f1c9c1624f2eb70286b3a0573/evaluations/zenlink-dex_1_semuelle.md). The work is really good, there are just two deliverables that are missing or inaccessible.
> 
> Let me know if you have any issues or questions.

We build smart contracts on Substrate with ink!. The test environment of ink! has some limits. One is that the contract cannot instantiate the other contract in test environment. The other is the test environment don't support cross call in contracts. So our core function don't work in test environment. The developers of ink! plan to improve the unit-test environment. We can find the plan in https://github.com/paritytech/ink/issues/565. Our team will continue to monitor its progress.

**Comment by v-van** [comment]
Just as @ByteRui said,  the ink! module is not perfect enough to run tests. 
For the grant deliverables, we recommend testing the functionalities manually, rather than unit tests at this stage.

**Comment by semuelle** [comment]
> Sorry, I didn't receive any access requests. Would you like to send me your google account? I will add you to the reviews.
Can you make the document accessible by link and send the link to grants at web3. foundation?

**Comment by v-van** [comment]
> Can you make the document accessible by link and send the link to grants at web3. foundation?

I just made [the article](https://docs.google.com/document/d/1zoXwg0VuMGlNnUAmz9TYubKX-B2dwJ54a5z4fSYss0E/edit?usp=sharing) public. Feel free to leave any comments.

**Comment by semuelle** [comment]
Hey @v-van & @ByteRui,
thanks for following up. The document is great. My only recommendation would be to make the tutorial (same as in the README) a little more verbose (what directory to compile from, what parameter values to choose, what functions to call specifically). 
And I heard you already came to an agreement with @Noc2 regarding unit tests. If you could follow up on those, we can close this PR.

**Comment by v-van** [comment]
Hey @semuelle 
We added some [unit tests](https://github.com/zenlinkpro/zenlink-dex-contract/commit/30eab5dbcad08f3a1d5e89e6d9516c2088189d3c), please have a look at them.
BTW, they only include liquidity token transferring and price calculation.

cc @Noc2 @mmagician

**Comment by semuelle** [comment]
Thanks for following up on the tests. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/9f5fe28fa130b3898b11eb00c3db102e9f26c1b9/evaluations/zenlink-dex_1_semuelle.md) and the milestone is accepted. :tada: 

Your invoice will be forwarded internally for processing.

**Comment by v-van** [comment]
Thank you very much！

**Comment by RouvenP** [comment]
hi @v-van, we just transferred the payment.

**Pull request merged**
