### PR TITLE
External Evaluation lip payments

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
This is an external evaluation for _milestone 1_ for the **lib_payments** project.

**Summary of Evaluation:**
Functionality is developed to a great extent. What is missing is the following:

Update readme.MD to make life easier for people in the ecosystem who want to build the project. 
Tests not building due to missing dependency: fixed via pull request on your repo: https://github.com/virto-network/virto-node/pull/173 

Question: 

1. By what mechanism are accounts added to JudgeWhitelist? (Random, Elected, By Sudo Account,or..)? 
2. Is it possible to do partial refunds to each party? ex (70/30, 50/50 ,etc)? 

Original Milestone Submission: https://github.com/w3f/Grant-Milestone-Delivery/pull/338

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks @JosephKnecht-lab for the second milestone evaluation. Are you aware of our current job openings:  https://web3.bamboohr.com/jobs/?  Feel free to apply. I’m also happy to jump on call: david@web3.foundation

**Comment by olanod** [comment]
Thanks @JosephKnecht-lab for your feedback, I merged your PR after a minor change.
About the questions, 
1. The `JudgeWhitelist` was a generic collection that could be set by the users of the pallet to be anything, for example the collective-pallet controlled by the sudo account or democracy. Later we replaced that concept in https://github.com/virto-network/virto-node/pull/152 as discussed in this [issue](https://github.com/virto-network/virto-node/issues/143)(links also in the milestone deliverables) because it wasn't flexible enough, it was a global list of accounts that could resolve any payment. Now there is a `DisputeResolver` that returns a single account that is assigned to a given payment, it means each payment can have its own distinct judge and the logic to get the account is generic and left to the user of the pallet(still could be the sudo account). This is going to be useful in Virto where we want to create local communities that can define more complex rules about who is going to judge disputes in a payment(e.g. a "mayor"/"local council member" that lives in the same geographical area speaking the same language). 
2.  At the moment is only possible for the dispute resolver to either cancel or release, meaning it's more of an all or nothing kind of refund. But it sounds interesting to do partial refunds, we will definitely consider adding that feature as we are polishing the resolve system for the second milestone.

**Comment by JosephKnecht-lab** [comment]
Thanks, @Noc2. I will consider applying for the position. 

@olanod. Also thank you for your extensive response. I will be happy to move my external evaluation to _Accepted_ if:

1. Include documentation in your README.MD how to run your benchmarks? (Running locaclly with `cargo test --features runtime-benchmarks`  failed for me.
2. Better describe the Makefile commands that you use. Since you are building your nodes in a different way, I think it would be nice to document this for the community. 

I am looking forward to your next delivery since it will be useful for a project I am also working on.

**Comment by olanod** [comment]
Will make the updates to the `README.md` that you suggest 👍🏽 
Once the second milestone is completed my hope is to [include payments pallet in ORML](https://github.com/open-web3-stack/open-runtime-module-library/issues/665) so it becomes easier to include it in projects that already use those pallets(we depend on orml-traits), also would standardize more how tests, benchmarks, etc are run and maintained.

**Comment by JosephKnecht-lab** [comment]
Hi @olanod 

I saw that you have improved documentation: https://github.com/virto-network/virto-node/tree/fix-benchmarks-weights#benchmark 
I have marked this evaluation as **Accepted**. 
Great work so far. I am looking forward to the next milestone. 

As described in the process for evalution, the internal evaluation team have a final say regarding this deliverable.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@JosephKnecht-lab Thanks again for the external evaluation. Could you quickly also update the rest of the evaluation to make sure it’s clear that all the deliverables are accepted? Once this is done, I will merge the evaluation.

**Comment by JosephKnecht-lab** [comment]
@Noc2 I updated the document accepting all deliverables and added some notes.

**Review by takahser — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
Thanks a lot for the update.

**Comment by RouvenP** [comment]
hi @JosephKnecht-lab we transferred the KSM. Thanks!

**Pull request merged**
