### PR TITLE
Add Milestone 1 Delivery for Spacewalk

### PR DESCRIPTION
**Pull request by TorstenStueber**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/749

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @TorstenStueber. We will look into it as soon as possible.

**Comment by TorstenStueber** [comment]
Hey @cruikshankss thanks for your message. I am happy to have a milestone 1 call with you and to answer your questions. How can I contact you in order to arrange a call?

**Comment by cruikshankss** [comment]
@TorstenStueber thank you so much! ashleyg@web3.foundation

**Comment by cruikshankss** [comment]
Thank you @TorstenStueber for the demo today. I've approved your milestone. I plan to process the documents on Monday.

**Comment by TorstenStueber** [comment]
Thanks Ashley!

**Comment by cruikshankss** [comment]
@TorstenStueber I did not start processing your evaluation today. Sorry and thanks for your patience.

**Comment by cruikshankss** [comment]
@TorstenStueber I've forwarded your invoice! And here is my evaluation: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/spacewalk_1_cruikshankss.md

**Pull request merged**
