### PR TITLE
ink! analyzer milestone 1 (#1615)

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1615

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@davidsemakula thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink_analyzer_1_dsm-w3f.md) and provide the proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by davidsemakula** [comment]
@dsm-w3f Thanks for taking the time review.

> The repository has 2 Licenses, Apache 2.0 and MIT. Please choose only one License.

The repository is dual licensed in keeping with the general [Rust ecosystem recommendation](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) and [the main dependency (ra_ap_syntax from rust-analyzer) which also dual-licensed](https://github.com/rust-lang/rust-analyzer#license). LMK if the language is not clear and I can try to improve it.

> Could you provide some examples with an Ink! contract for performing system tests to check the Derivable 1 and the features of the crates?

The [contracts diagnostics module](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/contract.rs) includes a few [ink! contract examples](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/contract.rs#L371-L772) that the tests are run against. The same applies for other ink! entities like [trait definitions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/trait_definition.rs#L173-L259), [chain extensions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/chain_extension.rs#L233-L313) and [storage items](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/storage_item.rs#L166-L226)

**Comment by davidsemakula** [comment]
> > Could you provide some examples with an Ink! contract for performing system tests to check the Derivable 1 and the features of the crates?
> 
> The [contract diagnostics module](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/contract.rs) includes a few [ink! contract examples](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/contract.rs#L371-L772) that the tests are run against. The same applies for other ink! entities like [trait definitions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/trait_definition.rs#L173-L259), [chain extensions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/chain_extension.rs#L233-L313) and [storage items](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/storage_item.rs#L166-L226)

@dsm-w3f I've also added [integration tests](https://github.com/ink-analyzer/ink-analyzer/tree/master/crates/analyzer/tests) that run on a few examples from the [ink! repo's integration tests](https://github.com/paritytech/ink/tree/v4.1.0/integration-tests).

**Comment by davidsemakula** [comment]
> > The repository has 2 Licenses, Apache 2.0 and MIT. Please choose only one License.
> 
> The repository is dual licensed in keeping with the general [Rust ecosystem recommendation](https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive) and [the main dependency (ra_ap_syntax from rust-analyzer) which also dual-licensed](https://github.com/rust-lang/rust-analyzer#license). LMK if the language is not clear and I can try to improve it.

I've updated the license info for both the [repo](https://github.com/ink-analyzer/ink-analyzer/tree/master/crates/analyzer#license) and the [delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/848/commits/56e89dc61be93e6b1bfb2e98ec81081030ebcfce), the nature of the dual-license should be clearer now.

**Comment by dsm-w3f** [comment]
@davidsemakula thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink_analyzer_1_dsm-w3f.md) and the milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by davidsemakula** [comment]
@dsm-w3f awesome! Thanks for the swift review!

**Comment by dsm-w3f** [comment]
@davidsemakula just a final suggestion for improvement maybe would be interesting to include in your system/integration test suite cases that show the diagnostics failing, i.e., where the ink! contract is incorrect and the tool shows this in the diagnostics. I know this would need to produce and store incorrect smart contracts in some repo but it provides ready-to-use examples for those who want to see the tool working.

**Comment by davidsemakula** [comment]
@dsm-w3f makes sense and definitely something I'm looking to add for the integration/system tests, there's already a bunch of failing examples/snippets being used at the unit test level (e.g. [overlapping selectors](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/contract.rs#L981-L1090), [invalid constructor definitions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/src/analysis/diagnostics/constructor.rs#L192-L301) e.t.c for basically all the ink! entities), I just need to create a system that reuses all these snippets and/or composes them into full ink! attribute macro level examples (where necessary) for running failing integration/system tests without too much manual duplication🙂.

**Comment by RouvenP** [comment]
hi @davidsemakula we just transferred the payment

**Comment by davidsemakula** [comment]
Hi @RouvenP I've received it, thanks!

**Pull request merged**
