### PR TITLE
Curve amm miilestone 1

### PR DESCRIPTION
**Pull request by mikolajsobolewski**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
#108

Thanks for the updates.

**Comment by mikolajsobolewski** [comment]
Replaced PR #108

**Comment by alxs** [comment]
Thank you for your patience @mikolajsobolewski. I'm happy to tell you that the milestone is a pass, you can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/curve-amm_1_alxs.md). I'll forward your invoice internally.

**Comment by alxs** [comment]
Hey @mikolajsobolewski. The address in the invoice you submitted seems to be a different one as that in the [application](https://github.com/w3f/Open-Grants-Program/pull/225/files). Could you either send us an invoice with the same address or submit a PR to change it?

**Comment by RouvenP** [comment]
hi @mikolajsobolewski we transferred the payment for milestone 1.

**Pull request merged**
