### PR TITLE
Openbrush milestone 2 delivery

### PR DESCRIPTION
**Pull request by themarkian**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: w3f/Grants-Program#497

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by takahser** [comment]
@themarkian unfortunately the links to the Testing prerequesites (ink! toolchain, Start the node with contract-pallet) on your [README](https://github.com/Supercolony-net/openbrush-contracts/tree/74524fb06a788aae011c3213561038a66ed7cac5#testing) are broken

**Comment by xgreenx** [comment]
Thanks for the comment, fixed=)

**Comment by takahser** [comment]
I just ran the unit tests. Unfortunately they are failing on my machine:
image

**Comment by xgreenx** [comment]
You are right, and it fails during the first build. The [fix](https://github.com/Supercolony-net/openbrush-contracts/commit/592b4c7b5129fafc227ef603bb8b96e1dab0eb68) is submitted. Could you try the latest `main` please? If everything is good, we will create a 1.0.1 release.

**Comment by takahser** [comment]
@xgreenx tests are green now, thx for fixing. 👍🏽 Are you planning to use any github-integrated CI-pipeline in the future to prevent this from happening again?

**Comment by xgreenx** [comment]
Yea, we plan to add more tests for macros in the next milestone and set up CI as part of it.

**Comment by mmagician** [comment]
@themarkian Congratulations on completing the second milestone! The full evaluation can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/openbrush_2_takahser.md).

**Comment by themarkian** [comment]
Hey @mmagician!
Thanks a lot. We appreciate your recognition!

Wondering if you have an ETA of an invoice payment?

**Comment by mmagician** [comment]
I have already approved the invoice, hopefully it should get paid tomorrow.

**Pull request merged**
