### PR TITLE
sunshine-keybase

### PR DESCRIPTION
**Pull request by 4meta5**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for delivering the milestone, we will look into it as soon as possible.

**Comment by Noc2** [comment]
Hi. Started to look into your delivery and only found some minor issues: The following repo currently has no license: https://github.com/sunshine-protocol/sunshine-keybase Could you add it to it (even if it’s the unlicense ;-))? Also the delivery currently doesn’t contain a dockerfile.

**Comment by 4meta5** [comment]
Thanks for the review @Noc2 ! I unlicensed the repo and updated the deliverable with a link to the [Dockerfile](https://github.com/sunshine-protocol/sunshine/blob/master/docker-compose.yml).  Let me know if there are any other issues.

**Comment by Noc2** [comment]
Thanks for the quick reply. I’m happy to tell you that the milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sunshine-keybase_1_Noc2.md) and will now forward your invoice internally

**Comment by RouvenP** [comment]
hi @4meta5 we just sent a test transaction. Could you please confirm if received?

**Comment by 4meta5** [comment]
I received a test transaction 0.01000012 BTC

**Comment by RouvenP** [comment]
> @RouvenP I received a test transaction 0.01000012 BTC

Thanks for confirming. Transaction is sent.

**Pull request merged**
