### PR TITLE
Fractapp Milestone 1 evaluation

### PR DESCRIPTION
**Pull request by semuelle**
Tests and documentation not 100%, but sufficient. Would be useful to have more thorough setup instructions (Android SDK, react-native, APK signing certificate, Jest snapshot updating)

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for looking into it. The evaluation looks good. I will see what we can do regarding the payment of KSM and you will probably hear from us next.

**Comment by Noc2** [comment]
Hi @semuelle Just wanted to double check if this is actually your KSM address before, we pay out anything: ESxS4A7GHMLzve4Mbc9t27RpXtVTnV3LtcMTtcnD26jcUHA

**Comment by semuelle** [comment]
@Noc2 Yep, thanks. Let me know if you need anything else!

**Comment by Noc2** [comment]
Just to keep you posted, you will get 10 KSM as soon as the invoice team takes care of the next round of KSM payments.

**Comment by Noc2** [comment]
Just for confirmation: You just received 10 KSM for your evaluation! Thanks again.

**Pull request merged**
