### PR TITLE
Delivery of cryptolab-staking-rewards-collector-front-end

### PR DESCRIPTION
**Pull request by yktseng**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
Thanks again for the delivery. I started to look into it. Could you take a look at my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptolab-staking-reward-collector-front-end_1_Noc2.md) and let me know if you have any questions?

**Comment by yktseng** [comment]
Hello Noc2. May I ask you which npm version do you use? or give us the report of "npm audit" from your side. Because the vulnerability count was differ from us. And we have identified each to be the vulnerabilities from a devDependency "vue-cli-service". As it does not used in production env. We think it should be ok.

**Comment by Noc2** [comment]
> hich npm version do you use? or give us the report of "npm audit" from your side. Because the vulnerability count was differ from us. And we have identified each to be the vulnerabilities from a devDependency "vue-cli-service". As it does not used in production env. We think it should be ok.

I'm using npm version 7.19.0

**Comment by yktseng** [comment]
@Noc2 We have implemented your suggestions and fixed the issues you mentioned. Please review. Thank you.

**Comment by Noc2** [comment]
@yktseng  Thanks for the update. I quickly did try to run the test for cryptolab-web-server and I still get a bunch of error messages (see below). Should I use a specific branch/tag for testing?

<pre>cargo test
<font color="#26A269"><b>    Finished</b></font> test [unoptimized + debuginfo] target(s) in 0.07s
<font color="#26A269"><b>     Running</b></font> unittests (target/debug/deps/cryptolab_backend-0c7ea6cc197195fc)

running 8 tests
test staking_rewards_collector::test_call_exe_end_date_earlier_than_start ... <font color="#26A269">ok</font>
test staking_rewards_collector::test_call_exe_future_date ... <font color="#26A269">ok</font>
test staking_rewards_collector::test_call_exe_stale_date ... <font color="#26A269">ok</font>
test staking_rewards_collector::test_call_exe_incorrect_address ... <font color="#C01C28">FAILED</font>
test staking_rewards_collector::test_call_exe_good ... <font color="#C01C28">FAILED</font>
test staking_rewards_collector::test_call_exe_no_rewards_found ... <font color="#C01C28">FAILED</font>
test staking_rewards_collector::test_incorrect_date_format ... <font color="#26A269">ok</font>
test staking_rewards_collector::test_unsupported_currency ... <font color="#C01C28">FAILED</font>

failures:

---- staking_rewards_collector::test_call_exe_incorrect_address stdout ----
thread &apos;staking_rewards_collector::test_call_exe_incorrect_address&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }&apos;, src/config.rs:27:70

---- staking_rewards_collector::test_call_exe_good stdout ----
thread &apos;staking_rewards_collector::test_call_exe_good&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }&apos;, src/config.rs:27:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- staking_rewards_collector::test_call_exe_no_rewards_found stdout ----
thread &apos;staking_rewards_collector::test_call_exe_no_rewards_found&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }&apos;, src/config.rs:27:70

---- staking_rewards_collector::test_unsupported_currency stdout ----
thread &apos;staking_rewards_collector::test_unsupported_currency&apos; panicked at &apos;called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: &quot;No such file or directory&quot; }&apos;, src/config.rs:27:70


failures:
    staking_rewards_collector::test_call_exe_good
    staking_rewards_collector::test_call_exe_incorrect_address
    staking_rewards_collector::test_call_exe_no_rewards_found
    staking_rewards_collector::test_unsupported_currency

test result: <font color="#C01C28">FAILED</font>. 4 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

<font color="#C01C28"><b>error</b></font><b>:</b> test failed, to rerun pass &apos;--bin cryptolab-backend&apos;
</pre>

**Comment by yktseng** [comment]
@Noc2, can you confirm that you did put correct `config.json` to the `./config` folder? Because the error message showed that the config file was not found.

image
image

as described here https://github.com/cryptolab-network/cryptolab-package#test

image

**Comment by Noc2** [comment]
Oh, sorry I missed this part. You should also add to the unit test section that mongodb has to be up and running. Independent of it, I’m happy to tell you that your milestone is a pass and I will forward your invoice internally.

**Comment by yktseng** [comment]
I really appreciate it. Thank you @Noc2

**Comment by mmagician** [comment]
Hey @yktseng, we noticed that your website http://cryptolab.network/tools is down. Are you planning on bringing it back up and doing some maintenance?

**Comment by yktseng** [comment]
Hello @mmagician, we made a brand new UI of our site, you can visit https://tools.cryptolab.network or visit the legacy site at https://legacy.cryptolab.network 

We didn’t declare it because staking features are not finished yet. Sorry for inconvenience

**Comment by yktseng** [comment]
Mobile users can only visit the legacy one for now. We are working on the RWD hardly ✊

**Pull request merged**
