### PR TITLE
Starry.Network milestone 1 delivery

### PR DESCRIPTION
**Pull request by poria-cat**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. Someone from the Grants team will look into it as soon as possible (we have a bit of a backlog, so it might take a couple of days).

**Comment by poria-cat** [comment]
> Thank you for the delivery. Someone from the Grants team will look into it as soon as possible (we have a bit of a backlog, so it might take a couple of days).

Hi @semuelle , thank you very much for your quick reply, hopefully it won't take long.

**Comment by mmagician** [comment]
@poria-cat After the first review of your project, here are my comments:

### Code

1. running `cargo clippy` generates multiple warnings

2. pallet-nft:

in rustdoc for `mint_non_fungible`, you state:
> `collection_id`: The id of the collection whose token type is NFT.

but there is no subsequent check for whether the `collection_id` provided is indeed of type fungible or not

same for `mint_fungible`


### Documentation & tutorial

Your article is entertaining, yet it contains little details on how to actually use your application.

The READMEs that I could find don't explain how to run and test your application either.

Please make sure that you either have a separate place for your documentation, or you improve the existing sources.

### Frontend

I'm getting:

```
Error: GraphQL Error (Code: 404): {"response":{"error":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /</pre>\n</body>\n</html>\n","status":404},"request":{"query":"\n query {\n orders {\n nodes {\n id\n amount\n seller\n nftId\n price\n }\n }\n }\n "}}
```

### Misc

What do you mean by:
> This relies on starry_query (in connection to the Frontend deliverable)

I can't see any dependency on `starry_query` in package.json of your [app](https://github.com/Starry-Network/app)

**Comment by poria-cat** [comment]
Thank you very much for your review! 😄 
For code, I found most of the warnings in the pallet-nftdao, then I fixed most of them, just not create_dao, submit_proposal which had too many parameters.
In mint_non_fungible and mint_fungible only do some basic checking, most of the checking is done in _mint_non_fungible and _mint_fungible, which includes type checking of the collection, e.g. 

`if let Some(token_type) = collection.token_type {
            ensure!(
                token_type == TokenType::NonFungible,
                Error::<T>::WrongTokenType
            );
        }
`

Whoops, I forget to write something about how to actually use my application. I will finish this tomorrow (Thursday).

Also, the error on the frontend is due to not running starry_query, I will create a new repository with query, node and frontend together and finish the description of these tomorrow.

Thank you again for your careful review.

**Comment by mmagician** [comment]
I would rather suggest to keep the repositories separate, but instead explain it properly how they depend on one another and how to run them. I believe this would be cleaner and also follow the pattern set by substrate-node-template & substrate-front-end-template.

**Comment by poria-cat** [comment]
> I would rather suggest to keep the repositories separate, but instead explain it properly how they depend on one another and how to run them. I believe this would be cleaner and also follow the pattern set by substrate-node-template & substrate-front-end-template.

Okay, I get it. 👌

**Comment by poria-cat** [comment]
Hi @mmagician , I add them to starry_node [readme](https://github.com/Starry-Network/starry_node#starry-documentation).
See how to get started [here](https://github.com/Starry-Network/starry_node/blob/master/tutorial/run_app.md).
See how to use Starry at [here](https://github.com/Starry-Network/starry_node/blob/master/tutorial/use_starry.md).

**Comment by mmagician** [comment]
After creating the collection, I tried using polkadot-js/apps to view what I had just created.
Here's a screenshot with the results I got for the following queries: bottom-to-top:
1. `collections` without the hash
2. `collections(0xced9acffbca18435be8008ac8310b268198c8425a9930c1aa676ff908a012375)`, which is the correct hash of my collection
3. `collections(0xced9acffbca18435be8008ac8310b268198c8425a9930c1aa676ff908a012371)`, which a random incorrect hash.

My expected result would have been to get an empty set for the 1st & 3rd query, and to retrieve details of my collection from the 2nd query. Yet, for my correct hash I get <unknown> and for a random hash I get my collection. 
Could you double check this on your end please? Here's a screenshot:

Screenshot 2021-05-27 at 15 04 07

**Comment by mmagician** [comment]
More issues: 
1. After minting some tokens, I can verify I have them in my account (query storage by: `nftModule.addressBalances(<hash>, <my account address>)` returns the correct number of tokens), but they're not showing up under Profile -> Tokens
2. The name `subModule` is a little bit ambiguous, since `submodule` is a term broadly used within the software industry (e.g. github submodules). Given that substrate is composed of modules as well, this might lead to confusion.
3. At the moment, when I mint NFTs, this is what happens: upload of metadata & image first, Tx approval (by polkadot js extension) second. Seems a bit of a waste of resources and opens a vector for attacks, if the users don't have an intention of signing, or for some reason fail to sign (e.g. what happened to me initially when testing, I didn't fund my account so couldn't cover the fees)
4. I still get warnings from clippy, and they're not just for `too many arguments`

I would please like to ask you to follow the steps from the tutorial yourself and double check that the provided steps work as expected, and that everything is polished. It seems to be that your solution is half baked so far, since I found quite a number of issues already without even getting halfway through your tutorial.

Please let me know once you are confident with the quality of your solution so that I can take another look.

**Comment by poria-cat** [comment]
Hi @mmagician , This problem may be due to not using the correct t ypes, because in subsequent development we have been using query queries and have forgotten to update the correct types.

Replace collectionInfo to this:

```
 "CollectionInfo": {
        "owner": "AccountId",
        "uri": "Vec<u8>",
        "total_supply": "u128",
        "token_type": "Option<TokenType>"
      },
```

Then it will work well.

image

For this example, 0x16811f9c4c28814b6a46ad8a266ffff9215a69939941556706d3cfed4c8eac37 is wrong hash and 0x16811f9c4c28814b6a46ad8a266ffff9215a69939941556706d3cfed4c8eac36 is current hash. 
1st use current hash, 2nd & 3rd use wrong hash. They proceed as expected.

Here are answers:
1. Also, I did follow a similar tutorial a number of times and most of the problems were caused by untimely data updates, as SubQuery stores data a few blocks slower than the blocks are generated. Also, I'll start trying to optimize the experience by using automatic updates so that I don't have to refresh the page multiple times.
2. Changing the subModule to subNftModule is a good option.
3. This is a good question, but don't worry about wasting resources, uploading the same content to ipfs will give you the same CID, and if you don't use a service like pinata the file will slowly disappear from the ipfs network. So, later on, you can open an Event Listening Server, and then read the event to pin the correct asset. That is, unsuccessful transactions will not be pinned to pinata or anything like that.

4.  Running `cargo build` on my development server, most of the problems are caused by node-templates, not pallets

image

I have post warnings to [gist](https://gist.github.com/poria-cat/db56041563bccc9333376863b38c1e92)

**Comment by poria-cat** [comment]
> I'm not sure about your clippy settings, but it's not even checking your pallets (it only checks `runtime` and `node`).
> 
> Please update the [types.json](https://github.com/Starry-Network/starry_node/blob/master/types.json) as well.

OK, the name of the subModule has now been changed, and the clippy warnings have been fixed. The rest of the changes will be done tomorrow.

**Comment by mmagician** [comment]
@poria-cat Great, that already helps.

I'm running into a frontend issue, steps to reproduce:

1. Create an account via the extension. I made a TestAccount 5H6d9gvP4JuQ5eWsgfjNkcD5A64jEF9YMMqxn3wRDBZwp8En
2. It needs to cover Tx fees. Transfer 100,000 tokens to TestAccount from Alice
3. Create a collection. I can successfully verify the creation by viewing chain state:

```
collectionModule.collections: CollectionInfo
[
  [
    [
      0x73d782fc7ea460e0a901a2c4086ed49b6de5bfa98757ffa9eab740bd921ec9aa
    ],
    {
      owner: 5H6d9gvP4JuQ5eWsgfjNkcD5A64jEF9YMMqxn3wRDBZwp8En,
      uri: QmdWn8cTjWFKF3eHF3nadne11xdB6Pcn2tVFgWtoGFWVy7,
      total_supply: 0,
      token_type: NonFungible
    }
  ]
]
```

4. mint some tokens from the "/createNFT/" URL path
5. Verify that `total_supply` from previous chain state > 0

6. tokens dont show under profile -> tokens. Checking the console I see the data returned as `{"data":{"nfts":{"nodes":[]}}}`

Same for splitNFTs, I can verify there is some data in chain state, but nothing shows under my profile.

**Comment by poria-cat** [comment]
Hi @mmagician , to make sure it was what I thought it was, I did the same thing, and luckily, NFT was able to show up in the profile. This is because it takes some time to synchronize the sub-query, usually 10-20s, so I added a popup box for the user to wait a while. If for some reason the data is not refreshed, refreshing the page will fix the problem. Remember to update the front-end app for a smoother experience. Also, since some updates were made to the Query, remember to delete the data volume (.data) before running the Query.

image

**Comment by mmagician** [comment]
> If for some reason the data is not refreshed, refreshing the page will fix the problem.

That didn't solve it. I was using the latest query & app codebases, and made sure to delete the `.data` folder beforehand.

Perhaps we should have a call? I could show you the steps that I performed and we can see whether I was missing something. You can reach out to me on Element: @marcin:web3.foundation to arrange this.

**Comment by poria-cat** [comment]
@mmagician Ok, it will save a lot of trouble

**Comment by poria-cat** [comment]
@mmagician I have put node, app and query to new repo https://github.com/Starry-Network/starry_docker.
The build instructions are written in the readme.

**Comment by mmagician** [comment]
@poria-cat I couldn't get it to work using the provided instructions, I think you're missing a couple of steps in your README. I reached out to your on Element with the details.

**Comment by alxs** [comment]
@poria-cat I also gave this a try and couldn't get it to work. [This](https://github.com/docker-library/postgres/issues/116) fixed the first issue I ran into, I recommend you update `docker-compose.yml` in your repo accordingly. This is the current output of `graphql-engine`:

```
graphql-engine_1  | 2021-06-10T20:55:12.802Z <nestjs> INFO Starting Nest application... 
graphql-engine_1  | 2021-06-10T20:55:12.841Z <nestjs> INFO AppModule dependencies initialized 
graphql-engine_1  | 2021-06-10T20:55:12.842Z <nestjs> INFO ConfigureModule dependencies initialized 
graphql-engine_1  | 2021-06-10T20:55:12.844Z <nestjs> INFO GraphqlModule dependencies initialized 
graphql-engine_1  | (node:6) UnhandledPromiseRejectionWarning: Error: unknown project name app
graphql-engine_1  |     at ProjectService.getProjectSchema (/usr/local/lib/node_modules/@subql/query/dist/graphql/project.service.js:29:19)
graphql-engine_1  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
graphql-engine_1  |     at async GraphqlModule.createServer (/usr/local/lib/node_modules/@subql/query/dist/graphql/graphql.module.js:49:26)
graphql-engine_1  |     at async GraphqlModule.onModuleInit (/usr/local/lib/node_modules/@subql/query/dist/graphql/graphql.module.js:40:29)
graphql-engine_1  |     at async Object.callModuleInitHook (/usr/local/lib/node_modules/@subql/query/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
graphql-engine_1  |     at async NestApplication.callInitHook (/usr/local/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application-context.js:166:13)
graphql-engine_1  |     at async NestApplication.init (/usr/local/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application.js:93:9)
graphql-engine_1  |     at async NestApplication.listen (/usr/local/lib/node_modules/@subql/query/node_modules/@nestjs/core/nest-application.js:147:33)
graphql-engine_1  |     at async /usr/local/lib/node_modules/@subql/query/dist/main.js:13:5
graphql-engine_1  | (Use `node --trace-warnings ...` to show where the warning was created)
graphql-engine_1  | (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
graphql-engine_1  | (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
starry_docker_graphql-engine_1 exited with code 0
```

**Comment by alxs** [comment]
`graphql-engine` keeps crashing after `node-template` is running.

I also get the following:

```
subquery-node_1   | 2021-06-11 11:14:49          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: connection failed
```

**Comment by poria-cat** [comment]
It will keep throwing until the node-template is compiled.

image

image

image
image

**Comment by poria-cat** [comment]
> `graphql-engine` keeps crashing after `node-template` is running.
> 
> I also get the following:
> 
> ```
> subquery-node_1   | 2021-06-11 11:14:49          API-WS: disconnected from ws://host.docker.internal:9944: 1006:: connection failed
> ```

See this [question](https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal).
Can try turn host.docker.internal to 172.17.0.1

**Comment by alxs** [comment]
Thanks, that worked. Now http://localhost:3000/ opens the [GraphQL Playground](https://github.com/graphql/graphql-playground) instead of the app.

**Comment by poria-cat** [comment]
> Thanks, that worked. Now http://localhost:3000/ opens the [GraphQL Playground](https://github.com/graphql/graphql-playground) instead of the app.

@alxs  Yes,  that's right. Since the default port for crate-react-app is 3000, I've changed it to localhost:3001 to prevent port conflicts. Open localhost:3001 and feel free to try it out.
Also, remember to transfer some uint for the test account :)

**Comment by alxs** [comment]
@poria-cat That worked. I tried to test minting an NFT and ran into the [same issue](https://github.com/w3f/Grant-Milestone-Delivery/pull/177#issuecomment-852198342) as Marcin. At this point, I'm ceding over the evaluation back to him.

**Comment by poria-cat** [comment]
> @poria-cat That worked. I tried to test minting an NFT and ran into the [same issue](https://github.com/w3f/Grant-Milestone-Delivery/pull/177#issuecomment-852198342) as Marcin. At this point, I'm ceding over the evaluation back to him.


Hi @alxs,  Maybe try deploying on a remote server. I deployed these on a digitalocean server and can then access them locally with no problem via ip and port

**Comment by poria-cat** [comment]
My workflow looks like this:
1. change the query host in the app to a public ip.
2. deploy these on the server.
3. forward port 9944 to local.
4. transfer to test account via https://polkadot.js.org/apps/
5. access the app locally via ip+port.

**Comment by mmagician** [comment]
Hey @poria-cat
As @alxs already mentioned, he was able to start the app, but then ran into the same frontend issue as I did earlier, with tokens not showing up. We have independent setups & different OS, therefore I don't think this issue is related to our local dev environment.
The UI is a critical part of any NFT-based project and I won't be able to accept the milestone without getting it to work.

**Comment by poria-cat** [comment]
> Hey @poria-cat
> As @alxs already mentioned, he was able to start the app, but then ran into the same frontend issue as I did earlier, with tokens not showing up. We have independent setups & different OS, therefore I don't think this issue is related to our local dev environment.
> The UI is a critical part of any NFT-based project and I won't be able to accept the milestone without getting it to work. I don't see how a local setup vs. the node running in a separate server would help. I've done this for numerous projects and running substrate locally was never an issue. Furthermore, I can verify that chain storage is updated properly. Given all the "clues", it really looks like an issue in your frontend app.
> 
> Since this has already consumed plenty of our resources from 2 team members going over the same issue, this is the last opportunity before I reject the grant. I kindly ask you to revise the issue again. My suggestion is to grab a friend's laptop and try to reproduce the steps from the beginning there, in a completely new environment. Good luck!

Okay, let me try to fix this.

**Comment by mmagician** [comment]
Congratulations on completing the milestone! Here's my evaluation: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/starry_1_mmagician.md

**Pull request merged**
