### PR TITLE
Submit xmc-tools m2

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1605

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the milestone delivery and thanks @Whisker17 for the external evaluation. Please see also the comments in this [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm_tools_2_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by gmajor-encrypt** [comment]
hi, @dsm-w3f Thanks for your evaluation. This issue has been fixed. Please check again.

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the improvements and fixes. Now the example provided worked well. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm_tools_2_dsm-w3f.md). The milestone is approved. I'll forward your invoice and the payment should take place within two weeks. Great job!

**Comment by RouvenP** [comment]
hi @gmajor-encrypt we just transferred the payment.

**Pull request merged**
