### PR TITLE
Kuma Wallet M1

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1414

### CODE REVIEW

**Comment by 0xslipk** [comment]
latest version [0.0.1](https://github.com/blockcoders/kuma-wallet/releases/tag/v0.0.1)

**Comment by semuelle** [comment]
Thank you for the delivery, @0xslipk! We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @0xslipk. I am happy to report that your milestone is accepted. I have very few notes, which you can find in my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kuma-cross-chain-wallet_1_semuelle.md). Just one thing to add to that: your specifications don't mention it, but we usually ask for inline documentation. It would be great if you could add some for the next milestone.

Your invoice is missing our VAT ID and the currency. I see you didn't choose a license in your application, but please put one in your invoice so there are no misunderstandings. Thanks!

**Comment by semuelle** [comment]
Not sure why I wrote "license" instead of "currency" above. Please let me know once you have submitted an updated invoice.

**Comment by 0xslipk** [comment]
> @0xslipk, please remember to resubmit your invoice so we can process your payment, as indicated [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/795#issuecomment-1471908226).

We are gonna do it today.

**Comment by RouvenP** [comment]
hi @0xslipk we transferred the payment today.

**Pull request merged**
