### PR TITLE
Clover January 2021

### PR DESCRIPTION
**Pull request by brqgoo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @brqgoo, sorry for the late reply. With the amount of work that you have submitted, we had to take a thorough look. 

You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/0ffbaeaa5cb75fb6c2deaa754b6150f7236792eb/evaluations/clover_clover_1_semuelle.md). But to sum up, you seem to have put in a lot of work into Clover. The only problem for us is to discern which work has been done as part of the grant. If you could

- document the Clover-specific tests (or changes to tests) you have written for the most important repositories (node, wallets, services) and
- document the Clover-specific changes you made to the Ethereum pallets

I will happily sign off on the last two remaining deliverables.

**Comment by brqgoo** [comment]
Hi @semuelle please see the following for the two items you requested:
https://docs.clover.finance/technical-documentation/clover-test-cases
https://docs.clover.finance/technical-documentation/clover-evm

**Comment by semuelle** [comment]
Thanks, @brqgoo. Could you please update the delivery documentation accordingly?

**Comment by brqgoo** [comment]
> Thanks, @brqgoo. Could you please update the delivery documentation accordingly?

Sorted it.

**Comment by semuelle** [comment]
Thanks for following up on the deliverables. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/1143ebf7f5e7cce1c82a6e62cfb7262e7e747f3f/evaluations/clover_clover_1_semuelle.md) and your milestone is hereby accepted. :tada: 

I have forwarded your invoice for processing.

**Comment by brqgoo** [comment]
> Thanks for following up on the deliverables. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/1143ebf7f5e7cce1c82a6e62cfb7262e7e747f3f/evaluations/clover_clover_1_semuelle.md) and your milestone is hereby accepted. 🎉
> 
> I have forwarded your invoice for processing.

Thank you @semuelle. Will reach out grantspr@web3.foundation for public announcement!

**Comment by RouvenP** [comment]
hi @brqgoo we just sent a test transaction. Could you confirm if received?

**Comment by brqgoo** [comment]
> hi @brqgoo we just sent a test transaction. Could you confirm if received?

Yes, received it.

**Comment by RouvenP** [comment]
@brqgoo thanks for confirming, we sent the remainder.

**Pull request merged**
