### PR TITLE
DINFRA Milestone 1

### PR DESCRIPTION
**Pull request by rvalle**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1622

### CODE REVIEW

**Comment by rvalle** [comment]
@keeganquigley, @dastansam let me know if you need any assistance or need any additional information.

**Comment by dsm-w3f** [comment]
@rvalle thank you the milestone delivery and @dastansam thank you for the external evaluation. I have some doubts. For deliverable 5. SSH Key Derivation, the link provided informs that is a WIP (work in progress), and there are no instructions for testing it. This deliverable is done? How can I test it? Furthermore, I could spin up the system but there is no testing guide for inside of Apache Cloud Stack to check the application. In the API part, some routes need authentication but there are no instructions on how to authenticate. In the deliverable "Substrate Deployment Descriptors" there are some examples and documentation, but there are some executable examples ready to use that we can use to deploy some substrate network and check it in the application. I couldn't find it.

**Comment by rvalle** [comment]
Hi @dsm-w3f :

My Replies bellow:

- In the Viability study of derivation of SSH Key milestone. the viability is negative (for now). Polkadot's APIs manage the key with a proprietary format, however there is a method to export as PKCS8 which is a standard recognized by both NodeJS and OpenSSL, however is not working. Having this working will open the door to interoperability with many other things. We have reached out to the author of the code with this Issue Report: https://github.com/polkadot-js/common/issues/1858 .  Once this issue is resolved we will continue with the implementation of a KeyTool to port keys to different systems, which is the one marked WIP, as it does not entirely depend on us. The KeyTool itself will be delivered after this MVP, after milestone 2. 

There is a Test to check the interoperability in that package, but it fails and that is why is not yet included in the package main test: You can test it manually as:

```
cd packages/keytool
yarn test
```

- For When you Spin up the system you have the relevant docs are this:

Test guide: https://gitlab.com/dinfra/dinfra#testing-guide

> The standard testdeploy run will start simulating deployment lifecycles. You can log on to the Apache Cloudstack Simulator
to follow the creation, update, and destruction of Cloud Computing objects accordingly. Project, Networks, Instances, Accounts,
Domains will be created and associated with DINFRA Ids. Enablement of Projects will be required to see the instances created.

So when you enter, while the system is UP, you will see that objects are created in ACS, according to events triggered from substrate. The Substrate Network is milestone 2, but the events are currently simulated by the Test Tookit. You can enter into Domains, Accounts, Projects and you will see that the deployments and accounts have been created, you can also go to instances, enable project switch, and check that an instance is created, then it is upgraded, and finally destroyed. The simulation runs in Loops.

In the Ogate component documentation you find out how to authenticate to check the API: https://gitlab.com/dinfra/dinfra/-/tree/main/packages/ogate#authentication

> Authentication during Development and QA
If no SHARED Secret is configured via Environment Variables, a Well Known development token will be set by default.
3 development tokens for 3 different accounts (for chain reactor instances) will be generated wihtout expiry date. They can be used to test the API in the interactive playground.

You can use any of the development tokens, which are logged at the start of OGate, and check the API methods. Like getting the next event, asking for deployments or getting the deployment details.

- The deployment descriptors. The milestone focuses on documenting of deployment descriptors for substrate use cases because providers of infrastructure will need to describe their infrastructure using them. The SIMULATOR Currently uses deployment descriptors embedded into its test script to spin up Virtual Machines in the Simulator. You can find them here: https://gitlab.com/dinfra/dinfra/-/blob/main/packages/ogate/test/scripts/simulator.yml?ref_type=heads

The current descriptor focuses on delivering independent VMs like this:

```
          descriptor:
            name: vm-1
            service_offering: Small Instance
            disk_offering: Small
```

We are not simulating the creation of more complex objects, because it was not relevant for delivering the milestone. Essentially different descriptors call different Ansible playbooks into the Reactor, so, from here it is fairly easy to simulate any descriptor imaginable.

**Comment by dsm-w3f** [comment]
@rvalle thank you for the answers. I checked again and the milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by rvalle** [comment]
@dsm-w3f, @dastansam thanks for your time reviewing the milestone.

**Comment by dsm-w3f** [comment]
@rvalle W3F finance team informed me that you would prefer to receive the payment in FIAT. In this case, could you please send an amendment to the application document to change from BTC to FIAT? You don't need to disclose your FIAT payment information, this is more to have registered the right payment information.

**Comment by rvalle** [comment]
@dsm-w3f thanks I will.

**Pull request merged**
