### PR TITLE
konomi-milestone-1

### PR DESCRIPTION
**Pull request by debbiecho**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [ ] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by debbiecho** [comment]
Hi guys, can I check what is wrong here? Do I have to change anything?

**Comment by mmagician** [comment]
@debbiecho Don't worry about the failed actions. This is an unfinished workflow on our side and we are working on fixing that.
Anyway, thanks for the delivery, we'll check it as soon as we can!

**Comment by mmagician** [comment]
Just after a quick look, it seems that [your demo repo](https://github.com/konomi-network/lending-demo) is private or otherwise unavailable, and that the [hosted site](https://app.konomi.tech/) gives a 503 error.

**Comment by debbiecho** [comment]
Changed the access to public already. We took the site down to upgrade with some new UI features. Now it's up. Please have a try.
Btw, you might need to have use the invitation codes, here are 10: 
["HAAytXboVGIN","KqVznjrGGOjt","8EO5jI5dI3Kb","wJUhRVOiFuno","9U2Xx2Jkj3PT","JbDczwkogrtU","DDgHNmj52HnP","eO3FFOgQp5TV","AYGz4FDjBVOJ","1gBw2WjUahmz"]

**Comment by alxs** [comment]
@debbiecho  Just checking in: have you had any progress with the milestone?

**Comment by willeslau** [comment]
Hey guys, sorry for the late reply. We have just updated the code, will update the repo in there few days.

**Comment by mmagician** [comment]
@willeslau @debbiecho I haven't seen any progress in your codebase since you merged my last PR.
I have also asked you to **urgently** address the issue of using someone else's code without attribution which you have failed to do. As per our guidelines:
> Using others' work with no attribution or indication that this was not your own work as part of a milestone delivery will lead to immediate termination.

I would like to give you the benefit of doubt. Please address the matter within the next 7 days, or else your grant shall be terminated.

**Comment by willeslau** [comment]
@mmagician Hi, the repo is not updated because we have migrated to the parachain repo, here it is: https://github.com/konomi-network/cumulus. We were testing the parachain on Rococo and decided not to maintain two repos. Sorry for the confusion. WE have updated the links accordingly already. 
We have completely rewrote the code, please take a look. It should be more readable and organised now. We are writing the missing test cases now.

As for the swap module, the proposal was written by a previous team member. We have decided to focus on the lending module instead. You can check in the repo, there are no swap related module. Sorry for the confusion and hope this explains.

**Comment by mmagician** [comment]
@debbiecho @willeslau I found the documentation to be severely lacking. Here's the list of issues:

> The choice of InitialInterestRate, UtilizationFactor are determined by the protocol.

these are not mentioned in the equations, and as such can be confusing. One needs to look at source code to understand it. Please clarify

---
first, you say that:
`UtilizationRatio = TotalBorrow / TotalSupply+TotalBorrow`

and in the second part of the README, it's different:

`UtilizationRatio = TotalBorrow / TotalSupply`

---
in the following equations:
```
UtilizationRatio = TotalBorrow / TotalSupply
BowrrowingInterestRate = InitialInterestRate + UtilizationRatio * UtilizationFactor

Interest = InterestRate * TotalUserBorrow * (CurrentTime - LastBorrowTime) / 360
```

It's not clear whether `Interest`, `InitialInterestRate` and `InterestRate` are supposed to refer to the same variables (and are re-defined in-place), or to different ones.

---
ConvertedBorrow also has two different equations at different places in the doc.

---
Why is `ExchangeRaten` used? Does it refer to the rate of asset `n`? (but you only sum up to `n-1`).

---
> Konomi will provide an API for arbitrageurs to list the HealthIndex of all the account in ascending order

Is this part of the current version already?

---
from your docs:
> assets: asset for swap and lending

You should probably update the naming, as that's not the name of your current pallet.

---
### UI:

Not working for me.

I get: `web3Accounts: Found 0 addresses: `. Button in the centre has no text, and disappears completely upon clicking it. (This behaviour is seen both in the hosted and localhost versions).

Instructions for end-users are missing from [the frontend repo](https://github.com/konomi-network/lending-demo) - alternative would be to host your docs page where you explain both the UI and the backend logic. 

---
Lastly, it is not clear how the users should launch your node (standalone/parachain?), since [the run instructions](https://github.com/konomi-network/cumulus#run) are mostly copied from the `cumulus` repo.

Overall, please make sure that the documentation is complete and up-to-date, as this allows easier onboarding of new users and allows the community to benefit from your work, which is an outcome we highly value within the Grants Program. As per [your contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/konomi.md), this is a requirement of acceptance of Milestone 1.

**Comment by willeslau** [comment]
@mmagician cool, thank you very much for your feedback. We will update the doc accordingly!

For the UI, I think `web3Accounts: Found 0 addresses:` is because polkadot js extension is not enabled or address cannot be found. But we will make the error clearer. Thanks again.

**Comment by mmagician** [comment]
> For the UI, I think web3Accounts: Found 0 addresses: is because polkadot js extension is not enabled or address cannot be found

Well of course, but the accounts from my extension work well in other Polkadot apps, so to me it seems like the issue is on how you integrate with the polkadot-js extension. Please double check that you have retries/error handling etc. in place.

**Comment by mmagician** [comment]
@debbiecho @willeslau You haven't fixed any of the issues from my last comment nor updated the docs. This is the second warning: we will now give you time until the end of the week to address the highlighted concerns or terminate the grant otherwise.

**Comment by willeslau** [comment]
@mmagician Hi, we are working on the comments already. You can check the repo for the past commits for tackling the issues. We will get them updated this week.

**Comment by willeslau** [comment]
Hello @mmagician, we have updated our docs. They should be up to date now. At the same time, we have switched our UI to the parachain setup, now they are at: `https://parachain.konomi.tech`. The UI wallet problem should be fixed now.
Sorry for not being so responsive and taking some time for the deliverable. Because we switched to the parachain develop, at the same time, we developed some extra features, such as integration with Chainlink and preliminary cross chain multi-currency transaction, for our go-live version. But the functions mentioned in the grant are all included. We will continuously develop the repos and keep the docs updated. Please have a look.

**Comment by mmagician** [comment]
I ran into an issue compiling your cumulus fork:
```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
...
44 | assert_eq_size!(usize, u32);
...
```

**Comment by willeslau** [comment]
@mmagician May I have the command you used and your full error, like which module, which line? I seem not to have any problem.

**Comment by mmagician** [comment]
This is on running `cargo test/build` from [your pallet](https://github.com/konomi-network/cumulus/tree/develop/polkadot-parachains/pallets/floating-rate-lend). Both on stable and latest nightly builds.

**Comment by willeslau** [comment]
I just ran it, seems ok from my side:
image
Would it be possible to post the entire error? The error that you shared, I could not find the line in the pallet.
image
My guess it's one of the dependencies?

**Comment by mmagician** [comment]
Could you please reach out on element? It might be easier to debug: @marcin:web3.foundation

**Comment by willeslau** [comment]
Reached out already!

**Comment by mmagician** [comment]
You're still missing the license in your frontend project. Otherwise all looks good, [here's the draft evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/198) which I'll merge once you have fixed the license!

**Comment by mmagician** [comment]
Done! Congratulations on the completion of your milestone, I've merged the previously linked evaluation PR now.

**Comment by willeslau** [comment]
Cool, thank you very much!

**Pull request merged**
