### PR TITLE
ink! analyzer (phase 2) - milestone 5

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1904 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@davidsemakula thanks for your patience, it looks mostly good already. I had troubles with spinning up the docker infrastructure though. Feel free to have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/a9054666634bab389aed9c1ef0a7650dd53ed4dd/evaluations/ink-analyzer_5_takahser.md) for more details.

**Comment by davidsemakula** [comment]
@takahser thanks for the thorough review and feedback.

I've [pushed a fix](https://github.com/ink-analyzer/ink-analyzer/commit/c08b875e723e7f8b27399b538c00123901b26ffc) for the docker issue to the master branch.
You'll need to pull the latest changes from master, and also rebuild the docker image before running it again.

**Comment by davidsemakula** [comment]
@takahser LMK if I need to clarify anything for the docker fix.

**Review by takahser — APPROVED** [review]
@davidsemakula it's all fine, I've retested it, and it worked well! You can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer_5_takahser.md).

**Comment by davidsemakula** [comment]
Thanks for the review @takahser 🎉
I've sent the invoice via the form.

**Comment by davidsemakula** [comment]
@RouvenP just checking in since it's about 2 weeks now since the approval 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula the payment will be settled today - I will let you know as soon as done!

**Comment by RouvenP** [comment]
hi @davidsemakula the transfer is done

**Comment by davidsemakula** [comment]
Hi @RouvenP received, thanks!

**Pull request merged**
