### PR TITLE
Milestone Delivery: Escrow pallet Milestone 2 and 3

### PR DESCRIPTION
**Pull request by herou**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1094

### CODE REVIEW

**Comment by herou** [comment]
Hi @keeganquigley
Is any progress on this PR?

**Comment by keeganquigley** [comment]
> Hi @keeganquigley Is any progress on this PR?

Hi @herou sorry for the delay, I am starting the eval now. Will let you know if I have any questions.

**Comment by herou** [comment]
> > Hi @keeganquigley Is any progress on this PR?
> 
> Hi @herou sorry for the delay, I am starting the eval now. Will let you know if I have any questions.

Thank you. I really appreciate it.

**Comment by keeganquigley** [comment]
Hi again @herou apologies for the delay. Here are my initial notes regarding your delivery. Please let me know if you can make these fixes.

1. The **Application Document** link at the top needs to link to your application our repo instead of your personal one. Can you please update this?
2. The [readme](https://github.com/herou/EscrowPallet/blob/eljo-prifti/escrow/README.md) file is still just the old `substrate-node-template` text. Can you replace this with your own text instead? A finished grant typically has a nice readme with your project name at the top, along with a blurb about what your pallet does and how to use it. You can remove anything that isn't necessary for your pallet, such as the "Template Structure" section.
3. To go along with the statement above, nothing has been added to your [docs](https://docs.google.com/document/d/1XpxfrG6Qd9AHJ7OUVv3L3D6ZcEyizGh68w7yZxN3p_A/edit) since the last milestone. The docs are very sparse and don't give great examples of how to use the pallet. For example, what exactly is a **workDay**, or a **takeActionDay**? What should it look like when someone receives a payment? It would be nice if you could explain these components in detail. Screenshots showing steps to take for a few different scenarios would also be helpful. See [this readme](https://github.com/OAK-Foundation/quadratic-funding-test/blob/main/README.md) for an example of what I am looking for.
4. Your deliverable **0d. Docker** states that you will create a Dockerfile to easily spin up the node/pallet. I am not finding a Dockerfile, are you planning on implementing one? Also, the docker-compose.yml file is just the original template. Are you going to update this with your own custom image?
5. Running `cargo +nightly clippy` generates a number of warnings. Can you take a look at these to see if any of them are able to be fixed?

Please let me know if these issues can be addressed. Thanks!

**Comment by herou** [comment]
> Hi again @herou apologies for the delay. Here are my initial notes regarding your delivery. Please let me know if you can make these fixes.
> 
> 1. The **Application Document** link at the top needs to link to your application our repo instead of your personal one (otherwise it will fail the GH actions checks). Can you please update this?
> 2. The [readme](https://github.com/herou/EscrowPallet/blob/eljo-prifti/escrow/README.md) file is still just the old `substrate-node-template` text. Can you replace this with your own text instead? A finished grant typically has a nice readme with your project name at the top, along with a blurb about what your pallet does and how to use it. You can remove anything that isn't necessary for your pallet, such as the "Template Structure" section.
> 3. To go along with the statement above, nothing has been added to your [docs](https://docs.google.com/document/d/1XpxfrG6Qd9AHJ7OUVv3L3D6ZcEyizGh68w7yZxN3p_A/edit) since the last milestone. The docs are very sparse and don't give great examples of how to use the pallet. For example, what exactly is a **workDay**, or a **takeActionDay**? What should it look like when someone receives a payment? It would be nice if you could explain these components in detail. Screenshots showing steps to take for a few different scenarios would also be helpful. See [this readme](https://github.com/OAK-Foundation/quadratic-funding-test/blob/main/README.md) for an example of what I am looking for.
> 4. Your deliverable **0d. Docker** states that you will create a Dockerfile to easily spin up the node/pallet. I am not finding a Dockerfile, are you planning on implementing one? Also, the docker-compose.yml file is just the original template. Are you going to update this with your own custom image?
> 5. Running `cargo +nightly clippy` generates a high number of warnings. Can you take a look at these to see if any of them are able to be fixed?
> 
> Please let me know if these issues can be addressed. Thanks!

Hi @keeganquigley 
Thank you for your update.
1. I think the link is fine. Otherwise, the GitHub link check will fail.  Please double-check and let me know.
2. The readme has been updated.
3. The docs have been updated.
4. We are not planning to deliver a docker file. The docker file is a bunch of instructions that explain to the docker how runs it. We are keeping it from substrate-template because we used substrate-template to build our pallet. It should be fine.
5. Fixed the warnings.

**Comment by keeganquigley** [comment]
Thanks for the updates @herou, the docs are looking a lot better now. The readme also looks great! 

1. Regarding the docker file, I assumed as much, and that's no problem seeing as the project is a pallet. However, the deliverable will need to be removed from the application since it is no longer a requirement. Can you please submit a new PR to update your application with the **0d. Docker** deliverable removed from M2 and M3? (just like you did with the updated payment info). You can also remove it from this delivery.

2. The numbers on the delivery need to match the ones on your application. So instead of starting with 1., 2., 3., etc. it needs to start with 0a. License, 0b. Documentation & Tutorial, 0c. Tests, 0d. Article, 0e. Benchmarking, etc. Can you please adjust these on the delivery?

3. Your application notes that benchmarking will be provided for milestones 2 & 3. After getting rid of the Docker section can you add **0e. Benchmarking** back into the delivery and provide a link?

4. Please also add a section for `send_funds` and `withdraw_funds` modules and provide links.

5. The filename of this delivery is still the old one: `deliveries/escrow-milestone_1.md` Can you please change this to `escrow-milestone_1_2.md?`

6. I talked to the team and the **Application Document** link does need to link to our repo instead of your personal repo (I should have noticed this on the first milestone). Therefore, after you submit the amended application, please change the delivery to link to https://github.com/w3f/Grants-Program/blob/master/applications/escrow_pallet.md

7. Your submitted invoice for M2 & M3 still has the old Tron payment address. Can you please submit a new invoice with the correct ETH USDT payment address? This will be needed for payment.

I hope all of this makes sense. Please excuse the pedantry here, as the application needs to match the delivery exactly. If you can make these final adjustments I will be ready to submit my final eval. Thanks!

**Comment by herou** [comment]
> Thanks for the updates @herou, the docs are looking a lot better now. The readme also looks great!
> 
> 1. Regarding the docker file, I assumed as much, and that's no problem seeing as the project is a pallet. However, the deliverable will need to be removed from the application since it is no longer a requirement. Can you please submit a new PR to update your application with the **0d. Docker** deliverable removed from M2 and M3? (just like you did with the updated payment info). You can also remove it from this delivery.
> 2. The numbers on the delivery need to match the ones on your application. So instead of starting with 1., 2., 3., etc. it needs to start with 0a. License, 0b. Documentation & Tutorial, 0c. Tests, 0d. Article, 0e. Benchmarking, etc. Can you please adjust these on the delivery?
> 3. Your application notes that benchmarking will be provided for milestones 2 & 3. After getting rid of the Docker section can you add **0e. Benchmarking** back into the delivery and provide a link?
> 4. Please also add a section for `send_funds` and `withdraw_funds` modules and provide links.
> 5. The filename of this delivery is still the old one: `deliveries/escrow-milestone_1.md` Can you please change this to `escrow-milestone_2_3.md?`
> 6. I talked to the team and the **Application Document** link does need to link to our repo instead of your personal repo (I should have noticed this on the first milestone). Therefore, after you submit the amended application, please change the delivery to link to https://github.com/w3f/Grants-Program/blob/master/applications/escrow_pallet.md
> 7. Your submitted invoice for M2 & M3 still has the old Tron payment address. Can you please submit a new invoice with the correct ETH USDT payment address? This will be needed for payment.
> 
> I hope all of this makes sense. Please excuse the pedantry here, as the application needs to match the delivery exactly. If you can make these final adjustments I will be ready to submit my final eval. Thanks!

Hello @keeganquigley  all the points mention above are done if there is something pls let me know. Thanks
1-done
2-done
3-done
4-done
5-done
6-done
7-done

**Comment by keeganquigley** [comment]
Thanks for the changes @herou you can view my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/598). Note that one benchmarking test is failing if you can take a look at it. Just waiting for a final check. I will let the team know and forward the invoice upon merge. Good luck with the next one!

**Comment by herou** [comment]
> Thanks for the changes @herou you can view my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/598). Note that one benchmarking test is failing if you can take a look at it. Just waiting for a final check. I will let the team know and forward the invoice upon merge. Good luck with the next one!

Hi @keeganquigley Thank you for your feedback. I already pushed and fixed the benchmarking. I hope to get this PR merged as soon as possible to start working on my idea. Thanks again!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Hi @herou I’m happy to merge this and confirm that the milestone is approved, but as part of this PR you are currently deleting your old delivery. Could you update this and only add the new document?

**Comment by herou** [comment]
> Hi @herou I’m happy to merge this and confirm that the milestone is approved, but as part of this PR you are currently deleting your old delivery. Could you update this and only add the new document?

Hi @Noc2 I created a new PR with the only file you need. Please, close this PR and take this one in consideration: https://github.com/w3f/Grant-Milestone-Delivery/pull/599

**Comment by Noc2** [comment]
Thanks for the update!

**Pull request closed without merging**
