### PR TITLE
societal-grant2-m1-delivery

### PR DESCRIPTION
**Pull request by gfox1**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1450

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@okalenyk thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal2_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by gfox1** [comment]
Hi @dsm-w3f, thanks for reviewing this so quickly! We have addressed the issues in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal2_1_dsm-w3f.md) regarding the Testing Guide and the Substrate Module. The [submission repo](https://github.com/sctllabs/societal-grant-2-submission) has been update with the following [PR](https://github.com/sctllabs/societal-grant-2-submission/pull/1). 

Let us know if you need anything else. Thanks!

**Comment by dsm-w3f** [comment]
@gfox1 thank you for the improvements and fixes. I updated the evaluation document and now the milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks.

**Comment by gfox1** [comment]
Amazing, thanks @dsm-w3f!

**Comment by dsm-w3f** [comment]
@gfox1 one more thing, I almost forgot. There are some automated unit tests skipped in the test suite. Please either remove or fix them for the next milestone.

**Comment by gfox1** [comment]
@dsm-w3f, Okay thanks for letting us know. We will get that fixed. Cheers!

**Comment by RouvenP** [comment]
hi @gfox1 we transferred the payment today.

**Comment by gfox1** [comment]
Received. Thanks @RouvenP!

**Pull request merged**
