### PR TITLE
lastic-price-simulator-milestone-2.md submission

### PR DESCRIPTION
**Pull request by poppyseedDev**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2111 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @poppyseedDev for the delivery! An evaluator will take a look at it shortly.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks again @poppyseedDev and apologies for the delay. Everything looks great and is working as expected, I just have two questions:

- Can you point me to where I can find deliverable 3. Functionality Comparison? I am not finding the "validation against the broker pallet implementation".
- Can you point me to any UI unit tests or e2e tests for the tool?

**Comment by poppyseedDev** [comment]
Hei @keeganquigley thanks for your comments, here are some adjustments we did.

> * Can you point me to where I can find deliverable 3. Functionality Comparison? I am not finding the "validation against the broker pallet implementation".

We added a functionality report [link](https://github.com/LasticXYZ/price-simulation/blob/main/functionality-report.pdf)

> * Can you point me to any UI unit tests or e2e tests for the tool?

We also added some unit tests for the tool you can run them with installing

**Comment by semuelle** [comment]
@poppyseedDev, did you submit an invoice for this milestone? I can't seem to find it.

**Comment by poppyseedDev** [comment]
As told by @phillux he submitted the invoice for the milestone quite some time ago. He did it again today/yesterday. I don't know if everything is okay now or not? pls check

**Comment by semuelle** [comment]
Hey @poppyseedDev, I'm afraid we haven't received anything. The only "Lastic" invoice is from Nov 14.

**Comment by phillux** [comment]
> Hey @poppyseedDev, I'm afraid we haven't received anything. The only "Lastic" invoice is from Nov 14.

Hi @semuelle, I re-submitted the invoice via the invoice form.

**Comment by RouvenP** [comment]
hi @poppyseedDev @phillux we just sent the payment

**Pull request merged**
