### PR TITLE
Perun App Channels - Milestone 1

### PR DESCRIPTION
**Pull request by matthiasgeihs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/893

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @matthiasgeihs! We will look into it as soon as possible.
There might be delays from our side since we're currently having a rather large backlog for which I'd like to apologise in advance.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@matthiasgeihs Thanks again for the delivery and sorry for the late reply here. I took a quick look at it and everything looks really good so far. I just have one question: How did you coordinate the integration with Ajuna so far. For example one of the deliveries of the contract says the following: “We plan to coordinate with Ajuna to ensure that the app registry abstraction can later be integrated with their platform.”

**Comment by matthiasgeihs** [comment]
> @matthiasgeihs Thanks again for the delivery and sorry for the late reply here. I took a quick look at it and everything looks really good so far. I just have one question: How did you coordinate the integration with Ajuna so far. For example one of the deliveries of the contract says the following: “We plan to coordinate with Ajuna to ensure that the app registry abstraction can later be integrated with their platform.”

Hi, thanks for asking. We are in direct contact with Ajuna via a Matrix channel. I kept them in sync about the development process. Once I was finished with the concept, we had a call with one of their developers and he approved that the abstraction would be integratable with their platform. One of there developers then also reviewed the corresponding pull request: https://github.com/perun-network/perun-polkadot-pallet/pull/16, reviewed by Ajuna's cowboy-bebug.

**Review by Noc2 — APPROVED** [review]
Thanks for the quick reply. That’s exactly what I was looking for. I’m happy to tell you that the milestone is hereby accepted and I will forward your invoice internally.

**Pull request merged**
