### PR TITLE
Typechain milestone 1 Delivery

### PR DESCRIPTION
**Pull request by TtomaS7**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/992

### CODE REVIEW

**Comment by TtomaS7** [comment]
Hello, @semuelle!
any updates regarding Typechain review?

**Comment by semuelle** [comment]
@TtomaS7 Should be done by the end of the day.

**Comment by semuelle** [comment]
Hi @TtomaS7. I finally finished the evaluation. Sorry for the delay, but it took some time to get Europa running and the [test and deployment instructions](https://github.com/Supercolony-net/typechain-polkadot/tree/6702732b4e89d80d46aececb933bb0379b2ac8b7/tests/deployed#typechain-polkadot-ink) are a bit vague. But I'm happy to say that your milestone is accepted. 

It would be great if you could improve upon the inline documentation, and, like I said, the deployment instructions for the tests are a bit vague. But otherwise, everything worked nicely. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain_1_semuelle.md). 

I just checked your invoice, and it contains our old address. Could you send a new one with our new address? It's Baarerstrasse 14, 6300 Zug, Switzerland now.

**Comment by meldien** [comment]
Hi @TtomaS7, 
I noted the billing address is wrong. Could you please update the address to following:

Web 3.0 Technologies Foundation
Baarerstrasse 14
6300 Zug
Switzerland 

Many thanks. 

Best,
Melanie

**Comment by TtomaS7** [comment]
Do you mean in the invoice?

**Comment by meldien** [comment]
@TtomaS7 yes exactly.

**Comment by TtomaS7** [comment]
I have sent the updated invoice. When are you planning to handle it?

**Comment by meldien** [comment]
Thank you for the updated invoice. The invoice is now in the process to be paid

**Comment by TtomaS7** [comment]
hello!
Could you update the status of the invoice?

**Pull request merged**
