### PR TITLE
citadel_milestone_1.md

### PR DESCRIPTION
**Pull request by citadeldao**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/81

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery, @citadeldao! We will look into it as soon as possible.

**Comment by semuelle** [comment]
For reference, see also previous delivery: #225

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @citadeldao. Thanks for your submission. I have been reviewing your milestone for the past couple of days. Everything looks good, I just have two requests:

- Deliverable 0e (article/press release) is missing, and
- the .dart files seem to contain only a small subset of the code required for the mobile app. As was [pointed out](https://github.com/w3f/Grants-Program/pull/81#pullrequestreview-520508266),  we usually expect a complete, public codebase with instructions of how to build the project (the app, in this case). Could you add some instruction on how this code is supposed to be used?

**Comment by semuelle** [comment]
ping @citadeldao

**Comment by citadeldao** [comment]
> ping @citadeldao

@semuelle Hi, we are working on detailed documentation for this Dart code, and some updates around that, we are going to will publish it on this week.

**Comment by citadeldao** [comment]
@semuelle Hello, we've updated our mobile part, so that you can now access all the detailed docs for Dart code. 
https://github.com/citadeldao/polkadot/blob/main/mobiledart.md
Could you also explain about Deliverable 0e (article/press release). What is missing from our side? Would be great to connect our marketing departments to make the best of it. 
That’s what was prepared so far: https://medium.com/citadel-one/polkadot-overview-f7c4f06208ec

**Comment by cruikshankss** [comment]
Good day @citadeldao, I've taken over your evaluation while Sebastian is out of office. I've just now seen your questions, but I've got some other work ahead of this. I hope to get back to you as soon as possible next week. Thanks!

**Comment by cruikshankss** [comment]
Hello @citadeldao! 

I have reviewed the conversation here and began reviewing your deliverables as well. 

I've prepared an email to connect you with our Grants PR department. Do you happen to have an email so I can connect you? Please either comment here with your email address or directly email me at ashleyg@web3.foundation.

Regarding your deliverables, it looks like your testing guide is quite detailed (thank you sincerely), but will probably require a good amount of time for me to understand your project. Thanks for your patience!

**Comment by cruikshankss** [comment]
Hi @citadeldao,

I'd really love to complete your evaluation this week. If you're available, I'd be super interested in meeting with you for 30 mins for a live demo video call/discussion of the software architecture so I can understand the value of your project.

Tomorrow I'm free 1-2:30pm and after 3pm CET. Friday I'm free 1-2:30pm and after 4:30 CET. My time zone is UTC−07:00 which hopefully explains my availability this week. Please feel free to choose a 30-min time window. I also plan to message the other teams who have evaluations I hope to finish this week. It's a really busy week for me which is why I'm trying to schedule these demos so I can speed up my pace; my apologies for the delay. And if a time gets taken, I plan to edit this message in GitHub so please check this convo tab on GH for the latest updates. Feel free to send a calendar invite to [ashleyg@web3.foundation](mailto:ashleyg@web3.foundation) if you select a time and I plan to RSVP from there.

Otherwise, I'm also open to scheduling an Element or Discord chat. If not, absolutely no worries & thanks for your continued patience while I study your testing guide.

**Comment by citadeldao** [comment]
> Tomorrow I'm free 1-2:30pm and after 3pm CET. Friday I'm free 1-2:30pm and after 4:30 CET. My time zone is UTC−07:00

Hello @cruikshankss,
Let's talk at Friday 5.00 CET. It will be Saturday morning for us, and 8:00pm Friday for you. Is everything correct?
We've sent a calendar invite to your e-mail.

**Comment by cruikshankss** [comment]
Hi @citadeldao, thank you very much for sending the calendar invitation. I've prepared a bit by reviewing your application and milestone delivery table. Coincidentally, I love to study blockchain storage solutions and very excited to learn more about Citadel.one! 

I just want to reiterate, thank you very much for the extremely detailed testing guide. Sorry I haven't been able to study it yet and thanks for accommodating my schedule with this demo call.

**Comment by cruikshankss** [comment]
Again, congrats! [my eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/citadel-one_1_cruikshankss.md)

**Comment by cruikshankss** [comment]
May I suggest you also take a look at [this other open-source evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/signac_1_cruikshankss.md) I completed today. It has some related frontend ideas.

**Comment by takahser** [comment]
@citadeldao could you open-source your web frontend and mobile app repositories? In the grant application they were included, but in the delivery repo there were only a bunch of `.dart` files without any instructions on how to use and build them. Regarding web frontend, I found [this repo](https://github.com/citadeldao/citadel-frontend) which appears to be the frontend repo. If it's the correct one, could you add a suitable LICENSE file to it? We prefer Apache 2.0, but GPLv3, MIT or Unlicense are also acceptable.

**Comment by citadeldao** [comment]
Hello! 
Our web platform is open source, but mobile is not yet ready to be open source completely. Nowadays we are publishing only polkadot related files. Also, in the future we have plans to publish our whole mobile app and make it open source.
These files are examples of how our web libraries are used on our mobile application.
This is the scheme of our mobile application.
photo_2022-09-29_19-23-19

**Comment by fededubbi** [comment]
Good afternoon,

I noticed that on the invoice is missing our billing address:

Baarerstrasse 14,
6300, Zug.

Can you please add it and resend the invoice?
Can you please also suggest which currency you want to be paid in?

Many thanks,
Federica Dubbini

**Comment by citadeldao** [comment]
@fededubbi Hello!
We've resend our invoice, is everything okay?
Thanks

**Comment by fededubbi** [comment]
Yes, all good.
Thanks,

Federica

**Comment by RouvenP** [comment]
hi @citadeldao we transferred the payment today.

**Pull request merged**
