### PR TITLE
submit iris milestone 1

### PR DESCRIPTION
**Pull request by driemworks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/657

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, Tony. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey Tony. Sorry for the late reply, but I am now looking at your delivery. Everything looks great so far (I especially appreciate the thorough documentation), but I am unable to compile the pallet. This is on `iris_milestone_1`. Can you verify that this is compiling on your end? 

```
error[E0599]: no function or associated item named `pre_dispatch` found for struct `pallet::Pallet` in the current scope
   --> bin/node-template/pallets/template/src/mock.rs:22:1
    |
22  | / construct_runtime!(
23  | |     pub enum Test where
24  | |         Block = Block,
25  | |         NodeBlock = Block,
...   |
32  | |     }
33  | | );
    | |_^ function or associated item not found in `pallet::Pallet<mock::Test>`
    |
   ::: bin/node-template/pallets/template/src/lib.rs:140:5
    |
140 |       pub struct Pallet<T>(_);
    |       ------------------------ function or associated item `pre_dispatch` not found for this
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `pre_dispatch`, perhaps you need to implement one of them:
            candidate #1: `SignedExtension`
            candidate #2: `ValidateUnsigned`
    = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0599]: no function or associated item named `validate_unsigned` found for struct `pallet::Pallet` in the current scope
   --> bin/node-template/pallets/template/src/mock.rs:22:1
    |
22  | / construct_runtime!(
23  | |     pub enum Test where
24  | |         Block = Block,
25  | |         NodeBlock = Block,
...   |
32  | |     }
33  | | );
    | |_^ function or associated item not found in `pallet::Pallet<mock::Test>`
    |
   ::: bin/node-template/pallets/template/src/lib.rs:140:5
    |
140 |       pub struct Pallet<T>(_);
    |       ------------------------ function or associated item `validate_unsigned` not found for this
    |
    = help: items from traits can only be used if the trait is implemented and in scope
    = note: the following traits define an item `validate_unsigned`, perhaps you need to implement one of them:
            candidate #1: `SignedExtension`
            candidate #2: `ValidateUnsigned`
    = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by driemworks** [comment]
My apologies, looks like I missed a commit when I created the fork. 

The issue is the inclusion of 'ValidateUnsigned' here.
https://github.com/iridium-labs/substrate/blob/eebe9208e84bffc468b2eb4c50e6a86c6f0405d4/bin/node-template/pallets/template/src/mock.rs#L31

I've added an additional commit to the **iris_milestone_1** branch that removed 'ValidateUnsigned' as well as enhances the test suite by adding support for mocking the offchain ipfs behavior as well as more fully testing the OCW functionality.   
commit hashes: ed3e84609a12f88b99a1d7d331adccad7017c7d6 and 86819ba749a082ee79c7eacf67038e451a4bf4b3

**Comment by semuelle** [comment]
I can't find these commits on the repo, @driemworks.

**Comment by driemworks** [comment]
Thank you Sebastian! I've resubmitted the invoice with the payment address included.

**Comment by Noc2** [comment]
@driemworks we received your email to support@polkadot.network. Thanks for chasing us. I shared your latest invoice with the invoice team. Sorry for the delay here. You should receive your payment in the next two weeks.

**Comment by RouvenP** [comment]
hi @driemworks, we transferred the payment today. Thank you & apologies for the delay.

**Pull request merged**
