### PR TITLE
Tesseract dApp/Wallet Connection: milestone #2

### PR DESCRIPTION
**Pull request by dileping**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/508

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @dileping. We'll look into it as soon as possible.

**Comment by dileping** [comment]
@alxs thank you! Looking forward to your feedback. Working on the article meanwhile.

**Comment by alxs** [comment]
Thanks a lot for the detailed walkthrough and overall clean delivery, it's appreciated.

I tried running the example app as described in the guide

image

and the build failed with the following output: [build.txt](https://github.com/w3f/Grant-Milestone-Delivery/files/10286352/build.txt). What do you think could be the issue?

**Comment by alxs** [comment]
Tagging this on hold until we've signed the amendment.

Also, would you mind using the list of features for this milestone from your email in the deliverables table? That would make it much easier to verify that the functionality is implemented. Thank you.

**Comment by dileping** [comment]
Hi @alxs! Thanks for starting the review.

As for the **amendment** - I think there is a misunderstanding. As the amendment is for another grant ([SwiftAPI](https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/swift_api.md)) and this grant is totally fine and doesn't need any amendment :)

As for the error you are getting, it's probably due to missing rust targets. They can be added the following way:
```
rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
```

Please, check the **Prerequisites** section in the testing guide for more details.

**Comment by dileping** [comment]
Just in case added one more item to the prerequisites list which I just encountered during migrating to a new Mac: you might need to add `rust.pythonCommand=python3` to `local.properties`. In the guide I've also updated it and marked with **UPDATE!** marker so that no one misses it :)

**Comment by alxs** [comment]
Ah sorry, of course - my bad :)

I was able to fix the errors by adding the new targets, thanks. When you're done with the article, could you please send it to grantsPR@web3.foundation with grants@web3.foundation in cc?

**Comment by dileping** [comment]
@alxs, thank you! I'm looking forward to more of your feedback. Glad that the targets suggestion worked for you.

As for the article, I just went ahead and sent it to the addresses you gave me.

**Comment by alxs** [comment]
That is all from my side, I'm happy to let you know that the milestone has been accepted :) You can have a look at my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mobile_dapp_connection_2_alxs.md). Thanks for the clean and thoroughly explained delivery! 

I'll notify the operations team to pay out your invoice. As usual, please allow for up to 14 days for processing.

**Comment by dileping** [comment]
@alxs, thanks a lot for the fast review! Moving to the last milestone.

**Pull request merged**
