### PR TITLE
added uke-protocol milestone 1

### PR DESCRIPTION
**Pull request by CrackTheCode016**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1176 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for your delivery @CrackTheCode016, we currently have a backlog in regard to evaluations but someone will take a look at it soon.

**Comment by keeganquigley** [comment]
@CrackTheCode016 I'm taking a look at your delivery shortly and will reach out if I have any questions.

**Comment by CrackTheCode016** [comment]
@keeganquigley Hi - if you have any questions or concerns, let me know! Keen to start working on the next milestone :)

**Comment by keeganquigley** [comment]
Hi @CrackTheCode016 I apologize for the delay. We don't require milestones to be delivered sequentially, so feel free to start working on your second milestone and create a PR when ready.

1. As for this milestone, I am getting some errors when building locally on `substrate-node-template` which are stopping me from testing the pallet. 107 errors that pretty much all consist of some form of [E0277]:
```rust
error[E0277]: the trait bound `pallet_uke::Pallet<Runtime>: Callable<Runtime>` is not satisfied in `RuntimeCall`
     --> /Users/keeganquigley/substrate-node-template/runtime/src/lib.rs:312:1
      |
  312 |    construct_runtime!(
      |   _^
      |  |_|
      | ||
  313 | ||     pub struct Runtime
  314 | ||     where
  315 | ||         Block = Block,
  ...   ||
  331 | ||     }
  332 | || );
      | ||_- in this macro invocation
  ...   |
      |
      = help: the following other types implement trait `Callable<T>`:
                frame_system::Pallet<T>
                pallet_aura::Pallet<T>
                pallet_authorship::pallet::Pallet<T>
                pallet_balances::Pallet<T, I>
                pallet_grandpa::Pallet<T>
                pallet_nicks::Pallet<T>
                pallet_randomness_collective_flip::Pallet<T>
                pallet_session::pallet::Pallet<T>
              and 4 others
  note: required because it appears within the type `RuntimeCall`
     --> /Users/keeganquigley/substrate-node-template/runtime/src/lib.rs:312:1
      |
  312 |    construct_runtime!(
      |   _^
      |  |_|
      | ||
  313 | ||     pub struct Runtime
  314 | ||     where
  315 | ||         Block = Block,
  ...   ||
  331 | ||     }
  332 | || );
      | ||_- in this macro invocation
  ...   |
  note: required by a bound in `sp_runtime::generic::UncheckedExtrinsic`
     --> /Users/keeganquigley/.cargo/git/checkouts/substrate-7e08433d4c370a21/a3ed011/primitives/runtime/src/generic/unchecked_extrinsic.rs:44:40
      |
  44  | pub struct UncheckedExtrinsic<Address, Call, Signature, Extra>
      |                                        ^^^^ required by this bound in `sp_runtime::generic::UncheckedExtrinsic`
      = note: this error originates in the macro `frame_support::construct_runtime` which comes from the expansion of the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)
```
2. I rebuilt it again a second time to be sure I wasn't missing any steps. Everything checks out with `cargo check` until Step 5:

After importing the pallet with `pub use pallet_uke;` I get this error when running `cargo check -p node-template-runtime --release`:
```rust
   Compiling node-template-runtime v4.0.0-dev (/Users/keeganquigley/substrate-node-template/runtime)
error: failed to run custom build command for `node-template-runtime v4.0.0-dev (/Users/keeganquigley/substrate-node-template/runtime)`

Caused by:
  process didn't exit successfully: `/Users/keeganquigley/substrate-node-template/target/release/build/node-template-runtime-5c800e10cf6146d5/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/Users/keeganquigley/.rustup/toolchains/nightly-aarch64-apple-darwin/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/keeganquigley/substrate-node-template/target/release/wbuild/node-template-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.66.0-nightly (c0983a9aa 2022-10-12)


  --- stderr
     Compiling node-template-runtime v4.0.0-dev (/Users/keeganquigley/substrate-node-template/runtime)
  error[E0152]: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `panic_impl`.
    |
    = note: the lang item is first defined in crate `sp_io` (which `frame_support` depends on)
    = note: first definition in `sp_io` loaded from /Users/keeganquigley/substrate-node-template/target/release/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-13fee1aebc5562cc.rmeta
    = note: second definition in `sp_io` loaded from /Users/keeganquigley/substrate-node-template/target/release/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-f742abcb10114081.rmeta

  For more information about this error, try `rustc --explain E0152`.
  error: could not compile `node-template-runtime` due to previous error
```
3. I'm not sure what the cause of these errors is; I am on an M1 Apple so I will try again on an Ubuntu machine. 

4. Running `cargo clippy` in uke-pallet folder generates  13 warnings. Please check to see if any of these can be easily fixed.

I'm able to build nicks pallet successfully so let me know if you can help with these errors. Thanks!

**Comment by CrackTheCode016** [comment]
@keeganquigley thank you for this, and no worries on the wait.  

Are you using a fresh `substrate-node-template` I assume? I'll check it out in the morning, but could be a versioning /dependency issue as it appears the template has been updated since my submission.   

In the mean time, you could try building https://github.com/Uke-Messaging/uke-node for comparison. 

I'll look tomorrow and adjust any issues accordingly 👍

**Comment by keeganquigley** [comment]
> @keeganquigley thank you for this, and no worries on the wait.
> 
> Are you using a fresh `substrate-node-template` I assume? I'll check it out in the morning, but could be a versioning /dependency issue as it appears the template has been updated since my submission.
> 
> In the mean time, you could try building https://github.com/Uke-Messaging/uke-node for comparison.
> 
> I'll look tomorrow and adjust any issues accordingly 👍

I agree I think it's something along those lines. Thanks @CrackTheCode016 I will try building the uke-node tomorrow.

**Comment by CrackTheCode016** [comment]
@keeganquigley Great to hear! I'll be doing my own testing a little later today with a fresh template to spot any nuances. 

In regards to the slight change, actually, I had already submitted that change and it merged / approved, which you may find here: 

https://github.com/w3f/Grants-Program/pull/1202

Also - thank you for the correction, went ahead and changed the application pull request in the milestone submission.

Let me know if you need anything else!

**Comment by CrackTheCode016** [comment]
@keeganquigley Yep, turns out there were some naming conventions changed / dependencies updated to `polkadot-v0.9.30` that were breaking. Went ahead and updated them, so it should be working with the latest node template. 

Committed everything on this milestone's working branch, `m1-delivery`.

Resolved anything `cargo clippy` had to say as well.  Let me know if there are any issues!

**Comment by CrackTheCode016** [comment]
Also - make sure to use the `m1-delivery`, not `main` when importing the pallet like so :

```
pallet-uke = { version = "4.0.0-dev", default-features = false, git = "https://github.com/Uke-Messaging/uke-pallet.git", branch = "m1-delivery" }
```

**Comment by keeganquigley** [comment]
Thanks again @CrackTheCode016 and apologies for the delay. You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/613). Just waiting for my evaluation to be merged before accepting your milestone.

**Comment by CrackTheCode016** [comment]
@keeganquigley No worries, and thank you very much! The feedback is very helpful, will be sure to revise once the frontend is fully implemented (it's almost there anyways ;)).

**Review by Noc2 — APPROVED** [review]
The milestone is hereby accepted.

**Comment by meldien** [comment]
@CrackTheCode016 
could you please add to your invoice also your crypto address and send the invoice again?
Many thanks

**Comment by CrackTheCode016** [comment]
@meldien hi, i resubmitted with same options (fiat), but added the bitcoin address therein. let me know if you need anything else, thank you!

**Comment by CrackTheCode016** [comment]
@meldien , may I please be notified when the payment is sent? No rush, but the hash of the transaction would be appreciated. Thank you!

**Pull request merged**
