### PR TITLE
evaluation(subgame): milestone 1

### PR DESCRIPTION
**Pull request by TomaszWaszczyk**
# Milestone Delivery Checklist

- [X ] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [X ] This pull request is being made by the same account as the accepted application. 
- [ ] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [ X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by TomaszWaszczyk** [comment]
@mmagician I see a room to automate many basic verification like:

1. `cargo clippy`
2. `cargo spellcheck`
3. the presence of tests

I am not able to deliver design how to implement it, but I think that something like `Substrate Delivery Guideline` in the form of basic Github's pipelines and suggested ways how to implement those projects will be able to automate big part of my current work, and then there will be much more time to test more deeply source code and logic itself.

**Comment by TomaszWaszczyk** [comment]
Sure, every project is different one, regarding Rusty part of the project it is probably possible to find common part (the most easier part) I am not even do not want to use word `verification` but just to help developers to deliver better quality source code, need to think it over.

**Comment by xtony77** [comment]
@TomaszWaszczyk It should be the browser cache, this is the new [whitepaper](https://www.subgame.org/api/assets/whitePaper/en/White_Paper_v8.pdf) link

**Comment by mmagician** [comment]
@xtony77 As you see in this evaluation update, there are still a few issues that we'd like to ask you to address before proceeding with the acceptance of the milestone. These seem like minor things and hopefully should not take too much effort :)

**Comment by TomaszWaszczyk** [comment]
@xtony77 Thanks for the link, as the one source of truth I was checking [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/160/files#diff-3429cc6f7805248f1a79ebd7d5844662182caab60c2f7fed3d0775ffd23aeb81R19) I think you can update it. Newest version of the whitepaper works good, thanks, found some really small typos:

0. Page 5: "Although Many companies" suggested change to "Although many companies"
1. Page 5: "the world’  s well-known" suggest change to "the world’s well-known"
2. Page 11: "developers achieve one-stop application development" - I am not sure what does mean `one-stop`, correct me if I am wrong that should be `one-step`, maybe I wrong here
3. There is may times written "Relay Station Contract Agreement" does it mean "relay chain", if so I suggest to change it just to "relay chain" as it is a proper naming within Polkadot.
4. "Relay Station Contract Agreement" but from another point of view:

image

For me the picture suggests me that you want to apply Artificial Intelligence in order to implement some component for connecting to different networks - in Polkadot's terminology the component is called - "bridge" as an example of a bridge I can mention about [Interlay](https://www.interlay.io/products/) which is a trustless Bitcoin bridge for Polkadot and according to my knowledge there is no need to apply in the bridge "AI Cloud Calculation".

I think that the picture needs to be more explanatory how you want to connect to another chains. I wrote it from two reasons, first reason is that a whitepaper is also for investors and serious investors can just ask about it in the context that delivering bridge in Polkadot is far from obvious job and the part could be interesting how are you going to implement it and whether do you really need Artificial Intelligence.

And besides that all is good for me, I do hope you understand my doubts and comments, all I wrote comes from my curiosity of the technology and I want to understand more the space but also learn something new, meanwhile I do my best to share my hints and I hope meritoric doubts about technical delivering the written ideas in the whitepaper. I just share openly my doubts as a software engineer which wants to deliver working solution (or even understand an architecture) which is implement-able.

**Comment by xtony77** [comment]
@TomaszWaszczyk Thanks for your comment, our team has revised the new version of the [whitepaper](https://subgame.org/api/assets/whitePaper/en/White%20Paper_v9.pdf).

**Comment by TomaszWaszczyk** [comment]
@xtony77 Thanks, will take a look in ASAP mode (<24h) and back write.

**Pull request merged**
