### PR TITLE
High-availability validator setup - Milestone 1

### PR DESCRIPTION
**Pull request by bufta**
Delivery of the Milestone 1

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1203

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @bufta. We will look into it as soon as possible.

**Comment by keeganquigley** [comment]
Thanks for the delivery @bufta however the deliverables don't contain any links, so I'm not sure which repo/branch I'm supposed to be working out of. Is it just `substrate-raft`? I see both a master and main branch. Also, in your forked `substrate` repo I also see a `raft-validators-dev` branch. Please let me know and update with links if possible. Thank you!

**Comment by bufta** [comment]
@keeganquigley Apologies for not stating it clearly in the file. I've just updated it to include the link to the Milestone 1 repository (https://github.com/bright/substrate-raft/tree/m1).

**Comment by keeganquigley** [comment]
Thanks @bufta much appreciated. Moving on, I am getting the following [error](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/High_availability_validator_setup_milestone_1_keeganquigley.md) when running both `cargo test` and `bash docker/build.sh` and I can't figure out what the issue is. I tried downgrading to version 1.68 `nightly-2022-12-30-x86_64-unknown-linux-gnu` with no luck. This shouldn't matter for Docker though, can you confirm this is not happening with Docker on your machine?

**Comment by mgralinski-bright** [comment]
> 

We were working / testing with the rust version 'nightly-2022-08-08', and there were no issues. It looks that this problem appears since rust 1.66 and there is a [fix](https://github.com/paritytech/substrate/commit/1763ff2273c4649fa969167503951371141a0272) on it, done by Parity. We will provide a commit which will force to use a right toolchain.

**Comment by bufta** [comment]
@keeganquigley the changes are now available in `milestone-1` branch. I also updated the proposal file. If you encounter any issues with this update, please let us know.

**Comment by keeganquigley** [comment]
Thanks for the changes @bufta however I am still having a lot of issues trying to build the Docker image and getting `cargo test` to run successfully. Docker seems to always freeze at the same spot:
docker

While cargo test always runs out of disk space no matter how much I give it:

```
warning: ar: /home/ubuntu/substrate-raft/target/debug/wbuild/sp-runtime-interface-test-wasm-deprecated/target/release/build/zstd-sys-3355ae1a188f4108/out/libzstd.a: No space left on device

  error: failed to run custom build command for `zstd-sys v2.0.1+zstd.1.5.2`

  Caused by:
    process didn't exit successfully: `/home/ubuntu/substrate-raft/target/debug/wbuild/sp-runtime-interface-test-wasm-deprecated/target/release/build/zstd-sys-1dcaf6c69ff3de81/build-script-build` (exit status: 1)
```

I'm not sure if this is on my end or not at this point, but I've tried running different variations of containers with extra disk space/memory and I still can't get it to work. Perhaps you have some other tips to get it to work correctly?

**Comment by keeganquigley** [comment]
Hi @mgralinski-bright I have updated my evaluation but still having some difficulties. Perhaps it would be best to schedule a call to go over some questions. If you're so inclined feel free to email me at keegan@web3.foundation so we can set something up!

**Comment by keeganquigley** [comment]
Thanks again for the call guys, with your help I was able to successfully spin up all the validator test nodes and test out the 
--permission-resolver tags. It's cool to see the leader-follower model in action. I'm happy to pass the milestone and look forward to M2. Here you can find my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/High_availability_validator_setup_milestone_1_keeganquigley.md). I will forward your invoice internally for processing.

**Comment by RouvenP** [comment]
hi @bufta we transferred the payment today.

**Pull request merged**
