### PR TITLE
Fractapp Milestone #2

### PR DESCRIPTION
**Pull request by CryptoBadBoy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by CryptoBadBoy** [comment]
Hi
We removed auth by Twitter because we think that its function will be not popular. Now we can connect by Email or Phone. And we added payment chats from Milestone 3.

Best regards

**Comment by semuelle** [comment]
Hi Elshan, thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @CryptoBadBoy, thanks for your patience with this evaluation.

I don't have a `bin/mockgen` under `$GOPATH` (as per your Makefile), can you tell what's missing?

**Comment by CryptoBadBoy** [comment]
Hello, @semuelle
You need to install https://github.com/golang/mock
I forgot to mention this in the readme

**Comment by semuelle** [comment]
Thanks for the follow-up. I was able to run the tests with `mock`. 

Could you add the `mock` requirement to the setup instructions and address the issues with documentation described in the [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/4b673eb855025ccc501502765accde16ae552029/evaluations/fractapp_2_sapranidi.md) under Deliverable 3 and the General Notes? 

Otherwise :+1:

**Comment by CryptoBadBoy** [comment]
@semuelle, thank you! I fixed it

- [x] [mockgen](https://github.com/fractapp/fractapp-server/commit/f3e9ea2ad9e9aa478f4e51420dc39d31e8eb7634)
- [x] https://github.com/fractapp/fractapp/pull/27

**Comment by semuelle** [comment]
Thanks for following up on the documentation. Your milestone is hereby accepted. :tada: 

I will forward your invoice for processing.

**Comment by semuelle** [comment]
@CryptoBadBoy, it seems your invoice shows the wrong date, could you fix that and re-submit the form?

**Comment by CryptoBadBoy** [comment]
@semuelle, Hello
Need a date when the milestone was accepted? Or today?

The date on the invoice is when I created the pull request

**Comment by semuelle** [comment]
It's the wrong year.

**Comment by CryptoBadBoy** [comment]
@semuelle 

Sorry, I re-sent 

Thank you!

**Comment by CryptoBadBoy** [comment]
@semuelle, Hello

Please tell me how soon will the grant be sent?

Thank you!

**Comment by semuelle** [comment]
Hey Elshan. The invoices usually take a couple of days. You should hear from our finances team very soon.

**Comment by RouvenP** [comment]
hi @CryptoBadBoy we transferred the BTC.

**Comment by CryptoBadBoy** [comment]
@semuelle @RouvenP,  Thank you very much!

**Pull request merged**
