### PR TITLE
Create Awesome-Polka-1.md

### PR DESCRIPTION
**Pull request by tolgayayci**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1587

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @tolgayayci I have started the evaluation. In the meantime, the correct link for the application document should be https://github.com/w3f/Grants-Program/blob/master/applications/Awesome-Polka.md

Can you fix this so that the actions execute correctly upon merging? Thanks!

**Comment by keeganquigley** [comment]
I'm also having trouble running the website locally. I'm on the [dev](https://github.com/tolgayayci/awesome-polka/tree/dev) branch but neither `yarn dev` or `npm run dev` work to launch it on port 3000. Can you help with that? Running Jest tests doesn't seem to work either.

**Comment by tolgayayci** [comment]
Hey @keeganquigley, thanks for your evaluation.

[x] Application link updated
[X] A manual has been added to [README](https://github.com/tolgayayci/awesome-polka/blob/dev/README.md) about how to configure on local machines

There is a few tools integrated and if there is any part not clear enough let me know.

After you configured locally also jest should work, I will keep maintain the codebase on regular intervals.

**Comment by keeganquigley** [comment]
Thanks @tolgayayci you can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/awesome-polka_1_keeganquigley.md). I see you have written some input validation using Yup, however, we usually ask for unit tests as well, written with Jest or something similar, to test happy paths as well as non-happy paths and ensure that errors execute correctly. I do see that you recently submitted the hook tests. Are you able to write the API tests and include them in the delivery?

Also, this wasn't specified in the application, but our ecosystem has a different set of wallets, including Polkadot{JS}, Talisman, Subwallet, Polkawallet, etc. Is there a reason you chose to integrate EVM wallets instead? Though it's not a part of the delivery criteria and therefore not mandated, I think it might confuse users because the entire site is for the Polkadot/Kusama community, who mostly don't use these wallets (with Moonbeam being the exception).

**Comment by tolgayayci** [comment]
Hey @keeganquigley, I've added some hooks tests for API you can run again ```yarn test``` after pulled the last changes. Actually AWS Amplify generates all the code itself automatically for all API queries, mutations and I use that functions in my hooks so I thought hooks test will be good enough for this purpose.

I use EVM based at this stage because I also use Lens Protocol for authentication purposes and will integrate social features with Lens. I'll see if I can come up with a better solution for this issue in the future.

**Comment by keeganquigley** [comment]
Thanks @tolgayayci for making the changes. I was able to run the updated tests successfully. 

The last remaining issue is that I registered an account using the provided TypeForm link but never received an email like it said I should. So I haven't been able to follow the guide to make the test posts. Should I try registering again?

**Comment by tolgayayci** [comment]
You are welcome @keeganquigley,

Mail process is a manual process, I need to look at and send mails to proejct owners. I defined your wallet address and project, [defined project link](https://awesomepolka.org/projects/awesome-polka-demo). You need to visit [Awesome Polka](https://awesomepolka.org) and connect your wallet, after that look into footer and you should see a ```Dashboard``` button. If you don't see please refresh the page and make sure wallet is correct.

**Comment by keeganquigley** [comment]
Thanks for whitelisting me @tolgayayci I was able to get into the dashboard but having a few UI issues. Please see my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/awesome-polka_1_keeganquigley.md) and let me know if you are able to address the issues and/or provide fixes. Thanks!

**Comment by tolgayayci** [comment]
Hey @keeganquigley 

I reviewed the documentation and here are my answers, thanks for evaluation.

1 - At first, I thought about a mobile application, but since the site is responsive enough, I did not include it in my plans, it will not be a mobile application and I removed these icons.

2 - You need to visit your project page which I mentioned on previous comment to see reflected changes (https://awesomepolka.org/projects/awesome-polka-demo) but if you had trouble to find that I need to add a project page indicator to dashboard for better ux, thanks for suggestion.

3 - Actually image uploaded but feedback is neat, I will make strong this component to show status and detailed informations about upload process, adding below to example console output. Buttons are fixed, seems like a validation bug thanks for report, you can test it now.

Screenshot 2023-05-17 at 22 25 30

**Comment by keeganquigley** [comment]
Thanks for making the changes @tolgayayci I can now see my changes reflected using your link. The milestone is hereby accepted. Although I would agree with Noc2's assessment that it's probably best to look for alternative sources of funding after this grant, as the site is at a stage where it could now be funded via advertisements or other typical web-focused business models. Congrats on completing the grant!

**Comment by keeganquigley** [comment]
@tolgayayci I found your invoice but it isn't in English. Can you please re-upload in English so the operations team can read and process it? Also, it doesn't contain a payment address. Can you please include the same address as the one on your application? They should both match. Thanks!

**Comment by tolgayayci** [comment]
Hey @keeganquigley, I uploaded invoice in English, thanks for your support. I will excitedly working for growing Awesome Polka 👍

**Comment by RouvenP** [comment]
hi @tolgayayci we transferred the payment today

**Pull request merged**
