### PR TITLE
Dotnix: Milestone Delivery 2

### PR DESCRIPTION
**Pull request by Ra33it0**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2259

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @Ra33it0 ,

where is the testing guide and why is it not linked to?

**Comment by Ra33it0** [comment]
Hey our tests are implemented using Nix tests, to run all test you can call nix flake check --print-build-logs as mentioned in our README.
https://github.com/sporyon/dotnix-core/blob/main/README.md#testing
Let me know if you have further questions, I am here to help.

**Comment by PieWol** [comment]
Hey @Ra33it0 ,
I've published [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1202) but sadly I'm running into a few issues. Would love to hear your feedback on what might have went wrong. I assume the docker setup didn't work as expected, even though I was strictly following your tutorial. I noticed that the tarball was already existing after running ``nix build .#docker`` so I didn't download it again explicitly and instead initiated the docker instance with the existing tarball.

**Comment by PieWol** [comment]
Sadly while revisiting today and setting up a fresh docker image it didn't work out. I already texted you on element but just for transparency I'll post it here as well.

```
ubuntu@ip-172-31-20-198:~/dotnix/dotnix-core$ sudo nix build .#docker --extra-experimental-features nix-command --extra-experimental-features flakes
warning: creating lock file '/home/ubuntu/dotnix/dotnix-core/flake.lock'
warning: Git tree '/home/ubuntu/dotnix/dotnix-core' is dirty
trace: evaluation warning: system.stateVersion is not set, defaulting to 24.11. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
[1 copied (148.7 MiB), 75.8 MiB DL]Segmentation fault
```

**Comment by Ra33it0** [comment]
The issue you are referencing is a segfrault  and likely caused by a bug in nix, maybe a full disk or insufficient free memory or something completely different.
To free up space you can use $ nix-collect-garbage -d or $ docker rm -vf $(docker ps -aq); docker rmi -f $(docker images -aq)

Regarding list-dependencies, we have added it to the docker image and to allow it to working there, the code had to be rewritten slightly as the nix daemon within Docker doesn't support all necessary operations that the old implementation used. It can be tested like this: list-dependencies --all $(nix-build --no-out-link -A nano '<nixpkgs>') (hints for generating auditable paths have been added to the README)

**Comment by PieWol** [comment]
Congratulations on completing your grant. Your second and final milestone is now accepted! 🎉

**Pull request merged**
