### PR TITLE
milestone 2 supersig_fellowship

### PR DESCRIPTION
**Pull request by decentration**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1630 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by dastansam** [comment]
hey @decentration!

[here](https://github.com/w3f/Grant-Milestone-Delivery/pull/923) is the evaluation of your milestone!

**Comment by decentration** [comment]
@dastansam glad to see the eval went smoothly after that one fix 👍

**Comment by dsm-w3f** [comment]
@decentration thank you for the milestone delivery and @dastansam thanks for the external evaluation. The evaluation looks good to me. I found only some problems with docker, which may not occur in all systems. Worthwhile to check but this don't prevent the acceptance of the milestone. The milestone is accepted. I'll forward the invoice internally and the payment should take place within two weeks. Great Job! 

See the problems found with docker below:
```
docker run --rm -it --name supersig-ui -p 3000:3000  decentration/supersig-ui:latest
Unable to find image 'decentration/supersig-ui:latest' locally                                                                                                                               
latest: Pulling from decentration/supersig-ui                                                                                                                                                
5af00eab9784: Pull complete 
2965f8acff1c: Pull complete 
8bcab8bf4013: Pull complete 
cde13b50385f: Pull complete 
1855b0fd6ff7: Pull complete 
02730c2c29c3: Pull complete 
042a1e45f17f: Pull complete 
eb1410a85d91: Pull complete 
Digest: sha256:0e50482042eccfebdc476e110fe7b25381d0541b60af2c6686c7eeeac616320c                                                                                                              
Status: Downloaded newer image for decentration/supersig-ui:latest                                                                                                                           
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested                                   
exec /usr/bin/yarn: exec format error 
```

Building locally the image also presented a error. I changed the Dockerfile the line 8 from `RUN curl -SL https://deb.nodesource.com/setup_lts.x | bash -` to `RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -` and solved the problem with npm. After this, I ran docker run --rm -it --name supersig-ui -p 3000:3000 decentration/supersig-ui:latest with the local image, and the application started.

Would be nice also to fix some `cargo clippy` warnings and check yarn lint since seem that the command is not working for the frontend project.

**Comment by decentration** [comment]
@dsm-w3f thanks Diogo, in the process of fixing linting (so we can deploy the build). Regarding the docker, i think its because i pushed the image from my mac m2. I also made the change you requested. Cheers 👍

**Pull request merged**
