### PR TITLE
Polkauction - milestone delivery 3

### PR DESCRIPTION
**Pull request by CrommVardek**
# Milestone Delivery Checklist

NOTE : the last milestone's invoice would be 0, so I'm not sure that it requires an invoice. In case it still does require an invoice, I'll fill the form and check below.

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone. (NA)
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. (NA)
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/452

### CODE REVIEW

**Comment by CrommVardek** [comment]
Due to an issue with www.polkauction.io, I'd rather have this PR set on-hold for now. 

Other delivery items can be checked, but accessing www.polkauction.io may not give you the correct experience. Sorry for the inconvenience.

**Comment by takahser** [comment]
@CrommVardek thanks for the info, I've set your delivery on-hold. Once you sort out your issues you can ping us so we can have a look at the delivery. 👍

**Comment by CrommVardek** [comment]
@takahser : It's now running again. Sorry for the inconvenience caused. You can now have a look at the delivery.

**Comment by CrommVardek** [comment]
Thanks for the feedback @Noc2 , no problem, take your time :)

**Review by Noc2 — APPROVED** [review]
I’m happy to confirm that the milestone is accepted ([see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polk-auction_3_Noc2.md)). I wasn’t aware that you are not getting paid for this milestone and it was rather easy to evaluate it. Thanks for delivering it anyway. If you continue to work on the project, I recommend you focus on the UI as the next step to make it more user friendly.

**Comment by CrommVardek** [comment]
Thanks @Noc2 , your suggestions are appreciated and noted, I know there is some work to make this website more interesting.

**Pull request merged**
