### PR TITLE
Threshold Signature Implementation: Milestone 2 Delivery 

### PR DESCRIPTION
**Pull request by Fiono11**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2250

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Thanks for the milestone submission, @Fiono11. I'm still waiting for review from @burdges. In the meantime, I am testing the tutorial and I get stuck at `./olaf_cli threshold-sign-round2 --participant 1`. Until then, output looks good, but this returns the error

```sh
# ./olaf-cli threshold-sign-round2 --participant 1
Error: CliError("Failed to parse threshold public key: Base 58 requirement is violated")
```

Any suggestions what I might be missing?

**Comment by Fiono11** [comment]
> Thanks for the milestone submission, @Fiono11. I'm still waiting for review from @burdges. In the meantime, I am testing the tutorial and I get stuck at `./olaf_cli threshold-sign-round2 --participant 1`. Until then, output looks good, but this returns the error
> 
> ```shell
> # ./olaf-cli threshold-sign-round2 --participant 1
> Error: CliError("Failed to parse threshold public key: Base 58 requirement is violated")
> ```
> 
> Any suggestions what I might be missing?

What is the output of `cat threshold_public_key.json`?

**Comment by Fiono11** [comment]
> Thanks for the milestone submission, @Fiono11. I'm still waiting for review from @burdges. In the meantime, I am testing the tutorial and I get stuck at `./olaf_cli threshold-sign-round2 --participant 1`. Until then, output looks good, but this returns the error
> 
> ```shell
> # ./olaf-cli threshold-sign-round2 --participant 1
> Error: CliError("Failed to parse threshold public key: Base 58 requirement is violated")
> ```
> 
> Any suggestions what I might be missing?

Sorry, I forgot to push some fixes. Can you try again, please?

**Comment by semuelle** [comment]
Sorry for the long wait, @Fiono11. I was out this week, but I will look into it asap.

**Review by burdges — APPROVED** [review]
LGTM

Very sorry for the delay.  I missed that this was you.

**Review by semuelle — APPROVED** [review]
Your milestone is hereby accepted, @Fiono11. You can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/threshold-signature_2_semuelle.md).

If you haven't yet, please submit your invoice(s) through our [invoice form](https://forms.gle/Rv8MhXt13m7GB4MB7).

Also, please submit the article to grantsPR@web3.foundation. They will help you with the publication.

**Comment by semuelle** [comment]
@Fiono11, the invoices you submitted are denominated in EUR, although the contract is in USD. We can pay in EUR, but then the amounts don't fit. Could you resubmit both invoices?

**Comment by Fiono11** [comment]
> @Fiono11, the invoices you submitted are denominated in EUR, although the contract is in USD. We can pay in EUR, but then the amounts don't fit. Could you resubmit both invoices?

Done!

**Comment by RouvenP** [comment]
hi @Fiono11, we settled the DOT part today - fiat follows early next week

**Pull request merged**
