### PR TITLE
Create galaxy-2.md

### PR DESCRIPTION
**Pull request by 7flash**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1642

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@7flash thank you for the milestone delivery. I notice that you are committing to this PR and the repository of code, is this milestone ready to be evaluated? We need a stable version to be able to evaluate and if you still committing could cause problems during the evaluation. Please let me know if I can start evaluating.

**Comment by 7flash** [comment]
> Update galaxy-2.md

Hi @dsm-w3f thanks for clarifying

Yes it's ready now as I mentioned here https://github.com/w3f/Grants-Program/pull/1642#issuecomment-1738966988

**Comment by dsm-w3f** [comment]
@7flash thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by 7flash** [comment]
> @7flash thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

Fixed all mentioned issues in the following commits:

[Setup](https://github.com/7flash/galaxy-polkadot/commit/677ec2439541e26934107dcf91ee7134310f377e)
[Install Deno](https://github.com/7flash/galaxy-polkadot/commit/b8edfb35f5872aaed7a4faf97cc7ed315fd2b27c)
[Dockerfile Node 18](https://github.com/7flash/galaxy-polkadot/commit/9f4ebbef69a3350aa140a1e5f623f74823a6285f)
[Docker Instructions](https://github.com/7flash/galaxy-polkadot/commit/e2e3e30feec42f88eeaada8168a2c68a58717f43)
[Contract Instructions](https://github.com/7flash/galaxy-polkadot/commit/9c1221e0800c26fc14eccc3802ca2aab63eb376c)
[Manual Test Multiple Freedraw](https://github.com/7flash/galaxy-polkadot/commit/bef782bba329b4d8523bd64c2e1dcb71b21f4850)

Please, can continue evaluation now.

**Comment by dsm-w3f** [comment]
@7flash thank you for the improvements and fixes. I was able to use the application but I'm still having some problems. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by 7flash** [comment]
> @7flash thank you for the improvements and fixes. I was able to use the application but I'm still having some problems. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

I have addressed all mentioned problems in the following new commits:

[.dockerignore](https://github.com/7flash/galaxy-polkadot/commit/f54bfd4eca6da6b252350dc44668f319a56d60c1)
[Docker yarn build](https://github.com/7flash/galaxy-polkadot/commit/a551fc37d0c91c453aa6d04e40fd5d66edb0bb02)
[Contract address](https://github.com/7flash/galaxy-polkadot/commit/487d34c1a20deadc525c427cfdff3fe7e167f075)
[webui-2.dylib](https://github.com/7flash/webui/commit/d4ebd709951e6f29ca20600c1b2f08d4eb8c692d)
[pnpm pull-submodules](https://github.com/7flash/galaxy-polkadot/commit/d5b684263696e1b0f7f311eb59cca37e2c4a7aff)
[Instructions WebUI and excalidraw-assets](https://github.com/7flash/galaxy-polkadot/commit/314227415adb2d28e604656a5713ab5d54387144)

Specifically, I think you would need to run following two commands, in your case.

First, to download webui.dylib

```
pnpm pull-submodules
```

Second, to copy excalidraw-assets

```
cp ./node_modules/@galaxydo/excalidraw/dist/excalidraw-assets ./dist
```

**Comment by dsm-w3f** [comment]
@7flash thank you for the improvements and fixes. The application improved, but I still having some problems. Please see the [evaluation document ](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by 7flash** [comment]
> @7flash thank you for the improvements and fixes. The application improved, but I still having some problems. Please see the [evaluation document ](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/galaxy_2_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

Thanks for update, I have addressed all mentioned issues in the following comments in README:

[Docker Limitations](https://github.com/7flash/galaxy-polkadot/commit/26414f789e587c83693a1758f4588a3b4882f70f)
[Pull submodules](https://github.com/7flash/galaxy-polkadot/commit/dfc0da4d7d7f2897b319cc0a2fcdfd0f4a5042c8)
[Layers padding](https://github.com/7flash/galaxy-polkadot/commit/52a623942dc0aeae942929bda9c583e7e5f091e5)

Please let me know, if any improvements are needed regarding these issues.

**Comment by dsm-w3f** [comment]
@7flash thank you for the improvements and fixes. It still only some improvement points that were not handled in the documentation. This doesn't prevent the acceptance of the milestone, which is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by 7flash** [comment]
> 🪙 Please fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform?usp=pp_url&entry.1070766548=https://github.com/w3f/Grant-Milestone-Delivery/pull/1015) in order to initiate the payment process. Thank you!

Thanks, payment received!

**Pull request merged**
