### PR TITLE
Create dot_marketplace-milestone_1.md

### PR DESCRIPTION
**Pull request by varun24143**
added dot_marketplace-milestone_1

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/496

### CODE REVIEW

**Comment by varun24143** [comment]
Can you help me figure out the problem why is it failing ?

**Comment by semuelle** [comment]
> Can you help me figure out the problem why is it failing ?

see my comment in your previous PR.

**Comment by varun24143** [comment]
> > Can you help me figure out the problem why is it failing ?
> 
> see my comment in your previous PR.

Just saw the comment. So, will this version work or do I need to update it ?

**Comment by semuelle** [comment]
> will this version work or do I need to update it ?

this is fine, thanks.

**Comment by varun24143** [comment]
> > will this version work or do I need to update it ?
> 
> this is fine, thanks.

> Thank you!

**Comment by varun24143** [comment]
Hi, we have submitted the milestone 2 delivery as well. 
Could you please check and confirm if this is fine or we need to submit it as a separate PR?

**Comment by semuelle** [comment]
Hi @varun24143, thanks for the delivery of the second milestone. It is okay to submit two milestones in one PR. It might just take a tad longer for the first milestone to be approved because we merge PRs to indicate the approval of a milestone, and this way we can only merge it when both are approved.

**Comment by varun24143** [comment]
> Hi @varun24143, thanks for the delivery of the second milestone. It is okay to submit two milestones in one PR. It might just take a tad longer for the first milestone to be approved because we merge PRs to indicate the approval of a milestone, and this way we can only merge it when both are approved.

> Hi @semuelle thanks for providing the clarity on this. We will wait for the approval on these 2 milestones for now. We have started working on 3rd milestone too and hopefully, we will be able to submit that soon.

**Comment by semuelle** [comment]
Hi @varun24143, I went over the deliverables for the first milestone. Most of them I already approved, as you can see in my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/7b1ac7ae75c5c19ebface6d2e9c98be225d6b6f9/evaluations/dot-marketplace_1_semuelle.md). There were some small issues with the frontend and authentication (see below); could you fix or comment on those?

- the `authentication_service` 
  - is published under Apache, but references MIT in the `Cargo.toml` and is published under MIT license under @Loaki07. Could you fix this?
  - does not contain any tests,
  - is not integrated into the frontend (I had to look up and manually navigate to `/auth`). Are you planning to change this?
- the wallet integration loads addresses from polkadotjs, but doesn't allow selecting them.

**Comment by varun24143** [comment]
> Hi @varun24143, I went over the deliverables for the first milestone. Most of them I already approved, as you can see in my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/7b1ac7ae75c5c19ebface6d2e9c98be225d6b6f9/evaluations/dot-marketplace_1_semuelle.md). There were some small issues with the frontend and authentication (see below); could you fix or comment on those?
> 
> * the `authentication_service`
>   
>   * is published under Apache, but references MIT in the `Cargo.toml` and is published under MIT license under @Loaki07. Could you fix this?
> * Sure we will fix this, didn't notice it earlier.
>   * does not contain any tests,
> Yes, we will be writing those and update it by tomorrow EOD
>   * is not integrated into the frontend (I had to look up and manually navigate to `/auth`). Are you planning to change this?
> Yes, we will be updating the UI flow and post it asap
> * the wallet integration loads addresses from polkadotjs, but doesn't allow selecting them.
> Can you please elaborate on this point, I am not sure if I understood it correctly. Is it regarding choosing the accounts from the polkadotjs extension to be seen on the Frontend ?

**Comment by varun24143** [comment]
> > Is it regarding choosing the accounts from the polkadotjs extension to be seen on the Frontend ?
> 
> Yes. I can choose Alice and Bob only.

> Alice and Bob are just the dummy accounts, but without any functionality implemented for them in Milestone 1. We planned to keep it for getting the understanding of the `pallet_tasking` and the flow in this Milestone. 
Multi-user Module is part of Milestone 3, which we are currently working on, where any user can connect the wallet and start to create/bid for the task based on their role too.
Whereas, if you want to see the account to be shown onto the frontend coming from the polkadot js extension, then we can submit that too in this itself.

**Comment by semuelle** [comment]
> Multi-user Module is part of Milestone 3

I remember now that we had a discussion about this when you applied. Keep it in M3.

**Comment by varun24143** [comment]
> > Multi-user Module is part of Milestone 3
> 
> I remember now that we had a discussion about this when you applied. Keep it in M3.

>> Sure, so we will fix the issues mentioned for frontend and authentication_service and update you here.

**Comment by varun24143** [comment]
Hi Semuelle, we have updated the requested issues for Milestone 1
> * the authentication_service
>   * is published under Apache, but references MIT in the Cargo.toml and is published under MIT license under @Loaki07. Could you fix this?
>     * This is updated to Apache 2.0 now and can be seen here [Updated License](https://github.com/WowLabz/authentication_service/blob/main/Cargo.toml#L2-L5)
>   * does not contain any tests,
>     * Several test cases have been written and updated [here](https://github.com/WowLabz/authentication_service/blob/main/src/main.rs#L76-L243)
>   * is not integrated into the frontend (I had to look up and manually navigate to /auth). Are you planning to change this?
>     * Frontend flow has been updated as mentioned [Here](https://github.com/WowLabz/tasking_frontend/tree/Phase1_Milestone1/src)

Also you can check all these functionalities by running the docker build. Hope this covers all and we will implement the Wallet Integration part in Milestone 3 as discussed.

**Comment by semuelle** [comment]
@varun24143, I have reviewed both milestones and can report that both are accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/8fd08df6e43622a31c4e6041dca9ea7956cc087e/evaluations/dot-marketplace_1_semuelle.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/5cb71dc297ec4b75fc11cecd5bbc2449a8aa2a1f/evaluations/dot-marketplace_2_semuelle.md).

Since the `frontend` deliverable is described as `Supporting UI to test functionality`, and because I know that it is a work in progress, I accepted it as is. However, I should point out that there are some issues still, seemingly across all branches. I would kindly ask you to resolve these issues for the next milestone.

- the browser console shows several warnings (``Warning: Each child in a list should have a unique "key" prop. Check the render method of `DashBoard`. in TaskCard (at DashBoard.js:133)``, ``validateDOMNesting(...): <div> cannot appear as a descendant of <p>. in div (at TaskCard.js:182)``)
- the `taskdetails` view is empty for me except for the dark blue header and footer
- Directly opening a `taskdetails` view results in an error (``Uncaught (in promise) Error: web3FromSource: Unable to find an injected polkadot-js at web3FromSource (index.js:185)``)
- the task filters in the header in the `taskdetails` view point to the wrong URL (e.g. `http://127.0.0.1:9001/taskdetails/3#InProgress`) 

I will forward your invoices for processing.

**Comment by varun24143** [comment]
Hi @semuelle, thanks for accepting both the milestones, please see the comments below
> @varun24143, I have reviewed both milestones and can report that both are accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/8fd08df6e43622a31c4e6041dca9ea7956cc087e/evaluations/dot-marketplace_1_semuelle.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/5cb71dc297ec4b75fc11cecd5bbc2449a8aa2a1f/evaluations/dot-marketplace_2_semuelle.md).
> 
> Since the `frontend` deliverable is described as `Supporting UI to test functionality`, and because I know that it is a work in progress, I accepted it as is. However, I should point out that there are some issues still, seemingly across all branches. I would kindly ask you to resolve these issues for the next milestone.
> Yes we will definitely close it
> * the browser console shows several warnings (`` Warning: Each child in a list should have a unique "key" prop. Check the render method of `DashBoard`. in TaskCard (at DashBoard.js:133) ``, `validateDOMNesting(...): <div> cannot appear as a descendant of <p>. in div (at TaskCard.js:182)`)
> * This is a react warning and we will clear it in the coming Milestone
> * the `taskdetails` view is empty for me except for the dark blue header and footer
> * This is because when you open the dashboard, all the tasks are dummy data, since the chain starts working when you as a user create a task and then follow the task lifecycle, and hence you would have seen an empty card for task details.
> * Directly opening a `taskdetails` view results in an error (`Uncaught (in promise) Error: web3FromSource: Unable to find an injected polkadot-js at web3FromSource (index.js:185)`)
> * we will look into this, but it is mainly if an account is not there, we will do better error handling on this.
> * the task filters in the header in the `taskdetails` view point to the wrong URL (e.g. `http://127.0.0.1:9001/taskdetails/3#InProgress`)
> * Those are dummy tabs again, the funcitonality for that has not been added. The flow will be clearer with Milestone 3 onto the UI
> I will forward your invoices for processing.
> * Thank you so much for approving and acepting it

**Comment by RouvenP** [comment]
hi @varun24143, we just transferred the payment for M1.

**Comment by varun24143** [comment]
> hi @varun24143, we just transferred the payment for M1 and M2.

> hi @RouvenP Thank you, for the update. We have almost completed the milestone 3 and will be submitting that too soon.

**Pull request merged**
