### PR TITLE
Polkadot js Plus / Pool Nominations milestone delivery

### PR DESCRIPTION
**Pull request by Nick-1979**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/934

### CODE REVIEW

**Comment by Nick-1979** [comment]
Hi @lucasvanmol,

Regarding [previous PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/474#issuecomment-1168398411).

I have changed the file name. But can't squash since there are some merges in between.  Hence I send another PR. I am sorry for any inconvenience.

Cheers,
Kami | Polkadot js plus

**Comment by lucasvanmol** [comment]
Hey there @Nick-1979, I'm just testing out the new functionality of the extension now, but couldn't find a way to leave (unbond) a pool once I've joined one. Is there a way to do this that I'm missing?

**Comment by Nick-1979** [comment]
Hi @lucasvanmol,

To unbound, you need to go to **unstake** tab:

image

But consider, If you are a root member of a pool, you need to change your pool state to destroying first, and then wait untill all members exist then you can unbound.

If there is any other situation please let me know, my id on element is @nick1979:matrix.org.

For testing , do you run  `yarn test:plus` 

the result should be something like:
image

**Comment by lucasvanmol** [comment]
I'm happy to confirm that this milestone has been accepted! You can see my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-js-plus-nomination-pools_1_lucasvanmol.md), and I'll forward your invoice internally.

**Pull request merged**
