### PR TITLE
update coinversation protocol deliversy

### PR DESCRIPTION
**Pull request by conversationpro**
update coinversation protocol deliversy

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
@conversationpro thanks for the delivery, I do have some questions though:
1. It looks to me that the deliverables stated in your application and the ones listed here don't match.

2. > Please note, the DApp can't be run from the source as we don't want to commit confidential data

I'm not sure which dapp you're referring to, but for the Open Grants Program we require all source code to be open source.

3. Lastly, the testnet link you provide is fork of jupiter with no additional changes.

**Comment by conversationpro** [comment]
@mmagician Hi, sorry for the late reply. Here is what we did to fulfill the changes requested.
1. We have already corrected the listed deliverables to match the application and submitted the invoice form again
2. We understand the requirement of the Open Grants Program. That is a mistake for us. The dapp was not what we wanted to submit this time. This sentence is extra. Sorry about that. We already deleted it.
3. Currently, our development is not based on the parachain. We cannot provide the testnet link to you. We have already updated the new deliverable. 
Please feel free to ask if there any questions.

**Comment by mmagician** [comment]
Your lists still don't match. In the application I have:
1. Complete the oracle function by an off-chain worker.
3. The code will have proper unit-test coverage to ensure functionality and robustness.

In your delivery list I see neither the implementation of the oracle nor any unit tests in your project.

**Comment by conversationpro** [comment]
That was our mistake. Sorry about that. For those part you mentioned, we still have something need to improve and upgrade. Once we finished, we will upload them to you.

**Comment by mmagician** [comment]
Alright, I'm going to close this PR for now. Please open a new one once you're ready.

**Comment by alxs** [comment]
@conversationpro seeing as your delivery is already heavily delayed, may we ask you to submit within the next two weeks?

**Comment by conversationpro** [comment]
@alxs Sorry for the delay. We try to do it to the best of our ability to submit them within the next two weeks. Apologize for the delay again.

**Pull request closed without merging**
