### PR TITLE
Add DotPay milestone 2

### PR DESCRIPTION
**Pull request by AdaLam7**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/715

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by AdaLam7** [comment]
> Thanks for the delivery. We will look into it as soon as possible.

Hi,have a nice day.
Long time no your information after you last messages,nearly 8 days past.
Do you have any matter,or our milestone have any problem, or we have successfully completed milestone.
Please feel free to tell us more.
Your early reply will be more appreciates.
Best regards

**Comment by takahser** [comment]
Hi @AdaLam7 
Thanks for your patience and for reaching out again. We have currently a lot of active milestone deliveries that are being reviewed which is why we didn't find the time to review yours yet. Please allow for some more time, we'll have a look as soon as we can and give you feedback.

**Comment by semuelle** [comment]
Hey @AdaLam7, thank you for your patience. I have looked into your delivery, and I'm generally happy with it. Some small issues, though:

- The documentation seems to only be available through your website. If you could provide a Github repo or similar so others can retrieve it if you ever decide to shut down your website, that'd be great.
- The `set_whitelist` function documentation states: "only author have permission to call this function". However, I don't see how or where this is enforced, unless "author" is defined as anyone who has `deposit`ed.
- I can't seem to be able to compile the smart contracts. I get the following error messages. Can you advise?

```
   Compiling bytepay v0.1.0 (/work/w3f/code/grants/deliverables/dotpay/bytepay/smart-contract)
error[E0603]: module `collections` is private
  --> lib.rs:19:32
   |
19 |         balances: ink_storage::collections::HashMap<AccountId, Balance>,
   |                                ^^^^^^^^^^^ private module
   |
note: the module `collections` is defined here
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/lib.rs:56:1
   |
56 | pub(crate) mod collections;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0603]: module `collections` is private
  --> lib.rs:20:33
   |
20 |         whitelist: ink_storage::collections::Vec<AccountId>,
   |                                 ^^^^^^^^^^^ private module
   |
note: the module `collections` is defined here
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/lib.rs:56:1
   |
56 | pub(crate) mod collections;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0277]: the trait bound `__ink_ConstructorDecoder: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
   --> lib.rs:14:5
    |
14  | /     /// Bytepay storage
15  | |     /// Save owner, balances map and whitelist vector
16  | |     #[ink(storage)]
17  | |     pub struct Bytepay {
...   |
20  | |         whitelist: ink_storage::collections::Vec<AccountId>,
21  | |     }
    | |_____^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `__ink_ConstructorDecoder`
    |
    = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `__ink_ConstructorDecoder`
note: required by a bound in `DecodeDispatch`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_lang-3.0.0-rc9/src/reflect/dispatch.rs:653:27
    |
653 | pub trait DecodeDispatch: scale::Decode {
    |                           ^^^^^^^^^^^^^ required by this bound in `DecodeDispatch`

error[E0277]: the trait bound `__ink_MessageDecoder: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
   --> lib.rs:14:5
    |
14  | /     /// Bytepay storage
15  | |     /// Save owner, balances map and whitelist vector
16  | |     #[ink(storage)]
17  | |     pub struct Bytepay {
...   |
20  | |         whitelist: ink_storage::collections::Vec<AccountId>,
21  | |     }
    | |_____^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `__ink_MessageDecoder`
    |
    = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `__ink_MessageDecoder`
note: required by a bound in `DecodeDispatch`
   --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_lang-3.0.0-rc9/src/reflect/dispatch.rs:653:27
    |
653 | pub trait DecodeDispatch: scale::Decode {
    |                           ^^^^^^^^^^^^^ required by this bound in `DecodeDispatch`

error[E0277]: the trait bound `bytepay::_::CallBuilder: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> lib.rs:14:5
   |
14 | /     /// Bytepay storage
15 | |     /// Save owner, balances map and whitelist vector
16 | |     #[ink(storage)]
17 | |     pub struct Bytepay {
...  |
20 | |         whitelist: ink_storage::collections::Vec<AccountId>,
21 | |     }
   | |_____^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `bytepay::_::CallBuilder`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `bytepay::_::CallBuilder`
note: required by a bound in `PackedLayout`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/traits/packed.rs:32:56
   |
32 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ^^^^^^^^^^^^^ required by this bound in `PackedLayout`
   = note: this error originates in the derive macro `::ink_storage::traits::PackedLayout` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `bytepay::_::CallBuilder: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> lib.rs:14:5
   |
14 | /     /// Bytepay storage
15 | |     /// Save owner, balances map and whitelist vector
16 | |     #[ink(storage)]
17 | |     pub struct Bytepay {
...  |
20 | |         whitelist: ink_storage::collections::Vec<AccountId>,
21 | |     }
   | |_____^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `bytepay::_::CallBuilder`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `bytepay::_::CallBuilder`
note: required by a bound in `PackedLayout`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/traits/packed.rs:32:40
   |
32 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ^^^^^^^^^^^^^ required by this bound in `PackedLayout`
   = note: this error originates in the derive macro `::ink_storage::traits::PackedLayout` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `BytepayRef: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> lib.rs:14:5
   |
14 | /     /// Bytepay storage
15 | |     /// Save owner, balances map and whitelist vector
16 | |     #[ink(storage)]
17 | |     pub struct Bytepay {
...  |
20 | |         whitelist: ink_storage::collections::Vec<AccountId>,
21 | |     }
   | |_____^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `BytepayRef`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `BytepayRef`
note: required by a bound in `PackedLayout`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/traits/packed.rs:32:56
   |
32 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ^^^^^^^^^^^^^ required by this bound in `PackedLayout`
   = note: this error originates in the derive macro `::ink_storage::traits::PackedLayout` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `BytepayRef: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> lib.rs:14:5
   |
14 | /     /// Bytepay storage
15 | |     /// Save owner, balances map and whitelist vector
16 | |     #[ink(storage)]
17 | |     pub struct Bytepay {
...  |
20 | |         whitelist: ink_storage::collections::Vec<AccountId>,
21 | |     }
   | |_____^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `BytepayRef`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `BytepayRef`
note: required by a bound in `PackedLayout`
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc9/src/traits/packed.rs:32:40
   |
32 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ^^^^^^^^^^^^^ required by this bound in `PackedLayout`
   = note: this error originates in the derive macro `::ink_storage::traits::PackedLayout` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0603.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `bytepay` due to 8 previous errors
```

**Comment by AdaLam7** [comment]
1. About documents we already put it on github: https://github.com/bytepayment/bytepay/discussions/4 https://github.com/bytepayment/bytepay/discussions/8 
2. There is indeed this problem, thanks for reminding us that we will fix it as soon as possible
3. When we submit our ink contract,  ink version is v3.0.0-rc8, now ink updated to  v3.0.0-rc9, seems cargo.lock haven't work, we will update our contract code to adapt it.

**Comment by sulnong** [comment]
@semuelle We have updated our contract code.

## Set Whitelist Function
- `"author" is defined as anyone who has deposit`, yes as you said, who has deposit means he can use his own balance by set whitelist
- whitelist stores account id and its corresponding value: `whitelist: Mapping<(AccountId,AccountId), Balance>`
- contract has permission to transfer specified amount from `author` account to any account setted in `author whitelist`

## Compile And Test
- Previous code can not compiled, cause  version [3.0.0-rc9](https://github.com/paritytech/ink/releases/tag/v3.0.0-rc9) is a drastic breaking change, it removed all storage data structure but add one new named `Mapping`
- Note there still have 3 tests failed caused off-chain test environment can not update account balance correctly. See issue [#1117](https://github.com/paritytech/ink/issues/1117) for detail.

**Comment by semuelle** [comment]
Hi @AdaLam7 & @sulnong. Thank you for the quick response. I am happy to report that your milestone is accepted. 

Apart from the issues raised above, I had no problems setting up and testing your code. The only issue I found - and it's not a dealbreaker, just something users should be aware of - is that there is no on-chain store of issues to payments and the `transfer` function is only callable by the `owner`. So it would be possible to pay more or less than advertised for an issue, and the users need to trust your backend to transfer the right amount to the right receiver. 

I will forward your invoice for processing. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DotPay_2_semuelle.md).

**Comment by AdaLam7** [comment]
@semuelle Now the owner can authorize the transaction to bytepay, so there will be no mismatch of the amount received. The contract also guarantees backend to transfer the right amount to the right receiver.  In the future we will support on-chain store of issues to payments~

Thank you for your suggestion~

**Comment by AdaLam7** [comment]
@semuelle @takahser  Good afternnon：
Since we comepleted Milestone 2 it has been more than 2 weeks but we haven't received the USD yet. Could you please let me know if there is something wrong caused so that we can make rectification.
Kind regards

**Comment by semuelle** [comment]
Hi @AdaLam7, thanks for reaching out. I'm very sorry for the delay, that is my fault. You should receive the payment at the end of this week. I will personally keep an eye on it.

**Comment by RouvenP** [comment]
hi @AdaLam7 we transferred the payment last Friday. Thanks!

**Pull request merged**
