### PR TITLE
Community health Milestone 2

### PR DESCRIPTION
**Pull request by katerinabc**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1482

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the new delivery, @katerinabc. Could you document the environment variables and the setup of dependencies one needs for the local setup and tests to work?

**Comment by semuelle** [comment]
pinging @katerinabc

**Comment by katerinabc** [comment]
> Thanks for the new delivery, @katerinabc. Could you document the environment variables and the setup of dependencies one needs for the local setup and tests to work?

On it. Waiting for changes to be merged in the readme file to make the environmental variables and setup of dependencies clearer.

**Comment by katerinabc** [comment]
@semuelle 

I've updated our readme file with the requested information

https://github.com/TogetherCrew/twitter-bot/tree/main?tab=readme-ov-file#environment-variables

**Comment by semuelle** [comment]
Hi @katerinabc, thanks for the update. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/community-health-check_2_semuelle.md).

**Comment by RouvenP** [comment]
hi @katerinabc we sent the payment today

**Pull request merged**
