### PR TITLE
Add Ink playground milestone 2

### PR DESCRIPTION
**Pull request by radhe-zeeve**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1731

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @radhe-zeeve , thanks for submitting the milestone. 

Can you please adjust the link of the deliverable so it points to the work you did to fulfill this milestone? 
Also where can I see on the ink! crate docs those code examples that are runnable? Please provide me a link for that too.

Thanks!

**Comment by PieWol** [comment]
Hey @radhe-zeeve just pinging to check on you for any updates :)

**Comment by radhe-zeeve** [comment]
@PieWol  give me couple of days, will update on the requested changes.

**Comment by PieWol** [comment]
Hey @radhe-zeeve, just checking in. If you have news to share just ping me here.

**Comment by radhe-zeeve** [comment]
@PieWol  I am moving it to draft, since it has little bit of development to be done in backend. Will move it to open once it is done.

**Comment by PieWol** [comment]
Hey @radhe-zeeve ,
any updates you can share? Are you facing any challenges?

**Comment by radhe-zeeve** [comment]
Sorry, Got busy with other work in the organization. Will resume and conclude the pending tasks by this week.

**Comment by radhe-zeeve** [comment]
@PieWol added new commits for 
- Ink Playgound's backend API for compilation as requested in the issue (https://github.com/paritytech/ink-playground/issues/428) 
- and Ink repository's code example in README  to invoke the compile fuctionality if published to create docs.

**Note**: I have not created PR for either of commits since one repository is in maintenance and other because playground in not active.

**Comment by PieWol** [comment]
nice @radhe-zeeve , can you please let me know how I can properly test it? I guess it would be easy to merge your changes just in case ink! is being continued by someone?

Thanks.

**Comment by PieWol** [comment]
@radhe-zeeve , any updates?

**Comment by PieWol** [comment]
I guess we just have to wait then until the repos are out of maintenance.

**Comment by PieWol** [comment]
Hey @radhe-zeeve under the special circumstances that ink! is currently I will accept the milestone. I didn't get to test it but I could see that you correctly implemented the changes necessary. In case you are interested here is the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink_playground_2_PieWol.md). Thank you for your efforts. 🎉

**Comment by RouvenP** [comment]
hi @radhe-zeeve we transferred the payment today

**Pull request merged**
