### PR TITLE
Add cScale Milestone 1

### PR DESCRIPTION
**Pull request by MatthewDarnell**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/625

### CODE REVIEW

**Comment by MatthewDarnell** [comment]
https://github.com/MatthewDarnell/cScale -- Link to actual project

**Comment by semuelle** [comment]
Thank you for the delivery, Matthew. We will look into it as soon as possible.

**Comment by alxs** [comment]
Hi Matthew, apologies for the late reply here. I looked at your delivery and I'm happy to tell you that I found no issues with it and the delivery is a pass. You can find some minimal evaluation notes from me [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cScale_1_alxs.md). Congratulations and good luck with your next milestone. I'll forward your invoice for processing.

**Comment by RouvenP** [comment]
hi @MatthewDarnell we transferred the payment.

**Pull request merged**
