### PR TITLE
dotmog milestone 2

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is being made by the same account as the accepted application. 
- [X] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Sorry for the very late reply. I was ooo last week. I just started to look into your milestone 2 delivery and in general it looks good (see my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotmog_2_Noc2.md)). I have a number of smaller comments regarding the pallets: 

- The pallets are currently only part of a substrate fork: https://github.com/dotmog/substrate It would be nice if you could integrate them into a separate repo including a small readme. 
- The pallets don't contain any testing guide as far as I can see it
- The unit tests don't compile for me. Which rust version are you using? 

Also, it looks like you didn’t provide any article or tutorial together with this milestone. Given the grant amount, it’s not such a big issue. But I thought maybe you have an interest in actually doing something like this and potentially sharing it via our channels (via grantspr@web3.foundation) .

**Comment by darkfriend77** [comment]
Hey @Noc2 ,

Thank you for the Feedback. We will work on the points you mentioned and provide some more information and a testing guide.

**Comment by darkfriend77** [comment]
Hey @Noc2,

Thank you I took finally the time to decouple the pallet and write up some tests.

- added standalone [LINK](https://github.com/dotmog/pallet-dotmog)
- added test [LINK](https://github.com/dotmog/pallet-dotmog/blob/master/src/tests.rs)
- integrated in DOTMogNode (substrate-node-template)  [LINK](https://github.com/dotmog/DOTMogNode)

Concerning the article and/or tutorial, we will create one and submit it later if that is okay. 
We have been applying now for a follow-up grant, to work on the generic gaming chain and the Unity SDK which should create a much lower entry point for game devs in the future. 

https://github.com/w3f/Open-Grants-Program/pull/433

**Comment by Noc2** [comment]
Thanks for the update. Looks good. I will forward your invoice internally. Regarding the article, it’s not mandatory at this point since you kind of published “articles” on github anyway. But feel free to reach out to grantspr, in case you want to publish something and we should retweet it, etc.

**Comment by RouvenP** [comment]
hi @darkfriend77 we transferred the payment for M2 today.

**Pull request merged**
