### PR TITLE
Asylum: milestone 2

### PR DESCRIPTION
**Pull request by YaremenkoM**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/805

### CODE REVIEW

**Comment by lucasvanmol** [comment]
Hi there @YaremenkoM,

I'm going through the delivery now but I'm finding the documentation/testing guide for the [Unity SDK integration](https://gitlab.com/asylum-space/asylum-unity-sdk/-/tree/main) to be a bit sparse. Could you provide additional documentation as to how to use/test the plugin with some example code (for someone not so familiar with Unity)?

Thanks!

**Comment by LastSymbol0** [comment]
Hi @lucasvanmol, thanks for your response!

We've updated [Readme for Unity SDK](https://gitlab.com/asylum-space/asylum-unity-sdk/-/blob/main/README.md) to make it more detailed, hope that now it is clear enough. If there is something else to improve, will be glad to hear.

Thanks!

**Comment by lucasvanmol** [comment]
Thanks for the update, the Readme is indeed more useful, and I got it compiling in a unity project. 

However, I'm still not clear on how to use the SDK - I'm trying to run something like this:

```csharp
using Asylum; // It probably should be mentioned in the Readme that this line is needed

public class ItemsController : MonoBehaviour
{
    public ReactControllerScript reactControllerInstance;    

    void Start()
    {               
        List<AsylumItem> items = reactControllerInstance.ItemsList;
        foreach (var item in items) {
            Debug.Log(item.id);
        }
    }
}
```

But nothing gets printed to the console (I've got `asylum-ui`'s `docker-compose up` running in the background, and the UI is working fine). Does the build have to run inside `Game Developers Console` in order to work (& connect to a wallet, I assume)?

Trying to build it also gives me some errors, after going to **File > Build Settings** and selecting WebGL, then **Build**, I get:

```
/Applications/Unity/Hub/Editor/2021.3.4f1/Unity.app/Contents/il2cpp/build/deploy/il2cpp --convert-to-cpp --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Xml.Linq.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Configuration.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextRenderingModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Assembly-CSharp.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Runtime.Serialization.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.AudioModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.InputLegacyModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/mscorlib.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreTextEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UIElementsNativeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Newtonsoft.Json.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Assembly-CSharp-firstpass.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.JSONSerializeModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/Mono.Security.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Data.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.SharedInternalsModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.ImageConversionModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.TextCoreFontEngineModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.CoreModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Numerics.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Xml.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.UnityWebRequestModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/UnityEngine.IMGUIModule.dll --assembly=Library/Bee/artifacts/WebGL/ManagedStripped/System.Core.dll --data-folder=/Users/lucasvanmol/Asylum Evaluation Test/Library/Bee/artifacts/WebGL/il2cppOutput/data --generatedcppdir=/Users/lucasvanmol/Asylum Evaluation Test/Library/Bee/artifacts/WebGL/il2cppOutput/cpp --emit-method-map --dotnetprofile=unityaot-linux --profiler-report --profiler-output-file=/Users/lucasvanmol/Asylum Evaluation Test/Library/Bee/artifacts/il2cpp_conv_ujri.traceevents --print-command-line
Error: IL2CPP error for type 'System.Net.WebHeaderCollection/RfcChar' in assembly '/Users/lucasvanmol/Asylum Evaluation Test/Library/Bee/artifacts/WebGL/ManagedStripped/System.dll'
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Unity.IL2CPP.CodeWriters.ChunkedMemoryStream.Seek(Int64 offset, SeekOrigin origin) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/ChunkedMemoryStream.cs:line 107
   at Unity.IL2CPP.CodeWriters.InMemoryGeneratedMethodCodeWriter.Write(IGeneratedMethodCodeStream other) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/CodeWriters/InMemoryGeneratedMethodCodeWriter.cs:line 44
   at Unity.IL2CPP.SourceWriters.SourceWriterBase`2.FlushStream(GlobalWriteContext context, IGeneratedMethodCodeStream stream, NPath filePath) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/SourceWriters/SourceWriterBase.cs:line 56
   at Unity.IL2CPP.Contexts.Scheduling.Streams.FileLevelParallelStreamManager`3.WorkerWriteItemsToFile(WorkItemData`2 data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling.Streams/FileLevelParallelStreamManager.cs:line 39
   at Unity.IL2CPP.Contexts.Scheduling.PhaseWorkScheduler`1.WorkerLoop(Object data) in /Users/bokken/build/output/unity/il2cpp/Unity.IL2CPP/Contexts.Scheduling/PhaseWorkScheduler.cs:line 339
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

BuildFailedException: Incremental Player build failed!
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/BeeBuildPostprocessor.cs:601)
UnityEditor.WebGL.WebGlBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:158)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Modules/DefaultBuildPostprocessor.cs:28)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPipeline/PostprocessBuildPlayer.cs:370)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

Build completed with a result of 'Failed' in 20 seconds (19769 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)

UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ce] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:193 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/buildslave/unity/build/Editor/Mono/BuildPlayerWindowBuildMethods.cs:94 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:189)
```

Please advise :)

**Comment by lucasvanmol** [comment]
Hi there, 
I'm trying to build the example project but still getting the same error as above. I've tried on both Windows and MacOS but to no avail, although I'm able to build some of Unity's example projects just fine for WebGL. Perhaps we can discuss further on matrix/element? My handle is @lucas:web3.foundation . Also happy to jump on a call!

**Comment by LastSymbol0** [comment]
Am I understand you right - when you're building for webgl everything is fine?
Because that's what we need, as SDK is exactly for unity webgl build, as mentioned in our docs

If I don't understand you right - yes, let's jump to element for further discussion

**Comment by lucasvanmol** [comment]
No, sorry, I meant the WebGL build fails for the example project you provided, but I'm able to build other projects just fine. Go ahead and shoot me a message :)

**Review by Noc2 — APPROVED** [review]
I’m happy to confirm that the milestone is approved: https://github.com/w3f/Grant-Milestone-Delivery/pull/472 We will forward your invoice internally.

**Pull request merged**
