### PR TITLE
multisig management tool milestone1

### PR DESCRIPTION
**Pull request by carlhong**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery of the milestone. We will look into it as soon as possible.

**Comment by Noc2** [comment]
Thanks for the delivery. This looks really good. I quickly started to look into it and have the following comments:

- Could you change the license to Apache 2. It’s the default license of our open grants program. 
- The account injection seems to depend on the address format of the extension. For example, when I copy pasted the KSM address of the accounts in my extension into the application it doesn’t recognize that I control the account via the extension. Could you improve this or at least mention it in the tutorial? 
- When I used the substrate address in the extension for the injection it works, but then it links to the wrong accounts in the explorer. 
- In you application you said something about a backend design doc, where can I find it?

**Comment by carlhong** [comment]
@Noc2  Thanks for your review, we've updated license to Apache 2. Besides, we fix address ss58 format related issues. As for the backend part, the doc link is [here](https://www.notion.so/backend-doc-e7b4f79ede7b4d9cb39a52769c2aab2d). We currently store call data on chain in milestone 1.

**Comment by semuelle** [comment]
Hey @carlhong, I am trying to transfer KSM from a multisig using your demo, but I get `web3FromAddress: Unable to find injected <address>`, even though it shows the address as injected. Any idea what's happening?

**Comment by Noc2** [comment]
Hi @carl Thanks for the quick reply and the additional information. Just to add something: I also quickly looked into your delivery again and had some issues with the extension and the address format as well. It would be nice if you could improve this. Also according to the original proposal, you need to deliver the following “Use database or other backend service to store the index data.” or we would need to amend the contract and potentially integrate it into milestone 2.

**Comment by carlhong** [comment]
@semuelle @Noc2 The address format problem should be fixed now, sorry for the inconvenience caused. You may need to delete old multi-sig account on the demo. As for the backend part, we'll schedule that ASAP and update pr for milestone 1 when finished.

**Comment by Noc2** [comment]
Cool. Thanks for the update and let us know once it’s integrated.

**Comment by semuelle** [comment]
@carlhong Any updates on this?

**Comment by carlhong** [comment]
@semuelle @Noc2 Sorry for the late reply, we've add backend to store history call and update the delivery, please check.

**Comment by semuelle** [comment]
@carlhong, the address format seems resolved. However, now I have the following two issues. Can you advise? 

1. Transactions on Polkadot all fail with `InsufficientBalance`, although all accounts should be sufficiently funded. See [example here](https://polkadot.subscan.io/extrinsic/3603789-2).
2. Connecting to Kusama doesn't work at all, not sure what the issue is here:
```
00:46:08        API/INIT: RPC methods not decorated: system_addLogFilter, system_resetLogFilter
00:46:11.156 logger.js?eb80:63 2021-02-02 00:46:11        METADATA: Unknown types found, no types for BlockWeights, ConsumedWeight
apply @ logger.js?eb80:63
warn @ logger.js?eb80:101
validateTypes @ validateTypes.js?e6f8:28
getUniqTypes @ getUniqTypes.js?f0c6:107
getUniqTypes @ MetadataVersioned.js?6068:150
_metaFromChain @ Init.js?ad1b:340
async function (async)
_metaFromChain @ Init.js?ad1b:311
_loadMeta @ Init.js?ad1b:248
async function (async)
_loadMeta @ Init.js?ad1b:227
value @ Init.js?ad1b:75
emit @ index.js?ba10:180
value @ index.js?ec14:159
value @ index.js?ec14:273
00:46:11.170 logger.js?eb80:63 2021-02-02 00:46:11        REGISTRY: Unable to resolve type BlockWeights, it will fail on construction
00:46:11.171 logger.js?eb80:63 2021-02-02 00:46:11        REGISTRY: Error: Cannot construct unknown type BlockWeights
    at new DoNotConstruct (DoNotConstruct.js?8982:21)
    at new eval (DoNotConstruct.js?8982:27)
    at new Type (registry.js?bf4a:300)
    at initType (createType.js?fcf6:49)
    at createTypeUnsafe (createType.js?fcf6:68)
    at createType (createType.js?fcf6:83)
    at TypeRegistry.createType (registry.js?bf4a:257)
    at eval (fromMetadata.js?ac7d:27)
    at Array.reduce (<anonymous>)
    at eval (fromMetadata.js?ac7d:24)
00:46:11.171 logger.js?eb80:63 2021-02-02 00:46:11        API/INIT: Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (Init.js?ad1b:87)
00:46:11.171 logger.js?eb80:63 2021-02-02 00:46:11        API/INIT: Error: createType(BlockWeights):: Cannot construct unknown type BlockWeights
00:46:11.179 index.js?d120:254 Uncaught (in promise) Error: FATAL: Unable to initialize the API: createType(BlockWeights):: Cannot construct unknown type BlockWeights
    at EventEmitter.value (Init.js?ad1b:87)
```

**Comment by carlhong** [comment]
@semuelle the depositbase of multisig in polkadot is 20.0880 DOT [link](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/chainstate/constants), you may need more dots to do multisig extrinsics.
As for kusama network, we've upgraded polkadot package,  it should be working now.

**Comment by semuelle** [comment]
Hey @carlhong. I should have caught the issue with the deposit base myself. Sorry about that. Thanks for fixing the Kusama package. It works fine now. 

You can find my [evaluation notes here](https://github.com/w3f/Grant-Milestone-Delivery/blob/8f0cf77056780ec46e023077c0f9aeb33319b91b/evaluations/multisignature_management_tool_1_Noc2.md). Your milestone is now formally accepted. I will forward your invoice for processing.

For the next milestone delivery, could you list the deliverables based on the list of features/deliverables outlined in the [proposal](https://github.com/carlhong/Open-Grants-Program/blob/master/applications/multisignature_management_tool.md#advanced-function-more-features-for-multisig-wallet-and-support-more-network)? Thanks in advance!

**Comment by carlhong** [comment]
@semuelle Thanks for your review. Sure, we'll list the deliverables in that way for next milestone.

**Comment by RouvenP** [comment]
hi @carlhong we just sent a test transaction. Could you please confirm if received?

**Comment by carlhong** [comment]
@RouvenP We received 0.001 from 2cf3a22761513e11f749409e255e62e3d0690fe3de71993d960c2787fbd32add.

**Comment by RouvenP** [comment]
@carlhong thanks for confirming. We just sent the payment

**Pull request merged**
