### PR TITLE
submit scale-codec-comparator milestone_1

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/953

### CODE REVIEW

**Comment by takahser** [comment]
@gmajor-encrypt thanks for your delivery! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until your delivery is evaluated. Nevertheless, we're going to take a look at it as soon as we can.

**Comment by keeganquigley** [comment]
Hi @gmajor-encrypt thanks for your delivery; I have started the process of my evaluation. I will reach out to you with any questions I may have. Thanks!

**Comment by keeganquigley** [comment]
Hi again @gmajor-encrypt sorry for the delay, I was having some testing issues because of my Apple chip so I had to test on a PC as well. Everything passes except:

1 Test is currently failing when running `cd polkadot-js && npm install && npm run test`

```php
ts-jest[versions] (WARN) Version 29.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=28.0.0 <29.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
 FAIL  test/base.spec.ts
  base ffi codec
    ✓ encodes compact<u32> (81 ms)
    ✓ decode compact<u32> (1 ms)
    ✕ encodes option<bool> (46 ms)
    ✓ decode option<bool> (46 ms)
    ✓ encodes bool (54 ms)
    ✓ decode bool (1 ms)
    ✓ encode result<u32,string> (51 ms)
    ✓ decode result<u32,string> (135 ms)
    ✓ encode struct (86 ms)
    ✓ decode struct (59 ms)
    ✓ encode enum (69 ms)
    ✓ decode enum (56 ms)
    ✓ encode (u32,u32) (50 ms)
    ✓ decode (u32,u32) (51 ms)
    ✓ encodes string (63 ms)
    ✓ decode string (93 ms)
    ✓ encode [u32;6] (52 ms)
    ✓ decode [u32;6] (11 ms)
    ✓ encode vec<u32> (52 ms)
    ✓ decode <u32> (44 ms)

  ● base ffi codec › encodes option<bool>

    expect(received).toEqual(expected) // deep equality

    Expected: "01"
    Received: "0101"

      80 |     it('encodes option<bool>', (): void => {
      81 |         expect(tohex(new Option(registry, bool, null).toU8a())).toEqual(libm.option_bool_encode("NONE"));
    > 82 |         expect(tohex(new Option(registry, bool, true).toU8a())).toEqual(libm.option_bool_encode("true"));
         |                                                                 ^
      83 |         expect(tohex(new Option(registry, bool, false).toU8a())).toEqual(libm.option_bool_encode("false"));
      84 |     });
      85 |     it('decode option<bool>', (): void => {

      at Object.<anonymous> (test/base.spec.ts:82:65)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 19 passed, 20 total
Snapshots:   0 total
Time:        3.984 s
Ran all test suites.
```
Any ideas why `base.spec.ts` is failing? Thanks!

**Comment by gmajor-encrypt** [comment]
@keeganquigley The goal of scale-codec-comparator is to compare other implementations with the implementation results of https://github.com/paritytech/parity-scale-codec. If there is any failure, prove that the results of this implementation are codec with parity-scale-codec results are different.

https://github.com/gmajor-encrypt/scale-codec-comparator You can simply get the test results from the top badges.

**Comment by keeganquigley** [comment]
thanks for explaining @gmajor-encrypt yep I can see that the [PHP Test](https://github.com/keeganquigley/scale-codec-comparator/actions/runs/3070028429/jobs/4959329617) and [Go Test](https://github.com/keeganquigley/scale-codec-comparator/actions/runs/3070014845/jobs/4959299711) both run successfully in GH actions. I see your improved test case [fails](https://github.com/gmajor-encrypt/scale-codec-comparator/actions/runs/3011958229/jobs/4839569205#step:6:155) with the same error. Will note this in the eval, thanks.

**Comment by gmajor-encrypt** [comment]
@keeganquigley Thanks your review. Cheers！

**Pull request merged**
