### PR TITLE
Create signet-milestone_1.md

### PR DESCRIPTION
**Pull request by replghost**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2051

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@replghost I've added my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/signet_1_takahser.md). Feel free to fix the issues related to Testing and Documentation and to ask questions here directly in this thread, should anything be unclear.

**Comment by takahser** [comment]
@replghost FYI - I'll be out of office for the next 2 weeks. In case you deliver an update to the code and somebody should take a look before I'm back, feel free to ping @keeganquigley or @semuelle on this PR.

**Comment by replghost** [comment]
Hello @keenanquigley and @semuelle - we have addressed all of the issues that @takahser has brought up so far, and would appreciate if you could take a look. Thanks.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for your patience @replghost I took over this eval for my colleague while he is out and it looks like the requested unit tests have been written and are successful. However I'm still having trouble running it locally with `npm install` and `npm run dev`. Should I be using the `siws` repo and not the `siws-demo` repo for testing? Thanks!

```
npm run dev
npm ERR! Missing script: "dev"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

**Comment by chrisling-dev** [comment]
> Thanks for your patience @replghost I took over this eval for my colleague while he is out and it looks like the requested unit tests have been written and are successful. However I'm still having trouble running it locally with `npm install` and `npm run dev`. Should I be using the `siws` repo and not the `siws-demo` repo for testing? Thanks!
> 
> ```
> npm run dev
> npm ERR! Missing script: "dev"
> npm ERR!
> npm ERR! To see a list of scripts, run:
> npm ERR!   npm run
> ```

Hey thanks for the review! You should be using `siws-demo` repo for testing. Could you double check that you're in the right repo? The `package.json` does have the `dev` script for `siws-demo` https://github.com/TalismanSociety/siws-demo/blob/main/package.json

**Comment by keeganquigley** [comment]
Thanks for your help @chrisling-dev it's working now in the demo repo. I'm willing to go ahead and pass the milestone, and here you can find the [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/signet_1_takahser.md). Thanks for your hard work and looking forward to the next one!

**Pull request merged**
