### PR TITLE
Sequester milestone 1 delivery

### PR DESCRIPTION
**Pull request by esbrown**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/932

### CODE REVIEW

**Comment by takahser** [comment]
@esbrown thanks for your delivery. We're currently experiencing a large backlog due to various reasons (sick leaves, company trips, internal changes). Hence, a longer than usual waiting time is likely. Nevertheless, we'll try to evaluate your deliveries as soon as possible.

**Comment by lucasvanmol** [comment]
Hi there @esbrown,

I'm in the process of evaluating this delivery but have run into some issues with the example node. I've outlined them in the in-progress evaluation here: 

https://github.com/lucasvanmol/Grant-Milestone-Delivery/blob/sequester-m1/evaluations/sequester_1_lucasvanmol.md

Could you address the issues mentioned? Thanks!

**Comment by esbrown** [comment]
Hi @lucasvanmol, thanks for the initial comments and for looking into this quickly.  We’ve addressed the article issues, removed the “make test” section from the example node README (this was a mistake, there are no tests in the node, only the pallet).

We are now seeing the same issue regarding exit code 137 and are looking into it.  We will update here when it’s updated and resolved!  Thanks again.

**Comment by brendanedelson** [comment]
@lucasvanmol are you using an M1 Mac?

The docker files are running fine for us on non-M1 macs, but are hitting the error you mentioned on an M1 mac. We tested running docker with the generic [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template) and got the same error, so this looks like a larger compatibility issue.

Is there a non-M1 mac available to evaluate the grant? I have also started a thread in the [substrate stack exchange](https://substrate.stackexchange.com/questions/3442/substrate-node-template-docker-crashes-on-m1-macs).

**Review by Noc2 — APPROVED** [review]
I’m happy to confirm that milestone is accepted, see https://github.com/w3f/Grant-Milestone-Delivery/pull/475

**Comment by RouvenP** [comment]
hi @brendanedelson @esbrown we transferred the payment yesterday. Thanks!

**Pull request merged**
