### PR TITLE
hamster milestone 1 delivery

### PR DESCRIPTION
**Pull request by ltmuyuan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/789

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @ltmuyuan. We will look into it as soon as possible.

**Comment by LwwL-123** [comment]
Thank you for your use, for the installation of wails, we are using the operating system ubuntu20 and the go version is 17.2. The implementation of the install wails command is as follows.

WechatIMG376

1611648618258_ pic

Then configure the path, the documentation has been added to [hamster-client](https://github.com/hamster-shared/hamster-client#233-system-check), add the following statement to ~/.bash_profile: `export GOROOT=/usr/local/go`, Replace `/usr/local/go` with your go directory, and run `source ~/.bash_profile`. The specific installation process can be viewed on the [wails official website](https://wails.io/docs/gettingstarted/installation)


Also:
- Regarding the docker-compose startup node issue, you need to change YourOwnPath and YourNodeName to start successfully, to avoid ambiguity, we have updated docker-compose.

- Regarding missing the libvirt-dev package, I'm sorry we missed it, but it has been updated [README](https://github.com/hamster-shared/hamster-provider#21-server-project)

**Comment by LwwL-123** [comment]
Thank you for your reply, for docker-compose, I am sorry for misunderstanding you, we have updated docker-compose now.

For the 3100 port unreachable issue, we found that the tutorial we provided only has build but not run on the frontend, you should use `npm run serve`, the documentation has been fixed now.

As for the api issue, we have fixed it, please check the latest [pull](https://github.com/hamster-shared/hamster-provider/pull/15
).

**Comment by semuelle** [comment]
Hey @LwwL-123, thanks for the update. 

I was now able to change the settings, set up my resource and start the service from the frontend. I'm overall quite impressed with the system. The only things I haven't been able to do are:

- building the hamster client. `wails build` fails with 

```sh
    -  Building for production...
     ERROR  TypeError: Cannot read properties of undefined (reading 'NormalModule')
    TypeError: Cannot read properties of undefined (reading 'NormalModule')
        at VueLoaderPlugin.apply (/home/sebastian/work/w3f/code/grants/deliverables/hamster/hamster-client/frontend/node_modules/vue-loader-v16/dist/pluginWebpack5.js:44:47)
        at webpack (/home/sebastian/work/w3f/code/grants/deliverables/hamster/hamster-client/frontend/node_modules/@vue/cli-service/node_modules/webpack/lib/webpack.js:51:13)
        at /home/sebastian/work/w3f/code/grants/deliverables/hamster/hamster-client/frontend/node_modules/@vue/cli-service/lib/commands/build/index.js:200:5
        at new Promise (<anonymous>)
        at build (/home/sebastian/work/w3f/code/grants/deliverables/hamster/hamster-client/frontend/node_modules/@vue/cli-service/lib/commands/build/index.js:199:10)
        at async /home/sebastian/work/w3f/code/grants/deliverables/hamster/hamster-client/frontend/node_modules/@vue/cli-service/lib/commands/build/index.js:89:7
    
Error: exit status 1
```

- successfully run all unit tests on the provider pallet:

```sh
---- tests::it_works_for_default_value stdout ----
thread 'tests::it_works_for_default_value' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', pallets/provider/src/tests.rs:11:9
```

- connecting the a purchased resource. The client (the binary, as I wasn't able to build it locally) crashes when I click `Link` and enter the port number with the following console output:

```sh
signal 11 received but handler not on signal stack
fatal error: non-Go code set up signal handler without SA_ONSTACK flag

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x7fad069037ba
```

Can you tell me what I might be missing here?

**Comment by LwwL-123** [comment]
- About wails build failure, this is a wails and webpack compatibility issue, we have fixed it, please pull the code, delete `dist`, `node_modules`, `package-lock.json` from the frontend directory where you compiled before, then go to the root directory and re-wails build. If you continue to get errors, please try changing the node version to 14, and contact us if you have any questions.

- As for problem 2, the test error, we have fixed it.

- As for issue 3, the crash after connecting, it is due to the IP restriction of our gateway server, you can't connect to gateway. Since gataway is under development and planned to be delivered in milestone 2, only specific gateway nodes are currently supported, we have now replaced the gateway nodes that can be connected, the program crash problem has been fixed, you need to execute `rm -rf ~/.hamster-provider/config` to delete the original config file.

**Comment by semuelle** [comment]
Thanks for the update, @LwwL-123. Everything is working now. The `wails` issue was indeed not present with node lts/fermium.

I'm happy to report that your milestone is accepted. Congratulations. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hamster_1_semuelle.md). 

I cannot find an invoice from you in our books. Could you, if you haven't yet, submit your invoice for this milestone through our [invoice form](https://docs.google.com/forms/d/18BdmYEt8gvcC-5f7TMHdJftBr9dEeA2_lUfIqkH7it8/viewform)? Please make sure that all the info that is mentioned in the form (your address, W3F's address, payment address, currency, etc.) is included in the invoice itself. Thank you.

**Comment by LwwL-123** [comment]
I'm happy to hear that, thanks. It looks like the invoice submission system has been updated and we have resubmitted the invoice, please contact us if you have any questions.

**Comment by semuelle** [comment]
Thanks, @LwwL-123. The invoice is missing *your* company information, though. Can you resubmit with that added, please?

`Your invoice contains your company info, consisting of name, address and if applicable VAT ID [...]`

**Comment by LwwL-123** [comment]
Thank you for your reply, our company is still established, we are currently in the technical development stage, operating as a team, we will set up a company afterwards, can we write our own company information as our own team information?

**Comment by semuelle** [comment]
Can you clarify what you mean by "our own company information"? Legally, we need a name and address of the recipient of the money. This can be an individual or an organisation.

**Comment by LwwL-123** [comment]
Thank you for your reply, the latest invoice has been submitted, please check it and continue to contact us if you have any questions

**Comment by fededubbi** [comment]
Good afternoon,

Can you please update the invoice with your address and send it back to invoices@web3.foundation?

Many thanks,
Regards,

Federica Dubbini

**Comment by LwwL-123** [comment]
Of course, we have sent the email, please check it

**Comment by LwwL-123** [comment]
OK, we've resent it

**Comment by RouvenP** [comment]
hi @LwwL-123, we transferred the payment today. Thanks!

**Comment by ltmuyuan** [comment]
hi @RouvenP,Received with thanks.

**Pull request merged**
