### PR TITLE
Milestone Delivery: Green Lemon Protocol🍋 Milestone 1

### PR DESCRIPTION
**Pull request by wuyahuang**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1096

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@wuyahuang thank you for the submission of M1 for evaluation. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/green-lemon_1_dsm-w3f.md) and provide proper answers or fixes for the comments. After that, let me know and I'll continue with the evaluation.

**Comment by wuyahuang** [comment]
@dsm-w3f Thank you for your valuable feedback. We have made the updates to the documentation and source code.

1. License
2. User Documentation / Testing guide:
[README.md](https://github.com/GreenLemonProtocol/dksap-polkadot/blob/main/README.md) is already updated.

3. Automated Testing
Add assertions to test total_supply & Error handling(`NotAllowed`), and we are still considering constructing the invalid signatures to trigger the signature error.

4. Static Analysis
Fix warnings from `cargo +nightly clippy` [Git commit](https://github.com/GreenLemonProtocol/dksap-polkadot/commit/c71462fa0525e6cc3c6ba34d8835a24dc4efbaa4)

5. Scripts
6. Code documentation
Support cargo doc. Review docs by executing `cargo doc --open`

7. Other
The methods `ApprovalForAll` and `set_approval_for_all` are not required because each token owner is a different, one-time encrypted address. Please check the PR [Update GreenLemon.md](https://github.com/w3f/Grants-Program/pull/1133)

Currently, user transactions are sent free of charge by relayer. This is impossible in the production environment, so we need to modify the relayer in milestone 2. We will add a deposit function to NFT so that users can deposit tokens into contracts, and then transfer the token to the relayer based on zero-knowledge proof. In practice, the relayer service is a decentralized network. Anyone can be running the relayer server to forward anonymous transactions.

**Comment by dsm-w3f** [comment]
@wuyahuang Thank you for the review and improvements. Only for clarification, the source code documentation question was about the documentation of the method not being present in the html generated by cargo docs. I was able to open the documentation and saw that even though there are comments on the top of each method in the ERC721 contract, they are not being transported to html documentation. As ERC721 is a standard, It is not complicated to figure out what each method and parameter means, although this shouldn't be necessary if the documentation is available. This is just for improvement. The evaluation was approved. Great work! See you at the next milestone delivery.

**Review by Noc2 — APPROVED** [review]

**Comment by dsm-w3f** [comment]
@wuyahuang Thank you again for your delivery. Your invoice was forwarded internally. The payment should take place within two weeks.

**Comment by RouvenP** [comment]
hi @wuyahuang we transferred the payment today.

**Pull request merged**
