### PR TITLE
Validator Monitoring Service Milestone 1

### PR DESCRIPTION
**Pull request by avtishin**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1791

### CODE REVIEW

**Comment by Ali-Usama** [comment]
Hi @avtishin, I'm having this error with `docker-compose -f docker-compose.yml -f polkadot.yml up`

```
 => CANCELED [bot 4/6] RUN pip3 install -r requirements.txt                                                                                                        62.6s
 => [polkadot_events_exporter linter 1/4] FROM docker.io/golangci/golangci-lint:v1.53-alpine@sha256:b61d8503f0ad16499c023772301ec8c0f2559bf76c28d228c390446c5e647f  0.0s
 => [polkadot_events_exporter builder 1/6] FROM docker.io/library/golang:1.20-alpine@sha256:03278bc16e1a5b4fb6cdd3462108c060aa1e9c2353ce4d15d744b3c40168677d        0.0s
 => CACHED [polkadot_events_exporter stage-2 1/3] FROM docker.io/library/alpine:3.17@sha256:f71a5f071694a785e064f05fed657bf8277f1b2113a8ed70c90ad486d6ee54dc        0.0s
 => [polkadot_events_exporter internal] load build context                                                                                                          0.0s
 => => transferring context: 736B                                                                                                                                   0.0s
 => CACHED [polkadot_events_exporter builder 2/6] WORKDIR /build/                                                                                                   0.0s
 => CACHED [polkadot_events_exporter linter 2/4] WORKDIR /build/                                                                                                    0.0s
 => CACHED [polkadot_events_exporter linter 3/4] COPY . .                                                                                                           0.0s
 => ERROR [polkadot_events_exporter linter 4/4] RUN golangci-lint run                                                                                              58.9s
 => CACHED [polkadot_finality_exporter stage-1 1/8] FROM docker.io/library/python:3.11-slim-buster@sha256:c46b0ae5728c2247b99903098ade3176a58e274d9c7d2efeaaab3e06  0.0s
 => [polkadot_finality_exporter linter 1/4] FROM docker.io/alpine/flake8:latest@sha256:650d28dc43cba13893a0a4f79dcf30d27f87c1d8410d90663deb32fbaeccdbd1             0.0s
 => [polkadot_common_exporter internal] load build context                                                                                                          0.0s
 => => transferring context: 177B                                                                                                                                   0.0s
 => CANCELED [polkadot_common_exporter stage-1 2/8] RUN apt-get update && apt-get install -y gcc g++                                                               58.4s
 => [polkadot_finality_exporter internal] load build context                                                                                                        0.0s
 => => transferring context: 177B                                                                                                                                   0.0s
 => CANCELED [polkadot_finality_exporter stage-1 2/8] RUN apt-get update && apt-get install -y gcc g++                                                             58.4s
 => CACHED [polkadot_common_exporter linter 2/4] WORKDIR /apps/                                                                                                     0.0s
 => CACHED [polkadot_common_exporter linter 3/4] COPY . /apps/                                                                                                      0.0s
 => CACHED [polkadot_common_exporter linter 4/4] RUN flake8 --ignore="E501" *.py                                                                                    0.0s
------
 > [polkadot_events_exporter linter 4/4] RUN golangci-lint run:
#0 58.76 level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/sirupsen/logrus\""
#0 58.76 level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"github.com/sirupsen/logrus\"\n\n"
------
failed to solve: process "/bin/sh -c golangci-lint run" did not complete successfully: exit code: 3
```

Can you please look into it? 
Thank you

**Comment by avtishin** [comment]
Hey @Ali-Usama thanks for noting, I believe that` RUN golangci-lint run --timeout=180s` will help, we already added this to the corresponding Docker file (exporters/events/Dockerfile)

**Comment by dsm-w3f** [comment]
@avtishin thank you for the milestone delivery and @Ali-Usama for the external evaluation. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/validator_monitoring_service_1_dsm-w3f.md) and provide the proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by avtishin** [comment]
@dsm-w3f thank you for such deep evaluation. We will prepare all requested changes)

**Comment by avtishin** [comment]
@dsm-w3f hey, hope you are well. Please, take a look at the repo once again, we incorporated all requested changes. Now you should be able to run all exporters, use a tg bot that sends you a link to your dashboard, and track metrics. As well as links are fixed. 
Moreover, I need to notice that /promalert is extensive in the current Milestone. This part relates to “Telegram bot adding alerting based on events” part will be made during the second Milestone. Full functionality of /promalert is expected in the 2nd Milestone. The option is added as a preparation for the 2nd Milestone (from the development perspective it was much easier to implement the option when we were working on a tg bot but full functionality for tg alerting will be released next). I hope I’m not being confusing)

**Comment by dsm-w3f** [comment]
@avtishin thank you for the improvements and fixes. This time the bot didn't starter because of a problem in one of the docker containers. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/validator_monitoring_service_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by avtishin** [comment]
@dsm-w3f Actually, it looks like a local problem. One of the packages did not download for some reason. Is your internet connection stable? I suggest cleaning everything saved from the previous run using `make clean` or `docker-compose -f docker-compose.yml -f kusama.yml -f polkadot.yml down -v`. 
We have tested the latest version and we do not find this issue. 
Please, let us know if the problem remains.

**Comment by dsm-w3f** [comment]
@avtishin thank you for the answer. I tried again with another machine and internet connection and had the same problem. Are you sure that is not a cache problem on your side?


I ran `docker system prune -a --volumes` before building and running the containers with docker compose. Make sure to stop all containers before running this command.


I also noticed that the package that is producing the problem (aiogram) is not with the specific version set in the requirements.txt, also the code used looks like based on an [outdated example of telegram webhook](https://docs.aiogram.dev/en/v2.25.1/examples/webhook_example_2.html). Maybe by building all images you could reproduce the error or set the proper version in the requirements.txt to fix it.

Let me know when I can continue this evaluation.

**Comment by avtishin** [comment]
@dsm-w3f hey, you are right. they released a new package version just after our last submission without backward compatibility. We added versions numbers in requirements.txt. You can continue. Thanks!

**Comment by semuelle** [comment]
pinging @avtishin

**Comment by avtishin** [comment]
@Ali-Usama @semuelle Sorry, guys, we remember, need some more time to fix

**Comment by avtishin** [comment]
@dsm-w3f please, take a look. I made a number of fixes. Once again, sorry for the delay

**Comment by dsm-w3f** [comment]
@avtishin thank you for the improvements and fixes. The milestone is approved. Please use the link below to submit the invoice. After that, the payment should take place within two weeks. Great job!

**Comment by avtishin** [comment]
@dsm-w3f Thanks; the invoice is submitted. I am looking forward to completing the second milestone)

**Comment by avtishin** [comment]
@dsm-w3f hey, we submitted an invoice more than two weeks ago. However, we have not received the payment yet.

**Comment by semuelle** [comment]
Hey @avtishin. Sorry for the long wait. Your invoice will be processed this week. Please let me know if you haven't received anything by Friday EOB.

**Comment by RouvenP** [comment]
hi @avtishin apologies for the delay. We transferred the funds today.

**Comment by avtishin** [comment]
@semuelle @RouvenP thanks, all received!

**Pull request merged**
