### PR TITLE
External evaluation of Contracts tool milestone 1

### PR DESCRIPTION
**Pull request by Whisker17**
All the milestone deliverables are provided and work as expected.

Application: https://github.com/w3f/Grants-Program/blob/master/applications/contracts-tool.md
Milestone delivery PR: https://github.com/w3f/Grant-Milestone-Delivery/pull/927

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@Whisker17 thank you for the external evaluation. I'll not merge it yet since we had two external evaluations for this milestone delivery. This is something new for us. We will discuss internally how to handle this case and circle back to you soon.

**Comment by Whisker17** [comment]
Thanks for your reply. @dsm-w3f 
I think this is a result of a lack of clarity in the external evaluation process, @Ali-Usama and I were both interested in a grant at the same time and had it externally evaluated, initially Ali submitted a PR but I realised that there was only general information about the grant so I submitted my PR after completing my evaluation and left a message for Ali hoping that it wouldn't be controversial. I think it's inevitable that this will happen as the number of grants grows and this is a good opportunity to clarify the external evaluation process.

**Comment by dsm-w3f** [comment]
@Whisker17 we discussed internally and in this case we will accept both evaluations. However, our guidelines will be updated soon to include that external evaluators open a draft PR as soon as they start to work to avoid duplicate evaluations. I'll forward your KSM payment. Great job!

**Comment by Whisker17** [comment]
> @Whisker17 we discussed internally and in this case we will accept both evaluations. However, our guidelines will be updated soon to include that external evaluators open a draft PR as soon as they start to work to avoid duplicate evaluations. I'll forward your KSM payment. Great job!

Thanks for your reply! @dsm-w3f 

I couldn't agree more with starting the external evaluation with a DRAFT PR first, looking forward to more details!

**Pull request merged**
