### PR TITLE
bdwallet_milestone-1

### PR DESCRIPTION
**Pull request by bdwallet**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @bdwallet,
the files in the `evaluations` folder are for evaluators. Could you please move your milestone information into a copy of the [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) file and resubmit?

**Comment by semuelle** [comment]
Also, could you provide (ideally English) instructions on how to test the mobile frontend? When I follow the instructions in [this file](https://github.com/bdwallet/wallet-app/blob/fe2a36c19b76ea564126816b5ec52c615019f5ad/README.md), I get:

```sh
$ npm run dev wap

> heizuan@2.1.2 dev /bdwallet/wallet-app
> node build dev "wap"

( ●    ) 正在编译"wap"模块的调试环境，请稍等...

 ERROR  Failed to compile with 5 errors                                                                                                 4:34:16 PM

This dependency was not found:

* Vue in ./application/wap/components/comment/creat.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./application/wap/components/compAnonymous/index.vue

To install it, you can run: npm install --save Vue


These relative modules were not found:

* ../../../../../caijing/script/constellation in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./application/wap/page/index/pages/user/homepage.vue
* ./App in ./application/wap/components/Uploader/index.js
* ./app in ./application/wap/components/projectList/index.js
> "wap"模块的调试环境编译完成！

> Listening at http://localhost:8082
```

**Comment by bdwallet** [comment]
Okay, we will modify it and submit it again.

**Comment by semuelle** [comment]
Hi @bdwallet, any news on your milestone?

**Comment by semuelle** [comment]
Hey @bdwallet, since we haven't heard from you about Milestone 1 in two months and it is now three months overdue, we are about to terminate your grant. If you are still working on it, please give a quick sign of life and share your short-term plans with us.

**Comment by semuelle** [comment]
This grant has been [terminated](https://github.com/w3f/Open-Grants-Program/pull/115#issuecomment-833812681).

**Pull request closed without merging**
