### PR TITLE
RV KMIR Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by ehildenb**
* deliveries/rv_kmir-milestone_1: milestone document

* milestone 1 delivery submission application

* update deliverable links to milestone1-delivery branch

---------

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by ehildenb** [comment]
@keeganquigley thank you! I've addressed it.

**Comment by Ali-Usama** [comment]
Hi @ehildenb, the repo  [links](https://github.com/runtimeverification/web3-grants-milestones/blob/rv_kmir-milestone_1/deliveries/rv_kmir-milestone_1.md#:~:text=Documentation-,README,-0c.) provided in your milestone delivery are inaccessible. Can you please look into it? Thank you!

**Comment by ehildenb** [comment]
@Ali-Usama apologies for the delay, I've made the repo public!

**Comment by Ali-Usama** [comment]
Thanks, @ehildenb. Looking into it!

**Comment by ehildenb** [comment]
@Ali-Usama I've made the relevant repo public to address the first issue. Will take a look into the second issue.

**Comment by Ali-Usama** [comment]
Appreciate the quick fixes, @ehildenb. Please let us know when the other issues are fixed too. :)
Thanks.

**Comment by Ali-Usama** [comment]
Thank you @ehildenb. I've updated my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/819)

**Comment by semuelle** [comment]
Thanks for the evaluation, @Ali-Usama. I have nothing to add. 

Your milestone is hereby accepted, @ehildenb. The evaluation notes are merged [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rv_kmir-1-ali-usama.md). I have forwarded your invoice for processing. 

cc @bhargavbh

**Pull request merged**
