### PR TITLE
ScoutCoinFabrik Milestone 1

### PR DESCRIPTION
**Pull request by valeriacaracciolo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x ] This pull request is being made by the same account as the accepted application.
- [x ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1490 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
@valeriacaracciolo So far everything is looking great. I'm just testing out the detectors, see my initial notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ScoutCoinFabrik_1_keeganquigley.md).

**Comment by keeganquigley** [comment]
Thanks everyone for the great work, I am happy to pass the milestone. My final eval is [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ScoutCoinFabrik_1_keeganquigley.md). I will forward your invoice internally for processing. Looking forward to the follow-up application!

**Comment by keeganquigley** [comment]
Hi @valeriacaracciolo apologies I didn't realize that your invoice was for USDT. Would you be willing to be paid in USDC or DAI instead? As we [don't support](https://github.com/w3f/Grants-Program#pencil-process) USDT payments via Ethereum anymore. If so, could you send an updated invoice?

**Comment by valeriacaracciolo** [comment]
Hello Keegan, 

(I’m not sure if replying by mail is what I should do - but I’m not such good friends with GitHub :/

Sure, no problem. We can use the same address for USDC. I’ll update the invoice, where should I upload the new version?

Thanks and best

PS: I’ve got your comments for M2, and we are working on those specs.

**Comment by RouvenP** [comment]
hi @valeriacaracciolo we transferred the payment today.

**Comment by valeriacaracciolo** [comment]
Received. Thank you so much Rouven and Keegan!

**Pull request merged**
