### PR TITLE
June::Db-milestone_1.md

### PR DESCRIPTION
**Pull request by MikeMS-sys**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/466

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
Just to link it here. You want to combine this delivery with [this amendment](https://github.com/w3f/Grants-Program/pull/580), correct? Could you provide more details? Why did you move the current delivery to milestone 4?

**Comment by andskur** [comment]
Hi @Noc2 
Yes we want to combine delivery of this Milestone with update of our initial application. 

we plan to change 2nd Milestone (hash map data storage) for a new (offchain::ipfs update) and then put hash map data storage in Milestone 4 (the last).

**Comment by semuelle** [comment]
The branches/paths linked in Deliverables 0b and 2 don't exist, could you fix those?

**Comment by semuelle** [comment]
Also:

- The image on Docker Hub is either private or nonexistent
- Deliverable 2 points to your own `substrate-frontend-template`, but the test instructions point to `substrate-developer-hub`, and I don't see any changes to your fork. Are you still planning on making changes to the frontend? Otherwise creating a fork of your own seems superfluous.
- Can you add instructions how to build and run locally, with and without Docker, to your testing guide? Following the `rs-ipfs` instructions, both `docker build` and `cargo build` fails with `type annotations needed` errors.

**Comment by MikeMS-sys** [comment]
@semuelle Hello and sorry for still not answer, unfortunately we were forced to hold the development works for a week for personal reasons beyond our control.

We almost done with updating offchain::ipfs (2nd Milestone). In there are we agreed to coordinate with equilibrium.co updating offchain::ipfs. We have send a mail them, but still didn't got any answer.

And of couse will fix requested changes for Milestone 1.

**Comment by alxs** [comment]
@MikeMS-sys maybe you want to try opening an issue or a draft PR on their [repo](https://github.com/rs-ipfs/substrate

**Comment by alxs** [comment]
@MikeMS-sys perhaps try opening an issue or a draft PR on their [repo](https://github.com/rs-ipfs/substrate)? If you still don't get an answer from them, we'll try to mediate. Happy to hear about your progress. By the way: you'll probably also want to bring the [`offchain::ipfs` Manual](https://github.com/rs-ipfs/offchain-ipfs-manual) up to date as part of the documentation for M2 if needed.

**Comment by MikeMS-sys** [comment]
@alxs Of course, we were planned it when achive the delivery of the Milestone.

**Comment by semuelle** [comment]
@MikeMS-sys, any updates on this?

**Comment by MikeMS-sys** [comment]
@semuelle 
To shut down Milestone 1, we had to first update offchain :: ipfs (M2).
So, we have already updated [offchain :: ipfs] (https://github.com/rs-ipfs/substrate) and opened a PR on their repo https://github.com/rs-ipfs/substrate/pull/5.

Today we are working on the remaining сlauses of the Grant-milestone-delivery, and then make update for the 1st stage and PR for the 2nd.

Remembering our conversation about the encryption module, we will most likely prepare a PR for 3 Milestone.

**Comment by semuelle** [comment]
Hi @MikeMS-sys, in order to continue with the evaluation of the milestone, could you address the issues I have raised in my two comments above?

**Comment by MikeMS-sys** [comment]
Hi @semuelle! For sure! We plan to make the update at night. Mostly it is not our style to delay the work, but objective reasons contributed to this and we will not keep you waiting long with a justification answer.

**Comment by alxs** [comment]
@MikeMS-sys

**Comment by alxs** [comment]
@MikeMS-sys any updates on Sebastian's feedback? Please note that the evaluation process is usually a lot faster than it's been the case for these deliveries - according to the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T%26Cs.md#4--procedure), you have 14 days to address feedback. If you can't get back to this within the next 2 weeks, please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline of your grant and we'll put the delivery on hold.

**Comment by andskur** [comment]
https://github.com/w3f/Grant-Milestone-Delivery/pull/322#issuecomment-1025243528

**Comment by semuelle** [comment]
Hi @andskur & @MikeMS-sys. I had planned to evaluate both of your milestones today, but there are still issues with this delivery. 

- There are no public `uddug/substrate-juni` or `andskur/juni-db` images on DockerHub as mentioned in 0c and 0d
- Deliverable 0c is described as "Complex quality assurance for all platform features. Core functions will be fully covered by unit tests to ensure functionality and robustness." The doc only describes how to call functions from the Substrate frontend template, though.

**Comment by andskur** [comment]
hi @semuelle , thanks for your reply. Would be very nice if we could evaluate 2nd milestone first. We still need to finish few issues with first milestone delivery (plan to update you about it this weekends)

**Comment by semuelle** [comment]
Hey @MikeMS-sys & @andskur, any news on this milestone?

**Comment by andskur** [comment]
> Hey @MikeMS-sys & @andskur, any news on this milestone?

Hi @semuelle, sorry for late reply. We should figure out last issues (web app and unit testing) and aim to update you later this week or early next week

**Comment by andskur** [comment]
Hi @semuelle, sorry for the long waiting again. We're on the final steps with last issue. Hope to resolve it very soon

**Comment by takahser** [comment]
@andskur sounds good, thanks for the update!

**Comment by MikeMS-sys** [comment]
Hi! @semuelle @takahser 
We finally added the requested positions and are waiting for the feedback. 
Also will make new pr with changes for the next Milestone in the week.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @MikeMS-sys, thanks for the update. Have you looked at [the comments I made 8 months ago](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-910184677)? It seems that most of the issues still aren't resolved.

- The documentation refers to the `offchain-ipfs-v0.3` branch, your delivery to the `Juni/key-value` branch. Which one should I be looking at? 
- The former doesn't contain the key-value functions and neither compiles with `cargo build`.
- The documentation also still refers to `rs-ipfs/substrate` in most cases.
- The branch in the frontend repo doesn't exist.
- I don't see any changes to the `substrate-front-end-template` in your fork. Have you made any? When you say your delivery will be "based on the substrate-front-end-template", I assume it will be fitted to your project's needs.

**Comment by andskur** [comment]
Hi, sorry for long response - was on holydays. All issues should be already fixed. Will check

**Comment by andskur** [comment]
Hi, sorry for the long reply. We are relocating our team and business from Russia now. Issues with this delivery should be resolved, i will update you shortly.

**Comment by andskur** [comment]
Hi guys, relocation seen a lot of time and we have just almost finished it. Please give us few more days. A lot of sorry for the delay

**Comment by alxs** [comment]
Hey @andskur, mind sharing your progress with us? Note that given the unreasonable delays on this grant and since it seems there's been no activity on your repository for the past 2 months, we may terminate it if you don't submit a final delivery within the next 2 weeks. According to our [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T%26Cs.md), you have 2 weeks to address defaults from the initial delivery date.

**Comment by andskur** [comment]
Hi @alxs , sorry again for delay. Team relocation spent a lot of our resources. I will provide final delivery soon.

**Comment by cruikshankss** [comment]
> Hi guys, I still have to update testing guide. will finish with it a bit later today

Hi @andskur, please keep me updated. I've taken over from Sebastian while he's out of office. Thanks!

**Comment by andskur** [comment]
Hi @cruikshankss i have already updated it🙂

**Comment by cruikshankss** [comment]
> Hi @cruikshankss i have already updated it🙂

Thank you. I'm a bit backlogged right now but I plan to keep you updated and get to it as soon as possible. To speed things up, please make sure your documentation explains the ideals you've achieved and the true value of your project, and ensure the testing guide is catered to make it as easy as possible (truly step-by-step with great details) for someone new to your project to test that your deliverables all work. Talk soon! Thanks!

**Comment by cruikshankss** [comment]
Good day @andskur! 

I tried cloning your repo and running `TRYBUILD=overwrite cargo test`, but I got this output

```
error: failed to parse manifest at `/Users/ash/wthree/substrate/Cargo.toml`

Caused by:
  feature `named-profiles` is required

  The package requires the Cargo feature called `named-profiles`, but that feature is not stabilized in this version of Cargo (1.57.0-nightly (d56b42c54 2021-09-27)).
  Consider adding `cargo-features = ["named-profiles"]` to the top of Cargo.toml (above the [package] table) to tell Cargo you are opting in to use this unstable feature.
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#custom-named-profiles for more information about the status of this feature.

```

Do you have any insight as to what I'm doing wrong? Many thanks! -Ashley

**Comment by cruikshankss** [comment]
Good day @andskur, 

I'd really love to complete your evaluation this week. If you're available, I'd be super interested in meeting with you for 30 mins for a live demo video call/discussion of the software architecture so I can understand the value of your project. 

Tomorrow I'm free 1-2:30pm and after 3pm CET. Friday I'm free 1-2:30pm and after 4:30 CET. My time zone is UTC−07:00 which hopefully explains my availability this week. Please feel free to choose a 30-min time window. I also plan to message the other teams who have evaluations I hope to finish this week. It's a really busy week for me which is why I'm trying to schedule these demos so I can speed up my pace; my apologies for the delay. And if a time gets taken, I plan to edit this message in GitHub so please check this convo tab on GH for the latest updates. Feel free to send a calendar invite to ashleyg@web3.foundation if you select a time and I plan to RSVP from there. 

Otherwise, I'm open to scheduling an Element or Discord chat. If not, I'm totally patient if you'd rather update the testing guide whenever you have free time. There's no rush and just hope you take all the time you need to build the tech right. :) Cheers!

**Comment by andskur** [comment]
hi @cruikshankss , sorry for a long reply. This week is a super busy for us too. I will check tests asap but don't think that we have a suitable time slots for a call this week☹️

**Comment by cruikshankss** [comment]
@andskur Thanks for the response! No rush. Please update the testing guide when you have the time and ping me with an update, or ping me to set up a demo. Hope you have a nice weekend. :)

**Review by takahser — CHANGES_REQUESTED** [review]
@andskur sorry again for the delay here. I have two of questions:

1. I took a look at your delivery and I'm confused about which testing guide to use. In your delivery you link [The offchain::ipfs Manual](https://uddugteam.github.io/JuniDB-manual/) while on @semuelle's evaluation I see the link to [this google doc](https://docs.google.com/document/d/1gTuJVTt13hMM_N9XlDCNTU0ykWpVH_fC336Ea0UznLQ/edit). The latter seems more complete to me, which is why I tried following this guide. Could you update delivery _0c. Testing Guide_, if neccessary?
2. I didn't find the docker image you linked: [uddug/substrate-juni](https://hub.docker.com/search?q=uddug%2Fsubstrate-juni). Could you double-check if you have uploaded it and if it's public?

**Comment by andskur** [comment]
hi @takasher. please check last updated delivery - https://github.com/w3f/Grant-Milestone-Delivery/blob/81c60850a3b95df679054f795c7005a52666aaf9/deliveries/Juni::Db-milestone_1.md

**Comment by takahser** [comment]
@andskur FYI - the docker image is still not public

> docker image - https://hub.docker.com/repository/docker/andskur/juni-db

**Comment by andskur** [comment]
Hi @takahser ,

Image is public... I don't understand why it private for you
image

Will check tests warning and why node starts

**Comment by andskur** [comment]
@takahser you right, sorry. I have sent wrong link.

Correct one - https://hub.docker.com/r/andskur/juni-db

**Comment by takahser** [comment]
@andskur thanks, this link works. Were you able to fix the other issues?

**Comment by takahser** [comment]
Ping @andskur

**Comment by andskur** [comment]
hi @takahser , sorry for long reply.

Seems like this warnings is come from original substrate v3. Should we fix it in this case?

About the node starts - I also see that this behaviour is okay for original substrate. Also node starts when tests running, not after tests.

**Comment by takahser** [comment]
@andskur sorry for the delay again and thanks for your patience. I took another look at your delivery.
I managed to:

- run the node using the docker template
- run the frontend
- run the unit tests (?)

However, when testing the frontend, I wasn't able to query the key that I previously stored a value for:

image

Or at least I cannot read the value (which should be `'BAR'`). Instead, I only see this message:

_**fetching data for key ...**
["5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"]_

Is this the expected behaviour? Am I missing something here?

Regarding the warnings:

> Seems like this warnings is come from original substrate v3.

Are you using the latest version of Substrate? Since you seem to have copied the whole Substrate repo I'd be curious to learn on how you're planning to keep it up to date with the original Substrate repo.

**Comment by takahser** [comment]
Hi @andskur 
Any update here? If there's no progress within the next 2 weeks I'm going to assume you're no longer interested in completing the grant.

**Comment by MikeMS-sys** [comment]
Hi @takahser
Earlier we jointly found that the offchain::ipfs fork is the best solution for developing Juni::Db. We updated it to the latest Substrate version and opened a PR, thus our fork become one of the main forks of the original offchain::ipfs.

But you asked the right question. In the last months, we have been trying to make an acceptable version of Juni by maintaining the current version of Substrate. But now we are thinking that it can be very difficult to keep the repository up to date and achieve adequate results. Due to the development of the ecosystem and, accordingly, the Substrate, etc.

If coming back earlier, Juni was 1 of 3 main components of a slightly larger project to analyze medical data. And perhaps our initial decision will be more logical to achieve the current goal - namely, the development of our database - means as a standalone Substrate pallet without dependencies on any forks like offchain::ipfs.

And, of course, we would like to get some advice on how best to proceed with the grant.

**Comment by takahser** [comment]
@MikeMS-sys thanks for your reply.

> We updated it to the latest Substrate version and opened a PR, thus our fork become one of the main forks of the original offchain::ipfs.

Which PR are you referring to? Does that mean you're currently blocked by the acceptance of said PR?

> But now we are thinking that it can be very difficult to keep the repository up to date and achieve adequate results.

Does that mean that you won't proceed with this grant?

> And perhaps our initial decision will be more logical to achieve the current goal - namely, the development of our database - means as a standalone Substrate pallet without dependencies on any forks like offchain::ipfs.

One solution would be to cancel this grant and apply for a new one. Or you could amend the current grant, if that makes more sense to you, depending on the overlap between the original and amended grant.

**Comment by MikeMS-sys** [comment]
@takahser 
> Which PR are you referring to? Does that mean you're currently blocked by the acceptance of said PR?

I refer to rs-ipfs/substrate#5 PR and No, that PR already was accepted, and don't block us.

> Does that mean that you won't proceed with this grant?

No, we aim at the release of the Juni::Db but are thinking about a more logical solution.

> One solution would be to cancel this grant and apply for a new one. Or you could amend the current grant, if that makes more sense to you, depending on the overlap between the original and amended grant.

Application Document https://github.com/w3f/Grants-Program/blob/master/applications/JuniDB.md
 
 What we’ve done. First, we updated off chain::ipfs https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/june-db_2_semuelle.md 

We plan to make a new PR and change the solution in Milestone 2 on "The standalone Substrate pallet" without dependencies on any forks like offchain::ipfs. And then to fix the Basic database layout implementation with key-value data storage (Milestone 1) as you commented earlier https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1330619906.

**Comment by takahser** [comment]
@MikeMS-sys 

> I refer to https://github.com/rs-ipfs/substrate/pull/5 PR and No, that PR already was accepted, and don't block us.

I didn't look deeply into the PR, but it wasn't accepted, instead it was closed, right? Did you post the wrong PR maybe?

> No, we aim at the release of the Juni::Db but are thinking about a more logical solution.

What's your estimate on coming up with a solution for it? I'm asking because this PR has been open for >1 year and I think it's time to close it, if we don't see any progress been made, nor concrete plans on what to achieve until what date.

> We plan to make a new PR and change the solution in Milestone 2

What's your time schedule on that?

**Comment by takahser** [comment]
@MikeMS-sys after a thorough review of your delivery and discussion within the grants committee, we've concluded that the best solution forward would be to terminate your grant. These are the reasons that lead to that decision:

- significant delays: this delivery has been open for nearly 1.5 years now
- no clear plans on how to move forward
- no activity in the codebase for more than [3 months](https://github.com/w3f/Grant-Milestone-Delivery/pull/254/commits/52cf0d5670d00c85a2682bb1a6346642b914793e)
- multiple warnings from W3F committee members [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1014817069), [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1184441701) and [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/254#issuecomment-1375296875)

Please note that this termination is in accordance to our [T&C](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md).

We would like to thank you for your interest in the grants program and for your contributions to the ecosystem. You're also welcome to apply for further grants in the future, though please note that the committee will likely take the current termination into account.

**Pull request closed without merging**
