### PR TITLE
FiDi DotSight M2 Delivery

### PR DESCRIPTION
**Pull request by fidiroman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1748

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the delivery, @fidiroman. I will review it more thorougly on Monday, but in the meantime, I have two issues:

- The Github login only returns an HTTP 500 error.
- Could you replace the dot.fidi.tech.v2 links with links to code in your repo where these features are implemented? We are more interested in the code than the deployment. 

Thanks!

**Comment by fidiroman** [comment]
Thanks Sebastian @semuelle! We've upgraded the /v2 version to our primary dot.fidi.tech link, but ended up sharing the old one here; that's on me, appreciate you catching that. All updated and tested now. We'll have more log-in options available as the platform matures, too.

Well noted on specifying links to the actual code -- just submitted an update, welcome to take a look.

**Comment by fidiroman** [comment]
In relevant news, since our submission, we've also added support for Steallswap, Beamswap, and Arth. Additionally, we've added the Radar chart for three-metrics cases, with more exciting widget types coming soon. All are available live now, and we'll be sharing with the community this week. Excited for your thoughts, and thanks!
FiDi dApps
FiDi Radar

**Comment by semuelle** [comment]
Thanks for the updates, @fidiroman. I can confirm that I can run and test everything locally. However, locally I can't find the metrics outlined in the 1a deliverable spec. Could you check if I'm missing something? Am I on the wrong branch?

Screenshot from 2024-03-26 12-32-53

**Comment by fidiroman** [comment]
Thanks for the feedback, @semuelle! Regarding the metrics and documentation (0b, 1a), see [Metrics Collection](https://docs.fidi.tech/fidi-overview/metrics-collection) (just updated for precision) for all available compositions today; it includes the ones in this submission and all additional ones delivered on top of the initial scope.

To illustrate how to access, the list of selectable metrics updates automatically based on what's available for the network user selected, i.e., if any dApps are selected, then Active Addresses, Unique Addresess, and Transaction Counts become available; similarly, if Arbitrum, Avalanche, or Ethereum are selected then Block Time and Block Counts become available.

Great catch on the GitHub login's credentials! @fidi-anton [addressed it](https://github.com/fidi-tech/dotsight/pull/40/files) last night. We had instances spun up fresh every time, and this didn't come up, glad you caught it.

Let us know if you'd like to see more precision anywhere, and excited for further comments!

**Comment by fidiroman** [comment]
Hi @semuelle, just following up, thanks!

In other news, the "Total Staked" metric is available now for Polkadot (see the docs); excited for your feedback!

FiDi Polkadot Total Staked

**Comment by semuelle** [comment]
> To illustrate how to access, the list of selectable metrics updates automatically based on what's available for the network user selected, i.e., if any dApps are selected, then Active Addresses, Unique Addresess, and Transaction Counts become available; similarly, if Arbitrum, Avalanche, or Ethereum are selected then Block Time and Block Counts become available.

Hey @fidiroman, thanks for the reply and the fix. Regarding the metrics, I am looking for the metrics mentioned in the [milestone spec](https://github.com/w3f/Grants-Program/blob/master/applications/fidi-dotsight-analytics.md?plain=1#L262-L264). I know that you made some change to the scope and order of milestones. Have these specs changed?

**Comment by fidiroman** [comment]
Thanks Sebastian @semuelle, here's how the metrics from milestone spec map into the current delivery:

[2a. Network-level signals](https://github.com/w3f/Grants-Program/blob/5d42e06c6ab25593098ea1449cb7cc15f3b0f67f/applications/fidi-dotsight-analytics.md?plain=1#L264C38-L264C365)  "UAW per network, number of new wallets, adoption rates, unstaked tokens currently in wallets, tokens in circulation, and tokens staked or locked.":
* Delivered in scope: [Unique Addresses](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-parachains) (UAW per network), [Transaction Count](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-parachains) (adoption rates), [Total Staked](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-parachains) (tokens staked or locked).
* Additional Metrics Available: [Treasury Balance](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-parachains), [Pricing](https://docs.fidi.tech/fidi-overview/metrics-collection#tokens-l0s-l1s-and-l2s).
* Network metrics are available for the following chains: Acala, Arjuna, Astar, Aventus, Bitfrost, Bitgreen, Centrifuge, Clover, Collectives, Composable, Crust, Darwinia, Equilibrium, Frequency, Hydradx, Integrity, Interlay, Invarch, Kapex, Kilt Spiritnet, Lientry, Manta, Moonbeam, Nodle, Origintrail, Parallel, Pendulum, Phala, Polkadex, Statemint, Unique, Zeitgeist; and Polkadot as a whole.
* Price data is available for the following chains: 1inch, Aave, APECoin, Aribtrum, Avalanche, Balancer, Binance USD, Bitcoin, BNB, Cardano, Chain, Chainlink, Circle USD, Compound, Convex, crvUSD, Curve DAO, DAI, Dogecoin, Ethereum, Ethereum Name Service, Frax Share, Hedera, Highstreet, Immutable X, Kyber, Lido Staked, Litecoin, Maker, Pancakeswap, Pax Dollar, Perpetual, Polkadot, Polygon, Radiant, Reserve Rights, Rocket Pool, Solana, Spell, Stargate, Sushi, Swipe, Synethtix, Tether Euro, Tether USD, The Graph, The Sandbox, True USD, Uniswap, USDD, Wing, and Yearn.


[1.b dApp-level signals: user activity](https://github.com/w3f/Grants-Program/blob/5d42e06c6ab25593098ea1449cb7cc15f3b0f67f/applications/fidi-dotsight-analytics.md?plain=1#L263) "Additionally, the dApp-specific user activity metrics will be surfaced, e.g., UAW, net new wallets, historical transactions, volume, and balance per dApp.":
* Delivered in scope: [Unique Active Wallets](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-dapps) (UAW), [Total Volume](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-dapps) (volume / balance), [Transactions Count](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-dapps) (historical transactions).
* dApp level data is available for the following chains: Arthswap, Beamswap, Jupiter Exchange, PancakeSwap, Stellaswap, and SyncSwap. 

[1.a dApp-level signals: collator metrics](https://github.com/w3f/Grants-Program/blob/5d42e06c6ab25593098ea1449cb7cc15f3b0f67f/applications/fidi-dotsight-analytics.md?plain=1#L262C14-L262C477)  "collator/nominator activity and make metrics such as uptime, block production rate, block processing time, rank/nominator rank, name, and value locked available in the views."
* Delivered in scope: [Produced Block Count](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-global-l0s-l1s-and-l2s) (block production rate), [Average Block Time](https://docs.fidi.tech/fidi-overview/metrics-collection#networks-global-l0s-l1s-and-l2s) (block processing time).

Let us know if you need help identifying any of the metrics above, happy to jump on the call, too. Thanks!

**Review by semuelle — APPROVED** [review]
Thanks for the clarifications, @fidiroman. Other than the questions above, I have nothing to add. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fidi_dotsight_2_semuelle.md). Congrats.

**Pull request merged**
