### PR TITLE
Turnkey private blockchain milestones 1 and 2

### PR DESCRIPTION
**Pull request by spoluyan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the submission of the milestone as well as the [amendment](https://github.com/w3f/Open-Grants-Program/pull/157). We will take a look at it as soon as possible.

**Comment by semuelle** [comment]
Hi @spoluyan,
could you provide me with the exact commit and toolchain version to test your code with? The [current](https://github.com/Cerebellum-Network/private-standalone-network-node/tree/9aed9428fce057bf7902690340bc48092ca08c10) version fails to compile with both current and previous Rust toolchain versions:

```sh
$ cargo +nightly test           
   Compiling node-template-runtime v2.0.0 (/cerebellum_turnkey-priv-blckchn-ntwrk/private-standalone-network-node/runtime)
   ...
   Compiling sp-state-machine v0.8.0
error[E0282]: type annotations needed
    --> /home/seb/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1595 | / implement_fixed!(
1596 | |     FixedI64,
1597 | |     test_fixed_i64,
1598 | |     i64,
...    |
1601 | |     "_Fixed Point 64 bits signed, range = [-9223372036.854775808, 9223372036.854775807]_",
1602 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /home/seb/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1604 | / implement_fixed!(
1605 | |     FixedI128,
1606 | |     test_fixed_i128,
1607 | |     i128,
...    |
1611 | |         [-170141183460469231731.687303715884105728, 170141183460469231731.687303715884105727]_",
1612 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
    --> /home/seb/.cargo/registry/src/github.com-1ecc6299db9ec823/sp-arithmetic-2.0.0/src/fixed_point.rs:541:9
     |
541  |                   let accuracy = P::ACCURACY.saturated_into();
     |                       ^^^^^^^^ consider giving `accuracy` a type
...
1614 | / implement_fixed!(
1615 | |     FixedU128,
1616 | |     test_fixed_u128,
1617 | |     u128,
...    |
1621 | |         [0.000000000000000000, 340282366920938463463.374607431768211455]_",
1622 | | );
     | |__- in this macro invocation
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors
```


```sh
$ cargo +nightly-2020-10-06 test 
   Compiling node-template-runtime v2.0.0 (/cerebellum_turnkey-priv-blckchn-ntwrk/private-standalone-network-node/runtime)
   ...
   Compiling pallet-grandpa v2.0.0
error[E0046]: not all trait items implemented, missing: `MinLength`, `MaxLength`
  --> pallets/cere-ddc/src/mock.rs:52:1
   |
52 | impl Trait for Test {
   | ^^^^^^^^^^^^^^^^^^^ missing `MinLength`, `MaxLength` in implementation
   | 
  ::: pallets/cere-ddc/src/lib.rs:28:5
   |
28 |     type MinLength: Get<usize>;
   |     --------------------------- `MinLength` from trait
...
31 |     type MaxLength: Get<usize>;
   |     --------------------------- `MaxLength` from trait

error[E0599]: no function or associated item named `do_something` found for struct `Module<mock::Test>` in the current scope
   --> pallets/cere-ddc/src/tests.rs:8:29
    |
8   |           assert_ok!(CereDDCModule::do_something(Origin::signed(1), 42));
    |                                     ^^^^^^^^^^^^ function or associated item not found in `Module<mock::Test>`
    | 
   ::: pallets/cere-ddc/src/lib.rs:74:1
    |
74  | / decl_module! {
75  | |     pub struct Module<T: Trait> for enum Call where origin: T::Origin {
76  | |         // Errors must be initialized if they are used by the pallet.
77  | |         type Error = Error<T>;
...   |
103 | |     }
104 | | }
    | |_- function or associated item `do_something` not found for this

error[E0599]: no function or associated item named `something` found for struct `Module<mock::Test>` in the current scope
   --> pallets/cere-ddc/src/tests.rs:10:29
    |
10  |           assert_eq!(CereDDCModule::something(), Some(42));
    |                                     ^^^^^^^^^ function or associated item not found in `Module<mock::Test>`
    | 
   ::: pallets/cere-ddc/src/lib.rs:74:1
    |
74  | / decl_module! {
75  | |     pub struct Module<T: Trait> for enum Call where origin: T::Origin {
76  | |         // Errors must be initialized if they are used by the pallet.
77  | |         type Error = Error<T>;
...   |
103 | |     }
104 | | }
    | |_- function or associated item `something` not found for this

error[E0599]: no function or associated item named `cause_error` found for struct `Module<mock::Test>` in the current scope
   --> pallets/cere-ddc/src/tests.rs:19:19
    |
19  |               CereDDCModule::cause_error(Origin::signed(1)),
    |                              ^^^^^^^^^^^ function or associated item not found in `Module<mock::Test>`
    | 
   ::: pallets/cere-ddc/src/lib.rs:74:1
    |
74  | / decl_module! {
75  | |     pub struct Module<T: Trait> for enum Call where origin: T::Origin {
76  | |         // Errors must be initialized if they are used by the pallet.
77  | |         type Error = Error<T>;
...   |
103 | |     }
104 | | }
    | |_- function or associated item `cause_error` not found for this

error[E0599]: no variant or associated item named `NoneValue` found for enum `Error<mock::Test>` in the current scope
  --> pallets/cere-ddc/src/tests.rs:20:19
   |
20 |               Error::<Test>::NoneValue
   |                              ^^^^^^^^^ variant or associated item not found in `Error<mock::Test>`
   | 
  ::: pallets/cere-ddc/src/lib.rs:62:1
   |
62 | / decl_error! {
63 | |     pub enum Error for Module<T: Trait> {
64 | |         /// A name is too short.
65 | |         TooShort,
...  |
68 | |     }
69 | | }
   | |_- variant or associated item `NoneValue` not found here

error: aborting due to 5 previous errors
```

**Comment by spoluyan** [comment]
Hello, @semuelle .
Please use this command to run tests:
```
cargo +nightly-2020-10-06 test
```
You can use [this](https://github.com/Cerebellum-Network/private-standalone-network-node/commit/af435c0d91ca365f2d41c72612b28488446833ba) commit.
Thanks!

**Comment by semuelle** [comment]
@spoluyan, the tutorial document in milestone 2 is not accessible, could you make it public?

**Comment by semuelle** [comment]
Also, @spoluyan, could you explain what the relationship is between the psn-node, Polkadot and Cere's "Layer-1"? Do I understand correctly that networks would have to choose between Polkadot and Cere Layer-1? Do I understand correctly that Cere Layer-1 will be public?

**Comment by semuelle** [comment]
@spoluyan, `https://github.com/Cerebellum-Network/test-scripts` is mentioned in your documentation several times, but does not exist. Where can I find these?

**Comment by spoluyan** [comment]
@semuelle 
> @spoluyan, the tutorial document in milestone 2 is not accessible, could you make it public?

Updated to the file inside repository.



> Also, @spoluyan, could you explain what the relationship is between the psn-node, Polkadot and Cere's "Layer-1"? Do I understand correctly that networks would have to choose between Polkadot and Cere Layer-1? Do I understand correctly that Cere Layer-1 will be public?

- Any business can easily set up a turnkey private blockchain network and integrate their app with it using the innovations being delivered in this grant/project.  they can be independent networks or can be come Layer 2 network that can plugs into Cere mainnet (or layer-1);
- Cere mainnet (or Layer-1) mostly provides access/security to its decentralized data cloud, which can work seamlessly with such private network (as well as any other substrate/polkadot network);
- Cere mainnet can become a Polkadot parachain in the near future



> @spoluyan, `https://github.com/Cerebellum-Network/test-scripts` is mentioned in your documentation several times, but does not exist. Where can I find these?

Fixed. Now it's public.

**Comment by semuelle** [comment]
Thanks for following up on my questions. The issue with the W3F logo and quote are also resolved. I updated my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/215afa02f6485adacfcac605102dd2716444c340/evaluations/cereNetwork_turnkeyPrivateBlockchainNetwork_1_semuelle.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/215afa02f6485adacfcac605102dd2716444c340/evaluations/cereNetwork_turnkeyPrivateBlockchainNetwork_2_semuelle.md) and both your milestones are hereby accepted. Congratulations. :tada: 

I will forward your invoices for processing.

**Comment by freddiemac** [comment]
Thank you, @semuelle! Appreciate all the help and feedback. We'll continue to make some improvements in this area. Look forward to future collaborations!

**Comment by RouvenP** [comment]
hi @freddiemac apologies, I just realized that I missed to pay the invoices for M1 and 2. We just sent a test transaction of 0.001 BTC. Could you confirm if received?

**Comment by freddiemac** [comment]
No worries. Yes, the 0.001 btc was received about 30 mins ago. Thanks!  Fred

**Comment by RouvenP** [comment]
Thanks for confirming @freddiemac. We just sent the remaining 1.799 BTC for M1&2.

**Comment by freddiemac** [comment]
awesome, 1.799 BTC was received!  Thank you!

**Pull request merged**
