### PR TITLE
LIP Payments - Milestone2

### PR DESCRIPTION
**Pull request by olanod**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the **kUSD** payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/756

### CODE REVIEW

**Comment by takahser** [comment]
@olanod feel free to ping me as soon as your PR is ready for review. :)
Have a great weekend!

**Comment by olanod** [comment]
Sorry I didn't made it ready for review before, we got busy polishing edge-case details, bug fixing and finishing core features of the pallet's logic for its inclusion in ORML. Let us know about any changes or requirements :)

**Comment by takahser** [comment]
Thanks for the delivery @olanod. We'll look into it as soon as possible.

> Sorry I didn't made it ready for review before

That's not a problem at all. Please excuse a longer than usual response time as we currently have a large number of deliveries pending evaluation.

**Comment by takahser** [comment]
@olanod thanks again for your patience and sorry for the delay here.
I just approved your milestone, you can find my [evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/commit/54ed6a11a773a8fbd3ade017c4188de3370bdd45).
Also, for the [blog post](https://github.com/virto-network/website/pull/13) feel free to send it over to our Grants PR team for proofreading: grantsPR@web3.foundation
You'll find more information in our [Announcement Guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md#announcement-guidelines), just in case you're not yet aware of it. :)
Thanks for your contribution and good luck with your project! 👍

**Comment by takahser** [comment]
@olanod I just saw that your invoice amount is denominated in EUR while in the original application it's denominated in kUSD. Could you please re-upload the invoice with the correct amount in kUSD as declared in the [original application](https://github.com/w3f/Grants-Program/pull/756/files?short_path=e50a3d3#diff-e50a3d32ace6ff8afd26fc794725b732fcbb1d5312e38835e5914855fbbf1b2f)?

**Comment by olanod** [comment]
My bad @takahser, I re-submitted the invoice. Let me know if everything is in order.

**Comment by takahser** [comment]
@olanod thanks, lgtm. I forwarded your invoice. 👍

**Pull request merged**
