### PR TITLE
Apron Network Milestone 1

### PR DESCRIPTION
**Pull request by Apron2050**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @Apron2050, two of the repos mentioned in your delivery do not contain a license. If they are part of a milestone, they need to be under one of the licenses mentioned in the guidelines. Could you fix that, please?

**Comment by Apron2050** [comment]
> Hi @Apron2050, two of the repos mentioned in your delivery do not contain a license. If they are part of a milestone, they need to be under one of the licenses mentioned in the guidelines. Could you fix that, please?

Hi @semuelle , thank you for your kind remind. All the missing license files are added. Sorry for the late reply. We are preparing for the Polkadot Hackathon Asia these days. Hope we can make it.

**Comment by Apron2050** [comment]
> I'm putting this temporarily on hold due to parallel participation in the [hackathon](https://github.com/ParityAsia/hackathon-2021-spring/). The hackathon organisers will contact you regarding further steps.
@mmagician Thank you for information.

**Comment by semuelle** [comment]
Hi @Apron2050. Since the contracts are a significant part of your milestone, I have to ask you to add one of the open source licenses mentioned in our guidelines to the `apron-contracts` repository.

**Comment by semuelle** [comment]
Hi @Apron2050, one more request:

I am trying to upload the services market contract, but I am getting the following error on `putCode`:

```
1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature
```

There are also a couple of missing or incomplete steps, such as `docker build -t apron-node` instead of `docker build . -t apron-node`, the submodule initialisation and warnings in the build script:

```
copy to ../release
cp: cannot stat '/apron/apron-contracts/services_statistics/target/services_statistics.wasm': No such file or directory
cp: cannot stat '/apron/apron-contracts/services_statistics/target/services_statistics.contract': No such file or directory
cp: cannot stat '/apron/apron-contracts/services_statistics/target/metadata.json': No such file or directory
```

Can you please check that the tutorial is complete and reproducible?

**Comment by Apron2050** [comment]
> Hi @Apron2050. Since the contracts are a significant part of your milestone, I have to ask you to add one of the open source licenses mentioned in our guidelines to the `apron-contracts` repository.

Thank you for the information. The license files are added now.

**Comment by Apron2050** [comment]
> Hi @Apron2050, one more request:
> 
> I am trying to upload the services market contract, but I am getting the following error on `putCode`:
> 
> ```
> 1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature
> ```
> 
> There are also a couple of missing or incomplete steps, such as `docker build -t apron-node` instead of `docker build . -t apron-node`, the submodule initialisation and warnings in the build script:
> 
> ```
> copy to ../release
> cp: cannot stat '/apron/apron-contracts/services_statistics/target/services_statistics.wasm': No such file or directory
> cp: cannot stat '/apron/apron-contracts/services_statistics/target/services_statistics.contract': No such file or directory
> cp: cannot stat '/apron/apron-contracts/services_statistics/target/metadata.json': No such file or directory
> ```
> 
> Can you please check that the tutorial is complete and reproducible?

Sorry for the inconvenience!

```
1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature
```
The error is due to bugs in `polkadot js apps`. Here is the wa 
```
{
  "Address": "AccountId",
  "LookupSource": "AccountId"
}
```
Paste the above config in `Setting -> Developer`.

Let me recheck all the steps in the tutorial. I have added a tool named `apron-deployer` to deploy and run all components with scripts.  The tutorial will be updated soon and rechecked.  Once we complete the tutorial, I will come to you ASAP.

**Comment by semuelle** [comment]
Since your grant agreement contains only one milestone, what do you mean by `Later with backend application, we need to provide the related SDK to handle load balance`? You are still planning to implement the SDK, but not as part of the grant? 

Can you explain what work you have done instead (`we choose to support metamask and other developement framework`)?

**Comment by Apron2050** [comment]
> Since your grant agreement contains only one milestone, what do you mean by `Later with backend application, we need to provide the related SDK to handle load balance`? You are still planning to implement the SDK, but not as part of the grant?
> 

Yes, we want to implement the SDK in the future, the schedule is still not planned yet, but not included in this grant, since there is no use case of the SDK when we tried to implement this milestone.

> Can you explain what work you have done instead (`we choose to support metamask and other developement framework`)?

In this milestone, we provide the access entry point for Metamask (the ethereum wallet), Truffle (the solidity development framework), and Hardhat (another solidity development framework) in the case of providing RPC service for Heco and BSC.  The words `we choose to support metamask and other development framework` are unrelated to this milestone as far as we see, can we remove it?

**Comment by semuelle** [comment]
>  providing RPC service for Heco and BSC.

I don't think an EVM RPC API is an adequate replacement for an Substrate node SDK. If you wish to remove the SDK from the list of deliverables, you can submit an amendment of the original contract. However, this will need to be approved by the committee and will probably also result in an adjustment of the price. 

You could also submit an amendment that moves the SDK to a later milestone. In any case, I cannot approve the delivery as it is, [_although I have already signed off on the rest of the deliverables_](https://github.com/w3f/Grant-Milestone-Delivery/blob/07b0d61135b5de1cde526afe9f37517aa7500020/evaluations/apron-network_1_semuelle.md).

Please let me know how you would like to proceed.

**Comment by Apron2050** [comment]
> > providing RPC service for Heco and BSC.
> 
> I don't think an EVM RPC API is an adequate replacement for an Substrate node SDK. If you wish to remove the SDK from the list of deliverables, you can submit an amendment of the original contract. However, this will need to be approved by the committee and will probably also result in an adjustment of the price.
> 
> You could also submit an amendment that moves the SDK to a later milestone. In any case, I cannot approve the delivery as it is, [_although I have already signed off on the rest of the deliverables_](https://github.com/w3f/Grant-Milestone-Delivery/blob/07b0d61135b5de1cde526afe9f37517aa7500020/evaluations/apron-network_1_semuelle.md).
> 
> Please let me know how you would like to proceed.

Hi @semuelle , thanks for the suggestions. We have updated the tutorial and the docker-related links. Now everything is okay to run. 

Regarding the SDK part, in the beginning, I thought we may need to encrypt the transmission between the service user and the service provider, but when we made some progress, I found implement such an SDK to encrypt the transmission will force the users to use the specific client we are not able to provide right now, and it's quite bad to users in the current state. 

Maybe I should update the delivery of SDK with the above sentences or submit an update to the grant application?

**Comment by Apron2050** [comment]
> > providing RPC service for Heco and BSC.
> 
> I don't think an EVM RPC API is an adequate replacement for an Substrate node SDK. If you wish to remove the SDK from the list of deliverables, you can submit an amendment of the original contract. However, this will need to be approved by the committee and will probably also result in an adjustment of the price.

Apron SDK is not a Substrate Node SDK. It's a client-side SDK, it's planned to encrypt and protect the transmission between the client-side application and the services provider side as we thought in the beginning.  But in the current state, `ssl` is good enough for this purpose.

> 
> You could also submit an amendment that moves the SDK to a later milestone. In any case, I cannot approve the delivery as it is, [_although I have already signed off on the rest of the deliverables_](https://github.com/w3f/Grant-Milestone-Delivery/blob/07b0d61135b5de1cde526afe9f37517aa7500020/evaluations/apron-network_1_semuelle.md).
> 
> Please let me know how you would like to proceed.

**Comment by semuelle** [comment]
> But in the current state, `ssl` is good enough for this purpose.

Maybe I misunderstood the purpose of the SDK. I thought the Apron SDK would provide convenience functions to access the Apron smart contracts through the Substrate node RPC. Then it would be quite simple to write a wrapper to simplify the contract calls. That's what I gathered from [your architecture sketch](https://github.com/Apron-Network/Open-Grants-Program/blob/32e0c7b43770e9c622367df0f906cb762bab3ad8/applications/Apron_Network.md#architecture).

**Comment by Apron2050** [comment]
> > But in the current state, `ssl` is good enough for this purpose.
> 
> Maybe I misunderstood the purpose of the SDK. I thought the Apron SDK would provide convenience functions to access the Apron smart contracts through the Substrate node RPC. Then it would be quite simple to write a wrapper to simplify the contract calls. That's what I gathered from [your architecture sketch](https://github.com/Apron-Network/Open-Grants-Program/blob/32e0c7b43770e9c622367df0f906cb762bab3ad8/applications/Apron_Network.md#architecture).

Thanks for the quick reply. Sorry, it's not detailed the SDK function in that architecture figure. 
To call the contracts is already handled by the project`polkadot js api` which is used in our demo too.

**Comment by Apron2050** [comment]
@semuelle Just updated the links in the delivery doc. Hope it could be helpful for the review of deliverables.

**Comment by semuelle** [comment]
I saw the updates on the documentation, thank you. 

With regard to the SDK, you will have to make an amendment to the contract by either removing it or delaying it until a second milestone ([as previously mentioned](https://github.com/w3f/Grant-Milestone-Delivery/pull/112#issuecomment-805740153)). Let me know how you would like to proceed.

**Comment by Apron2050** [comment]
> I saw the updates on the documentation, thank you.
> 
> With regard to the SDK, you will have to make an amendment to the contract by either removing it or delaying it until a second milestone ([as previously mentioned](https://github.com/w3f/Grant-Milestone-Delivery/pull/112#issuecomment-805740153)). Let me know how you would like to proceed.

Thank you. I think maybe make an amendment to the contract by removing it and reduce the price.

**Comment by Apron2050** [comment]
> I saw the updates on the documentation, thank you.
> 
> With regard to the SDK, you will have to make an amendment to the contract by either removing it or delaying it until a second milestone ([as previously mentioned](https://github.com/w3f/Grant-Milestone-Delivery/pull/112#issuecomment-805740153)). Let me know how you would like to proceed.

Please find the PR by remove SDK and reduce the price of the milestone.
https://github.com/w3f/Open-Grants-Program/pull/331

**Comment by Apron2050** [comment]
Hi @semuelle , could you continue the review? We have updated the deliverables in this PR.

**Comment by semuelle** [comment]
Hi @Apron2050, your smart contract tests currently test only whether a service was added or not. No value checks, no edge cases, no error handling. Given that this is your only milestone, I would like to ask you to expand those.

**Comment by Apron2050** [comment]
> Hi @Apron2050, your smart contract tests currently test only whether a service was added or not. No value checks, no edge cases, no error handling. Given that this is your only milestone, I would like to ask you to expand those.

Thanks for the advice. We will add it asap and will come to you when new cases added.

**Comment by Apron2050** [comment]
Hi @semuelle, we have added several test cases, and also created an issue for a special case which may not be the blocking issue here.  Here is the issue https://github.com/paritytech/ink/issues/747 

Could you help to continue the review?

**Comment by semuelle** [comment]
Hi @Apron2050, I am happy to report that [your milestone has passed](https://github.com/w3f/Grant-Milestone-Delivery/blob/b5502abeb79da29e91477720e700d9a4fc812738/evaluations/apron-network_1_semuelle.md). 

I have forwarded your invoice for processing.

**Comment by semuelle** [comment]
Hi @Apron2050, the date on your invoice shows 2022. Could you send an updated invoice?

**Comment by RouvenP** [comment]
Hi @Apron2050 we sent a test transaction of 0.001 BTC. Could you confirm if received?

**Comment by Apron2050** [comment]
> Hi @Apron2050, the date on your invoice shows 2022. Could you send an updated invoice?

Hi @semuelle  How can I update the invoice? Resubmit the google form?

**Comment by Apron2050** [comment]
> Hi @Apron2050 we sent a test transaction of 0.001 BTC. Could you confirm if received?

Hi @RouvenP , thank you. I have received 0.001 BTC.

**Comment by Apron2050** [comment]
Hi @semuelle, the date has been corrected, and the new pdf is submitted in the google form. Thank you!

**Comment by semuelle** [comment]
Thanks, @Apron2050, I have forwarded the invoice.

**Comment by RouvenP** [comment]
@Apron2050 thanks for confirming. We sent the remainder.

**Comment by semuelle** [comment]
Hi @Apron2050, could you send an invoice with the [updated BTC amount](https://github.com/w3f/Open-Grants-Program/pull/331)?

**Comment by RouvenP** [comment]
Hi @Apron2050: we noticed a discrepancy between the invoice you sent us (1.2 BTC) and your application (0.73 BTC). We kindly ask you to 
1. return the overpaid amount of 0.47 BTC to bc1qtwznev6ft4skmyuee8yqg495a6f9sk243xdfwghfqhl72vyudwks4sgmc3
2. send us an invoice with the correct amount as requested by semuelle

**Pull request merged**
