### PR TITLE
Add Larch 2nd milestone

### PR DESCRIPTION
**Pull request by radhe-zeeve**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1744, https://github.com/w3f/Grants-Program/pull/1399

@takahser Article Links will be updated soon, you can start with technical testing.

### CODE REVIEW

**Comment by takahser** [comment]
Great, thanks @radhe-zeeve. Will be back with feedback soon.

**Review by takahser — CHANGES_REQUESTED** [review]
@radhe-zeeve thanks for the submission.
Although I'm able to build it, execution fails:

```bash
bins % ll
total 130488
-rwxrwxr-x@ 1 xxx  staff  65938514 Oct 16 11:14 larch-linux

bins % ./larch-linux --help
zsh: exec format error: ./larch-linux

bins % ./larch-linux       
zsh: exec format error: ./larch-linux
```

Note: I'm using the same linux machine template on AWS as for M1, so it's likely not an environment-related problem.

**Comment by radhe-zeeve** [comment]
@takahser Can you tell on what OS did you built the binary and what command was used to build the binary and where are you executing the binary.

**Comment by takahser** [comment]
@radhe-zeeve I was using ubuntu on aws (a t2 instance). I followed the guide to create the binary, so it was `npx lerna run package:linux`. It's the same environment as I've already used for M1.

**Comment by radhe-zeeve** [comment]
@takahser I have checked on EC2 Ubunut 22 Instance, i am able to build and execute the binary

image

I believe you are trying to execute it on Mac M2: `bins % ./larch-linux` (`%` is not the current default shell in Ubuntu ). If this it the case, try to build and execute the binary on ubuntu instance.

**Review by takahser — CHANGES_REQUESTED** [review]
@radhe-zeeve I've added my evlauation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/larch_2_takahser.md). I've set up a new VM on AWS and updated all local dependencies, with that the build now passes. The main problem is currently that there is an error when creating the network from the template through the web UI. I remember we had similar problems in the M1 delivery. If you don't know the cause of the issue we can also investigate this together on a video call which you can book [here](https://calendar.app.google/MSKZxmkjivRc46dx8) - whatever works best/easiest for you! :)

**Review by takahser — APPROVED** [review]
@radhe-zeeve thanks for your patience and support. I've just accepted the delivery, you can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/larch_2_takahser.md).

**Comment by radhe-zeeve** [comment]
@takahser  I have uploaded new invoice with crypto as the currency transfer medium as mentioned in the Grant, earlier attached with fiat method, if the payment process is initiated with the fiat that's also fine.

**Comment by takahser** [comment]
@radhe-zeeve thanks for the update. We've recently changed the invoicing process to avoid outdated invoices. Could you upload the invoice also [here](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform?usp=pp_url&entry.1070766548=https://github.com/w3f/Grant-Milestone-Delivery/pull/1037)?

**Comment by semuelle** [comment]
@radhe-zeeve, the postal address in your invoice does not match the one in the grant application. Could you change either one to match the other? Thanks!

**Comment by semuelle** [comment]
@radhe-zeeve, I don't see the payment address in the invoice. Could you add that?

**Comment by radhe-zeeve** [comment]
It's present in the middle of the invoice.
image

**Comment by semuelle** [comment]
Sorry, @radhe-zeeve, my bad. Payment should go out this week if it hasn't yet.

**Comment by RouvenP** [comment]
hi @radhe-zeeve we just transferred the payment

**Pull request merged**
