### PR TITLE
Added the milestone#3 of native tesseract libraries

### PR DESCRIPTION
**Pull request by dileping**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1856

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @dileping many of us were on vacation over the holidays. I'm starting this evaluation now!

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the delivery @dileping everything is working well, I have three questions:

- Are there any Kotlin unit tests you can point me to or otherwise how can I check code coverage?
- The delivery states that "the rest of the libraries in siblings directories (both rust and java), even though are essential, are mostly private and contain code that serve the public APIs to function." Can you further explain what this means? Our current [policy](https://github.com/w3f/Grants-Program?tab=readme-ov-file#guidelines) states that "all code produced as part of a grant must be open-sourced, and it must also not rely on closed-source software for full functionality."
- The delivery states that the article will be emailed privately. Could you send this to grants@web3.foundation? Thanks!

**Comment by dileping** [comment]
Hi @keeganquigley,

Thanks for starting the review process. Please see my comments below.

> Thanks for the delivery @dileping everything is working well, I have three questions:
> 
> * Are there any Kotlin unit tests you can point me to or otherwise how can I check code coverage?
The tests are rather done in the form of applications due to the nature of the software (the communication between Apps in Android can hardly be tested with unit tests). As for the test applications, here are some:
1. Covers client APIs with Test protocol: https://github.com/tesseract-one/Tesseract.android/tree/main/examples/native/app
2. Covers wallet APIs with Test protocol: https://github.com/tesseract-one/Tesseract.android/tree/main/examples/native/wallet
3. Covers client APIs with the Substrate protocol: https://github.com/tesseract-one/polkachat.kotlin
4. Covers wallet APIs with the Substrate protocol: https://github.com/tesseract-one/dev-wallet.kotlin

Also, I'd suggest checking out the following:
1. https://github.com/tesseract-one/Tesseract.android/tree/main/java/client-transport-ipc
2. https://github.com/tesseract-one/Tesseract.android/tree/main/java/service-transport-ipc
3. https://github.com/tesseract-one/Tesseract.android/tree/main/java/common-transport-ipc
The above uses the API for transport development and implements Android IPC using the new APIs.

> * The delivery states that "the rest of the libraries in siblings directories (both rust and java), even though are essential, are mostly private and contain code that serve the public APIs to function." Can you further explain what this means? Our current [policy](https://github.com/w3f/Grants-Program?tab=readme-ov-file#guidelines) states that "all code produced as part of a grant must be open-sourced, and it must also not rely on closed-source software for full functionality."

Private means that they are "private" from the perspective of how the code is structured. Like a private function vs a public function. The code is fully open source, though, and is licensed under Apache 2.0. Please check it within the mentioned directories.

> * The delivery states that the article will be emailed privately. Could you send this to [grants@web3.foundation](mailto:grants@web3.foundation)? Thanks!
Of course, I will take care of it ASAP.

**Comment by keeganquigley** [comment]
Ah thanks for the explanations @dileping that makes sense. I was just concerned when you mentioned "private" so wanted to double-check. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tesseract-mobile-libraries_3_keeganquigley.md). Everything works as expected. Once the article is sent so I can check it over, we should be good to go to accept the delivery :)

**Pull request merged**
