### PR TITLE
Adding milestone delivery

### PR DESCRIPTION
**Pull request by rbrandao**
Project Name: A Knowledge-Oriented Approach to Enhance Integration and Communicability in the Polkadot Ecosystem

Milestone 1 — Literature review and conceptual framework specification

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1420.

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @rbrandao. We will look into it as soon as possible.

**Comment by rbrandao** [comment]
Hi @semuelle, thanks for your swift assessment. The documentation (auto generated HTML files) was inconsistent with the intended draft modeling. We have just updated the ontology (main.ttl) and regenerated the documentation to reflect the following changes:

1. Changed `rdfs:DatatypeProperty` to `owl:DatatypeProperty`
2. Changed `rdfs:ObjectProperty` to `owl:ObjectProperty`
3. Commented out the import of draft Rbox in `main.ttl`

Items 1 and 2 were messing with the intended modeling in the generated documentation, causing inconsistency in individuals / data properties. 

Item 3 is a quick fix for now, as we are still establishing the core ontology and identifying relevant use cases to drive its expansion and rule descriptions. It seems the documentation generator is not working well with our rule box. We will investigate a better solution to tackle this issue. We expect to have a first rule set by the end of milestone 3. This was the reason for the "Illegal character in scheme name" you encountered.

Can you please check if the documentation is in line with your expectations for now? Let us know about it.

**Comment by rbrandao** [comment]
Hi @semuelle, we made further progress on the ontology and its documentation. 

POnto:
- We are now using the more specific `owl:ObjectProperty` as opposed to more general `rdf:Property` for resources-resources relationships.
- Removed repetitive labels for properties.

Documentation:
- We are now generating the doc files with [Ontospy,](https://pypi.org/project/ontospy/) instead of Protegé's auto gen doc feature.

**Comment by semuelle** [comment]
Thanks for the updates, @rbrandao. 

As I said, my knowledge of ontologies is limited, so perhaps I should have someone from our education or research team look over it. But here are some questions I have based on a quick look at the documentation:

- Why does the `Block` documentation [reference `Astar` as implementation](https://github.com/mobr-ai/POnto/blob/3e609740f9e9c37154e18ba08e16b0f07cadaa94/deliverables/milestone1/pontov0_documentation/class-pontoblock.html#L772)?
- `Polkadot` is a `RelayChain` (as is `Kusama`), shouldn't they refer to another? And the different parachains (Moonbeam, Acala, etc.) to `Parachain`?
- Not sure what `PSCR` refers to (happy to review if you have a reference), I think this is what evolved into the (ink!) smart contracts pallet. 
- I'm surprised I don't see [`Pallet`s](https://docs.substrate.io/reference/frame-pallets/) mentioned anywhere, which to a large extent drive the functional differences between chains. 
- The council has been replaced on Kusama (and soon Polkadot) by the [Fellowship](https://wiki.polkadot.network/docs/learn-opengov).

**Comment by rbrandao** [comment]
> As I said, my knowledge of ontologies is limited, so perhaps I should have someone from our education or research team look over it. But here are some questions I have based on a quick look at the documentation:

Hi @semuelle, you are doing a great job pointing out relevant issues in the delivered draft. 

Before addressing your specific points, please bear in mind that in our proposal we foreseen the involvement of others from the W3F team in M3. The goal of M1 is to deliver a succinct ontology draft to serve as some sort of seed for our future discussion. In our experience, this is a good approach. Since the changes and updates we are carrying now are leading to a number of modeling decisions that will be eventually reviewed and/or completely changed according to M2 case study elaboration and the M3 discussions. We uploaded the current ontology documentation to our company website  (https://mobr.ai/ponto), so you can access it and browse through it easier.

Regarding your comments:

> * Why does the `Block` documentation [reference `Astar` as implementation](https://github.com/mobr-ai/POnto/blob/3e609740f9e9c37154e18ba08e16b0f07cadaa94/deliverables/milestone1/pontov0_documentation/class-pontoblock.html#L772)?

- There was an inconsistency in the Block definition causing the documentation to mess it up with the Astar definition. It should be correct by now. 

> * `Polkadot` is a `RelayChain` (as is `Kusama`), shouldn't they refer to another? And the different parachains (Moonbeam, Acala, etc.) to `Parachain`?

- Polkadot and Kusama both implement the same architecture (PolkadotArchitecture) and both are instances of RelayChain. We did not create any further relationships between the two, this is a good topic for further discussing with the team in M3.


> * Not sure what `PSCR` refers to (happy to review if you have a reference), I think this is what evolved into the (ink!) smart contracts pallet.
> * I'm surprised I don't see [`Pallet`s](https://docs.substrate.io/reference/frame-pallets/) mentioned anywhere, which to a large extent drive the functional differences between chains.
- We updated and extended the Tooling module with Ink, Substrate, FRAME and Pallet entities. We also created a first draft of their relationships, according to our view as of M1.

> * The council has been replaced on Kusama (and soon Polkadot) by the [Fellowship](https://wiki.polkadot.network/docs/learn-opengov).

- I think the detailed modeling of the current Governance (Council) and the next one (Fellowship) may also be a good topic for a deep dive with the team. What should be our approach, should we model them both and their relations, or stick with the latter? For now we have a simplistic model to serve as a basis for discussion.

**Comment by semuelle** [comment]
Thanks for the update and explanations, @rbrandao. Your milestone is hereby accepted (see evaluation notes here). I have forwarded your invoice for processing.

> `Polkadot` and `Kusama` both implement the same architecture (`PolkadotArchitecture`) and both are instances of `RelayChain`. We did not create any further relationships between the two, this is a good topic for further discussing with the team in M3.

I didn't notice that they were instances of `RelayChain`. That is what I was referring to, I don't think there is a need to create a relationship between Kusama and Polkadot beyond them being relay chains built on Substrate (`PolkadotArchitecture` is slightly confusing to me here, but this also touches the question of branding, which there have been [lively discussions](https://substrate.meta.stackexchange.com/questions/17/should-we-change-the-name-of-this-site-to-polkadot) about in the past, so it's ok to keep it for now). 

> I think the detailed modeling of the current Governance (Council) and the next one (Fellowship) may also be a good topic for a deep dive with the team. What should be our approach, should we model them both and their relations, or stick with the latter? For now we have a simplistic model to serve as a basis for discussion.

Currently, the new governance model is already deployed on Kusama and is in the pipeline for Polkadot. By the time you get to M3 it might be deployed there as well, but I think it makes sense to model them both, if only for backward compatibility.

**Comment by fededubbi** [comment]
Hi @rbrandao,

I noticed that on the invoice next to Subtotal amount and Balance due there is no currency.
Can you please add USD also here?

Many thanks,
Federica

**Comment by rbrandao** [comment]
Hi @fededubbi,

Just added the USD currency next to subtotal and balance due, as requested. 

Do you need this new version to be submitted through the "Invoice Form" as well?

Cheers,
Rafael

[mobr_invoice_20230001.pdf](https://github.com/w3f/Grant-Milestone-Delivery/files/11232880/mobr_invoice_20230001.pdf)
g else.

**Comment by fededubbi** [comment]
Hi @rbrandao,

No, thanks all good.

Cheers,
Federica

**Comment by fededubbi** [comment]
Hi @rbrandao,

For some reason i can't open the document.
Can you please send it to me as attachment?

Maybe that solves the problem.

Many thanks,
Federica

**Comment by rbrandao** [comment]
Hi @fededubbi,

I don't know what can be happening with the document, I managed to open it even in a incognito tab. 

Anyhow, here it is a google drive link to it: 
https://drive.google.com/file/d/1BvEYWGGwbbpI-hJjyC-vZNCkX4eRTLqP/view?usp=share_link

**Comment by RouvenP** [comment]
hi @rbrandao we transferred the payment today.

**Comment by rbrandao** [comment]
Thank you, @RouvenP. 

Looking forward for the next deliverables.

**Pull request merged**
