### PR TITLE
Stone index on substrate

### PR DESCRIPTION
**Pull request by calvinzhou-rockx**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @calvinzhou-rockx. However, the evaluation template is reserved for milestone evaluations. Could you fill out the [delivery template](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) and open a new PR with it? Thanks!

**Comment by calvinzhou-rockx** [comment]
> evaluations

Sorry @semuelle , there is no evaluation done for our project(Our project has 1 milestone only), shall I continue with delivery template still? Thanks

**Comment by Noc2** [comment]
Hi @calvinzhou-rockx  Yes. You need to submit the delivery template and someone from us or an external evaluator will take a look at your delivery and fill out the evaluation form. See https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process

**Comment by calvinzhou-rockx** [comment]
Understood now, thanks @Noc2 and @semuelle , and will create the PR accordingly

**Pull request closed without merging**
