### PR TITLE
submit scale-codec-comparator milestone_2

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/953 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by gmajor-encrypt** [comment]
@keeganquigley Sorry, it took a long time to do this milestone.hope you can help take a look at this

**Review by 0xCaso — COMMENTED** [review]
Hi @gmajor-encrypt, thanks a lot for the delivery, we'll look into it asap. 

In the meantime, please change the location of the file from 
```
deliveries/deliveries/scale-codec-comparator_milestone_2.md
``` 
to 
```
deliveries/scale-codec-comparator_milestone_2.md
```

**Comment by 0xCaso** [comment]
Thanks! Someone of our team will look into delivery as soon as possible.

**Comment by keeganquigley** [comment]
No worries @gmajor-encrypt thanks for the delivery and I will take a look at it now.

**Comment by keeganquigley** [comment]
@gmajor-encrypt here are my initial comments:

- the deliverables don't match the ones for M2 in your [application](https://github.com/w3f/Grants-Program/pull/953/files#diff-a7ff7cb3df4af9f3e81edfe7fe532d092977a0256d8da1783e287cf5408edd2fR83). The numbering is also off, as it should start with 0a., 0b., 1, 2, instead of starting with the number 1.
- The last one is fine, since it is for GH actions in both files, but for the third deliverable, can you include a GH badge? Also, the first two can be switched around so that "License" is first.
- You can see my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/scale-codec-comparator_2_keeganquigley.md). After making the changes above I will accept the milestone. Thanks!

**Comment by gmajor-encrypt** [comment]
@keeganquigley Thank you for your evaluation, the above problems have been resolved, please take a look again

**Comment by keeganquigley** [comment]
Thanks for the changes @gmajor-encrypt I remember your [comments](https://github.com/w3f/Grant-Milestone-Delivery/pull/559#issuecomment-1254353307) now about the test from the last milestone, so I am happy to go ahead and pass the milestone. Congrats!

**Comment by keeganquigley** [comment]
One last thing @gmajor-encrypt, our [payment methods](https://github.com/w3f/Grants-Program#pencil-process) have changed recently. If you'd like to stick with Ethereum, would you be willing to update your invoice for a payment in DAI instead? Otherwise, we offer USDT payments through Statemint/Statemine now, but you would need to file an amendment to change the address. Thanks!

**Comment by gmajor-encrypt** [comment]
@keeganquigley Thank you for your evaluation and reminder, I have updated my invoice.

**Comment by keeganquigley** [comment]
Thanks @gmajor-encrypt I have forwarded your invoice internally for payment.

**Comment by RouvenP** [comment]
hi @gmajor-encrypt we transferred the payment today

**Pull request merged**
