### PR TITLE
External evaluation of XCM domain milestone 1

### PR DESCRIPTION
**Pull request by dastansam**
Milestone delivery PR: #951 
Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1733

### CODE REVIEW

**Comment by semuelle** [comment]
Hey @dastansam. Thanks for your contributions! We noticed that you submitted three draft evaluations in the past day and a half. Going forward, we would prefer if everyone only did one evaluation at a time. We will leave the ones you already opened open, but might close some in the future if there are too many at a time, so as to give more people the chance to contribute. 

Hope that doesn't deter you. Keep up the good work.

**Comment by dsm-w3f** [comment]
@dastansam as you have only this external evaluation at this moment, let me know if you want to proceed and continue this evaluation.

**Comment by dastansam** [comment]
> @dastansam as you have only this external evaluation at this moment, let me know if you want to proceed and continue this evaluation.

hey @dsm-w3f,

I am completing the evaluation today. thank you

**Comment by dastansam** [comment]
Hey @dsm-w3f 

I have updated the evaluation. For me, the report looks very good and provided potential solutions seem feasible from the technical perspective

**Comment by dsm-w3f** [comment]
@dastansam thank you for the external evaluation. It is approved. I'll forward your KSM payment. Great job!

**Comment by dastansam** [comment]
> Hey @dastansam. Thanks for your contributions! We noticed that you submitted three draft evaluations in the past day and a half. Going forward, we would prefer if everyone only did one evaluation at a time. We will leave the ones you already opened open, but might close some in the future if there are too many at a time, so as to give more people the chance to contribute.
> 
> Hope that doesn't deter you. Keep up the good work.

hey @semuelle,

just wanted to confirm, one at a time here means one evaluation in review or one open draft pull request? For example, I have one not merged evaluation PR right now, does it mean that I can't submit new evaluations before it is accepted/merged? Or can I start new one?

thanks

**Comment by semuelle** [comment]
Please wait until the other evaluations have been merged. We'll look into them as soon as possible. 

Thank you for your contributions!

**Pull request merged**
