### PR TITLE
Create sandox_ms3_delivery.md

### PR DESCRIPTION
**Pull request by TradeLinkEstonia**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Statemint account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1694

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the milestone delivery. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sandox_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by TradeLinkEstonia** [comment]
Hello, Diogo @dsm-w3f .
Thank you for your review. We've fixed all mentioned bugs and added the `./cmd/libsBuild.sh` to the compilation script, so no need for corrections, I guess. Before new testing, please, clear the local storage with `localStorage.clear();`

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the improvements and fixes. The milestone is approved. Please submit the invoice using the link from the comment below. After that, the payment should take place within two weeks. Great job!

**Comment by TradeLinkEstonia** [comment]
@dsm-w3f , I appreciate your evaluation! Thak you!
If I have uploaded the invoice previouslu (after submitting the delivery), should I upload it now again or it's ok?

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia our process changed in this part, now the grantee uploads the invoice after the milestone delivery is approved. Feel free to upload it again.

**Pull request merged**
