### PR TITLE
Load balanced endpoints operations - milestones 1-3

### PR DESCRIPTION
**Pull request by robcxyz**
# Milestone Delivery Checklist

Note: An amendment is being filed that will satisfy all the below points. 

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

[Original Application Link](https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/load_balanced_endpoints_operations.md)

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @robcxyz. We will look into it as soon as possible.

**Comment by alxs** [comment]
Hey, just a quick heads up that the repo under https://github.com/geometry-labs/substrate-meta 404s - do you perhaps need to make it public?

**Comment by alxs** [comment]
@robcxyz ping.

**Comment by robcxyz** [comment]
@alxs - Sorry, long thanksgiving break. Made repo public.  - https://github.com/geometry-labs/substrate-meta

Let me know if there is anything else you need.

**Comment by Nexus2k** [comment]
Hi, do you plan to make the following repos public too?

* https://github.com/geometry-labs/terraform-polkadot-aws-telemetry
* https://github.com/geometry-labs/websocket-logger

**Comment by Nexus2k** [comment]
Can you also please review the links in this PR, Grafana EU / Kibana and Telemetry ones are broken/empty.

**Comment by robcxyz** [comment]
> Hi, do you plan to make the following repos public too?
> 
> * https://github.com/geometry-labs/terraform-polkadot-aws-telemetry
> * https://github.com/geometry-labs/websocket-logger

Just made them public.

**Comment by robcxyz** [comment]
> Can you also please review the links in this PR, Grafana EU / Kibana and Telemetry ones are broken/empty.

Fixed these links / dashboards.

**Comment by robcxyz** [comment]
@alxs - Also included the sync endpoint deliverable in this PR.

**Comment by alxs** [comment]
Thanks @robcxyz, I just changed the title to make it clearer.

@Nexus2k the deliverables for milestone 2 don't correspond to those in the application any longer, but they were agreed to be updated as described in the delivery. The amendment is being reviewed by the legal team I believe (hence the `on hold` label).

**Comment by Nexus2k** [comment]
Did you already publish the Medium article?

**Comment by alxs** [comment]
@robcxyz thank you for your patience. @Nexus2k has offered to take a look at milestone 2 as well, then we'll give both milestones one final look and we should be good. A reminder to fill in the invoice form in case you haven't yet.

I noticed a few inconsistencies in the licenses of the repositories, by the way. Some [lack a license file](https://github.com/geometry-labs/ansible-role-substrate-connect-envoy-config), some are MIT and others Apache, and a number of those don't contain the actual [license file](https://github.com/geometry-labs/terraform-polkadot-user-data/blob/main/LICENSE) but just the [notice](https://github.com/geometry-labs/terraform-polkadot-user-data/blob/main/LICENSE) that is meant for file headers. Could you look into this?

**Comment by robcxyz** [comment]
@Nexus2k - You can find a tutorial on how to use the backup endpoints [here](https://github.com/geometry-labs/substrate-meta/blob/main/docs/archive_sync.md). Once the milestone is approved we have a medium article lined up for the community.

**Comment by robcxyz** [comment]
@alxs - Just went through the repos and added a couple missing licenses.  They should all be there and consistently Apache except for an inherited license for one our repos, the status page.  Thanks for pointing this out.

**Comment by alxs** [comment]
Thanks @robcxyz. I followed the instructions to get the archive data and noticed the download was actually very slow at around 8 GB/h, meaning it would have taken around 60 hours to download a full copy of the Kusama chain. @Nexus2k reckoned it could have to do with CloudFront caching and we confirmed that future downloads are indeed an order of magnitude faster up until the point a previous download stopped. So the question is whether this is a one-time thing per region or if there will regularly be 60-hour windows during which no one is able to sync a node, assuming someone is patient enough to let it complete at that speed. For how long are the files cached on CloudFront, and how many regions is it distributed across? Can we do anything to improve the speed of that first run?

The instructions also mention that if a download extends past the current window 'you can finish the download normally and then refresh the files by downloading a fresh copy of the manifest and catching any files you missed'. However, the approach described doesn't check for existing files but downloads the entire data again. The process is also currently a bit cumbersome and can't be used in automated node deployment as it requires manually inspecting the manifest and ensuring the data is consistent. A simple script or set of commands to automate this would be appreciated.

**Comment by alxs** [comment]
Also: I just found this https://github.com/polkadot-js/apps/pull/6746

Would you mind sharing what went wrong and steps you've taken to address it? The status page still shows a large number of requests being served, who is currently using your endpoints? We'd have appreciated it if you'd been transparent about this. I understand you've already run over budget and invested a lot of effort into the project, but I hope you understand I now have some reservations as to accepting a delivery that's being reported as having "never been operational".

One of the deliverables of milestone 1 is metrics on 'latency on a per json-rpc request method basis'. Where can I access those? And could you point me to the repositories where this and the alarms are implemented?

**Comment by robcxyz** [comment]
Hi @alxs, thank you for the feedback.  Regarding the long download speeds, I think this as you pointed out is a caching issue in your region on first download though I am still a little surprised that initial downloads were only 2 mbps. This is also as you mention is unacceptably slow for any unfortunate person that would have to deal with this.  We’ll need a little bit of time to fully vet a solution as cloudfront can be a somewhat complicated technology and nothing is jumping out that could improve our [terrafom module](https://github.com/geometry-labs/terraform-substrate-archive-cloudfront/blob/main/cloudfront.tf) from the [docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution). We will take a closer look though and get back with some proposed solutions as brass tacts, raw s3 is faster if this is regional problem that we have to deal with.  Fortunately cloudfront doesn’t refresh files that haven’t changed which is the vast majority so once a region is warmed up, this should not be an issue. 

Regarding the redownloading, we will update the instructions with an updated command that will avoid redownloading files which should not happen.  Was a missed flag in the utility which we can work on reducing down to a bootstrap script that can be included in an archive distribution.

**Comment by robcxyz** [comment]
Again @alxs, thank you for the feedback.  

Regarding what went wrong and what we have done to fix it.  Some instances crashed we believe due to heavy use and we had some issues with our health checks not propagating up to our global load balancer.  The instances are back up (crashed over the chrismas holiday) and the health check is fixed except for an issue with sticky sessions and retries which we’re looking into.  

Regarding who is using our endpoints, we can show you IPs and a list of methods they have been using. Since we were taken off polkadot.js we have seen a decrease in traffic but the endpoints are operational now and still being used.  

Regarding the latency on a per requerst basis, that is something we’ll have to build but can include it with our [existing kibana dashboard](https://kibana.us-west-2.aws.geometry.io/) as indeed it should be something we should be monitoring.  Also for the alarms, we can follow up with that over another thread as those are in a private repo at the moment.  

Very sorry for the issues with the endpoints and will follow up with further information about the things we can do to fix them.

**Comment by alxs** [comment]
Sounds good @robcxyz, thanks for getting back to me. Let me know when you've addressed the issues and I will have a look at it again.

I'm not sure what you mean by another thread but yes, could you please include the repositories of all the metrics and alarms described in the application in the deliverables? Btw, does the Kibana dashboard aggregate all data for Polkadot and Kusama nodes, and wouldn't it be more useful to have it separated? Could you also point me to the code used to aggregate the metrics?

Regarding the endpoints being operational, I just wanted to point out that I quickly tested the ones that had been removed from polkadot.js apps and the Polkadot one took close to 20 seconds to load while the Kusama one didn't load at all.

**Comment by robcxyz** [comment]
@alxs - Just wanted to link to this [PR](https://github.com/polkadot-js/apps/pull/6897) to have our endpoints listed back on polkadot.js which gives a deeper explanation of the outage.  We now have 10 days with no disruptions per out [status page](https://status.substrate.geometry.io/).  Will follow up soon on the archive node endpoints.

**Comment by robcxyz** [comment]
Hi @alxs, just a quick update on the archive sync tooling.  We’ve update our [meta repo](https://github.com/geometry-labs/substrate-meta) with an [automated sync script](https://github.com/geometry-labs/substrate-meta/blob/main/sync/archive_download.sh) that can be used to bootstrap a node.  Requires a dependency [aria2](https://github.com/aria2/aria2) which we can discuss how / where to properly integrate with a user’s deployment environment (ie VM / docker) but the process works manually and we will include this in the medium to be published.  Also a download of the archive takes less than an hour now from my location though I have high a very fast internet connection so mileage might vary between users.  We didn’t change anything on [the configuration](https://github.com/geometry-labs/terraform-substrate-archive-cloudfront) so I suspect that was more of an initial problem relating to cloudfront’s caching which can be somewhat of a black box. 

Other than that we still have a [clear status page](https://status.substrate.geometry.io/) and have our [modules passing tests](https://github.com/geometry-labs/terraform-polkadot-aws-asg/actions/runs/1826996895).

**Comment by alxs** [comment]
Thank you for keeping us updated and for all the effort you're putting into addressing the issues, e.g. the detailed post-mortem. The script looks great and it does considerably simplify things! I've noticed `aria2` is available via package manager on several distros, I think it's fine if you just point this out, list the two commands you have in the script now and link to the repo for anyone else.

As for the download speed, I'm observing the same behaviour as last time. It became drastically slower midway, most likely where I had left off last time. On the one hand, it's really great news to see that the files were persisted in my region for the entire past month, though on the other hand, this means the problem will most likely still appear for every first download in each region. I think the following questions from one of my comments above are still relevant:

> For how long are the files cached on CloudFront, and how many regions is it distributed across? Can we do anything to improve the speed of that first run?

**Comment by robcxyz** [comment]
Hi @alxs - I have updated the milestone 1 + 2 report and added the milestone 3 report.  Some updates since the last message above, we have been continuing to keep a healthy [status page](https://status.substrate.geometry.io/).  We had to upsize our nodes before their drives filled and have employed a mixed instance policy on the autoscaling group to take advantage of both spot and on-demand instances. We also included a new [websocket monitor](https://github.com/upptime/uptime-monitor/pull/164) for our status page which would have alarmed us to the major downtime incident we incurred end of December (json rpc endpoints were functional and being monitored). 

On the sync endpoint, we spun up instances in EU, Tokyo, Australia, and Brazil and did full syncs from these locations. Initial sync was slow (ie ~24 hours total sync time) but after the first sync, download speeds on both kusama and polkadot increased to less than 2 hours.

We also included links to some of our [elasticsearch pipelines](https://github.com/geometry-labs/substrate-meta/tree/main/elasticsearch) / kibana dashboard and [prometheus alarms](https://github.com/geometry-labs/substrate-meta/tree/main/prometheus) in our meta repo.

**Comment by alxs** [comment]
Sounds good, thanks for the updates. For now on hold pending submission and review of another amendment.

**Comment by alxs** [comment]
Thanks a lot for the very detailed documentation and reports. I started looking into the final delivery and realised I had the same questions as in previous rounds, some of which were left unanswered. Here are some questions from previous comments of mine:

> - One of the deliverables of milestone 1 is metrics on 'latency on a per json-rpc request method basis'. Where can I access those? And could you point me to the repositories where this and the alarms are implemented?
> -  could you please include the repositories of all the metrics and alarms described in the application in the deliverables? Btw, does the Kibana dashboard aggregate all data for Polkadot and Kusama nodes, and wouldn't it be more useful to have it separated? Could you also point me to the code used to aggregate the metrics?

Lastly, I still have the same general concern with regard to the documentation as I already touched on in our calls, which is that while the documentation for individual repositories is great, the meta repo contains no information about the overall structure of the project and it's impossible to know how to replicate its structure or how the separate repositories relate to each other. This would be greatly appreciated. I'm not sure if this is what was meant under milestone 3 "main reference architecture to maintain an exact mapping of what is running on the cloud and what is deployable in automation, any manual steps with explicit documentation" but that deliverable is also missing.

I know I already said this but note that since another amendment is currently in the works anyway, if there's anything of the above or anything else in the application that you can't deliver, you can also amend the deliverables - in that case however, we'll of course need to discuss it again.

**Comment by alxs** [comment]
One last thing - I tried running the script to sync an archive node and it didn't terminate in over 3 hours, I remember you mentioning it looped at some point. It looked like that might still have been the issue.

**Comment by robcxyz** [comment]
Hi @alxs - Regarding your points above. 

Regarding the reference architecture, we'll update the amendment to "Steady improvements to the underlying terraform modules with an exact mapping of what is running on the cloud and the public repositories that were used to deploy the nodes." We had described our efforts to build the reference architecture and reasoning to focus on making the underlying repositories more generalized in the amendment's appendix.  

For the latency per rpc request, we instead plotted requests per second and count on a rpc request basis which you can find at the public kibana. https://kibana.us-west-2.aws.geometry.io/.  Will update amendment with this distinction. 

For the source for the kibana dashboards and prometheus alarms, you can find the configuration files in our meta repo for [kibana](https://github.com/geometry-labs/substrate-meta/tree/main/elasticsearch) and [prometheus](https://github.com/geometry-labs/substrate-meta/tree/main/prometheus).  The full deployment was on the margin of the scope of the reference architecture but because of the refocus on the individual modules, the configuration files for these alarms were included in the meta repo which is just connects all the underlying repositories into a single location. 

As far as docs to connect all the work together, we don't necessarily see people adopting the whole stack because everyone will have slightly different setups for monitoring / logging and needs from it. The documentation for it's adoption is thus focused on the main repositories that deploy the project for the [node](https://github.com/geometry-labs/terraform-polkadot-aws-node) and [autoscaling group](https://github.com/geometry-labs/terraform-polkadot-aws-asg). 

Regarding the sync endpoints, I can do another experiment to see exactly what is going on but the script does two passes, the first to pull the whole archive and a second to pull updates since the download started and should only download files with different checksums.  Can take a closer look but the downloads I did before did stop on the second pass through. 

Will send the updates amendment with the above items shortly.

**Comment by alxs** [comment]
Sounds good. Thanks for providing more background.

I left the script running on several fresh Ubuntu 20.04 instances for 15+ hours and can confirm it doesn't terminate. Could you please look into it?

**Comment by alxs** [comment]
Hey @robcxyz, I haven't been able to reach you using either your emai or Element handle. Would you mind providing us with your new details, in case they have changed? The last amendment to this grant was accepted from our side and sent out for signature on March 31. If you were so kind as to sign it, I'd be happy to finish my evaluation ([1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/load_balanced_endpoints_operations_1_alxs.md), [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/load_balanced_endpoints_operations_2_alxs.md), [3](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/load_balanced_endpoints_operations_3_alxs.md)) and then we can finally close this grant.

I'd only ask, seeing as a fair amount of time has passed since my last review and I remember you were migrating the project repositories, if you could please double-check one last time that all the links in your delivery reports are up-to-date and working? Thank you.

**Comment by robcxyz** [comment]
Hi @alxs - Sorry for delay.  Had to step away from this for a while as I needed to focus on my new company.  I signed the amendment from March 31.  

Regarding updating the links, all the repos have been migrated to my new [github org](https://github.com/sudoblockio) so those links should redirect fine. The status page is inactive though as I have shut off the load balanced endpoints.  I did update the [sync script](https://github.com/sudoblockio/substrate-meta/blob/main/sync/archive_download.sh) and tested it out and was able to get the DB to download and a polkadot client to recover from the snapshot.  Should be more robust now. Also updated [db snapshot](https://github.com/sudoblockio/ansible-role-polkadot-truth) script with some fixes.  Also I'm still planning on applying for treasury at a later date when new staff come on board.  Meeting with CDN vendors this week as cloudfront, even with costs passed down to the treasury, is simply too expensive when other vendors offer rates at a fraction of the price. 

Let me know if there is anything else.

**Comment by alxs** [comment]
We have an action that should have commented the following but failed:

Congratulations on completing the first milestone of this grant! As part of the Grants Program, we want to help grant recipients acknowledge their grants publicly. To that end, we’ve created a [badge for projects](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md) that successfully deliver their first milestone.  Note that it must only be used within the context of the delivered work, so please do not display it on your team or project's homepage unless accompanied by a short description of the grant.<br/><br/> Furthermore, you're now welcome to announce the grant publicly. Please remember to observe the [foundation’s guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) in doing so. In case you haven't done so yet, you may also reach out to grantsPR@web3.foundation for feedback on your announcement and cross-promotion.<br/><br/> Thank you for your contribution and good luck with the remaining milestones, if any! As usual, please let us know if you run into any delays by leaving a comment on the application PR, or directly submitting an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Pull request merged**
