### PR TITLE
Blackprint visual programming for Polkadot.js - M1

### PR DESCRIPTION
**Pull request by StefansArya**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/774

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by StefansArya** [comment]
Some update since I submitted this PR:

1. Some UI bug fixes for mobile device (editor)
2. Fix loading progress that was not being displayed on the right top screen (editor's toast)
3. Display individual passed test on [GitHub Actions](https://github.com/Blackprint/nodes-polkadot.js/runs/5226003456?check_suite_focus=true) -> (🔥 Run Tests)
4. Add `View source code` on the node's menu
    - This feature will display a single file/source code from the latest update on GitHub
    - Currently will only work for [nodes-polkadot.js](https://github.com/Blackprint/nodes-polkadot.js)
      - Nodes from different module need an update to use this feature
    - Can't be used for dynamically generated nodes like nodes for Substrate Metadata (RPC, Constants, Extrinsics)

<details>
  <summary>4. "View source code" on the node's menu (image preview)</summary>

> Right click on the header to open this menu

node's menu
</details>

By the way, it's OK to ignore this comment as I just want to keep it up to date and help the reviewing process 👍

**Comment by cruikshankss** [comment]
Hi @StefansArya. Thank you very much for submitting your milestone and for the code updates. This has been my first week and I am sorry for any delays. I am checking in with my team to perhaps help with this evaluation. Sorry I have not got to it sooner.

**Comment by cruikshankss** [comment]
Hello @StefansArya,

This is my second week here and I apologize for any delays!

I have studied and taken notes on your tech stack and architecture diagram. They are wonderful, thank you! I'm excited to try your software-as-hardware visual programming! I used visual programming in middle school in woodshop and then university for the Intro to Computer Science class and it was really excellent.

I still must read through the rest of your grant and milestone 1. And then I need to do some set up in order to test your code. That's wonderful your software runs both in the browser/Node.js and you have an IDE!

Is there any urgency on your side? Sorry again for the delay.

**Comment by StefansArya** [comment]
Hi @cruikshankss, it's okay about the delay. Don't worry :) 
Because it's your first two weeks, feel free to take your time for reviewing the milestone.

> I used visual programming in middle school in woodshop and then university for the Intro to Computer Science class and it was really excellent.

Wow really? That's awesome! Before creating [Blackprint](https://github.com/Blackprint/Blackprint), my first experience with visual programming is with UDK Kismet (for developing games). It was very useful tool that saved a lot of my time rather than writing scripts and restarting the whole game engine 🤣 

> That's wonderful your software runs both in the browser/Node.js and you have an IDE!

Thank you! I have put lots of effort to develop it since 2020, I have optimized the architecture design to be modular so we can easily add new nodes and embed [sketch](https://github.com/Blackprint/Blackprint) or the [engine](https://github.com/Blackprint/Blackprint#blackprint-roadmap) to different project. The engine can be combined with some frontend framework for developing a web apps, but currently I only have a [small example](https://github.com/Blackprint/Blackprint#example) on how we can combine it. I also have prepared the engine for different programming languages, but because it was difficult to maintain multiple project so prioritized the engine for JavaScript first.

> I need to do some set up in order to test your code.

Okay, feel free to ask me some question if you find an issue.

> Is there any urgency on your side? Sorry again for the delay.

Hmm, I think not something too urgent. I'm just managing and maintaining some other stuff since last few days while waiting for feedback, helping my friend with his programming tasks on Discord, and thinking the most efficient solution to integrate Telegram/Discord's library for Blackprint. If the integration was success, in the future I can provide an example on how we can use Telegram to interact with Blackprint + Polkadot.js.

My current update about the Blackprint is: I have created a working concept with the remote engine.
It can provide an ability for the editor to remote control (Browser <-> Node.js) and allows you to work collaboratively with your friends remotely (Browser <-> Browser).

But the current issue is: how to make it secure if the third person is untrusted. 😅

So.. no need to worries, actually I already expect about the delay on the reviewing process.

**Comment by cruikshankss** [comment]
Hi @StefansArya! Thank you so much for the thoughtful response. I'm so happy to hear your journey of visual programming and how you're implementing Browser <-> Browser collaborative functionality!

I have completed manual UI testing and I'm looping back to the [testing guide](), which I originally got errors with:

```
Test suite failed to run
Cannot find module '../dist/engine.min.js' from 'tests/browser.test.js'
    > 1 | require("../dist/engine.min.js");
```


I might be missing something super obvious, and if so I'm sorry, but essentially, I cloned [the main Blackprint repo](https://github.com/Blackprint/Blackprint/) and then ran `npm i & npm run build-prod & npm test`. Then I realized perhaps I should clone just this [Polkadot.js module repo](https://github.com/Blackprint/nodes-polkadot.js) and run those same commands, but I tried that, and got this error:

```
sh: blackprint: command not found
[2]  + exit 127   npm run build-prod
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/ash/wthree/nodes-polkadot.js/node_modules/jest/bin/jest.js'
```
So then I re-cloned the polkadot node repo, and ran just `npm install` to start but I got a 

```
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
```
which is probably my fault since I'm working on a mobile hotspot since my internet is down. I do plan to head back out to a coffeeshop later to see if I can fix this, but just in case, could I please make sure I have the instructions clear?

What are the steps to install all the proper dependencies locally and run your excellent test suite?

I am very sorry if this is a simple mistake, but at least I've made a lot of progress on your evaluation. I'm nearly done & I've read through the entire first unit test and it seems like a great test suite so far.

**Comment by StefansArya** [comment]
Hi! thank you @cruikshankss!
From the file path, looks like you're trying to build the main [Blackprint](https://github.com/Blackprint/Blackprint)'s repository.

The command for compiling the module from [Blackprint](https://github.com/Blackprint/Blackprint) repository was little different, I'm also sorry about it because I haven't put the guide on the `README.md`.

After you cloned the repository, you will need to run `npm i` to install the dependencies and then `npm run compile` to build the source code from `/src` into the `/dist` folder. And after the build was completed, you can run the unit tests with `npm test`.

By the way if you stuck on which command to run first, you can check the [workflow's file](https://github.com/Blackprint/Blackprint/blob/master/.github/workflows/build.yml#L32) that was available on the repository.

About the error message:
- `Cannot find module ...` : it seems you haven't run `npm run compile`
- `sh: blackprint: command not found`: you need to install the dependency first with `npm install`
- `npm ERR! code ERR_SOCKET_TIMEOUT`: I never seen this, but it seems it was the internet connection indeed

> I am very sorry if this is a simple mistake, but at least I've made a lot of progress on your evaluation.

No worries, thanks a lot for your time processing the evaluation 👍 
I will add guide to compile and run test on the `README.md` from [Blackprint](https://github.com/Blackprint/Blackprint) repository and then update this PR.

**Comment by cruikshankss** [comment]
Hi @StefansArya, thank you so much for the quick response! Working on it now & I plan to keep you updated!

**Comment by cruikshankss** [comment]
Hi again @StefansArya! 

I just cloned a fresh copy of https://github.com/Blackprint/Blackprint and ran `npm install` successfully and `npm run compile` which failed. Here's the copy of my entire terminal (below). Honestly, I really appreciate your excellent documentation, testing guide, and great communication. 

```
~/testing/Blackprint ± master
❯ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 1318 packages, and audited 1319 packages in 47s

59 packages are looking for funding
  run `npm fund` for details

19 vulnerabilities (8 moderate, 11 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

~/testing/Blackprint ± master
❯ npm run compile 

> @blackprint/sketch@0.6.3 compile
> gulp compile

[12:17:25] Using gulpfile ~/testing/Blackprint/gulpfile.js
[12:17:25] Starting 'compile'...
[12:17:25] 'compile' errored after 1.4 ms
[12:17:25] Error: ENOENT: no such file or directory, open 'editor/dev.html'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.clearGenerateImport (/Users/ash/testing/Blackprint/node_modules/scarletsframe-compiler/sfcompiler.js:25:17)
    at Object.beforeInit (/Users/ash/testing/Blackprint/gulpfile.js:177:8)
    at init (/Users/ash/testing/Blackprint/node_modules/scarletsframe-compiler/sfcompiler.js:53:24)
    at compileOnly (/Users/ash/testing/Blackprint/node_modules/scarletsframe-compiler/sfcompiler.js:157:2)
    at /Users/ash/testing/Blackprint/node_modules/scarletsframe-compiler/sfcompiler.js:167:30
    at taskWrapper (/Users/ash/testing/Blackprint/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (node:domain:421:15)
    at runBound (node:domain:432:12)


```

**Comment by cruikshankss** [comment]
Hi again @StefansArya, 

I am also trying to assess your deliverable (0d.)

On your grant application, you mentioned for milestone 1:

| 0d. | Docker | We will use GitHub Action/Workflow instead, for manual UI testing/interaction we can use Blackprint Editor |

So I assume you are using GitHub Action/Workflow instead of Docker, so I believe you can remove "Docker" from the deliverable list in milestone 1 delivery:

> | 0d. | Docker | [Test files](https://github.com/Blackprint/nodes-polkadot.js/tree/ce4de7b316d864489d4f207144ea87e4310e4299/tests), [GitHub Action](https://github.com/Blackprint/nodes-polkadot.js/actions/workflows/build.yml) | To run the test manually, please follow the instruction on the `README.md`. For manual UI testing, you can use the example provided for each deliverable nodes below. |

I am very new to GitHub Actions/Workflow and would appreciate a little explanation of if this is related to Docker (or instead of Docker), how it helps with testing, and if there are steps for me to recreate the testing?

Perhaps you could rename the deliverable from "Docker" to "GitHub Actions/Workflow" if you're not using a Dockerfile (or perhaps you are?) and give a little description of how to run the tests? Thank you so much! Sorry again that I am very new and sorry for any delay!

**Comment by StefansArya** [comment]
It seems the submodules haven't been cloned, the `/editor` and the `/engine-js` may be empty.

It's recommended to also clone the submodule with like I [described it](https://github.com/Blackprint/Blackprint#build-and-run-the-unit-test):
`git clone --depth 1 --recurse-submodules https://github.com/Blackprint/Blackprint.git .`

But it may take sometime to finish if you have internet problem, maybe you can also manually clone from it's repository and put them on it's folder
1. [engine-js](https://github.com/Blackprint/engine-js/tree/ae07915e43e7c55105e4d1132b9664d04d755626)
2. [editor](https://github.com/Blackprint/blackprint.github.io/tree/dca46d1e40fa1dca1aa68e3e57e24734faef3580)

If you run the `git clone` command, it should be ended up with:
```sh
Receiving objects: 100% (163/163), 36.72 KiB | 1.31 MiB/s, done.
Resolving deltas: 100% (84/84), done.
Submodule path 'editor': checked out 'dca46d1e40fa1dca1aa68e3e57e24734faef3580'
Submodule path 'engine-js': checked out 'ae07915e43e7c55105e4d1132b9664d04d755626'
```

---

> So I assume you are using GitHub Action/Workflow instead of Docker, so I believe you can remove "Docker" from the deliverable list in milestone 1 delivery

Yes, I keep the Docker on the `0d` because [the template](https://github.com/w3f/Grants-Program/blob/77c2359603c172e25398fa08a4331c393c58aa33/applications/application-template.md?plain=1#L116) said that I need to state my reason on the specification if I didn't intend to deliver it. But to be honest I get little confused right now that I need to change `Docker` to `GitHub Action` or just add a Dockerfile that can be used for testing. Both of them is can be used for testing the project anyway but I prefer to use GitHub Action because it's easy to setup and will immediately run after I push my commit on the repository. So everyone can easily see if the tests was passing or failing.

> and if there are steps for me to recreate the testing?

Hmm, you will need to fork the project if you want to modify the workflows. The `yaml` file in the `/.github/workflows` is used to configure GitHub Actions. I have [configured](https://github.com/Blackprint/nodes-polkadot.js/blob/bf9eae915b8246c70e956e98da8bcf6ed8917e95/.github/workflows/build.yml#L3-L11) the `build.yml` to automatically run build when I pushed new commit and may also try to build a new PR on the repository.

By the way, let me know if I actually need to rename `Docker` on my grant proposal, I just want to confirm it if I have misunderstand because of the template or maybe you prefer to use `Docker` instead

**Comment by cruikshankss** [comment]
Hi @StefansArya, 

I am so sorry for the confusion. 

You are correct, the `git clone --depth 1 --recurse-submodules https://github.com/Blackprint/Blackprint.git` works great; I was able to successfully run the tests and they passed!

Also, I'm so sorry for the confusion on (0d.). You are correct. Sorry, I am new here, and I was just confused. You *do not* and *should not* rename "Docker" on the deliverable list. You are correct. 

Thank you for explaining to me the purpose of GitHub Actions. That is sufficient and thank you for so clearly explaining the reasoning to me so I could learn about GitHub Actions.

No Dockerfile is necessary. I was just confused because I'm new, sorry. I do not need to modify the workflows. Your testing guide and tests are more than sufficient. Excellent job, thank you so much!! I am so delighted you are part of the ecosystem and so readily help beginners like me. Finishing up my evaluation now.

**Comment by StefansArya** [comment]
> Sorry, I am new here, and I was just confused. You do not and should not rename "Docker" on the deliverable list.

No worries, I'm also uncertain too when I was write the proposal, but it has been reviewed too so I think it was OK when it got approved.. Anyway, thanks for make it clear too! I really appreciate it 😄 

> Excellent job, thank you so much!! I am so delighted you are part of the ecosystem and so readily help beginners like me.

You're welcome! I'm also very happy to found this grants program actually and found people here was giving support to open source project. It was motivated me a lot to work on open source project.

---

By the way, I think I will be away for some hours (and may be online again at afternoon). Good luck for learning GitHub Action! Maybe you may also interested to check the GitHub Marketplace (Types -> Actions) to find some additional workflows for your project, maybe like send workflow status to Telegram or download the build artifact and automate the project release. or maybe reading article may be suitable for newbie.

**Review by Noc2 — APPROVED** [review]

**Comment by cruikshankss** [comment]
Thank you @Noc2! 

I have forwarded your invoice @StefansArya. 

Thank you for your thoughtful responses [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/377#issuecomment-1055279093) to my evaluation. Your points make sense and I'm happy to see you've already thought deeply into the points I raised. 

I wish you success in building and maintaining Blackprint! 🍀🙏

**Comment by RouvenP** [comment]
hi @StefansArya we transferred the payment today. Thanks!

**Comment by StefansArya** [comment]
I can confirm that I have received it @RouvenP
Thank you very much! 😆

**Pull request merged**
