### PR TITLE
Create On_chain_cash_exchange-Milestone_2.md

### PR DESCRIPTION
**Pull request by dsrdrk11a**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/803

### CODE REVIEW

**Comment by dsrdrk11a** [comment]
@cruikshankss great! Thank you for the clarification!

**Comment by cruikshankss** [comment]
Many congrats on completing a successful grant! More notes in [my M2 eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ocex_2_cruikshankss.md). :)

**Comment by cruikshankss** [comment]
@dsrdrk11a I've forwarded your invoice internally. Thank you again!

**Comment by dsrdrk11a** [comment]
Wow! That's amazing! @cruikshankss , thank you for the info.
We look forward to develop the entire product!

**Comment by RouvenP** [comment]
hi @dsrdrk11a we transferred the payment, thanks!

**Pull request merged**
