### PR TITLE
Fiat on-off ramp milestone 3 delivery

### PR DESCRIPTION
**Pull request by dastansam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1423

### CODE REVIEW

**Comment by wasabrot** [comment]
Invoice Form has also been filled out for this milestone.

**Comment by dsm-w3f** [comment]
@wasabrot thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/FIAT-on-off-ramp_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue the evaluation.

**Comment by dsm-w3f** [comment]
@dastansam thank you for the improvements and fixes. The application worked ok besides a small problem that could be fixed. See the details in the evaluation document. This doesn't prevent the acceptance of the milestone delivery, which is accepted. I'll forward the invoice internally and the payment should take place within two weeks. Great job!

**Comment by fededubbi** [comment]
Hi @dastansam,

I noticed that in the total amount of the invoice you added both DAI and USD currency, but there is another amount next to the DAI address.

Can you please insert only the amount in DAI also on the invoice?

Many thanks
Federica

**Comment by RouvenP** [comment]
hi @dastansam we transferred the payment today

**Pull request merged**
