### PR TITLE
ISO20022

### PR DESCRIPTION
**Pull request by OpenSmartContract**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1940 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
**UPDATE:** Changed application document to fix checks.

**Comment by keeganquigley** [comment]
Thanks for the delivery @OpenSmartContract I have started my evaluation and added some comments to the [document](https://docs.google.com/document/d/1pMY0D-vTBEVq65Ro4PW3LzXrT1ZVl9l4r7jIMHmfBqs/edit#heading=h.ukq4ckz52joz). Let me know if you can address these. Thanks!

**Comment by OpenSmartContract** [comment]
Thanks @keeganquigley for your evaluation and great comments in the doc. Pleasure addressed them. Appreciated for improving deliverables.

**Comment by keeganquigley** [comment]
Thanks @OpenSmartContract just added a few more.

**Comment by OpenSmartContract** [comment]
@keeganquigley Excellent points and suggestions. Think I've covered them all with clarifications. Please feel free to resolve comments there if addressed so we could filter them by status.  Thx!

**Comment by keeganquigley** [comment]
Thanks for the fixes and updates @OpenSmartContract since the paper now technically meets the requirements for the deliverables I'm willing to accept it. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/iso20022_1_keeganquigley.md). Please allow up to 14 days for payment processing.

**Comment by OpenSmartContract** [comment]
Thanks @keeganquigley for the evaluation and acceptance. The team learned and enjoyed this w3f project. We look forward to future collaborations!

**Comment by keeganquigley** [comment]
It looks like some of the GH actions have failed due to a missing **Total Cost** section, so I will post the messages below:

We noticed that this is the last milestone of your project. Congratulations on completing your grant! 🎊

So, where to from here? First of all, you should join our [Grants Community chat](https://matrix.to/#/!XpynPDLusWUWfDpaqr:matrix.org?via=web3.foundation&via=matrix.org), if you haven't already, so we can stay in touch.
If you are looking for continuative support for your project, there are quite a few options. The main goal of the W3F grants program is to support research as well as early-stage technical projects. If your project still falls under one of those categories, you might want to apply for a follow-up grant. However, depending on your goals and project status, there are other support programs in our ecosystem that might be better suited as the next step. For example, projects with a Business Case/Token should look into the [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) or [VC Funding](https://parachains.info/investors) and Common Good projects have a good chance of receiving [Treasury Funding](https://github.com/w3f/Grants-Program#treasury). If you are looking for guidance, the team at https://substrate.io/ecosystem/square-one/ has compiled a list of ecosystem support sources and are happy to help you navigate it.

For a more comprehensive list, see our [Alternative Funding page](https://w3f.github.io/Grants-Program/funding). Let us know if you have any questions regarding the above. We are more than happy to point you to additional resources and help you determine the best course of action.
Lastly, we hope your W3F grant was a success and we want to thank you for being part of the journey!

**Comment by keeganquigley** [comment]
Please fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform?usp=pp_url&entry.1070766548=https://github.com/w3f/Grant-Milestone-Delivery/pull/1032) in order to initiate the payment process. Thank you!

**Comment by OpenSmartContract** [comment]
Thanks for the congrats and links!  Just filled out the invoice form. Much appreciated!

**Pull request merged**
