### PR TITLE
Delivery: ArtZero InkWhale Milestone 2

### PR DESCRIPTION
**Pull request by nad128668**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1342 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by nad128668** [comment]
I split this M2 from M1 on https://github.com/w3f/Grant-Milestone-Delivery/pull/734 which Evaluation was completed by @dsm-w3f 

We will provide update on previous M2 Evaluation Report in the next few days.
@hnnam0906 will take over the process

**Comment by hnnam0906** [comment]
Dear @dsm-w3f,

We add some updates:

1. Smart Contract Development: Add contract deployment on testnet at https://github.com/InkWhale-net/contracts/blob/main/docs/contract_deployment_and_update_addresses_abis.md
 
2. Contract test: Update gas limit to suitable for Weight V2. Details in https://github.com/InkWhale-net/contracts/tree/main/tests

3. Frontend: Update FE, new .env, abis and add instructions at https://github.com/InkWhale-net/frontend/blob/main/README.md. 

4. BE: Update new abis for BE and add instructions at https://github.com/InkWhale-net/backend/blob/main/readme.md

Please kindly review and let me know if you need anything.

**Comment by dsm-w3f** [comment]
@nad128668 and @hnnam0906 thank you for the improvements and fixes. I tested the application and worked well. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_2_dsm-w3f.md). The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great work!

**Comment by RouvenP** [comment]
hi @nad128668 we transferred the payment today.

**Comment by nad128668** [comment]
Hi @RouvenP I haven't seen the amount in my account yet.

**Comment by RouvenP** [comment]
hi @nad128668, see here: https://statemint.subscan.io/account/1scixS3ofLuBN8XEQQdSjMQaLtvvbcJiQAqpnaov8xopX78

Are you using polkadot.js or something else? Feel free to reach out to us directly (invoices@web3.foundation)

**Comment by RouvenP** [comment]
great, glad to hear. Thanks for confirming.

**Pull request merged**
