### PR TITLE
dotpulse-milestone_2

### PR DESCRIPTION
**Pull request by arctic-ash**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1186

### CODE REVIEW

**Comment by randombishop** [comment]
Thanks for this delivery @arctic-ash 
I have a couple of other evaluations in my backlog right now but I will work on this one next week and get back to you with feedback asap.

**Comment by randombishop** [comment]
First quick remark: the link in the documentation tagged as `Webapp-docs` actually points to the scraper repo.

**Comment by randombishop** [comment]
Also, in previous milestone, I had suggested a database schema to complete the documentation. Did you add one?

**Comment by arctic-ash** [comment]
>Thanks for this delivery @arctic-ash
>I have a couple of other evaluations in my backlog right now but I will work on this one next week and get back to you with feedback asap.

Take your time, we'll be waiting patiently for your feedback. 

> First quick remark: the link in the documentation tagged as `Webapp-docs` actually points to the scraper repo.

Fixed it. Thanks for noticing!

> Also, in previous milestone, I had suggested a database schema to complete the documentation. Did you add one?

We just added a database schema as you suggested. We did observe the "Evaluation" made in the previous milestone, but missed the "General Notes". Fixed it, thank you!

**Review by Noc2 — APPROVED** [review]

**Comment by randombishop** [comment]
@arctic-ash Happy to inform you that your delivery was accepted.

Evaluation notes here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotpulse_2_randombishop.md

I forwarded your invoice to the finance team, please allow for up to two weeks for processing. (maybe 3 with holiday season.)

**Comment by RouvenP** [comment]
hi @arctic-ash we transferred the payment today.

**Pull request merged**
