### PR TITLE
FiDi DotSight Milestone 3 Delivery

### PR DESCRIPTION
**Pull request by fidiroman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1748

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @fidiroman I have started my evaluation. In the meantime, I am not finding a delivery for milestone 2. Did you ever submit this?

**Comment by fidiroman** [comment]
Thank you @keeganquigley, great to connect again. We've reordered the sequencing a bit in the most [recent delivery](https://github.com/fidiroman/Grant-Milestone-Delivery/blob/0045b32978b4fc53db66d5e3bd70a7baed702e71/deliveries/fidi-dotsight-milestone-1.md) (see "Scope"), the M2 will come shortly after M3 as we're extending the dashboards collection in parallel. Let us know if it'd necessitate a brief update to the original proposal, happy to craft one if so; thanks!

**Comment by keeganquigley** [comment]
@fidiroman ah thanks for the reminder, I see [an amendment](https://github.com/w3f/Grants-Program/pull/1971) was already passed for this so unless the deliverables for M2 are changing significantly from the ones listed in the application, I think there's no need for another one. I'll make a note of this for the next delivery, thanks!

In the meantime, I am having trouble running the `dotsight` repo. The Docker container runs successfully:
```sh
docker compose up -d

[+] Running 15/15
 ✔ db 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                             13.5s
   ✔ 24e221e92a36 Pull complete                                                                                      3.5s
   ✔ 85b20a3ade36 Pull complete                                                                                      0.9s
   ✔ dfccb87eabcd Pull complete                                                                                      1.4s
   ✔ c2b36c21cfca Pull complete                                                                                      2.2s
   ✔ b6773915c6e6 Pull complete                                                                                      5.4s
   ✔ 0f1622bae22c Pull complete                                                                                      3.8s
   ✔ 1fa0f3ae7f27 Pull complete                                                                                      3.9s
   ✔ 90e24ee29327 Pull complete                                                                                      4.2s
   ✔ 5b5e3d50b597 Pull complete                                                                                     10.1s
   ✔ 0109b546d717 Pull complete                                                                                      4.6s
   ✔ 77071f9d5376 Pull complete                                                                                      5.6s
   ✔ a03caa73b840 Pull complete                                                                                      6.6s
   ✔ 70606bcdcc01 Pull complete                                                                                      6.6s
   ✔ 9911f6f158a5 Pull complete                                                                                      7.3s
[+] Running 2/2
 ✔ Network dotsight_default  Created                                                                                 0.0s
 ✔ Container dotsight-db-1   Started                                                                                 0.7s
docker ps
CONTAINER ID   IMAGE         COMMAND                  CREATED          STATUS          PORTS                    NAMES
2f6180b1d0b5   postgres:16   "docker-entrypoint.s…"   15 seconds ago   Up 14 seconds   0.0.0.0:5433->5432/tcp   dotsight-db-1
```
But I still get an error when trying to start the service:
```ts
npm run typeorm:run-migrations

> @fidi/dotsight@0.0.1 typeorm:run-migrations
> npm run typeorm -- migration:run -d ./typeorm.config.ts


> @fidi/dotsight@0.0.1 typeorm
> ts-node ./node_modules/typeorm/cli migration:run -d ./typeorm.config.ts

Error during migration run:
Error: getaddrinfo ENOTFOUND dotsight
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dotsight'
}
```
```ts
npm start

> @fidi/dotsight@0.0.1 start
> nest start

[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [NestFactory] Starting Nest application...
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] AppModule dependencies initialized +13ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] MixersModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] MiddlewaresModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] HttpModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 7404  - 12/21/2023, 2:00:34 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
Error: getaddrinfo ENOTFOUND dotsight
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
[Nest] 7404  - 12/21/2023, 2:00:37 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
Error: getaddrinfo ENOTFOUND dotsight
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
```
My .env file looks like this:
```
DB_HOST=dotsight
DB_PORT=5433
DB_NAME=dotsight
DB_USERNAME=dotsight
DB_PASSWORD=d0tS1gHtRul3z
JWT_SECRET=secret-jwt
SESSION_SECRET=some-secret
UI_HOST=http://localhost:3001
```
Can you help with what I am missing? Or should I just be using the `dotsight-UI` repo for this milestone?

**Comment by keeganquigley** [comment]
Also, on the live site, the option to sign in with Twitter currently doesn't work. It is giving an error:
```{"statusCode":500,"message":"Internal server error"}```

It works with Google, although I wish there an option to connect with my wallet instead of traditional Web2 OAuth.

**Comment by keeganquigley** [comment]
Also what key should I be entering here? Is there one I can use for a demo?

fidi key

**Comment by semuelle** [comment]
pinging @fidiroman

**Comment by fidiroman** [comment]
Thanks for your patience @keeganquigley @semuelle, and happy holidays, we appreciate the review!

Regarding launching the `dotsight` repo, it seems like the issue is in `DB_NAME=dotsight`, you'd want to use `localhost` instead there. Great catch, I've streamlined the docs and re-validated the steps; [take a look](https://github.com/fidi-tech/dotsight).

As for the data provider keys, we naturally ask users to obtain their own provider API keys for local deployments. To skip that step, however, we just finished integrating FiDi-paid keys into the online product. Give it a try! https://dot.fidi.tech/. Additionally, I just DM'ed you a couple of keys for testing things locally. Feedback welcome!

Great catch on the Twitter OAuth, too. Twitter just changed their authentication API, so we're taking that option down for now and will re-release it when updated. The wallet login is definitely coming - we're going through its community testing in one of the DotSight-derived [products](https://app.fidi.tech/). When it's mature enough, we'll merge it into the public repo; the bar is definitely higher there.

Excited to hear more of your thoughts on the submission, thank you!

**Comment by semuelle** [comment]
That sounds great, thanks @fidiroman. One of us will continue the review in the coming days.

**Comment by fidiroman** [comment]
Quick update: Chainlink, DappRadar, and ANKR data sources are also merged now, e.g., see Historical Lines -> Token -> Price for Chainlink's price feeds. Our team is working on a new UI release focused primarily on non-technical users, with most configurations being preset as defaults and the chart-building streamlined. Coming soon as a part of the next milestone.

**Comment by keeganquigley** [comment]
Thanks for the changes @fidiroman everything is running now. I'm happy to accept the milestone, here is my [final eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fidi_dotsight_3_keeganquigley.md). Looking forward to seeing it all come together in the next milestone.

**Comment by RouvenP** [comment]
hi @fidiroman we just sent the payment

**Comment by fidiroman** [comment]
Thanks @keeganquigley @RouvenP; talk to you soon in the next milestone!

**Pull request merged**
