### PR TITLE
Create Web3Go_Milestone_2.md

### PR DESCRIPTION
**Pull request by Moehringen**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1293 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @Moehringen someone will take a look at it shortly.

**Comment by keeganquigley** [comment]
Hi @Moehringen thanks for the delivery. I am in the process of checking the evaluation. In the meantime:

- Can you please submit an updated invoice to include your Polkadot/Statemint address? It should match the one on the application.
- Can you please fix the PR so that it links to your application PR instead of "XXX"?

Thank you!

**Review by keeganquigley — CHANGES_REQUESTED** [review]
@Moehringen please see the comments in the above evaluation by @JosephKnecht-lab. I also have the following comments:

- I agree that for deliverable 0c. we are asking for a guide to the unit/e2e tests for the local build. We don't evaluate the CI/CD production side of things.
- Don't worry about the incompatibility with the Apple M2 chip; despite the warning, I was able to run it using the Docker AMD64 emulator (and on Ubuntu 20.04 as well).
- The Docker build for me is actually around 4 gigs which I agree is rather large. It is not a requirement to fix but consider making it smaller.
- Is there a reason you chose not to write an article? Typically this is required for the last milestone.

Thanks!

**Comment by Moehringen** [comment]
> Hi @Moehringen thanks for the delivery. I am in the process of checking the evaluation. In the meantime:
> 
> * Can you please submit an updated invoice to include your Polkadot/Statemint address? It should match the one on the application.
> * Can you please fix the PR so that it links to your application PR instead of "XXX"?
> 
> Thank you!

Done !

**Comment by keeganquigley** [comment]
Thanks for the updated invoice @Moehringen, however we only offer USDT payments on Statemint, as our [payment options](https://github.com/w3f/Grants-Program#pencil-process) have changed recently. Would you be willing to be paid in USDC instead? 

If so, you can keep the same address on the invoice but it would need to be updated to note USDC as the payment currency. I hope this helps and sorry for the confusion.

**Comment by Moehringen** [comment]
hi Keegan,

I have submitted a new invoice and noted USDC as the payment currency.

thanks!

**Comment by Moehringen** [comment]
We will submit an article and update unit/e2e tests for local build within
this week.  thanks!

**Comment by Moehringen** [comment]
Sorry I have reopen a new PR: https://github.com/w3f/Grant-Milestone-Delivery/pull/808 , can we start from there? 

I have made the changes according to the requirement.

**Comment by keeganquigley** [comment]
Sure thing @Moehringen thanks for the heads up, no worries I will just use the new one.

**Pull request closed without merging**
