### PR TITLE
shivarthu-milestone-2

### PR DESCRIPTION
**Pull request by amiyatulu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/525 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the delivery @amiyatulu a couple of initial comments:

- The application states that React will be used for the front-end. Instead, the front-end delivered is in Leptos/Rust. Can you state the reasons for the change? As a change like this typically requires an amendment to be approved ahead of time.
- On the [deployed Leptos app](https://shivarthu.on-fleek.app/), when I select the "test net" button it doesn't do anything. Is this supposed to be working?
- There is a ton of template text still left in the readme from the Substrate Node Template. Can you please remove the text that doesn't apply for this project? Most of it can be removed since this template has been deprecated, leaving a lot of broken links.
- Some unit tests are [failing](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/shivarthu_2_keeganquigley.md), if you could look into fixing these. Thanks!

**Comment by amiyatulu** [comment]
Hi, updated the unit tests and cleaned up the readme.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @amiyatulu thanks for the fixes, much appreciated. The unit tests are all passing now. Moving on, there are a ton of `cargo clippy` warnings, can you take a look to see if any of these are easily fixable?

Additonally, when running `cargo test --features runtime-benchmarks` there are quite a few benchmarking tests failing. Can you please take a look at the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/shivarthu_2_keeganquigley.md) and provide fixes when possible. 

Since it's the last milestone, would be great if we could button these up as much as possible. Thanks!

**Comment by amiyatulu** [comment]
Hi @keeganquigley Thank you for your reply. Working on benchmarking, and  will get back to you when done.

**Comment by keeganquigley** [comment]
Thanks @amiyatulu sounds good. Also, FYI I used the wrong command for benchmarks, the updated one is what I actually used `cargo test --features runtime-benchmarks`

**Comment by keeganquigley** [comment]
Hi @amiyatulu making any progress?

**Comment by amiyatulu** [comment]
Yes, I have updated benchmark of two pallets, more two pallets are left.

**Comment by keeganquigley** [comment]
Sounds good, no rush, just wanted to make sure progress was being made. Thanks!

**Comment by amiyatulu** [comment]
@keeganquigley Hi, please check out `cargo test --features runtime-benchmarks` Its successfully running now.

**Comment by keeganquigley** [comment]
Thanks for the fixes @amiyatulu looks great now. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/shivarthu_2_keeganquigley.md). Happy to pass the milestone, good work!

**Comment by amiyatulu** [comment]
Hi, may grant was approved before Feb 19, 2024  and don't contain DOT portion. The form asks Polkadot AssetHub address, but application form contain ethereum address. Should I give the ethereum address in Invoice?

**Comment by keeganquigley** [comment]
Hi @amiyatulu yes we stopped issuing ETH mainnet payments a while back. Would you be willing to accept USDC on AssetHub instead?

**Comment by amiyatulu** [comment]
@keeganquigley Hi, currently there are no good UI for asset swapping in AssetHub. I tried to teleport some DOT in [kheopswap](https://kheopswap.xyz/#/polkadot/swap), it failed without any error messages, may be some bug in it. Is it possible to pay DAI in Eth mainnet this time? I asked in W3F Community Element Chat, they said its still valid.

**Comment by amiyatulu** [comment]
@keeganquigley Thank you. Ya I already filled the form.

**Comment by amiyatulu** [comment]
Hi @keeganquigley Any updates when payment will be released.

**Comment by keeganquigley** [comment]
Hi @amiyatulu since it has been almost two weeks, I believe the payment should go out in this Friday's batch. Please let me know if you don't receive it after Friday. Thanks!

**Comment by amiyatulu** [comment]
@keeganquigley Hi, I have not recieved the payment last week. I was told to update the invoice as it was incomplete. I have re-submitted the invoice.

**Comment by amiyatulu** [comment]
Hi @keeganquigley, any updates regarding payment?

**Comment by keeganquigley** [comment]
Hi @amiyatulu just responded to your email :)

**Comment by RouvenP** [comment]
hi @amiyatulu we just sent the payment

**Pull request merged**
