### PR TITLE
Slushie mixer eval cromm vardek

### PR DESCRIPTION
**Pull request by CrommVardek**
My evaluation for the [Slushie Mixer Delivery 1](https://github.com/w3f/Grant-Milestone-Delivery/pull/506)

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the evaluation. It would be great if you could link to the lines in the files where each function is implemented. Also, we try to include some form of version in our evaluations, either by stating the commit hash being reviewed, or by using the permalink each time (like you did for the `Testing doc`). GH has a nice shortcut for that: https://docs.github.com/en/repositories/working-with-files/using-files/getting-permanent-links-to-files.

I will take a closer look early next week.

**Comment by CrommVardek** [comment]
Sure, I'll do that by next week and update the links accordingly

**Comment by CrommVardek** [comment]
I've adapted my evaluation accordingly.

**Comment by semuelle** [comment]
Thanks for the update, @CrommVardek. I have nothing else to add. 

Can you please confirm that the Kusama address in the document is yours?

**Comment by CrommVardek** [comment]
@semuelle I confirm the address in the document is mine `JCkD7cRTpfkQmk5v6XvWvR1JPTvrouPXSGmQqtWPcJQKFzx`

**Comment by CrommVardek** [comment]
Hi @semuelle , I'm unsure about the delay between the merging of an external evaluation and the transfer, but I have not received a transfer yet (https://kusama.subscan.io/account/JCkD7cRTpfkQmk5v6XvWvR1JPTvrouPXSGmQqtWPcJQKFzx?tab=transfer)

**Comment by RouvenP** [comment]
hi @CrommVardek apologies for our late reply. It took a bit longer due to vacation absences. I will make sure to get the KSM to you asap and let you know once done.

**Comment by RouvenP** [comment]
hi @CrommVardek we just transferred the KSM.

**Pull request merged**
