### PR TITLE
Create hybrid-3.md

### PR DESCRIPTION
**Pull request by ethernomad**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1582 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @ethernomad thanks for the delivery. @Ali-Usama is also in the process of conducting an external evaluation, but it is still in progress. In the meantime, I was able to get all the indexers to run but perhaps you could make the indexer instructions clear that the `[image_hash]` needs be replaced with the actual hash. Otherwise an error occurs:
```
ubuntu@ip-172-31-44-8:~/polkadot-indexer$ docker run --rm -p 8172:8172 [image_hash] -c polkadot -b 16730000 -p 8172
docker: invalid reference format.
See 'docker run --help'.
```
Also, for some reason the Docker image fails to build on my Apple machine:

```rust
#9 253.2   process didn't exit successfully: `/usr/local/rustup/toolchains/nightly-aarch64-unknown-linux-gnu/bin/rustc --crate-name metadata --edition=2021 metadata/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=3582e4355d5d6152 -C extra-filename=-3582e4355d5d6152 --out-dir /usr/src/polkadot-indexer/target/release/deps -L dependency=/usr/src/polkadot-indexer/target/release/deps --extern subxt=/usr/src/polkadot-indexer/target/release/deps/libsubxt-7f9f1e061408a150.rmeta -L native=/usr/src/polkadot-indexer/target/release/build/ring-6865e534f3ab37c2/out` (signal: 9, SIGKILL: kill)
------
process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 101
```

The [Dockerfile](https://github.com/hybrid-explorer/polkadot-indexer/blob/main/Dockerfile) doesn't specify an OS or a specific toolchain so I'm not sure if it's the problem is with `rustc 1.73.0` version or with my Apple M1 chip.

**Comment by Ali-Usama** [comment]
@ethernomad One more issue with the docker builds that I found in `polkadot-indexer` as it's not building successfully. 

```
#0 835.8    Compiling home v0.5.5
#0 836.4    Compiling hybrid-indexer v0.1.0
#0 849.0    Compiling clap v4.3.19
#0 849.2    Compiling metadata v0.1.0 (/usr/src/polkadot-indexer/metadata)
#0 2035.1 error: could not compile `metadata` (lib)
#0 2035.1 
#0 2035.1 Caused by:
#0 2035.2   process didn't exit successfully: `/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name metadata --edition=2021 metadata/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C metadata=c8f93a828242b360 -C extra-filename=-c8f93a828242b360 --out-dir /usr/src/polkadot-indexer/target/release/deps -L dependency=/usr/src/polkadot-indexer/target/release/deps --extern subxt=/usr/src/polkadot-indexer/target/release/deps/libsubxt-3998efaa841aca38.rmeta -L native=/usr/src/polkadot-indexer/target/release/build/ring-37c484a9d815ace0/out` (signal: 9, SIGKILL: kill)
------
Dockerfile:9
--------------------
   7 |     RUN rustup default nightly
   8 |     
   9 | >>> RUN cargo build --release
  10 |     
  11 |     EXPOSE 8172 8173 8174 8175
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 101
```

you can also refer to [this](https://github.com/w3f/Grant-Milestone-Delivery/pull/961) for a detailed evaluation and the error message.

**Comment by ethernomad** [comment]
Thanks for the reviews!

I think the issue with the docker build failing is that on MacOS docker runs in a VM with a fixed amount of memory. You can increase the memory size from the default of 2GB as described here: https://docs.docker.com/desktop/settings/mac/#advanced

The subxt macro to build the API from the metadata takes considerable resources and it needs to be run for each of polkadot, kusama, rococo and westend.

I have updated the docker instructions to explain `[image_hash]`.

**Comment by ethernomad** [comment]
I made some changes to reduce memory usage during the docker build. Can you perform a `git pull` on polkadot-indexer  and try it again?

**Comment by Ali-Usama** [comment]
> I made some changes to reduce memory usage during the docker build. Can you perform a `git pull` on polkadot-indexer and try it again?

Thanks for the swift fixes, @ethernomad. Working fine on my end now. Updating the evaluation accordingly

**Comment by keeganquigley** [comment]
Thanks @Ali-Usama I'm assuming this means you're done making changes?

**Comment by keeganquigley** [comment]
Also I think the link in [Deliverable 2](https://github.com/hybrid-explorer/hybrid-indexer/blob/main/doc/testing-guide.md) in the testing guide also points to the wrong repo - it should point to the [Polkadot Indexer](https://github.com/hybrid-explorer/polkadot-indexer) correct?

**Comment by ethernomad** [comment]
> Also I think the link in [Deliverable 2](https://github.com/hybrid-explorer/hybrid-indexer/blob/main/doc/testing-guide.md) in the testing guide also points to the wrong repo - it should point to the [Polkadot Indexer](https://github.com/hybrid-explorer/polkadot-indexer) correct?

```
## Deliverable 2 - Polkadot Indexer

1. Follow the [instructions](https://github.com/hybrid-explorer/polkadot-indexer/blob/main/README.md#docker) in polkadot-indexer to run a docker image in a separate console tab for each of polkadot, kusama, rococo & westend.
1. Observe that all 4 Polakdot chains are being indexed.
```

It points to polkadot-indexer, deliverable 3 points to hybrid-dapp.

**Comment by Ali-Usama** [comment]
> Thanks @Ali-Usama I'm assuming this means you're done making changes?

yes @keeganquigley I've made the updates to the evaluation yesterday

**Comment by keeganquigley** [comment]
Thanks @Ali-Usama see my comments on your eval. @ethernomad thanks much appreciated, your external eval has been accepted and I was also able to get all four networks to index and show up on the UI. 

hybrid

hybrid2

I was able to complete the manual testing list to see that all extrinsic searches work. Nice work! Happy to pass the milestone.

**Comment by keeganquigley** [comment]
@ethernomad yes I forwarded your invoice for payment yesterday. Please except up to 14 days for processing. Looking forward to seeing the follow-up.

**Comment by RouvenP** [comment]
hi @ethernomad we just transferred the payment and apologies for the delay!

**Comment by ethernomad** [comment]
> hi @ethernomad we just transferred the payment and apologies for the delay!

I already received it on August 24th:

https://etherscan.io/tx/0xbefa5b24324bcfc1c32741914ace361942c34c01779ea8e5c4970016df4c03e1

**Comment by fededubbi** [comment]
Hi @ethernomad,

Sorry that was our mistake.

Many thanks,
Federica

**Pull request merged**
