### PR TITLE
subsmt_milestone_1

### PR DESCRIPTION
**Pull request by YanOctavian**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/2335](https://github.com/w3f/Grants-Program/pull/2335)

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @YanOctavian. Thanks for the delivery, but the PR is currently editing our application template as well; could you undo those changes?

**Comment by YanOctavian** [comment]
> Hi @YanOctavian. Thanks for the delivery, but the PR is currently editing our application template as well; could you undo those changes?

@semuelle Thank you for your reminder. I will update it as soon as possible.

**Review by semuelle — CHANGES_REQUESTED** [review]
I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?

```sh
   Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
   Compiling alloc-stdlib v0.2.2
   Compiling num-bigint v0.4.6
   Compiling const-random v0.1.18
   Compiling scale-decode v0.11.1
error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
     |
75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
     |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
     |
     = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
note: required by a bound in `traits::Header`
    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
     |
1198 | pub trait Header:
     |           ------ required by a bound in this trait
1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
     |                           ^^^^^ required by this bound in `Header`
help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
     |
78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
   --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
    |
148 |         Hash::hash_of(self)
    |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
    |         |
    |         required by a bound introduced by this call
    |
note: required by a bound in `traits::Hash::hash_of`
   --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
    |
973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
    |                   ^^^^^^ required by this bound in `Hash::hash_of`
help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
    |
143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
    |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Compiling js-sys v0.3.74
   Compiling darling v0.20.10
For more information about this error, try `rustc --explain E0277`.
error: could not compile `sp-runtime` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by kevin-valerio** [comment]
> I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?
> 
> ```shell
>    Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
>    Compiling alloc-stdlib v0.2.2
>    Compiling num-bigint v0.4.6
>    Compiling const-random v0.1.18
>    Compiling scale-decode v0.11.1
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
>      |
> 75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
>      |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
>      |
>      = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
> note: required by a bound in `traits::Header`
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
>      |
> 1198 | pub trait Header:
>      |           ------ required by a bound in this trait
> 1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
>      |                           ^^^^^ required by this bound in `Header`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>      |
> 78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
>     |
> 148 |         Hash::hash_of(self)
>     |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
>     |         |
>     |         required by a bound introduced by this call
>     |
> note: required by a bound in `traits::Hash::hash_of`
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
>     |
> 973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
>     |                   ^^^^^^ required by this bound in `Hash::hash_of`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>     |
> 143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Compiling js-sys v0.3.74
>    Compiling darling v0.20.10
> For more information about this error, try `rustc --explain E0277`.
> error: could not compile `sp-runtime` (lib) due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> ```

Same issue for me.

**Comment by YanOctavian** [comment]
> I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?
> 
> ```shell
>    Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
>    Compiling alloc-stdlib v0.2.2
>    Compiling num-bigint v0.4.6
>    Compiling const-random v0.1.18
>    Compiling scale-decode v0.11.1
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
>      |
> 75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
>      |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
>      |
>      = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
> note: required by a bound in `traits::Header`
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
>      |
> 1198 | pub trait Header:
>      |           ------ required by a bound in this trait
> 1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
>      |                           ^^^^^ required by this bound in `Header`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>      |
> 78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
>     |
> 148 |         Hash::hash_of(self)
>     |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
>     |         |
>     |         required by a bound introduced by this call
>     |
> note: required by a bound in `traits::Hash::hash_of`
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
>     |
> 973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
>     |                   ^^^^^^ required by this bound in `Hash::hash_of`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>     |
> 143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Compiling js-sys v0.3.74
>    Compiling darling v0.20.10
> For more information about this error, try `rustc --explain E0277`.
> error: could not compile `sp-runtime` (lib) due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> ```

It seems that this issue was caused by some dependencies being updated, as I haven't encountered this problem locally.

**Comment by kevin-valerio** [comment]
> > I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?
> > ```shell
> >    Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
> >    Compiling alloc-stdlib v0.2.2
> >    Compiling num-bigint v0.4.6
> >    Compiling const-random v0.1.18
> >    Compiling scale-decode v0.11.1
> > error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
> >     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
> >      |
> > 75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
> >      |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
> >      |
> >      = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
> > note: required by a bound in `traits::Header`
> >     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
> >      |
> > 1198 | pub trait Header:
> >      |           ------ required by a bound in this trait
> > 1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
> >      |                           ^^^^^ required by this bound in `Header`
> > help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
> >      |
> > 78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
> >      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 
> > error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
> >    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
> >     |
> > 148 |         Hash::hash_of(self)
> >     |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
> >     |         |
> >     |         required by a bound introduced by this call
> >     |
> > note: required by a bound in `traits::Hash::hash_of`
> >    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
> >     |
> > 973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
> >     |                   ^^^^^^ required by this bound in `Hash::hash_of`
> > help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
> >     |
> > 143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
> >     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 
> >    Compiling js-sys v0.3.74
> >    Compiling darling v0.20.10
> > For more information about this error, try `rustc --explain E0277`.
> > error: could not compile `sp-runtime` (lib) due to 2 previous errors
> > warning: build failed, waiting for other jobs to finish...
> > ```
> 
> It seems that this issue was caused by some dependencies being updated, as I haven't encountered this problem locally.

Exactly, it was after I `cargo update`. I've just reverted to my previous `Cargo.lock` and it works now.

**Comment by YanOctavian** [comment]
> I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?
> 
> ```shell
>    Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
>    Compiling alloc-stdlib v0.2.2
>    Compiling num-bigint v0.4.6
>    Compiling const-random v0.1.18
>    Compiling scale-decode v0.11.1
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
>      |
> 75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
>      |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
>      |
>      = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
> note: required by a bound in `traits::Header`
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
>      |
> 1198 | pub trait Header:
>      |           ------ required by a bound in this trait
> 1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
>      |                           ^^^^^ required by this bound in `Header`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>      |
> 78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
>     |
> 148 |         Hash::hash_of(self)
>     |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
>     |         |
>     |         required by a bound introduced by this call
>     |
> note: required by a bound in `traits::Hash::hash_of`
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
>     |
> 973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
>     |                   ^^^^^^ required by this bound in `Hash::hash_of`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>     |
> 143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Compiling js-sys v0.3.74
>    Compiling darling v0.20.10
> For more information about this error, try `rustc --explain E0277`.
> error: could not compile `sp-runtime` (lib) due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> ```

@kevin-valerio @semuelle  Thank you very much for your feedback. After running `cargo update` locally, I was able to reproduce the issue. I will need a day to resolve this dependency error.

**Comment by YanOctavian** [comment]
It seems that there have been some major upgrades and updates to the Polkadot SDK recently.

**Comment by YanOctavian** [comment]
> I am trying to compile the project locally, but I run into issues. First, `cargo build` failed because the `members` folders are case sensitive (`SMT`, not `smt`). Then, it fails with the following error message. This also happens using `docker build` (`docker compose` works, though). Could you check?
> 
> ```shell
>    Compiling sp-runtime v31.0.1 (https://github.com/paritytech/polkadot-sdk?branch=release-polkadot-v1.14.0#778e9d15)
>    Compiling alloc-stdlib v0.2.2
>    Compiling num-bigint v0.4.6
>    Compiling const-random v0.1.18
>    Compiling scale-decode v0.11.1
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:75:39
>      |
> 75   | impl<Number, Hash> traits::Header for Header<Number, Hash>
>      |                                       ^^^^^^^^^^^^^^^^^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`, which is required by `generic::header::Header<Number, Hash>: Codec`
>      |
>      = note: required for `generic::header::Header<Number, Hash>` to implement `Codec`
> note: required by a bound in `traits::Header`
>     --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:1199:24
>      |
> 1198 | pub trait Header:
>      |           ------ required by a bound in this trait
> 1199 |     Clone + Send + Sync + Codec + Eq + MaybeSerialize + Debug + TypeInfo + 'static
>      |                           ^^^^^ required by this bound in `Header`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>      |
> 78   |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> error[E0277]: the trait bound `generic::header::Header<Number, Hash>: Encode` is not satisfied
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/generic/header.rs:148:17
>     |
> 148 |         Hash::hash_of(self)
>     |         ------------- ^^^^ the trait `Encode` is not implemented for `generic::header::Header<Number, Hash>`
>     |         |
>     |         required by a bound introduced by this call
>     |
> note: required by a bound in `traits::Hash::hash_of`
>    --> /home/x/.cargo/git/checkouts/polkadot-sdk-cff69157b985ed76/778e9d1/substrate/primitives/runtime/src/traits.rs:973:16
>     |
> 973 |     fn hash_of<S: Encode>(s: &S) -> Self::Output {
>     |                   ^^^^^^ required by this bound in `Hash::hash_of`
> help: consider extending the `where` clause, but there might be an alternative better way to express this requirement
>     |
> 143 |     Hash: HashT, generic::header::Header<Number, Hash>: Encode
>     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>    Compiling js-sys v0.3.74
>    Compiling darling v0.20.10
> For more information about this error, try `rustc --explain E0277`.
> error: could not compile `sp-runtime` (lib) due to 2 previous errors
> warning: build failed, waiting for other jobs to finish...
> ```

I switched the pokadot-sdk branch to `stable2409` and `cargo build` successfully. The code has been updated. Thank you for your feedback. Have a good day!

**Comment by YanOctavian** [comment]
> Thanks for the updates, @YanOctavian & @kevin-valerio. I am happy to report that everything is working now and your milestone is hereby accepted. Congrats! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subsmt_1_semuelle.md).

@semuelle Good job! Thank you very much. I have submitted the invioce.

**Comment by YanOctavian** [comment]
@semuelle @kevin-valerio Just wanted to know if the M1 payment could be processed before the 25th. If so, we would be very happy. Wishing you a wonderful holiday!

**Pull request merged**
