### PR TITLE
Distributed Cryptography for Polkadot Wallets (M2 and M3)

### PR DESCRIPTION
**Pull request by janbormet**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1908

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @janbormet I requested a review from @burdges again for this one in case he is available to give some insight. In the meantime, I'll take a look and do what I can to verify the deliverables.

**Comment by keeganquigley** [comment]
@burdges any chance you have a few moments to review the paper?

**Comment by keeganquigley** [comment]
Hi @janbormet thanks for your patience. I wasn't able to get an expert review but I was able to confirm your sources and references, and I was impressed by what I understood from the paper. Granted I am nowhere near an expert in this field, so I can't comment deeply on your findings. But I can tell that the work is articulate, well-organized, and perceptive. It appears to me to be skillfully written, with a coherent structure, and well-cited. 

Therefore I'm willing to go ahead and pass the milestones. Thanks for your thorough research, and have a happy holidays!

**Comment by RouvenP** [comment]
hi @janbormet we just sent the payment

**Pull request merged**
