### PR TITLE
Dotnix-milestone_1 delivery

### PR DESCRIPTION
**Pull request by Ra33it0**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2259

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the delivery, @Ra33it0, and thanks for the walking me through the tests. Everything is working (see evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotnix_1_semuelle.md)); I only have one request: we usually ask articles be published somewhere visible, such as Medium or a blog where it is easier to discover than in a Github repo. Also, it'd be great if you could add some details about yourself, why you are building this, and a mention of W3F. Check out our [announcement guidelines](https://grants.web3.foundation/docs/Support%20Docs/announcement-guidelines) for some more suggestions.

**Comment by Ra33it0** [comment]
Hey @semuelle I am happy to help. 
Thank you for your feedback, we have updated the blog article and published it on our website. 
https://dotnix.xyz/

**Review by semuelle — APPROVED** [review]
Thanks for the update, @Ra33it0. I am happy to report that your milestone is accepted. Nice work, really. See my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotnix_1_semuelle.md).

Best of luck going forward, hope to see you around.

**Comment by Ra33it0** [comment]
Thank you for your feedback, @semuelle .
We appreciate your evaluation and have already started working on Milestone 2.

**Pull request merged**
