### PR TITLE
Slothunter milestone 1

### PR DESCRIPTION
**Pull request by AurevoirXavier**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1531 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @AurevoirXavier, per this external [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/slothunter_1_ali-usama.md) your milestone has been accepted.

**Note:** For your next delivery, please include links in the delivery tables to help the evaluator easily find the different sections. Good luck and looking forward to seeing the next one!

**Comment by AurevoirXavier** [comment]
Hi! How is the payment process going?

**Comment by keeganquigley** [comment]
Hi @AurevoirXavier it typically takes up to 14 days to process, and it looks like I forwarded your invoice 13 days ago. If it doesn't show up tomorrow let me know and I will ping the operations team. Thanks!

**Comment by AurevoirXavier** [comment]
> Hi @AurevoirXavier it typically takes up to 14 days to process, and it looks like I forwarded your invoice 13 days ago. If it doesn't show up tomorrow let me know and I will ping the operations team. Thanks!

Unfortunately, I have not yet received the payment.

**Comment by keeganquigley** [comment]
Hi @AurevoirXavier the payment should go out tomorrow by end of day. Please let me know if this is not the case and sorry for the inconvenience!

**Comment by AurevoirXavier** [comment]
> Hi @AurevoirXavier the payment should go out tomorrow by end of day. Please let me know if this is not the case and sorry for the inconvenience!

Thanks for your help! Payment confirmed.

**Pull request merged**
