### PR TITLE
Candle Auction on Ink!: Milestone-2 delivered

### PR DESCRIPTION
**Pull request by agryaznov**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/666 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery! We'll check it as soon as we can :)

**Comment by semuelle** [comment]
Hey Alexander. Sorry for the late reply. We have a bit of a backlog.

I have looked at all your deliverables, and everything looks great. The only issue I have is that I am unable to deploy the contract locally. Whatever node I'm using, I get `PortableRegistry: 1: Error extracting {"path":[],"params":[],"def":{"composite":{"fields":[]}},"docs":[]}: n[0] is undefined` when trying to upload the contract. Any idea what's going on?

**Comment by agryaznov** [comment]
Hi Sebastian! I'm seeing this error for the first time. Could you please provide more info for me to try to reproduce it?:  
1. Are you getting this while deploying *candle_auction.contract* or *erc271.contract* as well?
2. How are you trying to deploy it - through PolkadotJS Apps?
3. Which build are you deploying - the one you've built yourself or the one which is attached to the [release](https://github.com/agryaznov/candle-auction-ink/releases/tag/v0.2.3)?

**Comment by semuelle** [comment]
1. both
2. yes
3. the one I built myself

I will try and deploy the one in the release, perhaps that changes anything. Which Rust toolchain and contracts-node versions do you use?

**Comment by agryaznov** [comment]
My env:
```bash
$ substrate-contracts-node --version
substrate-contracts-node 0.1.0-7d81166-x86_64-linux-gnu
$ cargo-contract --version
cargo-contract 0.16.0-unknown-x86_64-linux-gnu
$ rustc +nightly --version
rustc 1.59.0-nightly (532d2b14c 2021-12-03)
$ cargo +nightly --version 
cargo 1.58.0-nightly (294967c53 2021-11-29)
```

I have just re-checked, it builds and being deployed fine

**Comment by semuelle** [comment]
Okay, got it working. That took an unreasonable amount of time, but it looks like it was first an outdated `cargo-contract`, and _then_ some incompatibilities between the `cargo-contract` and `substrate-contracts-node`. 

Your milestone is hereby accepted. Great work overall. The only issue I could find was that, in the README, `getWinner` should be `getWinning`. Evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/candle-auction-ink_2_semuelle.md).

I will forward your invoice for processing. See you for Milestone 3. :)

**Comment by agryaznov** [comment]
> The only issue I could find was that, in the README, `getWinner` should be `getWinning`. 

Correct. Fixed this one. 

Thanks Sebastian!

**Comment by RouvenP** [comment]
hi @agryaznov we transferred the payment. Thanks!

**Pull request merged**
