### PR TITLE
Dart-SCALE-Codec milestone 1

### PR DESCRIPTION
**Pull request by alexxuyang**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for delivering the milestone, we will look into it as soon as possible.

**Comment by mmagician** [comment]
@alexxuyang I am not sure about the implementation details of your [boolean](https://github.com/nbltrust/dart-scale-codec/blob/master/test/compact_refl_tests.dart#L71)
It seems like you are assuming true = 1, false = 0 and encoding as if the following expressions were equal:
`expect(encode(Bool(true)), '0x04');` == `expect(encode(u32(1)), '0x04');`

As far as I understand it, booleans are a separate type within SCALE and as such should encode to a different value, rather than being interpreted as `u32`s. See [here](https://substrate.dev/docs/en/knowledgebase/advanced/codec#boolean) for reference. I might be missing something, please correct me if I'm wrong.

**Comment by cubeyo** [comment]
> @alexxuyang I am not sure about the implementation details of your [boolean](https://github.com/nbltrust/dart-scale-codec/blob/master/test/compact_refl_tests.dart#L71)
> It seems like you are assuming true = 1, false = 0 and encoding as if the following expressions were equal:
> `expect(encode(Bool(true)), '0x04');` == `expect(encode(u32(1)), '0x04');`
> 
> As far as I understand it, booleans are a separate type within SCALE and as such should encode to a different value, rather than being interpreted as `u32`s. See [here](https://substrate.dev/docs/en/knowledgebase/advanced/codec#boolean) for reference. I might be missing something, please correct me if I'm wrong.

Hello, @mmagician . The test file in your link is for compact types. In case Bool is wrapped by Compact, the least significant bytes are encoded as compact type, then Compact(Bool(true)) will be encoded as 0x04, same as Compact(u32(1))
Normal Bool value will only extract one byte from stream, you may refer to the definition [here](https://github.com/nbltrust/dart-scale-codec/blob/master/lib/src/base_types.dart#L335)
Btw, I have noticed there is a special case for Option<Bool> encoding, from the document your mentioned. I will fix that as soon as possible.

**Comment by mmagician** [comment]
@cubeyo That makes sense, thank you for clarifying. In this case, could you also add unit tests for non-compact Boolean types please?

**Comment by cubeyo** [comment]
> @cubeyo That makes sense, thank you for clarifying. In this case, could you also add unit tests for non-compact Boolean types please?

Yes, will deliver test cases for basic integer tests in next version 0.1.1, together with the fix to Optional\<Bool\>

**Comment by cubeyo** [comment]
> > @cubeyo That makes sense, thank you for clarifying. In this case, could you also add unit tests for non-compact Boolean types please?
> 
> Yes, will deliver test cases for basic integer tests in next version 0.1.1, together with the fix to Optional<Bool>

Has delivered version [0.1.1](https://pub.dev/packages/scalecodec/versions/0.1.1)

**Comment by mmagician** [comment]
@cubeyo Thanks for adding the relevant unit tests, they pass just fine.
However now I get the following error (x3):
```
Failed to load "test/generic_call_refl_test.dart": Cannot open file, path = 'metadata.bin' (OS Error: No such file or directory, errno = 2)
```
when I run `pub run test`. 

I have verified that this worked in the previous version (e.g. [this commit](https://github.com/nbltrust/dart-scale-codec/commit/22e062dfda1f0d49aab4e826d708bcf0949fc72e)).

**Comment by cubeyo** [comment]
> @cubeyo Thanks for adding the relevant unit tests, they pass just fine.
> However now I get the following error (x3):
> 
> ```
> Failed to load "test/generic_call_refl_test.dart": Cannot open file, path = 'metadata.bin' (OS Error: No such file or directory, errno = 2)
> ```
> 
> when I run `pub run test`.
> 
> I have verified that this worked in the previous version (e.g. [this commit](https://github.com/nbltrust/dart-scale-codec/commit/22e062dfda1f0d49aab4e826d708bcf0949fc72e)).

When decode/encode some calls/extrinsics, metadata need to be loaded, for encoders/decoders to find module index and function index.
In test cases, metadata need to be loaded from local file system, instead of from rpc call `state_getMetadata`.
There is a tool in ./tool/dump_metadata.dart, to generate metadata binary file from remote rpc call.
You may run it like this:
```dart
cd ./tool/
dart dump_metadata.dart // will generate a metadata.$current_timestamp.bin file
cd ../test
ln -s ../tool/metadata.$timestamp.bin ./metadata.bin
```
related test cases will work fine after that.

**Comment by mmagician** [comment]
Got it. Correct me if I'm wrong, but this is a step that is not immediately obvious. Could you, in your [README](https://github.com/nbltrust/dart-scale-codec/blob/master/README.md), include a subsection on executing the test suite please? Notice that a Testing Guide is part of your grant application and as such is considered a necessary condition for acceptance.

**Comment by cubeyo** [comment]
> Got it. Correct me if I'm wrong, but this is a step that is not immediately obvious. Could you, in your [README](https://github.com/nbltrust/dart-scale-codec/blob/master/README.md), include a subsection on executing the test suite please? Notice that a Testing Guide is part of your grant application and as such is considered a necessary condition for acceptance.

Hello @mmagician , has added a README file in test directory.

**Comment by mmagician** [comment]
Thanks, following the instructions worked. I have two follow up requests:

1) I also tried to run the examples that you provided. 
Using `pub run example/<example name>` I get all kinds of errors, e.g.
`pub run example/decode_extrinsics_demo`

```
NoSuchCapabilityError: no capability to invoke the constructor "fromBinary"
```

For `encode_extrinsics_demo` I get the same `metadata.bin` missing error as before. After resolving it, I encounter:
```
Exception: Invalid init type for integer
```

Similarly to testing README, could you please add instructions on how to run these examples?

2) I wanted to check the unit test coverage, so I followed the steps [here](https://pub.dev/packages/test_coverage). Perhaps you could try the same & help me resolve the errors? In any case I believe that including coverage metrics within your repo would be a valuable addition to the codebase.

**Comment by cubeyo** [comment]
> Thanks, following the instructions worked. I have two follow up requests:
> 
> 1. I also tried to run the examples that you provided.
>    Using `pub run example/<example name>` I get all kinds of errors, e.g.
>    `pub run example/decode_extrinsics_demo`
> 
> ```
> NoSuchCapabilityError: no capability to invoke the constructor "fromBinary"
> ```
> 
> For `encode_extrinsics_demo` I get the same `metadata.bin` missing error as before. After resolving it, I encounter:
> 
> ```
> Exception: Invalid init type for integer
> ```
> 
> Similarly to testing README, could you please add instructions on how to run these examples?
> 
> 1. I wanted to check the unit test coverage, so I followed the steps [here](https://pub.dev/packages/test_coverage). Perhaps you could try the same & help me resolve the errors? In any case I believe that including coverage metrics within your repo would be a valuable addition to the codebase.

Will deliver next version 0.1.2, in one or two days, with documents of examples and coverage test.

**Comment by cubeyo** [comment]
> Thanks, following the instructions worked. I have two follow up requests:
> 
> 1. I also tried to run the examples that you provided.
>    Using `pub run example/<example name>` I get all kinds of errors, e.g.
>    `pub run example/decode_extrinsics_demo`
> 
> ```
> NoSuchCapabilityError: no capability to invoke the constructor "fromBinary"
> ```
> 
> For `encode_extrinsics_demo` I get the same `metadata.bin` missing error as before. After resolving it, I encounter:
> 
> ```
> Exception: Invalid init type for integer
> ```
> 
> Similarly to testing README, could you please add instructions on how to run these examples?
> 
> 1. I wanted to check the unit test coverage, so I followed the steps [here](https://pub.dev/packages/test_coverage). Perhaps you could try the same & help me resolve the errors? In any case I believe that including coverage metrics within your repo would be a valuable addition to the codebase.

hello @mmagician , 0.1.2 has been delivered
for coverage test, please refer to test/README.md
for examples, I removed metadata.bin dependency and all demos can be run without any prerequisite of enviroment settings.

**Comment by mmagician** [comment]
@cubeyo Your milestone has been approved, see [the evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dart-scale-codec_1_mmagician.md) for more details. I will forward your invoice internally.

Thanks for the delivery!

**Comment by daCapricorn** [comment]
@Noc2 @mmagician We have still not received the payment. The invoice in [invoice form](https://forms.gle/8Wx7nxtq8fKrsuEz8) was out-of-date. A new invoice has been submitted.

**Comment by RouvenP** [comment]
hi @daCapricorn apologies for the delay. we just sent a test transaction. could you please confirm if received?

**Comment by daCapricorn** [comment]
Hi @RouvenP, 0.01 BTC received.

**Comment by RouvenP** [comment]
@daCapricorn thanks for confirming. We sent the payment.

**Comment by daCapricorn** [comment]
@RouvenP received. Thank you.

**Pull request merged**
