### PR TITLE
Milestone Delivery: Escrow pallet Milestone #1

### PR DESCRIPTION
**Pull request by herou**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1094

### CODE REVIEW

**Comment by herou** [comment]
Why Google Sheet check is failing?

**Comment by takahser** [comment]
@herou thanks for your delivery! We currently have a rather large backlog to tackle, so it might take a bit longer than usual until your delivery is evaluated. Nevertheless, we're going to take a look at it as soon as we can.

**Comment by keeganquigley** [comment]
Hi @herou I have started the process of evaluating your milestone. Please give me a bit of time to fully understand your project and I will reach out to you with any questions I may have. Thanks!

**Comment by keeganquigley** [comment]
@herou I looked over your milestone and am getting 404 errors on Deliverable #3. Docker and #6. Escrow Pallet. Can you fix these links? Thanks!

**Comment by herou** [comment]
> @herou I looked over your milestone and am getting 404 errors on Deliverable 4. Docker and 6. Escrow Pallet. Can you fix these links? Thanks!

It should be fine now. I made them public.

**Comment by herou** [comment]
> @herou I looked over your milestone and am getting 404 errors on Deliverable 4. Docker and 6. Escrow Pallet. Can you fix these links? Thanks!

It should be fine now. I made my repo public.

**Comment by keeganquigley** [comment]
Thanks @herou a couple more things to address: 

1. Can you provide a link to the license file? This will be needed for submission.
2. Is there a reason the license file is in the main branch and the rest of the pallet is in eljo-prifti/escrow?

**Comment by keeganquigley** [comment]
Thanks @herou however I was actually asking if you can update this on the milestone delivery itself. Right now it just says Apache 2.0 but doesn't link to it. Sorry for the confusion there. Can you update this?

**Comment by herou** [comment]
> Thanks @herou however I was actually asking if you can update this on the milestone delivery itself. Right now it just says Apache 2.0 but doesn't link to it. Sorry for the confusion there. Can you update this?

I added it to the milestone delivery doc.

**Comment by keeganquigley** [comment]
Thanks @herou moving on, your pallet code looks good and the unit tests are all successful. However, some of the benchmarking tests are failing when running `cargo test --features runtime-benchmarks`. Are you able to address these 2 errors?

```rust
  error[E0425]: cannot find function `assert_last_event` in this scope
    --> /Users/keeganquigley/EscrowPallet/pallets/escrow/src/benchmarking.rs:30:3
     |
  30 |      assert_last_event::<T>(Event::Locked(caller, amount).into());
     |      ^^^^^^^^^^^^^^^^^ not found in this scope

     Compiling frame-system-benchmarking v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.28#34a06217)
  error[E0599]: no function or associated item named `max_value` found for associated type `<<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance` in the current scope
    --> /Users/keeganquigley/EscrowPallet/pallets/escrow/src/benchmarking.rs:23:32
     |
  23 |         let amount = BalanceOf::<T>::max_value();
     |                                      ^^^^^^^^^ function or associated item not found in `<<T as pallet::Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance`
     |
     = help: items from traits can only be used if the trait is in scope
  help: the following traits are implemented but not in scope; perhaps add a `use` for one of them:
     |
  3  | use frame_support::sp_runtime::traits::Bounded;
     |
  3  | use num_traits::bounds::UpperBounded;
     |
  3  | use num_traits::float::FloatCore;
     |

  Some errors have detailed explanations: E0425, E0599.
  For more information about an error, try `rustc --explain E0425`.
  warning: `escrow` (lib) generated 2 warnings
  error: could not compile `escrow` due to 2 previous errors; 2 warnings emitted
  warning: build failed, waiting for other jobs to finish...
```

**Comment by herou** [comment]
> cargo test --features runtime-benchmarks

Sorry for this inconvenience, pushed my fix. Please take another look.

**Comment by alxs** [comment]
@herou we don't require milestones to be delivered sequentially, so feel free to create a PR for the second milestone already.

**Comment by keeganquigley** [comment]
@herou apologies for the delay and thanks for your patience during this process. I'm ready to submit my evaluation, which you can find [here](https://github.com/keeganquigley/Grant-Milestone-Delivery/blob/master/evaluations/escrow-pallet_1_keeganquigley.md). The only outstanding issue concerns the unit tests. Let me know if you are able to address these, and then I will submit the PR!

**Comment by herou** [comment]
> @herou apologies for the delay and thanks for your patience during this process. I'm ready to submit my evaluation, which you can find [here](https://github.com/keeganquigley/Grant-Milestone-Delivery/blob/master/evaluations/escrow-pallet_1_keeganquigley.md). The only outstanding issue concerns the unit tests. Please consider adding these for the next milestone.

Hi, thank you for your reply. **NoValueStored** and **WrongExpiringDate** are going to be used in the later milestones. If you see the sign_contract does not throw any of these errors, which means I can not write tests for them. SameAddressError error is used in the sign_contract, that's why I have written a test for it. Is it clear to you?

**Comment by keeganquigley** [comment]
@herou okay thanks for clarifying! Yes in that case I am happy to accept this milestone! I have submitted the PR and will let the rest of the team know.

**Comment by herou** [comment]
> @herou okay thanks for clarifying! Yes in that case I am happy to accept this milestone! I have submitted the PR and will let the rest of the team know.

My first milestone accepted :)

**Comment by herou** [comment]
> @herou could you upload a new invoice that includes your home address, please? Also, please make sure to include the W3F's address:
> 
> Web 3.0 Technologies Foundation Address: Baarerstrasse 14, 6300 Zug, Switzerland UID / VAT ID: CHE-322.596.347

Uploaded it, please let me know if it is okay. Thank you!

**Comment by takahser** [comment]
@herou thanks. I think, in your address the town and country are still missing though, can you add them and re-upload?

**Comment by herou** [comment]
> @herou thanks. I think, in your address the town and country are still missing though, can you add them and re-upload?

Can you please check it now and let me know? Thank you!

**Comment by keeganquigley** [comment]
@herou it looks good now, thanks!

**Comment by herou** [comment]
@keeganquigley I really liked your review and I would like to have a short conversation with you if possible. Can you please write me on twitter: @eljoprifti1 I would really appreciate it. Looking forward to hearing from you.  You rock it!

**Comment by keeganquigley** [comment]
@herou thanks for the compliments, and sure thing! I will DM you now.

**Comment by takahser** [comment]
@herou your address seems to be a [tron address](https://tronscan.org/#/address/TLQQGTvyCzhqCWp3w8pjVaEQU3uYWajRx1) which we [don't currently support](https://github.com/herou/Grants-Program#pencil-process) for payouts:

> Payment is made in Bitcoin, USDT, DAI or aUSD.

The amount in your [grant application](https://github.com/herou/Grants-Program/blob/af324cf01e0cfe707c262d86a0edaf81b53ca340/applications/escrow_pallet.md#development-roadmap) is denominated in USDT, which would work for us. Hence, could you please also update the wallet address?

**Comment by herou** [comment]
> @herou your address seems to be a [tron address](https://tronscan.org/#/address/TLQQGTvyCzhqCWp3w8pjVaEQU3uYWajRx1) which we [don't currently support](https://github.com/herou/Grants-Program#pencil-process) for payouts:
> 
> > Payment is made in Bitcoin, USDT, DAI or aUSD.
> 
> The amount in your [grant application](https://github.com/herou/Grants-Program/blob/af324cf01e0cfe707c262d86a0edaf81b53ca340/applications/escrow_pallet.md#development-roadmap) is denominated in USDT, which would work for us. Hence, could you please also update the wallet address?

Can you please check it again?

**Comment by keeganquigley** [comment]
thanks @herou we received the updated invoice but can you update it in the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/escrow_pallet.md) as well? Thanks!

**Comment by herou** [comment]
> thanks @herou we received the updated invoice but can you update it in the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/escrow_pallet.md) as well? Thanks!

It can not be done because the PR has been merged.

**Comment by keeganquigley** [comment]
@herou ah right, okay I will check with @takahser on how to proceed.

**Comment by keeganquigley** [comment]
@herou I checked with the team, and the contract will need to be amended. You can submit another PR for this. Thanks and apologies for the inconvenience.

**Comment by herou** [comment]
> @herou I checked with the team, and the contract will need to be amended. You can submit another PR for this. Thanks and apologies for the inconvenience.

This is a new PR of changing the address: https://github.com/w3f/Grants-Program/pull/1190

**Comment by herou** [comment]
> > @herou I checked with the team, and the contract will need to be amended. You can submit another PR for this. Thanks and apologies for the inconvenience.
> 
> This is a new PR of changing the address: [w3f/Grants-Program#1190](https://github.com/w3f/Grants-Program/pull/1190)

Hi @keeganquigley . Can you please let me know the status of the payment of this milestone?

**Pull request merged**
