### PR TITLE
ZeroDAO M1

### PR DESCRIPTION
**Pull request by DarkingLee**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/453

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Review by Noc2 — APPROVED** [review]
Thanks again for the delivery. I’m happy to tell you that the milestone is a pass and I have to say I’m really impressed by your work. Are you working on this alone so far? I think we would be more than happy to support this project with additional grants in the future and I will forward your invoice internally. I would also be happy to jump on a call with you (david@web3.foundation) and potentially discuss other options on how we can support your work (treasury, https://substrate.io/ecosystem/substrate-builders-program/, etc.). You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ZeroDAO_Network_1_Noc2.md). Also you might want to reach out to grantspr regarding announcements, see  https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md

**Comment by DarkingLee** [comment]
Awesome, really appreciate it.Thank you @Noc2 ! So far it is true that I have done this alone. After applying for W3f there were a few new members who joined but they were not able to get to work right away. Thank you again for your support. We will contact grantspr when the test network is online. Discussing the next support options with you sounds perfect!

**Comment by Noc2** [comment]
@DarkingLee The invoice team just informed me that we need your full address (including street, country etc.) Could you please upload a new invoice? And feel free to reach out via email, regarding scheduling a meeting.

**Comment by DarkingLee** [comment]
@Noc2 I'm sorry for the oversight.I have updated the a new invoice.

**Comment by Noc2** [comment]
Thanks. I just forwarded it internally.

**Comment by Noc2** [comment]
@DarkingLee Sorry to bother you again. But the invoice team just told me that invoice date is also missing. Could you please add this and send us another invoice? Thanks.

**Comment by DarkingLee** [comment]
Sorry, it was my mistake.I have updated a new invoice.Thanks.

**Comment by Noc2** [comment]
Thanks!

**Comment by RouvenP** [comment]
hi @DarkingLee we sent the payment today. Thanks!

**Comment by DarkingLee** [comment]
> 嗨@DarkingLee我们今天发送了付款。谢谢！

Received, thank you!

**Pull request merged**
