### PR TITLE
Orochi Network, Orosign part1, milestone 1

### PR DESCRIPTION
**Pull request by chiro-hiro**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1786

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@chiro-hiro thanks for your patience. I added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/5d961f50d93d1a80d7e13d65faacef2c4bb1b8af/evaluations/orochi_1_takahser.md). Let me know if you have any questions.

**Comment by takahser** [comment]
Btw, I also added a small PR [here](https://github.com/orochi-network/orochi-network.github.io/pull/44) to fix a link and some typos.

**Comment by semuelle** [comment]
pinging @chiro-hiro

**Comment by chiro-hiro** [comment]
Hi @semuelle and @takahser,

Our team is working on this problem and try to solve it before do comments.

Here is the WIP PR:
https://github.com/orochi-network/orochi-network.github.io/pull/45

**Comment by chiro-hiro** [comment]
Hi @takahser,

Our team had updated the proposal following your suggestion. All curves share something common cryptography primitives that why there are two main constructions [[Canneti et al 's Construction](http://localhost:3000/threshold-ecdsa/threshold-ecdsa-construction/introduction.html)](http://localhost:3000/threshold-ecdsa/threshold-ecdsa-construction/introduction.html) and  [[FROST's Construction](http://localhost:3000/threshold-ecdsa/frost-construction/introduction.html#frosts-construction)](http://localhost:3000/threshold-ecdsa/frost-construction/introduction.html).

**Review by takahser — APPROVED** [review]
@chiro-hiro thanks for the update. I took a look and I agree that FROST can be used to construct a MPC with ed25519 or sr25519 parameters, as you describe in your research. Hence, I'm accepting this. 👍 

You can find the final, accepted evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/orochi_1_takahser.md).

**Comment by fededubbi** [comment]
Hi @chiro-hiro,

Could you please add your complete address on the invoice and specify the currency in which you want to be paid in?

Many thanks,
Federica

**Comment by fededubbi** [comment]
Hi @chiro-hiro,

Could you please add also your complete address (street, number, post code, city and country)?

Many thanks,
Federica

**Comment by chiro-hiro** [comment]
Hi @fededubbi, should i add here or update the invoice?

**Comment by chiro-hiro** [comment]
Hi @fededubbi, I updated the invoice. The payment address in application is different from the address in the invoice due to this change in the template.

https://github.com/w3f/Grants-Program/commit/d60e2b5a94836f4c6ce3fe7449de086252c7d71e#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6bL17-R17

**Comment by RouvenP** [comment]
hi @chiro-hiro thanks for updating the invoice, looks good. We will process it within the next week.

**Comment by chiro-hiro** [comment]
Hi @RouvenP, sorry for bother you but we weren't received the grant.

**Comment by RouvenP** [comment]
hi @chiro-hiro apologies for the delay - the payment will go out tomorrow. I'll let you know as soon as processed

**Comment by RouvenP** [comment]
hi @chiro-hiro we just transferred the payment.

**Pull request merged**
