### PR TITLE
Libra milestone 3 delivery

### PR DESCRIPTION
**Pull request by psyduckio**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/776

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @psyduckio. We'll look into it as soon as possible.

**Comment by randombishop** [comment]
Hi @psyduckio,
Thank you for your delivery, I will be working on its evaluation.
Please bare with us as we currently have a backlog; but I will try to get back to you next week with feedback.

**Comment by psyduckio** [comment]
Hi @alxs @randombishop, 
Thanks for the response. Please take your time for the evaluation 🙏

**Comment by randombishop** [comment]
@psyduckio Sorry for the delay in processing this delivery.
Had to take some time to catch up with previous milestone, have both the substrate node and the javascript SDK up and running and understand what different components were doing; pretty impressive scope and quality work in my opinion.
The evaluation is under final checks and should be done shortly now.
Thanks again for your patience...

**Review by Noc2 — APPROVED** [review]

**Comment by randombishop** [comment]
@psyduckio Happy to inform you that your delivery was accepted.
Evaluation notes here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/libra_3_randombishop.md
I'll forward your invoice to the finance team, please allow for up to two weeks for processing.

**Comment by psyduckio** [comment]
@randombishop thank you for your evaluation and support 🙏

**Pull request merged**
