### PR TITLE
Hyperfridge Milestone 1

### PR DESCRIPTION
**Pull request by wstrametz**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2096

### CODE REVIEW

**Comment by wstrametz** [comment]
Hi - @takahser  - is there still something missing from our side? Its ready for review - we are alredy working on the next milestone and would be happy to do the review. Thx a lot, Walter

**Review by takahser — CHANGES_REQUESTED** [review]
@wstrametz thanks for your patience, I've finally completed this first evaluation iteration. You can find my evaluation report [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md). Basically, some parts of the code didn't pass and adding a few more inline comments might make sense. LMK if you have any questions.

**Comment by wasabrot** [comment]
> @wstrametz thanks for your patience, I've finally completed this first evaluation iteration. You can find my evaluation report [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md). Basically, some parts of the code didn't pass and adding a few more inline comments might make sense. LMK if you have any questions.

Hi @takahser - just a quick note, we are on it since a couple of days and looking into a solution with multi-platform docker images with Rust-Zero to have a good MacOs "experience",  but it takes a bit of time. Thanks a lot, walter

**Comment by takahser** [comment]
@wasabrot ok no problem, take your time. Thanks for the update!

**Comment by keeganquigley** [comment]
pinging @wstrametz for update :)

**Comment by wstrametz** [comment]
> pinging @wstrametz for update :)

yes - 100 % aware; just this morning I pinged Dastan to do final tests with the macos images - will merge likely until upcoming Monday

**Comment by wstrametz** [comment]
> > pinging @wstrametz for update :)
> 
> yes - 100 % aware; just this morning I pinged Dastan to do final tests with the macos images - will merge likely until upcoming Monday

Hi @keeganquigley - the macos Image works, but the local build on macos takes forever and consumes massive storge for building. Rootcause is the installation of risczero toolkit. They provide binary install via binstall just for linux; on  macos it triggers compilation automaically. Thats why we are having hard time getting the build into github actions, because this causes lot of runtime problems  - splitting the build in multiple stages does not help. Would you be OK just to test with the docker images on macos? Thx

**Comment by keeganquigley** [comment]
Thanks for the update @wstrametz I will let @takahser answer this since he is doing the evaluation.

**Comment by takahser** [comment]
@wstrametz thanks for the update, I'm planning to give you feedback early next week.

**Review by takahser — CHANGES_REQUESTED** [review]
@wstrametz I've accepted the Docker deliverables, see [my updated eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md). However, please clarify the testing deliverables, see my [previous comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1125#issuecomment-2023090633).

**Comment by wstrametz** [comment]
> @wstrametz I've accepted the Docker deliverables, see [my updated eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md). However, please clarify the testing deliverables, see my [previous comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1125#issuecomment-2023090633).

Hi @takahser - thx a lot for your review!

Is it "normal"? Yes, because we are using RISC0_DEV_MODE=true. This is a flag provided by the risc0 framework to do everything but the CPU intense computation when creating the Stark, and accepting a "fake" Stark when validating. On my Laptop (brand new lenovo legion 5) it takes 200 minutes to produce a real Stark. Its easy to switch on or off, so we left it off because we are at Milestone 1 and switching it on will not test or prove any work done on our side.  There is also a note in the README.md of the project about that.

But we experimented quite a lot with dev-mode off to learn about the runtime behaviour - details [here](https://github.com/element36-io/hyperfridge-r0/blob/main/docs/runtime.md). Apart from measurements, we we learned that you can not run it with normal gaming hardware acceleration on e.g. Geforce 4070 8GB due to lack of memory. Anyway, smaller samples showed a speed-up of around 80-100x on consumer hardware. Note that Risc0 provides an accelerated AWS machine as-a-service (risc0 bonsai) which most likely will offer more acceleration. 

To your next question - how do tests compare?

The docker images use pre-made test data, configs and commands, e.g. having RISC0_DEV_MODE turned on - pretty much all "hardcoded" so that is easy to spin up and do shakedown tests. Running it natively allows you to turn off the Dev-Mode and also to use  other risc0 features like hardware acceleration. The third tests are about changing test data and shows what actually happens when the data arrives at the backend which triggers the generation of a new proof. This part covers the preparation of the input data, where we off-load computation as much as possible. For example we decrypt payload outside of Stark generation and provide it as private input, because encrypting payload and comparing it with provided backend data (instead of just de-crypting) saved about 70 % computation time, because encrypting the payload with the session key is much cheaper then decrypting. 

Hope this answers your questions :)

Thx, Walter

**Comment by wstrametz** [comment]
Hi - @takahser - just pinging, was my comment above OK? Thx Walter

**Comment by takahser** [comment]
@wstrametz I'll get back to you on Monday.

**Review by takahser — CHANGES_REQUESTED** [review]
@wstrametz thx for your patience. I've updated my [eval again](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md). The only thing missing is the published crate.

**Comment by wstrametz** [comment]
Hello @takahser thx for feedback - Verifier crate is here: [cates.io](https://crates.io/crates/fridge-r0-verifier) now; this crate will be later used in the OCW to verify the JSON-STARK-Proof. Thanks for pointing this out, and hope that is OK, Walter

**Review by takahser — APPROVED** [review]
@wstrametz thanks, I've approved it. Final eval can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_1_takahser.md).

**Comment by RouvenP** [comment]
hi @wstrametz we sent the payment today

**Pull request merged**
