### PR TITLE
Webb Mixer milestone 1 delivery

### PR DESCRIPTION
**Pull request by drewstone**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by drewstone** [comment]
Blog post: https://www.notion.so/hicommonwealth/Blog-Post-9c7b84d8f030498389bd4dd19126cfa5

**Comment by alxs** [comment]
Hi @drewstone, thanks for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@drewstone Would you mind including a `types.json` in your repo or an explanation, to indicate the customTypes that are needed for interaction with your chain via the [polkadot-js/apps](https://polkadot.js.org/apps/) frontend?

Also the provided script `./scripts/build_benchmarks.sh` for building the node with benchmarks fails. If you can't reproduce that, please let me know and I'll provide the error msgs.

**Comment by drewstone** [comment]
The types can be found here: https://github.com/webb-tools/webb.js

we’ve done a lot more work since submission so likely best to test against latest work. I’ll remove this benchmark file as it isn’t used for us.

**Comment by mmagician** [comment]
@drewstone I've created a [draft evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/156) of your submission. I can't complain about the code itself, clearly your team has an abundance of Rust + substrate knowledge, although there are some cosmetic changes needed:
1. One licence is missing
2. Tutorial, documentation & appropriate instructions for setup and usage are missing. I find that there is no high-level overview of your project (and since it's not just the `anon` repo, it would be good to describe how it fits into your bigger vision and how it ties in with your other repos). Also, I understand that an end-to-end walkthrough might be tricky when relying purely on the pallets and not involving a dapp or your SDKs utils, but perhaps you could include a section that tries to describe how a user would go about interacting with your solution. 
In the end, one of the objectives of the Grants Program is to provide the users of the Polkadot ecosystem with open source tools to build with. This could be greatly facilitated by supplying user-oriented documentation. (I am also aware that there are different types of users, and perhaps for your work we're concerned more with \<User as Developer\> rather than \<User as EndUser\> )

Thanks for the work put into this so far! Let me know once you've addressed the above issues and I'll be happy to proceed with accepting this milestone.

**Comment by drewstone** [comment]
Hi @mmagician, documentation can be found here.
- https://docs.rs/pallet-mixer/3.0.0/pallet_mixer/
- https://docs.rs/pallet-merkle/3.0.0/pallet_merkle/

**Comment by drewstone** [comment]
Also since the grant was for runtime pallet work, I will add descriptions to the readme for this specifically and list some of the dependencies as you've mentioned are worthwhile. 

I had originally proposed a larger grant and we have done much of that work too, but since it was not funded through this grant I will not be included instructions for integrating with our dApp as that is outside the scope and unfair to hold us to that standard. This grant was for runtime pallets explicitly.

**Comment by mmagician** [comment]
Sounds reasonable. Let me know once you're happy with the README then

**Comment by drewstone** [comment]
Updated the readme :)!

**Comment by mmagician** [comment]
You're still missing a licence https://github.com/webb-tools/bulletproof-gadgets/

**Comment by drewstone** [comment]
Sorry about that, adding now!

**Comment by mmagician** [comment]
Congratulations on successfully completing the grant! You'll find the full evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/webb_mixer_1_mmagician.md)

**Comment by RouvenP** [comment]
hi @drewstone invoice received. we don't hold USDC - are you fine with DAI?

**Comment by drewstone** [comment]
Is there no way you can swap and send USDC?

**Comment by RouvenP** [comment]
we only do DAI and BTC ([see 1st paragraph here](https://github.com/w3f/Open-Grants-Program/blob/master/README.md). The Open Grants Program is limited to these two options to keep our operational efforts to a minimum.

**Comment by drewstone** [comment]
Ok DAI works for me.

**Comment by RouvenP** [comment]
great, thanks. the transfer is done: https://etherscan.io/tx/0x2cfe19be0bdf5a09dfcbec4a9bc52d6eb61a6d951bae66898928acb5eef037e9

**Pull request merged**
