### PR TITLE
add polkashots deliverable

### PR DESCRIPTION
**Pull request by nicolasochem**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [X] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [link is broken] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @nicolasochem,
I am testing your deployment instructions, and are stuck with the following error message when running `terraform apply plan.out`. 
Any idea what's missing?

```
error: unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
```

I also noticed that `firebase` is missing from the prerequisites, as well as any mention of the `terraform-gke-blockchain` dependency (at `../../`).

**Comment by nicolasochem** [comment]
@semuelle 

> error: unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

Kubernetes has custom resources definitions (CRDs), in that case it takes a while to propagate. You should simply retry and it will work. Let me edit the README to mention that.

> I also noticed that firebase is missing from the prerequisites, as well as any mention of the terraform-gke-blockchain dependency (at ../../).

That's a mistake on my end. It should be pulling the dependency from github instead of `../..`, let me fix.

**Comment by nicolasochem** [comment]
All done. The README already mentioned that you should expect to plan and apply several times for it to converge.

https://github.com/midl-dev/polkadot-snapshot-generator/commit/3f3fedfa607bdea848eadd913ce1aa7f149a3da7

(note you need to run `terraform init` again because the module source will change)

Please let me know if you have further issues.

**Comment by semuelle** [comment]
thanks for the swift reply. Is there anything I need to do between runs of `terraform apply`? I keep getting these errors. 

```
Error: Error creating Address: googleapi: Error 409: The resource 'projects/sturdy-yen-300923/regions/us-central1/addresses/blockchain-nat-external-1' already exists, alreadyExists

Error: Error creating service account: googleapi: Error 409: Service account blockchain-server already exists within project projects/sturdy-yen-300923., alreadyExists

Error: Error creating Address: googleapi: Error 409: The resource 'projects/sturdy-yen-300923/regions/us-central1/addresses/blockchain-nat-external-0' already exists, alreadyExists

Error: Error creating Network: googleapi: Error 409: The resource 'projects/sturdy-yen-300923/global/networks/blockchain-network' already exists, alreadyExists
```

**Comment by semuelle** [comment]
Tried all your suggestions twice. Same result. Here is a longer log.

```
null_resource.apply (local-exec): + cat
null_resource.apply (local-exec): + kubectl apply -k .
null_resource.apply (local-exec): storageclass.storage.k8s.io/dot-snapshottable-ssd created
null_resource.apply (local-exec): serviceaccount/dot-snapshot-engine created
null_resource.apply (local-exec): configmap/dot-polkadot-configmap-ht2m5t8t9d created
null_resource.apply (local-exec): configmap/dot-polkadot-snapshot-engine-configmap-ccb2t5gmdd created
null_resource.apply: Still creating... [10s elapsed]
null_resource.apply (local-exec): service/dot-private-node created
null_resource.apply (local-exec): deployment.apps/dot-private-node created
null_resource.apply (local-exec): cronjob.batch/dot-polkadot-snapshot-engine created
null_resource.apply (local-exec): networkpolicy.networking.k8s.io/dot-polkadot-private-node-policy created
null_resource.apply (local-exec): volumesnapshotclass.snapshot.storage.k8s.io/dot-ssd-snapshot-class created
null_resource.apply (local-exec): persistentvolumeclaim/dot-polkadot-private-node-claim created
null_resource.apply (local-exec): error: unable to recognize ".": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"


Error: Error running command 'set -e
```

**Comment by nicolasochem** [comment]
I have removed the ServiceMonitor from the code since it is not consumed by anything at the moment.

https://github.com/midl-dev/polkadot-snapshot-generator/commit/e7f0eaae87d36b4b96fe5b84af4917d9747b9a68

I am making a note that this CRD install appears to be not working properly, and I will address it for next release of terraform-gke-blockchain (which is some codebase that is shared with other projects). The commit above however should enable you to have a successful install of the polkadot node and snapshot engine.

**Comment by semuelle** [comment]
Hi @nicolasochem,
thanks for the quick fix. The milestone looks good (see evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkashots.io_1_semuelle.md). I am, however, missing this bit from your proposal: 

> we will be providing a script to parse terraform, dockerfile and kubernetes codebase and check for consistency

The script you have provided runs `terraform validate`, other features are missing.

**Comment by nicolasochem** [comment]
@semuelle thank you. I will add the missing linting code.

**Comment by nicolasochem** [comment]
@semuelle it is now resolved, please see comments and instructions in the commit msg:

https://github.com/midl-dev/polkadot-snapshot-generator/commit/571fc05601ba1958f5525236a7b3617340ad6a94

**Comment by semuelle** [comment]
Thanks for following up on that. I updated my evaluation notes and your milestone is now accepted. :tada: 

Your invoice will be forwarded for processing.

**Comment by RouvenP** [comment]
hi @nicolasochem we just sent a test transaction. Could you please confirm if received?

**Comment by nicolasochem** [comment]
Hi Rouven, yes, I received it.

**Comment by RouvenP** [comment]
@nicolasochem thanks for confirming. we sent the payment

**Comment by nicolasochem** [comment]
@RouvenP thank you. We received it.

**Pull request merged**
