### PR TITLE
QRUCIAL DAO - Milestone 1

### PR DESCRIPTION
**Pull request by sixTheDave**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/989](https://github.com/w3f/Grants-Program/pull/989)

### CODE REVIEW

**Comment by Noc2** [comment]
That’s great to hear. Thanks for the delivery and sorry for the delay. Part of our team is currently ooo. An external evaluator will take a look at your delivery in the coming days.

**Comment by smilingSix** [comment]
> That’s great to hear. Thanks for the delivery and sorry for the delay. Part of our team is currently ooo. An external evaluator will take a look at your delivery in the coming days.

No worries, we are patiently waiting for the evaluation. Please note that we started a new branch Milestone2 where we continue working on the project.

**Comment by dsm-w3f** [comment]
@smilingSix thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/qrucialdao_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by smilingSix** [comment]
> @smilingSix thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/qrucialdao_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

No worries and thank you for starting the process. We review the document and provide the answers/fixes soon.

**Comment by smilingSix** [comment]
Hello @dsm-w3f ,

Here are some updates. We will still make some changes to fit all evaluation feedback evaluation points if those below are not enough, but please note that we are working on a very low budget here (20k) on widespread changes requested.

**Improvements so far:**

0c. - More testing and exploratory documents are added.

0d. - We have improved the docker image and added more documentation on how to run/use it. Installation of "tmux" and "keccak256-cli" are included in the guide as well.

Warnings are fixed: clippy and compile time.

Exo_pallet methods were there from the template, these are removed. Other improvements are added.

Audit_pallet methods are implemented and errors are solved.

Exosysd improvements are planned for M2 as it is a phase for code cleanup/hardening.

Comments are improved in the code for rustdoc (exo_pallet and exosys to be added later). We also created a related wiki page for that.

**Substrate has been updated fully** to the latest runtime - also to fix some errors.

**Comment by dsm-w3f** [comment]
@smilingSix thank you for the improvements. I still have some problems with docker and now the tests are broken. I also need a complete example of running the process using the extrinsic and methods available. Regarding the low budget, these requests are really necessary to check your milestone deliverables and I think they will not take much time/effort to be done. No problem to plan improvements to M2, however, I need to check if the deliverables of M1 are working as declared in the grant proposal.

**Comment by smilingSix** [comment]
> @smilingSix thank you for the improvements. I still have some problems with docker and now the tests are broken. I also need a complete example of running the process using the extrinsic and methods available. The evaluation document was updated with details. Regarding the low budget, these requests are really necessary to check your milestone deliverables and I think they will not take much time/effort to be done. No problem to plan improvements to M2, however, I need to check if the deliverables of M1 are working as declared in the grant proposal.

Sure thing, thank you for the fast response. We check the evaluation updates and move forward. I'll drop the next message when we are ready.

**Comment by dsm-w3f** [comment]
@sixTheDave thank you for the improvements and fixes. Now the tests are passing but I still having problems with docker. The tutorial is covering a few features from what we have in this delivery. I updated [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/qrucialdao_1_dsm-w3f.md) with details. Please take a look and let me know when I could continue with the evaluation.

**Comment by sixTheDave** [comment]
> @sixTheDave thank you for the improvements and fixes. Now the tests are passing but I still having problems with docker. The tutorial is covering a few features from what we have in this delivery. I updated [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/qrucialdao_1_dsm-w3f.md) with details. Please take a look and let me know when I could continue with the evaluation.

Thank you, the problem with docker was that "git checkout milestone1" was not used before the docker build code. I have added this line to the tutorial.

A more detailed tutorial for the listed functions is on the way.

**Comment by sixTheDave** [comment]
@Noc2 @dsm-w3f We have updated the documentation with more tutorials.

To speed up the process we'd appriciate if you join in our public dev Matrix room: [https://matrix.to/#/#qdao_dev_pub:matrix.org](https://matrix.to/#/#qdao_dev_pub:matrix.org)

Sending messages here take a long time and we would be very happy to support the evaluation process with immediate answers.

Looking forward to the next step!

**Comment by dsm-w3f** [comment]
@sixTheDave thank you for the explanations. The milestone was approved. There are some improvements that need to be handled in the next delivery, see details in the evaluation document. I'll forward internally your invoice and it should be payed within two weeks (could happen before). Good Job!

**Comment by fededubbi** [comment]
Hi @sixTheDave,

I noticed on your invoice there is no payment address, could you please include it?
Do you want to be paid in USD or crypto?

Many thanks,
Federica

**Comment by sixTheDave** [comment]
> Hi @sixTheDave,
> 
> I noticed on your invoice there is no payment address, could you please include it? Do you want to be paid in USD or crypto?
> 
> Many thanks, Federica

Hi @fededubbi ,

Originally we though to ask for BTC, but if it possible to get USD, it is our preference. I have created a USD account for that.

Should we fill this form again: https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform ?

Thank you,
six

**Comment by sixTheDave** [comment]
> @sixTheDave thank you for the explanations. The milestone was approved. There are some improvements that need to be handled in the next delivery, see details in the evaluation document. I'll forward internally your invoice and it should be payed within two weeks (could happen before). Good Job!

Thank you @dsm-w3f , it was good to go though M1 evaluation with you. We get the improvements/hardening/frontend done in M2.

**Comment by fededubbi** [comment]
Hi @sixTheDave, i noticed on the invoice there are 2 different accounts.
Which one should we use?

Many thanks,
Federica

**Comment by sixTheDave** [comment]
> Hi @sixTheDave, i noticed on the invoice there are 2 different accounts. Which one should we use?
> 
> Many thanks, Federica

Hi @fededubbi ,

Please use the USD account: https://wise.com/pay#piq3oJkPjsX90gLJIiLXJDP-Sg0

Thank you,
six

**Comment by fededubbi** [comment]
Hi @sixTheDave,

According to your contract you should be paid in BTC.
Could you please include the address on the invoice and resend it?

Let me know if this still works for you or if you prefer another cryptocurrency.

Many thanks,
Federica

**Comment by sixTheDave** [comment]
> Hi @sixTheDave,
> 
> According to your contract you should be paid in BTC. Could you please include the address on the invoice and resend it?
> 
> Let me know if this still works for you or if you prefer another cryptocurrency.
> 
> Many thanks, Federica

Hi @fededubbi 

I updated and sent the invoice. This is the newly generated, correct BTC address: bc1qwr7awq55z2udjvxj0ar7qfeasf70fasee8fxf2

The old address is not valid anymore. Thank you.
six

**Comment by fededubbi** [comment]
Hi,

We check with our team and the BTC address on the invoice is not the same on the contract.
Could you please double check and replace it?

Many thanks,
Federica Dubbini

**Comment by sixTheDave** [comment]
> Hi,
> 
> We check with our team and the BTC address on the invoice is not the same on the contract. Could you please double check and replace it?
> 
> Many thanks, Federica Dubbini

Hi,

As I wrote above, the old address is not valid anymore, it has been replaced for security reasons. Please use the BTC address on the invoice. Please also match against the address for verification: bc1qwr7awq55z2udjvxj0ar7qfeasf70fasee8fxf2

Waiting for the transaction. Thank you,
six

**Comment by Noc2** [comment]
@sixTheDave, in this case, could you update the original application via a PR and integrate the new address: https://github.com/w3f/Grants-Program/blob/master/applications/QRUCIAL_DAO.md This way, we follow the normal process. Thanks a lot

**Comment by sixTheDave** [comment]
> @sixTheDave, in this case, could you update the original application via a PR and integrate the new address: https://github.com/w3f/Grants-Program/blob/master/applications/QRUCIAL_DAO.md This way, we follow the normal process. Thanks a lot

Sure thing. I just sent the PR.

**Comment by keeganquigley** [comment]
Thanks @sixTheDave I just approved the amendment, and it shouldn't take long to get the last two approvals in order to transfer the payment.

**Comment by sixTheDave** [comment]
> Hi,
> 
> We check with our team and the BTC address on the invoice is not the same on the contract. Could you please double check and replace it?
> 
> Many thanks, Federica Dubbini

Hello,

The PR just went through, please proceed with the payment.

Best,
six

**Comment by sixTheDave** [comment]
Hello @fededubbi ,

Can you please update us on the process? We are waiting for receiving the BTC.

**Comment by RouvenP** [comment]
hi @sixTheDave apologies for the delay - we transferred the payment yesterday.

**Comment by sixTheDave** [comment]
> hi @sixTheDave apologies for the delay - we transferred the payment yesterday.

Thank you, we have received it. We are starting Milestone 2.

**Pull request merged**
