### PR TITLE
Create ParaSpell Followup M2 & M3

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1245 
Link to delivery of milestone 1: https://github.com/w3f/Grant-Milestone-Delivery/pull/670

### CODE REVIEW

**Comment by dudo50** [comment]
We were able to finish the third milestone as well. Added it for review also :).
With kind regards,
ParaSpell team

**Comment by 0xCaso** [comment]
Hi @dudo50, thanks for the deliveries! Someone will look into them shortly.

**Comment by dsm-w3f** [comment]
@dudo50 thank you for the milestone submission. Please see the evaluation documents for milestones [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_2_dsm-w3f.md) and [3](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by dudo50** [comment]
Thank you @dsm-w3f . We will look into this shortly.

**Comment by dudo50** [comment]
@dsm-w3f  We tried to address the issues you pointed out and so here are explanations:
We have added a usage/testing guide for both UI tools to our documentation.
Links: [uiv1-transfer](https://paraspell.github.io/docs/ui/transfer.html), [uiv1-channnels](https://paraspell.github.io/docs/ui/channels.html), [uiv2-transfer](https://paraspell.github.io/docs/ui2/transfer2.html), [uiv2-channels](https://paraspell.github.io/docs/ui2/channels2.html). Commit [link](https://github.com/paraspell/docs/commit/e069d7f3c4842306e793a1203e49a701e3a7cc0b)

As for automatized testing of UI tools, we have not specified this in our milestones and we do not think it is necessary because these tools are not in production, they are meant for testing purpose for developers and people that want to learn more about XCM.

We have also addressed issue with docker in UI-V2 in following commit: [link](https://github.com/paraspell/ui-v2/commit/ddcee3d0f90b9fdbb885f4d2cc07e6cc2f492367)

As for implementation tests, the builder pattern is implemented directly into both UI tools so they serve as test tools for it. See this line for example: [link](https://github.com/paraspell/ui-v1/blob/main/src/views/ParaToRelay.vue#:~:text=w%20injected%20wallet-,let%20promise%20%3D%20Builder(api).from(%22Karura%22).currency(this.currency).currencyId(0).amount(this.amount).address(this.addr).build(),-promise.signAndSend), we have also put commit where we added them into UI in Milestone delivery. They are also covered with unit tests.

The XCM Pallet feature is indeed not covered yet and we will add unit tests for it as well as provide small script which will execute one example for you (This is TBA soon (max 1-2days), We provided the rest of the stuff for you so you can perhaps finish the evaluation of M3 while we bring XCM Pallet feature from M2 asap). 

With kind regards,
team ParaSpell

**Comment by dsm-w3f** [comment]
@dudo50 thank you for the prompt response. There are some operations in which the application shows a success msg but the events are not presented in the blockchain. Could you assist with that? See details in the evaluation documents for milestones [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_2_dsm-w3f.md) and [3](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_3_dsm-w3f.md).

**Comment by dudo50** [comment]
@dsm-w3f , this is because you do not have an asset you wish to transfer on that chain, make sure to transfer KSM from the Relay chain to Karura first (and a sufficient amount). Then your transfer will show in events. This is a bug that is in polkadot library or in parachain, not in our application (because the extrinsic we receive is about block finalization). Hope this solves your problem.
If you have any more questions feel free to ask.
With kind regards,
Dudo

**Comment by dsm-w3f** [comment]
@dudo50 thank you for the explanation. Now the transactions worked well. I update the evaluation for milestones [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_2_dsm-w3f.md) and [3](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_3_dsm-w3f.md) and the milestones are approved. Please consider doing the suggestions that I posted in the evaluation document. I'll forward your invoice internally and the payment should take place within two weeks. Great work!

**Comment by dudo50** [comment]
@dsm-w3f , thank you for the prompt evaluation. Your suggestions are valid, and we will certainly look into them. 
With kind regards,
team ParaSpell

**Pull request merged**
