### PR TITLE
Polkadart Milestone 1

### PR DESCRIPTION
**Pull request by Lohann**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1053

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @Lohann. We'll look into it as soon as possible.

**Comment by alxs** [comment]
Hey again @Lohann, I'm your evaluator for this milestone. Thanks for the effort that went into this delivery, it looks great so far. A few comments from my side:
- `docker compose up` to run the tests did not work for me:
  ```
  [+] Building 69.4s (17/17) FINISHED
   => [internal] load build definition from Dockerfile                                                                0.0s
   => => transferring dockerfile: 527B                                                                                0.0s
   => [internal] load .dockerignore                                                                                   0.0s
   => => transferring context: 2B                                                                                     0.0s
   => [internal] load metadata for docker.io/library/ubuntu:22.04                                                     1.1s
   => [internal] load build context                                                                                   0.0s
   => => transferring context: 2.71MB                                                                                 0.0s
   => [ 1/12] FROM docker.io/library/ubuntu:22.04@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4  1.7s
   => => resolve docker.io/library/ubuntu:22.04@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca400  0.0s
   => => sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47caebca4005c2 1.42kB / 1.42kB                      0.0s
   => => sha256:817cfe4672284dcbfee885b1a66094fd907630d610cab329114d036716be49ba 529B / 529B                          0.0s
   => => sha256:a8780b506fa4eeb1d0779a3c92c8d5d3e6a656c758135f62826768da458b5235 1.46kB / 1.46kB                      0.0s
   => => sha256:e96e057aae67380a4ddb16c337c5c3669d97fdff69ec537f02aa2cc30d814281 30.43MB / 30.43MB                    0.6s
   => => extracting sha256:e96e057aae67380a4ddb16c337c5c3669d97fdff69ec537f02aa2cc30d814281                           1.0s
   => [ 2/12] RUN apt-get update                                                                                      3.1s
   => [ 3/12] RUN apt-get install -y curl git wget unzip libglu1-mesa                                                 4.1s
   => [ 4/12] RUN apt-get clean                                                                                       0.2s
   => [ 5/12] RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter                                11.8s
   => [ 6/12] RUN flutter doctor                                                                                     23.9s
   => [ 7/12] RUN flutter channel stable                                                                              1.5s
   => [ 8/12] RUN flutter upgrade                                                                                    18.6s
   => [ 9/12] RUN mkdir /app/                                                                                         0.4s
   => [10/12] COPY .. /app/                                                                                           0.0s
   => [11/12] WORKDIR /app/                                                                                           0.0s
   => [12/12] RUN ["chmod", "+x", "/app/docker/run_tests.sh"]                                                         0.2s
   => exporting to image                                                                                              2.9s
   => => exporting layers                                                                                             2.9s
   => => writing image sha256:0d09e4c38d1c08d536dd59be4ec4b87ce8e6da924ef6fbebbd75fc12f9e93354                        0.0s
   => => naming to docker.io/library/polkadart-tests                                                                  0.0s
  [+] Running 2/0
   ⠿ Network polkadart_default    Created                                                                             0.0s
   ⠿ Container polkadart-tests-1  Created                                                                             0.0s
  Attaching to polkadart-tests-1
  polkadart-tests-1  | /usr/bin/env: 'sh\r': No such file or directory
  polkadart-tests-1 exited with code 127
  ```
- Could you add some documentation to the README, such as a brief intro to the project or just link to where the documentation can be found?
- Could you provide a test suite for the metadata parser and encoding/decoding metadata? I could only find [this test](https://github.com/rankanizer/polkadart/blob/main/packages/substrate_metadata/test/metadata/metadata_decoder_test.dart) that checks the decoder doesn't throw an exception in one case.

**Comment by leonardocustodio** [comment]
Hello @alxs, I made a change, can you give another go? If it doesn't work again can you please share with me the current environment that you are running? linux distro? windows? osx?

**Comment by alxs** [comment]
Hey @leonardocustodio, of course. It didn't work again, this is a VPS running Ubuntu 20.04.

```
[+] Running 1/0
 ⠿ Container polkadart-tests-1  Created                                                                             0.0s
Attaching to polkadart-tests-1
polkadart-tests-1  | /usr/bin/env: 'sh\r': No such file or directory
polkadart-tests-1 exited with code 127
```

**Comment by leonardocustodio** [comment]
Odd, I've removed the `/usr/bin/env` mention in the last PR could it be trying to run the cached image? After getting the latest commit on master could you try `docker compose build --no-cache && docker compose up`?

**Comment by alxs** [comment]
Sure! I don't get exactly the same error, but a very similar one:

```
docker compose build --no-cache && docker compose up

[+] Building 72.6s (17/17) FINISHED
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 32B                                                                                 0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                                     0.7s
 => CACHED [ 1/12] FROM docker.io/library/ubuntu:22.04@sha256:4b1d0c4a2d2aaf63b37111f34eb9fa89fa1bf53dd6e4ca954d47  0.0s
 => [internal] load build context                                                                                   0.0s
 => => transferring context: 67.01kB                                                                                0.0s
 => [ 2/12] RUN apt-get update                                                                                      3.0s
 => [ 3/12] RUN apt-get install -y curl git wget unzip libglu1-mesa                                                 3.6s
 => [ 4/12] RUN apt-get clean                                                                                       0.3s
 => [ 5/12] RUN git clone https://github.com/flutter/flutter.git /usr/local/flutter                                16.5s
 => [ 6/12] RUN flutter doctor                                                                                     25.6s
 => [ 7/12] RUN flutter channel stable                                                                              1.5s
 => [ 8/12] RUN flutter upgrade                                                                                    18.0s
 => [ 9/12] RUN mkdir /app/                                                                                         0.2s
 => [10/12] COPY .. /app/                                                                                           0.0s
 => [11/12] WORKDIR /app/                                                                                           0.0s
 => [12/12] RUN ["chmod", "+x", "/app/docker/run_tests.sh"]                                                         0.2s
 => exporting to image                                                                                              2.9s
 => => exporting layers                                                                                             2.9s
 => => writing image sha256:51184ef5860bd1fae46ee153bdec65554f12dc2c41e19f619e7c179f8bad6529                        0.0s
 => => naming to docker.io/library/polkadart-tests                                                                  0.0s
[+] Running 1/0
 ⠿ Container polkadart-tests-1  Recreated                                                                           0.0s
Attaching to polkadart-tests-1
polkadart-tests-1  | exec /app/docker/run_tests.sh: no such file or directory
polkadart-tests-1 exited with code 1
```

**Comment by leonardocustodio** [comment]
This one provides a bit more information because of the path. I believe I now know what is happening. Neither of our team had this issue, even though Docker is supposed to run almost equally across everybody sometimes we do see differences. I will go for another fix and let you know when it is done, thank you very much

**Comment by leonardocustodio** [comment]
Hey @alxs, can we try one more time? I was also wondering if this could be a CRLF issue. But you and I are both using Ubuntu so it shouldn't be that. If you can clone it again, the latest commit and make a fresh build with no cache. Thank you very much :)

**Comment by alxs** [comment]
That did the trick! No worries at all. Let me know when I should take another look at the delivery.

**Comment by Lohann** [comment]
@alxs ready for a second look 👀

**Comment by alxs** [comment]
@Lohann many thanks for the additional work and also for adding support for pre-v14 metadata, which wasn't even in the scope of this milestone!

After reviewing the code and your latest commits, it appears that you've implemented the encoding/decoding of some of the metadata contents as you list them [here](https://github.com/rankanizer/polkadart/tree/main#substrate-metadata-1), but not of all of them. To my understanding these will be necessary to construct transactions, but there's nothing else in your milestone plan between here and milestones 2 (networking) and 3 (cryptography). Am I missing something?

Otherwise, could you ensure that this is fully implemented before moving on to the next milestone? You can always [amend](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) the milestone plan if you want to redistribute the work or adjust the budget.

**Comment by Lohann** [comment]
Hi @alxs I think there's a confusion about what `metadata` means, once it have two meanings depending of the context, one is [frame-metadata](https://github.com/paritytech/frame-metadata), which is the format on how frame represents it's internal types, what we did in the milestone 1 is parse all types from this file:
``` bash
curl -H "Content-Type: application/json" -d '{"id":1,"jsonrpc":"2.0","method":"state_getMetadata","params":[]}' https://rpc.polkadot.io
``` 

The metadata described [here](https://github.com/rankanizer/polkadart/tree/main#substrate-metadata-1) is another thing, it is the API in Dart that allows the user to interact with the node, which includes read/mutate the chain state, similar to what polkadot-api does here:
https://polkadot.js.org/docs/substrate

Notice that both are called `metadata` but are different things, is not possible to implement `JSON-RPC`,  `Constants`, `Read Storage` etc, before the Milestone 2, because it requires the `RPC` and `websockets` layer to be implemented, so the read-only operations will be covered in the milestone 2, and the send signed extrinsics, derive wallet, etc, those items will be implemented in the milestone 3, because they require `Keyring` and `Crypto` libraries.

**Comment by alxs** [comment]
@Lohann we may be talking past each other here. What I meant to say is, isn't the reason that the frame-metadata is provided so one can communicate with the node? You don't only want to parse it correctly, you want to be able to understand and represent all types and other information provided in the metadata so that you can also create and encode extrinsics, RCP calls etc. Even if you don't have JSON-RPC and can't sign transactions, you'll still want to be able to create and encode them. Am I missing something?

**Comment by Lohann** [comment]
@alxs 
> isn't the reason that the frame-metadata is provided so one can communicate with the node?

Currently we don't have a way to communicate with Substrate node, once it requires a `websocket` connection between polkadart and the node, and this will be done in Milestone 2. Frame-metadata scope doesn't include how to communicate to the substrate node, only how to encode/decode it's metadata.

> Even if you don't have JSON-RPC and can't sign transactions, you'll still want to be able to create and encode them.

Notice that is already possible to encode/decode extrinsics, constants and RPC calls, etc using Polkadart Metadata, as you can see here:
https://github.com/rankanizer/polkadart/tree/main/packages/substrate_metadata#decode-extrinsic

Each metadata version expose different types depending of the version:
https://github.com/rankanizer/polkadart/blob/main/packages/substrate_metadata/lib/models/metadata/metadata_versions.dart#L65-L93

So the Metadata is ready, it already encode/decode extrinsics, storage, constants, but this is only useful once we connect to the node, so we can effectively use this to read the chain state.

**Comment by Lohann** [comment]
The user will should not use Polkadart `Metadata` directly, because polkadart seamlessly connects to the node, download the metadata and load the extrinsics dynamically, the same way that [polkadot-api](https://polkadot.js.org/docs/api/) does. The Metadata is the most complex component of Polkadart, and should only be used in very advanced scenarios (ex: offline sign extrincs, indexers, etc).

**Comment by alxs** [comment]
Thanks for the explanation and for adding more examples to the documentation. That makes sense - I was able to find the functionality thanks to the new examples and a bit more digging and, as I understand it now, [this list](https://github.com/rankanizer/polkadart/tree/main#substrate-metadata-1) represents the functionality of the library and is otherwise unrelated to Substrate metadata. Perhaps renaming this section would prevent confusion down the line.

And with this, I'm happy to let you know that the milestone has been accepted! Thank you for the great work on this milestone. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadart_1_alxs.md).

I'll notify the operations team to pay out the invoice you submitted. Please allow for up to 14 days for processing.

**Comment by alxs** [comment]
@Lohann I just noticed that your invoice is in USDT, but "only" USDC, USD and DOT are mentioned in the application :)

Could you submit a quick [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) replacing DOT with USDT [here](https://github.com/w3f/Grants-Program/blob/master/applications/Polkadart.md?plain=1#LL4), and USDC with USD [here](https://github.com/w3f/Grants-Program/blob/master/applications/Polkadart.md?plain=1#L144)? Thank you.

**Comment by alxs** [comment]
Also please update the address with the one in your invoice.

**Comment by Lohann** [comment]
@alxs will do!

**Comment by Lohann** [comment]
I put USDT because that's the only stablecoin currently supported by statemint:
https://tether.to/en/tether-usdt-to-launch-on-polkadot/

**Comment by alxs** [comment]
@Lohann we try to ensure the address and currency in the invoice are always the same ones as in the application.

**Comment by alxs** [comment]
@Lohann friendly reminder

**Comment by alxs** [comment]
Please ping @keeganquigley when you've submitted the amendment and it's been approved and he will forward the invoice to the operations team.

**Comment by Lohann** [comment]
@alxs @keeganquigley Invoice updated, it can be paid in DOT instead USDT.

**Comment by Lohann** [comment]
@keeganquigley Hmm so DOT is not support anymore, ok amend PR created!
https://github.com/w3f/Grants-Program/pull/1416

**Comment by keeganquigley** [comment]
@Lohann that's correct thank you! Please submit a new invoice accordingly since it is now USDC.

**Comment by Lohann** [comment]
@keeganquigley done ✅

**Comment by keeganquigley** [comment]
Thank you @Lohann I have forwarded your invoice for payment. Please expect up to 14 days for delivery.

**Comment by RouvenP** [comment]
hi @Lohann we just transferred the payment. Apologies for the delay!

**Pull request merged**
