### PR TITLE
add yc milestone2

### PR DESCRIPTION
**Pull request by davidrhodus**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/499

### CODE REVIEW

**Comment by semuelle** [comment]
Hi David, 
sorry for the long wait. I was able to review your milestone, at least most of it. The node and pallet side of things looks good, but I cannot use the frontend locally or run the integration tests due to the following issues. Can you advise?

- Uploading a site results in `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/api/Sites.`. Does this refer to the `yc-api` in your other repository?
- Opening the "My Sites" and "Marketplace" pages results in `Uncaught (in promise) TypeError: api.query.site is undefined`. Is this functionality on another branch than `sites-m2`?

**Comment by davidrhodus** [comment]
> Hi David, sorry for the long wait. I was able to review your milestone, at least most of it. The node and pallet side of things looks good, but I cannot use the frontend locally or run the integration tests due to the following issues. Can you advise?
> 
> * Uploading a site results in `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/api/Sites.`. Does this refer to the `yc-api` in your other repository?

We added in a backend API since our last milestone. It is primarily there to provide IPFS service to the frontend. We had difficultly getting larger amount of data e.g. a zipped website, to upload correctly from the web browser. If you are testing locally you'll need download https://github.com/YibanChen/yc-api There are setup instructions in the README.

> * Opening the "My Sites" and "Marketplace" pages results in `Uncaught (in promise) TypeError: api.query.site is undefined`. Is this functionality on another branch than `sites-m2`?

I am not able to reproduce this error. Is this error in the console log or a react error?

**Comment by semuelle** [comment]
I had another go, this time with the `yc-api` running. This resolves the CORS issue. However, I am still getting the `api.query.site` error. I have attached a screenshot 

image.

Also, when uploading a zipped website, I get the following error in the yc-api console:

```
error from front end:  pinata error
Executing (default): UPDATE `notes` SET `noteIndex`=$1,`updatedAt`=$2 WHERE `uuid` = $3
req.file here: {
  fieldname: 'siteFile',
  originalname: 'calculator.zip',
  encoding: '7bit',
  mimetype: 'application/zip',
  destination: './ipfsData/',
  filename: '36ce8500f9ef7184c97f59d971c92fea',
  path: 'ipfsData/36ce8500f9ef7184c97f59d971c92fea',
  size: 163973
}
size:  163973
Process finished.
TypeError: Cannot read property 'split' of undefined
    at uploadZipToIpfs (/usr/src/app/app/ipfs/ipfs.js:72:41)
    at exports.create (/usr/src/app/app/controllers/site.controller.js:32:16)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Immediate._onImmediate (/usr/src/app/node_modules/multer/lib/make-middleware.js:53:37)
    at processImmediate (internal/timers.js:466:21)
    at process.topLevelDomainCallback (domain.js:152:15)
    at process.callbackTrampoline (internal/async_hooks.js:128:24)
```

**Comment by davidrhodus** [comment]
> I had another go, this time with the `yc-api` running. This resolves the CORS issue. However, I am still getting the `api.query.site` error:
> 
> image

I was able to trigger this error by attaching the UI to a yc-node using the master branch without the site-pallet. Can you double check that you are using the branch with the site code? https://github.com/YibanChen/yc-node/tree/site-m2

> 
> Also, when uploading a zipped website, I get the following error in the yc-api console:
> 
> ```
> error from front end:  pinata error
> Executing (default): UPDATE `notes` SET `noteIndex`=$1,`updatedAt`=$2 WHERE `uuid` = $3
> req.file here: {
>   fieldname: 'siteFile',
>   originalname: 'calculator.zip',
>   encoding: '7bit',
>   mimetype: 'application/zip',
>   destination: './ipfsData/',
>   filename: '36ce8500f9ef7184c97f59d971c92fea',
>   path: 'ipfsData/36ce8500f9ef7184c97f59d971c92fea',
>   size: 163973
> }
> size:  163973
> Process finished.
> TypeError: Cannot read property 'split' of undefined
>     at uploadZipToIpfs (/usr/src/app/app/ipfs/ipfs.js:72:41)
>     at exports.create (/usr/src/app/app/controllers/site.controller.js:32:16)
>     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
>     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
>     at Immediate._onImmediate (/usr/src/app/node_modules/multer/lib/make-middleware.js:53:37)
>     at processImmediate (internal/timers.js:466:21)
>     at process.topLevelDomainCallback (domain.js:152:15)
>     at process.callbackTrampoline (internal/async_hooks.js:128:24)
> ```

I think this error is from not placing the site data(index.html, e.g.) into a directory. For multi file site, the backend api code is expecting everything to be side of a directory. We have some documentation that describes this workflow. https://docs.yibanchen.com/#multi-file-site

**Comment by semuelle** [comment]
> Can you double check that you are using the branch with the site code?

That resolved the `api.query.site` issue. My bad.

Regarding the upload, I succeeded by uploading a single HTML file. The zip I tried was a React project, and I did follow the docs (set `"homepage": "./"`, build, zip build folder). Perhaps you could look into that still. The project I used was https://github.com/ahfarmer/calculator.

Regardless, your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/yibanchen_2_semuelle.md). Other than the IPFS issue, I found it easy to set up and use, and I appreciate the thorough documentation! I will forward your invoice for processing.

**Comment by semuelle** [comment]
@davidrhodus, could you submit an updated invoice with the name and address of your company, as last time?

**Comment by RouvenP** [comment]
hi @davidrhodus we transferred the payment today.

**Pull request merged**
