### PR TITLE
Interstellar M1 Accepted

### PR DESCRIPTION
**Pull request by cruikshankss**
Link to the application pull request: https://github.com/w3f/Grants-Program/pull/734

### CODE REVIEW

**Comment by fededubbi** [comment]
Good morning,

We don't offer payments in ETH, could you please let us know if you prefer to be paid in USDT//DAI/BTC or USD and update your invoice accordingly?

Many thanks,
Federica Dubbini

**Comment by cruikshankss** [comment]
@nashjl @nathanprat ^ please see above message from our invoices team. @fededubbi, sorry I linked to my evaluation rather than [their M1 delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/394).

**Comment by nashjl** [comment]
Hi Federica, (@fededubbi )
Thanks for your message, in that case we prefer to be paid in USD, I submit a new invoice with our bank information.

Best
Jean-Luc Leleu

**Comment by nashjl** [comment]
Hi Asley @cruikshankss.
Thanks for your message, invoice with USD payment and bank information has been updated.
Have a great we!

**Comment by nashjl** [comment]
Hi Federica @fededubbi, do you have received our updated invoice? Please let us know if there are any issues.

**Comment by fededubbi** [comment]
Hi, 

Yes, well received thanks.
All good.

Many thanks,
Federica Dubbini

**Comment by nashjl** [comment]
Many thanks for the update !

**Comment by nashjl** [comment]
H Federica  @fededubbi have you already made the wire transfer to our bank account? if not, what is the process and how long does it takes?

**Comment by fededubbi** [comment]
Good morning,

The payment we did was returned, we are currently investigating on the reason and when we know the reason we will set up the payment again.

Many thanks.
Regards,

Federica Dubbini

**Comment by nashjl** [comment]
Many thanks for the update, Federica!
We will also check on our side with our bank!

**Comment by nashjl** [comment]
> The payment we did was returned, we are currently investigating on the reason and when we know the reason we will set up the payment again.
> 
> Many thanks.
Our bank just told us that the BIC/SWIFT information is incomplete you need to add Intermediary BANK BNP: BNPAFRPP in the "intermediary bank" field..

I have just updated the invoice accordingly:

You can initiate a wired transfer to the following Interstellar bank account:
IBAN FR76 1695 8000 0162 9728 3397 649 
BIC/SWIFT QNTOFRP1XXX 
Intermediary BANK BNP: BNPAFRPP
☝️ This BNP mention should not replace Qonto contact details. The BNP BIC must be entered in the "intermediary bank" field.
Titular: INTERSTELLAR 23 rue des Cordelieres 75013 Paris

Sorry for the inconvenience
Many Thanks

**Comment by nashjl** [comment]
Hi Federica @fededubbi 
Our bank just told us that the BIC/SWIFT information is incomplete you need to add the BIC: BNPAFRPP in the "intermediary bank" field. I have just updated the invoice accordingly: Sorry for the inconvenience Many Thanks

**Comment by nashjl** [comment]
Hi @fededubbi 

What is the status of the wired transfer? 30 days have passed since our first invoice but nothing has been received on our end so far. 

Greetings

**Comment by fededubbi** [comment]
Hi @nashjl,

We have tried to make the payment last week but it went back with a refund.
Could you please check again with your bank what went wrong?

We added the swift code of the intermediary bank this time, but it didn't work apparently.

Many thanks,
Federica Dubbini

**Comment by nashjl** [comment]
Hi @fededubbi 

Thank you very much for your answer, I checked with them, and they said it should have worked....
It would be great if you could provide me with a swift wire transfer receipt or any documents with swift field that might help them investigate the issue.
sorry again for the inconvenience.

Thanks very much

**Comment by fededubbi** [comment]
Hi @nashjl,

I will send them the document thanks.
I will ask our bank also a document with swift field.

Many thanks,
Federica Dubbini

**Comment by nashjl** [comment]
Hi @fededubbi,
Thanks, they can initiate a new swift wire transfer and provide us with MT103 details to investigate with our bank if it does not work.

**Comment by fededubbi** [comment]
Hi @nashjl,

I have set up again the payment today.
Let me know once received.

Many thanks,
Federica

**Comment by nashjl** [comment]
Hi @fededubbi,

Thanks a lot, I will keep you posted.
Sorry again for the inconvenience. 

Jean-Luc

**Comment by fededubbi** [comment]
Hi @nashjl,

Could you please confirm that you received the payment?

Many thanks,
Federica

**Comment by fededubbi** [comment]
Hi @nashjl,

From our side we didn't receive any refund.
Let me know if today is still not received and i will ask our bank the MT103 swift information doc.

Many thanks,
Regards,

Federica Dubbini

**Comment by nashjl** [comment]
Hi @fededubbi,

Sounds good but we still did not receive it. Please ask your bank the MT103.

Many thanks
Jean-Luc

**Comment by fededubbi** [comment]
Hi @nashjl,

I have asked now, i let you know as soon as we received it.

Many thanks,
Federica

**Comment by nashjl** [comment]
Hi @fededubbi  Thanks a lot

**Comment by fededubbi** [comment]
Hi @nashjl,

Pleas see the MT103 swift document attached.

Our bank is checking why the payment didn't go through and will let me know as soon as possible.

Sorry for this inconvenience.

Many thanks,
[USD9400.pdf](https://github.com/w3f/Grant-Milestone-Delivery/files/8714638/USD9400.pdf)

Federica [Dubbini[](url)](url)

**Comment by nashjl** [comment]
Hi @fededubbi, Thanks a lot for your prompt response and document.

Sorry for the inconvenience.
I will keep you posted on our bank feedback

Best
Jean-Luc

**Comment by nashjl** [comment]
Hi @fededubbi 

There is an issue with the MT103, the intermediary bank BIC:   BNPAFRPP must be in the field **56A** and not in the **70** field that is used for remittance information.

Our bank suggest that your bank send an **MT199** (message on the swift network) and add **BNPAFRP** in the intermediary bank field i.e. **56A**

Many Thanks
Jean-Luc

**Comment by nashjl** [comment]
I assume that MT199 message with the right information (including the missing 56A field in the MT103) should enable us to receive the payment.

**Comment by fededubbi** [comment]
Hi @nashjl,

Our bank sent to the correspondence bank the MT199.
Let me know if you receive the payment.

Many thanks,
Regards,

Federica Dubbini

**Comment by nashjl** [comment]
Hi @fededubbi,

Sure, I will be let know you as soon as we receive it.
Many thanks

Jean-Luc

**Comment by fededubbi** [comment]
Hi @nashjl,

Great to hear that!

Many thanks,
Federica

**Pull request merged**
