### PR TITLE
substrate_client_java milestone 1

### PR DESCRIPTION
**Pull request by strategyobjectadmin**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/726

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @strategyobjectadmin! We will look into it as soon as possible.

**Comment by alxs** [comment]
@strategyobjectadmin hey, sorry for the wait and thanks for the delivery from my side also. I haven't used Java in a while and struggled quite a bit to test this so please bear with me.

On the one hand, I wasn't able to set up the project to inspect it locally. Would you mind adding some instructions? I'm getting [these errors](https://github.com/projectlombok/lombok/issues/775) with the apt version of OpenJDK 8, but they may be just a symptom of a larger issue. Also instructions to run the tests and check coverage would be appreciated.

On the other hand, I tried using the packages from another project and couldn't figure out how to do it, e.g. where all the necessary imports were and what code was actually needed to run a simple example. For example the [documentation](https://github.com/strategyobject/substrate-client-java/wiki/Storage) for the storage package only provides incomplete examples for each feature and there's no mention of additional imports or boilerplate code needed. The first example refers to a `SystemPallet` class which seems to only exist as a [mock class](https://github.com/strategyobject/substrate-client-java/blob/master/api/src/test/java/com/strategyobject/substrateclient/api/SystemPallet.java) in your tests. Is that because the `pallet` package is not implemented yet? If so that's completely understandable, but it would be very useful to have a tutorial or a complete example of how to use the parts of the project that are already functional.

**Comment by strategyobjectadmin** [comment]
Hi @alxs, thanks for your reply.

Can you please specify the vendor of jdk you are using? There are multiple options (https://sdkman.io/jdks). If you are on ubuntu then it probably is `java.net`, I also tried `temurin` (former `adopt`, which is probably the most popular), but cannot reproduce the bug. To run the tests just run `gradle test` in terminal, test require docker . To check the coverage currently you can run "tests with coverage" from intellij, later we will setup jacoco plugin to make it easier.

The default SystemPallet is not provided currently, it will be implemented later. We are currently focused on code generation and implementation of protocols. We received several requests now to provide a better explanation on how to use the client, so I will try to write a sample project asap.

**Comment by strategyobjectadmin** [comment]
Hi @alxs. I've added a [sample project](https://github.com/strategyobject/substrate-client-sample). This is a simple example showing how to setup a project to use the client, all the necessary imports and so on. Please, take a look at it, and feel free to ask any questions.

**Comment by alxs** [comment]
Thanks for the updates! I managed to set up the project now and after some wrangling to run the tests.

The example project is of great help, thanks. Apart from that, the javadocs are excellent, but I still feel like users landing on your project e.g. from the [tech stack](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md) will have a hard time orienting themselves.

The [application](https://github.com/w3f/Grants-Program/blob/master/applications/substrate_client_java.md#milestone-1--queries-api) explicitly mentions "a basic tutorial that explains how a user can execute queries", and "a wiki page that explains the details of the implementation for queries within the substrate-client-java library". Could you make sure these two deliverables are present as such? Feel free to refer to and/or expand on the example project for this. Or if you think this distinction doesn't make sense any longer, feel free to submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to your application.

**Comment by strategyobjectadmin** [comment]
Hi @alxs we added "a basic tutorial", a HowTo section that we will continue to update.  Please, find it [here](https://github.com/strategyobject/substrate-client-java/wiki/HowTo-Examples). I also updated the milestone delivery.

**Comment by alxs** [comment]
Looks great, thank you!

Are all the traits in the [Storage module](https://paritytech.github.io/substrate/master/frame_support/storage/) implemented in the project, or do they not need to be? It looks like there are no Iterable types or PrefixedMap, for example.

The current [approach](https://github.com/strategyobject/substrate-client-java/wiki/Pallet#define-a-pallet) to describing a pallet's storage looks quite elegant, but I'm still not sure I understand how it's meant to be used. Is this always supposed to happen manually, or could it be generated from the metadata?

I also think it'd be useful to have the Javadocs online, maybe you could [publish](https://stackoverflow.com/a/15364790) them on GH pages as part of your CI.

**Comment by strategyobjectadmin** [comment]
@alxs indeed I think we should implement only things exposed with json-rpc interface. Currently, we support all storage types described in the official [documentation](https://docs.substrate.io/main-docs/build/runtime-storage/#storage-items). We consider our `StorageNMap` an n-dimensional map. So 0d corresponds to StorageValue, 1d to StorageMap, etc. The dimension depends on the number of keys you provide in the annotation.

Yes, you have to describe the type manually, because we need to know the types at compiletime and metadata becomes available at runtime.

Javadocs are now generated on CI. You can check it [here](https://strategyobject.github.io/substrate-client-java/).

**Comment by alxs** [comment]
Makes sense, thanks.

> Yes, you have to describe the types manually, because we need to know them at compiletime and metadata becomes available at runtime.

I meant that you can retrieve the metadata in advance and use it to auto-generate code to be compiled together with the project. That'd probably take quite a bit of effort, but it might be worth it if one is interacting with a large number of pallets. IIRC some of the other clients already implemented have functionality to do this.

Thanks for thoroughly addressing my comments. With this, I'm happy to tell you that the milestone is a pass! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/substrate-client-java_1_alxs.md).

I see you haven't checked the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89) checkbox in your first comment, could you please fill it out now? Let me know when you have and I'll notify the finance team to pay it.

**Comment by strategyobjectadmin** [comment]
@alxs thanks for the approval.

> I meant that you can retrieve the metadata in advance and use it to auto-generate code to be compiled together with the project. That'd probably take quite a bit of effort, but it might be worth it if one is interacting with a large number of pallets. IIRC some of the other clients already implemented have functionality to do this.

I got it. Yes, you are absolutely right it is possible. And actually we consider such a feature as a future improvement, but currently want to stay focused on making the client fully functional first.

**Comment by strategyobjectadmin** [comment]
Hi @alxs
> I see you haven't checked the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89) checkbox in your first comment, could you please fill it out now? Let me know when you have and I'll notify the finance team to pay it.

Sorry, I forgot to let you know that the form was submitted a long time ago.

**Comment by alxs** [comment]
Got it, I've notified the finance team.

**Pull request merged**
