### PR TITLE
Myriad Social Milestone 3 Deliverables Submission

### PR DESCRIPTION
**Pull request by gilangbh**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1795 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the delivery, @gilangbh, and sorry for the wait. 

I am going through all deliverables right now, and so far it looks great. I just have two requests:
1. The list of deliverables does not match the one in the application. For example, I am missing the `Additional Clients` and `Authentication Improvement` ones. Could you clarify this?
2. The list only ever links to the head commit of the `myriad-web` repo. That makes it difficult to verify the implementation of the individual deliverables. If you could provide links to specific commits or lines of code that relate to each deliverable, it would help us (and others in the future) to follow the evaluation.

**Comment by agustinustheo** [comment]
Hi @semuelle 

Thanks for pointing that out.

It was a mistake on our part, I've added new commits to update the document accordingly! (cc: @gilangbh)

But to make it easier for you to see as well, I've made a response to your questions in this post as well:

---

**Additional Clients**: @Decentricity and @RiXelanya built a browser extension to make it easy to import and cross-post content from platforms like Twitter, Reddit, YouTube, and Twitch to Myriad Social. Here’s where you can check it out:

- **Repository**: [Myriad Importer Extension](https://github.com/myriadsocial/myriad-importer-extension)
- **Chrome Web Store**: [Myriad Extension](https://chrome.google.com/webstore/detail/myriad-extension/caafifipbilmonkndcpppfehkhappcci)

---

**Authentication Improvement**: This one is under the deliverable titled **"B2B Features: Multi-User Management System"**. A big part of this improvement was adding **Personal Access Tokens (PATs)** to allow secure multi-user access and account sharing.

Here are the commits related to this feature:

- **[e15a84bf](https://github.com/myriadsocial/myriad-web/commit/e15a84bf5d364a1e62226f2c0a33088138e0eb4a)** - Add PAT & account sharing setting.
- **[d385a0e6](https://github.com/myriadsocial/myriad-web/commit/d385a0e6fc731cc5fae4029c045430fc81785f08)** - Fix PAT UI.
- **[6386e19c](https://github.com/myriadsocial/myriad-web/commit/6386e19ce7bc3df96a3951e9dfc6b3778b4ef0dc)** - Revert PAT UI.
- **[908d17a2](https://github.com/myriadsocial/myriad-api/commit/908d17a2be78e50c27b857de2a623beaf7e2e4d3)** - Prevent anonymous user from generating a Personal Access Token.
- **[b662acb8](https://github.com/myriadsocial/myriad-api/commit/b662acb8a84369b436a9dd0461d1e887a52e16ac)** - Add authentication with Personal Access Token.
- Our implementation within the Parachain can be seen here: https://github.com/myriadsocial/myriad-node-parachain/tree/main/pallets/access_token

---

Hopefully, this clears up the confusion.

If there’s anything else just let us know.

Thanks for your patience!

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @gilangbh. Looks good. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/a251b9df4c5ab89bbbbfc17e7c506dfba7358514/evaluations/myriad-social_3_semuelle.md).

Congrats on completing the grant! I hope it helped you with settling into the Polkadot ecosystem.

**Comment by RouvenP** [comment]
hi @gilangbh we just sent the payment

**Pull request merged**
