### PR TITLE
Create Tokenguard - Milestone 1 & 2.md

### PR DESCRIPTION
**Pull request by caaaml**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1944 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by caaaml** [comment]
Hey @keeganquigley !

Please find here the delivery for the Dashboard composer. As promised, here you can test the solution on real-life data:
https://demo-dc-app.tokenguard.io/

Happy to hear your thoughts! Also, we've modified our USDT wallet address, please let me know if I should correct it in the initial proposal.

Best,
Kmaik

**Comment by caaaml** [comment]
Hey @PieWol,

I've PRed the update to the initial proposal. Please kindly confirm if this has been done correctly :)

Best,
Kamil

**Comment by PieWol** [comment]
Hey @caaaml ,
glad to see the amendment PR was successful. The Milestone delivery has to list the same deliverables as agreed upon in the application. So please add e.g. "testing and testing guide", "license" and other missing deliverables in the tables.

**Comment by caaaml** [comment]
Hey @PieWol,

Sorry for issues, we've updated the tests - everything should work smooth now!

image
image

Best,
Kamil

**Comment by caaaml** [comment]
Hey @PieWol,

What are the next steps to move forward?

Best,
Kamil

**Comment by PieWol** [comment]
Hi @caaaml ,
your guide for the server doesn't work. Best way to make sure an evaluation is done quickly is to make sure everything is working and the testing guide covers all needed steps for unit testing and running your project locally. 

For example your dockerfile doesn't seem to be mentioned at all in the readme or testing guide. Please extend the documentation.

**Comment by PieWol** [comment]
I have now put up an [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1176/files?short_path=61b4386#diff-61b4386de2bed10f987e243c72883db46cdb629a2c7ae73b7173f6da10079647). Please introduce the changes I requested. Thank you!

**Comment by PieWol** [comment]
@caaaml ,
Hey, hope you are doing well. Any updated from your side?

**Comment by PieWol** [comment]
Hey @caaaml ,
I checked out your changes which look really promising! Thanks a lot for this well structured update. I will have your evaluation done by tomorrow.

**Comment by caaaml** [comment]
Hey @PieWol,

The repo is updated with the lacking pie chart (please note that links have changed) :) Thanks for the heads up!

The delivery is for both milestones - 1 and 2. Should I open a separate PR for the m2?

Best,
Kamil

**Comment by PieWol** [comment]
Hey @caaaml , thanks for the swift response! I'll check it out.

We usually recommend to split the delivery in different PRs. In this case though I am confident that the second milestone will be quickly approved after the first one as they are so closely linked together. Just by running the testing guide I already tested both front and backend. Meaning if you are willing to wait for me to finish the second milestone evaluation before you can invoice the funds for the first milestone feel free to leave it the way it is.

**Comment by caaaml** [comment]
Hey @PieWol,

Perfect, we'll wait for the m2 to be checked as well!

Best,
Kamil

**Comment by PieWol** [comment]
Hey @caaaml ,
The first milestone is accepted 🎉 
I will evaluate the second milestone shortly.

**Comment by PieWol** [comment]
Hey @caaaml ,
I have put up my [evaluation for M2](https://github.com/w3f/Grant-Milestone-Delivery/pull/1187) for you to review and address my comments and questions. Looking forward to your updates.

**Comment by caaaml** [comment]
Hey @PieWol,

We've updated the repo according to your evaluation. 

Regarding the M2 part 3. "Report & estimation" - we discussed this with Sebastian and agreed to limit this part to Changelog only. The estimation was supposed to include the costs for next features to be built with W3F grants but Sebastian said the follow-up should be done through DF grants, not W3F - so the estimation became obsolete.

Let me kindly know if everything works fine now!

Best,
Kamil

**Comment by PieWol** [comment]
Hey @caaaml , 
thanks for the changes. I still had no luck to start the service without docker following the readme. I updated my evaluation and I'm looking forward to your comments. Thanks!

**Comment by rrozek** [comment]
Hi @PieWol , i’m not sure if @caaaml mentioned it, but since there were new commits, the current tag to verify is v2.0.5 (https://github.com/tokenguardio/dashboard-creator-server/tree/v2.0.5)

or you can check dev branch at it is in sync with v2.0.5 now.
(https://github.com/tokenguardio/dashboard-creator-server/tree/dev)

if you can confirm that you checked one of those (that would be surprising) then i’ll take another look at that. Sorry for inconvenience

cheers,
Kuba

**Comment by PieWol** [comment]
Hey @rrozek ,
I tried it with the updated version. I assumed that ``.localhost.env`` contains a valid default config to launch the service.

```> dashboard-creator-server@2.0.5 server:dev
> ts-node-dev --inspect=0.0.0.0:9229 --exit-child --respawn -r tsconfig-paths/register src/server.ts

[INFO] 14:52:36 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 4.9.5)
Debugger listening on ws://0.0.0.0:9229/5058b6d5-f7ad-43c4-a296-e837a7464e11
For help, see: https://nodejs.org/en/docs/inspector
2024-06-08 14:52:36.999 info Logger level is set to debug
(node:49961) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
2024-06-08 14:52:37.977 info Connecting to MongoDB without CA cert
2024-06-08 14:53:07.991 error MongoDB connection error: getaddrinfo ENOTFOUND db
2024-06-08 14:53:07.997 error getaddrinfo ENOTFOUND db 
 Error: getaddrinfo ENOTFOUND db
    at Object.connect (/Users/-/Desktop/dashboard-creator/dashboard-creator-server/src/db.ts:28:11)
    at Server.<anonymous> (/Users/-/Desktop/dashboard-creator/dashboard-creator-server/src/server.ts:11:3)
[ERROR] 14:53:07 Error: getaddrinfo ENOTFOUND db
2024-06-08 14:53:07.998 info Server closed
```

**Comment by rrozek** [comment]
Thanks for providing logs!
So as i suspected the service starts but does not connect to mongodb (because it doesnt exist)

2024-06-08 14:53:07.991 error MongoDB connection error: getaddrinfo ENOTFOUND db

We could do the academic dispute if it means service works or not, but i get your point that it is not operational („it is, by design”)

similar thing is with the frontend that it opens but returns errors if ran without docker-compose.

i believe the instructions are clear enough given the comments about fully-working compose in TESTING dir.

cheers,
Kuba

**Comment by rrozek** [comment]
In such case, i believe it makes more sense to add all steps required for potential further development of the service (without the need for the frontend) by future users/developers here.

I’ll update the getting started section to use minimal docker-compose project which i will include in repo root dir „as usual”

ETA: this evening

cheers,
Kuba

**Comment by PieWol** [comment]
Awesome, happy to hear that! Thanks for putting in the extra work :)

**Comment by rrozek** [comment]
hi @PieWol ,
done. https://github.com/tokenguardio/dashboard-creator-server/tree/v2.0.6
or simply https://github.com/tokenguardio/dashboard-creator-server/dev
(please note that default repo branch is different than dev)

thank you!

**Comment by PieWol** [comment]
Thanks, both milestones are now accepted 🎉

**Comment by caaaml** [comment]
Hey @PieWol,

Thank you as well! Invoice submitted.

Best,
Kamil

**Comment by semuelle** [comment]
Hi @caaaml. The invoice you submitted lists a bank account, but the agreement is for USDT payment. Could you update one to match the other? Both would be fine for us, it just needs to match to avoid misunderstandings.

**Comment by caaaml** [comment]
Hey @semuelle,

I've create another PR but you need to accept and resolve the conflict:
https://github.com/w3f/Grants-Program/pull/2331

Best,
Kamil

**Pull request merged**
