### PR TITLE
Treasury Tracker - Milestone 1

### PR DESCRIPTION
**Pull request by senseless**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1900

### CODE REVIEW

**Comment by senseless** [comment]
Can you please provide insight into "Check Author" automated check? I'm not sure where I went wrong on this check. I'd like to correct it if possible. Thank you.

**Comment by keeganquigley** [comment]
Thanks for the delivery @senseless glad you were able to figure it out. You can find my initial eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/treasury_tracker_1_keeganquigley.md). Please have a look as there are currently some tests failing. Thanks!

**Comment by senseless** [comment]
> Thanks for the delivery @senseless glad you were able to figure it out. You can find my initial eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/treasury_tracker_1_keeganquigley.md). Please have a look as there are currently some tests failing. Thanks!

The speed of the build, that can't be helped unfortunately. It's doing both a npm install and a composer install. The only thing to speed up that process is additional cpu and network speed. In a production environment, this would be using apache, mysql and the polkadotjs-proxy on separate nodes communicating over lan. There is also a 10 second delay on startup to give time for mysql to load properly so the apache docker can bootstrap the SQL.

Regarding the unit tests, I have made a new commit which should resolve the unit test issues. It appears some code from another repo was lost inadvertently. I had to make some new tests. 

Regarding the UI bug that was highlighted, The referenda page should have been responsive already, but the banner may have caused an issue. The analytics page had a fixed width but is now responsive. We've pushed these changes to the live site. I recommend doing a force refresh in the browser to clear any caches. We do plan to improve UI significantly in the next set of updates bringing in the responsive elements and taking another step toward production quality. 

Please let me know if you have further issues with the updated master branch

**Comment by keeganquigley** [comment]
Thanks for the fixes @senseless no more failures, but still getting some [error](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/treasury_tracker_1_keeganquigley.md) notices. I'm not super familiar with PHP, are these normal at this stage?

**Comment by senseless** [comment]
> Thanks for the fixes @senseless no more failures, but still getting some [error](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/treasury_tracker_1_keeganquigley.md) notices. I'm not super familiar with PHP, are these normal at this stage?

Based on those errors it appears as if you're running the unit tests outside of the docker environment. It's failing due to not being able to connect to the database running inside the other container (the host has no knowledge of the docker hostname schema). Based on the current configuration of the repo (designed for instant docker deployment) you will need to operate the phpunit command inside of the docker container. I will issue a commit shortly to update the documentation to reflect this.

Execute the following commands:
- Gain access to a bash prompt on the web docker container `docker exec -it docker-test_web_1 /bin/bash`
- Execute the phpunit test from the "/var/www/treasurytracker" page `./vendor/bin/phpunit -v tests`

It's not really normal in most cases to build unit tests for php projects. This is honestly the first time I've done it. I can see use cases for more complex logic, but not at this stage.

**Comment by keeganquigley** [comment]
Thanks @senseless I appreciate it; let me know when I should take another look.

**Comment by senseless** [comment]
> Thanks @senseless I appreciate it; let me know when I should take another look.

It should be good now

**Comment by keeganquigley** [comment]
Thanks @senseless and apologies for the delay, I was OOO for a week. Here is my [final eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/treasury_tracker_1_keeganquigley.md). Please note the small UI glitch that I found. I am still happy to go ahead and accept the milestone. Thanks for your hard work!

**Pull request merged**
