### PR TITLE
deliveries/halva_bootstrapping

### PR DESCRIPTION
**Pull request by ByKeks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for delivering the milestone, we will look into it as soon as possible.

**Comment by Noc2** [comment]
Hi. I just finished the evaluation and I can confirm that everything works. So, I’m happy to tell you that the milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/halva_bootstrapping_1_Noc2.md) and will now forward your invoice internally

**Comment by ByKeks** [comment]
HI @Noc2. Thank you very much! We're happy to hear that.

**Comment by RouvenP** [comment]
Hi @ByKeks, we just sent a test transaction. Could you please confirm if received?

**Comment by ByKeks** [comment]
Hi @RouvenP, I confirm, a transaction is received to correct address

**Comment by RouvenP** [comment]
> Hi @RouvenP, I confirm, a transaction is received to correct address

Thanks for confirming. Transaction is sent.

**Pull request merged**
