### PR TITLE
Add hyperfridge milestone 4 delivery

### PR DESCRIPTION
**Pull request by dastansam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2096

cc @wstrametz

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @dastansam. Sorry for the delay. Someone will look into it asap.

**Comment by PieWol** [comment]
Hey @dastansam ,
Thank you for the delivery. I checked the original pull request and noticed that the deliveries are slightly different from the ones listed in this delivery. Would you be able to rephrase the deliveries so that they match the ones in the application? This would be much appreciated. Thanks.

**Comment by PieWol** [comment]
Thank you for the delivery @dastansam.
I'm evaluating it and will get back to you shortly.

**Comment by PieWol** [comment]
Hey @dastansam ,
could you please point me to instructions on how to run the e2e tests? Thanks!

**Comment by PieWol** [comment]
Hey @dastansam ,
thanks for the awesome milestone delivery. It's accepted. 🎉
Here is the [eval document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperfridge_4_piewol.md).

**Comment by RouvenP** [comment]
hi @dastansam we sent the payment yesterday

**Pull request merged**
