### PR TITLE
add daos m2

### PR DESCRIPTION
**Pull request by JimYam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1050 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @JimYam, thanks for the delivery! I'm starting the evaluation, so I'll reach out if I need your help.

**Comment by 0xCaso** [comment]
I wanted to locally setup the testnet provided [here](https://github.com/DICO-TEAM/dico-chain/blob/main/docs/create-vc-dao.md) to test this milestones' deliverables.  Do you know if the emergency module is implemented there?

**Comment by JimYam** [comment]
> Hi @JimYam, thanks for the delivery! I'm starting the evaluation, so I'll reach out if I need your help.

Many thanks.

**Comment by JimYam** [comment]
> 
ws://localhost:9946

**Comment by JimYam** [comment]
> 

ws://localhost:9946

**Comment by JimYam** [comment]
> Just a quick question, I was trying to setup the dico testnet locally to test the emergency module. I should have to run a local node with `substrate-contracts-node`, then run `polkadot-launch config.json`. After this, should I connect with https://polkadot.js.org/ to the local node, or am I missing something? Because I cannot make it work for some reason (maybe the local node is unnecessary).
> 
> EDIT: I've seen [in the tutorial](https://github.com/DICO-TEAM/dico-chain/blob/main/docs/emergency%20module.md) it's used a local frontend. So definitely I'm missing something

ws://localhost:9946

**Comment by 0xCaso** [comment]
If you mean putting that endpoint in polkadot.js, it doesn't work

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work

https://github.com/DICO-TEAM/dico-chain#development

**Comment by JimYam** [comment]
> > If you mean putting that endpoint in polkadot.js, it doesn't work
> 
> https://github.com/DICO-TEAM/dico-chain#development


Please follow this instruction to start the testnet, and connect to port 9946

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work

I use the ubuntu system, and it can run completely on my side. Please provide more error information

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work


Or you try to compile https://github.com/paritytech/polkadot/tree/release-v0.9.32 instead of the current polkadot

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work

Have you executed this command `cargo build --release`, both in the dico-chain directory and the polkadot directory?

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work


In the first milestone of daos, there is no problem at all when running like this

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work

Or check your yarn and node version, is it too old

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work


You need to make sure that you open the webpage on the computer running the node locally

**Comment by JimYam** [comment]
> If you mean putting that endpoint in polkadot.js, it doesn't work

I started the [test network here](https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F47.242.233.235%3A9946#/explorer), you can also connect directly

**Comment by 0xCaso** [comment]
Thanks a lot for the answers, probably I've made something wrong but in the end I managed to run the local testnet

**Comment by JimYam** [comment]
> Thanks a lot for the answers, probably I've made something wrong but in the end I managed to run the local testnet

Hello, Boy. You can run the node locally, right?

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Hi @JimYam, I've just added the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/daos_2_0xCaso.md). As you'll see, everything is almost perfect. If you have any questions let me know!

**Comment by JimYam** [comment]
> Hi @JimYam, I've just added the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/daos_2_0xCaso.md). As you'll see, everything is almost perfect. If you have any questions let me know!

Thanks a lot for your valuable advice. I've made corresponding changes to the minor issues that exist. The test coverage is already very comprehensive at the function level, but because of the tool, the code of the Storage part cannot appear in the report, and it has actually been covered. I tested it again in polkadot.js, and the result of `set_pledge` has no problem. It may be that your polkadot.js has not refreshed the data, and this part of the [test_code](https://github.com/daos-org/daos/blob/0af568d526a161e66d4eb4b3e4b2f974ae4fd2f5/emergency/src/tests.rs#L85) has been strictly tested. many thanks.

**Review by 0xCaso — APPROVED** [review]

**Comment by 0xCaso** [comment]
Hey @JimYam, I'm happy to inform you that Milestone 2 has been accepted, congrats for the great work, and thank you!

I'm notifying the finance team to pay out your invoice. As usual, please allow for up to 14 days for processing.

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
Sorry @JimYam, I noticed that (in your invoice) you requested USDT on Ethereum as payment method. Recently we changed our Guidelines, and I kindly ask you if it could be possible to change it to another method (one of [these](https://github.com/w3f/Grants-Program#pencil-process) so,  if you want to stay on Ethereum, USDC or DAI; otherwise one of the others). If yes, could you please resend an updated invoice?

**Comment by JimYam** [comment]
> Sorry @JimYam, I noticed that (in your invoice) you requested USDT on Ethereum as payment method. Recently we changed our Guidelines, and I kindly ask you if it could be possible to change it to another method (one of [these](https://github.com/w3f/Grants-Program#pencil-process) so, if you want to stay on Ethereum, USDC or DAI; otherwise one of the others). If yes, could you please resend an updated invoice?


Thanks for a great job. I have changed the address to USDC.

**Comment by JimYam** [comment]
> > Sorry @JimYam, I noticed that (in your invoice) you requested USDT on Ethereum as payment method. Recently we changed our Guidelines, and I kindly ask you if it could be possible to change it to another method (one of [these](https://github.com/w3f/Grants-Program#pencil-process) so, if you want to stay on Ethereum, USDC or DAI; otherwise one of the others). If yes, could you please resend an updated invoice?
> 
> Thanks for a great job. I have changed the address to USDC.

Hello boy. I have already sent you an invoice and provided you with a USDC address. If you have received it, you can let me know here so that I can confirm it. Many thanks!

**Comment by JimYam** [comment]
> Hi @JimYam, I've just sent the new invoice to the finance team, thanks a lot for changing it. Please allow for up to 14 days for processing.

Thanks!. It would be even better if the grant funds arrive before Christmas.

**Comment by 0xCaso** [comment]
Hi @JimYam! The finance team should have sent you an email one week ago (12 Dec) asking you to re-send the invoice without the "Term and Conditions" part. Did you send it?

**Comment by JimYam** [comment]
> Hi @JimYam! The finance team should have sent you an email one week ago (12 Dec) asking you to re-send the invoice without the "Term and Conditions" part. Did you send it?

Sorry, I don't have the habit of using emails frequently, so I didn't reply email messages in time. I just made changes to the invoice and it has been sent. if there is still a problem, please let me know as soon as possible. Merry Christmas!

**Comment by 0xCaso** [comment]
I'm sorry we didn't warn you also here; I've just notified the finance team. However, thanks a lot for the re-submission, and Merry Christmas!

**Comment by 0xCaso** [comment]
> Sorry, I don't have the habit of using emails frequently, so I didn't reply email messages in time. I just made changes to the invoice and it has been sent. if there is still a problem, please let me know as soon as possible. Merry Christmas!

Sorry again @JimYam, we noticed that the address in the invoice is different from the one provided in the application. You can chose between these two options:
- Amend the application, editing the address with the new one provided;
- Resend a last time the invoice with the address you put in the application.

**Comment by JimYam** [comment]
> 

Dear @0xCaso , Our team members work in a distributed manner. Because I am in Beijing personally, I have filled in the invoice address here. In the application, I did not provide any detailed address, this does not conflict.

**Comment by JimYam** [comment]
I mean, I didn't find any information about the detailed address in [https://github.com/w3f/Grants-Program/blob/master/applications/daos.md](https://github.com/w3f/Grants-Program/blob/master/applications/daos.md). Please let me know if something goes wrong elsewhere.

> > Sorry, I don't have the habit of using emails frequently, so I didn't reply email messages in time. I just made changes to the invoice and it has been sent. if there is still a problem, please let me know as soon as possible. Merry Christmas!
> 
> Sorry again @JimYam, we noticed that the address in the invoice is different from the one provided in the application. You can chose between these two options:
> 
> * Amend the application, editing the address with the new one provided;
> * Resend a last time the invoice with the address you put in the application.

I mean, I didn't find any information about the detailed address in [https://github.com/w3f/Grants-Program/blob/master/applications/daos.md](https://github.com/w3f/Grants-Program/blob/master/applications/daos.md). Please let me know if something goes wrong elsewhere.

**Comment by 0xCaso** [comment]
I was meaning this address (at the top of the application):
Screenshot 2022-12-22 at 09 56 08

**Comment by JimYam** [comment]
> I was meaning this address (at the top of the application): Screenshot 2022-12-22 at 09 56 08


I have resent the invoice. But I don't know if you are willing to pay USDT, if you can, it is better. Of course USDC is also available. Because I used the USDT address in M1.

**Comment by JimYam** [comment]
> > I was meaning this address (at the top of the application): Screenshot 2022-12-22 at 09 56 08
> 
> I have resent the invoice. But I don't know if you are willing to pay USDT, if you can, it is better. Of course USDC is also available. Because I used the USDT address in M1.


If the USDT address cannot be used, it means that I need to change `USDT` to `USDC` in the application, which will disturb your colleagues.

**Comment by 0xCaso** [comment]
Thanks a lot again, and no worries, you won't need to change from `USDT` to `USDC` in the application. If you can accept `USDC`, they'll use it as currency for the payout.

This time the invoice should be perfect!

**Comment by JimYam** [comment]
> Thanks a lot again, and no worries, you won't need to change from `USDT` to `USDC` in the application. If you can accept `USDC`, they'll use it as currency for the payout.
> 
> This time the invoice should be perfect!

Thank you very much, USDT is also available.

**Comment by JimYam** [comment]
> Thanks a lot again, and no worries, you won't need to change from `USDT` to `USDC` in the application. If you can accept `USDC`, they'll use it as currency for the payout.
> 
> This time the invoice should be perfect!

Thank you very much, USDC is also available.

**Comment by RouvenP** [comment]
hi @JimYam we transferred the payment today

**Pull request merged**
