### PR TITLE
dao-entrance-phase-1 milestone 1

### PR DESCRIPTION
**Pull request by bai-3**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1445

### CODE REVIEW

**Comment by bai-3** [comment]
@keeganquigley Hello, is there any new news aboutthis delivery

**Comment by keeganquigley** [comment]
@bai-3 Hi, I apologize for the delay. I was out of office last week. I am still evaluating and will get back to you tomorrow!

**Comment by keeganquigley** [comment]
Hi @bai-3 very sorry for the delay. You can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dao-entrance-node_1_keeganquigley.md). The node runs fine and all tests pass, but I had some issues getting through the guide. I am executing all as Alice test account. Can you check my eval and let me know what I'm doing wrong here? Thanks!

**Comment by bai-3** [comment]
@keeganquigley Hi Thank you very much for your reply.  I have update test image in testing-guide.md.  The original sample account is not clear, now use ALICE and BOB to demonstrate the program running.   Note that the daoid filled in with DAOGov and DAOSudo must be the same as the daoid for the following method.    [testing-guide ](https://github.com/dao-entrance/dao-entrance-node/blob/main/docs/testing-guide.md)is here.

**Comment by keeganquigley** [comment]
@bai-3 thanks for the changes, much appreciated!

I'm happy to pass the milestone. Nice work and it is cool to see it coming together; can't wait to see the front-end. You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dao-entrance-node_1_keeganquigley.md).

**Comment by keeganquigley** [comment]
@bai-3 unfortunately, we don't offer aUSD as a [payment option](https://github.com/w3f/Grants-Program#pencil-process) anymore. Would you be willing to switch to USDT instead? That way you could just submit a new invoice and keep the same Polkadot address. Otherwise, if you are not willing to switch from aUSD let me know and I will talk to the operations team. Thanks.

**Comment by bai-3** [comment]
@keeganquigley Of course, USDT is OK. I will submit a new invoice

**Comment by bai-3** [comment]
> @bai-3 thanks for the changes, much appreciated! Everything works properly now.
> 
> I'm happy to pass the milestone. Nice work and it is cool to see it coming together; can't wait to see the front-end. You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dao-entrance-node_1_keeganquigley.md). Please take a look at my notes near the bottom regarding Cargo Clippy.

I will take care of these warnings. Thank you especially for reminding me

**Comment by keeganquigley** [comment]
Thanks @bai-3 let me know when the invoice is submitted.

**Comment by bai-3** [comment]
Hi @keeganquigley  Thanks for your reply.  i have submit a new invoice

**Comment by keeganquigley** [comment]
thanks @bai-3 much appreciated. I have forwarded your invoice internally for processing.

**Comment by RouvenP** [comment]
hi @bai-3 we transferred the payment today.

**Pull request merged**
