### PR TITLE
DaoSign milestone 2 delivery

### PR DESCRIPTION
**Pull request by ramilexe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1770

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @ramilexe much appreciated. I have started my evaluation.

With only two unit tests, the code coverage is currently very low:

```ts
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |      25 |     5.26 |   15.38 |   26.41 |                   
 index.ts |      25 |     5.26 |   15.38 |   26.41 | 27-120,138-157    
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        4.769 s, estimated 5 s
Ran all test suites.
```
Are you able to write some additional tests to better cover all the functions? 80% or more is ideal.

<details>
<summary>Examples</summary>

`numberToArray`:
Test with positive and negative numbers.
Test with zero.
Test with large numbers.
Test with numbers that exceed the maximum safe integer.

`sendTransaction`:
Test successful transaction with valid parameters.
Test failed transaction with invalid parameters.
Test transaction with different gas limits and storage deposit limits.
Test transaction with different error scenarios (e.g., insufficient funds, network errors).

`storeProofOfAuthority`, `storeProofOfSignature`, `storeProofOfAgreement`:
Test successful storage of proofs with valid parameters.
Test failed storage with invalid parameters.
Test error handling for network issues or contract errors.
</details>

**Comment by ramilexe** [comment]
Hi @keeganquigley 
We definitely will do it, thank you for feedback

**Comment by ramilexe** [comment]
Hi @keeganquigley 
we enhanced unit tests, please check. Test coverage now more than 92%

image

**Comment by keeganquigley** [comment]
Thanks @ramilexe I appreciate the fixes. I have accepted the milestone, here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DAOsign_m2_keeganquigley.md).

**Comment by RouvenP** [comment]
hi @ramilexe we sent the payment last Friday

**Pull request merged**
