### PR TITLE
Propose XBI - standard for Polkadot's XCM Transact

### PR DESCRIPTION
**Pull request by MaciejBaj**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/903

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@MaciejBaj thanks for your delivery.
The deliverables in the delivery are supposed to match those from the contract. Hence, could you please add the [1a & 1b deliveries](https://github.com/w3f/Grants-Program/blob/master/applications/xbi-format-psp-t3rn.md#milestone-1--produce-psp-as-a-result-of-collaboration-with-selected-partners-which-sets-requirements-for-xbi-format-and-xbi-executors-interface)?

**Comment by MaciejBaj** [comment]
thanks @takahser. Updated the submission pointing to 1b. part of deliveries - the basic XBI Format implementation with documentation.

**Comment by dsm-w3f** [comment]
@MaciejBaj thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xbi-format-psp-t3rn_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by MaciejBaj** [comment]
Hi @dsm-w3f thanks for the feedback. Just added you to the repository where we collaborated on XBI for approximately 1 month with other Parachain Teams mentioned in Acknowledgement section of the grant submission. We hope that suffices for the `Call for Feedback stage` of PSP-33. 

In regards to the Documentation and lacking test coverage - we're happy to extend both.

**Comment by AwesomeIbex** [comment]
Hi @dsm-w3f - We have extended the test coverage as per https://github.com/t3rn/xbi/pull/3. 

In general, we take a pragmatic approach to testing and test functionality. Since most of our implementation is provided by the language or other libraries (e.g sp_core::U256), we don't cover tests as a KPI metric. However, we have tested other critical paths, and white box tested some paths that were not picked up due to bugs in the coverage tools (gcov/tarpaulin) where the tests covered generic input args.

**Comment by dsm-w3f** [comment]
@MaciejBaj and @AwesomeIbex thank you for the answers. The improvement in coverage looks good. About the Call for Feedback stage, would be nice if this kind of discussion could be held in public repositories since standards are for the community and this would allow to all community to participate. It is possible to delivery this discussions as public? Anyone for Parity was involved in the discussion?

**Comment by t3rninator** [comment]
Hey @dsm-w3f, thanks for the feedback. We can open a Gitter 

Appreciate that it is for community and feedback is pivotal is something like this 

We've collaborated with [](url)

**Comment by t3rninator** [comment]
Hey @dsm-w3f, thanks for the feedback.

Appreciate your input and that feedback is pivotal in initiatives like this. From our perspective, XBI was created in collaboration with the projects who are most likely to benefit from using it, opening it up further to full public input could have hindered our ability to bring it to this point where it is relatively usable and useful. We are more than happy to open it up to a public discussion on the next iteration. In the meantime, we can absolutely open a Gitter on this version.

On the Parity side we've collaborated with @SBalaguer, while @Noc2 accepted our proposal. I'm unclear about how to make discussions public as comms on XBI development were done through messaging platforms like Telegram and Element. 

Let me know your thoughts.

**Comment by dsm-w3f** [comment]
@t3rninator depending on how the discussion was performed in Telegram or Element you won't be able to make it public. Usually this kind of discussion is held in Github together with the artifact of the PSP in the pull request (https://github.com/w3f/PSPs/pulls). As it was discussed in other channels, this should not be a problem. The delivery is now approved. Great work!

**Comment by RouvenP** [comment]
hi @MaciejBaj we transferred the payment today.

**Pull request merged**
