### PR TITLE
dotmog milestone 1

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [X] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [X] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Hi @darkfriend77 and thank you for the delivery. I'm happy to look into this soon, but please allow for a few days as we are currently very busy due to a high number of applications.

**Comment by darkfriend77** [comment]
Hi @alxs 

any news? We already have the next milestone ready, ... could you give us an eta on the current one?

Regards
DOTMog Team

**Comment by alxs** [comment]
Hi @darkfriend77, apologies for the delay, as I said we currently have a lot to do. I will evaluate your milestone this week; in the meantime, feel free to submit milestone 2 as well.

**Comment by alxs** [comment]
This looks great. Could you add a testing guide as per deliverable 0c?

**Comment by alxs** [comment]
Yes that's all, thank you.

**Comment by alxs** [comment]
Alright, I think you've done really great work and clearly deserve something in recompense for your efforts. We've recently started putting extra care into making sure that projects always comply with the appropriate licenses so I'd just like to ask you to address the following:
- Which parts of your library are your own work, and which are adapted? Please disclose every project you based your work on.
- I see that at least the Schnorrkel part is adapted from [Usetech's API](https://github.com/usetech-llc/polkadot_api_dotnet), and also that you're making efforts to comply with the license since you have recent commits addressing this. However, Apache 2.0 is rather strict in this regard and you need to add a notice to every file you replicated or modified. This isn't a lot of work, just copy-paste a notice such as [this](https://pastebin.com/raw/Lz99iTeY) at the beginning of each file. A single LICENSE file at the root of your project suffices.

And a few unrelated points:
- There must be good reasons you chose not to use said library, what were they and could you highlight current differences between the two?
- I see there is some Mogwai-specific stuff in the library. Since we'd like this library to be as generic as possible, would it constitute a lot of work for you to remove these elements from the library and to provide an abstraction you can call from the client instead for example? Also some of the tests rely on your Zürich node. Please provide instructions on how to set up a local node instead (or just link to the [node template](https://github.com/substrate-developer-hub/substrate-node-template) if that works, this shouldn't be a DOTMog node in any case since again the library is supposed to be generic) and test locally.
- Inline documentation is very sparse and is part of your deliverables. If this is something you did not consider in your application, I'm happy to accept this part of the delivery as is given the low price but I'd appreciate it if you reapplied for a follow-up grant that encompasses it such that this is something that eventually gets done. I think this library has the potential to be widely used but it needs better documentation and probably some improvements.

If this seems like too much work in general, withdrawing your current delivery and reapplying again with sufficient funding is definitely also an option.

Otherwise, I encourage you to consider applying for a larger grant once you've completed this one. As I understand it, you all just work on this in your free time and for that, you're doing excellent work. I'm quite positive we could provide more funding such that you could invest more time and/or hire someone (can be a freelancer, just make sure it's someone with experience) to work on future improvements and maintenance of this library and other components that can be reused by the community, even if we can't fund later stages of your project as long as they rely on proprietary code.

**Comment by darkfriend77** [comment]
First of all, thank you for taking your time to review our milestone and for your appreciated feedback.

We have added the missing License information to the files in the Schnorrkel project.

SubstrateNetApi and SubstrateNetWallet have been written from scratch by our team.
For us, the most important part is 100% compatibility with Unity we provide this by making sure that every library we use is NETStandard2.0 [Unity profile support](https://docs.unity3d.com/2020.2/Documentation/Manual/dotnetProfileSupport.html) or less.

We focus on using standard packages like StreamJsonRPC (maintained by Microsoft), to avoid reinventing the wheel and rely on stability. We didn't just copy Rust to C#, instead, we rewrote the code from scratch to make use of C# where it would benefit the code readability and reduce complexity. One of our major key features is that we use the metadata to generate our storage access and types in runtime. We think that the API offers a good abstraction for game developers to make use of it without having to worry too much about the chains deep inside. Another feature is of course is the wallet which allows account creation and a cross-platform private key AES encryption on mobile devices.

Of course, we will remove the DOTMog specific tests, concerning the test setup and link the node-template. We will do the commit later this week.

Surely we will consider reapplying for a larger grant, after this one. Currently, the project is slowly but inevitably getting too big for the two of us to continue as a hobby. We are therefore very interested in further capable enthusiasts and possible collaborations. 
We would also like to point out which variants we see regarding the disclosure of the full source code and IP of our project, or how the community could benefit from it.

It would be great if we could discuss our project previously to our second application, so we can figure out what opportunities we have and how the w3f can profit from our project. Would this be a possible proceeding, if so please contact us to schedule a meeting, admin@dotmog.com

Kind regards Cédric Decoster, André Schneider

**Comment by darkfriend77** [comment]
Hi @alxs 
as promised, we committed a new tag including the requested changes, we would be glad if you could review milestone 1, so we can further process with our deilveries. I've documented the changes and my thoughts about them on the release page, https://github.com/dotmog/SubstrateNetApi/releases/tag/v1.0.2

PS: We can't wait to be eligible to have the w3f badge :-)

Regards
Cedric

**Comment by darkfriend77** [comment]
Hi @alxs,

is there something missing for the first milestone?

Regards
Cedric

**Comment by alxs** [comment]
Hi Cedric, sorry once again about the delay. If I'm the one looking into your next deliveries too, I'll make sure to make that happen faster. As I said, feel free to submit all remaining milestones already if yo have already finished them.

Thanks for the changes, this is great. I'm happy to tell you that the milestone is a pass, you can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotmog_1_alxs.md).

Regarding deliverable 0d: this usually means an article promoting your work or a step-by-step tutorial to build something simple using your project. Something like the short description in this [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/102#issuecomment-797060824) of yours would be perfect if expanded and would likely be good for visibility down the road, plus I'm sure it'd be an interesting read. I'd encourage you to publish something along those lines with the last milestone, if you want feedback on it, you can also reach out to grantsPR@web3.foundation with a final draft.

It's perfectly fine to keep your custom tests in a separate folder at the current stage of the project. Regarding pointing to Polkadot RPC, this is already better but ideally you'd eventually do all of this locally, especially so you can also test storage and transfers. If you can't spin up a Docker image for the AppVeyor tests, I guess you'd create a separate suite of integration tests that can be run locally or through GitHub Actions.

Happy to hear that you'll likely be applying for a follow-up grant. We can definitely have a chat before this, I'll send you an email.

**Comment by RouvenP** [comment]
hi @darkfriend77 we just sent a test tx. Could you confirm if received?

**Comment by darkfriend77** [comment]
received.
image

**Comment by RouvenP** [comment]
@darkfriend77 thanks for confirming. We sent the remaining part yesterday.

**Pull request merged**
