### PR TITLE
Stable Asset milestone 3 delivery

### PR DESCRIPTION
**Pull request by frankyin-factual**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/286
Amendment: https://github.com/w3f/Grants-Program/pull/804

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @frankyin-factual. We'll look into it as soon as possible.

**Comment by alxs** [comment]
Would you mind also pointing me to the documentation, i.e. deliverable 1 in your [application](https://github.com/w3f/Grants-Program/blob/master/applications/stable-asset.md#milestone-3--support-yield-in-stable-asset)?

**Comment by shengda** [comment]
> Would you mind also pointing me to the user documentation, i.e. deliverable 1 in your [application](https://github.com/w3f/Grants-Program/blob/master/applications/stable-asset.md#milestone-3--support-yield-in-stable-asset)?

The doc is on https://nutsfinance.gitbook.io/stable-asset/

The algorithm and architecture provide details on the implmentation.

**Comment by frankyin-factual** [comment]
just updated the dependencies so you should be able to build and run.

**Comment by alxs** [comment]
Thanks. Docker still fails with the same error, could you double-check that it works for you?

Also, the pallet contains almost no inline documentation - would it be possible for you to expand on it, ideally provide rustdocs? It would make it much easier to understand what you've implemented.

Lastly, the user documentation doesn't explain how to interact with it. Are you still planning to add this?

**Comment by frankyin-factual** [comment]
@alxs Fixed dockerfile, added some rustdoc, and the user guide is in a JS client in `demo/client`

**Comment by alxs** [comment]
Please note that the client isn't working either, and also the documentation doesn't seem to refer to the pallet. As per your application, the documentation should explain "how to handle yield in stable asset pools", which in the context of the milestone I think it would make sense to explain in terms of interacting with the pallet. 

I'd also be happy to see more documentation than the methods documented starting on line 1100. By the way, what I assume was a copy-paste mistake seems to have left the description of 3 different methods identical ("Redeem the token into a single token").

**Comment by frankyin-factual** [comment]
@alxs Fixed the client and the documentation. For `how to handle yield in stable asset pools`, this isn't a specific pallet interaction, but rather behind the scene that for each pallet call, we do `collect_yield` which updates the underlying token balances and mint the excess into a special account. For more details, @shengda can fill you in more.

**Comment by shengda** [comment]
@alxs In short, we have a yield recipient and fee recipient to collect yields and fees respectively.

Since yields are accrued in between calls, each time the stable asset is minted/redeemed/swapped, we do a yield collection before by checking if there is any balance or parameter increase that leads to pool value increase. If there is an increase, it's regarded as yield of the pool and the yield is minted as stable asset and sent to yield recipient.

Unlike in milestone where fees are collected via dedicated method, fees are collected after each mint/redeem/swap so that it can be separated from yields.

Please review if Frank's new commit has fixed the client issue. We hope that we can move on and start our tDOT application as soon as possible. Thank you.

**Comment by alxs** [comment]
Thanks, it did after re-generating `yarn.lock`, see my [PR](https://github.com/nutsfinance/stable-asset/pull/18).

Thanks for the explanation. Do you have any actual documentation on this? That'd be [deliverable 1 ](https://github.com/w3f/Grants-Program/blob/master/applications/stable-asset.md#milestone-3--support-yield-in-stable-asset) for this milestone, but also in general I think users will want to know how yield works in Stable Asset.

Could you also point me to the tests covering amplification parameter changes as per deliverable 3?

**Comment by shengda** [comment]
@alxs The documentation is [here](https://nutsfinance.gitbook.io/stable-asset/fundamentals/architecture).

@frankyin-factual will provide test detail and README.

**Comment by frankyin-factual** [comment]
@alxs so the tests are done on the Acala side because that's where we integrated the rebasing tokens, included in the submission: https://github.com/AcalaNetwork/Acala/blob/969878303c90f9a019df32b017e87c76c6b5d73e/runtime/integration-tests/src/stable_asset.rs

**Comment by frankyin-factual** [comment]
@alxs added tests for `modify_a` and fixed `README`.

**Comment by shengda** [comment]
@alxs That public repo is outdated. The latest doc for stable asset is [here](https://nutsfinance.gitbook.io/stable-asset/).

**Comment by alxs** [comment]
Thank you both. Could you push to the public repo though so we can fork it? Lastly, could you please update the delivery file with the latest commit hash? Thanks.

**Comment by shengda** [comment]
The stable asset doc is pushed to [another repo](https://github.com/nutsfinance/stable-asset-docs).

**Comment by frankyin-factual** [comment]
@alxs updated the git hash and line numbers.

**Comment by alxs** [comment]
Thanks @frankyin-factual @shengda. With this, I'm happy to tell you that the milestone is a pass - you can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stable-asset_3_alxs.md). I'll notify the operations team to pay your invoice. Please allow for up to 14 days for your payment to be processed. Best of luck with your current application.

**Comment by RouvenP** [comment]
hi @frankyin-factual we transferred the payment today. Thanks!

**Pull request merged**
