### PR TITLE
Create Afloat_Milestone1.md

### PR DESCRIPTION
**Pull request by LouiseWReed**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/911

### CODE REVIEW

**Comment by 3yekn** [comment]
A few technical notes on this project: 
- As reminder, Afloat is a current production application that is integrating with Hashed Network marketplaces (and other dotsama functionality)

- Referenced above, we are using Quasar/Vue for Hashed Network general purpose, block explorer-style clients, and this is where  functionality is being built initially. We are ensuring the functionality is modular/composable because it will also be used within Afloat's existing Angular application (which is closed source/private repo). So, for the grant, the deliverables are in Vue. 

- The version of the "Confidential Documents" (privacy preserving) component will be replaced with a pallet-powered solution imminently. The one linked in this PR works, but the new one will be: https://github.com/hashed-io/hashed-confidential-docs-client-api (which uses a pallet as the backend).

Lmk if there any any questions. I can provide a link and account key if you want to try the functionality out on our testnet. :pray: 

CC: @thowell332 @jmgayosso

**Comment by lucasvanmol** [comment]
Hi @LouiseWReed, @3yekn - thanks for the delivery!

Regarding the delivery document, could you please update the table under **Deliverables** to include a link to the deliverable itself? This could be a link to a document, a repository or a specific file/line(s) of code in a repository. Thanks!

**Comment by lucasvanmol** [comment]
In addition, could you also provide instructions for running the whole project locally? I'm able to build and run the private server, node, and frontend each individually, but it looks like the UI isn't able to connect to the node/private server. Feel free to also reach out to me on element if you prefer: https://matrix.to/#/@lucas:web3.foundation

**Comment by lucasvanmol** [comment]
Thanks for your communication on element, and helping with some minor issues. As such I've accepted the delivery and you can see my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/afloat_1_lucasvanmol.md). I'll also forward your invoice internally.

Finally, could you get into contact with grantspr@web3.foundation before publishing your article? They'll be able to look through it and help promote it. Feel free to also share the presentation slides with them aswell.

**Comment by lucasvanmol** [comment]
@LouiseWReed @3yekn 

It looks like the invoice you sent to us was for $21 600, however your application stated [$17,675](https://github.com/w3f/Grants-Program/blob/master/applications/Afloat.md#milestone-1--user-onboarding-set-and-verify-identity-with-gatekeeper-parameters-and-slides). Is this a mistake? If so, feel free to send an update invoice using the invoice form again.

**Comment by AugustoLara** [comment]
@lucasvanmol 

We've resubmitted the invoice with the correct amount of [$17,675](https://github.com/w3f/Grants-Program/blob/master/applications/Afloat.md#milestone-1--user-onboarding-set-and-verify-identity-with-gatekeeper-parameters-and-slides).

FYI @3yekn @LouiseWReed

**Comment by lucasvanmol** [comment]
Thank you, I've forwarded it to the finances team

**Comment by RouvenP** [comment]
hi @LouiseWReed we transferred the payment on Tuesday.

**Comment by LouiseWReed** [comment]
Thank you for paying so quickly.  I've confirmed it is in Afloat's wallet.

**Pull request merged**
