### PR TITLE
Project Delmonicos milestone 1

### PR DESCRIPTION
**Pull request by lumena-tech**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by fcroiseaux** [comment]
I don't understand the error. If the google sheet in the one related to the invoice, I've filled it.

**Comment by lumena-tech** [comment]
I thought it was related to the author but apparently not

**Comment by semuelle** [comment]
Thanks for the delivery, @lumena-tech & @fcroiseaux. We will look into it as soon as possible. 

The check is in fact just for our internal bookkeeping, so nothing to worry about!

**Comment by lumena-tech** [comment]
Hello, is ti possible to have an idea of the standard duration of the evaluation process of a milestone ?

**Comment by alxs** [comment]
Hey @lumena-tech. We currently have a bit of a backlog and this is likely to take a couple of weeks. Submitting a milestone shouldn't stop you from continuing to work on the project though. We recommend adding a tag or commit hash to the links in the deliverables so that you can continue to work without breaking anything.

**Comment by adetante** [comment]
Hi @alxs , thanks for your feedback, I have created a tag ([milestone-1](https://github.com/Delmonicos/charger-node/tree/milestone-1)) and updated the README to link a specific commit in our source repository.

**Comment by mmagician** [comment]
@lumena-tech @fcroiseaux I've got a few comments regarding your delivery from my initial review:

---
`UserConsent` struct in two modules:

`pallet-user-consent`
- map of hash -> (user_id, charger_id)

`pallet-session-payment`
- map of AccountId -> (timestamp, iban, bic_code) (of which timestamp is never used - unless I've missed something)

I think the name UserConsent here is slightly misleading (especially if timestamp is not used). To me it sounds more like UserDetails, as it holds the relevant banking information of the user.

---
`registrar` pallet:
Do you plan to support multiple organisations created by the same account, or rather just having one `charger` organisation as specified in your [docs](https://github.com/Delmonicos/charger-node/blob/milestone-1/Web3-Grant/milestone1/testing-guide.md#what-is-included-in-this-release)?

If the use case is to have just one organisation, why not use the [membership](https://github.com/paritytech/substrate/blob/master/frame/membership/src/lib.rs) pallet as you initially suggested in the [first milestone](https://github.com/w3f/Open-Grants-Program/pull/283)?

---
Otherwise everything looks fine. Some unit tests are still missing and there are a few leftover TODOs, but that's ok, as I see you're working on the next milestone already - I expect that would be addressed there?

---
Extra:

[PR](https://github.com/substrate-developer-hub/pallet-did/pull/15) to update the DID pallet to substrate 3.0. Still in review. Thanks for trying to merge upstream, it would be great to get that in!

**Comment by lumena-tech** [comment]
> @lumena-tech @fcroiseaux I've got a few comments regarding your delivery from my initial review: 
> `UserConsent` struct in two modules:
> 
> `pallet-user-consent`
> 
> * map of hash -> (user_id, charger_id)
> 
> `pallet-session-payment`
> 
> * map of AccountId -> (timestamp, iban, bic_code) (of which timestamp is never used - unless I've missed something)
> 
> I think the name UserConsent here is slightly misleading (especially if timestamp is not used). To me it sounds more like UserDetails, as it holds the relevant banking information of the user.

Actually both are user consents but for different things. We should have define more explicit names. We will rename at least one of the two elements.
- `pallet-user-consent` proves that the user has given his consent to start a specific charging session.
- UserConsent in `pallet-session-payment` proves that the user give consent to the bank to initiate payment from his account. If you have a look at the current version, we have added a signature that is generated and verified off-chain. The idea is that the user first connects to his web banking site and send a signed chalenge to prove to the bank that he owns a specific private key. For each payment, the signature stored in pallet-session-payment is send to the bank with the timestamp. Then the bank can verify that the initiator of the payment is really the account owner. 


`registrar` pallet:
> Do you plan to support multiple organisations created by the same account, or rather just having one `charger` organisation as specified in your [docs](https://github.com/Delmonicos/charger-node/blob/milestone-1/Web3-Grant/milestone1/testing-guide.md#what-is-included-in-this-release)?
> 
> If the use case is to have just one organisation, why not use the [membership](https://github.com/paritytech/substrate/blob/master/frame/membership/src/lib.rs) pallet as you initially suggested in the [first milestone](https://github.com/w3f/Open-Grants-Program/pull/283)?

Yes, we plan to create several organizations through this registrar pallet. Currently we only have the charger organization, but later we could have an organization that list all the users authorized to access the service, another organization that lists the accounts authorized to add a new charger for example, ... So the goal is to use the registrar to configure these different organizations, and check who can do what.
Another reason why we use the registrar pallet is the fact that we want to use the did-pallet to add trusted attributes to identities (e.g. the location of a charging station). 

> 
> Otherwise everything looks fine. Some unit tests are still missing and there are a few leftover TODOs, but that's ok, as I see you're working on the next milestone already - I expect that would be addressed there?

Yes, we will complete the tests and the TODO in the upcoming milestones.

> 
> Extra:
> 
> [PR](https://github.com/substrate-developer-hub/pallet-did/pull/15) to update the DID pallet to substrate 3.0. Still in review. Thanks for trying to merge upstream, it would be great to get that in!

**Comment by mmagician** [comment]
@lumena-tech thanks for a prompt response.

> We will rename at least one of the two elements.

Do you mean for this milestone? Seeing that you have already done work on top of the current codebase, I understand it might be somewhat tricky if you try to change `milestone1` branch and then cherry-pick those commits on your `master`. It's fine by me if you "fix it" for the next milestone, too. I'll leave that up to you, just let me know if I should wait or proceed.

**Comment by lumena-tech** [comment]
> @lumena-tech thanks for a prompt response.
> 
> > We will rename at least one of the two elements.
> 
> Do you mean for this milestone? Seeing that you have already done work on top of the current codebase, I understand it might be somewhat tricky if you try to change `milestone1` branch and then cherry-pick those commits on your `master`. It's fine by me if you "fix it" for the next milestone, too. I'll leave that up to you, just let me know if I should wait or proceed.

Yes, I meant we will rename for the next milestone if this is ok for you. It will be more easy for us.

**Comment by mmagician** [comment]
Great. Then I'm happy to announce that your first milestone has been accepted. Please see the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/164) & good luck with the next phase!

**Comment by mmagician** [comment]
@lumena-tech Currently your invoice's currency is BTC. As your [original contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/delmonicos.md#milestone-1-implement-charger-module-pallet) states USD, please send us an updated invoice using DAI. 

Also, something that slipped our attention is that your payment address in the contract is a BTC address. I imagine you'll want a different address for DAI. We'd need an amendment to the above document - please submit a relevant PR to the Open Grants repo. Thanks for understanding!

**Comment by fcroiseaux** [comment]
I've submitted a new PR with the DAI(ETH) address instead of the BTC address and refilled the invoice form with a new invoice.

**Pull request merged**
