### PR TITLE
Milestone Delivery: Dual-Key Stealth Address Protocol

### PR DESCRIPTION
**Pull request by wuyahuang**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/997

### CODE REVIEW

**Comment by cruikshankss** [comment]
Good day @wuyahuang, I was able to review your application and m1 details. Thank you very much for the delivery.

Forgive me for the rookie mistakes (and things I likely should know), but I figured it's good to ask you for help with testing. 

I ran these commands (below) which you link to from your testing guide but wasn't able to compile a local node. I am not sure if this is an issue with substrate or an issue with my machine. I just wanted to update you to let you know I'm still working on running a proper local node to test your project. I have a couple other machines I can test this on, but figured I'd write you a note just to keep you updated. Very sorry about this. If you have any advice, thanks.

```
❯ git clone https://github.com/substrate-developer-hub/substrate-node-template
❯ cd substrate-node-template && git checkout polkadot-v0.9.26                 
❯ cargo build --release
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/substrate.git`
error: failed to select a version for the requirement `libp2p = "^0.46.1"`
candidate versions found which didn't match: 0.45.1, 0.45.0, 0.44.0, ...
location searched: crates.io index
required by package `sc-cli v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.26#e8a7d161)`
    ... which satisfies git dependency `sc-cli` (locked to 0.10.0-dev) of package `node-template v4.0.0-dev (/Users/ash/wthree/substrate-node-template/node)`
```

**Comment by wuyahuang** [comment]
Hi, @cruikshankss . Thank you for starting the review.
It looks like a problem with the version of libp2p. You can try to use a compiled substrate node to launch a local Polkadot blockchain.
The easiest way is to download a binary release from [our releases page](https://github.com/paritytech/substrate-contracts-node/releases) and just execute ./substrate-contracts-node --dev.

**Comment by cruikshankss** [comment]
@wuyahuang that worked, thank you so much for the help. I plan to keep you updated.

**Comment by cruikshankss** [comment]
Hi @wuyahuang, I tried running "cargo +nightly contract build" in each repo but got: "error: no such subcommand: `contract`". Any advice on what I'm doing wrong? Thanks!

**Comment by wuyahuang** [comment]
Good day @cruikshankss, please install `cargo-contract` first.
cargo-contract is a CLI tool which helps you develop & compile smart contracts in Parity's [ink!](https://github.com/paritytech/ink).
[Read more details about carogo-contract](https://github.com/paritytech/cargo-contract)
Sorry for that, I have already updated README.md

**Comment by cruikshankss** [comment]
Hi @wuyahuang, thank you for updating the README. I was able to install `cargo-contract`.

I've run the next command `cargo +nightly contract build` in several different ways but keep getting:

```
cargo +nightly contract build

ERROR: Loading Cargo.toml

Caused by:
    No such file or directory (os error 2)
```

Any advice?

**Comment by wuyahuang** [comment]
🤣🤣🤣
The `Cargo.toml` is in the ink contract folder `erc721`, please execute `cd erc721/` before running `cargo +nightly contract build`.

**Comment by cruikshankss** [comment]
@wuyahuang 😂 Thank you so much.  I was able to successfully compile and test the `erc721/target/ink/erc721.contract`. I will keep you updated on deploying and testing the contract on the local node. Sorry I have not done this before and advice for next time is to include more detailed instructions in the case the evaluator has never compiled/deployed an ink! contract before. ;-)

**Comment by cruikshankss** [comment]
@wuyahuang I've made it to this screen on https://contracts-ui.substrate.io/. 
Screen Shot 2022-08-02 at 6 48 29 PM but I've got the error "StorageDepositLimitExhausted - More storage was created than allowed by the storage deposit limit." and don't know how to proceed. At this point, I'm going to have to take a break from working on your eval and request you update your testing guide. You've omitted so many steps already and it's a requirement that you provide quality testing guide and documentation. Please let me know once you've fulfilled the requirements of the milestone delivery. I'm very interested in learning about the true value of your project and how it works. Thank you.

**Comment by wuyahuang** [comment]
@cruikshankss 
I recorded a demo video, including:
* How to launch Polkadot local node.
* How to compile & test ink! smart contract.
* How to deploy ink! smart contract to the local node.
* How to test DKSAP implementation for Polkadot. 

https://www.youtube.com/watch?v=QB1QE0t7FeQ

**Comment by cruikshankss** [comment]
@wuyahuang Thank you very very much for this. I will look through this as soon as possible.

**Comment by wuyahuang** [comment]
Dear @cruikshankss, thank you for your time in evaluating Dual-Key Stealth Address Protocol.

I have resubmitted the invoice with addresses, and the output log "Encrypted owner address:" has also been added to the code repository.

I appreciate you showing me how to create an understandable test guide, especially for new Polkadot talents. I think this will make it easier for me to write understandable test guides in the future.

Finally, I would want to express my gratitude to the web3 Grants Program for funding DKSAP and bringing my idea into reality.

**Comment by cruikshankss** [comment]
Dear @wuyahuang, 

I've forwarded your invoice internally. Thanks for making those updates! Thanks also for the very kind message and gratitudes. I will pass them along to the team.

**Comment by RouvenP** [comment]
hi @wuyahuang we transferred the payment today. Thanks!

**Pull request merged**
