### PR TITLE
Subxtpy Milestone 2

### PR DESCRIPTION
**Pull request by philoniare**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: [Proposal](https://github.com/w3f/Grants-Program/pull/2246).

### CODE REVIEW

**Comment by philoniare** [comment]
Yep, right now, the user can subscribe to new blocks (they can fetch block details and all of the extrinsics associated with the new block) and events as they come in real-time.

**Comment by PieWol** [comment]
Thanks, sadly I get this error when running the tests. Do you have any idea why? 

```=============================================================================== FAILURES ================================================================================
_______________________________________________________________________ test_subscribe_new_blocks _______________________________________________________________________

    @pytest.mark.asyncio
    async def test_subscribe_new_blocks():
        client = await SubxtClient.new()
>       subscription = await client.subscribe_new_blocks()
E       AttributeError: 'builtins.SubxtClient' object has no attribute 'subscribe_new_blocks'

tests/test_subscription.py:8: AttributeError
======================================================================== short test summary info ========================================================================
FAILED tests/test_subscription.py::test_subscribe_new_blocks - AttributeError: 'builtins.SubxtClient' object has no attribute 'subscribe_new_blocks'
====================================================================== 1 failed, 7 passed in 0.29s ==============
```

**Comment by philoniare** [comment]
@PieWol I believe a previous version got installed, could you please make sure that the version is 0.2.0 by running this?
```
pip install subxtpy==0.2.0
```
Thanks, lmk if it still doesn't work.

**Comment by PieWol** [comment]
> @PieWol I believe a previous version got installed, could you please make sure that the version is 0.2.0 by running this?
> 
> ```
> pip install subxtpy==0.2.0
> ```
> 
> Thanks, lmk if it still doesn't work.

Great, that fixed it! What do you need to change in the readme or the requirements so that it works straight up? :)

**Comment by philoniare** [comment]
@PieWol thanks for pointing it out, I've updated the README with the upgrade option so that it fetches the latest version.

**Comment by PieWol** [comment]
Hey @philoniare ,
sounds good. I put up a PR with my evaluation which still contains a few little comments. e.g. about the Sphinx documentation and another package which seems to be needed but isn't mentioned in the readme. Looking forward to you addressing these minor comments. Should be resolved quickly 👍 .

**Comment by philoniare** [comment]
@PieWol thanks for the review, I'll be resolving those issues soon.

**Comment by philoniare** [comment]
@PieWol updated the readme with linux instructions and fixed the issue with styling for sphinx: [docs](https://philoniare.github.io/subxtpy/)

**Comment by PieWol** [comment]
Hey @philoniare ,
thanks for the latest changes. I still think the documentation needs a little love. Could you introduce spaces between the different classes so that it isn't a huge wall of text?

Why is the actual header and search bar of the documentation at the bottom?

**Comment by philoniare** [comment]
Hey @PieWol, I totally agree with you. The existing sphinx doc site wasn't doing the project justice, so I've chosen to document it with custom markdown files using `mkdocs`. The new doc site is available [here](https://philoniare.github.io/subxtpy/).

Thanks

**Comment by PieWol** [comment]
Awesome changes 👍 Documentation looks nice now.

**Comment by PieWol** [comment]
Congrats on successfully delivering your grant 🎉 !

I hope this keeps getting maintained and used :)

**Comment by philoniare** [comment]
Thanks for the detailed review as always!

For sure! Will be sure to keep a close eye on dev demand and feature requests.

**Comment by RouvenP** [comment]
hi @philoniare we sent the payments today.

**Pull request merged**
