### PR TITLE
Add hyperfridge milestone 3 delivery

### PR DESCRIPTION
**Pull request by dastansam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2096

cc @wstrametz

### CODE REVIEW

**Comment by wstrametz** [comment]
author check is failing; should be resubmit? thx alot

**Comment by PieWol** [comment]
Hey @wstrametz , no problem. Thanks to your comment we see that it is indeed you trying to hand in this delivery. No need for changes.

**Comment by PieWol** [comment]
Have you already conducted test in production mode? How did that work out?

**Comment by wstrametz** [comment]
> Have you already conducted test in production mode? How did that work out?

Hi @PieWol  - yes; we tested with and without CUDA on linux (not macOS metal yet) -  here are some findings: 

https://github.com/element36-io/hyperfridge-r0/blob/main/docs/runtime.md

I also did test with the API key (Bonsai) but did not measure that. Anyway want to add a productive version using Bonsai (with real bank account) for the last milestone - will add it measurement for bonsai then. 

Cheers, Walter

**Comment by PieWol** [comment]
Hey @wstrametz and @dastansam please check out my [current evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1183) I have put up for you. Looking forward to your comments. I sadly got stuck while following the testing guide.

**Comment by PieWol** [comment]
Hey @dastansam , thanks for the fixes, I'm getting further than before. Sadly I'm still runnning into an issue when trying to execute the API call from the testing guide. I have strictly used the values from the screenshot. (Bob transfers 2 tokens to Alice). Looks like for some reason the ebics-service is started in a simluation mode which provides fake statements but the runtimes isn't able to process them. The one I created doesn't even show up. How do I start the ebics service correctly so that only the specific statements I create in the swagger-ui are submitted?

Here is the error log from the node:
```
2024-05-23 16:56:42 ✨ Imported #166 (0x600f…a967)    
2024-05-23 16:56:42 [OCW] Instantiating offchain worker    
2024-05-23 16:56:42 [OCW] Syncing: true    
2024-05-23 16:56:42 [OCW] Current activity: <wasm:stripped>    
2024-05-23 16:56:42 [OCW] Activity: <wasm:stripped>    
2024-05-23 16:56:42 Requested started id=1348 method=GET uri=http://localhost:8093/ebics/api-v1/bankstatements
2024-05-23 16:56:42 [OCW] JSON received: [{"iban":"CH4308307000289537312","balanceOP":80842.45,"balanceOPCurrency":"CHF","balanceCL":80097.2,"balanceCLCurrency":"CHF","balanceCLDate":"2021-02-28","bookingDate":"2021-02-28","validationDate":"2021-02-28","incomingTransactions":[],"outgoingTransactions":[{"iban":null,"name":null,"addrLine":["VISECA CARD SERVICES SA \nHagenholzstrasse 56 \nPostfach 7007 \n8050 Zuerich","ich"],"currency":"CHF","amount":745.25,"reference":null,"endToEndId":null,"instrId":null,"msgId":null,"pmtInfId":null}]},{"iban":"CH2108307000289537320","balanceOP":0,"balanceOPCurrency":"CHF","balanceCL":110,"balanceCLCurrency":"CHF","balanceCLDate":"2021-03-14","bookingDate":"2021-03-14","validationDate":"2021-03-14","incomingTransactions":[{"iban":"CH4308307000289537312","name":null,"addrLine":["element36 AG \nBahnmatt 25 \n6340 Baar"],"currency":"CHF","amount":100,"reference":"Testanweisung","endToEndId":null,"instrId":null,"msgId":null,"pmtInfId":null}],"outgoingTransactions":[]}]    
2024-05-23 16:56:42 panicked at /Users/Desktop/ocw-ebics/pallets/fiat-ramps/src/utils.rs:25:78:
called `Option::unwrap()` on a `None` value    
2024-05-23 16:56:42 Error running offchain workers at 0x600fac6ef24e18a2e24d5eab1cdc5ceca623e86c215c2674066ba494ee92a967: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:
error while executing at wasm backtrace:
    0: 0x16ea51 - <unknown>!rust_begin_unwind
    1: 0x5e99 - <unknown>!core::panicking::panic_fmt::h3aff855fe938c13f
    2: 0x6510 - <unknown>!core::panicking::panic::h11a2021d92dc1cbb
    3: 0x64c8 - <unknown>!core::option::unwrap_failed::h0e0b231623e0d004
    4: 0xb0bd0 - <unknown>!<fiat_ramps::pallet::Pallet<T> as frame_support::traits::misc::OffchainWorker<<<<T as frame_system::pallet::Config>::Block as sp_runtime::traits::HeaderProvider>::HeaderT as sp_runtime::traits::Header>::Number>>::offchain_worker::h1b7953c444e0366c
    5: 0x4837b - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::offchain_worker::hd04f58194f863336
    6: 0x991b3 - <unknown>!OffchainWorkerApi_offchain_worker
```

**Comment by PieWol** [comment]
@dastansam  I ran it like this:
``    docker run -p 8093:8093 e36io/ebics-service``

**Comment by PieWol** [comment]
Got it, thanks @dastansam. I will retry it from scratch now with your updated commands and the latest commits of the ``hyperfridge`` branch.

**Comment by PieWol** [comment]
Hey @dastansam , regarding your fix with the ebics-service readme. Can you include the possibility to run this on arm? Or is arm currently not supported?

**Comment by PieWol** [comment]
Hey @dastansam ,
sadly even after retrying it with your latest changes it doesn't work for me to mint the stable coins. Can we please setup a quick call to figure out together what is going wrong? Please schedule a meeting with piet@web3.foundation

**Comment by PieWol** [comment]
Hey @dastansam, thanks for the latest change with the remot API. Now I was able to test everything and gave you some feedback. It worked great 🎉 ! Only question I still have was about the balance storage item within the fiat-ramps pallet. You can find it in the notes. [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1183)

Once this is answered the milestone will be approved.

**Comment by PieWol** [comment]
Thanks again for your latest improvements. Looking forward to the next milestone deliveries! 🎉

**Comment by RouvenP** [comment]
hi @dastansam we just sent the payment.

**Pull request merged**
