### PR TITLE
Subalfred milestone 2

### PR DESCRIPTION
**Pull request by AurevoirXavier**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1158

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @AurevoirXavier. We'll look into it as soon as possible.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier I went ahead and did a preliminary evaluation of your delivery. Could you please address the issues in my [notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subalfred_2_alxs.md) and get back to me? Let me know if anything's unclear, or if I missed anything.

Thanks for your review.

Once milestone 2 gets accepted. I'll get rid of the RC version.

0b - Check `subalfred-core`. `subalfred` is just a CLI wrapper.
0c - GitHub request requires an API key. It's a limitation on the GitHub side. And I updated the `--help` to make it more clear.

In the following parts, I assume people have some experience with Substrate update at the beginning. There are a lot of things that need to do during a version update. It isn't Subalfred's goal to guide people on how to do version updates. But I add some must-know/preset detail/knowledge now. Thanks for pointing that out. Does it make sense now?

2 - I updated the Subalfred book, please check again.
4 - I updated the Subalfred book, please check again.

**Comment by alxs** [comment]
Thanks @AurevoirXavier.

> The `GITHUB_TOKEN` API key must have the privilege of the target repository.

What do you mean by this? No privileges are required other than public repo access.

Also as I pointed out in my notes, doesn't this feature do something else than what was described in the application? The application describes it as "lists the companions that you need to do from substrate/cumulus/frontier/parity-bridges-substrate." However, it currently simply lists the commits between releases.

Could you please submit an amendment to update the deliverable specification? Feel free to include any changes you want to make to the next milestone.

**Comment by AurevoirXavier** [comment]
Thanks.

> Thanks @AurevoirXavier.
> 
> > The `GITHUB_TOKEN` API key must have the privilege of the target repository.
> 
> What do you mean by this? No privileges are required other than public repo access.

You even can do this for the private repo.
For example, you fork the Substrate repo and make it private(for some reason).

> Also as I pointed out in my notes, doesn't this feature do something else than what was described in the application? The application describes it as "lists the companions that you need to do from substrate/cumulus/frontier/parity-bridges-substrate." However, it currently simply lists the commits between releases.

You made some changes on Substrate and you want to apply the changes to Polkadot. Then you need to make a PR to Polkadot to bump the `Cargo.lock`. And that's what I did before. I have worked in this ecosystem for 3 years. So, to my understanding, each commits is a companion.

Also, I want to make this more powerful, but I've discussed this with Basti. Paritytech will refactor the labels later. The earliest time is the new year.

Or could you provide some ideas? What could make it "more like" a companions tracking tool?

I don't want to change my goal. Let me try my best and see if we can make some improvements.

**Comment by alxs** [comment]
Makes sense, feel free to add this to the docs.

> So, to my understanding, each commits is a companion.

Okay, I see what you mean! This probably seems obvious if one is familiar with the Substrate update lifecycle, but is otherwise not obvious.

>  Let me try my best and see if we can make some improvements.

Sure, please let me know when you're done.

**Comment by alxs** [comment]
@AurevoirXavier any updates?

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier any updates?

Sorry, I was busy last month. I will finish it this week.

**Comment by AurevoirXavier** [comment]
> > @AurevoirXavier any updates?
> 
> Sorry, I was busy last month. I will finish it this week.

Sorry, I got COVID last Friday. I have to delay this for a few days.

**Comment by alxs** [comment]
@AurevoirXavier no problem. I hope you feel better soon.

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier no problem. I hope you feel better soon.
Thanks.

Updated. cc @alxs @keeganquigley

**Comment by AurevoirXavier** [comment]
Hi! Any feedback?

**Comment by keeganquigley** [comment]
Hi @AurevoirXavier thanks for making the changes, and thanks for your patience as I got up to speed on this delivery. Everything is looking better now, except for the failing unit test. It took me a bit to get my mind around the GITHUB_TOKEN variable. I now see your note about omitting it for the time being with `export GITHUB_TOKEN=OMITTED`. Using this causes the test to time out instead of fail completely.

I'll accept this for now, but typically we ask that all unit tests pass, so for the next milestone I wonder if there is a way you could refactor the test to mock it or something similar. Either way, being that this is a GH limitation, I'm happy to accept your delivery. Please see my final notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subalfred_2_alxs.md).

**Comment by AurevoirXavier** [comment]
> I'll accept this for now, but typically we ask that all unit tests pass, so for the next milestone I wonder if there is a way you could refactor the test to mock it or something similar.

Because it makes a lot of requests. If you don't have an API key, your IP might be banned.

1. I can create a temporary token for milestone delivery.
2. I will enable the API key requirement. If the request failed, then enable it automatically.

**Comment by RouvenP** [comment]
hi @AurevoirXavier we transferred the payment today.

**Pull request merged**
