### PR TITLE
Create bright_tresury_milestone-3.md

### PR DESCRIPTION
**Pull request by aolszewska**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/251 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the delivery. I started to look into your delivery and noticed that user story 37 seems to be missing in your delivery documentation. Is this on purpose? Also the formatting of the links seems to be a little bit off. Furthermore a few tests are failing for me when I run yarn test [here](https://github.com/bright/bright-tresury/tree/milestone3/www)

**Comment by bufta** [comment]
Thank you @Noc2 for the feedback. Apologies, the lacking user story was just an oversight. We corrected the documentation and the faulty links. We also fixed the failing tests. Hope all's correct now.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the super quick reply. The tests now work. However, I did run into another issue. I selected a different account for the bounty proposer (first account linked to the app) and the curator (second account which I linked). However, when I now try to accept the nomination, I get the error message below (“No injected accounts”). Do you know how to fix this?  
Screenshot from 2022-01-05 09-36-23

**Comment by bufta** [comment]
Hi @Noc2, sorry for the trouble. We are aware that this issue sometimes appears after re-login. The quick solution is to refresh the app and then try again. However, we are working on a solution to fix this. We'll update the repository as soon as we have the fix ready and let you know.

**Comment by aolszewska** [comment]
Hi @Noc2, thanks for your feedback. We have just deployed the fix for the "No injected accounts" error to the testing environment. You can proceed with the testing and should not experience the error again.

**Review by Noc2 — APPROVED** [review]
Thanks for the super quick fix and reply here. I can confirm that everything works now and I’m happy to tell you that the milestone is a pass and I will forward your invoice internally. I know that you are already applying for treasury funding, but independent of it feel free to apply for another grant. Great work!

**Comment by bufta** [comment]
This is excellent news, thank you very much @Noc2 :) we will definitely think about other projects we might apply for through the grant. It was a great experience, thank you and web3 foundation very much for this opportunity!

**Comment by RouvenP** [comment]
hi @bufta, we transferred the payment today. Thanks!

**Pull request merged**
