### PR TITLE
Crowdloan Front End Template delivery

### PR DESCRIPTION
**Pull request by gsieczkowski10clouds**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1211

### CODE REVIEW

**Comment by takahser** [comment]
@gsieczkowski10clouds thanks for the submission of the delivery, I'm currently having a look at it. Regarding the _0c. | Article_ deliverable, the doc is currently private and I don't have access. Hence, I sent a request so please have a look at your inbox.
I'll give you more feedback soon.

**Comment by takahser** [comment]
@gsieczkowski10clouds any update on this?

**Comment by gsieczkowski10clouds** [comment]
> @gsieczkowski10clouds any update on this?

Hi. Sorry for the late replay.
* Access to the github repo with project is now public (we had some problems with global settings).
* Access to the document with prepared article was granted to the requesting account/email.
* Invoice was sent via form.
* Update for application (about Webflow implementation) is in progress - I'm waiting for confirmation from the delivery team which version is actual (removed from the scope or limited implementation) - I should get it soon.

**Comment by takahser** [comment]
@gsieczkowski10clouds thanks, the repo access problem is now resolved.

>  I'm waiting for confirmation from the delivery team which version is actual

I'm not sure what versions you refer to here. Did you submit an amendment PR yet?

**Comment by gsieczkowski10clouds** [comment]
> @gsieczkowski10clouds thanks, the repo access problem is now resolved.
> 
> >  I'm waiting for confirmation from the delivery team which version is actual
> 
> I'm not sure what versions you refer to here. Did you submit an amendment PR yet?

I mean if we should remove webflow implementation or change its scope in our grant aplication.
I will submit an amendment PR when I will have the final decision from the team.

**Comment by takahser** [comment]
@gsieczkowski10clouds FYI I've added the _on hold_ label for now. Once you've decided on your next steps w.r.t. _Webflow implementation_ we can remove it and continue the evaluation.

**Comment by gsieczkowski10clouds** [comment]
@takahser Hi. Sorry for a long delay. We encountered some technical problems with the publication of the Webflow template. Finally it is available on Webflow marketplace as a free to use template. So we are not changing our application and we can continue with the evaluation.

**Comment by takahser** [comment]
@gsieczkowski10clouds okay great, thanks for the note. I'll take another look and get back to you soon.

**Comment by takahser** [comment]
@gsieczkowski10clouds regarding the webflow template and the Contribute CTA button, I think the problem was that you didn't find any CDN for the `@polkadot/api` library that you [use](https://github.com/10clouds/parity-template/blob/dd4258fd0397a1aba139dabd170155de8094ff9e/package.json#L23) in the astro template, right? Did you consider using the [jsdelivr CDN](https://www.jsdelivr.com/package/npm/@polkadot/api)?

**Comment by gsieczkowski10clouds** [comment]
> @gsieczkowski10clouds thanks for your patience. I took a look and summarised my thoughts in [this evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/crowdloan-frontend-template_1_takahser.md).
> 
> Key takeaways are:
> 
> * Astro instead of Gatsby is used here; please amend the contract. This should be easy to pass.
> * Contribute CTA is currently missing on the Webflow template. I understand your reasoning and I'm trying to figure out if there's a workaround. I'll keep you posted.
> * NPM packages should not have critical vulnerabilities.
> * more details in the [general notes section](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/crowdloan-frontend-template_1_takahser.md#general-notes).
> * I found a few small issues in your README, see [this PR](https://github.com/10clouds/parity-template/pull/42).
> 
> Lmk if you have any questions.

1. Astro/Gatsby - PR with the update: https://github.com/w3f/Grants-Program/pull/1686
2. Contribute CTA - I will provide more details in a separate comment.
3. NPM package vulnerabilities - fixed.
4. We have updated the repository with the fixes you suggested in the general notes section.
5. Thank you for that catch.

**Comment by gsieczkowski10clouds** [comment]
In the topic of the CTA button.

The decision to branch with the development of Webflow and Astro versions was made intentionally and agreed upon with David Hawig. The CTA button in Weblow implementation should display all the necessary data to make the contribution possible through the external service:

Screenshot 2023-04-21 at 20 42 53

The main goal was to create a solution that can reach a wide group of users that can benefit from the template. Astro implementation was targeted towards developers who have no problems modifying the source code, can adjust functionalities, upgrade package versions and address potential bugs. Webflow implementation was simplified and prepared for designers who may not have coding expertise. Introducing extensive JavaScript code in Webflow that would integrate with @polkadot/api and manage UI to handle contributions, would require either keeping it inline in the editor or serving it from our external source. Both solutions would introduce additional problems - necessity of handling JavaScript by the designers or maintaining a versioned “library”, locked for eventual user modifications.

Please let us know if you have any further questions or concerns, and we'll be happy to help.

**Comment by takahser** [comment]
@gsieczkowski10clouds okay thanks for elaborating.
@Noc2 can you confirm [above comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/765#issuecomment-1518212162)?

> The decision to branch with the development of Webflow and Astro versions was made intentionally and agreed upon with David Hawig. The CTA button in Weblow implementation should display all the necessary data to make the contribution possible through the external service:

Screenshot 2023-04-21 at 20 42 53

**Review by Noc2 — APPROVED** [review]
Confirmed

**Review by takahser — APPROVED** [review]
@gsieczkowski10clouds thanks for the amendment and the fixes. I [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/crowdloan-frontend-template_1_takahser.md) your delivery.

**Pull request merged**
