### PR TITLE
NFT infrastructure | by walt.id - M1 (final)

### PR DESCRIPTION
**Pull request by philpotisk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1209

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @philpotisk. Can you share a non-public/draft link to the article? You can also send it to grants@web3.foundation if you want to keep it private for now.

**Comment by philpotisk** [comment]
Hi @semuelle, thanks for reviewing our work. The article it's already on it's way to you. All the best, Phil

**Review by semuelle — APPROVED** [review]
Thanks, @philpotisk. I updated the evaluation notes and your milestone is hereby accepted. @Ali-Usama left some change suggestions regarding the UI, but other than that we found no issues. 

Regarding your invoice: the contract lists an Ethereum address and USDC as payment method, but your invoice includes bank details and USD. Could you change the invoice accordingly and resubmit? Alternatively, if you want to be paid in fiat, you would have to amend the contract via pull request and send us your bank details via email for confirmation.

**Comment by semuelle** [comment]
pinging @philpotisk

**Comment by philpotisk** [comment]
Hey @semuelle & @Ali-Usama Thanks for your review and for accepting the deliverable!

Our tech team has looked into the issue and have fixed it. Everything is now working and deployed here https://wallet.walt-test.cloud/

Regarding the invoice: We would like to change the contract so that we can be paid in directly in FIAT to our bank account. Could you let us know to which e-mail address we should send the bank account details for confirmation? (Note that you should already have all information from our invoice.) Also, please let us know if you need anything else. Thanks!

**Comment by semuelle** [comment]
> Regarding the invoice: We would like to change the contract so that we can be paid in directly in FIAT to our bank account. Could you let us know to which e-mail address we should send the bank account details for confirmation? (Note that you should already have all information from our invoice.) Also, please let us know if you need anything else. Thanks!

Please send an email with your bank details to grants@web3.foundation and [amend the contract accordingly](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md?plain=1#L7). This is just to make sure that we are not processing the wrong invoice. Thanks!

**Comment by fededubbi** [comment]
Hi @philpotisk,

Can you please add also our VAT ID below our address?

CHE-322.596.347.

Many thanks,
Federica

**Pull request merged**
