### PR TITLE
Submitting Fennel Protocol M2.

### PR DESCRIPTION
**Pull request by Romulus10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/748

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @Romulus10. We'll look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the delivery. I’m planning to look into this milestone in the coming days. However, I already noticed that the milestone number currently says 1 and also the article which you linked says milestone one in the link. So just to double check, you submitted the second milestone, correct? Could you also update the milestone number?

**Comment by Romulus10** [comment]
> Thanks again for the delivery. I’m planning to look into this milestone in the coming days. However, I already noticed that the milestone number currently says 1 and also the article which you linked says milestone one in the link. So just to double check, you submitted the second milestone, correct? Could you also update the milestone number?

Thank you for pointing this out - I updated those two spots. The deliverables are for Milestone 2.

**Comment by Romulus10** [comment]
Thanks for the response, @Noc2, I just made some changes to address those points.
* Turns out we had an issue with our Github Pages build. I just ran a new one, that link should be available shortly.
* Added an Unlicense file to the fennel-lib repo: 
* I updated the Readme with more complete testing instructions - we had them in our testing guide but they're kind of buried, thank you for pointing that out. It should work on M1, I think the issue you're seeing is that macOS needs you to install the OpenSSL library (and probably LLVM too): https://github.com/fennelLabs/fennel-lib/blob/master/README.md

Thanks again!

**Comment by Noc2** [comment]
And just to add, I got a few warnings, see  https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Fennel_2_Noc2.md#general-notes Maybe you can fix these.

**Comment by RouvenP** [comment]
hi @Romulus10 we transferred the payment today. Thanks!

**Comment by Romulus10** [comment]
> hi @Romulus10 we transferred the payment today. Thanks!

Received. Thank you!

**Pull request merged**
