### PR TITLE
Create tracking_chain-milestone_2.md

### PR DESCRIPTION
**Pull request by FedeC87p**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1915

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@FedeC87p thank you for the milestone delivery. The application worked well but it is possible to improve some documentation and I had some doubts during the evaluation. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tracking_chain_m1_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by FedeC87p** [comment]
Hi, thanks for review, here are the answers below

> Docker
Would be possible to create a docker that configures and run all the application?  

I provided the Docker only for Sql server as it is the most invasive, while the other services are provided with the selfcontained packages of the dotnet framework. But if you need to test them I can also see to release a docker with a ready-to-use solution
  
> Documentation and Testing Guide
Could you explain the Account ID and ProfileGroup ID and how to use the Admin tools?  

Sorry, Account ID and ProfileGroup ID were not visible from the Admin tools, I already released a new version to fix this. Now they are visible in the Details section.  
  
I also updated the page https://github.com/TrackingChains/TrackingChain/wiki/Milestone-2-Guide-to-Demo by adding the "FrontEnd Configuration" section, where there are two configuration examples (the most common ones and which in practice they cover the whole configuration). In that guide he shows how to use AccountId and how to configure new smartccontracts to be used.  
  
  I remain at your disposal for further details and clarifications.

**Comment by FedeC87p** [comment]
Hi,

I just published a guide with instructions to be able to launch all services via docker https://github.com/TrackingChains/TrackingChain/wiki/Docker-Compose

The images are already configured with the test data and the configuration shown in the Step by Step guide.

With this I should have settled all the outstanding points and the review can continue.

 Thank you

**Comment by dsm-w3f** [comment]
@FedeC87p thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tracking_chain_m1_dsm-w3f.md) and now the milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by fededubbi** [comment]
Hi @FedeC87p,

I noticed that you used already in the past the same invoice number.
Could you please update the number for Milestone 2?

Many thanks,
Federica

**Comment by FedeC87p** [comment]
Thanks for reporting @fededubbi , I just sent with the correct number

**Comment by RouvenP** [comment]
hi @FedeC87p we just transferred the payment

**Pull request merged**
