### PR TITLE
shadows network milestone 1

### PR DESCRIPTION
**Pull request by ShadowsNetwork**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by ShadowsNetwork** [comment]
Hi～  any update？

**Comment by mmagician** [comment]
@ShadowsNetwork Hey, we have received your delivery, but haven't yet had a chance to check it. Please bear with us a couple of days more.

**Comment by semuelle** [comment]
Hi @ShadowsNetwork, 
something is missing to get your tests to succeed. When running `cargo test --workspace`, I get 

```
error[E0437]: type `debtreasury` is not a member of trait `auction_manager::Trait`
   --> modules/auction_manager/benchmarking/src/mock.rs:136:2
    |
136 |     type debtreasury = DEBTTreasuryModule;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not a member of trait `auction_manager::Trait`

error[E0433]: failed to resolve: use of undeclared crate or module `prices`
   --> modules/auction_manager/benchmarking/src/mock.rs:138:21
    |
138 |     type PriceSource = prices::Module<Runtime>;
    |                        ^^^^^^ use of undeclared crate or module `prices`

error[E0433]: failed to resolve: use of undeclared crate or module `prices`
   --> modules/auction_manager/benchmarking/src/mock.rs:220:6
    |
220 | impl prices::Trait for Runtime {
    |      ^^^^^^ use of undeclared crate or module `prices`

error[E0433]: failed to resolve: use of undeclared crate or module `loans`
   --> modules/auction_manager/benchmarking/src/mock.rs:243:6
    |
243 | impl loans::Trait for Runtime {
    |      ^^^^^ use of undeclared crate or module `loans`

error[E0433]: failed to resolve: use of undeclared crate or module `prices`
   --> modules/auction_manager/benchmarking/src/mock.rs:260:21
    |
260 |     type PriceSource = prices::Module<Runtime>;
    |                        ^^^^^^ use of undeclared crate or module `prices`

error: aborting due to 5 previous errors

error: build failed
```

Please advise.

**Comment by ShadowsNetwork** [comment]
Hi @semuelle 
there is some useless code. I have deleted and fixed it on develop branch. Please try again

**Comment by semuelle** [comment]
Thanks, @ShadowsNetwork, the tests are fixed. 

One more issue: most of the commits to your main repo are purely for name changes, such as [this one](https://github.com/ShadowsNetwork/shadows/commit/91d48b28ef8d52c60ce715b3622c908aa43c9eed) or [this one](https://github.com/ShadowsNetwork/shadows/commit/bf80d7a27e3df36805afc947c8fbe68d7529a66b). Could you provide some insight into your development process, i.e. whose code you base your implementations on? Based on some of the licenses in your repo I can see you are using some forks, such as open-web3-stack, but there seem to be different code bases coming together.

Thanks.

P.S.: Regarding [this commit](https://github.com/ShadowsNetwork/shadows/commit/f45e16418bba91732606884e5cf4d4b6408dca3b): you are referencing the open-web3-stack repository but changed the author. Since the open-web3-stack is published under Apache2,  you _can_ use the code, but you have to acknowledge the original author and copyright, and state the changes you have made when you republish it.

**Comment by ShadowsNetwork** [comment]
> Thanks, @ShadowsNetwork, the tests are fixed.
> 
> One more issue: most of the commits to your main repo are purely for name changes, such as [this one](https://github.com/ShadowsNetwork/shadows/commit/91d48b28ef8d52c60ce715b3622c908aa43c9eed) or [this one](https://github.com/ShadowsNetwork/shadows/commit/bf80d7a27e3df36805afc947c8fbe68d7529a66b). Could you provide some insight into your development process, i.e. whose code you base your implementations on? Based on some of the licenses in your repo I can see you are using some forks, such as open-web3-stack, but there seem to be different code bases coming together.
> 
> Thanks.
> 
> P.S.: Regarding [this commit](https://github.com/ShadowsNetwork/shadows/commit/f45e16418bba91732606884e5cf4d4b6408dca3b): you are referencing the open-web3-stack repository but changed the author. Since the open-web3-stack is published under Apache2, you _can_ use the code, but you have to acknowledge the original author and copyright, and state the changes you have made when you republish it.

@semuelle Thank you for the reply
Regarding the first question, because our team have done a lot of work before our code base is submitted to github, and the core shadows is already available. So the submission on github seems somewhat irrelevant. For example, in the future, we will rename our token DOS to DOWS, because many projects already use DOS. At the same time, in order to improve development efficiency, we have used some modules of Acala's code base, because in the first milestone, what we have to do is very similar to acala, including basic substrate code and mortgage cryptocurrency assets to generate stable coins Wait. But at the same time, we made some changes. For example, acala does not support collateralizing the underlying token of the parachain to generate stablecoins, while we mainly generate our stablecoin xUSD by collateralizing our underlying token DOS.
Of course, the different development focus of shadows and other parachains is mainly at Milestone 2. We will complete the code related to synthetic assets at Milestone 2, and also include the cross-chain with Ethereum. You can refer to our architecture diagram:

image

We have changed the author's modified module back, and marked in the module code which modules are implemented with reference to acala: [this commit](https://github.com/ShadowsNetwork/shadows/commit/4b0175e7dead12236c184bb23d1d1daf995f6b15) and [this commit](https://github.com/ShadowsNetwork/shadows/commit/83d8b4a47f8d990ffb5afff075f5b16a3dab745e) . This is our negligence. Thank you for your correction.

**Comment by semuelle** [comment]
Hi @ShadowsNetwork, thanks for the reply and the modifications. 

Since Acala's code is open sourced, it is of course perfectly fine to reuse their code. It seems that you have to deal with two different licenses here, though. Both Apache 2 and GPL3 require you to include a copyright notice and a list of changes made to the code. GPL3 also requires you to publish it under the same license. If you haven't done so, could you add these and post a link to the licenses and list of changes here? 

Here are the links I used:

1. https://github.com/AcalaNetwork/Acala/blob/master/LICENSE
2. https://github.com/open-web3-stack/open-runtime-module-library/blob/master/LICENSE
3. https://choosealicense.com/licenses/gpl-3.0/
4. https://choosealicense.com/licenses/apache-2.0/

**Comment by ShadowsNetwork** [comment]
Hi @semuelle, thanks for the reply.
We added a [NOTICE file](https://github.com/ShadowsNetwork/shadows/blob/develop/NOTICE) to the project root directory to disclose the use of open source software by Shadows, including copyright notice and a list of changes required by Apache 2 and GPL3.
This document was inspired by: https://infra.apache.org/licensing-howto.html
In addition, regarding the acceptance of Milestone 1, do you need us to provide other help to speed up the progress??

**Comment by semuelle** [comment]
Thanks for that. Could you add [such a reference] to the mintx module as well?

**Comment by ShadowsNetwork** [comment]
Thinks semuelle, already added

**Comment by ShadowsNetwork** [comment]
> Thanks for that. Could you add [such a reference] to the mintx module as well?

Thinks semuelle, already added

**Comment by semuelle** [comment]
Thanks for following up on the licensing, @ShadowsNetwork. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/c5d1db642b0d94ecf6de158ae5d380a0aa575c9c/evaluations/shadows-network_1_semuelle.md) and your milestone is hereby accepted.

I will forward your invoice for processing.

**Comment by ShadowsNetwork** [comment]
> Thanks for following up on the licensing, @ShadowsNetwork. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/c5d1db642b0d94ecf6de158ae5d380a0aa575c9c/evaluations/shadows-network_1_semuelle.md) and your milestone is hereby accepted.
> 
> I will forward your invoice for processing.

@semuelle 
I see that the submissions have been merged, thank you very much for your follow-up.
At the same time it means we can add the badge of web3 foundation grants right?

**Comment by semuelle** [comment]
correct.

**Comment by RouvenP** [comment]
hi @ShadowsNetwork we just sent a test transaction of 0.001. Could you confirm if received?

**Comment by ShadowsNetwork** [comment]
Received!

RouvenP <notifications@github.com> 于2021年3月5日周五 上午2:34写道：

**Comment by ShadowsNetwork** [comment]
> hi @ShadowsNetwork we just sent a test transaction of 0.001. Could you confirm if received?

@RouvenP 
Hello, when will the remaining funding be transferred?

**Comment by ShadowsNetwork** [comment]
> correct.

@semuelle 
Can you comment on our project in one sentence? This is very meaningful to us, thank you! !

**Comment by semuelle** [comment]
Sorry, can you clarify what you are asking for?

**Comment by ShadowsNetwork** [comment]
> Sorry, can you clarify what you are asking for?

can we get a quote from w3f about our developing work in terms of its novelty or something like that?

**Comment by alxs** [comment]
Hi @ShadowsNetwork. Your initial delivery has become a topic of controversy over the last few days as it evidently disregarded the rights of other teams to their intellectual property. Moreover, after further review we've established that your project still does not comply with the appropriate licenses.

Since we're in the process of tightening our policies to take such matters much more seriously, I regret to inform you that we will need to terminate the agreement in accordance with our [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md). 

Below is a non-exhaustive list of the relevant infringements:

- Acala's code is under GPLv3, which requires that
  - if it is reproduced or modified, the project it becomes part of is licensed under the same conditions. However, your project is currently under Apache 2.0.
  - it must carry prominent notices stating that you modified it, which you initially failed to comply with.
- The ORML Library is under Apache 2.0, which requires that
  - you retain all attribution notices, which you initially failed to comply with.
  - you must cause any modified files to carry prominent notices stating that you changed the files, which you have failed to comply with for all affected files.

We ask you to please cease usage of the grants badge and to take down any articles you may have published in connection with the grant. Nevertheless, we would like to thank you for your interest in the grants program and for your contributions to the ecosystem. 

These are all the measures we will take, but we urge you to fix these issues ASAP as a sign of respect for other teams' work and in order to avoid the possibility of a [DMCA takedown notice](https://github.com/contact/dmca) being filed against you.

**Comment by ShadowsNetwork** [comment]
Dear @alxs,
 
We are extremely sorry, and we sincerely apologize for the impact caused by our team’s mistakes during the grant process. At the same time, we hope to have a positive communication with you.
 
Regarding improper use of words: When we published the English version of the announcement, there were some errors in the title. It is described as “Shadows Network Joins the Web3 Foundation”,which is a wrong expression and a mistake in the translation process. What we posted in the Chinese community is “We have completed the first milestone acceptance”. Because most of our team members speak Chinese as their native language, we first wrote the content in Chinese and then translated it into English. The translator might have misunderstood the meaning in Chinese, and for that reason some translation errors just occurred. We are very sorry for this mistake and have removed all related articles and statements.

Regarding code licenses: we have been actively communicating with Auditors and made changes based on his feedback,which can be seen from our code commit record, such as: [this commit ](https://github.com/ShadowsNetwork/shadows/commit/4b0175e7dead12236c184bb23d1d1daf995f6b15) and [this commit](https://github.com/ShadowsNetwork/shadows/commit/83d8b4a47f8d990ffb5afff075f5b16a3dab745e). At the same time, we also added the [NOTICE file](https://github.com/ShadowsNetwork/shadows/blob/develop/NOTICE) required by Apache 2 and GPL3 to comply with the open source agreement. Of course, if there is still something to pay attention to,please point it out, we will get down to fix. We believe we can keep communication and make adjustments to avoid any copyright issue. 

Regarding advance announcement: We publicized the community before receiving the final funding, which is inappropriate. However,we also specifically asked Auditors if we can already use the web3 foundation's badge and make the news public, and we got an affirmative answer. We wonder if there was any miscommunication there. In any case, it is also our fault that we do not fully understand the process and standard operation. We apologize again. We have now removed all related articles and statements,and we feel sorry about that. We just perceived that passing the grant acceptance is a great honor for our team, so we can't help but share this good news with our community.
 
In any case, we are deeply sorry for our mistakes. Meanwhile, for any improper operation in the process of promoting the grant news due to our lack of understanding of the grant process, we hereby sincerely apologize.

Sincerely,
Shadows Network Team

**Comment by alxs** [comment]
See my last message for unresolved issues.

There was no miscommunication here since we do usually award teams these rights upon acceptance of the first milestone, this is only in relation to the termination. In this regard, I apologise for any inconveniences the timing from our side may have caused since it took us some time to look into the situation in detail.

Many thanks for your understanding and we also hope to maintain a positive relationship.

**Pull request merged**
