### PR TITLE
Submit php-rpc-lib follow up m1 

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1488

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/php-rpc-lib-follow-up_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by gmajor-encrypt** [comment]
@dsm-w3f * 
Thanks for your review, I have made the following modifications
* License: License updated, Delivery added License link
* Documentation: Modified the readme syntax error. Since the extension is installed on versions above php 8.0 by default, I think this does not need to be marked
* Test : The test failed because there is no balance in the account, and I just transferred it in.

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the explanations and improvements. There are some issues with the installation scripts and tests that need to be addressed. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/php-rpc-lib-follow-up_1_dsm-w3f.md) for details and let me know when I can continue with the evaluation.

**Comment by gmajor-encrypt** [comment]
@dsm-w3f Thanks for your review.I want to discuss this part

About ***Need improvements in the installation steps***
As a PHP lib, I don't think it is necessary to solve the problem of other dependent libraries of PHP.

In addition, as a lib, it should be referenced by other projects, so execute this directly. 
```
composer require gmajor/php-substrate-api
```
This is not correct either.

**Comment by gmajor-encrypt** [comment]
@dsm-w3f 
Thanks for your evaluation
I improved the documentation for **installation** and added contract calls tests for more complex scenarios.
If there is any problem, please let me know

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the improvements and fixes. We are almost finishing this evaluation. The installation instructions still need improvements. Please see the details in [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/php-rpc-lib-follow-up_1_dsm-w3f.md). Let me know when you addressed this last point to finish this evaluation.

**Comment by gmajor-encrypt** [comment]
@dsm-w3f Hi,
Thanks for your evaluation.
I have made changes to the document, please help to review again

**Comment by dsm-w3f** [comment]
@gmajor-encrypt thank you for the fix. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great work!

**Comment by gmajor-encrypt** [comment]
@dsm-w3f Great, Thanks for your evaluation.

**Comment by dsm-w3f** [comment]
@gmajor-encrypt Did you submit an invoice for this delivery? I couldn't find it. If you already submitted it, can you inform me which day you did it? Otherwise, can you submit it again using the invoice form?

**Comment by gmajor-encrypt** [comment]
@dsm-w3f Yesterday, March 7th, I just submitted it again. You can find it again

**Comment by dsm-w3f** [comment]
@gmajor-encrypt I got the invoice now. Unfortunately, we are not making payments in USDT anymore. Can you please change the currency in the invoice for one of these USDC/DAI/BTC?

**Comment by gmajor-encrypt** [comment]
@dsm-w3f Thanks. I resubmit my invoice again

**Comment by RouvenP** [comment]
hi @gmajor-encrypt we transferred the payment today.

**Pull request merged**
