### PR TITLE
Delivery: ArtZero InkWhale - Milestone 1

### PR DESCRIPTION
**Pull request by nad128668**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1342 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @nad128668, thanks for the delivery. Someone of the team will take care of it soon.

In the meantime, I opened a PR to fix the application document format, so all the checks will pass.

**Comment by nad128668** [comment]
@0xCaso I added 2 milestones in this PR. Is it ok?

**Comment by semuelle** [comment]
> I added 2 milestones in this PR. Is it ok?

That's generally okay, just keep in mind that we only pay when a milestone is merged, so it might take a little longer to review and approve both.

**Comment by dsm-w3f** [comment]
@nad128668 thank you for the milestones submission. Please see the evaluation documents for milestones [1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_1_dsm-w3f.md) and [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by nad128668** [comment]
Thanks for your feedbacks @dsm-w3f 
Lets focus on Milestone 2 for now. Here is our answers and fixes for your evaluation doc.

### Contract
1. We forgot to merge our work to main branch, so thats why you dont see the files in the test folder. Its fixed now
2. The test guide is at **https://github.com/InkWhale-net/contracts/blob/main/tests/readme.md** 
3. The correct syntax to build contract is `cargo +nightly contract build --release` not `cargo build --release`
4. Instruction for contract build is at **https://github.com/InkWhale-net/contracts/blob/main/readme.md** 
5. We removed all warnings from clippy

### Backend
1. The guide is at https://github.com/InkWhale-net/backend/blob/main/readme.md

## Frontend
1. We merged the main branch to latest version 
2. Please use **yarn** instead of **npm**
3. The guide to run FE is at **https://github.com/InkWhale-net/frontend/blob/main/README.md** Please change **REACT_APP_API_BASE_URL=https://api.inkwhale.net** to localhost when you run the backend api service

## License
License file location has been updated

**Comment by nad128668** [comment]
> > I added 2 milestones in this PR. Is it ok?
> 
> That's generally okay, just keep in mind that we only pay when a milestone is merged, so it might take a little longer to review and approve both.

Thanks We should then do it one by one, we want to focus on milestone 2 for now because the work load is much less than milestone 1. Should I remove the milestone 1 file from the PR?

**Comment by dsm-w3f** [comment]
> Should I remove the milestone 1 file from the PR?

I think you can maintain milestone 1 since, as far as understood, I will need M1 deliverables to evaluate M2. Usually, we don't evaluate milestones out of order.

**Comment by nad128668** [comment]
Milestone 1 and 2 actually are 2 separate project, so milestone 1 doesnt required to process milestone 2. Next time, I will create 2 grant proposals instead of 1.

**Comment by nad128668** [comment]
@dsm-w3f Apologize for late update, we have to move our backend code from private git repo to public repo and hide all private information there. Also a lot of documents have also been moved from private repos to public repos.

We have changed the base branch for Frontend and Contract repo so you are always in the correct branch. The errors you saw was on different branch other than the branch we are currently working on.

We have removed proxy contract as it is not needed. We use update code hash inside the contract for upgradability
Please check the latest commit of milestone 1 for updated information as new links are now added and continue the evaluation.

Kind Regards

**Comment by dsm-w3f** [comment]
@nad128668 thank you for the improvements and fixes. I reevaluated the M1 and updated [the eval document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_1_dsm-w3f.md). Please take a look and let me know when I can continue this eval.

**Comment by nad128668** [comment]
@dsm-w3f Thanks for your feedbacks, I have a quick question:
When you run the test, do you use the new contracts you created yourself or the contract we have in the code?

**Comment by dsm-w3f** [comment]
@nad128668 I followed strictly the installation instructions of the system. In the case of the API (https://github.com/ArtZero-io/backend/blob/main/Api/README.md), there is no indication to change the addresses of the contract in the code or how to do it. If this step is needed (probably it is), please add instructions to the installation tutorial to do it.

**Comment by nad128668** [comment]
We are creating .env in local test environment for you to make it easier. The keys we included in previous doc are not meant to use. Apologize as this is our first grant application so we dont know the process. I will update you as soon as possible.

**Comment by nad128668** [comment]
Hi @dsm-w3f,
1. We added instructions in FE and BE to generate .env file for you to run. Because it contains sensitive Key data, so we encrypted it. If possible, please contact me via Telegram: nad010286, I will give you the password for this action.
```
cd frontend-react
chmod +x setup_env_fe.sh.x
./setup_env_fe.sh.x
```

```
cd backend
chmod +x setup_env_be.sh.x
./setup_env_be.sh.x
```

2. Contract is now fixed the clippy issue.

3. To display NFT images and Metadata, the database must contain the cached images on CloudFlare and cached JSON on local computer. Please also contact me via Telegram, I will send you the database table data + JSON files.

Kind Regards

**Comment by nad128668** [comment]
We also fixed the Az_events_collector issue you have seen

**Comment by dsm-w3f** [comment]
@nad128668 thank you for the explanations. There is one problem with it, we are working with open-source software that anyone should be able to download and use without passwords and sensitive information. Can you provide a way to run that without sensitive information or services that are running in your accounts? A tutorial on how to set up the services needed and how to configure .env would be enough for this I think.

**Comment by nad128668** [comment]
@dsm-w3f please check, we have updated readme in backend and frontend with better instructions for you

**Comment by nad128668** [comment]
as database need to cache the images and json to be shown, you can create new collection and NFT to see them but for existing collections and NFTs you will need the file and database import from us

**Comment by dsm-w3f** [comment]
@nad128668 I did a first round of tests using the application connected with the testnet provided. I still need to test it using a local substrate node. In general, the tests went well although I couldn't use the admin profile. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_1_dsm-w3f.md) for details. Let me know when I can continue the evaluation.

**Comment by nad128668** [comment]
@dsm-w3f Building Aleph Zero local node for testing is quite complex can we write instructions for you to deploy contract on Aleph Zero Testnet including how to add to FE and BE so you can test FE BE locally using your own deployed contracts?

**Comment by hnnam0906** [comment]
@dsm-w3f : We add contract deployment, update abis, contract addresses for FE and BE at https://github.com/ArtZero-io/Contracts/blob/feature/ink-4-version/contract_deployment_and_update_addresses_abis.md 

The admin account is the contract deployment account, you can use this account to check admin functions on FE.

With regards to API, you should interact with FE first which is guided in https://docs.artzero.io/ then check API return later.

Should you have any questions, please kindly let us know. Thanks.

**Comment by dsm-w3f** [comment]
@hnnam0906 and @nad128668 thank you for the answer. I followed the [guide provided](https://github.com/ArtZero-io/Contracts/blob/feature/ink-4-version/contract_deployment_and_update_addresses_abis.md), which is complex and full of manual interaction with contracts and source code. I expected that kind of interaction was only for deploying the contracts of the application and after that, the user could create collections, NFT, and so on using the GUI of the system. However, to create and launch NFTs, interaction with code and contracts is also needed. The user will not have access to the source code (js scripts) to update contract addresses and also will probably not want to interact with contracts directly. I think this problem may be solved with the delivery of Milestone 2. Can you explain your how you plan to deal with that?

I also had some problems showing up the PMP project in the launchpad. After creating the project, it doesn't show up in the list. I figure out this in step 3 of the Check PMP collection on FE. Could you assist with that? These are the contract addresses used in the testnet:

Profile=”5GvP4WmwbCyzyugkASVhpoG8SiYZY7EJ5TXFvbVjncAS5Qpi”
psp34_standard=”5EujQLp8mCVModK2wXAbHn4htRpVMupHeGcPvJv2PcqpnqzW”
launchpad_manager=”5DGuXLcmg17ZPDCjLTNSmXu6MN5PyygshTHCn9uSuq8Ze28Y”
collection_manager=”5DWF2ff6dxvny4p3wca8BeZ4azyy66pfdjPuuVYCzo4P7oF4”
psp34_lauchpad_standard=”5EHW8JD7ej7eQDSo5MBsajoreNsHxeKf5Z1pFsSmvGJvDHaz”
staking=”5Gk3M2tAkhat7rvkftxo14kPVie3H5yFkUwjfip1hQHqNP2f”
marketplace=”5HjjDknqhbhbNcprDpezAmXDi3ziQB8EiNcLBCDR2wVskZ5x”
projectPMP=”5GnMb7GQg8z8EZ1xrABrHrmNxiBaXTPCjnwH3R7SQx8iDvyt”

**Comment by hnnam0906** [comment]
Dear @dsm-w3f ,
Thanks for your quick response.

For the launchpad, our initial design is to target to projects using off-chain data which have a large number of NFTs and most of creators are familiar with creating collections by code than doing manually. You know it is hard to create a large collection of 10k NFTs manually. Then we support them to run the js script as long as they provide all resources mentioned in our guide (image folder, json folder, image and json ipfs link). 

For normal or individual person, we has the simple mode in marketplace where they can easily create a collection of small number of NFTs just by using GUI to fill in information, upload NFT images and all data will be on chain (don't need to provide ipfs links).

I updated step 3 of the Check PMP collection on FE to show up PMP project in launchpad as requested. 

Please kindly review and look forward to hearing from you.

**Comment by dsm-w3f** [comment]
@hnnam0906 and @nad128668 thank you for your answer. We are almost finishing this evaluation (M1). Just small errors remain and the automated test cases suddenly stopped working. See [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ArtZero_InkWhale_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by hnnam0906** [comment]
@dsm-w3f,

**Documentation**
I use the Polkadot.js wallet and can deploy contracts. Can you provide more detailed info or which contracts have the deployment issue with this wallet? May i ask which version of Polkadot.js wallet extension on Chrome you are using? I'm using version 0.44.1.

**Frontend**
We updated FE, can you interact with collection again?

For the royalty percentage, we don't allow editing once the collection is created.

Regarding MY NFTs and MY Stakes tests, do you mean the testcase ids mynft_001 and  mystake_001? As said in the tests, by default, our FE will list all NFTs, there is no "All filter" option.  

**Automated tests**
The blockchain changed the gas limit (the proofsize is changed). I updated the automated tests in accordance with this change. 

Please kindly check and advise if you need anything. Thanks

**Comment by dsm-w3f** [comment]
@hnnam0906 thank you for the improvements and fixes. Now all parts of the Milestone 1 (M1) worked well. This milestone is approved. If you want you can remove the M2 from this PR and open a new one with M2. In this way, we would be able to pay M1 besides M2 is not accepted yet. Otherwise, if you think that are only small adjustments in M2 and could wait for both to be accepted to receive for them I'll continue the evaluation for M2 in this PR. Let me know what is your preference. Anyway, great job in M1. There are some adjustments needed in M2, let me know when I can continue M2 evaluation.

**Comment by dsm-w3f** [comment]
@nad128668 if you want to move M2 to another PR, please remove the M2 delivery file from this one and open a new PR with it. Did you have any advances in the technical requests from M2 evaluation? Just to know if we can continue that.

**Comment by nad128668** [comment]
Hi @dsm-w3f I have remove M2 from this PR. I will create another PR and update the status from previous M2 Evaluation.

**Comment by fededubbi** [comment]
Hi @nad128668,

I noticed that on your invoice is missing both the currency and payment address.
Can you please add both and resend?

Many thanks,
Federica

**Comment by nad128668** [comment]
Hi @fededubbi 
I have submitted the new invoice for the milestone with $ currency and Polkadot address.

thanks

**Comment by nad128668** [comment]
Hi @fededubbi 
do you have any update on the payment? Thanks

**Comment by RouvenP** [comment]
hi @nad128668 hi @nad128668 we transferred the payment today.

**Comment by nad128668** [comment]
Hi @RouvenP I havent seen the amount in my account yet.

**Pull request merged**
