### PR TITLE
YieldScan Phase 2 - Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by prastut**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/373

### CODE REVIEW

**Comment by saumyakaran** [comment]
Hi @mmagician,

I just wanted to check with you to see if there's any updates on the review or if there is anything that I can do to help with the review process.

I know it isn't in our place to ask for an update given the insane delay in shipping out the milestone (sincerest apologies for that 😓).

But, last month we saw a growing trend in the staking volume on YieldScan compared to the previous few months (17.5k KSM and 9.5k DOT staked for August) and wanted to leverage this momentum to open the gates for more people to use the new version of YieldScan 😄

Looking forward to hearing from you soon.

Thanks 🙏

**Comment by mmagician** [comment]
@saumyakaran I've just started looking at your delivery and hope to provide feedback by the end of the week.

**Comment by mmagician** [comment]
@saumyakaran @prastut I've done the first round of evaluation in this [draft PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/270). You can comment on the points I raised directly there in the PR. Let me know once you've addressed them all so I can have another look! Also, in case of any questions just ping me.

**Comment by saumyakaran** [comment]
Thanks @mmagician 🙏!

We'll get right on it. I'll ping you once we're done.

**Comment by sahilnanda1995** [comment]
Hi @mmagician,

We have pushed changes to the repos as per your advice and have commented on the questions you raised, we believe it's ready for review again. Let us know if there are any more questions or any changes required. 

Looking forward to hearing from you soon😊

**Comment by sahilnanda1995** [comment]
Hi @mmagician,

Just wanted to let you know that I have updated(added links and more detail to the respective changes) the comments on this [draft](https://github.com/w3f/Grant-Milestone-Delivery/pull/270).
Also, here’s a list of direct links to the tutorials/guides added on the platform:
- Articles links
  - [Getting started](https://intercom.help/yieldscan/en/articles/5341271-take-your-first-steps-choose-your-wallet-create-your-crypto-account-and-add-funds)
  - [I have my funds on an exchange, how can I stake with YieldScan?](https://intercom.help/yieldscan/en/articles/5428867-i-have-my-funds-on-an-exchange-how-can-i-stake-with-yieldscan)
  - [How to check which accounts on polkadot{.js} wallet are imported through a hardware wallet?](https://intercom.help/yieldscan/en/articles/5353515-how-to-check-which-accounts-on-polkadot-js-wallet-are-imported-through-a-hardware-wallet)

- Videos:
  - [How to import ledger account to polkadot-js browser extension](https://youtu.be/KjgWehjRWek)
  - [Introduction to secure staking on Polkadot with YieldScan](https://www.youtube.com/watch?v=fd9wDFD1R_g)
  - [How to create an account using the polkadot{.js} browser extension](https://www.youtube.com/watch?v=NlUxkSkFH2U)

**Comment by mmagician** [comment]
I've had another look at your milestone, and successfully managed to stake some funds with Ledger & a separate controller account, it's really cool!

Congratulations on finishing this milestone. You can find full evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/yieldscan_1_mmagician.md)
Please especially note the last point about derived accounts: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/yieldscan_1_mmagician.md
For testing purposes this was fine for me, but would be great to actually enable controlling the funds from a derived account.

**Comment by prastut** [comment]
Hey @mmagician! Thank you so much for investing your valuable time in YieldScan! More than grateful <3

We recently published all of our updates in a medium blog here: 
https://twitter.com/YieldScan/status/1439952078927958020?s=20

Some followup questions to you: 

- Who can we get in touch so that we can get this post retweeted through official Polkadot and Kusama twitter channels? 
- Regarding milestone payouts, can we get a soft ETA on when it will be paid out?

**Pull request merged**
