### PR TITLE
Add CoinFabrik_On_Ink_Integration_Tests-2

### PR DESCRIPTION
**Pull request by valeriacaracciolo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1980 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @valeriacaracciolo we will take a look at it in the next couple of days.

**Comment by valeriacaracciolo** [comment]
Thank you @keeganquigley We look forward to the review. Best,

**Comment by valeriacaracciolo** [comment]
Hello, we noticed some failing checks with our PRs. We are working on resolving these issues and we estimate it should be solved by the end of next week.

**Comment by keeganquigley** [comment]
Thanks for the updates @valeriacaracciolo here you can find my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CoinFabrik_On_Ink_Integration_Tests-2_1_keeganquigley.md). I'm happy to pass the milestone and great job on the completion of the grant!

**Comment by valeriacaracciolo** [comment]
> Thanks for the updates @valeriacaracciolo here you can find my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CoinFabrik_On_Ink_Integration_Tests-2_1_keeganquigley.md). I'm happy to pass the milestone and great job on the completion of the grant!

Thank you for your evaluation @keeganquigley !

**Comment by RouvenP** [comment]
hi @valeriacaracciolo we just transferred the payment

**Pull request merged**
