### PR TITLE
add xNFT_milestone1.md

### PR DESCRIPTION
**Pull request by anshulWeb3**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grant-Milestone-Delivery/pull/984

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @anshulWeb3. Thanks for the delivery. Could you explain why each of the changes to the NFT pallet were necessary? I know that there are some open issues with XCM transfers of NFTs, but ideally we'd be working against the stock pallet.

**Comment by anshulWeb3** [comment]
Hi @semuelle . We have tightly coupled NFT pallet with xNFT pallet so we need to access some of its default implementations and structs that are private in xNFT pallet and made them public, that are:
     a) create_delete_collection.rs file which contains all the logic for creation and deletion of NFTs
     b)  CollectionDetails, https://github.com/antiers-solutions/xNFT/blob/f4b5a9387a24bfc4be0fd4dc79872a07902a22bb/nfts/src/types.rs#L134, https://github.com/antiers-solutions/xNFT/blob/f4b5a9387a24bfc4be0fd4dc79872a07902a22bb/nfts/src/types.rs#L157 structs removed super from them to access them in xNFT pallet.

**Comment by anshulWeb3** [comment]
Hi @semuelle . To deliver the functionality of cross chain NFT transfer we had to use some of the existing implementation. As the NFT and xNFT pallet are tightly coupled we need to use its default implementation and structs that were private in NFT pallet. To make them accessible in our pallet we have changed its access to public. 
Functions changed:
a) Create_delete_collection.rs: this file code was reused to create and delete the NFTs with some modifications of access specifier.
b)  CollectionDetails:- https://github.com/antiers-solutions/xNFT/blob/f4b5a9387a24bfc4be0fd4dc79872a07902a22bb/nfts/src/types.rs#L157,
 ItemDetails:- https://github.com/antiers-solutions/xNFT/blob/f4b5a9387a24bfc4be0fd4dc79872a07902a22bb/nfts/src/types.rs#L134,
 CollectionMetadata:- https://github.com/antiers-solutions/xNFT/blob/f4b5a9387a24bfc4be0fd4dc79872a07902a22bb/nfts/src/types.rs#L157 
structs removed super from them to access them in xNFT pallet.

Please refer to our readme (https://github.com/antiers-solutions/xNFT/blob/master/pallet-xnft/README.md) and technical docs (https://github.com/antiers-solutions/xNFT/tree/master/pallet-xnft/docs) for better understanding.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the update, @anshulWeb3. The reason I am asking about these changes is that I expected your pallet to work with the `FRAME` NFT pallet. Not a custom one. These changes mean that the xNFT pallet is of no use to any chain using the FRAME pallet. You are also referencing "[_the_ NFT pallet](https://github.com/w3f/Grants-Program/blob/master/applications/xNFT.md#this-xnft-pallet-will-be-tightly-coupled-with-the-nft-pallet-in-substrate)" in your application:

> This pallet will not be able to transfer any NFT that is not registered using the NFT pallet for Substrate

Also:
- Can you add a license to the repo (https://github.com/antiers-solutions/xNFT)? I see that Apache 2.0 is mentioned [here](https://github.com/antiers-solutions/xNFT/blob/103f52bc742cc951341951c058bb4b3e15ca6f2e/pallet-xnft/src/lib.rs), but it's useful to have a global repo license. 
- Please provide a Dockerfile as outlined in the application. The prerequisites listed in the user guide are quite complex, so having a Dockerfile to automate at least some of these steps would be extremely helpful.

**Comment by anshulWeb3** [comment]
Hi @semuelle , thank you for your feedback.
- While strategizing the tasks, we have also planned to do it without the changes in NFT pallet but as we proceeded further with the development we realized that we cannot access some of the structs and modules of NFT pallet because of access restriction. Therefore, we had to make them public in order to use them within our pallet.
- We are aware that having a docker file is necessary but in our scenario we require a relay parachain environment which is not possible with docker for now, but we can provide you with a docker file of a parachain with our implemented code along with the required versions of rust and substrate. We'll add the needed files to the repository by Monday. 
- As for the Licence, it has been added to the https://github.com/antiers-solutions/xNFT.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @anshulWeb3. Sorry for the late reply. 
[Trappist](https://github.com/paritytech/trappist) actually contains a relay chain and three parachains with HRMP channels between them for local testing. You could you provide a tutorial how to integrate the pallets into it instead of just listing all that as a [prerequisite](https://github.com/antiers-solutions/xNFT/blob/master/pallet-xnft/docs/user_guide.md#prerequisites).
However, the bigger issue is that the pallet was supposed to work with the stock NFT pallet. You pointed [this](https://github.com/w3f/Grants-Program/pull/1798#issuecomment-1597044113) and the fact that [you would have to wait for changes to the pallet](https://github.com/w3f/Grants-Program/pull/1798#issuecomment-1598487429) out yourself. I'm sure you are aware that this pallet is integrated into the runtime of several parachains today. It seems highly unlikely to me that anyone would switch to your fork to enable NFT cross-chain transfers. Therefore, I must insist that the pallet be compatible with the FRAME pallet, not just a fork of it.

**Comment by anshulWeb3** [comment]
Hi @semuelle , we understand your concern, we have added a testing branch that contains files from the trappist repo and the name of this repo is `trappist`. Follow this [link](https://github.com/antiers-solutions/xNFT/tree/trappist).  Follow the readme for help on setup. Meanwhile we are working on integration with the FRAME NFT pallet.

**Comment by semuelle** [comment]
Thanks for the update, @anshulWeb3, but unless the xnft pallet works with the stock NFT pallet, there is no point in continuing this milestone review.

**Comment by semuelle** [comment]
@anshulWeb3, the extent of changes made to the pallet is irrelevant. What matters is that your pallet is compatible with the original FRAME pallet. The necessity to wait for changes to be made to the pallet has been pointed out by multiple people in your application PR. Your responses also indicate that you were aware at the time. 

A cross-chain NFT pallet that's incompatible with the FRAME NFT pallet is not of interest. Please let me know how you would like to proceed. But I recommend we close this PR and you revisit the milestone when the necessary changes have been made upstream.

**Comment by semuelle** [comment]
I am closing this delivery due to inactivity. Please let me know if you want to continue working on it.

**Pull request closed without merging**
