### PR TITLE
Delmonicos Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by lumena-tech**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the USD payment account provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the second delivery. As always, we'll check it as soon as we can!

**Comment by semuelle** [comment]
@lumena-tech, could you remove the milestone 1 doc from your pull request? It was already merged a while ago. Ideally, please use a more recent fork of our repo.

**Comment by adetante** [comment]
@semuelle thanks for your feedback. Can we remove this PR, and create a new one based on an up-to-date fork of your repo?

**Comment by mmagician** [comment]
@adetante Yes sure, go ahead with a fresh one. I'll close this for now.

**Pull request closed without merging**
