### PR TITLE
submit the EightFish Milestone 2 delivery.

### PR DESCRIPTION
**Pull request by miketang84**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1407.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @miketang84 someone will take a look at it shortly.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @miketang84. I am looking through your delivery currently. The `build_docker.sh` script is failing with the following error message. Could you check what the issue might be? 

```sh
❯ ./build_docker.sh
[+] Building 8.7s (10/14)                                                                                                      
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 2B                                                                                           0.0s
 => [internal] load build definition from FirstStage.Dockerfile                                                           0.0s
 => => transferring dockerfile: 633B                                                                                      0.0s
 => [internal] load metadata for docker.io/paritytech/ci-linux:production                                                 0.0s
 => [ 1/10] FROM docker.io/paritytech/ci-linux:production                                                                 0.0s
 => [internal] load build context                                                                                         0.1s
 => => transferring context: 1.23MB                                                                                       0.0s
 => [ 2/10] WORKDIR /eightfish                                                                                            0.0s
 => [ 3/10] COPY . .                                                                                                      0.1s
 => [ 4/10] RUN rustup target add wasm32-unknown-unknown --toolchain nightly                                              0.5s
 => [ 5/10] RUN rustup target add wasm32-wasi                                                                             3.3s
 => ERROR [ 6/10] RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/l  4.7s
------                                                                                                                         
 > [ 6/10] RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/:    
#0 2.593 Step 1: Downloading: https://github.com/fermyon/spin/releases/download/v1.1.0/spin-v1.1.0-linux-amd64.tar.gz          
#0 4.042 Done...                                                                                                               
#0 4.042                                                                                                                       
#0 4.043 Step 2: Decompressing: spin-v1.1.0-linux-amd64.tar.gz                                                                 
#0 4.064 crt.pem
#0 4.064 spin.sig
#0 4.064 README.md
#0 4.065 LICENSE
#0 4.065 spin
#0 4.556 ./spin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./spin)
#0 4.556 ./spin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./spin)
------
FirstStage.Dockerfile:12
--------------------
  10 |     
  11 |     # install third tools
  12 | >>> RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/
  13 |     
  14 |     RUN cd subnode && cargo build --release
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/" did not complete successfully: exit code: 1
```

Also, `cargo test` in the `subnode` directory fails with

```sh
❯ cargo test
   Compiling librocksdb-sys v0.6.1+6.28.2
   Compiling eightfish-runtime v4.0.0-dev (/deliverables/eightfish/eightfish/subnode/runtime)
   Compiling rocksdb v0.18.0
   Compiling kvdb-rocksdb v0.15.2
   Compiling sc-client-db v0.10.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.26#e8a7d161)
error: failed to run custom build command for `eightfish-runtime v4.0.0-dev (/deliverables/eightfish/eightfish/subnode/runtime)`

Caused by:
  process didn't exit successfully: `/deliverables/eightfish/eightfish/subnode/target/debug/build/eightfish-runtime-641edbc2b71e4ea0/build-script-build` (exit status: 101)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: RUSTFLAGS="-C link-arg=--export-table -Clink-arg=--export=__heap_base -C link-arg=--import-memory  " SKIP_WASM_BUILD="" "/home/sebastian/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/deliverables/eightfish/eightfish/subnode/target/debug/wbuild/eightfish-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.70.0-nightly (478cbb42b 2023-03-28)


  --- stderr
      Finished release [optimized] target(s) in 0.31s
  thread 'main' panicked at 'Failed to compact generated WASM binary.: Error(UnknownOpcode(192))', /home/sebastian/.cargo/git/checkouts/substrate-7e08433d4c370a21/e8a7d16/utils/wasm-builder/src/wasm_project.rs:673:14
```

**Comment by semuelle** [comment]
Also, could you add setup instructions to the [example readme](https://github.com/eightfish-org/eightfish-example-todo/blob/master/README.md)? I have neither `trunk` nor `spin` installed and the link to `init_pg.sh` returns 404.

**Comment by miketang84** [comment]
Thank you for your review, I'm looking into it.

**Comment by miketang84** [comment]
Hi,  @semuelle , for this issue:

```
 => ERROR [ 6/10] RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/l  4.7s
------                                                                                                                         
 > [ 6/10] RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/:    
#0 2.593 Step 1: Downloading: https://github.com/fermyon/spin/releases/download/v1.1.0/spin-v1.1.0-linux-amd64.tar.gz          
#0 4.042 Done...                                                                                                               
#0 4.042                                                                                                                       
#0 4.043 Step 2: Decompressing: spin-v1.1.0-linux-amd64.tar.gz                                                                 
#0 4.064 crt.pem
#0 4.064 spin.sig
#0 4.064 README.md
#0 4.065 LICENSE
#0 4.065 spin
#0 4.556 ./spin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./spin)
#0 4.556 ./spin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by ./spin)
```

I repeated this step, use the latest paritytech/ci-linux:production to test, why can I pass through this step, no `version `GLIBC_2.29' not found`.

```
Step 4/4 : RUN cd /tmp/ && curl -fsSL https://developer.fermyon.com/downloads/install.sh | bash && mv spin /usr/local/bin/
 ---> Running in 4e029c43b6d4
Step 1: Downloading: https://github.com/fermyon/spin/releases/download/v1.1.0/spin-v1.1.0-linux-amd64.tar.gz
Done...

Step 2: Decompressing: spin-v1.1.0-linux-amd64.tar.gz
crt.pem
spin.sig
README.md
LICENSE
spin
spin 1.1.0 (28655d5 2023-04-14)
Done...

Step 3: Removing the downloaded tarball
Done...

You're good to go. Check here for the next steps: https://developer.fermyon.com/spin/quickstart
Run './spin' to get started
Removing intermediate container 4e029c43b6d4
```

I thought it would be the version issue of the docker images version or tag, but right now I don't know where it is.

**Comment by miketang84** [comment]
For the `cargo test` in `subnode` dir, I started a new  `eightfish-m2-build`  container and entered it by:

```
docker run -it eightfish-m2-build bash
```

and `cd subnode; cargo test`, I got:

```
    Finished test [unoptimized + debuginfo] target(s) in 5m 47s
warning: the following packages contain code that will be rejected by a future version of Rust: fs_extra v1.2.0, nalgebra v0.27.1
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 2`
     Running unittests src/lib.rs (target/debug/deps/eightfish_rpc-43383f0396c0345d)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/eightfish_runtime-2c6b931eedb4fd4e)

running 1 test
test __construct_runtime_integrity_test::runtime_integrity_tests ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/eightfish_runtime_api-7c26f8f5e8520240)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/eightfish_subnode-9999ee5451a56310)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/eightfish_subnode-b37b2f156cbc9dfe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/pallet_eightfish-d1b5b1481fab9a6a)

running 11 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::test_disable_wasm_upgrade_flag_event ... ok
test tests::update_index_and_check_pair_list ... ok
test tests::wontwork ... ok
test tests::wontwork_update_index_and_check_pair_list ... ok
test tests::test_wasm_upgrade_event ... ok
test tests::test_wasm_upgrade ... ok
test tests::it_works ... ok
test tests::test_disable_wasm_upgrade_flag ... ok
test tests::test_update_index_event ... ok
test tests::test_act_event ... ok

test result: ok. 11 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.02s

   Doc-tests eightfish-rpc

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests eightfish-runtime

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests eightfish-runtime-api

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests eightfish-subnode

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests pallet-eightfish

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Found no problem as you met. :(

**Comment by miketang84** [comment]
> Also, could you add setup instructions to the [example readme](https://github.com/eightfish-org/eightfish-example-todo/blob/master/README.md)? I have neither `trunk` nor `spin` installed and the link to `init_pg.sh` returns 404.

We're reworking on this.

**Comment by semuelle** [comment]
Thanks for the info, @miketang84. I don't know what the issue was, but I tried it on a different machine and everything worked. I'll continue the evaluation tomorrow, but when the setup instructions are updated, I can probably approve everything.

**Comment by miketang84** [comment]
Hi, @semuelle , I just updated the eightfish-example-todo's README: https://github.com/eightfish-org/eightfish-example-todo/blob/master/README.md.

Right now, it's easy for it to be booted up by docker compose. Wish to enjoy it.

**Pull request merged**
