### PR TITLE
decentralized invoice M1

### PR DESCRIPTION
**Pull request by herou**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1276

### CODE REVIEW

**Review by 0xCaso — COMMENTED** [review]
Hi @herou, thanks for the delivery! I've fixed some things, such as:
- the PR name;
- the PR body ("_Link to the application pull request_");
- the "_Application Document_" field in the delivery file you committed;
- closed the other PR you've opened.

Someone of our team will take care of your delivery as soon as possible.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
[Here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/decentralized_invoice_1_0xCaso.md) you can find the evaluation. Please provide a feedback, so I can update it :)

**Comment by herou** [comment]
> [Here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/decentralized_invoice_1_0xCaso.md) you can find the evaluation. Please provide a feedback, so I can update it :)

Thank you for your quick feedback. I committed to what you asked. Can you please review it again? Thanks a lot!

**Comment by 0xCaso** [comment]
@herou thanks a lot for the addictions! I've just a really minor thing to note: could you re-format the benchmark command like this?
```
./target/release/node-template benchmark pallet \
   --chain dev \
   --execution=wasm \
   --wasm-execution=compiled \
   --pallet invoice \
   --extrinsic "*" \
   --steps 20 \
   --repeat 10 \
  --output pallets/invoice/src/weights.rs
```
It's the same but without any additional spaces, which give errors.

**Comment by herou** [comment]
> @herou thanks a lot for the addictions! I've just a really minor thing to note: could you re-format the benchmark command like this?
> 
> ```
> ./target/release/node-template benchmark pallet \
>    --chain dev \
>    --execution=wasm \
>    --wasm-execution=compiled \
>    --pallet invoice \
>    --extrinsic "*" \
>    --steps 20 \
>    --repeat 10 \
>   --output pallets/invoice/src/weights.rs
> ```
> 
> It's the same but without any additional spaces, which give errors.

Done

**Review by 0xCaso — APPROVED** [review]
Thanks, I'm updating the evaluation approving the delivery!

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
@herou Just one last thing: recently we changed our guidelines, and I would ask you if it's possible to change USDT on Ethereum as payment method to another option choosable from [here](https://github.com/w3f/Grants-Program#pencil-process) (so if you want to stay with Ethereum you should change it to USDC or DAI).

If yes, it would be great if you could resend the invoice changing the currency, and also adding the VAT Amount (which should be 0), and specifying the network (which should be Ethereum). Thanks!

**Comment by herou** [comment]
> @herou Just one last thing: recently we changed our guidelines, and I would ask you if it's possible to change USDT on Ethereum as payment method to another option choosable from [here](https://github.com/w3f/Grants-Program#pencil-process) (so if you want to stay with Ethereum you should change it to USDC or DAI).
> 
> If yes, it would be great if you could resend the invoice changing the currency, and also adding the VAT Amount (which should be 0), and specifying the network (which should be Ethereum). Thanks!

Unfortunately, I can't. Next grant I can but not this one. I and my partner have agreed to it and we can not change it.  It would be for the next time. Thank you!

**Comment by 0xCaso** [comment]
> Unfortunately, I can't. Next grant I can but not this one. I and my partner have agreed to it and we can not change it. It would be for the next time. Thank you!

However, we need you to resend the invoice with the VAT Amount and the specified network, please, and thanks!

**Comment by 0xCaso** [comment]
> Do you have any invoice template which I can have as a reference?

Actually, the invoice you've already submitted is perfect. You just need to add in the already existent "**Details**" section two fields like these: "Network: yourNetwork" and "VAT Amount: 0"

**Comment by herou** [comment]
> > Do you have any invoice template which I can have as a reference?
> 
> Actually, the invoice you've already submitted is perfect. You just need to add in the already existent "**Details**" section two fields like these: "Network: yourNetwork" and "VAT Amount: 0"

I did the needed changes. Please, take another look and let me know if it is okay. Thanks again!

**Comment by 0xCaso** [comment]
Thanks @herou, I forwarded it to the finance team, please allow up to 14 days for the payment.

**Comment by herou** [comment]
> Thanks @herou, I forwarded it to the finance team, please allow up to 14 days for the payment.

I submitted the second milestone. Can you please take a look?

**Comment by RouvenP** [comment]
hi @herou we transferred the payments for M1-M3

**Pull request merged**
