### PR TITLE
Add delivery of upgradeability milestone 1

### PR DESCRIPTION
**Pull request by hugopeixoto**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@hugopeixoto I've started looking at your delivery today. First of all, the explanations behind the logic are quite clear.

I've struggled to actually deploy the contracts & upgrade them as I was getting errors. So I thought - this must be because of me missing some steps...so I decided to automate the process and write some deployment scripts.
Due to both ink! & polkadot-js being moving targets, this proved to be somewhat cumbersome, but in the end I managed to get to a state, where my contracts were deployed to the local canvas node (latest master)
I have not been successful in calling the proxy contract, neither to insert values nor to upgrade the internal logic to V2.

I've forked [your repo](https://github.com/mmagician/ink-upgrade-template/tree/automated-testing) and created a TypeScript project there for the automation.
I would be grateful if you could have a look at these and point me to the steps that I was missing.

It's not absolutely necessary to do this in an automated way in TS, although it would be preferable, as then it's much faster to reproduce. Otherwise, I would like to ask you for a step-by-step walkthrough in your README, where you describe the entire process (i.e. all the CLI steps as well as UI calls with inputs, parameters etc.) and ideally a video/screen recording. I hope the TS project I bootstrapped should make it more attractive to go for the automated method :)

Let me know!

**Comment by hugopeixoto** [comment]
Thanks for reviewing it. I'll take a look at the typescript automation. I wasn't able to call the contracts directly without increasing the gas amount, maybe because the estimator doesn't properly account for cross contract calling. I also had to increase the initial endowment. I think I can make a small video reproducing it from scratch.

**Comment by hugopeixoto** [comment]
I've managed to get the typescript automation. I've merged it to the main branch, but here's the PR: https://github.com/trustfractal/ink-upgrade-template/pull/1

I added my changes to your initial PR in a single commit, if you're interested in what I had to fix. It was mostly waiting for transactions to finish.

I used this repository as inspiration for the wait code: https://github.com/naps62/ink-deployer

**Comment by mmagician** [comment]
I've submitted one final [PR](https://github.com/trustfractal/ink-upgrade-template/pull/2) to include the instructions on how to run the automated workflow.
Anyway, that's just cosmetic, and I'm happy to tell you the milestone has been accepted! You can find the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/145) - though there's nothing there that we haven't already discussed.

Am I right in thinking that you would need to wait for dynamic trait based contract calling ([issue](https://github.com/paritytech/ink/issues/631) and [PR](https://github.com/paritytech/ink/pull/665)) in order to take your work further, as described in your [readme](https://github.com/trustfractal/ink-upgrade-template#ink-features-that-would-improve-this-proposal)?

In the meantime, in case you are interested in working on other projects in the ecosystem, we have a couple of [RFPs](https://github.com/w3f/General-Grants-Program/tree/master/rfps) open, including an [implementation of candle auctions](https://github.com/w3f/General-Grants-Program/blob/master/rfps/candle-auction.md) within a smart contract.

**Comment by hugopeixoto** [comment]
> I've submitted one final [PR](https://github.com/trustfractal/ink-upgrade-template/pull/2) to include the instructions on how to run the automated workflow.

Thanks, it's merged.

> Anyway, that's just cosmetic, and I'm happy to tell you the milestone has been accepted! You can find the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/145) - though there's nothing there that we haven't already discussed.

Thank you for helping. The typescript bootstrap really helped me getting started with the automation.

> Am I right in thinking that you would need to wait for dynamic trait based contract calling ([issue](https://github.com/paritytech/ink/issues/631) and [PR](https://github.com/paritytech/ink/pull/665)) in order to take your work further, as described in your [readme](https://github.com/trustfractal/ink-upgrade-template#ink-features-that-would-improve-this-proposal)?

Yes, having trait support would let us improve our solution, but the linked PR is not sufficient. [I asked in the PR if it would cover what we need](https://github.com/paritytech/ink/pull/665#issuecomment-788355066) to fix our typing, but it seems like it won't.

Every reference to `V1` on [the proxy code](https://github.com/trustfractal/ink-upgrade-template/blob/main/proxy/src/lib.rs) would have to be replaced with a trait representing the `InternalContract`. Having V1 and V2 implement the trait would help us guarantee that the contracts are compatible.

**Pull request merged**
