### PR TITLE
Deep Account Analytics (Polkadot Data Alliance) Milestone 2

### PR DESCRIPTION
**Pull request by sourabhniyogi**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1768

### CODE REVIEW

**Comment by sourabhniyogi** [comment]
@takahser -- This project is not suitable for Docker-based review.  This is because Polkaholic.io, while open source, depends on a Google Cloud backend (BigTable, MySql, GS, BigQuery) and in this case Apache Superset.  We have worked with @michaelis @ w3f who has audited both Milestone 1 and 2 to his satisfaction, which I hope should satisfy the majority of your audit concerns.  Here is a log of @mkchungs 's conversation with him for the milestone 1/2:

[Chat_Export_1_PDA_deep_analytics.pdf](https://github.com/w3f/Grant-Milestone-Delivery/files/13540843/Chat_Export_1_PDA_deep_analytics.pdf)
[Chat_Export_2_michael&michalis_deep_analytics.pdf](https://github.com/w3f/Grant-Milestone-Delivery/files/13540844/Chat_Export_2_michael.michalis_deep_analytics.pdf)

May I recommend you check in with him, and then do a call with you to review outstanding issues as you see fit?

Here is our calendly link
  https://calendly.com/sourabhniyogi
or let us know your telegram so can add you to a Telegram room with both of them and me?

**Review by takahser — CHANGES_REQUESTED** [review]
See [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1038#pullrequestreview-1776583772) in the M1 delivery PR.

**Comment by sourabhniyogi** [comment]
Based on data collected from OpenGov referendum #248 + #366, Colorful Notion has decided to discontinue the polkaholic.io website.   Polkaholic remains as the indexer to support Dune + Google BigQuery for the Polkadot ecosystem.  It turned out there was little demand to covering APIs, cloud costs, SaaS subscriptions not already covered by Subscan, which covers block explorers and API for the ecosystem adequately.   

The work on this grant on traces, staking and governance directly informed how we did our first Dune dashboards, and we are deeply grateful for @michalis's deep and consistently thoughtful requests and feedback and support on this grant.  

As we are occupied with executing on #366 intensely over the next 2-4 months, we will come back to doing the Polkaholic public repo cleanup later this summer.

**Comment by takahser** [comment]
@sourabhniyogi thx for the update. Does this mean we can terminate the grant? What exactly do you mean by "Polkaholic public repo cleanup"?

**Comment by keeganquigley** [comment]
pinging @sourabhniyogi does this essentially mean this milestone won't be delivered?

**Comment by sourabhniyogi** [comment]
We already delivered all the milestones and submitted evidence of this in
November from michalis.  However, the last reviewer created a new
requirement that we deliver a Docker container (which makes no sense given
the GCP backend) + clean up our polkaholic repo, which is an unbounded task
with ad hoc evaluation.  We did a lot of Dune dashboards on staking and
governance and got actionable feedback from michalis.   We believe the
correct thing to do is to
1. isolate the traces part from Milestone into a new repo that actually CAN
be put into a Docker container and loaded in like a Dune table
2. Adjust our Milestone 2 report with documentation of how the Dune
dashboards work, which we did in Jan/Feb
This appears more substantive to me because (1) can be used by others and
quite cheap to execute on by anyone.  (2) is more useful for the Polkadot
community because we'll actually maintain it.

**Pull request closed without merging**
