### PR TITLE
xcNFT M1 & M2 Delivery

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2358

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @dudo50 thanks for the delivery and sorry for the delay. I am working on the eval now and am running into a couple failed unit tests. Could you take a look?

`cargo test --package pallet-parachain-xcnft --lib -- tests --nocapture`:
<details>
<summary>Output</summary>

```rust
   Compiling sp-panic-handler v13.0.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/panic-handler)
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/panic-handler/src/lib.rs:34:2
   |
34 |     sync::LazyLock,
   |     ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:13
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                ^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `sp-panic-handler` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:28:14
   |
28 |     sync::{Arc, LazyLock},
   |                 ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:22
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error: could not compile `sp-trie` (lib) due to 4 previous errors
```
</details>

`cargo test --package pallet-parachain-xcnft-two --lib -- tests --nocapture`:

<details>
<summary>Output</summary>

```rust
   Compiling sp-panic-handler v13.0.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/panic-handler)
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/panic-handler/src/lib.rs:34:2
   |
34 |     sync::LazyLock,
   |     ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:13
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                ^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `sp-panic-handler` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:28:14
   |
28 |     sync::{Arc, LazyLock},
   |                 ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:22
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error: could not compile `sp-trie` (lib) due to 4 previous errors
ubuntu@ip-172-31-16-209:~/polkadot-sdk$ cargo test --package pallet-parachain-xcnft-two --lib -- tests --nocapture
warning: /home/ubuntu/polkadot-sdk/Cargo.toml: unused manifest key: workspace.lints.rust.unexpected_cfgs.check-cfg
   Compiling sp-panic-handler v13.0.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/panic-handler)
   Compiling sp-keystore v0.34.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/keystore)
   Compiling sp-trie v29.0.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/trie)
   Compiling sp-weights v27.0.0 (/home/ubuntu/polkadot-sdk/substrate/primitives/weights)
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/panic-handler/src/lib.rs:34:2
   |
34 |     sync::LazyLock,
   |     ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:13
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                ^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `sp-panic-handler` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:28:14
   |
28 |     sync::{Arc, LazyLock},
   |                 ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:22
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/trie/src/cache/shared_cache.rs:32:53
   |
32 | static RANDOM_STATE: LazyLock<ahash::RandomState> = LazyLock::new(|| {
   |                                                     ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error: could not compile `sp-trie` (lib) due to 4 previous errors
```
</details>

`cargo test`:

<details>
<summary>Output</summary>

```rust
error[E0658]: use of unstable library feature 'lazy_cell'
  --> substrate/primitives/panic-handler/src/lib.rs:34:2
   |
34 |     sync::LazyLock,
   |     ^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:13
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                ^^^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
   --> substrate/primitives/panic-handler/src/lib.rs:132:31
    |
132 |     static RE: LazyLock<Regex> = LazyLock::new(|| {
    |                                  ^^^^^^^^^^^^^
    |
    = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
```
</details>

Zombienet is running and I'm in the root dir of the cloned `polkadot sdk`

Do I need to do something else for these to work? Thanks for any help you can provide.

**Comment by dudo50** [comment]
Hey @keeganquigley , no worries and thanks!

Looking into this, and the tests seem to work fine for me. 
Snímka obrazovky 2024-11-18 o 17 57 40

It seems like a compilation issue to substrate modules not to the xcNFT.

Could you please confirm your rust version and if you are running `nightly` and not `stable`? Also please list which version of rust are you running. You can do this by `rustup -V`

I have following version for comparison: `rustc` version is `rustc 1.84.0-nightly (5ec7d6eee 2024-11-17)`

If you are not on latest you can try using this to see if that would resolve your issue:
```
rustup upgrade 
rustup default nightly    
```

Let me know if this resolved your issue.

Thanks!

**Comment by keeganquigley** [comment]
Thanks @dudo50 you're right, indeed I was running stable. It's working now but `cargo test` fails due to the revive pallet now for some reason:

```rust
error: failed to run custom build command for `pallet-revive-fixtures v0.1.0 (/home/ubuntu/polkadot-sdk/substrate/frame/revive/fixtures)`

Caused by:
  process didn't exit successfully: `/home/ubuntu/polkadot-sdk/target/debug/build/pallet-revive-fixtures-35f4272dadda2e02/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_STRIP
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_OPTIMIZE
  cargo::rerun-if-changed=/home/ubuntu/polkadot-sdk/substrate/frame/revive/fixtures
  cargo::rerun-if-changed=/home/ubuntu/polkadot-sdk/substrate/frame/revive/uapi

  --- stderr
      Updating crates.io index
       Locking 12 packages to latest compatible versions
        Adding polkavm-derive v0.14.0 (available: v0.16.0)
  error: "/home/ubuntu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/Cargo.lock" does not exist, unable to build with the standard library, try:
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

  Error: Failed to build contracts
```

**Comment by dudo50** [comment]
Thanks for the swift reply @keeganquigley,

It again seems to be a compilation problem not related to xcNFT, as the cargo test works for me (It errored out at first due to no space on device, but then it compiled successfully).

screen

I've tried to ask Copilot for a resolution to problem that you are experiencing, and this is what it suggested:

"The error message indicates that the build process is failing because the standard library source code is missing. You can resolve this by adding the rust-src component for the nightly toolchain.

Run the following command in your terminal:

`rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu`

This command will install the source code for the standard library, which is required for the build process. After running this command, try building your project again."

Let me know if that resolved the issue.

Thanks!

**Comment by dudo50** [comment]
@keeganquigley Sorry for another ping, but meanwhile, I noticed that there was an ambiguous test present in the tests for the pallet_nfts xcNFT version. It accessed pallet_nfts storage directly which is not allowed. After removal error is no longer present. This test was removed from the pallet_uniques version as well, but I forgot to remove it from the pallet_nfts version. We were unable to use the `set_accept_ownership` function in both versions for some reason; it failed despite the parameters being 100% correct. For some reason, the function didn't set the proposed owner as accepting ownership. When overriding and directly accessing storage, we were able to make the test pass, but this isn't correct behaviour for tests (They shouldn't access the storage of other pallets (Thus the error occurred)). This is set as future work and requires further investigation. 

Commit: https://github.com/paraspell-research/polkadot-sdk/commit/57a29b14ecb1ff3edd90d85f23b2a2334c528cd3

Feel free to pull the latest version of the [ParaSpell research polkadot-sdk](https://github.com/paraspell-research/polkadot-sdk).

**Comment by keeganquigley** [comment]
Thanks @dudo50 yes I noticed this too, it's completely passing for me now thanks for the fix. 

Thanks for the suggestions, `cargo test` still errors out for me but now it's due to disk space, as you mentioned above, even after I try upping it. No worries since it's on my end I'm willing to go ahead and pass it but maybe consider testing on more platforms. Great work as usual!

**Comment by dudo50** [comment]
Thanks, @keeganquigley! 
Your kind words regarding our work are really appreciated!

Yes, improved testing is definitely part of future work plans. So is the switch towards reserved transfers instead of transact transfers.

I will ping you once we submit the invoices (tomorrow). 

With kind regards,
Dudo

**Comment by dudo50** [comment]
Hey @keeganquigley,
The DOT and FIAT invoice has been submitted. We combined the milestones together into 1 invoice for each currency. Hope that's fine.

Please let us know if everything is okay and invoices are received correctly.

Thanks!

With kind regards,
Dudo

**Comment by keeganquigley** [comment]
@dudo50 ok should be good to go, thanks for checking with us!

**Comment by dudo50** [comment]
Good. Thanks for the information @keeganquigley !

With kind regards,
Dudo

**Comment by dudo50** [comment]
Hey @keeganquigley we have received fiat payment about a week ago, but there wasn't DOT payment yet. Are these processed in different times? Just asking, to confirm everything is fine regarding DOT payment also.

**Comment by keeganquigley** [comment]
Hi @dudo50 thanks for the ping, let me check with the operations team and get back to you shortly.

**Comment by keeganquigley** [comment]
Hi @dudo50 the DOT payment should go out in tomorrow's batch, please let me know if you don't receive it by end of day!

**Comment by dudo50** [comment]
Hey @keeganquigley , no news regarding DOT payment so far. Can you please check the status?

Thanks a lot and sorry for ping!

**Comment by semuelle** [comment]
Hi @dudo50, sorry for the delay. If it wasn't paid yesterday, it should go out next Friday latest. Please let us know in case you haven't received anything by EOD Friday.

**Pull request merged**
