### PR TITLE
Add wasm-opt-for-rust M2

### PR DESCRIPTION
**Pull request by brson**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1070

### CODE REVIEW

**Comment by alxs** [comment]
@brson thank you for this amazing delivery. I'm more than happy to accept as is - you can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/wasm-opt-rust_2_alxs.md).

The article was a very enjoyable read and allowed me to understand the work you carried out far better than I would have managed without it. Thank you for putting so much effort into it. In case you want us to tweet an announcement about it, feel free to send an email to grantsPR@web3.foundation.

Let us know if you need any help applying for a maintenance or follow-up grant.

I'll notify the finance team to pay out your invoice. As usual, please allow for up to 2 weeks of processing time.

**Comment by meldien** [comment]
@brson, 
Could you please add on the invoice a number and also a invoice date?
Many thanks for the exchange/re upload of the invoice.

**Comment by brson** [comment]
@meldien I have resubmitted the invoice with a number and a date.

**Comment by brson** [comment]
@meldien can you give our updated invoice another look?

**Comment by meldien** [comment]
@brson, the new invoice is looking good. The payout would be done today.

**Comment by brson** [comment]
Thanks @meldien!

**Pull request merged**
