### PR TITLE
Submit scale-codec-comparator milestone 3

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/953 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @gmajor-encrypt for the delivery. Are you able to explain why the GH actions are failing for [this bump](https://github.com/gmajor-encrypt/scale-codec-comparator/actions/runs/3982725063/jobs/6827425214)? As well as [this one](https://github.com/gmajor-encrypt/scale-codec-comparator/actions/runs/3963658052/jobs/6791740391)?

**Comment by keeganquigley** [comment]
Other than that everything looks good. See my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/scale-codec-comparator_3_keeganquigley.md).

**Comment by gmajor-encrypt** [comment]
> Thanks @gmajor-encrypt for the delivery. Are you able to explain why the GH actions are failing for [this bump](https://github.com/gmajor-encrypt/scale-codec-comparator/actions/runs/3982725063/jobs/6827425214)? As well as [this one](https://github.com/gmajor-encrypt/scale-codec-comparator/actions/runs/3963658052/jobs/6791740391)?

@keeganquigley Hi, Thanks for your evaluation, this problem was caused by the inconsistency of polkadot.js and @polkadot/types-codec lib version in the recent upgrade, this problem has been resolved

**Comment by keeganquigley** [comment]
@gmajor-encrypt cool! Thanks for fix. I'm happy to go ahead and approve the milestone. Congrats on the completion of the grant. My final eval is [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/scale-codec-comparator_3_keeganquigley.md).

**Comment by keeganquigley** [comment]
I have forwarded your invoice for processing.

**Comment by RouvenP** [comment]
hi @gmajor-encrypt we transferred the payment today

**Pull request merged**
