### PR TITLE
Update X-Predict-Market_milestone_1.md

### PR DESCRIPTION
**Pull request by XPredictMarket**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by XPredictMarket** [comment]
@Noc2 @alxs @splix @woss Excuse me. Can I ask a question?We have been updating for a long time. How is our milestone review progress?

**Comment by alxs** [comment]
Hi @XPredictMarket. Sincere apologies for the long delay. This is on my to-do list and I will get back to you by mid-week.

**Comment by woss** [comment]
I am sorry  @XPredictMarket but you must have added me by a mistake :) I am not a part of the decision making process nor parity nor w3f :)

**Comment by XPredictMarket** [comment]
Hi Aleixo Sanchez,

 
Thank you so much for the reply

 
We appreciate it

 
Looking forward to your feedback

 
Best

 
X Predict Market

 
 
-----Original message-----

**Comment by XPredictMarket** [comment]
Hi Daniel

 
Sorry that we have added you by mistake

 
Thank you for your reply

 
Best

 
X Predict Market

-----Original message-----

**Comment by alxs** [comment]
Hey again @XPredictMarket, apologies for the late reply. I have a few remarks:
- You state multiple times across the documentation that X Predict Market support cross-chain transfers. How exactly is this implemented?
- Could you please update the deliverables to match those in the application? It is also OK to provide multiple links per deliverable, and in the notes you can specify where the different parts of each deliverable are implemented.
- Have you already conducted a token sale?

**Comment by XPredictMarket** [comment]
> Hey again @XPredictMarket, apologies for the late reply. I have a few remarks:
> 
> * You state multiple times across the documentation that X Predict Market support cross-chain transfers. How exactly is this implemented?
> * Could you please update the deliverables to match those in the application? It is also OK to provide multiple links per deliverable, and in the notes you can specify where the different parts of each deliverable are implemented.
> * Have you already conducted a token sale?
> * `cargo clippy` reports multiple warnings and errors, please address these.

Hey Alxs, thank you for your comment, it took us some time to fix the errors and update the application.

1. Cross-chain is one of the missions in our future plan, but we did not indicate that we will achieve it in our milestone 1 delivery goal. As for the implementation of cross-chain, we need to follow up the progress of Polkadot and also participate in the auction at the proper time.

2. We have updated the deliverables that match with the content in the application.  Among which links of the detailed description of the deliverables are added. Including description &  where the different parts of each deliverable are implemented.

3. We haven’t conducted a token sale yet.

4.The errors and bugs are fixed.

Thx again for your help, let us know if you have other questions.

**Comment by alxs** [comment]
Thank you for the clarification, in that case could you please remove this from the current documentation? It clearly states that X Predict Market "supports multi currency cross chain transactions", which is misleading. I was happy to see that the website correctly employs the future tense though ;)

For some reason, `cargo tarpaulin` now fails for me with the following error and almost crashed my machine the two times I tried to run it. Could you try it out yourself and see if you can reproduce the issue?
```
error: Broken pipe (os error 32)
warning: build failed, waiting for other jobs to finish...
error: Broken pipe (os error 32)
error: build failed
May 27 20:23:31.171 ERROR cargo_tarpaulin: Failed to compile tests! Error: linking with `cc` failed: exit code: 1
Error: "Failed to compile tests! Error: linking with `cc` failed: exit code: 1"
```

Another thing: it looks like the [X Predict Market Runtime Library](https://github.com/XPredictMarket/X-Predict-Market-Runtime-Library) repository contains outdated versions of some of the pallets used in NodePredict. Just to keep things tidy, I assume this repository can be nuked? Otherwise feel free to update the pallets therein and link to them from the node.

Regarding submitting the results through an oracle (i.e. deliverable 3 in the [application](https://github.com/XPredictMarket/Open-Grants-Program/blob/876f8aedc1f58e35fcfc4d5ccec58497a5bc4272/applications/XPredictMarket.md#milestone)), it looks like you currently haven't implemented any oracle integration but this is rather just a sudo call. Could you comment on this?

**Comment by XPredictMarket** [comment]
> Thank you for the clarification, in that case could you please remove this from the current documentation? It clearly states that X Predict Market "supports multi currency cross chain transactions", which is misleading. I was happy to see that the website correctly employs the future tense though ;)
> 
> For some reason, `cargo tarpaulin` now fails for me with the following error and almost crashed my machine the two times I tried to run it. Could you try it out yourself and see if you can reproduce the issue?
> 
> ```
> error: Broken pipe (os error 32)
> warning: build failed, waiting for other jobs to finish...
> error: Broken pipe (os error 32)
> error: build failed
> May 27 20:23:31.171 ERROR cargo_tarpaulin: Failed to compile tests! Error: linking with `cc` failed: exit code: 1
> Error: "Failed to compile tests! Error: linking with `cc` failed: exit code: 1"
> ```
> 
> Another thing: it looks like the [X Predict Market Runtime Library](https://github.com/XPredictMarket/X-Predict-Market-Runtime-Library) repository contains outdated versions of some of the pallets used in NodePredict. Just to keep things tidy, I assume this repository can be nuked? Otherwise feel free to update the pallets therein and link to them from the node.
> 
> Regarding submitting the results through an oracle (i.e. deliverable 3 in the [application](https://github.com/XPredictMarket/Open-Grants-Program/blob/876f8aedc1f58e35fcfc4d5ccec58497a5bc4272/applications/XPredictMarket.md#milestone)), it looks like you currently haven't implemented any oracle integration but this is rather just a sudo call. Could you comment on this?

Hi Alxs, thanks for pointing out the problems
We have initiated a request to update the grant: https://github.com/w3f/Open-Grants-Program/pull/432
Regarding 1 : we have removed the cross-chain related content in our grant.
Regarding 2 : we have tested the cargo tarpaulin on `https://playground.substrate.dev/` and we did not find the error that you mentioned. Our operation ：we are using the fork code of master, the other forks are our test code, not our main code.

Procedures are as follows:

```bash
# Update the rust compiler
rustup update nightly
rustup update stable
# Specify the default version
rustup default stable
# Remove the built-in old version
rustup uninstall nightly-2020-10-05
# Install cargo-tarpaulin
cargo install cargo-tarpaulin

# Clone code
git clone https://github.com/XPredictMarket/NodePredict.git

# Implement test
cd NodePredict && cargo tarpaulin
```

There is no corresponding error occurs on our side. You can try to reinstall rust and empty the target folder and try again, or Use a clean container to run continuous integration. Or you can provide us your integration environment and integration commands to see if we can reproduce the issue.

Regarding 3:
We upload the results directly through sudo because we are now at the testing stage. We have already changed the oracle into sudo. In our upcoming version, we plan to use the centralized node & consensus mechenism to upload the result, which is not included in this milestone delivery.

Let us know if you have any further question, looking forward to your feedback.

**Comment by alxs** [comment]
Thank you for your reply and the amendment @XPredictMarket, and apologies for the long delay. The issue with tarpaulin seems to indeed have originated on my end; in any case it doesn't happen any more. I have a few more extensive remarks than last time:

- Documentation (deliverable 0b.) needs to be vastly improved. There is no tutorial for end users as far as I can tell, which  should contain at least how to create predictions as per the milestone deliverables but would ideally explain the entire process and the underlying mechanisms. This could be similar to the Google Doc you provide, but catered to end users.
- Inline comments and documentation are virtually nonexistent. Also here, I'd like to ask you to please significantly improve in this aspect as per the same deliverable as above. Your code should be understandable by someone unfamiliar with it, such as but not limited to us.
- The [technical document](https://github.com/XPredictMarket/docs/blob/master/Technial.md) is outdated and doesn't correspond to the current design. The documentation in your [README](https://github.com/XPredictMarket/NodePredict#5pallet) would be far more useful as doc comments. I recommend you read into `rustdoc` if you're not familiar with it.
- Even after your last amendment, the current delivery doesn't provide the functionality you propose. I.e. deliverable 3 should allow one to "submit results through staked nodes", but currently this is simply possible by sudo accounts, however these have been created.
- Furthermore, under "Key Functions" in your application you state that results are "totally transparent to all users for judgement during the result announcement period." Is this currently the case and if so how?
- It is currently possible to create a prediction that ends at any time on the day it is created, regardless of the current time.
- The status of a prediction can be modified arbitrarily as long as the calling account has sudo rights, whereas only certain transitions should be allowed.

**Comment by XPredictMarket** [comment]
> Thank you for your reply and the amendment @XPredictMarket, and apologies for the long delay. The issue with tarpaulin seems to indeed have originated on my end; in any case it doesn't happen any more. I have a few more extensive remarks than last time:
> 
> * Documentation (deliverable 0b.) needs to be vastly improved. There is no tutorial for end users as far as I can tell, which  should contain at least how to create predictions as per the milestone deliverables but would ideally explain the entire process and the underlying mechanisms. This could be similar to the Google Doc you provide, but catered to end users.
> * Inline comments and documentation are virtually nonexistent. Also here, I'd like to ask you to please significantly improve in this aspect as per the same deliverable as above. Your code should be understandable by someone unfamiliar with it, such as but not limited to us.
> * The [technical document](https://github.com/XPredictMarket/docs/blob/master/Technial.md) is outdated and doesn't correspond to the current design. The documentation in your [README](https://github.com/XPredictMarket/NodePredict#5pallet) would be far more useful as doc comments. I recommend you read into `rustdoc` if you're not familiar with it.
> * Even after your last amendment, the current delivery doesn't provide the functionality you propose. I.e. deliverable 3 should allow one to "submit results through staked nodes", but currently this is simply possible by sudo accounts, however these have been created.
> * Furthermore, under "Key Functions" in your application you state that results are "totally transparent to all users for judgement during the result announcement period." Is this currently the case and if so how?
> * It is currently possible to create a prediction that ends at any time on the day it is created, regardless of the current time.
> * The status of a prediction can be modified arbitrarily as long as the calling account has sudo rights, whereas only certain transitions should be allowed.

Hi Alxs, thanks for pointing out the problems
1 The final user teaching guideline link has been added to the README
2 We have updated the README document and we have added rustdoc note of the codes.
3 We have completed the modification following the requirements above, the sudo implementation code has been modified to the community uploading method.

**Comment by XPredictMarket** [comment]
Hi @alxs , here is our update
1、The final project product guideline for users:
https://docs.google.com/document/d/1lW0NzIf45IKt3Z1Ggx-ZsKVRKI_4sSpmcDEuloACSig/edit?usp=sharing
2、We have added detailed internal notes in the codes so that people who are not familiar with our project can also comprehend it.
3、The technical files rust doc are organized and the links are as follows:
https://rustdoc.x-predict.com/xpmrl_autonomy/
https://rustdoc.x-predict.com/xpmrl_couple/
https://rustdoc.x-predict.com/xpmrl_proposals/
https://rustdoc.x-predict.com/xpmrl_tokens/
https://rustdoc.x-predict.com/xpmrl_traits/
https://rustdoc.x-predict.com/xpmrl_utils/
4、The related sudo codes are deleted and modified to the function ‘submit the results through staking nodes’ mentioned before
5、During the result publicity period, users can view the correct prediction result through UI interaction prompt in the prediction propasl page.
6、The ending time of prediction proposal has to be at leaset 10 minutes after the creation of it.
7、We can change the status of proper Original prediction into Formal prediction using sudo account, or we can end the improper proposals that can not obtain accurate result or related to criminal content in advance. （straight from Original prediction to End)

**Comment by alxs** [comment]
Thank you for the updates. I have a few follow-up comments:

- The user guide shouldn't be a Google Doc, but a proper tutorial/documentation such that regular users are able to use the application. This is not the same as the testing guide, which is mostly useful to us in order to assess the delivery.
- Could you point me to where the results uploading by staked nodes is documented?
- How does the judgement period work, isn't there some missing functionality here? I.e. shouldn't users be able to vote on whether they accept a result or not, instead of just being able to view it?
- Same goes for point 2 in [Key Functions](https://github.com/w3f/Open-Grants-Program/blob/master/applications/XPredictMarket.md#key-functions) in your application. Unless I'm missing something, this is currently not implemented?

**Comment by PredictDao** [comment]
Hi @alxs 
1. The user tutorial can be viewed in the menu bar on the left side of our prediction market page : https://test-app.x-predict.com/PredictMarket for users. 
The user tutorial is : https://app.gitbook.com/@x-protocol/s/x-protocol/

2. Link to view the results uploaded by the node
https://github.com/XPredictMarketdePredict/blob/master/pallets/autonomy/src/lib.rs#L158

3. At the current stage,  users can appeal the results in our community (Telegram channel) during the publicity period. Since we did not have enough users to participate as a node in the testing phase, the appeal is currently being reviewed by the official to determine the final result.  After the user base is gradually expanded, the voting mechanism of the nodes will be used to determine the final result.

4.The review of the initial proposal pool is currently being conducted by the project team, also because we did not have enough users to participate as a node in the testing phase, so in order to ensure the legitimacy of the proposal, the current stage is reviewed by the official team, after the gradual expansion of users, the transformation process of initial proposal to the formal proposal will be reviewed by the node voting mechanism.

5.The unit test is feasible under our environment, we would like to know what kind of testing tool that you are using to test our codes? If you have testing problems, please provide us with some related content such as Operating system version (we are testing on Ubuntu 20.04), rust version information (rustup show), it can help us to troubleshoot and fix the problem. If possible, please attach your error message.

**Comment by alxs** [comment]
Thanks for the quick reply. The user tutorial looks good. Do you also have some documentation on the mechanics of the prediction markets? I.e. who-gets-how-much-when?

The link under point 2 in your comment is currently broken.

As I see it, the review of proposals and results is part of the deliverables for the grant. I don't think this necessarily requires a certain number of users - you can simply develop it, set up a testing environment and submit it to us without the need to deploy it.

I've attached more details below re the failed tests.


<details>
  <summary> <code>uname -a </code></summary>
  
 ```
Linux aleixo-thinkpad-manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
 ```
</details>


<details>
  <summary> <code>rustup show </code></summary>
  
 ```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/aleixo/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-unknown-linux-gnu (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)
 ```
</details>

<details>
  <summary> <code>cargo test </code></summary>
  
 ```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test __construct_runtime_integrity_test::runtime_integrity_tests ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 7 tests
test mock::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
test tests::test_add_liquidity ... ok
test tests::test_retrieval ... FAILED
test tests::test_buy ... ok
test tests::test_remove_liquidity ... FAILED
test tests::test_set_result ... FAILED
test tests::test_sell ... ok

failures:

---- tests::test_retrieval stdout ----
thread 'tests::test_retrieval' panicked at 'Expected Ok(_). Got Err(
    DispatchErrorWithPostInfo {
        post_info: PostDispatchInfo {
            actual_weight: None,
            pays_fee: Pays::Yes,
        },
        error: DispatchError::Module {
            index: 3,
            error: 2,
            message: Some(
                "ProposalAbnormalState",
            ),
        },
    },
)', pallets/couple/src/tests.rs:234:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::test_remove_liquidity stdout ----
thread 'tests::test_remove_liquidity' panicked at 'Expected Ok(_). Got Err(
    DispatchErrorWithPostInfo {
        post_info: PostDispatchInfo {
            actual_weight: None,
            pays_fee: Pays::Yes,
        },
        error: DispatchError::Module {
            index: 3,
            error: 2,
            message: Some(
                "ProposalAbnormalState",
            ),
        },
    },
)', pallets/couple/src/tests.rs:113:9

---- tests::test_set_result stdout ----
thread 'tests::test_set_result' panicked at 'Expected Ok(_). Got Err(
    DispatchErrorWithPostInfo {
        post_info: PostDispatchInfo {
            actual_weight: None,
            pays_fee: Pays::Yes,
        },
        error: DispatchError::Module {
            index: 3,
            error: 2,
            message: Some(
                "ProposalAbnormalState",
            ),
        },
    },
)', pallets/couple/src/tests.rs:269:9


failures:
    tests::test_remove_liquidity
    tests::test_retrieval
    tests::test_set_result

test result: FAILED. 4 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
 ```
</details>

**Comment by XPredictMarket** [comment]
We are still improving the governance-related modules in the white paper,
Sorry, the second link we responded to above should be this: https://github.com/XPredictMarket/NodePredict/blob/master/pallets/autonomy/src/lib.rs#L158
We have already dealt with the compilation error you mentioned, and we will submit it together after the development of the governance module is completed, and it will be completed in July

**Comment by alxs** [comment]
Thanks. I was asking where this process was documented, see my [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/148#issuecomment-875797542). I'll be happy to receive a final delivery by the end of the month.

**Comment by XPredictMarket** [comment]
> Thanks. I was asking where this process was documented, see my [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/148#issuecomment-875797542). I'll be happy to receive a final delivery by the end of the month.

Hi Alxs, sorry for the late reply. 

The governance node demand is completed, along with the submitted codes, please do review it.

1.The updates include the function of initial proposal voting, which allows the original proposal to become a formal proposal through the community without the participation of administrators. 
2.Initial proposal reward function
3.Proposal results will be submitted by oracle and receive reward in the end
4.Proposal results reporting system
5.Oracle examples codes：https://github.com/XPredictMarket/spr-cli
6.The link to our mechanism document is: https://x-protocol.gitbook.io/x-protocol/2-working-mechanism-of-x-predict-market

**Comment by alxs** [comment]
@XPredictMarket is this functionality live in your test app? I can't seem to find any of it and I don't see any changes since last time. Or how should I test it?

Your "oracle" example seems to be a simple program that submits an extrinsic - what's its purpose exactly? I thought you weren't using oracles in the first place after your amendment?

**Comment by XPredictMarket** [comment]
Hi @alxs , thx for the quick response

Can you specify the functionality 

And regarding the ‘oracle examples’, we have clearly described that because each topic has a different interface for obtaining results, if it is required to be written into Hooks, all the scenes need to be written in advance, which requires high professional knowledge from users. We seperate them to facilitate more nodes to submit the data at their convenience.

And we wonder if you can schedule an online meeting with us to further discuss the details?

If possible, please do send an an email to official@x-predict.com

**Comment by alxs** [comment]
The new functionality that you described in your last comment.

I don't understand what you're trying to say, I'm sorry. Do you mean if oracle submission was automated? This is just manual for the moment no?

I've sent you an email.

**Comment by XPredictMarket** [comment]
Hi Alex, sorry for the confusion. We have updated the README and you can follow the workflow described here https://github.com/XPredictMarket/NodePredict/wiki/Workflow to test the functions.

**Comment by XPredictMarket** [comment]
Hi Alex, sorry for the confusion. We have updated the README and now you can run the integration tests using comments in the Test Guide. Meanwhile, you can also refer to the workflow described here https://github.com/XPredictMarket/NodePredict/wiki/Workflow to test the functions accordingly.

**Review by alxs — CHANGES_REQUESTED** [review]
- While I appreciate the effort from your side to already provide (and host) rustdocs for your pallets, in their current state these are incomplete/rather minimal and it is still generally hard to understand the logic you've implemented. Large portions of your code remain entirely undocumented. See https://github.com/perun-network/perun-polkadot-pallet or [any Substrate file](https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs) for examples of well-documented pallets. I recommend you to heed the [`missing_docs` lint](https://doc.rust-lang.org/rustdoc/what-to-include.html) and in general to familiarise yourself with the rustdoc book.
- I tried following your [workflow](https://github.com/XPredictMarket/NodePredict/wiki/Workflow#workflow) and couldn't get past creating a proposal: image
  I was probably passing invalid arguments but these are documented neither in said document nor in the rustdocs.
- The [user documentation](https://x-protocol.gitbook.io/x-protocol/) doesn't contain instructions to create nor to vote on proposals/results.
- The [test guide](https://github.com/XPredictMarket/NodePredict/wiki/Tutorials) is outdated and it is currently not possible to follow it. Specifically, it is no longer possible for normal users to interact with proposals via sudo calls.
- You can avoid having to maintain [two different node packages](https://github.com/XPredictMarket/NodePredict/tree/master/nodes) and instead use a [separate chain spec](https://substrate.dev/docs/en/tutorials/start-a-private-network/customspec), which I believe is the only difference between the two in this case. In general, please try to avoid code duplication.
- Your current design seems very centralised, as opposed to what you claim [in the application](https://github.com/w3f/Grants-Program/blob/master/applications/XPredictMarket.md#overview). E.g. as far as I understand it results can't be submitted without an account being whitelisted by the team and you can arbitrarily slash users. This also still diverges from the approach you proposed [in the amendment](https://github.com/w3f/Grants-Program/pull/432/files#diff-db63ed5be4836ed002df0156a2c99b002bc2a40f7a452a22dbf35096ce189964R223) since a user can stake as much as they want, but as long as they haven't been whitelisted they won't be able to submit results.

**Comment by XPredictMarket** [comment]
1. At the beginning, we referred to the code annotation style of Acala and Substrate, and only annotated user-oriented functions, storage and Config. Now we will refer to the link you gave to enrich our annotation content.

2. This is because the type of polkadotjs is not set up completely, you should not use the older version of the type, please use the latest type: https://github.com/XPredictMarket/NodePredict/blob/master/runtime/types.json.

3. The document is outdated, because the functions of uploading results and votes are recently updated, we will update the document once the integration test scripts done.

4. sudo permissions have been gradually stripped.

5. We will complete multiple node clients through chain_spec configuration, which will be updated along with the document.

6. We will follow your advice per element communication to modify the governance program, but it will take some time. We will re-submit when we finish modifying that part.

**Comment by alxs** [comment]
> please use the latest type

Updated, though the parameters should still be documented. Besides, could you transfer some test tokens to the following account? 5HmonM1WPAVryBBSTafrHiu1UeC94zkcpBLDcJYkeCYPiavu

Thanks for the remaining points.

**Comment by XPredictMarket** [comment]
> Updated, though the parameters should still be documented. Besides, could you transfer some test tokens to the following account? 5HmonM1WPAVryBBSTafrHiu1UeC94zkcpBLDcJYkeCYPiavu
> I have transferred the test coin to the address above

**Comment by alxs** [comment]
@XPredictMarket any updates? It looks like you [ceased development](https://github.com/XPredictMarket) of the project about 2 months ago. We would terminate the grant if you're no longer interested.

**Comment by XPredictMarket** [comment]
Hi @alxs , sorry for the late reply, we have been modifying the code structure in the past few days, and we have already completed the governance plan as we have stated in the Workflow (in github comment).
The codes of the governance part has been uploaded to https://github.com/XPredictMarket/NodePredict/tree/master/pallets/autonomy  , please contact us for any questions.

**Comment by alxs** [comment]
Hey, let me know when you've addressed all the points I raised in [my last comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/148#pullrequestreview-735853625) and things are generally in a working state. Please note that the review process is usually a lot faster than it's been the case for this delivery - according to the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T%26Cs.md#4--procedure) you have 14 days to address feedback which, in the interest of reaching a conclusion with this delivery, we will exercise from today.

**Comment by XPredictMarket** [comment]
> Hey, let me know when you've addressed all the points I raised in [my last comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/148#pullrequestreview-735853625) and things are generally in a working state. Please note that the review process is usually a lot faster than it's been the case for this delivery - according to the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T%26Cs.md#4--procedure) you have 14 days to address feedback which, in the interest of reaching a conclusion with this delivery, we will exercise from today.

Hi Alx, thanks for giving us the feedback. We have sorted out the details and update according to your last comment on Aug.23

1 The updated rustdocs :
https://rustdoc.x-predict.com/

2 The updated type :
https://github.com/XPredictMarket/NodePredict/blob/master/runtime/types.json 

3 User document  : due to time limit, we have not been able to finish the UI/UX of the updated X Predict Market, so the user document won’t be necessary. But you can execute a whole prediction process using the testing document in 4

4 Testing document : 
https://docs.google.com/document/d/1hA1cuc52WY5SevgnKQFzxxQUl1KYWLakjCQTBHGdt5U/edit?usp=sharing 

5 Separate chain spec : https://github.com/XPredictMarket/NodePredict 

6 X Predict Market  has changed from a relatively centralized governance method to a model in which users participate in governance. Through the incentive model and supervision system, users have realized the decentralization of the governance process.

Here is the mind maps that may help you visualize your thoughts better
https://docs.google.com/spreadsheets/d/1FAwbSJnMnY3II0F8Wc8yRggx-zaSvbSZ7Vp17KMmdDY/edit?usp=sharing 

We would appreciate your feedback on this, thank you for your help and patience in the past year, it really helped us to build towards a more decentralized way.

**Comment by alxs** [comment]
As far as I can tell, the rustdocs are in the same state as the last time I checked. I also don't see any changes in documentation in your repository [since my comment](https://github.com/XPredictMarket/NodePredict/compare/152f61dc5b72ba33bba12b117c07250e781f117e...b544651399e439efffb434146a3bc95465f18eda) in August.

Please note that user documentation, too, is required, as per your application.

I understand that a lot of effort has gone into this project but I'm afraid given the above, in its current state it doesn't meet the deliverables nor our guidelines, despite going through one of the longest evaluation processes we've ever had. As per my last comment, I'm afraid I'm putting the grant up for termination. I hope the feedback obtained during the program is still useful to you, and that this doesn't affect your decision on whether to continue working on the project.

Thank you for taking part in the grants program.

**Pull request closed without merging**
