### PR TITLE
Stardust Milestone 1 Submission

### PR DESCRIPTION
**Pull request by adit313**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/865

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @adit313. We will look into it as soon as possible. We currently have a bit of a backlog, so it might take a few more days.

**Comment by takahser** [comment]
@adit313 Thanks for your delivery. I already started looking into the PDF, but didn't finish yet.
So far I have the following questions:

i) Quote from page 8

> Collateral requirements vary depending on the underlying asset, so even though USDC is only 34% of collateral, it’s marginal 1% overcollateralization ratio means that USDC backs 53% of outstanding DAI issued.

Questions:

1. How did you get from 34% collateral with 1% overcollateralization to a 53% backing of the DAI? Can you lead me through the thought process? What I would have expected is 34*1.01 = 34.34%, not 53%, so I'm curious where the mistake is.
2. How did you determine Ethereum's risk free rate 2.73%? Personally, I know that concept only from [gov. bonds yields](https://www.investopedia.com/terms/r/risk-freerate.asp#:~:text=The%20risk%2Dfree%20rate%20of%20return%20is%20the%20theoretical%20rate,a%20specified%20period%20of%20time.).
image


ii) Quote from page 11

Question: What would the axis descriptions be here?
image

I'm going to continue reading, so I'll might be back with more questions later.

**Comment by adit313** [comment]
Hi there! All good questions and more than happy to answer.

On the first part. I agree, it sounds really counter intuitive that USDC is only 34% of DAI's collateral, but yet 53% of outstanding DAI is backed by it. The reason for that is down to the collateral ratio required. If you post ETH as collateral, you need to post a lot more of it. Depending on the pool, it will be 130-170% of the value you are borrowing. With USDC, you only need 101% of the value (and PSM is 1:1), so even though 53% of people have opted to use USDC, it forms far less of the collateral pool because they only need to give a little bit more of it, whereas the ETH collateral borrowers are posting a ton of it. This page has the collateral broken down live and the reserve ratio requirements: https://daistats.com/#/overview (this is a live view so the numbers have changed since we last looked at it, but the proportion discrepancy is still there between the collateral and DAI outstanding pie charts)

If it's still confusing though, we do deep dive more into it on slide 52. Also, there is no mistake, your math is completely right, it's just that you are missing the BTC and ETH pools, if you did the multiplication for all of them, added them together, and then normalized the total collateral back down to 100% you'd get that 34%.

For your second question, there are a whole host of ways to calculate a risk-free rate. Government bonds are a good easy to understand example, but you can also use LIBOR or the Fed Funds rate. If you want to get very technical, you can calculate them from sharpe ratios, backing them out of options, looking at risk-free lending rates etc. We used this work by the Serenity Fund who backed it out of lending pools and found it to be 2.73% for Ethereum. https://medium.com/coinmonks/market-info-de-fi-risk-free-rate-140734270b36
I'm sorry we missed the citation, I'm adding it to our working copy now.

Honestly, I personally don't like the method using lending pools. I'd much rather point someone towards calculating  risk-free rates from options, as there is an a real arbitrage opportunity to make money if that is priced incorrectly. That hasn't been done for Ethereum as it lacks traditional financial options, but Bitcoin has CME futures and people have done fantastic work breaking down it's risk-free rate. https://quantpedia.com/what-is-the-bitcoins-risk-free-interest-rate/
For all of our numerical analysis that involves calculating profits on capital or collateral, we've used the BTC risk-free rate as that feels more substantial.

And I'm really sorry about missing the axis labels on slide 11, we'll add those in. Those charts are the traditional supply/demand charts of economics. The Y axis is price and the X axis is quantity. As good's price increases the quantity demanded by the market drops which is why that line has a negative slope. Conversely, as good's price increases, more people are willing to supply that good so the line representing supply has a positive slope. Where the demand and supply curves cross is the prevailing optimal price and quantity of the market. https://www.britannica.com/topic/supply-and-demand

These are great questions, so please keep them coming as you go through the deck. It also helps us understand where we needed to have explained more. The deck is INCREDIBLY data and economic foundations/principle heavy so I apologize in advance for the sheer density.  The 34% vs 53% is a good callout. I agree, it's a bit confusing and since we introduce the topic a bit more at length later in the deck, maybe we can streamline there.

**Comment by takahser** [comment]
@adit313 thanks for your answers!
In the meanwhile, I went through the whole document and I have a couple of points I'd like to highlight:

- i) p. 17, quote:
  > (..) it (foreign currency reserve) has been proven by nearly a hundred years of history to offer additional options that help prevent hyperinflation.

  If my interpretation is correct, here you're claiming that having a foreign currency reserve would protect from having hyperinflation. However, in the example of Argentina, their foreign currency reserves in their inflationary period starting before the 1980s do not really correlate with their inflation rate:

  _Argentina [Foreign Exchange Reserves](https://tradingeconomics.com/argentina/foreign-exchange-reserves) 1970-1985:_
  image
  
  _Argentina [Inflation Rate](https://tradingeconomics.com/argentina/inflation-cpi) 1970-1985:_
  image

  My question: Is it really fair to assume that having foreign reserves protect from hyperinflation? How did you reach to this conclusion? For example, did you verify the data around other historical hyperinflation scenarios, such as in Weimar republic, Venezuela, Zimbabwe, etc.?

  (Note: Inflation is picking up even more post-1985, up to ~1990 but the peak was so big that the previous data would hardly be recognizable on this linear chart, this is why I decided to cut it at 1980)

- ii) p. 20: you mention "tobin tax" here. I didn't know the concept, so a definition would have been nice, but maybe it's just my financial illiteracy :)

- iii) p. 21: you mention Bitcoins risk-free rate being 3.7% here. Similar to the same in ETH, a reference would have been nice.
- iv) p. 24: here you included some asterisks and I'm not sure what it means, e.g. "$8.9B USD*"
  image
- v) p. 27: here the colors of USDC and TUSD are very similar and hardly distinguishable
- vi) p. 28: here the chart legend is incomplete - the label for lila is missing
- vii) p. 32: At the "Most Used Payment Methods for International Remittances" chart, I'm not sure why the vertical bars have different starting points instead of starting at 0%.
  image

- viii) p. 33, quote:
  > Most central banks have an in-depth understanding of monetary policy and its effects and spend billions to generate accurate forecasts of demand.

  This might be a bit of an opinionated comment to make, but I'm not convinced that these forecasts are mostly accurate. Recent examples: 2008 financial crisis, 2022 ongoing inflation problem - in both cases they didn't see it coming :)

- ix) p. 44, quote:
  > It should be noted however that these companies have seen significant downgrades in the past 3 months and as of writing (April 12) Tether has not released its March 31st audit report that would show any changes in the distribution of commercial paper after the major downgrades in the Chinese real estate sector earlier this year.

  Out of curiosity, do you have any updates on this?

- x) p. 45: Here you mention "parachain networks", however, the concept of parachains is (afaik) unique to substrate-based chains.

- xi) p. 51: typo "delpployed" => "deployed"

- xii) p. 55: Here the axis description is missing in the price/quantity chart

- xiii) p. 59, quote

  > These multi-token coins should have a fixed reserve ratio requirement of DOT in order to both serve as a backstop of
foreign currency reserve, and to perform repurchase operations on the central repo market.
  > (...) these multi-token stablecoins should be allowed to participate in centralized repo markets (...)

  I'm not quite sure how to interpret this. Are you suggesting to use DOT as a foreign currency reserve for a stable coin? Or what do you mean by "in order to both serve as a backstop". Also, what's the meaning of "central repo market" in this context? I am familiar with repo markets in traditional finance and you made a good job explaining it as part of the paper. However, I'm not sure how to apply this concept here.

**Comment by adit313** [comment]
Good questions and points, breaking down my responses by slide.

On slide 17, you are quite correct that foreign reserves aren't a magic bullet. We tired to use softer language by saying it offers an "options" to prevent hyperinflation, but maybe we change that to "an additional tool" or further soften the language.

It's not a magic bullet though, central banks and especially foreign reserves can be quickly overwhelmed by political and economic factors. Investopedia has a really good summary in their [article on currency crises](https://www.investopedia.com/articles/economics/08/currency-crises.asp).  The relevant section is "Fighting a Currency Crisis" but in summary they say: 

> Central banks cannot prop up the exchange rate for prolonged periods due to the resulting decline in foreign reserves as well as political and economic factors such as rising unemployment. Devaluing the currency by increasing the fixed exchange rate also results in domestic goods being cheaper than foreign goods, which boosts demand for workers and increases output.
> 
> In the [short run](https://www.investopedia.com/terms/s/shortrun.asp), devaluation also increases interest rates, which must be offset by the central bank through an increase in the [money supply](https://www.investopedia.com/terms/m/moneysupply.asp) and an increase in foreign reserves. As mentioned earlier, propping up a fixed exchange rate can eat through a country's reserves quickly, and devaluing the currency can add back reserves.
> 
> Investors are well aware that a devaluation strategy can be used, and can build this into their expectations—much to the chagrin of central banks. If the market expects the central bank to devalue the currency—and thus increase the exchange rate—the possibility of boosting foreign reserves through an increase in [aggregate demand](https://www.investopedia.com/terms/a/aggregatedemand.asp) is not realized. Instead, the central bank must use its reserves to shrink the money supply which increases the domestic interest rate. 

Argentina is a good example of where foreign reserves can't stabilize a country's currency indefinitely. [1976](https://en.wikipedia.org/wiki/1976_Argentine_coup_d%27%C3%A9tat) to the mid 1980s [was not a good time for Argentina](https://en.wikipedia.org/wiki/Dirty_War) [to put it mildly](https://en.wikipedia.org/wiki/Dirty_War#Human_rights_violations). Foreign reserves can only do so much and investors price in the stability ahead of time. So by the time the foreign reserves start getting deployed, investors are probably already heading for the exits as the foreign reserves were well known. Also, there is only so much risk investors are willing to tolerate and regular regime changes, economic collapse, and [ongoing wars](https://en.wikipedia.org/wiki/Falklands_War) are going to introduce far too much systemic risk for something like foreign reserves to manage. 

There are far better papers written about currency crises that I am happy to direct you towards but they are very dense and academic, [I particularly really like this one by the Federal Reserve of San Francisco](https://www.frbsf.org/economic-research/wp-content/uploads/sites/4/wp11-22bk.pdf). Also, keep in mind that not all of it is relevant and it's difficult to know what parts are irrelevant. As an example, you can ignore all the complications from the banking or credit sectors. Crypto doesn't really have lending or credit facilities. It may seem like you can "borrow" in crypto, but no matter how you borrow, you generally have to post collateral in excess of the loan amount. Meaning any sort of "lending" done through things such as AAVE, Compund, Block.fi, etc. actually reduces supply in the market the exact opposite dynamic of traditional lending.

Happy to change the language, especially if it is unclear that it's only an additional option that isn't guaranteed to work, as it is an important distinction. Foreign currency reserves only do so much. A good example of this being relevant to Crypto is Terra. Even though Terra is backed by some BTC, that BTC has to be deployed smartly and will only do so much, especially if demand for Luna (Terra's native token) precipitously drops. We'll look at the language on that slide on our end and see if we can make more helpful edits.

p. 20 Great callout, completely slipped my mind that it's not a normal term, adding it into the deck.

p21. I hear that, we have the reference in the notes under each slide in the powerpoint version, but I'll look into getting those notes to show up in the .pdf. Maybe we move them onto the slides proper, I just didn't want the slides to get too busy with long URLs.

p24. Those asterisks were from an earlier draft. They originally meant those numbers were from January 1st 2022. I've removed the asterisks as we now have the footnote.

p27. Changed the color. We were trying to use the brand colors of the respective projects, but everyone wants to use Coinbase blue for some reason. We've just made them purple.

p28. Good callout. We wanted to callout the custodial coins specifically which is why we didn't think to put in lilac as it is just the "other" category. It's now been added.

p32. Sorry about that, it's a waterfall chart that breaks down the 100% total. We use them in finance a lot, because it's an easy way to see if the total adds up to 100%, and the relative proportions. The fact that it goes down and up is really confusing on a slide that is already too dense. We've streamlined it to just go down so you can see what the individual pieces are.

Screen Shot 2022-05-08 at 4 34 58 PM

p33. Haha, you raise a very accurate point. I am probably a bit too pro-central banks and think a bit too highly of their competence. You will be happy to know that my co-founder Theresa is not and she'll keep me honest. I think softening that language is a good idea, and especially calling out that instances when they get it wrong like 2008, 2022, etc.

p44. You have no idea how curious I am about this... I literally check it everyday as soon as I get up. [Still nothing.](https://tether.to/en/transparency/#reports) Their last report was December 31st on the dot.... I'm really, really curious why their March 31st report is now 1.5 months late... It might be nothing, but I am deeply suspicious especially as it's the only way to see the credit rating of their internal assets.

p45. You are very right, it's probably more accurate to say "Multi-chain networks with cross-chain interaction". We've made that update.

p51. Embarrassing typo, it's been updated.

p55. Added axis.

p59. For now what I would say is that what we are suggesting is that DOT could be the agreed upon reserve currency. Right now in the fiat world, [that's the place of the US Dollar](https://en.wikipedia.org/wiki/International_use_of_the_U.S._dollar), we were suggesting that it could be DOT in the crypto world, or at least for stablecoins on the Polkadot network. Basically it's a currency everyone agrees is "worth something". In the repo market, if you trade securities, you have to pay for them in US dollars because everyone agrees on that, can't use shares or treasuries or bonds, only USD. On Polkadot, if there ever was a repo market, all the assets should be priced in and settled in DOT.

Honestly, we really didn't do the complexity of anything to do with repo markets or importance of reserve currencies justice in this Phase I. You'll see why the reserve currency is so important with our improved multi-coin stablecoin implementation architecture we are going to submit for Phase II. In essence, the reserve currency backs your currency, so its utility and choice are INCREDIBLY important to the stability of the overall network. As an example, Terra used BTC so now it is tied to the value of BTC and any shocks to BTC might jump to Terra, a really good example of [financial contagion.](https://en.wikipedia.org/wiki/Financial_contagion) 

We are happy to drop slide 59, or change the language. We'll take another look at it and see if we can improve it, but unfortunately, the real answers you are looking for as to why it's important or necessary for a stablecoin are probably in the Phase II deck.

**Comment by takahser** [comment]
@adit313 thanks for going into my question in such detail, it's been really helpful and interesting. In general, I'm really satisfied with them. I have a few remaining points.

- i) quote:
  > p. 20 Great callout, completely slipped my mind that it's not a normal term, adding it into the deck.

  What do you mean by "deck". Are you referring to Phase II here?

- ii) I think you didn't update [your delivery repo](https://github.com/adit313/State-of-the-Stablecoin-Industry) yet, I didn't see any new commit. Maybe you forgot to push the changes?

  image

- iii) Feel free to check your mailbox:)

**Comment by adit313** [comment]
Sorry! Old habits die hard. "Deck" is consulting/banking slang for a powerpoint presentation. I think it comes from the old days when presentations were physically an actually deck of slides. I just meant I've updated it in the presentation I have saved on my hard drive.

I haven't pushed any changes yet, I was waiting until I got the full feedback, made all the changes and then could push a clean copy that way it doesn't get too confusing which version you should be looking at it. I'll push the updated version with all the changes this afternoon.

And yes, agree wholeheartedly with that e-mail, we'll be dropping the last slide. Let's keep it at just the summary.

**Comment by takahser** [comment]
@adit313 thanks for pushing the new report. I reviewed it again and I'm happy to approve this delivery. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stardust_1_takahser.md).
I'll forward the invoice, which should be processed within 2 weeks. Looking forward to M2!

**Comment by takahser** [comment]
@adit313 btw, it's also exciting to observe the current developments in the market, especially after reading your report and the criticism w.r.t. non-collateralised stable coins.

image

**Comment by adit313** [comment]
Absolutely! I already talked to David about changing our M2 to be a Terra Autopsy to cover the events of the past week. We've been watching every development and event very, very closely. I was on a 2 hour call this morning breaking down a lot of the dynamics for one of the professors at UPenn who are working on the regulatory front in the US and trying to publish some papers on stablecoin regulations. That's probably not going in the next deck, but just for your own knowledge, they didn't feel like it would lead to any major developments. A couple of politicians are probably going to make statements and noise over the coming weeks just to show they are doing something. From a practical policy/regulatory perspective, I'm of the opinion that this event isn't likely to have much contagion and is incredibly difficult to regulate in the first place. They agreed and we came out feeling like it isn't likely to lead to any specific regulations. Most of the focus is still on stablecoins like Tether.

Ultimately, we sort of expected this crash as you've already seen from some of our criticism. It will become clearer in the autopsy, but not much has changed in terms of the dynamics, things sort of happened exactly as I expected. 70%+ of all Terra was in Anchor before the crash, once the currency depegged and trust was slightly threatened, everyone ran for the exits. Large amounts of liquidity drained out of Anchor, Curve pools got saturated almost immediately, and from there, the fate of Terra was sort of sealed. Being the native coin of the network just doesn't have enough intrinsic utility to enable that high of a market cap. Especially considering the network was relatively lightly used. With 70%+ of Terra just on Anchor and Mirror being stopped by the SEC, it didn't seem like there was a rich community of third-party applications.

It was a hard crash to manage. I personally think if I was in Do Kwon's shoes, it would have made more sense to let LUNA fall much farther before deploying the BTC reserves. After deploying them so early they really had no more arrows in the quiver, whereas the "idea" of the Billions of BTC in stability reserves might have bought them more trust and stability and might have slowed the fall knowing there was market cap hardstop. Right now LUNA's market cap is 1/2 of what their BTC Reserves were.

Appreciate all the help so far, definitely let me know if there are things you'd like to see in the M2 breakdown.

Adit

**Comment by semuelle** [comment]
@adit313, have you published this anywhere yet, outside Github, that I can share?

**Comment by adit313** [comment]
Sorry, I still haven't made a good landing page, been too busy analyzing the Terra events and updates. I plan to spin up a webpage to showcase it later today. In the meantime, I know it's not idea, but it is at least uploaded to our website. 
[Link](https://stardust.finance/resources/StateofStablecoins.pdf)
https://stardust.finance/resources/StateofStablecoins.pdf

I'll make a nice landing page with a bit of an explainer later this afternoon.

**Comment by adit313** [comment]
Also, I think you asked abut this tweet.
https://twitter.com/hasufl/status/1523817151471230976

The long story short is Binance suspended any order that had a price less than 70 cents, so you couldn't sell or buy Terra for less than $0.70. The legality of that is questionable, but seeing as Binance operates out of the Cayman Islands/Seychelles and officially doesn't do business in the US, it's hard to know who can regulate them. That being said, I haven't been able to identify if they are an investor, I know Coinbase Ventures has funded them, but I don't know about Binance.

**Comment by RouvenP** [comment]
hi @adit313, we transferred the payment today. Thanks!

**Pull request merged**
