### PR TITLE
Centrifuge GSRPC v2 milestone 2

### PR DESCRIPTION
**Pull request by mikiquantum**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1281

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @mikiquantum someone will take a look at it shortly.

**Comment by niklabh** [comment]
Hey team, i have submitted an external evaluation: https://github.com/w3f/Grant-Milestone-Delivery/pull/895

**Comment by semuelle** [comment]
I see that you have been active on the evaluation PR, @mikiquantum. Thanks for that. I just reviewed the evaluation and only added one clarifying comment. Feel free to continue the conversation here or there. Otherwise, ping one of us here when we should have another look.

**Comment by mikiquantum** [comment]
@semuelle For visibility completed the changes suggested and updated the delivery notes with latest commit:
https://github.com/w3f/Grant-Milestone-Delivery/pull/895#discussion_r1245625111
Let us know if we need to do anything else. 
Thank you!

**Review by semuelle — APPROVED** [review]
Thanks for the quick update, @mikiquantum! Your milestone is hereby accepted. You can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/centrifuge-gsrpc-v2_2_niklabh.md).

I have forwarded your invoice for processing.

**Comment by mikiquantum** [comment]
Thanks @semuelle and team!

**Comment by mikiquantum** [comment]
@semuelle any idea when the payment will be issued? All the best.

**Comment by keeganquigley** [comment]
Hi @mikiquantum I see that we sent the invoice over 2 weeks ago so I will ping the operations team internally and get back to you.

**Pull request merged**
