### PR TITLE
Polkadart Milestone 4

### PR DESCRIPTION
**Pull request by leonardocustodio**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2004

### CODE REVIEW

**Comment by justkawal** [comment]
🎉 🎉

**Comment by semuelle** [comment]
Sorry for the wait, @leonardocustodio. @diogosmendonca will look into it soon.

**Comment by dsm-w3f** [comment]
Thanks @semuelle I'll take a look at this evaluation.

**Comment by dsm-w3f** [comment]
@leonardocustodio thank you for the milestone delivery. Please take a look at the evaluation document [in this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by justkawal** [comment]
> @leonardocustodio thank you for the milestone delivery. Please take a look at the evaluation document [in this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144) and provide proper answers and fixes. Let me know when I can continue this evaluation.

Hey @dsm-w3f Sorry for the trouble, the fixes are now done.

**Comment by justkawal** [comment]
@dsm-w3f 
Also on the sr25519:
We think writing in pure dart code was a good choice although it took intensive testing and hours.

- Writing in pure dart makes it easy to maintain codebase with lesser dependencies.
- Bridging rust to flutter still lacks supports for some parts of intermediate code generation.
- Good amount of refactoring would be needed to align code with `async` native calls.
- With code written in pure dart, it enables to cover all the platforms and provide fixes without depending on 3rd parties.

**Comment by justkawal** [comment]
@dsm-w3f 
For the docker: surprisingly it worked on my side, I guess it’s a low memory issue maybe.
Can you try, giving higher swap and memory in docker-settings -> resources….

Thanks for your time.

**Comment by dsm-w3f** [comment]
@justkawal thank you for the answers and fixes. I updated the evaluation document. I'm still having problems to run the metadata automated tests. Could you please inform what is the configuration of the machine that you was able to run this tests? Please see more details in the evaluation document [in this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144).

**Comment by justkawal** [comment]
> [in this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144)

Hey @dsm-w3f,

Seed (Dev-Phrase): `bottom drive obey lake curtain smoke basket hold race lonely fit walk`

Derivation paths for signatories are: `//TeslaS1`, `//TeslaS2`, `//TeslaS3`
Derivation paths for receiver account: `//TeslaR`

So in the latest update to main branch, I had mentioned the seed (dev-phrase) in the `comment` in the file `multisig_example.dart`: https://github.com/leonardocustodio/polkadart/blob/020eae9fae70e71f838eb94623b43993de223b19/packages/polkadart/example/multisig_example.dart#L8

Also as I can see in the issue image of `multisig_example.dart` at `line 26`, So now in the updated code, `line 26` is having comment and not any code.
Here: https://github.com/leonardocustodio/polkadart/blob/020eae9fae70e71f838eb94623b43993de223b19/packages/polkadart/example/multisig_example.dart#L26

So, It seems that main is not up-to-date, Please can you do a git pull again from the main branch again or a fresh pull maybe?

Thank you so much for your time.

**Comment by justkawal** [comment]
@dsm-w3f 
Also to test and run the multisig example, we don't need polkadart_cli as we're not using it in that respective example.
So, to run and test multisig_example.dart, you can just run `dart pub get` in side that package and the run that `multisig_example.dart` file.



For the issue in examples: To add `polkadart_cli` and `polkadart` in pubspec.yaml
I guess I already fixed that previous week: https://github.com/leonardocustodio/polkadart/blob/020eae9fae70e71f838eb94623b43993de223b19/examples/pubspec.yaml#L30

So, maybe just needs a `git pull`, or a `fresh clone`.

Thank you so much. ❤️

**Comment by dsm-w3f** [comment]
@justkawal thank you for the answer. Now it worked for me. The evaluation document was updated in [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144). It would be nice to have these instructions added to the documentation. The only point that is still pending in this evaluation is the memory problem while running the automated tests. Please let me know when I can continue this evaluation.

**Comment by justkawal** [comment]
@dsm-w3f 
Sure, I'll have a look into the memory thing today. Sorry about that.

Either way, can you try? with:
`dart pub global activate melos`
`melos test`

**Comment by dsm-w3f** [comment]
@justkawal I tried these commands and the behavior was the same as running using docker. The memory is consumed until get all memory from the machine.

**Comment by justkawal** [comment]
@dsm-w3f 
Can you do a pull and try again?
I tested it on a lower memory system now and it seems to be working fine.

Note: (The build might take some time to build around (8-9 mins))

Thank you.

**Comment by dsm-w3f** [comment]
@justkawal thank you for the improvements and fixes. It worked now. I updated the evaluation document in [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144). Great job! @semuelle this evaluation is accepted by my side and [the evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1144) is open.

**Comment by justkawal** [comment]
@dsm-w3f @semuelle 
Thank you so much for your time team.
💯🎉

**Comment by leonardocustodio** [comment]
I'm just filling the form, all milestones we have received as USDC-ERC20, isn't that possible anymore? We must always used AssetHub now?

**Comment by keeganquigley** [comment]
Hi @leonardocustodio yes that's correct, our payment options changed recently and we no longer offer ETH mainnet payments. Does this work for you?

**Comment by leonardocustodio** [comment]
Ok @keeganquigley , I've submitted the invoice with the new address and also sent a PR amending the application with the new address: https://github.com/w3f/Grants-Program/pull/2245

**Comment by keeganquigley** [comment]
Thanks @leonardocustodio much appreciated, your milestone evaluation has been passed but I will wait for the amendment to be approved before merging the delivery to avoid any confusion. Congrats on finishing the grant!

**Comment by semuelle** [comment]
Amendment and evaluation are merged, milestone is accepted. Congrats, @leonardocustodio.

**Comment by leonardocustodio** [comment]
Thanks guys, exicited to see all new flutter apps to come to polkador usong flutter 😁

Filled the invoice and hopefully I can think of another project that can be beneficial for everybody soon

**Comment by leonardocustodio** [comment]
@keeganquigley may I ask how the payments work on AssetHub? Is it on Kusama and not Polkadot? I was looking into Polkadot AssetHub and it seems there are no assets with value over there.

**Comment by RouvenP** [comment]
hi @leonardocustodio we sent the payment today

**Comment by leonardocustodio** [comment]
Hello @RouvenP , received, thank you very much, hope to work with you guys again soon.

**Pull request merged**
