### PR TITLE
ISMP Delivery

### PR DESCRIPTION
**Pull request by Doordashcon**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1645 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @Doordashcon someone will take a look in the next few days.

**Comment by Doordashcon** [comment]
Hi @semuelle, Thanks for your response. There was no change in the implementation from our application, ISMP was under development before the application.

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the milestone delivery. I did a first round of evaluation in both milestones and provided feedback in evaluation documents [1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_1_dsm-w3f.md) and [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_2_dsm-w3f.md). I notice that there are some deliverables missing like the article and testing guides. Furthermore,  commits are happening during the evaluation. Are the milestones complete and ready to be evaluated? If not, please complete them and let me know when I can continue this evaluation. There is no need to rush with the deliveries, at least from our side, since you are delivering far before the schedule presented in the application.

**Comment by Doordashcon** [comment]
Hello @dsm-w3f and thank you for the review.

The new commits are cosmetic changes but doesn't imply an ongoing work regarding the ISMP application milestones, evaluation can continue on the main branch with the links provided.

Regarding the notes on Milestone (0b); 
- For **ismp-rs**, the prerequisites and instructions to run without docker have been added to the README.

- As for running **substrate-ismp** without docker, the test commands and prerequisites have been aded to the README file. We also provided a simple demo [here](https://github.com/polytope-labs/substrate-ismp/tree/main/ismp-demo).

Milestone (0c); 
- Currently, running `cargo tarpaulin` on **ismp-rs** results in a 56.10% coverage but using nightly on the entire workspace (i.e `cargo +nightly tarpaulin --all-features --workspace`) presents a slightly higher coverage of 56.74%.

- For the warnings gotten from `susbtrate-ismp` (i.e `It is deprecated to use hard-coded constant as call weight`) we expect teams to generate their own weight utilizing the [benchmarks](https://github.com/polytope-labs/substrate-ismp/blob/main/pallet-ismp/src/benchmarking.rs) provided, the current weights are placeholders.

- Currently, running `cargo tarpaulin` on **substrate-ismp** results in a 28.15% coverage but using nightly on the entire workspace (i.e `cargo +nightly tarpaulin --all-features --workspace`) presents a much higher coverage of 35.91%. Please note that some files are standalone and do not interact with the current tests. For further testing you'll be invited to our relayer repo.

Regarding Milestone (0d), **ismp-rs** is a primitive for **substrate-ismp**; therefore, an article that covers both as well as a [book](https://substrate-ismp.polytope.technology/) describing how teams can integrate ISMP will be announced together, currently there are support channels set up for early teams looking to integrate before this time.

Any further work being carried out is part of our efforts to add more features and improve the overall quality of the projects.

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the improvements and fixes. I updated the evaluation documents from [M1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_1_dsm-w3f.md) and [M2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_2_dsm-w3f.md). I missed a guide to run the demo. Could you provide it?

**Comment by Doordashcon** [comment]
Hello @dsm-w3f and thank you for the review, you currently have access to our relayer repo. pls run this [test](https://github.com/polytope-labs/tesseract/blob/main/integration-tests/src/lib.rs) and watch the block explorer on both chains for the events. Carefully look at the extrinsics and relative events defined in the [demo](https://github.com/polytope-labs/substrate-ismp/blob/main/ismp-demo/src/lib.rs)

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the answer. I tried to run the test case mentioned but looks like a network with parachains should be configured for that. I also saw the instructions in the book provided but they also look complex with many steps that need programming to configure. Could you provide an integration or system test, in a publicly available repository, that shows in an easy way the behavior of the system? I think would be easier for you to develop this example to show us the system working. You can try to use a zombienet, which makes easy to configure parachain related networks.

**Comment by Doordashcon** [comment]
Hi @dsm-w3f, Thank you for the review! Preparing a zombienet is beyond the scope of this application. For both M1 and M2, tests and testing guides ensuring functionality is present, including a walkthrough on the [Polkadot UI](https://twitter.com/PolytopeLabs/status/1666430470530256896?s=20).

We would like to invite you to our [Parachain repo](https://github.com/polytope-labs/hyperbridge/tree/blake2b) branch _blake2b_, which already integrates **substrate-ismp** to conduct further testing, you can use polkadot-lunch to set-up a test network.

After which head to the [relayer repo](https://github.com/polytope-labs/tesseract/tree/blake2b#integration-test-guide) and follow the integration testing steps.

Looking forward to your next review.

**Comment by dsm-w3f** [comment]
I followed these guides to setup the [relaychain](https://docs.substrate.io/tutorials/build-a-parachain/prepare-a-local-relay-chain/) and [parachain](https://docs.substrate.io/tutorials/build-a-parachain/connect-a-local-parachain/), using the polkadot as relaychain and hyperbridge-blake2b as the two parachain. But I couldn't do the communication between the two parachains. Could you help with this? Did I miss something?

**Comment by Doordashcon** [comment]
Hello @dsm-w3f, thank you for your quick response. Did you set up the relayer?

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the answer. Could you please provide an installation demo video for the software? There are some reasons for me to ask this. Some installation resources are being provided in private repositories, including installation instructions. The user must be able to install and use the scope of the grant without having privileged access to these repositories. Are you willing to disclose them as open source or another way of running the system will be provided? A video demo could be incorporated as installation instructions for the software. A live debugging call could be problematic to schedule and conduct, and cannot be used as user documentation, for this reason, would be better to provide a demo video.

**Comment by seunlanlege** [comment]
> @Doordashcon thank you for the answer. Could you please provide an installation demo video for the software? There are some reasons for me to ask this. Some installation resources are being provided in private repositories, including installation instructions. The user must be able to install and use the scope of the grant without having privileged access to these repositories. Are you willing to disclose them as open source or another way of running the system will be provided? A video demo could be incorporated as installation instructions for the software. A live debugging call could be problematic to schedule and conduct, and cannot be used as user documentation, for this reason, would be better to provide a demo video.
> 
>    

I'd like to note that this grant only covers pallet-ismp. Not the relayer, this is why the relayer is private. At least for now. Like you've rightfully noted the pallet installation isnt trivial. This is why we've provided an already integrated albeit private repo to speed things along.

We unfortunately cannot make either repos public at this time, neither can we record installation demos as this is also out of scope for this grant. This is why we provided an integration guide (which is covered by the grant). 


If the integration guide is too much to work with, the only alternative really is a private evaluation which from the grant application guidelines is a possibility. 

Pallet-ismp is fully functional and show off it's features in this video
https://twitter.com/polytopelabs/status/1666430470530256896

**Comment by dsm-w3f** [comment]
@seunlanlege I'll discuss your case internally and circle back to you soon.

**Comment by dsm-w3f** [comment]
@Doordashcon and @semuelle Our [grant guidelines](https://github.com/w3f/Grants-Program/) state that: "All code produced as part of a grant must be open-sourced, and it must also not rely on closed-source software for full functionality.". We understand that you plan to disclose the relayer as open-source in the near future. Let us understand better your plans with the product of this grant and also the forecast for disclosing the relayer as open-source.

**Comment by seunlanlege** [comment]
>  Let us understand better your plans with the product of this grant and also the forecast for disclosing the relayer as open-source.

The relayer will eventually be open-sourced, we're still finishing it up at this time. We expect this to happen no later than late july.

**Comment by dsm-w3f** [comment]
@seunlanlege thank you for the answer. I'll try again to run the system with all steps involved. If I can't make it work, we can schedule a call to try to debug it. Expect to hear from me at the beginning of next week.

**Comment by dsm-w3f** [comment]
@seunlanlege I tried again without success. See details in the [evaluation document of M2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_2_dsm-w3f.md). If you have any hints about the versions needed to run the system please let me know. I'll reach your team by the e-mail provided in the application to schedule a debugging call  to continue this evaluation.

**Comment by Doordashcon** [comment]
Hello @semuelle, a network setup with two parachains integrated with pallet ISMP would be required, to this end we would like to invite you to our private [Parachain](https://github.com/polytope-labs/hyperbridge/tree/blake2b) and [Relayer](https://github.com/polytope-labs/tesseract/tree/blake2b) repos. We've dedicated the blake2b branches for evaluation.

Please note that these repos should be located in the the same directory on your local machine.

You could use these guides to setup the [relaychain](https://docs.substrate.io/tutorials/build-a-parachain/prepare-a-local-relay-chain/) and [Parachains](https://docs.substrate.io/tutorials/build-a-parachain/connect-a-local-parachain/) for the network, after which head over to the Relayer and run using these [docker commands](https://github.com/polytope-labs/tesseract/tree/main#docker-guide), please include this flag `--network host` (i.e  `docker run --network host tesseract --config ./integration-tests/config.toml`) so localhost can be accessed from inside the container without port mapping.

You can also refer to this walkthrough of ISMP POST and Get request on the [polkadot UI](https://twitter.com/PolytopeLabs/status/1666430470530256896?s=20)

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the improvements and fixes. I was able to test manually the application using the ismpDemo project. However, the automated tests are still failing to compile with and without docker. Please adjust that for us to finish this evaluation. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ismp_2_dsm-w3f.md).

**Comment by Doordashcon** [comment]
Hello @dsm-w3f, Thanks for the review. Glad you were able to test the parachain transfers. To run the relayer integration tests inside the container, please run `RUSTFLAGS="-C link-args=-Wl,--allow-multiple-definition" cargo test`.

Also please note that all evaluation can now take place on the main branch.

**Comment by dsm-w3f** [comment]
@Doordashcon thank you for the improvements and fixes. The automated tests are passing now. The article was shared in private with me. The milestones are accepted. I'll forward the invoice internally and the payment should take place within two weeks. Great job!

**Pull request merged**
