### PR TITLE
QSTN - Milestone 1 (Delivery).md

### PR DESCRIPTION
**Pull request by qstnus**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1082

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @qstnus moving the conversation here, and thanks for the delivery. I updated the text to link to your original proposal's pull request. Can you also make the following changes?

- The **Application Document:** towards the top should link to your application, which in this case the link is https://github.com/w3f/Grants-Program/blob/master/applications/QSTN.md
- "Milestone 1 Example" should be changed to "Milestone 1" (above the delivery tables).
- Usually the links should be included in the tables themselves, but since you have all the links in the text above I think this should be okay. Optionally you could add links to each section of the text.

Thanks!

**Comment by qstnus** [comment]
Hello @keeganquigley,

Thanks for this information. The link has been added to the top. In terms of the deliverables, I kept the same original presentation but the order of information and flow is the same as the original grant milestone. 

Looking forward to next steps!

**Comment by keeganquigley** [comment]
Thanks @qstnus I updated it to get rid of the template text. Looks better now.

**Comment by keeganquigley** [comment]
Thanks again @qstnus I have started the evaluation, and I have the following comments:

- It's great to see that the app is live on Moonbeam, but the deliverables for this grant include custom pallets, presumably built into a local substrate node. Can you link me to these? Or am I to understand that these aren't built, as you pivoted to building Solidity contracts on Moonbeam instead?
- These changes aren't mentioned in the application, and I'm not seeing that any amendments were filed, which would be required to document these changes since they are rather significant.  Were these talked about at some point?

**Comment by qstnus** [comment]
Hello @keeganquigley ,

Thank you for the feedback. Post our engagement with engineers from the Polkadot Blockchain Academy, we opted to pivot to accelerate our time to market by transitioning to Solidity contracts on Moonbeam. This shift aligns better with our new multi-chain approach across EVM-compatible chains, facilitating business funding within our survey module.

I acknowledge the oversight in not updating our initial application. I seek guidance on amending our proposal and articulating the deliverables to align with Polkadot’s expectations. Your insight would be invaluable.

**Comment by keeganquigley** [comment]
Thanks for confirming @qstnus. After discussing the matter internally with the committee, I must inform you that, unfortunately, we can't accept the delivery as is, since it doesn't meet the technical requirements originally agreed upon. 

The reason we ask for amendments is to discuss significant changes such as these, because I would have been able to tell you earlier on that generally, our grants program doesn't support Solidity or Moonbeam development. This is partly because we aren't experts in the EVM field, and also because Moonbeam has its own [grants program](https://moonbeam.foundation/grants/) which caters to these types of projects.

Therefore, I believe this situation leaves two options:
- If you are still interested in developing the substrate pallets/modules, you could file an amendment to extend the timeline and continue to work on the grant as is. Although I will point out that this would need two approvals from the committee, who will likely take this situation into account.
- Alternatively, we could go ahead and reject the delivery and close the grant. That way you could try other funding means such as the Moonbeam grants program, although I'm not sure if they offer retroactive payments or not.

Please let me know and thanks for your understanding.

**Comment by qstnus** [comment]
Hello @keeganquigley ,

Thanks for this information. I spoke with our CTO and we can deliver the original scope in a few weeks. We will keep our Moonbeam implementation and proceed with the custom pallet built into a local substrate node. 

The original application has been amended. In regards to our commitment to DOT, we are excited to continue building in the ecosystem and applied for the Polkadot Blockchain Academy. Please let me know the next steps!

**Comment by keeganquigley** [comment]
Thanks @qstnus however I'm not seeing an amendment. Did you submit a PR [here](https://github.com/w3f/Grants-Program/pulls)?

**Comment by qstnus** [comment]
Hello @keeganquigley,

Sorry about that. I made the PR and signed the CLA agreement. Let me know if you have any questions. Thanks!

**Comment by keeganquigley** [comment]
Hi @qstnus just checking if you are you still on track to submit this by the end of this week?

**Comment by qstnus** [comment]
Hello @keeganquigley,

To my understanding - we extended the timeline to December based on the last revision with the W3F. Please confirm!

P.S. The timeline is 15 months - we received initial approval October 2022

Link: https://github.com/w3f/Grants-Program/pull/2030#event-10591009042

**Pull request closed without merging**
