### PR TITLE
add DNFT milestone1

### PR DESCRIPTION
**Pull request by bleemer4**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @bleemer4. We will look into it as soon as possible. In the meantime, could you add links for the deliverables 0a-d to the table of deliverables? Thanks!

**Comment by Noc2** [comment]
@bleemer4  Thanks again for the delivery. I started to look into it. Could you take a look at my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DNFT_1_Noc2.md) and let me know if you have any questions? Also could you explain what you mean with nft2006?

**Comment by alxs** [comment]
@bleemer4 any updates here?

**Comment by bleemer4** [comment]
> @bleemer4 any updates here?

yep, we will submit a detailed version this week

**Comment by bleemer4** [comment]
> @bleemer4 Thanks again for the delivery. I started to look into it. Could you take a look at my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DNFT_1_Noc2.md) and let me know if you have any questions? Also could you explain what you mean with nft2006?

Hi, @Noc2 , the EIP 2006 link you mentioned is the submit record, our NFT2006(ERC2006) is set to  a new ERC standard. To make clear, we're trying to make solidity version of ERC2006, and a video introduction. we'll submit a full version covering the question you mentioned soon.

**Comment by bleemer4** [comment]
> Thank you for the delivery, @bleemer4. We will look into it as soon as possible. In the meantime, could you add links for the deliverables 0a-d to the table of deliverables? Thanks!

Fine, will do.

**Comment by Noc2** [comment]
> > @bleemer4 any updates here?
> 
> yep, we will submit a detailed version this week

@bleemer4  Any updates? It’s now over three weeks.

**Comment by bleemer4** [comment]
> > > @bleemer4 any updates here?
> > 
> > 
> > yep, we will submit a detailed version this week
> 
> @bleemer4 Any updates? It’s now over three weeks.

We have updated more [detail](https://github.com/w3f/Grant-Milestone-Delivery/pull/213/commits/11a443c7ea28785fd9a886e7b5cd637b494fa7d3).
Node & front Repo have been updated.

1. Project Intro Vedio link: https://youtu.be/HkQorjfe4Z8
2. Substrate MVP Product Vedio link: https://youtu.be/_vHdjrVKNkg
3. Project Doc: https://dnft.gitbook.io/dnft/
4. About ERC2006: 
    It's a new ERC token(NFT) standard towards AI Data/Model we want to propose, facing 3 problems when dealing AI Data/Model  with the NFT solutions:
    1) Data type&content massive.When we usually come up with a conception of "data set", it's different with the common NFT ways, handling a NFT with  a pic, gif.etc.
   2)Public/Organization Data copyright. Public/Organization assets can be handled by MultiSign. When it comes to NFT, equity fragmentation may be a solution.
  3) Privacy protection, as we all know, NFT with a metadata link , which can be seen by anyone. We want to update the metadata with encryption algorithm, MPC, ZKP, which we called encrypted NFT.
  More details, please refer https://dnft.gitbook.io/dnft/erc-nft-2006-standard.

**Comment by Noc2** [comment]
Thanks for the update. It looks much better now. I have two follow-up comments/questions:

- I guess you are still working on integrating more tests, correct? 
- Regarding ERC2006 or NFT2006, how did you come up with the name? The name is usually based on the github pull request number to the following repo: https://github.com/ethereum/EIPs (at least that’s the case for all other standards). Because of this, the name is quite confusing.

**Comment by semuelle** [comment]
@bleemer4 Were you able to reproduce and fix the issues David had with the building? And could you answer the questions in his last comment?

**Comment by mmagician** [comment]
@bleemer4 We haven't heard from you in almost a month now. Please let us know if you are planning to complete the work, otherwise we will close this PR and terminate the grant if we don't hear back from you within the next 2 weeks.

**Pull request closed without merging**
