### PR TITLE
milestone 1 completion for supersig_fellowship

### PR DESCRIPTION
**Pull request by decentration**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by decentration** [comment]
Hi Diogo @dsm-w3f, thanks for the swift eval!

It seems that for pallet_supersig you are on incorrect branch. You should be on [v0.9.37-fix-unbounded](https://github.com/decentration/pallet_supersig/tree/polkadot-v0.9.37-fix-unbounded). I recognise the weights errors and that was for a previous branch. 

Regarding the apps fork testing: (my apologies!) i did not update the correct branch in the delivery doc. The branch should be [main-fellowship-1](https://github.com/decentration/apps/tree/main-fellowship-1), then you should no longer have those errors.

Re: running the version of supersig using the [blog post](https://decentration.medium.com/add-supersig-to-your-chain-789de9356de1) from March 8th. Can you provide a quick video or screenshots for what your issue is. You should definitely be able to add any account to the supersig. Though i think i can guess the issue. One thing to note is that if you propose a call, it does not mean it is a vote, therefore you need to approve call separately after you make the proposal. So if you propose a call as Alice, you then need to approve_call as Alice thereafter. Then if you added Bob. You now have 2 members. So if you want to add Charlie, then you need to proposal the call to add member, then after both Alice and Bob need to approve the call. 

I hope that helps, let me know how you get on : )

**Comment by decentration** [comment]
@dsm-w3f... i've updated [this guide](https://decentration.medium.com/add-supersig-to-your-chain-789de9356de1) with the fresh branches. i.e. `main-fellowship-1` for the frontend, and `v0.9.37-fix-unbounded` for the substrate-supersig-template (node-template).

**Comment by dsm-w3f** [comment]
@decentration thank you for the improvements and fixes. We are almost finishing this evaluation. The parts that didn't work before now worked for me. Could you please explain better the and provide a testing guide for the deliverable 2?

**Comment by decentration** [comment]
@dsm-w3f  thats great i'm glad everything passed with ease. 

To test pallet_supersig is `cargo test` which i believe you have done. 
And then for step 2, the linting needs to to pass. `yarn lint`, if it passes then it resolves what we want. Something that can be pulled upstream without causing errors.

In the next milestone (milestone 2 ) we will be creating our own custom UI which will have e2e tests that simulate user behaviour.

**Comment by decentration** [comment]
@dsm-w3f just for clarification, the frontend was completed in the previous, so we are not actually testing the frontend development in deliverable 2 of this milestone, because that is already done, we are just simply make sure there are no errors when linting. Let me know if that doesn't create more clarity?

**Comment by dsm-w3f** [comment]
@decentration thank you for the answers and fixes. I tried to run the commands that you mentioned but without success. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/supersig_1_dsm-w3f.md) for details.

**Comment by decentration** [comment]
@dsm-w3f looks like its almost there. There were some things in the incorrect alphabetical order which is caught by the linting. 

I have just pushed the changes which should remove all 3 errors. 

If you `git pull` the `origin/main-fellowship-1` branch and then `yarn lint`, it should now successfully complete. 

Expect to see one warning:

```
4:15  warning  '__AugmentedRpc' is defined but never used  @typescript-eslint/no-unused-vars
```
but we need to keep that in place because it is actually used.

**Comment by dsm-w3f** [comment]
@decentration thank you for the answer and fixes. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by decentration** [comment]
Thanks @dsm-w3f

**Comment by RouvenP** [comment]
hi @decentration we just transferred the payment

**Pull request merged**
