### PR TITLE
Substrate Swift Api milestone 2

### PR DESCRIPTION
**Pull request by dileping**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/General-Grants-Program/pull/333

### CODE REVIEW

**Comment by dastansam** [comment]
hey @dileping,

[here's](https://github.com/w3f/Grant-Milestone-Delivery/pull/928) the external evaluation of your milestone delivery. It looks good in general, with the except of few failing integration tests. Let me know if there is bug in tests or if I am not running them correctly.

**Comment by ypopovych** [comment]
> hey @dileping,
> 
> [here's](https://github.com/w3f/Grant-Milestone-Delivery/pull/928) the external evaluation of your milestone delivery. It looks good in general, with the except of few failing integration tests. Let me know if there is bug in tests or if I am not running them correctly.

Integration tests need an environment variable `TEST_MNEMONIC` set with a 12-word mnemonic(one from the test application can be used). Inside our repo, it's set in the GitHub Action as a secret. We will move tests to the local test node for milestone 3, but for now, they are running on the Westend test net.  

The simplest way is to run tests from console as `TEST_MNEMONIC="<mnemonic-from-testapp>" swift test`

**Comment by dastansam** [comment]
> > hey @dileping,
> > [here's](https://github.com/w3f/Grant-Milestone-Delivery/pull/928) the external evaluation of your milestone delivery. It looks good in general, with the except of few failing integration tests. Let me know if there is bug in tests or if I am not running them correctly.
> 
> Integration tests need an environment variable `TEST_MNEMONIC` set with a 12-word mnemonic(one from the test application can be used). Inside our repo, it's set in the GitHub Action as a secret. We will move tests to the local test node for milestone 3, but for now, they are running on the Westend test net.
> 
> The simplest way is to run tests from console as `TEST_MNEMONIC="<mnemonic-from-testapp>" swift test`

thank you for swift response! Indeed, integration tests are passing now with a mnemonic from the test app. I think it would be nice if it was documented in the testing guide or in the README. In any case, all issues are addressed and this delivery lgtm

**Comment by ypopovych** [comment]
> > > hey @dileping,
> > > [here's](https://github.com/w3f/Grant-Milestone-Delivery/pull/928) the external evaluation of your milestone delivery. It looks good in general, with the except of few failing integration tests. Let me know if there is bug in tests or if I am not running them correctly.
> > 
> > 
> > Integration tests need an environment variable `TEST_MNEMONIC` set with a 12-word mnemonic(one from the test application can be used). Inside our repo, it's set in the GitHub Action as a secret. We will move tests to the local test node for milestone 3, but for now, they are running on the Westend test net.
> > The simplest way is to run tests from console as `TEST_MNEMONIC="<mnemonic-from-testapp>" swift test`
> 
> thank you for swift response! Indeed, integration tests are passing now with a mnemonic from the test app. I think it would be nice if it was documented in the testing guide or in the README. In any case, all issues are addressed and this delivery lgtm

Yeah. My bad. I was too focused on the test app and forgot to add instructions on how to run integration tests from the repo

**Comment by keeganquigley** [comment]
Hi @dileping thanks for the delivery. The external evaluation has been accepted. Before I merge the milestone, can you update [this line](https://github.com/tesseract-one/Substrate.swift/blob/main/LICENSE#L189) of your license file to replace the boilerplate brackets with your copyright owner information date, in order to apply the license? Thanks!

**Comment by dileping** [comment]
> Hi @dileping thanks for the delivery. The external evaluation has been accepted. Before I merge the milestone, can you update [this line](https://github.com/tesseract-one/Substrate.swift/blob/main/LICENSE#L189) of your license file to replace the boilerplate brackets with your copyright owner information date, in order to apply the license? Thanks!

Hi @keeganquigley, thanks for accepting the milestone! It was a long one :)

**Comment by keeganquigley** [comment]
Thanks @dileping happy to accept the milestone. Yes so glad to see it completed!

**Pull request merged**
