### PR TITLE
sr25519 donna milestone 1

### PR DESCRIPTION
**Pull request by TerenceGe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will try to look into it as soon as possible.

**Comment by Noc2** [comment]
Hi @TerenceGe sorry for the late reply. I started to look into your delivery. It looks very good. I just have one questions so far, what’s the meaning of these “XXX hack” comments, e.g. https://github.com/TerenceGe/sr25519-donna/blob/dc5ead4ea72ecfe86dc588b55bdaeb621b735bb0/src/merlin.c#L219 and could you potentially replace them with something more understandable.

**Comment by TerenceGe** [comment]
Thanks, @Noc2. I use the implementation of the original author of merlin lib https://github.com/hdevalence/libmerlin/blob/4bf62284965eeeb5f11454b30289964afa4d5086/src/merlin.c#L236 , I thinks it's not necessary now and just removed it.

**Comment by Noc2** [comment]
Thanks for the quick reply. In this case could you add some kind of attribution to the files (and potentially others). Independent of it, I’m happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sr25519_donna_1_Noc2.md) and will forward your invoice internally.

**Comment by TerenceGe** [comment]
Thanks you @Noc2 , I’ll add some attributions for this later.

**Comment by RouvenP** [comment]
Hi @TerenceGe we sent a test transaction last Friday. could you please confirm if received?

**Comment by TerenceGe** [comment]
@RouvenP Ok, I received 0.01

**Comment by RouvenP** [comment]
@TerenceGe thanks for confirming, transfer is done

**Comment by TerenceGe** [comment]
@RouvenP thanks, already received.

**Pull request merged**
