### PR TITLE
subdex grant milestone 1 deliverables

### PR DESCRIPTION
**Pull request by whalelephant**
# Milestone Delivery Checklist

- [x ] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x ] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x ] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery of the milestone. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@whalelephant Congratulations! I've accepted your delivery now, you can see the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/68).
One question out of curiosity: What is the functionality of the [`Take`](https://subdex.network/#/take) tab?

**Comment by whalelephant** [comment]
Hey @mmagician, thank you for the acceptance!

The `Take` tab is part of the next milestone we had planned but was not made clear on the medium post, it is UI for withdrawals to another parachains

**Comment by mmagician** [comment]
@whalelephant A request from the invoice team: Could you please submit another invoice that includes your address on it please?

**Comment by whalelephant** [comment]
@mmagician ok done!

**Comment by whalelephant** [comment]
@mmagician was wondering if they received the new invoice and if it is ok? thanks!

**Comment by mmagician** [comment]
@whalelephant Yes, thanks, we received it. Bear in mind that due to the holiday period the payment processing might take longer than usual.

**Comment by whalelephant** [comment]
@mmagician any chance we can get an update on this? thanks!

**Comment by mmagician** [comment]
@whalelephant Your invoice is with us and being processed. Please allow a couple more days & apologies for the delays caused.

**Comment by RouvenP** [comment]
hi @whalelephant apologies for the delay. We sent a test transaction today, could you please confirm if received?

**Comment by fyang1024** [comment]
Hi @RouvenP yep, we've received it. Thanks.
[
Screen Shot 2021-01-07 at 9 57 36 am
](url)

**Comment by RouvenP** [comment]
@fyang1024 thanks for confirming. We just sent the payment.

**Comment by iorveth** [comment]
@mmagician @RouvenP Thank you!

**Pull request merged**
