### PR TITLE
wasm runtime fuzzing - milestone 4 delivery

### PR DESCRIPTION
**Pull request by pventuzelo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @pventuzelo As always, thanks for the delivery and we will try to look into it as soon as possible. We got three additional milestone deliveries today alone, so it might again take a little bit longer.

**Comment by pventuzelo** [comment]
Sure no worries, Thanks @Noc2 ;)

**Comment by Noc2** [comment]
I’m happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/wasm-runtimes-fuzzing_4_Noc2.md) and will forward your invoice internally.

**Comment by pventuzelo** [comment]
Awesome, Thanks @Noc2 ;)

**Comment by RouvenP** [comment]
hi @pventuzelo we just sent a test transaction. could you please confirm if received?

**Comment by pventuzelo** [comment]
Confirmed @RouvenP ;)

**Comment by RouvenP** [comment]
@pventuzelo thanks for confirming. Transaction is done.

**Pull request merged**
