### PR TITLE
Mobile Game Framework for Substrate Millestone 3

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@enfipy After an initial round of testing, I've ran into some issues. I've outlined them in this [draft PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/207). If these are not obvious to you and you think it might be due to my setup (I'm on OSX), it might be easier to jump on a quick call to try to debug. If so, please just email me and propose a good time for you.

**Comment by mmagician** [comment]
@enfipy Congratulations on completing the final milestone of your project! There were a few more minor issues that I've logged [in my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/207), but I've accepted your project as they're non-critical and the deliverables from the application are fulfilled. Well done and good luck with the future development of your game & tools.

**Comment by RouvenP** [comment]
hi @enfipy we sent a test transaction today. Could you confirm if received?

**Comment by enfipy** [comment]
Hi, @RouvenP we received the transaction. Thank you

**Comment by RouvenP** [comment]
thanks for confirming @enfipy. we transferred the rest yesterday.

**Pull request merged**
