### PR TITLE
Substrate Swift Api milestone 3

### PR DESCRIPTION
**Pull request by dileping**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/General-Grants-Program/pull/333

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @dileping and thanks for the delivery, as well as the well-written testing guide. It is appreciated! I was able to through the guide to successfully run `BalanceTransaction` and `CustomStaticConfig` but I'm not seeing in the docs how to run the `IntegrationTests`, `KeychainTests`, and `SubstrateTests`. I know these were built for milestone 2 but just want to make sure they still work. Can you help me out with how to run these in Xcode? I tried running them with the M2 instructions but am running into errors. Thanks.

**Comment by keeganquigley** [comment]
Ah nvm @dileping the tests were failing because of an incorrect SDK path. I was able to invoke the correct path using `sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer`

Now `swift test` and `swift build` are running successfully. Thanks, will update application accordingly.

**Comment by dileping** [comment]
Hi @keeganquigley, sorry I missed your messages yesterday. Glad you resolved everything. Please let me know if you need any other help with testing.

**Comment by keeganquigley** [comment]
Thanks @dileping I'm happy to pass the milestone. Here you can find my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/swift_api_3_semuelle.md). Great work! I hope to see more native iOS apps utilize the library in the future.

**Comment by keeganquigley** [comment]
@ypopovych I'm not finding an invoice for this milestone. Do you know if your team submitted one already when this was delivered? Thanks!

**Comment by dileping** [comment]
@keeganquigley Thanks a lot for merging! It was a long road for this grant :) I believe it can be helpful for wallets as well, not dApps only. The demo we are about to make for milestone 2 of the [Tesseract native libraries grant](https://github.com/w3f/Grants-Program/pull/1856) will include a use case of the library in the wallet.

As for the invoice, I'm pretty sure I submitted it through the form just before making a PR. Do you need me to resubmit it?

**Comment by keeganquigley** [comment]
Ah thanks @dileping I was able to find it under your name, please disregard. I have sent your invoice for processing. Please allow up to 14 days. Congrats on finishing the grant!

**Comment by keeganquigley** [comment]
Posting this since the GH bot failed:

We noticed that this is the last milestone of your project. Congratulations on completing your grant! 🎊

So, where to from here? First of all, you should join our [Grants Community chat](https://matrix.to/#/!XpynPDLusWUWfDpaqr:matrix.org?via=web3.foundation&via=matrix.org), if you haven't already, so we can stay in touch.
If you are looking for continuative support for your project, there are quite a few options. The main goal of the W3F grants program is to support research as well as early-stage technical projects. If your project still falls under one of those categories, you might want to apply for a follow-up grant. However, depending on your goals and project status, there are other support programs in our ecosystem that might be better suited as the next step. For example, projects with a Business Case/Token should look into the [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) or [VC Funding](https://parachains.info/investors) and Common Good projects have a good chance of receiving [Treasury Funding](https://github.com/w3f/Grants-Program#treasury). If you are looking for guidance, the team at https://substrate.io/ecosystem/square-one/ has compiled a list of ecosystem support sources and are happy to help you navigate it.

For a more comprehensive list, see our [Alternative Funding page](https://w3f.github.io/Grants-Program/funding). Let us know if you have any questions regarding the above. We are more than happy to point you to additional resources and help you determine the best course of action.
Lastly, we hope your W3F grant was a success and we want to thank you for being part of the journey!

**Pull request merged**
