### PR TITLE
Gafi Network milestone 2

### PR DESCRIPTION
**Pull request by mutobui**
* init

* gafi-tx

* reorder

* demo

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/896 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We have an external evaluator that potentially will take a look at the delivery in the coming days.

**Review by Noc2 — APPROVED** [review]
I’m happy to confirm that the milestone is accepted (see https://github.com/w3f/Grant-Milestone-Delivery/pull/468) and I will forward your invoice internally.

**Comment by mutobui** [comment]
Thank you @Noc2 @bitmaskit and W3F team for your great support on Gafi, I just sent the second milestone invoice.

**Comment by Noc2** [comment]
Thanks. I just forwarded it internally.

**Pull request merged**
