### PR TITLE
Milestone Delivery: Omniverse DLT Milestone 1

### PR DESCRIPTION
**Pull request by xiyu1984**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1431, and an update https://github.com/w3f/Grants-Program/pull/1475
 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by xiyu1984** [comment]
> @xiyu1984 thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

A quick answer. I think the problems might be mainly related to the configuration when you deploy your own o-token.
If you deploy your own o-token, you need to launch [off-chain synchronizers](https://github.com/Omniverse-Web3-Labs/Omniverse-DLT-Introduction/blob/main/docs/Deployment.md#synchronizer). And did you change the configuration of the tools?

**Comment by dsm-w3f** [comment]
@xiyu1984 thank you for the answer. I tried to continue the evaluation but seems that the balance of the account that is used for minting the tokens is too low. Can you provide more tokens for the test1 account?

`RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low`

**Comment by xiyu1984** [comment]
> @xiyu1984 thank you for the answer. I tried to continue the evaluation but seems that the balance of the account that is used for minting the tokens is too low. Can you provide more tokens for the test1 account?
> 
> `RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low`

Which account? This is my discord: xeeeyu#4107

**Comment by dsm-w3f** [comment]
@xiyu1984 my apologies for not explaining better this and for doing some confusion. The test1 account is from a local substrate, I thought that was in a remote node. I already transferred the balance from other accounts for it and still not having enough balance for minting the token. Should the balance from the image below be enough for minting? 

image

This project is complex to evaluate, maybe we could schedule a call to you to demonstrate it works. I'll get in touch with you using a private channel to schedule that.

**Comment by xiyu1984** [comment]
> @xiyu1984 my apologies for not explaining better this and for doing some confusion. The test1 account is from a local substrate, I thought that was in a remote node. I already transferred the balance from other accounts for it and still not having enough balance for minting the token. Should the balance from the image below be enough for minting?
> 
> image
> 
> This project is complex to evaluate, maybe we could schedule a call to you to demonstrate it works. I'll get in touch with you using a private channel to schedule that.

Hey @dsm-w3f ,

I'm happy to have a call with you, and we can date a time. As it's really late at my place, I need to go to sleep today. Before that, I will give a quick answer again.  

I think it might be because the **target account** you minted to does not have any gas tokens. In fact, the `o-token` is just an extension of the `assets` pallet and this is one of the mechanisms of the `assets` pallet of the `Substrate Parachain` that to hold `assets` tokens, the account needs to have some gas tokens.    

- Is the `test1` account [set to be the owner](https://github.com/Omniverse-Web3-Labs/Omniverse-DLT-Introduction/blob/main/docs/Deployment.md#create-token) of your `o-token`?
- Is the target account you minted `o-token` to [have any gas tokens](https://github.com/Omniverse-Web3-Labs/omniverse-swap-tools/tree/web3-grant#operations)?

**Comment by xiyu1984** [comment]
We made two detailed test-record videos here, and it may help.  
- A full workflow of an [Omniverse Fungible Token named `xyz`](https://omniversedlt.s3.amazonaws.com/FungibleToken-xyz-TestRecord.mp4)  
- A full workflow of an [Omniverse NFT named `abc`](https://omniversedlt.s3.amazonaws.com/NFT-abc-TestRecord.mp4)

**Comment by dsm-w3f** [comment]
@xiyu1984 thank you for producing the videos. I was able to run the system as presented. I had just one small problem that is not impeditive to accepting the milestone, see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_1_dsm-w3f.md). The milestone is accepted. I'll forward your invoice and the payment should take place within two weeks. Great work!

**Comment by xiyu1984** [comment]
> @xiyu1984 thank you for producing the videos. I was able to run the system as presented. I had just one small problem that is not impeditive to accepting the milestone, see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_1_dsm-w3f.md). The milestone is accepted. I'll forward your invoice and the payment should take place within two weeks. Great work!

Hi @dsm-w3f ,

Firstly, we sincerely appreciate your careful inspection and patience.  

Secondly, the problems mentioned in  [evaluation V2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_1_dsm-w3f.md#evaluation-v2):  
- The `Collection not exist.` problem is a small bug in the CLI tool. We fixed it some days before locally but unfortunately forgot to push it to GitHub. Now it has been [committed](https://github.com/Omniverse-Web3-Labs/omniverse-swap-tools/commit/422a15da5964b524d0eb6bd834a0f5a269bc8f8f). As the first o-NFT is with collection number `0`, the code before made a mistake.  

  

- The warnings are almost fixed, and we will leave two warnings to be fixed in the next milestone as they are related to updating the data structures. We record the two warnings as below:  

a3557de0f7663c53353974dda0fd3c0  

Lastly, just now we submitted the invoice.  

All the best~

**Comment by RouvenP** [comment]
hi @xiyu1984 we transferred the payment today. Thanks!

**Pull request merged**
