### PR TITLE
OpenBrush follow-up delivery milestone 1(3 milestone for OpenBrush) 

### PR DESCRIPTION
**Pull request by 0xMarkian**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: w3f/Grants-Program#621

We haven't filled the invoice form yet.
We did more progress than specified in the grant application. 

What was specified:
> We want to briefly(not full change, only minimal changes to reduce the size) implement them and provide a report(re-working data structure, reducing monomorphization, using dynamic dispatch in some cases).

In the description of the milestone, we mentioned that we're going to do "not full change,
only minimal changes to reduce the size", but we implemented them fully and it took more time.

Would it be possible to increase payment for that milestone from 9,000 USD to 15,000?

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
Thanks again. I’m happy to tell you that the milestone is hereby accepted. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/openbrush-follow-up_3_Noc2.md). 

Regarding amending the contract, I suggest creating a PR to update the contract. As part of the PR it would also be nice if you could tell us why you think your current delivery is worth 15k. For example, provide more information about how much work you put into it (hours). 
Something to be aware of, is that we usually don’t do this often, because in most cases teams are working on their own projects and aren’t directly contributing to parity code.

**Comment by TtomaS7** [comment]
Thank you for the quick approve!

Good, we will create the pull request for the grant, and we will update information about the hours etc.

**Comment by TtomaS7** [comment]
The invoice is applied with updated information.

**Comment by Noc2** [comment]
Thanks. I just forwarded the invoice internally.

**Comment by RouvenP** [comment]
hi @TtomaS7 we transferred the payment today. Thanks!

**Comment by TtomaS7** [comment]
Thanks to you too!

**Pull request merged**
