### PR TITLE
Create PANIC-1.md

### PR DESCRIPTION
**Pull request by crsfalzon**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/897

### CODE REVIEW

**Comment by lucasvanmol** [comment]
Hey there, thanks for the delivery! I'm looking into it now, but in the meantime, could you move the file from the `maintenance_evaluations` folder to the `evaluations` folder? Thanks!

**Comment by lucasvanmol** [comment]
I've also been looking through the delivery, but have some questions about the setup/install. Could you perhaps add me on matrix: https://matrix.to/#/@lucas:web3.foundation ?

**Comment by dillu24** [comment]
Hey @lucasvanmol it is important that you allow websocket connections on your node

**Comment by RouvenP** [comment]
hi @dillu24 we noticed that the ETH address on the invoice and on your application are different. Which one should we use?

**Comment by dillu24** [comment]
Hi @RouvenP it should be the same I think. Nontheless you can use the one on the invoice, i.e. 0x672b62B64abe450F8C6957785fA5c79E33422aEF

**Comment by RouvenP** [comment]
hi @dillu24 thanks for clarifying. I mixed up two different grants, that's why the addresses differ from each other. so all good, thanks!

**Comment by lucasvanmol** [comment]
Hey there, thanks for the additional assisstance and clarifications on element. I've accepted the delivery, and my evaluation is [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/panic_1_lucasvanmol.md).

I'll also forward your invoice to the finances team.

**Comment by RouvenP** [comment]
hi @dillu24 we transferred the payment today. Thanks!

**Pull request merged**
