### PR TITLE
dao-entrance-phase-1 milestone 2

### PR DESCRIPTION
**Pull request by bai-3**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1445 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by bai-3** [comment]
> 
Hi [semuelle](https://github.com/semuelle) ,Thank you very much for your reply. 
1. You can skip the matrix node deployment. I have not deployed a use case at http://im.tc.asyou.me
2-3. If you are testing this program with linux, run flutter run -d linux. If you are testing this program with macos, run flutter run -d macos.  
Can the flutter doctor command be executed? I want to know the specific information of your system. For example, the message after the execution of my flutter doctor is
```
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (version 2022.1)
    ✗ Unable to find bundled Java version.
[✓] Connected device (1 available)
[✓] HTTP Host Availability
```

**Comment by semuelle** [comment]
Thanks, @bai-3. Running `flutter upgrade` resolved the initial issue. Now `flutter doctor` shows

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on Ubuntu 22.04.2 LTS 5.19.0-35-generic, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.75.0)
[✓] VS Code
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

However, running `flutter run` now shows

```sh
❯ flutter run -d linux
Running "flutter pub get" in app...
Resolving dependencies... (10.0s)
  adaptive_dialog 1.8.2 (1.8.3 available)
  ...
  xml 5.4.1 (6.2.2 available)
Warning: You are using these overridden dependencies:
! ffi 2.0.1
Got dependencies!
Launching lib/main.dart on Linux in debug mode...
CMake Error at /snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  flutter/ephemeral/.plugin_symlinks/flutter_secure_storage_linux/linux/CMakeLists.txt:13 (pkg_check_modules)


Building Linux application...                                           
Exception: Unable to generate build files
```

**Comment by bai-3** [comment]
hi @semuelle , Thank you very much for your research. I forgot to inform you of the Flutter version, and I noticed from your error message that Flutter is installed in snap. Because our project depends on various platform dependencies, can you please try uninstalling Flutter Snap and installing it manually? Your error is caused by the dependency library flutter_secure_storage relying on Linux operating system shared libraries.  the issue is [here](https://github.com/mogol/flutter_secure_storage/issues/377) 
I suggest that you try the following steps:
1.  please try uninstalling Flutter Snap and installing it manually,It is best to install version 1.7.3
2.  Run `apt install libsecret-1-dev libjsoncpp-dev  libolm3 libclang-dev` to supplement the missing libraries
3.  Run `cargo install flutter_rust_bridge_codegen` to set rust code bind
Because it is too late on our side, I will find out more tomorrow whether more packages need to be installed, thank you

**Comment by bai-3** [comment]
I am very sorry to see this. Our project did have such limitations with the developer. I'm running on a new ubuntu machine and I don't see a dead bug, so I can only guess it's the pub package,

You can try running

` 
$ flutter pub cache repair
` 
` 
$ flutter clean
` 
` 
$ flutter run -d linux
` 
If still not successful, can you provide the output information of the flutter doctor again

**Comment by semuelle** [comment]
That did the trick. 

Is wss://chain.asyou.me the chain I'm connecting to?

**Comment by bai-3** [comment]
> That did the trick.
> 
> Is wss://chain.asyou.me the chain I'm connecting to?

This milestone does not involve the connection with blockchain. In the next milestone, we will complete the connection with blockchain, and enable each matrix node to have the ability to create and connect DAO, communicate with and complete tasks in DAO project in our client. Send the status of the view modification task in our client.

The login of the current client account is done by sending sign data and then matrix node verify sign.

**Comment by semuelle** [comment]
I understand. Sorry, I probably should have read the milestone description a bit closer. Anyway, I got another issue: some tests are failing. This is the output I'm getting. Could you look into it?

```sh
❯ flutter test integration_test/main_test.dart
00:00 +0: ... /xxx/dao-entrance/app/integration_test/main_test.dart              B    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
01:21 +0: ... /xxx/dao-entrance/app/integration_test/main_test.dart              
01:23 +0: signup                                                                                                              
objectbox ==> /home/xxx/.local/share/me.asyou.asyou_app/daoent
init called
window.platformBrightness => Brightness.dark
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'selectAccountType'>] (ignoring offstage widgets)" (used in a
call to "tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1224:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1163:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:18)
#3      main.<anonymous closure> (file:///xxx/dao-entrance/app/integration_test/main_test.dart:32:18)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  signup
════════════════════════════════════════════════════════════════════════════════════════════════════
01:26 +0 -1: signup [E]                                                                                                       
  Test failed. See exception logs above.
  The test description was: signup
  

To run this test again: /xxx/flutter/bin/cache/dart-sdk/bin/dart test /xxx/dao-entrance/app/integration_test/main_test.dart -p vm --plain-name 'signup'
01:26 +0 -1: joinChannel                                                                                                      
init called
window.platformBrightness => Brightness.dark
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'auto_test'>] (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1224:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1163:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:18)
#3      login (file:///xxx/dao-entrance/app/integration_test/main_test.dart:156:16)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  joinChannel
════════════════════════════════════════════════════════════════════════════════════════════════════
01:33 +0 -2: joinChannel [E]                                                                                                  
  Test failed. See exception logs above.
  The test description was: joinChannel
  

To run this test again: /xxx/flutter/bin/cache/dart-sdk/bin/dart test /xxx/dao-entrance/app/integration_test/main_test.dart -p vm --plain-name 'joinChannel'
01:33 +0 -2: createChannel                                                                                                    
init called
window.platformBrightness => Brightness.dark
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'auto_test'>] (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1224:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1163:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:18)
#3      login (file:///xxx/dao-entrance/app/integration_test/main_test.dart:156:16)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  createChannel
════════════════════════════════════════════════════════════════════════════════════════════════════
01:38 +0 -3: createChannel [E]                                                                                                
  Test failed. See exception logs above.
  The test description was: createChannel
  

To run this test again: /xxx/flutter/bin/cache/dart-sdk/bin/dart test /xxx/dao-entrance/app/integration_test/main_test.dart -p vm --plain-name 'createChannel'
01:38 +0 -3: startDirectChat                                                                                                  
init called
window.platformBrightness => Brightness.dark
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'auto_test'>] (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:1224:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:1163:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:504:18)
#3      login (file:///xxx/dao-entrance/app/integration_test/main_test.dart:156:16)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  startDirectChat
════════════════════════════════════════════════════════════════════════════════════════════════════
01:44 +0 -4: startDirectChat [E]                                                                                              
  Test failed. See exception logs above.
  The test description was: startDirectChat
  

To run this test again: /xxx/flutter/bin/cache/dart-sdk/bin/dart test /xxx/dao-entrance/app/integration_test/main_test.dart -p vm --plain-name 'startDirectChat'
01:44 +0 -4: Some tests failed.
```

**Comment by semuelle** [comment]
Also: the grant application lists "voice and video calls" for this milestone. Are those possible?

**Comment by bai-3** [comment]
hi @semuelle 
Hello, I see that you have pointed out the problem carefully. Because I misestimated the difficulty of the project, I completed the development of the project with great difficulty within one month, so the project is not quite perfect

1. The complete unit test on 0x is very difficult for me to achieve for such a project. Milestone 3 and Milestone 2 are the same project and share most of the code completely. So can you deliver the unit test at Milestone 3



2. The code of voice and video calls was placed in a new branch. Because matrix does not provide Voip service by default, we did not have an available back end to debug our code. So we will code based on the new branch (https://github.com/WeteeDAO/app/tree/voip), such as research through an open source voip service and fully and matrix fusion, merge into the main branch



3. I have updated the E2E test code. You need to update the following code



This is not to escape the problem. This project is written for my dream. Thank you again for your understanding

**Comment by bai-3** [comment]
As of now I have updated the unit tests and you can run it with 'flutter test'

**Comment by bai-3** [comment]
Because the api server is in China, the distance between the two sides is too far, so the api response speed becomes slow. Now I change the waiting speed of an operation to 50 seconds at most. I have updated the code, you can pull the code and test it again

**Comment by bai-3** [comment]
hi @semuelle ，Thank you for your understanding. 

I have received all the questions you raised. When these functions are perfected, I will definitely tell you here again. I am especially looking forward to more people to tell me its problems. The next two milestones will surely deliver satisfactory results. Thank you very much for your urging.

 Since aUSD is not offered now, we have used USDT as currency for our last milestone

**Comment by RouvenP** [comment]
hi @bai-3 we transferred the payment today.

**Pull request merged**
