### PR TITLE
Plus: Polkadot js Plus extension, Milestone 2

### PR DESCRIPTION
**Pull request by Nick-1979**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/778

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery @Nick-1979. We'll look into it as soon as possible.

**Comment by cruikshankss** [comment]
Hi @Nick-1979! I began testing Plus milestone 2. By the way, Plus has already been useful for me and I've really enjoyed using it and learning from it.

I got all the tests to pass locally! I downloaded Firefox and the Plus plugin extension for Firefox from the browser. Next I plan to manually test your three deliverables with my two new WND test accounts.

**Comment by cruikshankss** [comment]
Good day @Nick-1979 !

Congratulations on your successful invention! Here is [my M2 evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-js-plus-extension_2_cruikshankss.md).

I hope I speak on behalf of everyone in saying congratulations for completing your grant with the Web3 Foundation! I hope you celebrate.

I plan to forward your invoice on Monday.

Good luck and hope you enjoy continuing to evolve Plus. 🍀🧬🙏

Kind regards,
Ashley

**Comment by Nick-1979** [comment]
Hi Ashley,

I really appreciate your time, spending to evaluate the Polkadot js Plus extension.
Working with the W3F is a great honor for me.

I hope we can follow-up with more new features.

Sincerely yous,
  Kami

**Comment by cruikshankss** [comment]
Hi Kami,

Thank you for your comment! If you are not already aware, here is information about our [maintenance grants](https://github.com/w3f/Grants-Program#hammer_and_wrench-maintenance-grants) as well in case that could potentially work with your roadmap.

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
