### PR TITLE
Add Slushie Milestone 2 Delivery report

### PR DESCRIPTION
**Pull request by Kyrylog**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1004 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @Kyrylog. Looks great, however I couldn't find the usage guide for the prover tool as per deliverable 0b. Could you provide some instructions on how to use it, obtain the parameters etc.?

**Comment by Kyrylog** [comment]
Hi @alxs , we've added instructions and usage example to https://github.com/4IRE-Labs/Slushie/blob/main/plonk_prover_tool/README.md

**Comment by alxs** [comment]
Thanks. But it's currently not documented how the parameters are defined, in what format they are expected or how they are generated. For example, someone unfamiliar with your project has no way of knowing what a nullifier is and how they can generate it, or that the tree opening argument actually expects a file name. Could you add this information?

Besides, a more verbose high-level description of the project would also really help others understand it. The main README only links to the individual components but it would make sense if it also described how they relate to each other and what the general idea is.

**Comment by Kyrylog** [comment]
Hi @alxs we updated documentation, however please take into account that this is only Milestone 2 of 4, so some components are still under development and we'll add their usage later

**Comment by alxs** [comment]
Thanks @Kyrylog, that looks really great. One more thing - when you wrote the application, you intended for the prover tool to [compile to WASM](https://github.com/w3f/Grants-Program/blob/master/applications/Slushie%20Mixer.md#milestone-2-plonk-prover-cli-tool-compiles-to-wasm). However, unless I missed it, this is currently not possible (and I'm not sure if it would be as easy as making a few changes to the tool's `Cargo.toml` or, probably, require more work). Could you either implement this or submit an amendment to remove it from the application?

**Comment by armyhaylenko** [comment]
Hey @alxs, the "tool" comprises two parts: the prover library and the CLI. The prover library can be compiled to WASM, therefore can be later used on the front-end to generate plonk proofs. The CLI however is only intended to be used locally, therefore it does not need to compile to WASM.

**Comment by alxs** [comment]
Of course! Thanks, I missed that. No, that makes sense; there's no need to submit an amendment for this.

In that case, I'm happy to let you know that the milestone has been accepted. You can find my delivery notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/slushie_mixer_2_alxs.md). I'll notify the invoice team to pay out your invoice. As usual, please allow for up to two weeks for processing.

**Pull request merged**
