### PR TITLE
xtoken-2

### PR DESCRIPTION
**Pull request by bette7**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is being made by the same account as the accepted application. 
- [X] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
@bette7 Thanks for the delivery, we'll look at it whenever possible! Don't worry about the failed github action, it's got nothing to do with your PR. We're working on fixing it.

**Comment by Noc2** [comment]
@bette7 I just took a quick look at it. Everything looks good. I only ran into one issue, when I tried to run the unit test of the [xtokens module](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/xtokens/src/tests.rs), I currently get the following error:` no matching package named cumulus-pallet-xcm-handler found`. Could you take a look at it?

**Comment by shaunxw** [comment]
@Noc2 All `ORML` pallets need patches in [`Cargo.dev.toml`](https://github.com/open-web3-stack/open-runtime-module-library/tree/xtokens-v2#cargotoml) to work(by using fixed version of dependencies), as upstream dependencies like Substrate/Cumulus/Polkadot are changing everyday.

To run `orml-xtokens` module unit tests, please do:
1. Go to root directory of `open-runtime-module-library` repo, check out `xtokens-v2` branch by `git checkout xtokens-v2`.
2. Run `make Cargo.toml` to make cargo patches effective.
3. Run unit tests by `cargo test -p orml-xtokens`.

**Comment by Noc2** [comment]
Thanks for the quick reply. I’m happy to tell you that the milestone is a pass and I will forward your invoice internally.

**Comment by Noc2** [comment]
@shaunxw and @bette7 I couldn’t find the invoice. Did you already upload it via the form? Alternatively you can send it to us via email.

**Comment by bette7** [comment]
> @shaunxw and @bette7 I couldn’t find the invoice. Did you already upload it via the form? Alternatively you can send it to us via email.

Just submitted the invoice via the form. Thanks!

**Comment by Noc2** [comment]
Thanks, I just forwarded it internally.

**Comment by RouvenP** [comment]
hi @bette7 we just sent the payment.

**Pull request merged**
