### PR TITLE
add deliveries/substrate-tutorials-milestone_2.md

### PR DESCRIPTION
**Pull request by tdelabro**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/949

### CODE REVIEW

**Comment by tdelabro** [comment]
Hi. 
Sorry, it took such a long time, I was a background task for us during the past year. 
The good thing is, because we gradually added more exercises, many people already tried those and helped us debug or improve those.
Still, I'm curious to have your feedback about it, especially about things like the exercise order.

**Comment by tdelabro** [comment]
@semuelle Thanks a lot for pointing it our. I removed the link to the website.

**Comment by tdelabro** [comment]
@semuelle Okay, give me a few days an I will write such an article and post it :)

Great news overall. Thanks for your time!

**Comment by tdelabro** [comment]
@semuelle 
here is a medium article: https://medium.com/@timothedelabrouille/learn-substrate-hands-on-5126069d1334
Does it fulfill what is expected?

**Comment by semuelle** [comment]
Thanks, @tdelabro. I noticed that your grant also mentions that you are planning to use the exercises yourself and that you are planning to promote them on various platforms. The article is mainly for those who otherwise might not draw attention to their project, but it's still useful for sharing. I hope you are successful in drawing enough people to carry on. Best of luck with it!

Your delivery is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/substrate-tutorials_2_semuelle.md).

I will forward your invoice for processing.

**Comment by semuelle** [comment]
Hi @tdelabro. Sorry, but W3F does not provide tech support. I suggest reaching out on substrate.stackexchange.com or on the Substrate Devs chat: https://matrix.to/#/#substratedevs:matrix.org.

**Comment by RouvenP** [comment]
hi @tdelabro we transferred the payment today

**Comment by tdelabro** [comment]
@RouvenP thanks a lot !!

**Pull request merged**
