### PR TITLE
Iris Milestone 3 Delivery

### PR DESCRIPTION
**Pull request by driemworks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/657
Amendment: https://github.com/w3f/Grants-Program/pull/812

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @driemworks. We will look into it as soon as possible.

**Comment by driemworks** [comment]
@semuelle @cruikshankss please do let me know if there's any way I can assist

**Comment by cruikshankss** [comment]
@driemworks Hi Tony! Can I chat you on disc in about an hour? I could maybe get through the testing guide today with your help.

**Comment by driemworks** [comment]
Hey @cruikshankss , I didn't see your message until just now (and on discord). I could be available in the next 30 mins or so, otherwise anytime tomorrow is fine for me.

**Comment by cruikshankss** [comment]
Good day @driemworks!

Congratulations on your successful invention! Here is [my M3 evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/iris_3_cruikshankss.md). 

Exemplary testing guides. I learned a lot about software architecture from studying/testing the codebase. 

I hope I speak on behalf of everyone in saying congratulations for completing your grant with the Web3 Foundation! I hope you celebrate. 

I plan to forward your invoice on Monday. 

Good luck and hope you enjoy continuing to evolve Iris. 🍀🧬🙏

Kind regards, 
Ashley

**Comment by driemworks** [comment]
@cruikshankss @semuelle My team is interested in submitting a followup proposal. I've sent you both emails (I think I got the addresses right but I'm not sure) regarding some questions I had related to this.

**Comment by cruikshankss** [comment]
@driemworks I did receive your email when I was out of office. Sorry for the delay. I am planning to discuss how to respond to your email tomorrow with the team! I plan to update you asap!

**Pull request merged**
