### PR TITLE
Stardust 2- Terra Deep Dive Pull Request

### PR DESCRIPTION
**Pull request by adit313**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/940 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
Hey @adit313 
Thanks for your patience here.

> I'm assuming you guys are a bit swamped at the moment.

Indeed. Sorry for the wait. I also had to acquire some additional knowledge w.r.t. some of your report's context (e.g. curve protocol) to understand it to a sufficient extent. In general, similarly to M1 I'm very happy with the quality of your research and I only have a few questions:

- p. 14: you use LFG here which appears to stand for [Luna Foundation Guard](https://lfg.org/), however, it would be nice to have introduced that term as not everybody is necessarily familiar with it (e.g. me :D)
- p. 14, quote:

  > LFG begins to drain liquidity out of the Curve3+UST Pool in preparation for the move to 4Pool.

  What's LFG's motivation to move liquidity from Curve's pool to the alternative 4Pool at this time? Both are [competing pools](https://medium.com/@crypto8fi/4pool-enters-the-curve-wars-e10c73a637dd), based on the _Curve Protocol_, right? What difference does it make if 1 of them is drained?

- p. 17, quote:

  > It is highly unlikely that an hedge fund would seek to attract that sort of regulatory scrutiny in the current market environment in the US where both parties are seeking to restrict Wall Street activities.

  I'm going to play devil's advocate here: Wouldn't it also be possible that hedge funds actually **do** seek additional regulatory scrutiny which they'd be able to implement while smallers competitors wouldn't be able to do so? An example from the financial industry are the additional AML/KYC regulatories, that seem to have driven a lot of smaller financial institutions out of business, while only the rather bigger ones can afford to implement solutions (which are expensive) to satisfy the regulatory requirements.

- p. 21, quote:

  >    image

  Wait, so Anchor only allowed for $20M in Terra to be withdrawn daily, but during the crisis this limitation was increased to $100M?! This seems to be adding fuel to the fire, since this would increase the supply of UST if more people could redeem them, which naturally would lead to even lower prices compared with a $20M daily outflow. Hence, this seems to be a counterproductive measure to be taken. What am I missing here?

- p. 22: This link is dead: https://www.basis.io/article/could-a-crisis-of-confidence-cause However, I was able to find a working copy of it on the internet archive: https://web.archive.org/web/20180510202115/http://www.basis.io/article/could-a-crisis-of-confidence-cause/index.html

**Comment by adit313** [comment]
Perfect, just made and pushed the changes to the linked repo.

**Review by takahser — APPROVED** [review]
@adit313 thanks for pushing the changes. You can find my [evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stardust_2_takahser.md).

**Comment by adit313** [comment]
Hey there, any updates on the payment for this milestone?

**Comment by adit313** [comment]
@takahser Hey there, any updates on the payment?

**Comment by takahser** [comment]
@adit313 you should have received it, but I pinged finance to double-check. We'll keep you posted!

**Comment by takahser** [comment]
@adit313 FYI - I just got the note from the invoice team that it will be paid today. Please accept our apology for the delay in the payment. 🙏

**Comment by adit313** [comment]
No worries, we are still not seeing it today though. Any updates from finance?

**Comment by takahser** [comment]
@adit313 I've asked them again to double-check. Sorry for the inconvenience, usually this process is smooth.

**Pull request merged**
