### PR TITLE
Citadel milestone 1

### PR DESCRIPTION
**Pull request by citadeldao**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Open-Grants-Program/pull/81

### CODE REVIEW

**Comment by semuelle** [comment]
Hey @citadeldao, don't worry about the Github action failing. That's just for our internal bookkeeping.

**Comment by alxs** [comment]
Please add all deliverables to this PR, instead of opening a new one for each of them.

**Comment by alxs** [comment]
This PR should consist of only one file containing **all deliverables** in the application. If you only want to deliver some of them, please submit an amendment to your application file via PR.

**Comment by semuelle** [comment]
Hey @citadeldao, this doesn't look right. There are now files for milestones 1 to 3, and then one `citadel.md` file with six "steps". I only see one milestone in your application, so, as Aleixo already said, could you submit a single file with all deliverables, and remove any other file?

**Comment by citadeldao** [comment]
Hello @semuelle, as you said, we removed other files and left only single file with all deliverables named as "citadel.md".

**Comment by alxs** [comment]
@citadeldao I've renamed the file to match our naming conventions. What about steps 7-9, do you plan on adding them to the file as well?

**Comment by citadeldao** [comment]
@alxs Yes we will add them, but later. We are preparing reports for them. Thanks.

**Comment by alxs** [comment]
@citadeldao any updates here?

**Comment by citadeldao** [comment]
@alxs Yes, we wil add them in a few days, thanks.

**Comment by alxs** [comment]
@citadeldao do you still intend to add step 8 to the delivery?

**Comment by alxs** [comment]
Hey @citadeldao. I started looking into your delivery and have the following comments:

- Are you still planning to add deliverable 8?
- The main [repository](https://github.com/citadeldao/polkadot) containing this delivery will just look like a bunch of JavaScript files thrown together to anyone who finds it. Please keep in main that the main purpose of the grants program is to provide funding for projects that will be beneficial to the ecosystem. Hence, I'd like to ask you to please provide proper documentation and to work on the structure of the project in order to make it more accessible. Documentation should consist of abundant inline comments and a README that accurately describes what the project does and any instructions necessary to use it. You're welcome to also describe the interactions with Polkadot but please pay some attention to the formatting.
- I signed up to Citadel to quickly test whether Polkadot integration was there and it wasn't in the list of networks for which to generate addresses. I chose Cosmos and Secret instead and the site hung.
- The YouTube videos are appreciated, but we need to be able to reproduce the behaviour ourselves. May I ask you to provide a testing guide that showcases the implemented functionality?

**Comment by citadeldao** [comment]
Hello Web3 Foundation team!

This amendment is a follow-up on the previous grant requested by Citadel.one team.
https://docs.google.com/document/d/1mtE83hEbPcEofcPe0B6ALydfUT8XxMyxChazQCd04ek/edit?usp=sharing

**Comment by alxs** [comment]
Please follow the process outlined in the link above to submit the amendment. Thank you.

**Comment by alxs** [comment]
@citadeldao ping. The new interface looks great by the way!

**Comment by citadeldao** [comment]
Hello Web3 Foundation team.
We've followed all the instructions that you sent and updated our application. We've added a final delivery date and updated the price to an appropriate USD amount. 
Thanks!

**Comment by alxs** [comment]
Closing this PR in light of the delivery date being [postponed](https://github.com/w3f/Grants-Program/pull/687) by a considerable amount of time.

**Pull request closed without merging**
