### PR TITLE
Subcoin milestone 1

### PR DESCRIPTION
**Pull request by liuchengxu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2304

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @liuchengxu thanks for the delivery. I started the eval and have a few comments:

- Unit tests are all passing, thanks!
- Could you please add Docker instructions to the readme for clarity? I was able to build and run it successfully using `docker build -t subcoin-node --file ./Dockerfile .` and `docker run -d subcoin-node` but it exits immediately. Will it have more functionalities in future milestones?
- How can I spin up the node (locally)? Usually after building it w/ `cargo build --release` I am able to launch it with something like `./target/release/subcoin-node --dev` but I'm having no luck.

Thanks for any help you can provide!

**Comment by liuchengxu** [comment]
>Could you please add Docker instructions to the readme for clarity? I was able to build and run it successfully using docker build -t subcoin-node --file ./Dockerfile . and docker run -d subcoin-node but it exits immediately. Will it have more functionalities in future milestones?

The installation instruction using Docker is here at https://github.com/subcoin-project/subcoin/blob/subcoin-milestone-1/docs/src/installation.md#docker-linuxamd64, the docker image has already been built via GitHub Action and hosted on GitHub, you don't have to make it on your own. The prebuilt executables are available on GitHub as well https://github.com/subcoin-project/subcoin/releases/tag/v0.1.0. Apart from the commands using the executable, Docker commands are now added in this commit https://github.com/subcoin-project/subcoin/commit/9e509efb2a1b02aaf2886250980419c1d935b598

>How can I spin up the node (locally)? Usually after building it w/ cargo build --release I am able to launch it with something like ./target/release/subcoin-node --dev but I'm having no luck.

Please check out this link in 0b in which every step to test the functions in this milestone has been elaborated
https://github.com/subcoin-project/subcoin/blob/subcoin-milestone-1/docs/src/usage.md#import-bitcoin-blocks-from-bitcoind-database.

@keeganquigley  In addition, Subcoin provides a custom interface for CLI usage due to its uniqueness, so the experiences in other typical Substrate chains may not directly work in Subcoin, please do read the links carefully in the delivery.

**Comment by keeganquigley** [comment]
Thanks @liuchengxu for the changes, and also for linking the docs. I completely missed these additional docs, sorry! Everything is working now and I'm happy to pass the milestone. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subcoin_1_keeganquigley.md). Cheers and looking forward to the next one.

**Comment by semuelle** [comment]
@liuchengxu, the invoice must include your full name and address. Could you resend the invoice with the information added? Thanks!

**Comment by liuchengxu** [comment]
Hmm, the full name and address were both included in the invoice. Is it because the full name must match the one filled in KYC? Anyway, I already resend the invoice, the full name now is the same as the one in KYC, and unlike the last invoice in which the address was in the item section, the polkadot address is now attached to the Notes section. Let me know if it's fine this time. @semuelle

**Comment by semuelle** [comment]
Sorry. Not payment address, but postal address.

**Comment by liuchengxu** [comment]
The invoice is supposed to include the Notes section at the bottom in which the Polkadot address was attached. Could you check whether the invoice has this section? Here are the online version of the invoices ([1](https://invoice-generator.com/d/es1YXCr7PwPTm86ZSmKkZCcKzgRTAF4EPHFxpJRoCIVryeWhvvEF4YbtYecYMvIl), [2](https://invoice-generator.com/d/d2QlnHaGmK7LIZTLv8GdlgkK1otfp1s32vJZgTV2Bal6hXGWHzmwZw8fkVjo8sU2)), please see if the invoices you received are the same as the online ones. @semuelle 

截屏2024-07-26 16 17 04

**Comment by semuelle** [comment]
> The invoice is supposed to include the Notes section at the bottom in which the Polkadot address was attached. Could you check whether the invoice has this section?

We have your payment address. Swiss law requires that you also list your postal address.

**Comment by liuchengxu** [comment]
@semuelle  Oops, sorry that I misread your last comment, the postal address was added and invoice resent again!

**Comment by RouvenP** [comment]
hi @liuchengxu today we sent the USDT. The DOT payment follows this Friday.

**Comment by RouvenP** [comment]
hi @liuchengxu we transferred the DOTs today

**Comment by liuchengxu** [comment]
Hey @RouvenP Is the transfer complete now? I haven't received the DOTs.

**Pull request merged**
