### PR TITLE
Crossbow Milestone 3

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/668

### CODE REVIEW

**Comment by alxs** [comment]
Replicating @enfipy's [comment](https://github.com/w3f/Grants-Program/pull/668#issuecomment-1226775748) here:

> The showcase of Crossbow Plugins is in Internal Testing on Google Play, and if the reviewer doesn't want to publish and go through all processes of configuring Games Services, Play Billing (Play Store products), and signing - I can add email to Internal Testing testers and reviewer will be able to download and use the App from Google Play Store. I think this is also a good option.

**Comment by enfipy** [comment]
@alxs Thank you for the quick reply! I released the Open Testing track, and now I think it's possible to enroll in it through these links:
Join on the web: https://play.google.com/apps/testing/com.crossbow.example.plugins
Join on Android: https://play.google.com/store/apps/details?id=com.crossbow.example.plugins

**Comment by alxs** [comment]
@enfipy the links don't work for me, is there anything you can do?

**Comment by alxs** [comment]
Also trying to install the command line tools or the SDK manager with `crossbundle install`, or trying to run a project, returns the following:

```
error: Crossbundle Tools error: Android(AndroidTools(AndroidSdkIsNotFound))
caused by: Android error: AndroidTools(AndroidSdkIsNotFound)
caused by: AndroidTools error: AndroidSdkIsNotFound
caused by: Android SDK is not found. Check the installation path or use crossbundle install command to install it
```

By the way, feel free to send the article to grantsPR@web3.foundation for proofreading and cross-promotion, in case you haven't yet.

**Comment by enfipy** [comment]
Hey @alxs! Finally, Google published the showcase app to Play Store, and you can freely download it from [official Play Store](https://play.google.com/store/apps/details?id=com.crossbow.example.plugins)! 🥳

About the error you've faced: I think it's because you don't have any ENV variable in your system like: `ANDROID_SDK_ROOT`, `ANDROID_HOME`, or `ANDROID_SDK_PATH`. If you haven't installed Android libraries and etc. - I would recommend you to install the latest version of `crossbundle` (with this command: `cargo install crossbundle`), and run a new flag that we added to install command-line-tools, Android SDK/NDK, and bundletool: `crossbundle install --preferred`.

**Comment by alxs** [comment]
That's great news, thanks for sharing! I was able to install it and test it.

Thanks for the tip, I updated `crossbundle` and got a new error with `crossbundle install --preferred`:

```
Installing all preferred tools
Downloading commandlinetools-linux-8512546_latest.zip into: /home/aleixo
Extracting zip archive contents into: /home/aleixo/Android/sdk
Deleting zip archive thaw was left after installation
You have installed budletool on your system already. Use `--force` command to overwrite.
error: Crossbundle Tools error: PathNotFound("/home/aleixo/Android/sdk/build-tools")
caused by: Path "/home/aleixo/Android/sdk/build-tools" doesn't exist
```

**Comment by enfipy** [comment]
@alxs Hey, thanks for the quick reply!

We fixed this issue, and now it should work correctly on your PC too :)

Just update `crossbundle` like this: `cargo install --git https://github.com/dodorare/crossbow --force crossbundle`.

**Comment by alxs** [comment]
Thanks @enfipy, the installation worked this time! Could you also please link in deliverable 0b. to "a basic tutorial that explains how to use Google Play Billing and In-App updates in your own rust game project", as described in the application?

**Comment by enfipy** [comment]
Hey @alxs! Just added tutorials and updated delivery. I hope now it looks nice :)

**Comment by alxs** [comment]
Thanks @enfipy, that looks great. I tried running the `bevy-explorer` example again to test the build process and see if the Substrate integration still worked, and I only see a black screen. Can you reproduce this?

**Comment by enfipy** [comment]
Hey @alxs! Bevy got updated, and we forgot to test this example. Now everything should work as expected in the latest commit of the main branch. Thank you for pointing this out!

**Comment by enfipy** [comment]
@alxs Oh, haha. It's just here: https://github.com/dodorare/crossbow/tree/main/examples/crossbow-plugins (which is precisely what I published). I thought it would be cool to place it inside examples. I think I will also update the Play Store link so that anyone can download it and try everything.

Also, I think it would be great to put the link to it somewhere in Milestone Delivery, right?

**Comment by enfipy** [comment]
Hey @alxs! I've published the new v0.2.3 tag and updated links, if you noticed any other problems - let us know :)

**Comment by alxs** [comment]
Thanks @enfipy! With this, I'm happy to let you know the milestone is accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/crossbow_3_alxs.md). I'll notify the finance team to pay out your invoice. As usual, please allow for up to 2 weeks of processing time.

Good luck with the continuation of Crossbow, and don't hesitate to apply for more grants to build in the Substrate ecosystem!

**Pull request merged**
