### PR TITLE
Create Diffy_messenger_st1_ms2.md

### PR DESCRIPTION
**Pull request by beoblock**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the Statemint account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1560

### CODE REVIEW

**Comment by dastansam** [comment]
hey @beoblock,

[here](#913) is the detailed evaluation of your milestone

**Comment by keeganquigley** [comment]
Hi @beoblock thanks for the delivery, please see the external evaluator's comments [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/912#issuecomment-1632964507) and address the issues in order to continue with the evaluation.

I also was having the same lagging issues when trying it out. I commented in more detail [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/913#issuecomment-1636361467).

**Comment by beoblock** [comment]
@dastansam , @keeganquigley thanks for the review!
Сounter requests is a good test, thank you! If Bob has already received Alice's chat request, no need to send the opposite request from Bob. We are already fixing all issues and will deliver I guess tomorrow.

For the Polkadot.js - correct, we are using just the library. Embedding a wallet seems too complicated for the UX now, as the user will have to confirm all multiple requests. But we see a good opportunity for in-messenger payments, so this is a feature to think of in future.

**Comment by beoblock** [comment]
@keeganquigley, @dastansam , we've pushed all fixes, please, check. It should work smooth now.

**Comment by keeganquigley** [comment]
Thanks for making the fixes @beoblock your [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/diffy_chat_2_dastansam.md) has been accepted and therefore this milestone is passed. Congrats on the completion of the grant!

**Comment by beoblock** [comment]
Hi, @keeganquigley , @RouvenP
I want to kindly request your assistance in confirming the status of the payment for the last milestone. Is it just pending?

**Comment by keeganquigley** [comment]
Thanks for letting us know @beoblock I have pinged the operations team internally and will get back to you when I hear from them.

**Comment by meldien** [comment]
@beoblock the payout will be done in the next hours. Stay you updated.

**Comment by meldien** [comment]
@beoblock transfer done

**Pull request merged**
