### PR TITLE
Candle Auction on Ink!: Milestone-1 delivery

### PR DESCRIPTION
**Pull request by agryaznov**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/666

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@agryaznov I've done a first review of your code and created a small PR to your repo. Otherwise looks very good!
Please let me know once you've addressed the TODOs from that PR so we can proceed.

**Comment by agryaznov** [comment]
@mmagician thanks a lot for your review and feedback! Please find my responses in [that PR](https://github.com/agryaznov/candle-auction-ink/pull/1)

**Comment by agryaznov** [comment]
@mmagician all mentioned issues have been addressed so far. Is anything else needed to process this delivery?

**Comment by mmagician** [comment]
Hey, thanks for the quick fixes!
I'll revise the delivery by the end of the week and get back to you

**Comment by mmagician** [comment]
Hey, quick follow-up:
- created another PR to make tests panic more explicitly: https://github.com/agryaznov/candle-auction-ink/pull/2
- there is no way (aside from watching events) to check the current auction winner. Perhaps it's worth adding this to the output of `get_status`?
- I wanted to instantiate the contract twice (with different params), but it errors out with the following message, at least via Canvas-UI: `Uncaught error. Something went wrong with the query and rendering of this component. Cannot read properties of undefined (reading 'createType')`. Other contracts seem to allow double instantiation (e.g. erc721). Let me know if you can reproduce and if you know a possible cause for this.
- Payout didn't work. Steps: bid from Alice, outbid by Bob. `get_winner()` returns Bob correctly. I am unable to call `payout()` from neither of the participating accounts. The error is: 
```
system.ExtrinsicFailed
contracts.ContractTrapped
```

Let me know once you've checked these!

**Comment by agryaznov** [comment]
Hi Marcin, 

> Hey, quick follow-up:
> 
>  * created another PR to make tests panic more explicitly: [Add explicit panic messages agryaznov/candle-auction-ink#2](https://github.com/agryaznov/candle-auction-ink/pull/2)
Great one! I've merged it, thank you.
> 
>  * there is no way (aside from watching events) to check the current auction winner. Perhaps it's worth adding this to the output of `get_status`? 

That's right, I agree. I've made a separate `get_winning()` method for that (because I'm not sure if it has something to do with the auction status itself - opening, ending period or ended). Please check it out [@v0.1.9](https://github.com/agryaznov/candle-auction-ink/blob/v0.1.9/src/lib.rs#L381).

**Please note** that Canvas UI for some reason doesn't show its response correctly. Anyway, PolkadotJS does show it in Contracts section.

> 
>  * I wanted to instantiate the contract twice (with different params), but it errors out with the following message, at least via Canvas-UI: `Uncaught error. Something went wrong with the query and rendering of this component. Cannot read properties of undefined (reading 'createType')`. Other contracts seem to allow double instantiation (e.g. erc721). Let me know if you can reproduce and if you know a possible cause for this.
> 

I confirm that I can reproduce it at Canvas UI [current version](https://github.com/paritytech/canvas-ui/commit/a9073cf116f20c78312f2c46044a1b96ff99d305). However, PolkadotJS app allows instantiation of several candle auction contracts from the same code hash (with different salts), which I've just tested. So I guess this is not a problem of the contract itself, and maybe we should report this issue to Canvas UI? 

>  * Payout didn't work. Steps: bid from Alice, outbid by Bob. `get_winner()` returns Bob correctly. I am unable to call `payout()` from neither of the participating accounts. The error is:
> 
> 
> ```
> system.ExtrinsicFailed
> contracts.ContractTrapped
> ```

I can't reproduce it now. But, last time I saw this issue, it was because *OutOfGas*. Please try to increase Max Gas amount far this transaction. 

Thanks for your review and let me know if it helps!

**Comment by mmagician** [comment]
@agryaznov Thanks a lot for quick fixes and replies again!
Sure, it's enough for it to work via the polkadot-js/apps.
I've now accepted milestone 1: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/candle-auction-ink_1_mmagician.md

Congratulations and I'm looking forward to the M2!

**Pull request merged**
