### PR TITLE
grant management webapp milestone1 delivery

### PR DESCRIPTION
**Pull request by lawmeskiviahs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1766

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@lawmeskiviahs thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/grant_management_webapp_1_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue the evaluation.

**Comment by lawmeskiviahs** [comment]
@dsm-w3f Thankyou for your evaluation. We have made some changes to the repository. You may continue the evaluation on the master branch of the repository. Updates have been made to the documentation. I hope you'll find everything you need in the docs :D

# Environment Variables Setup Guide

This guide will help you set up your development environment for testing the code using docker-compose. We'll be using the `env.example` file provided in the root directory of the [backend repository](https://github.com/antiers-solutions/gmw-backend) to configure the required environment variables.

## Step 1: Clone the Repository

1. Take a fresh clone of the master branch of the [backend repository](https://github.com/antiers-solutions/gmw-backend)


## Step 2: Copy and Configure the Environment Variables

1. Locate the `env.example` file in the repository's root directory.
2. Create a copy of `env.example` in `/src/config` and name it `prod.env`.


## Step 3: Fill in the Environment Variables

Open the `prod.env` file in a text editor of your choice and fill in the following environment variables:

### General configuration
| Env name | Default value | Possible values | Description |
| ---------- | ------ |-------------------------|---------------------------------- |
| `PORT` | 7001 | any port number| The port number on which your application will listen |
| `DBNAME` | myappdb | any string value | The name of the database you'll be using |
| `REDIS_URL` | redis://localhost:6379 | any string value | The connection URL for your Redis server. |
| `MONGO_URI` | mongodb://localhost:27017/'DBNAME' | any string value | The connection URI for your MongoDB database |

### Github configurations
| Env name | Default value | Possible values | Description |
| ---------- | ------ |-------------------------|---------------------------------- |
| `GITHUB_CLIENT_ID` | - | provided by github | The client ID for your GitHub OAuth application. To get this, first [register an OAuth App](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authenticating-to-the-rest-api-with-an-oauth-app#registering-your-app). |
| `GITHUB_CLIENT_SECRET` | - | provided by github | The client secret for your GitHub OAuth application. Can be found in settings once and OAuth app is registered. |
| `GITHUB_REDIRECT_URI` | - | provided by github | The redirect URI for your GitHub OAuth application. This [Guide](https://docs.github.com/en/apps/oauth-apps/maintaining-oauth-apps/modifying-an-oauth-app) will help you in locating this in your OAuth app settings. |
| `APPLICATIONS_REPO` | '/repos/w3f/Grants-Program/contents/applications' | link to the application folder of any grants repo | URL to the folder containing application MD files |
| `DELIVERIES_REPO` | '/repos/w3f/Grant-Milestone-Delivery/contents/deliveries' | link to the deliveries folder of any grants repo | URL to the folder containing delivery MD files |
| `GITHUB_PULL_REQUEST_URL` | https://github.com/w3f/Grants-Program | link to the any grants repo | URL for getting data for Pull Requests |
| `GIT_USER_DETAILS_URL` | https://api.github.com/user | - | URL for getting user details |
| `GITHUB_ACCESS_TOKEN_CLASSIC` | - | any valid github Personal Access Token | Access token for GitHub API |
| `GITHUB_VERIFY_ACCESS_TOKEN_URL` | https://github.com/login/oauth/access_token | - | URL to check the validity of the access token |

## Step 4: Save and Run

1. Save the changes to the `prod.env` file.
2. Run the application using: ```docker-compise up -d```
3. The application should now use the configured environment variables.

## Step 5: Test

1. Locate the `env.example` file in the repository's root directory.
2. Create a copy of `env.example` in `/src/config` and name it `test.env`.


#### This guide has also been added to the documentation of the repository. If you encounter issues or need further assistance, please feel free to write to me at `shaivik@antiersolutions.com` If the need be we could get into a video call and help you setup the environment.

**Comment by lawmeskiviahs** [comment]
pinging @dsm-w3f

**Comment by dsm-w3f** [comment]
@lawmeskiviahs thank you for the improvements and fixes. I checked again and now I was able to run the application. It works, however there are some doubts and improvement suggestions. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/grant_management_webapp_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by lawmeskiviahs** [comment]
Thank you @dsm-w3f evaluating the delivery again. 
Regarding the pointers that you mentioned in the evaluation document:
1. We've opted for shortened project names on the front-end for a cleaner and organised look. Some longer project names take up to three lines in the table, which doesn't appear very neat. This can be changed if you want.
2. Filter on basis of date has been implemented. Regarding the cost, we're using different crypto forms for various grants, and sorting based on value will take some additional effort. We could consider adding this in the next milestone.
3. The proposals (applications) are part of the next milestone. The button you are referring to will also work by the time we are finished developing the next milestone. Meanwhile we have added a 'coming soon' screen to it.
4. The merge and status changes are only in the database and don't reflect on GitHub. We can do something about this in the second milestone.
5. Application mentioned in the web-app are proposals to the grants program (Proposal Pull Requests). Whereas projects are the applications that got accepted and now are being worked upon.
6. Borders have been added to all tables in the web app.

**Comment by dsm-w3f** [comment]
@lawmeskiviahs thank you for the improvements and fixes. I tested again and most of my comments were fixed/improved. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/grant_management_webapp_1_dsm-w3f.md) for details. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

Just a final comment. I think the application is becoming good and with minor adjustments could be possible to try to use it in practice. I'll try to gather more feedback from other members of the grants team. We can try to discuss possible improvements in your next grant application, if you plan to do it.

**Comment by semuelle** [comment]
@lawmeskiviahs, I noticed that your grant application lists DOT as payment, which we don't support. You can choose USDT payment on Polkadot Asset Hub. Can you please submit an amendment to provide a different currency and/or payment method as per our [application process description](https://grants.web3.foundation/docs/Process/how-to-apply)? Also, the invoice only lists fiat payment details. If you want to be paid in cryptocurrency, please add the payment address to the invoice.

**Comment by lawmeskiviahs** [comment]
Thankyou @semuelle for your observation. In the default delivery message above I have mentioned that the payment address is not the same as the one in the application. Could you please proceed with the payment with the details provided in the invoice?

**Comment by semuelle** [comment]
I don't see a comment in that regard. But if you would like to change the payment details, could you submit an amendment to the grant document? It's simple and usually quickly approved; we just want to make sure there is a "paper trail" in case there are questions later.

**Comment by semuelle** [comment]
Hey @lawmeskiviahs. We are good to go. It might still take a week for the invoice to be processed. But do let me know if you haven't heard back in a week.

**Comment by lawmeskiviahs** [comment]
@semuelle any updates on the payment?

**Comment by RouvenP** [comment]
hi @lawmeskiviahs we transferred the payment on 1st September. Could you check again whether you received it? If not, we will get in touch with our bank to investigate

**Comment by lawmeskiviahs** [comment]
Hi @RouvenP. We have recieved the payment. Thank-you so much

**Comment by RouvenP** [comment]
great, thanks for the update @lawmeskiviahs

**Pull request merged**
