### PR TITLE
Add nft_explorer-milestone_2.md

### PR DESCRIPTION
**Pull request by wuminzhe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/527

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @wuminzhe . I will look into it as soon as possible.

**Comment by semuelle** [comment]
Thanks again for the delivery, @wuminzhe. Looks good so far. Could you help me with the following issues?

- Local setup doesn't work. There were some issues with mysql packages missing from my system, which I managed to resolve, but now it's failing with `access denied` errors. I have replaced the host string with `localhost`. 
- When I run the dockerized version and open `localhost:3000` in the browser, I get the following two errors in the browser console:

```
Uncaught TypeError: Error resolving module specifier “application”. Relative module specifiers must start with “./”, “../” or “/”. 0.0.0.0:3000:38:7
Error connecting controller

 TypeError: glide1Hidden is null
```

**Comment by wuminzhe** [comment]
> Thanks again for the delivery, @wuminzhe. Looks good so far. Could you help me with the following issues?
> 
> * Local setup doesn't work. There were some issues with mysql packages missing from my system, which I managed to resolve, but now it's failing with `access denied` errors. I have replaced the host string with `localhost`.
> * When I run the dockerized version and open `localhost:3000` in the browser, I get the following two errors in the browser console:
> 
> ```
> Uncaught TypeError: Error resolving module specifier “application”. Relative module specifiers must start with “./”, “../” or “/”. 0.0.0.0:3000:38:7
> Error connecting controller
> 
>  TypeError: glide1Hidden is null
> ```

I will try it in another blank machine.

**Comment by wuminzhe** [comment]
@semuelle I tried the docker again, it is ok. I fixed some problems but I did not have your err.
Can you clean and try it again? 
https://github.com/uni-arts-chain/uniscan#docker

**Comment by semuelle** [comment]
Hi @wuminzhe, not sure what did the trick, but I'm one step further. I managed to fix the db connection issues by replacing `host` in the `database.yml` and by running `rails db:create` and `rails db:migrate`. Then there were some issues because the ImageMagick CLI under Ubuntu 20.04 does not includ `magick`. Removing `magick` from `magick identify` did the trick. Now the only failing test I have is the following (with and without docker). 

```
❯ rails test
Running via Spring preloader in process 54127
Run options: --seed 39107

# Running:

...................E

Error:
AccountsControllerTest#test_should_get_show:
ActionView::Template::Error: Mysql2::Error: Column 'collection_id' in where clause is ambiguous
    app/models/account.rb:28:in `tokens_by_collection'
    app/views/accounts/show.html.erb:5
    test/controllers/accounts_controller_test.rb:6:in `block in <class:AccountsControllerTest>'

rails test test/controllers/accounts_controller_test.rb:4

.........
```

**Comment by wuminzhe** [comment]
> Hi @wuminzhe, not sure what did the trick, but I'm one step further. I managed to fix the db connection issues by replacing `host` in the `database.yml` and by running `rails db:create` and `rails db:migrate`. Then there were some issues because the ImageMagick CLI under Ubuntu 20.04 does not include `magick`. Removing `magick` from `magick identify` did the trick. Now the only failing test I have is the following (with and without docker).
> 
> ```
> ❯ rails test
> Running via Spring preloader in process 54127
> Run options: --seed 39107
> 
> # Running:
> 
> ...................E
> 
> Error:
> AccountsControllerTest#test_should_get_show:
> ActionView::Template::Error: Mysql2::Error: Column 'collection_id' in where clause is ambiguous
>     app/models/account.rb:28:in `tokens_by_collection'
>     app/views/accounts/show.html.erb:5
>     test/controllers/accounts_controller_test.rb:6:in `block in <class:AccountsControllerTest>'
> 
> rails test test/controllers/accounts_controller_test.rb:4
> 
> .........
> ```

I fixed the problem, you can try it again.

```
❯ DB_HOST=127.0.0.1 RAILS_ENV=test rails db:create
❯ DB_HOST=127.0.0.1 RAILS_ENV=test rails db:migrate
❯ DB_HOST=127.0.0.1 rails test
```

If the docker compose failed, you can also see the final result in https://uniscan.pro/

**Comment by semuelle** [comment]
Thanks for the update. I can confirm all the tests are passing now. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/uniscan-nft-explorer_2_semuelle.md).

I will forward your invoice for processing.

**Comment by wuminzhe** [comment]
Thanks for your evaluation!

**Comment by wuminzhe** [comment]
@semuelle When will the invoice be processed?

**Comment by semuelle** [comment]
Hi @wuminzhe, it seems that I missed forwarding your invoice. I will ask for it to be processed asap. Very sorry about that!

Could you send an updated one with our new address (Baarerstr. 14 instead of Reiffergässli 4)?

**Comment by wuminzhe** [comment]
@semuelle I have updated the address in the invoice form.

**Comment by semuelle** [comment]
Thanks. I just forwarded it to our operations team. I'll let you know as soon as I hear back.

**Comment by RouvenP** [comment]
hi @wuminzhe we just transferred the payment.

**Pull request merged**
