### PR TITLE
Typechain Revived Milestone 1

### PR DESCRIPTION
**Pull request by WookashWackomy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2289 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by WookashWackomy** [comment]
> Thanks for the delivery, @WookashWackomy. I am currently working my way through the documentation. However, when I run `npm i` on the example project, I get
> 
> ```shell
> > npm i
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @c-forge/typechain-compiler@^0.5.16.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> ```
> 
> It looks like the most recent version is 0.2.0, maybe you forgot to publish it?

Hi, sorry you've encountered this issue. We've missed the refinement of that particular docs file. It's updated now, additionally couple of fixups made along the way merged in. Regarding version - 0.2.2 is the newest one (reflected in docs). Gonna handle the versioning in milestone 2, during ironing out the last details.
 
 Also, the whole example project that's being laid down in the document you've tried to go through was integrated into the repository. https://github.com/C-Forge/typechain-polkadot/tree/main/examples/typechain-compiler-example.
 
Should be all good now!

**Comment by semuelle** [comment]
Sorry, I am now following the [testing guide](https://github.com/C-Forge/typechain-polkadot/blob/aec8ed9ed2d4f87e08be4c435cdcc68a7bba9826/tests/README.md), and `pnpm run test` keeps failing with missing packages (fs-extra, handlebars, globby, ...). Did I miss a step?

**Comment by WookashWackomy** [comment]
> Sorry, I am now following the [testing guide](https://github.com/C-Forge/typechain-polkadot/blob/aec8ed9ed2d4f87e08be4c435cdcc68a7bba9826/tests/README.md), and `pnpm run test` keeps failing with missing packages (fs-extra, handlebars, globby, ...). Did I miss a step?

Hey, as long as you run `pnpm i` beforehand it should be all good. We've verified that today and the packages install properly for us, I don't really know why would it fail for you. The only thing that come to my mind is that you use `npm` instead of `pnpm` and the install command **does not** install dependencies for workspace packages (hence the behavior you've experienced).

That being said - we've added npm workspace support to support `npm <something>` workspace wide commands (meaning `npm i` & `npm run test` or `npm run build  --workspaces --if-present` will work as well as the mentioned in README.md's `pnpm i`, `pnpm run test` or `pnpm -r build` commands.

If you update, run install command and it still's failing - please let me know. Could be something OS/environmental.... If possible over Element (@lukas7980:matrix.org), telegram: @wookashwackomy or Discord (@wookashwackomy) so I can help better/quicker

**Review by semuelle — APPROVED** [review]
Hi @WookashWackomy, thanks for the fixes. I am happy to report that your milestone is hereby accepted. Other than the minor issue with the testing instructions, everything worked out of the box. Much appreciated! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain-revived_1_semuelle.md).

**Comment by RouvenP** [comment]
hi @WookashWackomy we're about to proceed with the transfers. we will send the USDT on AssetHub and the DOTs on the relay chain - could you briefly confirm whether that is OK?

**Pull request merged**
