### PR TITLE
Create Rubeus_keeper_Milestone_2.md

### PR DESCRIPTION
**Pull request by dsrdrk11a**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1124

### CODE REVIEW

**Comment by dsrdrk11a** [comment]
Thank you, @keeganquigley !
The link is changed.
We plan to apply for a follow-up grant to add autofill functionality, so **** and recovery (as well as registration for a new wallet) will be included in it.

**Comment by keeganquigley** [comment]
Thanks @dsrdrk11a I appreciate it! My eval is completed, and you can find it [here](https://github.com/keeganquigley/Grant-Milestone-Delivery/blob/master/evaluations/rubeus_keeper_2_keeganquigley.md). The only outstanding issue is that I realized that there are no UI tests. Typically we ask for core functionalities to be covered by tests, and your application notes that unit tests will be provided for M2. Are you able to point me to some or make some basic tests using Cypress or Jest or something similar? Thanks!

**Comment by keeganquigley** [comment]
I have forwarded your invoice for payment. Please expect up to 14 days for delivery.

**Comment by dsrdrk11a** [comment]
Great, @keeganquigley ! Thank you for your review!
We are planning to apply for the follow-up grant this week, so the UI tests using Cypress will be included.

**Pull request merged**
