### PR TITLE
Fair Squares milestone 4 delivery

### PR DESCRIPTION
**Pull request by ilhanu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/971 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @ilhanu, I look forward to diving into it as soon as possible. Don't worry about the Guardian. @dsm-w3f could you look into why it detects a secret in your evaluation?

**Comment by dsm-w3f** [comment]
@ilhanu and @alxs the alert was fixed in [this commit](https://github.com/w3f/Grant-Milestone-Delivery/commit/050d691093ec180f25538a86aeb8f5494466010a). Please replicate this change wherever is needed to bypass Git Guardian alert. I talked with Massbit to notify this and happily there is no problem in the disclose of the password, it was from a test repository.  if it is convenient just ignore this alert.

**Review by alxs — CHANGES_REQUESTED** [review]
Thank you Diogo and sorry @ilhanu for the delay in getting back to you. A few things from my side:

- The `docker_run` script fails for me with the following output:
  ```
  ./scripts/docker_run.sh
  *** Start Fair Squares node  ***
  Removing network fair-squares_default
  Creating network "fair-squares_default" with the default driver
  Creating fair-squares_dev_run ... error

  ERROR: for fair-squares_dev_run  Cannot create container for service dev: invalid mount config for type "bind": bind 
  source path does not exist: /home/aleixo/fair-squares/.local

  ERROR: for dev  Cannot create container for service dev: invalid mount config for type "bind": bind source path does not exist: /home/aleixo/fair-squares/.local
  ERROR: Encountered errors while bringing up the project.
  ```
- In deliverable 0c., you specified you would deliver integration tests in addition to unit tests. Could you point me to these?
- Could you also provide a tutorial that "walks through how finalization works, how this role can be acquired and why it was created" as described in the application, or add it to the article?

**Comment by ilhanu** [comment]
@alxs thank you for the review! Below my answers to your feedback and issues you came across.

> * The `docker_run` script fails for me with the following output:

The docker run script if forked from [node-template](https://github.com/substrate-developer-hub/substrate-node-template/blob/main/scripts/docker_run.sh).  The problem can be solved when you create `.local` folder in your `$HOME` directory.  The script expects this folder to already exist

We mentioned in the milestone would provide a [Dockerfile](https://github.com/Fair-Squares/fair-squares/blob/main/Dockerfile) to build and test all functionality and additional to that we are providing images [here](https://github.com/Fair-Squares/fair-squares/pkgs/container/fs-node) to test it even quicker with instructions [here](https://github.com/Fair-Squares/fair-squares#docker-images).


> * In deliverable 0c., you specified you would deliver integration tests in addition to unit tests. Could you point me to these?

For us the definition of integration tests is the cross-pallet testing, as currently there is not much more to have integration tests with. From the first milestone the integration test was limited, but as the pallets and runtime have increasing functionality so do the integrations tests. A good example of our integration tests that have been created during M4 in the [asset-management-pallet](https://github.com/Fair-Squares/fair-squares/blob/main/pallets/asset_management/src/tests.rs#L87-L579)


> * Could you also provide a tutorial that "walks through how finalization works, how this role can be acquired and why it was created" as described in the application, or add it to the article?

I have expanded in the article and the guide the details why this role is relevant for a real world implementation and how it can be acquired.  The guide covers in step 1 and 6. how it can be acquired and works. Furthermore I linked the article to the guide.

**Comment by alxs** [comment]
Thank you for your answers! With this, I'm happy to let you know that the milestone has been accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fair-squares_4_alxs.md).

I'll notify the operations team to pay out your invoice. As usual, please allow for up to 14 days for processing.

**Comment by RouvenP** [comment]
hi @ilhanu we transferred the payment today

**Pull request merged**
