### PR TITLE
milestone-1 delivery of SEOR code-less smart contract platform

### PR DESCRIPTION
**Pull request by AKACoder**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @AKACoder. We will look into it as soon as possible.

**Comment by AKACoder** [comment]
> Hi @AKACoder, did you actually check if the test coverage is >80%? I am not keen to nail you down to that number, but the contract states you provide "proper unit-test coverage (min 80%) to ensure the robustness and safety", and I currently only see about one test per (Solidity) contract function, and none on the ink! side.

@semuelle  , So sorry for that, due to our mistakes in work and insufficient understanding of unit testing, thus the unit testing part is missing and self-review is insufficient. We will add more test codes  in few days and try our best to improve and meet the request in our application.

**Comment by AKACoder** [comment]
Hi @semuelle , we add more testing code for both solidity contract and !ink contract.
And since remix-tests does not have a coverage measurement tools, we switched remix-tests to truffle & solidity-coverage for solidity testing.

We use the low-code-platform-dev branch for this milestone's development as we mentioned in the document.

Please review again, thanks!

**Comment by semuelle** [comment]
Thanks for following up on the tests and coverage report, @AKACoder. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/993862e3f52f11e7a25c21a35b719cd2cdf2fdce/evaluations/seor_1_semuelle.md) and your milestone is hereby accepted. :tada: 

I will forward your invoice for processing.

**Comment by AKACoder** [comment]
@semuelle, We are very happy that our milestone have been accepted. Thank you for the review!

We will continue to work to complete the follow-up milestones as soon as possible.

**Comment by RouvenP** [comment]
hi @AKACoder we transferred the payment for milestone 1.

**Pull request merged**
