### PR TITLE
Asylum: milestone 1

### PR DESCRIPTION
**Pull request by YaremenkoM**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/805

### CODE REVIEW

**Comment by LastSymbol0** [comment]
Hey!

I know that web3 foundation is pretty busy right now as you have a lot of deliveries.
But just let me know if there are any blockers for you to review our request and I would be glad to help you!

**Comment by LastSymbol0** [comment]
Hi @semuelle !

Tagging you because you were in conversation on our application PR.
Could you please help me with an estimation for that delivery review?

**Comment by semuelle** [comment]
Sorry for the delay, @LastSymbol0 & @YaremenkoM. I will look into it tomorrow.

**Comment by semuelle** [comment]
Hey @YaremenkoM & @LastSymbol0. I had a look at your delivery today. Sorry again for the delay here. 

Code and documentation look very good so far, but I noticed that you didn't submit a Docker file/image or an article. They are more or less mandatory for all milestones, at least where appropriate (M1s often come without articles for understandable reasons). Could you also provide links for deliverables 1.1 to 1.3, either to the most important code sections for these functionalities or references to it in the testing guide?

**Comment by LastSymbol0** [comment]
Hey @semuelle , thanks for your feedback!

We've just submitted all requested updates:
- added Dockerfiles to our repositories (and docker-compose to UI repo) and mentioned them in the testing guide
- extended the testing guide regarding multiple 3d and 2d interpretations
- added deliverables 1.1 to 1.3 and links to the particular sections of the testing guide

Looking forward to the review!

**Comment by semuelle** [comment]
Thanks for the update, @LastSymbol0, and sorry for the late reply. 

I had some trouble getting the setup to complete. `host.docker.internal` seems to be a Windows specific variable. Also, the manual setup instructions are missing the `yarn` and `yarn start` steps. I got around those issues, but it would be great if you could clear those up for the next milestone. All the functionality seems to be there, only I cannot mint any NFTs. I was able to mint them through polkadotjs, but clicking the [`mint item` button](https://gitlab.com/asylum-space/asylum-ui/blob/6674dbb4013fb2bdd4caf8c48cae00bf742938b0/packages/game-developers-console/src/pages/game-templates/index.tsx#L74) does nothing. Am I missing something?

Other than that I am quite happy with the code and material. The UI is really sleek, great job!

**Comment by LastSymbol0** [comment]
Hi @semuelle , thanks for your comments!

We fixed issues with docker and tested them, now everything should work well. Also, the documentation was reorganized, considering your point about scripts (yarn start and yarn seed)

Speaking about minting items -  as the application says - functionality related to the items is part of the second milestone, so we do not work on it within the first one. To clarify this moment we've also added the notification to the app by pressing the "Mint" button.

**Comment by semuelle** [comment]
Thanks for the update, @LastSymbol0. The grant document actually [mentions minting in milestone 1](https://github.com/w3f/Grants-Program/blob/master/applications/asylum.md?plain=1#L286), but I see now what you are saying. 

Your milestone is hereby accepted. Congratulations. :) I will forward your invoice for processing. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/asylum_1_semuelle.md).

**Comment by LastSymbol0** [comment]
Amazing, thanks for your review!

**Pull request merged**
