### PR TITLE
Create ParaSpell-followup-m1.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1245

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @dudo50. We'll look into it as soon as possible.

**Comment by randombishop** [comment]
@dudo50 Thanks for this delivery. I'll start working on the evaluation and get back to you with feedback in upcoming days...

**Comment by dudo50** [comment]
@randombishop thanks, sounds good!

**Comment by randombishop** [comment]
Hi @dudo50 !
I am getting an error when I try `make dockerLaunch`
Please find attached the full log in my machine.
Can you help me fix it?
[paraspell_docker.log](https://github.com/w3f/Grant-Milestone-Delivery/files/10346492/paraspell_docker.log)

**Comment by dudo50** [comment]
Checking on this @randombishop , should ping you with answer shortly :)

**Comment by dudo50** [comment]
@randombishop this was the same issue that our previous reviewer had. I have tested this on 3 laptops now (MacOS - Intel mac, Ubuntu and WIndows PC (both clean install)) which did not display this issue. Perhaps if you have M1 or M2 mac this could be why. https://github.com/w3f/Grant-Milestone-Delivery/pull/584
Let me know if pull request I linked helped.
With kind regards,
Dudo

**Comment by randombishop** [comment]
@dudo50 Thanks for the link, turned out to be the same issue with Mac M1 indeed.
Moved to a different linux box and the docker running fine now, cheers!

**Review by Noc2 — APPROVED** [review]

**Comment by randombishop** [comment]
Hey @dudo50 

Happy to inform you that your delivery was accepted.

Evaluation notes here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_1_randombishop.md

I'll forward your invoice to the finance team, please allow for up to two weeks for processing.

**Pull request merged**
