### PR TITLE
pallet-verifier (milestone 1 & 2)

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2234 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @davidsemakula ,
thanks for submitting your delivery. I'd like to ask you to either submit the deliveries for individual milestones separately or point out which work has been done to achieve each milestone. In it's current format it's hard to differentiate the work that went towards each milestone. This would make it easier for me to review. Best ✌️

**Comment by davidsemakula** [comment]
Hi @PieWol

> I'd like to ask you to either submit the deliveries for individual milestones separately or point out which work has been done to achieve each milestone.

I'll do the latter and ping you. 🙂

**Comment by PieWol** [comment]
Great, thank you :)

**Comment by davidsemakula** [comment]
Hi @PieWol 

> point out which work has been done to achieve each milestone.

I've added the details to the delivery document.

**Comment by PieWol** [comment]
Great, thanks. I'll let you know once I made progress on the review.

**Comment by davidsemakula** [comment]
@PieWol I pushed a few updates, please pull the latest from master before reviewing 🙂

**Comment by PieWol** [comment]
Thanks for the update @davidsemakula :)

**Comment by PieWol** [comment]
Hey @davidsemakula ,
sadly when I try to follow the readme and install pallet-verifier I run into the issue that it's using the authenticated ssh request for getting additional code from github. What do you think about switching this to the http option that doesn't need authentication?

See 
```ubuntu@ip-172-31-17-139:~/pallet-verifier$ cargo install --locked --path ./
  Installing pallet-verifier v0.1.0 (/home/ubuntu/pallet-verifier)
    Updating crates.io index
    Updating git submodule `git@github.com:microsoft/vcpkg.git`
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: failed to get `mirai` as a dependency of package `pallet-verifier v0.1.0 (/home/ubuntu/pallet-verifier)`

Caused by:
  failed to load source for dependency `mirai`

Caused by:
  Unable to update https://github.com/davidsemakula/MIRAI.git?branch=pallet-verifier-2024-02-08#7f2d3cee

Caused by:
  failed to update submodule `vcpkg`

Caused by:
  failed to fetch submodule `vcpkg` from git@github.com:microsoft/vcpkg.git

Caused by:
  process didn't exit successfully: `git fetch --tags --force --update-head-ok 'git@github.com:microsoft/vcpkg.git' '+refs/heads/*:refs/remotes/origin/*' '+HEAD:refs/remotes/origin/HEAD'` (exit status: 128)```

**Comment by davidsemakula** [comment]
Hi @PieWol 
Technically, the vcpkg git submodule affected by this is from upstream MIRAI, so before I make a change that I will eventually have to upstream ([I've already started upstreamed a few other things, so that's not a issue](https://github.com/endorlabs/MIRAI/pulls?q=is%3Apr+author%3Adavidsemakula)), can you try to comment out [this line in `.cargo/config.toml`](https://github.com/davidsemakula/pallet-verifier/blob/master/.cargo/config.toml#L3) and LMK if you still get an error?

**Comment by davidsemakula** [comment]
Pinging @PieWol 🙂

**Comment by davidsemakula** [comment]
@PieWol The [suggested cargo config update](https://github.com/w3f/Grant-Milestone-Delivery/pull/1222#issuecomment-2514551456) appears to fix the issue in my testing, so I've pushed an [update to master](https://github.com/davidsemakula/pallet-verifier/blob/1ee6421a42ab32a9b3cfbf7abd0440d64c65d30f/.cargo/config.toml) with the fix applied.

**Comment by PieWol** [comment]
Thanks, I'll update you later today.

**Comment by PieWol** [comment]
@davidsemakula 
I think the issue lies in this [file](https://github.com/davidsemakula/MIRAI/blob/pallet-verifier-2024-02-08/.gitmodules). The url should be using the https url. Would you mind changing this? ^^
Thanks.

**Comment by davidsemakula** [comment]
@PieWol should be fixed, please pull latest `Cargo.lock` from master

**Comment by PieWol** [comment]
Hey @davidsemakula ,
everything looks good so far and I'm expecting to have both milestones evaluated by Monday if nothing goes wrong :) I'm just doing some additional testing now.

I have put up a [draft pr](https://github.com/w3f/Grant-Milestone-Delivery/pull/1230) already for the milestone 1 evaluation. 

Thanks

**Comment by PieWol** [comment]
Hey @davidsemakula ,
when I try to run ``cargo verify-pallet`` on this [pallet](https://github.com/Moonsong-Labs/storage-hub/blob/main/pallets/proofs-dealer/) then I get this error:
```
error: Failed to generate tractable entry points for any dispatchable function in public interface
  |
  = help: Add some unit tests for dispatchable functions.

error: could not compile `pallet-proofs-dealer` (lib) due to 1 previous error
```

Whats the reason for this error? Is it because the testing functions have different names than the actual calls of the pallet? 🤔

**Comment by davidsemakula** [comment]
@PieWol Checking it out ... the names of the tests shouldn't matter though 🙂

**Comment by davidsemakula** [comment]
Hi @PieWol

The issue was this [pallet](https://github.com/Moonsong-Labs/storage-hub/blob/main/pallets/proofs-dealer/) has a cyclic transitive dependency on itself in test mode ([via some of its dev dependencies](https://github.com/Moonsong-Labs/storage-hub/blob/e3d42d3b262bead49dafc42bdff22fd5c6105660/pallets/proofs-dealer/Cargo.toml#L49-L50) -  [see also](https://github.com/Moonsong-Labs/storage-hub/blob/e3d42d3b262bead49dafc42bdff22fd5c6105660/pallets/providers/Cargo.toml#L43)). So our custom rustc driver was being prematurely invoked on this cyclic dependency (instead of the "primary" package - for the compiler, these are different artifacts because of different compiler flags, configs, features et.c). So no unit tests where being found because the test harness (and hence the tests module in this case) is NOT built/compiled for dependencies (only for the "primary" package).

I've updated the cargo subcommand to [detect these cases and only invoke our custom rustc driver for the right artifact](https://github.com/davidsemakula/pallet-verifier/blob/a0d40d98523dfb8e3e1b002f529f3191747f9f37/src/main.rs#L56-L61), so it should work fine now.

Thanks for finding/reporting the issue 🙂

**Comment by PieWol** [comment]
Hey @davidsemakula ,
great job figuring this out and fixing it so quickly.

**Comment by PieWol** [comment]
Congratulations on finishing this grant 🎉 . Nice work!
I really hope this will be maintained and refined so it becomes a must-have tool for pallet development 🙏

**Pull request merged**
