### PR TITLE
Universaldot.me M2

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/714

### CODE REVIEW

**Review by alxs — CHANGES_REQUESTED** [review]

**Comment by semuelle** [comment]
Hey @JosephKnecht-lab. Sorry for the delay, but I was finally able to review your delivery.

Generally, I'm quite happy with it. It looks good, and most things worked out of the box. I very much appreciate the thorough inline documentation! I just had some tests failing (looks like it's just a misnamed div), and I managed to break the UI with a simple input. Could you add some _basic_ input validation and verify that the tests succeed? Lastly, `yarn npm audit` found several high and one critical severity issues, it would be great if you could make sure that you are using the latest package versions where possible. See my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/universaldot-me_2_semuelle.md).

**Comment by JosephKnecht-lab** [comment]
Hi @semuelle 

Thank you for the evaluation and the nice words. 

We have incorporated most of your feedback already in the following pull request: https://github.com/UniversalDot/universal-dot-front-end/pull/19

We were unable to find any critical severity issues with our npm packages. Running `yarn npm audit` on `universal-master` and `universal-develop` yielded `YN0001: No audit suggestions`. Can you let us know where you encountered the critical severity issues? 

Regarding your comments on the tests, we are still working with a design team to finalize the [Dao design](https://github.com/UniversalDot/documents/blob/master/designs/documents/DAODesign2.pdf). We submitted the delivery in the current state because we believe we met the milestone requirements. Since we know that major parts of the UI will change, we didn't want to focus too much on writing tests that we have to rewrite later. 

Let us know if you have further questions or comments.

**Comment by semuelle** [comment]
Hey @JosephKnecht-lab, thanks for the update. 

I just verified that the tests run successfully on the pull request. 

The audit issues show up when running `yarn npm audit --recursive`. However, I just had a closer look and noticed that most issues are via `react-scripts` and that there was only one version published after 4.0.3, and that rather recently, so no need for an update. 

Regarding the input validation: when reviewing the last milestone of a grant, we tend to look a bit closer as anything after that is outside our influence. Seeing your SBP application, roadmap and design doc, I'm willing to wave it through as is. I updated my evaluation notes and your milestone is hereby accepted.

**Comment by JosephKnecht-lab** [comment]
Thanks, @semuelle. 

Thank you to everyone from WEB3 Foundation for making it possible to build the MVP. 

Now onto building the full application.

**Comment by meldien** [comment]
Hi all, 
I noted the billing address is missing. Please update the invoice with following address:
Web 3.0 Technologies Foundation
Baarerstrasse 14
6300 Zug

Many thanks.

**Comment by RouvenP** [comment]
hi @JosephKnecht-lab we transferred the payment last Friday. Thanks!

**Pull request merged**
