### PR TITLE
Nolik Milestone #2

### PR DESCRIPTION
**Pull request by amrbz**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/759 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by amrbz** [comment]
@takahser Sure, no problem. Thank you very much!

**Comment by keeganquigley** [comment]
Hi @amrbz I have started the process of evaluating your milestone. Please give me some time to fully understand your project and I will reach out to you with any questions that I may have. Thanks!

**Comment by amrbz** [comment]
Hi @keeganquigley Great, I hope this one will be easy for you. Thanks!

**Comment by andredif** [comment]
Hi @amrbz , I'm also currently reviewing your milestone. While I successfully managed to generate wallet and account, compose message and send it, it seems that in the documentation the command needed to read messages is missing, only valid arguments are shown. Can you please check it and fix it?Thank you very much.

**Comment by amrbz** [comment]
Hi @andredif 
Yeah, for some reason missed this one. My bad. I've updated the README file.
The required command would be:
`cargo run -- get messages -a alice`

**Comment by keeganquigley** [comment]
Thanks for the evaluation @andredif and thanks for your patience @amrbz while I tested everything out and ran all the tests. The CLI app works great! Excellent test coverage as well. Docker setup was easy. I'm good to go ahead and pass this milestone!

**Comment by amrbz** [comment]
Thank you @andredif @keeganquigley @takahser for your work and for the great news! You made my day ) It was a pleasure to work with you on this project. I'm currently writing an article that describes in details the idea behind the protocol and intend to publish it during the next week. I've applied to [Polkadot DevCamp](https://medium.com/polkadot-network/polkadot-devcamp-intake-2-ddebc5fb9096) and going to join Substrate Builders program as well. So, I hope that we will have a chance to work closely in future. Thank you very much, guys )

**Comment by keeganquigley** [comment]
@andredif You're very welcome! I will share the news with the team. Your invoice has been forwarded for payment.

**Comment by amrbz** [comment]
Hi guys,
I've published the article:
[https://medium.com/@amrbz/decentralising-messaging-f4cc73d4d9b7](https://medium.com/@amrbz/decentralising-messaging-f4cc73d4d9b7)

**Pull request merged**
