### PR TITLE
Add subscript_lang milestone-1 delivery

### PR DESCRIPTION
**Pull request by synote**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks, we'll let you know once we've evaluated the delivery.

**Comment by semuelle** [comment]
Hi @synote, I can only find unit tests for some of the utility functions (`__tests__`). Your proposal promises you [`will have unit-test for all the following runtime api.`](https://github.com/w3f/Open-Grants-Program/pull/61/files#diff-5f841c95463791ecffdc5da1c2d2791010cba174291721dbdbe9a5dcecf93d93R84) Is there a reason you didn't commit any other tests?

**Comment by semuelle** [comment]
Also, are you aware of [Ask!](https://github.com/patractlabs/ask/)? It would be useful to know if there are any significant differences between your project and theirs. And obviously some work might not need to be done twice.

**Comment by synote** [comment]
For ink!, there is a [off chain environment](https://github.com/paritytech/ink/blob/v3.0.0-rc2/crates/env/src/engine/off_chain/mod.rs) for testing purpose, though it's still feature limited. Solidity also has a js vm for unitest. It's not sufficient with mocking some code to implement the contract module host functions. So the low-level contract environment need much more work to cover the seal api.  It may be a more complex feature for the future milestone to provide the mock-chain environment which is similar to ink!. We only use example code to test some seal api. As to ask!  impl,  we may provide different api abstraction and decorator for the contract developer. We extend the standard AssemblyScript compiler to implement decorator to provide contract feature. For some memory operation feature, the subscript lib may implement a different codec compared with limechain's scale-codec as it's not well suited for contract scenario. Both contract implementation will be compatible with the ink! and polkajs contract api.

**Comment by semuelle** [comment]
@synote: in your delivery document, would you mind documenting what exactly is missing to complete the tests? We obviously don't expect perfect test coverage, but the more detailed the delivery documentation, the better feedback we can give regarding developer needs.

**Comment by synote** [comment]
Tests notes was added for the missing coverage. CommitId is added for all the delivery link url as we are still moving on the project for new features.

**Comment by semuelle** [comment]
Thanks for the follow-up. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/26314b7e2f00faa5c421a530315e24e719d93dab/evaluations/subscript_1_semuelle.md) and your milestone is now accepted. :tada: 

Your invoice will be forwarded for processing.

**Comment by RouvenP** [comment]
hi @synote we just sent a test transaction of 0.001 BTC. Could you confirm if received?

**Comment by synote** [comment]
@RouvenP  I've received the test transaction.

**Comment by synote** [comment]
Hi @RouvenP,  I wonder if there are any updates about the payment. Let us know if the payment is available.

**Comment by RouvenP** [comment]
hi @synote apologies for the delay. we transferred the payment today.

**Comment by synote** [comment]
Thanks @RouvenP, I've received the payment.

**Pull request merged**
