### PR TITLE
Setheum Milestone 1 - SERP Pallets

### PR DESCRIPTION
**Pull request by JBA-Khalifa**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery. Could you add the link to the original accepted PR, as well as the link to your testing guide, as specified by deliverable 0b. of your contract, please?

**Comment by JBA-Khalifa** [comment]
Thanks for the review and sorry for the late reply

**Comment by mmagician** [comment]
Thanks for the updates. Could you make sure to only edit your own file (and not the template `deliveries/milestone-delivery-template.md`) please?

**Comment by JBA-Khalifa** [comment]
Okay, thank you

**Comment by JBA-Khalifa** [comment]
Thanks for the opportunity  to be nominated for this Grant. I just want to inform you that, I am currently the only Rust developer in my team, the rest are still learning and there are Solidity developers and so on. 

There used to be one more if you see, Valentine Oragbakosi left just 8 days after we got the grant because I couldn't pay him stipends and he said it is overwhelming and he didn't expect it to be this overwhelming. 

From then onwards I did it all alone with many sleepless nights. I have a lower middle-class level of experience in rust, just a few weeks of learning as we were starting. Now I am finding it very difficult to make the unit tests, mock and a clean seamless code. I am asking your favourable consideration to receive the transaction and get a helper to fix the issues together, God's willing I will get it fixed within a few days. 

I rushed to submit the deliverables, but I am sure they are not perfectly made. Please grant me and give me a few more days to fix it. I need the transaction to get help. 

But if you can help me with the issues and how to tackle them and make unit tests, I will be the most grateful. I need to build a successful Network.

**Comment by mmagician** [comment]
@JBA-Khalifa thank you for the info & I'm sorry to hear about your team. We haven't yet assigned anyone to check your delivery. Unfortunately we cannot issue the transaction yet, as that is only possible after one of our reviewers has accepted the milestone.  If you need extra time to polish the code, that should not be a problem, I can see that you're actively working on your repo. 

Should you decide to do go for an extension, please close this PR for the time being & I will make a note internally to extend the timeline of your project. After you're satisfied with your code you can open another PR. 
This is all I can do for you, I hope that helps.

**Comment by JBA-Khalifa** [comment]
Thank you very much @mmagician. This more than helps a lot. I really appreciate this opportunity.

**Pull request closed without merging**
