### PR TITLE
ink! analyzer (phase 2) - milestone 4

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1904 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by davidsemakula** [comment]
It looks like the "Google Sheet Update" action is hitting some kind of limit (or bug) https://github.com/w3f/Grant-Milestone-Delivery/actions/runs/7377042382/job/20070544925

**Comment by keeganquigley** [comment]
Thanks @davidsemakula you can disregard the error, we added it in manually. I will get started on this today!

**Comment by davidsemakula** [comment]
Hi @keeganquigley 👋 

So I just submitted [milestone 6](https://github.com/w3f/Grant-Milestone-Delivery/pull/1110) as well.
I'm mentioning here because it may make sense to review them together because in terms of manual testing (via VS Code), milestone 6 is exactly the same as this milestone combined with milestone 3 (which you already reviewed - [PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1072) and [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_3_keeganquigley.md) - including manual testing via VS Code).

On the automated testing side, my default testing instructions run unit and integration tests for both the semantic-analyzer (ink-analyzer crate) and language server (ink-lsp-server crate), so the review will also be pretty much identical for both milestones from your perspective.

I thought I'd point this out since it could save some time on both sides 🙂 

Lastly, if you decide to review them together, the [lsp-server-v0.2.22](https://github.com/ink-analyzer/ink-analyzer/releases/tag/lsp-server-v0.2.22) tag/release for the language server in milestone 6 is exactly the [same commit](https://github.com/ink-analyzer/ink-analyzer/commit/b7f3724353bea1cdf6d50f021753cd93a8350c59) as the [analyzer-v0.8.20](https://github.com/ink-analyzer/ink-analyzer/releases/tag/analyzer-v0.8.20) tag/release for the semantic analyzer. So you can clone using either tag/release for local testing (and we can update this delivery to mention the analyzer-v0.8.20 release instead of the analyzer-v0.8.17 release).

**Comment by keeganquigley** [comment]
Thanks @davidsemakula apologies for the delay, I should have some notes for you tomorrow.

**Comment by keeganquigley** [comment]
Great work as usual! I did end up reviewing them together, you can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_4_keeganquigley.md).

**Comment by davidsemakula** [comment]
@keeganquigley Awesome! Thanks for the thorough review(s) and positive feedback 🙂.

The [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ink-analyzer.ink-analyzer) install base is also growing steadily at about ~220 unique installs now (roughly +40 new unique installs since the last review) 🚀

**Comment by davidsemakula** [comment]
I've submitted the invoice 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula we just sent the payment

**Comment by davidsemakula** [comment]
Hi @RouvenP,
Received ... thanks!

Just in case you missed it, there's also a second delivery/invoice that was approved the same day as this one
(see https://github.com/w3f/Grant-Milestone-Delivery/pull/1110)

**Comment by RouvenP** [comment]
@davidsemakula thanks for confirming. Yes, we're aware - this one is still in the process and will most likely be paid out next Friday

**Comment by davidsemakula** [comment]
@RouvenP Gotcha ... thanks!

**Pull request merged**
