### PR TITLE
Add delivery milestone 1, IPFS utilities

### PR DESCRIPTION
**Pull request by dobschal**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the DAI payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1187

### CODE REVIEW

**Comment by randombishop** [comment]
Hi @dobschal Thanks for this delivery, I will be working on the evaluation and will get back to you with feedback in next few days...

**Comment by randombishop** [comment]
Hi @dobschal !
I managed to run tests on the substrate codebase; but it seems like the frontend doesn't come with unit tests.
Did you deliver those? And if yes, can you please document how to run them?
Thank you!

**Comment by dobschal** [comment]
Hey @randombishop ,
the frontend has no unit tests, as it was used for testing the implemented logic on the Substrate chain itself.

**Comment by thomasdingler** [comment]
@Noc2 fyi, milestone 1 was delivered.

**Comment by randombishop** [comment]
Hey @dobschal, thanks for the precision.
No problem with that, but can please you just remove the link to the frontend in the 0c. item deliverables. 
I expected to find tests when I found that link.
Thank you

**Comment by dobschal** [comment]
Thanks @randombishop,
removed the repo from client app used for testing from 0c.

**Comment by randombishop** [comment]
Hey @dobschal happy to accept this delivery.

Please find my evaluation here:
https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ipfs_utilities_1_randombishop.md

I will forward your invoice; please expect up to 2 weeks for processing.

**Pull request merged**
