### PR TITLE
Tracking Chain - Milestone 1

### PR DESCRIPTION
**Pull request by FedeC87p**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1847

### CODE REVIEW

**Comment by Whisker17** [comment]
Hey @FedeC87p, I've finished my evaluation here #969. Everything goes fine for me, just a small problem: I can't open Swagger UI. Could you have a look on that, appreciate it!

**Comment by FedeC87p** [comment]
Thanks for the review @Whisker17 Could you give me some details about the error? Because it's working for me, Swagger is configured on the Triage API service (not WebApplication), which at least in the case of my examples is on port 5000. The generated json is located at http://localhost:5000/swagger/v1 /swagger.json (web interface at http://localhost:5000/swagger)

**Comment by Whisker17** [comment]
Hey @FedeC87p, I just had a test again, seems everything goes fine with me(including the Swagger UI). So I would accept this milestone, appreciate your work!

**Comment by dsm-w3f** [comment]
@FedeC87p thank you for the milestone delivery and @Whisker17 thanks for the external evaluation. I was able to check the the application. However, in the Ink! smart contract there is a problems to compile it. I needed to add the code below to the Cargo.toml to be able to compile it.
```
[lib]
path = "lib.rs"
crate-type = ["cdylib"]
```
This problem don't that prevents the approval of the milestone but would be nice to fix it. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by FedeC87p** [comment]
Thank you for the review, I will immediately rectify the Smart Contact so that I can begin developing Milestone 2.

**Comment by RouvenP** [comment]
hi @FedeC87p we transferred the payment today - apologies for the delay

**Comment by FedeC87p** [comment]
No problem, thanks for the update

**Pull request merged**
