### PR TITLE
Native Bitcoin Vaults Milestone #2 Delivery

### PR DESCRIPTION
**Pull request by 3yekn**
# Milestone Delivery Checklist

This video provides an end-to-end demonstration: https://us02web.zoom.us/rec/play/5d8024FYk5NwGPVncmDQklHjJkN9rJQTHjMIJR5g6s2uRCNXn31uzZhye-gegg55QBAONFYoqxJmiuNK.Wv8GfHCImD9ePKPw

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/868

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the delay here. I just started to look into it. Could you potentially update some of the links, like [nbv-storage](https://github.com/hashed-io/hashed-substrate/tree/main/pallets/nbv-storage) or [tests](https://github.com/hashed-io/hashed-substrate/blob/main/pallets/nbv-storage/src/tests.rs)? They currently don’t work for me.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick update and sorry again for the delay here (Too many meetings). The delivery looks really good. I just have a couple of minor things:

- I had two failed tests, when I tried to run https://github.com/hashed-io/hashed-substrate/blob/main/pallets/bitcoin-vaults/src/tests.rs, see https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/native-bitcoin-vaults-milestone_2_Noc2.md 
-  The following repos don’t have a license file: https://github.com/hashed-io/hashed-network-portal-ui and https://github.com/hashed-io/nbv-client-api

**Review by Noc2 — APPROVED** [review]
Thanks for the super quick reply. I can confirm that everything works now and I’m happy to tell you that the milestone is approved. I will forward your invoice internally.

**Comment by Noc2** [comment]
@3yekn it looks like the address in the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/native-bitcoin-vaults.md) is different from the address on the invoice. Could you either update the invoice or the address in the contract? Thanks

**Comment by 3yekn** [comment]
@Noc2 ah, sorry, I just re-sent the invoice with the same address as the original grant. thx

**Comment by Noc2** [comment]
Thanks. I just forwarded the invoice internally.

**Pull request merged**
