### PR TITLE
ink! analyzer milestone 3 (#1615)

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1615 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @davidsemakula I am currently reviewing the external evaluation. In the meantime, can you update the [license file](https://github.com/ink-analyzer/ink-analyzer/blob/master/LICENSE-APACHE#L189) to include the copyright owner name and date? Thanks!

**Comment by davidsemakula** [comment]
@keeganquigley Thanks for the feedback.

> In the meantime, can you update the [license file](https://github.com/ink-analyzer/ink-analyzer/blob/master/LICENSE-APACHE#L189) to include the copyright owner name and date? Right now it is blank.

I've pushed an update to the[Apache license file](https://github.com/ink-analyzer/ink-analyzer/blob/master/LICENSE-APACHE#L189).

**Comment by keeganquigley** [comment]
Thanks @davidsemakula much appreciated. The external evaluation was accepted and I was able to reproduce most of the results, except for two tests with the translator in the `ink-lsp-server`:
```rust
test translator::from_lsp::tests::offset_works ... FAILED
test translator::to_lsp::tests::position_works ... FAILED
```
I tried running it on both macOS and Ubuntu 20.04, but for some reason it fails to translate to and from the lsp. Does this have to do with running an LSP client? I also have Visual Studio Code open. Is there something I need to do to initialize it?

**Comment by davidsemakula** [comment]
> Does this have to do with running an LSP client?
@keeganquigley Nope, the unit and integration test should be able to run without an LSP client.

I'm guessing it has something to do with [these characters](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/lsp-server/src/test_utils.rs#L32) I use to test translating positions/offsets between different encodings.
But I'm on Ubuntu 20.04 as well and can't reproduce the failing translator tests.

Can you please run `cargo test translator -p ink-lsp-server` and share all the output? 

Also LMK if these 2 unit tests also fail when using docker. Thanks!

**Comment by keeganquigley** [comment]
Thanks much @davidsemakula here is the full output:
```rust
   Compiling test-utils v0.1.0 (/Users/keeganquigley/ink-analyzer/crates/test-utils)
    Finished test [unoptimized + debuginfo] target(s) in 15.89s
     Running unittests src/lib.rs (target/debug/deps/ink_lsp_server-9e2f844225099299)

running 2 tests
test translator::from_lsp::tests::offset_works ... FAILED
test translator::to_lsp::tests::position_works ... FAILED

failures:

---- translator::from_lsp::tests::offset_works stdout ----
thread 'translator::from_lsp::tests::offset_works' panicked at 'assertion failed: `(left == right)`
  left: `Some(3)`,
 right: `Some(5)`', crates/lsp-server/src/translator/from_lsp.rs:84:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- translator::to_lsp::tests::position_works stdout ----
thread 'translator::to_lsp::tests::position_works' panicked at 'assertion failed: `(left == right)`
  left: `None`,
 right: `Some(Position { line: 1, character: 3 })`', crates/lsp-server/src/translator/to_lsp.rs:155:17


failures:
    translator::from_lsp::tests::offset_works
    translator::to_lsp::tests::position_works

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.00s

error: test failed, to rerun pass `-p ink-lsp-server --lib`
```

Yes unfortunately it does fail with the same error when I run `docker run -it ink-analyzer`

Thanks for looking into it.

**Comment by davidsemakula** [comment]
Thanks @keeganquigley

So it looks like a recent update to one of the `ink-lsp-server` dependencies from the `rust-analyzer` project was the cause of the issue.

I was only able to reproduce the issue after running `cargo update`. This explains why this initially didn't affect me and @dastansam as our lock files already had the previous version.

I've locked the dependency's version, and since `ink-lsp-server` is a binary crate,  I've also [committed and pushed `Cargo.lock` to make building from source and tests for it deterministic](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) (I should have done this already 🙈 ).

Pulling the latest update from master should fix the 2 failing tests for the translator module. Thanks!

**Comment by keeganquigley** [comment]
Nice, thanks @davidsemakula that worked! I appreciate the quick fix. I'm happy to pass the milestone and I will forward your invoice for payment.

**Comment by davidsemakula** [comment]
Awesome! Thanks for the swift reviews @keeganquigley and @dastansam 🙂

**Pull request merged**
