### PR TITLE
Polkadot.js Desktop App - Milestone 1

### PR DESCRIPTION
**Pull request by krzysztof-jelski**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @krzysztof-jelski  Thanks for the delivery and we will try to look into it as soon as possible.

**Comment by Noc2** [comment]
It looks pretty good so far. Could you add some information to the readme (or another file) https://github.com/polkadot-js/apps/tree/master/packages/apps-electron on how to run and test the app? Or did Jaco not want to include this? 
fyi: The electron app currently doesn’t have an icon in the ubuntu taskbar.

**Comment by krzysztof-jelski** [comment]
@Noc2 Addressed, see [PR #3362](https://github.com/polkadot-js/apps/pull/3362) and [PR #3365](https://github.com/polkadot-js/apps/pull/3365).

**Comment by Noc2** [comment]
Thanks for fixing these small issues. It’s great to finally have a desktop app version of polkadot.js and I didn’t find any additional issues. So, I’m happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-desktop-app_1_Noc2.md) and I will forward your invoice internally.

**Comment by RouvenP** [comment]
hi @krzysztof-jelski we issued a test transaction. could you please confirm if received?

**Comment by krzysztof-jelski** [comment]
hi @RouvenP yes, we have received the test transaction.

**Pull request merged**
