### PR TITLE
Societal MVP Milestone 2

### PR DESCRIPTION
**Pull request by gfox1**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1249

### CODE REVIEW

**Comment by gfox1** [comment]
Hey @0xCaso, thanks looking at this so quick. I have updated the document to only include ` **Milestone Number:** 2`.

Cheers!

**Comment by 0xCaso** [comment]
I have another quick question: the second deliverable ("Substrate module: DAO Factory") was in the [first milestone](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/societal-milestone-1.md), as you written in the deliverable description. However, in the [application](https://github.com/w3f/Grants-Program/blob/master/applications/Societal.md) there is a delivery called "Substrate chain", which is not present in this delivery. Did you integrate it during the first milestone?

**Comment by gfox1** [comment]
Hi @0xCaso, yes we completed the Substrate Chain delivery during Milestone 1. In Milestone 1 we created the DAO factory pallets for the "Substrate Module: DAO Factory" submission, but also incorporated other pallets into our node at that time. So in the Milestone 1 submission, you have the full working Societal node, with all the pallets listed in the Milestone 2 Delivery "Substrate Chain". This is why I referenced the Milestone 1 submission for this, as all of those pallets were already incorporated into the node.

**Comment by 0xCaso** [comment]
Thanks a lot for the clarifications @gfox1!

**Comment by gfox1** [comment]
@0xCaso No problem!

**Comment by dsm-w3f** [comment]
@gfox1 thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grants-Program/blob/master/applications/Societal.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by gfox1** [comment]
Hi @dsm-w3f, thanks for getting to this so quickly!

We have completed all of the requirements from the notes, except for the article. I will write a medium article over the next few days, publish it and update you. However, I just wanted to let you know about the updates, so you could review the other items in the meantime. 

Her are the updates from your notes:

- Docker:
  We have updated the Milestone 2 submission [document](https://github.com/w3f/Grant-Milestone-Delivery/pull/665/commits/93ddade09a73f24e4131f320b4e0a3c1887c1e9b) and the [README](https://github.com/sctllabs/societal-grant-submission-2#run-in-docker) to include instructions on the command to run the image.

- Article:
  Article in progress that will explain what the software is and how to use it.

- Substrate Project (Milestone 1 Reviewed in Milestone 2)
   We have updated the repo and removed the warnings. No warning should be found while compiling. 

- Frontend (Milestone 2)
   Automated tests have been [included](https://github.com/sctllabs/societal-grant-submission-2/pull/2).


Please let us know if you have any other issues or questions.

**Comment by dsm-w3f** [comment]
@gfox1 thank you for the improvements and fixes. I reevaluated the milestone and updated the  [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal_2_dsm-w3f.md). We are mainly waiting for the article and there is a possible improvement which is creating a docker-compose file to spin up the backend and frontend together. Let me know when I can continue this evaluation.

**Comment by gfox1** [comment]
Hi @dsm-w3f, we have completed the medium article. Please find the link [here](https://medium.com/@societal.xyz/societals-web3-foundation-grant-e74d760c4f27). 

We have also added the Docker Compose script and added it to the [README](https://medium.com/@societal.xyz/societals-web3-foundation-grant-e74d760c4f27).

**Comment by dsm-w3f** [comment]
@gfox1 thank you for the improvements. The milestone delivery was approved. I'll forward your invoice internally and the payment should take place within two weeks (could happen before). Great work!

**Comment by gfox1** [comment]
@dsm-w3f Great to hear that it has been approved! Thanks for doing this so quickly.

**Comment by RouvenP** [comment]
hi @gfox1 we transferred the payment today.

**Comment by gfox1** [comment]
Hi @RouvenP, we have received the payment. Thanks so much! Have a good weekend.

**Pull request merged**
