### PR TITLE
Polkadot Protocol Conformance Tests RFP research grant

### PR DESCRIPTION
**Pull request by hgergov**
# Milestone Delivery Checklist
- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.

### <b>Note: The initial application contains an incorrect payment address. Please use the following accurate payment address: 0x050801be60d8535f433d5c15db3129276cc1cc6a (USDT on Ethereum Mainnet) </b>

- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @hgergov. Based on @bhargavbh's review, your milestone is hereby accepted. Congratulations!

**Comment by semuelle** [comment]
@hgergov, have you submitted an invoice yet?

**Comment by hgergov** [comment]
> @hgergov, have you submitted an invoice yet?

Hey @semuelle we just submitted the invoice — apologies for taking a while!

**Comment by semuelle** [comment]
Not a problem 😄

**Pull request merged**
