### PR TITLE
Polkadot Light Client Milestone #1

### PR DESCRIPTION
**Pull request by vbar**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/968

### CODE REVIEW

**Comment by FlorianFranzen** [comment]
> Link to the application pull request: [w3f/Grants-Program#579](https://github.com/w3f/Grants-Program/pull/579)

Should be w3f/Grants-Program#968

**Comment by vbar** [comment]
> > Link to the application pull request: [w3f/Grants-Program#579](https://github.com/w3f/Grants-Program/pull/579)
> 
> Should be [w3f/Grants-Program#968](https://github.com/w3f/Grants-Program/pull/968)

yes, fixed

**Comment by bhargavbh** [comment]
Apologise for the delay in evaluating. Please find my evaluations here: https://github.com/w3f/Grant-Milestone-Delivery/pull/603

Would be great if you could address the issues raised, thanks.

**Comment by bhargavbh** [comment]
Please find the evaluation for the revised delivery here: https://github.com/w3f/Grant-Milestone-Delivery/pull/625

**Overall remark:**
The concerns raised in previous evaluation have been by and large addressed. However, the delivery is more of an implementation roadmap than a Light Client Spec that can be integrated into [Polkadot Spec](https://spec.polkadot.network/). We have a few minor suggestions mentioned above, please include them. We have also taken into consideration the initial strides towards implementing a Light Client [here](https://github.com/eqlabs/polkadot-light-client-spec/). We suggest integrating it into your delivery and making necessary amendments (e.g removing claims of integration into Polkadot Spec) to the initial Grant proposal via a PR.

**Comment by bhargavbh** [comment]
LGTM. Approved from my side for merging the delivery.

**Review by Noc2 — APPROVED** [review]
Sorry for the delay here. I'm happy to confirm that the milestone is a pass and I will forward your invoice internally, see https://github.com/w3f/Grant-Milestone-Delivery/pull/645

**Comment by RouvenP** [comment]
hi @vbar we transferred the payment today.

**Pull request merged**
