### PR TITLE
SubRelay milestone 1 delivery

### PR DESCRIPTION
**Pull request by budtr**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1252

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @budtr , thanks for the delivery. Someone of the team will take care of it asap.

**Comment by dsm-w3f** [comment]
@budtr thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subrelay_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by budtr** [comment]
Hi @dsm-w3f, thank you for the evaluation.

We appreciate your feedback from the evaluation, and we have taken steps to implement the suggested changes, which are outlined below:

**1. Documentation**
We have added documentation to provide guidance on how to use the interface with screen record and a self-hosting guide. You can access this documentation at https://docs.subrelay.xyz/.
To improve the code's security, we have replaced the .env file with a template added to the code.

**2. Interface**
To ensure that the logs feature is working as intended, we have rechecked it and confirmed its functionality.
We recommend testing the logs feature with a more frequently triggered event, such as Balance.transfer.

**3. API**
We have resolved the vulnerabilities and setup issues identified. You can follow the instructions provided at https://docs.subrelay.xyz/self-hosting/quick-start to verify that the configuration is correct.

**4. Code Quality**
To enhance the code's quality, we have added a Github Action to check Eslint. You can review this at https://github.com/subrelay/interface/actions/workflows/eslint.yml.

Please spend sometime to re-evaluate and let me know if you have any questions or change requests.

**Comment by dsm-w3f** [comment]
@budtr thank you for the improvements and fixes. I'm having some problems to start the application only using the quick start guide. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subrelay_1_dsm-w3f.md) for details.

**Comment by budtr** [comment]
@dsm-w3f I apologize for the inconvenience. 
We have already tested the setup on team devices running MacOS and on an Ubuntu server, and it worked as expected. We assumed that the Docker configuration on your machine is different from ours. We have updated the Docker Compose file and made some changes to the [quick start guide](https://docs.subrelay.xyz/self-hosting/quick-start), adding more environment variables for the API configuration. Would you be able to try again on your device and let us the result?

**Comment by dsm-w3f** [comment]
@budtr I tried again but had the same results. I notice that the database in the container is without any table and there is no script in the quick guide to creating those tables. Can you please try the quick guide scripts from a clean environment? One that doesn't have a previously created database, code, or docker images/containers? I tried the scripts in two different machines without success.

**Comment by budtr** [comment]
@dsm-w3f The database tables will be generated automatically through migration scripts when the API services are executed. There is no need to create them in the database container or run any additional scripts. If the API service fails to start, the event service may not be able to access the database.

What operating system are you using for the setup? We haven't tested it on Windows or Windows WSL yet, but we are confident that it works perfectly on MacOs and Linux if you follow the setup guide properly.

By the way, we have made some changes that utilize the NestJs Cli to launch the application instead of building and executing the dist files. Could you please try again with the updated code?

**Comment by dsm-w3f** [comment]
@budtr I'll try again. I'm using Linux with an Ubuntu-based distribution.

**Comment by budtr** [comment]
@dsm-w3f Thank for your feedback.

We are investigating the problem now. The API should automatically execute the migration upon starting up.  Please see the logs bellow:

Screenshot 2023-02-24 at 09 55 02

I also spin up an Ubuntu server, install Docker and do exactly steps that listed in the [quick start guide](https://docs.subrelay.xyz/self-hosting/quick-start).  You can see the result bellow:

**The application start**
Screen Shot 2023-02-24 at 10 48 17

**The migration is completed**
Screen Shot 2023-02-24 at 10 48 59

**The application successfully started**
Screen Shot 2023-02-24 at 10 49 22

Could you remove the related docker containers, volumes, images, try again and provide us the logs? And if it continues to fail, could we obtain your real-time contact information? This would enable us to identify the issue more efficiently and expeditiously.

**Comment by dsm-w3f** [comment]
@budtr thank you for the answer. I tried again. First I removed all containers, images and volumes with `docker system prune -a --volumes`. After that, I tried again without success.

We can schedule a call if needed. Let's make this contact by email. 

These are the logs for the API container.

image

image

image

**Comment by budtr** [comment]
@dsm-w3f Thanks for letting us know about the issue. We're on it 👀

**Comment by budtr** [comment]
@dsm-w3f we changed the API configuration. Can you pull the latest code, delete docker images and volumes, and try again?

**Comment by dsm-w3f** [comment]
@budtr thank you for the answer. I tried again without success. My suggestion to conclude this evaluation is to add a comment or troubleshooting section in the quick start guide in order to handle this case. It seems that in some environments works and others don't. Adding an "if" in the quick start guide with the explanation on how to run the migrations manually in case of necessity would be enough to consider this evaluation as finished.

**Comment by budtr** [comment]
@dsm-w3f thank for your suggestion.
We added troubleshooting section for the issue. You can see it at https://docs.subrelay.xyz/self-hosting/quick-start#troubleshooting. Because of caching issue from GitBook, may be you need to view it in a incognito tab or clear browser cache to see the updated content.

**Comment by dsm-w3f** [comment]
@budtr thank you for adding the section. The milestone is approved. I'll forward the invoice internally and the payment should happen within two weeks. Great work!

**Comment by budtr** [comment]
@dsm-w3f Thank for evaluation, valuable feedback, and supports. We absolutely appreciate it. And if you think there's anything we could do to improve the product, feel free to drop me an email at [bumapdtr@gmail.com](mailto:bumapdtr@gmail.com). We're always looking for ways to make things better, so your input is much appreciated!

**Comment by fededubbi** [comment]
Hi @budtr, can you please add our complete VAT number to the invoice?

CHE-322.596.347.

Many thanks,
Regards,

Federica Dubbini

**Comment by budtr** [comment]
Hi @fededubbi,  
Sorry for my mistake. I've updated the invoice and submitted a new form with the corrected information. 
Could you please take a look and let me know if there are any further issues?
Thank you for your understanding.

**Comment by RouvenP** [comment]
hi @budtr we transferred the payment today.

**Pull request merged**
