### PR TITLE
wasm runtime fuzzing - milestone 2 delivery

### PR DESCRIPTION
**Pull request by pventuzelo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. I will try to look into it as soon as possible.

**Comment by Noc2** [comment]
Hi. I’m currently looking into your delivery. What’s the reason for the lightbeam/wasmtime errors [here]( https://github.com/pventuzelo/wasm_runtimes_fuzzing/blob/master/docs/WARF_SUBCOMMANDS.md#execute-one-wasm-module-throw-all-targets-execute-all). I'm getting the same output.

**Comment by pventuzelo** [comment]
Hi @Noc2, lightbeam is still under development and integration inside wasmtime is still experimental. It will maybe make sense to deactivate it temporarily since errors and crashes are frequent on this one. Some existing bugs I've reported on lightbeam in the past are still open for the moment [here](https://github.com/bytecodealliance/wasmtime/issues?q=is%3Aissue+author%3Apventuzelo+lightbeam+is%3Aopen)

**Comment by pventuzelo** [comment]
I just verify and lightbeam return an error because some webassembly features are not implemented.
I will deactivate it for now.

**Comment by pventuzelo** [comment]
Hey @Noc2, have you got any issue with `warf` during your testing?

**Comment by Noc2** [comment]
Sorry for the late reply. I took another look at your delivery and I’m now happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/wasm-runtimes-fuzzing_2_Noc2.md) and will forward your invoice internally.

**Comment by pventuzelo** [comment]
Awesome thanks @Noc2 for the evaluation :)

**Comment by RouvenP** [comment]
Hi @pventuzelo we issued a test transfer. Could you confirm if received?

**Comment by pventuzelo** [comment]
Hi @RouvenP, I confirm (received 0,0100 BTC)

**Pull request merged**
