### PR TITLE
PolkaMask: Polkadot with Metamask, milestone 1

### PR DESCRIPTION
**Pull request by Nick-1979**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2058

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @Nick-1979 and thanks for the great delivery! You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkamask_1_keeganquigley.md). Happy to pass it and glad to see this completed. It's very nice to have this functionality for Polkadot!

**Comment by RouvenP** [comment]
hi @Nick-1979 we sent the payment today

**Comment by Nick-1979** [comment]
@RouvenP 

Unfortunately, I haven't received anything. Could you please share the link to the transaction? Thank you.

**Comment by RouvenP** [comment]
hi @Nick-1979 apologies, seems something went wrong. Could you check again?

**Comment by Nick-1979** [comment]
@RouvenP Great, All good. Thank you.

**Pull request merged**
