### PR TITLE
Hybrid milestone 3 evaluation

### PR DESCRIPTION
**Pull request by Ali-Usama**
# External Evaluation

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1582

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the evaluation @Ali-Usama a couple questions:

- Is [Polkadot Indexer](https://github.com/hybrid-explorer/polkadot-indexer/tree/main) working for you now? If so can you update the delivery table in your eval accordingly?
- Were you able to use the UI to see the indexers in action? I am currently having trouble getting the front-end to work with pnpm. 
- Were you able to get through the manual testing in [Deliverable 3](https://github.com/hybrid-explorer/hybrid-indexer/blob/main/doc/testing-guide.md#deliverable-3---chain-select)?

**Comment by keeganquigley** [comment]
**UPDATE:** I was able to get the front end working and see the indexing in action. Let me know can address the above for me to merge the eval. Thanks!

**Comment by Ali-Usama** [comment]
> * Is [Polkadot Indexer](https://github.com/hybrid-explorer/polkadot-indexer/tree/main) working for you now? If so can you update the delivery table in your eval accordingly?
> * Were you able to get through the manual testing list in [Deliverable 3](https://github.com/hybrid-explorer/hybrid-indexer/blob/main/doc/testing-guide.md#deliverable-3---chain-select)?

Yes, @keeganquigley It's working fine for me after they fixed the docker build errors. I had already updated my evaluation when it was fixed. However, I recently removed the error message I was getting before and replaced it with the working output. Please let me know if there's anything else on my side.

**Comment by keeganquigley** [comment]
Thanks @Ali-Usama I was referring to the table in 0d. which states that "images are running and building successfully except `polkadot-indexer`".

**Comment by Ali-Usama** [comment]
> Thanks @Ali-Usama I was referring to the table in 0d. which states that "images are running and building successfully except `polkadot-indexer`".

Thank you for pointing it out @keeganquigley . I've updated the evaluation

**Comment by keeganquigley** [comment]
Awesome thanks @Ali-Usama much appreciated. Thanks for your efforts, I will merge the application now and forward your payment.

**Pull request merged**
