### PR TITLE
SaaS3_Milestone_2

### PR DESCRIPTION
**Pull request by SaaS3Lab**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1339.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @SaaS3Lab, an evaluator will take a look shortly.

**Comment by dsm-w3f** [comment]
@SaaS3Lab thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue the evaluation.

**Comment by songtianyi** [comment]
> During the execution of the installation steps I had one doubt. Is the [Prepare parachain node](https://github.com/SaaS3-Foundation/saas3-dao#prepare-parachain-node) step needed since the para-2000-genesis-state and para-2000-wasm files are in the repository?

**Yes, they are in the repo root directory.**

> In [Register with the local relay chain](https://github.com/SaaS3-Foundation/saas3-dao#register-with-the-local-relay-chain) and in the Prepare parachain node needs to specify that the user needs to access the substrate with port 9977 to do the configuration.

**Access the relay chain with port 9944 to do the configuration should be ok for all.**

> The testing guide needs to have examples of inputs and expected outputs. The frontend also needs a testing guide.

**We added some input examples in Tutorial, please check**
Check [this](https://github.com/SaaS3-Foundation/SaaS3-DAO-Pallets/blob/main/docs/Testing%20guide.md) for frontend testing guide.

> Automated Test
> I ran cargo test. All tests passed but returned some warnings.

**FIXED** Please check again

> I ran cargo tarpaulin to check the coverage of the tests in the pallets. The coverage can be improved.

**The pallet test coverage are 90%+ now**

> Manual testing
> Despite the testing guide doesn't have examples of inputs and expected outputs, I tried to check the pallets and the frontend.
> I couldn't figure out what to put in the category_type of Treasury.receive. So I have done the donations using the frontend and could check the transfer to the Treasury in the substrate. I could submit a lawsuit and vote using the frontend and the substrate, but when I tried to process the lawsuit, in the frontend, nothing occurred. In the substrate, I received a BadOrigin message. So I couldn't try to claim the rewards.

`category_type` is used for categorizing the donation. For testing, any non-zero u32 value can be used.

For now, only the root user can process a lawsuit. In the future, this functionality will be available to all jury members.
Please recheck the tutorial.


> Code Quality

We have fixed the winnings in the pallet court and pallet treasury. Actually, we cloned the parachain template from [this repo](https://github.com/substrate-developer-hub/substrate-parachain-template), and most of the warnings come from the original repo.

Yarn lint warnings are fixing

**Comment by songtianyi** [comment]
@dsm-w3f When the warnings are fixed, we will let you know.

**Comment by songtianyi** [comment]
@dsm-w3f yarn lint warnings are fixed

**Comment by dsm-w3f** [comment]
@SaaS3Lab and @songtianyi thank you for the improvements and fixes. I tried again and some parts were improved. I'm having problems with the part that needs a root user for the testing. Could you assist with that? See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md). Let me know when I can continue this evaluation.

**Comment by songtianyi** [comment]
> @SaaS3Lab and @songtianyi thank you for the improvements and fixes. I tried again and some parts were improved. I'm having problems with the part that needs a root user for the testing. Could you assist with that? See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md). Let me know when I can continue this evaluation.

You could try it with your own created account, if some error happens, let me know.

**Comment by songtianyi** [comment]
> @songtianyi I tried again but seems that [the parachain provided](https://github.com/SaaS3-Foundation/saas3-dao/tree/main/chainspecs) there is no sudo pallet nor a root user specified in the chainspec. I tried to create one based on your plain chainspec but didn't work as well. In the relaychain there is sudo pallet and root user but not in the parachain where we need to make the calls. I suggest taking a look at these links ([origins](https://docs.substrate.io/build/origins/), [sudo pallet](https://github.com/paritytech/substrate/tree/master/frame/sudo), [chainspec](https://docs.substrate.io/build/chain-spec/)) where I got the information about root users and try to add sudo pallet and generate a parachain with a root user to test the application integrated with polkadot.js. Without that I (and possible users) can't make the privileged calls for some extrinsics using plokadot.js. Let me know when this is available to continue this evaluation.

I have changed the permission; please try it again. So sorry for the trouble.

**Comment by dsm-w3f** [comment]
@songtianyi thank you for the answer and fixes. I tried again using polkadot.js to interact with the pallet and didn't work. I tried it in the unit tests are working. Did you try with polkadot.js? Maybe I'm missing something. I just to know if it is working for you and if any further step is needed to complete these tests. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md).

**Comment by songtianyi** [comment]
> @songtianyi thank you for the answer and fixes. I tried again using polkadot.js to interact with the pallet and didn't work. I tried it in the unit tests are working. Did you try with polkadot.js? Maybe I'm missing something. Just to know if it is working for you and if any further step is needed to complete these tests. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md).

Did you try it with our frontend web page?

**Comment by dsm-w3f** [comment]
@songtianyi I tried and didn't work. I tried again and added some prints to the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md). I think would be nice if you produce a demo video showing the installation process and also the usage of the software. In this way, I can check if there is some step missing and try to reproduce your results.

**Comment by songtianyi** [comment]
> @songtianyi I tried and didn't work. I tried again and added some prints to the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md). I think would be nice if you produce a demo video showing the installation process and also the usage of the software. In this way, I can check if there is some step missing and try to reproduce your results.

OK

**Comment by songtianyi** [comment]
@dsm-w3f 
Hi, I have fixed the `bad origin` problem.
Please update the code source, the chain spec files, the genesis state file, and the wasm file both updated.
Then try it again. I have added some images for demonstration; you can check them in `Tutorial.md` file

**Comment by dsm-w3f** [comment]
@songtianyi Thanks for the improvements and fixes. Now I was able to check the functions that failed before, they worked. However, now the automated tests are not passing and I was not able to remove a Sue (removeSue). I don't know if this is in the scope of the grant, but at least the automated tests need to pass. See details in the e[valuation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saas3_2_dsm-w3f.md). Let me know when I can continue this evaluation. PS: Next week I'll be out-of-office, so maybe someone take over this evaluation or hope to hear from me after the next week.

**Comment by songtianyi** [comment]
@dsm-w3f  The tests are fixed.

**Comment by fededubbi** [comment]
Hi @songtianyi,

I noticed that on the invoice you report an amount in USDT, but the payment address is in USDC.
Can you please update one of these two accordingly?

Many thanks,
Federica

**Comment by dsm-w3f** [comment]
@SaaS3Lab thanks for updating the invoice. I notice that the payment address is different from the one reported in the grant application. Could you please either update the application by sending an amendment or submit a new invoice with the same payment address from the application?

**Comment by fededubbi** [comment]
Hi @SaaS3Lab,

We noticed that your supplier name is strange.
Can you please only put 'SaaS3'? 

Many thanks,
Federica

**Comment by meldien** [comment]
@SaaS3Lab Hi everyone, could you please update the USDC to USDT, also the amount should be 5000 USDT instant of 5000 USDC. Many thanks for your support.

**Comment by meldien** [comment]
@SaaS3Lab Apologies my explanation was not clear. 
If the goal would be to pay you in USDC then the invoice is fine, so far your address is correct. 
If we have to pay in USDT (Statemint) please update the invoice. The last payment for the Milestone 1 was done in USDT. 
Properly that's the reason for my confusion.

**Comment by fededubbi** [comment]
Hi @SaaS3Lab,

We can't pay in USDC on Polkadot, is it okay for you if we pay in USDT?

Many thanks,
Federica

**Comment by meldien** [comment]
@SaaS3Lab Many thanks for your conformation. 
Could you please update your send invoice?
I have to make sure, the payout is matching with the added information on the invoice. 

Many thanks, Melanie

**Comment by meldien** [comment]
@SaaS3Lab apologies the payout delay. I didn't share the updated invoice in time. 
The payout will be done lastet tomorrow. Stay you updated when it's done

**Comment by meldien** [comment]
@SaaS3Lab transfer done

**Pull request merged**
