### PR TITLE
Add ZK-Snarks_with_Substrate_tutorial-Milestone2

### PR DESCRIPTION
**Pull request by bufta**
Milestone 2 delivery submission

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1446 & https://github.com/w3f/Grants-Program/pull/1290

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @bufta, thanks for the delivery, someone of our team will take care of it soon.

In the meantime, I opened a PR to fix some minor formatting issues in the application document, so the checks will pass.

**Comment by bufta** [comment]
Thank you @dsm-w3f for the feedback. We applied your remarks and the updated version is ready for further review in our repository.

**Comment by dsm-w3f** [comment]
@bufta thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zk-snarks-tutorial_2_dsm-w3f.md) and the only part that is still pending is checking the concepts involved in the tutorial. This part will be handled by another evaluator which has more knowledge in zp-proof.

**Comment by bufta** [comment]
Hi @dsm-w3f @mmagician, hope all is well. I would just like to check in to ask about the status of our milestone approval - is there anything that we could do or provide to support the evaluation process?

**Comment by dsm-w3f** [comment]
@bufta my apologies for the delay in the evaluation. We need one more week to complete this evaluation. This is because of the availability of the technical specialist who is not fully dedicated to evaluation tasks.

**Comment by dsm-w3f** [comment]
@bufta my apologies for the delay. The milestone is accepted. I'll forward the invoice and the payment should take place within two weeks. Great work!

**Comment by RouvenP** [comment]
hi @bufta we transferred the payment today.

**Pull request merged**
