### PR TITLE
DEIP - Milestone 2 delivery

### PR DESCRIPTION
**Pull request by aliakseikulik**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request:  https://github.com/w3f/Open-Grants-Program/pull/130 (amendment PR https://github.com/w3f/Grants-Program/pull/689).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I started to look into your delivery, see [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DEIP_2_Noc2.md). Could you take a look at it and let me know if you have any questions? The snyk test is just for your information and nothing you need to fix for the acceptance of the grant.

**Comment by aliakseikulik** [comment]
Hi @Noc2. Thank you for your feedback. I have updated delivery with a link to the article we've published, and we will take a look at your comments and work towards fixing delivery asap.

**Comment by Noc2** [comment]
Thanks. I’m currently ooo (sick) anyway, so take your time ;-)

**Comment by aliakseikulik** [comment]
@Noc2 Hi. Could you please provide a `make start` full log so we can investigate why the database is not starting up and sign up is failing for you? Thank you

**Comment by alxs** [comment]
@aliakseikulik checking in here, any updates?

**Comment by aliakseikulik** [comment]
> @aliakseikulik checking in here, any updates?
Hi @alxs. I am adding our CTO @egortsaryk9 to the conversation so he can quickly address any issues and technical questions.

**Comment by Noc2** [comment]
Just to double check: Are you still working on this? What is the current status?

**Comment by Noc2** [comment]
I’m closing this PR due to inactivity. Let me know if I should reopen it. Also, it would be appreciated if you could give us a status update on the grant and if you still plan to deliver it.

**Pull request closed without merging**
