### PR TITLE
Perun Integration: Milestone delivery 1-5

### PR DESCRIPTION
**Pull request by matthiasgeihs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/589, amended by https://github.com/w3f/Grants-Program/pull/692

### CODE REVIEW

**Comment by matthiasgeihs** [comment]
Please note that we developed the milestones concurrently, as they have dependencies on each other and changes in one milestone may propagate to another. This is also why I submitted the milestones together, as I thought it might give a more coherent basis for reviewing. If you prefer that we split the delivery into one PR per milestone, please let us know and we will do that.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Hi. Sorry for the late reply here. Everything looks really good so far. I only have two questions/comments: Which rust version should I use for compiling cargo test, here: https://github.com/perun-network/perun-polkadot-pallet. And for the backend, only one minor thing, it requires a go version above go1.16, since embedded files were added in go1.16. Maybe you can add this to the readme.

**Comment by matthiasgeihs** [comment]
Hi @Noc2!

- The Pallet tests require Rust version 1.52.0. We added a remark to the Pallet README (https://github.com/perun-network/perun-polkadot-pallet/pull/15).

- We also added a remark regarding the Go version to the Backend README (https://github.com/perun-network/perun-polkadot-backend/pull/9).

**Comment by Noc2** [comment]
Thanks for the quick reply. I’m happy to confirm that the milestones are a pass and I will forward your invoices internally.

**Comment by RouvenP** [comment]
hi @matthiasgeihs we sent a test transaction of 10 DAI. Can you confirm if received?

**Comment by matthiasgeihs** [comment]
> hi @matthiasgeihs we sent a test transaction of 10 DAI. Can you confirm if received?

Yes, we can confirm.

**Comment by RouvenP** [comment]
@matthiasgeihs thanks for confirming, we transferred the remainder.

**Pull request merged**
