### PR TITLE
assethub indexer m1 evaluation

### PR DESCRIPTION
**Pull request by PieWol**

### CODE REVIEW

**Comment by vikiival** [comment]
Hello @PieWol,

I have added 300 LOC of inline documentation describing each handler + utility functions

https://github.com/kodadot/stick/pull/222

**Comment by PieWol** [comment]
Hey @vikiival thanks for your comments and the documentation update. I'll check it on monday 👍

**Comment by PieWol** [comment]
Hi @vikiival ,
good job on updating the documentation 👍.
Also thanks for clarifying the questions I had. 

The only thing I still don't get even after reading your comment regarding the testing aswell as the updated readme is unit testing. In the `/tests` folder I see about 3 unit tests but with all the functionality you provide and all the events you process I would expect a lot more. Also ``npm run test`` didn't work for me in the main folder of the repo. I'm not that familiar with node projects so I appreciate your help on that matter.

**Comment by vikiival** [comment]
> all the events you process I would expect a lot more

As stated in the README 

https://github.com/kodadot/stick/blob/78f61d32f089f4906409152dd6002184ccc4b0f5/README.md?plain=1#L114

@subsquid does not offer a way to test the handlers, therefore I unit tested the things where bug can appear (e.g our code)

+ the packages that are used by indexer are already covered by unit test
- https://github.com/kodadot/packages/tree/main/hyperdata/tests
- https://github.com/kodadot/packages/tree/main/minipfs/test

> Also npm run test didn't work for me in the main folder of the repo.

https://pastebin.com/AGWWLSZj

**Comment by PieWol** [comment]
Well, I didn't checkout the correct branch 😬, works though!

**Review by semuelle — APPROVED** [review]
Thanks, Piet. Confirmed.

**Pull request merged**
