### PR TITLE
add parachain-pos-template-milestone_1.md

### PR DESCRIPTION
**Pull request by octavei**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1370 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by randombishop** [comment]
Hi @octavei ! Thank you for this delivery. I'll start working on the evaluation and will get back to you with feedback in next couple of days...

**Comment by octavei** [comment]
> Oups, please ignore previous message, haven't seen that @semuelle was already on it...

Thank you for your reply!  We have done a lot of basic work on this template and hope that more community developers will use it together. We have developed aband-network based on this template
, Every time the aband-network is upgraded in the future, this template will be upgraded first. We believe that it will greatly save every developer's time, and they don't need to do repetitive work if they want to use Substrate's native staking in their network.

**Comment by semuelle** [comment]
Hi @octavei. As @randombishop noted, I am currently reviewing your milestone. 

Could you add instructions to the test doc how to run from the Dockerfile? I am currently getting ``Invalid input: `rococo-local` only supported with `rococo-native` feature enabled.`` when trying to start the container built from the Dockerfile.

**Comment by octavei** [comment]
> Hi @octavei. As @randombishop noted, I am currently reviewing your milestone.
> 
> Could you add instructions to the test doc how to run from the Dockerfile? I am currently getting `` Invalid input: `rococo-local` only supported with `rococo-native` feature enabled. `` when trying to start the container built from the Dockerfile.


This docker is provided for the main network of the parachain. If you want to run it, you can add the command `-- --chain kusama` to the docker, but it will not generate any blocks. Of course, if it is necessary to use docker in the test network, I will provide it as soon as possible. However, for the convenience of testing, I do not recommend using docker to start the testnet.

**Comment by semuelle** [comment]
Hi @octavei. Thanks for the updates. I had a closer look at the `polkadot-launch` config and realized that it launches a relay and parachain, which is basically all we are looking for. We usually ask for a Dockerfile/image as it is useful in many cases for us and others for quick testing, but sometimes other tools are more useful or make more sense. 

Your milestone is hereby accepted. Congratulations. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/parachain-PoS-template_1_semuelle.md). 

Your PR states that you filled out the invoice form, but I cannot find an invoice for this project in our records. Are you sure you submitted it?

**Comment by octavei** [comment]
> Hi @octavei. Thanks for the updates. I had a closer look at the `polkadot-launch` config and realized that it launches a relay and parachain, which is basically all we are looking for. We usually ask for a Dockerfile/image as it is useful in many cases for us and others for quick testing, but sometimes other tools are more useful or make more sense.
> 
> Your milestone is hereby accepted. Congratulations. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/parachain-PoS-template_1_semuelle.md).
> 
> Your PR states that you filled out the invoice form, but I cannot find an invoice for this project in our records. Are you sure you submitted it?


We will build Aband-Network, the largest social network in the Polkadot community. We have fully considered and prepared for this matter, and we really need your support.

**Comment by octavei** [comment]
> Hi @octavei. Thanks for the updates. I had a closer look at the `polkadot-launch` config and realized that it launches a relay and parachain, which is basically all we are looking for. We usually ask for a Dockerfile/image as it is useful in many cases for us and others for quick testing, but sometimes other tools are more useful or make more sense.
> 
> Your milestone is hereby accepted. Congratulations. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/parachain-PoS-template_1_semuelle.md).
> 
> Your PR states that you filled out the invoice form, but I cannot find an invoice for this project in our records. Are you sure you submitted it?

Thank you very much, I did forget to submit it, I will make it up as soon as possible.

**Comment by octavei** [comment]
> > Hi @octavei. Thanks for the updates. I had a closer look at the `polkadot-launch` config and realized that it launches a relay and parachain, which is basically all we are looking for. We usually ask for a Dockerfile/image as it is useful in many cases for us and others for quick testing, but sometimes other tools are more useful or make more sense.
> > Your milestone is hereby accepted. Congratulations. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/parachain-PoS-template_1_semuelle.md).
> > Your PR states that you filled out the invoice form, but I cannot find an invoice for this project in our records. Are you sure you submitted it?
> 
> Thank you very much, I did forget to submit it, I will make it up as soon as possible.

I have submitted a docker tutorial [https://github.com/Aband-Network/substrate-parachain-PoS-template/blob/main/docs/build-docker.md](https://github.com/Aband-Network/substrate-parachain-PoS-template/blob/main/docs/build-docker.md)to teach developers how to quickly spin up their testnet

**Comment by octavei** [comment]
> Hi @octavei. Thanks for the updates. I had a closer look at the `polkadot-launch` config and realized that it launches a relay and parachain, which is basically all we are looking for. We usually ask for a Dockerfile/image as it is useful in many cases for us and others for quick testing, but sometimes other tools are more useful or make more sense.
> 
> Your milestone is hereby accepted. Congratulations. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/parachain-PoS-template_1_semuelle.md).
> 
> Your PR states that you filled out the invoice form, but I cannot find an invoice for this project in our records. Are you sure you submitted it?

Thanks many!

**Comment by octavei** [comment]
@semuelle I have submitted the invioce. If you have any questions, you counld let me know here. Thanks again!

**Comment by octavei** [comment]
> @semuelle I have submitted the invioce. If you have any questions, you counld let me know here. Thanks again!

Here, I am very grateful to the [daos team](https://github.com/daos-org/daos) for their recommendation.

**Comment by octavei** [comment]
Hello, boys @randombishop  @semuelle  @juntao @splix .  I have sent you an invoice, but I don't know if you have received it?

**Comment by semuelle** [comment]
Hi @octavei. Sorry I didn't follow up. Yes, we have received your invoice. I have forwarded it to our finances team. If you don't hear back from them in the next two weeks, let us know here.

**Comment by octavei** [comment]
> Hi @octavei. Sorry I didn't follow up. Yes, we have received your invoice. I have forwarded it to our finances team. If you don't hear back from them in the next two weeks, let us know here.

Sorry to bother you @semuelle , the invoice has been sent out for almost a week now. It would be great if we could get funding this week.

**Comment by semuelle** [comment]
Hi @octavei. As stated in the [README](https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process), invoices are usually processed within 14 days. I can check with the finances team that this happens, but I'm afraid there is not much more I can do in that regard.

**Comment by RouvenP** [comment]
hi @octavei we transferred the payment today.

**Comment by octavei** [comment]
> > hi @octavei we transferred the payment today.
> 
> Greate work ! @octavei @RouvenP @semuelle , I recommended this grant project to @octavei . And heard that there is a referral reward of 500 US dollars. How can I get it?

I think the referral bonus of $500 should not be included in this $4000, right? @RouvenP @semuelle

**Comment by semuelle** [comment]
Thanks for the reminder. No, @octavei, the USD500 are not out of the granted amount, they are paid separately. 

@JimYam, [as per our website](https://w3f.github.io/Grants-Program/referral-program), USDT is paid on Polkadot or Kusama, so we would need an address for one of them. Alternatively, we could pay USDC or DAI on Ethereum. Sorry this wasn't picked up at the time of the application.

**Comment by JimYam** [comment]
Can be paid with USDC, this is my address `0x08A7876db92b07057E12fAF29AA3CCF33b5aAe3D`. @RouvenP  @semuelle . Thanks!

**Comment by semuelle** [comment]
@JimYam Since you already provided an Ethereum address in the original application, it'd be easier if we used that one. Otherwise, we'd have to modify the application. Would that be ok with you?

**Comment by JimYam** [comment]
[https://github.com/w3f/Grants-Program/blob/master/applications/daos.md](https://github.com/w3f/Grants-Program/blob/master/applications/daos.md) @semuelle @randombishop @RouvenP

**Comment by semuelle** [comment]
@JimYam I have requested USDC 500 to be paid to the address in the original grant application. Let me know if you haven't received two weeks from now.

**Comment by JimYam** [comment]
> @JimYam I have requested USDC 500 to be paid to the address in the original grant application. Let me know if you haven't received two weeks from now.

Thx

**Pull request merged**
