### PR TITLE
Milestone delivery for `create-substrate-app`

### PR DESCRIPTION
**Pull request by philoniare**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2227

### CODE REVIEW

**Comment by PieWol** [comment]
hey @philoniare ,
thanks for submitting this milestone.

I have a few questions.
1. Where is your testing guide?
2. Please update the table of deliveries so that the links not only point at the main repo but at the exact deliverable.
3. Have you made sure that tests for all app possibilities are passing? What about build errors? `npm run build` in the Vue example leads to errors.
4. The angular example is not working on my machine.
5. Following your application I expected you to port this existing [frontend-template](https://substrate-developer-hub.github.io/substrate-front-end-template/?rpc=wss://rpc.polkadot.io) to angular and vue so that the developer can start with a good amount of showcase components. You right now submitted the generic framework template with just a single "connect wallet" button. Thats not acceptable.

Looking forward to your answers and updates.

**Comment by philoniare** [comment]
hey @PieWol,

Thanks for the review. Here's my response:
1. Each project has the `npm test` command available and this has been included in the available scripts section in the documentation: https://www.create-substrate-app.dev/docs/available-scripts
2. Yep, they should already be that way though, but I've updated the test and license section. 
3. Yep, here's the detailed analysis on the message, mostly warning from dependencies that I can't do anything about:
- `angular` - warning due to the `polkadot.js` dependency:
```sh
▲ [WARNING] Module 'bn.js' used by 'node_modules/@polkadot/util/bn/bn.js' is not ESM

  CommonJS or AMD dependencies can cause optimization bailouts.
  For more information see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
- `react` - also another warning due to the `polkadot.js` dependency:
```sh
Creating an optimized production build...
One of your dependencies, babel-preset-react-app, is importing the
"@babel/plugin-proposal-private-property-in-object" package without
declaring it in its dependencies. This is currently working because
"@babel/plugin-proposal-private-property-in-object" is already in your
node_modules folder for unrelated reasons, but it may break at any time.

babel-preset-react-app is part of the create-react-app project, which
is not maintianed anymore. It is thus unlikely that this bug will
ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
your devDependencies to work around this error. This will make this message
go away.
  
Compiled successfully.
```
- `vue` - there was an import lint error and I've fixed it in this release. 

4. Maybe something was cached when I did `npm link` locally. I was able to repro the issue with angular on a different computer. I've released a new version, should be working for you now.
5. The application mentioned that it exists and we'll be making use of it and we did make use of the main providers, context and hooks, but the main point of `create-substrate-app` is to make a generic template that's usable by anyone. Most DApp developers that interact with the blockchain mainly need to read the balance and sign extrinsics on the DApp. I think including how to make a transaction would be useful, but everyone using this template would have to manually remove all of the components related to metadata, block and runtime. Just like the original simple `create-react-app`, the template should not be filled with unrelated code that needs to be removed.

**Comment by PieWol** [comment]
This is the error I'm referencing for 3.

```
Creating a new Substrate app in /create-substrate-app/ang_app
node:fs:2352
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, open '/create-substrate-app/ang_app/src/environments/environment.ts'
    at Object.writeFileSync (node:fs:2352:20)
    at /create-substrate-app/index.js:110:12
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/create-substrate-app/ang_app/src/environments/environment.ts'
}

Node.js v20.11.1
```

**Comment by philoniare** [comment]
@PieWol yep, this has been fixed. You can try running the `npx create-substrate-app my-ng` and choosing angular again? This should call the version 1.0.2 that has the above fixed

**Comment by philoniare** [comment]
@PieWol I've just released another version of the library (`1.0.3`) with the following updates:
- some simple visual improvements
- it contains logic and UI to allow the user to make a transfer. Since to make a transfer, we're just calling the `balances` pallet, the DApp developer should be able to modify it to call any signed pallet extrinsic on the specified chain. 

Let me know what else is needed from my side

**Comment by PieWol** [comment]
@philoniare thank you for the update. I will have your evaluation finished tomorrow.

**Comment by philoniare** [comment]
@PieWol thank you for your time. I've also published another iteration:
- Updated all of the substrate service files on templates with jsdocs for better readability
- I've also added screenshots so that it's easier for devs to understand what they're getting with the library. Added a small FAQ section as well to allow for customizing the chain endpoint.

Definitely open to feedback to make it a useful tool for DApp devs.

**Comment by PieWol** [comment]
Hey @philoniare ,
thanks for the latest updates. I have published my current [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1149). Please don't be surprised about most things not yet accepted. It looks like only minor changes and some cleanup are necessary at this point. :) 
Looking forward to hearing from you.

**Comment by philoniare** [comment]
@PieWol thanks, will be sure to update soon

**Comment by philoniare** [comment]
@PieWol appreciate the thorough evaluation, all of the comments on the evaluation have been addressed. Here's a brief overview:
- Added the `License.md` file on the repo and PR
- All of the tests and builds should be working without any issues now
- Updated vue README with correct run command
- Ability to select from multiple accounts has been added with a selector. Balance updates automatically on an account change and transfer is configured to initiate from the selected account. Also, updated the screenshots here that you can check out: http://github.com/philoniare/create-substrate-app/
- The logo/network representation changes based on the specified chain

**Comment by PieWol** [comment]
awesome @philoniare 👍 ,
I'll get back to you on monday.

**Comment by philoniare** [comment]
> awesome @philoniare 👍 ,
> 
> I'll get back to you on monday.

Thanks, have a nice weekend

**Comment by PieWol** [comment]
Hey @philoniare, 
awesome changes 👍. Thanks!
May I suggest one final change? It's about the addresses always having the same representation (prefix 42 to be precise) and don't change in relation to which network the dApp is created for. 

I think it would be good if you would introduce a change that shows the addresses connected in the format that the chain actually uses. Otherwise users will probably be confused about addresses. Check this [address transformation tool](https://polkadot.subscan.io/tools/format_transform?input=5DoTwNSWNE9GHTvf2f3mdj5LfmTcUaVtV33XxbeedsqAS7br&type=All) to see what I'm talking about. Let me know what you think. 

I will update my evaluation afterwards and have the milestone accepted 🎉

**Comment by philoniare** [comment]
> Hey @philoniare, awesome changes 👍. Thanks! May I suggest one final change? It's about the addresses always having the same representation (prefix 42 to be precise) and don't change in relation to which network the dApp is created for.
> 
> I think it would be good if you would introduce a change that shows the addresses connected in the format that the chain actually uses. Otherwise users will probably be confused about addresses. Check this [address transformation tool](https://polkadot.subscan.io/tools/format_transform?input=5DoTwNSWNE9GHTvf2f3mdj5LfmTcUaVtV33XxbeedsqAS7br&type=All) to see what I'm talking about. Let me know what you think.
> 
> I will update my evaluation afterwards and have the milestone accepted 🎉

Yep, of course. Ah thanks for the suggestion, definitely make sense to have this. Will let you know once I've added it, thanks

**Comment by philoniare** [comment]
@PieWol I've added the https://www.npmjs.com/package/@polkadot/util-crypto library as a dependency to format the addresses on all front-end templates based on the specific prefix that each chain uses. I've published a new version, so the cli tool should be updated. Looking forward to hearing back from you.

**Comment by PieWol** [comment]
awesome, thank you @philoniare!
I have updated my evaluation and once a team member has reviewed and merged it, the milestone will be accepted 🎉 .

**Comment by philoniare** [comment]
@PieWol Thank you very much for all of the recommendations and suggestions to improve the project! You've been an integral part of `create-substrate-app`'s development. The CLI tool downloads are already past 600, not sure how much of that is organic though, but this tool definitely would have been a great help when I was getting started with substrate.

**Comment by keeganquigley** [comment]
Thanks @PieWol for the evaluation and @philoniare for your fast assistance. Your evaluation has been accepted and I hereby accepting this milestone. Nice work!

**Comment by philoniare** [comment]
@RouvenP much appreciated. Confirmed that I've received it. Have a nice weekend.

**Comment by RouvenP** [comment]
hi @philoniare we were planning to send the DOT on Assethub but would instead send them on Polkadot now. Otherwise you wouldn't be able to stake them and couldn't transfer them out due to the vesting. is that fine with you?

**Comment by philoniare** [comment]
@RouvenP Yep, that's fine

**Pull request merged**
