### PR TITLE
DEIP - Milestone 1

### PR DESCRIPTION
**Pull request by aliakseikulik**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

Did you already agree on an adjustment of the price? If so, could you also create a pull request on the original grant application to reflect that?

**Comment by aliakseikulik** [comment]
> Thank you for the delivery. We will look into it as soon as possible.
> 
> Did you already agree on an adjustment of the price? If so, could you also create a pull request on the original grant application to reflect that?

We discussed the adjustment with David and agreed to not include the Web-based UI into this delivery and not invoice it. We have created a pull request (https://github.com/w3f/Open-Grants-Program/pull/414) updating our grant application and splitting it into two milestones instead of one. Milestone 2 will include the web-based UI part we are not able to deliver now and will deliver it once we have all the necessary components. Thus, the total price we provided in the grant application remains unchanged, but for now, we only deliver Milestone 1 with the price summed up in the invoice.

**Comment by semuelle** [comment]
Hi @aliakseikulik. I just updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/8339465a395d834fadcf21267140d4bf4ce344c4/evaluations/DEIP_1_semuelle.md) and your milestone is hereby accepted. :tada: 

Nice work overall. Easy to follow. Good documentation and tutorials are always appreciated.

I will forward your invoice for processing.

**Comment by aliakseikulik** [comment]
Hi @RouvenP , yes we confirm it received. Thanks

**Pull request merged**
