### PR TITLE
Delivery for M2 of Polkadot Contract Wizard

### PR DESCRIPTION
**Pull request by alongoni**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1413

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @alongoni I have started my evaluation. When I try to use the demo at https://www.contractwizard.xyz/ I get an error when trying to deploy the contract:

contract wizard error

Do you know what could be causing this? I don't see an option to pick what network I'm deploying on.

**Comment by alongoni** [comment]
Hi @keegan
Thank you for testing out our deliverable and bringing this issue to our attention. We apologize for the inconvenience you experienced while trying to use our demo.
In order to investigate this error, we would need some more details about the specific steps you followed leading up to it. Could you please provide us with more information about which features you selected?
Additionally, we would like to clarify that our current version of Contract Wizard only supports contracts on Rococo network, and there is no option to select a different network from the UI.

**Comment by alongoni** [comment]
As mentioned in my previous message, our current version only supports contracts on the Rococo network. However, if you would like to test the tool on a different network, you can do so by running the docker-compose and setting the env var NEXT_PUBLIC_PROVIDER_DEFAULT_SOCKET in the .env file to the desired network’s endpoint.

**Comment by keeganquigley** [comment]
Ah thanks @alongoni for the clarifications. This first happened when trying to create a PSP22 token, after connecting my wallet. However, it is working now after switching to Chrome browser, maybe that was the issue. Thanks! I will test the Docker version as well with a different endpoint.

**Comment by keeganquigley** [comment]
I'm able to compile it but now it gives an error about MAX_SAFE_INTEGER when trying to deploy:
integererror

With the other token types, it tells me I have insufficient funds to cover the transaction. I have 400 ROC's currently, how many should I have to successfully deploy it?

**Comment by alongoni** [comment]
hey @keeganquigley  thanks for keep testing the contract, the limit for a token supply is 2^53-1 you are trying 1e+42 that is a larger number. That's causing your error, please try with a smaller number and it'll work. Please let us know if you have further questions.

**Comment by keeganquigley** [comment]
Thanks @alongoni I was just entering 1000 and it was auto converting to this number so I will play around with it.

**Comment by keeganquigley** [comment]
You can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-contract-wizard_1_keeganquigley.md). Please note that both installation methods are failing. Should I be using the `development` branch or `milestone-1`?

**Comment by keeganquigley** [comment]
Thanks @0xLucca yep I was just about to update that it works after modifying the .env file. Thanks!

**Comment by keeganquigley** [comment]
I've updated my application and everything looks good. I think the only outstanding issues are with the deployed site. When I try to deploy either the PSP34 or the PSP37 it says I have insufficient funds, even though [my account](https://rococo.subscan.io/account/5CfwW8QTeFCotapEukrre4sT9tjMAp3jNY6VTyFAQ8hpd7F3) has 400 ROC.

insufficient funds

I'm not sure what is the issue here. Also, I am populating the initial supply with a smaller amount:

pre

But for some reason it changes it when I select "deploy", and also gives the insufficient funds error:

past

Is it working properly on your end? Thanks for any assistance you can provide here!

**Comment by 0xLucca** [comment]
Hi @keeganquigley !

It appears that the insufficient funds error is occurring because the ROC tokens you have are on the Rococo relay chain, whereas they need to be on the Rococo Contracts Parachain.

To obtain ROC tokens on the Rococo Contracts Parachain, you can use the following command in the Rococo Testnet Channel on Element:

!drip YOUR_SS_58_ADDRESS:1002

For further information and instructions, you can refer to the following link: https://use.ink/testnet/

Please give this a try and let us know if you encounter any further issues.

**Comment by 0xLucca** [comment]
@keeganquigley

We apologize for the confusion caused by this behavior.

The issue you experienced was due to the initial supply value being multiplied by 10^decimals during the deployment process. This conversion was not clearly communicated, resulting in unexpected changes to the value. We understand that this could be confusing and have taken your feedback into account.

I'm happy to inform you that we have addressed this issue in a new version. The updated version now displays the conversion of the initial supply value in a more user-friendly manner, providing clearer visibility into the adjusted value.

The fix has already been implemented and is available on our GitHub repository. We are in the process of updating the production deployment to include this new version, and it should be live shortly.

**Comment by keeganquigley** [comment]
Thanks @0xLucca very helpful, yes that makes sense I needed to be on the Contracts parachain. Thanks also for making the fixes. I'm happy to pass the milestone! You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-contract-wizard_1_keeganquigley.md) (note the minor broken link). 

Nice work!

**Comment by keeganquigley** [comment]
I have forwarded your invoice internally for payment.

**Comment by 0xLucca** [comment]
Hey @keeganquigley! 

Thank you for your positive feedback and for confirming that being on the Contracts parachain resolved the issue. 

Regarding the broken link, we will promptly address this issue and ensure that it is fixed.

We want to express our gratitude for your collaboration throughout the project. Your feedback and insights have been invaluable in refining our project. We are thrilled to have reached the end of the project and appreciate the opportunity.

**Pull request merged**
