### PR TITLE
Create ces_data_store_1.md

### PR DESCRIPTION
**Pull request by swowk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/855

### CODE REVIEW

**Comment by takahser** [comment]
@swowk Thank you for the delivery, we'll look into it as soon as possible.
Also, please allow for a longer than usual waiting time since we currently have a lot of open deliveries in the queue. I apologise for any inconveniences this might cause.

**Comment by ZoettaVerse** [comment]
hi @Noc2 , could you please have a look at this? We are still waiting for your response, thanks!

**Comment by Noc2** [comment]
@ZoettaVerse Sorry for the delay. I will try to look into this asap. Initially we had someone external, who wanted to look into this delivery, but apparently never did.

**Review by Noc2 — CHANGES_REQUESTED** [review]
I just took a very quick look at it and noticed a few minor issues. For example that the documentation on the benchmarks still mentions the template: https://github.com/CESSProject/data-store-pallet/blob/a552b78abfad0a4d6c81968731df611add1c4c66/pallets/data-store/src/benchmarking.rs#L1 and cargo test --release shows zero tests for pallet_data_store, but also runs the 6 tests for pallet_data_store-81554982bd3a900a. Additionally there seems no limit for new new_keywords (at least no error message) and the weight edit is constant (see https://github.com/CESSProject/data-store-pallet/blob/main/pallets/data-store/src/lib.rs#L193). Shouldn't this depend on the input.

**Comment by swowk** [comment]
Hi, @Noc2 . Thanks for your review, and sorry for the issue due to our negligence. We have resolved most of the issues as you suggested, please check again. About why cargo test --release will have the phenomenon you said, we will continue to deal with it. We would be grateful if you could tell us why.

**Comment by swowk** [comment]
Hi, @Noc2 . Thanks for your review, and sorry for the issue due to our negligence. We have resolved most of the issues as you suggested, please check again. About why cargo test --release will have the phenomenon you said, It may be that I didn't understand what you meant, I thought this output was ok. We would be grateful if you could explain this further.

**Review by Noc2 — APPROVED** [review]
Thanks for fixing everything. I’m happy to tell you that the milestone is a pass. The comment regarding cargo test --release wasn’t really relevant anyway. I will forward your invoice internally.

**Comment by RouvenP** [comment]
hi @swowk, we transferred the payment today. Thanks!

**Pull request merged**
