### PR TITLE
Yatima Milestone 2

### PR DESCRIPTION
**Pull request by johnchandlerburnham**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/463

### CODE REVIEW

**Comment by alxs** [comment]
Many thanks for the delivery. We will look into it as soon as possible.

**Comment by johnchandlerburnham** [comment]
Hi @mmagician, just want to double-check and make sure you have everything you need to review this submission. It's structurally very similar to our Milestone 1 delivery.

**Comment by mmagician** [comment]
Hey @johnchandlerburnham, thanks for checking in here. You're right, it is analogous and looks mostly fine as far as I've checked. I'm taking some time to understand the use cases for immutable data structures in Rust to understand the context for your delivery, as I wasn't familiar with the concept before. I hope to give you more structured feedback by the end of the week, please bear with me!

**Comment by mmagician** [comment]
@johnchandlerburnham Congratulations on completing M2! You can find my full evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/yatima_2_mmagician.md). Looking forward to M3, I guess that's where the fun really begins.

**Comment by RouvenP** [comment]
hi @johnchandlerburnham we just sent the payment for M2. Thanks!

**Pull request merged**
