### PR TITLE
Create Afloat_Milestone4.md

### PR DESCRIPTION
**Pull request by LouiseWReed**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/911

### CODE REVIEW

**Comment by randombishop** [comment]
Hi @LouiseWReed !
Just accepted M3, but before starting M4 evaluation, can you please provide the couple of docs I had requested before:
- Provide a general architecture guide that describes the different repos and how they interact with each other.
- Provide a doc that describes how to deploy and configure a full system locally.
Thanks a lot!

**Comment by AugustoLara** [comment]
> Hi @LouiseWReed ! Just accepted M3, but before starting M4 evaluation, can you please provide the couple of docs I had requested before:
> 
> * Provide a general architecture guide that describes the different repos and how they interact with each other.
> * Provide a doc that describes how to deploy and configure a full system locally.
>   Thanks a lot!

Working on it @randombishop

**Comment by jmgayosso** [comment]
> Hi @LouiseWReed ! Just accepted M3, but before starting M4 evaluation, can you please provide the couple of docs I had requested before:
> 
> * Provide a general architecture guide that describes the different repos and how they interact with each other.
> * Provide a doc that describes how to deploy and configure a full system locally.
>   Thanks a lot!

Hi @randombishop , we have been working on these docs, please review them and feel free to let us know any comments.
https://docs.hashed.network/general_architecture

**Comment by randombishop** [comment]
Thank you @jmgayosso the docs look good, I finally understood how Afloat fits into Hashed project; was kind of confused before because dev was happening in hashed repos and couldn't understand the relationship... Anyways, documentation looks good now and congrats to Hashed projects for securing a parachain slot!

Will finish this evaluation tomorrow...

**Comment by randombishop** [comment]
Hey @LouiseWReed !

The project looks great and I am happy to see a concrete real life application like this being built.
I checked all the boxes except last one "Launch Materials": it's defined in the contract as "Launch materials, videos and speaking arrangements for Louise are already in queue."; but the links shared don't look specific to Afloat product, do they?

Can you please replace with the Afloat specific launch material?

Or if the intention was to reference similar things done already and that you're planning to deliver something similar soon about Afloat, just indicate "Presentation X planned at Y."  I would go ahead with the delivery anyways given the amount of documentation and videos already produced along the different milestones.

Thank you!

**Comment by AugustoLara** [comment]
> Hey @LouiseWReed !
> 
> The project looks great and I am happy to see a concrete real life application like this being built. I checked all the boxes except last one "Launch Materials": it's defined in the contract as "Launch materials, videos and speaking arrangements for Louise are already in queue."; but the links shared don't look specific to Afloat product, do they?
> 
> Can you please replace with the Afloat specific launch material?
> 
> Or if the intention was to reference similar things done already and that you're planning to deliver something similar soon about Afloat, just indicate "Presentation X planned at Y." I would go ahead with the delivery anyways given the amount of documentation and videos already produced along the different milestones.
> 
> Thank you!

Hi @randombishop, thanks for your help and you are right. The talks mentioned are not about Afloat's launch, but they definitely touch on Afloat on Substrate in a context relevant to CPAs. They are a series of talks and we thought was the most "real" launch material since it's with Statewide CPA Societies and Universities. As you mentioned, we have Spanish and English videos and articles that explain what was built and how it can be used. And if people have questions, we share that material. Does that clarify the concern?

**Comment by randombishop** [comment]
Hi Afloat team!

Thanks for the clarification about launch materials, and congratulations for delivering this quality project.

Happy to accept this delivery, please find my evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/afloat_4_randombishop.md

Also forwarded your invoice, please expect up to 2 weeks for processing.

Cheers!

**Comment by RouvenP** [comment]
hi Afloat team, we transferred the payments for M3 and M4 today. Apologies for the delay on M3

**Pull request merged**
