### PR TITLE
Aisland docsig   milestone 2

### PR DESCRIPTION
**Pull request by poseidon-aisland**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] This pull request is being made by the same account as the accepted application.
- [ x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x ] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [ x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1853 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by nikw3f** [comment]
Hello @poseidon-aisland I am getting this error while running tests:

/Users/nikhil/w3f/docsig/node_modules/mysql2/promise.js:112
    const localErr = new Error();
                     ^

Error: Unknown column 'private' in 'where clause'
    at PromiseConnection.execute (/Users/nikhil/w3f/docsig/node_modules/mysql2/promise.js:112:22)
    at /Users/nikhil/w3f/docsig/docsig-server.js:1057:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: "select * from templates where private='N' or creator=? order by description",
  sqlState: '42S22',
  sqlMessage: "Unknown column 'private' in 'where clause'"
}

Seems like schema is not up to date

**Comment by poseidon-aisland** [comment]
Sorry for the issue, I've updated the databases schema for docker and tested it well, I've updated the repo accordingly.  There is also a new variable that may be necessary to update in case of use behind a reverse proxy. The README has been updated to explain it.

**Comment by poseidon-aisland** [comment]
I've updated the unit tests as well, for what I see everything is ok.

**Comment by poseidon-aisland** [comment]
can I help in doing something more?

**Comment by nikw3f** [comment]
Hey team, tests still not passing.

server stops on.

```
TypeError: Bind parameters must not contain undefined. To pass SQL NULL specify JS null
    at /Users/nikhil/w3f/docsig/node_modules/mysql2/lib/connection.js:664:17
    at Array.forEach (<anonymous>)
    at Connection.execute (/Users/nikhil/w3f/docsig/node_modules/mysql2/lib/connection.js:656:22)
    at /Users/nikhil/w3f/docsig/node_modules/mysql2/promise.js:121:11
    at new Promise (<anonymous>)
    at PromiseConnection.execute (/Users/nikhil/w3f/docsig/node_modules/mysql2/promise.js:118:12)
    at /Users/nikhil/w3f/docsig/docsig-server.js:1238:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  ```
  on test   ● Api - Update Document Counterpart
  Please fix all the tests

**Review by nikw3f — APPROVED** [review]

**Comment by nikw3f** [comment]
Thanks for the delivery @poseidon-aisland. You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Aisland-DocSig_2_nikw3f.md) here. Happy to pass the milestone.

**Pull request merged**
