### PR TITLE
Create lunie-governance_milestones-1-2-3.md

### PR DESCRIPTION
**Pull request by jbibla**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by jbibla** [comment]
Thank you kindly!

**Comment by mmagician** [comment]
@jbibla Thanks for the delivery! Could I ask you to update your PR to inclide links to the relevant files (+lines, if applicable) in your github repository where the specific deliverables are implemented? Please do this for all the points specified in your original contract PR to the Open Grants Program, e.g. : 
```
* see list of active proposals (<github link>)
* see when proposals are active and for how long (<github link>
* etc
```

This will speed up our evaluations.

**Comment by jbibla** [comment]
Hey @mmagician! I've edited the PR to include some links to our codebase. Much of our code is not specific to this grant but I did my best to include some relevant links. Here are some screenshots which demonstrate the deliverables. 

This project is currently live and accessible at https://app.lunie.io/kusama/proposals and https://app.lunie.io/polkadot/proposals. 

Governance Overview for Polkadot and Kusama:
Screen Shot 2020-09-28 at 9 27 22 AM
Screen Shot 2020-09-28 at 11 34 02 AM

Proposal Page for Polkadot and Kusama:
With Depositing:
Screen Shot 2020-09-28 at 9 30 29 AM
With Voting:
Screen Shot 2020-09-28 at 11 37 55 AM

Council Members for Polkadot and Kusama:
Screen Shot 2020-09-28 at 9 27 42 AM
Screen Shot 2020-09-28 at 11 34 13 AM

**Comment by jbibla** [comment]
Hey @mmagician just following up here. Anything we can do to help move this along?

**Comment by mmagician** [comment]
@jbibla Not really, thanks for checking though. Please give us a couple of days more.

**Comment by blrhc** [comment]
I have performed an external evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/pull/41.
As this is my first evaluation, please let me know if any improvements are required or if I have misunderstood the process.

**Comment by jbibla** [comment]
Thank you @blrhc! We really appreciate the time and energy. I'd love to hear your feedback about our governance system from a UX / UI perspective if there is any!

**Comment by mmagician** [comment]
@jbibla When looking at a proposal on Lunie, I can't see its body:
Screenshot 2020-10-05 at 19 14 27

Whereas on polkadotJS apps I see: `staking.increaseValidatorCount`.
Isn't that the core feature of viewing proposals?

**Comment by jbibla** [comment]
That's a simple bug - we'll make a quick fix to display the data in the `call` object of param change proposals.

**Comment by mmagician** [comment]
@jbibla Btw, what's the status of the integration with Polkadot JS Extension? Quoting from the original PR:
> Support would include integration with [...] Polkadot JS extension

Thanks!

**Comment by jbibla** [comment]
We've released the fix to display all the data from the `call` object on param proposals.

Screen Shot 2020-10-07 at 8 25 42 AM

> what's the status of the integration with Polkadot JS Extension? 

It's on our roadmap but not something we've been able to accomplish yet.

**Comment by mmagician** [comment]
@jbibla Thanks! It seems that the previous evaluator withdrew their PR so I'll be looking into your delivery shortly (unless we get new external deliveries in the meantime)

**Comment by jbibla** [comment]
hey @mmagician hope you're well. we're eagerly awaiting approval on this grant. let me know if there's anything else we can do!

**Comment by jbibla** [comment]
thanks @Noc2!

**Comment by Noc2** [comment]
Hi @jbibla I finally started to look into your delivery and I have a few questions/comments: 

- The extension and api folder currently don’t contain a license file. The open grants program requires you to publish the software under the apache license. 
- When you use not your default browser to sign up for notifications, you get an error message when you just click the magic link. Maybe integrate a notification, so that people are aware of it (optional)
- For time locking on polkadot, the UI shows a black number on a black background for the selected parameter (optional)
- In the browser, it shows list of proposals, but there is no way to create a proposal. Although it says "There are currently no governance proposals to display. Click the 'Create Proposal' button to submit the first network proposal!" (optional) 
- In the app the initial window when I log into my account is too big for the screen and it let’s me scroll left and right (optional)
- In general it takes quite long to load the information (optional)

**Comment by jbibla** [comment]
thanks for the feedback @Noc2! 

> The extension and api folder currently don’t contain a license file. The open grants program requires you to publish the software under the apache license.

thanks. i'll update the licenses and add the license files.

> When you use not your default browser to sign up for notifications, you get an error message when you just click the magic link. Maybe integrate a notification, so that people are aware of it (optional)

not sure what you mean here. would you mind [filling out an issue](https://github.com/luniehq/lunie/issues/new/choose) with steps to reproduce? 

> For time locking on polkadot, the UI shows a black number on a black background for the selected parameter (optional)

thanks. i'll push a fix for this css bug. 

> In the browser, it shows list of proposals, but there is no way to create a proposal. Although it says "There are currently no governance proposals to display. Click the 'Create Proposal' button to submit the first network proposal!" (optional)

ah interesting! i don't think i've ever seen polkadot / kusama without proposals - we'll address this case though! 

> In the app the initial window when I log into my account is too big for the screen and it let’s me scroll left and right (optional)

on mobile / in the browser? could you share a screenshot?

> In general it takes quite long to load the information (optional)

yes, sorry about this - we're debugging some performance issues at the moment. for polkadot and kusama we have found the nodes generally quite slow and unreliable (constantly dropping connections) so we are in the process of switching to use https://github.com/paritytech/substrate-api-sidecar

**Comment by Noc2** [comment]
Thanks for the quick fixes. I’m happy to tell you that the milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/lunie_1_Noc2.md) and will now forward your invoice internally

> ah interesting! i don't think i've ever seen polkadot / kusama without proposals - are you talking about the list of proposals for polkadot / kusama?

I saw it while I was testing the Kusama version

> on mobile / in the browser? could you share a screenshot?

On mobile

**Comment by jbibla** [comment]
thank you @Noc2 - appreciate the time and effort!

**Comment by RouvenP** [comment]
hi @jbibla we just sent a test transaction. Could you please confirm if received?

**Comment by jbibla** [comment]
hey @RouvenP - thank you. i really appreciate this test! yep, we did receive it.

**Pull request merged**
