### PR TITLE
ink! analyzer (phase 2) - milestone 6

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1904 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @davidsemakula great work as usual, here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_6_keeganquigley.md). Looking forward to seeing everything put together in VS Code.

**Comment by davidsemakula** [comment]
Thanks @keeganquigley 🎉 
Full VS Code updates will ship in the next 2-3 weeks!

I've also submitted the invoice for this one. 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula we sent the payment today

**Comment by davidsemakula** [comment]
Hi @RouvenP 
Received thanks! 🙂

**Pull request merged**
