### PR TITLE
Substrate MolochDAO v2 milestone delivery

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @zhangjiannan. We will look into it as soon as possible.

Could you remove the M1 document and the .DS_Store files from your PR? The M1 document is already merged.

**Comment by zhangjiannan** [comment]
@semuelle thanks! Submitted again and the files should be removed now.

**Comment by alxs** [comment]
@zhangjiannan I've gone ahead and removed the unnecessary files. @semuelle will be in touch with you soon to provide feedback.

**Comment by semuelle** [comment]
Hi @zhangjiannan,
I had to again fix line 37 of `authorities.rs` of `sc-finality-grandpa`, and also remove the `[replace]` section in the `Cargo.toml` for the project to compile. Could you add this information to the readme and testing guide? Or better yet, use a newer `grandpa` version?

**Comment by semuelle** [comment]
> The contracts can support multiple tokens at the same time. So there are dedicated proposals to accept new tokens.
>
> As multiple tokens are not implemented yet in substrate, we'll skip this part in our pallet.

By `contracts`, you mean the Solidity implementation?

**Comment by tinydjp** [comment]
> Hi @zhangjiannan,
> I had to again fix line 37 of `authorities.rs` of `sc-finality-grandpa`, and also remove the `[replace]` section in the `Cargo.toml` for the project to compile. Could you add this information to the readme and testing guide? Or better yet, use a newer `grandpa` version?

Hi @semuelle We've just updated the Cargo file and test guide for Linux compilation. Please help check again. Sorry for the inconvenience

**Comment by tinydjp** [comment]
> > The contracts can support multiple tokens at the same time. So there are dedicated proposals to accept new tokens.
> > As multiple tokens are not implemented yet in substrate, we'll skip this part in our pallet.
> 
> By `contracts`, you mean the Solidity implementation?

Yes, the Solidity one.

**Comment by semuelle** [comment]
> As multiple tokens are not implemented yet in substrate, we'll skip this part in our pallet.

Did you consider using the [Assets](https://docs.rs/pallet-assets/3.0.0/pallet_assets/index.html) pallet?

**Comment by tinydjp** [comment]
> > As multiple tokens are not implemented yet in substrate, we'll skip this part in our pallet.
> 
> Did you consider using the [Assets](https://docs.rs/pallet-assets/3.0.0/pallet_assets/index.html) pallet?

From our understanding the most similar module is `Balance`, which means our node just make a record of these tokens. We won't issue different assets per user's request. Assets module is more fit to some chain-bridge functions. As for the multiple token protocols, we hope there's a CurrencyAdapter or something to help us manage all kinds of token in polkadot's ecosystem. However, your hint reminds us to do some chain-bridge support, it's very helpful. Maybe it's the better to allow more customers to use.

**Comment by semuelle** [comment]
With the assets module, anyone can create an asset. It should also be possible to use XCM to use assets created on Statemine/Statemint. But I understand if that's not something you want to implement yet. It might be worth revisiting this (and an upgrade to `sc-grandpa-finality v0.9.0`) once we have a stable [fungible token standard](https://github.com/w3f/PSPs/pull/22). 

I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/7ff06d45c58a3f98a7c4361d582f701ba3147b82/evaluations/molochDAO_2_semuelle.md) and your milestone is hereby accepted. :tada: 

I will forward your invoice for processing.

**Comment by tinydjp** [comment]
Yes, in the long run, we'll use XCM to help us with the multiple tokens(assets) transferring. As for the `sc-grandpa-finality`, we did try to upgrade, there'r 3 versions: 0.8.0, 0.8.1 and 0.9.0. Unfortunately, the previous 2 versions have the same bug, while the latter one is designed for Frame V2(i.e. Substrate `3.0.0`).

**Pull request merged**
