### PR TITLE
Add openPayroll deliverable

### PR DESCRIPTION
**Pull request by rtomas**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1592

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @rtomas your external evaluation was [passed](https://github.com/w3f/Grant-Milestone-Delivery/pull/940). I was able to run the tests as well, create a contract and add beneficiaries, and play around with sending payments.

payroll

payroll2

Was also able to upload the existing contract + metadata in polkadot.js and execute different messages manually. Great work!

**Comment by fededubbi** [comment]
Hi @rtomas,

I noticed that our name on the invoice is wrong and also address.
The correct one is:

Web 3.0 Technologies Stiftung 
Baarerstrasse 14,
6300, Zug.

Can you please change it and update?

Many thanks,
Federica

**Comment by rtomas** [comment]
Hi @fededubbi,
Hope you are doing good. 
We have already amended the invoice with the correct name and address. If you need further assistance or have any other issues, please don't hesitate to reach out.

Thanks 
Tomas

**Comment by semuelle** [comment]
Hi @rtomas. Sorry for the delay. I don't have insight into the payment info, but I have pinged the finance team about it.

**Comment by meldien** [comment]
@rtomas apologies for the delay from our end. The payment will be done in the next 24h. Stay you updated

**Comment by meldien** [comment]
@rtomas payment done

**Pull request merged**
