### PR TITLE
Universaldot.me - Milestone 1

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/714

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible. Btw. you are not allowed to submit your own evaluation for this. Or we would probably more or less ignore it.  ;-)

**Comment by JosephKnecht-lab** [comment]
Hi @alxs. Thank you for the feedback. I am glad someone likes the videos. 

Regarding your points...
1. I have created benchmarks for all extrinsics as promised. The autogenerated weights for the extrinsics can be found here: https://github.com/UniversalDot/universal-dot-node/commit/70e1884112a3234cdc624e19a1a418ccf7b3303c 
2. I was able to build the image in Ubuntu. Docker seems to have some issues with the latest Mac M1 architecture. I pushed the image on DockerHub: https://hub.docker.com/r/universaldot/node . 
3. I have updated the README.MD to reflect better the current state of the project. https://github.com/UniversalDot/universal-dot-node . There are some ongoing changes, but we will consolidate for the official release. 

Let me know if you have any further questions/comments.

**Comment by JosephKnecht-lab** [comment]
Hi @alxs 

To build the latest update from source, please checkout the `add_weights` branch. Here are the exact commands.
`git clone https://github.com/UniversalDot/universal-dot-node.git`
`cd universal-dot-node`
`git checkout add_weights`
`cargo run --release -- --dev --tmp`
(I am using rustc 1.58.1 (db9d1b20b 2022-01-20)) 
Alternatively, you can also connect to a node that is already running on VPS: "ws://109.235.70.27:9944"

I have updated the instructions for running the application with docker: https://github.com/UniversalDot/docker-compose. I tested it on ubuntu:20.04 machine and it builds correctly for me.  

We are actively working on Milestone2, and would appreciate joining the substrate builder program. I had a call with Santiago Balaguer a while back and he mentioned that we will be automatically enrolled in the program after the first milestone is accepted. Is that still the correct process?

**Comment by alxs** [comment]
Thank you, that worked.

I meant instructions to [run the node](https://github.com/UniversalDot/universal-dot-node#run-in-docker) using Docker.

I'm getting nothing other than the error below when running the node+front end using docker compose. Any idea what the issue could be? By the way, I'd recommend renaming the repository since it's not `docker-compose` itself that it contains, but a different project. I.e. after cloning there's no way of knowing what the project is. Just a comment.

image

Let me get back to you on the Substrate Builders Program.

**Comment by JosephKnecht-lab** [comment]
Hi @alxs 

I can see how running docker-compose in docker-compose repo can be confusing. I have renamed the repo to compose-service. (https://github.com/UniversalDot/compose-service)

The error looks familiar. I have resolved it before can't recall the cause anymore. I have a front-end developer working on the React application at the moment, and the React application is to be delivered as part of milestone2. 

We look forward to joining the Substrate Builders Program. Please let us know how we can do that... Thanks

**Comment by alxs** [comment]
True, I didn't realise the frontend wasn't part of M1. Just a [few last things](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/universaldot-me_1_alxs.md):

- Please modify [these instructions](https://github.com/UniversalDot/universal-dot-node#run-in-docker) (and potentially the Docker image) to describe how to run the node using Docker.
- Could you please merge everything that is part of the delivery into one branch in the `universal-dot-node` repo? Currently, it's split across 3 different branches.
- The Dockerfile in the `add_pallets` branch didn't work for me on Ubuntu either. Please make sure the final branch has a working one.
- Could you address the warnings reported by `cargo clippy` in `pallet-dao` and `pallet-task`?

Regarding the Substrate Builders Program, you aren't exactly automatically enrolled when your first milestone is accepted; you still need to [apply](https://substrate.io/ecosystem/substrate-builders-program/). However, if you already applied Parity may just be waiting for this milestone to be accepted. If that's the case, please just reach out to Santiago once the milestone has been accepted or if you haven't applied yet, simply mention it in your application.

**Comment by JosephKnecht-lab** [comment]
Hi @alxs 

* I have modified the [instructions](https://github.com/UniversalDot/compose-service#build-docker-node) for building the node. Use this [Dockerfile](https://github.com/UniversalDot/compose-service/blob/master/node/Dockerfile) as described in the instruction. 
* I have merged all the code changes to a new branch callled `master-release`. 
* The Dockerfile has been updated to use the `master-release` branch. I also made small adjustments to the locale and language settings which probably was causing problems. 
* Great find. I have addressed all clippy warnings for the [Task](https://github.com/UniversalDot/pallets/commit/33b03745dbbd61eddcbabbb25099875fc86e2b50) and [Dao](https://github.com/UniversalDot/pallets/commit/1e96f1d72212fa2f6743befda7b518ad3060829a) pallets. 

I have already applied for the Substrate Builders Program. In fact, I have applied for the Substrate Builders Program before I applied for this grant. I will reach out again to Santiago or team after the milestone has been accepted.  Thank you for your help.

**Comment by alxs** [comment]
Thanks for the changes. The [docker script](https://github.com/UniversalDot/universal-dot-node/tree/master-release#run-in-docker) failed for me on two accounts - you need to first create the `.local` directory, and then with the following error:

```
error: failed to parse manifest at `/var/www/node-template/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-entity-0.77.0/Cargo.toml`

Caused by:
  feature `resolver` is required

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can add
  `cargo-features = ["resolver"]` to enable this feature
ERROR: 101
```

**Comment by JosephKnecht-lab** [comment]
HI @alxs,

This is unusual since I just tested it and it worked for me on Ubuntu 20.04. 

When I do a google search it seems to be an incompatibility with your `cargo --version`. You can see the open issue here: https://github.com/emilk/egui/issues/297

**Comment by alxs** [comment]
How can this be? It's running on the same image for both of us. My cargo version shouldn't matter.

Could you test it on a fresh install?

**Comment by JosephKnecht-lab** [comment]
I did a new build and it worked also. I have included the command-line output here: https://hackmd.io/@D3QwgNTnSnmMYhahCx8PMQ/ryxHg0Cjk5 

If this is the only issue left from milestone 1, we can investigate and fix it in Milestone 2 which is also nearly done. 

By the way, I will be out of the office until Wednesday of next week so there might be a delay in responses.

**Comment by JosephKnecht-lab** [comment]
> Are you actually running the script in the `universal-dot-node` repository? Given the prompt at the end, it doesn't look like it.

No. Sorry. I was using the Dockerfile from the compose-service. I have updated the application file to include the correct Dockerfile.

**Comment by alxs** [comment]
Thanks, that one worked. Please think of updating the [instructions](https://github.com/UniversalDot/universal-dot-node#run-in-docker) in the repository of the node too.

With this, I'm happy to tell you that the milestone is a pass! You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/universaldot-me_1_alxs.md). I'll notify the operations team to pay out your invoice.

**Comment by alxs** [comment]
@JosephKnecht-lab we have a bot that should have posted the following, but failed since you the link in your delivery points to your fork:

Congratulations on completing the first milestone of this grant! As part of the Grants Program, we want to help grant recipients acknowledge their grants publicly. To that end, we’ve created a [badge for projects](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md) that successfully deliver their first milestone. Note that it must only be used within the context of the delivered work, so please do not display it on your team or project's homepage unless accompanied by a short description of the grant.

Furthermore, you're now welcome to announce the grant publicly. Please remember to observe the [foundation’s guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) in doing so. In case you haven't done so yet, you may also reach out to grantsPR@web3.foundation for feedback on your announcement and cross-promotion.

Thank you for your contribution and good luck with the remaining milestones, if any! As usual, please let us know if you run into any delays by leaving a comment on the application PR, or directly submitting an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Comment by JosephKnecht-lab** [comment]
Great. Thank you @alxs. 

I have already reached out to Santiago regarding joining the Substrate Builders Program.

We will update our GitHub repositories to include the badge and will make announce the grant publicly in due time. 

Thanks again.

**Comment by RouvenP** [comment]
hi @JosephKnecht-lab we transferred the payment today. Thanks!

**Pull request merged**
