### PR TITLE
RegionX: Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by Szegoo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] This pull request is being made by the same account as the accepted application.
- [X] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [X] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2080

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @Szegoo, 
the code for the xc-regions contract looks good, thanks for the update today 👍 

I enjoyed the article, wiki and additional documents that you linked at the right time to make sure the reader knows the needed concepts to progress. Thanks for that. 

I'm trying to test with the "full" option of the Coretime-Mock testing options you described in the Coretime-Mock readme. 
Can you please add a similar step-by-step testing guide as you have for the CoreHub? E.g. declare how to correctly pull submodules, change script permissions etc.. I would really appreciate it. It doesn't need be explicitly for every testing possibility but I think it would make a lot of sense to do it for the full testing option that includes the testing of the ink contracts.

**Comment by Szegoo** [comment]
@PieWol Thanks for the feedback. The Coretime-Mock documentation was indeed a bit confusing. However, that should now be resolved with this [PR](https://github.com/RegionX-Labs/Coretime-Mock/pull/39). Let me know if it looks good now, or if you have some further suggestions on how to improve it.

**Comment by PieWol** [comment]
I'm trying to use your suggested additional testing commands so that on both chains I pass alice's account to transfer the region and xc-region to on the coretime chain aswell as the contracts chain. Sadly all I get is API-WS abnormal closure output. The network doesn't seem to be launched correctly. Do you have any hint how to solve this issue? Without additional flags the full network launch works fine 👍.

This is my console input with alice's keys for both chains. 

```
npm run zombienet-init:full -- \
  --contracts ../RegionX/target/ink/ \
  --coretimeAccount "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY" \
  --contractsAccount "ajYMsCKsEAhEvHpeA4XqsfiA9v1CdzZPrCfS6pEfeGHW9j8"
```

**Comment by Szegoo** [comment]
@PieWol The reason why the full init wasn't working is because it requires the `npm run zomibenet:full` command to be run in the background. I added some more clarification to the docs to point this out: https://github.com/RegionX-Labs/Coretime-Mock/pull/40

The primary purpose of specifying the receiver of the regions is for UI testing. The reason you can't see the regions on the dashboard is that it only displays the regions you own. Since the init script transferred them to Alice, one option is to manually transfer the regions back to yourself. However, a simpler solution would be to rerun the local network and specify your own address as the recipient this time.

**Comment by PieWol** [comment]
Thank you for clarifying now I see what went wrong. 💡

**Comment by semuelle** [comment]
Hi @Szegoo, I am happy to report that your milestone is hereby accepted. You can find our evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/RegionX_1_PieWol.md). 

The only thing I want to add to @PieWol's evaluation notes is that the Coretime-Mock test scripts refer to `zombienet-macos` and `zombienet` executables, but for Linux it'd be `zombienet-linux-x86`.

**Comment by PieWol** [comment]
Congratulations @Szegoo  🥳

**Comment by Szegoo** [comment]
Thanks! Preparing to release the frontend for testing on Rococo this week :)

If the invoice form was filled out prior to the acceptance of the milestone, does it need to be filled out again?

**Comment by PieWol** [comment]
Hey @Szegoo , no worries we still got the invoice. No need to submit it again 👍

**Comment by RouvenP** [comment]
hi @Szegoo we sent the payment today

**Pull request merged**
