### PR TITLE
SpiderDAO Delivery Milestone

### PR DESCRIPTION
**Pull request by AnasSpider**
# Milestone Delivery Checklist

- * [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- * [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- * [x] This pull request is being made by the same account as the accepted application. 
- * [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- * [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Marked `on hold` as we're still waiting for hardware

**Comment by AnasSpider** [comment]
@mmagician We can see the hardware has now been collected by yourselves. Hopefully the review is going to start imminently. Thanks!

**Comment by mmagician** [comment]
@AnasSpider Indeed we got the hardware, thank you! We will try to look at your milestone as soon as we can. Since we currently have a number of deliveries in the pipeline, this might take longer than usual. We'll keep you posted in case the evaluators have any questions.

**Comment by AnasSpider** [comment]
No worries. Cheers @mmagician, Much appreciated! Please let us know if you have any questions.

**Comment by Lederstrumpf** [comment]
Hi @AnasSpider, I forgot to submit my review over here: https://github.com/w3f/Grants-Program/pull/113#discussion_r689952944

Basically, how do I explore the chain state of the testnet you're using for the hardware router? It's not on official Westend.

**Comment by AnasSpider** [comment]
Hi @Lederstrumpf thanks for your reply. We are currently using our own internal testnet and the plan is to migrate to Westend once all approved by yourselves. You can check the chain state here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnode3.spiderdao.io 

Please let us know if you have any questions. Cheers!

**Comment by AnasSpider** [comment]
Hi @Lederstrumpf Just checking in to see how's the review going and if you have any questions as it's been more than 2 weeks since your last reply. We have put all substrate new features/improvements on hold for release (Development is done) until you are done reviewing this delivery. Could you please quicken that up so we can move other things forward?

cc. @Noc2 @mmagician @alxs 

Thanks!

**Comment by Lederstrumpf** [comment]
Hi @AnasSpider, apologies for the delay in getting back to this.

1. Your application stated that the DAO logic would be implemented using `ink!` smart contracts. Where do I find these?
2. How do I use the dVPN service? Under which conditions is it "complimentary"? 
3. Where do I find the implementation of `SpiderDashboard` that was promised in the grant application? From what I can tell, the only GUI akin to this is the `wallet.php` from the router dashboard, and it's ... limited ... at best.
4. What exactly was changed in SpiderDAO's fork of polkadot? Aside from [parameters](https://github.com/SpiderDAO/polkadot/commit/a487768efcee14fab29be8e4e3534fe70da150b0) and typo fixes, the only other two commits from your contributors are absolutely massive [SpiderDAO democracy mods](https://github.com/SpiderDAO/polkadot/commit/3dc5f145f78ae7a13eac351a90559e45d1fe47b4): `126,664 additions and 18,276 deletions` and [spidertestnet mods](https://github.com/SpiderDAO/polkadot/commit/bd245f4bf83c202737480b616dfef5f1acbb6755): `12,442 additions and 16,570 deletions`.
5. Are your "SpiderDAO framework modules" strictly python wrappers around the `System`, `Balances`, and `Democracy` pallets? Because I don't see anything else going on in [spiderdao.py](https://github.com/SpiderDAO/spiderdao_testnet/blob/main/src/spiderdao.py), except for keeping this in sync with a `pickledb` (which is also all the functionality I see available under `wallet.php`).

I'll have further questions, but it's best to start with these.

**Comment by Lederstrumpf** [comment]
Oh, before I forget: one of the routers has become so slow that it's impossible to use the interface - including for a factory reset (although the device still routes fine with VPN disabled). Holding down the pin at the back didn't work for me either - I tried for around 30 seconds. Anything else I could try to get it useable again?

**Comment by AnasSpider** [comment]
> 1- Your application stated that the DAO logic would be implemented using ink! smart contracts. Where do I find these?

After a lengthy discussion between our developers, we decided to use Pallets instead of ink!. The single most important feature within Pallets was its ability to seamlessly make changes on its source, this also reflected our desire to offer the Democracy pallets features that we deemed important to the project.

> 2- How do I use the dVPN service? Under which conditions is it "complimentary"?

Due to our high workload the dVPN feature is not yet integrated in the substrate ecosystem, however, our network is currently being successfully handled internally as well as by our trusted partners. We are currently in the final stages of an additional (as yet undisclosed) project which will incorporate the first steps of our dVPN network.

> 3- Where do I find the implementation of SpiderDashboard that was promised in the grant application? From what I can tell, the only GUI akin to this is the wallet.php from the router dashboard, and it's ... limited ... at best.

We agree that the current SpiderDashboard is in a limited form, however, this is just the first step. The next steps are already completed and will be implemented shortly, however, we have our hands tied until we get the current delivery approved by yourselves. Once this is done we will announce the next milestone.

> 4- What exactly was changed in SpiderDAO's fork of polkadot? Aside from parameters and typo fixes, the only other two commits from your contributors are absolutely massive SpiderDAO democracy mods: 126,664 additions and 18,276 deletions and spidertestnet mods: 12,442 additions and 16,570 deletions.

The mods and deletions are substantial because we initially started development using Polkadot based on Substrate v2.0 and after some time we upgraded to Substrate v3.0. Most of the changes are caused by the update to Substrate v3 on branch spiderdao-testnet. The changes to Polkadot's fork consist of adding Democracy module support and other changes needed to make it work correctly. These changes are explained here:

 https://github.com/SpiderDAO/spiderdao_testnet/blob/main/trackchanges/spider_changes.md 

> 5- Are your "SpiderDAO framework modules" strictly python wrappers around the System, Balances, and Democracy pallets? Because I don't see anything else going on in spiderdao.py, except for keeping this in sync with a pickledb (which is also all the functionality I see available under wallet.php).

Yes you are correct, the spiderdao.py is a Python wrapper based on substrate-interface library to make chain calls for democracy pallet.

> Oh, before I forget: one of the routers has become so slow that it's impossible to use the interface - including for a factory reset (although the device still routes fine with VPN disabled). Holding down the pin at the back didn't work for me either - I tried for around 30 seconds. Anything else I could try to get it useable again?

Sorry to hear of your problems, this is quite a rare occurrence, however, you can follow these steps to fix the unit: 

https://docs.spidervpn.org/guides/uboot-recovery-for-windows.

**Comment by Noc2** [comment]
Hi @AnasSpider. Apologies for once again a very long delay. This certainly shouldn't have happened on our end and we'd like to extend our apologies. However, the delivery is far away from what was promised in the original contract. The main reason for example I originally approved it was ““We are going to build our DAO framework using Ink! Smart Contracts for this milestone.”  Are you still planning on delivering this DAO framework in ink!? Otherwise we would terminate the current contract in the next two weeks. Also because it looks like you are no longer working and maintaining the project.

**Comment by AnasSpider** [comment]
Hi @Noc2 Not a problem, I know teams can be under tight deadlines and this things happen. Hopefully we can fast track the process now given the delays.

> However, the delivery is far away from what was promised in the original contract. The main reason for example I originally approved it was ““We are going to build our DAO framework using Ink! Smart Contracts for this milestone.” Are you still planning on delivering this DAO framework in ink!?

We mentioned earlier the reasons why we used pallets instead of Ink! smart contracts which offered more flexibility to our hardware routers integration. Even though we are happy to rewrite the code using the smart contracts instead and update our APIs accordingly. 

We will start of the smart contracts implementation right after new year holidays. We will keep updating the schedule accordingly.

Happy Holidays to you and your team!

Thanks,
Anas

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the reply. In this case I suggest creating a PR to update the current contract here: https://github.com/w3f/Grants-Program/blob/master/applications/SpiderDAO.md and try to get the required approval by the grants committee as soon as possible. Given that the grant is now officially delayed for one year, the timeline should definitely be updated. In general, if you plan on changing the scope, it is always good to update the grant accordingly and get the necessary approval first.

**Comment by Noc2** [comment]
Since you haven’t created any PR to update the original contract and all of [your repositories don’t seem to be maintained](https://github.com/SpiderDAO), we will go ahead with the termination. Thanks again for all the effort you put into this. If you want to continue to work on the project, feel free to apply for a new grant.

**Comment by AnasSpider** [comment]
Hi @Noc2 Sorry we have been busy with other priorities and unfortunately we didn't had the time to create the PR to update the original contract. We will start a new grant in due course once our  plans execution substrate framework is underway.

Please keep the hardware routers we sent earlier as you will be using the same devices for evaluating our upcoming web3 grant project.

All the best,
Anas

**Pull request closed without merging**
