### PR TITLE
Add ZK-Snarks_with_Substrate_tutorial-Milestone1

### PR DESCRIPTION
**Pull request by bufta**
Adding the delivery specification for Milestone 1

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. <- we needed to change the wallet address. The correct one is on the invoice. Please let us know if we should update the proposal file as well.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1290

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @bufta. We'll look into it as soon as possible. Yes, could you please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the payment address in your application?

**Comment by dsm-w3f** [comment]
@bufta thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zk-snarks-tutorial_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by bufta** [comment]
Hi @dsm-w3f, thank you very much for your feedback. We incorporated your remarks and the improved version is available in the repository in the branch: https://github.com/bright/zk-snarks-with-substrate/tree/M1. Should you have any comments or suggestions during the further evaluation, please let us know and we'll be happy to reply.

**Comment by dsm-w3f** [comment]
@bufta thank you for the improvements and fixes. The milestone delivery was approved. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zk-snarks-tutorial_1_dsm-w3f.md). I'll forward the invoice internally and it should be paid within two weeks (could happen before). Good Job!

**Comment by dsm-w3f** [comment]
@bufta It seems the address in the invoice is different from the address in the application. Could you please either update the application sending an amendment or the invoice?

**Comment by bufta** [comment]
@dsm-w3f yes, sorry - the one in the invoice is correct. I prepared a PR with amendment of our proposal to include the correct address, however I haven't pushed it apparently. I will do it today.

**Comment by RouvenP** [comment]
hi @bufta we transferred the payment today

**Pull request merged**
