### PR TITLE
Dante Network Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by xiyu1984**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/895 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @xiyu1984. We will look into it as soon as possible.

**Comment by keeganquigley** [comment]
Hi @xiyu1984 I have started the process of reviewing your milestone. Please give me some time to research and understand your project, and I will reach out with any questions that I may have. Thanks!

**Comment by keeganquigley** [comment]
Thanks for your patience @xiyu1984! Wow, this is a very interesting project indeed! I have a few initial questions while working through the [testing guide](https://github.com/dantenetwork/cross-chain-demo/tree/main). 

1. When I run the first script avalancheToAstar.js I get this error:

```
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --greet
date "2022-08-19T16:03:51.659Z"
gasUsed: sendGreeting 665819
/Users/keeganquigley/cross-chain-demo/node_modules/web3-core-helpers/lib/errors.js:28
        var err = new Error('Returned error: ' + message);
                  ^

Error: Returned error: execution reverted
    at Object.ErrorResponse (/Users/keeganquigley/cross-chain-demo/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /Users/keeganquigley/cross-chain-demo/node_modules/web3-core-requestmanager/lib/index.js:302:36
    at XMLHttpRequest.request.onreadystatechange (/Users/keeganquigley/cross-chain-demo/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  data: '0x'
}
```
Despite it saying the execution was reverted, the transaction executes successfully on FUJI: https://testnet.snowtrace.io/tx/0xad92b96644a7ba43043bd4527b0411a0147e032dec0e2e844ba16ffd79fdf502

So I'm not sure what this error is indicating.

2. It appears to be working, as when querying the result on Shibuya, I can successfully get the `id` by calling `getReceiveMessageNumber`:

getreceivedmessagenumber

And then using the `id` I can see my message!

getret

Pretty cool! Though I would suggest flipping the order of instructions around to make it clear that you need the message `id` in order to find the corresponding message.

3. Next, I'm able to successfully send a greeting from Shibuya:

sendgreeting

And I can see the message `id` successfully increments by 1.

getsentmessagenumber

However, when trying to query the received message on FUJI it just waits forever with this message:

```
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --query 9   
Wait for the message to be synchronized. 9
^C
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --query 10  
Wait for the message to be synchronized. 10
```
4. Finally, the rest of the test greetings for Moonbeam and Near work great. 

```
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node moonbeamToNear.js --greet
date "2022-08-19T17:05:35.422Z"
gasUsed: sendGreeting 669889
Wait for the message to be synchronized. 28
{
  from_chain: 'MOONBASEALPHA',
  title: 'Greetings',
  content: 'Greeting from MOONBASEALPHA',
  date: '"2022-08-19T17:05:35.422Z"'
}
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node nearToMoonbeam.js --greet
date "2022-08-19T17:08:42.977Z"
Processing transaction...
nonce = 78589014000142 , blockHash = 6AcHFE6sLMBPZDmfoc36MZfZXo4JsLcGD7zguSTbUUBR
Transaction Results:  {
  actions: [ { FunctionCall: [Object] } ],
  hash: '4hpPEEPi2STSYSwEnPLuLbuT5YssujBtMX2pUbqVMgDD',
  nonce: 78589014000142,
  public_key: 'ed25519:Hr61mCNpgBxuCNJNAH82A6fKhsXsSsUB8zp1m2VYTars',
  receiver_id: '99ff32da92227f302056389ce208d77e12f88a6ffd2cee1b238586cc4cc20bd7',
  signature: 'ed25519:3vokCYjcsbUBRzFXZZzjgp8EWZwQUU5nBdrwBUKrwQxVV9iL1VRnFgcrhDk8arWpRLn14KzgiuYsDB2xWHRwocqt',
  signer_id: 'shanks.testnet'
}
--------------------------------------------------------------------------------------------
OPEN LINK BELOW to see transaction in NEAR Explorer!
$https://explorer.testnet.near.org/transactions/4hpPEEPi2STSYSwEnPLuLbuT5YssujBtMX2pUbqVMgDD
--------------------------------------------------------------------------------------------
Wait for the message to be synchronized. 23
Result {
  '0': 'NEARTEST',
  '1': 'Greetings',
  '2': 'Greeting from NEAR',
  '3': '"2022-08-19T17:08:42.977Z"',
  fromChain: 'NEARTEST',
  title: 'Greetings',
  content: 'Greeting from NEAR',
  date: '"2022-08-19T17:08:42.977Z"'
```

I'm assuming in this case, "28" and "23" are the respective message `id`'s. But there is no option to query these:

```
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node moonbeamToNear.js --query 28
error: unknown option '--query'
keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node nearToMoonbeam.js --query 23
error: unknown option '--query'
```
Can you tell me what I am missing regarding the queries and the Avalanche error above? Thanks!

**Comment by xiyu1984** [comment]
> Thanks for your patience @xiyu1984! Wow, this is a very interesting project indeed! I have a few initial questions while working through the [testing guide](https://github.com/dantenetwork/cross-chain-demo/tree/main).
> 
> 1. When I run the first script avalancheToAstar.js I get this error:
> 
> ```
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --greet
> date "2022-08-19T16:03:51.659Z"
> gasUsed: sendGreeting 665819
> /Users/keeganquigley/cross-chain-demo/node_modules/web3-core-helpers/lib/errors.js:28
>         var err = new Error('Returned error: ' + message);
>                   ^
> 
> Error: Returned error: execution reverted
>     at Object.ErrorResponse (/Users/keeganquigley/cross-chain-demo/node_modules/web3-core-helpers/lib/errors.js:28:19)
>     at /Users/keeganquigley/cross-chain-demo/node_modules/web3-core-requestmanager/lib/index.js:302:36
>     at XMLHttpRequest.request.onreadystatechange (/Users/keeganquigley/cross-chain-demo/node_modules/web3-providers-http/lib/index.js:98:13)
>     at XMLHttpRequestEventTarget.dispatchEvent (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
>     at XMLHttpRequest._setReadyState (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
>     at XMLHttpRequest._onHttpResponseEnd (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
>     at IncomingMessage.<anonymous> (/Users/keeganquigley/cross-chain-demo/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
>     at IncomingMessage.emit (node:events:532:35)
>     at endReadableNT (node:internal/streams/readable:1346:12)
>     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   data: '0x'
> }
> ```
> 
> Despite it saying the execution was reverted, the transaction executes successfully on FUJI: https://testnet.snowtrace.io/tx/0xad92b96644a7ba43043bd4527b0411a0147e032dec0e2e844ba16ffd79fdf502
> 
> So I'm not sure what this error is indicating.
> 
> 2. It appears to be working, as when querying the result on Shibuya, I can successfully get the `id` by calling `getReceiveMessageNumber`:
> 
> getreceivedmessagenumber
> 
> And then using the `id` I can see my message!
> 
> getret
> 
> Pretty cool! Though I would suggest flipping the order of instructions around to make it clear that you need the message `id` in order to find the corresponding message.
> 
> 3. Next, I'm able to successfully send a greeting from Shibuya:
> 
> sendgreeting
> 
> And I can see the message `id` successfully increments by 1.
> 
> getsentmessagenumber
> 
> However, when trying to query the received message on FUJI it just waits forever with this message:
> 
> ```
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --query 9   
> Wait for the message to be synchronized. 9
> ^C
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node avalancheToAstar.js --query 10  
> Wait for the message to be synchronized. 10
> ```
> 
> 4. Finally, the rest of the test greetings for Moonbeam and Near work great.
> 
> ```
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node moonbeamToNear.js --greet
> date "2022-08-19T17:05:35.422Z"
> gasUsed: sendGreeting 669889
> Wait for the message to be synchronized. 28
> {
>   from_chain: 'MOONBASEALPHA',
>   title: 'Greetings',
>   content: 'Greeting from MOONBASEALPHA',
>   date: '"2022-08-19T17:05:35.422Z"'
> }
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node nearToMoonbeam.js --greet
> date "2022-08-19T17:08:42.977Z"
> Processing transaction...
> nonce = 78589014000142 , blockHash = 6AcHFE6sLMBPZDmfoc36MZfZXo4JsLcGD7zguSTbUUBR
> Transaction Results:  {
>   actions: [ { FunctionCall: [Object] } ],
>   hash: '4hpPEEPi2STSYSwEnPLuLbuT5YssujBtMX2pUbqVMgDD',
>   nonce: 78589014000142,
>   public_key: 'ed25519:Hr61mCNpgBxuCNJNAH82A6fKhsXsSsUB8zp1m2VYTars',
>   receiver_id: '99ff32da92227f302056389ce208d77e12f88a6ffd2cee1b238586cc4cc20bd7',
>   signature: 'ed25519:3vokCYjcsbUBRzFXZZzjgp8EWZwQUU5nBdrwBUKrwQxVV9iL1VRnFgcrhDk8arWpRLn14KzgiuYsDB2xWHRwocqt',
>   signer_id: 'shanks.testnet'
> }
> --------------------------------------------------------------------------------------------
> OPEN LINK BELOW to see transaction in NEAR Explorer!
> $https://explorer.testnet.near.org/transactions/4hpPEEPi2STSYSwEnPLuLbuT5YssujBtMX2pUbqVMgDD
> --------------------------------------------------------------------------------------------
> Wait for the message to be synchronized. 23
> Result {
>   '0': 'NEARTEST',
>   '1': 'Greetings',
>   '2': 'Greeting from NEAR',
>   '3': '"2022-08-19T17:08:42.977Z"',
>   fromChain: 'NEARTEST',
>   title: 'Greetings',
>   content: 'Greeting from NEAR',
>   date: '"2022-08-19T17:08:42.977Z"'
> ```
> 
> I'm assuming in this case, "28" and "23" are the respective message `id`'s. But there is no option to query these after the fact:
> 
> ```
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node moonbeamToNear.js --query 28
> error: unknown option '--query'
> keeganquigley@Keegans-MacBook-Pro cross-chain-demo % node nearToMoonbeam.js --query 23
> error: unknown option '--query'
> ```
> 
> Can you tell me what I am missing regarding the queries and the Avalanche error above? Thanks!

OK, we will check the error happened on Avalanche Testnet as soon as possible. Maybe there's some unclear points in the test guide, we will check it and make it more clear~

**Comment by keeganquigley** [comment]
Thanks @xiyu1984 for making the changes! All points have been addressed and the scripts work now. I am able to use the sendGreeting method with 4 arguments.

Moving on, most of your contracts test and compile successfully and I'm able to run them on a local substrate node. But I have questions on a few:

1. Running `cargo +nightly test` on the **Algorithms** contract produces an error regarding a generic argument:

```
Compiling algorithm v0.1.0 (/Users/keeganquigley/protocol-stack-for-ink/contracts/algorithm)

error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> lib.rs:399:41
    |
399 |                 let msg_hash = recv_msg.into_hash::<ink_env::hash::Keccak256>();
    |                                         ^^^^^^^^^---------------------------- help: remove these generics
    |                                         |
    |                                         expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters
   --> /Users/keeganquigley/message-ink/payload/message_define.rs:231:12
    |
231 |     pub fn into_hash(&self) -> <ink_env::hash::Sha2x256 as ink_env::hash::HashOutput>::Type {
    |            ^^^^^^^^^

error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> lib.rs:439:41
    |
439 |                 let msg_hash = recv_msg.into_hash::<ink_env::hash::Keccak256>();
    |                                         ^^^^^^^^^---------------------------- help: remove these generics
    |                                         |
    |                                         expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters
   --> /Users/keeganquigley/message-ink/payload/message_define.rs:231:12
    |
231 |     pub fn into_hash(&self) -> <ink_env::hash::Sha2x256 as ink_env::hash::HashOutput>::Type {
    |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0107`.
warning: `algorithm` (lib test) generated 2 warnings
error: could not compile `algorithm` due to 2 previous errors; 2 warnings emitted
```

2. Running the tests on the **Payload** contract, it panics on one test.

```
running 5 tests
test Payload::tests::test_vec_compare ... ok
test Payload::tests::it_works ... ok
test Payload::tests::test_encode_decode ... ok
test Payload::tests::default_works ... ok
test Payload::tests::test_contract_en_de ... FAILED

failures:

---- Payload::tests::test_contract_en_de stdout ----
thread 'Payload::tests::test_contract_en_de' panicked at 'assertion failed: `(left == right)`
  left: `"MessageDetail { name: \"Nika\", age: 37, phones: [\"123\", \"456\"] }\n"`,
 right: `"MessageDetail { name: \"Nika\", age: 37, phones: [\"123\", \"456\"] }\nMessageDetail { name: \"Nika\", age: 37, phones: [\"123\", \"456\"] }\nMessageDetail { name: \"Nika\", age: 37, phones: [\"123\", \"456\"] }\n"`', lib.rs:286:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    Payload::tests::test_contract_en_de

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '--lib'
```
3. The **signatureCrseco** contract is also unable to compile:

```
Compiling signatureCrseco v0.1.0 (/Users/keeganquigley/protocol-stack-for-ink/contracts/signatureCrseco)
error[E0422]: cannot find struct, variant or union type `InkAddressData` in module `payload::message_protocol`
   --> lib.rs:205:59
    |
205 |             let address_here = payload::message_protocol::InkAddressData {
    |                                                           ^^^^^^^^^^^^^^ not found in `payload::message_protocol`

warning: unused imports: `InMsgType`, `MessageItem`, `MessagePayload`, `MsgDetail`
  --> lib.rs:18:38
   |
18 |     use payload::message_protocol::{ MessagePayload, MessageItem, MsgDetail, InMsgType};
   |                                      ^^^^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `IReceivedMessage`, `ISentMessage`
  --> lib.rs:19:35
   |
19 |     use payload::message_define::{ISentMessage, IReceivedMessage};
   |                                   ^^^^^^^^^^^^  ^^^^^^^^^^^^^^^^

warning: unused import: `super::*`
  --> lib.rs:80:13
   |
80 |         use super::*;
   |             ^^^^^^^^

warning: unnecessary parentheses around `if` condition
   --> lib.rs:178:20
    |
178 |                 if (i < 255u8) {
    |                    ^         ^
    |
    = note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
    |
178 -                 if (i < 255u8) {
178 +                 if i < 255u8 {
    |

For more information about this error, try `rustc --explain E0422`.
warning: `signatureCrseco` (lib test) generated 4 warnings
error: could not compile `signatureCrseco` due to previous error; 4 warnings emitted
```
Can you help me find the cause of these errors or give an explanation if they can be ignored?

Also, just a suggestion, you could probably clean up the inline comments a bit by removing the default ink! template comments.

Thanks and looking forward to hearing back!

**Comment by xiyu1984** [comment]
Thanks @keeganquigley for your patience, these errors are mainly because we are continuing developing and we have not cleaned up some of the deprecated code. I will do this to make it more clearly and provide a detailed explanation of these.~

**Comment by keeganquigley** [comment]
Awesome, thanks @xiyu1984 for addressing these issues, I figured that might be the case! These contracts now successfully test and build when using the `crypto-dev` branch for `message-ink`. 

I'm finalizing my eval [here](https://github.com/keeganquigley/Grant-Milestone-Delivery/blob/master/evaluations/dantenetwork_1_keeganquigley.md), where you can see my notes. Are you able to fix the 404 error on the [GPLv3](https://github.com/dantenetwork/protocol-stack-for-ink/blob/feature-evaluation/LICENSE) license link? That will be needed to accept the submission. Thanks!

**Comment by xiyu1984** [comment]
> Awesome, thanks @xiyu1984 for addressing these issues, I figured that might be the case! These contracts now successfully test and build when using the `crypto-dev` branch for `message-ink`.
> 
> I'm finalizing my eval [here](https://github.com/keeganquigley/Grant-Milestone-Delivery/blob/master/evaluations/dantenetwork_1_keeganquigley.md), where you can see my notes. Are you able to fix the 404 error on the [GPLv3](https://github.com/dantenetwork/protocol-stack-for-ink/blob/feature-evaluation/LICENSE) license link? That will be needed to accept the submission. Thanks!

Thank you very much @keeganquigley,  
We have fixed the 404 error on the [GPLv3](https://github.com/dantenetwork/protocol-stack-for-ink/blob/feature-evaluation/LICENSE) license link.  

Thanks for your advice on https://contracts-ui.substrate.io/, we will try it in our future development and testing work. It looks very nice and convenient for our future work. 

 Lastly, the suggestion of `cargo +nightly clippy -- -A clippy::let_unit_value` is indeed useful, and we will use it to improve our code as soon as possible. It will help a lot in our future code.

Have a nice day!

**Comment by keeganquigley** [comment]
Thanks @xiyu1984 you're welcome! Glad those resources will come in handy for you, and I'm happy to pass this milestone. I have finalized my eval and submitted the pull request. Thanks again for your patience during this process!

**Comment by lucasvanmol** [comment]
Thank you for the evaluation @keeganquigley!

@xiyu1984: I've forwarded your invoice to the finances team for payment.

**Comment by meldien** [comment]
Hi @xiyu1984, I noted our billing address is not complete and your payment information is missing at the invoice. Could you please update the invoice with following information:

Web 3.0 Technologies Foundation
Baarerstrasse 14
6300 Zug
Switzerland 

And your payment address

Many thanks.

**Comment by xiyu1984** [comment]
Hey meldien,
I have sent the new invoice to Federica Dubbini with my gmail as I received an email about this same problem first there. I will forward that email to you later.
Anyway, I will attach the new invoice in this reply.


Thanks for your patience,
Best regards


Xiyu
Dante Network










在 2022-09-01 17:37:41，"meldien" ***@***.***> 写道：

Hi @xiyu1984, I noted our billing address is not complete and your payment information is missing at the invoice. Could you please update the invoice with following information:

Web 3.0 Technologies Foundation
Baarerstrasse 14
6300 Zug
Switzerland

And your payment address

Many thanks.

**Comment by RouvenP** [comment]
hi @xiyu1984 we transferred the payment today.

**Comment by xiyu1984** [comment]
> hi @xiyu1984 we transferred the payment today.

Thanks a lot, and we have received~

**Pull request merged**
