### PR TITLE
NewOmega M1

### PR DESCRIPTION
**Pull request by celrisen**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [X] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [X] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @celrisen, thanks for the delivery. Could you please update the doc to list the deliverables as outlined in the application?

**Comment by celrisen** [comment]
@semuelle Thanks for the quick response. Updated as per your request.

**Comment by semuelle** [comment]
Are you keeping the project secret, or is there another reason the article is so abstracted away from the application? While I appreciate a developer's view of writing `ink!` contracts, I would have expected a more concrete description of the project itself.

**Comment by celrisen** [comment]
Fair enough, @semuelle, I suppose I was waiting with a more specific article for an end-to-end functional version (Milestone 2), but I see your point and I'm happy to produce one now. I'll update the PR shortly.

**Comment by semuelle** [comment]
I haven't reviewed the other deliverables yet, but I think that's fair. It makes more sense to have a technical deliverable in the beginning and a user-oriented publication when it's usable. Maybe you can update this article after Milestone 2 to reference that second article instead.

**Comment by celrisen** [comment]
I liked your point @semuelle about something a bit more descriptive being out there already, so I went ahead and published what I think could be a nice solution. PR updated.

**Comment by semuelle** [comment]
Hey @celrisen, which rust toolchain version do you use to run the tests?

**Comment by celrisen** [comment]
> Hey @celrisen, which rust toolchain version do you use to run the tests?

Hey @semuelle, I've used the ```nightly-2020-12-29-x86_64-apple-darwin``` toolchain.

**Comment by semuelle** [comment]
It's failing for me, have you come across this?

```sh
nightly-2020-12-29-x86_64-unknown-linux-gnu (directory override for 'newomega/newomega.polkadot/newomega_delegator')
rustc 1.51.0-nightly (2987785df 2020-12-28)
```

```sh
   Compiling newomega v1.0.0 (/home/sebastian/work/w3f/code/open-grants/deliverables/newomega/newomega.polkadot/newomega_delegator/newomega)
error[E0277]: the trait bound `NewOmega: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> newomega/newomega.rs:15:5
   |
15 |     pub struct NewOmega {}
   |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `NewOmega`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:56
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `NewOmega`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `NewOmega: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> newomega/newomega.rs:15:5
   |
15 |     pub struct NewOmega {}
   |     ^^^^^^^^^^^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `NewOmega`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:40
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `NewOmega`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `FightResult: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> newomega/newomega.rs:70:58
   |
70 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `FightResult`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:56
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `FightResult`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `FightResult: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> newomega/newomega.rs:70:58
   |
70 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `FightResult`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:40
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `FightResult`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Ship: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> newomega/newomega.rs:49:58
   |
49 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout, Copy, Clone)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `Ship`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:56
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `Ship`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Ship: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> newomega/newomega.rs:49:58
   |
49 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout, Copy, Clone)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `Ship`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:40
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `Ship`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Move: parity_scale_codec::codec::WrapperTypeDecode` is not satisfied
  --> newomega/newomega.rs:29:58
   |
29 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout, Copy, Clone)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeDecode` is not implemented for `Move`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:56
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Decode` for `Move`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `Move: parity_scale_codec::codec::WrapperTypeEncode` is not satisfied
  --> newomega/newomega.rs:29:58
   |
29 |     #[derive(scale::Encode, scale::Decode, SpreadLayout, PackedLayout, Copy, Clone)]
   |                                                          ^^^^^^^^^^^^ the trait `parity_scale_codec::codec::WrapperTypeEncode` is not implemented for `Move`
   | 
  ::: /home/sebastian/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:40
   |
19 | pub trait PackedLayout: SpreadLayout + scale::Encode + scale::Decode {
   |                                        ------------- required by this bound in `PackedLayout`
   |
   = note: required because of the requirements on the impl of `parity_scale_codec::codec::Encode` for `Move`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 8 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `newomega`
```

**Comment by celrisen** [comment]
```cargo +nightly test``` from newomega/

```
    Finished test [unoptimized + debuginfo] target(s) in 3.45s
     Running /Users/celrisen/projects/newomega-substrate/newomega_delegator/target/debug/deps/newomega-4ad796c5b234260b

running 3 tests
test newomega::tests::test_damage_calculation ... ok
test newomega::tests::test_isdead ... ok
test newomega::tests::test_fight_end_to_end ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Are you running ```cargo +nightly test``` from inside the directories with tests?

**Comment by celrisen** [comment]
@semuelle Managed to reproduce by updating all my crates, and now I get the error. I guess something must've changed in the ink crates (though it's slightly surprising since all the crate versions are locked in the .toml's). I'll investigate and get back to you.

**Comment by semuelle** [comment]
Thanks. Could you also add a license to the repo, please?

**Comment by celrisen** [comment]
> Thanks. Could you also add a license to the repo, please?

@semuelle 

Ok so several findings, it's definitely due to the RC3 version of ink crates being used (they were not available 2 weeks ago I believe). You can see the RC3 version being wired up here during build:

```/Users/celrisen/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_storage-3.0.0-rc3/src/traits/packed.rs:19:56```

Which is slightly strange considering that the .toml's lock the version at RC2.

However, I discovered the RC3 is only used when executing
```
cargo +nightly contract build --manifest-path newomega/Cargo.toml
```

and it works fine when executing
```
cargo +nightly build --manifest-path newomega/Cargo.toml
```
(without the ```contract``` parameter).

So if you adjust the ```build.sh``` to remove the ```contract```, you should be able to build the entire thing using RC2 of the Ink crates, and run the tests (it worked for me just now). There is probably an explanation as to the "why", but I have to say it eludes me at this point.

As for getting RC3 to work, is there by any chance some changelog published I could look at to see the breaking changes?

Sorry for the troubles, but hey, bleeding edge development right? :)

**Comment by semuelle** [comment]
Here are some notes on the rc3 release: https://github.com/paritytech/ink/releases/tag/v3.0.0-rc3

As for the compilation, `cargo --nightly build` is what I have been doing. I'll try and see if I can downgrade to ink 3 rc2.

**Comment by celrisen** [comment]
Ok got it to compile again, by upgrading my environment to the latest and greatest. 
Currently my "Optimizing wasm file" step fails, which I'm investigating, but maybe it will help you already.

I've had to (and you will have to):
1. Update toolchain to ```2021-02-25``` nightly.
2. Update cargo-contract
- via: ```cargo install --force cargo-contract```
- reason: https://github.com/paritytech/ink/blob/master/RELEASES.md

And for whomever it might help,
3. Bump crate versions (commited to the repo)
- Ink crates, to 3.0.0-rc3 (reason: because they were being forced anyway)
- parity-scale-codec to 2.0.1 (reason: https://github.com/paritytech/parity-scale-codec/pull/254, which I believe is the fix for the error we were getting)
- scale-info to 0.6.0

**Comment by celrisen** [comment]
And finally final, I've fixed my wasm generation problem, by installing ```wasm-opt``` via ```binaryen``` (not npm, which didnt work). Now my ```build.sh``` script works and generates all the contracts correctly. Not sure why I had to do this manually, perhaps worth passing to an appropriate team to investigate.

```brew install binaryen```
(https://github.com/WebAssembly/binaryen)

@semuelle 
Let me know if the setup works for you now.
Also make sure to pull the repo again, as I've had to make some adjustments, as described in previous comment; as well as run the build via the ```build.sh``` (I believe this is important in such setup, to build the contracts in order from the delegator contract level, not individually. The tests however, are to be executed individually.).

To add even more spice to the whole experience, I sometimes get
```
ERROR: `"/Users/celrisen/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo" "run" "--package" "metadata-gen" "--manifest-path=/var/folders/5m/qltwmc4s0tg2ztgx8zhvz8s80000gn/T/cargo-contract_PlH3HT/newomegastorage/Cargo.toml" "--target-dir=/Users/celrisen/projects/newomega-substrate/newomega_delegator/target/ink/newomegastorage" "--release"` failed with exit code: None
```
randomly during the build. If that happens, just run the build again, and it will pick up where it left off, and work (doesnt seem like I can do anything about that).

**Comment by semuelle** [comment]
thanks for the quick fix. Looking good so far.

I believe there is a test that's outdated in `newomegastorage`:

```
error[E0308]: mismatched types
   --> newomegastorage/newomegastorage.rs:170:48
    |
170 |             let leaderboard: Vec<PlayerData> = contract.get_leaderboard();
    |                              ---------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `newomegastorage::PlayerData`, found tuple
    |                              |
    |                              expected due to this
    |
    = note: expected struct `std::vec::Vec<newomegastorage::PlayerData>`
               found struct `std::vec::Vec<(ink_env::AccountId, newomegastorage::PlayerData)>`
```

**Comment by celrisen** [comment]
> thanks for the quick fix. Looking good so far.
> 
> I believe there is a test that's outdated in `newomegastorage`:
> 
> ```
> error[E0308]: mismatched types
>    --> newomegastorage/newomegastorage.rs:170:48
>     |
> 170 |             let leaderboard: Vec<PlayerData> = contract.get_leaderboard();
>     |                              ---------------   ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `newomegastorage::PlayerData`, found tuple
>     |                              |
>     |                              expected due to this
>     |
>     = note: expected struct `std::vec::Vec<newomegastorage::PlayerData>`
>                found struct `std::vec::Vec<(ink_env::AccountId, newomegastorage::PlayerData)>`
> ```

Good spot, fixed.

**Comment by semuelle** [comment]
Hi @celrisen, I have been able to compile and test. Overall, pretty cool stuff. Only one issue: we like to see inline documentation, as reflected in the grant application. I didn't find any. If you could fix that, I'd be happy to call this one done. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/9b759d321a3d525aa37acfb87bfc996d141e4fcc/evaluations/newomega_1_semuelle.md).

**Comment by celrisen** [comment]
Thanks @semuelle, I've added the inline documentation to all the contracts now.

**Comment by semuelle** [comment]
Thanks for following up on the documentation. I have updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/a5ae987d04aa15503a8fd585594624512e7bbe6a/evaluations/newomega_1_semuelle.md) and your milestone is hereby accepted. :tada: 

I will forward your invoice for processing. 

I also want to commend you for the speedy and thorough responses to my requests and suggestions.

**Pull request merged**
