### PR TITLE
Polkadot.js NoCode Plugin-Milestone 1

### PR DESCRIPTION
**Pull request by inartin**
Milestone 1

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/745

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by cruikshankss** [comment]
Good day @inartin! I have a small bookkeeping note as I'm working on your milestone review. I noticed on the milestone delivery, you indicate MIT license. But on [your web page](https://polkadot.js.org/docs/), in the Intro > Overview, it says: “All code is made available on Github with a permissive Apache-2.0 license.” 

I'm planning on completing the milestone evaluation as soon as possible. Thanks.

**Comment by takahser** [comment]
Hi @inartin 
First of all, thanks for your delivery.
I'd like to raise the following two points:

1. I played around with the demo and realised that the ["verify signature" feature](https://polkadotjs.bubbleapps.io/version-test/verify_signature) doesn't work. To create the signature I used the ["Sign a message" demo](https://polkadotjs.bubbleapps.io/version-test/simple_connect). However, I noticed the message to be signed contains a break while the message field in the "verify signature" form isn't multiline, plus it's disabled. After removing the `disabled` attribute from the `<textarea>` element I was able to edit the message and signed a single-line message which I was able to verify successfully. Pls consider making that change in your codebase to fix this issue and to add flexibility when using the sign feature.
2. I opened an account on [bubble.io](bubble.io) to test the plugin. I was able to add some simple actions (e.g. forwarding to a different page on a button click event) however, so far I didn't figure out how to add any action related to the polkadot.js plugin. I already installed the plugin into my project:
    
image

Can you guide me through the process of adding a polkadot.js related action here?

**Comment by inartin** [comment]
> But on [your web page](https://polkadot.js.org/docs/)

Hi,
Perhaps the link you have indicated is wrong, but it is not my page, it is the official Polkadot documentation page, or maybe I misunderstood something in your question?





> I'd like to raise the following two points:

1. Thank you! I made the multiline input enabled and replaced the input with multiline input on the verify page. 

2. After installing the plugin, follow these steps from plugin [documentation](https://polkadotjs.docs.ezcodeplugins.com/installation) 
When you install the plugin, the plugin element will appear in Visual elements in the app editor, find the Polkadot Wallet and Polkadot Utils, and drag and drop them on the page.

**Comment by cruikshankss** [comment]
@inartin Thanks for the clarification. This is my first attempt at helping with an eval and I've had to spend a bit of time understanding the tech stack. I was unclear if you contribute to the Polkadot{.js} codebase or are a separate entity using their APIs, but now I believe I understand you're using the Polkadot{.js} APIs. 

You mentioned in [this comment](https://github.com/w3f/Grants-Program/pull/745#issuecomment-996786991), "After deployment it is open source, and all code is visible in the Bubble plugin editor". It's my first time reviewing code in the Bubble plugin editor rather than on GitHub, so thanks for your patience with me. 

In the [W3F Grants Milestone Delivery Documentation section](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md#documentation), it's required to document API calls, architecture overview, and individual component details. I don't intend to slow down your delivery, but would really appreciate a more detailed documentation of your tech stack & dependencies since there's no GitHub. I hope this comment serves as a helpful note. :)

In your [Grant Proposal Milestone 1 section](https://github.com/w3f/Grants-Program/blob/master/applications/polkadotjs_no_code.md#milestone-1-implement-extension-utilities), you indicate you intend to provide these two items:

> A documentation page that will explain the plugin element fields, what they mean, what parameters are needed, and how to use the element actions (For example, action to connect the wallet or to Sign a message)

> Since No-Code doesn't have any type of testing, we will provide demo pages that will cover 100% of all plugin features that can be tested directly on the page with a description in the documentation

I see your [documentation is here](https://polkadotjs.docs.ezcodeplugins.com/) and you do explain element fields, element actions, params, etc. I know your intention is to provide access to Polkadot to non-developers, so ideally your documentation would be more friendly to non-devs. I think your project is really exciting and only hoping to assist you with providing access to the NoCode community. Thank you for your work!

**Comment by inartin** [comment]
> it's required to document API calls, architecture overview, and individual component details. I don't intend to slow down your delivery but would really appreciate more detailed documentation of your tech stack & dependencies since there's no GitHub.

Each action (plugin function) has a separate demo page, we mentioned in the testing guide of the milestone that the demo pages will cover 100% of the plugin functionality since there's no other way to test it.
All demo pages are open-sourced, when opening the app editor, you can see the workflows, and how the plugin was implemented. 

I know that you may not quite understand how Bubble works so you don't see where and how the plugin works, so here's an example of the implementation of the Sign a message function in a [video](https://youtu.be/2zSGtHic36A). I run a step by step (think of running a code with debug mode)

I hope it will clarify it a bit. 

> so ideally your documentation would be more friendly to non-devs

I don't quite understand this. The documentation was written in a way that anyone with a basic understanding of Bubble itself will understand the documentation and how to implement the plugin in their app. 
The main complicated part of initializing the plugin was written on a separate page "installation"
The same way was written the [Rarible SDK documentation](https://rarible.docs.ezcodeplugins.com/) for example. The plugin has over 700 installs so far:) with good reviews. 
And if a user doesn’t understand something, there's always the forum thread where we will provide support (as we do with the Rarible)

P.S.
The plugin is actually available on GitHub, but it is used only as a backup of the code. See [here](https://github.com/ezcodeco/Bubble-Plugin-Polkadot.js).

**Comment by cruikshankss** [comment]
@inartin Thank you so much for explaining and responding so quickly. Excited to demo it.

**Comment by cruikshankss** [comment]
@inartin I had a look through all your crypto-related plugins on Bubble so I could understand a bit better what the goal of your Polkadot.js NoCode plugin is. They seem really cool. I'm glad to see so many tutorials, demos and videos.

I made a Bubble account and followed the first two general tutorials so I understand what 'elements' and 'actions' are now. I'm planning to continue my evaluation on Monday. It's been a steep learning curve for me to understand this tech stack, so thanks again for your patience with me.

**Comment by Noc2** [comment]
Thanks a lot for the update @cruikshankss and the external evaluation! It looks really good. Feel free to create a PR to our repo.

**Comment by takahser** [comment]
> here's an example of the implementation of the Sign a message function in a [video](https://youtu.be/2zSGtHic36A).

Thanks for the helpful [explanations](https://github.com/w3f/Grant-Milestone-Delivery/pull/343#issuecomment-1018531887) and the quoted video @inartin.
I tried again and was able to execute the `load app` action on a button click event which opened a polkadot.js dialog for connecting the page to the extension. 👍

However, when trying the same using the more complex `Sign a message` action which requires an input nothing happens.
This is how my Design and Workflow look like.

**Design**
image

**Workflow**
image

After filling the `MessageToSign` input and clicking the `Sign Message` button, nothing happens. However, I'd expect the polkadot.js to open a popup where it asks me to sign the message. Also, I'd like to know how I can use the `PolkadotWallet A Message Signed` workflow to do something with the signed message, as soon as it's called. Could you walk me through the process of correctly implementing these 2 workflows as currently it doesn't seem to work with my current configuration?

**Comment by inartin** [comment]
> Could you walk me through the process of correctly implementing these 2 workflows as currently it doesn't seem to work with my current configuration?

@takahser sure!

1) The sign issue. I assume that you have tested the Load App on one page, and the sign on the other. Make sure you have loaded the app first and then you can do any other action like the sign one. 

2) `PolkadotWallet A Message Signed` Is an event, this event will trigger when the signature is signed successfully, to see it in action, add a popup on your page (search for popup in elements), then in the event Message Signed, add a new action -> `Show an element` and select the popup that you have added. 
Here's where to find show element:
Screenshot 2022-01-24 at 18 44 15

**Comment by inartin** [comment]
Hey @cruikshankss thanks for the amazing review. 
I was unsure about the Forum Post because I wanted to see the first reviews here first, but now you convinced me that it is the right time to post it. So, I will do it today and inform you once it is done, thanks again.

**Comment by inartin** [comment]
@cruikshankss Done! https://forum.bubble.io/t/plugin-polkadot-js-by-ezcode/187940

About the testing guide, I'm thinking it will be easier if I will create a video tutorial on how to create a basic app similar to the demo app, and show how to implement the plugin features, what do you say?

**Comment by cruikshankss** [comment]
@inartin I just realized I should've suggested perhaps you give us the draft of your forum post so you can adhere to the grant announcement guidelines. That's my bad for giving you an ambiguous +1 on your previous comment.  

A video does sound great because the forum post doesn't seem to be a step-by-step guide. It's your choice on how to do a Testing Guide, either post or video, as long as it meets the guidelines. Here's [more info](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md#a-step-by-step-guide-demonstrating-how-your-code-achieves-the-milestones):

> Please provide documentation on how to install, compile, run and test the deliverable(s). Make sure to include all necessary prerequisites. Common issues while replicating test results involve, among others, undocumented dependencies, version numbers, local database setups, breaking changes in the main branch since delivery, OS- and browser-specific incompatibilities.

> Depending on the deliverable, this could include (but is not limited to)

> - how to embed your library in another application,
> - how to make example API calls to your service,
> - running your web app, and
> - steps to complete some desired action in your mobile app.

**Comment by inartin** [comment]
@cruikshankss 
> adhere to the grant announcement guidelines

I have edited the post, I will not mention in the forum thread about the web3 foundation until the first milestone acceptance.

> A video does sound great because the forum post doesn't seem to be a step-by-step guide.

Yes, the forum isn’t meant to show a step-by-step, it is for contacting the users and providing support. 
I will do the video and post it here then.


> * steps to complete some desired action in your mobile app.

What do you mean by this? To show in the video how the Bubble app works in a mobile app?

**Comment by cruikshankss** [comment]
> I have edited the post

Sounds great!

> Yes, the forum isn’t meant to show a step-by-step, it is for contacting the users and providing support.

Sorry I misunderstood about the purpose of the forum post. Makes sense now, thanks.

> I will do the video and post it here then.

Looking forward to it!

> - steps to complete some desired action in your mobile app.

I was simply copying in the guidelines, but those bullets are "depending on the deliverable". That's just an example. Really what we're seeking from you is some step-by-step guide on how to essentially recreate your live demo app. It seems to work well and I'd love to follow along a video and create one of my own in Bubble! The Bubble desktop app is perfect. A mobile app is not applicable in this case.

**Comment by Noc2** [comment]
Fyi: I just merged and updated the milestone evaluation by @cruikshankss: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadotjs-nocode-plugin_1_cruikshankss.md Thanks again for your evaluation! However, I will wait for @takahser to finish his milestone evaluation, before I merge the PR.

**Comment by takahser** [comment]
@inartin thanks again for your helpful instructions. I'm also very looking forward to the video tutorial since it was a bit tricky to get started for me although I got a lot of help from your side which I appreciate. However, new users are likely not going to get that level of support. :)

> * The sign issue. I assume that you have tested the Load App on one page, and the sign on the other. Make sure you have loaded the app first and then you can do any other action like the sign one.

Unfortunately I was using the same app. I even reinstalled the polkadot.js browser extension to make sure to have no potentially weird caching issues and to make the connection dialog appear in the same session as where I call the sign function. That didn't change anything though.
I also realized that there is a console error when clicking the sign button/calling the sign action:
image
I also made sure that the message input has some text content (i.e. there is something to sign).
What else could be the issue here?

**Comment by inartin** [comment]
> However, new users are likely not going to get that level of support. :)

That's why we have the forum thread, helping users there so the new users can go through old posts and find solutions to similar issues (just like github hah)

> I added a new `Create Mnemonic` action and replicated the steps taken for the `Sign a message` action. Here there is no console error when calling the action and the popup appears but it's empty.

Did I understand correctly that the error no more appears for you? Because I can’t reproduce this error.
Also, the popup is empty because you didn’t set anything in there :D But it is not related to the plugin itself, if it appears then it proves that the plugin works, all steps after that are up to the developer what to populate in the popup, etc.

Also, making a full tutorial basically means I should teach the users how to use Bubble itself, I don’t quite see the point in doing it, there's already plenty of basic intro into Bubble. 
When installing a plugin, a user already knows the basics. 
A new potential user will learn how to work with Bubble first, and then try to implement any plugins, not the opposite. 
For example, let's say Javascript, you don't try to use a new library without knowing how the javascript works and trying to learn how js works from that library, isn't it true?

But I will definitely look into ways to improve the documentation of course.

**Comment by inartin** [comment]
@takahser I have fixed the error you mentioned. 
Update the plugin to 1.01 (Go to the Plugins tab, select the plugin, see the section "Currently installed version")

**Comment by takahser** [comment]
@inartin Thanks a lot for the quick fix, I retested on v1.01 and confirm that the error doesn't occur anymore.

> When installing a plugin, a user already knows the basics.

True, that makes sense as well to me. Maybe for the next milestone it would be good, if you could provide some basic instructions on how to test your delivery. This'd safe us time when testing since we don't have to do a whole tutorial first.:)
I'll go ahead and merge the delivery, thx again and good job! 👍

**Comment by fededubbi** [comment]
Good afternoon, I noticed that the invoice is missing of your address and also our address is missing.
Please note that our new address is:

Baarerstrasse 14
6300 Zug
Switzerland

Can you please send us the updated invoices to the following address: invoices@web3.foundation?

Many thanks,
Federica Dubbini

**Comment by inartin** [comment]
> Good afternoon, I noticed that the invoice is missing of your address and also our address is missing. Please note that our new address is:
> 
> Baarerstrasse 14 6300 Zug Switzerland
> 
> Can you please send us the updated invoices to the following address: [invoices@web3.foundation](mailto:invoices@web3.foundation)?
> 
> Many thanks, Federica Dubbini

@fededubbi Done!

**Comment by RouvenP** [comment]
hi @inartin we transferred the payment today.

**Comment by inartin** [comment]
> hi @inartin we transferred the payment today.

@RouvenP  Received, thank you!

**Pull request merged**
