### PR TITLE
Create RainbowDAO-Protocol-ink!-Phase1-milestone-2.md

### PR DESCRIPTION
**Pull request by RainbowcityKun**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/680

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @RainbowcityKun. We'll look into it as soon as possible.

**Comment by takahser** [comment]
@RainbowcityKun just FYI, I was not able to get started with the evaluation for your delivery yet. Apologies for the delay and thanks for your patience. I'm planning to take a look at it next week.

**Comment by RainbowcityKun** [comment]
> just FYI, I was not able to get started with the evaluation for your delivery yet. Apologies for the delay and thanks for your patience. I'm planning to take a look at it next week.

@takahser Okay, it's okay, we'll be patient. If you have any questions during the evaluation process, please leave us a message and we will solve it as soon as possible. Thanks again for your hard work!

**Comment by semuelle** [comment]
Hey @RainbowcityKun. Sorry for the long wait. I am now reviewing your milestone.

Could you add instructions on how to compile and run the UI? Also, I am unable to compile any of the packages in the ink repo. They all fail with the following error. Could you check if the `main` branch is compiling for you and that all dependencies are listed?

```sh
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
   --> /home/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.9.8/src/atomic.rs:314:6
    |
314 | impl<T: ?Sized + Pointable> Atomic<T> {
    |      ^
...
346 |     pub const fn null() -> Atomic<T> {
    |     -------------------------------- function declared as const here
    |
    = note: see issue #93706 <https://github.com/rust-lang/rust/issues/93706> for more information
    = help: add `#![feature(const_fn_trait_bound)]` to the crate attributes to enable
```

**Comment by RainbowcityKun** [comment]
Hi, @semuelle  , it doesn't matter, we will always wait patiently and deal with it, and thank you for your hard work.

Now the front-end UI documentation has been updated,

https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/README.md

We have not encountered the other problems you mentioned, and we are trying to find a way to investigate and solve them. We'll update here as soon as it's done.

If you find other problems in the follow-up, please leave a message at any time, and we will deal with it as soon as possible.

Thanks again for your hard work!

**Comment by RainbowcityKun** [comment]
Hi, @semuelle ,  we are currently compiling correctly locally. We just updated the code again, you can wait to see if it compiles successfully. If there is still a problem, we will check the error message again.

**Comment by semuelle** [comment]
Quick update: I was able to compile on a different machine. I haven't found the reason yet, but either way I will continue evaluation today.

**Comment by semuelle** [comment]
@RainbowcityKun, I cannot match the contracts and the entries in the `abiMap` mentioned in the setup instructions, so I don't know which addresses to put where. Can you clarify this?

**Comment by RainbowcityKun** [comment]
Okay, @semuelle   sorry we didn't explain this very clearly, now we've updated the documentation, check it out again,

https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/docs/README.md

//Configuration required to run this site (https://www.rainbowdao.io/daoManage) config:
//address ink => src/api/connectContract.js
dao_factory => dao_factory
//contractHash ink=> utils/contractHash.json
erc20 => erc20_code_hash
dao_proposal => dao_proposal
dao_setting => dao_setting
dao_users => dao_user
dao_vault => dao_vault
dao_manager => dao_manage

If you find any new problems, please feel free to leave us a message.

**Comment by semuelle** [comment]
I have added/changed the addresses in the `abiMap` I could match, but there are some that don't match any contracts (`core`, `incomeManage`, etc.). In the `contractHash.json` file, there are also some entries that I couldn't match to any contract (`multisig_hash`, `dao_hash`). Can I ignore those?

**Comment by RainbowcityKun** [comment]
> I have added/changed the addresses in the `abiMap` I could match, but there are some that don't match any contracts (`core`, `incomeManage`, etc.). In the `contractHash.json` file, there are also some entries that I couldn't match to any contract (`multisig_hash`, `dao_hash`). Can I ignore those?

Core, incomeManage, etc. are all contracts that belong to the first milestone, and you can choose to ignore them here.

We are very happy to see ink! 3.0 has been released, and we will consider rewriting all contracts based on ink! 3.0 in the future.

**Comment by semuelle** [comment]
Hey @RainbowcityKun, thanks for the info. Unfortunately, I am still unable to test anything manually. 

When I use rainbowdao.io, I get a `Uncaught (in promise) ReferenceError: eventBus is not defined` when trying to mint a token and `TypeError: a is undefined` in the console and a `Not enough gas` popup. I can't tell what network this is connected to, though, so I don't know how to check my balance.

When I run a `substrate-contracts-node` and the UI locally, I get `Error: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low` when I try to transact as `Alice` and the `a is undefined` error else. Also, the page doesn't seem to recognize which account I logged in as. The screenshot below shows that I am logged in as `5Grwva...`, but the suggested transaction is from `5DHyoa...`.

Screenshot from 2022-03-21 14-38-09

**Comment by RainbowcityKun** [comment]
Hi, @semuelle  , I'm very sorry, because our work has not been detailed enough to cause trouble to your test, we are now telling you the detailed steps:

1. https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/docs/README.md

First of all, this is our documentation, and some steps have been included in the documentation. Your problem may be caused by no balance in the current account. You can get fees by switching nodes.

2. Detailed operation:

Switch nodes to ws://127.0.0.1:9944 or wss://pot.rainbow.kim at https://polkadot.js.org/apps/#/explorer, 
https://polkadot.js.org/apps/#/accounts , 
 Send the fees to the wallet test account.

3. For better convenience of testing, we have added a new tutorial document today, you can also refer to this step.

https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/docs/RainbowDAO_DAOFactory_Ink_Introduce.md

4. If you encounter other problems during the test, please feel free to contact us. Thanks again for your hard work, it's your testing that makes our development even better. 

We also found many problems in the process of developing the first version of the RainbowDAO protocol, and we will refactor all the logic in the future. We will re-develop the second version of the product on the basis of ink!3.0. Our development team has also grown a lot during this development process.

Thanks again for your hard work!

**Comment by semuelle** [comment]
Hi @RainbowcityKun, thank you for the updates. I am now able to initialize a DAO and basic and token settings. However, when I press `Create`, I get a `ContractTrapped` error (this is on rainbowdao.io). Any idea why this might be? Here's my input:

DAO Name
`MyTestDAO`
DAO Logo
`https://i.redd.it/57fpfzfeth781.png`
DAO Introduction
`Testitest`
Token Name
`S3btoken`
Token Symbol
`S3B`
Token Decimals
`10`
Token Total Supply
`1000000000000`


I will continue tests locally in the meantime.

PS.: the "Create DAO" page states "The creation will cost approximately ＜ 0.1 **Eth**".

**Comment by RainbowcityKun** [comment]
Hi @semuelle   , thanks for your patience and helping us keep finding issues.

The problem is caused by your insufficient reserve fund in the contract. 

 New reserved fund in contracts prompt has been added in the UI.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @RainbowcityKun, thanks for the update. I was now able to follow the instructions in the doc you linked above. Unfortunately, there are still a large number of issues with both the code and the UI. I cannot accept the milestone in this state, especially since this is the last milestone in your grant. Please have a look at the list of issues below. They are roughly sorted by importance, but this list is also not complete, so I would kindly ask you to go through both code and UI, check for edge cases and verify that everything behaves sensibly, not just when following the "happy path". We don't expect a fully fleshed out product at the end of a grant, but the code should be functional and thoroughly tested. 

- Your proposal states that "Core functions will be fully covered by unit tests". However, every contract contains only a single test. That is hardly "fully covered".
- Generally, there is little input validation is done on both frontend and contracts. For example:
  - I was able to join my own DAO, even though I was already a member. I think this should be caught on both the front end and the contract.
  - I was also able to create a token with zero initial balance. Given that there currently is no minting function, that makes no sense to me to be possible. 
  - The proposal category input field allows any positive number.
  - After clicking `Create alliance`, I am taken to the DAO creation screen (?). After creating a DAO there, I can no longer open my original DAOs page. After clicking the DAO I get `Uncaught (in promise) Error: Expected 1 arguments to contract message 'get_childs_daos', found 0`. Perhaps this is related to the values I entered when it asked me about the DAO details. For example, I put an initial balance of zero and put special characters into the DAO name. The notification did say that the DAO creation was successful, though.
- There are a lot of string input fields on your frontend where I wasn't able to tell what values are allowed or expected. For example, in your screenshot [here](https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/PIC/CreateDao/4-Create-Alliance.png), you wrote "One coin, one vote". But as a user, how do I know that I can enter that, or any other value?
- Conversely, when voting or delegating on a proposal, I cannot enter my an amount or where to delegate it to. The first vote removed 2000 units from `My votes`, the second zero. 
- The displayed value seems to not take the token decimals into account, because it now shows `1999999998000`.
- What is the use of `expire_time` in the `dao_users` contract? It doesn't seem to be used anywhere.
- What are the `conditions` reference in `dao_users` and `dao_setting`, and what do the values (2, 4, 6, etc.) refer to? I couldn't find documentation on these.
- The `My votes` number updates when I vote or delegate on a proposal, but it doesn't show on the `Support` or `Refuse` displays.
- When I refresh a page, it loses track of what DAO, department or proposal I was looking at and shows the page with all data removed or set to zero.
- When I click on `MineDao` and then on my DAO, I should be taken to that DAO's page. Instead I'm back on `daoManage`.
- All transaction notifications pop up twice.
- When I support a proposal, the transaction notification is empty.
- The balance shown on a department I created is "5000000 RBD". Are those minted on the spot, or assigned from somewhere? And why 5 million?
- This might be a language issues, but what are `mother` and `union` DAOs?

This is all on rainbowdao.io, by the way. Let me know if you have any further questions.

**Comment by RainbowcityKun** [comment]
Okay, @semuelle   thanks for your rigorous testing that made us realize there are so many problems, and I'm really, really sorry. I would ask the development team to do a complete re-review of all the code and UI. We will definitely come up with a fully tested product eventually.

**Comment by RainbowcityKun** [comment]
Hello, @semuelle  , I have asked our technical staff to review the contract and front-end code again. We mainly made the following updates, please review the following:

- Front end
1. Added the verification of joining Dao and joining department to prevent repeated joining.
2. Information verification is added to generate Dao, and governance tokens with quantity of 0 are not allowed to be generated; Information verification is also added to the generated proposal.
3. For the proposal voting problem, the proxy input address pop-up window is added, but at present, the proxy is to entrust all votes at one time, and the function of entrusting the specific number of votes has not been added.
4. Unified treatment has been made for the problem of controlling the accuracy of tokens.
5. Added Dao holding, and updated the current proposal information after voting.
6. For the display error of Department funds, we updated the Department information page and corrected the mismatch between the display information and the contract.
7. Fixed the transaction notification bug, processed the received Polka callback information, and each reminder only pops up once. 
- Contract
1. More unit tests have been added and coverage tests have been conducted for the main methods
2. The authentication of joining the Dao is added. Users who have joined the Dao cannot join again
3. The proposal category has been verified and the problem that any positive integer can be entered has been modified. Now only specific proposal types are allowed to be entered
4. Users joining Dao have time limit, The expire_time in dao_user is used to determine whether the user has expired in the Dao
5. 2, 4 and 6 of condition are used to judge the restriction type of Dao currently added. For convenience, only 2 are reserved now
6. Mother is a parent-child Dao. This type of Dao can create a child Dao.Union is a federation Dao, and other Daos can join this Dao for Federation
7. The bug that does not appear in the voting record is modified. Previously, the record could not be saved due to the wrong use of ``clone``. Now remove the ``clone`` and you can store it


Right now I can't confirm that we have fully resolved all issues. You can review it again to see if there are any new problems. If there are still new issues, please log them and we will continue to optimize our code based on your review.

Thank you again for your hard work, your rigorous work has also raised our own requirements. It is with your help that our team can continue to improve.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @RainbowcityKun. Thank you for the update. 

I still had some trouble with the documentation. For example, what is "govnance_dao" that is referenced in the [UI readme](https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/docs/README.md?plain=1#L123)? I also don't see an "rbdAddr" parameter anywhere. 

It seems that you have put considerable effort into improving the codebase. And I was able to see and test all changes in the deployed version, which seems sufficient to me at this point. The only thing I would still like to ask you to improve is the contract code coverage. If you look at DaoFactory, for example, it only tests two of the seven functions within, only for a single case (list is empty after `new` and `joined_dao` returns `true`, which is the only possible return value of that function) and none of the more complex ones. This should not just be for our or other people's benefit, but for your and your users'.

**Comment by RainbowcityKun** [comment]
HI,@semuelle , thanks again for your review. It is because of your patience test that it helps us to continuously find and solve problems, and also allows our technical team to continuously improve.

Because our technicians have only been in contact with the ink! contract for half a year, they still do not have a very high level of proficiency. It is with your help that our technicians are able to ink! understanding has grown rapidly.

 1. Regarding the "govnance_dao" you mentioned, it is a brief introduction to the steps of deploying the contract. We made another update to the deployment documentation today.

https://github.com/RainbowcityFoundation/RainbowDAO-Protocol-Ink-UI-milestone_2/blob/main/docs/README.md

The detailed steps to deploy the contract should be:
erc20 > dao_category > dao_proposal > dao_setting > dao_users > dao_vault > template_manager > dao_manager > dao_factory.


2. Regarding your point  contract testing, we now cover as many methods as possible. However, there are many cross-contract calling methods in our project, and our technicians don't know how to test them.

Our technical staff also checked the official issue of ink!, and their answer for this type of contract is that it cannot be tested. Here is the relevant link of the issue we saw.

https://github.com/paritytech/ink/issues/1125

For the test of this contract, if you have a test method, you can also provide it to us here, and our technical staff also need more help.

Thank you again for your selfless help, and if you need any more changes, please feel free to leave us a message.

**Comment by semuelle** [comment]
Hi @RainbowcityKun. Thanks for the update. You are right that cross-contract function calls are currently hard to test. What you could do, however, is write tests that not only verify that a function has the right result and effects when called correctly, but also the right result when called incorrectly. For example, `dao_proposal` tests both cancel and propose once, for being successful with the right parameters, but there are no tests to check the results and effects for incorrect calls, such as calls from the wrong account, wrong category, blocks that are in the past, and so on.

**Comment by RainbowcityKun** [comment]
Hi @semuelle   , thanks for your valuable advice. We made some more updates to the code.

We added the judgment of input error information to the code. If the input is wrong, the contract will fail and exit. If the test of error information is added to the test, the test will fail. Therefore, we think it is not necessary to test the input error.

The following pictures are a few examples we have chosen,






Please check again if this is possible. Also check to see if there are any other problems. If there are other questions, please continue to leave comments, we will continue to revise and improve.

**Comment by semuelle** [comment]
Hi @RainbowcityKun. Thank you for the update. I went ahead and approved your milestone. 

Thanks for being responsive and fixing the issues I asked about. The UI is still rather rough around the edges, as I assume you are aware. But I hope and assume that you will keep working on it and make it a great user experience. Regarding the smart contracts, indeed we never had a project with so many contracts interacting, so your project does suffer from the lack of cross-contract call testing abilities in ink!. I hope that this limitation does get addressed soon. With regard to the tests: if the goal of the project was to create a smart contract library (which, to be honest, is how we view most smart contract projects), I would expect that every line of code would be tested, even the `assert`s. If you look at the OpenZeppelin library, you can see that they too have [tests](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/token/ERC20/ERC20.test.js#L289) for behaviour that is prevented by [`require`](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L231)s. 

I have forwarded your invoice for processing. You can find my final evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/rainbowDAO_2_semuelle.md). 

Good luck going forward!

**Comment by semuelle** [comment]
@RainbowcityKun: We just noticed that your invoice has a date stamp of January 2021, we will need one with the correct date. Can you resubmit?

**Comment by RainbowcityKun** [comment]
Hi, @semuelle  , we have resubmitted the invoice information, please check.

Thank you very much for your patient review over the past month, which has helped our technicians a lot. At the same time, we also realize that there are many problems in our code, and there is a lot of room for improvement. At the same time, in the past few months, our understanding of the product itself has also undergone some new changes. In the future, we will rewrite and optimize these codes to create the best user experience.

We will also re-plan the product and continue to apply for grants. We are not in a hurry to bring the product to the market and users very quickly. We hope to make the product truly mature, and then start the operation of the market. Now your Web3 Foundation team is our best teacher, and our technical members have grown rapidly under your guidance.

**Comment by RouvenP** [comment]
hi @RainbowcityKun we transferred the funds today. Thanks!

**Pull request merged**
