### PR TITLE
Cryptex Milestone 1

### PR DESCRIPTION
**Pull request by driemworks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1660

### CODE REVIEW

**Comment by Whisker17** [comment]
Hey @driemworks, I'm doing an external evaluation of your project, and when I run uts, some errors happened, could you have a look at this?
image

**Comment by driemworks** [comment]
My changes shouldn't have impacted that part of the codebase, so that's odd ([the failing test](https://github.com/ideal-lab5/substrate/blob/8673a5db5209755a7959d5dae43ed6c3d893a2ea/frame/system/benchmarking/src/lib.rs#L51)). I ran `cargo test --package frame-system-benchmarking --features runtime-benchmarks` and recieved `test bench_set_code ... ok`., but it fails without the runtime-benchmarks feature enabled. There were some significant changes to the frame system benchmarking package since I forked so I merged with master (commit hash d3711ab6e5700ddf03480920602e238a78f27de4) and cargo test passes. Hopefully that resolves everything.

**Comment by Whisker17** [comment]
I've pulled your code, and tried to cargo test again, but seems no tests run.

image

**Comment by driemworks** [comment]
@Whisker17 I reverted the merge with master, I didn't realize it introduced breaking changes to my pallet. I put this into a new branch: https://github.com/ideal-lab5/substrate/tree/etf_m1. Can you try executing tests against that branch? I'll merge to the `milestone1` branch if all is good. Can you post the command you used when you see the `bench_set_code` failure? I'm only able to replicate it if I try to run tests in frame/system/benchmarking explicitly and without the runtime-benchmarks feature enable (`cargo test --package frame-system-benchmarking`). When I run cargo test from the /frame directory everything looks good for me.

**Comment by Whisker17** [comment]
> Can you post the command you used when you see the bench_set_code failure?

I used this command: `cargo +nightly test`. And everything goes fine when I use this: `cargo test --package pallet-etf --features runtime-benchmarks`, which also makes me confused.


> I put this into a new branch: https://github.com/ideal-lab5/substrate/tree/etf_m1. Can you try executing tests against that branch?

I will try it again on this branch, thx for your update!

**Comment by Whisker17** [comment]
Just have a try again, seems the same problem.
image

**Comment by driemworks** [comment]
@Whisker17 thanks for the patience, it's fixed now. It looks like that test failure is unrelated to my changes. That test had some issues which were fixed in master after I made my fork ([some commits here](https://github.com/ideal-lab5/substrate/commits/master/frame/system/benchmarking/src/lib.rs)). Instead of merging with master and redoing my pallet (which we'll need to do eventually), I just fixed the test. It was failing because the frame_system pallet was initialized with an empty version in the mock and there was nothing to setup a version (one of the new commits does that), so when the test ran the check_set_code function would execute and compare the new to existing spec name, but since the existing is "", it always fails. I fixed it [here in the etf_m1 branch](https://github.com/ideal-lab5/substrate/blob/6107ea484f23d4bbf9b0ea03deb41833a1b3ef38/frame/system/benchmarking/src/mock.rs#L45).  If it looks good, I'll merge to the milestone1 branch.

**Comment by Whisker17** [comment]
@driemworks thx for your updates, I just finished test, lgtm, I've updated my evaluation here #950.

**Review by semuelle — APPROVED** [review]
Thanks for the fixes, @driemworks. I verified the evaluation and can report that your milestone is hereby accepted. You can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_1_whisker.md).

I have forwarded your invoice for processing.

**Pull request merged**
