### PR TITLE
Ajuna network milestone 4

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/433

### CODE REVIEW

**Comment by darkfriend77** [comment]
Also, we need help reorganizing the SDK and moving it into a neutral repository with a proper naming not related to Ajuna to get it into the asset store.

As we would stay within those blockchain competitors, https://assetstore.unity.com/decentralization

image

It would be well worth the effort. The SDK is substrate only and provides everything needed to access and work with Substrate as the backend.

**Comment by semuelle** [comment]
Hi @darkfriend77 & @dimitrispaxinos. Thanks for the submission. I am currently trying to follow the setup instructions [here](https://github.com/ajuna-network/Ajuna.Automation.DOT4G), and `docker-compose build worker` is failing with the following error. Any idea what's missing?

```sh
 => ERROR [build 6/6] RUN CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make                                             59.8s
------                                                                                                                         
 > [build 6/6] RUN CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make:                                                         
#18 0.527 /opt/sgxsdk/bin/x64/sgx_edger8r --trusted enclave-runtime/Enclave.edl --search-path /opt/sgxsdk/include --search-path ./rust-sgx-sdk/edl --trusted-dir enclave-runtime                                                                              
#18 0.969 /opt/sgxsdk/bin/x64/sgx_edger8r --untrusted enclave-runtime/Enclave.edl --search-path /opt/sgxsdk/include --search-path ./rust-sgx-sdk/edl --untrusted-dir service                                                                                  
#18 1.416 GEN  =>  enclave-runtime/Enclave_t.c enclave-runtime/Enclave_t.h service/Enclave_u.c service/Enclave_u.h
#18 1.825 CC   <=  enclave-runtime/Enclave_t.c
#18 1.825 ar rcsD service/libEnclave_u.a service/Enclave_u.o
#18 1.828 cp service/libEnclave_u.a ./lib
#18 1.923 
#18 1.924 Building the integritee-service
#18 2.475     Updating git repository `https://github.com/apache/incubator-teaclave-sgx-sdk`
#18 7.206     Updating crates.io index
#18 40.59     Updating git repository `https://github.com/encointer/substrate-fixed`
#18 41.36     Updating git repository `https://github.com/mesalock-linux/thiserror-sgx`
#18 41.94     Updating git repository `https://github.com/mesalock-linux/rust-url-sgx`
#18 42.91     Updating git repository `https://github.com/integritee-network/http-sgx.git`
#18 43.57     Updating git repository `https://github.com/integritee-network/http_req`
#18 44.19     Updating git repository `https://github.com/paritytech/substrate.git`
#18 57.19     Updating git repository `https://github.com/scs/jsonrpc`
#18 58.09     Updating git repository `https://github.com/ajuna-network/Ajuna`
#18 59.64 error: failed to get `ajuna-solo-runtime` as a dependency of package `ita-stf v0.9.0 (/workspace/app-libs/stf)`
#18 59.64 
#18 59.64 Caused by:
#18 59.64   failed to load source for dependency `ajuna-solo-runtime`
#18 59.64 
#18 59.64 Caused by:
#18 59.64   Unable to update https://github.com/ajuna-network/Ajuna?branch=release/bengal#953bb8fc
#18 59.64 
#18 59.64 Caused by:
#18 59.64   object not found - no match for id (953bb8fc554323484d23d4a3fd3c7e5cf91a9cc2); class=Odb (9); code=NotFound (-3)
#18 59.65 make: *** [Makefile:174: bin/app] Error 101
------
executor failed running [/bin/bash -c CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make]: exit code: 2
ERROR: Service 'worker' failed to build
```

**Comment by semuelle** [comment]
Regarding the Android app: 
- Is the app open source? I can't find it.
- The app seems to be stuck on this screen:

**Comment by darkfriend77** [comment]
> Regarding the Android app:
> 
> * Is the app open source? I can't find it.
> * The app seems to be stuck on this screen:
> 
> 

Yep, we stopped the servers, but let me give you access to the repo, so you can run it towards the backed-devel as soon as I am able to provide you with the instructions how to build.

**Comment by dimitrispaxinos** [comment]
> Hi @darkfriend77 & @dimitrispaxinos. Thanks for the submission. I am currently trying to follow the setup instructions [here](https://github.com/ajuna-network/Ajuna.Automation.DOT4G), and `docker-compose build worker` is failing with the following error. Any idea what's missing?
> 
> ```shell
>  => ERROR [build 6/6] RUN CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make                                             59.8s
> ------                                                                                                                         
>  > [build 6/6] RUN CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make:                                                         
> #18 0.527 /opt/sgxsdk/bin/x64/sgx_edger8r --trusted enclave-runtime/Enclave.edl --search-path /opt/sgxsdk/include --search-path ./rust-sgx-sdk/edl --trusted-dir enclave-runtime                                                                              
> #18 0.969 /opt/sgxsdk/bin/x64/sgx_edger8r --untrusted enclave-runtime/Enclave.edl --search-path /opt/sgxsdk/include --search-path ./rust-sgx-sdk/edl --untrusted-dir service                                                                                  
> #18 1.416 GEN  =>  enclave-runtime/Enclave_t.c enclave-runtime/Enclave_t.h service/Enclave_u.c service/Enclave_u.h
> #18 1.825 CC   <=  enclave-runtime/Enclave_t.c
> #18 1.825 ar rcsD service/libEnclave_u.a service/Enclave_u.o
> #18 1.828 cp service/libEnclave_u.a ./lib
> #18 1.923 
> #18 1.924 Building the integritee-service
> #18 2.475     Updating git repository `https://github.com/apache/incubator-teaclave-sgx-sdk`
> #18 7.206     Updating crates.io index
> #18 40.59     Updating git repository `https://github.com/encointer/substrate-fixed`
> #18 41.36     Updating git repository `https://github.com/mesalock-linux/thiserror-sgx`
> #18 41.94     Updating git repository `https://github.com/mesalock-linux/rust-url-sgx`
> #18 42.91     Updating git repository `https://github.com/integritee-network/http-sgx.git`
> #18 43.57     Updating git repository `https://github.com/integritee-network/http_req`
> #18 44.19     Updating git repository `https://github.com/paritytech/substrate.git`
> #18 57.19     Updating git repository `https://github.com/scs/jsonrpc`
> #18 58.09     Updating git repository `https://github.com/ajuna-network/Ajuna`
> #18 59.64 error: failed to get `ajuna-solo-runtime` as a dependency of package `ita-stf v0.9.0 (/workspace/app-libs/stf)`
> #18 59.64 
> #18 59.64 Caused by:
> #18 59.64   failed to load source for dependency `ajuna-solo-runtime`
> #18 59.64 
> #18 59.64 Caused by:
> #18 59.64   Unable to update https://github.com/ajuna-network/Ajuna?branch=release/bengal#953bb8fc
> #18 59.64 
> #18 59.64 Caused by:
> #18 59.64   object not found - no match for id (953bb8fc554323484d23d4a3fd3c7e5cf91a9cc2); class=Odb (9); code=NotFound (-3)
> #18 59.65 make: *** [Makefile:174: bin/app] Error 101
> ------
> executor failed running [/bin/bash -c CARGO_NET_GIT_FETCH_WITH_CLI=true SGX_MODE=SW make]: exit code: 2
> ERROR: Service 'worker' failed to build
> ```

@semuelle Can you please remove the two following `Cargo.lock` files within the backend-devel directory and run `docker-compose` once more?

First one in `backend-devel\worker\` and the second one in `backend-devel\worker\enclave-runtime\`

**Review by semuelle — COMMENTED** [review]
Thanks. One more question: you left out deliverable `1` from the delivery doc. I dug a little and found [this closed issue](https://github.com/ajuna-network/Open-Grants-Program/issues/59), which looks outdated. But I assume it refers to [this](https://github.com/ajuna-network/Ajuna/tree/028534df8156c49171b4119fac50cdf455f5b576/pallets/ajuna-board), correct?

**Comment by semuelle** [comment]
Thanks for the updates, @darkfriend77 & @dimitrispaxinos. I am happy to report that your milestone is accepted. 
You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ajuna-follow-up_4_semuelle.md).

I will forward your invoice for processing. Since this is your last milestone, I'd like to wish you best of luck going forward. I'm sure we will hear from you.

**Pull request merged**
