### PR TITLE
Token-economics Survey 2022: Milestone 2

### PR DESCRIPTION
**Pull request by taqtiqa-mark**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) Pending setup of required corporate entities.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1348

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @taqtiqa-mark someone will take a look at it shortly.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @taqtiqa-mark. Thanks again for the delivery. I have a few questions/comments:

- What does `NC` stand for in the economy type diagram?
- Can you elaborate what the `framework put forward by Burnie, A., Burnie, J., and Henderson, A. (2018)` used in the `Native Token Functions` section is, what those values mean and what we can learn from it?
- Are you planning any kind of summary or overview for the `Sector Type` section?

**Comment by taqtiqa-mark** [comment]
>     * What does `NC` stand for in the economy type diagram?

Native Coin. I've now introduced it in the preamble for that section.  This will land in M3:

image

>     * Can you elaborate what the `framework put forward by Burnie, A., Burnie, J., and Henderson, A. (2018)` used in the `Native Token Functions` section is, what those values mean and what we can learn from it?

The following will land in M3:

image

>     * Are you planning any kind of summary or overview for the `Sector Type` section?

I'm not planning a decision tree, for the reasons stated. I'll think a bit more about whether I can add any helpful guidance, but I'm running way over time as it is. Hopefully something constructive springs to mind, but I've got nothing right now.

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @taqtiqa-mark. Your milestone is hereby accepted. 

You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tokenomics-survey-2022_2_semuelle.md). Please let us know here or by email once you submitted the invoice.

**Comment by keeganquigley** [comment]
Hi @taqtiqa-mark did you ever submit this invoice?

**Comment by taqtiqa-mark** [comment]
Not yet. Co is setup and bank account remains.

**Pull request merged**
