### PR TITLE
Create distributedKeyManagement-milestone_2.md

### PR DESCRIPTION
**Pull request by jettblu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1200

### CODE REVIEW

**Comment by jettblu** [comment]
Hey there, I believe the 'author check' failed since a member of the W3F team made the final commit (after I accidentally made a commit to the wrong directory). Please let me know if there is anything I can do to help the review process.

**Comment by keeganquigley** [comment]
Thanks @jettblu no problem I will take a look at it and start the evaluation.

**Comment by keeganquigley** [comment]
Hi @jettblu after my initial evaluation, I have a couple of questions:

- The app works great and I'm able to manually test all of the functionality. However, I'm not finding a quick way to run all the unit tests such as using `yarn test`, is there an easy way to run the TS tests?
- Your app is very intuitive and easy to use, and the syncing function is great! But I'm not seeing any way to create Polkadot/Kusama accounts. The application notes that the deployed app will have substrate specific examples, is this still supposed to be the case? Thanks!

**Comment by jettblu** [comment]
Hi @keeganquigley  ! Thank you for your feedback.  I've addressed your questions below.

- Yes! `yarn test` is specified in the package.json. Tests are also run upon every deployment via a CI pipeline.
- I'm glad you found the interface intuitive. We decided against adding substrate methods to the keyring. Instead, we focused on the sync and key management routines. While we can add support for substrate signatures/address creation, the 'polkadotjs' [keyring library](https://github.com/polkadot-js/common/tree/master/packages/keyring) already provides strong support for this. 
The SWORD demo uses the [hdseedloop ](https://github.com/KryptikApp/kryptik-seedloop)package to manage keys and create multichain signatures. We try to use as few external libraries as possible for this package. If we were to incorporate substrate signatures/addresses, we would do so from 'the ground up,' which may be outside the scope of this grant.
I am interested to hear your thoughts. Thanks again for the feedback.

**Comment by keeganquigley** [comment]
@jettblu awesome thanks for the explanations! I was able to get all 18 tests pass, and I'm happy to pass this milestone. I think the sync technology is great and very useful. I was able to manually test all functions as well. You can find my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DistributedKeyManagement_2_keeganquigley.md). Congrats on the completion of the grant!

**Comment by jettblu** [comment]
@keeganquigley wonderful! Thank you for reviewing the milestone. I appreciate your comments.

**Comment by RouvenP** [comment]
hi @jettblu we transferred the payment today.

**Pull request merged**
