### PR TITLE
Signac Milestone 1

### PR DESCRIPTION
**Pull request by hskang9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1044

### CODE REVIEW

**Comment by hskang9** [comment]
@semuelle @cruikshankss The form is not accepting invoice. Can you please check

**Comment by lucasvanmol** [comment]
Hi there, thank you for the delivery. I'm trying to run the commands in the readme but I'm running into this issue:

```console
~ ❯  git clone https://github.com/digitalnativeinc/signac && cd signac/packages/nxinc
Cloning into 'signac'...
remote: Enumerating objects: 197, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (131/131), done.
remote: Total 197 (delta 49), reused 175 (delta 38), pack-reused 0
Receiving objects: 100% (197/197), 5.42 MiB | 4.77 MiB/s, done.
Resolving deltas: 100% (49/49), done.

signac/packages/nxink ❯ npm install -g nx                                                                                                                 

added 110 packages, and audited 111 packages in 5s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

signac/packages/nxink ❯ nx generate nxink:ink my-ink-contract                                                                                     16:54:39

 >  NX   Could not find Nx modules in this workspace.

   Have you run npm/yarn install?


signac/packages/nxink ❯ npm install                                                                                                                 

added 119 packages, and audited 120 packages in 5s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

signac/packages/nxink ❯ nx generate nxink:ink my-ink-contract  
                                                                             
 >  NX   Could not find Nx modules in this workspace.

   Have you run npm/yarn install?


```

So I'm not sure what the problem is. Any advice?

**Comment by hskang9** [comment]
Ah I think you need to run yarn first all before running it.

**Comment by hskang9** [comment]
I built preset for you so you can run ‘npx create-nx-workspace —preset=nxink’ to see how nxink works. @lucasvanmol

**Comment by hskang9** [comment]
@lucasvanmol Is there any other questions on the delivery?

**Comment by cruikshankss** [comment]
Good day @hskang9, I have actually taken responsibility of your evaluation. @lucasvanmol was very kind to help me with another evaluation I was blocked on, so we traded. I am not sure if there are any other questions on the delivery yet but I plan to get started as soon as possible and let you know if there are. Thanks!

**Comment by cruikshankss** [comment]
Hello @hskang9,

I'd really love to complete your evaluation this week. If you're available, I'd be super interested in meeting with you for 30 mins for a live demo video call/discussion of the software architecture so I can understand the value of your project.

Tomorrow I'm free 1-2:30pm and after 3pm CET. Friday I'm free 1-2:30pm and after 4:30 CET. My time zone is UTC−07:00 which hopefully explains my availability this week. Please feel free to choose a 30-min time window. I also plan to message the other teams who have evaluations I hope to finish this week. It's a really busy week for me which is why I'm trying to schedule these demos so I can speed up my pace; my apologies for the delay. And if a time gets taken, I plan to edit this message in GitHub so please check this convo tab on GH for the latest updates. Feel free to send a calendar invite to [ashleyg@web3.foundation](mailto:ashleyg@web3.foundation) if you select a time and I plan to RSVP from there.

Otherwise, I'm also open to scheduling an Element or Discord chat. If not, absolutely no worries & thanks for your continued patience while I study your delivery.

**Comment by hskang9** [comment]
It is good to see this organization now refer ETA other than Soon™️. My discord id is `Hyungsuk | Standard Protocol#7929`. Please open up a chat

**Comment by cruikshankss** [comment]
@hskang9 😂 we should really get the trademark on that. I just tried adding you on disc but it says you're not accepting friend requests. I used to have a calendly but i don't have one any longer; it really is so much easier; sorry. Could you try adding me on disc? `cruikshankss#6287`

**Comment by cruikshankss** [comment]
@hskang9 If you're free, please pick any time after 4pm CET next week and send a cal invite to ashleyg@web3.foundation. I work in USA mountain time (GMT-7:00). I start work at 1pm CET so if you're only free between 1pm-4pm CET next week, I can send you some available time windows.  

I love !nk 🖊 and wasm; and also your pointillism metaphor seems like really cool artistic side to this dev work. 🎨 ... I just finished the sol2!nk evaluation today and finished OpenBrush's milestone 6 evaluation last week. I was fortunate to attend some of the wasm conference this year and done some other wasm review in another eval, so I should be pretty well set up to review your project! 

Again, so sorry for the delay. Super looking forward to reviewing your project, SOON™️ 😂

**Comment by cruikshankss** [comment]
Again, congrats! Here's [my eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/signac_1_cruikshankss.md).

May I suggest?: take a look at [this other open-source evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/citadel-one_1_cruikshankss.md) I completed today. It has some related frontend ideas.

**Comment by hskang9** [comment]
@cruikshankss invoice has been resubmitted. Please check.

**Comment by fededubbi** [comment]
Good morning,

I noticed the invoice is divided in two pages.
Can you please insert all in one page?

Many thanks,
Federica Dubbini

**Pull request merged**
