### PR TITLE
evaluation(subgame): milestone-1

### PR DESCRIPTION
**Pull request by TomaszWaszczyk**
# Milestone Delivery Checklist

- [ ] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [ ] This pull request is being made by the same account as the accepted application. 
- [ ] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the evaluation. Looks pretty good. Did you already share your feedback with the team? Also it would be nice if you could update the formatting of the “Accepted” column. In general we usually accept the deliveries as long as they fulfill the contract, but independent of it try to share as much feedback with the team as possible. I will already merge your evaluation, since this way it’s easier to share it with the team and it says “in progress” anyway.

**Comment by TomaszWaszczyk** [comment]
I have created an issue [here](https://github.com/SubGame-Network/GameCenter/issues/1) and in the already merged PR I have described my view on the subject. In the context of:

> After smart contract is processed by AI cloud computing, it can be perfectly compatible with other public chains to achieve high chain-to-chain collaboration.

I think that the most time efficient way to explain it will be managing ~20minutes video call with the Team having short agenda:

- What does mean: "AI cloud computing, it can be perfectly compatible with other public chains to achieve high chain-to-chain collaboration", what are going to be deliverables in that context.

**Comment by Noc2** [comment]
Okay got it. It’s usually easier to keep track of the evaluation in the delivery repo, [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/160). Feel free to also talk to the team directly. Just keep in mind that for the acceptance of the delivery, you mostly should take a look at the contract and see if the requirements are fulfilled (checked off as finished). Obviously independent of it, it makes sense to give them feedback and see if the project itself makes sense in its current form.

**Comment by TomaszWaszczyk** [comment]
I have run successfully the SubGame and [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/160) I have also written my comments.

image

I am do aware of the fact that evaluation means feedback.

**Pull request merged**
