### PR TITLE
Update GitHub workflow to be able to parse multiple delivery files

### PR DESCRIPTION
**Pull request by lucasvanmol**
Example runs of the updated workflow can be seen here:

https://github.com/lucasvanmol/Grant-Milestone-Delivery/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

Note that it's normal for `check_author` to fail because that action is looking for @lucasvanmol to show up as an author in the application repo.

### CODE REVIEW

**Comment by alxs** [comment]
Looks really good. Let's merge it and keep an eye on it

**Comment by alxs** [comment]
And here the first problem ;) https://github.com/w3f/Grant-Milestone-Delivery/actions/runs/2494761855

The badge action also used the composite file, can you take care of it? Feel free to copy-paste instead of going through the trouble with composite again

**Comment by alxs** [comment]
I'll revert this for now

**Comment by lucasvanmol** [comment]
Oops - sorry about that. How should the badge action handle multiple files? For example, should the badge message be posted only once if [this condition](https://github.com/w3f/Grant-Milestone-Delivery/blob/870296e802e7ebb10add0c9cd5f3f313a15f9f7c/.github/workflows/badge.yml#L29) is met on any of the delivery files?

**Comment by alxs** [comment]
Exactly, it doesn't need to be the first one

**Pull request merged**
