### PR TITLE
Fair Squares - milestone 2 delivery

### PR DESCRIPTION
**Pull request by ilhanu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/971

### CODE REVIEW

**Comment by lucasvanmol** [comment]
Hi @ilhanu, thank you for the delivery! I've been looking over it and was running into some issues while going through the tutorial document you provided, notably at part 2 (Submitting a proposal), step 2 - issuing a council vote on the `votingModule.callDemocracyProposal`. I'm trying to submit a `vote()` extrinisic in the council pallet like so (this is using the fair-squares node):

Screenshot 2022-08-24 at 16 25 49

Screenshot 2022-08-24 at 16 27 41

But I am getting a `system.CallFiltered` error when I try to submit the vote. Please let me know if I'm doing something wrong!

**Comment by ilhanu** [comment]
Hi @lucasvanmol,
I've just tested it and at the last moment we decided to [filter](https://github.com/Fair-Squares/fair-squares/blob/main/runtime/src/lib.rs#L532-L547) the democracy, collective and NFTModule pallets. The guide was written before implementing that. I'll adjust the guide today, apologies for the sloppiness. 

The filter is implemented  because we want the investor-vote and the current democracy pallet allows conviction and allowing to vote with balance. Whereas we wanted to make use as much as possible the substrate pallets, we have our own call on top of it. If we would not filter the democracy pallet you could vote with your full available credits/balance. 

The right call to make if you want to vote from the council and or investor is using the votingModule (see screenshot). You would also use the voting-module for the `investorVote`. 

image

Thanks a lot for pointing this out!

**Comment by lucasvanmol** [comment]
Thank you for those changes @ilhanu, the rest of the delivery is looking great and as such I've accepted it, ([evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fair-squares_2_lucasvanmol.md)). 

A couple of small notes:
* In `pallets/onboarding/src/lib.rs` (line 250) there are still some sample functions:
```rs
/// An example dispatchable that takes a singles value as a parameter, writes the value to
/// storage and emits an event. This function must be dispatched by a signed extrinsic.
//#[pallet::weight(10_000 + T::DbWeight::get().writes(1))]
#[pallet::weight(<T as pallet::Config>::WeightInfo::do_something(100))]
pub fn do_something(origin: OriginFor<T>, something: u32) -> DispatchResult {
    // Check that the extrinsic was signed and get the signer.
    // This function will return an error if the extrinsic is not signed.
    // https://docs.substrate.io/v3/runtime/origins
    let who = ensure_signed(origin)?;

    // Update storage.
    <Something<T>>::put(something);

    // Emit an event.
    Self::deposit_event(Event::SomethingStored(something, who));
    // Return a successful DispatchResultWithPostInfo
    Ok(())
}
```

* Regarding your article and tutorial document, feel free to forward this to [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) for feedback, and they can also help out with cross-promotion.

**Comment by ndkazu** [comment]
> Thank you for those changes @ilhanu, the rest of the delivery is looking great and as such I've accepted it, ([evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fair-squares_2_lucasvanmol.md)).
> 
> A couple of small notes:
> 
> * In `pallets/onboarding/src/lib.rs` (line 250) there are still some sample functions:
> 
> ```rust
> /// An example dispatchable that takes a singles value as a parameter, writes the value to
> /// storage and emits an event. This function must be dispatched by a signed extrinsic.
> //#[pallet::weight(10_000 + T::DbWeight::get().writes(1))]
> #[pallet::weight(<T as pallet::Config>::WeightInfo::do_something(100))]
> pub fn do_something(origin: OriginFor<T>, something: u32) -> DispatchResult {
>     // Check that the extrinsic was signed and get the signer.
>     // This function will return an error if the extrinsic is not signed.
>     // https://docs.substrate.io/v3/runtime/origins
>     let who = ensure_signed(origin)?;
> 
>     // Update storage.
>     <Something<T>>::put(something);
> 
>     // Emit an event.
>     Self::deposit_event(Event::SomethingStored(something, who));
>     // Return a successful DispatchResultWithPostInfo
>     Ok(())
> }
> ```
> 
> * Regarding your article and tutorial document, feel free to forward this to [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) for feedback, and they can also help out with cross-promotion.

Many thanks for the review Lucas!
The sample function is actually used for [dummy call/default call value] in the struct containing the calls that are to be sent to the voting pallet.
Kazu

**Pull request merged**
