### PR TITLE
New BLS12 hash function M1

### PR DESCRIPTION
**Pull request by dishport**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/966

### CODE REVIEW

**Review by alxs — CHANGES_REQUESTED** [review]
Thanks for the delivery @dishport, that was quick! Could you please:

- List all the deliverables you included [in the application](https://github.com/w3f/Grants-Program/blob/master/applications/new_bls12_hash_function.md#milestone-1--implementation-of-the-new-hash-function).
- Submit an amendment, i.e. a PR to update the original file, adding a payment address.
- Submit an invoice.
- Provide the documentation on the hash function in a readable format. There are hacks to render formulas in GitHub markdown, otherwise feel free to link to a [HackMD](https://hackmd.io/).
- Also provide some documentation on the implementation.
- Deliver unit tests as per your application.

Let me know if you have any questions.

**Comment by dishport** [comment]
@alxs, I added the necessary information except for the payment address and invoice. Could I fill these data after the milestone is accepted by evaluators?

**Comment by alxs** [comment]
As you wish. Could you refer to the last 3 points in my last comment?

**Comment by dishport** [comment]
Please answer the following questions or give some remarks. This is my first milestone delivery, so excuse me for my stupidity.

> Provide the documentation on the hash function in a readable format. 
I added the link to my published article. Is it regarded as a documentation of a readable format?

> There are hacks to render formulas in GitHub markdown, otherwise feel free to link to a [HackMD](https://hackmd.io/).
I don't understand what it is.

> Also provide some documentation on the implementation.
What is the difference between this and the first point? I provided inline documentation on the implementation. Is it sufficient ?

> Deliver unit tests as per your application.
My application doesn't contain units, because the implementation is compact.

**Comment by dishport** [comment]
> Keep in mind your article is behind a paywall, so you shouldn't assume everyone has access to it.

I included the link to free eprint version, where all math formulas have already been clearly explained.

**Comment by alxs** [comment]
@dishport and yet anyone who finds your repository will have no idea what it contains. The only person who will see the link you just added is me, but we're trying to make your delivery accessible to the open-source community. Again, please refer to my last message.

Also could you please move the delivery file to its proper location in the `deliveries` folder?

**Comment by drskalman** [comment]
@alxs I'll review this. could point me to the code. I can't somehow find it easily.

**Comment by alxs** [comment]
Great. Here's the [repository](https://github.com/dishport/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation) and [this](https://github.com/w3f/Grant-Milestone-Delivery/blob/74873a7ba1efbf96ad0ce70d44321a87c6443ad4/deliveries/new_bls12_hash_function-milestone_1.md) is @dishport's delivery file.

**Comment by dishport** [comment]
@Noc2, I added.

**Comment by dishport** [comment]
@drskalman, what is the progress in reviewing my delivery ?

**Comment by alxs** [comment]
Hey @dishport, @drskalman just submitted his evaluation of your delivery [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/398). Could you please address his comments and get back to him when you're done? You can keep the conversation on this PR.

**Comment by Noc2** [comment]
@dishport and @drskalman It’s usually easier to keep the conversation on the PR of the original delivery. Sorry that I replied to the other PRs myself. Maybe we should just continue here. (https://github.com/w3f/Grant-Milestone-Delivery/pull/398#pullrequestreview-957476302)

**Comment by alxs** [comment]
On hold since @dishport submitted an amendment that partially replaces the current deliverables.

**Comment by dishport** [comment]
@drskalman, let me know. Did you start to review my general Sage code ?

**Comment by drskalman** [comment]
@dishport : I added a [test](https://github.com/w3f-grants-archive/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/commit/7bf0597cedb9d2fa21113382cd31c67e68bb772) to your sage code I constantly gets hash results of the BLS12-381 curve. 
```
TypeError: Coordinates [25512803050240595101211008508174725228106586266775130773852922027289, 5992629649244653585476993497810980157902032946450917934672222453825, 1] do not define a point on Elliptic Curve defined by y^2 = x^3 + 4 over Finite Field of size 26959946667149205758383469736921695435015736735261155141423417423923 
```
also the size of the field seems off compared to let say: https://hackmd.io/@benjaminion/bls12-381 
nonetheless it is a curve with j-invariant 0 and it should hash correctly right?

**Comment by dishport** [comment]
@drskalman, it is necessary to call the function test_several_hashes(Fq,b,NUMBER_TEST_HASHES) after the code starting from # Precomputations and checking conditions
and ending with # In both cases, c is a cubic non-residue in Fq
Because this code initialize all preliminary values.

**Comment by drskalman** [comment]
@dishport could you please commit your changes to the test and push it to your repo? I'll take it from there. Thanks a lot.

**Comment by dishport** [comment]
> @dishport could you please commit your changes to the test and push it to your repo? I'll take it from there. Thanks a lot.

@drskalman, you can find the changed code on the link https://disk.yandex.ru/d/RuqWxbUx_qrhWw
I don't want to push this code to my GitHub repo, because this is a draft, not the original version.

**Comment by drskalman** [comment]
I see what went wrong. 

You shouldn't really use global variables. It renders the code unreusable (as it did for me): https://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil

I moved the tests to their own unit test class so they don't interfere with the global state.  I also add @noglobal decorators to prevent the use of global variables in your functions. 

Please modify the code so it passes the tests without the use of global variables. You could make a pull request to our repo if you wish not to modify your own, so I can verify the code successfully passes the test or review and comment on the pr. 

Thanks a lot.

**Comment by dishport** [comment]
> I moved the tests to their own unit test class so they don't interfere with the global state. I also add @noglobal decorators to prevent the use of global variables in your functions:

> https://github.com/w3f-grants-archive/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/commit/ba93ab217c14089cb8a1e46db74a7d008b73367c

> Please modify the code so it passes the tests without the use of global variables. 

@drskalman, thank you for your work. However, I don't understand what exactly I have to write, because I don't know how to use unittest. Why don't you finish testing yourself if you started doing it? The use of professional testing tools is not included in Milestone 1 according to the new grant proposal. Thorough testing (in Rust) was moved to Milestone 2.

**Comment by drskalman** [comment]
The test are for me to evaluate your code and see if the delivery does what is supposed to do. I moved them out, in case you find them confusing.

What you need to do, is *not to use global variables*. I moved every thing global in your original submission to `main` function.

Could you please edit this code so it runs without error and without using global variables:

https://github.com/w3f-grants-archive/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/blob/no-test-prohibt-global-vars/Indifferentiable%20hashing%20with%20the%20cost%20of%20one%20exponentiation.sage

For example, it currently results in this error:
```
...
  File "~/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/Indifferentiable hashing with the cost of one exponentiation.sage.py", line 212, in H
    t1,t2 = eta(s)

  File "~/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/Indifferentiable hashing with the cost of one exponentiation.sage.py", line 204, in eta
    return Fq(hash0), Fq(hash1)
NameError: name 'Fq' is not defined
```
If you want to use `Fq` in `eta` function you need to provide it as a parameter (like `s`) not as a global variable. (otherwise your code doesn't pass the tests as you saw).

Thanks!

**Comment by dishport** [comment]
@drskalman, I edited the code. Please find it on the link https://disk.yandex.ru/d/es_kKJbm0bssGA

**Comment by cruikshankss** [comment]
@dishport Thank you for editing the code. I haven't had a look yet, but I agree with @drskalman strongly about the global variables point. Much of the point of Rust is memory safety and much of the paradigm of memory safety is ownership and I think global variables should be used exceedingly sparingly in the spirit of ownership. Thanks!

**Comment by drskalman** [comment]
> @drskalman, I edited the code. Please find it on the link https://disk.yandex.ru/d/es_kKJbm0bssGA

Thanks! could you make a pull request against my branch so I don't need to re-read the whole thing, get a diff and be able to comment on it? thank you very much.

**Comment by dishport** [comment]
> Thanks! could you make a pull request against my branch so I don't need to re-read the whole thing, get a diff and be able to comment on it? thank you very much.

@drskalman, I made:
https://github.com/w3f-grants-archive/Indifferentiable-hashing-to-ordinary-elliptic-curves-of-j-0-with-the-cost-of-one-exponentiation/pull/1/commits/4eb3d50e9832b129c03e229c54132918e1de2107

**Comment by alxs** [comment]
Hey @dishport, @drskalman just [updated](https://github.com/w3f/Grant-Milestone-Delivery/pull/555) his evaluation and accepted your delivery. Thank you for your patience during the delivery process and @drskalman for taking care of the evaluation. I'm happy to approve it from my side as well.

@dishport when you're ready, feel free to submit the next milestone by opening a new pull request.

**Comment by dishport** [comment]
> @dishport could you please fill in the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89) and let me know when you've done so?

@alxs, in which cryptocurrency can you pay ? What about stablecoins ?

**Comment by alxs** [comment]
We can currently make payments in Bitcoin, USDT (on Kusama or Ethereum) or USDC/DAI (Ethereuem).

I remember you [didn't include](https://github.com/w3f/Grants-Program/pull/966/files#diff-1a8ccbeecef8393afdfef1d94cc665041e51e00c79c6d731c1c3d9a7dbd86667R5) a payment address in your application, so you'll need to do that first. Please add the address you want to be paid to and specify the currency [here](https://github.com/w3f/Grants-Program/edit/master/applications/new_bls12_hash_function.md). You'll need to create a new pull request.

I'll get back to you on the new delivery there.

**Comment by dishport** [comment]
> That's great, thank you. I will let the finance team know that you've requested a test transaction first.

Thank you!
 
> Could you please submit an invoice that meets the requirement specified in the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89)? Please read the instructions carefully. Please also specify your payment address and the currency (USDC). You can generate an invoice using an online tool like https://invoice-generator.com/.

I already submitted the pdf file containing the following text:

> Project name: Implementation of the new hash function to BLS12 curves
> Milestone/delivery number/name: Milestone 1 — An implementation in Sage 
> Payment address: 0x050240CB2f5F7f7aA8AA10a5A9AE36c784AEdE49 
> Currency: ERC20 USDC
> Amount: 10,000 USD
> Name: Dmitrii Koshelev
> Address: 27 B boulevard Jourdan, app. 317, Paris, France 

Is this normal or do I have to necessarily use an online tool ?

**Comment by alxs** [comment]
The file you submitted does not meet the requirements. Please use the online tool and follow the instructions in the form.

**Comment by dishport** [comment]
> The file you submitted does not meet the requirements. Please use the online tool and follow the instructions in the form.

@alxs, please look at the pdf file: https://disk.yandex.ru/i/ImD7-nXn5ghhmA
Does it satisfy the requirements ?

**Comment by alxs** [comment]
That should be fine, thank you. You can submit a similar invoice for milestone 2 through the invoice form.

I've let the team know. Please allow for up to two weeks of processing time until the payment is made.

**Comment by RouvenP** [comment]
hi @dishport we sent a test transaction of 10 USDC. Could you confirm receipt?

**Comment by dishport** [comment]
> hi @dishport we sent a test transaction of 10 USDC. Could you confirm receipt?

Hi @RouvenP. Yes, I received 10 USDC.

**Comment by RouvenP** [comment]
thanks for confirming @dishport. We transferred the remainder.

**Comment by dishport** [comment]
> Hi @RouvenP. Yes, I received 10 USDC.

Thank you, @RouvenP. In addition, could I obtain some document from your side to confirm the origin of my money ? Perhaps such a document will be required if I decide to declare income to a tax authority.

**Comment by RouvenP** [comment]
hi @dishport apologies for the late reply. I think that should be possible. Would you have a template for that?

**Comment by dishport** [comment]
> hi @dishport apologies for the late reply. I think that should be possible. Would you have a template for that?

@RouvenP, no, I don't have.

**Pull request merged**
