### PR TITLE
Add faterium-milestone-1

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1264.

## Context

The main goal of `Milestone 1` was to create the base functionality of Faterium Polls. We created Substrate Node that contains Pallet Assets (for creating assets), Pallet Scheduler (for scheduling polls endings), and main Pallet Faterium Polls.

To minimize storage on the chain - we created a Golang server that embedded the IPFS node and PocketBase, to create the best User Experience and make it possible to store big media files as IPFS CID in the database. To make it simple and straightforward to test - we launched a test Substrate Network on our servers, created simple interface pages for creating Polls, and voting on them (with help of the polkadot{.js} extension).

In the next `Milestone 2` - we will create all remaining pages, improve UI, and add community management logic.

https://user-images.githubusercontent.com/24860875/206148756-165b3e9e-d130-4323-a1d5-1214959e26fa.mp4

### CODE REVIEW

**Comment by enfipy** [comment]
Hello @alxs! We are glad to announce our completion of `Milestone 1`.

As we have a backend for this milestone, I would like to give some additional context and logins:

**Faterium Server**
- https://dapp-api.faterium.com/_/
- Email: `test@faterium.com`; Password: `1234567890`

**Faterium dApp**
- https://dapp.faterium.com/
- Our dApp UI works with `@polkadot/extension-dapp`. So [extension](https://polkadot.js.org/extension/) is required.

**Faterium Node**
- https://dapp-apps.faterium.com/
- This is just a simple `--dev` network, with all dev accounts available. Feel free to send some tokens or assets (asset_id=0, already created) to your account.

**Comment by 0xCaso** [comment]
Here I am @enfipy, I wrote the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/faterium_1_0xCaso.md). Let me know if you have any questions!

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Here I am @enfipy, I wrote the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/faterium_1_0xCaso.md). Let me know if you have any questions!

**Comment by enfipy** [comment]
Hi @0xCaso, glad to e-meet you, and thanks for the quick review.

Regarding your notes in the evaluation:

### 0b. Documentation

- [Done](https://github.com/faterium/faterium-node/blob/v0.1.1/scripts/docker_run.sh#L9) (preferred to update `docker_run.sh`).
- [Done](https://github.com/faterium/faterium-server/blob/v0.1.1/infra/local/docker-compose.yml).
- Done by [this](https://github.com/faterium/faterium-server/tree/v0.1.1#docker-and-local-network) and [this](https://github.com/faterium/faterium-dapp/tree/v0.1.1/#local-setup) (better solution with ENV variables).

### Other notes

- [Done](https://github.com/faterium/faterium-server/tree/v0.1.1#dedicated-testnet-server) (wrote additional info about it).
- [Added](https://github.com/faterium/faterium-node/blob/v0.1.1/pallets/faterium-polls/src/lib.rs#L483).
  - Hey, thanks for pointing out a bug! [Fixed](https://github.com/faterium/faterium-node/blob/v0.1.1/pallets/faterium-polls/src/lib.rs#L482).
- [Fixed](https://github.com/faterium/faterium-dapp/blob/v0.1.1/src/utils/Substrate.ts#L258).

---

Have a nice day!

**Review by 0xCaso — APPROVED** [review]
Hey @enfipy, thanks a lot for the fast additions/fixes, super efficient! I'm updating the evaluation, accepting the delivery. 

Btw I've just a minor thing to mention: during the creation of the poll, if you try to create one with only an option to vote, it gives an error, so probably you could put two options by default instead of only one.

**Comment by 0xCaso** [comment]
Sorry @enfipy, I noticed that (in your invoice) you requested USDT on Ethereum as payment method. Recently we changed our Guidelines, and I kindly ask you if it could be possible to change it to another method (one of [these](https://github.com/w3f/Grants-Program#pencil-process) so, if you want to stay on Ethereum, USDC or DAI; otherwise one of the others). If yes, could you please resend an updated invoice?

**Comment by enfipy** [comment]
Hey @0xCaso, just updated to USDC and uploaded the invoice.

**Comment by 0xCaso** [comment]
Thanks a lot @enfipy! I've just notified the finance team, please allow up to 14 days for the payment process.

**Comment by enfipy** [comment]
Hi @fededubbi,

Thank you for your notice. Updated and sent it.

Best,
David

**Pull request merged**
