### PR TITLE
societal-saas-pricing-m1

### PR DESCRIPTION
**Pull request by gfox1**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1671

### CODE REVIEW

**Comment by Ali-Usama** [comment]
Hi @gfox1 and @okalenyk. Thank you for submitting the milestone. However, I'm getting this error on running the docker image:
```
$ bash scripts/docker_run.sh 
*** Start Societal Node ***
[+] Building 0.0s (0/0)                                                                                                                                                               
[+] Creating 1/0
 ✔ Network societal-node_default  Created                                                                                                                                        0.0s 
[+] Running 6/6
 ✔ dev 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                 420.4s 
   ✔ 01085d60b3a6 Pull complete                                                                                                                                                318.7s 
   ✔ 8fcfcb47b1c2 Pull complete                                                                                                                                                410.5s 
   ✔ c1af8e07a1f9 Pull complete                                                                                                                                                410.5s 
   ✔ 28d8d4683eb7 Pull complete                                                                                                                                                413.5s 
   ✔ 170dcfc3956d Pull complete                                                                                                                                                413.5s 
[+] Building 0.0s (0/0)                                                                                                                                                               
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/home/societal-node/.local
```
Can you please look into it?

Thanks

**Comment by okalenyk** [comment]
> Hi @gfox1 and @okalenyk. Thank you for submitting the milestone. However, I'm getting this error on running the docker script:
> 
> ```
> $ bash scripts/docker_run.sh 
> *** Start Societal Node ***
> [+] Building 0.0s (0/0)                                                                                                                                                               
> [+] Creating 1/0
>  ✔ Network societal-node_default  Created                                                                                                                                        0.0s 
> [+] Running 6/6
>  ✔ dev 5 layers [⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                 420.4s 
>    ✔ 01085d60b3a6 Pull complete                                                                                                                                                318.7s 
>    ✔ 8fcfcb47b1c2 Pull complete                                                                                                                                                410.5s 
>    ✔ c1af8e07a1f9 Pull complete                                                                                                                                                410.5s 
>    ✔ 28d8d4683eb7 Pull complete                                                                                                                                                413.5s 
>    ✔ 170dcfc3956d Pull complete                                                                                                                                                413.5s 
> [+] Building 0.0s (0/0)                                                                                                                                                               
> Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/home/societal-node/.local
> ```
> 
> Can you please look into it?
> 
> Thanks

Hi @Ali-Usama, good catch! I've fixed the problem creating the `.local` directory before running the docker-compose.

**Comment by Ali-Usama** [comment]
Thank you for the quick fixes @okalenyk. A detailed evaluation can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/911).

**Comment by dsm-w3f** [comment]
@okalenyk thank you for the submission and @Ali-Usama thanks for the evaluation. One doubt, the correct license is Apache 2.0 or Unlicense? The deliverables table says Apache 2.0 and in the repository is Unlicense. The evaluation looks good to me. The only points that I would add are that the testing coverage could be higher (~60%) in the pallet and there are some cargo clippy warnings that could be fixed. I'll wait for the answer and possible fix of the license before merging.

**Comment by okalenyk** [comment]
> @okalenyk thank you for the submission and @Ali-Usama thanks for the evaluation. One doubt, the correct license is Apache 2.0 or Unlicense? The deliverables table says Apache 2.0 and in the repository is Unlicense. The evaluation looks good to me. The only points that I would add are that the testing coverage could be higher (~60%) in the pallet and there are some cargo clippy warnings that could be fixed. I'll wait for the answer and possible fix of the license before merging.

Hi @dsm-w3f! Thanks for the review! We've fixed the license as well as clippy warnings in the latest revision of the milestone submission source code. We've also added more unit tests to the dao-subscription pallet to increase the coverage.

**Comment by dsm-w3f** [comment]
@okalenyk thank you for the improvements and fixes. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Pull request merged**
