### PR TITLE
Create validators_selection_2.md

### PR DESCRIPTION
**Pull request by miepsik**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1326 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by randombishop** [comment]
Thanks for this delivery @miepsik, will evaluate and get back to you in coming days...

**Comment by randombishop** [comment]
Hi @miepsik !

I am getting an error when I try `pip3 install -r requirements.txt`

```
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.4.0
```

My python version is `3.9.6`

Also tried after `pip install --upgrade pip setuptools wheel` but still got the same error.

Can you please provide a fix?

Thank you!

**Comment by miepsik** [comment]
Hi @randombishop , thanks for the feedback.
The environment was setup for python 3.8. I added the description how to run it with python 3.9

**Comment by randombishop** [comment]
@miepsik Thank you for the updated requirements file. Now managed to install and run the tests locally.

But the same error shows in docker build even if it's using python 3.8

Command:
```
docker build -t "validators_selection:Dockerfile" .
```

See log file 
[validator_selection_docker.log](https://github.com/w3f/Grant-Milestone-Delivery/files/10883455/validator_selection_docker.log)

Can you please clean your docker history and see if you can reproduce in your environment, then commit a fix?

Thanks!

**Comment by miepsik** [comment]
@randombishop thanks for the review. They have updated this docker image in the meantime with the newer pip version that no longer holds torch 1.4.0. I changed this version for the one that is available in the pip version in this image

**Comment by randombishop** [comment]
Thank you @miepsik !
Docker works fine now.
Question about deployment and average response time measurements, did you deploy a server and test it as mentioned in the deliveries? I can't find the link in the readme?

**Comment by miepsik** [comment]
Thanks @randombishop . Yes I deployed and tested it. Times were provided in the readme but in a not clear way. Now the time is clearly visible for each of the three endpoints. The server was deployed on my resources and it was turned off after the measurements so there is no link. However, I'm in touch with a team that will deploy this server and use it.

**Comment by randombishop** [comment]
Thanks for the clarification @miepsik, I went ahead and accepted your delivery.
Here are my evaluation notes: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/validator_selection_2_randombishop.md

**Comment by randombishop** [comment]
@miepsik I forwarded your invoice to accounting, please expect up to 2 weeks for processing.
Cheers!

**Comment by miepsik** [comment]
Thanks @randombishop . One more question - can you provide a server for the deployment? We are going to integrate it and the frontend is nearly ready so we need a server to set up the backend

**Comment by randombishop** [comment]
> Thanks @randombishop . One more question - can you provide a server for the deployment? We are going to integrate it and the frontend is nearly ready so we need a server to set up the backend

Unfortunately, we don't provide servers to grantees. Maybe you can try a treasury proposal to fund the deployment and maintenance of the solution as a public good for the ecosystem?

**Comment by randombishop** [comment]
@jonasW3F I agree with you that this should definitely be deployed and hopefully adopted by the community and ultimately integrated in the staking UX etc.
But with that, the Grants Program policy is generally a no-go for centralized deployments and hosting.
We can support maintenance grants to fix or add features to existing repos; but not hosting.
That's why I recommended a treasury proposal in-chain instead. Given the low cost of servers it should be possible to convince the community to accept funding it as a public good.

**Pull request merged**
