### PR TITLE
Evaluation "polkadot js extension per account auth" milestone 1 

### PR DESCRIPTION
**Pull request by CrommVardek**
[Link to PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/501)

Overall the features are well developed and has already been merged to the polkadot-js extension's master branch.

There are two missing steps of the delivery : the article and the documentation. Not problematic in my opinion. This is why I think the status should be accepted.

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the external evaluation. I’m going to merge it already. However, not sure I agree with the acceptance. I guess the [PR](https://github.com/polkadot-js/extension/pull/1068) including the video and inline documentation counts as documentation. But an article would have still been nice.

**Comment by CrommVardek** [comment]
@Noc2 : Thanks, I was hesitant to mark it as accepted, mostly because of the documentation honestly. Maybe I should have inform the PR author to update his delivery to include both the doc and the article before marking my evaluation as accepted - since then it has been done by takahser.  

My KSM address is correct : )

**Comment by CrommVardek** [comment]
@Noc2 : I'm unsure about the delay between the merging of an external evaluation and the transfer, but I have not received a transfer yet (https://kusama.subscan.io/account/JCkD7cRTpfkQmk5v6XvWvR1JPTvrouPXSGmQqtWPcJQKFzx?tab=transfer)

**Comment by Noc2** [comment]
Thanks for chasing us. I will ask the operation team about it.

**Comment by RouvenP** [comment]
hi @CrommVardek thank you - the KSM will be sent tomorrow.

**Pull request merged**
