### PR TITLE
Quadratic Funding Pallet Milestone-2 Delivery

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
@zhangjiannan Thanks for the delivery. We will look into it as soon as possible. Just to double check: You are aware that you don’t get paid for this milestone according to the most recent amendment: https://github.com/w3f/Open-Grants-Program/blob/master/applications/dorahacks-quadratic-funding.md#milestone-2-----frontend-integration

**Comment by zhangjiannan** [comment]
@Noc2 Hi David, yes I'm aware of the amendment. We would like to complete the frontend integration and demonstrate a working quadratic funding grant based on Substrate.

**Comment by Noc2** [comment]
Makes sense. I just noticed that you are updating your first delivery, since the file didn’t have a milestone number in the name. Could you change this? Your second delivery should simply add the following file to the repo: “quadratic-funding-pallet_2.md”.

**Comment by Noc2** [comment]
Btw. I quickly looked at the delivery. “Connecting to PolkadotJS extension” doesn’t seem to be implemented.

**Comment by zhangjiannan** [comment]
@Noc2 just fixed the names. When proceed to voting, Polkadot JS Extension is required to install. If not installed, the website will ask users to install. Is there a problem when connecting Polkadot JS Extension to vote?

**Comment by Noc2** [comment]
@zhangjiannan Sorry for the late response. I think it currently no longer works, because the round is closed. Could you start a new round and I will try it again? Is there a way for me to test it local?

**Comment by Noc2** [comment]
Hi @zhangjiannan Any update on this?

**Comment by zhangjiannan** [comment]
Hi @Noc2 we are completing Substrate MolochDAO v1 now. Once we complete that, we will set up another testing environment for this milestone, will take a few more days.

**Comment by tinydjp** [comment]
Hi @Noc2 ，I've just extended the grant expiration date, could you please retry?

**Comment by Noc2** [comment]
Thanks for the update. I will take a look at it today.

**Comment by Noc2** [comment]
@tinydjp I just took a quick look at it and it seems I can not really test it at the moment, because the UI says “No Project On Board Yet”.

**Comment by tinydjp** [comment]
@Noc2 Sorry for the inconvenience, some of our cloud services are due, it took us a day or two to recover. You should be able to see the ranking and vote now. Currently, the projects are all registered with `DAVE` account，so after ending round you can check its balance via  https://polkadot.js.org/apps/#/accounts . One more thing, you may need to transfer some Unit to your account which will be used to vote. If any problems encountered, please let me know.

**Comment by tinydjp** [comment]
> @tinydjp I just took a quick look at it and it seems I can not really test it at the moment, because the UI says “No Project On Board Yet”.

BTW, polkadot just upgraded, which will lead to no balance displayed in accounts tab. Just navigate to  Settings->Developer, and paste the json then save.
```
{
  "AccountInfo": "AccountInfoWithRefCount"
}
```

**Comment by Noc2** [comment]
Thanks for the update. It works now and you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dorahacks-quadratic-funding_2_Noc2.md), but it’s definitely far from perfect and I recommend to further improve it and test it. Also let me know in case you make the code publicly available, in this case I could take another look at it.

**Comment by zhangjiannan** [comment]
Hi @Noc2 thanks for the update! We are working on several improvements on HackerLink QF grants in general -- usability, anti-sybil staking, and reducing inequality of fund distribution from the QF grants. We expect to run it on some parachain soon, will update here as we progress.

**Pull request merged**
