### PR TITLE
Delivery: Project Aurras MVP - Phase 2 - Milestone 3

### PR DESCRIPTION
**Pull request by MuhammedIrfan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/814

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @MuhammedIrfan we have a bit of a backlog at the moment but an evaluator will be able to take a look in the next few days.

**Comment by MuhammedIrfan** [comment]
> Thanks for the delivery @MuhammedIrfan we have a bit of a backlog at the moment but an evaluator will be able to take a look in the next few days.

Sure @keeganquigley, No problem 😊

**Comment by MuhammedIrfan** [comment]
@keeganquigley, Hope you are doing well, I see that you have assigned the PR to you. I just wanted to check if you are facing any trouble with the milestone delivery. We are here to assist you in making the evaluation as smooth as possible.

**Comment by keeganquigley** [comment]
Sorry for the delay @MuhammedIrfan I'm taking a look at this today!

**Comment by keeganquigley** [comment]
Hi @MuhammedIrfan sorry again for the delay. I have a couple of questions:

- The video doesn't seem to be matching up with the instructions for this milestone. Which branch should I be on? Right now I'm using the `next` branch. For example in the video I'm not seeing anything about updating the FIREBASE_API_KEY.
- Some of these [tests](https://github.com/HugoByte/aurras/blob/next/docs/integration-testing.md) are from two years ago. Should I only be completing the tests for payout notification example?
- Where should I be updating the FIREBASE_API_KEY? I'm not seeing any example .env files. Should I just be updating it in deploy.sh? Or in the PayoutNotification.yaml file? I don't see anywhere for it in there. Same goes for DEVICE_TEST_TOKEN.
- When you say to "generate a server token", I'm guessing that means a web push certificate keypair?

keypair

This is my first time evaluating the project and I know there has been a lot of progress but I'm just catching up. Thanks for any assistance you can provide!

**Comment by Mr-Nobody21** [comment]
@keeganquigley 
The tests are in integration-testing-for-payout-notify [Testing guide](https://github.com/HugoByte/aurras/blob/next/docs/integration-testing-for-payout-notify.md)

For Firebase API key:-
[Firebase config location](https://github.com/HugoByte/aurras/blob/6b696e771f3d462ba56356b83783d20913df85f8/examples/payout-notification/src/config/firebase.js)
`export FIREBASE_API_KEY=<Your API Key>`
When you say to "generate a server token", I'm guessing that means a web push certificate keypair? :- Instead of Web Configurations in FCM we have to generate Cloud Messaging API (Legacy)

image

**Comment by Mr-Nobody21** [comment]
@keeganquigley Thank you for reviewing.

> * The video doesn't seem to be matching up with the instructions for this milestone. Which branch should I be on? Right now I'm using the `next` branch. For example in the video I'm not seeing anything about updating the FIREBASE_API_KEY.

The [video](https://www.youtube.com/watch?v=Tkk86peAkG8) is specific for polkadot payout, Firebase setup can be found in the video
 

> * Some of these [tests](https://github.com/HugoByte/aurras/blob/next/docs/integration-testing.md) are from two years ago. Should I only be completing the tests for payout notification example?

The tests in integration-testing-for-payout-notify are to tested [Testing guide](https://github.com/HugoByte/aurras/blob/next/docs/integration-testing-for-payout-notify.md)



> * Where should I be updating the FIREBASE_API_KEY? I'm not seeing any example .env files. Should I just be updating it in deploy.sh? Or in the PayoutNotification.yaml file? I don't see anywhere for it in there. Same goes for DEVICE_TEST_TOKEN.

For Firebase API key:- [Firebase config location](https://github.com/HugoByte/aurras/tree/6b696e771f3d462ba56356b83783d20913df85f8/examples/payout-notification)

> * When you say to "generate a server token", I'm guessing that means a web push certificate keypair?

Instead of Web Configurations in FCM we have to generate *Cloud Messaging API (Legacy)*
image

**Comment by keeganquigley** [comment]
Thanks for the help @Mr-Nobody21 this video differs from the one in the deliverables, hence the reason for my confusion. Also, the video is 17 minutes long. 

- Could you point to where (in the video) the instructions are for setting the Firebase key? I'm not sure which steps in this video apply to this milestone. Understood that I need to use the legacy Cloud Messaging API.
- I'm not sure you answered my question about the branch. Should I be using `next` branch (set as the default) or the `master` branch? Or `feature/UI-for-polkadot-payout`?
- Am I supposed to have a local Aurras node running while completing these tasks?
- Do I need to be running the [deployment instructions](https://docs.aurras.hugobyte.com/dependencies/openwhisk/deployment) for Kubernetes and Docker Compose, or were those from a previous milestone?

**Comment by keeganquigley** [comment]
UPDATE: I was able to set the API server key and successfully run `./deploy.sh` but it failed, I think because of my Apple ARM64 chip. I will have to try again on Ubuntu.

```sh
73d61506f446: Download complete
15518faa499b: Pull complete
73d61506f446: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:e706aab3cc002471008f31b0fe80b7003d8cdd2f66bd32dd6f122cd6adbb7816
Status: Downloaded newer image for hugobyte/openwhisk-runtime-rust:v0.3
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023/11/23 00:00:36 warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /usr/src/action_loop/Cargo.toml
workspace: /usr/src/Cargo.toml
    Updating crates.io index
    Updating git repository `https://github.com/hugobyte/aurras`
warning: spurious network error (3 tries remaining): failed to create locked file '/usr/local/cargo/git/db/aurras-7a79c31b974d5a1e/objects/pack/pack_git2_43080ff061ceidx.lock': Read-only file system; class=Os (2)
warning: spurious network error (2 tries remaining): failed to create temporary file '/usr/local/cargo/git/db/aurras-7a79c31b974d5a1e/objects/pack/pack_git2_a9b249b199e400f7': Read-only file system; class=Os (2)
warning: spurious network error (1 tries remaining): failed to create temporary file '/usr/local/cargo/git/db/aurras-7a79c31b974d5a1e/objects/pack/pack_git2_2b47ecf3648617ff': Read-only file system; class=Os (2)
error: failed to get `actions-common` as a dependency of package `actions v0.1.0 (/usr/src/actions)`

Caused by:
  failed to load source for dependency `actions-common`

Caused by:
  Unable to update https://github.com/hugobyte/aurras?rev=1f7e117

Caused by:
  failed to clone into: /usr/local/cargo/git/db/aurras-7a79c31b974d5a1e

Caused by:
  failed to create temporary file '/usr/local/cargo/git/db/aurras-7a79c31b974d5a1e/objects/pack/pack_git2_a366568d220d2482': Read-only file system; class=Os (2)
ERRO[0206] Error waiting for container: container 8a98a5e9a3fb6eff3bcc0bb6b7e7ac1f539b5cf58a0c9eb40f56e9eb439c07f4: driver "overlay2" failed to remove root filesystem: unlinkat /var/lib/docker/overlay2/6afa21c1800a1ca9b7e1ac5f755536fbb00d3d660a1f4ec7b574865be566d4ed: read-only file system
```

**Comment by Mr-Nobody21** [comment]
@keeganquigley 

> * I'm not sure you answered my question about the branch. Should I be using `next` branch (set as the default) or the `master` branch? Or `feature/UI-for-polkadot-payout`

code for this milestone is in `next` 

> * Am I supposed to have a local Aurras node running while completing these tasks?

You can either run locally or run it on an linux server

> * Do I need to be running the [deployment instructions](https://docs.aurras.hugobyte.com/dependencies/openwhisk/deployment) for Kubernetes and Docker Compose, or were those from a previous milestone?

You need to have aurras running to test polkadot payout

> UPDATE: I was able to set the API server key and successfully run `./deploy.sh` but it failed, I think because of my Apple ARM64 chip. I will have to try again on Ubuntu.

Please let me know if you face any issues

**Comment by keeganquigley** [comment]
Thanks for the changes @MuhammedIrfan and sorry for the delay. I was new to this project, so it took me a while to configure Google Firebase, OpenWhisk, OpenWhisk CLI, and all the dependencies. I was able to run the notification example, with Ubuntu, and you can find my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_3_keeganquigley.md).

**Comment by MuhammedIrfan** [comment]
> Thanks for the changes @MuhammedIrfan and sorry for the delay. I was new to this project, so it took me a while to configure Google Firebase, OpenWhisk, OpenWhisk CLI, and all the dependencies. I was able to run the notification example, with Ubuntu, and you can find my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_3_keeganquigley.md). The delivery has hereby been accepted. Congrats on finishing the grant!

No problem @keeganquigley, Thank you very much for the support.

**Pull request merged**
