### PR TITLE
SydTek_Milestone1.md

### PR DESCRIPTION
**Pull request by jgophd**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1183

### CODE REVIEW

**Comment by jgophd** [comment]
All checklist items have been completed.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the delivery, @jgophd. We will look into it as soon as possible.

In the meantime, could you replace the delivery template? Your PR currently deletes it.

**Comment by jgophd** [comment]
> Thanks for the delivery, @jgophd. We will look into it as soon as possible.
> 
> In the meantime, could you replace the delivery template? Your PR currently deletes it.

@semuelle, thank you for your quick response. How do I replace the template, as I cannot do so on my end?

**Comment by semuelle** [comment]
> How do I replace the template

You [renamed the template](https://github.com/w3f/Grant-Milestone-Delivery/pull/641/commits/38074db809a205da5847597d5cdf51f2a3e72409) in your repository. It should be resolved if you just copy the [template](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) back into your deliveries folder.

**Comment by jgophd** [comment]
> > How do I replace the template
> 
> You [renamed the template](https://github.com/w3f/Grant-Milestone-Delivery/pull/641/commits/38074db809a205da5847597d5cdf51f2a3e72409) in your repository. It should be resolved if you just copy the [template](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) back into your deliveries folder.

@semuelle, I think it is not resolved as all checks have now passed.

**Comment by semuelle** [comment]
It looks like you deleted and recreated your delivery file, but didn't touch the template at all. Try creating a `milestone-delivery-template.md` file in the applications folder with the original contents.

**Comment by jgophd** [comment]
> It looks like you deleted and recreated your delivery file, but didn't touch the template at all. Try creating a `milestone-delivery-template.md` file in the applications folder with the original contents.

@semuelle, can you check to see if I copied and created the file correctly?

**Review by semuelle — CHANGES_REQUESTED** [review]
> @semuelle, can you check to see if I copied and created the file correctly?

Almost. I moved it into the `deliveries` folder, now it is resolved. 

Thanks again for the delivery. I have a couple of questions:

1. I assumed the deliverable covering "an overview of the current state of the soulbound tokens" would be a text. A long list of citations is useful, but it's not what I would call an "overview". Do you have any texts or other materials derived from this that you could share?
2. There are no links and quotes from line 102 onwards in the Lit Matrix Master tab. Is this still in progress?
3. Could you put a copy of the file into the repository? Otherwise involving Github in the process doesn't make much sense. Ideally, it would be as a CSV file (Google Sheets lets you export as CSV) so the material is discoverable, but xlsx would work.

**Comment by jgophd** [comment]
> > @semuelle, can you check to see if I copied and created the file correctly?
> 
> Almost. I moved it into the `deliveries` folder, now it is resolved.
> 
> Thanks again for the delivery. I have a couple of questions:
> @semuelle, please see my responses to your questions below:

> 1. I assumed the deliverable covering "an overview of the current state of the soulbound tokens" would be a text. A long list of citations is useful, but it's not what I would call an "overview". Do you have any texts or other materials derived from this that you could share?
- Please see the updated milestone deliverable. I have included an overview document that will act as the foundation for the soulbound token section of the literature review.
> 2. There are no links and quotes from line 102 onwards in the Lit Matrix Master tab. Is this still in progress?
- The references after 102 are references we included for milestone 2. Will it resolve confusion if I just remove them? These references weren't in scope for milestone 1, but I included them in the document, given we came across them when performing milestone 1 research.
> 3. Could you put a copy of the file into the repository? Otherwise involving Github in the process doesn't make much sense. Ideally, it would be as a CSV file (Google Sheets lets you export as CSV) so the material is discoverable, but xlsx would work.
- I created a CSV file of the Google Sheets per your request and added them to the repo.

**Comment by semuelle** [comment]
Thanks for the update, @jgophd! 

> Will it resolve confusion if I just remove them?

No need. I just wanted to check if they are part of this milestone.



> I created a CSV file of the Google Sheets per your request and added them to the repo.
> Please see the updated milestone deliverable. I have included an overview document that will act as the foundation for the soulbound token section of the literature review.

These are great. Only I was referring to [your repository](https://github.com/jgophd/Developed-Materials-and-Raw-Data). This repository should only contain the delivery document, no other material. Sorry for the confusion.

**Comment by jgophd** [comment]
> Thanks for the update, @jgophd!
> 
> > Will it resolve confusion if I just remove them?
> 
> No need. I just wanted to check if they are part of this milestone.
> 
> > I created a CSV file of the Google Sheets per your request and added them to the repo.
> > Please see the updated milestone deliverable. I have included an overview document that will act as the foundation for the soulbound token section of the literature review.
> 
> These are great. Only I was referring to [your repository](https://github.com/jgophd/Developed-Materials-and-Raw-Data). This repository should only contain the delivery document, no other material. Sorry for the confusion.

@semuelle, thank you for your quick response. I added the documents to my repo and removed them from the other.

**Comment by semuelle** [comment]
Thanks for the update. Looks good now.
One last request: your repository currently doesn't contain a license, so technically the work is copyrighted. Could you [add a license](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository#including-an-open-source-license-in-your-repository)? Since your application mentions public domain, I'd suggest the `Unlicense`.

**Comment by jgophd** [comment]
> 

@semuelle, thanks for this. The Unlicense has been added to the repo.

**Comment by semuelle** [comment]
Thanks for the quick reply. Your milestone is hereby accepted.

You can find my evaluation sheet [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sydtek_1_semuelle.md). I saw that you submitted an invoice, but it's currently missing W3F's data (Web 3.0 Technologies Foundation, Baarerstrasse 14, 6300 Zug, Switzerland, UID / VAT ID: CHE-322.596.347). Could you resubmit?

**Comment by jgophd** [comment]
> here

@semuelle, thank you for this. I just resubmitted the invoice. Could you double-check to see if everything is good now?

**Comment by semuelle** [comment]
Looks good. Thanks. I have forwarded it for processing.

**Comment by RouvenP** [comment]
hi @jgophd we transferred the payment today.

**Pull request merged**
