### PR TITLE
Kuma Wallet evaluation milestone 4

### PR DESCRIPTION
**Pull request by Ali-Usama**
# External Evaluation

The delivery is as per the application and no major issues were found. A detailed evaluation is attached. 

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1414
Link to milestone pull request: https://github.com/w3f/Grant-Milestone-Delivery/pull/976

### CODE REVIEW

**Comment by Whisker17** [comment]
Hey @Ali-Usama, I am very happy that you are actively participating in external evaluations, but I hope that you can follow the rules set by the GRANT TEAM so that external evaluations can be conducted in a more orderly manner. Please check the replies [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/952#issuecomment-1667296711) and do not open a new external evaluation when you still have unmerged evaluations.

cc @semuelle @dsm-w3f @keeganquigley

**Comment by dsm-w3f** [comment]
@Ali-Usama thank you for posting this external evaluation. As mentioned in the previous comment, seem that you was working in two external evaluations at same time. This is against our guidelines. Unless this is not the case, I'll close this evaluation. Any comments on that?

**Comment by Ali-Usama** [comment]
> @Ali-Usama thank you for posting this external evaluation. As mentioned in the previous comment, seem that you was working in two external evaluations at same time. This is against our guidelines. Unless this is not the case, I'll close this evaluation. Any comments on that?
I thought the guidelines are about not opening multiple draft PRs, which I didn't.

**Comment by dsm-w3f** [comment]
@Ali-Usama thank you for the external evaluation. It is approved. I'll forward your KSM payment. Great job! About the previous discussion in the evaluation, I think there is no problem to be merged since our guidelines by the time that it was open could leave some doubts about the moment that the evaluation is finished.

**Pull request merged**
