### PR TITLE
DIA Bridgestate Milestone 2

### PR DESCRIPTION
**Pull request by kaythxbye**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1887

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @kaythxbye I'm not seeing that the [requested changes](https://github.com/w3f/Grant-Milestone-Delivery/pull/964) in the external evaluation have been implemented yet. Are you planning to make these changes soon? Policy-wise, we allow two weeks to make changes. Please let me know if you need more time.

**Comment by kaythxbye** [comment]
Hey @keeganquigley sorry for the delay, I was OOO last week. I will check internally and follow up with an update shortly.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the changes @kaythxbye and the evaluation @dastansam I left some additional comments in the private channel, if you can take a look.

**Comment by keeganquigley** [comment]
Thanks for making the changes @kaythxbye looks good now. Thanks for fixing most of the Cargo clippy warnings as well. Your delivery has been accepted. I will forward your invoice for processing.

**Comment by RouvenP** [comment]
hi @kaythxbye we just transferred the payment.

**Pull request merged**
