### PR TITLE
Tuxedo parachain milestone 1

### PR DESCRIPTION
**Pull request by JoshOrndorff**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1932

### CODE REVIEW

**Review by semuelle — APPROVED** [review]
Hi @JoshOrndorff. Thanks for the delivery. I have reviewed all deliverables and everything is in great shape. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tuxedo-parachain_1_semuelle.md).

I submitted a PR against your README because I had some issues with the docker commands. Otherwise great delivery as usual.

**Comment by JoshOrndorff** [comment]
Thank you for your review and accepting our milestone. 

Thanks also for being a tuxedo contributor :rocket:

for tuxedo contributors including samuelle

**Comment by semuelle** [comment]
@JoshOrndorff, have you submitted an invoice yet?

**Comment by semuelle** [comment]
pinging @JoshOrndorff

**Comment by JoshOrndorff** [comment]
It seems I have not submitted the invoice yet. I lost track of this while teaching at PBA. I will do it very soon.

**Pull request merged**
