### PR TITLE
Milestone 3 Submission.

### PR DESCRIPTION
**Pull request by Romulus10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/748

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @Romulus10. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @Romulus10. Sorry for the wait. I am now reviewing your milestone. 

I succesfully built everything and followed the "Testing Milestone 3" instructions. I get a "Welcome to Fennel Server" message on the server, but when I run `cargo run create-identity` through the CLI, it seems to be stuck at `Setting up a new keypair...`. Is this supposed to take more than 20 minutes?

**Comment by Romulus10** [comment]
On first run, the CLI generates an RSA key it uses to identify your client session to the server. This is currently pretty slow, since the generation function makes a direct call to the RSA crate. Integration with GPG instead is planned. Does the server produce any output while the client is running?

**Comment by semuelle** [comment]
> Does the server produce any output while the client is running?

No. I'll try again tomorrow, maybe I was too impatient. But I'm pretty sure there was no progress indication anywhere. Are there any restrictions on what the ID can/should be?

**Comment by Romulus10** [comment]
Currently, the ID is just a 32-bit integer to be used as a 'pointer' by applications to group identity traits.
I've been working through some possible ways to speed things up, so I'll push those forward and see if we can cut down on the runtime limitations of this version.

**Comment by semuelle** [comment]
Thanks for the update, @Romulus10. I did make some progress, but it still seems to be stuck, at least after the identity creation. I get 

```sh
Setting up a new keypair...
Finished.
Instantiate TransactionHandler
Submit a new identity to the Fennel network.
Fennel Protocol Identity successfully created.
Next available ID was 1
```

on the CLI, and 

```sh
Welcome to Fennel Server
begin handling new connection
```

on the server. The code tells me there should be more output, but it's been stuck there for the past 20 min. 

I had to use the second last commit of `fennel-server`, because the build was failing with 

```sh
❯ ./scripts/build-test.sh
   Compiling fennel-server v0.1.0 (/deliverables/fennel/fennel-server)
error[E0308]: mismatched types
  --> src/server/mod.rs:42:26
   |
42 |                 message: [0; 512],
   |                          ^^^^^^^^ expected an array with a fixed size of 1024 elements, found one with 512 elements

error[E0308]: mismatched types
  --> src/server/mod.rs:43:28
   |
43 |                 signature: [0; 512],
   |                            ^^^^^^^^ expected an array with a fixed size of 1024 elements, found one with 512 elements

...
```

Could that be the issue?

**Comment by Romulus10** [comment]
Yes - sorry about that, I figured you'd use the latest commit but completely forgot to consider the update to the dependencies. The most recent commit for both the CLI and server are both going to need a `cargo update` to bring shared structs from fennel-lib up to date.

**Comment by semuelle** [comment]
Thanks, @Romulus10, that did the trick. 

Your milestone is hereby accepted. I will forward your invoice for processing.

**Pull request merged**
