### PR TITLE
silent_data-milestone_1.md

### PR DESCRIPTION
**Pull request by annazambon**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1137 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @annazambon. Thanks for the delivery. We will look into it as soon as possible. 

Why are `silentdata-defi-core` and `silentdata-defi-app` private? It seems to me that they are part of the grant and there should be published under MIT.

**Comment by annazambon** [comment]
Hi Sebastian,We've submitted public links for all the required documents. In addition, we’ve added the silentdata-defi-core and the silentdata-defi-app links as additional documents just in case you want to control the code.All the best,AnnaIl giorno 18 apr 2023, alle ore 15:22, Sebastian Müller ***@***.***> ha scritto:﻿
Hi @annazambon. Thanks for the delivery. We will look into it as soon as possible.
Why are silentdata-defi-core and silentdata-defi-app private? It seems to me that they are part of the grant and there should be published under MIT.

**Comment by keeganquigley** [comment]
Thanks for the delivery @annazambon I am starting my evaluation. However the links you provided still don't work because the `silentdata-defi-core` and `silentdata-defi-app` repositories are still private. Are you planning on publishing these?

**Comment by annazambon** [comment]
Hi Keegan,Thank you for updating me on this.As stated before, we’ve submitted public links for all the required documents. In addition, we’ve added the silentdata-defi-core and the silentdata-defi-app links as additional documents just in case you want to control the code, that’s why these are private.Il giorno 21 apr 2023, alle ore 19:02, Keegan | W3F ***@***.***> ha scritto:﻿
Thanks for the delivery @annazambon I am starting my evaluation. However the links you provided still don't work because the silentdata-defi-core and silentdata-defi-app repositories are still private. Are you planning on publishing these?

**Comment by keeganquigley** [comment]
Thanks @annazambon so are you saying that [silentdata-defi-enclave](https://github.com/appliedblockchain/silentdata-defi-enclave) is the only repo that pertains to this milestone? As was [noted](https://github.com/w3f/Grants-Program/pull/1137#issuecomment-1334965631) during the application process, all code delivered must be open-sourced and also not rely on closed-source software for full functionality. 

Also it sounds like I would need to be added for read-only access regardless.

**Comment by keeganquigley** [comment]
@annazambon I also noticed that your article mentions a partnership with the Polkadot Foundation, but there is no such entity as far as I'm aware. We also ask that teams wait until the first milestone is completed before publishing an article, as noted in our [announcement guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md). Before publishing we typically ask that it is sent to grantsPR@web3.foundation beforehand for proofreading.

**Comment by annazambon** [comment]
Hi Keegan,
Thank you for pointing that out.
We've made the amendments and shared the closed link with
***@***.*** for their review.

Kind regards,
Anna

**Comment by keeganquigley** [comment]
Thanks @annazambon were you able to add me for read-only access?

**Comment by keeganquigley** [comment]
You can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/silentdata_1_keeganquigley.md). Note that Docker works but `npm run build` currently fails with errors as you'll see in my notes.

**Comment by annazambon** [comment]
Hi Keegan,

Thanks for sharing the initial evaluation. It should work now, can you
please double check?

Many thanks,
Anna

**Comment by annazambon** [comment]
Hi Keegan,

I confirm that we gave you read-only access to the docs.

All the best,
Anna

**Comment by keeganquigley** [comment]
Thanks for the access @annazambon I can confirm that it worked for `silentdata-defi-core` but not `silentdata-defi-app`. Can you also explain the reasoning for not wanting to make these repos public? Since they are part of the deliverables I believe they would fall under the MIT license, and therefore they would need to be made public to meet our [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/T%26Cs.md). Otherwise we may not be able to accept the delivery.

**Comment by campbell-codes** [comment]
Hi Keegan,

Thanks for your feedback. I think there may be some context missing here.

Silent Data is an existing platform developed by us for doing privacy preserving checks off chain and utilising proof of these checks in smart contracts.

The grant was issued to develop an SDK and smart contracts on Polkadot for validating Silent Data check. We have open sourced all the components developed as part of this grant.

Let me know any questions also happy to jump on a call.

All the best,
Andy.

**Comment by keeganquigley** [comment]
@campbell-codes friendly ping.

**Comment by keeganquigley** [comment]
Thanks @campbell-codes for the friendly call and for clearing up the issue. I'm more confident now that the repos aren't related to the extension part of the delivery and shouldn't have originally been included. Therefore I'm willing to pass the milestone, and you can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/silentdata_1_keeganquigley.md).

**Comment by RouvenP** [comment]
hi @annazambon we transferred the payment today

**Pull request merged**
