### PR TITLE
Web3 RPC Grant Milestone 1 Deliverable

### PR DESCRIPTION
**Pull request by dtyoo**
# Milestone Delivery Checklist

- [ X ] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ X ] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [ X ] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [ X ] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 

Hi David, let me know if you hit any issues or if you have any questions.

Thanks,

Derek

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @dtyoo. Thanks again for the delivery and we will try to look into it as soon as possible.

**Comment by Noc2** [comment]
Hi @derek I started to look into the project and in general it looks really good and I’m impressed by all the work you put into this. The only thing I found so far is that the docker part (https://github.com/PureStake/moonbeam/tree/moonbeam-tutorials#docker-image) doesn’t work for me. Could you look into this?
```
error[E0599]: no method named `sign` found for struct `ed25519_dalek::Keypair` in the current scope
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.19.2/src/identity/ed25519.rs:55:16
```

And some general tips: I saw the mb-session pallet contains no unit tests. In general I recommend to develop runtimes/pallets test driven (at least part of it), because it’s much faster to compile the tests.
And you might want to take a look at cargo remote in case, you are not aware of it: https://www.chevdor.com/post/2019/12/23/cargo-remote/

**Comment by crystalin** [comment]
Hi @Noc2. Derek asked me to reply directly to the ticket.

For the Docker image, you are right. I forgot to update the branch we were using in the Docker image, which didn't have a Cargo.lock
We have merged the fix. Can you try again after pulling the changes (still moonbeam-tutorials branch) ?
(We also provide a Docker image for Frontier template directly: https://github.com/paritytech/frontier/tree/master/template)

You are right for the tests, and we find it important too. Currently the pallets mb-session and mb-core are only for experimentation and not included in our runtime. We don't have yet a clear goal on what they are going to achieve or if they are used in our final implementation.
We focused our efforts on Frontier and have built a little test framework to accelerate our development on it
(see https://github.com/paritytech/frontier/tree/master/ts-tests)

**Comment by Noc2** [comment]
Thanks for the quick reply and fixes. I’m happy to confirm that this milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3-compatible-api_1_Noc2.md) and will now forward your invoice internally.

**Comment by dtyoo** [comment]
@Noc2 Thank you!

**Comment by RouvenP** [comment]
hi @dtyoo we just sent a test transaction. Could you please confirm if received?

**Comment by dtyoo** [comment]
@RouvenP confirming receipt of 0.01 BTC.

**Comment by RouvenP** [comment]
thanks for confirming. we transferred the remainder

**Comment by dtyoo** [comment]
@RouvenP the transfer of the remainder hasn't gone through.  we see it, but there are no confirmations.  is this expected given the amount of fees you specified for the transaction?

**Comment by dtyoo** [comment]
@RouvenP confirming that the remainder successfully transferred.  Thank you!

**Pull request merged**
