### PR TITLE
milestone 2 from ajuna

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/433 < please fill this in with the PR number of your application.

There have been two amendments:
1. https://github.com/w3f/Grants-Program/pull/1062
2. https://github.com/w3f/Grants-Program/pull/729

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @darkfriend77. We will look into it as soon as possible.

**Comment by lucasvanmol** [comment]
Hey there @darkfriend77, 

I'm trying to run the scaffolding setup in https://github.com/ajuna-network/Ajuna.SDK by following your helpful video (ToolChain.mkv). However I'm running into problems when I run `dotnet new ajuna ...`:

It works correctly until the `GenerateOpenApiDocuments` step: 

```
GenerateOpenApiDocuments:
    dotnet "/Users/lucasvanmol/.nuget/packages/microsoft.extensions.apidescription.server/3.0.0/build//../tools/dotnet-getdocument.dll" --assembly "/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/bin/Release/net5.0/SubNetTutorial.RestService.dll" --file-list "obj/SubNetTutorial.RestService.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v5.0" --output "obj" --project "SubNetTutorial.RestService" --assets-file "/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/obj/project.assets.json" --platform "AnyCPU" 
  SubNetTutorial.RestClient.Mockup -> /Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestClient.Mockup/bin/Release/netstandard2.0/SubNetTutorial.RestClient.Mockup.dll
/Users/lucasvanmol/.nuget/packages/microsoft.extensions.apidescription.server/3.0.0/build/Microsoft.Extensions.ApiDescription.Server.targets(62,5): error : You must install or update .NET to run this application. [/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/SubNetTutorial.RestService.csproj]

...
```

My guess is that I'm running .NET 6 :

```
lucasvanmol SubNetTutorial % dotnet --list-sdks           
6.0.302 [/usr/local/share/dotnet/sdk]
```

Whereas the above error is trying to run using .NET 5 - however since I'm running MacOS, that version [does not seem supported](https://docs.microsoft.com/en-us/dotnet/core/install/macos#supported-releases). Is there a way to run the command using .NET 6, or should I try the command on a Windows machine with .NET 5 installed?

By the way, feel free to also ping me on element in case I run into other problems or have other questions: [@lucas:web3.foundation](https://matrix.to/#/@lucas:web3.foundation). Thanks!

**Comment by darkfriend77** [comment]
> Hey there @darkfriend77,
> 
> I'm trying to run the scaffolding setup in https://github.com/ajuna-network/Ajuna.SDK by following your helpful video (ToolChain.mkv). However I'm running into problems when I run `dotnet new ajuna ...`:
> 
> It works correctly until the `GenerateOpenApiDocuments` step:
> 
> ```
> GenerateOpenApiDocuments:
>     dotnet "/Users/lucasvanmol/.nuget/packages/microsoft.extensions.apidescription.server/3.0.0/build//../tools/dotnet-getdocument.dll" --assembly "/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/bin/Release/net5.0/SubNetTutorial.RestService.dll" --file-list "obj/SubNetTutorial.RestService.OpenApiFiles.cache" --framework ".NETCoreApp,Version=v5.0" --output "obj" --project "SubNetTutorial.RestService" --assets-file "/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/obj/project.assets.json" --platform "AnyCPU" 
>   SubNetTutorial.RestClient.Mockup -> /Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestClient.Mockup/bin/Release/netstandard2.0/SubNetTutorial.RestClient.Mockup.dll
> /Users/lucasvanmol/.nuget/packages/microsoft.extensions.apidescription.server/3.0.0/build/Microsoft.Extensions.ApiDescription.Server.targets(62,5): error : You must install or update .NET to run this application. [/Users/lucasvanmol/dev/ajuna/SubNetTutorial/SubNetTutorial.RestService/SubNetTutorial.RestService.csproj]
> 
> ...
> ```
> 
> My guess is that I'm running .NET 6 :
> 
> ```
> lucasvanmol SubNetTutorial % dotnet --list-sdks           
> 6.0.302 [/usr/local/share/dotnet/sdk]
> ```
> 
> Whereas the above error is trying to run using .NET 5 - however since I'm running MacOS, that version [does not seem supported](https://docs.microsoft.com/en-us/dotnet/core/install/macos#supported-releases). Is there a way to run the command using .NET 6, or should I try the command on a Windows machine with .NET 5 installed?
> 
> By the way, feel free to also ping me on element in case I run into other problems or have other questions: [@lucas:web3.foundation](https://matrix.to/#/@lucas:web3.foundation). Thanks!

Hey Lucas, nice to meet you. Let me check on this matter. Will ping you.

**Comment by lucasvanmol** [comment]
Thanks again for the delivery and the help/changes you offered on Matrix. [Here is my in-progress evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ajuna-follow-up_2_lucasvanmol.md). As you'll see, there's only one deliverable I haven't yet accepted, regarding the persistance layer in service layer. You can see my questions about it there, in addition to some other questions I have on the bottom of the document. Could you please address them? Thank you!

**Comment by darkfriend77** [comment]
Let me try to answer your questions about the overall architecture @lucasvanmol.

_In my understanding, the Ajuna.SDK generates the following things:
C# code to interface with a node and its extrinsics (Ajuna.NetApiExt)
A rest api to have endpoints to poll the node's information and subscribe to events
Test and mockup code to test the above_
Is this correct? Not exactly, but let me try just to list up each artifact and explain.

[Ajuna.NetApi](https://github.com/ajuna-network/Ajuna.NetApi/tree/master/Ajuna.NetApi), is the basic framework for accessing and handling JSON-RPC connections and handling the generic RPC calls that every substrate nodes offer and are exposed by the rpc.methods(). It additionally implements rust primitives and generics as a C# representation like U8, BaseVec (Vec<>), or EnumExt (Rust-specific Enums). The [Ajuna.NetApi](https://github.com/ajuna-network/Ajuna.NetApi/tree/master/Ajuna.NetApi) has no types, so accessing the node storage or sending extrinsic would involve manually creating the necessary types.

[Ajuna.NetApiExt](https://github.com/ajuna-network/SubstrateNET/tree/master/SubstrateNET.NetApi) is the extension of the NetApi, with a generated client extension, adding all the node-specific types, storage access, extrinsic calls and more to the client. As an example here is the [FrameSystem](https://github.com/ajuna-network/SubstrateNET/blob/master/SubstrateNET.NetApi/Generated/Model/FrameSystem/MainSystem.cs). With the API and the Extensions, all possible interactions with a node and the specific network are given. However, if your application is targeted to be used by many consumers and needs to be on a high availability provide storage access or storage subscription, then accessing or subscribing straight to a node might be an issue in terms of scalability, but also in terms of efficiency.

[Ajuna.RestService](https://github.com/ajuna-network/SubstrateNET/tree/master/SubstrateNET.RestService), this service, in its core, just connects to a node and subscribes to the global storage changes, which are then maintained in memory. It holds all stored items exposed from a node and maintains them. On top, there is a REST service (poll) exposing all the storage information as REST, and additionally, there is a subscription service (pub/sub) providing changes over a WebSocket. This artifact is much more lightweight than the node and can be scaled according to the needs of the consumers without putting any load on an RPC node except for one connection for the global storage subscription.

[RestClient](https://github.com/ajuna-network/SubstrateNET/tree/master/SubstrateNET.RestClient) is the artifact used in the client application C#, Unity, or whatever is using the client to access the information. It is the counterpart for the previously described service, allowing you to subscribe to storage through the WebSocket or access storage through REST and providing it in an intuitive C# manner, where you can build events on stage changes and access REST by using the prepared node specific library. As an example, here is the pre-generated access for an account subscription ([subscribe](https://github.com/ajuna-network/SubstrateNET/blob/d42d23fa2f9bbd940df6b796ab1bd55a944b77fa/SubstrateNET.RestClient.Test/Generated/SystemControllerClientTest.cs#L109), [await](https://github.com/ajuna-network/SubstrateNET/blob/d42d23fa2f9bbd940df6b796ab1bd55a944b77fa/SubstrateNET.RestClient.Test/Generated/SystemControllerClientTest.cs#L117)) or getting the account through rest ([polling](https://github.com/ajuna-network/SubstrateNET/blob/d42d23fa2f9bbd940df6b796ab1bd55a944b77fa/SubstrateNET.RestClient.Test/Generated/SystemControllerClientTest.cs#L119)). This allows once you build your node specific SDK. You launched your Service to create Applications on top of the substrate without any further knowledge except the library usage.

This should empower any application to use the C# stack.

I hope this answers the relation/difference between NetApiExt, RestClient, and RestService.

For deliverable 3d, is there some tutorial/example/test that uses it?

_The framework for turn-based board-like games is really interesting. Are there plans/ideas for other types of games that might fit?_ Currently, we work towards providing the essentials for any turn-based game, further plans are in our partnered grant [here](https://github.com/w3f/Grants-Program/pull/893).

Repos relevant for this milestone:
- https://github.com/ajuna-network/Ajuna.NetApi - Ajuna NET API Framework
- https://github.com/ajuna-network/Ajuna.SDK - Ajuna SDK Toolchain
- https://github.com/ajuna-network/Ajuna - Ajuna node, including pallets used by this milestone
- https://github.com/ajuna-network/worker - Integritee worker (TEE environment)
- https://github.com/ajuna-network/SubstrateNET - An example SDK generated by Ajuna.SDK, includes a Unity demo.
- https://github.com/ajuna-network/backend-devel - Backend development environment used to setup/test the bot games, uses Ajuna & worker repos
- https://github.com/ajuna-network/Ajuna.NetApi/tree/post-decoded-workload - Includes to Dot4G bot from deliverable 5

**Comment by lucasvanmol** [comment]
Thanks for your detailed answer @darkfriend77 , in addition to the provided tutorial!
Sorry for the wait here - I was on holiday - but I'm happy to accept the delivery. I will forward your invoice internally.

**Comment by meldien** [comment]
@darkfriend77 @lucasvanmol 
Hi all, 
I noted you have the old billing address on the invoice. Could you please update the invoice with following address:
Web 3.0 Technologies Foundation
Baarerstrasse 14
6300 Zug
Switzerland 

Many thanks for your support. 

Best,
Melanie

**Comment by darkfriend77** [comment]
@meldien done.

**Comment by RouvenP** [comment]
hi @darkfriend77, according to your application the first milestone should be paid to 1FgaH4sRHF4boR4Fw316ddKMJbFpsDXGeL. The address on the invoice is 3H2shhx3GyMjc5Y4QuF9D5skbQgZDhvPMq. Which one should we use? If the latter, could you update the application accordingly?

Thanks

**Comment by RouvenP** [comment]
hi @darkfriend77 we transferred the payment today. Thanks!

**Pull request merged**
