### PR TITLE
Coong wallet evaluation

### PR DESCRIPTION
**Pull request by Ali-Usama**
# External Evaluation Coong Wallet
- The delivery needs some improvements as mentioned in the [evaluation form](https://github.com/w3f/Grant-Milestone-Delivery/commit/739113420ff5b734002a21cd66022d3671746399)

Link to the application pull request: [Coong Wallet](https://github.com/w3f/Grants-Program/blob/master/applications/coong_wallet.md)

### CODE REVIEW

**Comment by Ali-Usama** [comment]
The delivery is satisfactory after the recent commits to the milestone. The `docker build` and `yarn test` errors have been resolved and there are improvements in the inline documentation as well.

**Review by semuelle — APPROVED** [review]
Thanks for the evaluation, @Ali-Usama. We'll be in touch soon.

**Comment by semuelle** [comment]
Just double-checking: [this](https://github.com/w3f/Grant-Milestone-Delivery/blob/80a575f304a485ef4c5d7ab69ab70489d04c3e78/evaluations/coong_wallet-1-ali-usama.md?plain=1#L6) is your Kusama address, @Ali-Usama?

**Comment by Ali-Usama** [comment]
Yes @semuelle , that is mine

**Comment by RouvenP** [comment]
hi @Ali-Usama we transferred the KSM today.

**Comment by Ali-Usama** [comment]
yes @RouvenP , received. Thank you! :)

**Pull request merged**
