### PR TITLE
Liberland milestone 1 delivery

### PR DESCRIPTION
**Pull request by flipchan**
Here comes liberland's first milestone

# Milestone Delivery Checklist

 * [x]  The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
 * [x]  The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
 * [x]  This pull request is being made by the same account as the accepted application.
 * [x]  In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
 * [x]  The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/831  < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @flipchan. We will look into it as soon as possible. As you can already tell, we have a bit of a backlog, so it might take a few days. Please bear with us.

In the meantime, could you add the deliverables 0a to 0e to the table?

**Review by takahser — CHANGES_REQUESTED** [review]
@flipchan as already indicated by @semuelle the deliverables 0a-0e are currently missing. Please copy them over from [your contract](https://github.com/w3f/Grants-Program/blob/6c6cb6ecc51d6e0503821e56999759ae7770fc29/applications/liberland.md#milestone-1-citizens-llm-and-public-veto) and fill in the links & notes.

**Comment by flipchan** [comment]
@semuelle @takahser Thanks for the feedback, I will get these sorted out with  @michalptacnik

**Comment by flipchan** [comment]
@takahser @semuelle I have added 0a-0e

**Comment by takahser** [comment]
@DorianSternVukotic sounds good, thanks for the update!

**Comment by takahser** [comment]
Just for reference, I had a call with @DorianSternVukotic today and the Liberland team identified a few smaller bugs, that they'd like to fix. Also, they'll give notice as soon as these bugs are fixed.

**Comment by takahser** [comment]
@DorianSternVukotic thanks for the confirmation, I'm having a look right now.

Here are my first findings:

- The [twitter account](https://twitter.com/liberland) linked in your [README](https://github.com/liberland/liberland_substrate/) doesn't seem to be the correct one
- The link to the liberland logo seems to be [broken](https://github.com/liberland/liberland_substrate/blob/main/Liberland_official_znak.png)
- not an expert in Licenses, but I saw that you're claiming to use the MIT License:

  > All code that is committed on behalf of Liberland is contributed using the MIT license.

  However, there are currently 3 LICENSE files in the project root:

  image

  I assume, the other two are copied over from the substrate repo, which is fine I guess. However, on their repo they [indicate](https://github.com/paritytech/substrate/tree/982f5998c59bd2bd455808345ae1bd2b1767f353#license) which files use which License. Could you add this indication to your repo as well?

I'll have a deeper look and be back with more feedback soon.

**Review by takahser — CHANGES_REQUESTED** [review]
Thanks for the update, I took another look and have some additional comments:

- Regarding the limitation with PolkadotJs Apps, it might be a good idea to open up an [issue](https://github.com/polkadot-js/apps).
- I think from a UX perspective it would be good to have the account names listed here as well (not just the address):

    image

- Also, I noticed that it won't allow me to sign on with the credentials of the account that was created when I registered:

    image

Also FYI - I'll be on holiday next week, so I'll might not answer until the week after (from 12 December).

**Comment by flipchan** [comment]
> @DorianSternVukotic thanks for the confirmation, I'm having a look right now.
> 
> Here are my first findings:
> 
> * The [twitter account](https://twitter.com/liberland) linked in your [README](https://github.com/liberland/liberland_substrate/) doesn't seem to be the correct one
> * The link to the liberland logo seems to be [broken](https://github.com/liberland/liberland_substrate/blob/main/Liberland_official_znak.png)
> * not an expert in Licenses, but I saw that you're claiming to use the MIT License:
>   > All code that is committed on behalf of Liberland is contributed using the MIT license.
>   
>   
>   However, there are currently 3 LICENSE files in the project root:
>   image
>   I assume, the other two are copied over from the substrate repo, which is fine I guess. However, on their repo they [indicate](https://github.com/paritytech/substrate/tree/982f5998c59bd2bd455808345ae1bd2b1767f353#license) which files use which License. Could you add this indication to your repo as well?
> 
> I'll have a deeper look and be back with more feedback soon.

Twitter linked fixed, image fixed, licenses looked into and okey has been given

**Comment by flipchan** [comment]
@takahser should be all green now

**Comment by takahser** [comment]
Sorry for the delay, I pushed a first version of my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/506fbd5a62b76152c3eba7ebead70790dfaf1e84/evaluations/liberland_1_takahser.md).
Note that I wasn't sure how to get started with 1-4, because I wasn't able to get to the wallet application inside your frontend. Could you assist me here?


I have a few more comments:

- regarding _Fake sending LLM_ in your testing guide, usually we'd call this concept _Faucet_
- regarding _Legislation_, what exactly do you mean by the following?

    > In the future, this will be a headcount veto option but for now it is just a simple referendum repeal process.

- Since the 0.9% of all LLMs are minted each year, what happens after all LLM are minted (which will happen after ~111 years, if I'm not mistaken)?

    > decrease the total supply with 0.9 % per year mint 0.9% per year to the treasury with pallet assets

- Since there are lots of pallets you copied over from Substrate and a few you added or modified, maybe it would be useful to list all your pallets in the README

- I didn't really understand how I can navigate to the wallet application on the frontend. Can you provide assistance?

**Review by takahser — CHANGES_REQUESTED** [review]
@flipchan @DorianSternVukotic

Sorry for the delay, I pushed a first version of my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/506fbd5a62b76152c3eba7ebead70790dfaf1e84/evaluations/liberland_1_takahser.md).
Note that I wasn't sure how to get started with 1-4, because I wasn't able to get to the wallet application inside your frontend. Could you assist me here?

image

I have a few more comments:

- regarding _Fake sending LLM_ in your testing guide, usually we'd call this concept _Faucet_
- regarding _Legislation_, what exactly do you mean by the following?

    > In the future, this will be a headcount veto option but for now it is just a simple referendum repeal process.

- Since the 0.9% of all LLMs are minted each year, what happens after all LLM are minted (which will happen after ~111 years, if I'm not mistaken)?

    > decrease the total supply with 0.9 % per year mint 0.9% per year to the treasury with pallet assets

- Since there are lots of pallets you copied over from Substrate and a few you added or modified, maybe it would be useful to list all your pallets in the README

**Comment by takahser** [comment]
@flipchan @DorianSternVukotic also, I improved the LLM README and opened a [PR](https://github.com/liberland/liberland_substrate/pull/195)

**Pull request closed without merging**
