### PR TITLE
Relation Graph delivery

### PR DESCRIPTION
**Pull request by relationlabs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/928

### CODE REVIEW

**Comment by alxs** [comment]
Hi @relationlabs. Thanks for the delivery, but please note that your grant was [terminated](https://github.com/w3f/Grants-Program/pull/1128) due to inactivity. If you're still interested, as it seems to be the case, we'd ask you to first please apply to reverse the termination. To this end, you can create a PR removing the line added in the termination. Note that you will need the same number of approvals as for the original grant.

**Comment by takahser** [comment]
Just adding this for reference here - the grant termination has been reverted: https://github.com/w3f/Grants-Program/pull/1184

**Comment by semuelle** [comment]
Hi @relationlabs. Sorry for the long wait, but I have been reviewing all three milestones, and I can report that I have almost all deliverables ticked off. Some minor issues:

1. One of the tests fails: 
```sh
---- sparql::model::test_serialization_rountrip stdout ----
thread 'sparql::model::test_serialization_rountrip' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`
```
2. I am unable to build the wasm binary. Could you add some instructions for building the binary in the readme or testing guide?
3. I am missing deliverable 0e of milestone 2 ("publish an article that explains function and structure of Relation graph").

**Comment by relationlabs** [comment]
> Hi @relationlabs. Sorry for the long wait, but I have been reviewing all three milestones, and I can report that I have almost all deliverables ticked off. Some minor issues:
> 
> 1. One of the tests fails:
> 
> ```shell
> ---- sparql::model::test_serialization_rountrip stdout ----
> thread 'sparql::model::test_serialization_rountrip' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `0`
> ```
> 
>  2. I am unable to build the wasm binary. Could you add some instructions for building the binary in the readme or testing guide?
> 3. I am missing deliverable 0e of milestone 2 ("publish an article that explains function and structure of Relation graph").

Hi @semuelle, 
for issue 1, I just comment out this test case. Due to the features of this test case are experimental and extended but not related to the current grant function, and will not affect the compiling and executing of this project.

for issue 2, I have added the instruction of compiling steps in the Readme of source code.

**Comment by semuelle** [comment]
Thanks for the update @relationlabs. What about issue 3?

**Comment by semuelle** [comment]
> for issue 2, I have added the instruction of compiling steps in the Readme of source code.

Sorry, but I don't think this resolves the issue. The `SKIP_WASM_BUILD=1 cargo build` instruction was already in the documentation, which I followed, but it explicitly skips the wasm.

**Comment by relationlabs** [comment]
> 感谢更新@relationlabs. 第三题呢？

We will publish it this week

**Comment by relationlabs** [comment]
> > for issue 2, I have added the instruction of compiling steps in the Readme of source code.
> 
> Sorry, but I don't think this resolves the issue. The `SKIP_WASM_BUILD=1 cargo build` instruction was already in the documentation, which I followed, but it explicitly skips the wasm.

Aoubt issue2.Graphdb relies on the api of the rust std library ,substrate wasm runtime environment  doesn't integrate the std library.Graphdb needs to adapt the std dependency to no_ The wasm runtime execution environment of std.
So,instead of generating the wasm binary, we implemented the Pallet by using the direct deployment form of the binary. @semuelle

**Comment by semuelle** [comment]
> direct deployment form of the binary

What does that mean? How did you build the [wasm binaries in the repo](https://github.com/relationlabs/Relation-Graph/tree/main/src/runtime/wasm)? 

Also, I'm not sure what I did differently initially, but now the build is failing for me. Can you test this on your side and let me know which toolchain version you used?

```
[...]
error[E0412]: cannot find type `Variable` in this scope
    --> pallets/graphdb/src/sparql/plan_builder.rs:1141:33
     |
1141 |     variables: &mut HashSet<&'a Variable>,
     |                                 ^^^^^^^^ not found in this scope
     |
help: there is an enum variant `crate::sparql::plan_builder::Expression::Variable` and 6 others; try using the variant's enum

error[E0412]: cannot find type `QueryResults` in this scope
  --> pallets/graphdb/src/sparql/results/csv_results.rs:12:14
   |
12 |     results: QueryResults,
   |              ^^^^^^^^^^^^ not found in this scope

warning: unused imports: `DatasetFormat`, `DatasetParser`, `GraphParser`
  --> pallets/graphdb/src/lib.rs:12:17
   |
12 | use crate::io::{DatasetFormat, DatasetParser, GraphFormat, GraphParser};
   |                 ^^^^^^^^^^^^^  ^^^^^^^^^^^^^               ^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `crate::sparql::model::*`
 --> pallets/graphdb/src/sparql/algebra.rs:8:5
  |
8 | use crate::sparql::model::*;
  |     ^^^^^^^^^^^^^^^^^^^^^^^

   Compiling frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.17#22d40c76)
error[E0282]: type annotations needed for `HashSet<T, S>`
    --> pallets/graphdb/src/sparql/plan_builder.rs:1085:9
     |
1085 |     let mut assigned_variables = HashSet::default();
     |         ^^^^^^^^^^^^^^^^^^^^^^
[...]
warning: `pallet-graphdb` (lib) generated 7 warnings
error: could not compile `pallet-graphdb` due to 144 previous errors; 7 warnings emitted
```

**Comment by relationlabs** [comment]
> > direct deployment form of the binary
> 
> What does that mean? How did you build the [wasm binaries in the repo](https://github.com/relationlabs/Relation-Graph/tree/main/src/runtime/wasm)?
> 
> Also, I'm not sure what I did differently initially, but now the build is failing for me. Can you test this on your side and let me know which toolchain version you used?
> 
> ```
> [...]
> error[E0412]: cannot find type `Variable` in this scope
>     --> pallets/graphdb/src/sparql/plan_builder.rs:1141:33
>      |
> 1141 |     variables: &mut HashSet<&'a Variable>,
>      |                                 ^^^^^^^^ not found in this scope
>      |
> help: there is an enum variant `crate::sparql::plan_builder::Expression::Variable` and 6 others; try using the variant's enum
> 
> error[E0412]: cannot find type `QueryResults` in this scope
>   --> pallets/graphdb/src/sparql/results/csv_results.rs:12:14
>    |
> 12 |     results: QueryResults,
>    |              ^^^^^^^^^^^^ not found in this scope
> 
> warning: unused imports: `DatasetFormat`, `DatasetParser`, `GraphParser`
>   --> pallets/graphdb/src/lib.rs:12:17
>    |
> 12 | use crate::io::{DatasetFormat, DatasetParser, GraphFormat, GraphParser};
>    |                 ^^^^^^^^^^^^^  ^^^^^^^^^^^^^               ^^^^^^^^^^^
>    |
>    = note: `#[warn(unused_imports)]` on by default
> 
> warning: unused import: `crate::sparql::model::*`
>  --> pallets/graphdb/src/sparql/algebra.rs:8:5
>   |
> 8 | use crate::sparql::model::*;
>   |     ^^^^^^^^^^^^^^^^^^^^^^^
> 
>    Compiling frame-benchmarking-cli v4.0.0-dev (https://github.com/paritytech/substrate.git?branch=polkadot-v0.9.17#22d40c76)
> error[E0282]: type annotations needed for `HashSet<T, S>`
>     --> pallets/graphdb/src/sparql/plan_builder.rs:1085:9
>      |
> 1085 |     let mut assigned_variables = HashSet::default();
>      |         ^^^^^^^^^^^^^^^^^^^^^^
> [...]
> warning: `pallet-graphdb` (lib) generated 7 warnings
> error: could not compile `pallet-graphdb` due to 144 previous errors; 7 warnings emitted
> ```
toolchain version:
 wasm32-unknown-unknown
rustc 1.61.0

**Comment by relationlabs** [comment]
[build_wasm.zip](https://github.com/w3f/Grant-Milestone-Delivery/files/9895449/build_wasm.zip)

@semuelle Some new progress has been made in the construction of wasm，you can try to add build_ wasm.patch to the project directory.And run the following command.

#compile runtime wasm
git apply build_wasm.patch
cargo build

#runtime binary wasm 
mv ./target/debug/wbuild/node-template-runtime/target/wasm32-unknown-unknown/release/node_template_runtime.wasm ./runtime/wasm/
mv ./target/debug/wbuild/node-template-runtime/node_template_runtime.compact.compressed.wasm ./runtime/wasm/

#recovery graphdb code 
git reset --hard origin/main

**Comment by semuelle** [comment]
Dear @relationlabs, we have found your delivery to be a very close copy of [Oxigraph](https://github.com/oxigraph/oxigraph). Since you failed to comply with the Oxigraph license(s), this delivery is rejected and your grant will be terminated.

**Pull request closed without merging**
