### PR TITLE
FIAT-on-off-ramp milestone 1

### PR DESCRIPTION
**Pull request by wstrametz**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Grants-Program/pull/348
Amendment: https://github.com/w3f/Grants-Program/pull/501

### CODE REVIEW

**Comment by alxs** [comment]
Many thanks for the delivery @wstrametz. We will look into it as soon as possible. Just one small request: could you add the milestone number to the delivery file name to match our naming conventions?

**Comment by wstrametz** [comment]
Hi Aleixo - I changed the name, hope thats OK now! Cheers, Walter

**Comment by alxs** [comment]
Hi @wstrametz, apologies for the long wait. GitHub doesn't send notifications when comments are edited, so I didn't see your ping. Just wanted to say that I've started looking into your delivery and will provide feedback by the end of the week.

**Comment by alxs** [comment]
Hi again @wstrametz! It was very interesting to look into this. A couple of remarks:

- Are you somehow related to the team behind https://github.com/ebics-java/ebics-java-client/ and to what extent is your work based on said project (maybe percentage-wise)? You don't list many changes [here](https://github.com/element36-io/ebics-java-client/blob/master/README.md#kudos) but the structure of both projects differs significantly.
- Note that the project above is licensed under LGPL, which stipulates that works derived from it must also be licensed under the same terms. I.e. your project can't be Apache 2.0 but must use GPL/LGPL. As an aside, it also states that you must cause any modified files "to carry prominent notices stating that you changed the files and the date of any change."
- Maybe I'm missing something, but I can only find 4 unit tests for the entire project, which as far as I can see are only useful for manual testing as they merely print data. We generally expect deliveries to achieve >70% code coverage, ideally higher. How extensive you want your test suite to be is up to you, but I'd like to ask you to please invest some time into it for this and future milestones. If you have any questions, please let us know.
- Do you have any way of performing integration testing currently? Would it be possible for you to for example run an EBICS server for this purpose?
- I tried to test `/ebics/api-v1/bankstatements` with the existing Ebics configuration in production mode and ran into the following. Let me know in case you need the full log.
  ```
  Exception while moving file: /root/ebics/out/z53-1624255130.zip
  [...] DEBUG 1 --- [nio-8093-exec-2] i.e.c.e.s.i.EbicsStatementServiceImpl    :  statements returned []
  ```

**Comment by wstrametz** [comment]
Hi Aleixo @alxs - many thanks for your feedback! I pick it up dot by dot: 

1. No - not related, but Uwe Maurer is located nearby in Zurich - I could easily reach out. We added some “banking commands” to the library (nothing dramatic) - but as you noted, we did some structural changes. We wanted it to be better integrated in the dev-ecosystem, meaning docker-hub and the maven-repository so it can be used with the standard toolset to make developers (and hopefuly polkadot) people happy. 

2. Two things: a) We kept LGPL in the clone/branch of the library above, so still fine in terms of licence. b) In the “consuming” (Apache 2) project, we use the library as an executable (!) not as an integrated library - an extra effort, and a common practice of closed source projects to use LGPL - we just wanted be ultra-secure on that, but we had the impression that “Apache 2 uses LGPL” would also work. In short: Using LGPL as executable should be fine in any case.  

3. Yeaah.. lets say you dont miss much, we could have done better. But it is not as band as it seems, because: a)  quite some code is generated - so we dont see use to unit test that. b)  In our specification we only have 4 methods (like create transaction, download daily statement, etc), so thats why you dont see much. c) Our REST-Calls are boilerplate and go straight to the service-calls  - the code that contains the meat. There we have coverage between 40 and 80 %, so there are gaps. I will add more test-code and also add build-target where you to see a test coverage report.

4. That is unfortunately a difficult topic. I can offer to send you a screen recording or we do a hangout where you can see that the system creates a productive transaction in the bank account. Most banks offer a test system for clients, but not ours…and we did not find a public sandbox. Anyway: what we discovered is a quite new project (“libfineu”) - which offers a new Ebics library and a server counterpart. It was first released in April, is not hosted on github and it is packaged for Debian installs - so still quite some work to do and too risky to try for the short period of time of the grant. In contrast to that, the current library is used in production environments without problems. 

5. I think yes. Basically production mode only makes sense if you really have already set up the connectivity with the bank. But the issue here is (I guess) that you mounted a directory into the docker container which can not be moved by the root-user of the container - so pls check access-rights on file-system level. Would be happy to take a look at the log - I will add documentation on that issue. 

Hope I could answer your questions. I will notify you as soon as the test coverage is up. For the issue with the integration test, pls let me know what you think. 

Thanks, Walter

**Comment by wstrametz** [comment]
Hi Aleixo @alxs  - we have commited an update to main:

- Added more tests
- Integrated Test Coverage report to build & documentation (where to find the report)
- Added a coverage-badge in README and TEST.md, which currently shows 77 % Coverage

For the Coverage of 77 % note, that we have excluded generated sources as well as the Class, which forwards the REST calls to Java Calls.

Kind regards, Walter

**Comment by alxs** [comment]
Apologies for the delay again @wstrametz - I've been more or less OOO since my last message. Do you mind sending me an email to `aleixo@web3.foundation` to schedule a quick demo?

I'm still seeing most tests only printing to console, which sort of defeats the point of unit testing. Seeing as this is the only testing the code's being subverted to, it would make sense to significantly expand on it. Happy to discuss this in the call; in the meantime feel free to get started. You also mentioned it would be possible to test M1 using Libfineu in your application, but I understand your position.

And something small: I would recommend you integrate (auto-)formatting the code to a specific style into your workflow.

**Comment by wstrametz** [comment]
## Overview of changes

### Changes to Open-Grant application FIAT-on-off-ramp.md ([link](https://github.com/element36-io/Open-Grants-Program/blob/master/applications/FIAT-on-off-ramp.md))
- Naming of methods & more specific documentation with links to standards
- Integrated getBalance into getBankstatements

### ebics-java-service ([link](https://github.com/element36-io/ebics-java-service))

- More specific docu and links to standards
- Improved testing & linting the source
- Removed "paymentStatus" REST call, because it is not in the specification (FIAT-on-off-ramp.md) , but function is still in the services layer (EbicsPaymentStatusService)
- Other smaller improvements

## Further remarks

We used a library for for handling ebics cryptographic protocol. Because this library is central for our implementation, we wanted to make this base-library more accessible and easier to use: Therefore we forked the  library for into ebics-java-client ([link](https://github.com/element36-io/ebics-java-client)), implemented new Ebics-commands, added the library to public repo ([maven](https://mvnrepository.com/artifact/io.github.element36-io/ebics-cli)) and dockerized it (dockerhub [link](https://hub.docker.com/repository/docker/e36io/ebics-cli)). 

Logically we have these layers between a bank account and a node: 

`node <--(txns/events)--> OCW --(REST)--> ebics-java-server  --(cmd-line)--> ebics-java-client --(ebics)--> bank`

Alex @alxs helped with discussions to define the added value of our Rest-based ebics wrapper vs. the ebics-base-library, vs. Ebics protocol a) and implemented natively in Rust b). 

a) The Rest-Wrapper (ebics-java-server) adds following value:
- Active server component with REST and Json interfaces instead of generating/parsing Ebics-XML in Rust and making native-calls to ebics-java-client.
- Ebics commands are “hidden” in ebics-java-server, the cryptographic protocol of Ebics is hidden in ebics-java-client. 
- ebics-java-server generates necessary ebics XML documents from Json and translates results back into JSON and applies some business logic doing that. Ebics XML documents are far more complex than our Json documents in terms of structure (hierarchy and amount of node in the documents) - we tried to reduce the complexity to what we need for the pegging. 

b) Native Rust implementation:

- Having a module in Rust which handles XML and Ebics crypto-protocols  would be ultra-nice, but efforts to implement that would far stretch the scope of the project with only little gains and more implementation risk, and it was not proposed to do so in the Grant application. 
- Java is the domain language of many banks, thus it seems to be better suited to bridge from Polkadot into the banking world. At least it does not seam to be a bad idea, and might help to get trust from banks to support the idea of decentralizing the on- and off-ramping of Fiat through bank accounts.

**Comment by alxs** [comment]
Many thanks for your patience @wstrametz and for the submitted amendment.

I've gone through your delivery one last time and I'm happy to tell you that with this, the milestone is a pass. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/FIAT-on-off-ramp_1_alxs.md). I've forwarded your invoice for processing, I think everything is correct but the invoices team will reach out to you if there are any questions.

Good luck with M2, and please reach out to us in case you run into delays or would like to amend the list of deliverables.

**Pull request merged**
