### PR TITLE
Zenlink: delivery milestone 1

### PR DESCRIPTION
**Pull request by v-van**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by milonite** [comment]
@v-van Hi van,
I've requested the test tokens yesterday but I didn't received anything. Could you please check?

**Comment by Noc2** [comment]
Hi. I’m happy to tell you that the milestone is a pass and will now forward your invoice internally! @milonite made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zenlink_1_milestone_milonite.md).

**Comment by RouvenP** [comment]
hi @milonite we just sent a test transaction. could you please confirm if received?

**Comment by v-van** [comment]
> hi @milonite we just sent a test transaction. could you please confirm if received?

The transaction is confirming, and the address is correct.
https://blockchair.com/bitcoin/transaction/c891f3ac5906908628ca95e1104b790d6d4df2e7448e20cbc11deafe4a5db6eb

Thanks!

**Comment by RouvenP** [comment]
@milonite thanks for confirming. We just sent the remainder.

**Pull request merged**
