### PR TITLE
Create dot_marketplace_v2-milestone_2.md

### PR DESCRIPTION
**Pull request by varun24143**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/832 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by varun24143** [comment]
Hi @takahser Thanks for approving and merging the first milestone. Please do have a look at the second milestone too and let us know.

**Comment by takahser** [comment]
@varun24143 it's on my TODO list, I'm planning to give you feedback within the next 2 days.

**Comment by varun24143** [comment]
> @varun24143 I've checked out the _Phase2_Milestone2_ branch of your repo and ran the node.
> 
> According to your [testing guide](https://github.com/WowLabz/dot-marketplace-v2/blob/Phase2_Milestone2/testing_guide.md), there should be a `disapproveTask` extrinsic:
> 
> image
> 
> However, I don't see that extrinsic in my local node:
> 
> image
> 
> Any idea why, am I working on an outdated version maybe?

> @takahser  After checking out to Phase2_Milestone2 please build it again using `cargo build --release` and `./target/release/node-template --dev --tmp`
> Looks like you are using the previous built from Phase2_Milestone1

**Comment by takahser** [comment]
@varun24143 I did that already, but it's still not showing up.
I'm currently on `cb86225088dc61cd00cc3019ab62235c97870037`:

```bash
$ git log -1
commit cb86225088dc61cd00cc3019ab62235c97870037 (HEAD -> Phase2_Milestone2, origin/Phase2_Milestone2)
Author: loaki07 <loakesh.i@gmail.com>
Date:   Fri Jun 24 11:50:13 2022 +0530

    remove: default template scripts
```

Could you double-check if everything was committed and pushed?

**Comment by takahser** [comment]
@varun24143 thanks for pointing out, it works now.

Couple of things to note here:

1. I just noticed, that the [docker instructions](https://github.com/WowLabz/dot-marketplace-v2/blob/Phase2_Milestone2/README.md#run-in-docker) are probably outdated and don't currently work. For example, I can't find the `./scripts/docker_run.sh` script in either of the two repositories.
2. Also, I'm able to run the tests using  `cargo test`, however, I can't find the instructions on how to run tests in your [README](https://github.com/WowLabz/dot-marketplace-v2/blob/Phase2_Milestone2/README.md). Consider adding these.
3. When running `clippy`, I get 109 warnings and an error. It would be good if you could fix these.

    ```bash
    $ cargo clippy
    warning: `pallet-tasking` (lib) generated 109 warnings
    error: could not compile `pallet-tasking` due to previous error; 109 warnings emitted
    warning: build failed, waiting for other jobs to finish...
    error: build failed
    ```
4. While the manual build succeeds, building the docker image currently fails:

    ```bash
    $ docker-compose up --build -d
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:57:5
       |
    57 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:12:5
       |
    12 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:26:5
       |
    26 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:44:5
       |
    44 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:73:5
       |
    73 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
      --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:93:5
       |
    93 |     asm!(
       |     ^^^
       |
       = note: consider importing one of these items:
               std::arch::asm
               core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:114:5
        |
    114 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:136:5
        |
    136 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:159:5
        |
    159 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:183:5
        |
    183 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:208:5
        |
    208 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:234:5
        |
    234 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:261:5
        |
    261 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: cannot find macro `asm` in this scope
       --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/rsix-0.23.9/src/imp/linux_raw/arch/inline/x86_64.rs:289:5
        |
    289 |     asm!(
        |     ^^^
        |
        = note: consider importing one of these items:
                std::arch::asm
                core::arch::asm
    
    error: could not compile `rsix` due to 14 previous errors
    warning: build failed, waiting for other jobs to finish...
    The command '/bin/sh -c cargo build --release' returned a non-zero code: 101
    ERROR: Service 'dot_marketplace_node' failed to build : Build failed$
    ```

**Comment by Loaki07** [comment]
@takahser Please find the updates below:
1. Removed the docker scripts from the template code, as we already have a dedicated docker repo with instructions maintained for all the phases.
2. Added a testing guide to the `Readme` to run tests. `cargo test` command will execute successfully for this branch.
3. Fixed all the clippy warnings and errors.
4. Probably this error is from the old docker, probably running the docker build again should work (please delete all old docker instances of the app). Also, after the updates to `parity-db` we have changed one of the steps in the `Dockerfile`. Its tested and working. 

Kindly, check the new updates and let us know.

**Review by takahser — APPROVED** [review]
@varun24143 thanks for the fixes. I accepted your delivery, you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dot-marketplace-v2_2_takahser.md).

**Comment by takahser** [comment]
@varun24143 Btw, one thing that caught my eye: all your `palletTasking` extrinsics follow the patterin ´{verb}+{noun}´, except for the `taskCompleted` extrinsic. It would be more coherent with the others to rename it to `completeTask`. Feel free to improve that.
Another thing I noticed is that you never merged anything to your main branch, hence the [repo](https://github.com/WowLabz/dot-marketplace-v2) looks empty when initially visiting it.

**Comment by Loaki07** [comment]
@takahser thank you for evaluating the delivery!
we have just uploaded the invoice with date 9th August, 2022.

thank you for pointing it out, we will make sure to fix it in the upcoming deliveries.

Also the main branch of the repos now are merged with the accepted delivery.

**Comment by takahser** [comment]
@Loaki07 thanks for the update & for uploading the invoice. I just forwarded it. 👍

**Comment by meldien** [comment]
@Loaki07, I noted we have a old billing address on the invoice. 
Could you please update the address to following: 

Web 3.0 Technologies Foundation 
Baarerstrasse 14
6300 Zug
Switzerland

Many thanks. 

Best,
Melanie

**Comment by Loaki07** [comment]
@meldien The invoice has been re-uploaded with the new address and date 10th August, 2022.

**Pull request merged**
