### PR TITLE
Massbit Milestone 2 delivery

### PR DESCRIPTION
**Pull request by daywednes**
* Massbit Route milestone 2

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the USDC/USDT(ETH network) payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/985

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @daywednes thanks for your delivery. We have a bit of a backlog with evaluations currently but someone will take a look at this shortly. Thanks for your patience!

**Comment by daywednes** [comment]
Thank you. Looking forward to it!!!

**Comment by dsm-w3f** [comment]
@daywednes thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/massbit_2_dsm-w3f.md) and provide proper answers and fixes. The main problems were the testing guides were failing, which prevented me to perform the tests for the milestone delivery. Regarding the code quality assessment, feel free to fix/improve what makes sense for you. After that, let me know to continue with the evaluation.

**Comment by hoanito** [comment]
@dsm-w3f Thanks. I will look into the evaluation and let you know as soon as we have things adjusted

**Comment by hoanito** [comment]
@dsm-w3f The bash script for creating the environment was missing some docker components, and it has been corrected. Feel free to ping me on Element if you have question during your evaluation. 

Please note that the docker environment we submitted for this grant demonstrates features in application document, so some parts are bypassed (such as new account created will be verified without email confirmation, each new account will have 1000 KEI token for staking without accessing the faucet)

We also added documentation for the code and tests for Session and Stats

**Comment by dsm-w3f** [comment]
@daywednes and @hoanito thank you for the improvements and help during this evaluation. The [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/massbit_2_dsm-w3f.md) was updated and the milestone is approved. I'll forward internally the invoice and the payment should occur within two weeks (could happen before). Great Job!

**Comment by daywednes** [comment]
@dsm-w3f we submitted the invoice last week FYI.

**Comment by dsm-w3f** [comment]
Hi @daywednes, I already forwarded your invoice last week, it should be processed soon.

**Comment by daywednes** [comment]
@dsm-w3f can you please check the status? thank you

**Comment by daywednes** [comment]
@dsm-w3f friendly remind again as i have not received it. Cheers

**Comment by dsm-w3f** [comment]
@fededubbi can you give an update about the status of the payment of this grant delivery?

**Comment by RouvenP** [comment]
hi @daywednes we just transferred the payment - apologies for the delay!

**Pull request merged**
