### PR TITLE
Mobile Game Framework for Substrate Millestone 1

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by mmagician** [comment]
@enfipy At the moment I'm running into the following problems:
1. `docker pull docker.pkg.github.com/creator-rs/creator/android:latest` doesn't work out-of-the-box, one needs to first authenticate to github with `docker login`, see the [following thread](https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/87). This seems to be an issue with GitHub itself, but perhaps you could include the workaround in your instructions? 
2. Once I succeeded with the above, I run into the following error: `docker run --rm -it -v "$(pwd)/:/src" -w /src/examples/paint docker.pkg.github.com/creator-rs/creator/android cargo creator build --release`

Output: 
```
Warning: You use environment variable ANDROID_HOME that is deprecated.Please, remove it and use ANDROID_SDK_ROOT instead. Now ANDROID_HOME is used
Error: NDK error

Caused by:
    Android SDK has no platforms installed
```

Inside the container I can manually set `ANDROID_SDK_ROOT=$ANDROID_HOME` and remove the latter env var. This gets rid of the warning for me, but the NDK error still persists. Perhaps the docker image is missing some dependencies?

3. I get the same NDK error locally. I have NDK 21.3 installed and `PATH=...:/Users/marcin/Library/Android/sdk/ndk:...`. Should I set some environment variables that your tool is expecting? 

Let me know if you could help!

**Comment by enfipy** [comment]
@mmagician Thank you a lot for your notices! I updated [wiki](https://github.com/creator-rs/creator/wiki) and commit hash in this PR. Also, there were some problems with SDK 30 inside the docker so I updated it. Now it should build as expected!

**Comment by enfipy** [comment]
@mmagician Just yesterday Github released enhanced [improved container support](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/enabling-improved-container-support) and we moved to it. Now you don't need to login to download docker images. Hooray 🥳

**Comment by mmagician** [comment]
Congrats, your milestone has been approved! You will find the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/52)

**Comment by RouvenP** [comment]
hi @enfipy we just sent a test transaction. Could you please confirm if received?

**Comment by enfipy** [comment]
Hi @RouvenP! Yes, I received 0.01 btc

**Comment by RouvenP** [comment]
hi @enfipy, thanks for confirming. We sent the payment.

**Pull request merged**
