### PR TITLE
Web3Go Milestone 1 

### PR DESCRIPTION
**Pull request by Moehringen**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/629

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @Moehringen. We'll look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @Moehringen. I am currently reviewing your milestone. Sorry for the long wait. It will still take a day or two to review everything, but I just noticed that some of the repositories referenced in the milestone don't contain a license. Some of the indexers have an MIT license, one is forked from a repo with MIT license and one has no license at all. Can you please verify that all grants-related code is properly licensed? MIT license is generally fine.

**Comment by Moehringen** [comment]
Hi sorry for that, we will double-check it.

**Comment by Moehringen** [comment]
Dear Sir,

We have added all licenses to the repository.

Please visit our website: https://web3go.xyz/#/

to play it around, we have delivered more than committed in the grant, and
we want to talk with Web3 Foundation for further collaboration.

Thanks

hao

**Comment by Moehringen** [comment]
Dear Sir,

I just found there is a new grant for XCM explorer:
https://github.com/w3f/Grants-Program/blob/master/rfps/multi-chain-block-explorer.md?utm_campaign=w3%20grants&utm_content=201575199&utm_medium=social&utm_source=twitter&hss_channel=tw-884511390987407360

we do have a new module, that is profile, see the profile for Shawn:

https://web3go.xyz/#/ProfileIndex/Balance?address=12hAtDZJGt4of3m2GqZcUCVAjZPALfvPwvtUTFZPQUbdX1Ud

and if you click the view button, you can see all the tx for this address:

[image: image.png]

I think that might be a very prototype for what web3 foundation needs,
right?

And this morning I have a talk with Sam from Subquery,  maybe we can
together work on it!  just let you know.

thanks

Hao

**Comment by semuelle** [comment]
Hi @Moehringen. Thanks for the update. 

I have now reviewed all deliverables. First of all, let me say that the website looks great and I was able to very quickly create some nice graphs from custom queries. All the deliverables seem to be satisfied, the only problem I have is reproducing the system locally. I put the errors I got into the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3go_1_semuelle.md). Can you please check that the instructions are complete (for example, I don't know how to reproduce your database schema; perhaps you can provide a script or dump for testing) and the build process works for you?

Also, `npm audit` found multiple critical issues in your dependencies. It would be great if you could update the most critical ones.

**Comment by semuelle** [comment]
Regarding the RFP, feel free to submit a grant application for it. Just keep in mind that we don't usually approve multiple grants simultaneously, so you would have to conclude this grant first.

**Comment by Moehringen** [comment]
hi we are preparing everything and will submit it again soon.

**Comment by Moehringen** [comment]
hi sir, just want to check it the status of the submission, thanks!

**Comment by semuelle** [comment]
Hi @Moehringen, sorry for the delay. We have a bit of a backlog currently. I hope to get back to your evaluation later today.

**Comment by semuelle** [comment]
Hi @Moehringen. I have reviewed the changes and I'm happy to report that all issues have been addressed and that I was able to run everything locally. The only thing that's missing is the inline documentation. I understand that this might not be a high priority for you, but there is virtually none although the application specifically mentions it (`We will provide both inline documentation of the code and...`). I think it would be of great help to others if you could annotate at least the most important entry points of the service.

**Comment by Moehringen** [comment]
hi Sebastian,

Thanks for your email!

Yes, you are correct. as we developed very fast so the inline document is
not complete, we will finish it recently.

Does it mean we have achieved the M1 of this grant now?

thanks.

Hao

**Comment by semuelle** [comment]
When a milestone is accepted, the pull request is merged. I would like to ask you to add some inline documentation to your code. I can then merge this PR and accept the milestone.

**Comment by Moehringen** [comment]
we will do it asap, thanks!

**Comment by Moehringen** [comment]
hi Sir, 

We have added the inline comments for each related file, the list is as follows: 

https://github.com/web3go-xyz/RMRK-Indexer
https://github.com/web3go-xyz/Crowdloan-Indexer
https://github.com/web3go-xyz/moonbeam-balance-indexer
https://github.com/web3go-xyz/polkadot-balance-indexer
https://github.com/web3go-xyz/portal-ui
https://github.com/web3go-xyz/portal-service

would you please help to check?

**Comment by takahser** [comment]
@Moehringen thanks for the update!
Sorry for the delay here, we currently have a large backlog of deliveries. Also, @semuelle is currently on sick leave so I'll take this over for now. Please allow for some time until I can take a closer look and get back to you.

**Comment by semuelle** [comment]
Hi @Moehringen. Thank you for the update and sorry for the delay. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3go_1_semuelle.md).

**Comment by Moehringen** [comment]
thanks!

Can we put Web3 foundation logo on our website now? is there any PR from
Web3 foundation can help us? as we are doing the fundraising, we need the
exposure.

Sebastian Müller ***@***.***> 于 2022年4月21日周四 17:35写道：

**Comment by Moehringen** [comment]
hi, I have resubmitted the invoice, please check it! thanks Hao

**Comment by RouvenP** [comment]
hi @Moehringen, we transferred the payment today. Thanks!

**Comment by Moehringen** [comment]
received!

RouvenP ***@***.***> 于 2022年5月2日周一 23:30写道：

**Pull request merged**
