### PR TITLE
Create polkaj_android_support_milestone_1.md

### PR DESCRIPTION
**Pull request by nschwermann**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/573

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Nathan, 

sorry for the long wait - we had a bit of a backlog. I am happy to report that everything looks good and your milestone is hereby accepted. :tada: You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/4c10123da53cbe888dddd6f87705380bcc4a4b57/evaluations/polkaj-android_1_semuelle.md). 

Could you add version numbers of your toolchain to the next delivery? It [seems](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin) the current setup is incompatible with Gradle 7.

I will forward your invoice for processing.

**Comment by nschwermann** [comment]
@semuelle thanks so much! I have actually already removed the maven install for next milestone just last night! The documentation isn't clear it's meant to be built with the included gradle wrapper I will make sure to clarify the toolchain.
Cheers!

**Comment by semuelle** [comment]
Excellent. I was thinking if I could ask you to improve on the general documentation. But I see you have a documentation deliverable in M3, so I'll wait for that. :)

**Comment by semuelle** [comment]
@nschwermann, your invoice says 2014. Could you (re-)submit one from 2021?

**Comment by nschwermann** [comment]
@semuelle whoops, I have submitted another one!

**Comment by nschwermann** [comment]
@semuelle just wanted to be sure that you got the second one. Thanks :)

**Comment by semuelle** [comment]
Yep, thanks. Should be processed within a week.

**Pull request merged**
