### PR TITLE
Add wasm-opt-for-rust-m1.md

### PR DESCRIPTION
**Pull request by brson**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1070

### CODE REVIEW

**Comment by brson** [comment]
cc @cmichi @Robbepop @kripken wasm-opt-for-rust milestone 1

**Comment by brson** [comment]
Note that if somebody actually tries to install the binary for this "preview" version, they will need to specify the version explicitly, like `cargo install wasm-opt --version 0.0.1-preview.3 --locked`, as cargo will not select prerelease versions by default.

**Comment by brson** [comment]
Thanks for the evaluation @lucasvanmol and for running tarpaulin on it. I filed an issue (https://github.com/brson/wasm-opt-rs/issues/59) to look into it. It's not surprising that a tool that exercises the program would find a segfault - particularly in the low level bindings there are code paths that binaryen doesn't expect and will fail hard. I'll figure out how to get taurpaulin working, and consider running at least the high-level apis through additional analysis tools to see if they uncover any more obvious segfaults.

**Comment by lucasvanmol** [comment]
>  I'll figure out how to get taurpaulin working, and consider running at least the high-level apis through additional analysis tools to see if they uncover any more obvious segfaults.

Thanks for that! I mentioned it because I thought it might be of interest to the project, but note that it's not a requirement for us in terms of milestone delivery - you're of course free to look into it on your own volition.

**Comment by cmichi** [comment]
It's great to see this going well, looking forward to M2 :blush:!

>[Non-ascii paths on Windows don't work.](https://github.com/brson/wasm-opt-rs/issues/40)

Nice to see that you are thinking about issues like this.

**Comment by RouvenP** [comment]
hi @brson we transferred the payment today.

**Comment by brson** [comment]
@RouvenP I have received the payment. Thank you.

**Pull request merged**
