### PR TITLE
Grant Milestone 2 Delivery - Tempora

### PR DESCRIPTION
**Pull request by pcorrado-np**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1857

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @pcorrado-np ,
glad to see your delivery come in. I kindly ask you to check the [FAQ section](https://grants.web3.foundation/docs/faq#-milestone-delivery) for milestone delivery and adjust the table with your deliverables to match the one you listed in your application. Thank you.

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np , glad to see your delivery come in. I kindly ask you to check the [FAQ section](https://grants.web3.foundation/docs/faq#-milestone-delivery) for milestone delivery and adjust the table with your deliverables to match the one you listed in your application. Thank you.

Hi @PieWol!

Done :heavy_check_mark: 

Thanks for your time.

**Comment by PieWol** [comment]
Hey @pcorrado-np, 
which networks are you using for dApp demo? Somehow Talisman is unable to detect which network is used even though it should be able to pick up Astar, Shiden and even Shibuya with testnets enabled. In the application you said that you are using the rococo testnet version of Astar but I can't seem to find that network listed in polkadot.js/apps.

So I wonder which other Tokens than $TUR I need to try out the demo. Thanks :)

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np, which networks are you using for dApp demo? Somehow Talisman is unable to detect which network is used even though it should be able to pick up Astar, Shiden and even Shibuya with testnets enabled. In the application you said that you are using the rococo testnet version of Astar but I can't seem to find that network listed in polkadot.js/apps.
> 
> So I wonder which other Tokens than $TUR I need to try out the demo. Thanks :)

Hi @PieWol, 

We are using the Rococo environment of OAK (Turing Staging) and Astar (Rocstar) because we need a testing environment that has the HRMP channel open between these chains (Shibuya is not connected with any OAK environment). 

The RPC for Rocstar is `wss://rocstar.astar.network` ([link](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frocstar.astar.network#/explorer)), and we recommend to use the Polkadot.js wallet. 
We could send you tokens but the chain has been halted for several days. Alternatively, you can try with the local environment configuration.  

Thanks!

**Comment by PieWol** [comment]
Thanks for the info @pcorrado-np. Now with rocstar added to Talisman it works. In the sense that the networks are properly decoded. I will have to wait for the testnet tokens to further test the dApp. You can see the current state of my evaluation[ here](https://github.com/w3f/Grant-Milestone-Delivery/pull/1139). Feel free to address my questions already even though I haven't finished testing the demo dApp yet.

**Comment by pcorrado-np** [comment]
> Thanks for the info @pcorrado-np. Now with rocstar added to Talisman it works. In the sense that the networks are properly decoded. I will have to wait for the testnet tokens to further test the dApp. You can see the current state of my evaluation[ here](https://github.com/w3f/Grant-Milestone-Delivery/pull/1139). Feel free to address my questions already even though I haven't finished testing the demo dApp yet.

Hi @PieWol!

We've taken a look at the current status of the evaluation:

- We just added [Smart Contracts tests](https://github.com/NeoPower-Digital/tempora/commit/4cfa2fced1c308e7ccd1569e748e8077120c48a6) :heavy_check_mark: 

- About the Kusama deployment: The UI currently supports a deployment for Kusama chains through the environment file by changing the NEXT_PUBLIC_CHAIN_ENVIRONMENT variable to "kusama" and configuring contract addresses. Our deployed version is using "testing" for that value since the goal of the demo is to test with testnet tokens. Once all the corresponding tests are completed and the milestone delivery is approved, we will coordinate the deployment of the smart contract and announcement.

- Regarding Rocstar: We've posted on the Astar Discord asking about the status of the chain. For now we have had no news.

Let us know if you have further questions. Thanks again!

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np , thanks for the swift reply and changes. I would like to see a little more detail in the ink! contract testing. Trigger payment should also check for balance changes :)
> 
> Could you please also respond to the issue I raised with the state bloat? I think it makes sense to either have the option to re-enable schedules somehow with the current setup. Otherwise `remove_schedule` should actually remove the schedules data from the contracts storage. Thats what I think about it at least. Let me know what you think.

Hi @PieWol!
- We included new test cases for the smart contract and new validations on messages.  
- Regarding the trigger payment checks, we'll add more on-chain validations in the next versions, including error tracking on the UI.
- About the logic deletion of schedules, we have the feature to pause/play payments on the roadmap. That is the reason we currently have this behavior on the remove_schedule function. We know about the state bloat, but we need the current implementation to lay the groundwork for the upcoming feature.  

Your feedback is much appreciated! Please let us know if you have any comments or questions. 

Thanks!

**Comment by PieWol** [comment]
Hey @pcorrado-np , 

thank you for your stamement and announced changes.

Now I think there is only one thing thats missing. With Rocstar being shutdown I can't test the webapp and the UI features. 
Do you think you could migrate the webapp to use Kusama already? Given your previous answers it sounds like you already prepared the webapp to be able to work in this environment. With this in mind and that the Kusama connection being a deliverable listed in the application I would suggest this as the way going forward and complete this milestone. 

Let me know if that would work for you or if there are any problems. 👍

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np , 
> 
> thank you for your stamement and announced changes.
> 
> Now I think there is only one thing thats missing. With Rocstar being shutdown I can't test the webapp and the UI features. 
> Do you think you could migrate the webapp to use Kusama already? Given your previous answers it sounds like you already prepared the webapp to be able to work in this environment. With this in mind and that the Kusama connection being a deliverable listed in the application I would suggest this as the way going forward and completing this milestone. 
> 
> Let me know if that would work for you or if there are any problems. 👍 

Hi, @PieWol.

We are working on the Kusama deployment. We'll keep you posted.

Thanks!

**Comment by pcorrado-np** [comment]
Hi @PieWol,

We are fixing a specific bug that only happens on Kusama (Shiden). As soon as we fix it, we'll let you know.

Thanks!

**Comment by pcorrado-np** [comment]
Hi @PieWol!

We've talked with the Astar team, and they have informed us that Shiden currently doesn't support WASM smart contract calls through XCM. However, they have assured us that they will include this feature in the next Shiden release.  

In light of this, the best approach would be to proceed with testing in a local environment. The README file can guide you through the process. 

In the meantime, we've prepared a demonstration video showcasing Tempora. You can view the video here: https://youtu.be/Ga9a3yiFCFk.

If you have any doubts or comments, don't hesitate to reach out to us. 

Thanks!

**Comment by PieWol** [comment]
Hi @pcorrado-np ,
thanks for the update. I think that will work. Thanks for linking me the demo 👍.
I'll get back to you as soon as I have updated the evaluation.

**Comment by PieWol** [comment]
Hey @pcorrado-np , in the local setup you are stating that one should "run zombienet" but please add some additional info. Zombienet is not an executable that comes with the repos listed so a link to an install guide is needed. It would also be really helpful if you were to provide a step-by-step guide with command snippets so that the user trying to set it up locally can just follow your steps and rely on the provided commands.

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np , in the local setup you are stating that one should "run zombienet" but please add some additional info. Zombienet is not an executable that comes with the repos listed so a link to an install guide is needed. It would also be really helpful if you were to provide a step-by-step guide with command snippets so that the user trying to set it up locally can just follow your steps and rely on the provided commands.

Hi @PieWol. 

We just updated the README file. 

Thanks!

**Comment by PieWol** [comment]
hey @pcorrado-np , 
Thanks for the update. The guide is much appreciated and I'm sure you also realized how much it was needed to setup this project without having developed this very project 😉.  I see you have specified in the guide where to clone the OAK and Astar repo but what about the Polkadot repo? Where to clone it?

**Comment by pcorrado-np** [comment]
> hey @pcorrado-np , Thanks for the update. The guide is much appreciated and I'm sure you also realized how much it was needed to setup this project without having developed this very project 😉. I see you have specified in the guide where to clone the OAK and Astar repo but what about the Polkadot repo? Where to clone it?

Hi @PieWol,

You don't need to clone it. You can directly install the `polkadot` executable with the documented command. That way you can avoid cloning the project and running the build manually.

Thanks!

**Comment by PieWol** [comment]
@pcorrado-np ,

sadly even after following your guide I get the following error. The Zombienet doesn't boot up correctly. Can you provide me with a fix?
```
│ Rococo Local Testnet ⚙ Clear Boot Nodes                                                                                │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ alice                                                                                              │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Launching                                                                                          │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Command            │ polkadot --chain /tmp/zombie-a76fd7994968b47635cac3239407df10_-1029-LVtojZrrE4I1/alic              │
│                    │ e/cfg/rococo-local.json --name alice --rpc-cors all --unsafe-rpc-external --rpc-methods un         │
│                    │ safe --unsafe-ws-external --no-mdns --node-key 2bd806c97f0e00af1a1fc3328fa763a9269723c8db8         │
│                    │ fac4f93af71db186d6e90 --no-telemetry --prometheus-external --validator --prometheus-port 4         │
│                    │ 9228 --rpc-port 8850 --ws-port 60613 --listen-addr /ip4/0.0.0.0/tcp/49227/ws --base-path /         │
│                    │ tmp/zombie-a76fd7994968b47635cac3239407df10_-1029-LVtojZrrE4I1/alice/data                          │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
┌────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Pod                │ alice                                                                                              │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Status             │ Error                                                                                              │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Message            │ Process: 1126, for node: alice dies.                                                               │
├────────────────────┼────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Output             │ error: unexpected argument '--unsafe-ws-external' found                                            │
│                    │                                                                                                    │
│                    │   tip: a similar argument ex                                                                       │
│                    │ ists: '--unsafe-rpc-external'                                                                      │
│                    │                                                                                                    │
│                    │ Usage: polkadot --name <NAME> --rpc-cors <ORIGINS> --unsafe                                        │
│                    │ -rpc-external --rpc-methods <METHOD SET> <--chain <CHAIN_SPEC>|--dev|--base-path <PATH>|--         │
│                    │ log <LOG_PATTERN>...|--detailed-log-output|--disable-log-color|--enable-log-reloading|--tr         │
│                    │ acing-targets <TARGETS>|--tracing-receiver <RECEIVER>>                                             │
│                    │                                                                                                    │
│                    │ For more information, try '--help'                                                                 │
│                    │ .                                                                                                  │
│                    │                                                                                                    │
└────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────┘
Error:           Error
```

**Comment by PieWol** [comment]
Hey @pcorrado-np ,
I have noticed that there are some basic checks missing in the dApp. For example the dApp should do sanity checks on user inputs to create a more user friendly experience. It the job of the frontend to only construct extrinsics that are actually expected to be executable. This should include e.g. to only allow to construct payments that the user has enough funds for. Furthermore as there is not only one account involved but also the proxy accounts it should be explicitly mentioned which account is not funded with enough tokens to setup a successful payment. 

Otherwise thank you for the changes and the work you put in this far! I'm sure the changes requested are small adjustments. I'm looking forward to see this working on Kusama once the next Shiden version will be released 👍 .
What do you think about the additional checks I mentioned?

**Comment by PieWol** [comment]
Also I as the user expect to see my current spendable balance of whatever token I have selected for the payment I am currently setting up. It would be great if you could integrate this too.

What about directly below this field?
Screenshot 2024-04-16 at 21 50 03

**Comment by pcorrado-np** [comment]
> Also I as the user expect to see my current spendable balance of whatever token I have selected for the payment I am currently setting up. It would be great if you could integrate this too.
> 
> What about directly below this field? Screenshot 2024-04-16 at 21 50 03

Hi Piet! 

Thanks for the feedback. We really appreciate it.

We'll work on these improvements and keep you posted about them 👌

**Comment by pcorrado-np** [comment]
Hi @PieWol!

We just committed the changes to the Tempora repository with the improvements.

Please let us know if you have comments or questions.

Thanks!

**Comment by PieWol** [comment]
Hey @pcorrado-np ,
changes are looking good! thanks. 

Why are the Turing fees also denominated in SBY? Should't it be in TUR?

**Comment by pcorrado-np** [comment]
> Hey @pcorrado-np , changes are looking good! thanks.
> 
> Why are the Turing fees also denominated in SBY? Should't it be in TUR? Screenshot 2024-04-22 at 18 33 34

Hi Piet! 

We are using Astar native tokens to pay fees on the OAK side too.

**Comment by PieWol** [comment]
Okay awesome, thanks for clarifying.

**Comment by PieWol** [comment]
Your milestone is now accepted. Congratulations for completing your grant 🎉 !

**Comment by pcorrado-np** [comment]
Awesome @PieWol! Thanks for all the review and feedback. 

We are going to continue with the following steps!

**Comment by RouvenP** [comment]
hi @pcorrado-np we sent the payment last Friday

**Comment by pcorrado-np** [comment]
> hi @pcorrado-np we sent the payment last Friday

Received ✅ Thanks!

**Pull request merged**
