### PR TITLE
Create LightSpell-milestone1.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the ETH(USDC) account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1817

### CODE REVIEW

**Comment by dudo50** [comment]
Hey @dsm-w3f, any news on payment? Was the invoice from us received properly? Many thanks for the information!

**Comment by dudo50** [comment]
Thanks @semuelle, please let us know if there was a problem from our side and if we should resubmit the invoice.

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
@semuelle , payment still haven't arrived today. 
Can you please let us know current status of this delayed payment? Many thanks for the information!

With kind regards, 
Team ParaSpell

**Comment by semuelle** [comment]
Should still happen today, @dudo50. Please hang tight.

**Comment by RouvenP** [comment]
hi @dudo50 we just transferred the payment. Apologies for the delay

**Comment by dudo50** [comment]
@RouvenP thanks for the information.

With kind regards,
Team ParaSpell

**Pull request merged**
