### PR TITLE
Typechain-Polkadot Milestone 2

### PR DESCRIPTION
**Pull request by TtomaS7**
Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1105

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@TtomaS7 thanks for your submission.
I was following your [instructions to create an example project](https://github.com/Supercolony-net/typechain-polkadot/tree/3445db875d08a08a8d4ac60bbca40505e915a52c/examples) but it threw an error:

```bash
~/repos/typechain-example$ npm i

up to date, audited 244 packages in 524ms

35 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~/repos/typechain-example$ npx typechain-polkadot --in artifacts --out out
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/typechain-polkadot - Not found
npm ERR! 404 
npm ERR! 404  'typechain-polkadot@latest' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/seraya/.npm/_logs/2022-11-14T08_26_06_082Z-debug.log
```

Could you double-check whether everything is properly published on npm and wether this example works on your side?

**Comment by varex83** [comment]
> ```shell
>  https://registry.npmjs.org/typechain-polkadot
> ```

Have you installed typechain into your npm package, if not you can use npx @727-ventures/typechain-polkadot --input path/to/input --output path/to/output

**Comment by takahser** [comment]
@varex83 

> If not you can use npx @727-ventures/typechain-polkadot --input path/to/input --output path/to/output

Thanks that worked. Could you please update the guide?

**Comment by varex83** [comment]
> @varex83
> 
> > If not you can use npx @727-ventures/typechain-polkadot --input path/to/input --output path/to/output
> 
> Thanks that worked. Could you please update the guide?

Updated

**Review by takahser — CHANGES_REQUESTED** [review]
@varex83 I tested the command using the [demo flipper smart contract](https://docs.substrate.io/tutorials/smart-contracts/prepare-your-first-contract/) but it threw an error and didn't generate the types:

```bash
$ ll /home/xxx/repos/typechain-example/flipper/target/ink/flipper.contract
-rw-rw-r-- 1 xxx xxx 32231 Nov 16 16:02 /home/xxx/repos/typechain-example/flipper/target/ink/flipper.contract
$ npx @727-ventures/typechain-polkadot --in ./flipper/target/ink/flipper.contract --out ./output
Error: ENOTDIR: not a directory, scandir '/home/xxx/repos/typechain-example/flipper/target/ink/flipper.contract'
    at Object.readdirSync (node:fs:1406:3)
    at Object.<anonymous> (/home/xxx/repos/typechain-example/node_modules/@727-ventures/typechain-polkadot/index.ts:86:29)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Module.m._compile (/home/xxx/repos/typechain-example/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/xxx/repos/typechain-example/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -20,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: '/home/xxx/repos/typechain-example/flipper/target/ink/flipper.contract'
}
npm notice 
npm notice New major version of npm available! 8.18.0 -> 9.1.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.1.1
npm notice Run npm install -g npm@9.1.1 to update!
npm notice 
```

Seems like it's generating only the hardcoded __sdk_ types:

image

Any ideas what could be the issue here? Also, feel free to include a example contract for easier reproduction of the steps you laid out in your tutorial.

**Comment by varex83** [comment]
> 

Thanks for the question. Could you provide your project structure, especially the target dir and arguments you provide in the typechain

**Comment by takahser** [comment]
> Could you provide your project structure

@varex83 sure, I've added them here: https://github.com/takahser/typechain-example

**Comment by varex83** [comment]
> > Could you provide your project structure
> 
> @varex83 sure, I've added them here: https://github.com/takahser/typechain-example

I've updated Guide. You can check, also read docs and check https://github.com/Supercolony-net/typechain-polkadot/tree/master/examples to understand how to use typechain

**Comment by varex83** [comment]
@takahser Any updates? Feel free to ask any questions if you have one

**Review by takahser — CHANGES_REQUESTED** [review]
@varex83 yes I followed the instructions but I got an error.
I described the steps I took [here](https://github.com/takahser/typechain-example/tree/c322cec70c5d09a39c10150e760b5965635c3b48#reproduction-instructions) for your convenience, feel free to reproduce them.

**Comment by varex83** [comment]
> @varex83 yes I followed the instructions but I got an error. I described the steps I took [here](https://github.com/takahser/typechain-example/tree/c322cec70c5d09a39c10150e760b5965635c3b48#reproduction-instructions) for your convenience, feel free to reproduce them.

Thank you for the response! Since input should contain the folder that contains artifacts, it won't work in the way you are doing now (passing the .contract file). Your problem could be fixed by moving metadata.json to the artifacts directory and renaming it to .json, also if you want to deploy the contract, you should also move .contract to artifacts directory from your target dir.

**Comment by takahser** [comment]
@varex83 

> Since input should contain the folder that contains artifacts, it won't work in the way you are doing now (passing the .contract file)

In that case, I should pass `./flipper/target/ink` to the `--in` argument, right?
Unfortunately, it still fails. I updated the [reproduction repo README](https://github.com/takahser/typechain-example/tree/0b760456eecb878142d77ad84ccbf996fb4298ee).

> Your problem could be fixed by moving metadata.json to the artifacts directory and renaming it to .json

So I need to create a separate `/artifacts` directory? Or are you referring to the existing `/target` directory?
In general, it would be nice if you could provide me with the exact steps to follow using the example contract I added to the repo. Alternatively, feel free to add your own.

**Comment by takahser** [comment]
@varex83 thanks, this time it worked. It generated a bunch of files that seem to reflect the types of the contract. I'll take a closer look and give you further feedback soon.

**Review by takahser — CHANGES_REQUESTED** [review]
@varex83 I tried to compile your contract by myself using `cargo +nightly contract build` but it failed with "ERROR: No 'ink_lang' dependency found".
Can you advise me, how to build the contract successfully?

**Comment by varex83** [comment]
> @varex83 I tried to compile your contract by myself using `cargo +nightly contract build` but it failed with "ERROR: No 'ink_lang' dependency found". Can you advise me, how to build the contract successfully?

It's ink! 4 contract, so you need to install new version of cargo contract, you can do this with the following command: `cargo install --force --locked cargo-contract --version 2.0.0-beta.1`

**Review by takahser — CHANGES_REQUESTED** [review]
@varex83 thanks for the advice, it worked.
I finished the first version of my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain_2_takahser.md), feel free to have a look.

**Comment by varex83** [comment]
> @varex83 thanks for the advice, it worked. I finished the first version of my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain_2_takahser.md), feel free to have a look.

Thanks for the reply! I will review it ASAP. Can you try to `gen-test-ts` script before testing https://github.com/727-Ventures/typechain-polkadot/blob/master/packages/typechain-polkadot/package.json, it will generate all typechain files, because it seems to me it could be a problem and also note you should start https://github.com/paritytech/substrate-contracts-node before running tests.

**Comment by varex83** [comment]
Hello @takasher, we have addressed all comments from the evaluation. Please have a look.

**Comment by takahser** [comment]
@varex83 sorry for the delay here, I'll take a look again as soon as possible. You can expect feedback by the end of the week.

**Comment by takahser** [comment]
@varex83 I updated my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain_2_takahser.md), feel free to have a look and ask further questions

**Comment by varex83** [comment]
Hello @takahser ! Thank you for a quick response! 

> It's not clear to me how a contract can be deployed using typechain-polkadot.

We have created simple explanation how to deploy the contract https://github.com/727-Ventures/typechain-polkadot/blob/master/packages/typechain-polkadot/README.md#constructors also you can check other stuff here, and feel free to take a look on how we deploy tests and check our examples

> smoke testing succeeded thanks to the support of the grantee (see convo in the delivery PR), however, it would be nice to see this information incorporated into the docs, incl. compiling an example ink! contract (generating the .contract and .json artifacts) before generating the TypeScript files

We have this information in the README, and more deep info in https://github.com/727-Ventures/typechain-polkadot/blob/master/examples/README.md

> tests are still failing

It seems like you didn’t run the substrate-contracts-node, feel free to take a look on our testing guide: https://github.com/727-Ventures/typechain-polkadot/blob/master/packages/typechain-polkadot/tests/README.md

> In general, I think it's bad design that we need to run 2 scripts to run the tests. This dependency is not obvious any imho unneccessary. It would be better if the files were transcompilated as part of the npm run test script, ahead of running the tests.

We have fixed that! Now you can run all tests with npm run test : ) 

> there are currently a lot of lint issues

We have updated eslint config, in order to not get such errors, in some places we can’t fix warnings or errors, because typechain uses for example arrays, and we assure that everything is ok

>At this point it's unclear which bugs with new versions of polkadot have been fixed. Please explain, as this might be of interest for other projects as well. In the newest delivery report, you mentioned such "problems with gasLimits" but you didn't give any more information. Could you elaborate and maybe show us the PR or code that fixed it?

Sure! We had some problems with new versions of substrate-contracts-node, before we used default gasLimit as -1 and now we are using just big number, feel free to check out our commit https://github.com/727-Ventures/typechain-polkadot/commit/710896c7b9f2677a97f7b84cbf035c5c8fb1996d in file packages/typechain-polkadot/src/output-generators/raw/_sdk/query.ts, we have created preprocessAbi function and added _ before each type’ display name, it was done because of polkadot-js can optimize usage of known types such as Balance, and change it interface that can break typechain-polkadot-parser, also we figured out with ink! 4 update abi changed a little bit, and in some places we used raw abi (mainly in preprocessABI function) so we created __getV3 function that gets everything we need no matter which ink version we are using. You can check that here https://github.com/727-Ventures/typechain-polkadot/blob/master/packages/typechain-polkadot/src/output-generators/_utils.ts#L88

**Comment by 0xMarkian** [comment]
@takahser pls be aware that we also just update the delivery report accordingly. Also, we added additional information there with details. Looking forward to your feedback!

**Comment by varex83** [comment]
@takahser We have updated our README, feel free to have a look https://github.com/727-Ventures/typechain-polkadot/blob/master/packages/typechain-polkadot/README.md

**Review by takahser — APPROVED** [review]
Thanks for taking the time to have a call, it was very helpful to speed up the process.
I decided to accept the delivery, you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/typechain_2_takahser.md).
Please note that the linting errors still persist, it would be nice if this would be fixed. And also, feel free to fix the indentation issues in the newly added [ink! contract](https://github.com/727-Ventures/typechain-polkadot/blob/ca4d8900935eca6a4bb1df2e3beec7214239d7a6/packages/typechain-polkadot/README.md) that serves as an example for deployment using your library.

**Comment by 0xMarkian** [comment]
Thanks a lot for reviewing @takahser! Appreciate taking the call.
Pls let us know how much it would usually take right now to process the payment. Since the grant delivery has taken a lot of time I would appreciate it if the payment could be done as soon as possible as we were relying on this grant. Thanks in advance!

**Comment by takahser** [comment]
@0xMarkian it can take up to two weeks for the payment to be processed.
The grant delivery has taken a lot of time mostly due to unclear and incomplete instructions and because changes that I requested have not been addressed.

**Comment by TtomaS7** [comment]
Hello @takahser, I would like to amend this contract as we have sent an incorrect invoice. 
We would like to open a new PR with the correct invoice, @coreggon11 will do it.

I want to notify you that I left the 727.ventures, so @coreggon11 is going to lead it in the future.
It was a pleasure to work with you and see you around Polkadot ecosystem ✌️

**Comment by takahser** [comment]
@TtomaS7 got it, thanks for telling us. I'll interpret this as a transfer of ownership of the Typechain grant from you to @coreggon11 then.

**Comment by coreggon11** [comment]
@takahser thanks for the reply. I have filled the invoice form once again with a new invoice.

**Comment by 0xMarkian** [comment]
> @0xMarkian it can take up to two weeks for the payment to be processed. The grant delivery has taken a lot of time mostly due to unclear and incomplete instructions and because changes that I requested have not been addressed.

thanks!

**Comment by RouvenP** [comment]
hi @TtomaS7 we transferred the payment today.

**Pull request merged**
