### PR TITLE
submit xcm-tools milestone 1

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1605

### CODE REVIEW

**Comment by randombishop** [comment]
@gmajor-encrypt Thanks for this delivery.

I will work on the evaluation and get back to you with feedback asap...

**Comment by gmajor-encrypt** [comment]
ping @randombishop

**Comment by randombishop** [comment]
Sorry I had a backlog @gmajor-encrypt will make sure i work on this and get back to you this week

**Comment by randombishop** [comment]
Hi @gmajor-encrypt !

I am trying to run the tests on this delivery.

They run fine in `scale.go` repo.

But I couldn't find how to run the tests in `substrate-api-rpc`. I tried `go test ./... --cover -v` but got some errors, see log attached.

I guess I need to be running a substrate node or something right? Can you please provide a guide on how to test or make it part of the docker? (docker run yields the same kind of log file with that error)

Thank you!

[substrate_api_rpc_test.log](https://github.com/w3f/Grant-Milestone-Delivery/files/11358101/substrate_api_rpc_test.log)

**Comment by gmajor-encrypt** [comment]
@randombishop Thanks for your review. It is a network problem. You can try a few more times, or replace this node https://github.com/gmajor-encrypt/substrate-api-rpc/blob/master/rpc/transactions_test.go#L21

This is the test guide
https://github.com/gmajor-encrypt/substrate-api-rpc/blob/master/README.md#test

**Comment by randombishop** [comment]
Hey @gmajor-encrypt !

So I see the tests rely on Alice and Bob accounts too, so I guess I need to connect to a local dev node to run the tests?

I tried running a local polkadot node in dev mode and changing the url to `ws://localhost:9944` but still getting this error at the beginning of the tests:
```
panic: websocket send error: websocket: not connected
```

Can you please explain how to set up the tests exactly to make sure they run?

Thank you!

**Comment by randombishop** [comment]
By the way, the errors are different when using `wss://shibuya-rpc.dwellir.com` 

As you can see in the log file I shared previously, it doesn't show a connection error in the beginning, but later in the tests.

**Comment by gmajor-encrypt** [comment]
@randombishop 

No additional settings are required. I have changed the websocket url and timeout to ensure the stability of the test better.

**Comment by randombishop** [comment]
@gmajor-encrypt thank you for this fix, the tests work fine now and I am happy to accept your delivery.

Please find the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm_tools_1_randombishop.md)

Also, I couldn't find your invoice, did you submit it through this [form](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform)?

**Comment by gmajor-encrypt** [comment]
@randombishop Thanks for your evaluation.

Sorry, I forgot to submit the invoice. I just submitted my invoice. Please help recheck it.

**Comment by gmajor-encrypt** [comment]
@randombishop Hi, I see that you have accepted this delivery, should this pr need to be merged?

**Comment by randombishop** [comment]
@gmajor-encrypt Yes, delivery merged and invoice just forwarded.

Please expect up to 2 weeks for payment.

Cheers!

**Pull request merged**
