### PR TITLE
PolkaKey milestone 1 deliverables

### PR DESCRIPTION
**Pull request by HiZhaoYun**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the milestone delivery. I will look into it as soon as possible.

**Comment by Noc2** [comment]
Everything works as intended (different languages, signatures, etc.). The only issue I noticed is that the app has no icon on ubuntu. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkakey_1_Noc2.md). So, I'm happy to tell you this milestone is a pass! I will forward your invoice internally.

**Comment by HiZhaoYun** [comment]
May I ask how many days it will take to receive the funds?

**Comment by RouvenP** [comment]
> May I ask how many days it will take to receive the funds?

Hi @HiZhaoYun 
Your payment will be issued this week. Will let you know as soon as done.

**Comment by RouvenP** [comment]
> May I ask how many days it will take to receive the funds?

@HiZhaoYun: we sent a [test transaction of 0.01 BTC](https://www.blockchain.com/btc/tx/9c59151744f36f55d656872b1f5520ac2fd7586efbf8d3c007939d7b9c4acc36) yesterday. Could you please confirm if received? Thanks

**Comment by HiZhaoYun** [comment]
> > May I ask how many days it will take to receive the funds?
> 
> @HiZhaoYun: we sent a test transaction of 0.01 BTC yesterday. Could you please confirm if received? Thanks

Yes, I received 0.01BTC :)

**Comment by RouvenP** [comment]
> > > May I ask how many days it will take to receive the funds?
> > 
> > 
> > @HiZhaoYun: we sent a test transaction of 0.01 BTC yesterday. Could you please confirm if received? Thanks
> 
> Yes, I received 0.01BTC :)

You should have received the remainder now. Thanks!

**Pull request merged**
