### PR TITLE
Evanesco_Network_milestone1_and_2

### PR DESCRIPTION
**Pull request by eva-networks**
Commit milestone 1 and milestone 2

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by eva-networks** [comment]
It seems there is something wrong with the two milestone files, do I need to re-send one of them again?

**Comment by semuelle** [comment]
Hi @eva-networks, thanks for the delivery. The Github Action is just for our internal bookkeeping, nothing to worry about. We will look into it as soon as possible.

**Comment by mmagician** [comment]
Hey @eva-networks, I started looking into your delivery recently. When compiling your substrate node, I get the following error:
```
error[E0599]: no method named `unbounded_send` found for struct `tokio::sync::mpsc::unbounded::UnboundedSender` in the current scope
  --> node/src/noise_rpc_api.rs:32:33
   |
32 |             node_request_sender.unbounded_send(whitenoisers::network::whitenoise_behaviour::NodeRequest::GetMainNetsRequest(get_main_nets));
   |                                 ^^^^^^^^^^^^^^ method not found in `tokio::sync::mpsc::unbounded::UnboundedSender<NodeRequest>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `node-template`
```

I'm using latest nightly build `rustc 1.55.0-nightly (6a758ea7e 2021-06-22)`

Do you have any clue on how to resolve that?

**Comment by eva-networks** [comment]
> Hey @eva-networks, I started looking into your delivery recently. When compiling your substrate node, I get the following error:
> 
> ```
> error[E0599]: no method named `unbounded_send` found for struct `tokio::sync::mpsc::unbounded::UnboundedSender` in the current scope
>   --> node/src/noise_rpc_api.rs:32:33
>    |
> 32 |             node_request_sender.unbounded_send(whitenoisers::network::whitenoise_behaviour::NodeRequest::GetMainNetsRequest(get_main_nets));
>    |                                 ^^^^^^^^^^^^^^ method not found in `tokio::sync::mpsc::unbounded::UnboundedSender<NodeRequest>`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0599`.
> error: could not compile `node-template`
> ```
> 
> I'm using latest nightly build `rustc 1.55.0-nightly (6a758ea7e 2021-06-22)`
> 
> Do you have any clue on how to resolve that?

Hi @mmagician it`s a dependency issue, we have fix it and please using the latest stable build `rustc 1.53.0 (53cb7b09b 2021-06-17)`

**Comment by mmagician** [comment]
@eva-networks That fix worked, thanks. It has come to our attention that you are using the grants badge on your website. Since your milestone hasn't been accepted yet, we kindly ask you to remove it until we've merged this PR. For more details, see our [badge guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).

Same applies to your twitter account -> you are not a grant recipient yet, please remove that information until at least one of the milestones is completed and accepted.

Regarding your delivery now: I have found a number of issues with your codebase. Furthermore, it seems to me that not all deliverables from the original contract had been met. I've compiled a preliminary list in [this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/204). At the present state of the delivery, I cannot accept neither of the milestones due to the severity of problems described in that PR. Please review these points accordingly and get back to me to address them.

**Comment by eva-networks** [comment]
> @eva-networks That fix worked, thanks. It has come to our attention that you are using the grants badge on your website. Since your milestone hasn't been accepted yet, we kindly ask you to remove it until we've merged this PR. For more details, see our [badge guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).
> 
> Same applies to your twitter account -> you are not a grant recipient yet, please remove that information until at least one of the milestones is completed and accepted.
> 
> Regarding your delivery now: I have found a number of issues with your codebase. Furthermore, it seems to me that not all deliverables from the original contract had been met. I've compiled a preliminary list in [this pull request](https://github.com/w3f/Grant-Milestone-Delivery/pull/204). At the present state of the delivery, I cannot accept neither of the milestones due to the severity of problems described in that PR. Please review these points accordingly and get back to me to address them.

Thanks @mmagician, we wiil remove the grants badge and review your list soon

**Comment by mmagician** [comment]
Thanks for fixing the clippy warnings and small code refactors. I've updated my evaluation slightly, although I still have major concerts. Please see my replies to your [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/204#issuecomment-869174449) below:

> Specifically, you are able to build a WhiteNoise privacy network by running the customized node template, which can provide privacy connections for clients

Could you outline what I achieve by running your binary from inside node-template, as opposed to running your binary as a standalone package? It's not like it provides anonymity for submitting substrate-based extrinsics. These are completely disconnected networks from what I can see.

As far as I see, the integration provided is limited to:

```
let node = start_noise_server(&cli, &node_keypair);
```

The above starts a WhiteNoise host. I could replace this by any other arbitrary binary and claim that I have integrated with substrate.

---
>  Also the node template can act as a relay node to join a remote WhiteNoise Network to provide services. 

Again, let's make a clear distinction: the `substrate node` doesn't act as a relay server. It's the WhiteNoise host that does. Since they are packaged under one executable `node-template` under the WhiteNoise-For-Substrate project then sure, it's technically correct to say that node template acts as a relay node, but in practice the substrate node` part of it is not involed at all.

---
> For data transmission between adjacent nodes, WhiteNoise will perform traffic confusion and time jitter on the data packet before each time it is sent. 

where is the code for this?

---
Regarding M2:
- it's not necessary to create a separate repository per each milestone. I believe it would be much cleaner if you removed code duplication from the sdk and Whitenoise-client repo. I'll leave the final design up to you.

---
Misc:
Seeing "Dial upgrade error Upgrade(Select(Failed))" in logs

**Comment by eva-networks** [comment]
@mmagician  Thanks for your suggestion. We've merged the branch supporting traffic confusion and time jitter. The following are our proposal for better integration with Substrate：

We implemented the customized node-template to facilitate the simultaneous startup of the Substrate node and the whitenoise node with the same account and rpc. In our design, WhiteNoise is part of a privacy protocol stack. These nodes participating in the WhiteNoise network can get token incentives, and they will also participate in consensus in a specific way. This is the reason why we want Substrate and WhiteNoise to start and share accounts at the same time.

We think it's better to implement components that improve the privacy of Substrate based on the WhiteNoise network. So we have this proposal:

Substrate has implemented rpc based on http, websocket and IPC. Similarly, we will add a WhiteNoise-based rpc component to Substrate, so that clients and Substrate nodes can make rpc requests and responses through the WhiteNoise network. The rpc messages will pass through the WhiteNoise routing node and reach the dest address through multi-hop connection. This can protect the network privacy of both the rpc client and the node. For example, if you use WhiteNoise rpc to send transactions, your IP won't be exposed. This component can be enabled or disabled through configuration.

Specifically, after the Substrate node is started, it will register to the WhiteNoise network and get a WhiteNoiseID. The nodes in this WhiteNoise network can be started by a customized node-template or other WhiteNoise protocol implementations. Then the rpc client establishes a privacy connection by dialing the WhiteNoiseID, and sends an rpc request on this connection. After Substrate nodes receive the request, they also response on the same connection.

----

Regarding M2:

Thanks for the suggestion, we will adjust the code and repo structure.

---

> For data transmission between adjacent nodes, WhiteNoise will perform traffic confusion and time jitter on the data packet before each time it is sent.

We've merged the branch supporting traffic confusion and time jitter. [Code](https://github.com/Evanesco-Labs/WhiteNoise.rs/blob/main/src/network/utils.rs#L359).

---

Misc:

> Seeing "Dial upgrade error Upgrade(Select(Failed))" in logs

This log does not affect the functionality of the WhiteNoise protocol.

It appears because after a client connects to a WhiteNoise node, the WhiteNoise node will try to new a substream of gossipsub protocol with the client. But the client does not support  gossipsub protocol and not need to, so the dial fails and returns this error.

**Comment by mmagician** [comment]
> Similarly, we will add a WhiteNoise-based rpc component to Substrate, so that clients and Substrate nodes can make rpc requests and responses through the WhiteNoise network

So if I understand correctly, you are currently working on this right? To me this would better reflect the deliverable of "substrate integration" than the current status of the project. Ideally you would provide automated tests which easily allow to verify that the request sender's identify is indeed hidden when using WhiteNoise network, and exposed when using the node without this option.

**Comment by eva-networks** [comment]
Yes @mmagician  ,we are working on the WhiteNoise-based rpc now, and the automated tests will also be provided. We will let you know as soon as it ready for review.

**Comment by calehh** [comment]
@mmagician We've implemented the WhiteNoise-based rpc and integrated it with substrate. WhiteNoise rpc clients and substrate nodes can now send jsonrpc requests and responses through the WhiteNoise network. These implementations are in repositories [WhiteNoise-RPC](https://github.com/Evanesco-Labs/WhiteNoise-RPC.git) and [Evanesco-Labs/substrate](https://github.com/Evanesco-Labs/substrate.git). We also add these two repositories to the [Evanesco_Network-Milestone_1.md](https://github.com/Evanesco-Labs/Grant-Milestone-Delivery/blob/master/deliveries/Evanesco_Network-Milestone_1.md).

**Comment by mmagician** [comment]
@calehh @eva-networks Is there a difference between running the `node-template` from [substrate fork](https://github.com/Evanesco-Labs/substrate) or [WhiteNoise-For-Substrate](https://github.com/Evanesco-Labs/WhiteNoise-For-Substrate)?

I just tried running the following setup:
- 2 instances of node-template from [WhiteNoise-For-Substrate](https://github.com/Evanesco-Labs/WhiteNoise-For-Substrate)
- bootstrap node (as above)
- local WhiteNoise-RPC client

When I send an RPC request as outlined in your tutorial, I get:
```
2021-07-29 16:42:44 12D3KooWJgwGfpWJGZWAcxpQQHfVW4Jj7WjcryFbHdvGEVZ1KARt have connected
2021-07-29 16:42:44 [WhiteNoise] Ack as sink node, session id:8fX3WEpTZJAXWC8ry1qvFYpGkmRzAaXz7yczrHUfRxPD
2021-07-29 16:42:44 [WhiteNoise] i donnot contains probe
```

-> nothing gets returned and the RPC-client gets stuck.

---
Also, when I submit RPC calls from `https://polkadot.js.org/apps/`, the results are returned correctly, but there's nothing in the node logs (especially nothing from the Whitenoise logs).

Am I missing something?

**Comment by calehh** [comment]
@mmagician @eva-networks `node template` from [substrate fork](https://github.com/Evanesco-Labs/substrate) and [WhiteNoise-For-Substrate](https://github.com/Evanesco-Labs/WhiteNoise-For-Substrate) is different. 

Substrate fork starts a WhiteNoise rpc server which act as a WhiteNoise client. And WhiteNoise-For-Substrate starts a WhiteNoise relay node or bootstrap node parallel with substrate node, it has no WhiteNoise rpc function. There is no duplication of functions about WhiteNoise between the two. Sorry that their names may be confusing.

So to run this test example, you may first start a WhiteNoise network, with nodes either from [Whitenoise.rs](https://github.com/Evanesco-Labs/WhiteNoise.rs) or [WhiteNoise-For-Substrate](https://github.com/Evanesco-Labs/WhiteNoise-For-Substrate). Then start a `node template` from [substrate fork](https://github.com/Evanesco-Labs/substrate), which is the WhiteNoise rpc server. Finally call it from [WhiteNoise-RPC](https://github.com/Evanesco-Labs/WhiteNoise-RPC).

To add, we didn't modify code in `\bin\node-template` package of [substrate fork](https://github.com/Evanesco-Labs/substrate). The WhiteNoise rpc function is added to substrate framework, so it can be used by other node implementations based on this substrate fork.

**Comment by mmagician** [comment]
@eva-networks Apologies for the delay, I'll have another look at your code as soon as I can.

**Comment by mmagician** [comment]
@eva-networks I've had another go at running your application, and still I'm experiencing issues:

1. 
> So to run this test example, you may first start a WhiteNoise network, with nodes either from Whitenoise.rs or WhiteNoise-For-Substrate. Then start a node template from substrate fork, which is the WhiteNoise rpc server. Finally call it from WhiteNoise-RPC.

When running a WhiteNoise network composed of `WhiteNoise-For-Substrate` nodes, I am not able to connect the substrate fork node, with the following error message:
```
2021-08-18 14:28:48.975 DEBUG                 main whitenoisers::sdk::host: local peer id: PeerId("12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp")
2021-08-18 14:28:48.976 DEBUG    async-std/runtime whitenoisers::network::whitenoise_behaviour: receive node request for client
2021-08-18 14:28:48.976 DEBUG    async-std/runtime whitenoisers::network::whitenoise_behaviour: receive node request for client
2021-08-18 14:28:48.976 DEBUG    async-std/runtime libp2p_swarm: New dialing attempt to peer PeerId("12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp") failed: ConnectionLimit(ConnectionLimit { limit: 0, current: 0 }).
2021-08-18 14:28:48.976 DEBUG    async-std/runtime whitenoisers::network::whitenoise_behaviour: proxy outbound failure:DialFailure
```

Now, these are of course two incompatible chains, so they should not be able to *form a blockchain* together, but as I understand, this should be independent of connecting as WhiteNoise clients, right?

2. When I run the network composed of Whitenoise.rs nodes, substrate fork node seems to connect to the network:
```
2021-08-18 14:31:48 [WhiteNoise] finished get mainnets this turn:5MUeAz3UwWjkreXzL8seC87dJwb3qv4NgeabouMyHq3U
```

However, I do not see any WhiteNoiseID as outlined in your [README](https://github.com/Evanesco-Labs/substrate#start-substrate-node-template), so it seems I cannot really send any RPC calls from [WhiteNoise-RPC](https://github.com/Evanesco-Labs/WhiteNoise-RPC).

In addition I see these logs in WhiteNoise.rs bootstrap node:
```
[2021-08-18T12:40:14.799Z INFO  libp2p_gossipsub::behaviour] New peer connected: 12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp
[2021-08-18T12:40:14.800Z WARN  libp2p_gossipsub::handler] Dial upgrade error Upgrade(Select(Failed))
```

I am not sure whether I am following the instructions wrong? I would again like to ask you to clarify the tutorial and delivery documentation for this milestone. Up until now I still haven't been able to test your work properly, and I imagine this would be even harder for a newcomer who is not familiar with substrate.

**Comment by calehh** [comment]
@mmagician 
1.

> When running a WhiteNoise network composed of WhiteNoise-For-Substrate nodes, I am not able to connect the substrate fork node 

This failed because the substrate fork uses the same node-key as the WhiteNoise bootstrap node. If they are using the same node-key,  their PeerId derived from the node-key is also the same. Like in the error message you gave:

```
2021-08-18 14:28:48.975 DEBUG                 main whitenoisers::sdk::host: local peer id: PeerId("12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp")

2021-08-18 14:28:48.976 DEBUG    async-std/runtime libp2p_swarm: New dialing attempt to peer PeerId("12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp") failed: ConnectionLimit(ConnectionLimit { limit: 0, current: 0 }).

```

One node cannot dial another node with the same PeerId, so the connection failed.

This kind of error may be caused by two misleading commands in Readme. One is in substrate fork Readme to start a node-template with WhiteNoise based RPC: 

```
./rpctest/node-template \
--base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9945 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --validator \
--whitenoise-bootstrap /ip4/127.0.0.1/tcp/6661/p2p/12D3KooWMNFaCGrnfMomi4TTMvQsKMGVwoxQzHo6P49ue6Fwq6zU
```

Another is in Whitenoise-For-Substrate Readme to start a bootstarp node of WhiteNoise network:

```
cd path/to/boot
nohup ./node-template \
--base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9945 \
  --rpc-port 9933 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --validator \
--noise-port 3331 &
```

First, the flag `--alice` may conflict between two node-template nodes. Second, the same parameter in the `--node-key` flag may cause starting two node-template with the same node-key.

So to start each node-template, use different shortcut flags like `--alice`, `--bob` ... `--dave`and different `--base-path` flags , also unset the `--node-key` flag. This will avoid key duplication issues. We will modify and supplement in Readme.

2.
Have you constructed a WhiteNoise network with a bootstrap node and at least one routing node? If only the bootstrap node is started, the WhitenoiseID will not be displayed after the substrate fork node is connected. 
After requesting the mainnet nodes information from bootstrap, the fork node will select one to register. Then print WhiteNoiseID and other information. The complete log is as follows：

```
2021-08-20 11:35:10 [WhiteNoise] finished get mainnets this turn:5MUeAz3UwWjkreXzL8seC87dJwb3qv4NgeabouMyHq3U    
2021-08-20 11:35:10 [WhiteNoise] mainnets address:["/ip4/127.0.0.1/tcp/3332", "/ip4/192.168.1.21/tcp/3332"],peer_id:PeerId("12D3KooWD1eU9Yypepvzx5vZvgd6ZkzAm7EijXtHjh56yWKafe4A")    
2021-08-20 11:35:10 [WhiteNoise] mainnets address:["/ip4/127.0.0.1/tcp/3333", "/ip4/192.168.1.21/tcp/3333"],peer_id:PeerId("12D3KooWAWhc2B7uH6rgWkpk67y2ZmMCQ39HoSoTMrPp1XYsrHxd")    
2021-08-20 11:35:10 [WhiteNoise] mainnets address:["/ip4/127.0.0.1/tcp/3334", "/ip4/192.168.1.21/tcp/3334"],peer_id:PeerId("12D3KooWJ3zvVWKzZBDwVaXgiVTSuc4TuWRrLgDPipM1PVfx5esM")    
2021-08-20 11:35:10 [WhiteNoise] mainnets address:["/ip4/127.0.0.1/tcp/3335", "/ip4/192.168.1.21/tcp/3335"],peer_id:PeerId("12D3KooWKhyxA98ku14DZCe4n3e2ThzS66E3YfHh5qS59c6qrf33")    
2021-08-20 11:35:10 choose id:PeerId("12D3KooWD1eU9Yypepvzx5vZvgd6ZkzAm7EijXtHjh56yWKafe4A") to register    
2021-08-20 11:35:10 [WhiteNoise] local whitenoise id:0FCef6bii1q66vijFpft4UQ5NtrMkKfd66JgNKJ6o5XF1    
2021-08-20 11:35:10 [WhiteNoise] finished register proxy this turn:Ack { command_id: "HqNtdnpE2n5G13vUfRyYKA5TQqn4U9xCfL9iRVnqBWjf", result: true, data: [] }  
```

It is true that WhiteNoiseID should be printed right after startup. We will changes this right away.



> [2021-08-18T12:40:14.800Z WARN  libp2p_gossipsub::handler] Dial upgrade error Upgrade(Select(Failed))

Besides, this gossipsub upgrade warning, doesn't affect our functionality.

If you have already started multiple routing nodes, please tell us the more logs of bootstrap node and substrate fork node to help analyze the problem.


We will revise the documents right away and let you know as soon as we are done.

**Comment by calehh** [comment]
@mmagician We removed the repo `WhiteNoise-For-Substrate` from milestone 1. Also We updated the documentation, add a tutorial and update delivery. Please check them out.

**Comment by calehh** [comment]
@mmagician Did it run successfully? We also add test net bootstrap address in the [tutorial](https://github.com/Evanesco-Labs/substrate/blob/master/tutorial.md), you can try it.

**Comment by mmagician** [comment]
@calehh @eva-networks That worked indeed. There are still some minor, cosmetic issues that I've listed in the evaluation for milestones 1 & 2. Please review the files in my [PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/204/files) to address these. But we're on a good track now, it shouldn't take you long now hopefully 👍🏼

**Comment by calehh** [comment]
@mmagician We have fixed the log error and add Apache 2.0 license to repositories. Also we move the p2p private chat application from Whitenoise-client.rs into WhiteNoise.rs and remove duplicate codes. Now this chat client can be compiled from WhiteNoise.rs. A Docker setup for testnet is a good suggestion, we will add it in the future.
Please check out the changes.

**Comment by mmagician** [comment]
Thanks for these updates and congratulations, your milestones have now been officially accepted! You can view the evaluations [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/204).

**Comment by calehh** [comment]
@mmagician Thanks you for your patient review! Normally when will the payment be made?

**Comment by mmagician** [comment]
Usually within two weeks of acceptance. If it takes longer than that, please ping me here

**Comment by eva-networks** [comment]
@mmagician

**Pull request merged**
