### PR TITLE
Delivery hyperdot milestone 2

### PR DESCRIPTION
**Pull request by cattania**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1815

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @cattania many of us were out for the holidays. I will start on this in the next day or two.

**Review by semuelle — COMMENTED** [review]
Hi @cattania, thanks for the delivery. I am testing hyperdot.xyz at the moment, and I'm not able to get any queries to work. For example, `select * from bigquery-public-data.crypto_polkadot.accountreference0 where block_number > 18900000` results in popups "I is undefined" and "http error" and in the console I get a 504 error. Can you advise?

**Comment by cattania** [comment]
Hi @semuelle , thanks for reply, We checked that the service queries on the backend were working, and finally we found out that because we're using Cloudflare proxies, the `select * from bigquery-public-data.crypto_polkadot.accountreference0 where block_number > 18900000` running needs to process a lot of data, so it takes a while to run, in fact it takes about 1m21s to process. But Cloudflare closes the connection by default after 60s.


We've adjusted the infrastructure so that's not a problem now.
image

For queries, since the on-chain data of the index is huge and our server has limited resources, we recommend adding some condition for filtering and adding limit to limit the size of the data returned, for example `select * from bigquery-public-data.crypto_polkadot.accountreference0 where block_number > 18900000 limit 100`

**Review by semuelle — APPROVED** [review]
Thanks for the update, @cattania. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperdot_2_semuelle.md). 

Congratulations on completing the grant. I hope you will continue working on it to make it a success. I left some improvement suggestions in the evaluation notes, I suggest you have a look and let me know if anything's unclear.

**Comment by cattania** [comment]
> Thanks for the update, @cattania. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/hyperdot_2_semuelle.md).
> 
> Congratulations on completing the grant. I hope you will continue working on it to make it a success. I left some improvement suggestions in the evaluation notes, I suggest you have a look and let me know if anything's unclear.

Thank you for your response, we will follow your guidance and continue to optimize the hyperdot experience to make it successful, we firmly believe that this is valuable, thank you again for your guidance on hyperdot.

**Comment by cattania** [comment]
Hi @semuelle,  I'm sorry to disturb you. We have submitted the invoice, and we need to upgrade the server further. Is there any progress regarding the payment information?

**Comment by semuelle** [comment]
Hey @cattania, the invoice is being processed right now. It should be paid Friday latest.

**Comment by cattania** [comment]
Hey @semuelle , Thank you very much for your reply, great for us!!

**Comment by RouvenP** [comment]
hi @cattania we just sent the payment

**Pull request merged**
