### PR TITLE
add Solang Playground milestone 3

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1894

### CODE REVIEW

**Comment by ditavia-br** [comment]
Hi, we'll do this evaluation.

**Comment by salaheldinsoliman** [comment]
@ditavia-br Hello,
I addressed your questions in a comment in the PR. please let me know if the comment answers your questions

**Comment by ditavia-br** [comment]
@salaheldinsoliman thanks for the answer. The milestone is accepted from our side. Great job!

**Comment by semuelle** [comment]
Hey @salaheldinsoliman, I am doing a cursory review of the evaluation. I tried compiling the example contract using the deployed version you link in the repo README, but I'm getting `ERR_CONNECTION_REFUSED` in the console. Might be related to the certificate warning I'm getting, but this is on both Firefox and Chrome. Am I missing something?

**Comment by salaheldinsoliman** [comment]
@semuelle Hello, can you please try `edge` instead? and make sure the connection is `http` is instead of `https` ?
This is temporary, as we have initiated conversations with Hyperledger labs to provide a suitable domain name.
Please let me know if you still have problems

**Comment by keeganquigley** [comment]
Hi @salaheldinsoliman thanks for your help, I was able to get it to run on both the deployed (unsecured) version and at `http://localhost:9000/` 

playground

Unit tests are all passing but with a few warnings. Consider fixing these for the next milestone. Other than that I was able to reproduce everything, and since @ditavia-br has accepted your delivery, I'm happy to pass this milestone. Thanks for the nice work and looking forward to seeing UI improvements on the next one.

**Pull request merged**
