### PR TITLE
Create SydTek_Milestone3.md

### PR DESCRIPTION
**Pull request by jgophd**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x ] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1183

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Hey @jgophd. Thanks for the delivery. I agree with Keegan that waiting for IEEE doesn't make sense when the article is available on arXiv. Regarding deliverable 1a, have you held any of these virtual sessions yet?

**Comment by semuelle** [comment]
pinging @jgophd

**Review by semuelle — APPROVED** [review]
Thanks for the info. I have approved the milestone. We usually don't approve deliverables in advance, but in this situation there is no need to wait for the publisher. Also, as academics, I know that it's in your best interest to share the findings beyond arXiv. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sydtek_3_semuelle.md). 

I have forwarded your invoice for processing. Best of luck with the publication and the presentations! Please share your notes/findings/recordings of the virtual sessions with us when you've held them.

**Comment by RouvenP** [comment]
hi @jgophd we transferred the payment today

**Pull request merged**
