### PR TITLE
Standard Protocol Milestone 1 Delivery 

### PR DESCRIPTION
**Pull request by hskang9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Grants-Program/pull/244
Amendment: https://github.com/w3f/Grants-Program/pull/514

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
I've done a first round of the evaluation of your project. Most sub-deliverables have been achieved, though I've got some minor issues and questions. I've created a draft evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/242), please get back to me once you've addressed my comments there and hopefully we can proceed with the milestone soon.

**Review by hskang9 — COMMENTED** [review]
I will get things done for required changes as soon as possible

**Comment by mmagician** [comment]
@hskang9 We've noticed that you are using the Grants Badge on your website.
We will be [deprecating](https://github.com/w3f/General-Grants-Program/pull/458) the badge soon.
Regardless, even under the current badge guidelines your milestone hasn't been merged yet and so I would kindly ask you to remove it.

**Comment by Noc2** [comment]
Also just for additional clarification: teams should only use the badge in the context of the grant and “don’t: display the badge on your team’s landing page”, see https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md

**Comment by hskang9** [comment]
oh I see. I will remove it for now.

**Comment by hskang9** [comment]
Alright so, 
I fixed pallet asset-registry [here](https://github.com/digitalnativeinc/standard-substrate/commit/745ba5437e7c5c32fcf02a50abf57c7bf135c2ce),
I updated validator docs for oracle to build from sources [here](https://validator.standard.tech/provider-setup/oracle-binary), orml submodule seems hard since we have not seen polkadot v0.9.6 dependancies so we are making local commit, for chainlink attributes, I think now the oracle module has different mechanisms from chainlink in that the module asks information from the node on the other hand our oracle module accepts information from the off-chain client. The direction is opposite. For the term slot, I replaced the term to socket [here](https://github.com/digitalnativeinc/standard-substrate/tree/open-grants-milestone1-fix)

**Comment by hskang9** [comment]
Badge is removed

**Comment by hskang9** [comment]
1. We are targeting the recent confirmed version which produces block in rococom, and v0.9.6 is now verified version which produced block after running our local rococo testnet. For v0.9.8, we need to find parts around to build it new to get confirmed by the team's devops. Hopefully, it seems we just need to change the tag, and the team is now updating parts now.  
2. It is true that local copy is not a good development practice, and we were having issues with versions in polkadot...until we found this [commit](https://github.com/open-web3-stack/open-runtime-module-library/commit/ca054d3078a8d157d0c176ed319d6ff49f38d349). Now we may finally be able to add submodule.
3. for `cargo test` errors, I think you are working on oracle module on master branch, so I am pushing changes in grant milestone 1 to master.

**Comment by hskang9** [comment]
@mmagician now all tests have been done at master. Please check if there is any issues

**Comment by mmagician** [comment]
Ok, I can accept submodules if you really want to stick with it, but I really don't understand why you can't just reference these 3 ORML modules directly from your `Cargo.toml` by their git repo & commit?

You still haven't removed the template pallet, this is already the third time I'm mentioning it.

Regarding testing, I'm confused as to whether to use `master` branch now, or your custom branch? (right now I'm using `master` and it still fails. Just so you know, I'm running `cargo test` from the root of your project, so it tests all modules)

**Comment by hskang9** [comment]
Oops, I wasn't aware after merging for `pallet-template`. Thank you for letting me know, we are now  upgrading to `v0.9.8` though. For submodule, i mean it would be great if we import directly, but we might need to fiddle around with it in some cases so we kept it there. For `cargo test`, we use `nightly

**Comment by hskang9** [comment]
For `cargo test`, I found errors regarding `frame_system` after versioning up and pallet-staking-reward-curve precision failed precision test. I will commit once the tests are fixed.

**Comment by mmagician** [comment]
Okey, I'm going to put this PR on hold. Let me know once you are ready with the rest!

**Comment by hskang9** [comment]
@mmagician So I removed template pallet, found orml's working v0.9.8 commit, and tests are now updated after versioning up to v0.9.8. I have checked all the points that was referred but please let me know if we miss anything.

**Comment by hskang9** [comment]
@mmagician So I removed template pallet, found orml's working v0.9.8 commit, and tests are now updated after versioning up to v0.9.8. However, it seems orml is having problems in mock.rs which it cannot find pallet_elections_phragmen dependancy. This will cause `cargo test` to break. Should we make local commit to this package to pass the test?

**Comment by hskang9** [comment]
Other than the errors from orml tokens breaking mockups, all of our internal errors has been fixed. to check this, change `orml-token`'s cargo.toml 's pallet-elections-phragmen dependancies to 
```
pallet-elections-phragmen = { version = "4.0.0", default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.8" }

```

**Comment by hskang9** [comment]
@mmagician now it is done. Please let me know if there are any other issues

**Comment by mmagician** [comment]
@hskang9 I'll check it shortly, thanks for the update!

**Comment by mmagician** [comment]
@hskang9 Congratulations, the milestone has been accepted now! Please check my full evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/standard-protocol_1_mmagician.md).

**Comment by hskang9** [comment]
Thank you! I will make milestone 2 as soon as possible.

**Comment by hskang9** [comment]
Thank you @RouvenP , I received it.

**Pull request merged**
