### PR TITLE
Melodot milestone 1

### PR DESCRIPTION
**Pull request by DarkingLee**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1804

### CODE REVIEW

**Comment by DarkingLee** [comment]
Dear Committee, I've reused the code from the Apache 2.0 license in a few places. I have already provided proper attribution ([e.g.](https://github.com/ZeroDAO/melodot/blob/w3f/primitives/src/blob.rs#L349)), but I am uncertain if this is sufficient. If there is anything else I might have missed, please let me know.

**Comment by dastansam** [comment]
hey @DarkingLee,

[here](https://github.com/w3f/Grant-Milestone-Delivery/pull/944) is the external evaluation of your milestone.

**Comment by keeganquigley** [comment]
Thanks @DarkingLee sorry for the delay. Everything looks good. I wanted to take some time to research erasure coding. Looking through the attributions, I believe all are done correctly. Here are the [requirements](https://www.apache.org/licenses/LICENSE-2.0) for reference. Your evaluation has been accepted; therefore the milestone is passed. I will forward your invoice for processing.

**Comment by DarkingLee** [comment]
@meldien Hope everything is going well on your end. Could you please provide an update on the payment status?

**Comment by meldien** [comment]
@DarkingLee this would be paid this week

**Pull request merged**
