### PR TITLE
`pallet-drand-client` milestone 1

### PR DESCRIPTION
**Pull request by random-ham**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1271

--- 

Also, the `milestone-deliverables-guidelines.md` hyperlink is broken in the milestone template document.

### CODE REVIEW

**Comment by random-ham** [comment]
cc @random-bacon

**Comment by keeganquigley** [comment]
Hi @random-ham thanks for the delivery. Someone from our team will look at it shortly.

**Comment by 0xCaso** [comment]
Hi @random-ham, I'm starting the evaluation and I'll reach out if I have any questions.

In the meantime, could you slightly improve the delivery document you've committed, adding the deliverables 0a, 0b and 0c you provided in the application document?

**Review by 0xCaso — COMMENTED** [review]
Hi @random-ham, I'm starting the evaluation and I'll reach out if I have any questions.

In the meantime, could you slightly improve the delivery document you've committed, adding the deliverables `0a. License`, `0b. Documentation` and `0c. Testing Guide` you provided in the application document?

**Review by 0xCaso — CHANGES_REQUESTED** [review]
I also leave [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pallet-drand-client_1_0xCaso.md) my evaluation, please review it and answer to the comments.

**Comment by 0xCaso** [comment]
Hi @random-ham, any updates?

**Comment by random-bacon** [comment]
Hi @0xCaso. Apologies for the delay. Let me reply to the notes from your evaluation:
> 1. To compile the code, I had to add #![feature(format_args_capture)] on top of the source, is it normal?

No, that doesn't sound right. Both myself and @random-ham have verified that the code compiles as-is.
We verified it for both latest `stable` as well as latest `nightly` versions of Rust.
If you wish, I could add a [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) to the project, but IMHO this would artificially limit the repository. Before we go down the route of pegging Rust, please first make sure you have the latest `stable`, should be 1.66.1 as of today, and then try: `cargo update; cargo clean; cargo build`. I hope this resolves the issue.

> 2. The coverage is 57/89 = 64%, is it improvable?

When I run `cargo tarpaulin` on the project root, I get:
```
77.70% coverage, 115/148 lines covered
```
May I ask which command you ran to get a different coverage?

If you check our `tests/mod.rs`, you will see that all the API functions are tested at least once. Notwithstanding, I added one extra test `get_latest_err`, which showcases what happens when a response is malformed. The logic for `get_round_err`, `get_info_err`, etc. is identical, so these are skipped for brevity.
The new test is pending @random-ham's review here: https://github.com/random-meat/drand-substrate-client/pull/11

> 3. It would be nice to provide a minimal setup (substrate-contract-node)

I fully agree. Please note though that this is the crux of Milestone 2 :) That's why we left it out of this delivery.

**Review by 0xCaso — COMMENTED** [review]
Hi @random-bacon, no worries, and thanks a lot for the answers!
1. I tried to run `cargo update; cargo clean; cargo build` but didn't solve the issue, which is the following:

    ```Rust
    error: there is no argument named `round`
       --> src/lib.rs:155:41
        |
    155 |         url_str.extend(format!("/public/{round}").as_bytes().to_vec());
        |                                         ^^^^^^^
        |
        = help: if you intended to capture `round` from the surrounding scope, add `#![feature(format_args_capture)]` to the crate attributes
    
    error: could not compile `drand-substrate-client` due to previous error
    ```
    By the way, I tried to build it in my local machine and it works. Probably there is some misconfiguration in the remote machine I've been using, but still it's strange as I've run the commands to "clean" cargo; Do you have any idea what the problem might be? If not, I'll just proceed as the build works in my local machine;
2. I think I made something wrong, and for some reason I just counted the coverage for the `lib.rs` file. By the way thanks also for the new addictions;
3. You're absolutely right, sorry ;) so if the only way to test the functionality is using it directly in a pallet, I'll wait for the next milestone (if you have no advice on how to test it apart from automatic tests)!

**Comment by random-bacon** [comment]
1. My guess is that your remote machine is using an older version of Rust. You can verify the Rust version with `rustup show`. If that's not the case, I'm not sure, I haven't seen this error before.
2. Let me explain in more detail. The usage of standard libraries for networking is not possible in the context of substrate, because the WASM runtime is limited to `no_std` context. If you look at a "native" (i.e. `std` is allowed) library for drand in Rust, you will see that it relies on other 3rd party libs like [reqwest](https://docs.rs/reqwest/latest/reqwest/), see [usage here in drand-rs](https://github.com/iprs-dev/drand-rs/blob/master/src/http.rs#L164), which as I mentioned is not allowed in the context of substrate. Therefore if you want to make any http calls from substrate (specifically, from the off-chain worker), you need to use the substrate-specific package to do that, namely the `sp_runtime::offchain::http` module. As such, the only context that's allowed for actually executing such calls is the substrate context, and so we make the full circle in that we indeed cannot fully* test it in a stand-alone library.

*notice that this is precisely why `sp_runtime::offchain::{testing, OffchainWorkerExt}`is provided by `sp_runtime` crate, to allow to test these features quickly, without the need of spinning up a full substrate node, which is slow and inefficient for testing something as simple as an http call.

This is the best we can do without providing the full-fledged solution of Milestone 2 which we're working on, and is a standard engineering practice to use mock calls.

I hope this resolves any outstanding questions you may have, otherwise let us know please!

**Comment by 0xCaso** [comment]
Thank you very much for the very detailed and comprehensive answer @random-bacon! Now it's very clear, I was quite curious ;) and as you said the mock calls are enough to test the functionality. I am updating the evaluation to accept the delivery.

**Review by 0xCaso — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
@random-bacon I just forwarded internally the invoice, please allow up to 14 days for the payment.

**Comment by RouvenP** [comment]
hi @random-bacon we transferred the payment yesterday.

**Pull request merged**
