### PR TITLE
Adding polkadot_analytics_platform_m1.md

### PR DESCRIPTION
**Pull request by rbrandao**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1883

### CODE REVIEW

**Comment by nikw3f** [comment]
It would be great if https://github.com/mobr-ai/PolkadotAnalytics/blob/main/pap/swagger.yml can be deployed somewhere in swagger UI

**Comment by rbrandao** [comment]
> It would be great if https://github.com/mobr-ai/PolkadotAnalytics/blob/main/pap/swagger.yml can be deployed somewhere in swagger UI

Hi Nikhil, do you mean deploying it on SwaggerHub ? 

When you run the platform locally, the openAPI/swagger specification is served on http://127.0.0.1:5000/. Alternatively, you could import the github raw URL (https://github.com/mobr-ai/PolkadotAnalytics/raw/main/pap/swagger.yml) in Swagger Editor (https://editor.swagger.io/) for a formatted visualization. Would that work for you?

**Comment by nikw3f** [comment]
Hey team, I would recommend the usage of virtual environments https://docs.python.org/3/library/venv.html for https://github.com/mobr-ai/PolkadotAnalytics as we are installing custom requirements. It keeps default python installation error free. Also it would be great if you can add the relevant `venv` commands in README.

**Comment by rbrandao** [comment]
> Hey team, I would recommend the usage of virtual environments https://docs.python.org/3/library/venv.html for https://github.com/mobr-ai/PolkadotAnalytics as we are installing custom requirements. It keeps default python installation error free. Also it would be great if you can add the relevant `venv` commands in README.

Hi Nikhil, we just added the virtual environment instructions to the README (section a). 

Thanks for the heads up.

**Comment by nikw3f** [comment]
Thanks for the delivery @rbrandao Good Work! You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot_analytics_platform_1_nikw3f.md) here.

**Review by nikw3f — APPROVED** [review]

**Comment by rbrandao** [comment]
> Thanks for the delivery @rbrandao Good Work! You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot_analytics_platform_1_nikw3f.md) here. Happy to pass the milestone.

Thanks for the swift review, @nikw3f . 

We at MOBR are really excited with the roadmap for the upcoming Polkadot Analytics Platform. Looking forward to the next stage.

**Pull request merged**
