### PR TITLE
Subalfred milestone 3

### PR DESCRIPTION
**Pull request by AurevoirXavier**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1158

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @AurevoirXavier thanks for the delivery. We appreciate it and someone will be assigned to look at it shortly.

**Comment by randombishop** [comment]
Hi @AurevoirXavier, I'll start working on this evaluation and get back to you with feedback in upcoming days...

**Comment by AurevoirXavier** [comment]
> Hi @AurevoirXavier, I'll start working on this evaluation and get back to you with feedback in upcoming days...

Hi! Any feedback?

**Comment by randombishop** [comment]
@AurevoirXavier Sorry I got caught on another task, just getting started on this today. Will get back to you soon...

**Comment by randombishop** [comment]
@AurevoirXavier Checked the codebase and the github actions and it looks good to me. The delivery is pending a final check and should be approved soon...

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier Checked the codebase and the github actions and it looks good to me. The delivery is pending a final check and should be approved soon...

Cool. Thanks.

**Comment by randombishop** [comment]
Hey @AurevoirXavier

Happy to inform you that your delivery was accepted.

Evaluation notes here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup_1_randombishop.md

I forwarded your invoice to the finance team, please allow for up to two weeks for processing.

**Comment by RouvenP** [comment]
hi @AurevoirXavier we transferred the payment today

**Comment by AurevoirXavier** [comment]
> hi @AurevoirXavier we transferred the payment today

Confirmed. Thanks.

**Pull request merged**
