### PR TITLE
zkwasm rollups transfer milestone 1

### PR DESCRIPTION
**Pull request by ashWhiteHat**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1487

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@ashWhiteHat thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_1_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by ashWhiteHat** [comment]
> Could you explain how you got the values for deliverable 2 and if I can reproduce it?

Sorry for lack of explanation.

# Jubjub Curve
https://github.com/KogarashiNetwork/Kogarashi/tree/master/primitive/jubjub

## Unit Test

```sh
cd primitive/jubjub
cargo test
```
https://github.com/KogarashiNetwork/Kogarashi/tree/master/primitive/jubjub#test

## Benchmark
https://github.com/KogarashiNetwork/Kogarashi/tree/master/benches

Jubjub curve points arithmetic benchmark.
https://github.com/KogarashiNetwork/Kogarashi/blob/master/Cargo.toml#L99
Jubjub field arithmetic benchmark.
https://github.com/KogarashiNetwork/Kogarashi/blob/master/Cargo.toml#L91

> The repository has some broken links

Thank you for letting me know.
It seems relative path doesn't work.
I fixed all links.

> or is it the all the content of the site?

I would say all the content of the site.

- What's RedDSA?
https://kogarashinetwork.github.io/Kogarashi/technical/reddsa_signature/
- RedDSA wallet tutorial
https://kogarashinetwork.github.io/Kogarashi/tutorial/reddsa_wallet/

However, I think developers still don't know why we should use RedDSA with above contents.
I am going to publish library using RedDSA and article describing it next week.

> I had some problems with the fund command.

Umm...
Let me check.
It might be problem of command option when we run node.

> The pallets could have better coverage.

Exactly.
I am going to publish library so I will improve coverage then.

**Comment by ashWhiteHat** [comment]
> I had some problems with the fund command.

I fixed this error.
I would appreciate it if you could check.
Thank you!

**Comment by dsm-w3f** [comment]
@ashWhiteHat thank you for the improvements and fixes. I tried again and I was able to run the tutorial. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_1_dsm-w3f.md). I asked a cryptography specialist from our research team to check the cryptography part. He should give us a feedback in some days.

**Comment by ashWhiteHat** [comment]
Hi @dsm-w3f 
Thank you for the review.
> Could you specify what machine configuration was used for running the benchmark?

We do benchmark on Github Actions.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Spec**
2 core
7GB RAM
14GB SSD
> I asked a cryptography specialist from our research team to check the cryptography part

Thank you!

**Comment by dsm-w3f** [comment]
@ashWhiteHat just to let you know that the research team will need more time to complete this review. Probably they will two weeks to review. I'll keep you posted about the progress.

**Comment by ashWhiteHat** [comment]
Hi @dsm-w3f 
Copy that.
Please take your time 👍

**Comment by ashWhiteHat** [comment]
Hi @dsm-w3f 
Is everything okay?

**Comment by dsm-w3f** [comment]
@ashWhiteHat my apologies for the long time waiting for a review of this milestone. Our research team is in high demand. I'll wait for them to take a look until the end of this week, otherwise, I'll approve this milestone and the zk part will be checked later.

**Comment by dsm-w3f** [comment]
@ashWhiteHat my apologies again for making you wait so long to finish this evaluation. We will evaluate the zk part in the next milestone. This milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by ashWhiteHat** [comment]
@dsm-w3f 
Thank you for the review!

**Comment by dsm-w3f** [comment]
@ashWhiteHat did you provide an invoice for this milestone? I was not able to find it. Could you please resend it using [our invoice form](https://forms.gle/LSRr7PCjBpEbKGh89)?

**Comment by ashWhiteHat** [comment]
@dsm-w3f 
I sent you the invoice.
I would appreciate it if you could confirm.
Thank you!

**Comment by semuelle** [comment]
@ashWhiteHat confirmed

**Comment by ashWhiteHat** [comment]
Hello there
Did you transfer the fee?
I seems we still haven't received it.

I would appreciate it if you could confirm.
Thank you.

**Comment by fededubbi** [comment]
Hi @ashWhiteHat,

We noticed that you sent in the past an invoice with the same number.
Could you please update and resend?

Many thanks,
Federica

**Comment by ashWhiteHat** [comment]
Hi @fededubbi 
Thank you for letting me know.
I submitted the invoice.

I would appreciate it if you could confirm.
Thank you.

**Comment by fededubbi** [comment]
Hi @ashWhiteHat,

That's correct.

Many thanks,
Federica

**Comment by ashWhiteHat** [comment]
@fededubbi 
Thank you for the confirmation.
When can we receive it?

**Comment by fededubbi** [comment]
Hi @ashWhiteHat,

The invoice will be paid on Friday this week.

Many thanks,
Federica

**Pull request merged**
