### PR TITLE
Create ParaSpell-milestone_1.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
~~-   Invoice will be uploaded within a week/a week and a half from this pull request submit. I will update this comment then.~~
- EDIT: Invoice uploaded.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the ETH payment address (USDC) provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request:  [w3f/Grants-Program#1175](https://github.com/w3f/Grants-Program/pull/1175)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @dudo50 I have started the process of evaluating your milestone. I am running into a few initial issues.

1. I'm running into this error when running `make dockerLaunch`. It's having trouble installing Python:

```js
keeganquigley@Keegans-MacBook-Pro ui % make dockerLaunch
docker build -t paraspell . && docker run -it -p 8080:8080 --rm --name paraspell1 paraspell
[+] Building 33.1s (9/11)                                                                                                                                   
 => [internal] load build definition from Dockerfile                                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                      0.0s
 => => transferring context: 2B                                                                                                                        0.0s
 => [internal] load metadata for docker.io/library/node:lts-alpine                                                                                     0.8s
 => [1/7] FROM docker.io/library/node:lts-alpine@sha256:4d68856f48be7c73cd83ba8af3b6bae98f4679e14d1ff49e164625ae8831533a                               0.0s
 => [internal] load build context                                                                                                                      9.9s
 => => transferring context: 367.32MB                                                                                                                  9.8s
 => CACHED [2/7] RUN npm install -g http-server                                                                                                        0.0s
 => CACHED [3/7] WORKDIR /app                                                                                                                          0.0s
 => CACHED [4/7] COPY package*.json ./                                                                                                                 0.0s
 => ERROR [5/7] RUN npm install                                                                                                                       22.3s
------                                                                                                                                                      
 > [5/7] RUN npm install:
#9 22.10 npm ERR! code 1
#9 22.10 npm ERR! path /app/node_modules/bufferutil
#9 22.10 npm ERR! command failed
#9 22.10 npm ERR! command sh /tmp/install-bba325fc.sh
#9 22.10 npm ERR! gyp info it worked if it ends with ok
#9 22.10 npm ERR! gyp info using node-gyp@9.0.0
#9 22.10 npm ERR! gyp info using node@16.17.1 | linux | arm64
#9 22.10 npm ERR! gyp ERR! find Python 
#9 22.10 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#9 22.10 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#9 22.10 npm ERR! gyp ERR! find Python checking if "python3" can be used
#9 22.10 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#9 22.10 npm ERR! gyp ERR! find Python checking if "python" can be used
#9 22.10 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#9 22.10 npm ERR! gyp ERR! find Python 
#9 22.10 npm ERR! gyp ERR! find Python **********************************************************
#9 22.10 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#9 22.10 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#9 22.10 npm ERR! gyp ERR! find Python you can try one of the following options:
#9 22.10 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#9 22.10 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#9 22.10 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#9 22.10 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#9 22.10 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#9 22.10 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#9 22.10 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#9 22.10 npm ERR! gyp ERR! find Python **********************************************************
#9 22.10 npm ERR! gyp ERR! find Python 
#9 22.10 npm ERR! gyp ERR! configure error 
#9 22.10 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#9 22.10 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#9 22.10 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#9 22.10 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#9 22.10 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#9 22.10 npm ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
#9 22.10 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
#9 22.10 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
#9 22.10 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#9 22.10 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#9 22.10 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#9 22.10 npm ERR! gyp ERR! System Linux 5.10.124-linuxkit
#9 22.10 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#9 22.10 npm ERR! gyp ERR! cwd /app/node_modules/bufferutil
#9 22.10 npm ERR! gyp ERR! node -v v16.17.1
#9 22.10 npm ERR! gyp ERR! node-gyp -v v9.0.0
#9 22.10 npm ERR! gyp ERR! not ok
#9 22.10 
#9 22.10 npm ERR! A complete log of this run can be found in:
#9 22.10 npm ERR!     /root/.npm/_logs/2022-10-10T20_30_00_184Z-debug-0.log
------
executor failed running [/bin/sh -c npm install]: exit code: 1
make: *** [dockerLaunch] Error 1
```
2. When running `make install` I get this error:

```
parachain-launch generate paraspell-network-config.yml
make: parachain-launch: No such file or directory
make: *** [install] Error 1
```
I tried locally installing [parachain-launch](https://github.com/open-web3-stack/parachain-launch) in the directory, but no luck.

3. I am able to locally run the `dev` and `prod` versions successfully, and I can successfully connect to my wallet as well as the test accounts. However no options appear in the drop down menus:

paraspell

Are Karura, Pichui, and Bifrost networks supposed to be working out of the box? Could this be due to the network config not working? Can you help me out with what I am missing here? Thanks!

**Comment by dudo50** [comment]
Hey @keeganquigley, thanks for getting back with update. 
- Most likely with parachain launch it is either an issue with PATH not being exported by npm or that you have not run command `make initialize` or `make initializemac` firstly before the others. 
- Please let me know if you run initialize and if yes, then I will look into it. It is probably some simple issue with PATH or something not being installed properly.. 
- The nodes should appear in dropdowns automatically once make install command will run successfully as it would also launch entire local network in docker. It will then query these nodes for you from relay chain via API 
- As for docker, the issue with python is weird as it does not appear on my machine. Can you please let me know what operating system are you trying to launch docker on? I will look into it. Thanks in advance!

**Comment by dudo50** [comment]
Hey @keeganquigley , so I ran tests on both fresh install of MacOS and Ubuntu 22.
I found & fixed following issue:
- Command `make initialize `& `make initializemac` had wrong link to folder which has changed once project was moved into organization and repo renamed. This caused command to fail on start and not install dependencies. Here I think was your problem also. I have issue update that should fix this for you. Please clone latest version of ParaSpell thank you.
Screenshots from MacOS testing, it runs fine:

Screenshot 2022-10-12 at 17 11 15 (2)
Screenshot 2022-10-12 at 17 09 08 (1)
Screenshot 2022-10-12 at 16 59 11 (1)


Screenshots from Ubuntu 22 testing, it runs fine:
Screenshot from 2022-10-12 16-02-22 (1)
Screenshot from 2022-10-12 15-58-41 (1)

**Comment by keeganquigley** [comment]
@dudo50 Thanks for the changes! I'm on MacOS M1 chip. Yep that was the issue, as I can now successfully run `make initializemac` and `make install`. The docker containers run successfully. So that solves that issue, however when running `make dockerLaunch` I'm still running into the same error. 
```
#8 32.92 npm ERR! gyp info using node@16.17.1 | linux | arm64
#8 32.92 npm ERR! gyp ERR! find Python
#8 32.92 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#8 32.92 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#8 32.92 npm ERR! gyp ERR! find Python checking if "python3" can be used
#8 32.92 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#8 32.92 npm ERR! gyp ERR! find Python checking if "python" can be used
#8 32.92 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#8 32.92 npm ERR! gyp ERR! find Python
#8 32.92 npm ERR! gyp ERR! find Python **********************************************************
#8 32.92 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#8 32.92 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#8 32.92 npm ERR! gyp ERR! find Python you can try one of the following options:
#8 32.92 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#8 32.92 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#8 32.92 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#8 32.92 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#8 32.92 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#8 32.92 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#8 32.92 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#8 32.92 npm ERR! gyp ERR! find Python **********************************************************
#8 32.92 npm ERR! gyp ERR! find Python
#8 32.93 npm ERR! gyp ERR! configure error
#8 32.93 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
```

I'm still not sure what is causing this error. I'm wondering if it is a weird macOS thing.

**Comment by dudo50** [comment]
@keeganquigley that is truly weird issue. I am not experiencing same one on mine (Intel version however but that should not cause issue). Command `make initializemac` should install python3.9 . 
- Have you tried to export it into PATH variable? Perhaps that might be the thing here. 
- If not please try downloading python manually. https://www.python.org/downloads/release/python-3108/

However nothing from this is necessary on my MacOS machine.
If none from above work, please ping me I will try to investigate this further.

**Comment by keeganquigley** [comment]
Thanks for the suggestions @dudo50 I already have Python installed so I first tried `export PATH=$PATH: /usr/local/bin/python3` to no avail. I also tried installing it manually using the link above. I tried all the suggestions in the error but no luck. Also tried these suggestions: https://stackoverflow.com/questions/73306832/npm-error-find-python-python-is-not-set-from-command-line-or-npm-configurati but no luck. I'm wondering if it has something to do with conflicting node versions.

I can get it to run fine on Ubuntu though, so I think it's safe to say this is an issue on my end. Let me know if you can find anything else out.

Moving on, the docker containers all start successfully:
```
 ⠿ Container output-parachain-2102-0-1    Started                                                                   0.7s
 ⠿ Container output-parachain-2001-0-1    Started                                                                   1.2s
 ⠿ Container output-parachain-2000-1-1    Started                                                                   1.0s
 ⠿ Container output-relaychain-alice-1    Started                                                                   1.4s
 ⠿ Container output-relaychain-bob-1      Started                                                                   0.9s
 ⠿ Container output-parachain-2102-1-1    Started                                                                   1.2s
 ⠿ Container output-relaychain-charlie-1  Started                                                                   1.3s
 ⠿ Container output-parachain-2001-1-1    Started                                                                   1.5s
 ⠿ Container output-parachain-2000-0-1    Started                                                                   1.3s
 ⠿ Container output-parachain-2102-2-1    Started
```
However they start to shut down after they initialize, are all 10 nodes supposed to stay running?

docker nodes

I still can't connect to them in the front-end drop down menus. Let me know if it would be easier to schedule a call in order for you to show me how its supposed to work. Thanks!

**Comment by dudo50** [comment]
Hey, @keeganquigley thanks for reaching out. I haven't found anything that could cause that for you. I have tried to update my mac to newer software and try that again but I was not able to reproduce it anyway as everything worked fine for me.

As for docker
- Parachains do take some time to start producing blocks. It is around a few minutes. You can observe if they communicate with the Relay chain here https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/parachains

You can also check each node once it starts via:
- Acala https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9999#/explorer
- Pichiu https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9991#/explorer
- Bifrost https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9995#/explorer

It may happen, that some nodes will stop, but the network should still run and communicate. For me, it is around 2-3 minutes until I can see the first nodes communicating with the Relay chain
Screenshot from 2022-10-13 23-35-24

After they start communicating with the Relay chain they should be able to be seen in the application dropdown after the page refresh.

I think it would be best if we have a call, it would save time for you and I can demonstrate functionality so you can then adapt to testing faster. You can contact me via dudo.morhac@gmail.com or xmorhac@stuba.sk I check both regularly.

**Comment by dudo50** [comment]
Hey @keeganquigley, I had this app tested on friend's M1 Mac. He also reported issue with docker containers for network startup. I think this might be related to ARM architecture and either Docker, Parachain-launch lib or their dependencies might not yet be fully compatible with this relatively new tech. As for ParaSpell, it runs for him just fine even in Docker. Since we did not specify in our application, that this project will be compatible with M1/M2 Macs we kindly ask you to consider this and test it with compatible system. Application is fully compatible with Linux (Mainly Ubuntu) and Intel Macs for now. I am going to investigate M processor MacBooks once I get my hands on one because this will be needed in future. We now need to focus mainly on continuing development of ParaSpell SDK for which we have followup grant in plan and we need to proceed with this Grant first. SDK one will help developers on every system. ParaSpell UI will continue to evolve with support to new systems as Parachain-launch and Docker will increase their support. Thanks in advance.

Regards
Dudo

**Comment by keeganquigley** [comment]
Thanks for investigating this @dudo50! I don't think that should be an issue. I was able to successfully run it on Ubuntu 18.04 on a Google Cloud VM. I will reach out to you via email to schedule a call!

**Comment by dudo50** [comment]
Hey, @keeganquigley  requested UNIT tests for core functionality have just been uploaded and I have edited deliverables in the following commit https://github.com/w3f/Grant-Milestone-Delivery/pull/584/commits/453e5837215e2e058989beaf4a87416830a0a255. Hope this covers everything for this delivery. If you have any questions feel free to contact me.
With regards
Dudo

**Comment by keeganquigley** [comment]
@dudo50 Thanks for making the changes! I am happy to go ahead and approve this milestone. You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/609). Just waiting for a final check before merge. Good luck on the next one!

**Review by Noc2 — APPROVED** [review]

**Comment by keeganquigley** [comment]
Thanks again @dudo50 for your patience during this process. I have forwarded your invoice for payment.

**Comment by dudo50** [comment]
Thank you for being kind and patient to me during this process @keeganquigley . It motivated me in future process with the project. Looking forward to future cooperation.

With kind regards,
Dudo

**Comment by dudo50** [comment]
> hi @dudo50 we transferred the payment today.

Yes I can see. Thanks for cooperation guys. See you soon!

With kind regards,
Dudo

**Pull request merged**
