### PR TITLE
Added ink-boxes M1

### PR DESCRIPTION
**Pull request by nerdsince98**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1243

### CODE REVIEW

**Comment by nerdsince98** [comment]
@alxs When could we expect response for this?

**Comment by alxs** [comment]
Thanks for the delivery @nerdsince98. The length of the review process depends on how quickly an evaluator has the capacity to pick up your delivery, and the amount of changes required to it. Someone will most certainly get back to you in the next two weeks. Once the delivery has been accepted, payment happens within 14 days.

**Comment by 0xCaso** [comment]
Hi @nerdsince98, thanks for the delivery. I'm starting the evaluation, and I'll ping you if I have any questions.

**Comment by avirajkhare00** [comment]
Hey Aviraj here and I am also working on it.

Here is the output of `rustup show`:
```
➜  flipper git:(main) rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/avirajkhare/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-2022-06-30-aarch64-apple-darwin
nightly-aarch64-apple-darwin

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.65.0 (897e37553 2022-11-02)
```

Also running `cargo-contract contract build` is running fine on my machine.

**Comment by avirajkhare00** [comment]
@0xCaso 
This should do the trick for you: `cargo install cargo-contract --version 2.0.0-alpha.5`

**Comment by 0xCaso** [comment]
Yea I've seen the issue you opened, that fixed the problem, thanks 👍🏼

**Comment by avirajkhare00** [comment]
@0xCaso let me know if you need help anywhere else.

**Review by Micassa93 — APPROVED** [review]

**Comment by avirajkhare00** [comment]
Hey @0xCaso. I can see that it is approved. What are the next steps?

**Comment by 0xCaso** [comment]
Hey @avirajkhare00, I'm writing the evaluation right now. Unfortunately, @Micassa93 is not part of the team, so his review is meaningless, especially without any feedback/evaluation. I'll reach out again very soon!

**Comment by avirajkhare00** [comment]
@0xCaso thanks for this info

**Comment by 0xCaso** [comment]
Hi @avirajkhare00 and @nerdsince98, I've just pushed the evaluation. You can find it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/9e95bdee0368381b1d6245acf06337a6dbbca7a9/evaluations/ink-boxes_1_0xCaso.md). Let me know if you have any questions!

**Comment by avirajkhare00** [comment]
Thanks for the evaluation. I will work on it and get back soon.

**Comment by avirajkhare00** [comment]
Hey @0xCaso. Since @nerdsince98 got locked out of GitHub account due to the fact that she is unable to login inside her email, I have cloned the repo and continued the development: https://github.com/avirajkhare00/ink-boxes

I hope that is fine since we don't want to change our payment address.

Also, for NFT marketplace, Decentralized Ecommerce platform, we will create a follow-up grant since these are the heavy tasks in itself.

Please take a look again. I have reflected on all the changes you requested in the evaluation.

The article is on the way as I am writing this. I will post the link here.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Hi @avirajkhare00, I updated the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_1_0xCaso.md). Let me know if you have any question!

**Comment by avirajkhare00** [comment]
Testing internal variables go against the guiding principles of `react-testing-library.`
You can read more about it here: https://testing-library.com/docs/guiding-principles/
And here: https://stackoverflow.com/questions/60100133/how-can-i-test-if-usestate-hook-has-been-called-with-jest-and-react-testing-libr

I have never tested the internal variables. We should only test what users can interact with. The user can't interact directly with react hook called useState variables. 

Also, I have updated the UI where the user can see what smart contract address the user has submitted.

**Comment by 0xCaso** [comment]
Thanks @avirajkhare00 for the changes.

For the testing, in the evaluation I was mentioning "more feedbacks" in the UI also for this reason, so you can easily check if everything goes well or not. You can always check if an error message appears during tests. Also, if a state variable changes the UI in some way, you can verify that the specific change happens.

**Comment by avirajkhare00** [comment]
Hey @0xCaso. I have updated the tests. Kindly check.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Thanks again for the changes @avirajkhare00.

By the way, I'd like to ask you to test all the functionalities in the way you've done with the last unit test you wrote [here](https://github.com/avirajkhare00/ink-boxes/blob/main/erc20/ui/tests/index.test.tsx#L80).

Also, you could do it without rendering the exact component, but by rendering the whole page in a `beforeEach` cycle (see [jest docs](https://jestjs.io/docs/setup-teardown)). In this way you don't need anymore to render things on your specific tests, and then you can directly test the functionalities in a faster way.

If you would do these tests, you could notice there are some errors in the UI, which I have already mentioned in the first version of the evaluation, [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_1_0xCaso.md#0-creation-of-boxes). I'm referring to ERC20 and ERC721 `transfer` and `approve` mentioned errors.

Hope this clarifies everything, and thanks a lot for your efforts.

**Comment by avirajkhare00** [comment]
@0xCaso, Thanks for clarifying. I will get back with the tests.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Hi @avirajkhare00. Thanks a lot for the new additions and the youtube video. I've updated the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_1_0xCaso.md). I've also suggested some minor changes (mentioned in the evaluation) in a pull request (https://github.com/avirajkhare00/ink-boxes/pull/1) I've made.

**Comment by avirajkhare00** [comment]
@0xCaso   I do need to add the assertions right?

**Comment by avirajkhare00** [comment]
Hey @0xCaso, I have added assertions to the tests. Please check them.
Interestingly, three of them will fail when you run the tests for the first time. When you try to run them a second time, all will pass.

**Comment by 0xCaso** [comment]
Thanks again. Yea, it's the thing i was pointing out till the beginning of the evaluation. Have you tried to understand why it happens? And to fix it? And also, you should improve the ERC721 tests, not only the ERC20 ones.

**Comment by avirajkhare00** [comment]
I was busy in the hackathon. Won ETHIndia 2022. Will start to work on this tomorrow onwards.

**Comment by 0xCaso** [comment]
> I was busy in the hackathon. Won ETHIndia 2022. Will start to work on this tomorrow onwards.

Congrats! And perfect, thanks

**Comment by avirajkhare00** [comment]
Hey @0xCaso. I have fixed all the tests. Now they are passing in the first time itself.

**Comment by avirajkhare00** [comment]
Hey @0xCaso. Any update on this 🙏

**Comment by avirajkhare00** [comment]
If possible, can you please accelerate it?
I am in very bad financial condition right now. I don’t have a job either.

**Comment by 0xCaso** [comment]
Hi @avirajkhare00

**ERC20 tests**:
- the first time I run them, I get 2 failed (`transfer` and `transferFrom`);
- after that, on every execution I get just 1 failed (`transferFrom`);

**ERC721 tests**:
- they're fine, but I see [here](https://github.com/0xCaso/ink-boxes/blob/a648dca726e728fb40f79b2fb158442f043dbc69/erc721/ui/cypress/e2e/spec.cy.ts#L38), for the `transfer`  you're clicking 2 times, in order to get the expected result;
- the same happens for the `approve` function [here](https://github.com/0xCaso/ink-boxes/blob/a648dca726e728fb40f79b2fb158442f043dbc69/erc721/ui/cypress/e2e/spec.cy.ts#L45).

I would point out that tests are useful if you make them success for real, not "hacking" them, otherwise they have no sense to exist. If you notice that there is something wrong with the tests, you should try to fix the application, not to make them pass in some way.

That said, I'll let you decide what to do with this, so decide if you want to understand why you need to press two times, or if you want to keep these tests "hacked". I'd be happy if you (at least) could fix the ERC20 tests (making them not fail the first time they get executed). Also, I never managed to call the `transferFrom` function from the UI, always for the ERC20 contract. If you did, how did you do?

**Comment by avirajkhare00** [comment]
I will try my best and will investigate it, and won’t hack them.

**Comment by avirajkhare00** [comment]
Hi. Here is what I found out:

1. ERC721 contract:

When calling `mint` with `tokenId` from the UI, the token gets minted, but an error is received in the UI. Since the error is not meaningful, I cannot decode what the error means, although the token gets minted.

A user would click button again and again if result is not successful, I am doing the same using tests. I checked the frontend code, nothing is wrong in it.

2. ERC20 contract:

I ran tests for 10 times, It passed all the times.

**Comment by avirajkhare00** [comment]
There was a issue with a test in erc20, I have fixed it. It is working now in first try. Please check.
Thanks

**Comment by avirajkhare00** [comment]
@0xCaso. Let me know if everything is perfect this time.

**Comment by 0xCaso** [comment]
Hi @avirajkhare00. Thanks, now the tests run correctly (also if there are still the "double click" things). By the way, I'm finishing the evaluation and can accept the milestone, but I warmly suggest to try to fix the UI bugs (UI for this project is really important; user must know if an operation goes well or not).

**Review by 0xCaso — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
Great @avirajkhare00, the milestone 1 has been accepted, thanks a lot for the collaboration. However, I'd ask you to send another invoice through [this](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform) form, making sure it has every information needed. The one you've already submitted lacks of a lot of things. Thanks again.

**Comment by avirajkhare00** [comment]
Hey @0xCaso @Noc2. Thanks a lot for approving this delivery milestone. I have submitted another invoice.

**Comment by 0xCaso** [comment]
Have you followed the form of the previous comment? In the new invoice, please put the amount in USD and the same (Bitcoin) address you've put in the grant application document

**Comment by avirajkhare00** [comment]
@0xCaso, sure. Got it

**Comment by avirajkhare00** [comment]
@0xCaso, I have submitted the invoice again. Please do check 🙏

**Comment by 0xCaso** [comment]
Again, there is something missing.
Screenshot 2022-12-12 at 13 34 06
There isn't our company info in the invoice.

**Comment by avirajkhare00** [comment]
Hey @0xCaso, I have raised invoice again. It's correct this time.

**Comment by 0xCaso** [comment]
Thanks again for the update. I've just noticed the BTC address you put in the invoice is different from the one you've put in the application. If you want to change the address, you must amend the [grant application](https://github.com/w3f/Grants-Program/blob/master/applications/ink-boxes.md) with a pull request.

**Comment by avirajkhare00** [comment]
Hey @0xCaso, thanks for pointing out. We don't want to update the wallet address. I have updated the wallet address in the invoice and raised it. Thanks.

**Comment by 0xCaso** [comment]
Hi @avirajkhare00, thanks again. This time should be all good, so I've notified the finance team. Please allow up to 14 days for the payment.

**Comment by avirajkhare00** [comment]
Hey @0xCaso, thanks a lot for your support.

**Comment by fededubbi** [comment]
Hi @avirajkhare00,

I noticed on your invoice is missing VAT amount.
Could you please added and resend?
Note that VAT amount should be 0.

Many thanks,
Federica

**Comment by avirajkhare00** [comment]
Hey @fededubbi, thanks for letting me know. I have submitted the invoice again.

**Comment by RouvenP** [comment]
hi @avirajkhare00 we transferred the payment yesterday.

**Comment by avirajkhare00** [comment]
@RouvenP i received the payment. Thanks a lot 🙏

**Pull request merged**
