### PR TITLE
Genesis DAO Milestone Delivery Part 3

### PR DESCRIPTION
**Pull request by deep-ink-ventures**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

https://github.com/w3f/Grants-Program/blob/master/applications/GenesisDAO.md

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the milestone delivery. Please see the [evaluation document ](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_3_dsm-w3f.md)and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by deep-ink-ventures** [comment]
Thanks @dsm-w3f. We had a very short work week due to some holidays in germany. We are close to provide the changes / updates. Expect them early next week! 

Have a great weekend.

**Comment by deep-ink-ventures** [comment]
@dsm-w3f

Here are our answers to the evaluation doc. Have a great start to the week.

> Could you provide a manual testing guide that shows the usage of the new features?

We've created a walkthrough [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/walktrough.md).

> The integration test failed.

Fixed within [this PR](https://github.com/deep-ink-ventures/genesis-dao-node/pull/105).

> Do I need to wait until the end of the timer to close the proposal?

Yes. 

Unless you mark it as faulty. Everyone can *report* it as faulty (this is an offchain operation [implemented](https://github.com/deep-ink-ventures/genesis-dao-service/blob/main/core/models.py#L96-L98) by our backend service) and then the DAO council can mark it as faulty [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/pallets/dao-votes/src/lib.rs#L240). 

We have added documentation on how to do this in the walkthorugh!

> How do I report the proposal using the frontend?

We've added a `Report this Proposal as Faulty` button to proposals. See [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/walktrough.md#marking-a-proposal-as-faulty) for details.

> Can I change the proposal duration and cust using the frontend? 

Currently the frontend supports in only via dao creation. But is useful and I add it to the list of features we add when revise the [Dashboard](https://github.com/w3f/Grants-Program/blob/master/applications/Stylograph.md#dao-dashboard-add-on).

> When I tried to use some commands, for example, faultProposal from votes in substrate using the account that created the DAO, I received the "vote.SenderIsNotDaoOwner" error.

The account that created the DAO releases it to a council during the setup - that is a multisig account utilizing `pallet_multisig`. You need to fault a proposal using that multisig account. 

We'll add frontend support for multisig [here](https://github.com/w3f/Grants-Program/blob/master/applications/Stylograph.md#council-management) to have it as an experience for people who do not have any experience with the polkadot ecosystem.

You can do this using the multisig account in polkadot.js.org. We have created a video on how to do this [here](https://drive.google.com/file/d/1nD1wxHhs0jP_zL49tCeidj46ZLFTgm4X/view). 

The twist here is that the address of the multisig is [deterministic](https://github.com/paritytech/substrate/blob/master/frame/multisig/src/lib.rs#L504-L508) - as long as you use the same accounts (in the same order) and threshold as during setup. (As a side note: It would make a lot of sense to have a open source tool for this that can connect to arbitraty parachains.)

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the answers and fixes. I was able to advance in the evaluation but I didn't finish yet since I'll need to wait 24 hours to finalize the proposal. I'll continue tomorrow and hope to be finished soon. The [evaluation document was updated](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_3_dsm-w3f.md) with the current progress.

**Comment by deep-ink-ventures** [comment]
Thanks for the update, enjoy your time out of office!

**Comment by deep-ink-ventures** [comment]
Unfortunately our backend service runs into this error: https://github.com/paritytech/polkadot/issues/7021, which in turn requires us to upgrade to `0.9.43` to fix it which in turn requires us to reset our testnet :-(

We will do so tomorrow but we will change the minimum proposal duration to minutes instead of days, so you have an easier time testing (will revert back after testing).

Sorry for that.

**Comment by deep-ink-ventures** [comment]
Thank @dsm-w3f.

We have changed the underlying AWS setup and that has unfortunately caused a few errors. We have now run a full QA round on this, can you give it another go?

**Comment by dsm-w3f** [comment]
@deep-ink-ventures I tried again but I got another error. It seems related to some package or something missing in the frontend part of the application. Please see the details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_3_dsm-w3f.md).

**Comment by deep-ink-ventures** [comment]
We fixed this, @dsm-w3f !

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the fixes. I still have a small problem but this don't prevent the acceptance of the milestone. See the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_3_dsm-w3f.md) for details. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by deep-ink-ventures** [comment]
@dsm-w3f thanks so much! Already on stylograph!

@x-xo can you please ticketize the remainder from the evaluation project for either Eric or Jowelyn to priotize it?

**Pull request merged**
