### PR TITLE
TuxedoDapp milestone 2

### PR DESCRIPTION
**Pull request by AltiMario**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2112

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @AltiMario ,
I'm looking forward to finally review this delivery. Is there anything you would like to change or fix beforehand? Just checking in as there were quite some changes to the first delivery after this one was put up. Let me know if the testing guide is complete and working.

**Comment by AltiMario** [comment]
hi @PieWol thanks for your support. We managed to fix the frontend, however, a little tuning has to be done in the backend as well because the flag "not for selling" after a purchase doesn't reset. I believe it can be fixed this week and I will invite you for the (hopefully) final review asap.

**Comment by PieWol** [comment]
Perfect, thank you!

**Comment by PieWol** [comment]
Hey @AltiMario ,
any updates? :)

**Comment by AltiMario** [comment]
hi, @PieWol, I think @NadigerAmit is going to share some information about it

**Comment by NadigerAmit** [comment]
Hi @PieWol 
cc: @AltiMario 

I am sorry for the late reply.

The status of a kitty being **"for sale"** or **not** is determined by the blockchain logic. This information is stored as part of the transaction in the block, so the frontend does not control whether a kitty is for sale. The decision is based on whether the output kitty instance in the transaction is of type "Kitty piece" or "Tradable kitty piece."

Our original game design is as follows:

We categorized kitties into two types: 
a. Kitty - These kitties are not for sale. 
b. TradableKitty - These kitties are available for sale which as extra feild price.

When we want to sell a kitty, a "Kitty" is converted to a "TradableKitty" via the "List kitty for sale" process. Once a sale is completed, only the ownership of the kitty changes from the seller to the buyer, along with the transfer of funds. The type of the kitty remains "TradableKitty" even after the transaction.

If the new owner does not wish to sell the purchased kitty, they need to submit a separate transaction to convert the "TradableKitty piece" back to a regular "Kitty piece" using the **delist_kitty_from_sale** API.

Implementing a feature that automatically makes the purchased kitty "not for sale" would require changes to both the blockchain logic and the web service code. This would not be a straightforward modification and needs a significant effort. 

Therefore, I recommend maintaining the current design and implementation at this point in time.

**Comment by PieWol** [comment]
Thank you @AltiMario  and @NadigerAmit ,
I'll start my review tomorrow.

**Comment by PieWol** [comment]
Hey @AltiMario ,
where exactly is the testing guide for this milestone located?

**Comment by PieWol** [comment]
Hey @AltiMario and @NadigerAmit ,
I'm sad to hear that this change from a ``tradableKitty`` back to a ``kitty`` upon a sale isn't within the scope of your options for this grant. This issue will not hinder this milestone from acceptance though. Thanks for all of your time and efforts you put into this.

**Pull request merged**
