### PR TITLE
gluon - mileston 1 - External Evaluation - felixniemeyer

### PR DESCRIPTION
**Pull request by felixniemeyer**
#125

The evaluation template has been copied and filled out.

### CODE REVIEW

**Comment by felixniemeyer** [comment]
Hey @Noc2 @alxs, 
please have a look and review the review :)

**Comment by alxs** [comment]
Hey @felixniemeyer, thanks for the evaluation. Just a quick note: the LICENSE files are fine as they are, the bottom text is only a template for the boilerplate notice that can be added to individual files. It would be more important to check that the code doesn't infringe the copyright of other projects, i.e. that no code has been copied from other repos while removing the license etc. You can do so through GitHub global search with a few sample lines of any relevant/suspect files.

**Review by kevingzhang — APPROVED** [review]

**Review by kevingzhang — APPROVED** [review]

**Comment by Noc2** [comment]
@felixniemeyer could you provide a kusama address and maybe integrate it into the readme (via another PR)? Even if you don't have set up an on-chain identity. We definitely want to pay you for the evaluation ;-)

**Comment by felixniemeyer** [comment]
@Noc2 
I have created a pull request in order to add a Kusama address in the evaluation header: https://github.com/w3f/Grant-Milestone-Delivery/pull/134
This is the address: FobBHc2eLy4HbfdRnKBCaQMvZkmLwqKG8LdTBHTBMewkczv

Is it fine like this? You said "integrate it into the readme" but I suspect you meant the the evaluation markdown file.
Kind regards :-)

**Comment by Noc2** [comment]
Yes sorry I meant the md file. Thanks

**Comment by semuelle** [comment]
Hi Felix, you should have received 1 KSM: https://kusama.subscan.io/extrinsic/0xedbfa355797aed643f89c1204cdada18dea8ee52f008f604d42d3e72da3d3d10

**Comment by felixniemeyer** [comment]
@semuelle Hi Sebastian, 
I just checked, it's there, thanks! :-)

**Pull request merged**
