### PR TITLE
Сrossbow Milestone 1

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/668.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by JosephKnecht-lab** [comment]
Hi guys,

I have provided an external evaluation of this project here: https://github.com/w3f/Grant-Milestone-Delivery/pull/337

**Comment by alxs** [comment]
Thanks for submitting an evaluation @JosephKnecht-lab! As soon as you think the delivery fulfils the requirements, please let us know and change the status of the evaluation to `Approved`. @enfipy I'll let you address Joseph's comments directly. If any of you has any question, feel free to reach out here or on Element.

**Comment by enfipy** [comment]
Hey @JosephKnecht-lab! Thank you a lot for checking out our delivery. I've updated everything you specified and hope you will like it.

One little remark is that currently, M1 processors can't handle docker building with `linux-x86` architecture and `rust-bindgen`. I've created a tracking issue for this here: https://github.com/dodorare/crossbow/issues/58. On other platforms, the docker image should work like a charm.

**Comment by JosephKnecht-lab** [comment]
Thanks @enfipy for the fast reply. 

I have changed the status of my external evaluation for **milestone 1** to _Approved_.

As described in the process documentation, the internal evaluators will have to give their own evaluation. Their evaluation will finalize the deliverable.

**Comment by alxs** [comment]
@enfipy looks good from my side! Thank you for your hard work.

I don't think there's a need for an additional evaluation from my side here - we just need to double-check external evaluations and I'm happy to accept @JosephKnecht-lab's.

@enfipy apologies as it seems there was an oversight during your application regarding the payment information. We currently need to sign a contract for all grants if payment in fiat is requested. Since we didn't do it when you applied, I suppose we would need to sign one now or if you can accept payment in any of the [supported cryptocurrencies](https://github.com/w3f/Grants-Program/blob/master/applications/application-template.md#w3f-grant-proposal), you can just create a PR to add an address to your application and submit a new invoice. Again, sorry we missed this.

**Comment by alxs** [comment]
A contract was signed by both parties and payment will be made in fiat. @enfipy I'll notify the operations team to process your invoice - please allow up to 2 weeks until the payment is made.

**Pull request merged**
