### PR TITLE
Zondax - Ledger Asset apps (statemint/statemine)

### PR DESCRIPTION
**Pull request by jleni**

### CODE REVIEW

**Comment by ainhoa-a** [comment]
Hi @alxs do you have any update on this one?

**Comment by alxs** [comment]
Hey @ainhoa-a. Yes, I was just looking at this. First of all thanks for all the hard work!

The only thing I would point out is that it would be great to have some documentation for https://github.com/zondax/ledger-substrate-js, which it looks like you've been [planning](https://github.com/Zondax/ledger-substrate-js/issues/21) to work on for some time. Though I guess this isn't specific to this grant but goes for the library in general. I also think it would make sense to provide some actual usage examples as part of the documentation, instead of the test cases in the statemine/t apps which aren't easily accessible. I feel like that would make other teams' life easier when using the library, but let me know if you don't think this is needed or I'm missing anything.

And just out of curiosity, is there any reason you don't support XCM calls or is it simply still on your roadmap?

**Comment by ainhoa-a** [comment]
Hi @alxs we fully agree, we want to improve this documentation  https://github.com/zondax/ledger-substrate-js and have prioritized it to solve it in the following days. 
As per XCM calls this is in our roadmap and we plan to implement it during this quarter.

**Comment by alxs** [comment]
Sounds good, let me know when you're done and I'll take another look at it ASAP

**Comment by ainhoa-a** [comment]
Hi @alxs  we have updates the documentation of https://github.com/zondax/ledger-substrate-js  and published the npm package  https://www.npmjs.com/package/@zondax/ledger-substrate

**Comment by alxs** [comment]
Thanks guys, looks good! The milestones are accepted, you can find my evaluation notes here: [1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Zondax-LedgerAssetApp_1_alxs.md), [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Zondax-LedgerAssetApp_2_alxs.md), [3](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Zondax-LedgerAssetApp_3_alxs.md). I'll forward the invoice to the finance team. As usual, please allow for up to 2 weeks for processing.

**Pull request merged**
