### PR TITLE
Milestone Delivery: Dante Network Milestone 2

### PR DESCRIPTION
**Pull request by xiyu1984**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/895

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @xiyu1984. We'll look into it as soon as possible.

**Comment by xiyu1984** [comment]
> Hi again @xiyu1984 I'm starting your evaluation now, and I'm excited to dive in, as I enjoyed evaluating your last milestone and this is super cool tech! Just a heads up though that I probably won't get back to you until next week due to the US Thanksgiving holiday. Thanks!

Cool~ Feel free to check it, and we will be very appreciative of your suggestions. 
Take your time~ Have a nice Thanksgiving holiday : )

**Comment by keeganquigley** [comment]
Hi @xiyu1984 terribly sorry for the delay. Here are some initial notes for you to check over:

1. The deliverables in your [application](https://github.com/w3f/Grants-Program/blob/master/applications/Dante_Network.md#milestone-2--parallel-router-scheduling-algorithms-sqos-off-chain-routers-sdk-testnet) state that you will build a Dockerfile. This has been removed from the delivery. Are you planning to create one? If not we would need to amend the application contract to remove it.

2. "Source code" is added as deliverable 0e. but it is not in the original application. This isn't something I can evaluate anyway, so can you remove this from the deliverables?

3. I'm not able to compile some of the smart contracts due to errors:

When running `cargo test` for the `ink_sdk` contract:
```rust
Compiling ink_sdk v0.1.0 (/Users/keeganquigley/ink-sdk/contracts)
warning: unused import: `super::*`
  --> lib.rs:98:13
   |
98 |         use super::*;
   |             ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

error[E0061]: this function takes 2 arguments but 5 arguments were supplied
   --> cross_chain_helper.rs:87:19
    |
87  |     let session = ISession::new(0, 0, Vec::<u8>::new(), Vec::<u8>::new(), Vec::<u8>::new());
    |                   ^^^^^^^^^^^^^    -                    ----------------  ---------------- argument of type `Vec<u8>` unexpected
    |                                    |                    |
    |                                    |                    argument of type `Vec<u8>` unexpected
    |                                    argument of type `{integer}` unexpected
    |
note: associated function defined here
   --> /Users/keeganquigley/message-ink/payload/message_define.rs:177:12
    |
177 |     pub fn new(id: u128, callback: ink_prelude::vec::Vec<u8>) -> Self {
    |            ^^^
help: remove the extra arguments
    |
87  |     let session = ISession::new(0, Vec::<u8>::new());
    |                                ~~~~~~~~~~~~~~~~~~~~~

error[E0061]: this function takes 2 arguments but 5 arguments were supplied
   --> cross_chain_helper.rs:96:19
    |
96  |     let session = ISession::new(0, 0, Vec::from(callback), Vec::<u8>::new(), Vec::<u8>::new());
    |                   ^^^^^^^^^^^^^    -                       ----------------  ---------------- argument of type `Vec<u8>` unexpected
    |                                    |                       |
    |                                    |                       argument of type `Vec<u8>` unexpected
    |                                    argument of type `{integer}` unexpected
    |
note: associated function defined here
   --> /Users/keeganquigley/message-ink/payload/message_define.rs:177:12
    |
177 |     pub fn new(id: u128, callback: ink_prelude::vec::Vec<u8>) -> Self {
    |            ^^^
help: remove the extra arguments
    |
96  |     let session = ISession::new(0, Vec::from(callback));
    |                                ~~~~~~~~~~~~~~~~~~~~~~~~

error[E0061]: this function takes 2 arguments but 5 arguments were supplied
   --> cross_chain_helper.rs:105:19
    |
105 |     let session = ISession::new(context.id, 0, Vec::<u8>::new(), Vec::<u8>::new(), Vec::<u8>::new());
    |                   ^^^^^^^^^^^^^             -                    ----------------  ---------------- argument of type `Vec<u8>` unexpected
    |                                             |                    |
    |                                             |                    argument of type `Vec<u8>` unexpected
    |                                             argument of type `{integer}` unexpected
    |
note: associated function defined here
   --> /Users/keeganquigley/message-ink/payload/message_define.rs:177:12
    |
177 |     pub fn new(id: u128, callback: ink_prelude::vec::Vec<u8>) -> Self {
    |            ^^^
help: remove the extra arguments
    |
105 |     let session = ISession::new(context.id, Vec::<u8>::new());
    |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0061`.
warning: `ink_sdk` (lib test) generated 1 warning
error: could not compile `ink_sdk` due to 3 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: could not compile `ink_sdk` due to 3 previous errors
```

This happens when using both the `main` branch and the `develop` branch. Can you remind me which branches I should be using? This would ideally be in the testing guide as well.

When running `Callee`:

```rust
   Compiling ryu v1.0.11
error: ink! only supports compilation as `std` or `no_std` + `wasm32-unknown`
   --> /Users/keeganquigley/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_allocator-3.4.0/src/bump.rs:107:13
    |
107 | /             compile_error! {
108 | |                 "ink! only supports compilation as `std` or `no_std` + `wasm32-unknown`"
109 | |             }
    | |_____________^

error[E0599]: no method named `request_pages` found for mutable reference `&mut InnerAlloc` in the current scope
   --> /Users/keeganquigley/.cargo/registry/src/github.com-1ecc6299db9ec823/ink_allocator-3.4.0/src/bump.rs:125:35
    |
125 |             let page_start = self.request_pages(required_pages)?;
    |                                   ^^^^^^^^^^^^^ method not found in `&mut InnerAlloc`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `ink_allocator` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```
Also, should I be using the Rust 1.65 stable toolchain or Rust 1.67 nightly? While you check these out I will continue the eval to the best of my ability. Thanks!

**Comment by xiyu1984** [comment]
Hey @keeganquigley ,
The compile problem is influenced by the recent update of `ink!`, and we are solving the problem, it may need some time~

**Comment by xiyu1984** [comment]
Her @keeganquigley ,
Sorry for the late. We have solved the problems as [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/630#issuecomment-1341944260)~ Feel free to check it~

**Comment by keeganquigley** [comment]
Thanks for the reply @xiyu1984 the explanation is much appreciated! I was able to get the contracts to compile using the `feature-sqos` branch.

Can you explain what you mean by "the testnet is not fully open to the public"? I noticed your [note](https://github.com/dantenetwork/protocol-stack-for-ink#protocol-stack-for-ink) that mentions the development repo was temporarily made private. Is this still the case?

Regarding 0e. Article deliverable, do you have a general announcement blogpost you can link to? Rather than the notion page (especially since the notion page is already linked in deliverable 0b. Documentation). See our [Announcement Guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md) for more info on how the article should be formatted.

Thanks! While you work on this I will finish up my evaluation.

**Comment by xiyu1984** [comment]
Hi @keeganquigley,
 First about the [note](https://github.com/dantenetwork/protocol-stack-for-ink#protocol-stack-for-ink). Frankly speaking this was an oversight on our part. The state of the `note` was actually out of date and we have updated it. Everything is open source and the newest version is merged into the `feature-sqos` branch. 
The "the testnet is not fully open to the public" is only related to the test routers as I explained above.

Secondly, we updated the link of the article link in `0e.`. It is substituted by a direct article in Dante’s “Medium”. We have several articles in “Medium” and a typical one is provided.   

Thanks very much for your patience, and hope you have a nice weekend~  

Best~

**Comment by keeganquigley** [comment]
Thanks @xiyu1984 and I appreciate your patience. Your project has many repos and many branches, and it hasn't been super clear on exactly which ones need testing, which ones are not related, etc. Please see my comments below:

1. Your Milestone 1 [test guide](https://github.com/dantenetwork/cross-chain-demo) was awesome. Very clear instructions, including CLI commands. There was a clear separation of sections with titles and bullet points. This [second one](https://github.com/dantenetwork/protocol-stack-for-ink/tree/feature-sqos/test) is very muddy in my opinion (not clear). The screenshots are very helpful, but it has been hard for me to figure out exactly what I need to do to replicate the tests. 

1a. For example, here:
```
The initial credibility of all routers is 4000, as shown in Fig.1-1.
```
Where is that data coming from? I'm not sure which call is used. Also here:
```rust
export greeting=d8ae7a513eeaa36a4c6a42127587dbf0f2adbbda06523c0fba4a16bd275089f9
​​near call $greeting send_greeting "{\"to_chain\": \"POLKADOTTEST\", \"title\": \"Greeting\", \"content\": \"Hi there\", \"date\": \"`date +'%Y-%m-%d %T'`\"}" --accountId keegan.testnet
```
This isn't clear to me. Where is this greeting hash coming from? Do I need to enter this into the CLI? When I enter this:
```rust
export greeting=d8ae7a513eeaa36a4c6a42127587dbf0f2adbbda06523c0fba4a16bd275089f9
```
Nothing happens. If I copy and paste in its entirety, I get this:
```rust
export greeting=d8ae7a513eeaa36a4c6a42127587dbf0f2adbbda06523c0fba4a16bd275089f9
<200b><200b>near call $greeting send_greeting "{\"to_chain\": \"POLKADOTTEST\", \"title\": \"Greeting\", \"content\": \"Hi there\", \"date\": \"`date +'%Y-%m-%d %T'`\"}" --accountId YOU_NEAR_TEST_ACCOUNT
zsh: command not found: \u200b\u200bnear
```
When I enter just the second part, it seems to work and send the message.

1b. What should I be entering here? POLKADOTTEST?

dante

1c. What is this and how are you getting it to show up?

image

1d. For the next section, I am able to deploy the contracts and make the call but for me it returns "No value". I'm also not sure why you are using your MAIN (EXTENSION) account instead of the test accounts (Alice, Bob, etc.)?

dante2

1e. For the Malicious Message section, I am able to execute the call:

dante3

But it doesn't work and the contract reverts:

dante4

2. Am I supposed to be evaluating the [Demo-Show](https://github.com/dantenetwork/Demo-Show) repo? I see that commits have been made recently but this repo isn't mentioned anywhere in the M2 delivery.

3. I have some concerns about the centralization of this project. I should also be able to test the components without having to contact you to essentially "let me in". We only fund software that is completely open source and open to the public to scrutinize. Your code is open-source, but my reservations lie in the router credibility scheme, and the fact that the off-chain routers are running on AWS and are not open to the public. With other cross-chain smart contract bridging solutions, I've been able to test everything on Docker local testnets with no intervention from the team. Since we are in different time zones, it also delays the evaluation if I have to contact you and wait for you to add me, then troubleshoot, etc.

Maybe I am missing some knowledge here that you can fill me in on? Are you able to make the tests more clear? Thank you!

**Comment by xiyu1984** [comment]
Hey @keeganquigley ,

Thanks for your reminder and we found that some details are missing and we will fix them as soon as possible. You know that the features in this Milestone are really not very easy, so we missed some explanations that were obvious for us but may be confusing to others. I’m sorry about that.
Actually, I found most of the problems are related to the deployment environment. We have presented detailed deployment information in the [test guide](https://github.com/dantenetwork/protocol-stack-for-ink/tree/feature-sqos/test#test-environment), in which the key point is that we have started a testing chain of Polkadot ourselves because we have not found there are Testnet with the matched version of `ink!`. 

The recent update in [Demo-Show](https://github.com/dantenetwork/Demo-Show) is something about our next work, a Demo of a Omniverse Token Protocol, it's based on Dante but not in this Milestone. We can explain the details about it if you are interested.

Lastly, the concern about centralization.  I think I need to explain more. As mentioned before, it's not "let me in", and the main reason is that economic incentives are not included in this grant which is the plan at the next stage. Everyone can **freely** launch a router and register to Dante Network by **staking enough Token**, but now the incentive mechanisms are not ready. So, the Testnet at this stage is an **inner** Testnet which is also our first Testnet, and it is mainly used for users to try the abilities of interaction between smart contracts deployed on different public chains and show how some basic SQoS Items works.   
So, we think the registry is not very important at this stage and we just want to make the testing and evaluation more convenient. But I find that this may have confused you even more, and this may have been botched by us. 

So, if you think it's really necessary for the testing and evaluation, feel free to let us know and we really appreciate your suggestions. It's not very hard for us to change it that way as we just need to let routers in without any limitation temporarily, and it won't influence any other functions at this stage. 

By the way, although this is the end of this grant, we have decided to make a long development journey in the Polkadot ecosystem. This grant is just the beginning of Dante Network and it helps us make a very good start. Maybe we will apply new grants for the future development, which we have presented in the `future work` of this PR. Actually we have started the development of the Omniverse Token Protocol and Omniverse Swap Protocol in the `Substrate Pallet` tech stack. And the economic mechanism and the `Multi-Layer Gaming Model` based on these basic SQoS Items of this Milestone are what we are planning to build for the Dante Protocol at the next stage, which will provide a higher security guarantee with high efficiency. 

So we really appreciate your patience and suggestions, feel free to tell us any questions. Let’s complete this Milestone perfectly together~

*All of our teams are suffering from the COVID-19, so please give us some time to fix the details. I will tell you as soon as we finish it~*
2022.12.14 22:48----------------------------------------------------------------------------------------------

**Comment by xiyu1984** [comment]
Hey @keeganquigley ,

I think everything is ready. 

Actually, we found some incompatible problems of `substrate-contracts-node 0.21.0-e336e78ee2d` yesterday, trying the version of `ink!` and `substrate-contract-node` did take us a lot of time. Now we are temporarily using `substrate-contracts-node 0.20.0-8d76d04faca`. And we will publish another stable version until `ink 4.0.0` becomes stable.  

That's why I contact you again so late until now. 

Thank you for your patience and have a nice weekend. 

Best,

**Comment by keeganquigley** [comment]
Thanks for the changes @xiyu1984, the docs look much better now! The tests make a whole lot more sense, thanks for separating them and adding a detailed description at the top of each. I was able to get through all of the examples and better understand how the app works. Much appreciated! The contracts work for me with node `v0.20.0` and on your testnet. I'm happy to give this milestone a pass. Congrats! I will forward your invoice for payment.

**Comment by keeganquigley** [comment]
@xiyu1984 I am not finding a second invoice from your team. Can you upload a new one for Milestone 2?

**Comment by xiyu1984** [comment]
Hi @keeganquigley ,
Thanks again. We have submitted the invoice and changed the receiving address to the address on `Polkadot (Statemint)`.
We will continue our development on Polkadot, and I hope there's future cooperation with you. 
Feel free to contact us if you have any demands or questions, and we will appreciate it~

Best~

**Comment by keeganquigley** [comment]
Thanks @xiyu1984 for being willing to change the payment address. The invoice address needs to match the one on the original application, could you please submit an amendment PR to change the address on your application as well? It will need 3 approvals but these should happen quickly. Then I will submit the invoice for payment once it is approved. Thanks and sorry for the hassle!

**Comment by xiyu1984** [comment]
> Thanks @xiyu1984 for being willing to change the payment address. The invoice address needs to match the one on the original application, could you please submit an amendment PR to change the address on your application as well? It will need 3 approvals but these should happen quickly. Then I will submit the invoice for payment once it is approved. Thanks and sorry for the hassle!

Hey @keeganquigley ,
We've done the PR for that [here](https://github.com/w3f/Grants-Program/pull/1386), and it's come in handy for us. Just take your time and have a great Christmas break.

Best,

**Comment by keeganquigley** [comment]
No problem @xiyu1984 you're welcome! The amendment PR has been merged and I have sent the invoice for payment, so should be good to go now.

**Comment by RouvenP** [comment]
hi @xiyu1984 we transferred the payment today

**Comment by xiyu1984** [comment]
> hi @xiyu1984 we transferred the payment today

Thanks, @RouvenP, we have received it.

Merry Christmas，

Best,

**Pull request merged**
