### PR TITLE
Substratesnap_Maintenance-2

### PR DESCRIPTION
**Pull request by danforbes**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/874

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the delivery. However, is this for June or july? Delivery number 1 or 2? Since https://github.com/ChainSafe/metamask-snap-polkadot/pull/134 was already part of your previous delivery and the work was done at the beginning of june, see also https://github.com/w3f/Grant-Milestone-Delivery/blob/master/maintenance_evaluations/Substratesnap_Maintenance_1_Noc2.md

**Comment by danforbes** [comment]
Hi, David - I think this would be delivery 2 for June. Delivery number 1 was for May and the invoice for that was submitted by some non-standard mechanism, I believe. Most of the work for https://github.com/ChainSafe/metamask-snap-polkadot/pull/134 was done in June, but it looks like the work was started at the very end of May, which is probably why it was represented on the May delivery as well.
image

**Review by Noc2 — APPROVED** [review]
I’m generally happy to approve the delivery and merge it. But regarding the invoice, weren’t we supposed to get a discount or something because of the previous month?  Could you potentially upload an updated invoice?

**Comment by Noc2** [comment]
Just for the records: I will forward the updated invoice internally.

**Pull request merged**
