### PR TITLE
Create Sandox_st1_ms2_delivery.md

### PR DESCRIPTION
**Pull request by TradeLinkEstonia**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the Statemint account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1694

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sandox_2_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by TradeLinkEstonia** [comment]
Hi, @dsm-w3f 
we've fixed the issue with FireFox and supplemented the main `readme` file.
Also, we have udated the IDE to the latest version on the sandox.io web site

Please, check

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the improvements and fixes. We are almost finishing this evaluation. Just a small problem in Firefox yet. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sandox_2_dsm-w3f.md). Let when I can continue this evaluation.

**Comment by TradeLinkEstonia** [comment]
@dsm-w3f Diogo, we have fixed the lately mentioned FF-related bugs.
About displaying the column number of the cursor: as we didn't plan it in the 2nd Milestone and not to break the current work sprint, I suppose to deliver it in the 3rd Milestone. Is that ok?

**Comment by dsm-w3f** [comment]
@TradeLinkEstonia thank you for the answer and fixes. It is okay to deliver this improvement in the next milestone. I checked again and now it works well with Firefox. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by RouvenP** [comment]
hi @TradeLinkEstonia we just transferred the payment

**Pull request merged**
