### PR TITLE
Social Recovery Wallet Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by n13**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1001](https://github.com/w3f/Grants-Program/pull/1001)
```https://github.com/w3f/Grants-Program/pull/1001```

### CODE REVIEW

**Comment by n13** [comment]
This check fails: Match not found for: application_document. I have linked the application document - not sure what's wrong with this.

**Comment by n13** [comment]
> This check fails: Match not found for: application_document. I have linked the application document - not sure what's wrong with this.

Fixed

**Comment by n13** [comment]
Please contact me for a Hashed account with a balance, and for adding emails to the test tracks on Apple App store @n1300:matrix.org

**Review by takahser — CHANGES_REQUESTED** [review]
@n13 as discussed on Element, the tests are currently resulting in an error. The rest of the delivery looks good. For more details, please have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_1_takahser.md).

Also, for reference, I'll link the issues that correspond to the bugs we've discussed:

- https://github.com/hypha-dao/hashed-wallet/issues/106
- https://github.com/hypha-dao/hashed-wallet/issues/107
- https://github.com/hypha-dao/hashed-wallet/issues/108

**Comment by n13** [comment]
> @n13 as discussed on Element, the tests are currently resulting in an error. The rest of the delivery looks good. For more details, please have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_1_takahser.md).
> 
> Also, for reference, I'll link the issues that correspond to the bugs we've discussed:
> 
> * [hypha-dao/hashed-wallet#106](https://github.com/hypha-dao/hashed-wallet/issues/106)
> * [hypha-dao/hashed-wallet#107](https://github.com/hypha-dao/hashed-wallet/issues/107)
> * [hypha-dao/hashed-wallet#108](https://github.com/hypha-dao/hashed-wallet/issues/108)
> 
> As discussed, you won't need to fix these bugs as part of this delivery, but it would be nice if you could address them until the M2 delivery.

Thank you for the review!

1 - I will fix these bugs for the M2 delivery, no problem. Already created tickets
2 - Also created a ticket for the active button/label - this is a case of programmer doing the design ;) 
3 - Docker - docker works, please try again with a new version.

## Docker Issue Overview

I removed all cached containers from my docker build and ran again, everything worked. 
I also installed Docker from scratch on another laptop, and ran the tests for the first time ever, it all worked too. 
Reviewer has the exact same OS version as I do, running on the same hardware (M1 Mac OS X 12.5.1. 
I was searching on the web for the reported error and found that it can be caused by older Docker versions, and the fix was using a newer Docker version.

My best guess is therefore that the Docker version needs to be updated on the reviewer machine.

I was unaware of this bug in older Docker versions, or else the tutorial and install instructions would have included something about Docker version - I will add this to the instructions. 

### Docker run logs running on a new Mac

```
~/play/polkadot/hashed-wallet/docker tags/1.0.0_prerelease_M1
❯ ./run_docker.sh 
[+] Building 979.3s (24/24) FINISHED                                                                                   
 => [internal] load build definition from Dockerfile                                                              0.0s
 => => transferring dockerfile: 1.41kB                                                                            0.0s
 => [internal] load .dockerignore                                                                                 0.0s
 => => transferring context: 2B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                   6.1s
 => https://api.github.com/repos/hypha-dao/hashed-wallet/commits?per_page=1                                       0.0s
 => [builder  1/16] FROM docker.io/library/ubuntu:20.04@sha256:af5efa9c28de78b754777af9b4d850112cad01899a5d37d2  10.6s
 => => resolve docker.io/library/ubuntu:20.04@sha256:af5efa9c28de78b754777af9b4d850112cad01899a5d37d2617bb94dc63  0.0s
 => => sha256:3f8ab90e40ca1d1741effaaab60bae74ca8b6d4500fe3967706b55d700a76ae6 529B / 529B                        0.0s
 => => sha256:eb574ad4e57ceb06d0b32e014e1579acaca4debe37db5c4cc375aad1335d70fd 1.48kB / 1.48kB                    0.0s
 => => sha256:a749a280e3e905de447c3d95a39e8aa1ede5835a6eadeb0c11596051592b675b 27.19MB / 27.19MB                  9.8s
 => => sha256:af5efa9c28de78b754777af9b4d850112cad01899a5d37d2617bb94dc63a49aa 1.42kB / 1.42kB                    0.0s
 => => extracting sha256:a749a280e3e905de447c3d95a39e8aa1ede5835a6eadeb0c11596051592b675b                         0.7s
 => [builder  2/16] RUN ln -snf /usr/share/zoneinfo/Asia/Dubai /etc/localtime && echo Asia/Dubai > /etc/timezone  0.2s
 => [builder  3/16] RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk wg  346.6s
 => [builder  4/16] RUN useradd -ms /bin/bash user                                                                0.2s
 => [builder  5/16] WORKDIR /home/user                                                                            0.0s 
 => [builder  6/16] RUN mkdir -p Android/sdk                                                                      0.1s 
 => [builder  7/16] RUN mkdir -p .android && touch .android/repositories.cfg                                      0.2s 
 => [builder  8/16] RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.  35.1s 
 => [builder  9/16] RUN unzip sdk-tools.zip && rm sdk-tools.zip                                                   1.8s 
 => [builder 10/16] RUN mv tools Android/sdk/tools                                                                0.7s 
 => [builder 11/16] RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses                                 3.9s 
 => [builder 12/16] RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platform-to  59.5s 
 => [builder 13/16] RUN git clone https://github.com/flutter/flutter.git                                        202.3s 
 => [builder 14/16] RUN flutter channel stable                                                                  132.3s 
 => [builder 15/16] RUN flutter upgrade                                                                          69.2s 
 => [builder 16/16] RUN flutter doctor                                                                           18.2s 
 => [test 1/3] ADD https://api.github.com/repos/hypha-dao/hashed-wallet/commits?per_page=1 latest_commit          0.0s 
 => [test 2/3] RUN git clone https://github.com/hypha-dao/hashed-wallet.git                                      33.1s 
 => [test 3/3] RUN cd hashed-wallet && flutter test                                                              49.6s 
 => exporting to image                                                                                            9.4s 
 => => exporting layers                                                                                           9.4s 
 => => writing image sha256:0e1c7a134a33e395462b89afa42a5fd20398afb3fb155e1914369e1691c4d0c6                      0.0s 
 => => naming to docker.io/library/flutterdocker                                                                  0.0s 
```
=> this is a successful run

#### Docker version 
```
❯ docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.17.2
 Git commit:        b485636f4b
 Built:             Fri Oct 15 14:45:13 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```


#### OS version
```
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.5.1
BuildVersion:	21G83

```

**Comment by n13** [comment]
@takahser I have updated the testing instructions for the unit tests with the Docker version info.

image

**Comment by takahser** [comment]
@n13 thanks for the update and the advice regarding the docker update, this resolved the error I experienced.
I'm now able to compile the container:

```bash
% docker build -t flutterdocker .
[+] Building 353.6s (24/24) FINISHED                                                                                     
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 37B                                                                                 0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                     3.2s
 => [builder  1/16] FROM docker.io/library/ubuntu:20.04@sha256:af5efa9c28de78b754777af9b4d850112cad01899a5d37d2617  0.0s
 => CACHED https://api.github.com/repos/hypha-dao/hashed-wallet/commits?per_page=1                                  0.0s
 => CACHED [builder  2/16] RUN ln -snf /usr/share/zoneinfo/Asia/Dubai /etc/localtime && echo Asia/Dubai > /etc/tim  0.0s
 => CACHED [builder  3/16] RUN apt update && apt install -y curl git unzip xz-utils zip libglu1-mesa openjdk-8-jdk  0.0s
 => CACHED [builder  4/16] RUN useradd -ms /bin/bash user                                                           0.0s
 => CACHED [builder  5/16] WORKDIR /home/user                                                                       0.0s
 => CACHED [builder  6/16] RUN mkdir -p Android/sdk                                                                 0.0s
 => CACHED [builder  7/16] RUN mkdir -p .android && touch .android/repositories.cfg                                 0.0s
 => CACHED [builder  8/16] RUN wget -O sdk-tools.zip https://dl.google.com/android/repository/sdk-tools-linux-4333  0.0s
 => CACHED [builder  9/16] RUN unzip sdk-tools.zip && rm sdk-tools.zip                                              0.0s
 => CACHED [builder 10/16] RUN mv tools Android/sdk/tools                                                           0.0s
 => CACHED [builder 11/16] RUN cd Android/sdk/tools/bin && yes | ./sdkmanager --licenses                            0.0s
 => CACHED [builder 12/16] RUN cd Android/sdk/tools/bin && ./sdkmanager "build-tools;29.0.2" "patcher;v4" "platfor  0.0s
 => [builder 13/16] RUN git clone https://github.com/flutter/flutter.git                                          100.2s
 => [builder 14/16] RUN flutter channel stable                                                                     87.1s 
 => [builder 15/16] RUN flutter upgrade                                                                            70.6s
 => [builder 16/16] RUN flutter doctor                                                                             16.6s 
 => [test 1/3] ADD https://api.github.com/repos/hypha-dao/hashed-wallet/commits?per_page=1 latest_commit            0.0s 
 => [test 2/3] RUN git clone https://github.com/hypha-dao/hashed-wallet.git                                        22.0s 
 => [test 3/3] RUN cd hashed-wallet && flutter test                                                                50.7s 
 => exporting to image                                                                                              3.2s 
 => => exporting layers                                                                                             3.2s 
 => => writing image sha256:cfde87760c72a7e34f4747daadd06b66751306b7587f89abddefb5b1a78a61f8                        0.0s 
 => => naming to docker.io/library/flutterdocker        
```
I was wondering if there are any more detailed results available, other than those listed below.

```bash
 => [test 1/3] ADD https://api.github.com/repos/hypha-dao/hashed-wallet/commits?per_page=1 latest_commit            0.0s 
 => [test 2/3] RUN git clone https://github.com/hypha-dao/hashed-wallet.git                                        22.0s 
 => [test 3/3] RUN cd hashed-wallet && flutter test                                                                50.7s 
```

**Review by takahser — APPROVED** [review]
@n13 as discussed on Element, I'm fine with accepting this delivery, since you shared more detailed outputs for the unit tests:

```bash
~/play/polkadot/hashed-wallet feature/restart_2* 12s
❯ flutter test test/account_service_test.dart 
00:02 +3: All tests passed!   
❯ flutter test -r expanded test/account_service_test.dart 
00:00 +0: Test loadAccounts saveAccounts
00:00 +1: Test createAccount
00:00 +2: Test getPrivateKeys, savePrivateKeys
00:00 +3: All tests passed!
```
However, please add more detailed test outputs for M2. Currently it's not clear, which tests actually were run, when using Docker (which is currently the recommended approach according to your instructions, mainly because it simplifies the dependency management, e.g. Android emulator installation). Also, feel free to add more tests. Thanks for already having added a corresponding [ticket](https://github.com/hypha-dao/hashed-wallet/issues/116).

The final evaluation can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_1_takahser.md).

**Comment by n13** [comment]
> @n13 as discussed on Element, I'm fine with accepting this delivery, since you shared more detailed outputs for the unit tests:

Thank you for the approval!

I have fixed the unit test output, it's now showing all unit tests run and their results by default.

https://github.com/hypha-dao/hashed-wallet/issues/116

release branch has been merged so this is going to be in M2.

**Comment by fededubbi** [comment]
Good morning, I noticed on the invoice is missing our billing address:
Baarerstrasse 14,
6300, Zug.

Could you please add it and resend the invoice?

Many thanks,
Federica Dubbini

**Comment by n13** [comment]
> Good morning, I noticed on the invoice is missing our billing address: Baarerstrasse 14, 6300, Zug.
> 
> Could you please add it and resend the invoice?
> 
> Many thanks, Federica Dubbini

@fededubbi I have updated the invoice and re-submitted it through the same process as before.

Let me know if it is complete now.

**Comment by fededubbi** [comment]
All good, thanks.

Federica

**Comment by RouvenP** [comment]
hi @n13 we transferred the payment today.

**Comment by n13** [comment]
I have run the tests again from scratch and they are working for me 

However, I have googled the error and it has to do with security protocols and the Docker version with some people reporting a new docker version does not have the problem. 

I am attacking the version of docker that I am running. Please make sure your docker version is at least at that revision when running docker. 

I was unaware of this issue but I believe it is a tools issue - Docker - and not a project or test issue. 

docker version
Client:
 Cloud integration: v1.0.28
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.11.1 (84025)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Pull request merged**
