### PR TITLE
project idiyanale: multi-token community contributions for verified creators milestone 2

### PR DESCRIPTION
**Pull request by woss**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1224

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @woss, thanks a lot for the delivery. Someone of the team will evaluate it soon.

**Comment by randombishop** [comment]
Hi @woss !
Sorry for the delay in processing your delivery, we are working on it and I will send you feedback soon!
Can you please send me some test net tokens (MIDI?) to this address 5Gnixfp6vnznRkr91JgwkxYnCJCyHr8EaBzYfFsUKcTMzVYF so I can test the deployed webapp?
Thank you!

**Comment by Eltairovy** [comment]
Hi @randombishop sent you some IDI for testing. Looking forward for the feedback. Thanks!

**Comment by randombishop** [comment]
Thank you @Eltairovy !

**Comment by randombishop** [comment]
One more question @Eltairovi @woss please: I registered a domain to my account and would like to test the tipping process with the UX, how can I install the extension?

**Comment by woss** [comment]
@randombishop i believe we provided the videos in the delivery table. 

Nevertheless here is the URL  for the tutorial we published https://anagolay.dev/blog/chrome_extension_wallet/installation-and-step-by-step-tutorial/

**Comment by randombishop** [comment]
Thanks for the link @woss ! I watched the video and found it cool so I wanted to try out the extension myself :)
I am trying now to compile the substrate blockchain (with `makers build`) but I am hitting this error:
```
 error[E0658]: `let` expressions in this position are unstable
     --> /Users/w3f/pycharm_workspace/anagolay-chain/pallets/tipping/src/lib.rs:188:14
      |
  188 | ...if let Some(request) = verification::Pallet::<T>::verification_request_by_account_id_and_verification_context(holder.clone(), setting.context.clone()) &&...
      |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
      = help: add `#![feature(let_chains)]` to the crate attributes to enable
```
Any idea on how I could fix this?
Thank you!

**Comment by woss** [comment]
@randombishop, you should use the nightly for building and use this tag https://github.com/anagolay/anagolay-chain/tree/w3f-project-idiyanale-multi-token-community-contributions-for-verified-creators-milestone-2

Unfortunately, we don't maintain developer environments apart from the gitpod. If you are using that, then you will have the environment set up. If you do not use it, there are scripts in the `.devops/scripts`, which you need to run to get stuff installed.

Let me know if you need anything

**Comment by randombishop** [comment]
Thanks @woss !
Never used gitpod so tried to build stuff as usual. 
Installing and setting `nightly-2022-08-29` as the default rustup toolchain fixed the issue. I can run the `makers` tasks fine now.
Should finish this evaluation tomorrow...

**Comment by randombishop** [comment]
Hi @woss
Happy to inform you that your delivery was accepted.
You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/anagolay_idiyanale_2_randombishop.md)
Cheers!

**Comment by woss** [comment]
@randombishop thanks :) I hope the invoice is OK.

**Comment by randombishop** [comment]
@woss Yes, just forwarded the invoice for payment.
Please allow for up to two weeks for processing.

**Comment by randombishop** [comment]
+cc @cwilker you should have a look at this: https://anagolay.network/

**Comment by woss** [comment]
if you guys are interested in learning more about this, can we set up a Matrix chat for us? Here is my matrix `@woss:matrix.org`

**Comment by randombishop** [comment]
@woss I am not active anymore on the Wika Network project but maybe @cwilker would be interested...
Anyways, best of luck for the future of Anagolay and looking forward to seeing more progress, you guys are building good things for web3!

**Pull request merged**
