### PR TITLE
Pontem Network. Milestone #1

### PR DESCRIPTION
**Pull request by borispovod**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [X] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [X] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md). 

**Important:** We've changed BTC address to 3NyW7fGDFqZW2PopiXeHdMvTtmXrkgQb8w.

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery. We will look into it next year ;)

**Comment by borispovod** [comment]
Hello @mmagician ! Any update?

**Comment by mmagician** [comment]
Hi @borispovod, not yet. Please allow a couple more days for the review and apologies for the delay.

**Comment by mmagician** [comment]
Hey @borispovod, so far these are my comments regarding the first milestone:
1. License from pallet repo missing
2. > During our research we can use sp-std for part of cases, but unfortunately we will have to fork it and add additional functional or create our analogue crates contains missed functional.

While I see that you forked petgraph and indexmap & your modifications are easy to track, for the [Move VM](https://github.com/dfinance/sp-move-vm) repo it seems that you chose the latter solution of creating your own crate alongside the main diem repo. 
I wonder how easy it'll be for you to keep up-to-date with latest developments of the parent repo - since yours is not a fork, you probably can't easily rebase your modifications & get upstream Move updates, right?

Furthermore, your standalone repo is a small subset of the [diem](https://github.com/diem/diem) parent. 
Is this because you don't need all of upstream functionality, or is this just a temporary measure for milestone 1 & later you're planning to bring in the rest?
Either way, the [difference](https://github.com/dfinance/sp-move-vm#differences) section falls short of explaining what's included, what's skipped, and why. Could you please elaborate on that?

3. Could you perhaps add a line to move-tools README explaining which rust toolchain to use? I could not install `dove` neither using latest stable nor nightly and so without it I can't finalise the manual test.

**Comment by borispovod** [comment]
Hello, @mmagician!

Thank you for review. 

1. See [PR](https://github.com/dfinance/sp-move/commit/c2175435b233d8b74f79cdecce5c5a04a3951e36) merged.
2. Well, we have to replace Rust std and make it runtime compatible, this is the main reason why we've done forks. Such small libs like petgraph, indexmap we can update from time to time manually, when new versions releases, also we can try to make a pull request to parent repos, but we are pretty not sure someone will merge it. 

Now about Diem. We've forked the virtual machine. We also can't find another way, only a fork now. Diem mono repo contains a lot of non-VM related code, but also blockchain related code (consensus, configs, node, p2p, etc). In the case of the VM pallet we don’t need that code. During the fork of the virtual machine we removed usage of standard library, also we removed cryptography,  yet we are planning to bring it back and make compatibility with Polkadot cryptography, etc.

We also planned to bring a Move standard library to our pallet later, so it is also part of Diem, but we are going to change it a little to make it compatible with Polkadot and our pallet. 

In case of new updates to Diem we are going to do a manual update, it takes time for sure,  but we can't find another way, also soon Diem will release a stable version and we expect that updates will become not so often. 

3. Can you provide more details, please? 
I'm using `rustc 1.49.0` and everything just builds fine, i build using command:

```
cargo install --bin=dove --path dove --features="ps_address" --no-default-features
```

So in nutshell use latest stable or nightly must works too, we tried on 1.48.0 and it works also.
I'm not sure that update to README will solve issue somehow.

**Comment by borispovod** [comment]
Hey @mmagician . 

We [fixed bug](https://github.com/dfinance/move-tools/commit/1f29cfccd706c770f0490d447e3d4b19e4d816a6) which happens during dove build. 

So, you can try now, fetch latest master branch from [move-tools](https://github.com/dfinance/move-tools) repo.

**Comment by mmagician** [comment]
Congratulations on completing the first milestone! See the [official evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/pull/87) for more details.

**Pull request merged**
