### PR TITLE
Social Recovery Wallet Milestone 3 Delivery

### PR DESCRIPTION
**Pull request by n13**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1001](https://github.com/w3f/Grants-Program/pull/1001)
```https://github.com/w3f/Grants-Program/pull/1001```

### CODE REVIEW

**Comment by takahser** [comment]
@n13 thanks for the delivery, I'll have a look shortly and get back to you.

**Comment by takahser** [comment]
@n13 thanks for your patience here and sorry for the delay. I tested your app on two iPhones and I have a few comments:

- When receiving tokens through the app a share link is being displayed. In my case it was `ssr://H4sIAAAAAAAAEz2MzQqCQBhF3-VbuygjKNdJpLTIChJ18Tkz_uD84cwYKL57g4vu6nA43AVIh728UYhAKz4gVRYCsCNKg8T2ShqIigWEoo4zH9XIURJmfESQc2-2tmGjN4ZJ6iEC07dyMxpHFP4CihKO17jWc3iOh-f9MKV2du_4Y786PU2ty0X4yjIj2PBwTZ5cEj2XEOx3_1WwVusP92-m_68AAAA=`.
    - What format is that?
    - How can I use it to send tokens?
    - I didn't find any way to copy the wallet address itself, e.g. if you want to receive tokens from a different wallet. Maybe this would make sense to add there?
- When scanning the QR code with a 2nd phone, it doesn't validate whether the account is sufficiently funded. I think it'd be helpful to have validation. Also, if the balance is too low an error occurs, and if you then tap the "back" button the app hangs, showing a spinner in the center:

    Screenshot 2023-02-10 at 17 56 03

**Comment by n13** [comment]
> @n13 thanks for your patience here and sorry for the delay. I tested your app on two iPhones and I have a few comments:
> 

Thanks for your comments - going through these!

> * When receiving tokens through the app a share link is being displayed. In my case it was `ssr://H4sIAAAAAAAAEz2MzQqCQBhF3-VbuygjKNdJpLTIChJ18Tkz_uD84cwYKL57g4vu6nA43AVIh728UYhAKz4gVRYCsCNKg8T2ShqIigWEoo4zH9XIURJmfESQc2-2tmGjN4ZJ6iEC07dyMxpHFP4CihKO17jWc3iOh-f9MKV2du_4Y786PU2ty0X4yjIj2PBwTZ5cEj2XEOx3_1WwVusP92-m_68AAAA=`.
>   
>   * What format is that?

This is an encoded substrate signing request URL. 

Spec version 0.1 is here: https://github.com/hypha-dao/hashed-wallet/wiki/Substrate-Signing-Request-Specification

The idea is to make this into a full blown spec by adding identity (login) and callbacks. Both relatively easy to do. 

For the time being the URL encodes a signing request for a substrate transaction.

A receiver - another phone - can tap on the link, the wallet will open with this link, and the signing request will display, then can be accepted or canceled. 

The URL can also be encoded as QR code and users can use the scan function on the phone to open the link.

The ssr:// URL scheme should open the app on both iOS and android. 

There's also another option to show firebase deep links - these would allow us to download the wallet app and then open it with a parameter delivered to the newly installed app. That's cool, but in our case, a new user doesn't have a polkadot balance and firebase deep links, while more powerful, are also less decentralized, as they depend on Google services. 

Naked SSR:// URL scheme does not have any dependencies and is universally parseable. (see spec)


>   * How can I use it to send tokens?

It's more a request for someone else to sign. 

So you could request tokens from your friend, your friend scanning the QR on your phone, or opening the ssr:// link. 

A website could request you to pay some tokens, showing you a QR code. You could scan the QR code, send the tokens, and a callback can alert the website that the transfer happened. 

This is replacing the browser plugins people normally use, with a much more secure and 2FA style system. 

Any transaction can be signed by the wallet, so it's just as powerful as the browser plug-in.


>   * I didn't find any way to copy the wallet address itself, e.g. if you want to receive tokens from a different wallet. Maybe this would make sense to add there?

If you want to have a specific wallet send you the token, the wallet does not do that right now - request for token is always set to "whoever signs off" which makes it more generic. 

It's possible to encode a transaction that says "I want 4 tokens from Nik". 

What the wallet is doing - receive is really just a showcase for the QR Codes - is "I want 4 tokens from whoever is signing this", so it's more universal. 

We could add the ability to specify a wallet but not sure how useful that would be?

We are using this system every day on EOSIO using Anchor wallet and UAL and esr:// signing requests, and generally we don't need this. But maybe Polkadot is different, I don't know - for example, if it's common for people to have many different wallets then maybe it would make sense?

> * When scanning the QR code with a 2nd phone, it doesn't validate whether the account is sufficiently funded. I think it'd be helpful to have validation. Also, if the balance is too low an error occurs, and if you then tap the "back" button the app hangs, showing a spinner in the center:

>     Screenshot 2023-02-10 at 17 56 03

Ok I will fix these 2 bugs
- check for low balance
- on error, make sure user sees error message and can exit

**Comment by n13** [comment]
@takahser 

Actually I am unsure we can check for low balance - since the QR code scan function can be any transaction, or even a sequence of transactions, it will be impossible to figure out beforehand how many tokens this will cost. 

We will have to try the transaction, and show an error on fail

Best we could do is check if the balance is 0 and the user can't make any transactions - that's possible.

**Comment by takahser** [comment]
@n13 thanks for the thorough replies.

> It's more a request for someone else to sign.

Sorry, I meant to say _"How can I use it to receive/request tokens?"_ there. Assuming the counter-party who's supposed to send me tokens does NOT use the _HashedWallet_ app (or any other app that might support the _ssr_ URL scheme), how will they be able to send the tokens? That's why I thought it might be helpful to have the wallet address there to copy and send it, even though we lose the information on how many tokens we request.
Btw, thanks for sending the ssr URL scheme, that's pretty cool actually. And no, I don't think we need to encode the sender into it. :)

> Ok I will fix these 2 bugs
> (...)
> (from the Element chat) For payment info, I found this - I didn't know Polkadot has a fee estimator https://polkadot.js.org/docs/api/start/api.tx.subs/#payment-information

Okay sounds good 👍

**Comment by n13** [comment]
> Sorry, I meant to say _"How can I use it to receive/request tokens?"_ there. Assuming the counter-party who's supposed to send me tokens does NOT use the _HashedWallet_ app (or any other app that might support the _ssr_ URL scheme), how will they be able to send the tokens? That's why I thought it might be helpful to have the wallet address there to copy and send it, even though we lose the information on how many tokens we request.

On the top bar of the app, next to the address, there's a "copy" icon for copying the wallet address

image

**Comment by n13** [comment]
- [ ] Forever Spinner bug:
https://github.com/hypha-dao/hashed-wallet/issues/191

- [ ] Add feature to share wallet address:
https://github.com/hypha-dao/hashed-wallet/issues/193

- [ ] Low balance check:
https://github.com/hypha-dao/hashed-wallet/issues/192

**Comment by n13** [comment]
Ok @takahser I will fix these - I should have done more on device testing for the QR code bug, I know why this happens.

**Comment by n13** [comment]
I posted build 15 which addresses these issues:

- Check low balance - this was due to Polkadot existential deposit of 1 DOT. It was not a transaction fee error, but rather an error that happened when an account with only 1 dot tries to send DOT to another account - it fails. So in this case the wallet was showing the correct error message. 

- QR code scanner had issues on real device, scanning endlessly and opening many windows. This is fixed.

- Done button did not work on QR code screen - fixed.

**Comment by takahser** [comment]
@n13 thanks for the wait, I reassessed, and these are my findings:

- Regarding the existential deposit, I confirm the transfer works if the balance is sufficient. ✅
- QR code glitch (multiple windows spawned: Fixed ✅
- Done button bug: Fixed ✅

In addition to that, I noticed that:

- after the transaction is successfully completed, the amount in the wallet is not updated automatically. To update the UI, the user has to refresh the wallet (reopen or pull-down gesture). I think if it'd automatically update, it would be great. And once that's implemented, it'd probably make sense to show a notification.
- in a scenario where the receiver wouldn't have an amount that at least matches the existential deposit (e.g. 1 DOT for Polkadot) the transaction is still being sent and fails. Hence, the sender loses transaction fees. I was wondering how (or if) other wallets solve this problem?

**Comment by n13** [comment]
> @n13 thanks for the wait, I reassessed, and these are my findings:
> 
> * Regarding the existential deposit, I confirm the transfer works if the balance is sufficient. ✅
> * QR code glitch (multiple windows spawned: Fixed ✅
> * Done button bug: Fixed ✅
> 
> In addition to that, I noticed that:
> 
> * after the transaction is successfully completed, the amount in the wallet is not updated automatically. To update the UI, the user has to refresh the wallet (reopen or pull-down gesture). I think if it'd automatically update, it would be great. And once that's implemented, it'd probably make sense to show a notification.
> * in a scenario where the receiver wouldn't have an amount that at least matches the existential deposit (e.g. 1 DOT for Polkadot) the transaction is still being sent and fails. Hence, the sender loses transaction fees. I was wondering how (or if) other wallets solve this problem?


(1) - I did this even if I think fixing the wallet up to be an actual beta version isn't really part of the milestone... but - it is nice. 

(2) - I think that is out of scope for this delivery but I would add this as a ticket for beta. https://github.com/hypha-dao/hashed-wallet/issues/195

I am also showing fees on the QR screen and on Send. Not really part of the milestone either, but cool. 

Let me know if there's anything still missing or buggy as the milestone delivery is concerned. Thanks for your throurough review @takahser

**Review by takahser — CHANGES_REQUESTED** [review]
Hi @n13

As discussed on Element, I think by now we've sufficiently tested and fixed this delivery when it comes to its features, so I now took a closer look at the delivery report. I'd like to raise the following points:
- could you get rid of any HTML code in the delivery report? Currently, there are a bunch of `<BR>` which might interfere with our processes.
- regarding deliveries 1-4, could you add links there as well?
- regarding 4), did you publish the app to the corresponding stores, yet?

You can find my interim evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_3_takahser.md).

**Comment by n13** [comment]
@takahser I updated the delivery report as requests. 

I was a little unclear on some things, please let me know if this is sufficient.

**Review by takahser — APPROVED** [review]
@n13 thanks, I've accepted your delivery. Feel free to have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/social-recovery-wallet_3_takahser.md).

**Comment by fededubbi** [comment]
Hi @n13,

Our complete name and address is the following.
Can you please update it and resend?

Web 3.0 Technologies Foundation 
Baarerstrasse 14
6300 Zug
SWITZERLAND

Many thanks,
Federica

**Comment by n13** [comment]
> Hi @n13,
> 
> Our complete name and address is the following. Can you please update it and resend?
> 
> Web 3.0 Technologies Foundation Baarerstrasse 14 6300 Zug SWITZERLAND
> 
> Many thanks, Federica

I have sent another invoice, updated with the requested information. 

Thank you!

**Comment by RouvenP** [comment]
hi @n13 we transferred the payment today.

**Comment by n13** [comment]
> hi @n13 we transferred the payment today.

Thank you! Received!

**Pull request merged**
