### PR TITLE
SubsCrypt milestone 2 & 3

### PR DESCRIPTION
**Pull request by SaberDoTcodeR**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/171

### CODE REVIEW

**Comment by SaberDoTcodeR** [comment]
The node is running on this address: wss://canvas.subscrypt.io:443

**Comment by alxs** [comment]
Thank you for the delivery @SaberDoTcodeR. We will look into it as soon as possible.

**Comment by Noc2** [comment]
@SaberDoTcodeR Thanks again for the delivery. I started to look into it. Could you take a look at my [notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md)?  I did run into a few issues, when I tried to test the deliverables. A tutorial might be useful also for other users.

**Comment by SaberDoTcodeR** [comment]
@Noc2 Thanks for the notes; The tests were failed because the contract was trapped due to insufficient balance. Now the tests will work, please recheck it. Also, we will upload a Demo Video for a tutorial of our service, but for sure, lots of work is ahead of us for making the front-end user-friendly and make the project ready for a product stage(including making a home page for the project). 
‍‍could you please mention your npm version regarding to your `npm run dev` error? I can not reproduce that error.

**Comment by Noc2** [comment]
Quick update: I tried to compile the front-end with npm 6.14.11 and 7.20.6, it’s still doesn’t load for me, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md)

**Comment by SaberDoTcodeR** [comment]
> Quick update: I tried to compile the front-end with npm 6.14.11 and 7.20.6, it’s still doesn’t load for me, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md)

I'm afraid that I can not reproduce the error with the exact same npm version of you on multiple devices. Please, run the code on this [branch](https://github.com/oxydev/SubsCrypt-front/tree/unhandled-promise-rejection) to produce a more descriptive error message. Also, Docker option is available for easier deployment. Just run `docker-compose up`. We can continue the discussion about this error in this [issue](https://github.com/oxydev/SubsCrypt-front/issues/10).

PS: Tests should work fine right now; please run and test it.

**Comment by mmagician** [comment]
@SaberDoTcodeR The tests are indeed fixed. I ran into the same error as previously reported, I commented [here](https://github.com/oxydev/SubsCrypt-front/issues/10#issuecomment-900182821).

**Comment by Noc2** [comment]
To also confirm it here. It compiles now, see my [updated evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md). But it would still be nice to have a tutorial or demo video. I managed this time to subscribe to a plan. I used https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcanvas.subscrypt.io%3A443#/accounts to send me some tokens and used a browser with a fresh polkadot.js extension installed. Otherwise I did run into the issue that it always selected the same account even though I selected a completely different account. But still I wasn’t able to do a refund or to select a plan, which I created as admin.

**Comment by Noc2** [comment]
I also started to look into milestone 3, see [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_3_Noc2.md)

**Comment by Noc2** [comment]
To confirm it here as well. The test coverage was improved, see https://github.com/oxydev/SubsCrypt-npm-library/issues/26#issuecomment-904392498

**Comment by SaberDoTcodeR** [comment]
@mmagician  Sorry for the delay, You can see a tutorial video of SubsCrypt here on [youtube](https://www.youtube.com/watch?v=FvGJJdy5ub4). 
As mentioned in the evaluation notes of [Second Milestone](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_Noc2.md) the refund had a UI problem which is resolved now. Also, The faucet doesn't have a problem please use it as the tutorial and let me know if it doesn't send you test coins.

PS: We will fix issues of the 3rd milestone meanwhile.

**Comment by HadiEsna** [comment]
@mmagician 
We've improved the test coverage [here](https://github.com/oxydev/SubsCrypt-nodejs-backend/issues/17)

**Comment by HadiEsna** [comment]
Hi @mmagician 

- I didn't find any notes about item 1.1 in this [list](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_3_Noc2.md)

- We've improved test coverage(item 1.3), and it is covering 100% of testable functionalities now. Please check if it meets the conditions.

- For item 2.4, we implemented the npm package for interaction with the contract and both front-end and back-end are using that library. Because of this, it is the same as for milestone 2.

- For item 2.5, [this](https://oxydev.github.io/SubsCrypt-docs/#/Tech/Back_end/SubsCrypt-npm) is how to use the package and [this](https://github.com/oxydev/SubsCrypt-npm-library/tree/main/docs) is the documentation of functionalities of the library.

- For items 2.1 and 2.3, please check out this links [repo](https://github.com/oxydev/SubsCrypt-python-package), [published package](https://pypi.org/project/subscrypt/). Please note if you expect something else.

**Comment by mmagician** [comment]
@SaberDoTcodeR @HadiEsna I've done another evaluation round of Milestone 2 [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subscrypt_2_mmagician.md). You will find there are quite a lot of outstanding issues and I would like to ask you to fix these before proceeding with the evaluation.

**Comment by mmagician** [comment]
@HadiEsna @SaberDoTcodeR Thanks for the revision, I'll check it in the coming days.

**Comment by mmagician** [comment]
@SaberDoTcodeR @HadiEsna I've checked the new portal, I must say it looks great!
I would be happy to accept Milestone 2.
Regarding Milestone 3, I believe the original scope has changed and you are no longer delivering Django code. If that's indeed the case, we would need to officially amend the contract before I can accept M3.
I have created a PR to amend the original deliverables list to make things easier, but I would need @SaberDoTcodeR to comment under that PR whether the changes are ok with you: https://github.com/w3f/Grants-Program/pull/673

Once we have this merged, I will go ahead and merge the [acceptance PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/300).

**Comment by SaberDoTcodeR** [comment]
@mmagician Thanks a lot for your guidance throughout this project.🙏

**Pull request merged**
