### PR TITLE
MassBit Route - Milestone 1 - Grant delivery

### PR DESCRIPTION
**Pull request by daywednes**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the USDC/USDT(ETH network) payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/985

### CODE REVIEW

**Comment by takahser** [comment]
@daywednes thanks for the delivery. I'll look into it shortly.

**Review by takahser — CHANGES_REQUESTED** [review]
Hey @daywednes
I took a look and spinned up your docker infrastructure, only to find out that somebody hijacked the postgres instance and installed some malware on it. Most probably, the attack was possible due to the following:

- [weak passwords](https://github.com/massbitprotocol/w3f-testing-guide/blob/be3c563d93452e76883eeb3d395c1ccc1ad3c63c/docker-compose.yaml#L17-L21) used in the postgres instance
- [publicly exposed ports](https://github.com/massbitprotocol/w3f-testing-guide/blob/be3c563d93452e76883eeb3d395c1ccc1ad3c63c/docker-compose.yaml#L24-L25)

Could you update the credentials to some safer values and also avoid exposing the ports publicly? Alternatively, you can expose it for the container's IP only:

```yaml
networks:
      mbr_test_network:
        ipv4_address: "172.24.24.203"
ports:
    - '172.24.24.203:5432:5432'
```

**Comment by hoanito** [comment]
> Hey @daywednes I took a look and spinned up your docker infrastructure, only to find out that somebody hijacked the postgres instance and installed some malware on it. Most probably, the attack was possible due to the following:
> 
> * [weak passwords](https://github.com/massbitprotocol/w3f-testing-guide/blob/be3c563d93452e76883eeb3d395c1ccc1ad3c63c/docker-compose.yaml#L17-L21) used in the postgres instance
> * [publicly exposed ports](https://github.com/massbitprotocol/w3f-testing-guide/blob/be3c563d93452e76883eeb3d395c1ccc1ad3c63c/docker-compose.yaml#L24-L25)
> 
> Could you update the credentials to some safer values and also avoid exposing the ports publicly? Alternatively, you can expose it for the container's IP only:
> 
> ```yaml
> networks:
>       mbr_test_network:
>         ipv4_address: "172.24.24.203"
> ports:
>     - '172.24.24.203:5432:5432'
> ```

Hey @takahser,

Thanks for taking a look at our grant delivery docs.

For the docker infrastructure, I removed the port mapping for the containers as those are not needed. 

Could you please give us more detail on this " somebody hijacked the postgres instance and installed some malware on it" ? In the docker environment, we are just using the standard postgres image and run a migration script to initialize some databases.

**Comment by hoanito** [comment]
Hello @takahser,

Do you need any more information for the delivery from  Massbit team or it is still in the process of evaluation?

**Comment by takahser** [comment]
@hoanito thanks for fixing it. I sent you an email with some additional contextual information.
I'll get back to you with additional feedback in the next days, I don't need any additional information from your side at this time.

**Comment by hoanito** [comment]
> Hello @takahser,
> 
> Do you need any more information for the delivery from Massbit team or it is still in the process of evaluation?

Thank you so much @takahser

**Comment by takahser** [comment]
@hoanito I currently struggle to access the frontend (http://dapi.massbitroute.net/). I sent you more info via mail as it contains some potentially sensitive information.

**Comment by takahser** [comment]
For completeness: I had a call with @hoanito today to help me sort out the connectivity issues so I can test this delivery (thx @hoanito for your flexibility and time here).
The smoke test was successful and I went on testing the other parts of the delivery independently.
However, the unit tests can't be run on my machine. Also, to increase the reusability of the pallet code, I think it would be nice to add some more inline comments there. For more details, please have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/6f735dc27e3b2e0094d6d693b2ca7ceb9eb55bf4/evaluations/massbit_1_takahser.md).

**Comment by hoanito** [comment]
> For completeness: I had a call with @hoanito today to help me sort out the connectivity issues so I can test this delivery (thx @hoanito for your flexibility and time here). The smoke test was successful and I went on testing the other parts of the delivery independently. However, the unit tests can't be run on my machine. Also, to increase the reusability of the pallet code, I think it would be nice to add some more inline comments there. For more details, please have a look at my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/6f735dc27e3b2e0094d6d693b2ca7ceb9eb55bf4/evaluations/massbit_1_takahser.md).

Thanks for your feedback @takahser . 

Let's schedule another quick call so I can assist you with the unit tests for this delivery 😃

**Comment by takahser** [comment]
@hoanito thx for today's call. As discussed, most of the things are now fixed. The only thing pending are:

- addition of more inline comments within the [Provider Staking Pallet](https://github.com/massbitprotocol/massbitchain/blob/5ef9f9a696ee281ec40b083a194a88dd6d2abc53/pallets/dapi/src/lib.rs)
- making the Core API Tests run reproductively

You can find the updated evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/massbit_1_takahser.md)

**Review by takahser — APPROVED** [review]
@hoanito thanks for the latest changes, everything is fine now.
I accepted the delivery, you can find the updated evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/massbit_1_takahser.md).

**Comment by RouvenP** [comment]
hi @daywednes we transferred the payment today.

**Comment by daywednes** [comment]
@RouvenP let me know when the fund is tranferred. Thank you @RouvenP @takahser @hoanito for making it happen.

**Comment by daywednes** [comment]
I have received the payment - thank you @RouvenP

**Pull request merged**
