### PR TITLE
Fractapp Milestone 1

### PR DESCRIPTION
**Pull request by CryptoBadBoy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for delivering the milestone, we will look into it as soon as possible.

**Comment by Noc2** [comment]
Hi. I’m happy to tell you that the milestone is a pass and will now forward your invoice internally! An external evaluator made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/46/files). Overall I agree with his evaluation. Everything looks really good, but it would be nice to have a little bit more documentation (for example regarding the setup). Also snyk found the following security issues:
```
  ✗ Cross-site Scripting (XSS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-HERMESENGINE-1015406] in hermes-engine@0.5.1
    introduced by react-native@0.63.3 > hermes-engine@0.5.1
  No upgrade or patch available
  ✗ Prototype Pollution [Medium Severity][https://snyk.io/vuln/SNYK-JS-HERMESENGINE-608850] in hermes-engine@0.5.1
    introduced by react-native@0.63.3 > hermes-engine@0.5.1
  This issue was fixed in versions: 0.7.0
  ✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-HERMESENGINE-629268] in hermes-engine@0.5.1
    introduced by react-native@0.63.3 > hermes-engine@0.5.1
  This issue was fixed in versions: 0.7.0
  ✗ Out-of-Bounds [Medium Severity][https://snyk.io/vuln/SNYK-JS-HERMESENGINE-629748] in hermes-engine@0.5.1
    introduced by react-native@0.63.3 > hermes-engine@0.5.1
  This issue was fixed in versions: 0.7.0
  ✗ Denial of Service (DoS) [Medium Severity][https://snyk.io/vuln/SNYK-JS-HERMESENGINE-629766] in hermes-engine@0.5.1
    introduced by react-native@0.63.3 > hermes-engine@0.5.1
  This issue was fixed in versions: 0.7.0
  ✗ Denial of Service [Medium Severity][https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311] in node-fetch@1.7.3
    introduced by react-native-reanimated@1.13.1 > fbjs@1.0.0 > isomorphic-fetch@2.2.1 > node-fetch@1.7.3 and 1 other path(s)
  This issue was fixed in versions: 2.6.1, 3.0.0-beta.9
```

**Comment by CryptoBadBoy** [comment]
@Noc2 @semuelle 
Thank you very much! 

We will be fix it soon

**Comment by Noc2** [comment]
@CryptoBadBoy I just noticed that your invoice doesn’t contain a private address (if you don’t have a company) as well as our company info (Web 3.0 Technologies Foundation, Reiffergässli 46300, Zug, Switzerland, UID / VAT ID: CHE-322.596.347). Could add this information to the invoice and upload it again according to the [invoice form](https://forms.gle/8Wx7nxtq8fKrsuEz8). Thanks!

**Comment by CryptoBadBoy** [comment]
@Noc2 
Thank you! I fixed it

**Comment by Noc2** [comment]
Thanks, I just forwarded your invoice internally.

**Comment by fededubbi** [comment]
Good morning, I noticed that the invoice you sent is in another alphabet, could you please send it to us in a form that we can read it? Many thanks, Federica

**Comment by CryptoBadBoy** [comment]
@fededubbi 
I have an international passport with English text. I will be attach it. But it hasn't my address and individual taxpayer number.
I have documents with address and individual taxpayer number only in Russian. Can I write duplicate this information in English? 
Thank you!

**Comment by fededubbi** [comment]
Hi @CryptoBadBoy, yes this is okay for us. Many thanks.

**Comment by CryptoBadBoy** [comment]
@fededubbi 
Thank you! I sent it

**Comment by CryptoBadBoy** [comment]
Hello

Is my invoice form ok?

**Comment by fededubbi** [comment]
Good morning,

Yes the invoice form is correct.

Many thanks,
regards,

Federica Dubbini

**Comment by CryptoBadBoy** [comment]
@fededubbi, Thank you!

**Comment by RouvenP** [comment]
hi @CryptoBadBoy we just sent a test transaction. Could you please confirm if received?

**Comment by CryptoBadBoy** [comment]
@RouvenP hi, yes

**Comment by CryptoBadBoy** [comment]
@RouvenP Hi
Can you tell me when I will receive the full translation please?

Many thanks

**Comment by RouvenP** [comment]
hi @CryptoBadBoy the transaction is done. apologies for the delay.

**Comment by CryptoBadBoy** [comment]
@RouvenP hi, i received it
@Noc2, @RouvenP @fededubbi Thank you very much!

**Pull request merged**
