### PR TITLE
wasm runtime fuzzing - milestone 3 delivery

### PR DESCRIPTION
**Pull request by pventuzelo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. I’m ooo this week, but I will look into it as soon as possible.

**Comment by pventuzelo** [comment]
OK no prob, Thanks @Noc2

**Comment by Noc2** [comment]
I started to look into it. When I run make test, I get the following error:
``` 
error[E0599]: no associated item named `READ_WRITE` found for struct `region::protect::Protection` in the current scope
   --> /home/noc2/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/60ac091/crates/runtime/src/mmap.rs:185:75
    |
185 |         unsafe { region::protect(ptr.add(start), len, region::Protection::READ_WRITE) }
    |                                                                           ^^^^^^^^^^ associated item not found in `region::protect::Protection`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `wasmtime-runtime`.

``` 
Which rust version are you using?

**Comment by pventuzelo** [comment]
Oh that's strange, I'm using:
``` sh
$ rustc -V
rustc 1.45.0-nightly (5fd2f06e9 2020-05-31)
```

**Comment by pventuzelo** [comment]
@Noc2 Have you succeed to make it work? Are you using a previously cloned repo?

**Comment by Noc2** [comment]
Sorry for the late reply. I’m still getting the error (but only tried updating the rust version to the latest version). But I’m also getting an error when I run “make docker-test-all” (make docker-test works): 

```
   Compiling dynasm v0.5.2
error: failed to run custom build command for `wabt-sys v0.7.1 (https://github.com/pepyakin/wabt-rs#e34c1f7b)`

Caused by:
  process didn't exit successfully: `/warf/workspace/execute_all/target/release/build/wabt-sys-5221c9d985996f9f/build-script-build` (exit code: 101)
``` 
And yes, I’m using a previously cloned repo (obviously updated to the latest commit). I can try to clone a new version.

**Comment by pventuzelo** [comment]
Yes please, try with a fresh clone because I just run the github CI and it's compiling without errors.

**Comment by Noc2** [comment]
Your latest [commit](https://github.com/pventuzelo/wasm_runtimes_fuzzing/commit/43dadb714a31f1156b718b4a4e064f3496990384) resolved my problems. Everything works now. In general, great work and thanks for all extra work. Your milestone is a pass and I will forward your invoice internally. You can find my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/wasm-runtimes-fuzzing_3_Noc2.md).

**Comment by pventuzelo** [comment]
Awesome, Thanks @Noc2

**Pull request merged**
