### PR TITLE
add Epirus Substrate Phase 2 -Milestone 2 delivery

### PR DESCRIPTION
**Pull request by conor10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1159.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @conor10, thanks for the delivery! I'm starting the evaluation soon, and I'll reach out if I need your help.

**Review by 0xCaso — COMMENTED** [review]
I was following the [tutorial](https://github.com/web3labs/ink-verifier-server/blob/main/docs/TUTORIAL.md) for the contracts verification, but in the scenario 1 (S1) I get the error
```
[+] Building 0.0s (1/2)
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 2B                                                                                                                       0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount105346809/Dockerfile: no such file or directory
```
if I run the command
```
docker build . -t ink-verifier:develop
```
Do you have idea of what's happening?

**Comment by XY-Wang** [comment]
Hi @0xCaso,

May I know what OS you're using?

From what I've found online, it seems that the issue could be related to this: https://github.com/docker/buildx/issues/426#issuecomment-723208580

Could you please try

```
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```

in your terminal and try the build again?

The other possibility is one of the issues mentioned here: https://github.com/docker/for-win/issues/8781
Please make sure you are running the build command from the root directory of the `ink-verifier-image`  project. If you were running in VS Code, please try exiting VS Code and run from terminal.

**Comment by 0xCaso** [comment]
Thanks a lot, in the end I managed to build the image, but I'm having problem running it. I'm using a Mac M1 (unfortunately we cannot use our test server at the moment, which runs Ubuntu).

I run the command
```
build-verifiable-ink -t develop .
```
and I get
```
   Compiling contract-transcode v2.0.0-alpha.4 (/usr/local/cargo/git/checkouts/cargo-contract-0e593efc9d3a70d5/e2e804b/crates/transcode)
   Compiling wasm-opt v0.110.1
    Finished release [optimized] target(s) in 10m 38s
  Installing /usr/local/cargo/bin/cargo-contract
   Installed package `cargo-contract v2.0.0-alpha.4 (https://github.com/paritytech/cargo-contract?rev=e2e804be3bab2a987f0441fb8025a5a82da1c10e#e2e804be)` (executable `cargo-contract`)
SRC_ROOT=/build/package/src
BUILD_PARAMS= --release --optimization-passes Z
cargo-contract-contract 2.0.0-alpha.4-e2e804b-aarch64-unknown-linux-gnu
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```
This should be a problem related to the Mac M1 (or Mac in general), so I rebuilt the image with
```
docker build --platform linux/x86_64 . -t ink-verifier:develop
```
And if I retry to run the image I get this
```
info: installing component 'rust-std'
 30.0 MiB /  30.0 MiB (100 %)   4.8 MiB/s in  6s ETA:  0s
info: installing component 'rustc'
 67.4 MiB /  67.4 MiB (100 %)   6.1 MiB/s in 10s ETA:  0s

  1.66.1-x86_64-unknown-linux-gnu installed - rustc 1.66.1 (90743e729 2023-01-10)

info: checking for self-updates
info: downloading self-update
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
 19.0 MiB /  19.0 MiB (100 %)   5.0 MiB/s in  3s ETA:  0s
info: downloading component 'rust-src'
info: installing component 'rust-src'
    Updating git repository `https://github.com/paritytech/cargo-contract`
  Installing cargo-contract v2.0.0-alpha.4 (https://github.com/paritytech/cargo-contract?rev=e2e804be3bab2a987f0441fb8025a5a82da1c10e#e2e804be)
    Updating crates.io index
/usr/local/bin/build-contract: line 49:    71 Killed                  cargo install --git https://github.com/paritytech/cargo-contract --locked --rev e2e804be3bab2a987f0441fb8025a5a82da1c10e --force
```

**Comment by XY-Wang** [comment]
Hmm... Could you try `docker build --platform=linux/amd64 . -t ink-verifier:develop` instead?

**Comment by mfornos** [comment]
hi @0xCaso

Seems that the container is running out of resources, with the emulation to run amd64, and is being killed because of it.

Maybe increasing the resource limits of Docker helps?


---
PS: unfortunately we don't have access to an arm64 machine to try a proper build for that architecture.

**Review by 0xCaso — COMMENTED** [review]
Here I am, sorry for the big delay.

I'm following the [tutorial](https://github.com/web3labs/ink-verifier-server/blob/main/docs/TUTORIAL.md) for the verification. I should have followed correctly all the steps till where I have to verify the uploaded smart contract ([here](https://github.com/web3labs/ink-verifier-server/blob/main/docs/TUTORIAL.md#uploading-to-the-network)). 

When I go to "Source Code" in order to upload the package.zip and press "Verify Source Code", I get an error:

Screenshot 2023-02-23 at 14 55 09

**Comment by XY-Wang** [comment]
Hi @0xCaso,

It seems that the error is due to the browser not being able to connect to the `ink-verifier-server`.

I assume that you're running the verifier server in your remote VM with the command `SERVER_HOST=0.0.0.0 npm start`? Is the port 3001 open? You can verify this by going to `https://[REMOTE_HOST_IP]:3001/api-docs/` in your browser and it should show the Swagger API docs. You will also need to configure the environment of the explorer UI to point to the corresponding endpoints.

e.g. In the [docker compose file](https://github.com/web3labs/epirus-substrate/blob/main/local-testnet/docker-compose.explorer-ui.yml) 
```
environment:
      - REACT_APP_SQUID_ENDPOINT=https://[REMOTE_HOST_IP]:4000/graphql
      - REACT_APP_SOURCE_CODE_ENABLED=true
      - REACT_APP_VERIFIER_ENDPOINT=https://[REMOTE_HOST_IP]:3001
      - REACT_APP_VERIFIER_WS_ENDPOINT=wss://[REMOTE_HOST_IP]:3001
```

Please let us know if this is the issue :smile:

**Comment by 0xCaso** [comment]
Thanks a lot, obviously I forgot to open the `3001`, my fault! I'll update you when I finish with the evaluation.

**Review by 0xCaso — APPROVED** [review]
I'm approving the delivery, thanks for the help!

I don't have particular suggestions, I'd just put somewhere an icon that shows the smart contract is verified (so one can see it without entering in the https://substrate.sirato.xyz/codes/... page), if you think that could be useful.

**Comment by XY-Wang** [comment]
Thanks a lot @0xCaso! And thanks for the suggestion, it's something that we are planning to do.

**Comment by 0xCaso** [comment]
Congrats for the grant's completion! I've just forwarded internally the invoice, the payment should happen within 14 days.

**Pull request merged**
