### PR TITLE
Societal SaaS Pricing Grant

### PR DESCRIPTION
**Pull request by gfox1**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1671

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@gfox1 thank you for the [milestone delivery](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal_grant_3_3_dsm-w3f.md). Please see the evaluation document and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by okalenyk** [comment]
> @gfox1 thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal_grant_3_3_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

@dsm-w3f thanks for the evaluation! Here is short update on the evaluation:

### Unit tests

- fixed

### Manual Test

- fixed `chain spec|genesis|wasm` in `examples` folder that are used for the docker parachain launch.
- fixed references to Readme section for rococo local run

P.S. We got rid of the solo chain runtime configuration completely and became a parachain so the old launch configuration doesn't work anymore. Now we have to run our own rococo local testnet to test our parachain locally.

Please let us know if you have any questions.

**Comment by dsm-w3f** [comment]
@okalenyk thank you for the improvements and fixes. I checked again and now it works well. Just one point that needs to be fixed is the documentation, which still includes outdated instructions to run the system. Please see the details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal_grant_3_3_dsm-w3f.md). Let me know when I can check it again to finish this evaluation.

**Comment by okalenyk** [comment]
> @okalenyk thank you for the improvements and fixes. I checked again and now it works well. Just one point that needs to be fixed is the documentation, which still includes outdated instructions to run the system. Please see the details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/societal_grant_3_3_dsm-w3f.md). Let me know when I can check it again to finish this evaluation.

@dsm-w3f I've removed legacy single node launch configuration and updated references in the documentation. Should be good now.

**Comment by dsm-w3f** [comment]
@okalenyk thank you for the improvements. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Pull request merged**
