### PR TITLE
NewOmega M2

### PR DESCRIPTION
**Pull request by celrisen**
# Milestone Delivery Checklist

- [X] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [X] This pull request is being made by the same account as the accepted application. 
- [X] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @celrisen. We'll look into it as soon as possible.

**Comment by semuelle** [comment]
Sorry @celrisen, I pushed to the wrong repo.

**Comment by celrisen** [comment]
> Sorry @celrisen, I pushed to the wrong repo.

No worries :)

**Comment by semuelle** [comment]
Hey @celrisen, sorry for the delay in the evaluation of your delivery. I am now working through it. 

I noticed that there are several references to local folders in the client code, could you check those? I suspect they are causing the issues I've been having.

`"testRunner": "/Users/wiktor/projects/newomega-substrate/newomega_client/node_modules/jest-circus/runner.js",`
```
return isDelegator
   ? `/Users/wiktor/projects/newomega-substrate/newomega_client/src/ink/${contract}.wasm`
   : `/Users/wiktor/projects/newomega-substrate/newomega_client/src/ink/${contract}/${contract}.wasm`;
```

**Comment by celrisen** [comment]
Hey @semuelle, no problem at all about the delay.

I've pushed the test runner package.json update to the repo (commit ```d8e56657ec75e6c21cb8244e02449b836a36c42d```), so that should fix the test runner.

I'll have a look at the Deployer, however as I wrote in the documentation, I stopped using it some time ago due to breaking changes around deploying contracts on the canvas nodes, and the polkadot.js support for them, and I recommend deploying them manually. 

I will check if now the script based deployment works with latest polkadot.js / canvas though, as there was/is rapid development around the area and hopefully it works now.

**Comment by celrisen** [comment]
Hi @semuelle, 

Sorry it took some time but unfortunately the documented ways of deploying contracts in polkadot.js do not work at all, so I had to pretty much dissect the library itself, and came up with a solution. I hope this is the right approach (I dont know since the documentation doesnt mention it at all), and it does work in my setup (I'm running it against canvas-node v0.1.6).

I pushed the ```98a8dbb88ff0cf662fafd794f5d5ddb20cee701c``` commit (```origin/grant-milestone-m2```) which adapts the Deployer and wires it up to tests. To use the deployed contract (during tests) to run the game, just note down its address (its being printed by console log) and pass it to ```npm genconfig``` (a little script I made which updates the game client contract address config). 

Let me know if everything works for you or anything's unclear.

**Comment by semuelle** [comment]
Thanks for the extra work, @celrisen. I did have trouble deploying all the contracts, though I'm not quite sure what the issue was. I'll try this out on Monday.

**Comment by celrisen** [comment]
No worries @semuelle, honestly I'm glad I got it to work. Would be really nice to update the polkadot.js docs asap or even rework the portal completely, so that we dont get people discouraged too quickly... And for what it's worth, the new proposed technique for contract instantiation works and looks really nice, once you figure out how to use it :)

**Comment by semuelle** [comment]
Thanks for following up on the deployer, @celrisen. I just pushed my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/1b5fe14661b93d6c3108ddd5a51a9bf66b1bebae/evaluations/newomega_2_semuelle.md) and your milestone is hereby accepted. :tada: 

Keep up the good work.

I will forward your invoice for processing.

**Comment by RouvenP** [comment]
hi @celrisen we transferred the payment for milestone 2.

**Pull request merged**
