### PR TITLE
added tellor_milestone_1.md

### PR DESCRIPTION
**Pull request by brendaloya**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ x] This pull request is being made by the same account as the accepted application.
- [x ] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1532

### CODE REVIEW

**Comment by brendaloya** [comment]
Hello, can someone help me out with the author check? It's failing but I submitted the application and the milestone update by forking the w3f repos into tellor-io.

**Comment by dsm-w3f** [comment]
@brendaloya thank you for the milestone delivery. Don't worry, this is probably because there are two committers in the application document. You don't need to take any action. We will evaluate the milestone delivery soon.

**Comment by brendaloya** [comment]
@dsm-w3f Thank you for taking the time to review this. I've added notes below based on the evaluation notes. 

| Number | Deliverable | Evaluation Notes | Notes |
| ------------- | ------------- | ------------- |------------- |
| **0c.** | Testing and Testing Guide | Automated unit tests. Some problems to check the coverage. | We are working on correcting the inaccurate coverage report since we do have tests for each function. We have opened an issue on foundry here: https://github.com/foundry-rs/foundry/issues/4876 . |
| **0c.**  | Code Quality | Warnings on test files | Resolved the test/coverage warnings here: https://github.com/tellor-io/tellor-parachain-contracts/pull/87 |
| **0d.** | Docker | The tests fail | We inadvertently ignored some files on the push but have fixed the docker setup here: https://github.com/tellor-io/tellor-parachain-contracts/pull/85 |

Testing for the Tellor pallet and integration of the two parts are wrapping up. Would it be possible to arrange a meeting about the tutorial? Just to get clarity on the expectation. 

Also, let me know if I should update the commit to PR 87 while we continue to work with Foundry on the issue.

**Comment by dsm-w3f** [comment]
@brendaloya thank you for the improvements and fixes. The problems with this milestone delivery are solved and the milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job! 

Regarding the tutorial, usually we perform manual or automated system tests to validate it. As Milestone 2 covers "complete documentation with usage examples", there should be enough material in the next delivery for us to test the system from a perspective of a user. Usually, we ask the grantees to produce a test plan in a format of a tutorial, with inputs and expected outputs for the main flow of the system. We can execute the test plan manually or you can provide automated E2E tests to show that the system is working. Here is an [example from other grant](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/testing.md). If you need further explanations on that I'll be happy to schedule a call with you.

**Comment by RouvenP** [comment]
hi @brendaloya we transferred the payment today.

**Pull request merged**
