### PR TITLE
MangoSale_Milestone_1

### PR DESCRIPTION
**Pull request by Mangoboxlabs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1400 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by takahser** [comment]
Hi @Mangoboxlabs 
Thanks for the delivery, one of our grant evaluators will take a look and provide you with feedback soon.

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by Mangoboxlabs** [comment]
@dsm-w3f  Thank you. We have received the evaluation document and will check it carefully.

**Comment by Mangoboxlabs** [comment]
@dsm-w3f I found that you failed to deploy the contract. Did you deploy it by uploading the``.contract`` file? I need to know your detailed operation. In addition, the deployment contract does not need to enter any parameters. You can directly upload the ``.contract`` file. We have solved the remaining problems. You need to update the code before continuing. Thank you for your review.

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the answer. Yes, the deployment was performed by uploading the .contract file.

**Comment by dsm-w3f** [comment]
@Mangoboxlabs I'm trying both local and remote nodes. The version of the cargo contract is cargo-contract 0.15.0-unknown-x86_64-linux-gnu. I was able to bypass the contract compilation problem but now I'm having an execution one. See the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by Mangoboxlabs** [comment]
@dsm-w3f Thank you for your reply. With regard to the front-end npm problem, we have updated the code. You only need to update the code and run it again. With regard to the e2e test, we have updated the tutorial. You can follow our tutorial. With regard to the compilation contract, through consulting the data, it is found that your rust version is incompatible with the code. You can add -- optimization classes=0 to compile. It is recommended that you create a completely new rust environment to compile. Follow our tutorial, and there will be no errors. Your error in application appears to be calling token_factory, the first error may be that you did not send gas to the token_factory contract.The second error of sending gas in the factory contract is because version is a random number. It is recommended that you fill in the current timestamp. For the configuration of ipfs, you need to get the config from[ pinata](https://app.pinata.cloud/).

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the improvements and fixes. The evaluation is almost finished. There are only a few documentation fixes and improvements. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangosale_1_dsm-w3f.md). Let me know when I can check them.

**Comment by Mangoboxlabs** [comment]
@dsm-w3f Thank you for your reply. We have solved the problem.

**Comment by RouvenP** [comment]
hi @Mangoboxlabs we transferred the payment today.

**Pull request merged**
