### PR TITLE
ZK Rollups Pallet Milestone1

### PR DESCRIPTION
**Pull request by SotaWatanabe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
@SotaWatanabe At the moment the `test` container is failing to resolve some dependencies, see the output:
```
test         | Prover is working
yarn run v1.22.5
$ mocha -r ts-node/register 'tests/**/test-integration.ts'
test         |
test         | TSError: ⨯ Unable to compile TypeScript:
test         | tests/zksync/src/transport.ts:1:19 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.
test         |
test         | 1 import Axios from 'axios';
test         |                     ~~~~~~~
test         | tests/zksync/src/transport.ts:2:38 - error TS2307: Cannot find module 'websocket-as-promised' or its corresponding type declarations.
test         |
test         | 2 import WebSocketAsPromised = require('websocket-as-promised');
```
It seems that both `axios` and `websocket-as-promised` are part of the `package.json` dependency list, so I'm not sure why it's not working. Since I'm not an expert on mocha and how it handles packages, I kindly ask for support on this issue.

**Comment by mmagician** [comment]
Below you'll find further comments from the codebase evaluation:

---
`ts-tests` sub-directory is largely copied & restructured from [matter-labs/zksync](https://github.com/matter-labs/zksync/tree/1cda8c7c1a9bfbec6491a1e4634b0fc33b206834/core/tests/ts-tests/tests) & no references nor acknowledgements are provided as far as I could see.

Additionally, the since the zksync repo (a fork thereof) is already a submodule and contains the exact same files (or is there a difference?), why duplicate it into a separate top level ts-tests?

---
Regarding the concrete milestone 1 deliverables: 
> Integration Test On Substrate | Test for all contracts and sidechain network actors

other than `setup-wallet/contract-test.ts` & the tests from matter-labs/zksync, are there any other original tests provided?

**Comment by NoCtrlZ** [comment]
> @SotaWatanabe At the moment the `test` container is failing to resolve some dependencies, see the output:
> 
> ```
> test         | Prover is working
> yarn run v1.22.5
> $ mocha -r ts-node/register 'tests/**/test-integration.ts'
> test         |
> test         | TSError: ⨯ Unable to compile TypeScript:
> test         | tests/zksync/src/transport.ts:1:19 - error TS2307: Cannot find module 'axios' or its corresponding type declarations.
> test         |
> test         | 1 import Axios from 'axios';
> test         |                     ~~~~~~~
> test         | tests/zksync/src/transport.ts:2:38 - error TS2307: Cannot find module 'websocket-as-promised' or its corresponding type declarations.
> test         |
> test         | 2 import WebSocketAsPromised = require('websocket-as-promised');
> ```
> 
> It seems that both `axios` and `websocket-as-promised` are part of the `package.json` dependency list, so I'm not sure why it's not working. Since I'm not an expert on mocha and how it handles packages, I kindly ask for support on this issue.

In my environment, it didn't happen so I'll check whether this error happens on Github Actions.

> ts-tests sub-directory is largely copied & restructured from matter-labs/zksync & no references nor acknowledgements are provided as far as I could see.

Thank you for the detailed review.
I copied a lot of parts from [`matter-labs/zksync/sdk/zksync.js`](https://github.com/matter-labs/zksync/tree/master/sdk/zksync.js), not whole `matter-labs/zksync`.
The reason why I copy `matter-labs/zksync/sdk/zksync.js` is to import some modules needed for the integration test for example [zksync provider](https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/tester.ts#L3), [zksync wallet](https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/test-integration.ts#L7) and so on.
The reason I modified was it didn't work by just importing as a reference so I customized some modules.
In particular, I modified the following modules mainly.
- [getDefaultProvider](https://github.com/ArtreeTechnologies/zksync/blob/48d46b19b68794b47f657d2c53d8a07ac610e86d/sdk/zksync.js/src/provider.ts#L19)
I modified it in order to use the operator network.
https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/zksync/src/provider.ts#L44
- [etherTransaction](https://github.com/ArtreeTechnologies/zksync/blob/48d46b19b68794b47f657d2c53d8a07ac610e86d/sdk/zksync.js/src/wallet.ts#L593)
I modified the way to get etherTransaction because frontier can't use socket to get transaction hash so I changed the code getting etherTransaction after finalizing block and getting transaction using transaction hash.
In order to change the above, I changed the way to initialize the contract instance [ethersjs](https://github.com/ArtreeTechnologies/zksync/blob/48d46b19b68794b47f657d2c53d8a07ac610e86d/sdk/zksync.js/src/wallet.ts#L583) to [web3](https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/zksync/src/wallet.ts#L585).
- [fundedWallet](https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/tester.ts#L46)
I modified the way to transfer ether because etherjs socket can't use on frontier.
I changed [ethersjs handle wait](https://github.com/ArtreeTechnologies/zksync/blob/48d46b19b68794b47f657d2c53d8a07ac610e86d/core/tests/ts-tests/tests/tester.ts#L54) to [web3 transaction and finalize manually](https://github.com/PlasmNetwork/ZKRollups/blob/master/ts-tests/tests/tester.ts#L54).

> other than setup-wallet/contract-test.ts & the tests from matter-labs/zksync, are there any other original tests provided?

I did an integration test as same as matter-labs do.
The `matter-labs` tests all components with `zk test i server` command.
https://github.com/matter-labs/zksync/blob/master/docs/development.md#testing
The command link workspace [ts-tests](https://github.com/matter-labs/zksync/blob/master/infrastructure/zk/src/test/integration.ts#L114) and executes [`zksync/core/tests/ts-tests/tests/main.test.ts`](https://github.com/matter-labs/zksync/blob/master/core/tests/ts-tests/tests/main.test.ts).
They provide only `zksync/core/tests/ts-tests/tests/main.test.ts` for integration test.

Sorry for writing such a long message😘
Please confirm.
Thank you!

**Comment by NoCtrlZ** [comment]
Hi @mmagician .

> At the moment the test container is failing to resolve some dependencies, see the output:
I did an integration test on Github Actions and the same error happened.
Thank you for letting me know.
And I fixed that issue and Github Actions worked correctly at the latest change.
https://github.com/PlasmNetwork/ZKRollups/runs/1909749575

Please confirm.
Thank you!

**Comment by mmagician** [comment]
I can see your integration test passing. Just after a quick look I see that you've changed the startup process slightly - could you please also update the docs / READMEs accordingly?

**Comment by NoCtrlZ** [comment]
> I can see your integration test passing. Just after a quick look I see that you've changed the startup process slightly - could you please also update the docs / READMEs accordingly?

Thank you for your check.
I changed some code but it's mainly for Github Actions so we can check locally with the same command.

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
Is there any point I need to fix?

**Comment by mmagician** [comment]
@NoCtrlZ apologies for the delay. So far so good, but I would still like to test a couple more things. Please allow a couple of extra days for the review. Thanks!

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
Is everything going well?

**Comment by SotaWatanabe** [comment]
Thank you  @NoCtrlZ for the update. 

Hello Web3 Foundation team, @mmagician, if you need it, we are more than happy to set up a call and explain how it works and show you a demo so that you can understand the status and technical architecture. ZK Rollups is obviously new and not easy to understand. I hope this may help you understand what we have done on Substrate.

**Comment by semuelle** [comment]
Hi @SotaWatanabe & @NoCtrlZ,
thanks for the message and sorry for the slow response. The W3F grants program is very popular these days and we are working hard to keep up with evaluations. I'm sure we will be able to dig further into your delivery this coming week. 

If there is further need for a demo or setup instructions, we will communicate that here.

**Comment by NoCtrlZ** [comment]
Thank you for the answer!
Please take your time.

**Comment by mmagician** [comment]
Apologies for the delay in reviewing your code.

The only problem I see with accepting this milestone is code attribution, namely what I mentioned earlier about largely copying the `ts-tests` directory.
I wonder, since you are already [forking the zksync repo](https://github.com/ArtreeTechnologies/zksync), why not modify the `ts-tests` there, and use these for your integration tests? This way:
1. It is clear that you didn't write all the tests yourself and everyone can easily do a diff between your fork and the original
2. You avoid code duplication, as right now you have a zksync submodule + an extra `ts-tests` directory in root.

Lastly, adding the defaultProvider `operator` is very docker-specific, as this is bound to work for your setup only, where the zkSync server container is called `operator`. I wonder if you could re-work the network setup of your containers? I would suggest exploring the concept of [host networking in docker](https://docs.docker.com/network/host/) - I think this way you can avoid setup-specific changes to the codebase and instead limit the changes to your docker files.

**Comment by NoCtrlZ** [comment]
Hi @mmagician.
Thank you for the review!
I changed the structure according to your review.

> It is clear that you didn't write all the tests yourself and everyone can easily do a diff between your fork and the original
You avoid code duplication, as right now you have a zksync submodule + an extra ts-tests directory in root.

I merged [zksync](https://github.com/PlasmNetwork/ZKRollups/tree/master/test/src) to one to avoid duplication and it's referred by the operator and test containers.

> Lastly, adding the defaultProvider operator is very docker-specific, as this is bound to work for your setup only, where the zkSync server container is called operator

I fixed this problem and there are no docker-specific  [defaultProvider](https://github.com/ArtreeTechnologies/zksync/blob/65f83998aba33cd0f4aaae50f2b437970d481837/sdk/zksync.js/src/provider.ts#L19).

I modified the documentation accordingly and made the github actions test pass.
https://github.com/PlasmNetwork/ZKRollups/runs/2111077264

Please confirm🚀

**Comment by mmagician** [comment]
@NoCtrlZ Thanks for the updates. I'll let you know once I've reviewed your changes

**Comment by mmagician** [comment]
The structure looks much better now, thank you!
Now sure whether it's because of the changes you introduced, but now I'm getting the following error when executing the tests:
```
test         |        "before all" hook: create tester and test wallets for "should execute an auto-approved deposit":
test         |      Error: connect ECONNREFUSED 172.21.0.5:3030
```
Let me know if you are able to reproduce that?

**Comment by NoCtrlZ** [comment]
Hi @mmagician.
Thank you for the review.
It seemed like I forgot to remove debug operation.
I fixed and it works now.
Please confirm!

**Comment by mmagician** [comment]
@NoCtrlZ I just pulled & updated submodules, but I'm still seeing the same error.

**Comment by NoCtrlZ** [comment]
@mmagician 
I think it will work after you execute `$ docker-compose rm`.
If it doesn't work, please give me the full log.
In my environment, it worked without any cache.
Thank you!

**Comment by mmagician** [comment]
It worked! I can already tell you that the first milestone is accepted, congrats! I'll submit an official evaluation PR soon.

**Comment by NoCtrlZ** [comment]
@mmagician 
Thank you so much!

**Comment by mmagician** [comment]
@SotaWatanabe @NoCtrlZ Please find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/120)

**Comment by mmagician** [comment]
@SotaWatanabe @NoCtrlZ We noticed that the invoice you submitted contains a different payment address than the original contract.
As you'll find in our application template:
`The combination of your GitHub account submitting the application and the payment address above will be your unique identifier during the program. Please keep them safe.`
If you want to change your payment address, we would require you to amend the original contract via a PR.

**Comment by SotaWatanabe** [comment]
Hello Marcin,

Thank you very much for notifying us. I will review it as soon as possible
and get it back to you. Thank you.

2021年3月22日(月) 22:06 Marcin ***@***.***>:

**Comment by SotaWatanabe** [comment]
@mmagician Sorry for the delay. Recently, we moved our HQ from Japan to Singapore and now this grant is operated by the Singapore entity. This is why we have 2 different bitcoin address. I will create the  PR and send it to you shortly. Sorry for the inconvenience.

**Comment by SotaWatanabe** [comment]
I just amend our bitcoin address via a PR. Please check it when you have time. Thank you.
https://github.com/w3f/Open-Grants-Program/pull/330#issue-598933448

**Pull request merged**
