### PR TITLE
Create vera_defi_phase_1.md

### PR DESCRIPTION
**Pull request by arbach**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Grants-Program/pull/281

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @arbach. We'll look into it as soon as possible.

**Comment by Noc2** [comment]
Thanks again for the delivery. I quickly [started to look into it](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/vera_1_Noc2.md) and have a few questions/comments:
- The license file seems to be missing in your repo. Could you please add it? 
- The UI repo doesn’t seem to be public https://github.com/veradefi/ambrosia
- For the article, you only linked to the docs. Are you still planning to write an article and to share it with grantspr@web3.foundation? 
- Most of the figma design pages seems to be unrelated to the wireframe https://balsamiq.cloud/sa6mpd1/pvn6rks/r5D27  (for example: https://www.figma.com/proto/ien0b4twQ5nygfCy7AYokO/Vera-Real-Estate?node-id=223%3A0&scaling=min-zoom&page-id=218%3A0) and none of the show polkadot.js. Obviously if the UI is already ready and implemented this might no longer be necessary.

**Comment by arbach** [comment]
@Noc2 

- License fixed.
- Public now.
- Can we hold on this ? we are still figure out our marketing strategy with changing market condition. 
- Yes. Sorry there is a mixed with figma looks like. This is the actual [figma](https://www.figma.com/file/oZOJk9ujxFZ4Ip1To7mWDP/Vera-web-app-UI_v1?node-id=0%3A1).   the UI is ready and fully functional at http://beta.vera.financial/    here is a recording of the flow in dev version in the new UI  https://drive.google.com/file/d/16sUVt-wvYdWAUsfupGVtnzWDOvYAbio6/view

**Comment by Noc2** [comment]
Thanks for the quick reply and for open sourcing the UI. I have a few additional/follow-up questions: 

- It seems you only added the license file to the [ambrosia repo](https://github.com/veradefi/ambrosia). The [defi repo](https://github.com/veradefi/defi) still has no license file. 
- Regarding the article: It’s not mandatory to publish this via grantspr. I just thought you might be interested in doing so. 
- I’m unable to compile your smart contract at the moment, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/vera_1_Noc2.md). In order to get to this stage, I first had to update the cargo.toml files, [see](https://github.com/veradefi/defi/pull/1).

**Comment by arbach** [comment]
- License added
- We are interested but not now. Maybe in the future if that possible. 
- We have added build.sh that will build all contracts in [defi](https://github.com/veradefi/defi) it was tested on ubuntu.

**Comment by Noc2** [comment]
Thanks for the update and sorry for the late reply. Could you also update the readme to mention  build.sh? Additionally the tests need to be run with [cargo +nightly test](https://github.com/veradefi/defi/pulls). It would also be great if you could clean up the code (e.g. remove unused variables) and add additional unit tests (e.g. ExchangeManager currently has no unit tests). Regardless, I’m happy to tell you that the milestone is a pass. I will forward your invoice internally.

**Comment by Noc2** [comment]
@arbach did you already upload the invoice? I could not find it. See https://docs.google.com/forms/d/e/1FAIpQLSdSqj2vYjvpiIytkjcc40Pwl0Eg76WGUAq5L9e8eFuuOegmLw/viewform

**Comment by arbach** [comment]
@Noc2  I am pretty sure I did from the same email associated with this github account. I sent the form again now with the invoice.

**Comment by Noc2** [comment]
Thanks. This time we received it.

**Pull request merged**
