### PR TITLE
hamster milestone 2 delivery

### PR DESCRIPTION
**Pull request by ltmuyuan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/789

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @ltmuyuan. We will look into it as soon as possible. We currently have a bit of a backlog, so it might take a few more days.

**Comment by semuelle** [comment]
Hi @ltmuyuan. Thank you for your patience. 

I have reviewed your milestone. Everything seems to work well, and, as I mentioned in my first evaluation, it is well documented and relatively easy to set up. I have two requests:

1. You have submitted the same repo for "Documentation", "Testing Guide" and "Article". While the repo does contain documentation how to set up and use the system, as "Article" we expect more of a high-level description of what was done as part of the grant. Most grantees publish an announcement on Medium or Subsocial. It can be on Github as well, but I would like to ask for a separate document that a less technically minded audience might understand.
2. The `gateway` pallet includes a single unit test. I see that the `register_gateway_node` is not complex, but you could for example check if `peerIds` has changed, depending on whether it was registered before. Also, `heartbeat` is not tested at all.

**Comment by jian-guo-s** [comment]
Hi @semuelle.Thank you for your reply and patience.
We have modified your request:
1. We have added a new gateway test. Please check the latest [pull](https://github.com/hamster-shared/hamster/pull/11)
2. We revised the article in the second milestone of hammerer and wrote a separate document according to your requirements. Please check it.

**Comment by ltmuyuan** [comment]
Thank you @semuelle . I have submitted our invoice, thanks to the Foundation for giving us the grant.

**Comment by RouvenP** [comment]
hi @ltmuyuan, we transferred the payment today. Thanks!

**Pull request merged**
