### PR TITLE
Tuxedo milestone 1

### PR DESCRIPTION
**Pull request by JoshOrndorff**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/blob/master/applications/tuxedo.md

### CODE REVIEW

**Comment by takahser** [comment]
Hi @JoshOrndorff  
Thanks for the delivery, I will take a look and provide you with feedback soon.

**Comment by JoshOrndorff** [comment]
Any update on this? How long does it typically take to get the submission reviewed?

**Comment by takahser** [comment]
@JoshOrndorff it takes up to 14 days, but I'll try to give you feedback as soon as I can. We recently had a bulk of new incoming deliveries, so please bear with us :)

**Review by takahser — CHANGES_REQUESTED** [review]
@JoshOrndorff sorry for the delay here, you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/1dda069fcaef1c4ca0182a12206c69a122e3bf30/evaluations/tuxedo_1_takahser.md). Feel free to have a look and ask questions, if you need further information.

**Comment by JoshOrndorff** [comment]
@takahser Thanks for taking a look. I really appreciate it.

> the alledged genesis utxo for `coin000000000000000000000000000000000000000000000000000000000000000000000000` doesn't exist

I'm sorry there was a small typo in the command in the readme. The readme is now updated.
```sh
# Incorrect command that you ran with missing space
./target/release/tuxedo-template-wallet verify-coin000000000000000000000000000000000000000000000000000000000000000000000000

# Correct command with space inserted. (Rea
./target/release/tuxedo-template-wallet verify-coin 000000000000000000000000000000000000000000000000000000000000000000000000
```

> clippy shows some warnings

I cannot reproduce these warnings locally nor in CI. You can see that our CI runs clippy on each commit and is set to fail if there are any warnings. Here is the latest passing run with no warnings https://github.com/Off-Narrative-Labs/Tuxedo/actions/runs/4409652419/jobs/7726203651

**Comment by JoshOrndorff** [comment]
@takahser Any chance you can take another look at this. I'm sorry the missing space character in the command got you stuck. The readme is updated now.

**Comment by takahser** [comment]
@JoshOrndorff yes don't worry, I'm working on it. You'll hear back soon :)

**Comment by takahser** [comment]
@JoshOrndorff I updated [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/1dda069fcaef1c4ca0182a12206c69a122e3bf30/evaluations/tuxedo_1_takahser.md). All previously mentioned issues are resolved. However, something that confused me was that the utxo's seem to be spent on txs that are controlled by the same account. So my question would be if I can somehow spend some of "my" utxo's to somebody elses' account, similarly to [P2PKH](https://river.com/learn/terms/p/p2pkh/) or [P2WPKH](https://river.com/learn/terms/p/p2wpkh/) in Bitcoin?

**Comment by JoshOrndorff** [comment]
@takahser Thanks for taking another look. I believe you included an outdated link that actually points to your original evaluation. I believe this is your [updated evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/f14c0b2b5a233907b1d5f17c3fb66e48eaeebb94/evaluations/tuxedo_1_takahser.md).

Your observation about the **example commands** from the readme is correct. All of those commands create new UTXOs that are owned by the same example address. I just chose those example commands to keep the readme relatively concise. However, the wallet supports sending coins to and from different addresses.

There was a small bug at the time of the `milestone-1` tag that ignored the recipient address, but it has since [been fixed](https://github.com/Off-Narrative-Labs/Tuxedo/pull/44/commits/ec1ea6cede73b5616ef9f0c17c97c0208b2d058f). I've pushed a new tag in case you want to explore this functionality for yourself. A guided walkthrough follows, although please remember, full wallet functionality comes in milestone 2, and a full tutorial comes in milestone 3.

```sh
$ # First read the help page to learn about all CLI flags, even the ones not mentioned directly in the README.
$ docker run --network host ghcr.io/off-narrative-labs/tuxedo-wallet:milestone-1-recipient-patch spend-coins --help
Spend some coins.

For now, all inputs must be owned by the same signer, and all outputs go to the same recipient.

Usage: tuxedo-template-wallet spend-coins [OPTIONS]

Options:
  -s, --seed <SEED>
          The seed phrase of the coin owner who will sign the inputs. For now, all inputs must be owned by the same signer
          
          [default: "news slush supreme milk chapter athlete soap sausage put clutch what kitten"]

  -i, --input <INPUT>
          An input to be consumed by this transaction. This argument may be specified multiple times. They must all be coins and, for now, must all be owned by the same signer

  -r, --recipient <RECIPIENT>
          Hex encoded address (sr25519 pubkey) of the recipient (non 0x prefixed for now) Generate with subkey, or use Shawn's: d2bf4b844dfefd6772a8843e669f943408966a977e3ae2af1dd78e0f55f4df67
          
          [default: d2bf4b844dfefd6772a8843e669f943408966a977e3ae2af1dd78e0f55f4df67]

  -o, --output-amount <OUTPUT_AMOUNT>
          An output amount. For the transaction to be valid, the outputs must add up to less than the sum of the inputs. The wallet will not enforce this and will gladly send an invalid transaction which will then e rejected by the node

  -h, --help
          Print help (see a summary with '-h')

          
$ # Now use subkey to generate another example account. Let's call her Karl.
$ docker run parity/subkey generate
Secret phrase:       disagree bridge nuclear paper usage spirit switch guard exist fix error share
  Network ID:        substrate
  Secret seed:       0x0f72ac68d7fe779ef5775464e77bdaa0f310dab4cbb67b39545cbf300d856c87
  Public key (hex):  0x4a2bc56e618a2a8fc71ab1728bca2c53738324447a39207714008f54b3bdf202
  Account ID:        0x4a2bc56e618a2a8fc71ab1728bca2c53738324447a39207714008f54b3bdf202
  Public key (SS58): 5DjxQMGxuzMPWP9Au7AYxNsdJg5Uv2BDJ6woPJX5B7zbpot3
  SS58 Address:      5DjxQMGxuzMPWP9Au7AYxNsdJg5Uv2BDJ6woPJX5B7zbpot3

$ # Starting from the Genesis UTXO, let's send 90 of the coins to Karl, burning the remaining 10
$ docker run --network host ghcr.io/off-narrative-labs/tuxedo-wallet:milestone-1-recipient-patch spend-coins \
  --input 000000000000000000000000000000000000000000000000000000000000000000000000 \
  --output-amount 90 \
  --recipient 4a2bc56e618a2a8fc71ab1728bca2c53738324447a39207714008f54b3bdf202

000000000000000000000000000000000000000000000000000000000000000000000000: Found coin worth 100 units owned by 0xd2bf4b844dfefd6772a8843e669f943408966a977e3ae2af1dd78e0f55f4df67
Node's response to spend transaction: Ok("0x97b437c59b0f67d6085de78d6fa3f578dc44898efbda6093a9be71779ab4951d")
7cdc4eec5ba8238d2fe1ce1730790031524d3273128e9cdeb51c26f99ba91fd000000000: Found coin worth 90 units owned by 0x4a2bc56e618a2a8fc71ab1728bca2c53738324447a39207714008f54b3bdf202

$ # Now Karl can send her coins anywhere she wants. We need to supply Karl's private information in order to sign her transactions. By not explicitly specifying a recipient, we are sending the coins back to the default example address
$ docker run --network host ghcr.io/off-narrative-labs/tuxedo-wallet:milestone-1-recipient-patch spend-coins \
  --input 7cdc4eec5ba8238d2fe1ce1730790031524d3273128e9cdeb51c26f99ba91fd000000000 \
  --output-amount 90 \
  --seed "disagree bridge nuclear paper usage spirit switch guard exist fix error share"

7cdc4eec5ba8238d2fe1ce1730790031524d3273128e9cdeb51c26f99ba91fd000000000: Found coin worth 90 units owned by 0x4a2bc56e618a2a8fc71ab1728bca2c53738324447a39207714008f54b3bdf202
Node's response to spend transaction: Ok("0xf62add2935d51d1750ebe2b4ead53fe90df3b346dc6453a1fd21e91d5aab3109")
90b35536832469cddaae24d00fc403eb80ac129e2fafbf8a27f947a9c48a7b5800000000: Found coin worth 90 units owned by 0xd2bf4b844dfefd6772a8843e669f943408966a977e3ae2af1dd78e0f55f4df67
```

**Comment by JoshOrndorff** [comment]
@takahser Good catch. We renamed the runtime right before publishing the tag. The links are all fixed now.

**Review by takahser — APPROVED** [review]
Thanks for the fixes. I [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/98347613a965e984f788abdc7e32e0b41ef200c0/evaluations/tuxedo_1_takahser.md) your delivery.

**Comment by fededubbi** [comment]
Hi @JoshOrndorff,

I noticed you are based in CH, then can you please add your VAT number under your name on the invoice and add the 7.7.% on top of the amount?

Many thanks,
Federica

**Comment by coax1d** [comment]
> Hi @JoshOrndorff,
> 
> I noticed you are based in CH, then can you please add your VAT number under your name on the invoice and add the 7.7.% on top of the amount?
> 
> Many thanks, Federica

Hi Federica,

We dont have a company incorporated in Switzerland or a company incorporated at all is that a requirement for a web3 foundation grant? If so we can work on starting a sole proprietorship or perhaps resubmit an invoice from a company we partner with.

Andrew

**Comment by fededubbi** [comment]
Hi @JoshOrndorff,

No, the invoice is fine.
Sorry for the confusion.

Many thanks,
Federica

**Pull request merged**
