### PR TITLE
Deitos Network - Milestone Delivery 1

### PR DESCRIPTION
**Pull request by Ernih**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2040

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Hi @Ernih. Sorry for the long wait, we have a bit of a backlog at the moment. 

I am trying to build the `docker-ip` images using `make`, but it keeps failing with the following error message. Any idea what might cause it?

```sh
 => ERROR [2/7] RUN apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       cur  0.0s
------
 > [2/7] RUN apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       curl       wget       bash       coreutils       software-properties-common:
------
Dockerfile:12
--------------------
  11 |     
  12 | >>> RUN apt-get -qq update  \
  13 | >>>  && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends \
  14 | >>>       sudo \
  15 | >>>       curl \
  16 | >>>       wget \
  17 | >>>       bash \
  18 | >>>       coreutils \
  19 | >>>       software-properties-common 
  20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       curl       wget       bash       coreutils       software-properties-common" did not complete successfully: error creating overlay mount to /var/lib/docker/overlay2/pl0kzu5t5gqzu05mmkegqh5u5/merged: no such file or directory
make: *** [Makefile:8: build] Error 1
```

**Comment by hbulgarini** [comment]
> Hi @Ernih. Sorry for the long wait, we have a bit of a backlog at the moment.
> 
> I am trying to build the `docker-ip` images using `make`, but it keeps failing with the following error message. Any idea what might cause it?
> 
> ```shell
>  => ERROR [2/7] RUN apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       cur  0.0s
> ------
>  > [2/7] RUN apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       curl       wget       bash       coreutils       software-properties-common:
> ------
> Dockerfile:12
> --------------------
>   11 |     
>   12 | >>> RUN apt-get -qq update  \
>   13 | >>>  && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends \
>   14 | >>>       sudo \
>   15 | >>>       curl \
>   16 | >>>       wget \
>   17 | >>>       bash \
>   18 | >>>       coreutils \
>   19 | >>>       software-properties-common 
>   20 |     
> --------------------
> ERROR: failed to solve: process "/bin/sh -c apt-get -qq update   && DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends       sudo       curl       wget       bash       coreutils       software-properties-common" did not complete successfully: error creating overlay mount to /var/lib/docker/overlay2/pl0kzu5t5gqzu05mmkegqh5u5/merged: no such file or directory
> make: *** [Makefile:8: build] Error 1
> ```

hello @semuelle ! thanks for reviewing our milestone delivery.

Quick question, from which OS are you running this? At the moment the docker file is intended to be run in Linux environments.  However we never faced that issue during our testing in different computers (even if in MacOS). 

@rvalera : any idea of what would be the cause of the error? any recommendation for samuelle?

**Comment by semuelle** [comment]
I'm on Ubuntu 22.04.

**Comment by semuelle** [comment]
> What version of Docker do you have used? 

24.0.7

> How much disk space do you have?

70G free. I did run out of space running it the first time and pruned everything, perhaps it's related to that.

**Comment by rvalera** [comment]
> > What version of Docker do you have used?
> 
> 24.0.7
> 
> > How much disk space do you have?
> 
> 70G free. I did run out of space running it the first time and pruned everything, perhaps it's related to that.

Yes, it is possible that it could be happen. I suggest previousyly to next execution call the script named clean-all.sh to remove all elements created.

**Comment by hbulgarini** [comment]
@semuelle, ramon is referring to this script that cleans up everything:

https://github.com/Deitos-Network/deitos-ip/blob/w3f-grant-m1-delivery/clean-all.sh

The amount of disk space needed is around 30 GB, please try cleaning all with the script and try again? thanks!

**Comment by semuelle** [comment]
Thanks, @hbulgarini & @rvalera. I reinstalled Docker and that fixed it. 
Everything worked out of the box. Your milestone is hereby accepted. I will upload my evaluation notes tomorrow, but I have few comments. Thanks for the smooth delivery!

**Comment by RouvenP** [comment]
hi @Ernih we sent the payment today

**Comment by Ernih** [comment]
Hello and thank you
I have informed the team

Bests

**Pull request merged**
