### PR TITLE
create map bridge milestone 1 deliveries

### PR DESCRIPTION
**Pull request by zcheng9**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by alxs** [comment]
Hello @zcheng9 and apologies for the delay in getting back to you.

On your [application](https://github.com/w3f/Open-Grants-Program/pull/59), you mentioned you were planning on expanding on [this](https://github.com/tari-project/tari/tree/development/base_layer/mmr) existing MMR implementation. Have you used that in your work in the end? If so, please update the concerned files with the appropriate [license](https://github.com/tari-project/tari/blob/development/LICENSE). If not, would you mind sharing a bit of context as to why you changed your mind in the end?

Instead, I see you've been able to use some of the code in the recently released MMR [pallet](https://crates.parity.io/pallet_mmr/index.html). That's great! Do you have any insights on what elements of it you were able to use, or any issues you faced? Furthermore, would it make sense to make that pallet a dependency of yours instead of adapting it to this use case? It has also even more recently received some [improvements](https://github.com/paritytech/substrate/pull/7891), check it out if you haven't yet. And also here, please comply with the appropriate [license](https://github.com/paritytech/substrate/blob/master/LICENSE-APACHE2). Simply removing the copyright notice is not an acceptable practice (and could get you in trouble).

Finally, I see that you're using the grant recipient badge on your website. While we want to help winning teams acknowledge their grants publicly, we have [guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md) in place that require teams to a) only use the badge in project-specific settings, i.e. explicitly with regard to the deliverables we're funding and not to the team, and b) only use the badge after successful delivery of the first milestone. Same goes for announcing the grant publicly, but it's likely this wasn't stated clearly when you first applied. Anyway, may I kindly ask you to please remove the badge from your landing page, and if you would like to coordinate on any future announcements, feel free to reach out to <grantspr@web3.foundation>.

**Comment by zcheng9** [comment]
Thanks very much for the comments and apologies for the later reponse due to the Spring Festival vacation. 

First, we changed our mind because we found that the relesased MMR pallet is a better choice for our MMR implementation. 

And for your second questions, we have tried to make the pallet a dependency of our implementation at the begining. However, we found that there are some diffculty to do so. As you can see example here [here](https://github.com/Philasande-map/mapbridge/blob/master/pallets/map-mmr/primitive/src/lib.rs#L39),  when merging two MMR nodes, we need do some extra work instead of simply hashing them together. The MMR in our setting looks like the tree in this picture below. Do you have any better ideas for us to do so？

MMR

For your concern regarding the badge on our websit, we have removed it and sorry for the mis-understanding.  Also we  have updated the appropriate license.

**Comment by alxs** [comment]
No worries. Hope you enjoyed your holidays.

I assumed as much, could you expand on why it was in fact a better choice?

Yes, you brought this up in your application. You mentioned you need a number of extra fields and you need to redefine the prove and verify functions. I'm no expert but there should be a straightforward way of doing this without copy-pasting the entire pallet. Perhaps @mmagician has some useful suggestions.

Otherwise, the proper way of doing this would be to fork the MMR pallet. This way you can also easily integrate upstream changes in your work.

**Comment by zcheng9** [comment]
For your first question, after comparing two libraries, we found that MMR pallet is succincter and clearer. Besides it is convenient for substrate integration with MMR pallet. That's the reason why we choice MMR pallet as our start point. 

We planned to integrate most map bridge functionality(not only MMR Trie) into this pallet. That's the reason why we did not fork MMR pallet. Meanwhile MAP bridge would strictly abide by Apache open source agreement, keep the copyright and license statement of the original author.

**Comment by alxs** [comment]
Hi @zcheng9, apologies for the delay as your delivery was the subject of some controversy in the past days.

As a result, I regret to inform you that we will have to reject the delivery and terminate the original agreement due to the following reasons:

- The delivery contains no documentation, code comments, or testing guide of your own and only minimal additional tests. We would normally ask you to simply add these items, but it constitutes a significant portion of the work and we prefer not to ask for it at this stage given our next concern:
- The fact that your delivery originally contained all files from the MMR pallet with the license stripped off wasn't taken lightly at all by the committee. We've recently had a few issues with teams complaining about other projects plagiarising their work for milestone deliveries and intend to take such matters much more seriously. This is the main reason for the current termination.
- You specified in your application that you would expand Tari's MMR library, but instead based your work on Parity's MMR pallet. This already constitutes a significant deviation from the original agreement, especially since the pallet contained most of the work required for this milestone. In itself, this probably wouldn't have been an issue but ideally you would have raised it with us such that we could reevaluate the application.

Nevertheless, we would like to thank you for your interest in the grants program and for your contributions to the ecosystem. Feel free to reapply for a grant and we will evaluate it independently of the current incident, but note that we're in the process of establishing stricter guidelines so you may need a stronger application.

**Pull request closed without merging**
