### PR TITLE
NewOmega M3

### PR DESCRIPTION
**Pull request by celrisen**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @celrisen. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @celrisen, 
if I run `yarn test` from the `client` directory against a local node, some of the `ContractFacade` tests fail (different numbers depending on the versions of `api` and `api-contract` I choose) with `NotCallable`. Any idea what's wrong?

**Comment by celrisen** [comment]
> Hey @celrisen,
> if I run `yarn test` from the `client` directory against a local node, some of the `ContractFacade` tests fail (different numbers depending on the versions of `api` and `api-contract` I choose) with `NotCallable`. Any idea what's wrong?

Hey @semuelle,

Ok so just a sanity check:
1. Did you deploy all the contracts (manually, because the Deployer got broken for me again)
2. Did you select the right dependencies when deploying (polkadot apps UI shows you those contract address deps when deploying)
3. Did you run authoriseDelegator on all the contracts, and passed the Delegator
4. Did you run authoriseRanked, authoriseUniverse, authoriseIndustrial on the Storage contract, and passed in the appropriate contract addesses

Also make sure that the local node is a customised node available here https://github.com/celrisen/newomega-node

By the way, you can test against newomega.network where all this is done ;)

**Comment by celrisen** [comment]
@semuelle I'll have another look at the Deployer today, if that can work again then it will make it easier for you to test.

**Comment by celrisen** [comment]
@semuelle I've pushed the Deployer fixes, so now running the client tests will also deploy and then test the contracts end to end. All you need on your end is the customised node mentioned above, running locally.

Let me know how it works :)

**Comment by semuelle** [comment]
Hey @celrisen, thanks for the follow-up. I was able to test everything locally. 

One more thing: I can't find the code around betting, most notably the `setBet` function I found referenced in the client code. Can you point me to the logic where bets are set and processed?

**Comment by celrisen** [comment]
Sure @semuelle,

Conceptually, in Universe mode there are actions that both generate and consume tokens (currently capturing planets on the generate side, and convenience functions/planet upgrades on the consume side; to be expanded later on, for example token generating quests or module crafting for token spending). 

In the Ranked mode, you can register your fleet for ranked combat and optionally attach token value to it (see Delegator's ```register_defence``` and subsequently Ranked's ```register_defence``` to see how it's done). Then, you are allowed to attack other fleets. When attacking a fleet, you can specify a bet ```(0 <= bet <= min(balance, attacked_fleet_balance))```, which when you win, you get back 150% of to your Defence fleet's account. If you lose, you lose the bet, which is transferred in full to the account of the fleet you lost against. Note that the attacker only gets 50% for win, whereas defender 100%. This is intended, since attacking is easier (in theory).

In client code, have a look at the ```BetSelector``` component which is wired up to ```CompactShipSelection```, and allows choosing the value to either attach to defensive fleet, or to attack a fleet with. Note that if your balance is 0, or if you want to bet 0, you can, and it is the default option (Play for Fun / Ranking). This value, whatever it is, makes its way down to the ```ContractFacade```, and is attached as ```value``` to the contract calls described in previous paragraph.

Let me know if that makes it clearer.

**Comment by semuelle** [comment]
Thanks for the info, @celrisen. That helped a lot. I just pushed my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/0349a186c79fae408169c4bfb119771dd19c06de/evaluations/newomega_3_semuelle.md) and your milestone is hereby accepted. Congratulations! :tada: 

I was again impressed with the game, and it was fun to watch the transactions trickle into the explorer while playing. In the end, I had one minor issue with the tests, where I got two `doc test` failures because it interpreted indented text as code. Also, I would have preferred to see unit tests on all contracts. Overall, the code is well maintained and documented, though. Maybe something for the next milestone.

I will forward your invoice for processing.

**Pull request merged**
