### PR TITLE
Whiteflag on Fennel Protocol, Milestone 1

### PR DESCRIPTION
**Pull request by Romulus10**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/873

### CODE REVIEW

**Comment by takahser** [comment]
@Romulus10 thanks for your delivery. We're currently experiencing a large backlog due to various reasons (sick leaves, company trips, internal changes). Hence, a longer than usual waiting time is likely. Nevertheless, we'll try to evaluate your deliveries as soon as possible.

**Comment by lucasvanmol** [comment]
Hey there @Romulus10,

I'm running into some issues running the webapp - could you or perhaps someone from your team ping me on element [@lucas:web3.foundation](https://matrix.to/#/@lucas:web3.foundation) so that I can share some screenshots/logs?

Thanks!

**Comment by lucasvanmol** [comment]
Thanks for reaching out and helping to resolve issues on element. Happy to say the delivery has now been accepted, and you can see my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/whiteflag-on-fennel-protocol_1_lucasvanmol.md). I'll forward your invoice internally!

**Comment by Romulus10** [comment]
> Thanks for reaching out and helping to resolve issues on element. Happy to say the delivery has now been accepted, and you can see my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/whiteflag-on-fennel-protocol_1_lucasvanmol.md). I'll forward your invoice internally!

Excellent - thanks for your feedback!

**Comment by RouvenP** [comment]
hi @Romulus10 we transferred the payments today. Thanks!

**Comment by Romulus10** [comment]
Received. Thanks @RouvenP!

**Pull request merged**
