### PR TITLE
PRIMIS_Milestone_1

### PR DESCRIPTION
**Pull request by Andy-Meta**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1059 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by randombishop** [comment]
Hi @Andy-Meta !

Thanks for submitting your deliverables for review.

I will be conducting an external evaluation (I am not a W3F member so it will be an external evaluation until further review by an official W3F officer.)

So far, these tests went well:
- I installed the app on Mac :check:
- Created a wallet :check:
- Received DOT :check:
- Received KSM :check:

First identified issues:

- There is a typo in "Recieve" 

- When I tried sending DOT, the app showed success; but the transaction actually failed (I guess because I sent less than the existential deposit.)
Screen Shot 2022-09-30 at 10 32 38 AM
https://explorer.polkascan.io/polkadot/event/12276165-39
The app should show that the transaction failed instead of the success status.

- Sometimes, when I switch the network, the balance is not loaded and the progress turns forever until I close and re-open the app.

I will be running the app from source so that I can merge new changes and test new versions without re-installing the Mac package...

Also, I have never bought NFTs in Polkadot ecosystem before, can you recommend cheap (under $5) collections in the different chains supported by Primis so that I can test with NFTs? Which DApps should I be using for that?

Thanks and looking forward to working together on this delivery process...

**Comment by randombishop** [comment]
@Andy-Meta Little detail: yarn failed in my machine with this error:
```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/Yuripetusko/json-stream-stringify.git
Directory: /Users/randombishop/PycharmProjects/client
Output:
Host key verification failed.
fatal: Could not read from remote repository.
```
npm install worked fine though.

**Comment by randombishop** [comment]
```Also, I have never bought NFTs in Polkadot ecosystem before, can you recommend cheap (under $5) collections in the different chains supported by Primis so that I can test with NFTs? Which DApps should I be using for that?```
>> I found a couple of NFTs in RMRK2 to test, but it seems like trading in RMRK1 is disabled now in https://singular.rmrk.app/?

**Comment by randombishop** [comment]
@Andy-Meta 
It was cool discovering your app and it looks like a nice start for a desktop wallet.
Please find my first evaluation of the delivery here:
https://github.com/w3f/Grant-Milestone-Delivery/pull/587
Cheers!

**Comment by Noc2** [comment]
@Andy-Meta could you take a look at the external evaluation and the comments above?

**Comment by Andy-Meta** [comment]
> @Andy-Meta could you take a look at the external evaluation and the comments above?

@Noc2 ok, I will report the above issues to our dev

**Comment by Andy-Meta** [comment]
@Noc2 @randombishop  very appreciate you guys' quick testing responses, here is our feedback

1. I tested again with Mac Version and sent DOT successfully(https://polkadot.subscan.io/extrinsic/12339981-2), you could try again, maybe some network problem at your sending time.  And also, not only DOT&KSM, we support ACA, STAR, and GLMR, you could try these assets sending and receiving functions.
2. Sorry about the wrong spell of "Receive", we will update.
3. For NFT management, as our testing guide mentioned, we only support Kusama Network, and now we linked https://singular.app/ (That's singular 2.0 under Kusama Network) to get users' NFT assets, and then display them in Primis
4. Sometimes, if you changed the network, Primis would need some time to display the balance of your assets, but it wouldn't be the wrong balance. So far it's a little slow when changing networks,  we will optimize it.
5. Our dev will check yarn error, but we will update the latest Mac version on primis.cc, and I suggested you test our Mac Desktop as the main target. Once we updated, I would notify you guys here.

**Comment by randombishop** [comment]
@Andy-Meta Did you check out the detailed evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/pull/587, it explains the issues in more detail.
To clarify the reported bug in sending: yes, if everything is fine, sending works, but the bug is actually: if you send a bad transaction, like try sending 0.0001 DOT to an empty address, it will actually fail in the blockchain because it's under the existential deposit; but the app will show it as success.

**Comment by Andy-Meta** [comment]
> @Andy-Meta Did you check out the detailed evaluation here: #587, it explains the issues in more detail. To clarify the reported bug in sending: yes, if everything is fine, sending works, but the bug is actually: if you send a bad transaction, like try sending 0.0001 DOT to an empty address, it will actually fail in the blockchain because it's under the existential deposit; but the app will show it as success.

@randombishop  Got it, we will also check #587 in detail and update soon.

**Review by Noc2 — APPROVED** [review]
I’m happy to confirm that the milestone is accepted and I will forward your invoice internally.

**Comment by Andy-Meta** [comment]
> @Andy-Meta I just checked the invoice and it looks like the amount is missing on the invoice. Could you add this?

@Noc2 Got it, We submitted the Invoice Form again that added the amount info, you could check it when you are available.

**Comment by Andy-Meta** [comment]
@Noc2 hi, any update about the grant payment and invoice?

**Comment by Noc2** [comment]
Hi @Andy-Meta  I forwarded your invoice internally, but the invoice probably also needs to contain our address.

**Comment by Andy-Meta** [comment]
> I forwarded your invoice internally, but the invoice probably also needs to contain our address.
Thanks, but we don't know your address, I think we just need to provide our info for you guys. So next step, we only need to wait or tell me your address and then I submit the invoice form again?

**Comment by semuelle** [comment]
Hey @Andy-Meta. Please check the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89) for our address.

**Comment by Andy-Meta** [comment]
> Hey @Andy-Meta. Please check the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89) for our address.

Got it, I checked again, got this, Web 3.0 Technologies Foundation, Baarerstrasse 14, 6300 Zug, Switzerland, UID / VAT ID: CHE-322.596.347). Sorry about that, I would submit again right now.

**Comment by Andy-Meta** [comment]
@semuelle @Noc2  Submitted the invoice form again, which added your address. Appreciate you guys‘ patience.

**Comment by fededubbi** [comment]
Hi, i noticed on your invoice is missing our name and address.
Could you please include them in the "Bill to" section?

Web3.0 Technologies Stiftung
Baarerstrasse 14,
6300, Zug.

Many thanks,
Federica

**Comment by Andy-Meta** [comment]
> Hi, i noticed on your invoice is missing our name and address. Could you please include them in the "Bill to" section?
> 
> Web3.0 Technologies Stiftung Baarerstrasse 14, 6300, Zug.
> 
> Many thanks, Federica

image

@fededubbi Hi, Federica, Is it correct? I submitted the invoice form again.

**Comment by fededubbi** [comment]
Hi @Andy-Meta,

The "Bill to" should be before our name and address, and you can just write our name (Web 3.0 Technologies Foundation) once, with address and VAT number.
I hope this helps.

Many thanks,
Federica

**Comment by Andy-Meta** [comment]
> Hi @Andy-Meta,
> 
> The "Bill to" should be before our name and address, and you can just write our name (Web 3.0 Technologies Foundation) once, with address and VAT number. I hope this helps.
> 
> Many thanks, Federica

@fededubbi  Got it, I submitted it again, plz check the latest submission from Primis. And I suggest that W3F could provide the invoice template  in the [Invoice Form](https://forms.gle/LSRr7PCjBpEbKGh89) which would help some projects that are not very familiar with financial invoice events proceed with the process of invoice better.

**Comment by fededubbi** [comment]
Hi @Andy-Meta,

That's correct.

Many thanks,
Federica

**Comment by RouvenP** [comment]
hi @Andy-Meta we transferred the payment today.

**Comment by Andy-Meta** [comment]
> hi @Andy-Meta we transferred the payment today.

Received, thanks

**Comment by randombishop** [comment]
@Noc2 @fededubbi Hey W3F team! I didn't receive the KSM for the evaluation, any action I need to take for that or is it just pending? Cheers! :)

**Pull request merged**
