### PR TITLE
Grant milestone 1 delivery

### PR DESCRIPTION
**Pull request by lukastanisic99**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2350

### CODE REVIEW

**Comment by lukastanisic99** [comment]
The state of the project repository is also for milestone 2, but need to write an article for it. Expect an update in the next few days when the article is written. Do I have to coordinate with someone for the article?

**Comment by keeganquigley** [comment]
Thanks @lukastanisic99 you can email grantsPR@web3.foundation to coordinate the announcement.

**Comment by lukastanisic99** [comment]
@PieWol I've added a more detailed testing guide next to the docs - take a look https://github.com/peer3to/state-channels-plus/blob/master/docs/testingGuide.md

It covers tests both for milestone 1 and milestone 2

**Comment by PieWol** [comment]
Thank you @lukastanisic99
You mentioned in the application that you are planning on having 7 FTEs working on this project. Yet I can only see commits made by you. The way you published all your existing code doesn't allow insights in previous commits. Who is now actually working on this project?

**Comment by lukastanisic99** [comment]
@PieWol yes - we're targeting 7 but need to resolve funding first. In the grant PR it says 1 person 24/7 (me) and other part time. That's why all the commits are from me since I designed it and have full context of the implementation. Part time doesn't really work for core tech or it's not as efficient since people are constantly switching context and are working on different things and we want to finish this as soon as possible, so we can build the business side and make it sustainable. Others are mostly focused on the business, product and design parts that are more tolerable for part time contribution.

**Comment by PieWol** [comment]
Okay, so it's not 7 but how many are now actually working on this grant project?

**Comment by lukastanisic99** [comment]
Sorry if something was unclear. Currently, on this grant project (the code - public good - open source) only me since for now we got $0 for it and no VC is interested in funding public goods (if you know some send them our way). The rest are focused on the business. After you guys approve we'll ask the treasury to fund the completion of this project (public good).

**Comment by PieWol** [comment]
thanks, understood.

**Comment by PieWol** [comment]
With this [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1223) your milestone delivery is accepted 🎉 .

**Pull request merged**
