### PR TITLE
Lastic milestone 1

### PR DESCRIPTION
**Pull request by poppyseedDev**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2008 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @poppyseedDev. Please give it a couple of days, we have quite the backlog currently. In the meantime, could you add the link to the whitepaper?

**Comment by poppyseedDev** [comment]
> Thanks for the delivery, @poppyseedDev. Please give it a couple of days, we have quite the backlog currently. In the meantime, could you add the link to the whitepaper?

No worries, thanks for letting us know. Btw I can't seem to pass the error, do you guys have an idea what might I be doing wrong?

Run w3f/parse-milestone-delivery-action@master
Error: Match not found for: milestone_number

**Comment by keeganquigley** [comment]
Thanks for the delivery @poppyseedDev it is unable to correctly parse the milestone number, can you try changing it to:

**Milestone Number:** 1

instead of:

**Milestone Number:** Milestone 1 

Thanks!

**Comment by poppyseedDev** [comment]
> Thanks for the delivery @poppyseedDev it is unable to correctly parse the milestone number, can you try changing it to:
> 
> **Milestone Number:** 1
> 
> instead of:
> 
> **Milestone Number:** Milestone 1
> 
> Thanks!

Great looks like all checks have passed now, thanks! Hopefully I am not bodering you guys too much, but could you possibly provide an estimated timeline for when the checks might be completed? It would help us a lot to plan accordingly. 😊

**Comment by keeganquigley** [comment]
Yep looks good, thanks @poppyseedDev and apologies for the delay, we have a bit of a backlog at the moment. I should be able to look at this tomorrow!

**Comment by keeganquigley** [comment]
Hi @poppyseedDev I started my evaluation today and have the following initial comments:

- The proposal states that "core functions will be fully covered by comprehensive UI testing framework" but the deliverable is blank. I know that it is all mock data but shouldn't there still be some tests here?
- The docs still contain some boilerplate text like this [markdown template](https://docs.lastic.xyz/markdown-examples.html), and this [trader index](https://docs.lastic.xyz/trader/). Is the website still a work-in-progress at this point?

**Comment by keeganquigley** [comment]
Thanks @phillux much appreciated. Moving on, the [substrate-interact](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact) repo instructions say to use `yarn` for the front-end, but the [static_frontend](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact) repo says to use `pnpm`. Is there a reason for using both package managers? `yarn install` works but it gives a warning about mixing package managers:
```js
yarn install v1.22.19
warning ../../package.json: No license field
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @azns/resolver-core@1.6.0: The engine "node" is incompatible with this module. Expected version ">=16 <=18". Got "20.6.1"
warning @azns/resolver-core@1.6.0: The engine "pnpm" appears to be invalid.
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
And then `yarn start` fails:
```js
yarn run v1.22.19
warning ../../package.json: No license field
$ next start
[Error: ENOENT: no such file or directory, open '/Users/keeganquigley/LasticUI/static_frontend/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/keeganquigley/LasticUI/static_frontend/.next/BUILD_ID'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

`pnpm run dev` also fails:
```js
pnpm run dev

> lastic@0.1.0 dev /Users/keeganquigley/LasticUI/static_frontend
> next dev

FatalError: error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.

    at getTypeScriptConfiguration (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/typescript/getTypeScriptConfiguration.js:49:19)
    at writeConfigurationDefaults (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:178:117)
    at verifyTypeScriptSetup (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/verify-typescript-setup.js:119:74)
    at async verifyTypeScript (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:108:26)
    at async startWatcher (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:129:29)
    at async setupDevBundler (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1627:20)
    at async initialize (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:71:30)
    at async Server.<anonymous> (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:221:36)
```
Can you help me look into this? I'll try on Ubuntu as well.

**Comment by keeganquigley** [comment]
UPDATE: Doing the same thing on Ubuntu:
```js
ubuntu@ip-172-31-26-199:~/LasticUI/static_frontend$ yarn start
yarn run v1.22.19
$ next start
[Error: ENOENT: no such file or directory, open '/home/ubuntu/LasticUI/static_frontend/.next/BUILD_ID'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/ubuntu/LasticUI/static_frontend/.next/BUILD_ID'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by keeganquigley** [comment]
Okay, I was able to get the front-end running from the [substrate-interact](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact) dir. But I'm not sure where I'm supposed to be entering the extrinsics in the [coretime-chain-setup](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact#coretime-chain-setup). Also `yarn test` doesn't seem to be working in any of the directories.

substrate-interact

**Comment by keeganquigley** [comment]
Also, deliverable 2b. links to a Figma prototype of the existing [website](https://www.lastic.xyz/). But the application states that an initial prototype of the coretime marketplace would be delivered for M1, based on the mockups in the proposal. Is there a working front-end that exists to demo the app? As this front-end is just a copy of the substrate front-end template, I'm not seeing any differences.

**Comment by poppyseedDev** [comment]
> Also, deliverable 2b. links to a Figma prototype of the existing [website](https://www.lastic.xyz/). But the application states that an initial prototype of the coretime marketplace would be delivered for M1, based on the mockups in the proposal.

Thank you for your message and the opportunity to clarify the deliverables. I've made some updates to the README to help differentiate between the various states of our application:

What is featured on the [lastic website](https://lastic.xyz/) currently is the stable branch. This branch does not have all of the latest features, however the website presented there has been tested on different browsers, I am about to update that deliverable as well.

I linked the deployment that is featured on the main branch to [test.lastic.xyz](https://test.lastic.xyz/) you can also view it by running the [lasticUI](https://github.com/LasticXYZ/LasticUI) locally and running it first with `pnpm i` and then `pnpm run dev`.  Then for seeing the website you can navigate to `localhost:3000` 😊

**Comment by poppyseedDev** [comment]
> Thanks @phillux much appreciated. Moving on, the [substrate-interact](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact) repo instructions say to use `yarn` for the front-end, but the [static_frontend](https://github.com/LasticXYZ/LasticUI/tree/main/substrate-interact) repo says to use `pnpm`. Is there a reason for using both package managers? `yarn install` works but it gives a warning about mixing package managers:
> 
> ```js
> yarn install v1.22.19
> warning ../../package.json: No license field
> info No lockfile found.
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> error @azns/resolver-core@1.6.0: The engine "node" is incompatible with this module. Expected version ">=16 <=18". Got "20.6.1"
> warning @azns/resolver-core@1.6.0: The engine "pnpm" appears to be invalid.
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```
> 
> And then `yarn start` fails:
> 
> ```js
> yarn run v1.22.19
> warning ../../package.json: No license field
> $ next start
> [Error: ENOENT: no such file or directory, open '/Users/keeganquigley/LasticUI/static_frontend/.next/BUILD_ID'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/Users/keeganquigley/LasticUI/static_frontend/.next/BUILD_ID'
> }
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> `pnpm run dev` also fails:
> 
> ```js
> pnpm run dev
> 
> > lastic@0.1.0 dev /Users/keeganquigley/LasticUI/static_frontend
> > next dev
> 
> FatalError: error TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
> 
>     at getTypeScriptConfiguration (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/typescript/getTypeScriptConfiguration.js:49:19)
>     at writeConfigurationDefaults (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/typescript/writeConfigurationDefaults.js:178:117)
>     at verifyTypeScriptSetup (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/lib/verify-typescript-setup.js:119:74)
>     at async verifyTypeScript (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:108:26)
>     at async startWatcher (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:129:29)
>     at async setupDevBundler (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-utils/setup-dev-bundler.js:1627:20)
>     at async initialize (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/router-server.js:71:30)
>     at async Server.<anonymous> (/Users/keeganquigley/LasticUI/static_frontend/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/lib/start-server.js:221:36)
> ```
> 
> Can you help me look into this? I'll try on Ubuntu as well. Should I be using the main branch?

I made changes to the package manager now both directories use `pnpm` and you can run both from the master directory so `lastic_ui` or if you want you can run them individually going into their specific directories `lastic_ui/substrate_interact` or `lastic_ui/static_frontend` and run same commands. So those as written in the README.md are:

 - `pnpm i` and then `pnpm run dev`

The `substrate_interact` for us currently serves more as a tool that we can quickly use for checking the interactions. Those functions will be moved into an [`lastic-sdk`](https://github.com/LasticXYZ/lastic-sdk) in the future

**Comment by poppyseedDev** [comment]
> Hi @poppyseedDev I started my evaluation today and have the following initial comments:
> 
> * The proposal states that "core functions will be fully covered by comprehensive UI testing framework" but the deliverable is blank. I know that it is all mock data but shouldn't there still be some tests here?

I have updated the milestones and tried to add more clarity to our overall documentation. Therefor I have provided additional  testing instructions that found in the deliverables file under [testing-guide](https://github.com/LasticXYZ/Grant-Milestone-Delivery/blob/lastic/deliveries/lastic-milestone_1.md#testing-guide).

**Comment by poppyseedDev** [comment]
Hey @keeganquigley added everything needed, please let is know if you are able to run it now.

**Comment by keeganquigley** [comment]
Thanks @poppyseedDev sorry I was out Friday, looking at the updates now.

**Comment by keeganquigley** [comment]
Thanks for your hard work @poppyseedDev @phillux and thanks for resolving the issues. The docs look amazing now too. I am now able to get through all the testing guides, and run the chain & app locally as well as on the test Vercel site. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/lastic.md). Please note a few minor issues.

Great work! I'm excited to see the coretime marketplace come to life and looking forward to seeing an initial implementation. I'm happy to pass the milestone, and congrats! Please expect up to 14 days for payment once your invoice is submitted.

**Comment by phillux** [comment]
@keeganquigley we have submitted the invoice using the invoice form.

thank you for the review!

**Pull request merged**
