### PR TITLE
Polkadot-Dart Milestone 1

### PR DESCRIPTION
**Pull request by cyaolong**
This is edited for creating a new pull request.

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @cyaolong,

I am trying to run the tests, but don't get very far:

```bash
$ flutter test test/polkadot_dart_test.dart                    
00:04 +0 -1: loading /polkadot-dart/Polkadot-Dart/test/polkadot_dart_test.dart [E]         
  Failed to load "/polkadot-dart/Polkadot-Dart/test/polkadot_dart_test.dart": ERROR: The library is not initialized 🙁
  package:polkadot_dart/crypto/common.dart 291:22        ed25519KeypairFromSeed
```

I have a suspicion that you should be referencing the `.so` file, not the `.dylib` for Linux in the build and helpers files. 

Can you verify that the tests run under Linux?

**Comment by neeboo** [comment]
> Hi @cyaolong,
> 
> I am trying to run the tests, but don't get very far:
> 
> ```shell
> $ flutter test test/polkadot_dart_test.dart                    
> 00:04 +0 -1: loading /polkadot-dart/Polkadot-Dart/test/polkadot_dart_test.dart [E]         
>   Failed to load "/polkadot-dart/Polkadot-Dart/test/polkadot_dart_test.dart": ERROR: The library is not initialized 🙁
>   package:polkadot_dart/crypto/common.dart 291:22        ed25519KeypairFromSeed
> ```
> 
> I have a suspicion that you should be referencing the `.so` file, not the `.dylib` for Linux in the build and helpers files.
> 
> Can you verify that the tests run under Linux?

Known issue that related to crossenv compiling. We will fix it asap.

**Comment by semuelle** [comment]
Hey @neeboo & @cyaolong,
I reviewed your milestone; you can follow the progress [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-dart_1_semuelle.md). I am happy to report that, apart from the testing issue, everything looks really good.

Do you have an estimate on when you might be able to submit a fix for the crossenv compilation?

**Comment by neeboo** [comment]
> Hey @neeboo & @cyaolong,
> I reviewed your milestone; you can follow the progress [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-dart_1_semuelle.md). I am happy to report that, apart from the testing issue, everything looks really good.
> 
> Do you have an estimate on when you might be able to submit a fix for the crossenv compilation?

Hi @semuelle,

Give it one to two days,  will get it done.

To ensure all platform are compiled correctly and avoid the complexity of cross-env settings. we might use CI to build all dynamic libraries and push to master/main.

And thank your for your review,  we will keep it going.

**Comment by neeboo** [comment]
Hi @semuelle ,

Linux `.so`  has been build and push to main, and we had use CI to generate those libs.
Please pull the latest branch main on your linux machine and run the tests.

**Comment by semuelle** [comment]
@neeboo & @cyaolong,

thanks for following up on the compilation and test issue. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-dart_1_semuelle.md) and I am happy to report that your milestone is hereby accepted. :tada: 

Your invoice will be forwarded for processing.

**Comment by neeboo** [comment]
> @neeboo & @cyaolong,
> 
> thanks for following up on the compilation and test issue. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-dart_1_semuelle.md) and I am happy to report that your milestone is hereby accepted. 🎉
> 
> Your invoice will be forwarded for processing.

Thank you for evaluation, we will move on milestone 2

**Comment by Noc2** [comment]
Hi @neeboo and @cyaolong The invoice you sent us seems to be wrong. It’s says 0.64 BTC, but according to grant proposal you only receive 0.56 BTC for this milestone. Could you please upload a new invoice. Thanks

**Comment by neeboo** [comment]
> Hi @neeboo and @cyaolong The invoice you sent us seems to be wrong. It’s says 0.64 BTC, but according to grant proposal you only receive 0.56 BTC for this milestone. Could you please upload a new invoice. Thanks

Sorry its my fault. I will send the correct one.

**Comment by neeboo** [comment]
> > Hi @neeboo and @cyaolong The invoice you sent us seems to be wrong. It’s says 0.64 BTC, but according to grant proposal you only receive 0.56 BTC for this milestone. Could you please upload a new invoice. Thanks
> 
> Sorry its my fault. I will send the correct one.

Sent already @Noc2. Please check the latest one.

**Comment by Noc2** [comment]
Thanks. I just forwarded your invoice internally.

**Comment by RouvenP** [comment]
hi @neeboo, we just sent a test transaction of 0.01 BTC. Could you please confirm if received?

**Comment by neeboo** [comment]
> hi @neeboo, we just sent a test transaction of 0.01 BTC. Could you please confirm if received?

Sure. Will confirm when received.

**Comment by neeboo** [comment]
> hi @neeboo, we just sent a test transaction of 0.01 BTC. Could you please confirm if received?

@RouvenP test transaction received.

**Comment by RouvenP** [comment]
@neeboo thanks for confirming. we just sent the remainder.

**Comment by neeboo** [comment]
> @neeboo thanks for confirming. we just sent the remainder.

The remainder is also confirmed.

Thank you very much!

Can we announce to public that the project is accepted?

**Comment by mmagician** [comment]
@neeboo @cyaolong I've sent an email to Michael So (ghostcorn@gmail.com) with the guidelines for making public announcements.

**Pull request merged**
