### PR TITLE
Add psc milestone 1

### PR DESCRIPTION
**Pull request by icodezjb**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1425

### CODE REVIEW

**Comment by icodezjb** [comment]
what is invoice form ? Is there a template for reference ?

**Comment by 0xCaso** [comment]
Hi @icodezjb, thanks for the delivery. I'll start the evaluation soon.

The form (that you can find in the pull request body) will guide you for the creation of the invoice. It works like a template, also if you cannot "visualize" it. If you mean a template like a PDF ready to use, we can't have it but online is full of those.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
I just wrote the evaluation, you can find it [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/psc_1_0xCaso.md). Let me know if you have any question!

**Comment by icodezjb** [comment]
> 1. Could you please add tests for the Solidity contracts?

Within the scope of this grant, we only prepared simple ERC20 contracts, and did not prepare EVM contract tests.
We refer to [chainx-frontier](https://github.com/chainx-org/frontier), here are related [how to run contract tests](https://github.com/chainx-org/frontier/blob/polkadot-v0.9.32/.github/workflows/rust.yml#L50).

> 2. zombienet spawn --provider native

Please build polkadot as described in [test_guide](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md#11-build-relaychain-polkadot). In order to be consistent with the configs of polkadot, [we modified rococo-local chainspec](https://github.com/OmniBTC/polkadot/commits/release-v0.9.32-fix) for test.

> 3. address and decimals

On rococo-local, Alice is `5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY`. On PSC, Alice is `15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5`. They have [the same public key](https://polkadot.subscan.io/tools/format_transform?input=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY&type=Polkadot), so are equivalent.

About `decimamals=10`, PSC and [statemint](https://github.com/paritytech/cumulus/blob/master/parachains/chain-specs/statemint.json#L23) are consistent. Although DOT `decimals=12` on  the application layer, but still `decimals=10` in the chainspec.

> 4. remix.sh script

Thanks, [we have uploaded it](https://github.com/OmniBTC/PSC/blob/main/scripts/remix.sh).

> 5. function register

Please see [register source code](https://github.com/OmniBTC/PSC/blob/main/pallets/assets-bridge/src/lib.rs#L433), only the admin of assets-bridge can resiger. 
In [test guide](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md), Alice(`15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5`) is the admin of assets-bridge. 
[Here](https://github.com/OmniBTC/PSC/blob/main/pallets/assets-bridge/README.md#dispatchable-functions) is the documentation for assets-bridge.

> 6. zombienet spawn --provider podman

We do not recommend using `podman`. Now [zombienet](https://github.com/paritytech/zombienet) sometimes fails to connect to the network with `podman` on linux and macos. After zombienet is optimized, the problem may be solved.

**Review by 0xCaso — COMMENTED** [review]
Thanks a lot for the updates and answers!
> Within the scope of this grant, we only prepared simple ERC20 contracts, and did not prepare EVM contract tests.

I was referring to the deliverable **0c. Testing and Testing Guide**; if you are not able to add those tests for the milestone, I'd recommend you to add them as soon as possible.

> Please build polkadot as described in [test_guide](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md#11-build-relaychain-polkadot).
> I successfully launched local testnet on linuxmint 20, no need to edit `psc-small-network.toml`

As I wrote in the evaluation, I had to do those edits because I'm using a MacOS machine (M1), and in my case you cannot simply run the [`psc-local-launch-native.sh`](https://github.com/OmniBTC/PSC/blob/main/zombienet/psc-local-launch-native.sh) script.

> On rococo-local, Alice is `5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY`. On PSC, Alice is `15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5`. They have [the same public key](https://polkadot.subscan.io/tools/format_transform?input=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY&type=Polkadot), so are equivalent.
> About `decimamals=10`, PSC and [statemint](https://github.com/paritytech/cumulus/blob/master/parachains/chain-specs/statemint.json#L23) are consistent. Although DOT `decimals=12` on  the application layer, but still `decimals=10` in the chainspec.

Then could you please then the guide [here](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md#24-transfer-dot-from-relaychain-to-parachain-by-dmp) and [here](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md#25-transfer-dot-from-parachain-to-relaychain-by-ump), with the right address (where it's "wrong"), and instead of putting "100000 DOT (decimals=10)", just put the right number to insert?

> Please see [source code of register](https://github.com/OmniBTC/PSC/blob/main/pallets/assets-bridge/src/lib.rs#L433), only the admin of assets-bridge can resiger.

Yes I've seen, but I was referring to the [ERC20 address](https://github.com/OmniBTC/PSC/blob/main/pallets/assets-bridge/src/lib.rs#LL430) taken as input, not to the caller of the function. Also from the code is visible that the only thing checked is if that address has already been registered.

**Comment by icodezjb** [comment]
@0xCaso 
Thank you for the reply.

Following your suggestion we [have updated](https://github.com/OmniBTC/PSC/commit/a143c2da535d0969f6a0a5e682b24f9eb43c0873) the test_guide.

In test_guide, `4.2 Deploy ERC20 contract`, `4.3 Bind wasm Reserved0 and erc20 Reserved0`, `4.4 Deposit Reserved0 (wasm -> evm)`, `4.5 Withdraw Reserved0 (evm -> wasm)`  are integration tests guide about the `AssetsBridgeErc20_OnlyAdmin.sol`.

0c. | Testing and Testing Guide | Core functions will be fully covered by comprehensive unit tests to ensure functionality and robustness. In the guide, we will describe how to run these tests.
-- | -- | --

We have prepared unit tests for the core functionality of `pallet-assets-bridge`.

As an auxiliary, the tests of `AssetsBridgeErc20_OnlyAdmin.sol` exists in the form of integration tests.

In the production environment, the admin of assets-bridge must audits whether the erc20 contract implements `IAssetsBridge` interface and whether it has the `AssetsBridgeAdmin` modifier.

**Review by 0xCaso — APPROVED** [review]
Many thanks again for the new changes and the clarifications!

I forgot to say that `docker pull comingweb3/polkadot` doesn't work (error: `manifest unknown`);

By the way, all the rest seems good and I'm updating the evaluation approving the milestone.

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
Congratulations on completing the first milestone of this grant!
As part of the Grants Program, we want to help grant recipients acknowledge their grants publicly.
To that end, we’ve created a [badge for projects](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/grant-badge-guidelines.md) that successfully deliver their first milestone.
Please use the badge only in reference to the work that has been completed as part of this grant, so please do not display it on your team or project's homepage unless accompanied by a short description of the grant.
Furthermore, you're now welcome to announce the grant publicly. Please remember to observe the
[foundation’s guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/announcement-guidelines.md) in doing so.
If you haven't already, reach out to grantsPR@web3.foundation for feedback on your announcement and cross-promotion.<br/>


We noticed that this is the last milestone of your project. Congratulations on completing your grant!
So, where to from here? The main goal of the W3F grants program is to support research as well as early-stage technical projects. So, if your project still falls under one of those categories, you might want to apply for a follow-up grant. Depending on your goals and project status, there are other support programs in our ecosystem that might be better suited as the next step, for example: <br/> 
- Project with a Business Case/Token: [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) or [VC Funding](https://parachains.info/investors) <br/> 
- Common Good Projects: [Treasury Funding](https://github.com/w3f/Grants-Program#treasury)

For a more comprehensive list, see our [Alternative Funding page](https://w3f.github.io/Grants-Program/funding).
Let us know if you have any questions regarding the above. We are more than happy to point you to additional resources and help you determine the best course of action.

**Comment by 0xCaso** [comment]
Also @icodezjb you did not send the invoice for the grant, could you do it following the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89)?

**Comment by icodezjb** [comment]
@0xCaso 
Thanks again.

I have fixed the [docker cmds](https://github.com/OmniBTC/PSC/blob/main/docs/test_guide.md#15-launch-testnet-with-podman).

**Comment by 0xCaso** [comment]
No problems, and thanks.

Could you please resend the invoice with inside the following info?
- Payment address (the same you specified in the [application document](https://github.com/w3f/Grants-Program/blob/master/applications/psc.md))
- Currency (idem)
- VAT Amount (also if it's zero)

**Comment by icodezjb** [comment]
Resent it.

- [x] Payment address
- [x] Currency
- [ ] VAT Amount

We generate the invoice pdf file by [this tool](https://create.onlineinvoices.com/invoices-generator/create/1). If the VAT amount is zero, it will not exist in the invoice pdf file.

**Comment by 0xCaso** [comment]
Thanks again. May you add it in some way? Like with a PDF editor, for example. Sorry for the bother but it's required

**Comment by icodezjb** [comment]
> Thanks again. May you add it in some way? Like with a PDF editor, for example. Sorry for the bother but it's required

Good idea.
- [x] VAT Amount

Resent it again.

**Comment by 0xCaso** [comment]
Thanks a lot, this time should be perfect. I forwarded internally, and the payment should happen within 14 days.

**Comment by fededubbi** [comment]
Hi @icodezjb,

I noticed that in the 'Bill to' invoice you put your name instead of ours.
Your name should be where you currently put ours.

Can you please exchange the names and resend the invoice?

Many thanks,
Federica Dubbini

**Comment by fededubbi** [comment]
Also invoice number is missing.
Can you please add it and resend?

Many thanks,
Federica

**Comment by icodezjb** [comment]
Sorry, I really don't know much about this invoice form, I submitted it again.

**Pull request merged**
