### PR TITLE
Submit xcm-tools-follow-up-2_1.md

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2334

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @gmajor-encrypt thanks for the delivery. I started my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-tools-follow-up_2_keeganquigley.md) and just have one comment about the examples.

When I run the UMP test the return message looks correct:
```
ubuntu@ip-172-31-28-63:~/xcm-tools/cmd$ go run . send UMP --dest 0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d --amount 10 --keyring 0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a --endpoint wss://rococo-asset-hub-rpc.polkadot.io
2024/09/04 21:53:07 send UMP message success, tx hash: 0xb926e3856620ac28f4edaaba5bcae02c7ea0d45355a61a71665a48e29faea686
```
But running a DMP test gives an HRMP return message:
```
ubuntu@ip-172-31-28-63:~/xcm-tools/cmd$ go run . send DMP --dest 0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d --amount 10 --keyring 0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a --endpoint wss://rococo-rpc.polkadot.io --paraId 1000
2024/09/04 21:53:28 send HRMP message success, tx hash: 0x5bc0611c48eafaad574c0b6a6158d9028d0c8f1deb072fc942d5db6aff347d1d
```
The same happens for ETH bridge and S2S bridge:
```
go run . send EthBridge --dest 0x6EB228b7ab726b8B44892e8e273ACF3dcC9C0492 --amount 10  --keyring 0xc0417c253312107d808921fb1dd3b740b64e99794dca74bcc550179f7c42a255 --endpoint wss://rococo-asset-hub-rpc.polkadot.io --contract 0xfff9976782d46cc05630d1f6ebab18b2324d6b14 --chainId 11155111
2024/09/04 21:57:59 send HRMP message success, tx hash: 0x38c8fd62a73926e2c9bcd9f527009de5dec2e081f0169ed591d57313d5fe233f
```
```
go run . send S2SBridge --paraId 1000 --destChain westend --dest 0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d --amount 10 --keyring 0xc0417c253312107d808921fb1dd3b740b64e99794dca74bcc550179f7c42a255 --endpoint wss://rococo-asset-hub-rpc.polkadot.io
2024/09/04 21:58:21 send HRMP message success, tx hash: 0x332d24b0df60d762c4844e8a5646a4d91a87de2906787f809783db4e66f3677b
```
Are you able to modify the success messages to either be customized or be uniform? Thanks

**Comment by gmajor-encrypt** [comment]
Hi, @keeganquigley Thanks for the evaluate. I have update this issue, please check it again

**Comment by keeganquigley** [comment]
Thanks for the fixes @gmajor-encrypt nice work as usual. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-tools-follow-up_2_keeganquigley.md). Happy to pass the milestone.

**Comment by RouvenP** [comment]
hi @gmajor-encrypt we sent the two payments today

**Pull request merged**
