### PR TITLE
Added Ink Boxes Milestone 2

### PR DESCRIPTION
**Pull request by avirajkhare00**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1243

### CODE REVIEW

**Comment by avirajkhare00** [comment]
Check author will fail due to the following issue: https://github.com/w3f/Grant-Milestone-Delivery/pull/621#issuecomment-1328050579

**Comment by avirajkhare00** [comment]
Hey @0xCaso, will you be evaluating this delivery too?

**Comment by 0xCaso** [comment]
Hi @avirajkhare00, thanks for the second milestone submission. I'm beginning the evaluation, and I'll reach out if I need your help.

**Comment by avirajkhare00** [comment]
@0xCaso, thanks a lot.

**Review by 0xCaso — CHANGES_REQUESTED** [review]
@avirajkhare00 [Here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-boxes_2_0xCaso.md) you can find my evaluation, I'll wait for updates. Write me if you have any questions.

**Comment by avirajkhare00** [comment]
Hey @0xCaso, I have updated the website.

Here is the list of changes I did:
 - /contribute endpoint will serve as the documentation to create a new ink box
 - Added the header
 - Ink boxes are now being displayed in grid
 - Added tests for contribute page
 - Fixed button color
 - Fixed LICENSE name
 - Added the blog for the same.

Here is the link of the blog: https://medium.com/@avirajkhare00/introducing-the-ink-boxes-website-39037e5bdf25

**Comment by avirajkhare00** [comment]
Hey @0xCaso , can you please review the changes

**Review by 0xCaso — APPROVED** [review]
Thanks for the changes, I've opened a PR to accept the milestone.

**Comment by avirajkhare00** [comment]
Thanks a lot @0xCaso

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
@avirajkhare00 Could you please resend the invoice with the right file name (M2 instead of M1 (1))? Also, you should re-emit it, the data is correct but there is written "Invoice#1, Date: 12/12/2022", and these fields refer to the old invoice.

**Comment by avirajkhare00** [comment]
Hey @0xCaso, I have fixed the invoice number, date, and file name. Thanks for pointing it out.

**Comment by 0xCaso** [comment]
Thanks! I've just notified the finance team, so allow up to 14 days for the payment process.

**Comment by avirajkhare00** [comment]
Hey @Noc2 @0xCaso. I have fixed few things around ink boxes and ink boxes website.

 - Made Ink Boxes UI more pretty. Please Check the screenshot below.
erc20 token screenshot
erc721 token screenshot

 - Fixed ink boxes website. Below is the screenshot.
 ink boxes contribution page

I tried fixing the issue with erc721 UI. But I am unable to understand why mint button is not working. The error I am getting in console, I am unable to understand it.

Let me know if you want to fix me anything else either in ink boxes and ink boxes website.

I have shared about ink boxes in polkadot forum: https://forum.polkadot.network/t/introducing-ink-boxes/1553

One is building something like this, hoping to collaborate for the same.

**Comment by Noc2** [comment]
Thanks for the update.

**Comment by avirajkhare00** [comment]
Hey @0xCaso. It’s been more then two weeks. May I know when can I receive the payment.

**Comment by RouvenP** [comment]
HI @avirajkhare00 apologies for the delay. we will transfer the payment on Monday.

**Comment by avirajkhare00** [comment]
Thanks for letting me know :)

**Comment by avirajkhare00** [comment]
Hey @RouvenP. Hoping to receive the payment today.

**Comment by RouvenP** [comment]
hi @avirajkhare00, yes, the payment will be executed this evening (CET). I will confirm as soon as sent.

**Comment by RouvenP** [comment]
hi @avirajkhare00, we just transferred the payment. Again, apologies for the delay.

**Comment by avirajkhare00** [comment]
Hey @RouvenP, I received the payment. Thanks a lot :)

**Comment by avirajkhare00** [comment]
Hey @RouvenP I it's been more then 14 days I didn't get the payment for my grant: https://github.com/w3f/Grant-Milestone-Delivery/pull/691
Can you please check from your end 🙏 
Thanks

**Comment by avirajkhare00** [comment]
@RouvenP thanks a lot 🙏

**Comment by RouvenP** [comment]
hello @avirajkhare00 the payment will go out this evening. I'll let you know as soon as done

**Comment by avirajkhare00** [comment]
Thanks for the info @RouvenP

**Comment by avirajkhare00** [comment]
Hey, @RouvenP apologies for disturbing again and again. I needed the payment on an urgent basis. Let me know if it's happening today. Thanks

**Comment by RouvenP** [comment]
hi @avirajkhare00 yes, the payment will go out within the next hour. I will notify you as soon as done

**Comment by RouvenP** [comment]
hi @avirajkhare00 we transferred the payment. I also sent you an email - feel free to contact me directly once the next milestone is approved and I will make sure to include it in the next payment run.

**Comment by avirajkhare00** [comment]
Thanks a lot 🙏 
I received the payment.

**Pull request merged**
