### PR TITLE
zkrollups evaluation

### PR DESCRIPTION
**Pull request by mmagician**
- zk rollups evaluation, partially complete
- finish zkrollups evaluation

### CODE REVIEW

**Comment by RouvenP** [comment]
hi @SotaWatanabe we just sent a test transaction. Could you confirm if received?

**Comment by SotaWatanabe** [comment]
Hello Rouven,

I have received 0.1 BTC. Thank you !

Best,
Sota

2021年3月30日(火) 18:06 RouvenP ***@***.***>:

**Comment by SotaWatanabe** [comment]
Sorry 0.001 BTC

2021年3月30日(火) 18:44 Sota Watanabe ***@***.***>:

**Comment by RouvenP** [comment]
hi @SotaWatanabe thanks for confirming. We sent the remainder.

**Comment by SotaWatanabe** [comment]
Thank you, Rouven. I have confirmed the 2nd transaction!

2021年4月1日(木) 12:37 RouvenP ***@***.***>:

**Pull request merged**
