### PR TITLE
Add openrollup-mvp-phase-1-milestone-1 delivery.

### PR DESCRIPTION
**Pull request by chrisicen**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/912

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @chrisicen an evaluator will take a look at it shortly.

**Comment by chrisicen** [comment]
Hi @keeganquigley @semuelle is there feedback about this delivery? Please let me know if there are any questions.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @chrisicen. Sorry for the delay. I have now reviewed your milestone. It's mostly complete, but I have one request: the pallet needs a step-by-step tutorial in which a basic example problem is implemented. The documentation, tests and article show that it's working, but now _how_ it's working. It would be great if you could add an example to the readme, the article or both.

**Comment by semuelle** [comment]
pinging @chrisicen

**Comment by chrisicen** [comment]
hi @semuelle I have create a demo example to demonstrate how to interact with `pallet-open-rollup`, https://github.com/open-rollup/fib-miden-example , It seems `Substrate-frontend-template` doesn't support some data types, so I do it with polkadot.js , looking forward to your feedback.

**Review by semuelle — COMMENTED** [review]
Thanks for the update, @chrisicen. Everything looks pretty solid, I just have one issue: I can register the miden app, deposit, set it inactive, etc., but when I try to `exit`, I always get a `KeepAlive` error. I can see that it's working in your test, but I cannot figure out why it's not working manually. It doesn't matter if I'm exiting as owner or user. Any idea what I might be doing wrong?

**Comment by chrisicen** [comment]
Hi @semuelle , thanks for your feedback, it is a bug when the `Currency` balance of `open-rollup` pallet reduce to zero, I have fix it in commit https://github.com/open-rollup/pallet-open-rollup/commit/4f6493f50a4671b12e919573b496488ea977ec02

It's working in test because the `ExistentialDeposit` parameter of `Currency` pallet is set to 0  in the test mock runtime.

**Review by semuelle — APPROVED** [review]
Thanks for the quick fix, @chrisicen. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/open-rollup_1_semuelle.md).

I have forwarded your invoice for processing. Best of luck going forward!

**Comment by chrisicen** [comment]
Thank you for your time to evaluate this delivery @semuelle , I appreciate your support.

**Comment by RouvenP** [comment]
hi @chrisicen we transferred the payment today

**Comment by chrisicen** [comment]
hi @RouvenP Thanks for the update, we have received the payment.

**Pull request merged**
