### PR TITLE
Gafi Network milestone 3

### PR DESCRIPTION
**Pull request by mutobui**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/896 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by mutobui** [comment]
Hi w3f team,
Thanks for your support on this journey, we would like to submit the last milestone to the W3F Grants Program.
Looking forward to the feedback.

**Comment by semuelle** [comment]
Hi @mutobui. Thank you for the submission and for your patience. I am now reviewing your milestone. 

According to the application document, deliverable `0e` should be "Article", `2` should be `pallet-dao` and `demo` should be `3`. Could you update the doc accordingly? Or did you make changes to the roadmap I am not aware of?

**Comment by mutobui** [comment]
Hey @semuelle, I have reordered the list and added the DAO feature.
In the beginning, we want to support DApps constructing their own DAO by "pallet_dao", but this job works much better in the DApps layer, thus we built Heroes and Empires Governance to let the project can deploy their DAO mechanism easily.

**Comment by semuelle** [comment]
Hey @mutobui. Thanks for the update and sorry for the late reply. 

I am generally quite impressed with the work you have done and I have ticked off most of the deliverables. However, 

a) the `Article` you linked (the Gafi whitepaper) does not really cover the work done as part of the milestone. We usually expect publication of either a high-level announcement or a technical description of what was done _within the scope of the grant_. Since I don't see any articles of this kind in your previous deliveries either (please point them out in case I missed anything), even though they were expected ("wiki.gafi.network **and** Medium"), I would like to ask you to do so now.
b) you have decided to replace the `pallet_dao` with a suite of Solidity smart contracts. While we have no strong feelings towards pallets or smart contracts, we don't usually accept Solidity deliverables. I assume you are not interested in replacing these again with a pallet, so my suggestion would be that you amend the grant application removing this deliverable and lowering the cost of M3 by one third. 

Let me know your thoughts.

**Comment by mutobui** [comment]
Hey @semuelle,
Really appreciate your advice.

a, About the Article, do you mean the "Roundup post" as we did in [M1](https://blog.gafi.network/p/the-first-milestone-of-the-gafi-network) and [M2](https://blog.gafi.network/p/the-second-milestone-of-the-gafi) in Gafi's blog: https://gafi.network/blogs, we will publish M3 announcement and Roundup same time at M3 accepted and tweet from W3F e.g: https://twitter.com/Web3foundation/status/1546756748723294209?s=20&t=oVoXg47tzY_8qlKpxLB9JQ

b, Yes, we will lower the cost of M3 by one-third.

**Comment by semuelle** [comment]
> do you mean the "Roundup post" as we did in [M1](https://blog.gafi.network/p/the-first-milestone-of-the-gafi-network) and [M2](https://blog.gafi.network/p/the-second-milestone-of-the-gafi) in Gafi's blog: [gafi.network/blogs](https://gafi.network/blogs) ?, we will publish M3 announcement and Roundup same time at M3 accepted and tweet from W3F e.g: [twitter.com/Web3foundation/status/1546756748723294209?s=20&t=oVoXg47tzY_8qlKpxLB9JQ](https://twitter.com/Web3foundation/status/1546756748723294209?s=20&t=oVoXg47tzY_8qlKpxLB9JQ)

Yes, that is exactly what I was looking for. Thanks. Do you have a draft you could add as the `Article` deliverable? It'd be okay if it was private for now.

**Comment by mutobui** [comment]
Hey @semuelle, we will work on it and let you know once we finish, probably next week 💪

**Comment by mutobui** [comment]
Hi @semuelle, I have updated the document, please take a look.

**Comment by semuelle** [comment]
Thanks for the amendment and the update, @mutobui. Your milestone is hereby accepted. See my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/gafi_milestone-3_semuelle.md).

Congratulations on completing the grant. I wish you all the best going forward, and I hope to hear from you again!

I will forward your invoice for processing.

**Comment by mutobui** [comment]
Hey @semuelle,
Thank you for the evaluation, and thanks to the W3F team.
This is an honor to build the decentralized web mission with you, I wish you all the best on this journey 💪💪

**Comment by RouvenP** [comment]
hi @mutobui we transferred the payment today.

**Pull request merged**
