### PR TITLE
Subcoin milestone 3

### PR DESCRIPTION
**Pull request by liuchengxu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2304

### CODE REVIEW

**Comment by PieWol** [comment]
Sorry for the delay @liuchengxu. I was on vacation in the meantime. I'll have an update for you shortly.

**Comment by liuchengxu** [comment]
Hey @PieWol While the final milestone is still pending review, I sent an email to grantsPR@web3.foundation two weeks ago about the Subcoin cross-promotion, but I haven't received any response, is this expected?

**Comment by liuchengxu** [comment]
@PieWol Thanks for this message. I just re-sent the email, hope it won't get lost this time :P

**Comment by PieWol** [comment]
Hey @liuchengxu , 
I almost finished the evaluation. Do I literally need to host my own bitcoin node in order to test out the transaction relaying feature? Is there a possibility to use another one which is publicly available? Asking because you are definitely more experienced than me in Bitcoin nodes. Thanks

**Comment by liuchengxu** [comment]
@PieWol Yes, you have to set up an isolated Bitcoin Core node locally otherwise you can't tell whether the transaction in the pool is relayed from the Subcoin node or the other bitcoin nodes in the network.

**Comment by liuchengxu** [comment]
Hey @PieWol Thanks for the evaluation! I still have not received a response regarding the cross-promotion after re-sending the email. Is there any other approach I can get in touch with for the cross-promotion?

**Comment by RouvenP** [comment]
hi @liuchengxu we sent both payments today

**Pull request merged**
