### PR TITLE
JetonNetwork - Polkadot Play Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by darkfriend77**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/433

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @darkfriend77. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @darkfriend77, I am looking into your delivery, and some of the tests are failing. Any idea what's missing here?

```
  Failed GetBalanceTestAsync [5 s]
  Error Message:
     Expected: True
  But was:  False

  Stack Trace:
     at IntegrationTest.Tests.GetBalanceTestAsync() in /substrateNetApi/SubstrateNetApi/IntegrationTest/LocalNodeTests.cs:line 258
```

```
  Failed GetPendingExtrinsicTestAsync [21 ms]
  Error Message:
     Expected: 0
  But was:  1

  Stack Trace:
     at IntegrationTest.Tests.GetPendingExtrinsicTestAsync() in /substrateNetApi/SubstrateNetApi/IntegrationTest/LocalNodeTests.cs:line 112
```

```
  Failed GetSystemTestAsync [23 ms]
  Error Message:
     String lengths are both 30. Strings differ at index 6.
  Expected: "3.0.0-3a1acf0-x86_64-linux-gnu"
  But was:  "3.0.0-8370ddd-x86_64-linux-gnu"
  -----------------^

  Stack Trace:
     at IntegrationTest.Tests.GetSystemTestAsync() in /substrateNetApi/SubstrateNetApi/IntegrationTest/LocalNodeTests.cs:line 214
```


```
  Failed KeyPairTest [12 ms]
  Error Message:
   System.FormatException : Invalid mnemonic
  Stack Trace:
     at dotnetstandard_bip39.BIP39.<>c__DisplayClass8_0.<MnemonicToEntropy>b__0(String word)
```

and two more tests with the same `Invalid mnemonic` exception.

**Comment by darkfriend77** [comment]
@semuelle the first error message is a bad test, as the system version changes in node template, will remove the specific part.

The second one irritates me currently and I need to dig into as it happens not in the API, it happens in a library that we include. dotnetstandard-bip39, maybe it is related to this issue https://github.com/elucidsoft/dotnetstandard-bip39/issues/1 that would also explain why it is not falling on my side with windows.

**Comment by semuelle** [comment]
Thanks for the quick reply, @darkfriend77. I have now gone through all deliverables. You can track my notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/eda66bc6b9033a17686f0838286048981b2d3f0a/evaluations/unity_sdk_1_semuelle.md).

First of all, kudos for the way you are tracking deliverables as issues. That is a great way for us (and everyone else) to follow the progress of a project. Everything looks very good overall, I just have the issue with the tests described above and a few minor follow-up questions. 

- The links for deliverables 0d and 7a are the same, was that intended? 7a contains `at least one deep dive post into each milestone subject area`, according to the contract, which I can't find;
- deliverable 6 is missing a link;
- you specified deliverable 2a with `Publish [...] with proper licensing`. I'm not quite familiar with NuGet, can you clarify how published packages there are licensed? I could only find an `author` and `requireLicenseAcceptance` tag in the package.

**Comment by darkfriend77** [comment]
@semuelle Thank you, I will go through your errors and bullet points one by one.

First the mnemonic errors and the bad test, I pushed a branch including the repo of dotnetstandard-bip39 with the [pull request](https://github.com/elucidsoft/dotnetstandard-bip39/pull/2) I made in their repo and also fixed the bad test. Please use this branch for the mnemonic test [experimental branch] (https://github.com/JetonNetwork/SubstrateNetApi/tree/replace_dotnetstandard-bip39) and the bad test.

I will dig into the next three bullet points mentioned, asap.

**Comment by darkfriend77** [comment]
@semuelle bullet 2a, thanks for the hint concerning the missing NuGet licensing properties is fixed https://github.com/JetonNetwork/Open-Grants-Program/issues/11#issuecomment-892918334

**Comment by darkfriend77** [comment]
@semuelle okay, we have added the deep dive article :-) https://github.com/JetonNetwork/Open-Grants-Program/issues/22#issuecomment-897134158

Concerning the inline code documentation, we have been through the code and added documentation where the code is not enough. https://github.com/JetonNetwork/Open-Grants-Program/issues/16#issuecomment-892966649

Hope that fits.

**Comment by Noc2** [comment]
Since @semuelle is currently ooo, I took another look at the application and I’m happy to tell you that the milestone is a pass. I will forward your invoice internally.

**Comment by RouvenP** [comment]
hi @darkfriend77 we transferred the payment today.

**Pull request merged**
