### PR TITLE
Societal Milestone 1 Grant Submission

### PR DESCRIPTION
**Pull request by gfox1**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1249

### CODE REVIEW

**Comment by randombishop** [comment]
@gfox1 Thanks for submitting this delivery. 
I'll work on evaluating it and respond with feed back in the coming days...

**Comment by gfox1** [comment]
Thanks @randombishop! Happy to answer any questions you may have.

**Comment by randombishop** [comment]
Hey @gfox1 !

I spent some time today playing with your codebase and it looks good so far, well done!

Before I write my evaluation, I have a few questions:

1) Testing guide:
I managed to run the manual tests against a dev node fine, though I didn't understand a couple of things:
- How come did the DAO end up with 800 million tokens in its treasury? Is it just a mock behaviour to facilitate testing right now that will be changed later?
- When I did the `daoCouncil-propose` step, I specified 2 as a threshold. But what if I specified 1? Would it mean I would just need my own signature? Feels like I am missing something, shouldn't the minimum number of signatures required be part of a global policy or something? Otherwise any council member can just set it to one and pass whatever they want?

2) Unit tests
I found unit tests in each pallet folder and assumed I could run them with cargo - all passed.
But could you please add a `How to run unit tests` section in your README.md?

3) Article
You commented `No article` in your delivery; does it mean this got replaced by the testing guide? If yes, please put a link to the doc. Nice bonus would be to add some context and explanations to the guide to make each step easier to understand. Like what is actually happening under the hood at each step.

4) Frontend
I tested with both Polkadot-js (all the guide) and https://github.com/sctllabs/societal-front-end (a couple of steps)
and they both worked fine.
Is there any reason why you didn't include a link to the customized template in the delivery table?
(I would have expected a link since you mentioned "minor UI updates" in the application.)

Next, I will be deep diving into the pallets source code; shooting for the end of this week to finish my evaluation.

Looking forward to hearing back from you in the meantime.

**Comment by gfox1** [comment]
Hey @randombishop, thanks for looking at this so quickly! 

Here are the answers to your questions:

> How come did the DAO end up with 800 million tokens in its treasury? Is it just a mock behavior to facilitate testing right now that will be changed later?
- Yes, it was just a mock behavior coded in the assets pallet to perform this function. We are updating it to a user inputted value.  

> When I did the daoCouncil-propose step, I specified 2 as a threshold. But what if I specified 1? Would it mean I would just need my own signature? Feels like I am missing something, shouldn't the minimum number of signatures required be part of a global policy or something? Otherwise any council member can just set it to one and pass whatever they want?
- Yes, if you specified 1 then only one of the council members would need to vote on the referenda to make it pass. We have made it like this to allow the DAO to choose how they would like the system set up. They can set up the organization to only have one council member that needs to vote or set the threshold to the max number of council members. In essence we are letting the DAO choose.

> I found unit tests in each pallet folder and assumed I could run them with cargo - all passed. But could you please add a How to run unit tests section in your README.md?

- We have added a **Unit Test** section to the [README](https://github.com/sctllabs/societal-grant-submission#unit-test), instructing the user how to run the unit tests. 
 

> You commented No article in your delivery; does it mean this got replaced by the testing guide? If yes, please put a link to the doc. Nice bonus would be to add some context and explanations to the guide to make each step easier to understand. Like what is actually happening under the hood at each step.

- I have updated the [delivery](https://github.com/sctllabs/Grant-Milestone-Delivery/blob/20a23c686067854eaa17dcdc7067fb5a32068807/deliveries/societal-milestone-1.md) to include a link to the testing guide as the article. This will replace the article. 

> Is there any reason why you didn't include a link to the customized template in the delivery table?

- I have updated the [delivery](https://github.com/sctllabs/Grant-Milestone-Delivery/blob/20a23c686067854eaa17dcdc7067fb5a32068807/deliveries/societal-milestone-1.md) to include a link to a branch of the Societal UI with the minor edits to interact with the pallets. 

Please let me know if you need something else. Thanks!

**Comment by randombishop** [comment]
@gfox1 Thanks for incorporating my remarks and updating the delivery!

Now looking into the pallets source code, I noticed it's mainly based on substrate codebase from frame/collective, frame/treasury and frame/membership.

Can you please provide a small documentation on the reasons why these pallets were copied and adapted rather than imported and re-configured or extended? What are the differences between substrate implementation and yours?

**Comment by okalenyk** [comment]
Hi, @randombishop! Thanks for the review. 

The basic idea of re-purposing the pallets is described at the top of each pallet, e.g: [dao-collective](https://github.com/sctllabs/societal-grant-submission/blob/f8da1d8c89c2be33c1108314e09db0c1d55e2e50/pallets/dao-collective/src/lib.rs#L18)

Basically, we needed to store the data and utilize the function similar to the way it's done in the pallets, except of one thing - we had to store the data per each DAO. In other words we had to update the way the pallet is handling the storage, e.g - StorageMap instead of a StorageValue or StorageDoubleMap instead of a StorageMap. We couldn't achieve this by simple re-configuring the pallet.

In the next iterations we're going to extend the pallets we re-used, for instance, adding some extended logic for the treasury pallet to handle custom assets or re-work the governance to make use of a custom token(asset) for governance.

P.S. We're using the pallets described above for managing our blockhain.

**Review by Noc2 — APPROVED** [review]

**Comment by gfox1** [comment]
@randombishop This is great news! Thanks so much for your evaluation. Looking forward to submitting milestone 2.

**Comment by gfox1** [comment]
Hey @RouvenP, if possible can we continue with the payment of USDT on Ethereum. This will make accounting much easier on our end. Thanks.

**Comment by RouvenP** [comment]
hi @gfox1 absolutely, we will proceed with UDST on Ethereum. Thanks for your feedback.

**Comment by gfox1** [comment]
Thanks @RouvenP!

**Comment by RouvenP** [comment]
hi @gfox1 we transferred the payment today.

**Comment by gfox1** [comment]
Hi @RouvenP, thanks! We have received the payment.

**Pull request merged**
