### PR TITLE
Decentralized well being game api

### PR DESCRIPTION
**Pull request by iumairazhar**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ x] This pull request is being made by the same account as the accepted application.
- [ x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/675< please fill this in with the PR number of your application.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the delivery. We will look into this as soon as possible. In the meantime, the deliverables don’t seem to match the ones in the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/decentralized_well-being_game_api.md). Could you update this and in case you implemented something differently, explain why?

**Comment by iumairazhar** [comment]
@Noc2 sure, let me confirm the delivery and applications matches each other.

**Comment by iumairazhar** [comment]
Hi @Noc2  Hope all is well, I just wanted to circle back and see if there was anything else you need from me or the team for the submission? Thank you.

**Comment by Noc2** [comment]
@iumairazhar  Sorry. I haven’t looked into it yet. It might also take a little bit longer, since most of the team is on a business trip or ooo this week.

**Comment by iumairazhar** [comment]
> @iumairazhar Sorry. I haven’t looked into it yet. It might also take a little bit longer, since most of the team is on a business trip or ooo this week.

sure, no worries let me know if anything needed

**Review by Noc2 — CHANGES_REQUESTED** [review]
I finally started to quickly look into your delivery, [see here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/decentralized_well-being_game_api_1_Noc2.md). However, this seems a lot different than the original contract. For example the ink smart contract doesn’t seem to have any of the functionality, which you described in the original application. Also I couldn’t find any testing guide or tutorial about your project. Also not sure about the state channel backend in rust (which is implemented in go [here](https://github.com/perun-network/go-perun), but even the go implementation seems not part of your repo. Let me know in case I’m missing something.

**Comment by iumairazhar** [comment]
> I finally started to quickly look into your delivery, [see here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/decentralized_well-being_game_api_1_Noc2.md). However, this seems a lot different than the original contract. For example the ink smart contract doesn’t seem to have any of the functionality, which you described in the original application. Also I couldn’t find any testing guide or tutorial about your project. Also not sure about the state channel backend in rust (which is implemented in go [here](https://github.com/perun-network/go-perun), but even the go implementation seems not part of your repo. Let me know in case I’m missing something.

Let me confirm with Team, that everything is pushed and up to date with the application.

**Comment by iumairazhar** [comment]
We are working on things, will submit as soon as I have an update thanks

**Comment by iumairazhar** [comment]
@Noc2 
Hope all is well. Just wanted to follow up and send you an update. The team is currently working on the latest stages of the project so we wanted to let you know that things are moving smoothly on our side.

**Comment by Noc2** [comment]
@iumairazhar Just to double check: Are you still working on this? What is the current status?

**Comment by iumairazhar** [comment]
> @iumairazhar Just to double-check: Are you still working on this? What is the current status?

Hi @Noc2,
Hope all is well and thank you for your message. We are currently in progress working on the smart contracts and some workaround perun. We apologize for the small delay in getting back to you but we will keep you posted as soon as we're ready to submit. In the meantime, we'll send another update by Monday and keep you in the loop.
Thank you in advance

**Comment by Noc2** [comment]
Thanks for the update.

**Comment by Noc2** [comment]
Just a quick update: I’m going to close the PR for now due to inactivity, since it seems this will take a little bit longer. Feel free to ping me in case I should reopen it or simply submit a new PR once you are ready.

**Pull request closed without merging**
