### PR TITLE
Deliver Solang_developer_experience_improvements Milestone 1

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1334

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @salaheldinsoliman, here you can find my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/solang_developer_experience_improvments_1_keeganquigley.md). I'm happy to pass this milestone and thanks for all the hard work. The Solang project is pretty cool.

**Comment by keeganquigley** [comment]
The actions failed because the application contains a **Project Name** instead of **Team Name** so I will paste the M1 completion message below:

Congratulations on completing the first milestone of this grant! As part of the Grants Program, we want to help grant recipients acknowledge their grants publicly. To that end, we’ve created a [badge for projects](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md) that successfully deliver their first milestone. Note that it must only be used within the context of the delivered work, so please do not display it on your team or project's homepage unless accompanied by a short description of the grant.

Furthermore, you're now welcome to announce the grant publicly. Please remember to observe the [foundation’s guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/announcement-guidelines.md) in doing so. In case you haven't done so yet, you may also reach out to [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) for feedback on your announcement and cross-promotion.

Thank you for your contribution and good luck with the remaining milestones, if any! As usual, please let us know if you run into any delays by leaving a comment on the application PR, or directly submitting an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Comment by keeganquigley** [comment]
@salaheldinsoliman Have you submitted an invoice already? I'm not finding it.

**Comment by salaheldinsoliman** [comment]
@keeganquigley Hello, I have submitted an invoice at the time of submitting the delivery document

**Comment by keeganquigley** [comment]
Ah thanks @salaheldinsoliman I found it under your name. I will forward it internally for processing.

**Comment by salaheldinsoliman** [comment]
@keeganquigley Hello keegan, please contact me ASAP concerning my innovice. It seems that I have uploaaded a wrong Ethereum address. Thanks

**Comment by keeganquigley** [comment]
Thanks @salaheldinsoliman can you also submit a new invoice with the updated address? Along with the amendment PR to change the address on the application. Thanks!

**Comment by salaheldinsoliman** [comment]
@keeganquigley I submitted a new one including the link for the PR in the notes sections. Thanks for your help!

**Comment by RouvenP** [comment]
hi @salaheldinsoliman we transferred the payment today.

**Comment by salaheldinsoliman** [comment]
@RouvenP Received! Thanks

**Pull request merged**
