### PR TITLE
ventur milestone 2

### PR DESCRIPTION
**Pull request by Gryczka**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1126

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @Gryczka thank you for the delivery. Someone will be assigned to look at it shortly.

**Comment by 0xCaso** [comment]
Hi @Gryczka, I started the evaluation, and I'll reach out if I need help!

**Comment by 0xCaso** [comment]
Here I am, I left my notes in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ventur_2_0xCaso.md). Looking forward the answers to my comments/questions :)

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Here I am, I left my notes in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ventur_2_0xCaso.md). Looking forward the answers to my comments/questions :)

**Comment by Gryczka** [comment]
Hi @0xCaso, thank you for taking the time to review our delivery!  We appreciate the feedback.

0a. License

Confirming we switched to GPLv3, we found it to be a better fit for the project.  Noted in our Notes for Milestone 1 and 2.


0c. Testing Guide

The cancel assignment function should allow both user B to reject it and user A to cancel it.

(The function checks that the account signing the transaction is either the owner of the nft or the target of the assignment.)

Currently the 'Reject Assignment' path in the guide shows account A (Alice in the screenshots) creating the collection and minting individual items, and account B (Ferdie in this step's screenshots) rejecting the assignment.

But having A both create, assign, and then reject(cancel) would also work with the same extrinsic.


1. Substrate module: rfp-process

1. Is it ok if I managed to accept a bid without editing the payment details? 

Could you expand on this question, is the question whether we have functional requirements to prevent Alice from creating an RFP, and then bidding and accepting her own bid?

If so, we do not have preventing self bidding as a functional requirement.  

Arguably, certain organizations could go through an RFP process to validate their internal costs against contractors before proceeding to still accept their own bid.  Although, it might make sense for us to add a flag to explicitly note RFPs where self bidding is allowed.

2. When you have to bid, why do you need to input all the rfp parameters when it should be needed just the id (and the other params could be obtained with a free query)?

Out thinking on this was prioritizing preserving node storage by not storing data twice in both an RFP storage and Owner->RFP storage.  Our RFPs are currently stored as a double map of Owner ID and RFP ID, which allows us to iterate over all RFPs for a single owner.  We don't have a storage item for querying RFPs solely by ID.

We envisioned that in dApps interacting with RFPs, most bids would likely be taking place in front-ends when the RFP data is being viewed, so when it is listed and available to provide further to the bid function.

This might be an overly conservative or naive approach, but I think it's one we'll be able to analyze better down the road once we have a test net up and running.

3. What’s the purpose of shortlisting before being able to accept a bid?

This seemed like a standard process for us, where you would want to finalize discussions with a subset of bids before accepting one.  But it's reasonable to ask whether this makes sense for all applications.

We have updated the rfp pallet to make shortlisting optional.

4. The payment seems completely detached from the rfp, apart from the rfpReferenceId param (e.g., I can put payer X and payee Y, with X and Y ≠ from the rfp/bids actors). Is this ok? This way, an rfp owner can accept the bid without actually paying the bidder, or am I wrong?

This is by design, to allow the RFP creator to specify other accounts, such as other accounts with funds in escrow (escrow pallet) that they are admins for.  Payment permissions are validated on the payment pallet.

**Comment by 0xCaso** [comment]
Thanks a lot @Gryczka for the detailed answers! 

About the `cancelAssignment` function, I retried it and worked both for A and B actors, probably I did something wrong the other day, thanks!

The questions about the `rfp-process` pallet are intended as point of discussion to understand better the choices of your team, and now I get all of them and I think you have weighed them well. Also I agree with making optional some parameters!

I'll post the updated evaluation soon :)

**Review by 0xCaso — APPROVED** [review]

**Comment by 0xCaso** [comment]
Congrats @Gryczka, the delivery has been accepted!

One last thing: could you please add the VAT amount in your invoice (it should be 0)?
Thanks a lot!

**Comment by Gryczka** [comment]
Resubmitted the invoice with added 'VAT amount' of 0.

Thanks again @0xCaso!

**Comment by RouvenP** [comment]
hi @Gryczka we transferred the payment.

**Comment by Gryczka** [comment]
Hi @RouvenP confirming, received.

**Pull request merged**
