### PR TITLE
add solang playground milestone 2

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] This pull request is being made by the same account as the accepted application.
- [X] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [X] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1894

### CODE REVIEW

**Comment by dsm-w3f** [comment]
Hi, we'll evaluate this milestone.

**Comment by dsm-w3f** [comment]
@salaheldinsoliman thanks for the milestone delivery. We did a first round of evaluation. Please take a look at the document in [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1188) and provide proper answers and fixes. After that, let me know to continue this evaluation.

**Comment by salaheldinsoliman** [comment]
@dsm-w3f Hi, 
We have addressed your comments, and accordingly updated the .md file.

**Comment by dsm-w3f** [comment]
@salaheldinsoliman thank you for the improvements and fixes. We checked again and we still having problems to run the docker version of the application. Please see [the evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1188) for details. Please let me know when we can continue this evaluation.

**Comment by tareknaser** [comment]
Hey @dsm-w3f

Sorry about the trouble with the docker image! Solang released a new version 7 days ago, and we needed to update `solang-playground` as well. I pushed a commit with the fix and updated `solang-playground` images on Docker Hub. I also included more verbose instructions on how to run the docker image.

Give it another try - this should resolve the issue you were seeing. Let us know if you run into any other issues.

**Comment by dsm-w3f** [comment]
@tareknaser and @salaheldinsoliman thank you for the improvements and fixes. We tested again and the docker is working. This milestone is approved from my side. Great work!

**Comment by semuelle** [comment]
Sorry, @salaheldinsoliman, this milestone somehow slipped through the cracks. It's now approved.

**Pull request merged**
