### PR TITLE
Create ParaSpell-followup2-m1.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1589

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @dudo50 someone will take a look at it shortly.

**Comment by dsm-w3f** [comment]
@dudo50 thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/paraspell_followup2_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by dudo50** [comment]
Hello @dsm-w3f,
- As for derivable 2, it is tested in our scripts for assets, compatible pallets and command to test it can be found here https://github.com/paraspell/xcm-sdk#-development (`pnpm runAll `- this will update both pallets and assets maps for all nodes including new ones)
- As for derivable 3, we will add new tests as requested asap along with guide on testing them (This change is mostly to reduce code reuse and make it cleaner and easier to modify so does not really require tests however we will try to add some for you).
- When I clean-pulled the V2 repo I did not receive the same issue on my laptop (Tested on Mac and Ubuntu), could you switch to the stable node 18 version? The issue is mentioned and resolved here: https://github.com/nuxt/nuxt/issues/19682
Screenshot 2023-04-21 at 01 22 45
- As for derivable 5, as stated, we do not control the Sub-Scaffold repository anymore, it is under Kodadot maintenance. We could only open an issue (And this was done as an extra). The main commit was a Phase 1 suggestion with links. 

Hope this answered all your questions for now,
If any new arise, feel free to ping us,
With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Hey @dsm-w3f, derivable 3 is now merged and tests were added as you requested. You can run them with command `pnpm runAll` and you will be able to see all newly nodes tested just as shown on image below:
Screenshot 2023-04-21 at 20 23 04
Hope this resolves all your questions.
With kind regards,
Team ParaSpell

**Comment by dsm-w3f** [comment]
@dudo50 thank you for the improvements and fixes. The remainder parts of the application are working now. There is a small fix to do but don't prevent the acceptance of the milestone, see the details in the evaluation document. The milestone is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great work!

**Comment by dudo50** [comment]
Thank you, I will check the evaluation and make sure that that small issue is resolved asap. 
Once again thanks for your time.
With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
@dsm-w3f can you please check with the team if we have submitted an invoice (Could have happened that I have forgotten by mistake)? Because we haven't received any info since last week. Many thanks!
With kind regards,
Team ParaSpellll.

**Comment by dsm-w3f** [comment]
@dudo50 Yes, your invoice was received and forwarded internally. It could take two weeks to process the payment. I think next week should be paid.

**Comment by dudo50** [comment]
Great to hear that it was received correctly @dsm-w3f . Many thanks for info. Have nice rest of the day.
With kind regards,
Team ParaSpell

**Comment by RouvenP** [comment]
hi @dudo50 we transferred the payment today.

**Comment by dudo50** [comment]
@RouvenP thank you for letting us know.
With kind regards,
Team ParaSpell

**Pull request merged**
