### PR TITLE
Infimum: milestone 1

### PR DESCRIPTION
**Pull request by rhysbalevicius**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1948

### CODE REVIEW

**Review by takahser — CHANGES_REQUESTED** [review]
@rhysbalevicius currently the build fails when run on my machine. I've added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/infimum_1_takahser.md), lmk if you have any questions.

**Comment by rhysbalevicius** [comment]
Hey @takahser, thanks for the review!

For the Docker build I suspect that there is a versioning mismatch. To help narrow things down I've pinned the docker images, do you mind repulling the branch (or recloning) and trying them again? If you run into the same error, do you mind sharing the output of `docker --version`? To resolve the issue we may need to bump the version of Docker you're using. I can confirm that it's working on version 24.0.2, build cb74dfc (macOS 14.0) and 25.0.2, build 29cf629 (Ubuntu 22.04).

As for the error messages encountered when running the tests, do you mind trying to run them in a fresh shell and see if the issue reproduces? The output containing the warnings referenced is specifically related to line 6 of pos_build.Dockerfile which appears to be a [Dockerfile](https://github.com/wetee-dao/chain/blob/main/pos_build.Dockerfile) from a separate milestone you're evaluating (WeTee Network - M1). After those lines I see the tests from this evaluation running and exiting normally.

Let me know if you hit any other snags - I appreciate you taking the time to step through this with me.

**Review by takahser — CHANGES_REQUESTED** [review]
@rhysbalevicius I've tried again using the latest changes, but the Docker build is still failing:

```zsh
infimum % git rev-parse HEAD
6d0bac54cf0c056789f04a8d5a607b355e8505c9

infimum % docker compose --profile dev up
[+] Running 1/1
 ! pallet-base Warning                                                                                                                                      3.8s 
[+] Building 27.3s (5/15)                                                                                                                                                              docker:desktop-linux
 => [pallet-base internal] load build definition from Dockerfile.base                                                                                                                                  0.0s
 => => transferring dockerfile: 806B                                                                                                                                                                   0.0s
 => [pallet-base internal] load .dockerignore                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                        0.0s
 => [pallet-base internal] load metadata for docker.io/library/rust:1.74.1-slim                                                                                                                        3.1s
 => ERROR [pallet-base  1/11] FROM docker.io/library/rust:1.74.1-slim@sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf                                                         24.1s
 => => resolve docker.io/library/rust:1.74.1-slim@sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf                                                                              0.0s
 => => sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf 984B / 984B                                                                                                             0.0s
 => => sha256:e6ed1bc5dee5d6fa8bb1c5a92565ba8037c84491545f494a073599c3a079c903 742B / 742B                                                                                                             0.0s
 => => sha256:db03bffb7019f4c2fe42d020cff55928ca6873c264bf1fc54d29d3569e3696ab 4.86kB / 4.86kB                                                                                                         0.0s
 => => sha256:24e221e92a36ab5b0075dd156b4f2ff095532a9b0927946cf6070bb1bea208b8 29.16MB / 29.16MB                                                                                                       2.4s
 => => sha256:6de2b1bae375f8282350ed3de56e7f12bf160649d06ffb78518bd74bb71b8d1d 315.80MB / 315.80MB                                                                                                    19.0s
 => => extracting sha256:24e221e92a36ab5b0075dd156b4f2ff095532a9b0927946cf6070bb1bea208b8                                                                                                              1.8s
 => => extracting sha256:6de2b1bae375f8282350ed3de56e7f12bf160649d06ffb78518bd74bb71b8d1d                                                                                                              5.0s
 => [pallet-base internal] load build context                                                                                                                                                          6.6s
 => => transferring context: 1.20GB                                                                                                                                                                    6.1s
------
 > [pallet-base  1/11] FROM docker.io/library/rust:1.74.1-slim@sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf:
------
failed to solve: failed to register layer: write /usr/local/rustup/toolchains/1.74.1-aarch64-unknown-linux-gnu/lib/librustc_driver-ab5467781feb79bd.so: no space left on device
```

My docker version is slightly newer:

```zsh
infimum % docker --version
Docker version 24.0.7, build afdd53b
```

Same for my OS: 14.3 (23D56).

Regarding the "no space left on device" error, at the time of running I had like 15GB of free RAM and 714GB free disk space:
image
image

I've also re-ran the tests which now pass without any errors or warning. I've updated the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/infimum_1_takahser.md) accordingly.

**Comment by rhysbalevicius** [comment]
Hey @takahser, thanks for the follow up.

Typically for Docker I've seen the "no space left on device" or "out of memory" errors actually refer to the resources that the user has provisioned for Docker. I believe this particular error message is referring to the total disk space available to Docker on your machine.

The resources that are available to Docker might be being consumed by other images, build caches, etc., that are no longer needed, and can be reclaimed with [`docker system prune`](https://docs.docker.com/engine/reference/commandline/system_prune/) (you can check if there is any reclaimable disk space with [`docker system df`](https://docs.docker.com/engine/reference/commandline/system_df/)).

As a baseline, I can confirm that on my machine (Macbook Air M1), I've allocated 2 CPUs, 4GB Memory, 2GB Swap Memory, and a Virtual disk limit of 128GB is sufficient (with 100gb of the allocated disk space unused). Could you confirm if you've provisioned similar resources, and if no space is reclaimable, could you increase the limit and try again? 

To increase the resource limits available to Docker:
- If you're using Docker Desktop, you can navigate to Docker Desktop > Settings > Resources to check and control the provisioned resources.
- If you're using a CLI only installation, you can check the available resources by running `docker info`. I personally use Docker desktop, and am unsure as to how to increase the limit via the CLI. Apparently you can edit a [local config file](https://stackoverflow.com/a/47521652/19945291) and restart the docker daemon (let me know if this is applicable to you and I can dig into this more).

Thanks again for your time.

**Comment by takahser** [comment]
@rhysbalevicius according to `docker info` the total memory is `7.662GiB` before running `docker system prune`:

```zsh
infimum % docker info
Client:
 Version:    24.0.7
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     /Users/xxx/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     /Users/xxx/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/xxx/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     /Users/xxx/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     /Users/xxx/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     /Users/xxx/.docker/cli-plugins/docker-scout

Server:
 Containers: 5
  Running: 0
  Paused: 0
  Stopped: 5
 Images: 5
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: xxxx
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.5.11-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.662GiB
 Name: docker-desktop
 ID: xxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: daemon is not using the default seccomp profile
```

After running it, it reclaimed 23GB:

```zsh
infimum % docker system prune

(...)

Total reclaimed space: 23.31GB
```

However, the total memory was still `7.662GiB` after that, since I think we're comparing RAM to disk space here. Anyway, after that I tried spinning up the docker infrastructure again and I got a different error this time:

```zsh
infimum % docker compose --profile dev up
[+] Running 1/1
 ! pallet-base Warning                                                                                                                                                                                  3.3s 
[+] Building 745.9s (15/15) FINISHED                                                                                                                                                    docker:desktop-linux
 => [pallet-base internal] load .dockerignore                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                         0.0s
 => [pallet-base internal] load build definition from Dockerfile.base                                                                                                                                   0.0s
 => => transferring dockerfile: 806B                                                                                                                                                                    0.0s
 => [pallet-base internal] load metadata for docker.io/library/rust:1.74.1-slim                                                                                                                         3.7s
 => [pallet-base  1/11] FROM docker.io/library/rust:1.74.1-slim@sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf                                                               117.7s
 => => resolve docker.io/library/rust:1.74.1-slim@sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf                                                                               0.0s
 => => sha256:53596c66027523b2289c6e7c96bff119416be22d2cf52734b4962e13371c54cf 984B / 984B                                                                                                              0.0s
 => => sha256:e6ed1bc5dee5d6fa8bb1c5a92565ba8037c84491545f494a073599c3a079c903 742B / 742B                                                                                                              0.0s
 => => sha256:db03bffb7019f4c2fe42d020cff55928ca6873c264bf1fc54d29d3569e3696ab 4.86kB / 4.86kB                                                                                                          0.0s
 => => sha256:24e221e92a36ab5b0075dd156b4f2ff095532a9b0927946cf6070bb1bea208b8 29.16MB / 29.16MB                                                                                                        9.7s
 => => sha256:6de2b1bae375f8282350ed3de56e7f12bf160649d06ffb78518bd74bb71b8d1d 315.80MB / 315.80MB                                                                                                    113.3s
 => => extracting sha256:24e221e92a36ab5b0075dd156b4f2ff095532a9b0927946cf6070bb1bea208b8                                                                                                               0.9s
 => => extracting sha256:6de2b1bae375f8282350ed3de56e7f12bf160649d06ffb78518bd74bb71b8d1d                                                                                                               4.1s
 => [pallet-base internal] load build context                                                                                                                                                           5.6s
 => => transferring context: 1.27GB                                                                                                                                                                     5.6s
 => [pallet-base  2/11] RUN ln -snf /usr/share/zoneinfo/America/New_York /etc/localtime && echo America/New_York > /etc/timezone                                                                        0.4s
 => [pallet-base  3/11] RUN rustup update     && rustup update nightly     && rustup target add wasm32-unknown-unknown                                                                                111.8s
 => [pallet-base  4/11] RUN apt-get update -y && apt-get install -y     build-essential     clang     curl     git     libssl-dev     protobuf-compiler                                                71.3s 
 => [pallet-base  5/11] RUN git clone --branch infimum https://github.com/rhysbalevicius/substrate-node-template /node                                                                                 99.3s 
 => [pallet-base  6/11] COPY ./.dev/Cargo.toml ./node/Cargo.toml                                                                                                                                        0.0s 
 => [pallet-base  7/11] COPY ./.dev/runtime/Cargo.toml ./node/runtime/Cargo.toml                                                                                                                        0.0s 
 => [pallet-base  8/11] COPY ./.dev/runtime/src/lib.rs ./node/runtime/src/lib.rs                                                                                                                        0.0s 
 => [pallet-base  9/11] COPY ./pallet ./node/pallets/infimum                                                                                                                                            2.0s 
 => [pallet-base 10/11] WORKDIR /node                                                                                                                                                                   0.0s 
 => ERROR [pallet-base 11/11] RUN cargo build --release                                                                                                                                               339.6s
------                                                                                                                                                                                                       
 > [pallet-base 11/11] RUN cargo build --release:                                                                                                                                                            
0.164 info: syncing channel updates for 'nightly-aarch64-unknown-linux-gnu'                                                                                                                                  
0.905 info: latest update on 2024-02-09, rust version 1.78.0-nightly (98aa3624b 2024-02-08)                                                                                                                  
0.935 info: component 'cargo' for target 'aarch64-unknown-linux-gnu' is up to date                                                                                                                           
0.935 info: component 'rust-std' for target 'aarch64-unknown-linux-gnu' is up to date                                                                                                                        
0.935 info: component 'rustc' for target 'aarch64-unknown-linux-gnu' is up to date
0.936 info: downloading component 'clippy'

(...)

85.15 info: installing component 'rustfmt'
85.44 warning: virtual workspace defaulting to `resolver = "1"` despite one or more workspace members being on edition 2021 which implies `resolver = "2"`
85.44 note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
85.44 note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
85.44 note: for more details see https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions
85.47     Updating crates.io index
85.64     Updating git repository `https://github.com/paritytech/substrate.git`
151.1     Updating git repository `https://github.com/paritytech/polkadot-sdk.git`
310.5  Downloading crates ...
311.6   Downloaded atty v0.2.14

(...)

336.7    Compiling cc v1.0.79
336.7    Compiling rand_core v0.6.4
336.8 error[E0635]: unknown feature `stdsimd`
336.8   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.6/src/lib.rs:33:42
336.8    |
336.8 33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
336.8    |                                          ^^^^^^^
336.8 
336.8    Compiling parking_lot v0.12.1
336.8 For more information about this error, try `rustc --explain E0635`.
336.8    Compiling rand_chacha v0.3.1
336.8 error: could not compile `ahash` (lib) due to 1 previous error
336.8 warning: build failed, waiting for other jobs to finish...
------
failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 101
```

I'll be OOO next week, so I'll be able to do another iteration on Monday the week after (19th March).

**Comment by rhysbalevicius** [comment]
Hey @takahser hope you had some nice time off :-) 

Looks like the issue was with an dependency upstream to substrate - I've bumped ahash to v0.7.8 and updated the pallet lock file, so will need to re-pull on your end once you revisit this evaluation.

I've been able to reproduce the environment on a setup similar to yours so hopefully we have better luck the next time around, but please feel free to reach out for anything at all.

**Comment by takahser** [comment]
@rhysbalevicius I confirm that the docker issues have been resolved, see my [updated evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/infimum_1_takahser.md). I'm still in the process of testing the extrinsics related to M1 and will be back with more feedback tomorrow.

**Review by takahser — COMMENTED** [review]
@rhysbalevicius thanks for your patience here, it's greatly appreciated! I've taken a closer look at the delivery and the following questions came up:

- In your proposal you mention two extrinsics called `commitProcessedMessages` and `commitTallyResult` that are supposed to be part of M1, however, they're not part of this delivery. Instead, there is an exstrinsic called `commitOutcome` that isn't specified in the proposal. Could you comment on that mismatch?
- The [Usage Guide](https://github.com/rhysbalevicius/infimum/tree/m0?tab=readme-ov-file#usage) covers a couple of extrinsics but by far not all of them. Why is that?

Thanks.

**Comment by rhysbalevicius** [comment]
>  In your proposal you mention two extrinsics called `commitProcessedMessages` and `commitTallyResult` that are supposed to be part of M1, however, they're not part of this delivery. Instead, there is an exstrinsic called `commitOutcome` that isn't specified in the proposal. Could you comment on that mismatch?

Great question @takahser. 

The `commitOutcome` extrinsic was decided on unifying both of the `commitProcessedMessages` and `commitTallyResult` extrinsics. We feel this decision simplifies the interface and reduces code duplication. There are similar (but lower priority) plans to unify `rotateVerifyKey` and `rotatePublicKey` into a singular `rotateKeys` extrinsic.

The deeper motivation however is to remove certain assumptions as to how the underlying cryptographic scheme is designed. For example, one can imagine a scheme wherein the tally is homomorphically computed “on-chain”. In such a scheme it is no longer necessary for a coordinator to process and tally votes, and then commit the results, as that is already done, they would only be responsible for providing a proof of the decrypted result. 

To summarize, the change is part of an ongoing (long term) effort for the project to provide a generic interface in order to afford greater flexibility with respect to innovating upon the underlying cryptographic scheme. The scheme used within the scope of this grant will effectively rely on the `commitOutcome` extrinsic to perform the duties of both of `commitProcessedMessages` and `commitTallyResult` where the coordinator is responsible for providing the generated proofs in the correct order (rather than calling two separate extrinsics in order).

> The [Usage Guide](https://github.com/rhysbalevicius/infimum/tree/m0?tab=readme-ov-file#usage) covers a couple of extrinsics but by far not all of them. Why is that?

This is a fair thing to point out. In it's current state the pallet is not usable as it largely depends on the deliverables outlined in M2 so it felt inappropriate, if not misleading to the reader, to include any further details there. However, if it would make you more comfortable with the acceptance criteria I can include additional commentary on the extrinsics and their parameters to the readme.

**Review by takahser — CHANGES_REQUESTED** [review]
@rhysbalevicius 

> The `commitOutcome` extrinsic was decided on unifying both of the `commitProcessedMessages` and `commitTallyResult` extrinsics. We feel this decision simplifies the interface and reduces code duplication. There are similar (but lower priority) plans to unify `rotateVerifyKey` and `rotatePublicKey` into a singular `rotateKeys` extrinsic.

If that's the case, could you amend the original proposal accordingly? This should be easy to approve from our side.

> This is a fair thing to point out. In it's current state the pallet is not usable as it largely depends on the deliverables outlined in M2 so it felt inappropriate, if not misleading to the reader, to include any further details there. However, if it would make you more comfortable with the acceptance criteria I can include additional commentary on the extrinsics and their parameters to the readme.

Thanks for ellaborating. That's fine by me. But please include it in the next milestone (also in the guide), since they'll become usable.

**Comment by rhysbalevicius** [comment]
> If that's the case, could you amend the original proposal accordingly? This should be easy to approve from our side.

No problem @takahser, I've opened an [amendment PR here](https://github.com/w3f/Grants-Program/pull/2230). 

> Thanks for ellaborating. That's fine by me. But please include it in the next milestone (also in the guide), since they'll become usable.

Absolutely, will do.

**Review by takahser — APPROVED** [review]
@rhysbalevicius thanks for the amendment, LGTM now. Please don't forget to cover the missing extrinsics in the docs/tutorial for M2. You can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/infimum_1_takahser.md).

**Comment by RouvenP** [comment]
hi @rhysbalevicius we sent the payment today

**Pull request merged**
