### PR TITLE
Threshold Signature Implementation: Milestone 1 Delivery

### PR DESCRIPTION
**Pull request by Fiono11**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2250

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @Fiono11, thanks for the delivery, but you are currently modifying the template. Could you use a copy of the template (as per [the instructions](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/README.md#mailbox-milestone-delivery-process)) and resubmit?

**Comment by Fiono11** [comment]
> Hi @Fiono11, thanks for the delivery, but you are currently modifying the template. Could you use a copy of the template (as per [the instructions](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/README.md#mailbox-milestone-delivery-process)) and resubmit?

Done!

**Review by semuelle — APPROVED** [review]
Thank you for the milestone delivery, @Fiono11. Your milestone is hereby accepted. If you haven't yet, please submit your invoice through our invoice form: https://forms.gle/Rv8MhXt13m7GB4MB7

**Comment by Fiono11** [comment]
> Thank you for the milestone delivery, @Fiono11. Your milestone is hereby accepted. If you haven't yet, please submit your invoice through our invoice form: https://forms.gle/Rv8MhXt13m7GB4MB7

Thank you! In the application the selected payment method was USDC, is it possible to change it to fiat?

**Comment by semuelle** [comment]
> Thank you! In the application the selected payment method was USDC, is it possible to change it to fiat?

Sure. Please submit a PR with "fiat" instead of payment address and send us your banking details by email. Instructions are [here](https://github.com/w3f/Grants-Program/blob/abfde65cfd9682082cb3eb3ca9156670423542ac/applications/application-template.md?plain=1#L10).

**Pull request merged**
