### PR TITLE
Deliver DelightfulDOT M1

### PR DESCRIPTION
**Pull request by sinzii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1907

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @sinzii I have started on this today. Should I be using the `w3f-delivery/m1` branch for everything or `main`? Thanks!

**Comment by sinzii** [comment]
Hi @keeganquigley, please use the branch `w3f-delivery/m1` for M1 evaluation. The main branch is now containing commits for M2. Thank you!

**Comment by keeganquigley** [comment]
Thanks @sinzii much appreciated! Everything is looking great except for a couple of unit tests that are failing:

```ts
> @delightfuldot/codecs:test


 RUN  v0.34.6 /Users/keeganquigley/delightfuldot/packages/codecs

 ✓ src/generic/__tests__/Header.spec.ts  (3 tests) 3ms
 ❯ src/registry/__tests__/CodecRegistry.spec.ts  (15 tests | 2 failed) 12ms
   ❯ src/registry/__tests__/CodecRegistry.spec.ts > CodecRegistry > with metadata > findCodec > should supports wrapper type
     → inspect is not a function
   ❯ src/registry/__tests__/CodecRegistry.spec.ts > CodecRegistry > with metadata > findPortableCodec > should find existing codec
     → inspect is not a function
 ✓ src/metadata/__tests__/Metadata.spec.ts  (4 tests) 79ms

⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/registry/__tests__/CodecRegistry.spec.ts > CodecRegistry > with metadata > findCodec > should supports wrapper type
TypeError: inspect is not a function
 ❯ Shape._inspect ../../node_modules/subshape/src/common/shape.ts:68:33
 ❯ Shape.[nodejs.util.inspect.custom] ../../node_modules/subshape/src/common/shape.ts:45:17
 ❯ src/registry/__tests__/CodecRegistry.spec.ts:63:21
     61|
     62|       it('should supports wrapper type', () => {
     63|         expect(util.inspect(registry.findCodec('Option<u32>'))).toEqua…
       |                     ^
     64|         expect(util.inspect(registry.findCodec('Vec<u32>'))).toEqual('…
     65|         expect(util.inspect(registry.findCodec('Result<u32, bool>'))).…

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  src/registry/__tests__/CodecRegistry.spec.ts > CodecRegistry > with metadata > findPortableCodec > should find existing codec
TypeError: inspect is not a function
 ❯ Shape._inspect ../../node_modules/subshape/src/common/shape.ts:68:33
 ❯ Shape.[nodejs.util.inspect.custom] ../../node_modules/subshape/src/common/shape.ts:45:17
 ❯ src/registry/__tests__/CodecRegistry.spec.ts:96:21
     94|     describe('findPortableCodec', () => {
     95|       it('should find existing codec', () => {
     96|         expect(util.inspect(registry.findPortableCodec(1))).toEqual('$…
       |                     ^
     97|         expect(registry.findPortableCodec(2)).toEqual($.u8);
     98|         expect(registry.findPortableCodec(4)).toEqual($.u32);

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯

 Test Files  1 failed | 2 passed (3)
      Tests  2 failed | 20 passed (22)
   Start at  21:10:18
   Duration  803ms (transform 155ms, setup 0ms, collect 855ms, tests 94ms, environment 590ms, prepare 141ms)


 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  Lerna (powered by Nx)   Running target test for 4 projects failed

   Tasks not run because their dependencies failed or --nx-bail=true:

   - delightfuldot:test

   Failed tasks:

   - @delightfuldot/codecs:test
   - ```

**Comment by sinzii** [comment]
@keeganquigley Thank you for the feedback. May I ask which OS, Node version that you are using for running tests.

The tests are running fine in my environment (MacOS, Node v18.14.2) and also on [GH action](https://github.com/CoongCrafts/delightfuldot/actions/runs/7513482944/job/20455290787) (Ubuntu, Node v18.19.0). So this is probably due to some OS or Node version specific issue.

**Comment by keeganquigley** [comment]
Hi @sinzii thanks I was able to get it running on both Ubuntu and Codespaces, so it must have been an issue with my Mac. I'm happy to pass the milestone, great work! Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/delightfuldot_1_keegan.quigley.md). Everything is working out of the box. Any chance for light clients to be supported in the future?

Looking forward to the next one.

**Comment by sinzii** [comment]
@keeganquigley Wonderful! Thank you for the evaluation!

> Any chance for light clients to be supported in the future?

Definitely, this is on our roadmap for the future!

> Please fill out the invoice form in order to initiate the payment process.

I did submit the invoice at the time I created the PR, but I've just resubmitted again just in case!

**Comment by RouvenP** [comment]
hi @sinzii we sent the payment today

**Comment by sinzii** [comment]
@RouvenP Thank you, we've received the fund!

**Pull request merged**
