### PR TITLE
Create milestone 2 delivery for Coong Wallet

### PR DESCRIPTION
**Pull request by sinzii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1387.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @sinzii your milestone had an accepted [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/coong_wallet_2_si.md) from an external evaluator, and I was able to play around with the wallet as well and verify that all the tests passed. Therefore I am happy to pass it. Great work!

**Comment by sinzii** [comment]
Thank you @keeganquigley!

**Comment by RouvenP** [comment]
hi @sinzii we transferred the payment today.

**Comment by sinzii** [comment]
Thank you @RouvenP, we've received the fund!

**Pull request merged**
