### PR TITLE
Create Afloat_Milestone3.md

### PR DESCRIPTION
**Pull request by LouiseWReed**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/911 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by randombishop** [comment]
Hey @LouiseWReed ! Glad to see a new delivery from Afloat. Will work on the evaluation and get back to you with feedback in next couple of days...

**Comment by AugustoLara** [comment]
> Hey @LouiseWReed ! Glad to see a new delivery from Afloat. Will work on the evaluation and get back to you with feedback in next couple of days...

Thanks @randombishop . We also have M4 ready. Can we submit it too?

**Comment by AugustoLara** [comment]
> Hey @LouiseWReed ! Glad to see a new delivery from Afloat. Will work on the evaluation and get back to you with feedback in next couple of days...

Thanks @randombishop . We also have M4 ready. Can we submit it too?

**Comment by AugustoLara** [comment]
> Hey @LouiseWReed ! Glad to see a new delivery from Afloat. I will work on the evaluation and get back to you with feedback in next couple of days...

Thanks @randombishop . We also have M4 ready. Can we submit it too?

**Comment by randombishop** [comment]
Hi @AugustoLara ! Yes you can submit M4 as well and I'll evaluate both at the same time. But can you please put the M4 delivery in a separate pull request? (The reason is we have some automated tasks and they don't support multiple deliveries in the same PR, also good to track the evaluation and invoice afterwards separately)

**Comment by randombishop** [comment]
@AugustoLara & @LouiseWReed Did you manage to reproduce this issue or is it related to my env?

**Comment by randombishop** [comment]
Thank you for the fixes @tlacloc, everything works fine now and I am happy to approve this delivery, please find my evaluation here:
https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/afloat_3_randombishop.md

I will forward your invoice; please expect up to 2 weeks for processing.


@tlacloc @AugustoLara @LouiseWReed, Also, In the previous evaluation, I had recommended the following additional documentation:
- Provide a general architecture guide that describes the different repos and how they interact with each other.
- Provide a doc that describes how to deploy and configure a full system locally. 

Did you deliver those docs?

I no, can you please include them in M4 delivery?

Thank you!

**Pull request merged**
