### PR TITLE
Polkadot.js NoCode Plugin Milestone 1 Submission Evaluation

### PR DESCRIPTION
**Pull request by cruikshankss**
I am not sure whether to approve or deny this milestone. This is a complete eval for this stage, however.

My recommendations are to either :
1. Approve this Milestone 1 and require the Forum Post as a testing guide so we can recreate a Bubble app to deeply test the plugin.
2. Deny because in their Grants Proposal they planned the Forum Post delivery for Milestone 1. I gave them a lot of feedback for a Forum Post & I'd be happy to wait for that and more deeply test the plugin.

Project Name: Polkadot.js NoCode Plugin
Team Name: EzCode
[Grant Proposal](https://github.com/w3f/Grants-Program/pull/745)
[Milestone 1 Submission](https://github.com/w3f/Grant-Milestone-Delivery/pull/343)

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks a lot for the evaluation and all the effort you put into this. I’m going to merge it. 
Also I believe the requirements of the contract: “We will create a thread on Bubble's forum describing the plugin features with all links to the plugin, demo, and documentation” are fulfilled by this [forum post](https://forum.bubble.io/t/free-plugin-polkadot-js-by-ezcode/187940). So, I’m going to update your evaluation and change it to accepted. Thanks a lot!

**Comment by Noc2** [comment]
@cruikshankss Btw., just to double check: Is the following address https://kusama.subscan.io/account/HNdC4zNpYVUHJYT9Du9p9Haad5xkXvcyte9vmfUQvHAf8dC, your kusama address?

**Comment by cruikshankss** [comment]
@Noc2 Thanks so much for updating my eval with their new deliverable and merging it!

I double-checked via the Account Format Transform. Yes, that's my account. It's empty/below the existential deposit. Sorry I'm new here. I expect it to come alive with an existential deposit. Thank you for verifying the address.

**Comment by RouvenP** [comment]
hi @cruikshankss we transferred the KSM today. Thanks!

**Pull request merged**
