### PR TITLE
High-availability validator setup - Milestone 3

### PR DESCRIPTION
**Pull request by bufta**
Delivery of Milestone 3

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1203

### CODE REVIEW

**Comment by mgralinski-bright** [comment]
Hi, in case of any technical question, you can use this [link](https://bright-inventions.slack.com/archives/D03V24JGAN9/p1688120791597459) to schedule a meeting.

**Comment by Ali-Usama** [comment]
Hi @bufta and @mgralinski-bright. Thank you for delivering this amazing work. However, the `cargo test` command is still failing in the repo. A detailed evaluation can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/910).

Please have a look into this.
Thanks

**Comment by mgralinski-bright** [comment]
Hello @Ali-Usama, I have answered in the evaluation pull request.

**Review by semuelle — APPROVED** [review]
Hi @bufta & @mgralinski-bright, thanks for the delivery. I double-checked the evaluation and found all tests running successfully. That means, your milestone is hereby accepted. Congratulations.

You can the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/high-availability-validator-setup_3_ali-usama.md). The only thing I would have liked to see is more documentation. For example, an article describing the background and functionality of the project. 

I have forwarded your invoice for processing.

**Pull request merged**
