### PR TITLE
Sensio Network milestone 1 

### PR DESCRIPTION
**Pull request by woss**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. I will try to look into it asap.

**Comment by Noc2** [comment]
Hi Daniel. I started to look into your delivery ([see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sensio_network_1_Noc2.md)). It would be nice if you could add some information to the [readme of the node](https://gitlab.com/sensio_group/network-node/-/tree/10-merge-requests-from-here-improvements-in-general-for-0-2-0). Also do you have some tutorial on how to use the [explorer](http://explorer.sensio.network/) and or node?

**Comment by woss** [comment]
hi, thanks for the comments. now some of mine:

> the network node readme.md is empty

i thought it is obvious for all how to start it since it is substrate based chain. I'll add some info how to start it or even better a script that does all for the user. that would be ok?

> wiki is WIP

oh yes, i'm writing it as we speak, it is NOT the best place to go if you are interested in short info


> tutorial for the usage

i thought the description in explorer front page explains it well seems not, i'll fix that to be more clear, 


ping you when done

**Comment by woss** [comment]
I've updated the starter repo and deployed slightly new version of explorer, plus wrote a tutorial and explanations on the process and PoE parts. i hope this will suffice

**Comment by Noc2** [comment]
Thanks for the additional documentation. Everything works as promised. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sensio_network_1_Noc2.md). So, I'm happy to tell you this milestone is a pass! I will forward your invoice internally.

**Comment by RouvenP** [comment]
hi @woss: we sent a test transaction - could you confirm if received? thanks

**Comment by woss** [comment]
0.01 received

**Comment by woss** [comment]
@RouvenP  this PR is merged. Does that entail that i should see the rest of the BTC on my account? Coz i don't see them.

**Comment by Noc2** [comment]
The merging of the PR only means that it’s accepted. Rouven probably can tell you more about the payment.

**Comment by woss** [comment]
that is quite misleading, i'd expect that when you merge the PR everything is OK and the case is closed.

**Comment by Noc2** [comment]
But everything is ok (delivery was officially accepted) and it’s the signal for the invoice team to issue the payment (see above, it was merged and after this Rouven sent you the test transaction and now he’ll send you the rest as soon as he is able to do this). Btw. this way you can prove that your delivery was accepted and that the payment process isn’t finalized.

**Comment by woss** [comment]
if you say so, it's your workflow. 

i still think think that when PR is merged that is finalized state. imagine if all of us developers would merge the PR to master and then wrote a message that not everything is done, but i acknowledge the delivery of expected features.  😀

**Comment by RouvenP** [comment]
@woss we just transferred the remainder. Apologies for the delay, we had a quite eventful week :)

**Pull request merged**
