### PR TITLE
Pacificstore-Milestone-1

### PR DESCRIPTION
**Pull request by vlbos**
# Milestone Delivery Checklist

- [x ] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x ] This pull request is being made by the same account as the accepted application. 
- [ x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [ x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery. We'll review it as soon as we have availability.

**Comment by vlbos** [comment]
Sorry for the late update.Could you help to continue the review? 
previous PR   https://github.com/w3f/Grant-Milestone-Delivery/pull/127
1 . create the Pacificstore-node repository 
2. Update front-end/readme.md.
3.Update front-end script /example code

**Comment by Noc2** [comment]
Thanks for the update. I’m happy to tell you that the milestone is a pass. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pacificstore_milestone_1_Noc2.md). I will now forward the invoice internally.

**Comment by vlbos** [comment]
> Thanks for the update. I’m happy to tell you that the milestone is a pass. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/pacificstore_milestone_1_Noc2.md). I will now forward the invoice internally.

Thanks.

**Comment by mmagician** [comment]
Just FYI, I moved the submission document into the correct directory, see [this commit](https://github.com/w3f/Grant-Milestone-Delivery/commit/a9e90b4c63268b413c20de51565c16c11dfa0abb).

**Comment by vlbos** [comment]
I have received 0.001 BTC.Thank you.

**Comment by RouvenP** [comment]
@vlbos thanks for confirming. The remainder will be transferred next week.

**Comment by vlbos** [comment]
> hi @vlbos we just transferred the remainder.

I have received 0.399 BTC.Thank you.

**Pull request merged**
