### PR TITLE
Kuma Wallet M2

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1414

### CODE REVIEW

**Comment by Ali-Usama** [comment]
Thank you @0xslipk for the delivery. However, I'm getting the following errors on `npm test`:
```
stderr | src/Extension.test.ts > Extension > init > should throw error on init
failed_to_save_backup

stderr | src/Extension.test.ts > Extension > areAccountsInitialized > should return with catch error false
undefined

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.1.2      node_modules/@polkadot/ui-keyring/node_modules/@polkadot/util/
        esm 12.1.2      node_modules/@polkadot/keyring/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
```
Can you please look into it? 
Thanks!

**Comment by 0xslipk** [comment]
> Thank you @0xslipk for the delivery. However, I'm getting the following errors on `npm test`:
> 
> ```
> 
> stderr | src/Extension.test.ts > Extension > init > should throw error on init
> 
> failed_to_save_backup
> 
> 
> 
> stderr | src/Extension.test.ts > Extension > areAccountsInitialized > should return with catch error false
> 
> undefined
> 
> 
> 
> stderr | unknown test
> 
> @polkadot/util has multiple versions, ensure that there is only one installed.
> 
> Either remove and explicitly install matching versions or dedupe using your package manager.
> 
> The following conflicting packages were found:
> 
>         esm 12.1.2      node_modules/@polkadot/ui-keyring/node_modules/@polkadot/util/
> 
>         esm 12.1.2      node_modules/@polkadot/keyring/node_modules/@polkadot/util/
> 
> @polkadot/util has multiple versions, ensure that there is only one installed.
> 
> Either remove and explicitly install matching versions or dedupe using your package manager.
> 
> ```
> 
> Can you please look into it? 
> 
> Thanks!

We are gonna take a look. Will keep you posted.

**Comment by 0xslipk** [comment]
Hi @Ali-Usama,

We fixed on [main](https://github.com/blockcoders/kuma-wallet/tree/main) and version [v0.1.1](https://github.com/blockcoders/kuma-wallet/tree/v0.1.1)

**Comment by keeganquigley** [comment]
Thanks for the fixes @0xslipk and for the review @Ali-Usama I am happy to accept the milestone. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kuma-cross-chain-wallet_2_keeganquigley.md). I will forward your invoice internally for processing.

**Comment by RouvenP** [comment]
hi @0xslipk we transferred the payment today.

**Pull request merged**
