### PR TITLE
Create CosmWasmVM_CoreProduct-Milestone_1.md

### PR DESCRIPTION
**Pull request by JafarAz**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1430

### CODE REVIEW

**Comment by JafarAz** [comment]
The author of the original grant application is no longer a team member of Composable, therefore, I will be submitting the milestones for this grant.

**Comment by keeganquigley** [comment]
**Update for transparency:** Fixed **Application Document** in order to parse it correctly.

**Comment by keeganquigley** [comment]
Thanks @JafarAz someone will take a look at the delivery soon.

**Comment by dsm-w3f** [comment]
@JafarAz thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CosmWasmVM_1_dsm-w3f.md) and provide proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by JafarAz** [comment]
@dsm-w3f hi sir, I have updated the commands to install the ccw-vm and run a local network. It may take a while at first but once it's installed, you can come back to it almost instantly at a later time. 

> Is the CosmWasm CLI part of the deliverable of this milestone?

No it is a tool we developed for better developer experience, I guess it could have been a good part of the milestone but we did not include it at the time. Also, it is basic functionality right now, we intend to improve the cli in future iterations for better developer experiences.

> Could you explain how to run the tests for the deliverable 1b?

Some precompiles that can be tested include: 

1.[ XCM precompiles ](https://github.com/ComposableFi/composable/blob/main/code/xcvm/lib/core/src/transport/xcm/mod.rs)

2. [Pablo (PolkadotSDK DEX) precompiles](https://github.com/ComposableFi/composable/blob/6db2dedb093b1cfb02cd5a3abbfb49a0a9c0fb96/code/parachain/frame/composable-traits/src/dex.rs#L20)

3. [Fuzzing test](https://github.com/ComposableFi/composable/tree/main/code/parachain/frame/cosmwasm/fuzz_targets)

**Comment by dsm-w3f** [comment]
@JafarAz thank you for the improvements and fixes. How long should the Fuzzing test take to finish? I'm waiting for some time them to finish but I don't know how long it would take or if should I just finish the process once this kind of test could not stop to run. What is the case here?

**Comment by JafarAz** [comment]
@dsm-w3f Fuzzing can go on for hours, likely infinite. If fuzzing will crash/exit with an error code - then it means that something has been found. For the test we linked, we ran it for half a day and nothing unusual showed up.

**Comment by dsm-w3f** [comment]
@JafarAz thank you for the answer. I think now the milestone is ok, please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CosmWasmVM_1_dsm-w3f.md). The milestone is approved. I'll forward you invoice internally and the payment should take place within two weeks. Great job!

**Comment by meldien** [comment]
Hi @JafarAz 
I noted on your invoice our recipient information is missing (Name, address, VAT number) and I'll missing the payment information as well. 
Could you please update the invoice with the missing information?
Many thanks for your support.

**Comment by JafarAz** [comment]
@meldien hey, I resubmitted the invoice back when you messaged but I just noticed I forgot to reply. Lmk if there was any issue with the updated invoice

**Comment by semuelle** [comment]
Hey @JafarAz. The invoice is missing the payment address. Please add this (the one from the application) to the invoice, so that there is no possible confusion about it. Thanks!

**Pull request merged**
