### PR TITLE
Anchor milestone 1

### PR DESCRIPTION
**Pull request by ff13dfly**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1528](https://github.com/w3f/Grants-Program/pull/1528)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @ff13dfly, an evaluator will look at it soon!

**Comment by ff13dfly** [comment]
> Thanks for the delivery @ff13dfly, an evaluator will look at it soon!

Got it, thank you, :-)

**Comment by dsm-w3f** [comment]
@ff13dfly thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/anchor_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by ff13dfly** [comment]
Hi, @dsm-w3f , I have fixed all the bugs in [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/anchor_1_dsm-w3f.md) but docker.

I was a bit depressed. The test for docker I do build via `cargo build --release --locked` as follow:

| System | Docker | Result |
| -----: | ----------- | ------------- |
| MacOS | No | Successful |
| MacOS | Yes | Successful |
| Centos7 (VM) | No | Successful |
| Centos7 (VM) | Yes | Failed |

Still try to find the reason, any suggestion ?

**Comment by ff13dfly** [comment]
The System Test part is here:
https://github.com/ff13dfly/Anchor/tree/main/js/test

**Comment by ff13dfly** [comment]
> > Still try to find the reason, any suggestion ?
> 
> @ff13dfly I think if it is an OS-dependent problem could be in the .sh files. Furthermore, the instructions in [Integration Files](https://github.com/ff13dfly/Anchor#intergration-files) are pretty unclear to me. Is it possible to delivery those files as needed by the application without needing further modifications?

About the docker, I am working on it step by step, hope to solve it.

About the `Intergration files`, no need to modify, they will be copied and replace the substrate ones. 
The code is in the `anchor_builder.Dockerfile`.

```SHELL
RUN ls -alh\
	&& git clone https://github.com/ff13dfly/Anchor\
	&& cp -rf Anchor/docker/deploy/Cargo.toml Cargo.toml \
	&& cp -rf Anchor/docker/deploy/bin_node_cli_src_chain_spec.rs bin/node/cli/src/chain_spec.rs\ 
	&& cp -rf Anchor/docker/deploy/bin_node_runtime_Cargo.toml bin/node/runtime/Cargo.toml\
	&& cp -rf Anchor/docker/deploy/bin_node_runtime_src_lib.rs bin/node/runtime/src/lib.rs\
	&& cp -rf Anchor/docker/deploy/bin_node_testing_src_genesis.rs bin/node/testing/src/genesis.rs\
	&& cp -rf Anchor/frame/anchor/* frame\
	&& cargo build --locked --release
```

**Comment by ff13dfly** [comment]
Hello, @dsm-w3f , I am back, :-)
Good news, I do have built the docker image in Centos 7 ( VM ). Thank for your suggestion, it is the shell problem, I tried another way to build the image and successful.

Please check the result, hope to solve all the issues.

**Comment by ff13dfly** [comment]
> @ff13dfly thank you for the improvements and fixes. The milestone is approved. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/anchor_1_dsm-w3f.md). I'll forward your invoice internally and the payment should take place within two weeks. Great work!

Thank you @dsm-w3f !

**Comment by fededubbi** [comment]
Hi @ff13dfly,

I noticed you put the invoice in Chinese currency.
Can you please show the amount in USDT?

Many thanks,
Federica

**Comment by ff13dfly** [comment]
> Hi @ff13dfly,
> 
> I noticed you put the invoice in Chinese currency. Can you please show the amount in USDT?
> 
> Many thanks, Federica

Ok, let me check the invoice.

**Comment by ff13dfly** [comment]
> Hi @ff13dfly,
> 
> I noticed you put the invoice in Chinese currency. Can you please show the amount in USDT?
> 
> Many thanks, Federica

Checked, there is no currency in the table, will modify it.
How can I post you the new invoice ?

**Comment by ff13dfly** [comment]
Hello @fededubbi , checked again, modify the table head to English, :-)

**Comment by fededubbi** [comment]
Hi @ff13dfly,

Can you please resend the invoice through the form?

Many thanks,
Federica

**Comment by ff13dfly** [comment]
Hi, @fededubbi , uploaded, :-)

**Comment by ff13dfly** [comment]
> Hi @ff13dfly, Sorry to bother you again, but could you please change 'From' with 'Bill to' where you find our information? Also can you add the USDT where you have the total of the invoice?
> 
> Many thanks, Federica

Done, :-)

**Comment by fededubbi** [comment]
Hi @ff13dfly, all good thanks.

**Comment by RouvenP** [comment]
hi @ff13dfly we transferred the payment today.

**Comment by ff13dfly** [comment]
> hi @ff13dfly we transferred the payment today.

Thank you, :-)

**Comment by ff13dfly** [comment]
> hi @ff13dfly we transferred the payment today.

Hi, @RouvenP , I saw the transfer, thank you!  It is my job now to change it to RMB, haha.

**Pull request merged**
