### PR TITLE
Milestone Delivery: Omniverse DLT Milestone 2

### PR DESCRIPTION
**Pull request by xiyu1984**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1431, and an update https://github.com/w3f/Grants-Program/pull/1475

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @xiyu1984 someone will take a look at it shortly.

**Comment by dsm-w3f** [comment]
@xiyu1984 thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_2_dsm-w3f.md). There are some doubts and small improvements there. Please let me know when I can continue the evaluation.

**Comment by xiyu1984** [comment]
> @xiyu1984 thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_2_dsm-w3f.md). There are some doubts and small improvements there. Please let me know when I can continue the evaluation.

Hey @dsm-w3f ,

Thanks for your helpful evaluation, which is clear and detailed.

### License

The [license problem](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_2_dsm-w3f.md#license) is due to that we forgot to merge the `milestone-2` branch into the `main` so every other branch will be `Unlicense`, and now [it has been fixed](https://github.com/Omniverse-Web3-Labs/omniverse-swap/blob/milestone-2/LICENSE).  

### Auto-Test

About the [Auto-Test](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/omniversedlt_2_dsm-w3f.md#auto-testing) problem, **did you meet this problem every time when running `node src/index.js -t swap`?**

From the information you provided, it seems to be the reason that when checking the balance on different chains the synchronization has not been completed. But we checked the related codes and tried it many times today and everything works OK in our environment.  

And also, now that you've made it this far, your operation and configuration should be fine.  

But actually, we found that sometimes when the computer is running under high load, the blocking mechanism of the locally underly EVM chain may be slowed down or even pended, in which case the synchronization may not be completed when checking the balance.  

If it is the case, we think it would be a very rare event related to the underly EVM chain tools. So maybe we need to know whether you meet this every time.  

### secp256k1

The `secp256k1 unavailable, reverting to browser version` is due to the underly lib of the `node.js`, and this does not have any influence on our project. Here're [some details](https://github.com/bitchan/eccrypto/issues/86) about it.  

### Code Quality

Actually, we found these warnings when developing, but as they are related to the `substrate framework`, maybe it's not very suitable for us to change them. Here are some examples:  

 
0c4cb4943471bd8e3737de4519fd45e

c62b0cd7c539881a7ba0bd2a372a93e

**Comment by dsm-w3f** [comment]
@xiyu1984 thank you for the quick answer and fixes. I think the explanations are reasonable. The possible synchronization problem could deserve more investigation and a possible fix but this doesn't prevent the acceptance of the milestone. The milestone is accepted. I'll forward you the invoice internally and the payment should take place within two weeks. Great job!

**Comment by xiyu1984** [comment]
> @xiyu1984 thank you for the quick answer and fixes. I think the explanations are reasonable. The possible synchronization problem could deserve more investigation and a possible fix but this doesn't prevent the acceptance of the milestone. The milestone is accepted. I'll forward you the invoice internally and the payment should take place within two weeks. Great job!

Hey @dsm-w3f ,

Thanks so much for your suggestions and direction, and again it's a very enjoyable grants project journey.  

The invoice has been submitted.  

Have a nice day~
All the best~

**Comment by RouvenP** [comment]
hi @xiyu1984 we transferred the payment today

**Pull request merged**
