### PR TITLE
Web3Box_Milestone_1

### PR DESCRIPTION
**Pull request by web3andrew**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1256 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by web3andrew** [comment]
image

Hi, guys, what should I do with this? Unfortunately, I submitted our milestone delivery unsuccessfully.I have writen the address, contact name, contact email, and total cost in this latest application md https://github.com/w3f/Grants-Program/commit/b6bd8e139792bd83599ff1384c54d3387cd69434.

**Comment by keeganquigley** [comment]
Thanks @web3andrew it looks like this happened because you had edited some of the formatting in the application. No worries I just filed the above PR to fix it.

**Comment by web3andrew** [comment]
> Thanks @web3andrew it looks like this happened because you had edited some of the formatting in the application. No worries I just filed the above PR to fix it. Someone will look at your delivery soon.

Thanks Keegan

**Comment by keeganquigley** [comment]
Hi @web3andrew I have started the evaluation for your milestone. In the meantime, can you please address these initial comments:

- The mandatory deliverables (0a. - 0e.) are not present in the delivery tables. Can you please add these in?
- Also, your application displays 1 - 6, while the delivery only contains 1 - 4. Can you add numbers 5 & 6?
- Basically, the table should mirror the one in your application and contain the same deliverables.

**Comment by keeganquigley** [comment]
@web3andrew you can find my initial evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md). For security reasons I can't open the .exe or .dmg files, but cloning the repo and running the dev server with Yarn should suffice.

Typically we require unit tests for apps, but I am not seeing a tests folder. Have you written any unit tests you can point me to? Thanks!

**Comment by web3andrew** [comment]
> Hi @web3andrew I have started the evaluation for your milestone. In the meantime, can you please address these initial comments:
> 
>     * The mandatory deliverables (0a. - 0e.) are not present in the delivery tables. Can you please add these in?
> 
>     * Also, your application displays 1 - 6, while the delivery only contains 1 - 4. Can you add numbers 5 & 6?
> 
>     * Basically, the table should mirror the one in your application and contain the same deliverables.

@keeganquigley Hi, Keegan; we appreciate your quick feedback and will update what you mentioned asap. And also recommend you better test our .exe or .dmg clients' deliverables; they are the final showcases of Web3Box, which would be used by most Polkadot eco users anyway, like the screenshots below. 
Btw, You can open the Security & Privacy Setting and then allow your Mac to open it when you install .dmg of Web3Box.
Dashboard
image
Multichain Wallet
image

**Comment by keeganquigley** [comment]
Thanks @web3andrew so you are saying that the .exe and .dmg versions have more features than the yarn version? Because when I spin up the app it looks the same to me, I'm not seeing any differences...

web3box

**Comment by web3andrew** [comment]
> Thanks @web3andrew so you are saying that the .exe and .dmg versions have more features than the yarn version? Because when I spin up the app it looks the same to me, I'm not seeing any differences...
> 
> web3box

Got it. Keegan. I mean, you could also experience the .exe and .dmg versions, which would be used mainly by the community since few people can handle the yarn version. It's ok that you test our deliverables with the yarn version. Our devs are adding the units testing, and once ready, I will update our delivery file and notify you.

**Comment by web3andrew** [comment]
@keeganquigley Hi, Keegan; check this latest commit, [70a3928](https://github.com/w3f/Grant-Milestone-Delivery/pull/739/commits/70a39288194b1a04e63dda1de40d07beae8aa390), including unit tests.

**Comment by keeganquigley** [comment]
@web3andrew thanks for the changes! When running `yarn test`, it looks like all of them are passing except for the Assets Pie Chart. It has somethign to do with the RPC calls, can you check it out?

```js
 FAIL  src/substrate/polkadot.test.js (9.675 s)
   polkadot wallet manager
    ✓  create wallat address and set passwd  (511 ms)
    ✓  account address format  (6 ms)
    ✓  export account  (446 ms)
    ✓  import account
   account transaction
    ✓  Account balance inquiry  (1434 ms)
    ✓  Account transfer token
   Dashboard query
    ✓  balance  (1397 ms)
    ✕ Assets Pie Chart (5002 ms)
    ✓  market  (10 ms)

  ●  Dashboard query  › Assets Pie Chart

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      74 |
      75 |
    > 76 |   test('Assets Pie Chart',async() => {
         |   ^
      77 |     const rpcs = {
      78 |       "0":'wss://rpc.polkadot.io',
      79 |       "2":'wss://kusama-rpc.dwellir.com',

      at test (src/substrate/polkadot.test.js:76:3)
      at Object.describe (src/substrate/polkadot.test.js:63:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 passed, 9 total
Snapshots:   0 total
Time:        9.701 s, estimated 10 s
Ran all test suites matching /src\/substrate\/polkadot.test.js/i.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
  console.warn
    2023-02-15 15:15:55        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect

      at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
      at TypeRegistry.setSignedExtensions (node_modules/@polkadot/types/cjs/create/registry.js:509:9)
      at TypeRegistry.setMetadata (node_modules/@polkadot/types/cjs/create/registry.js:488:10)
      at ApiPromise._initRegistry (node_modules/@polkadot/api/cjs/base/Init.js:117:14)
      at ApiPromise._metaFromChain (node_modules/@polkadot/api/cjs/base/Init.js:325:10)

  console.warn
    2023-02-15 15:15:55        API/INIT: RPC methods not decorated: evm_blockLimits, evm_call, evm_estimateResources, oracle_getAllValues, oracle_getValue, tokens_queryExistentialDeposit, transaction_unstable_submitAndWatch, transaction_unstable_unwatch

      at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
      at ApiPromise._filterRpcMethods (node_modules/@polkadot/api/cjs/base/Decorate.js:291:9)
      at ApiPromise._filterRpc (node_modules/@polkadot/api/cjs/base/Decorate.js:262:10)
      at ApiPromise._metaFromChain (node_modules/@polkadot/api/cjs/base/Init.js:326:10)
      at ApiPromise._loadMeta (node_modules/@polkadot/api/cjs/base/Init.js:259:192)

  console.warn
    2023-02-15 15:15:55        API/INIT: acala/2120: Not decorating unknown runtime apis: 0xe3df3f2aa8a5cc57/2

      at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
      at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
      at ApiPromise._decorateCalls (node_modules/@polkadot/api/cjs/base/Decorate.js:483:11)
      at ApiPromise._createDecorated (node_modules/@polkadot/api/cjs/base/Decorate.js:156:26)
      at ApiPromise._injectMetadata (node_modules/@polkadot/api/cjs/base/Decorate.js:186:14)
      at ApiPromise._initFromMeta (node_modules/@polkadot/api/cjs/base/Init.js:351:10)
      at ApiPromise._loadMeta (node_modules/@polkadot/api/cjs/base/Init.js:260:17)
```

**Comment by web3andrew** [comment]
> @web3andrew thanks for the changes! When running `yarn test`, it looks like all of them are passing except for the Assets Pie Chart. It has somethign to do with the RPC calls, can you check it out?
> 
> ```js
>  FAIL  src/substrate/polkadot.test.js (9.675 s)
>    polkadot wallet manager
>     ✓  create wallat address and set passwd  (511 ms)
>     ✓  account address format  (6 ms)
>     ✓  export account  (446 ms)
>     ✓  import account
>    account transaction
>     ✓  Account balance inquiry  (1434 ms)
>     ✓  Account transfer token
>    Dashboard query
>     ✓  balance  (1397 ms)
>     ✕ Assets Pie Chart (5002 ms)
>     ✓  market  (10 ms)
> 
>   ●  Dashboard query  › Assets Pie Chart
> 
>     thrown: "Exceeded timeout of 5000 ms for a test.
>     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
> 
>       74 |
>       75 |
>     > 76 |   test('Assets Pie Chart',async() => {
>          |   ^
>       77 |     const rpcs = {
>       78 |       "0":'wss://rpc.polkadot.io',
>       79 |       "2":'wss://kusama-rpc.dwellir.com',
> 
>       at test (src/substrate/polkadot.test.js:76:3)
>       at Object.describe (src/substrate/polkadot.test.js:63:1)
> 
> Test Suites: 1 failed, 1 total
> Tests:       1 failed, 8 passed, 9 total
> Snapshots:   0 total
> Time:        9.701 s, estimated 10 s
> Ran all test suites matching /src\/substrate\/polkadot.test.js/i.
> Jest did not exit one second after the test run has completed.
> 
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
>   console.warn
>     2023-02-15 15:15:55        REGISTRY: Unknown signed extensions SetEvmOrigin found, treating them as no-effect
> 
>       at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
>       at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
>       at TypeRegistry.setSignedExtensions (node_modules/@polkadot/types/cjs/create/registry.js:509:9)
>       at TypeRegistry.setMetadata (node_modules/@polkadot/types/cjs/create/registry.js:488:10)
>       at ApiPromise._initRegistry (node_modules/@polkadot/api/cjs/base/Init.js:117:14)
>       at ApiPromise._metaFromChain (node_modules/@polkadot/api/cjs/base/Init.js:325:10)
> 
>   console.warn
>     2023-02-15 15:15:55        API/INIT: RPC methods not decorated: evm_blockLimits, evm_call, evm_estimateResources, oracle_getAllValues, oracle_getValue, tokens_queryExistentialDeposit, transaction_unstable_submitAndWatch, transaction_unstable_unwatch
> 
>       at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
>       at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
>       at ApiPromise._filterRpcMethods (node_modules/@polkadot/api/cjs/base/Decorate.js:291:9)
>       at ApiPromise._filterRpc (node_modules/@polkadot/api/cjs/base/Decorate.js:262:10)
>       at ApiPromise._metaFromChain (node_modules/@polkadot/api/cjs/base/Init.js:326:10)
>       at ApiPromise._loadMeta (node_modules/@polkadot/api/cjs/base/Init.js:259:192)
> 
>   console.warn
>     2023-02-15 15:15:55        API/INIT: acala/2120: Not decorating unknown runtime apis: 0xe3df3f2aa8a5cc57/2
> 
>       at apply (node_modules/@polkadot/util/cjs/logger.js:62:22)
>       at Object.warn (node_modules/@polkadot/util/cjs/logger.js:131:14)
>       at ApiPromise._decorateCalls (node_modules/@polkadot/api/cjs/base/Decorate.js:483:11)
>       at ApiPromise._createDecorated (node_modules/@polkadot/api/cjs/base/Decorate.js:156:26)
>       at ApiPromise._injectMetadata (node_modules/@polkadot/api/cjs/base/Decorate.js:186:14)
>       at ApiPromise._initFromMeta (node_modules/@polkadot/api/cjs/base/Init.js:351:10)
>       at ApiPromise._loadMeta (node_modules/@polkadot/api/cjs/base/Init.js:260:17)
> ```

@keeganquigley Hi, Keegan; We increased the setTimeout parameter. The failure of Assets Pie Chart may be caused by the timeout when the network is not very stable. And you could try again.
image

**Comment by keeganquigley** [comment]
Thanks for the update @web3andrew please see the following issues:

- The UI works well, no issues there.
- The test passes now but some [RPC calls](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md?plain=1#L403) still timeout. 
- I'm confused by some of your code. For example, why is the [Talisman API](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L5) imported but then never used?
- Why are BTC & ETH images [imported](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L24) but never used?
- Why is there a [function](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L80) to create an Ethereum address?
- What is this [Utils file](https://github.com/web3box-labs/apps/blob/main/src/substrate/utils.js) for? It seems to be for working with Filecoin addresses.
- Many of the functions don't have code comments.

It seems as though there are many leftover elements in the code, possibly from previous grants such as [this one for Filecoin](https://github.com/filecoin-project/devgrants/issues/1123). Can you explain and/or clean up the code?

**Comment by web3andrew** [comment]
> Thanks for the update @web3andrew please see the following issues:
> 
>     * The UI works well, no issues there.
> 
>     * The tests all pass now but some [RPC calls](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md?plain=1#L403) still timeout.
> 
>     * I'm confused by some of your code. For example, why is the [Talisman API](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L5) imported but then never used?
> 
>     * Why are BTC & ETH images [imported](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L24) but never used?
> 
>     * Why is there a [function](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L80) to create an Ethereum address?
> 
>     * What is this [Utils file](https://github.com/web3box-labs/apps/blob/main/src/substrate/utils.js) for? It seems to be for working with Filecoin addresses.
> 
>     * Many of the functions don't have code comments.
> 
> 
> It seems as though there are many leftover elements in the code, possibly from previous grants such as [this one for Filecoin](https://github.com/filecoin-project/devgrants/issues/1123). Can you explain and/or clean up the code?

@keeganquigley Hi, Keegan; We answered your questions list one by one. Check the following info.

1. The UI works well, no issues there.
:NP

2. The tests all pass now but some [RPC calls](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md?plain=1#L403) still timeout.
:Yes, we have adjusted the timeout, the RPC service may be unstable.

3. I'm confused by some of your code. For example, why is the [Talisman API](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L5) imported but then never used?
:We have reviewed and removed code that is not relevant to this commit.
image

4. Why are BTC & ETH images [imported](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L24) but never used?
:We have reviewed and removed code that is not relevant to this commit.
image

5. Why is there a [function](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L80) to create an Ethereum address?
:This is because our Web3Box supports Moonbeam and needs to be compatible with the GLMR asset address format. The GLMR address is compatible with the EVM system address, such as 0x62d...c736, which is also done with Talisman Wallet and Fearless Wallet. Don't worry.
**Talisman-Moonbeam-GLMR wallet account**
image
**Fearless-Moonbeam GLMR wallet account**
image
**Web3Box-Moonbeam-GLMR wallet account**
image

6. What is this [Utils file](https://github.com/web3box-labs/apps/blob/main/src/substrate/utils.js) for? It seems to be for working with Filecoin addresses.
:We have reviewed and removed code that is not relevant to this commit.

7. Many of the functions don't have code comments.
:We have reviewed and updated the code comments.

8. It seems as though there are many leftover elements in the code, possibly from previous grants such as [this one for Filecoin](https://github.com/filecoin-project/devgrants/issues/1123). Can you explain and/or clean up the code?
:Yes, we also got Grant support from Filecoin Foundation. Since Web3Box is a multi-chain development strategy, it will support more ecologies in the future, thus allowing various ecological traffic to converge on Web3Box, which can also provide more users for Polkadot ecology. 
Some of the code appeared Filecoin-related content, also due to the need to save the transaction records of each network. Therefore, we have rechecked and removed the code unrelated to this commit.

**Comment by web3andrew** [comment]
> > Thanks for the update @web3andrew please see the following issues:
> > ```
> > * The UI works well, no issues there.
> > 
> > * The tests all pass now but some [RPC calls](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md?plain=1#L403) still timeout.
> > 
> > * I'm confused by some of your code. For example, why is the [Talisman API](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L5) imported but then never used?
> > 
> > * Why are BTC & ETH images [imported](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L24) but never used?
> > 
> > * Why is there a [function](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L80) to create an Ethereum address?
> > 
> > * What is this [Utils file](https://github.com/web3box-labs/apps/blob/main/src/substrate/utils.js) for? It seems to be for working with Filecoin addresses.
> > 
> > * Many of the functions don't have code comments.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seems as though there are many leftover elements in the code, possibly from previous grants such as [this one for Filecoin](https://github.com/filecoin-project/devgrants/issues/1123). Can you explain and/or clean up the code?
> 
> @keeganquigley Hi, Keegan; We answered your questions list one by one. Check the following info.
> 
>     1. The UI works well, no issues there.
>        :NP
> 
>     2. The tests all pass now but some [RPC calls](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md?plain=1#L403) still timeout.
>        :Yes, we have adjusted the timeout, the RPC service may be unstable.
> 
>     3. I'm confused by some of your code. For example, why is the [Talisman API](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L5) imported but then never used?
>        :We have reviewed and removed code that is not relevant to this commit.
>        image
> 
>     4. Why are BTC & ETH images [imported](https://github.com/web3box-labs/apps/blob/main/src/ui/pages/Dashboard/Dashboard.js#L24) but never used?
>        :We have reviewed and removed code that is not relevant to this commit.
>        image
> 
>     5. Why is there a [function](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L80) to create an Ethereum address?
>        :This is because our Web3Box supports Moonbeam and needs to be compatible with the GLMR asset address format. The GLMR address is compatible with the EVM system address, such as 0x62d...c736, which is also done with Talisman Wallet and Fearless Wallet. Don't worry.
>        **Talisman-Moonbeam-GLMR wallet account**
>        image
>        **Fearless-Moonbeam GLMR wallet account**
>        image
>        **Web3Box-Moonbeam-GLMR wallet account**
>        image
> 
>     6. What is this [Utils file](https://github.com/web3box-labs/apps/blob/main/src/substrate/utils.js) for? It seems to be for working with Filecoin addresses.
>        :We have reviewed and removed code that is not relevant to this commit.
> 
>     7. Many of the functions don't have code comments.
>        :We have reviewed and updated the code comments.
> 
>     8. It seems as though there are many leftover elements in the code, possibly from previous grants such as [this one for Filecoin](https://github.com/filecoin-project/devgrants/issues/1123). Can you explain and/or clean up the code?
>        :Yes, we also got Grant support from Filecoin Foundation. Since Web3Box is a multi-chain development strategy, it will support more ecologies in the future, thus allowing various ecological traffic to converge on Web3Box, which can also provide more users for Polkadot ecology.
>        Some of the code appeared Filecoin-related content, also due to the need to save the transaction records of each network. Therefore, we have rechecked and removed the code unrelated to this commit.

@keeganquigley  Hi, Keegan. Any update about our delivery?

**Comment by keeganquigley** [comment]
@web3andrew thanks for the changes.

- Regarding the .exe file, I was able to fully evaluate using the yarn version. We don't fund shipping production-ready code anyway, so no worries here.
- I would still recommend cleaning up the code a bit. For example, this [inline comment](https://github.com/web3box-labs/apps/blob/main/src/substrate/polkadot.js#L25) is in Chinese. Also, the main.js file still has some default boilerplate [comments](https://github.com/web3box-labs/apps/blob/main/main.js#L94) in it.
- Seeing as the app works and the deliverables were met, I will go ahead and pass the milestone. See my final eval[ here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/web3box_1_keeganquigley.md). However I would consider the changes above as these might be a considering factor if you apply for a follow-up grant. Thanks!

**Comment by web3andrew** [comment]
> 

@keeganquigley Thank you, Keegan, for your careful testing and timely feedback. Our team is delighted to have passed this milestone delivery. We will continue our efforts to apply for Follow-up Grant.
Btw, We have cleaned up the code again and changed the Chinese inline comment and some default boilerplate comments according to your latest feedback.

**Comment by web3andrew** [comment]
@keeganquigley @semuelle  Hi, guys, what's the next step about this milestone?

**Comment by semuelle** [comment]
Hi @web3andrew. As Keegan pointed out [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/739#issuecomment-1437511702), the delivery was approved. We have forwarded your invoice for internal processing, so you should receive the payment in the next two weeks.

**Comment by web3andrew** [comment]
> Hi @web3andrew. As Keegan pointed out [above](https://github.com/w3f/Grant-Milestone-Delivery/pull/739#issuecomment-1437511702), the delivery was approved. We have forwarded your invoice for internal processing, so you should receive the payment in the next two weeks.

Thanks,sir

**Comment by RouvenP** [comment]
hi @web3andrew we transferred the payment last Friday.

**Pull request merged**
