### PR TITLE
CILA first milestone

### PR DESCRIPTION
**Pull request by AlexShkor**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1679 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@AlexShkor thank you for the milestone delivery and @BaranBayden for the external evaluation. The application look works for me. However, I'm getting the error below when I try to build the docker container. Could you please take a look? Would be nice to add to the documentation some instructions on how to build and run the application using docker as well.

screen

**Comment by AlexShkor** [comment]
@dsm-w3f thank you for the review. May you please provide the local setup on your machine since it's building fine on my Mac M1 - probably just your CPU will be enough.

**Comment by AlexShkor** [comment]
@dsm-w3f we have added a documentation file run-docker.md to the root directory of the repository

**Comment by dsm-w3f** [comment]
@AlexShkor thank you for the improvements and fixes. I tried again and still not working. I'm receiving another error. See the image below. This is not supposed to be caused by running on Mac or Linux. Maybe clean up the docker image cache and try to build again you could reproduce the error. 

image

**Comment by dsm-w3f** [comment]
@AlexShkor I tested again and I was able to build it. However, when I tried to connect with the container I was not possible to access it. Probably some port or export issue. As I was able to test the application without docker, I don't see a problem to approve it. The milestone is approved. I"ll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by fededubbi** [comment]
Hi @AlexShkor,

I noticed that on your invoice is missing the indication of VAT (this should be 0).
Can you please include it and resend?

Many thanks,
Federica

**Comment by AlexShkor** [comment]
Hi @fededubbi , sure

**Comment by AlexShkor** [comment]
@fededubbi I did resend the invoice, please check it out. Also it looks like that notification from this PR are not coming to me - maybe because it's closed

**Pull request merged**
