### PR TITLE
GamePower nft-collectibles-wallet Milestone 1

### PR DESCRIPTION
**Pull request by GamePowerDev**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @GamePowerDev, looks good. We'll look into it as soon as possible. As an initial remark, could you potentially improve on the documentation of both repos in the delivery to describe the project/repositories a little? Potentially you can just copy-paste this from the application.

Also just adding a link to your [amendment PR](https://github.com/w3f/Open-Grants-Program/pull/418) to facilitate the evaluation.

**Comment by GamePowerDev** [comment]
@alxs Thanks for the initial remark and good call. I've updated the repo's main README to provide a quick explanation of the project at a glance.

**Comment by mmagician** [comment]
@GamePowerDev I started testing your delivery by following the tutorial. I have a few comments so far:
### Template usage

The repository where you host your node is marked as a template. This is just a minor thing, but I think that instead of utilising `Use this template` functionality, you've forked the original [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template) repository.

### `ClaimId` vs `ListingId`

Any reason one is u64, whereas the other one is u128?

### Double-buy

After you create a listing and try to call `buy(<ListingId>)` twice on the same ID, you run into an error that your logic doesn't catch and the runtime throws an error (i.e. REALLY BAD!). This is most likely caused by the fact that listing is not removed properly. I've added some new conditions to your repo's unittest to demonstrate this, see [this PR](https://github.com/GamePowerNetwork/gamepower-module-library/pull/2). Once you merge the PR, you'll see that it fails on the last condition. 

In general the above unittest demonstrates an important feature of testing that you've missed: you never check the storage of your pallet in the tests. I strongly suggest that you revise that, especially given that your data is scattered across many storage objects (`Listings`, `LinstingsByOwner`, `AllListings` - and similarly for `Claims`), which creates potential for the state to get out-of-sync.

**Comment by GamePowerDev** [comment]
@mmagician I was able to easily reproduce that error! thanks for catching that. I will update all my tests to also make sure storage is checked properly.

**Comment by GamePowerDev** [comment]
Hi @mmagician 

I took your feedback and implemented more robust unit tests to also account for the storage/state of the pallet. Let me know if you have any other concerns related to that.

The commit for these changes can be found here: [Unit tests commit](https://github.com/GamePowerNetwork/gamepower-module-library/commit/06d391ad57415fc7da814a99d585849b8f90393c)

**Comment by GamePowerDev** [comment]
> Congratulations on completing the first milestone, you can find the full evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/189). I'm looking forward to seeing the full product!

Thank you so much @mmagician and the entire W3F team! We are working hard on milestone 2!

**Pull request merged**
