### PR TITLE
Sol2Ink Milestone 2

### PR DESCRIPTION
**Pull request by coreggon11**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1164
Amendment of the original application: https://github.com/w3f/Grants-Program/pull/1367

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @coreggon11, thanks for the delivery! Someone of the team will take care of it soon.

Don't worry for the check failing, I've opened a PR to fix the formatting in the application document.

**Comment by semuelle** [comment]
Hi @coreggon11. I am currently reviewing your milestone. First of all, great progress! I am glad to see the results and the project moving forward. 

- According to the grant application, you wanted the "core functions [to] be fully covered by comprehensive unit tests to ensure functionality and robustness." However, I only see one unit test that fails when the Solidity input has changed. I wouldn't consider that "ensuring robustness". Am I missing something?
- Could you point me to an example of a chained selector and how it's handled in Sol2Ink? I'm not familiar with the concept from Solidity.
- Could you review the issues page in your [documentation](https://github.com/727-Ventures/sol2ink/blob/6533e9eaad2307f50c82f3e1fc0f9c1f9e619819/docs/docs/issues.md)? It looks like it still lists some issues that have been fixed in this delivery. 

Generally speaking, we prefer a delivery to directly point to either lines of code or commits to show a deliverable instead of pointing to example output. I understand that that's not always sensible, but it would make our job a lot easier. Also, the testing guide we usually ask for is not only for us, but for the public as well. If you could include it in your docs or repo instead of the delivery document next time, that'd be great.

Other than that, everything seems to be in good shape. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sol2ink_2_semuelle.md).

**Comment by coreggon11** [comment]
Hi @semuelle, thanks for the reply!

About tests - the core function of Sol2Ink is code transpilation, and we know it works well if the output of Sol2Ink matches the expected output. By robustness in this instance we can consider multiple Solidity code examples, so we created multiple Solidity examples, which contain different examples of Solidity code and are then parsed during this unit test. Moreover, the unit test also expects the correct file structure.

The issues page is indeed outdated, and we will update it ASAP.

About your other comments, I will update the delivery application to point you to a specific line/commit.

**Comment by coreggon11** [comment]
Hi again @semuelle, just letting you know that I updated the application document with all links, sorry for inconvenience 😄

**Comment by semuelle** [comment]
Thanks for the updates, @coreggon11. With regard to the unit tests, considering the size of the grant and the fact that this is the last and only milestone in it, I'd say it would be reasonable to add more fine-grained unit tests that provide more information than "these contracts are not the same". It would also make future development easier. 

I tried following the ERC20 tutorial, but I get tons of error messages. I assume it's related to an outdated toolchain or something, I'll keep looking into it. In the meantime, could you answer these questions?

- Regarding [this line](https://github.com/727-Ventures/sol2ink/blob/6533e9eaad2307f50c82f3e1fc0f9c1f9e619819/src/assembler.rs#L1429): have you considered matching other variables, such as `block.timestamp` or `block.number`? Since Uniswap also uses `block.timestamp`, wouldn't that be a simple, useful fix?
- In the ERC20 example, why do we need to [copy the events from the IERC20 interface](https://727-ventures.github.io/sol2ink/tutorial/preparation) manually? Does sol2ink not handle interfaces in general?

**Comment by coreggon11** [comment]
Hi @semuelle, thanks for the reply. Would you mind continuing our conversation in Element to speed up the process? 😄

**Comment by coreggon11** [comment]
Hi @semuelle, thanks for reply and updated evaluation. Sorry for the inconvenience about the invoice. I have submitted a new valid one.

**Comment by RouvenP** [comment]
hi @coreggon11 we transferred the payment

**Comment by coreggon11** [comment]
@RouvenP hi, thanks for the information

**Pull request merged**
