### PR TITLE
Bit.country M1

### PR DESCRIPTION
**Pull request by codemeit**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [ ] *This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 

***Github user "bit-country" was the user for accepted application, but is now an organization.**

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery of the milestone. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @codemeit & @shannon-christie,
which docker image tag should I use? `latest` fails with a node dependency tree issue.

**Comment by shannon-christie** [comment]
Hi @semuelle,

Right, we'll get a fix out for that soon. In the meantime, you can use mvpstudionz/bit.web:17
`docker run -p 3000:3000 mvpstudionz/bit.web:17`.

**Comment by semuelle** [comment]
Hey @codemeit & @shannon-christie, 
thanks for following up on the docker issue. I just pushed my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/bit.country_1_semuelle.md). I am happy to report that your milestone is officially accepted. :tada: 

Your invoice will be forwarded for processing.

**Comment by codemeit** [comment]
Thank you very much for your time @semuelle 
We will evaluate your comments and feedback, the team will ensure we take those into account in the future.

On behalf of Bit.Country team, we wish you and the team have a great holiday ahead. 

Best Regards,
Ray Lu

**Comment by RouvenP** [comment]
hi @codemeit, we just sent a test transaction. Could you please confirm if received?

**Comment by codemeit** [comment]
Hi @RouvenP thanks for the test transaction, I can confirm that I have received 0.01 in the test trasnsaction.
Thanks.

**Comment by RouvenP** [comment]
hi @codemeit we sent the payment. apologies for the delay.

**Comment by codemeit** [comment]
Thanks @RouvenP for your payment. We have received it.  

~Happy New Year from our bit country team.

**Pull request merged**
