### PR TITLE
Subauction Milestone 2

### PR DESCRIPTION
**Pull request by green-jay**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/351 + edit https://github.com/w3f/Grants-Program/pull/605 + edit https://github.com/w3f/Grants-Program/pull/854 + edit https://github.com/w3f/Grants-Program/pull/861

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the delivery. In general this looks really good. The only thing that seems to be missing according to the contract is: “Record demo walkthrough recording to better illustrate how to set up auctions of different types and describe different mechanics between each of them.” Are you still working on this?

**Comment by green-jay** [comment]
> Thanks again for the delivery. In general this looks really good. The only thing that seems to be missing according to the contract is: “Record demo walkthrough recording to better illustrate how to set up auctions of different types and describe different mechanics between each of them.” Are you still working on this?

Hi @Noc2,

Thanks for the comments. I completely missed that the video requirement was even originally in the proposal (since I wasn't the one writing it). I didn't plan to record it. My thinking is, the pallet is inline documented really well and also heavily covered by unit tests (~2.6k lines) so all the various scenarios and setups can be found in the code. How the implemented auction types function and differ can be found in the proposal document and in the line comments.

As there is no front end for the project (yet), what I can do is run the project and replicate some of the test scenarios in polkadotJS apps commenting it and presenting different setups. But it will be quite lenghty and I don't believe it will particularily benefit the ecosystem.

What do you think?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Makes sense. In this case, feel free to just create a PR to update the application and remove the video from the milestone. Once the amendment is merged, I will accept the milestone.

**Review by Noc2 — APPROVED** [review]
Thanks for creating the PR. Since the amendment is already signed, I’m happy to tell you the milestone is a pass and I will forward your invoice internally.

**Comment by green-jay** [comment]
> Thanks for creating the PR. Since the amendment is already signed, I’m happy to tell you the milestone is a pass and I will forward your invoice internally.

Thank you for the review.

**Comment by RouvenP** [comment]
hi @green-jay we transferred the payment today. Thanks!

**Pull request merged**
