### PR TITLE
Delivery: Project Aurras MVP - Phase 2 - Milestone 2

### PR DESCRIPTION
**Pull request by MuhammedIrfan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/814

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @MuhammedIrfan, thanks for the delivery. Someone of the team will look into it soon.

By the way, could you please remove the Milestone 1 delivery file from this pull request?

**Comment by MuhammedIrfan** [comment]
> Hi @MuhammedIrfan, thanks for the delivery. Someone of the team will look into it soon.
> 
> By the way, could you please remove the Milestone 1 delivery file from this pull request?

I have removed it. Thank you @0xCaso.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan this PR was marked as stale due lack of interaction for two weeks. Do you still intend to perform the fixes requested during the evaluation?

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan this PR was marked as stale due lack of interaction for two weeks. Do you still intend to perform the fixes requested during the evaluation?

@dsm-w3f We have fixed couple of issues still need to fix couple more issues, I kindly request you to give us 1 more week to revert back with all issues fixed. Thank you.

**Comment by keeganquigley** [comment]
Thanks @MuhammedIrfan please ping @dsm-w3f once complete.

**Comment by MuhammedIrfan** [comment]
> Thanks @MuhammedIrfan please ping @dsm-w3f once complete.

Sure @keeganquigley

**Comment by keeganquigley** [comment]
Hi @MuhammedIrfan I see you moved this to a draft. Are you still working on it?

**Comment by MuhammedIrfan** [comment]
> Hi @MuhammedIrfan I see you moved this to a draft. Are you still working on it?

Hi @keeganquigley, Yes, Most of the parts are complete. We are waiting for M1 to complete.

**Comment by MuhammedIrfan** [comment]
@dsm-w3f We have made some fixes and this PR is ready for review. Kindly review the milestone submission. Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for updating the milestone delivery. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). Please provide proper answers and fixes and let me know when I can continue this evaluation.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for updating the milestone delivery. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). Please provide proper answers and fixes and let me know when I can continue this evaluation.

@dsm-w3f Thank you for reviewing the delivery, We will fix the issues and revert back soon.

**Comment by MuhammedIrfan** [comment]
@dsm-w3f We have fixed the issue and updated the delivery document. I request you to kindly re-evaluate the delivery. Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). I need a way to run the workflow that doesn't needs programming and a testing guide to check it. Could you provide it?

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). I need a way to run the workflow that doesn't needs programming and a testing guide to check it. Could you provide it?

@dsm-w3f Thank you for the evaluation. Workflow Macro is a rust macro and the core component of the workflow, The unit test along with workflow composer test infact would be covering the Workflow Macro, Our next milestone would be covering the utility of polkadot payout utility which would be covering the workflow macro that can be tested without programming guide.

The test for push notification might have failed due to missing FIREBASE_API_KEY and TEST_DEVICE_TOKEN [Source](https://github.com/HugoByte/aurras/blob/next/actions/push-notification/src/lib.rs#L75) [Source](https://github.com/HugoByte/aurras/blob/next/actions/push-notification/src/lib.rs#L102), which can be generated using [Link](https://github.com/HugoByte/aurras/tree/next#testing)

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the answer. Ok to deliver the interface for workflow macro in the next milestone delivery. Besides that, I adjusted the env variables and the two tests are still failing. Could you please verify that?  See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md).

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for the answer. Ok to deliver the interface for workflow macro in the next milestone delivery. Besides that, I adjusted the env variables and the two tests are still failing. Could you please verify that? See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md).

@dsm-w3f We have prepared a video to help you navigate through the issue you are facing [Link](https://youtu.be/ShjUA6rbwHE). Hope this helps you. Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for providing the demo video. Now all tests are passing. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). The milestone delivery is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for providing the demo video. Now all tests are passing. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_2_dsm-w3f.md). The milestone delivery is approved. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

Thank you @dsm-w3f

**Comment by MuhammedIrfan** [comment]
@RouvenP As its been two weeks, Just wanted to check if you are facing any challenges with the invoice.

**Comment by RouvenP** [comment]
hi @MuhammedIrfan apologies for the delay! we just sent the payment

**Comment by MuhammedIrfan** [comment]
> hi @MuhammedIrfan apologies for the delay! we just sent the payment

No problem @RouvenP, Thank you. I acknowledge the receipt.

**Pull request merged**
