### PR TITLE
Substratesnap_Maintenance-3

### PR DESCRIPTION
**Pull request by danforbes**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/874

### CODE REVIEW

**Comment by danforbes** [comment]
Thank you for your notes, @takahser. I have updated the delivery document with some additional details. The snap has been [released to NPM](https://www.npmjs.com/package/@chainsafe/polkadot-snap) and should be available for people in the community to use. There is also a PR that has been open for over two weeks to [integrate snap support into Polkadot-JS Apps UI](https://github.com/polkadot-js/apps/pull/8070). Please let me know if there are additional details that I can provide. I have a meeting w/ the grants team on Monday and I'd be happy to demo the snap at that time or any other that may be better for you and colleagues.

**Review by takahser — CHANGES_REQUESTED** [review]
I've a couple of points to make here.

1) Quote from your [wiki](https://github.com/ChainSafe/metamask-snap-polkadot/wiki#architecture):

    > Metamask Polkadot snap is enabled through [metamask-polkadot-adapter](https://www.npmjs.com/package/@nodefactory/metamask-polkadot-adapter).
    
    I think this is outdated. [@nodefactory/metamask-polkadot-adapter](https://www.npmjs.com/package/@nodefactory/metamask-polkadot-adapter) has been deprecated in favor of [@chainsafe/metamask-polkadot-adapter](https://www.npmjs.com/package/@chainsafe/metamask-polkadot-adapter). That's also the package that you've used for the [integration into polkadot-js apps](https://github.com/polkadot-js/apps/pull/8070/files#diff-90021c2282310ab6dec4dcb2dd8440af002b04367e36b139a7145fa39bc9abe2R19).

2) It would be nice if you could add the README to the [npm package](https://www.npmjs.com/package/@chainsafe/polkadot-snap):

    image

3) Also, feel free to have a look at [my comments on the polkadot-js/apps integration](https://github.com/polkadot-js/apps/pull/8070#pullrequestreview-1120597767).

**Review by Noc2 — APPROVED** [review]
@danforbes I’m going to merge this PR and forward the invoice internally. But you might still want to take a look at @takahser comments.

**Comment by danforbes** [comment]
Apologies for the delay - the snap has been released and the README now appears on the NPM page https://www.npmjs.com/package/@chainsafe/polkadot-snap. The requested changes to the wiki have also been made.

**Pull request merged**
