### PR TITLE
Zondax - Ledger Support 2021 Q1

### PR DESCRIPTION
**Pull request by jleni**

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the detailed report @jleni. I'll look into it sometime next week.

**Comment by alxs** [comment]
Hey Juan, sorry for not following up - I'm waiting for our finance team to send a few DOTs to an account on one of our testing devices. I'll get back to you as soon as I've been able to test it!

**Comment by alxs** [comment]
Hey, sorry once again for the long wait. The scope of the work here was really a little too large to thoroughly review, but everything I tried worked without issues and I'm happy to share that I only heard positive feedback about the apps everywhere I asked.

As for the grant, I have mainly one question, in [deliverable 6](https://github.com/w3f/Grants-Program/blob/master/applications/Zondax-Support.md#milestone-1--support) you describe "initiating a support subdomain with relevant content, material and tutorials to support both the recovery extension as well as to mitigate future community issues", but I can't find anything like that. How did you end up addressing this? Also, Anja left the foundation a while ago. Are you in contact with anybody else from the support team or shall we connect you again?

And just to check if I understood the situation correctly: the recovery mode is probably not used that often anymore, since this issue was addressed in polkadot-js so that it's not possible for this to happen so easily any longer, correct?

**Comment by ainhoa-a** [comment]
Hi @alxs  as per deliverable 6, it was decided to publish this content in form of blog posts, see:

- https://zondax.ch/blog/recover-blocked-ksm
- https://zondax.ch/blog/dot-recovery-mode
- https://zondax.ch/blog/ksm-dot-recovery

With regards to the recovery mode, this mode is still active, in case the issue (unlikely, but possible) happens again.

**Comment by alxs** [comment]
Sounds good. In that case, I'm happy to let you know that the milestones have been accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Zondax-Support_1_alxs.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Zondax-Support_2_alxs.md).

I'll forward your invoice to the finance team for payment - please allow for up to 2 weeks for processing.

**Comment by alxs** [comment]
Hey @jleni, could you please submit a pull request to change the [address](https://github.com/w3f/Grants-Program/blob/master/applications/Zondax-Support.md#open-grant-proposal) in your application to the one in the invoice, or the other way around?

**Comment by jleni** [comment]
Hi @alxs 
Please find the address change here:

https://github.com/w3f/Grants-Program/pull/1116/files

**Pull request merged**
