### PR TITLE
parallel_milestone_1 delivery

### PR DESCRIPTION
**Pull request by yz89**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery! We'll look into it as soon as possible. In the meantime, would you mind making the notion doc on User Testing public?

**Comment by yz89** [comment]
Thanks for your quick reply. The notion doc goes public now. 

In addition, we've revised the milestone before. https://github.com/w3f/Open-Grants-Program/pull/419

**Comment by semuelle** [comment]
@yz89, could you provide a little bit of context for the UX doc? Did you interview 10-15 users as you suggested in the contract? Are these the main action points you derived from these interviews?

**Comment by yz89** [comment]
Hi @semuelle, we have invited more than 10 people to use our product and ask them to give us their suggestions. Part of this is documented in UX Doc. We understood the user experience, but only adopted some of the recommendations. You can check out the evolution of our dApp.

V1: https://www.youtube.com/watch?v=lgQX9rELpL8
V2: https://www.youtube.com/watch?v=qyMdNYBgsq0
V3: https://www.loom.com/share/0d24207ffdbb4dc284a19c2d95291a3a

**Comment by yubo-ruan** [comment]
@semuelle @alxs Hi guys, It's been over two weeks since we submitted the UX doc. I wanted to follow up with you on our milestone delivery and let us know if you have other questions.  Thank you

**Comment by Noc2** [comment]
@yubo-ruan Sorry for the delay. I will look into it today

**Comment by Noc2** [comment]
I started to look into your delivery and found the following. It looks like you used compounds code. Could clarify this and potentially update the attribution?  

- https://github.com/compound-finance/gateway/blob/46eebcc25afce6ba13c544efcc1efda14e8e9628/pallets/cash/src/rates.rs 
- https://github.com/parallel-finance/parallel/blob/d5fd52ccdb1dc933a6afbb357046db8212bc51be/pallets/loans/src/rate.rs

**Comment by yz89** [comment]
Hi @Noc2, Thank you for pointing out the problem in our code.  It has been addressed in latest commit [rate_model.rs](https://github.com/parallel-finance/parallel/blob/9156578c074080276859f3fbeca5eeb39b67cf19/pallets/loans/src/rate_model.rs) file.

Here is a bit more context, 
a month ago, we found that [rate parameters](https://github.com/parallel-finance/parallel/blob/a29ca73614059187798290f9c5be16bbffea6ef6/pallets/loans/src/rate.rs) in our design are not easy to understand and governed. After some research in ecosystem, the Compound geteway provides a pretty clean solution, we've learned a lot about the design of interest rate model from Compound, also some concepts in AAVE. We accidentally merge some early code into the master and forget to clean them. The latest commit has already do the cleaning. Also we are contributing more ideas to the DeFi ecosystem like curved interest model and fixed interest rate. You can check more detail with the related [issue](https://github.com/parallel-finance/parallel/issues/229) and [whitepaper](https://app.gitbook.com/@parallelfi/s/parallel-finance/white-paper#3-experimental-models).

**Comment by yubo-ruan** [comment]
@Noc2 Is the front-end repo required to be open-source in order to complete our milestone?

**Comment by yubo-ruan** [comment]
@Noc2 I'd like to follow up here. We made the relevant changes to the interest rate model and also accredit for the compound chain. Could you double-check?  Let me know what are some other questions you have. We'd like to finalize the milestone delivery.

**Comment by Noc2** [comment]
Sorry for the late response and thanks for the explanation. Also it’s nice to see that you added the credit section to the readme.  Regarding the front-end, you don’t need to open source the entire front-end, but it would be nice to have some kind of “integration with front-end” open source, since this is part of the contract. Also originally you planned to deliver a “Substrate module: Price aggregation oracle”. It seems that you are now simply using the ORML oracle pallet. This is fine, but we probably need to amend the contract and remove this delivery. Feel free to create a PR for it. You could also remove the front-end as part of this PR/amendment, but you should explain this reason for it. Keep in mind that the amendment needs to be accepted by 1/3 of the grants committee.

**Comment by yz89** [comment]
Hi @Noc2, I updated the deliverables. We have done the price oracle as stated in the contract, and please recheck section 1c. Regarding the "integration with front-end", we open the key integration code of the front-end by using gist. With a live demo and docker-compose file, I believe it enough to prove our work.

**Comment by yubo-ruan** [comment]
Hope you have a great weekend
@Noc2 We made multiple changes to our interest rate model and we open source the integration code with the front-end. Let us know what are some other questions for the milestone deliverable. We'd like to move forward

**Comment by Noc2** [comment]
Sorry for the late response. I’m happy to confirm that the milestone is a [pass](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Parallel_1_Noc2.md) and I will forward your invoice internally. Regardless, it would be nice if you could add readmes to your pallets to make it easier for others to use and understand your pallets.

**Comment by fededubbi** [comment]
Good morning,

Could you please add your address to the invoice?

Many thanks,
Federica

**Comment by yubo-ruan** [comment]
Hi @fededubbi, thanks for getting back to me. 

I don't think I can edit this form any more (https://forms.gle/8Wx7nxtq8fKrsuEz8)
Here is the DAI receiving address on this page: https://github.com/parallel-finance/Open-Grants-Program/blob/master/applications/Parallel.md

**Comment by fededubbi** [comment]
Hi,

I didn't mean the payment address, but your legal address.
Can you please send an update invoice with that?

If it is a problem then i will accept the first invoice.

Many thanks,
Federica

**Comment by yubo-ruan** [comment]
@fededubbi 

Hope you have a good day.

Sorry for the confusion!  I tried a few times to modify it but unfortunately, the system wouldn't allow me. It would be great to use the first invoice! 

Best,
Yubo

**Comment by Noc2** [comment]
@yubo-ruan You can just send an updated invoice to invoices@web3.foundation. Thanks!

**Comment by yubo-ruan** [comment]
Hi @Noc2 I was able to submit the invoice again through the form. Let me know if you have any other questions.

**Comment by RouvenP** [comment]
hi @yubo-ruan we transferred the payment today.

**Pull request merged**
