### PR TITLE
Native Bitcoin Vaults - Milestone #1 Delivery

### PR DESCRIPTION
**Pull request by 3yekn**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/868

15-minute video of milestone explainer and demonstration: 
https://youtu.be/OYKvt-xir3E

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @3yekn! We will look into it as soon as possible.

**Comment by lucasvanmol** [comment]
Hi @3yekn. I'm trying to set an xpub with the UI, but when trying to scan a QR code the UI tells me to allow camera permissions. However, my browser never actually asks for it (this happened on Firefox, and then also on Chrome). Console error logs from Firefox:

```
Uncaught (in promise) TypeError: 'camera' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    open qr-decode-xpub.vue:47
    ...
```

Additionally, trying to input an xpub manually does not seem to work as expected:

Screenshot 2022-06-03 at 11 21 08

Finally, https://github.com/hashed-io/native-bitcoin-vaults-UI is now 404'ing for me, has it been privated?

**Comment by lucasvanmol** [comment]
Would love some data for `wss://n1.hashed.systems`. Also, could you add appropriate LICENSE files to `bdk-services`, `native-bitcoin-vaults-UI` and `nbv-ur-codec`?

**Comment by 3yekn** [comment]
@lucasvanmol ok, I will create some data, vault/wallet, and we will also deploy an instance of the UI to make it easier to test. You will need to download BlueWallet though if you want to test importing the vault into a signer. This will also be needed for milestone 2, which includes signing the PSBTs and finalizing/broadcasting the transaction. I will report back when this is ready.

Also, I will update the LICENSE files as you mention. thanks

**Comment by lucasvanmol** [comment]
Hi @3yekn, thank you for your patience and your help so far. Before we accept the delivery, we'd like to ask you for a few things:

* Could you make sure the table included in this delivery is identical to the one in the [application](https://github.com/w3f/Grants-Program/blob/master/applications/native-bitcoin-vaults.md#milestone-1--prepare-dependencies-and-build-vault-configuration)? 
* Could you edit the application document to include the changes you decided on, notably integrating BlueWallet instead of Spectre? Notably [this section](https://github.com/w3f/Grants-Program/blob/master/applications/native-bitcoin-vaults.md#bitcoin-signer-spectre-desktop-andor-caravan), and [this one](https://github.com/w3f/Grants-Program/blob/master/applications/native-bitcoin-vaults.md#signatures). You can edit them down quite a bit, just mention the technology you ended up going with.

Thanks!

**Review by lucasvanmol — APPROVED** [review]

**Comment by lucasvanmol** [comment]
Thanks for the changes @3yekn ! You can see my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/5a6e2347d69be04c2c10bc9b5fc783081c8118ec/evaluations/native-bitcoin-vault_1_lucasvanmol.md). I'll notify the finance team to pay your invoice.

**Comment by RouvenP** [comment]
hi @3yekn we transferred the BTC yesterday. Thanks!

**Pull request merged**
