### PR TITLE
Kuma Wallet M4

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1414

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@0xslipk thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kuma-cross-chain-wallet_4_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by 0xslipk** [comment]
> @0xslipk thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kuma-cross-chain-wallet_4_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

Thank you for taking the time to review our delivery. We are gonna look the evaluation and address it

**Comment by 0xslipk** [comment]
Hello @dsm-w3f, 

We fixed all the issues reported. You can check the latest version [v0.3.6](https://github.com/kumawallet/extension/releases/tag/v0.3.6).

Let me know if you have any question.

**Comment by dsm-w3f** [comment]
@0xslipk and @rubenguc thank you for the improvements and fixes. Look like most of the problems raised in the evaluation were fixed. However, I'm not able to use the wallet with Testnets yet. It would be possible to enable this? How did you test the application? We are not supposed to test applications using Mainnets.

**Comment by rubenguc** [comment]
@dsm-w3f you can enable them in Settings > General > Show testnets

Screenshot 2023-08-22 at 2 03 22 PM

**Comment by dsm-w3f** [comment]
@rubenguc thank you for the answer. Let me explain in more detail what is happening. The problem is not showing the testnet list, is when you select one of the testnets on the list, there is only the option to make XCM transfer to the same testnet. There is no option to make XCM transfers between testnets, which is the most common use case for XCM. See the prints below, when using mainnets it is possible to make this kind of transfer, but with testnets it is not possible. How could we test XCM transfers on testnets in this way? It is possible to enable this functionality?

Networks available:
image (35)

Doing XCM with Mainnets:
image (36)


Doing XCM with Testnets:

 
image (37)


image (38)

**Comment by 0xslipk** [comment]
> @rubenguc thank you for the answer. Let me explain in more detail what is happening. The problem is not showing the testnet list, is when you select one of the testnets on the list, there is only the option to make XCM transfer to the same testnet. There is no option to make XCM transfers between testnets, which is the most common use case for XCM. See the prints below, when using mainnets it is possible to make this kind of transfer, but with testnets it is not possible. How could we test XCM transfers on testnets in this way? It is possible to enable this functionality?
> 
> Networks available: image (35)
> 
> Doing XCM with Mainnets: image (36)
> 
> Doing XCM with Testnets:
> 
> image (37)
> 
> image (38)

Hi @dsm-w3f,

We added the functionality for testnet on version [v0.3.7](https://github.com/kumawallet/extension/releases/tag/v0.3.7). We mainly tested in the relayer chain, but you are right, we should allow do the same on testnet.

**Comment by dsm-w3f** [comment]
@0xslipk and @rubenguc thank you for the improvements and fixes. Now I was able to test the XCM transfer. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kuma-cross-chain-wallet_4_dsm-w3f.md). The milestone is approved. I'll forward you invoice internally and the payment should take place within two weeks. Great job!

**Comment by RouvenP** [comment]
hi @0xslipk we just transferred the payment.

**Pull request merged**
