### PR TITLE
WeTEE Network Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by BurnWW**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2065

### CODE REVIEW

**Comment by dsm-w3f** [comment]
Hi @BurnWW, I tried to install the software using [these instructions](https://github.com/wetee-dao/chain/blob/patch/docs/grants/milestone-2-documentation.md) but I'm having an error while running `make install` instruction.

I'm using an Intel 7th gen CPU and Ubuntu 20.04.

I ran `make install` and got this error:

```
make install
test -s /home/user/workspace/w3f/worker/bin/controller-gen && /home/user/workspace/w3f/worker/bin/controller-gen --version | grep -q v0.13.0 || \
GOBIN=/home/user/workspace/w3f/worker/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
can't load package: package sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0: can only use path@version syntax with 'go get'
make: *** [Makefile:169: /home/user/workspace/w3f/worker/bin/controller-gen] Error 1

```

Can you help with that?

I'm using the go version `go1.13.8 linux/amd64`.

**Comment by BurnWW** [comment]
Thank you @takahser, I have already fully understood the problem.
I see that your golang version is 1.13, which is the default golang version for Ubuntu 20.04, but this version is rather outdated. We currently recommend using the go 1.20 version, and you can install and switch to the new version of golang by following the command below.
```bash
sudo apt remove golang

# Install golang 1.20 ,ubuntu 20.04 default golang version is 1.13, is too low 
sudo apt install golang-1.20

# set golang env, also you can add it to .bashrc file（in home dir) or .zshrc file（in home dir)
export GOROOT=/usr/lib/go-1.20/
export PATH=$PATH:$GOROOT/bin
```

We have also checked recent updates to the code and made the following updates in the documentation:
 - 1. Updated the Docker image for chain to`wetee/wetee-node:dev.2024-02-16-20_40`
 - 2. Documentation for installing and configuring the Golang environment.

After updating golang, please update the worker’s code and execute the following command.
```
go mod tidy
sudo chmod 744 /etc/rancher/k3s/k3s.yaml
```

**Comment by dsm-w3f** [comment]
@BurnWW thanks for the answer. I tried again, but is not working yet. This is the Go language version that I'm using currently. I installed it using snap. 
```
go version
go version go1.21.6 linux/amd64
```
When I try to run without docker I got this error:

```
sh hack/dev.sh
mkdir: cannot create directory ‘/opt/wetee-worker’: File exists

/home/user/workspace/w3f/worker/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/user/workspace/w3f/worker/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
rm -f  bin/manager
cd bin && export KUBECONFIG=/etc/kube/config &&  \
        ego-go build -o manager ../cmd/main.go && \
        ego sign manager && \
        ego run ./manager
go: errors parsing go.mod:
/home/user/workspace/w3f/worker/go.mod:5: unknown directive: toolchain
make: *** [Makefile:84: run] Error 1

```

When I tried to run with docker I got this other one

```
docker run --device /dev/sgx/enclave --device /dev/sgx/provision --network host -e KUBECONFIG=/etc/kube/config -v /etc/rancher/k3s:/etc/rancher/k3s wetee/worker:dev
Unable to find image 'wetee/worker:dev' locally
dev: Pulling from wetee/worker
edaedc954fb5: Pull complete 
cf6d27f4425f: Pull complete 
990a29630794: Pull complete 
25beea55acce: Pull complete 
eb032c327707: Pull complete 
6aa96f1a0359: Pull complete 
Digest: sha256:a537675ee61a86a382fdfdc9ed3a01e2cd22cdc31f9282cd6782ac1b3fbdc072
Status: Downloaded newer image for wetee/worker:dev
ERRO[0030] error waiting for container:                 
docker: Error response from daemon: error gathering device information while adding custom device "/dev/sgx/enclave": no such file or directory.

```

Can you assist with these problems?

**Comment by BurnWW** [comment]
Thank you @dsm-w3f , I have already fully understood the problem.
These are two problems that need to be inspected and addressed individually in this way.

>  /home/user/workspace/w3f/worker/go.mod:5: unknown directive: toolchain make: *** [Makefile:84: run] Error 1

This error occurs because the Golang version defined in our go.mod file is 1.20, and executing `go mod tidy` with Golang 1.21 will result in a reference to `toolchain go1.21.6` being generated in the go.mod file. We have updated the go.mod file, and the default Golang version is now 1.21. Run git pull to get the latest code, which should resolve the issue.

> docker: Error response from daemon: error gathering device information while adding custom device "/dev/sgx/enclave": no such file or directory.

This issue is caused by the incomplete installation of ego and SGX SDK on the English host machine. 
Since ego depends on a complete SGX SDK, the following command is guaranteed to fully install the SGX environment.
```bash
sudo apt install build-essential libssl-dev

sudo mkdir -p /etc/apt/keyrings
wget -qO- https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo tee /etc/apt/keyrings/intel-sgx-keyring.asc > /dev/null
echo "deb [signed-by=/etc/apt/keyrings/intel-sgx-keyring.asc arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/intel-sgx.list
sudo apt update

EGO_DEB=ego_1.4.1_amd64_ubuntu-$(lsb_release -rs).deb
wget https://github.com/edgelesssys/ego/releases/download/v1.4.1/$EGO_DEB
sudo apt install ./$EGO_DEB build-essential libssl-dev
```
After the installation is completed, executing `cpuid -1 -l 0x7 | grep SGX` will display the following information, indicating that the sgx environment has been successfully configured.
```bash
$ cpuid -1 -l 0x7 |grep SGX                 
SGX: Software Guard Extensions supported = true
SGX_LC: SGX launch config supported      = true
```

**Comment by BurnWW** [comment]
@dsm-w3f I’m truly sorry that we haven’t fully researched the support of intel 7th cpu for the ego program, which has caused inconvenience to your verification process. After checking, we found out that SGX FLC is supported starting from intel 8th generation processors, and we have already corrected the documentation accordingly. I will go back to investigate the cloud service and provide you with the test results as soon as possible. Once again, please accept my apologies.

**Comment by BurnWW** [comment]
hello @dsm-w3f, I’ve conducted a comprehensive research on the Azure operating environment, and I found that Azure fully meets the requirements for software debugging and usage. Attached are my testing logs.
This is the official tutorial and documentation https://learn.microsoft.com/en-us/azure/confidential-computing/quick-create-portal

> Free trial accounts do not have access to the VMs in this tutorial. Please upgrade to a Pay-As-You-Go subscription.
This is the configuration for the virtual machine I created.

WX20240220-183323@2x

This is the result of my test in a virtual machine.

WX20240220-183754@2x

**Comment by BurnWW** [comment]
hello @dsm-w3f, Due to the inability to directly use https://polkadot.js.org/apps for debugging non-https blockchain nodes in a cloud-based debugging environment, I am providing a copy of the http version of Polkadot UI for convenient debugging at http://polkadot-ui.tc.asyou.me/.

**Comment by dsm-w3f** [comment]
Hi @BurnWW, thanks for the explanation. I set up a virtual machine in Azure with the same type of instance that you did. I was able to run the installation instructions. However, in the last step, when running without docker, I received this logs, which indicate that something is not ok. Could you assist with that? Is this in a state that I can proceed with the tests?

```
sh hack/dev.sh
mkdir: cannot create directory ‘/opt/wetee-worker’: File exists

Makefile:65: warning: overriding recipe for target 'fmt'
Makefile:57: warning: ignoring old recipe for target 'fmt'
Makefile:69: warning: overriding recipe for target 'vet'
Makefile:61: warning: ignoring old recipe for target 'vet'
test -s /home/azureuser/worker/bin/controller-gen && /home/azureuser/worker/bin/controller-gen --version | grep -q v0.13.0 || \
GOBIN=/home/azureuser/worker/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0
/home/azureuser/worker/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/azureuser/worker/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
rm -f  bin/manager
cd bin && export KUBECONFIG=/etc/kube/config &&  \
        ego-go build -o manager ../cmd/main.go && \
        ego sign manager && \
        ego run ./manager
EGo v1.4.1 (8b99356398dd3bcb5f74e5194d20ce421f607404)
EGo v1.4.1 (8b99356398dd3bcb5f74e5194d20ce421f607404)
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
Loading: Load from env
LoadingRules: &{ [/etc/kube/config] map[.kube/config:.kube/.kubeconfig] false <nil> true <nil>}
2024-02-21T16:54:43Z    INFO    setup   starting manager
2024/02/21 16:54:43 connect to http://localhost:8880/ for GraphQL playground
MintKey =>  5FUBwrwgnxRmRShJJvLEihw7cJ33nuY6cYhGoxVyJx6HMX8o
2024/02/21 16:54:43 connect to http://0.0.0.0:8883 for InCluster server
2024-02-21T16:54:43Z    INFO    controller-runtime.metrics      Starting metrics server
2024-02-21T16:54:43Z    INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8180", "secure": false}
2024-02-21T16:54:43Z    INFO    starting server {"kind": "health probe", "addr": "[::]:8181"}
2024-02-21T16:54:43Z    INFO    Starting EventSource    {"controller": "app", "controllerGroup": "secret.wetee.app", "controllerKind": "App", "source": "kind source: *v1.App"}
2024-02-21T16:54:43Z    INFO    Starting Controller     {"controller": "app", "controllerGroup": "secret.wetee.app", "controllerKind": "App"}
2024-02-21T16:54:43Z    INFO    Starting EventSource    {"controller": "task", "controllerGroup": "secret.wetee.app", "controllerKind": "Task", "source": "kind source: *v1.Task"}
2024-02-21T16:54:43Z    INFO    Starting Controller     {"controller": "task", "controllerGroup": "secret.wetee.app", "controllerKind": "Task"}
ClusterId =>  GetK8sClusterAccountsLatest => not ok
2024-02-21T16:54:43Z    INFO    Starting workers        {"controller": "task", "controllerGroup": "secret.wetee.app", "controllerKind": "Task", "worker count": 1}
2024-02-21T16:54:43Z    INFO    Starting workers        {"controller": "app", "controllerGroup": "secret.wetee.app", "controllerKind": "App", "worker count": 1}
ClusterId =>  GetK8sClusterAccountsLatest => not ok
ClusterId =>  GetK8sClusterAccountsLatest => not ok
ClusterId =>  GetK8sClusterAccountsLatest => not ok

```

I ran with docker and got a different error, see the logs below:

```
 docker run --device /dev/sgx/enclave --device /dev/sgx/provision --network host -e KUBECONFIG=/etc/kube/config -v /etc/rancher/k3s:/etc/rancher/k3s wetee/worker:dev
Unable to find image 'wetee/worker:dev' locally
dev: Pulling from wetee/worker
edaedc954fb5: Pull complete 
cf6d27f4425f: Pull complete 
990a29630794: Pull complete 
25beea55acce: Pull complete 
ec967e51deb3: Pull complete 
9af71a9600ef: Pull complete 
Digest: sha256:6148c00402e3429445a944f7c0636e4f37a514a218850c963227aac620877785
Status: Downloaded newer image for wetee/worker:dev
EGo v1.4.1 (8b99356398dd3bcb5f74e5194d20ce421f607404)
[erthost] loading enclave ...
[erthost] entering enclave ...
[ego] starting application ...
Loading: Load from env
LoadingRules: &{ [/etc/kube/config] map[.kube/config:.kube/.kubeconfig] false <nil> true <nil>}
MintKey =>  5FUBwrwgnxRmRShJJvLEihw7cJ33nuY6cYhGoxVyJx6HMX8o
2024-02-21T16:59:44Z    INFO    setup   starting manager
2024/02/21 16:59:44 connect to http://0.0.0.0:8883 for InCluster server
2024/02/21 16:59:44 connect to http://localhost:8880/ for GraphQL playground
ClusterId =>  GetK8sClusterAccountsLatest => not ok
2024-02-21T16:59:44Z    INFO    controller-runtime.metrics      Starting metrics server
2024-02-21T16:59:44Z    INFO    controller-runtime.metrics      Serving metrics server  {"bindAddress": ":8180", "secure": false}
2024-02-21T16:59:44Z    INFO    starting server {"kind": "health probe", "addr": "[::]:8181"}
2024-02-21T16:59:44Z    INFO    Starting EventSource    {"controller": "app", "controllerGroup": "secret.wetee.app", "controllerKind": "App", "source": "kind source: *v1.App"}
2024-02-21T16:59:44Z    INFO    Starting Controller     {"controller": "app", "controllerGroup": "secret.wetee.app", "controllerKind": "App"}
2024-02-21T16:59:44Z    INFO    Starting EventSource    {"controller": "task", "controllerGroup": "secret.wetee.app", "controllerKind": "Task", "source": "kind source: *v1.Task"}
2024-02-21T16:59:44Z    INFO    Starting Controller     {"controller": "task", "controllerGroup": "secret.wetee.app", "controllerKind": "Task"}
2024-02-21T16:59:44Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: secret.wetee.app/v1: Get \"https://127.0.0.1:6443/apis/secret.wetee.app/v1\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:68
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:49
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:50
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:56
2024-02-21T16:59:44Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: secret.wetee.app/v1: Get \"https://127.0.0.1:6443/apis/secret.wetee.app/v1\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:68
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:73
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:74
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:56
2024-02-21T16:59:44Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: secret.wetee.app/v1: Get \"https://127.0.0.1:6443/apis/secret.wetee.app/v1\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:68
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func1
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:49
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:50
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:56
2024-02-21T16:59:44Z    ERROR   controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: secret.wetee.app/v1: Get \"https://127.0.0.1:6443/apis/secret.wetee.app/v1\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:68
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:73
k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/loop.go:74
k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel
        /home/wetee/go/pkg/mod/k8s.io/apimachinery@v0.28.4/pkg/util/wait/poll.go:33
sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1
        /home/wetee/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.0/pkg/internal/source/kind.go:56
ClusterId =>  GetK8sClusterAccountsLatest => not ok

```

**Comment by BurnWW** [comment]
hello @dsm-w3f, I reproduced this issue by reinstalling the environment.
 >controller-runtime.source.EventHandler  failed to get informer from cache       {"error": "failed to get API group resources: unable to retrieve the complete list of server APIs: secret.wetee.app/v1: Get \"https://127.0.0.1:6443/apis/secret.wetee.app/v1\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
 
I have update new docker image, The solution can be achieved by following these steps.
```bash
docker pull wetee/worker:dev
docker run --device /dev/sgx/enclave --device /dev/sgx/provision \
     --network host \
     -e KUBECONFIG=/etc/kube/config \
     -v /etc/rancher/k3s:/etc/rancher/k3s \
     wetee/worker:dev
```

**Comment by dsm-w3f** [comment]
@BurnWW thanks for explanations and fixes. I was able to run the system and a first round of evaluation is available in [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1141). Please provide the proper answers and fixes. Let me know when I can continue this evaluation.

**Comment by BurnWW** [comment]
@dsm-w3f  think
> azureuser@weteevm:~/examples/my-ego-app$ ego-go build main.go
go: errors parsing go.mod:
/home/azureuser/examples/my-ego-app/go.mod:3: invalid go version '1.22.0': must match format 1.23

Before Monday, I will upgrade the golang version and provide a more detailed instruction manual.

> I followed [this guide](https://github.com/wetee-dao/chain/blob/patch/docs/grants/milestone-2-documentation.md) to test. The test didn't have any problem. One doubt, is it expected to finalize the task a few blocks after [its creation](https://github.com/wetee-dao/chain/blob/patch/docs/grants/milestone-2-documentation.md)?

Here we will provide a better testing method; currently, it can only be stopped before task scheduling, which typically lasts for just one block of time. I will modify it so that tasks can be stopped at any time.

> git clone  https://github.com/integritee-network/worker && cd worker
go test ./...

 There is not a particularly strong connection between the two projects, which is due to the fact that the test document was not thoroughly reviewed, leading to elementary errors.
 Currently, we are referring to the security logic of integritee-network/worker to enhance the security of our golang program and the stability of the miners, which led to us mistakenly copying an incorrect link from the browser in our test documentation. Although we do not use the same programming language as integritee-network, nor do we have identical functionalities, the security logic and protective measures between substrate and Enclave are consistent. We sincerely apologize for making such a basic mistake.

> The examples work, but the [ego-http-server](https://github.com/wetee-dao/examples/tree/main/ego-http-server) needs instructions to build the hello.go.
The examples could have a better explanation about them on the Readme.md.
Can you explain where are the C, C++ and Python examples?

In this case, nginx is an example written in C language, and I will provide examples of both C++ programs and Python programs.

**Comment by BurnWW** [comment]
@dsm-w3f  Thank you very much, this is a significant oversight.
Due to the excessive similarity between examples in C++ and Python, compared with Nginx (written in C), we have not included them in the code. However, please be aware that we have indeed added these examples and have thoroughly tested and refined all cases.

c++  https://github.com/wetee-dao/examples/tree/main/gramine-c%2B%2B
python  https://github.com/wetee-dao/examples/tree/main/gramine-python

**Comment by dsm-w3f** [comment]
@BurnWW thank you for the improvements and fixes. I checked again and the milestone is accepted from my site. Just a small issue with the docker that could be fixed but don't prevent the acceptance of the milestone. See details in the [evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1141). Thanks for the collaboration, great job! 

@keeganquigley [the PR with the evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1141) is open and updated.

**Comment by keeganquigley** [comment]
Thanks for the quick fixes @BurnWW your evaluation was accepted and I hereby pass this milestone. Nice work!

**Comment by BurnWW** [comment]
@dsm-w3f hello, I have investigated the cause of the warning in detail.
> (libos_arch_prctl.c:81:libos_syscall_arch_prctl) [P1:T1:my-gramine-app] warning: Not supported flag (0x3001) passed to arch_prctl

A more specific warning has been found through adjustment.
`(libos_parser.c:1647:warn_unsupported_syscall) [P1:T1:ls] warning: Unsupported system call rseq`

his warning is generated by gramine, and it exists in all gramine official cases. I will continue to pay attention to and follow up this warning

**Comment by RouvenP** [comment]
hi @BurnWW we sent the payment today

**Pull request merged**
