### PR TITLE
XNFT added

### PR DESCRIPTION
**Pull request by anshulWeb3**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] This pull request is being made by the same account as the accepted application.
- [ ] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [ ] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [ ] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1798

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @anshulWeb3, thanks for the new delivery. It is currently missing the Docker deliverable, could you add that please? Ideally, it would contain the whole setup including HRMP channels already. You can leverage [Zombienet](https://github.com/paritytech/zombienet) for this.

**Comment by anshulWeb3** [comment]
We've integrated Trappist into our system, and you can find detailed information about it in the accompanying README located within the repository. For a more in-depth understanding and exploration of Trappist's features, please navigate to the Trappist branch. [Link](https://github.com/antiers-solutions/xnft/tree/trappist)

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @anshulWeb3, thanks for the update. I'm going through the readme in the trappist branch and noticed that you removed any mention of Linux: [antiers-solutions/xnft@`master...trappist`#diff-b335630551](https://github.com/antiers-solutions/xnft/compare/master...trappist#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L70). I happen to run Linux and don't have a Mac at hand; where do I find (or build) the Linux binaries?

**Comment by anshulWeb3** [comment]
Sure @semuelle . Please let me know about the distro and the  version of Linux that you are using so that we can provide the appropriate binaries to you. Thanks.

**Comment by semuelle** [comment]
> Sure @semuelle . Please let me know about the distro and the  version of Linux that you are using so that we can provide the appropriate binaries to you. Thanks.

I run Ubuntu 22.04, but I'd prefer if you could point me to the code and build instructions so anyone can build it themselves.

**Comment by anshulWeb3** [comment]
@semuelle please find the instructions [here](https://github.com/antiers-solutions/xnft/blob/master/pallet-xnft/README.md).

**Comment by anshulWeb3** [comment]
Hi @semuelle. You can find the binaries for the same in the README of this [repo](https://github.com/antiers-solutions/xnft/tree/trappist). Thanks.

**Comment by anshulWeb3** [comment]
Hello @semuelle . Do you have any updates for us regarding the delivery? Thanks.

**Comment by semuelle** [comment]
> @semuelle please find the instructions [here](https://github.com/antiers-solutions/xnft/blob/master/pallet-xnft/README.md?rgh-link-date=2024-02-13T13%3A10%3A44Z).

Hey @anshulWeb3, I am looking for instructions how to build the binaries you are referring to in the trappist readme.

**Comment by anshulWeb3** [comment]
Hello @semuelle 
Greetings of the day. 
Just wanted to check with you, is there is any progress on this grant. Are u able to build it? Is there any action pending from my side?
Please help me to take it forward!

**Comment by semuelle** [comment]
@anshulWeb3, please see my previous comment: https://github.com/w3f/Grant-Milestone-Delivery/pull/1115#issuecomment-1959032162. The readme is still referencing binary files. I would like to see the source for these and build them myself.

**Comment by anshulWeb3** [comment]
Hi @semuelle . I think there is some confusion here. I had provided the link to the instructions in  [this comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1115#issuecomment-1941483977) and in  [this subsequent comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1115#issuecomment-1943458325) i had provided the required binaries, in case you were having issues creating them yourself. Please find the attached screenshot for the same here.
Screenshot from 2024-02-28 14-53-07

**Comment by semuelle** [comment]
> I had provided the link to the instructions in [this comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1115#issuecomment-1941483977)

So, if I `cargo build` from the `master` branch, I get the `polkadot`, `parachain-template-node` and `zombienet-linux` binaries?

**Comment by anshulWeb3** [comment]
Hi @semuelle . You will get the **polkadot binary** simply by cloning the repo provided in the link https://github.com/paritytech/polkadot/tree/release-v0.9.43 and running the command as 
cargo build --release
**For the parachain-template-node binary:**
Simply clone the repo from link https://github.com/substrate-developer-hub/substrate-parachain-template/tree/polkadot-v0.9.40 
You need to add pallets _Frame nft_ and _pallet xnft_ to your parachain node template. For integration of pallets in your chain you can refer to the link https://docs.substrate.io/tutorials/build-application-logic/add-a-pallet/
After adding the pallets to your parachain node template, Kindly build it using the following command 
cargo build --release
**For zombinet-linux binary :**
You can directly download it from the link https://github.com/paritytech/zombienet/releases/
In this way you can build all the three binaries required for the testing enivironment.
After getting all the binaries please refer to step 4 of the instructions provided in the link  https://github.com/antiers-solutions/xnft/blob/master/pallet-xnft/README.md?rgh-link-date=2024-02-13T13%3A10%3A44Z to do the complete setup of Relay-Para environment.

**Comment by semuelle** [comment]
Thanks, I will try. In the meantime, could you add these instructions to the readme?

**Comment by anshulWeb3** [comment]
Hi @semuelle 
Sure, Done . Kindly check it here: https://github.com/antiers-solutions/xnft/blob/master/pallet-xnft/README.md?rgh-link-date=2024-02-13T13%3A10%3A44Z, Thanks.

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @anshulWeb3. Your milestone is hereby accepted. 

It would have been very helpful if you had provided a Dockerfile with a working trappist + xnft setup. But given the long list of changes that have already been made since your first delivery, it's acceptable as is. 

Best of luck going forward.

**Comment by semuelle** [comment]
@anshulWeb3, the invoice you submitted a while ago doesn't contain the payment address, but bank details. Please submit a new one with the payment address included or amend the grant application with fiat info (see template for details).

**Comment by anshulWeb3** [comment]
Hi @semuelle 
We have filled the invoice form with the payment address included in invoice.Please acknowledge the same.Thanks.

**Comment by semuelle** [comment]
> Hi @semuelle 
> We have filled the invoice form with the payment address included in invoice.Please acknowledge the same.Thanks.

Confirmed.

**Comment by anshulWeb3** [comment]
Hi @semuelle . Please share the Txn Hash once the payment is done so that i can confirm the same. Thanks.

**Comment by anshulWeb3** [comment]
Hello @semuelle . Any updates regarding the processing of the payment?

**Comment by anshulWeb3** [comment]
Thanks @semuelle . Looking forward to it.

**Comment by anshulWeb3** [comment]
Hi @semuelle . Waiting for your update regarding the same. Once done, please share the txn hash. Thanks.

> Hi @anshulWeb3, apparently there are technical difficulties with the invoice. I expect it to be processed on Monday.

**Comment by anshulWeb3** [comment]
Hi @semuelle . I quickly wanted to check with you. Is the payment processed?

**Comment by RouvenP** [comment]
hi @anshulWeb3 we just sent the payment

**Comment by anshulWeb3** [comment]
Thank you @RouvenP . Please share the transaction hash so that I can confirm the same.

**Comment by RouvenP** [comment]
Sure, please see [here](https://etherscan.io/tx/0xed7a28d93917a96c52cc673ebfff6d8ee5e78c4da93660a9538ef8f52bce312a)

**Comment by anshulWeb3** [comment]
Thanks @RouvenP . Verified from my side.

**Pull request merged**
