### PR TITLE
Submit the eightfish milestone 1

### PR DESCRIPTION
**Pull request by miketang84**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1407

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @miketang84. We will look into it as soon as possible. In the meantime, could you finish checking off the rest of the delivery checklist? Looks like you have everything covered.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/eightfish_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by miketang84** [comment]
> 

Got, will do it ASAP. Thanks for your evaluation.

**Comment by miketang84** [comment]
Hi, @dsm-w3f. We have done all reworks on your evaluation.

> target/release/eightfish_subnode --dev the file was named as eightfish-subnode during the building. Please either rename the file or adjust the script command.

Fixed.

> cargo build --release && target/release/subxtproxy got some warnings during the building and fails to connect.

Fixed. 

Please notice that you should boot subnode and redis server at first, and run the subxtproxy binary.

> cd http_gate && spin build --up --follow-all and cd examples/simple && spin build --up --follow-all got many errors, for example from http_gate:

Fixed.

Please notice that you should enter the container to test this. Because the new version of spin: v0.9 requires that the version of rust is above 1.66.

> The test in eightfish/eightfish-derive failed to get spin-sdk

Fixed.

> I need a complete testing guide to evaluate the system's behavior. This guide should include all features in the milestone delivery and could have print screens or videos showing how to use them. The testing guide should not need programming skills to be used. In this way, if there are programming examples they need to be complete and have scripts that we can just run to evaluate the system.

You can look at the flow_tests.md and unit_tests.md.

> I ran cargo clippy in some folders like eightfish (main folder), subnode and subproxy and got some warnings, for example in the main folder:

Fixed. 

Right now all code have been checked by `cargo check`, `cargo clippy` and `cargo fmt`.

> I tried to run cargo tarpulin in the folder eightfish/subnode/pallets/eightfish and the tests coverage is low:

Fixed.

The pallet_eightfish has been fully tested, with 11 unit tests.

But the subnode itself is just a copy of the substrate template, we didn't add more tests on it.

Since the bad network connection in this place, I'm sorry to solve these problems till today.
---

Best Regards,
Daogang Tang

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the improvements and fixes. I still having some problems to run the application. Please see details in [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/eightfish_1_dsm-w3f.md). Let me know when I can continue the evaluation.

**Comment by miketang84** [comment]
Hi, @dsm-w3f  Forgive my stupid mistakes please. Now I fixed them.

> The command cd http_gate && spin build --up --follow-all in run services returns this error:

Fixed.

> The tests in eightfish-derive is now work, but two tests were ignored.

Fixed.

> cargo clippy only returned warnings in the subnode folder.

Fixed. Currently cargo +nightly clippy remains complaining two warnings:

```
warning: type parameter goes unused in function definition                                                                                                                  
  --> pallets/eightfish/runtime-api/src/lib.rs:9:1                                    
   |                                       
9  | / sp_api::decl_runtime_apis! {                                                   
10 | |     pub trait EightFishApi {                                                   
11 | |         fn check_pair_list(Vec<u8>, Vec<(Vec<u8>, Vec<u8>)>) -> bool;                                                                                                
12 | |     }                               
13 | | }                                   
   | |_^                                   
   |                                       
   = help: consider removing the parameter                                            
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_type_parameters
   = note: `#[warn(clippy::extra_unused_type_parameters)]` on by default                                                                                                    
   = note: this warning originates in the macro `sp_api::decl_runtime_apis` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `eightfish-runtime-api` (lib) generated 1 warning                                                                                                                  
    Checking eightfish-rpc v0.1.0 (/root/eightfish/subnode/pallets/eightfish/rpc)                                                                                           
warning: very complex type used. Consider factoring parts into `type` definitions                                                                                           
  --> node/src/service.rs:41:6                                                        
   |                                       
41 |   ) -> Result<                        
   |  ______^                              
42 | |     sc_service::PartialComponents<                                             
43 | |         FullClient,                 
44 | |         FullBackend,                
...  |                                     
59 | |     ServiceError,                   
60 | | > {                                 
   | |_^                                   
   |                                       
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity                                                          
   = note: `#[warn(clippy::type_complexity)]` on by default                                                                                                                 

warning: `eightfish-subnode` (lib) generated 1 warning                                
warning: `eightfish-subnode` (bin "eightfish-subnode") generated 1 warning (1 duplicate) 
```

But they come from the substrate-node-template, not from my customized code. So here I will ignore it.

All done, thank you for your patience.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the explanations and fixes. I was able to run and test the requests provided. They worked well, however, I think the cases provided do not show all the deliverables working with the expected results. I need more examples with explanations of how the system works with them to verify the deliverables. See details in the evaluation document. Let me know when I can continue the evaluation.

**Comment by miketang84** [comment]
@dsm-w3f Thank you for your third evaluation. That's sure there is distance between the example representation we gave and the deliverables we should release. Let me do some explanations for you. 

We just provided the post process flow and query process flow tests, that seems too simple. But internally, they are complicated at all. Here are the sequence diagrams for them.

POST PROCESS FLOW:

```
     ┌────┐              ┌─────────┐                           ┌─────┐                       ┌──────────┐                           ┌───────┐          ┌───────────────┐                       ┌──┐
     │User│              │http_gate│                           │redis│                       │subxtproxy│                           │subnode│          │spin_worker_app│                       │pg│
     └─┬──┘              └────┬────┘                           └──┬──┘                       └────┬─────┘                           └───┬───┘          └───────┬───────┘                       └┬─┘
       │    1. HTTP Request   │                                   │                               │                                     │                      │                                │  
       │ ─────────────────────>                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │      2. redirect raw request      │                               │                                     │                      │                                │  
       │                      │ ──────────────────────────────────>                               │                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │ 3. listen channel `spin2proxy`│                                     │                      │                                │  
       │                      │                                   │ ──────────────────────────────>                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │      4. call `act` dispatchable     │                      │                                │  
       │                      │                                   │                               │ ────────────────────────────────────>                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │        5. emit event of `Act`       │                      │                                │  
       │                      │                                   │                               │ <────────────────────────────────────                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │        6. pass through        │                                     │                      │                                │  
       │                      │                                   │ <──────────────────────────────                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               7. listen channel `proxy2spin`        │                      │                                │  
       │                      │                                   │ ───────────────────────────────────────────────────────────────────────────────────────────>                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │ 8. main logic, write data to db│  
       │                      │                                   │                               │                                     │                      │ ───────────────────────────────>  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │     9. the result of action    │  
       │                      │                                   │                               │                                     │                      │ <───────────────────────────────  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │10. update id-hash pair index        │                      │                                │  
       │                      │                                   │ <───────────────────────────────────────────────────────────────────────────────────────────                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │        11. pass through       │                                     │                      │                                │  
       │                      │                                   │ ──────────────────────────────>                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │ 12: call `update_index` dispatchable│                      │                                │  
       │                      │                                   │                               │ ────────────────────────────────────>                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │   13: emit event of `UpdateIndex`   │                      │                                │  
       │                      │                                   │                               │ <────────────────────────────────────                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │        14. pass through       │                                     │                      │                                │  
       │                      │                                   │ <──────────────────────────────                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │      15. pass through               │                      │                                │  
       │                      │                                   │ ───────────────────────────────────────────────────────────────────────────────────────────>                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │                                   │                               │16. write data to redis cache        │                      │                                │  
       │                      │                                   │ <───────────────────────────────────────────────────────────────────────────────────────────                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │                      │ 17. retreive data from redis cache│                               │                                     │                      │                                │  
       │                      │ <──────────────────────────────────                               │                                     │                      │                                │  
       │                      │                                   │                               │                                     │                      │                                │  
       │ 18. back data to user│                                   │                               │                                     │                      │                                │  
       │ <─────────────────────                                   │                               │                                     │                      │                                │  
     ┌─┴──┐              ┌────┴────┐                           ┌──┴──┐                       ┌────┴─────┐                           ┌───┴───┐          ┌───────┴───────┐                       ┌┴─┐
     │User│              │http_gate│                           │redis│                       │subxtproxy│                           │subnode│          │spin_worker_app│                       │pg│
     └────┘              └─────────┘                           └─────┘                       └──────────┘                           └───────┘          └───────────────┘                       └──┘

```

QUERY PROCESS FLOW:

```
     ┌────┐              ┌─────────┐                                      ┌─────┐                                      ┌───────────────┐              ┌──┐          ┌──────────┐                    ┌───────┐
     │User│              │http_gate│                                      │redis│                                      │spin_worker_app│              │pg│          │subxtproxy│                    │subnode│
     └─┬──┘              └────┬────┘                                      └──┬──┘                                      └───────┬───────┘              └┬─┘          └────┬─────┘                    └───┬───┘
       │     1. HTTP query    │                                              │                                                 │                       │                 │                              │    
       │ ─────────────────────>                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │ 2. push request to redis channel `proxy2spin`│                                                 │                       │                 │                              │    
       │                      │ ─────────────────────────────────────────────>                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │          3. listen channel `proxy2spin`         │                       │                 │                              │    
       │                      │                                              │ ────────────────────────────────────────────────>                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │ 4. query data from db │                 │                              │    
       │                      │                                              │                                                 │ ──────────────────────>                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │ 5. return data from db│                 │                              │    
       │                      │                                              │                                                 │ <──────────────────────                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │ 6. make id-hash list to check the on-chain index│                       │                 │                              │    
       │                      │                                              │ <────────────────────────────────────────────────                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                               7. listen channel `spin2proxy`            │                 │                              │    
       │                      │                                              │ ──────────────────────────────────────────────────────────────────────────────────────────>                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │ 8. call `check_pair_list` rpc│    
       │                      │                                              │                                                 │                       │                 │ ─────────────────────────────>    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │   9. return checked result   │    
       │                      │                                              │                                                 │                       │                 │ <─────────────────────────────    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │                                  10. pass result through                │                 │                              │    
       │                      │                                              │ <──────────────────────────────────────────────────────────────────────────────────────────                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │   11. get the checked result and process data   │                       │                 │                              │    
       │                      │                                              │ ────────────────────────────────────────────────>                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │                                              │          12. write data to redis cache          │                       │                 │                              │    
       │                      │                                              │ <────────────────────────────────────────────────                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │                      │      13. retreive data from redis cache      │                                                 │                       │                 │                              │    
       │                      │ <─────────────────────────────────────────────                                                 │                       │                 │                              │    
       │                      │                                              │                                                 │                       │                 │                              │    
       │ 14. back data to user│                                              │                                                 │                       │                 │                              │    
       │ <─────────────────────                                              │                                                 │                       │                 │                              │    
     ┌─┴──┐              ┌────┴────┐                                      ┌──┴──┐                                      ┌───────┴───────┐              ┌┴─┐          ┌────┴─────┐                    ┌───┴───┐
     │User│              │http_gate│                                      │redis│                                      │spin_worker_app│              │pg│          │subxtproxy│                    │subnode│
     └────┘              └─────────┘                                      └─────┘                                      └───────────────┘              └──┘          └──────────┘                    └───────┘


```


And for the docker part, we are going to use docker-compose to divide these services and tests to different parts in the next phase.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the answer. We need to check the deliverables and if they are working. For example, the Upgrade utilities deliverable, how did you test it? How can I reproduce these tests? I saw that the second milestone is an integration one, however, the components should work individually in this milestone. For the flow test, how can I check if these sequence diagrams are actually running? Are there any logs? How can I see these logs? For producing examples, I recommend using examples that demonstrate the utility of the software that you are developing. If I remember, this is to facilitate the web2 to web3 adoption. Can you provide a concrete example of that for running in this evaluation?

**Comment by miketang84** [comment]
@dsm-w3f Hi, great appreciations on your reply.

> For example, the Upgrade utilities deliverable, how did you test it? How can I reproduce these tests? I saw that the second milestone is an integration one, however, the components should work individually in this milestone. 

Ok, got, we will add upgrade flow testing later.

> For the flow test, how can I check if these sequence diagrams are actually running? Are there any logs? How can I see these logs? 

Yes, there are logs. Let me write a document on how to inspect them. :)

> For producing examples, I recommend using examples that demonstrate the utility of the software that you are developing. If I remember, this is to facilitate the web2 to web3 adoption. Can you provide a concrete example of that for running in this evaluation?

Sure! We are designing our open data application now, and ready to write verifying code now, but this needs some time to advance, so I beg you give us more time (2~3 months) to accomplish the prototype of the new app, that would be a general forum for developer community. I think that would be a practical application users can use, including the front-end and back-end, and the user system. 

In addition, I want to mention that our workmate has done an [example of todo](https://github.com/eightfish-org/eightfish-example-todo), for which the backend is developed by EightFish, the frontend is developed by Yew.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the explanation and the example provided. For this milestone delivery, I need to check if the components are working individually and the flows provided. I tried to run the [TODO app example](https://github.com/eightfish-org/eightfish-example-todo) but I got this error. Can you assist with that? 

```
Worker::work: msg_obj: InputOutputObject { model: "/todo", action: "query", data: [123, 34, 114, 101, 113, 100, 97, 116, 97, 34, 58, 110, 117, 108, 108, 44, 34, 114, 101, 113, 105, 100, 34, 58, 34, 55, 48, 97, 101, 100, 97, 51, 54, 56, 98, 99, 55, 52, 102, 97, 57, 98, 54, 102, 54, 48, 54, 49, 100, 99, 55, 49, 53, 48, 52, 51, 54, 34, 125], ext: [] }
Worker::work: in query branch: ef_req
in handler todo list: params: {}
in handler todo: list: "SELECT id, description, completed FROM todo"
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: PgError::ConnectionFailed("db error: FATAL: database \"spin_dev\" does not exist\n\nCaused by:\n    FATAL: database \"spin_dev\" does not exist")', src/todo.rs:29:22
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Worker::work: msg_obj: InputOutputObject { model: "/todo", action: "query", data: [123, 34, 114, 101, 113, 100, 97, 116, 97, 34, 58, 110, 117, 108, 108, 44, 34, 114, 101, 113, 105, 100, 34, 58, 34, 50, 49, 100, 54, 57, 52, 99, 101, 100, 49, 100, 53, 52, 55, 51, 100, 97, 52, 100, 56, 100, 98, 50, 100, 55, 98, 52, 48, 50, 51, 101, 56, 34, 125], ext: [] }
Worker::work: in query branch: ef_req
in handler todo list: params: {}
in handler todo: list: "SELECT id, description, completed FROM todo"
thread '<unnamed>' panicked at 'called Result::unwrap() on an Err value: PgError::ConnectionFailed("db error: FATAL: database \"spin_dev\" does not exist\n\nCaused by:\n    FATAL: database \"spin_dev\" does not exist")', src/todo.rs:29:22
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

**Comment by taokeqin** [comment]
@dsm-w3f This is Hacken from EightFish team. 
Based on the error you pasted above, it might caused that the database is not initialized.
And I assume you are are in the docker container.
in eightfish repo we have a script to init database for the `examples/simple`:  https://github.com/eightfish-org/eightfish/blob/master/init_pg.sh


To make this todo work, 
1. we need a database named: `spin_dev`, can use use: [init_pg.sh](https://github.com/eightfish-org/eightfish/blob/master/init_pg.sh)
2. we need the following schema for todo application. refer: [create.sql](https://github.com/eightfish-org/eightfish-example-todo/blob/master/backend/schema/create.sql)

```
CREATE TABLE todo (
        id varchar PRIMARY KEY, 
        title varchar(80) NOT NULL,
        completed  boolean NOT NULL
);
CREATE TABLE todo_idhash (
        id varchar PRIMARY KEY,
        hash varchar NOT NULL
);
```

Sorry that this part does not fully described in the todo example, will improve that.
Thank you for the question.

**Comment by dsm-w3f** [comment]
@taokeqin thank you for the answer. I was able to run the application although I needed to change the "title" field name to "description" in order for the application to work. I saw some events happening during the usage of the application, however, I need to check if the todos that I registered are in the storage since is an open data application. How can I check that? I notice this storage element available but I cannot guess what to fill in the field. Can you assist with that? 

image (8)

**Comment by miketang84** [comment]
Hi, @dsm-w3f , I collected the logs of the example/simple here, and annotate it with the corresponding steps of  sequence diagrams:

https://gist.github.com/miketang84/7ae8bb7998c67c64513df480d91e93ac

Regards.

**Comment by dsm-w3f** [comment]
@taokeqin thank you for the explanations. I was able to check the logs that you provided and the information on the substrate. I understood from the application that each hash maps to a row on postgres and this should be enough to share the information between the nodes although it is not clear to me how the postgres databases sync. I didn't see yet the upgrade utilities code flow. Can you provide an example for this part?  Another part that still requires some work is the SDK. For using that, the developers need complete documentation of the code and APIs. Can you provide this documentation?

**Comment by miketang84** [comment]
Hi, regarding to the sync of pg, it doesn't sync in the pg db layer, the synchronization is based on the substrate node, just using the blockchain sync mechanism.

And other two remaining issues, pls let us do them in the following days.

Thank you.

**Comment by semuelle** [comment]
> And the testings of the upgrade functionality are on the way.

Hey @miketang84. Are you still working on this? In any case, make sure that you notify @dsm-w3f when the changes are ready for review.

**Comment by miketang84** [comment]
@semuelle Hi, I will update the progress in two days.

**Comment by miketang84** [comment]
Hi, @dsm-w3f , we updated the final two steps:

1. The SDK intro document: https://github.com/eightfish-org/eightfish/blob/master/docs/eightfish_app_tutorial.md
2. The upgrade flow tests. And the testing doc is located here:  https://github.com/eightfish-org/eightfish/blob/master/docs/upgrade.md

Sorry we're late for some other stuff.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for the improvements and fixes. The upgrade flow worked fine. The milestone is accepted. See the details in the evaluation document. I'll forward the invoice internally and the payment should take place within two weeks. Great work.

**Comment by miketang84** [comment]
Great, many thanks to all of you. :D

**Comment by miketang84** [comment]
@dsm-w3f Thank you, let me have a check and figure out how to address it.

**Comment by miketang84** [comment]
@dsm-w3f Hi, Diego, I just submitted the invoice form and file again, could you please check on that? Thanks.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for submitting a new invoice. I looked at it and seems a little confusing who is paying and who is receiving. You should try to use some invoice templates, see for example these ones: https://create.microsoft.com/en-us/templates/invoices. Usually, there are some common fields. If you fill one of these templates making clear who is receiving, who is paying, what was the service, the date of issue, and the data from payment should be enough for us. Remember, need to have the full information of W3F in the invoice, value, and address for payment as well.

**Comment by miketang84** [comment]
@dsm-w3f Hi, Diogo, I just submitted again, hope it works this time :) .   Thank you.

**Comment by dsm-w3f** [comment]
@miketang84 thank you for adjusting the invoice. Looks good to me. I'll forward it internally and the payment should take place within two weeks.

**Comment by RouvenP** [comment]
hi @miketang84 we transferred the payment today.

**Comment by miketang84** [comment]
Thanks @RouvenP , I'll check that.

**Pull request merged**
