### PR TITLE
Subauction Milestone 0

### PR DESCRIPTION
**Pull request by green-jay**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/351 + edit https://github.com/w3f/Grants-Program/pull/605

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @green-jay! We'll look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @green-jay. I am looking through your milestone and it looks pretty good so far. I was able to build the node and run the auctions tests from the `feat/auctions` branch. However, I have trouble getting the node up. Using `docker-compose`, first it failed because `./.local` was missing, now it's failing with ``"Relay chain argument error: Invalid input: `rococo-dev` only supported with `rococo-native` feature enabled.")``.

Using `polkadot-launch` as suggested in the [readme](https://github.com/galacticcouncil/Basilisk-node#rococo-local-testnet), I get the following error:

```
2021-12-07 21:53:55 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
Error: Service(Other("Failed to get runtime version: RuntimeConstruction(Other(\"host doesn't provide such function: env:ext_cr
ypto_secp256k1_ecdsa_recover_compressed_version_2\"))"))
```

Which version/branch of polkadot do you use?

**Comment by green-jay** [comment]
> Hey @green-jay. I am looking through your milestone and it looks pretty good so far. I was able to build the node and run the auctions tests from the `feat/auctions` branch. However, I have trouble getting the node up. Using `docker-compose`, first it failed because `./.local` was missing, now it's failing with `` "Relay chain argument error: Invalid input: `rococo-dev` only supported with `rococo-native` feature enabled.") ``.
> 
> Using `polkadot-launch` as suggested in the [readme](https://github.com/galacticcouncil/Basilisk-node#rococo-local-testnet), I get the following error:
> 
> ```
> 2021-12-07 21:53:55 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
> Error: Service(Other("Failed to get runtime version: RuntimeConstruction(Other(\"host doesn't provide such function: env:ext_cr
> ypto_secp256k1_ecdsa_recover_compressed_version_2\"))"))
> ```
> 
> Which version/branch of polkadot do you use?

Hi @semuelle,

Thanks! Out of curiosity, why do you want to run the whole testnet? I thought unit tests should be sufficient and provide the same guarantees for this milestone. But I updated the branch to version 0.9.12 and all seems working well now. Relay and parachain are producing blocks. Please try out :)

My setup is:
latest polkadot-launch
relay: polkadot release-v0.9.12

**Comment by semuelle** [comment]
Thanks for the update, it is working now.

> why do you want to run the whole testnet?

Indeed, the unit tests are quite thorough. I like to additionally test pallets manually, and I usually do that by running the node and using the apps UI.

One last thing: the milestone should contain "a basic tutorial describing how the software can be used and tested". Could you add that, for example as a readme in the auctions pallet folder?

**Comment by green-jay** [comment]
> One last thing: the milestone should contain "a basic tutorial describing how the software can be used and tested". Could you add that, for example as a readme in the auctions pallet folder?

done

**Comment by semuelle** [comment]
Thanks. `docker-compose` still doesn't work for me, can you have a look?

**Comment by green-jay** [comment]
> Thanks. `docker-compose` still doesn't work for me, can you have a look?

Hi @semuelle,
`(sudo) docker-compose up` executed from the root directory works on my machine. It builds the node and runs the dev chain.

**Comment by green-jay** [comment]
The problem might be that there is no dev mode for collators at the moment, so if you want to have functioning local network, polkadot-launch (or similar manual setup) is the only option.

**Comment by semuelle** [comment]
> `(sudo) docker-compose up` executed from the root directory works on my machine. It builds the node and runs the dev chain.

I'm still gettting ``Error: Input("Relay chain argument error: Invalid input: `rococo-dev` only supported with `rococo-native` feature enabled.")``. Anyway, I think the polkadot-launch config satisfies what was asked for. Your milestone is hereby accepted. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subauction_0_semuelle.md).

**Comment by semuelle** [comment]
The invoice needs our name and address, a date and should be denominated in USD. We will convert to BTC at time of payment. Please resubmit.

**Comment by green-jay** [comment]
Hi @semuelle, thank you for the guidance. I have resubmitted the invoice.

**Comment by semuelle** [comment]
Thanks, I have forwarded it for processing. Let me know if you haven't heard back within two weeks.

**Comment by RouvenP** [comment]
hi @green-jay we transferred the payment today. Thanks!

**Pull request merged**
