### PR TITLE
Stylograph

### PR DESCRIPTION
**Pull request by deep-ink-ventures**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1725

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @deep-ink-ventures. We will look into it as soon as possible. Please note that, since you submitted both milestones in one PR, we have to evaluate and approve both at the same.

**Comment by deep-ink-ventures** [comment]
We have in the meantime added a few more meaningful plugins to showcase the features at genesis dao:

[A vesting wallet and escrow contract](https://github.com/deep-ink-ventures/genesis-dao-node/tree/main/contracts/plugins), can be seen in action [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/tests/contracts/src/tests/test_genesis_dao_contract.rs#L81).

**Comment by semuelle** [comment]
Thanks for the info, @deep-ink-ventures. I started reviewing the milestones yesterday. I should have some meaningful feedback EOD tomorrow.

**Review by semuelle — COMMENTED** [review]
Hey @deep-ink-ventures. Sorry for the long wait. I have gone through most of the deliverables, and everything looks pretty good. 
Now I am trying the Genesis DAO Docker image you provided (not technically part of the milestone, but much easier to evaluate), and it seems the `genesis-dao-service` isn't working. I cannot create a DAO, because the token balance call is returning a 404: `ERROR fetchNativeTokenBalance errors - Assertion failed`. Any idea what the issue might be?

FYI, the repository link on crates.io leads to a 404: https://github.com/deep-ink-ventures/pallet-hookpoints/

**Comment by deep-ink-ventures** [comment]
Thank you Sebastian! We are currently adding a lot of updates to our chain and the service is actively changing as well, so as long as we are testnet this might happen :-)!

We'll look into this beginning of this week and come back to you asap! We'll as well fix the link.

**Comment by deep-ink-ventures** [comment]
@semuelle we fixed the link here: https://github.com/deep-ink-ventures/pallet_hookpoints/commit/f339c73f9fe69537de6afed48a1dda27c9b42325#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L8

For the other error: We are not able to reproduce that, but our frontend engineer has a suspicion and fixed that. If it still occurs please provide us with the full stack trace.

**Comment by semuelle** [comment]
Thanks for the updates. The error is gone. I'm not sure if it's based on something you changed, but I can see that the `/accounts` endpoint lists accounts with non-zero balance (so transfering tokens to any account will add it to the result list) but /account/<account> will result in 404. Perhaps by design?

**Comment by deep-ink-ventures** [comment]
In general terms the service is acting as a middleware between the node and the frontend. It listens to events and put them into a relational structure, so that it can answer things more straightforward that the frontend might need to know (things like "I'd like to show a chart of the historic balance"). [Stay tuned on this, since we and everyone who launches an app does this everytime, we are doing some design drafts on how this could be abstracted away](https://docs.google.com/document/d/1FOOj7O9aEy2Zy51kDemh4QTjBt1LDMAucqI3L3t-qP4/edit?usp=sharing).

Therefore:

- `https://service.genesis-dao.org/accounts/` lists all accounts that have been taken action, at least emitted an event
- `https://service.genesis-dao.org/accounts/5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY/` show the accounts details

So a `404` is basically the service saying "I haven't heard about this account yet", which gives you slightly more information than just showing `0`. So, yes, it's by design.

**Comment by semuelle** [comment]
Just leaving a quick update here: I have reviewed all of M1 now. Unless I run into any other issues, I will hopefully be able to finish M2 tomorrow as well.

**Review by semuelle — APPROVED** [review]
Hey @deep-ink-ventures. Sorry for the long wait. I am happy to report that both milestones are accepted. I appreciate the thorough documentation and seeing everything already in practice!

I have forwarded your invoice for processing. You can find the evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stylograph_1_semuelle.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/stylograph_2_semuelle.md). 

FYI, the transactions page on genesis-dao.org is currently return a `500` for me right now. I am logged in as Alice, if you want to test it yourself.

**Comment by deep-ink-ventures** [comment]
Thank you, very much appreciated.

Thanks as well for the error report, we are in the midst of upgrading to both v1.0.0 of polkadot and some chain improvements, and the service is currently upgrading. We're on it :-)

**Pull request merged**
