### PR TITLE
AssetHub: Atomic Swap NFT indexer M1

### PR DESCRIPTION
**Pull request by vikiival**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2271 < please fill this in with the PR number of your application.

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @vikiival thanks for the delivery. 

- The license file is broken. Can you please fix it to point to https://github.com/kodadot/stick/blob/main/LICENSE
- Are there unit tests for the CRUD handler as well?

**Comment by vikiival** [comment]
> * The license file is broken. Can you please fix it to point to 

Fixed in [9a9ef8d](https://github.com/w3f/Grant-Milestone-Delivery/pull/1198/commits/9a9ef8d97cd81b7a8053629209276c65f396499a)

> * Are there unit tests for the CRUD handler as well?

Unit tests that require usage `database` are very tricky to write.
We have written unit tests to ensure that data transformation pipeline is returning expected data. 

Regarding to the testing @subsquid team has promised some kind of testing framework for internals.

Screenshot 2024-07-29 at 11 01 16

Screenshot 2024-07-29 at 11 03 30

**Comment by keeganquigley** [comment]
> Regarding to the testing https://github.com/subsquid team has promised some kind of testing framework for internals.

Additionally, regarding the above, did you get a response?

**Comment by vikiival** [comment]
> did you get a response?

image

**Comment by vikiival** [comment]
> TODO comments in [this file](https://github.com/kodadot/stick/blob/feat/swap-it-up/src/mappings/nfts/createSwap.ts#L25).

- added clarification for dev - https://github.com/kodadot/stick/pull/294/commits/6fefe71f010baab331ef926fe7b50d89b49b7e88
- implemented saving if its present in schema - https://github.com/kodadot/stick/pull/294/commits/f1bbe8759066a597bce95e5714266e414f5feb8c

**Comment by vikiival** [comment]
gm @keeganquigley any progress>

**Comment by keeganquigley** [comment]
Thanks for the fixes @vikiival and sorry for the delay, as I was out of office last week. The TODOs have been fixed, and I'm assuming it will take some time for Subsquid to flesh out the internal testing framework (regarding the above). Since the application deliverables don't specify anything about testing for downstream dependencies, I'm willing to go ahead and pass it, but consider adding additional coverage.

Thanks and here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kodadot_assethub_indexer_m2_keeganquigley.md).

**Comment by vikiival** [comment]
> sorry for the delay

No problem, I'd rather asked ^-^ 

> as I was out of office last week.

Sun is shining ☀️, you are making awesome job. Your OOO was well-deserved!

**Comment by RouvenP** [comment]
hi @vikiival we just transferred the DOTs

**Pull request merged**
