### PR TITLE
PacificStore-Milestone-1

### PR DESCRIPTION
**Pull request by vlbos**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
I quickly started to look into your delivery. It contains some functions that are never used. Could you clean this up? Also the test for [wyvern-exchange](https://github.com/vlbos/pacific-store-node/tree/milestone-1/pallets/wyvern-exchange) didn’t compile for me, which rust version are you using? Furthermore, it looks like you are putting a lot of data on-chain. Are you planning to improve this? You should at least limit the amount of data, which is stored on-chain.

**Comment by vlbos** [comment]
> I quickly started to look into your delivery. It contains some functions that are never used. Could you clean this up? Also the test for [wyvern-exchange](https://github.com/vlbos/pacific-store-node/tree/milestone-1/pallets/wyvern-exchange) didn’t compile for me, which rust version are you using? Furthermore, it looks like you are putting a lot of data on-chain. Are you planning to improve this? You should at least limit the amount of data, which is stored on-chain.

thanks for the comment.
1. I will clean any functions that are never used.
2. rust version :   rustc 1.48.0 (7eac88abb 2020-11-16);stable-x86_64-apple-darwin (default).
3. I am to improve this.firstly, I will limit  the amount of data.secondly,I will reduce duplication of the data.thirdly, I will put a part of the data to off-chain.

**Comment by vlbos** [comment]
code updated:
1.clean some function  that are never used.

**Comment by Noc2** [comment]
@vlbos Thanks for the quick response and sorry for the very late reply. It would be nice if you could turn this into a separate repo rather than a fork of the template. Also I suggest to update the front-end template [readme.md](https://github.com/vlbos/pacific-store-node/tree/milestone-1/front-end). Additionally the testing guide for the front-end currently doesn’t work for me https://github.com/vlbos/pacific-store-node/blob/milestone-1/doc/pacific_store_milestone1_testing_guide.md#testing-guide. Specifically the following: 
```
cd front-end/scripts
yarn install
yarn example
```

**Comment by vlbos** [comment]
Thanks for the comment .We will update the repo and the front-end code as soon as possible.

**Pull request closed without merging**
