### PR TITLE
External evaluation DIA Bridgestate milestone 2

### PR DESCRIPTION
**Pull request by dastansam**
Link to the milestone delivery: #963 
Link to the application: https://github.com/w3f/Grants-Program/pull/1887

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the evaluation @dastansam so far, I haven't seen that your requested changes have been implemented yet by the grantee.

**Comment by kaythxbye** [comment]
Hi @keeganquigley we applied the changes, can you check if they fulfill your requirements?

**Comment by keeganquigley** [comment]
Thanks @kaythxbye I'll let Dastan finish his evaluation but I'll also check as well.

**Comment by dastansam** [comment]
hey @keeganquigley,

I have update my evaluation.

cc @kaythxbye

**Comment by keeganquigley** [comment]
Thanks @dastansam much appreciated. I will forward your address for payment.

**Pull request merged**
