### PR TITLE
sr25519 donna milestone 2

### PR DESCRIPTION
**Pull request by TerenceGe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks again for the delivery. I will look into it as soon as possible.

**Comment by mmagician** [comment]
@TerenceGe I've started reviewing the code and it looks good so far - however I will need more time to finish the evaluation. Please be patient and bear with me.

**Comment by TerenceGe** [comment]
@mmagician ok, no rush

**Comment by mmagician** [comment]
@TerenceGe I've been reading through your code and running the examples. In general the examples are quite illustrative and allow a user to more or less follow the workflow.

However, I've noticed that there are virtually no code comments. Everyone has their own coding style of course, though in general I would not consider this a good practice. I would not be so picky, had the documentation been perhaps a bit more inclusive than just stating the function signature, as is done in your README.

Please understand that this will be openly available code that we wish for other developers to use. The reference Rust library contains almost more comments than actual code - and while I don't expect that level of detail, in my opinion a good C library should aim to be more easily readable.

Could I please ask you to either/both:
1) include a description of the key functions & parameters within your code
2) include a more detailed description of the functions mentioned in README - could perhaps be the same as point 1), if that makes sense

**Comment by TerenceGe** [comment]
@mmagician thanks for the reviewing, just added some comments for both the code and document as you suggested.

**Comment by Noc2** [comment]
Hi @TerenceGe Thanks for the additional comments. Marcin just finished his [notes](https://github.com/w3f/Grant-Milestone-Delivery/pull/26/) and accepted your delivery. I will forward your invoice internally.

**Comment by TerenceGe** [comment]
@Noc2 ok,thanks

**Comment by RouvenP** [comment]
hi @TerenceGe test transaction sent (177cafda5f27dff8199bc4ae3cb1273c0816e690145508762354127e235456d6). could you please confirm if received?

**Comment by TerenceGe** [comment]
@RouvenP received 0.01

**Comment by RouvenP** [comment]
@TerenceGe thanks for confirming. We sent the remainder.

**Comment by TerenceGe** [comment]
@RouvenP ok, received

**Pull request merged**
