### PR TITLE
Substrate startkit GUI milestone #2 delivery 

### PR DESCRIPTION
**Pull request by ivorrr**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @ivorrr, I am trying to evaluate your code locally, but there are no pallets or templates showing in the menu. Can you advise?

image

**Comment by pajicf** [comment]
Hi @semuelle,

Could you please check if the `REACT_APP_API_BASE_URL` variable in your `.env` file is pointing to the right address of the backend (eg. `http://localhost:3001`) and if the [backend](https://github.com/MVPWorkshop/substrate-startkit-gui-api) instance is running?

**Comment by semuelle** [comment]
Hi @pajicf & @ivorrr, please see my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/substrate_startkit_gui_2_semuelle.md). 

Everything except the tests is already ticked off. Could you just add a few more tests, such as for the services on the backend and a few more integration tests?

**Comment by ivorrr** [comment]
@semuelle Sure. It was part of the plan to add more tests. Great to hear that everything else is working as you expected. We will continue to work on it this week, and we will get back to you when we finish.

**Comment by pajicf** [comment]
Hi @semuelle, we have implemented the requested changes from the evaluation notes.
Please pull the changes and check it out.
P.S. you'll need to update the `.env` file with additional new variables which can be found in the `.env.example`

**Comment by semuelle** [comment]
@ivorrr & @pajicf,
thanks for following up on the tests and installation requirements. That's a nice set of tests. :) 
I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/substrate_startkit_gui_2_semuelle.md) and your milestone is now accepted. :tada: 

Your invoice will be forwarded for processing.

**Comment by RouvenP** [comment]
hi all, we sent a test transaction. Could you please confirm if received?

**Comment by pajicf** [comment]
Hi @RouvenP , we received 0.001BTC from 35pRT........SKMt

**Comment by RouvenP** [comment]
Thanks for confirming @pajicf. we sent the payment

**Pull request merged**
