### PR TITLE
submit ink-pallet-benchmarking milestone 3

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1722

### CODE REVIEW

**Comment by Nikhil-Desai-Talentica** [comment]
Hi Team,
I had an issue while submitting the invoice form. Please help me resolve it.
Thanks.

**Comment by keeganquigley** [comment]
Hi @Nikhil-Desai-Talentica thanks for the delivery. Yes I can confirm that there is no invoice submitted for milestone 3 as far as I can tell. What issues were you having with it? Can you try submitting it again?

**Comment by dsm-w3f** [comment]
@Nikhil-Desai-Talentica thank you for the milestone delivery. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-pallet-benchmarking_3_dsm-w3f.md) and provide proper answer and fixes. Let me know when I can continue this evaluation.

**Comment by Nikhil-Desai-Talentica** [comment]
> @Nikhil-Desai-Talentica thank you for the milestone delivery. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-pallet-benchmarking_3_dsm-w3f.md) and provide proper answer and fixes. Let me know when I can continue this evaluation.

Hi team, thanks for sharing the evaluation notes, I have made the necessary changes. Please try executing the code again.

**Comment by dsm-w3f** [comment]
@Nikhil-Desai-Talentica thank you for the improvements and fixes. Now worked well. See details in [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-pallet-benchmarking_3_dsm-w3f.md). The milestone is accepted. I'll forward internally your invoice and the payment should take place within two weeks. Great job!

**Comment by dsm-w3f** [comment]
@Nikhil-Desai-Talentica I notice that you didn't send an invoice for this milestone yet. Could you please send it?

**Comment by dsm-w3f** [comment]
@Nikhil-Desai-Talentica could you confirm if the invoice was send?

**Comment by Nikhil-Desai-Talentica** [comment]
Hi Team,

Sorry for responding late. I still couldn't upload the invoice as the screen freezes as soon as I reach the stage where I have to upload the invoice for some reason. Please help me resolve it.

Thanks

**Comment by semuelle** [comment]
> Sorry for responding late. I still couldn't upload the invoice as the screen freezes as soon as I reach the stage where I have to upload the invoice for some reason. Please help me resolve it.

Hi @Nikhil-Desai-Talentica. Do you mind me asking what browser you are using? If no other browser works, you can send the invoice to grants at web3.foundation.

**Comment by Nikhil-Desai-Talentica** [comment]
Hi @semuelle, thanks for sharing this alternative. I have mailed the invoice. I am using chrome by the way.

**Comment by Nikhil-Desai-Talentica** [comment]
Hi @semuelle, I have submitted an amendment to this application(at W3F Grants repo) providing the new registered address and entity. Please process this as soon as possible.

**Comment by Nikhil-Desai-Talentica** [comment]
Hi @semuelle, just a gentle reminder to process the payment for this. Thanks and have a great day!

**Comment by semuelle** [comment]
Sorry for the delay, @Nikhil-Desai-Talentica. It should be paid this Friday latest.

**Comment by RouvenP** [comment]
hi @Nikhil-Desai-Talentica we just processed the payment. Thanks & apologies for the delay

**Pull request merged**
