### PR TITLE
Konomi evaluation, M1

### PR DESCRIPTION
**Pull request by mmagician**
Still missing one license file

### CODE REVIEW

**Comment by willeslau** [comment]
@mmagician We have added in the license file, should be all good now

**Comment by RouvenP** [comment]
hi @willeslau we just sent a test transaction. Could you confirm if received?

**Comment by willeslau** [comment]
Hi @RouvenP, may I know if you test transaction is on our parachain test site? Or something else?

**Comment by RouvenP** [comment]
@willeslau we sent a BTC test transaction for your invoice #101: https://www.blockchain.com/btc/tx/2848eedfa30395aee58c6ee422cfdc5333f75068a5cad9b27a14dbdfe7121fc1

**Comment by willeslau** [comment]
@RouvenP ok, will check with the team. Please give me some time as it's already Friday night in our timezone, will take some time to reach them. I'll update asap.

**Comment by RouvenP** [comment]
@willeslau no hurry, we can do that next week too.

**Comment by willeslau** [comment]
@RouvenP we have received the testing transaction:)

**Comment by willeslau** [comment]
@RouvenP may I check with you on the follow ups of the transactions:)?

**Comment by RouvenP** [comment]
hi @willeslau we sent the payment last Friday: 1569b6f29c5d90101d2063722240fde6a3379b30c78992777294a6deafef3e3a

**Pull request merged**
