### PR TITLE
java client lib - milestone 1 delivery

### PR DESCRIPTION
**Pull request by splix**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. I will try to look into it as soon as possible.

**Comment by Noc2** [comment]
I started to look into your delivery, but when I run gradle install. I currently get the following error: 
```
> Task :polkaj-types:javadoc FAILED
/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Address.java:3: error: cannot access SS58Type
import io.emeraldpay.pjc.ss58.SS58Type;
                             ^
  bad class file: /home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-ss58/build/libs/polkaj-ss58-0.2.0-SNAPSHOT.jar(io/emeraldpay/pjc/ss58/SS58Type.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
1 error
```

**Comment by splix** [comment]
It seems that you have Java 8 enabled (52.0), but the project has Java 11 (55.0). Can you switch to Java 11 or later?

**Comment by Noc2** [comment]
Thanks for the quick reply. I don't know much about java, but my `java --version` output is currently the following, which looks like java 11 to me: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)
```

**Comment by splix** [comment]
Yes, it's Java 11.

**Comment by splix** [comment]
That's strange, but there is definitely a version conflict, but I don't understand how it happened. The error message is also looks weird.

Can you try?
```
gradle clean install
```

`clean` should remove all existing artifacts before the next command

**Comment by Noc2** [comment]
I’m still getting the same error. It’s probably again some issue because I’m running it on ubuntu and you are using a mac (if I remember correctly).

**Comment by splix** [comment]
Yes, I'm on Mac, but this doesn't look like something related to OS. 

You can try to run Gradle with `--info` with gives more details. Also please check if there anything in your `~/.m2/repository/io/emeraldpay/polkaj`, it's where it intals the binaries. You may remove the directory, maybe it would help. As well as remove `./build` directory

**Comment by splix** [comment]
That's actually what `install` is basically doing, it makes a build and copies files to the `~/.m2/repository/io/emeraldpay/polkaj` so other projects can reuse it from here. 

You may also use `gradle test` to run tests, or `gradle build` to build without installing. It will build each module (`polkaj-***`) and put results into module's `build` dir

**Comment by Noc2** [comment]
I tried to remove the diretory ~/.m2/repository/io/emeraldpay/polkaj, but it doesn’t help. Also here is the important part of the gradle install --info output:
```
Task :polkaj-types:javadoc FAILED
Caching disabled for task ':polkaj-types:javadoc' because:
  Build cache is disabled
Task ':polkaj-types:javadoc' is not up-to-date because:
  Task has failed previously.
file or directory '/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/groovy', not found
Starting process 'command '/usr/bin/javadoc''. Working directory: /home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types Command: /usr/bin/javadoc @/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/tmp/javadoc/javadoc.options
Successfully started process 'command '/usr/bin/javadoc''
/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Address.java:3: error: cannot access SS58Type
import io.emeraldpay.pjc.ss58.SS58Type;
                             ^
  bad class file: /home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-ss58/build/libs/polkaj-ss58-0.2.0-SNAPSHOT.jar(io/emeraldpay/pjc/ss58/SS58Type.class)
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
1 error
Problems generating Javadoc.
  Command line issued: [/usr/bin/javadoc, @/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/tmp/javadoc/javadoc.options]
  Generated Javadoc options file has following contents:
------
-classpath '/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/classes/java/main:/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/classes/groovy/main:/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/resources/main:/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-ss58/build/libs/polkaj-ss58-0.2.0-SNAPSHOT.jar:/home/noc2/.gradle/caches/modules-2/files-2.1/com.github.multiformats/java-multibase/v1.0.0/745c5b560514a1ba22c5b045aae0367cd033ced/java-multibase-v1.0.0.jar'
-d '/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/build/docs/javadoc'
-doctitle 'polkaj-types 0.2.0-SNAPSHOT API'
-notimestamp 
-quiet 
-windowtitle 'polkaj-types 0.2.0-SNAPSHOT API'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/DotAmount.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Hash512.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Hash256.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Address.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/FixedBytes.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/Units.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/DotAmountFormatter.java'
'/home/noc2/source/web3/evaluation/emeraldpay/polkaj/polkaj-types/src/main/java/io/emeraldpay/pjc/types/HexNumberFormat.java'
------
:polkaj-types:javadoc (Thread[Execution worker for ':',5,main]) completed. Took 0.667 secs.
```

**Comment by splix** [comment]
I'm setting up an environment with Ubuntu, to test everything and make sure it works. Will keep you posted

**Comment by splix** [comment]
I've tried to make a build on Ubuntu (versions `19.10` and `20.04`), but wasn't able to reproduce. It's something more tricky. 

I suggest you to try to run with bundled gradle by `./gradlew clean build`. It will make sure that the Gradle version is the same as I was using for the development. And it will eliminate the chance that it was somehow affected by the Gradle.

Also I would suggest to try to build with Java 13 (`sudo apt install openjdk-13-jdk-headless`), which works with class-files with version `55.0`. Java 11 is not requirements, it's just current LTS and a minimal requirement for compatibility. So at is somehow gave you compiled files for Java 13 just use that version.

**Comment by Noc2** [comment]
Hi. Thanks for the quick reply and help here. `sudo apt install openjdk-13-jdk-headless` was indeed able to resolve the issue for me. As you might have noticed, in the meantime also someone else looked [into your delivery](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/java-client_1_mmagician.md) and you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/java-client_1_Noc2.md). (I didn’t have much to add) I will forward your invoice internally.

**Comment by splix** [comment]
Thank you for the update and review. And thank you for the feedback notes, it was really helpful.

DecimalFormat is indeed producing different results depending on locale and other configurations, that's the whole purpose of it. Which I totally forgot writing those unit tests. Funny enough, I use en_US locale on my machines only because I stepped on this problem many times before with other's code.

I've fixed the test, and updated testing config for Polkaj, to include all locales. Including de_DE, and de_CH. Also, now I run tests on all combinations of OSes and available JVM versions.

**Comment by splix** [comment]
@Noc2 hi, I'd like to ask if I need to do anything to initiate the payment for the milestone

**Comment by Noc2** [comment]
@splix No, I forwarded you invoice to the open grants operations team: https://github.com/w3f/Open-Grants-Program#team They should reach out to you in case they have any questions.

**Comment by RouvenP** [comment]
> @Noc2 hi, I'd like to ask if I need to do anything to initiate the payment for the milestone

hi @splix we sent a test transaction yesterday. Could you please let us know if received?

**Comment by splix** [comment]
@RouvenP hi, yes, I can confirm receiving of 0.01BTC

**Comment by RouvenP** [comment]
@splix we just transferred the remainder of 1.44BTC

**Comment by splix** [comment]
@RouvenP thank you, I confirm receiving

**Pull request merged**
