### PR TITLE
Sup milestone 1 and 2

### PR DESCRIPTION
**Pull request by clearloop**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 

## [Sup](https://github.com/clearloop/sup)

Note: Here are some changes in this delivery of milestone 2, we use a `config.toml` under `~/.sup/config.toml` to handle the customized substrate registry instead of adding a `--registry` flag to every command.

### CODE REVIEW

**Comment by mmagician** [comment]
@clearloop Thanks for delivering the milestones, we will check them as soon as possible.

**Comment by clearloop** [comment]
+ Forgetting to add tag fields to the node-templates sup generated, it will cause the template could not be compiled.
+ The output of `update` and `upgrade` have low quality

I'll fix the issues above this weekend, welcome to find more issues

**Comment by clearloop** [comment]
> * Forgetting to add tag fields to the `node-template` sup generated, it will cause the template with old tags could not be compiled.
> * The output of  command `update` and `upgrade` has low quality
> 
> I'll fix the issues above this weekend, welcome to find more issues

+ [x] Fixed the old tag problems
+ [x] Use `sup switch` instead of `sup upgrade` for easy understanding

**Comment by mmagician** [comment]
@clearloop I just tried running `sup tag` and got the following list:
```
v2.0.0-rc6
v2.0.0-rc5+2
v2.0.0-rc5+1
v2.0.0-rc5
v2.0.0-rc4
v2.0.0-rc3
v2.0.0-rc2+2
v2.0.0-rc2
v2.0.0-rc1
v2.0.0-alpha.8
```
It doesn't look to be a comprehensive list (e.g. the newest v2.0.0 is missing). Is this expected behaviour?

Also, perhaps you could add some usage examples to your [README](https://github.com/clearloop/sup/blob/master/README.md) please?

**Comment by clearloop** [comment]
> @clearloop I just tried running `sup tag` and got the following list:
> 
> ```
> v2.0.0-rc6
> v2.0.0-rc5+2
> v2.0.0-rc5+1
> v2.0.0-rc5
> v2.0.0-rc4
> v2.0.0-rc3
> v2.0.0-rc2+2
> v2.0.0-rc2
> v2.0.0-rc1
> v2.0.0-alpha.8
> ```
> 
> It doesn't look to be a comprehensive list (e.g. the newest v2.0.0 is missing). Is this expected behaviour?
> 
> Also, perhaps you could add some usage examples to your [README](https://github.com/clearloop/sup/blob/master/README.md) please?

Please check this page, https://github.com/clearloop/sup/blob/master/GUIDE.md, it is mentioned in the README.

**Comment by clearloop** [comment]
Updated at https://github.com/clearloop/sup/pull/9 @mmagician 

+ [x] Auto-check `rustup` toolchain in `sup new`
+ [x] Init v2.0.0 substrate as default in `sup new`
+ [x] Order the output of `sup tag` by the created date
+ [x] Update [GUIDE.md][GUIDE] for v0.2.6

Now we can try `sup v0.2.6` with `cargo install sup` ~

[GUIDE]: https://github.com/clearloop/sup/blob/master/GUIDE.md

**Comment by mmagician** [comment]
@clearloop Thanks for quick fixes.
I have some more questions:

1. I suppose that `sup config` without arguments should just `cat` the config file, right? 
2. When I ran `sup config -r https://github.com/shawntabrizi/substrate.git`, the command correctly edited the file under `~/.sup/config.toml`, but then simply `sup config` doesn't output anything.
Running `sup config` again resets the config file to the original state, erasing my earlier changes
3. Let's say I update the config file manually to point to: `https://github.com/shawntabrizi/substrate.git`. How do I then update the project (running `sup update` doesn't work)?

**Comment by clearloop** [comment]
> @clearloop Thanks for quick fixes.
> I have some more questions:
> 
> 1. I suppose that `sup config` without arguments should just `cat` the config file, right?

It shows the content of the `.sup/config.toml`


> 2. When I ran `sup config -r https://github.com/shawntabrizi/substrate.git`, the command correctly edited the file under `~/.sup/config.toml`, but then simply `sup config` doesn't output anything.
>    Running `sup config` again resets the config file to the original state, erasing my earlier changes

This is a BUG XDD, I'll fix it tonight.

> 3. Let's say I update the config file manually to point to: `https://github.com/shawntabrizi/substrate.git`. How do I then update the project (running `sup update` doesn't work)?

The `update` command updates the registry, it pulls the upstream of the current git source. If you want to update the project, you should run `sup switch -p <your-project>`

### `Update` or `Switch`

`sup update` is like `rustup update`, but for a package manager, it should like `cargo update`, it makes you confused, and I think you are right.

I'm preparing to swap the `update` command and `switch` command, maybe remove the current `switch` command, I'll update a new version tonight, thanks for your testing @mmagician!!, this will make this project better than before~

**Comment by mmagician** [comment]
@clearloop Thanks.
Regarding the last point, feel free to stick to either `update` or `switch`. The most important thing is that documentation clearly states which is which, and how to use it :)

**Comment by clearloop** [comment]
Hi @mmagician, I just refactored the commands of sup:

+ [x] Rename command `switch` to `update`
+ [x] Use `--pull` as a top flag for updating registry
+ [x] Combines `tag` and `source` into list

**Comment by mmagician** [comment]
@clearloop I did another round of testing.
- It still looks like `sup config set -r <registry name>` doesn't work. 
E.g. `sup config set -r https://github.com/shawntabrizi/substrate.git` doesn't change anything under `~/.sup/config.toml`
What is this registry responsible for, anyway?
- Update command worked for tag. Is it used for anything else? Does it somehow tie into how registry is used? Because even if I manually set the registry and then run `sup update -t <tag from new registry>`, nothing happens.
Example:
1. `sup update -t polkadot-0-8-25-dep` works fine, as it updates the file `<my_project>/runtime/Cargo.toml`
2. Manually set registry as `registry = "https://github.com/shawntabrizi/substrate.git"`
3. `sup list tag` lists the tags from new registry just fine
4. `sup update -t <tag from new registry>` doesn't seem to affect `<my_project>/runtime/Cargo.toml` anymore

**Comment by clearloop** [comment]
> @clearloop I did another round of testing.
> 
> * It still looks like `sup config set -r <registry name>` doesn't work.
>   E.g. `sup config set -r https://github.com/shawntabrizi/substrate.git` doesn't change anything under `~/.sup/config.toml`
>   What is this registry responsible for, anyway?

Sorry about that! It's a BUG...Fixed at https://github.com/clearloop/sup/pull/12#discussion_r532838083.


> * Update command worked for tag. Is it used for anything else? Does it somehow tie into how registry is used? Because even if I manually set the registry and then run `sup update -t <tag from new registry>`, nothing happens.

This is a BUG as well...FIxed at https://github.com/clearloop/sup/pull/12/commits/76d00751c1d2442b9fbe3824fa363f20eb632d6c

---

Just published [sup v0.2.8][0],

<details>
<summary>Test</summary>
<code><pre>
 𝝺 sup
sup 0.2.8

USAGE:
    sup [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -p, --pull       Pulls and updates the global registry
    -V, --version    Prints version information

SUBCOMMANDS:
    config    Shows or edits the current config
    help      Prints this message or the help of the given subcommand(s)
    list      List registry source or tags
    new       Create a new substrate node template
    update    Update the target substrate project

 𝝺 sup new hello
Created node-template "hello" succeed!

 𝝺 sup config list
Config {
    metadata: MetaData {
        authors: [
            "clearloop <udtrokia@gmail.com>",
        ],
        version: "0.1.0",
        license: "MIT",
    },
    node: Node {
        registry: "https://github.com/paritytech/substrate.git",
    },
}

 𝝺 sup config set -r https://github.com/shawntabrizi/substrate.git 
 𝝺 sup list tag
v0.2.16
v0.2.15
v0.2.14
v0.2.13
v0.2.12
v0.2.11
v0.2.10
v0.2.9
v0.2.8
v0.2.7

 𝝺 sup update -p hello 
Use the latest registry without tags for hello

 𝝺 cat hello/node/Cargo.toml 
[package]
name = "node-template"
version = "2.0.0"
authors = ["clearloop <udtrokia@gmail.com>"]
description = "A new FRAME-based Substrate node, ready for hacking."
edition = "2018"
license = "MIT"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git", features = ["wasmtime"] }
sp-core = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-executor = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git", features = ["wasmtime"] }
sc-service = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git", features = ["wasmtime"] }
sp-inherents = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-consensus-aura = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-consensus-aura = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-consensus = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-consensus = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-finality-grandpa = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-finality-grandpa = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-client-api = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-runtime = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }

\# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.0.0"
sc-rpc = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-api = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-rpc-api = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-blockchain = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sp-block-builder = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/shawntabrizi/substrate.git" }
substrate-frame-rpc-system = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
pallet-transaction-payment-rpc = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }

\# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }
frame-benchmarking-cli = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]
</pre></code></details>

Passed the test above, ready for review @mmagician  : )

> Note: We can not update the node-template generated by sup using the tags of https://github.com/shawntabrizi/substrate.git, because the tagged code in that repo doesn't have `node-template`

[0]: https://crates.io/crates/sup

**Comment by mmagician** [comment]
@clearloop Sorry for the delay. I've reviewed your package again. Thanks for fixing the bugs.
So there is no checking done, for example clearly if you list the tags for `https://github.com/shawntabrizi/substrate.git` there is no version/tag "2.0.0" - is this indended?

**Comment by clearloop** [comment]
> So there is no checking done, for example clearly if you list the tags for `https://github.com/shawntabrizi/substrate.git` there is no version/tag "2.0.0" - is this indended?

Yep, you can view the tags of this repo at https://github.com/shawntabrizi/substrate/tags

**Comment by mmagician** [comment]
@clearloop Yes, that's what I'm saying. There is no tag "2.0.0" listed for that repository, and yet in the `Cargo.toml` we end up with things like: `sp-core = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }`

This does not seem correct to me, I think it's misleading to the users, don't you think?

**Comment by clearloop** [comment]
> @clearloop Yes, that's what I'm saying. There is no tag "2.0.0" listed for that repository, and yet in the `Cargo.toml` we end up with things like: `sp-core = { version = "2.0.0", git = "https://github.com/shawntabrizi/substrate.git" }`
> 
> This does not seem correct to me, I think it's misleading to the users, don't you think?

Yep, you are right.

I can add a tag check at switching repos, tonight
+ If the target repo has the current tag
   + switch
   + panic or use the latest tag

**Comment by mmagician** [comment]
@clearloop Thanks, sounds good. I think it would greatly improve the user experience.

**Comment by clearloop** [comment]
The process is quite complex, now we have `.sup.toml` for projects generated by `sup`.

```
 𝝺 sup --version
sup 0.2.9

# Global registry is https://github.com/shawntabrizi/substrate.git, can not create node-template with the latest tag v0.2.16
 𝝺 sup new hello
The registry https://github.com/shawntabrizi/substrate.git at tag v0.2.16 doesn't have node-template
failed.

# Set to https://github.com/paritytech/substrate.git
 𝝺 sup config set -r https://github.com/paritytech/substrate.git
ok!

# Create node-template succeed
 𝝺 sup new hello                                                
Created node-template "hello" succeed!
ok!

# Set to shawntabrizi
 𝝺 sup config set -r https://github.com/shawntabrizi/substrate.git
ok!

# Trying to update and failed, because of the protection of `hello/.sup.toml`, 
#
# Note: Here we are using the global config because we are out of the directory `hello`
 𝝺 sup update -p hello                                            
Registry https://github.com/shawntabrizi/substrate.git with tag None doesn't have node-template, please retry with `--update` flag
failed.

# Enter `hello` and try to update, it will succeed because the `.sup.toml` 
# recorded the registry https://github.com/paritytech/substrate.git
 𝝺 cd hello && sup update
Update . with tag v2.0.0
ok!

# Set registry under `hello`, it will apply to `hello/.sup.toml`
 𝝺 sup config set -r https://github.com/shawntabrizi/substrate.git
ok!

# Update and fail
 𝝺 sup update                                                     
Doesn't have tag v2.0.0 in registry, please retry with `--update` flag
failed.
```

Please check this update @mmagician ~

**Comment by mmagician** [comment]
@clearloop I could reproduce the above steps and get the same output as you did.
So at the current state, is there any use for the command `sup update`? From our last exchange I understood that it would check which dependencies have the current tag (e.g. v2.0.0) and update these; otherwise use the newest tag available.
The last step from your instructions says to use it with `--update` (which would be `sup update --update`?) but the flag `--update` is not recognised. Perhaps you could provide some concrete example where changing a registry and updating would work please?

**Comment by clearloop** [comment]
> The last step from your instructions says to use it with `--update` (which would be `sup update --update`?) but the flag `--update` is not recognised. Perhaps you could provide some concrete example where changing a registry and updating would work please?

Likewise, `sup --update update`... 

I'll make a new PR tonight to clean the instructions~

**Comment by clearloop** [comment]
The new instruction is like below

```
 𝝺 sup --version
sup 0.2.11

 𝝺 sup new hello
Created node-template "hello" with tag v2.0.0 succeed!
ok!

 𝝺 cd hello && sup config set -r https://github.com/shawntabrizi/substrate.git
ok!

 𝝺 sup update
Doesn't have tag v2.0.0 in registry https://github.com/shawntabrizi/substrate.git, please retry with `sup -p update -t v2.0.0`
failed.
```

`sup` is a powerful command-line tool as a substrate generator, we are thinking it's too simple and functions less, it is, and it also because the substrate project is at an early stage that we hardly can realize the usage of both `sup` and `substrate`.

`sup` is the first step of my great adventure in the ecosystem which is wrapping substrate as a decentralized App Engine, I need daily jobs to learn substrate, prove my thought, and integrate into society, so I have to implement it step by step, and the next project of mine is providing a GraphQL Engine for the storage of substrate.

**Comment by mmagician** [comment]
@clearloop I understand that your project is still in its early stage. I wish you best of luck on your journey with substrate.

> The main usage of the update command is sup update -t <tag>, switching registry tag for target projects.

Ok, that makes sense. So then as far as I see, there is no practical use case for switching the registries themselves, but only the tags within one registry, right?

Anyway, I have now accepted your milestones 1 & 2, you can see the comments [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/65). Thank you for being very responsive to my comments in this thread 👍

**Comment by RouvenP** [comment]
hi @clearloop we just sent a test transaction. Could you please confirm if received?

**Comment by clearloop** [comment]
> hi @clearloop we just sent a test transaction. Could you please confirm if received?

@RouvenP  Received~

**Comment by RouvenP** [comment]
thanks for confirming @clearloop. the payment is done.

**Comment by clearloop** [comment]
> thanks for confirming @clearloop. the payment is done.

Received, thanks!!! I'll work harder next time.

**Pull request merged**
