### PR TITLE
Submit php-rpc-lib milestone 2

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/622

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery @gmajor-encrypt. We will look into it as soon as possible. We currently have a large backlog, so it might take a bit longer than usual.

**Comment by keeganquigley** [comment]
Hi @gmajor-encrypt, I'm helping to review your milestone and I have a question. After running the troubleshooting script you provided, I am still running into the binding errors when navigating back to `php-substrate-api` to run the tests. Is there something else I need to do after running the script? As someone who is not super familiar with Go, any expansion upon the troubleshooting instructions would be of great help. Thanks!

**Comment by gmajor-encrypt** [comment]
@keeganquigley hi, Are you still getting this error? https://github.com/gmajor-encrypt/php-substrate-api/#ffi-error-ffiexception-failed-loading-php-substrate-apivendorgmajorsr25519-bindingssrccryptosr25519so

**Comment by keeganquigley** [comment]
@gmajor-encrypt yep, that's the exact error I'm getting when running the tests from my MacBook. I ran the provided script but I still get the same binding error:

```
4) Rpc\Test\HashTest::testEd25519
FFI\Exception: Failed loading '/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.so'

/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.php:29
/Users/keeganquigley/php-substrate-api/src/Rpc/Hasher/Hasher.php:20
/Users/keeganquigley/php-substrate-api/test/Rpc/HashTest.php:18

5) Rpc\Test\HashTest::testKeyring
FFI\Exception: Failed loading '/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.so'

/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.php:29
/Users/keeganquigley/php-substrate-api/src/Rpc/Hasher/Hasher.php:20
/Users/keeganquigley/php-substrate-api/test/Rpc/HashTest.php:18

6) Rpc\Test\StorageKeyTest::testStorageKeyEncode
FFI\Exception: Failed loading '/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.so'

/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.php:29
/Users/keeganquigley/php-substrate-api/src/Rpc/Hasher/Hasher.php:20
/Users/keeganquigley/php-substrate-api/src/Rpc/StorageKey.php:104
/Users/keeganquigley/php-substrate-api/test/Rpc/StorageKeyTest.php:35

--

There was 1 failure:

1) Rpc\Test\ClientTest::testHttpClientShouldReceiveData
Failed asserting that exception of type "FFI\Exception" matches expected exception "InvalidArgumentException". Message was: "Failed loading '/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.so'" at
/Users/keeganquigley/php-substrate-api/vendor/gmajor/sr25519-bindings/src/Crypto/sr25519.php:29
/Users/keeganquigley/php-substrate-api/src/Rpc/Hasher/Hasher.php:20
/Users/keeganquigley/php-substrate-api/src/Rpc/SubstrateRpc.php:40
/Users/keeganquigley/php-substrate-api/test/Rpc/ClientTest.php:59
.

ERRORS!
Tests: 11, Assertions: 18, Errors: 6, Failures: 1.
```

**Comment by gmajor-encrypt** [comment]
Uh, no idea,  run this command ``cd vendor/gmajor/sr25519-bindings/go && go build -buildmode=c-shared -o ../src/Crypto/sr25519.so .``  Are there any errors?

**Comment by gmajor-encrypt** [comment]
@keeganquigley I try to use github ci in macOS https://github.com/gmajor-encrypt/php-substrate-api/runs/6317088363?check_suite_focus=true,There seems to be no problem 
maybe the GOLANG version will cause some errors. 

you can try use golang 1.7.3 like this https://github.com/gmajor-encrypt/php-substrate-api/blob/master/.github/workflows/ci.yml#L28

**Comment by keeganquigley** [comment]
Hi again @gmajor-encrypt thanks for linking your CI tests. I was able to get the FFI to build as well. Seeing as everything else works, I'm okay with passing this milestone. However, I will agree with Alxs' previous assessment that the docs are a bit sparse and could be improved. Even adding a sentence or two above your code examples would help to make it clearer and more robust. I will let the team know!

**Comment by gmajor-encrypt** [comment]
@keeganquigley  Thanks for your reply. At present, this is a long-term project, and I will continue to improve the feature, including the code, which has been used by some developers, and I am constantly improving it.

**Review by takahser — APPROVED** [review]
@gmajor-encrypt I'm happy to announce that the delivery has been [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/php-rpc-lib_2_keeganquigley.md) by @keeganquigley
I'll forward the invoice, pls allow for up to 2 weeks until the payment arrives.

**EDIT**

@gmajor-encrypt unfortunately I wasn't able to locate your [invoice](https://forms.gle/LSRr7PCjBpEbKGh89). Did you upload it? Can you maybe share the filename and upload date? Thanks.

**Comment by gmajor-encrypt** [comment]
@takahser Thank you. I have filled out https://forms.gle/LSRr7PCjBpEbKGh89, the time is `May 10`, the file name is `inva.html.pdf`

**Comment by fededubbi** [comment]
Good morning,

I noticed that the invoice reports still our old billing address.
The correct one is the following:

Baarerstrasse 14,
6300, Zug.

Could you please update the invoice with this address?
Also, can you please use only the currency in which you want the payment to be made in?

Right now next to the amount there is both USD and DAI.
I think this should be only DAI.

Many thanks,
Federica

**Comment by gmajor-encrypt** [comment]
@fededubbi I have just resubmitted my invoice, thanks for your feedback

**Pull request merged**
