### PR TITLE
add merkle tree milestone 1 delivery

### PR DESCRIPTION
**Pull request by frisitano**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1179

### CODE REVIEW

**Comment by takahser** [comment]
Hi @frisitano 
Thanks for the delivery, I will take a look and provide you with feedback soon.

**Comment by frisitano** [comment]
> Hi @frisitano 
> 
> Thanks for the delivery, I will take a look and provide you with feedback soon.

Thank you. I appreciate it!

**Review by takahser — CHANGES_REQUESTED** [review]
@frisitano I took a first look and added [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/merkle-tree_1_takahser.md), feel free to have a look and ask questions here in this thread, should there be any unclarities.

**Comment by takahser** [comment]
@frisitano

> I believe this is the pattern that we use? Could you provide some feedback with reference to one of the tests so I can better understand what you are expecting please?

I think you use it in some places, but maybe you can double-check.
Let's for example take [this test](https://github.com/frisitano/merkle-tree-db/blob/0c876f48a6605960eb3f16e5fca4af6a9e91721f/src/tests.rs#L271-L295):

```rust
macro_rules! test_insert {
    ($name:ident, mut $tree:ident, $selector:tt) => {
        #[test]
        fn $name() {
            let (mut db, mut root) = mock_data();
            let mut tree = $tree::<TREE_DEPTH, Sha3>::new(&mut db, &mut root)
                .unwrap()
                .build();

            let new_value = b"new value";
            let new_leaf = Sha3::hash(new_value).into();
            let old_value = tree
                .insert(&TEST_DATA[0].$selector, new_value.to_vec())
                .unwrap();

            assert_eq!(old_value, Some(TEST_DATA[0].2.to_vec()));

            let actual_value = tree.value(&TEST_DATA[0].$selector).unwrap();
            assert_eq!(actual_value, Some(new_value.to_vec()));

            let actual_leaf = tree.leaf(&TEST_DATA[0].$selector).unwrap();
            assert_eq!(actual_leaf, new_leaf);
        }
    };
}
```

There are quite a few things happening in there, so it'd be helpful to group the code into 3 sections:
- Arrange
- Act
- Assert

One possible way to do it would be:

```rust
macro_rules! test_insert {
    ($name:ident, mut $tree:ident, $selector:tt) => {
        #[test]
        fn $name() {
            // ARRANGE
            let (mut db, mut root) = mock_data();
            let mut tree = $tree::<TREE_DEPTH, Sha3>::new(&mut db, &mut root)
                .unwrap()
                .build();
            let new_value = b"new value";

            // ACT
            let new_leaf = Sha3::hash(new_value).into();
            let old_value = tree
                .insert(&TEST_DATA[0].$selector, new_value.to_vec())
                .unwrap();
            let actual_value = tree.value(&TEST_DATA[0].$selector).unwrap();
            let actual_leaf = tree.leaf(&TEST_DATA[0].$selector).unwrap();

            // ASSERT
            assert_eq!(old_value, Some(TEST_DATA[0].2.to_vec()));
            assert_eq!(actual_value, Some(new_value.to_vec()));
            assert_eq!(actual_leaf, new_leaf);
        }
    };
}
```

Though I think you can skip the comments if you group the statements and leave a break between each block.
Mixing _act_ and _assert_ code makes the tests harder to read. Does that make sense, or am I missing something?

>I have updated the examples with the new name and also added github CI tests to ensure this doesn't happen again see the PR https://github.com/frisitano/merkle-tree-db/pull/26.

Ok perfect, thanks! I'll be back with more feedback soon.

**Comment by frisitano** [comment]
> Though I think you can skip the comments if you group the statements and leave a break between each block. Mixing _act_ and _assert_ code makes the tests harder to read. Does that make sense, or am I missing something?

@takahser.  Yes that makes sense, thanks for taking the time to provide an example and explanation! I've gone ahead and updated the tests to follow this pattern and also updated the milestone delivery doc to reflect the new commit hash.  I look forward to hearing back with additional feedback.

**Review by takahser — APPROVED** [review]
@frisitano thanks for the updates and the speedy feedback to my [PR](https://github.com/frisitano/merkle-tree-db/pull/28). LGTM now! You can find my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/merkle-tree_1_takahser.md).

**Comment by RouvenP** [comment]
hi @frisitano we transferred the payment today.

**Pull request merged**
