### PR TITLE
feat: Doter milestone2

### PR DESCRIPTION
**Pull request by ChainBridgeNetworkTeam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Open-Grants-Program/pull/356

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks @ChainBridgeNetworkTeam, we will check your delivery as soon as we can.

**Comment by Noc2** [comment]
Thanks again for the delivery. I started to look into the delivery, [see](
https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/doter_2_Noc2.md). I did run into two issues:
- I’m unable to do transfers on kusama (I used chromium on ubuntu for testing)
- And two of the tests currently fail. 

Could you look into this?

**Comment by ChainBridgeNetworkTeam** [comment]
> Thanks again for the delivery. I started to look into the delivery, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/doter_2_Noc2.md). I did run into two issues:
> 
> * I’m unable to do transfers on kusama (I used chromium on ubuntu for testing)
> * And two of the tests currently fail.
> 
> Could you look into this?



> Thanks again for the delivery. I started to look into the delivery, [see](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/doter_2_Noc2.md). I did run into two issues:
> 
> * I’m unable to do transfers on kusama (I used chromium on ubuntu for testing)
> * And two of the tests currently fail.
> 
> Could you look into this?

Thank you for the reply! I will fix the issue you mentioned.

**Comment by ChainBridgeNetworkTeam** [comment]
helllo! @Noc2 We had fixed the bugs you mentioned in the evaluation:  
1. The UI bug which will block the transaction has been fixed  
2. We had update the unit test in the repository, and now it has passed all the case

The latest version of Doter has been released at the branch v1.0.5 of the repository(at directory "plugin"), and this version has under the review of google extension store and will been launched in the near future.

**Comment by Noc2** [comment]
Thanks for the quick reply. I can confirm that everything works now and I will forward your invoice internally. The milestone is approved. Apart from this I noticed two additional issues: The USD price sometimes shows the wrong amount. For example it seems to take the KSM price for DOTs. Also the UI sometimes doesn’t reload the information when you switch between multiple wallets.

**Comment by Noc2** [comment]
@ChainBridgeNetworkTeam Did you already upload your invoice, here https://docs.google.com/forms/d/e/1FAIpQLSdSqj2vYjvpiIytkjcc40Pwl0Eg76WGUAq5L9e8eFuuOegmLw/viewform? For some reason I can not find it.

**Comment by ChainBridgeNetworkTeam** [comment]
> @ChainBridgeNetworkTeam Did you already upload your invoice, here https://docs.google.com/forms/d/e/1FAIpQLSdSqj2vYjvpiIytkjcc40Pwl0Eg76WGUAq5L9e8eFuuOegmLw/viewform? For some reason I can not find it.

Sorry, I had filled in the form again, could you find it now?

**Comment by ChainBridgeNetworkTeam** [comment]
> Thanks for the quick reply. I can confirm that everything works now and I will forward your invoice internally. The milestone is approved. Apart from this I noticed two additional issues: The USD price sometimes shows the wrong amount. For example it seems to take the KSM price for DOTs. Also the UI sometimes doesn’t reload the information when you switch between multiple wallets.

Thank you for reporting the bugs! I will fix them as soon as possible.

**Comment by Noc2** [comment]
@ChainBridgeNetworkTeam Thanks! We received the invoice, but the payment address is different from the original contract. https://github.com/w3f/Grants-Program/blob/master/applications/Doter.md Could you either update the contract via a PR or send us a new invoice?

**Comment by ChainBridgeNetworkTeam** [comment]
> @ChainBridgeNetworkTeam Thanks! We received the invoice, but the payment address is different from the original contract. https://github.com/w3f/Grants-Program/blob/master/applications/Doter.md Could you either update the contract via a PR or send us a new invoice?

@Noc2 Hello David! I had committed a pull request to update the address. https://github.com/w3f/Grants-Program/pull/530/files

**Comment by Noc2** [comment]
Thanks. I forwarded the invoice internally.

**Comment by ChainBridgeNetworkTeam** [comment]
> Thanks for the quick reply. I can confirm that everything works now and I will forward your invoice internally. The milestone is approved. Apart from this I noticed two additional issues: The USD price sometimes shows the wrong amount. For example it seems to take the KSM price for DOTs. Also the UI sometimes doesn’t reload the information when you switch between multiple wallets.

@Noc2 Hello! I had fixed the bugs and the new version is under the review of chrome, you can get the new version with the tag v1.0.6

**Pull request merged**
