### PR TITLE
Deliver PolkaSign M1

### PR DESCRIPTION
**Pull request by WannaM**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/517 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Noc2** [comment]
Let me know if and when we should take a look at the delivery.

**Comment by WannaM** [comment]
> Let me know if and when we should take a look at the delivery.

Thanks. We are publishing the promised article. When it's ready, the link will be pasted in delivery.

**Comment by WannaM** [comment]
> Let me know if and when we should take a look at the delivery.

Hi David @Noc2, it's ready now. Everything needed is in this PR.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I started to look into your delivery and noticed that the [readme](https://github.com/SubDAO-Network/polkasign-contract/blob/main/README.md) and also the repo is a based on https://github.com/Apron-Network/apron-contracts.git. Could you update the readme? Also what’s your relationship with the apron network? Are they aware that you are using their code? Officially their code is published under the apache license.

**Comment by WannaM** [comment]
> Thanks for the update. I started to look into your delivery and noticed that the [readme](https://github.com/SubDAO-Network/polkasign-contract/blob/main/README.md) and also the repo is a based on https://github.com/Apron-Network/apron-contracts.git. Could you update the readme? Also what’s your relationship with the apron network? Are they aware that you are using their code? Officially their code is published under the apache license.

Hi @Noc2 , we used to cooperate with apron network before that they provided node API service for us. And our techs exchanged technical ink! issues with them too. I have checked with our tech guy, it's a typo. The readme is updated. Thanks for the comments.

**Comment by Noc2** [comment]
Thanks for the quick reply. It seems https://github.com/sharkygg works for both companies, so this isn’t an issue. I’m happy to tell you that the milestone is a pass, you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SubDAO_PolkaSign_1_Noc2.md). However, I just noticed that the payment address of the invoice, is different from the payment address, which you provided as part of the grant application: 0x0c105bA504D1905bb47EeA57FA8694893bDEd27f. Could you either send us a new invoice or update the payment address of the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/SubDAO_PolkaSign.md)? This way we make sure to not pay the wrong person.

**Comment by WannaM** [comment]
> Thanks for the quick reply. It seems https://github.com/sharkygg works for both companies, so this isn’t an issue. I’m happy to tell you that the milestone is a pass, you can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SubDAO_PolkaSign_1_Noc2.md). However, I just noticed that the payment address of the invoice, is different from the payment address, which you provided as part of the grant application: 0x0c105bA504D1905bb47EeA57FA8694893bDEd27f. Could you either send us a new invoice or update the payment address of the [contract](https://github.com/w3f/Grants-Program/blob/master/applications/SubDAO_PolkaSign.md)? This way we make sure to not pay the wrong person.

Hi @Noc2 David, sorry for that, our colleague mistake to use another address. And I have confirmed with him that both of the addresses are good.

**Comment by Noc2** [comment]
@WannaM Thanks. Could you upload an updated invoice here: https://forms.gle/LSRr7PCjBpEbKGh89?

**Pull request merged**
