### PR TITLE
Bit.Country M2

### PR DESCRIPTION
**Pull request by justinphamnz**
Good day,

The team has completed the M2 grant application. Please find the deliverables in the PR. 

Have a good one. 

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone. The accounting department will complete the form in 2 hours.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/696

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by justinphamnz** [comment]
> Thanks for the delivery. We will look into it as soon as possible.

Thanks David.

**Comment by semuelle** [comment]
Hi Justin, the video you linked to is private. Could you make it public or make it otherwise accessible? You can send private info to grants@web3.foundation, if needed.

Also, `make build` is failing on my machine with the following error. Do you know what's the issue here?

```
error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
  --> node/src/command.rs:48:41
   |
48 |         "pioneer-dev" => Box::new(chain_spec::pioneer::development_config(para_id)),
   |                                               ^^^^^^^ could not find `pioneer` in `chain_spec`

error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
  --> node/src/command.rs:49:43
   |
49 |         "pioneer-local" => Box::new(chain_spec::pioneer::local_testnet_config(para_id)),
   |                                                 ^^^^^^^ could not find `pioneer` in `chain_spec`

error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
  --> node/src/command.rs:50:37
   |
50 |         "pioneer" => Box::new(chain_spec::pioneer::pioneer_network_config_json()?),
   |                                           ^^^^^^^ could not find `pioneer` in `chain_spec`
```

**Comment by justinphamnz** [comment]
> Hi Justin, the video you linked to is private. Could you make it public or make it otherwise accessible? You can send private info to [grants@web3.foundation](mailto:grants@web3.foundation), if needed.
> 
> Also, `make build` is failing on my machine with the following error. Do you know what's the issue here?
> 
> ```
> error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
>   --> node/src/command.rs:48:41
>    |
> 48 |         "pioneer-dev" => Box::new(chain_spec::pioneer::development_config(para_id)),
>    |                                               ^^^^^^^ could not find `pioneer` in `chain_spec`
> 
> error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
>   --> node/src/command.rs:49:43
>    |
> 49 |         "pioneer-local" => Box::new(chain_spec::pioneer::local_testnet_config(para_id)),
>    |                                                 ^^^^^^^ could not find `pioneer` in `chain_spec`
> 
> error[E0433]: failed to resolve: could not find `pioneer` in `chain_spec`
>   --> node/src/command.rs:50:37
>    |
> 50 |         "pioneer" => Box::new(chain_spec::pioneer::pioneer_network_config_json()?),
>    |                                           ^^^^^^^ could not find `pioneer` in `chain_spec`
> ```

Hello Sabastian,

Thanks for looking into it. 

Yeah, we upgraded 0.9.12 yesterday for pioneer collator node, attribute filter was removed. I already pushed changes and should be able to compile them now. 

To help save time for the team, I also made the markdown of the detailed testing guide and full official demo link in this [commit](https://github.com/w3f/Grant-Milestone-Delivery/pull/311/commits/07d1e1092110843e5f1edd2e4c30f2ea7df50741)

Have a good day.

**Comment by justinphamnz** [comment]
Thanks Sebastian @semuelle. We stopped the faucet a couple of days ago. 

I just transferred some testnet token to your wallet 5ELdsMwkZ16wETueuwxzBi31yrKULAVGqfti42Dm6LqsrnkB to test on https://dev.bit.country. You can just log in using the given username and password. 

The dev environment is under rapid development for the upcoming launch, just let me know if you have any issues while doing testing. 

I am looking forward to the feedback.

**Comment by semuelle** [comment]
Thanks. Does dev.bit.country not connect to Tewai? I was waiting for my balance to update there.

**Comment by justinphamnz** [comment]
> Thanks. Does dev.bit.country not connect to Tewai? I was waiting for my balance to update there.

No, dev is connected to our development chain which is the latest. We constantly roll out updates to our dev chain which is the faster approach for us.

**Comment by semuelle** [comment]
Hi Justin,
I have now reviewed all your deliverables. I am happy to [report](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/bit.country_2_semuelle.md) that all the tests succeeded and manual testing also didn't bring up any issues. The only thing I couldn't really verify was the `NFT Minting - Extended` functionality. Can you point me to where `co-creator, origin details, NFT-Future-Event (e.g. time capsule), Smart Contract Enabled NFT` functionalities are implemented? I only see `Timecapsule` [referenced in an error that's thrown when the collection type is `Executable`](https://github.com/bit-country/Metaverse-Network/blob/eaa05d83387b233fad86e5ecbad4f496933e442b/pallets/nft/src/lib.rs#L623); and then the same `burn` event happens as with non-executable collections.

**Comment by justinphamnz** [comment]
Good day Sebastian,

Thanks for your feedback. It's great to hear. 

We handle these events through an off-chain indexer, the executables and time capsule NFT will be executed depending on the logic hash format of the game engine. We tend to only use on-chain storage for keeping ownership, verifying the NFT type, retrieving code executable logic.

In terms of co-creator, we support UI for multi-sign wallets when creating new NFT, transferring NFT. 

We're committed and looking forward to bringing the more traditional user to the ecosystem through multi-metaverse. 

Thanks,
Justin

**Comment by semuelle** [comment]
Thanks for the reply, Justin. To be honest, I would have expected this functionality to be included in the pallet, given that the deliverable is titled `Substrate: NFT Minting - Extended`. Is this indexer open source? Otherwise, it would also not be reproducible by anyone, which is what we usually look for in a deliverable.

**Comment by justinphamnz** [comment]
Thanks for the feedback Sebastian. Sure thing, totally makes sense. 

I can move the Time-capsule execution to execute on chain logic. 

Thanks,
Justin.

**Comment by justinphamnz** [comment]
> Thanks for the reply, Justin. To be honest, I would have expected this functionality to be included in the pallet, given that the deliverable is titled `Substrate: NFT Minting - Extended`. Is this indexer open source? Otherwise, it would also not be reproducible by anyone, which is what we usually look for in a deliverable.

Hi Sebastian,

Hope you had a great weekend. 

Based on your feedback, we moved the Time Capsule execution on-chain which will execute as future events. [0998e0a](https://github.com/bit-country/Metaverse-Network/commit/0998e0a40b67ab0de7dc2b9c17755dfb16d92120). 

For your reference, I also updated the Testing Guide which explains the Time capsule logic [Testing Guide](https://hackmd.io/@justinphamnz/S1yuiQVtY).

Have a good day.

**Comment by semuelle** [comment]
Thanks for the quick reply. Your milestone is hereby accepted. Congratulations! 

It seems that your invoice contains fiat payment information, although the contract contains a BTC address. Could you add the BTC address to the invoice and resubmit?

**Comment by justinphamnz** [comment]
Thanks Sebastian for the feedback, happy to hear the milestone is accepted. 
I will forward it to the accounting team to sort out the BTC address.

**Comment by justinphamnz** [comment]
@semuelle 

Hello Sebastian,

We just resubmitted the invoice which contains BTC Address. 

Have a great day.
Justin

**Comment by semuelle** [comment]
Hey Justin, thanks for sending, but the address needs to be the same as the one in the application. You can either change the address in the invoice or submit an amendment to the grant document.

**Comment by semuelle** [comment]
Thanks for the [amendment](https://github.com/w3f/Grants-Program/pull/736). I have forwarded your invoice for processing. Best of luck going forward! And congrats on the parachain slot!

**Comment by justinphamnz** [comment]
Thanks @semuelle. Very happy being a part of the ecosystem with other serious builders. 

We are committed to bringing more users to web3 and the ecosystem through a metaverse.

**Comment by RouvenP** [comment]
hi @justinphamnz, we transferred the payment today. Thanks!

**Comment by justinphamnz** [comment]
Thanks @RouvenP. 

We really appreciate the support from Web 3 Foundation.
 
Have a great weekend.

**Pull request merged**
