### PR TITLE
Add wasm-opt-for-rust-maintenance-4

### PR DESCRIPTION
**Pull request by brson**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1305

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @brson someone will take a look as soon as possible.

**Comment by semuelle** [comment]
Thanks for the delivery, @brson. Happy to report that your milestone is accepted. 

I have forwarded your invoice for processing.

**Comment by RouvenP** [comment]
hi @brson we transferred the payment today.

**Comment by brson** [comment]
> hi @brson we transferred the payment today.

I see it. Thanks!

**Pull request merged**
