### PR TITLE
Melodot milestone 3

### PR DESCRIPTION
**Pull request by DarkingLee**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1804

### CODE REVIEW

**Comment by niklabh** [comment]
Hey team, thanks for the milestone. I have submitted an external evaluation on this milestone: https://github.com/w3f/Grant-Milestone-Delivery/pull/1055

**Comment by DarkingLee** [comment]
Hey @niklabh , thanks for the evaluation.

**Comment by DarkingLee** [comment]
Hi, @keeganquigley, I hope you're doing well. When you have a moment, could you please take a look at this?

**Comment by keeganquigley** [comment]
Thanks for the delivery @DarkingLee and apologies for the delay. We have a bit of a backlog atm but I should be able to look at this in the next couple of days.

**Comment by keeganquigley** [comment]
Thanks @DarkingLee for your patience. Your milestone delivery was checked by an external evaluator and he has [accepted it](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/melodot_3_niklabh.md). Therefore I'm happy to merge it, great work! Looking forward to the completion of the grant.

**Comment by DarkingLee** [comment]
Hello @RouvenP, I just wanted to check in regarding the payment timeline, as it has been about two weeks since the approval.

**Comment by DarkingLee** [comment]
> hi @DarkingLee we just sent the payment. Thanks

hi @RouvenP, thank you very much, we have received it!

**Pull request merged**
