### PR TITLE
Candle Auction Workshop (Milestone-3) delivery

### PR DESCRIPTION
**Pull request by agryaznov**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/739 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by mmagician** [comment]
@agryaznov The tutorial text looks great! I've proposed some minor changes [here](https://github.com/agryaznov/substrate-docs/pull/1), but otherwise it ticks all the points from the deliverables list.

You should also consider keeping up-to-date with paritytech/ink master. Your current version fails on building with an error regarding `overflow-checks`, which has been (at least temporarily) [resolved](https://github.com/paritytech/ink/pull/1034) in upstream master now.

Lastly - the steps outlined don't actually work for me right now. Upon uploading the ERC721 contract, I get a "Contract Trapped" error. My environment:
```
$ rustc 1.60.0-nightly (ee5d8d37b 2022-01-17)
$ cargo-contract 0.16.0-unknown-x86_64-macos
$ Substrate Contracts Node - version 0.3.1-faa5cb4-x86_64-macos
$ polkadot-js/apps: commit e36b38f36bcc3e0829030de35ef3b0886233031f from Wed Jan 19
```

Also I have locally rebased your branch on upstream master to avoid the overflow error as described above.

I'm aware that I'm not using exactly the same steps as outlined in your tutorial, but since your goal is to be included in the official docs, you should make sure that (at least at the time of making a PR to upstream) your dependencies and environment is the newest possible.

Let me know if you manage to reproduce the behaviour. Once you've updated the tutorial and the branches accordingly, let me know and I'll test on my side again. Good luck, I'm looking forward to a complete solution and I'll also happily share it with my colleagues to test it out once it's done.

**Comment by agryaznov** [comment]
@mmagician thanks a lot for the tutorial text improvements! I've accepted them.

Regarding `ContractTrapped` you faced while deploying the contract: I confirm I can reproduce the bug on the latest ink env (rc8), and AFAIK I'm not alone with it. Please see this reported [issue](https://github.com/paritytech/ink/issues/1108) for details. 

That actually was the reason why I proposed specific versions to be installed in the tutorial: to date it is the latest env I know where all parts (*ink*, *cargo-contract*, *contracts-node* and *polkadotjs-apps*) work together.  

I'm looking forward that issue being fixed, and once it is, will test the whole thing again and update the workshop. Until then though I urge you to use just exact steps as mentioned in the tutorial.

**Comment by agryaznov** [comment]
Hey @mmagician it turns out that with storage deposits being introduced in *pallet_contracts* (see [this PR](https://github.com/paritytech/substrate/pull/10082)), **a lot** has been changed in how contracts work. In particular, there is no *endownment* required by contract by default, and hence contract constructor can be non-payable. That's exactly the case with *ERC721* - it constructor does not accept payment now, and that's the reason it fails with error in case you specify a non-zero ~*endownment*~ *value* on deployment.

To moment it's not an Ink! issue though, it's a change in *UI* (see [this issue](https://github.com/polkadot-js/apps/issues/6645)) that should be implemented to avoid user misbehavior leading to an error. 

Regarding updating the tutorial to work on the latest env possible: I'll certainly do this, BUT until another [#6643](https://github.com/polkadot-js/apps/issues/6643) issue is fixed in PolkadotJS apps, it won't work with contracts properly anyway.

**Comment by mmagician** [comment]
@agryaznov I see, that's unfortunate that your tutorial's proper functioning is blocked by upstream issues.
In this case I will accept the milestone with the steps that are outlined so far.
I know it's also in your best interest to get the tutorial merged into substrate docs, so I guess you'll do all you can do make that happen. And if I can help, let me know too :)
I'll complete the official evaluation later this week.

**Comment by mmagician** [comment]
Apologies for the delayed review! The milestone is finally accepted and that brings your grant to a successful close. Congratulations! The full review can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/392).

**Pull request merged**
