### PR TITLE
Delivery: Project Aurras MVP - Phase 2 - Milestone 1

### PR DESCRIPTION
**Pull request by MuhammedIrfan**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/814

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @MuhammedIrfan, thanks a lot for the delivery. Someone of the team will look into it ASAP.

**Comment by MuhammedIrfan** [comment]
> Hi @MuhammedIrfan, thanks a lot for the delivery. Someone of the team will look into it ASAP.

Thank you @0xCaso

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for your milestone delivery. Could you please add links to the License, documentation and tutorial from your milestone? They are mandatory deliverables and without them I cannot evaluate the milestone.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for your milestone delivery. Could you please add links to the License, documentation and tutorial from your milestone? They are mandatory deliverables and without them I cannot evaluate the milestone.

@dsm-w3f I have added the mandatory deliverables

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

Thank you @dsm-w3f for looking into the deliverables. We will fix the requested changes and revert back to you.

**Comment by MuhammedIrfan** [comment]
Hi Team, We have re-submitted the invoice.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan Is this milestone delivery ready for reevaluation? I saw that you submitted M2. Usually, we evaluate the milestones in order since is common that there are dependencies between them. Is that the case? or M2 is independent of M1?

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan Is this milestone delivery ready for reevaluation? I saw that you submitted M2. Usually, we evaluate the milestones in order since is common that there are dependencies between them. Is that the case? or M2 is independent of M1?

@dsm-w3f We are still working on requested changes for M1. M1 and M2 have independent components hence can be evaluated separately but inorder to do system testing we would require both M1 and M2 to be ready, hence we had to deliver M2.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan this PR was marked as stale due lack of interaction for two weeks. Do you still intend to perform the fixes requested during the evaluation?

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan this PR was marked as stale due lack of interaction for two weeks. Do you still intend to perform the fixes requested during the evaluation?

@dsm-w3f We have fixed couple of issues still need to fix couple more issues, I kindly request you to give us 1 more week to revert back with all issues fixed. Thank you.

**Comment by MuhammedIrfan** [comment]
@dsm-w3f We have made the requested changes, Kindly look into it.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the answers and fixes. I reevaluated the project but I'm still having problems with some tests and understanding what exactly the system should be doing. See details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md). Let me know when I can continue this evaluation.

**Comment by MuhammedIrfan** [comment]
@dsm-w3f Thank you for Re-evaluating the delivery, and apologies for slow response. The utility of Generating push notifications from the events from substrate based chain has been covered in https://github.com/w3f/Grants-Program/blob/master/applications/project_aurras_mvp_phase_1.md .

In M1 we targeted the workflow composer. ie Generating the workflow wasm from the given yaml file which will deployed to Aurras System. As part of M3 we have added a utility of Polkadot Payout as a workflow generated using workflow composer which will help in claiming validator rewards which will be listening to events from the chain to automatically claim the rewards and notify using push notification.

openwhisk-client-rust is a sub component of the workflow. The [configuration](https://github.com/HugoByte/openwhisk-client-rust#configuration) used are the variables that are generated upon deploying the openwhisk server. Openwhisk-client-rust library is being developed as an independent component which can use by other rust applications to communicate with openwhisk api. The [default values](https://github.com/HugoByte/aurras/blob/next/docs/configuration.md)  provided are defined in [aurras-deployment-docker-compose](https://github.com/HugoByte/aurras-deployment-docker-compose/tree/master). 

For the issue faced while testing openwhisk-client-rust, can you please try again with cargo clean.

Kindly use https://github.com/HugoByte/aurras/tree/next/workflow/composer#testing-the-hooks-for-provided-yaml-file for testing workflow hooks.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thanks for the explanations and fixes. Some problems were solved and other remains. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thanks for the explanations and fixes. Some problems were solved and other remains. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

Thank you @dsm-w3f, The issue for generating wasm has been fixed and issue with tarpaulin is due to wasi-experimental-http library we are using. Will revert back to you after issues are fixed.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thanks for the explanations and fixes. Some problems were solved and other remains. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md) for details. Let me know when I can continue this evaluation.

@dsm-w3f We have fixed the issues. As for testing composer STRUCTURED_YAML is just an example structure to define a yaml, and it will not be supported. I request you to kindly re-evaluate the delivery. Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan than you for the improvements and fixes. I tried again and some parts is still presenting problems. Please see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md). Let me know when I can continue the evaluation.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan than you for the improvements and fixes. I tried again and some parts is still presenting problems. Please see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md). Let me know when I can continue the evaluation.

@dsm-w3f Thank you for the evaluation, The issue you faced was due to some old packages in substrate front end template. We have update to the available latest version also fixed a bug we identified. As the gateway is served through https on self signed certificate, please whitelist the host in browser level if the api fails. I request you to kindly re-evaluate the delivery. Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the improvements and fixes. I tested again and almost everything worked. I just didn't get the push notification. Please see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md). Maybe I have missed something while testing. Can you assist with that?

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for the improvements and fixes. I tested again and almost everything worked. I just didn't get the push notification. Please see details in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/aurras_phase_2_1_dsm-w3f.md). Maybe I have missed something while testing. Can you assist with that?

Thank you @dsm-w3f for the evaluation, Possible chances are you might have missed the record button in chrome developer tools or further needed to debug. If possible can we connect on meeting.

muhammedirfan@hugobyte.com

**Comment by dsm-w3f** [comment]
@MuhammedIrfan I tried again without success. I already face this kind of situation before, when I cannot reproduce the same behavior of the grantee. Usually, producing a demonstration video showing how to test the software and produce the expected result solves the problem. It is probably some detail that is missing or some step that I'm not performing correctly. Can you produce this demo video? Otherwise, I'm happy to schedule a call to try to perform this. The video usually works better because sometimes timezones and schedules are complicated to match.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan I tried again without success. I already face this kind of situation before, when I cannot reproduce the same behavior of the grantee. Usually, producing a demonstration video showing how to test the software and produce the expected result solves the problem. It is probably some detail that is missing or some step that I'm not performing correctly. Can you produce this demo video? Otherwise, I'm happy to schedule a call to try to perform this. The video usually works better because sometimes timezones and schedules are complicated to match.

Sure @dsm-w3f, We will create a demonstration video and share that with you.

**Comment by MuhammedIrfan** [comment]
> > @MuhammedIrfan I tried again without success. I already face this kind of situation before, when I cannot reproduce the same behavior of the grantee. Usually, producing a demonstration video showing how to test the software and produce the expected result solves the problem. It is probably some detail that is missing or some step that I'm not performing correctly. Can you produce this demo video? Otherwise, I'm happy to schedule a call to try to perform this. The video usually works better because sometimes timezones and schedules are complicated to match.
> 
> Sure @dsm-w3f, We will create a demonstration video and share that with you.

@dsm-w3f We have compiled a video demo, Kindly find it [here](https://youtu.be/Tkk86peAkG8). Thank you.

**Comment by dsm-w3f** [comment]
@MuhammedIrfan thank you for the video tutorial. I was able to follow it and the application worked fine. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Good Job!

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan thank you for the video tutorial. I was able to follow it and the application worked fine. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Good Job!

@dsm-w3f Thank you very much for the support all along.

**Comment by RouvenP** [comment]
hi @MuhammedIrfan we transferred the payment today.

**Comment by MuhammedIrfan** [comment]
> hi @MuhammedIrfan we transferred the payment today.

@RouvenP I confirm the receipt. Thank you.

**Pull request merged**
