### PR TITLE
Added hs-web3 milestone 3

### PR DESCRIPTION
**Pull request by akru**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hey @akru, thanks for the delivery. Looking very good overall. 
One issue: I tried running the example as described on dockerhub. If I'm not mistaken, the correct command should be `stack run example-polkadot` (instead of `polkadot-example`). That runs the example, but fails to connect to `localhost:9933`. I then manually started `polkadot` (the `Dockerfile` looks like it should already be running), which resolved that issue, but then throws an error halfway through:

```sh
# stack run example-polkadot
System name: "Parity Polkadot"
Best hash: Just HexString "0x0f89481e66b3f83451bc3ad0f6e933a4b5f9883b39b54336357d3ee083ebffa8"
example-polkadot: user error (Pattern match failure in do expression at Main.hs:21:9-17)
```

Could you (a) walk me through how to successfully run the tests and (b) add a written manual to the docker image or repository with these same instructions?

**Comment by akru** [comment]
Hello @semuelle, thank you for the feedback!

I've change README instructions in docker and tried it on my host, works well. I've use latest stable polkadot release `0.8.27` for tests.

**Comment by semuelle** [comment]
Thanks for following up on the test instructions. You can now find my [evaluation notes here](https://github.com/w3f/Grant-Milestone-Delivery/blob/01d8fa2a637c0cfe629aab043bc24f115f6826d8/evaluations/hs-web3_3_semuelle.md). With that, your milestone is accepted. :tada: 

I will forward your invoice for processing.

**Comment by akru** [comment]
Hello @semuelle, how can I track invoice processing?

**Comment by semuelle** [comment]
Hi @akru, I sent your invoice to our finances team. They should be in touch with you about the payment soon. If you have any urgent or specific questions, you can email them at invoices at web3.foundation.

**Comment by akru** [comment]
I see, absolutely no problem, thank you so much @semuelle

**Comment by RouvenP** [comment]
@akru we just sent a test transaction. Could you please confirm if received?

**Comment by akru** [comment]
@RouvenP I can confirm that received it.

**Comment by RouvenP** [comment]
@akru thanks for confirming, we sent the transaction

**Comment by akru** [comment]
Thank you so much!

**Pull request merged**
