### PR TITLE
Create Everlasting_Cash-Milestone_1.md

### PR DESCRIPTION
**Pull request by steve1588**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the initial BTC/ETH payment address. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery. We will look into it as soon as possible, though please allow for up to a couple of weeks since we currently have a bit of a backlog. In general we recommend adding a release tag or commit hash to the deliverables so you can keep working on the project without breaking anything.

Besides, could you please update the deliverables to match [those in the application](https://github.com/CycanTech/Open-Grants-Program/blob/00a71dde2f1baa278fd2bd63419077037f85df44/applications/EverlastingCash.md#milestone-1--implement-elc-contracts)?

**Comment by steve1588** [comment]
> Thank you for the delivery. We will look into it as soon as possible, though please allow for up to a couple of weeks since we currently have a bit of a backlog. In general we recommend adding a release tag or commit hash to the links in the deliverables so you can keep working on the project without breaking anything.
> 
> Besides, could you please update the deliverables to match [those in the application](https://github.com/CycanTech/Open-Grants-Program/blob/00a71dde2f1baa278fd2bd63419077037f85df44/applications/EverlastingCash.md#milestone-1--implement-elc-contracts)?

Thank you for noticing.

We have added a Release tag to the version we committed.

The reason that the deliverables are different from the applicaion is we have compile the specs into  "ELC contracts".

We have updated the Everlasting_Cash-Milestone_1.md to match with our application.

For the specs we listed in our application, we have specified the code lines that match the deliverables.

**Comment by bld84** [comment]
Hi @steve1588! I'm reviewing your tests and I haven't seen some tests for the expand_elc and contract_elc functions. Do you have them?

**Comment by bld84** [comment]
Hi @steve1588! I'm trying to run the ELP runtime node and it's not working for me. I'm using the one that it's in master. Are you using any specific version for the node? Thank you very much in advance

**Comment by steve1588** [comment]
> Hi @steve1588! I'm reviewing your tests and I haven't seen some tests for the expand_elc and contract_elc functions. Do you have them?

Sorry for the late reply. We're working on more tests.

**Comment by steve1588** [comment]
> Hi @steve1588! I'm trying to run the ELP runtime node and it's not working for me. I'm using the one that it's in master. Are you using any specific version for the node? Thank you very much in advance

We're using the ELP runtime node main branch, you need run relay chain first, for now using rococo. We call ELP as Phoenix Parachain on rococo. In ELP runtime node, price-fetch pallet feed price to ELC oracle contract.

**Comment by bld84** [comment]
> > Hi @steve1588! I'm reviewing your tests and I haven't seen some tests for the expand_elc and contract_elc functions. Do you have them?
> 
> Sorry for the late reply. We're working on more tests.

No problem! Please try to improve the tests coverage, specially in these 2 functions, they are pretty critical.

**Comment by bld84** [comment]
> > Hi @steve1588! I'm trying to run the ELP runtime node and it's not working for me. I'm using the one that it's in master. Are you using any specific version for the node? Thank you very much in advance
> 
> We're using the ELP runtime node main branch, you need run relay chain first, for now using rococo. We call ELP as Phoenix Parachain on rococo. In ELP runtime node, price-fetch pallet feed price to ELC oracle contract.

Actually, I'm having problems launching the Phoenix Parachain ( as it's explained in this README https://github.com/CycanTech/ELP-runtime-node). I getting the following error:

./target/release/phoenix-collator   --collator   --base-path ../data/phoenix-c1   --parachain-id 6806   --chain phoenix-raw.json   --rpc-methods Unsafe   --ws-external   --rpc-external   --rpc-cors all   --ws-port 9966   --rpc-port 9955   --port 40335   --   --execution wasm   --chain rococo-local-raw.json   --port 30335
Error: Input("Error opening spec file: No such file or directory (os error 2)")

If you follow this error, it looks like there is a missing step generating the phoenix-raw.json. Do you know how to solve it?

BTW I think it would be great if you set a docker machine with all the steps and requirements to run your code then everybody can run your code easily

**Comment by steve1588** [comment]
> > > Hi @steve1588! I'm trying to run the ELP runtime node and it's not working for me. I'm using the one that it's in master. Are you using any specific version for the node? Thank you very much in advance
> > 
> > 
> > We're using the ELP runtime node main branch, you need run relay chain first, for now using rococo. We call ELP as Phoenix Parachain on rococo. In ELP runtime node, price-fetch pallet feed price to ELC oracle contract.
> 
> Actually, I'm having problems launching the Phoenix Parachain ( as it's explained in this README https://github.com/CycanTech/ELP-runtime-node). I getting the following error:
> 
> ./target/release/phoenix-collator --collator --base-path ../data/phoenix-c1 --parachain-id 6806 --chain phoenix-raw.json --rpc-methods Unsafe --ws-external --rpc-external --rpc-cors all --ws-port 9966 --rpc-port 9955 --port 40335 -- --execution wasm --chain rococo-local-raw.json --port 30335
> Error: Input("Error opening spec file: No such file or directory (os error 2)")
> 
> If you follow this error, it looks like there is a missing step generating the phoenix-raw.json. Do you know how to solve it?
> 
> BTW I think it would be great if you set a docker machine with all the steps and requirements to run your code then everybody can run your code easily

# Export spec file
./target/release/phoenix-collator \
  build-spec  \
  --disable-default-bootnode \
  > phoenix-src.json

./target/release/phoenix-collator \
  build-spec \
  --chain phoenix-src.json \
  --disable-default-bootnode \
  --raw \
  > phoenix-raw.json

We updated ELP-runtime-node README, use this two commands can generate phoenix-raw.json

**Comment by bld84** [comment]
Thank you for the update. Now the phoenix-collator is crashing because something else:

2021-05-05 16:51:41 Is collating: yes    
2021-05-05 16:51:41 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2021-05-05 16:51:41 [Relaychain] Cannot create a runtime: Instantiation("Instantiation: Export ext_logging_max_level_version_1 not found")    
Error: Service(Other("Execution failed: RuntimeConstruction(Instantiation(\"Instantiation: Export ext_logging_max_level_version_1 not found\"))"))


Any idea? Thank you very much in advance

**Comment by steve1588** [comment]
> Thank you for the update. Now the phoenix-collator is crashing because something else:
> 
> 2021-05-05 16:51:41 Is collating: yes
> 2021-05-05 16:51:41 [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
> 2021-05-05 16:51:41 [Relaychain] Cannot create a runtime: Instantiation("Instantiation: Export ext_logging_max_level_version_1 not found")
> Error: Service(Other("Execution failed: RuntimeConstruction(Instantiation("Instantiation: Export ext_logging_max_level_version_1 not found"))"))
> 
> Any idea? Thank you very much in advance

Sorry for the late reply.
Please make sure you are using polkadot v0.8.30.

# Compile Polkadot v30 fork
git clone https://github.com/CycanTech/polkadot.git
cargo build --release

Please try and see if it works.

**Comment by bld84** [comment]
Ok @Noc2 !
@szout I just tried the Parachain and it's working for me now :). Thank you very much! I will check the ELC tests later

**Comment by bld84** [comment]
@steve1588  I'm trying to check your tests and I'm having some problems to run them. 
I tried to compile the contracts with the following command:
$ npx redspot compile

And I'm getting the following error:
Error RS608: The cargo contract should be installed correctly and the version should be at least v0.8.0.

Run the following command to install cargo-contract:                                                                                                                                            
`$ cargo install cargo-contract --force --locked`,
or go to [cargo-contract](https://github.com/paritytech/cargo-contract) to learn more. 

I have installed cargo-contract 0.12.0-unknown-x86_64-linux-gnu so the problem should be in another place. Any idea?

In any case I can build the contracts using the next command:
 $ cargo +nightly contract build

**Comment by steve1588** [comment]
> @steve1588 I'm trying to check your tests and I'm having some problems to run them.
> I tried to compile the contracts with the following command:
> $ npx redspot compile
> 
> And I'm getting the following error:
> Error RS608: The cargo contract should be installed correctly and the version should be at least v0.8.0.
> 
> Run the following command to install cargo-contract:
> `$ cargo install cargo-contract --force --locked`,
> or go to [cargo-contract](https://github.com/paritytech/cargo-contract) to learn more.
> 
> I have installed cargo-contract 0.12.0-unknown-x86_64-linux-gnu so the problem should be in another place. Any idea?
> 
> In any case I can build the contracts using the next command:
> $ cargo +nightly contract build

@bld84 
It's redspot upgrade version problem, maybe you should upgrade your redspot or use cargo-contract  version 0.10.0 or 0.8.0

**Comment by bld84** [comment]
> > @steve1588 I'm trying to check your tests and I'm having some problems to run them.
> > I tried to compile the contracts with the following command:
> > $ npx redspot compile
> > And I'm getting the following error:
> > Error RS608: The cargo contract should be installed correctly and the version should be at least v0.8.0.
> > Run the following command to install cargo-contract:
> > `$ cargo install cargo-contract --force --locked`,
> > or go to [cargo-contract](https://github.com/paritytech/cargo-contract) to learn more.
> > I have installed cargo-contract 0.12.0-unknown-x86_64-linux-gnu so the problem should be in another place. Any idea?
> > In any case I can build the contracts using the next command:
> > $ cargo +nightly contract build
> 
> @bld84
> It's redspot upgrade version problem, maybe you should upgrade your redspot or use cargo-contract version 0.10.0 or 0.8.0

@steve1588 which versions of redspot and cargo-contract are you using?(Just to be sure that we have the same environment). Thank you very much in advance

**Comment by steve1588** [comment]
> > > @steve1588 I'm trying to check your tests and I'm having some problems to run them.
> > > I tried to compile the contracts with the following command:
> > > $ npx redspot compile
> > > And I'm getting the following error:
> > > Error RS608: The cargo contract should be installed correctly and the version should be at least v0.8.0.
> > > Run the following command to install cargo-contract:
> > > `$ cargo install cargo-contract --force --locked`,
> > > or go to [cargo-contract](https://github.com/paritytech/cargo-contract) to learn more.
> > > I have installed cargo-contract 0.12.0-unknown-x86_64-linux-gnu so the problem should be in another place. Any idea?
> > > In any case I can build the contracts using the next command:
> > > $ cargo +nightly contract build
> > 
> > 
> > @bld84
> > It's redspot upgrade version problem, maybe you should upgrade your redspot or use cargo-contract version 0.10.0 or 0.8.0
> 
> @steve1588 which versions of redspot and cargo-contract are you using?(Just to be sure that we have the same environment). Thank you very much in advance

@bld84  Sorry to trouble you.
For redspot:  npm i redspot
For cargo-contract: use version 0.8.0

**Comment by steve1588** [comment]
> @steve1588 Thank you! It started to build everything using cargo-contract 0.8.0, but I found a problem. There is a dependency at ELC/contracts/pool/Cargo.toml (https://github.com/ningxin18/store-contracts) that I cannot access. Do you have that repo as private?

@bld84 Sorry, I just found this problem. This dependency has now been updated to "https://github.com/CycanTech/store-contracts" , please try again.

**Comment by bld84** [comment]
Hey! I changed that reference and it compiled! Now I'm having another problem when I try to deploy the smart contract:

→ npx redspot run scripts/elc.deploy.ts --no-compile
2021-05-25 12:12:50        REGISTRY: Unable to resolve type Outcome, it will fail on construction
2021-05-25 12:12:50        REGISTRY: Unable to resolve type PalletId, it will fail on construction
2021-05-25 12:12:50        REGISTRY: Error: Cannot construct unknown type PalletId
    at new DoNotConstruct (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:340:16)
    at initType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:69:12)
    at createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:297:39)
    at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
2021-05-25 12:12:50        API/INIT: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
    at EventEmitter.value (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/api/base/Init.js:91:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
2021-05-25 12:12:50        API/INIT: Error: createType(PalletId):: Cannot construct unknown type PalletId
    at createTypeUnsafe (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:72:11)
    at createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:84:10)
    at TypeRegistry.createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:297:39)
    at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
    at Array.reduce (<anonymous>)
    at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
    at Array.reduce (<anonymous>)
    at decorateConstants (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:17:18)
    at extractProperties (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:120:53)
    at TypeRegistry.setMetadata (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:456:29)
(node:333664) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
    at EventEmitter.value (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/api/base/Init.js:91:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runNextTicks (internal/process/task_queues.js:62:3)
    at processImmediate (internal/timers.js:434:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:333664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:333664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any suggestion? Thank you very much in advance

**Comment by steve1588** [comment]
> Hey! I changed that reference and it compiled! Now I'm having another problem when I try to deploy the smart contract:
> 
> → npx redspot run scripts/elc.deploy.ts --no-compile
> 2021-05-25 12:12:50 REGISTRY: Unable to resolve type Outcome, it will fail on construction
> 2021-05-25 12:12:50 REGISTRY: Unable to resolve type PalletId, it will fail on construction
> 2021-05-25 12:12:50 REGISTRY: Error: Cannot construct unknown type PalletId
> at new DoNotConstruct (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
> at new (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
> at new Type (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:340:16)
> at initType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:49:19)
> at createTypeUnsafe (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:69:12)
> at createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:84:10)
> at TypeRegistry.createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:297:39)
> at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
> at Array.reduce ()
> at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
> 2021-05-25 12:12:50 API/INIT: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
> at EventEmitter.value (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/api/base/Init.js:91:25)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at runNextTicks (internal/process/task_queues.js:62:3)
> at processImmediate (internal/timers.js:434:9)
> 2021-05-25 12:12:50 API/INIT: Error: createType(PalletId):: Cannot construct unknown type PalletId
> at createTypeUnsafe (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:72:11)
> at createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/createType.js:84:10)
> at TypeRegistry.createType (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:297:39)
> at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:29:30
> at Array.reduce ()
> at /home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:26:58
> at Array.reduce ()
> at decorateConstants (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/metadata/decorate/constants/index.js:17:18)
> at extractProperties (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:120:53)
> at TypeRegistry.setMetadata (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/types/create/registry.js:456:29)
> (node:333664) UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(PalletId):: Cannot construct unknown type PalletId
> at EventEmitter.value (/home/dcabrera/devel/polkadot/ELC/node_modules/@polkadot/api/base/Init.js:91:25)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at runNextTicks (internal/process/task_queues.js:62:3)
> at processImmediate (internal/timers.js:434:9)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:333664) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:333664) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> Any suggestion? Thank you very much in advance

answer：
1、please check parachain is working
     $netstat -an | grep 9966
2、modify  redspot.conf.ts
     replace 'ws://127.0.0.1:9944' to 'ws://127.0.0.1:9966'
3、reDeploy ELC contracts
     $npx redspot run scripts/elc.deploy.ts --no-compile

**Comment by steve1588** [comment]
@bld84  Hi, is it going well? What can we do for you?

**Comment by mmagician** [comment]
To run the ELP-runtime-node I see that I need to `git clone https://github.com/CycanTech/polkadot.git`
I've noticed that the above "fork" of polkadot is not actually a fork of the [paritytech polkadot](https://github.com/paritytech/polkadot/) repo and as such, it's much more difficult to see how your version differs from the original, especially that you added all the code in one commit (not the best development practice). Please make sure that you properly fork the repo.

**Comment by steve1588** [comment]
> To run the ELP-runtime-node I see that I need to `git clone https://github.com/CycanTech/polkadot.git`
> I've noticed that the above "fork" of polkadot is not actually a fork of the [paritytech polkadot](https://github.com/paritytech/polkadot/) repo and as such, it's much more difficult to see how your version differs from the original, especially that you added all the code in one commit (not the best development practice). Please make sure that you properly fork the repo.

Answer:

1、https://github.com/CycanTech/polkadot.git
  this repo fork from https://github.com/paritytech/polkadot.git

2、you also can use follow cmd to clone
  $git clone -b rococo-v1 https://github.com/paritytech/polkadot.git

**Comment by mmagician** [comment]
@steve1588 [Your repo](https://github.com/CycanTech/polkadot) is fork of https://github.com/szout/polkadot, but it does not link back to original polkadot repo. You can see it only has 2 commits (if it were a fork, it would have all the original commits from paritytech, and it would be possible to compare the changes)

**Comment by szout** [comment]
this repo https://github.com/szout/polkadot is removed , please use https://github.com/CycanTech/ELP-PARA-CHAIN ,all in one !

**Comment by mmagician** [comment]
1. It's very difficult to tell which part of the codebase is yours and which you cloned from paritytech. I appreciate your effort to place it all in one repo, but this way we lose the entire commit history. An alternative would be using submodules.
2. Why do you need a parachain in the first place? From the [Testing Guide](https://github.com/CycanTech/ELC/blob/main/Testing%20Guide.md) I understood that a simple canvas node (+ price-fetch pallet) would suffice, no?

**Comment by szout** [comment]
1、in the https://github.com/CycanTech/ELP-PARA-CHAIN  , phoenix is our parachain .there our add some code.   polkadot is clone from paritytech  as same as " git clone -b rococo-v1  https://github.com/paritytech/polkadot.git" 
2、our target is building a parachain(Phoenix), so don't use node frame like canvas ,  There's a big difference at parachain & node。I don't want to transplant it again。 thx！

**Comment by mmagician** [comment]
From your tutorial:
> If you use other substrate node such as parity's canvas node, there's no oracle-pallet, you need add your orcale, if not, you still can deploy ELC contracts, but oracle contract will provide zero price.

So my question is: why do you make things more complicated now by requiring parachains for this milestone?

Also, whatever the latest state of your development is, please update those READMEs to reflect that, and if anything else has changed in your delivery, please make sure this PR is kept up-to-date as well.

**Comment by mmagician** [comment]
When I tried registering the parachain from the UI, I ran into the following error. Perhaps `types.json` is missing?
```
2021-06-17 13:00:29  Failed to submit extrinsic: Extrinsic verification error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn't exist" } })
```

**Comment by szout** [comment]
please use follow json in UI Settings->Developer
{
  "AmountOf": "Amount",
  "Address": "MultiAddress",
  "LookupSource": "MultiAddress",
  "AccountInfo": "AccountInfoWithProviders"
}

**Comment by mmagician** [comment]
I'm finding more issues each time:
1. Currently when running `npx redspot test`, I get the following 2 errors (multiple for each):
```
  2) ERC20
       Assigns initial balance:
     Error: the object {
  "error": {
    "message": "1014: Priority is too low: (3107761987428 vs 3107761987428): The transaction has too low priority to replace another transaction already in the pool."
  }
  "from": "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY"
  "txHash": "0x163ea13c8f71633c8acc8e1b7c4010cd84dff35fb0d9ea8f0b03349d6d27c26a"
} was thrown, throw an Error :)
      at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

```
RedspotError: RS700: Artifact for contract "exchange2" not found.
```

2. The parachain doesn't seem to produce any blocks.
3. You still haven't replied to my question [in the previous comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/157#issuecomment-863000672), nor updated this PR with most recent changes, nor updated the links in your Testing Guide.

Two evaluators have already struggled to follow the steps in your delivery, encountering numerous errors along the way. Frankly, the code and instructions are not in a state that is usable by a wider community. Since this has been dragging on for quite long now, I would like to ask you to fix all outstanding issues (including polishing the documentation) by the end of the week, or else the grant will be terminated as per our [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T%26Cs.md)

**Comment by steve1588** [comment]
> From your tutorial:
> 
> > If you use other substrate node such as parity's canvas node, there's no oracle-pallet, you need add your orcale, if not, you still can deploy ELC contracts, but oracle contract will provide zero price.
> 
> So my question is: why do you make things more complicated now by requiring parachains for this milestone?
> 
> Also, whatever the latest state of your development is, please update those READMEs to reflect that, and if anything else has changed in your delivery, please make sure this PR is kept up-to-date as well.

hi, mmagician

You are right! I just noticed your message. Indeed, I also propose not to run the independent parallel chain in milestone 1 for the time being, because it makes the acceptance work more complicated, and the parallel chain itself is not the development and delivery content of the ELC project. Therefore, please allow us to correct as soon as possible, so as to make the acceptance work more smoothly. I'm sorry to trouble you.

**Comment by derrickf87** [comment]
> From your tutorial:
> 
> > If you use other substrate node such as parity's canvas node, there's no oracle-pallet, you need add your orcale, if not, you still can deploy ELC contracts, but oracle contract will provide zero price.
> 
> So my question is: why do you make things more complicated now by requiring parachains for this milestone?
> 
> Also, whatever the latest state of your development is, please update those READMEs to reflect that, and if anything else has changed in your delivery, please make sure this PR is kept up-to-date as well.

Hi, we have updated the release package to V0.1.1, as well as the delivery document. 
After this update, there's no requiring for parachains.
Some of the dependent libraries have been upgraded since we committed the delivery as well.
Here is the detail we have updated:

1. Several new files have been added. 
    1) four files in folder _artifacts_ : swap contract of the patractlabs/store-contracts, use to exchange token.
    2) InkConfiguration.md: substrate and ink! environment configuration.
    3) tests/pub.parameter.ts: Test cases common parameters.

2. Duplicate test cases deleted.

3. Several files have been modified.
    1) script/elc.deploy.ts: optimize for deployment.
    2) other configuration files about the library: Dependency library version updated to ensure the contract is compiled successfully.

Sorry for the inconvenience.
Please leave us comments if there are any problems.

**Comment by mmagician** [comment]
Ok, thanks for the updates. I'll check it at my earliest convenience.

**Comment by mmagician** [comment]
You can find my milestone evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/everlasting-cash_1_mmagician.md).

Since your supply expansion and contraction logic is fairly complex, I tried to understand its nature via the unit tests. Unfortunately, I found that the code that you included in the test directory is limited to console logs and there are no actual tests there. This is unacceptable for our quality standards and fails to meet the following contract requirements:
> The code will have proper unit-test coverage to ensure functionality and robustness

Already last week I mentioned that due to a large number of issues found, we would not continue with this project in case these were not fixed. As you've completely neglected testing, this is for me yet another reason to terminate the grant.

I hope you understand my position and thank you for your interest in the Grants Program.

**Comment by steve1588** [comment]
> You can find my milestone evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/everlasting-cash_1_mmagician.md).
> 
> Since your supply expansion and contraction logic is fairly complex, I tried to understand its nature via the unit tests. Unfortunately, I found that the code that you included in the test directory is limited to console logs and there are no actual tests there. This is unacceptable for our quality standards and fails to meet the following contract requirements:
> 
> > The code will have proper unit-test coverage to ensure functionality and robustness
> 
> Already last week I mentioned that due to a large number of issues found, we would not continue with this project in case these were not fixed. As you've completely neglected testing, this is for me yet another reason to terminate the grant.
> 
> I hope you understand my position and thank you for your interest in the Grants Program.

@mmagician @Noc2 
hi, 
We are very grateful for your comments and the evaluation work.
We can understand your work position.  
We will seriously work on the unit testing and hold it accountable internally. At the same time, we need to inform you of the latest plan. 
As I mentioned before, we have arranged an audit team with several senior engineers to start auditing the code of the ELC contract. In their current audit opinion, we are not satisfied with the current results as well. There is more design optimization that needs to be done. The stablecoin project is considerably complicated, and we cannot allow it to have any flaws. Therefore, we plan to start  refactoring the code of the ELC ink! in late July. 
We hope you could give us more time to work and improve the ELC project. 
Regardless of the result, we will continue to complete the ELC ink! project. At that time, we believe that you will receive a more complete project code that could be widely used by the community. 
Looking forward to your continued attention.

**Pull request closed without merging**
