### PR TITLE
PolkaKey milestone 2 deliverables

### PR DESCRIPTION
**Pull request by HiZhaoYun**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the second milestone delivery. I will look into it as soon as possible.

**Comment by Noc2** [comment]
I’m happy to tell you that your milestone is a pass and I will forward the invoice internally. You can find my evaluation [here](
https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkakey_2_Noc2.md).

**Comment by HiZhaoYun** [comment]
thanks~ @Noc2

**Comment by RouvenP** [comment]
@HiZhaoYun we just sent a test transaction. could you please confirm if received? thanks

**Comment by HiZhaoYun** [comment]
> @HiZhaoYun we just sent a test transaction. could you please confirm if received? thanks

Yes, i received 0.01BTC.

**Comment by RouvenP** [comment]
> > @HiZhaoYun we just sent a test transaction. could you please confirm if received? thanks
> 
> Yes, i received 0.01BTC.

We transferred the remainder.

**Pull request merged**
