### PR TITLE
ink! analyzer (phase 2) - milestone 7

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1904 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @davidsemakula please see my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_7_keeganquigley.md) here. It mostly looks great with a couple minor issues.

**Comment by davidsemakula** [comment]
Hi @keeganquigley 
Thanks for the swift review.

I can see the cause of the issues.  
The necessary changes are gonna be mostly to instructions (for commands) and improving dependency declarations in Cargo.toml files for the test fixtures a bit (I kinda went bare minimum their initially, just enough for rust-analyzer to not scream too much but I can see how the approach can make testing more confusing).

I'm gonna push some changes and ping you in a bit 🙂

**Comment by davidsemakula** [comment]
@keeganquigley I've made the following changes.

For the commands, I've updated [instructions for running commands](https://github.com/ink-analyzer/ink-vscode/blob/master/TESTING.md#1-commands) to be a bit more clear.

For test-fixtures used in integration tests (especially the one for [non-packed-tuple-struct](https://github.com/ink-analyzer/ink-vscode/tree/master/test-fixtures/non-packed-tuple-struct)), I've updated the dependencies a bit to at least remove unresolved dependency errors from rust-analyzer while in the editor (you'll need to pull from the master branch to get the latest changes). 

Finally, in terms, running automated tests, only the `yarn test` ones for the actual VS Code extensions (run from the project root, not the `test-fixtures` folder) are relevant in this case. The ink! contracts in the `test-fixtures` directory are simply copied from https://github.com/paritytech/ink/tree/v4.2.1/integration-tests and are only there to support the integration tests run with `yarn test` (as well as the manual testing through launch configurations). So they're not meant to be tested directly with something like `cargo test ...` because those tests don't really say anything about the functionality of the VS Code extension itself 🙂. You can have a look at the inline comments in one of the VS Code integration tests (e.g. https://github.com/ink-analyzer/ink-vscode/blob/master/src/test/suite/actions.test.ts#L16-L34) for some details about how the test-fixtures are used (especially, the integration tests perform similar actions to the ones described in the manual testing guides to verify that the extension works correctly).

**Comment by keeganquigley** [comment]
Thanks for the changes @davidsemakula and the explanations are greatly appreciated. Everything works great and I appreciate the great documentation. The tool works seamlessly alongside rust-analyzer and I really hope to see devs start utilizing this, thanks for your hard work! Final evaluation is [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_7_keeganquigley.md). Congrats on the completion of the grant!

**Comment by davidsemakula** [comment]
I've also submitted the invoice 🙂

**Comment by davidsemakula** [comment]
Hi @RouvenP 
just checking in since it's about 2 weeks now since the approval 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula we sent it an hour ago :)

**Comment by davidsemakula** [comment]
@RouvenP received, thanks!

**Pull request merged**
