### PR TITLE
Blackprint visual programming for Polkadot.js - M2

### PR DESCRIPTION
**Pull request by StefansArya**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/774

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @StefansArya. We'll look into it as soon as possible.

**Comment by cruikshankss** [comment]
Good day @StefansArya, sorry for the delay on beginning the review of your second milestone. I began work on your evaluation today and since I reviewed your first milestone, I'm anticipating the process will be rather quick for M2! This is just a brief update for you. Hope you have a nice weekend.

**Comment by cruikshankss** [comment]
Hello again @StefansArya,

I made progress today on your evaluation. My apologies that I had other tasks this week as well. 

It's a privilege to work with your codebase as always. I was trying so hard to finish your evaluation today; I am so close but still need some time. Hope you have a nice holiday weekend.

**Comment by StefansArya** [comment]
Hi @cruikshankss ,
Thank you for the update, for me it's okay about the delay, don't worry about it :)

I'm also still working on some stuff and considering some concepts and features for Blackprint.
In the meantime, I'm also working to integrate Blackprint with UE5.
<details>
  <summary>In case if you want to see it</summary>

bxwWTMMf85

Btw sorry about the low quality picture😅 

The screenshot was taken last week when I wasn't commit anything on GitHub. The integration module (Plugin for UE5) itself hasn't been open sourced yet as the final decision with the other game dev team haven't been made. This integration will allow the player to create a custom program inside the game with the available nodes. After everything is ready maybe the plugin will be available on UE marketplace so it can also help for further development.

I planned to develop open source module to integrate Babylon and PlayCanvas too, but I also need some time 🤣 

---

</details>

Anyway.. feel free to take your time and ask something if you find some problem when evaluating.
Have a nice weekend too!

**Comment by cruikshankss** [comment]
Hi @StefansArya, this is incredible work. It's incredible to see the quality of your codebases and that you're working with UE5 to ideally bring more people into the ecosystem. That screenshot is so cool!! It's a privilege to review you project and to see your passion for teaching and thanks so much for contributing to the Polkadot ecosystem.

I did rename `.env.example` to `.env` and ran the tests but unfortunately got some failing:

Screen Shot 2022-04-18 at 6 24 50 PM

Also, on the editor (https://blackprint.github.io/#page/sketch/1) I was able to load the `@blackprint/nodes-polkadot.js` example at first, but then could load some examples and not able to load some others.

When I attempted to load `send balance extension`, I got this:

Screen Shot 2022-04-18 at 6 29 14 PM


And when I attempted to load `send balance mnemonic`, it hung on this:

Screen Shot 2022-04-18 at 6 29 25 PM

Also, in this list of examples, I am not sure how to load this [deliverable 4: payment-info example](https://github.com/Blackprint/nodes-polkadot.js/blob/11a27d89879a4f15e8c745f607ac31fdb9048c49/example/payment-info.json) since I do not see it on this list:

Screen Shot 2022-04-18 at 6 20 10 PM

To give more information, as you can see, today I am still able to load the encrypt/decrypt example properly and it loads!

Screen Shot 2022-04-18 at 6 34 09 PM


If I remember correctly, for milestone 1 your tests worked extremely well, so I'm assuming this is a small mistake on my end or a small bug. Sorry about this! Could you please let me know if/what I'm doing (something) wrong? Thank you!

**Comment by StefansArya** [comment]
Hi @cruikshankss,
Thank you! it's fun to work with you too honestly 😄 

> I did rename .env.example to .env and ran the tests but unfortunately got some failing:

Looking at the counter, I assume that `Load required modules` on the test was failing. Maybe you forgot to compile the module before running the test or something was missing.

By the way, can you run `npm run build-prod` and try the test again?

If it didn't solve the problem and still give the similar error (`35 failed, 2 success, ...`), it would be nice if you can show me some other error message.

---

About the example that you experience, looks like it was the old version, I'm sorry.. it seems it was my mistake because I haven't added a button or mechanism to "refresh the cached example from the browser". I already planned to update the editor, but after I updated the framework, engine-js, and the sketch library. Because I still need some time to finish some feature and make sure something doesn't broken when get deployed 😅 

For now, can you open incognito/private mode on your browser with `CTRL + Shift + N` and load the module for `polkadot.js` again?

You can also directly import the example by opening the main menu, and click `Sketch` then `Open` then `from Clipboard`. By using this method you can skip loading the module manually.
brave_Owyzr0noAY

You will need to copy and paste the JSON from this [example on GitHub](https://github.com/Blackprint/nodes-polkadot.js/tree/main/example).

**Comment by cruikshankss** [comment]
@StefansArya Ah, yes, sorry for the mistake that I didn't run `npm run build-prod`. 

Now I only have 4 failures, each due to insufficient balance:

Screen Shot 2022-04-19 at 1 22 43 PM

Screen Shot 2022-04-19 at 1 23 18 PM

Could you please let me know how I can proceed to test this? I'm willing to use my own addresses, but curious what balance would be needed on which network, and if so, could you provide the step-by-step instructions so I don't get lost?

By the way, I got the `send balance extension` and `send balance mnemonic` working! Excellent job with the detail in these two!! Makes sense there was an issue with the cache. Great job with the project overall so far and I trust your roadmap. 

Just curious again which example on this list below corresponds to [Deliverable 4: payment info](https://github.com/Blackprint/nodes-polkadot.js/blob/11a27d89879a4f15e8c745f607ac31fdb9048c49/example/payment-info.json) on your Milestone 2 Delivery?

Screen Shot 2022-04-18 at 6 20 10 PM

**Comment by StefansArya** [comment]
@cruikshankss That's okay, thanks for screenshooting the unit testing.

> and if so, could you provide the step-by-step instructions so I don't get lost?

Sure! We will use faucet for Westend test network for obtaining WND token.
But instead of giving a direct link to the faucet, we will start from the documentation. Just for letting you know how I get the information and you can easily verify it. You can also just follow this step if you get lost.

By the way sorry about below's formatting, it's looks not tidy 😅

1. Go to the [Polkadot's Wiki](https://wiki.polkadot.network/docs/learn-DOT#getting-westies)
2. On the `Getting Westies` section you can click on [#westend_faucet:matrix.org](https://matrix.to/#/#westend_faucet:matrix.org).
<details><summary>3. Click <code>Continue</code>, and you will see a list of app that you can use</summary>

brave_Ilf6kOAYRd

After that, you will see this page:
explorer_1T6mAoiSna

Personally, I'm using Element.io.
But you can freely choose in case if you have Weechat or something else that available on the list.
</details>
<details>
  <summary>4. After you opened and logged in on one of the app, make sure you have joined the chat room</summary>

brave_yORUJigey2
</details>
<details>
  <summary>5. Copy your wallet address for testing and go to the faucet's chat room</summary>
</br>

Your wallet address should be begin with `5`, if you don't know how to convert it you can go to below link (replace the `ADDRESS` with your wallet address like `1KczAVb5...`) and click `transform to Westend network account` then copy the wallet address.

`https://westend.subscan.io/account/ADDRESS`

Type `!drip YOUR_WALLET_ADDRESS` and wait for some seconds.
brave_Kgk4G9mlFe
</details>

<details>
  <summary>6. After you receive a response from the bot, you can check your address on Subscan</summary>
</br>

`https://westend.subscan.io/account/YOUR_ADDRESS_HERE`
Code_OzJkevASyu
</details>

After you verify that your wallet address received the WND token, you can re-run the test again.

---

By default the unit test is importing the mnemonic using `ed25519` type.
Because `Sign and verify data` is passed from your side, I assume that you already put the correct address on the `.env` file.

Good luck! It should be easy after you get familiar with it 😄 

---

> Great job with the project overall so far and I trust your roadmap.

Thanks! <3

> Just curious again which example on this list below corresponds to Deliverable 4: payment info on your Milestone 2 Delivery?

It seems it's because I added the `payment info`'s example after I have published the v0.3.0 to the NPM, so it went missing from the list. That list is using [this list](https://cdn.jsdelivr.net/npm/@blackprint/nodes-polkadot.js@0.3.0/example/) and may get outdated if the module is not updated. I think I should fetch the latest example from GitHub instead so the module author can easily add example without the need to publish the module. I still have a lot of thing that need to be reconsider anyway.

Well, even it doesn't exist on the list, it can be easily imported by copy and paste from the [example file](https://github.com/Blackprint/nodes-polkadot.js/blob/11a27d89879a4f15e8c745f607ac31fdb9048c49/example/payment-info.json) into the editor.

**Comment by cruikshankss** [comment]
Hi @StefansArya, do I put the same WND address in for both `WALLET_ADDRESS_A=` and `WALLET_ADDRESS_B`? Why is the example a different length than my WND address? Thanks for your help!

**Comment by cruikshankss** [comment]
>imported by copy and paste from the [example file](https://github.com/Blackprint/nodes-polkadot.js/blob/11a27d89879a4f15e8c745f607ac31fdb9048c49/example/payment-info.json) into the editor. 

Also, how do I import by copy and paste into the editor? Thank you!

**Comment by StefansArya** [comment]
Hi @cruikshankss
Btw, I have updated the example for payment info and the `.example.env`.
I added token decimal note about for [Westend](https://support.polkadot.network/support/solutions/articles/65000168663) and [Shibuya](https://docs.astar.network/tutorial/develop-and-deploy-your-first-smart-contract-on-aster-shiden-evm/deploy-contract-on-local-network) in the example.

WND = 12 decimal
SBY = 18 decimal

---

> do I put the same WND address in for both WALLET_ADDRESS_A= and WALLET_ADDRESS_B?

I think it should be okay if you just want to test for sending balance. But one of the sign/verify test may fail because one the address must be different.

---

> Why is the example a different length than my WND address?

Can I know your wallet address? maybe it's just the address's lower/upper case that make it looks different. You can also put address for `5CPKq... (chain id: 42)` in the `.env` directly.

---

> Also, how do I import by copy and paste into the editor? Thank you!

Maybe you missed my [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/405#issuecomment-1102025098) 😅 , if it has a problem on your side feel free to report it.

**Comment by cruikshankss** [comment]
@StefansArya, thank you so much for helping me out when I was confused and missed your responses or when I got confused about my own WND address 😂 sorry!

I've finished writing your evaluation except waiting for one line regarding passing these last tests.

My WND test account address is: 5HTsTr5u26K6QQ8k7UAThQMUyYfrJ3yM8s94VNbro3AJ233R. 

Btw, I have another WND address I want to keep private that I can use for the other address.

Both my accounts have at least 1 WND.

I deleted my repo, recloned, ran these:
```
  npm install
  npm run build-prod
  npm test
```

and this is what my dev env looks like:
Screen Shot 2022-04-28 at 5 31 57 PM

But the tests are hanging here:
Screen Shot 2022-04-28 at 5 11 48 PM

Hoping to get this finished for you ASAP, thanks for your patience!

**Comment by StefansArya** [comment]
@cruikshankss No worries,
I think I also get confused on my first experience with crypto 🤣 

> My WND test account address is: 5HTsTr5u26K6QQ8k7UAThQMUyYfrJ3yM8s94VNbro3AJ233R.

I have checked it and it was a valid address, and it seems you already know how to obtain WND token. That was great, good job!

---

> Btw, I have another WND address I want to keep private that I can use for the other address.

It's okay, we can use the shared mnemonic and address from `.env.example` for testing. But for GitHub Actions I was using different mnemonic, so when someone is emptied the balance of the shared mnemonic the test on GitHub wouldn't get affected.

---

> But the tests are hanging here:

Hmm, it seems pretty difficult to debug.
I already put [default timeout to 40 sec](https://github.com/Blackprint/nodes-polkadot.js/blob/main/tests/prepare-env.js#L16) for Jest, and it should finish [less than 10 minute](https://github.com/Blackprint/nodes-polkadot.js/runs/6187266525?check_suite_focus=true#step:7:47) 🤔. 

It looks to stuck on `Tests: 4 passed, 4 total`, maybe Jest was failed to create a VM for testing for Browser environment, but able to run test for Node.js. Well.. [module support for Jest](https://jestjs.io/docs/ecmascript-modules) is still experimental anyway, maybe it was failed in a rare condition.

But anyway, can you rerun it?
I have tried to do fresh clone on my computer and run the test, but I can't reproduce the hang.
The tests also runs properly on [GitHub Actions](https://github.com/Blackprint/nodes-polkadot.js/runs/6187266525?check_suite_focus=true#step:7:47) 😅

**Comment by StefansArya** [comment]
> and this is what my dev env looks like:

Oh.. by the way, the correct address for format 42 (Substrate) for the shared mnemonic is:

```sh
WALLET_ADDRESS_A=5GqT7pbxcp6FK3EAy9a3nXf9U6YP5ifgCadHhSnqs9vMAWR1
WALLET_ADDRESS_B=5GwdcntcqjFFQCXzVgDxApqc8zAgP1CvD9w5nkKu1VYiyjdn
```

brave_4YA7nzDmat

**Comment by cruikshankss** [comment]
@StefansArya I'll try a fresh clone, thanks!

**Comment by cruikshankss** [comment]
Good day @StefansArya !

Congratulations on your successful milestone delivery! Here is [my M2 evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/blackprint_2_cruikshankss.md).

I learned a lot about the Polkadot runtime from studying/testing the code and editor. Innovative visual programming style!

I plan to forward your invoice on Monday. Good luck with your next milestone! 🍀

Kind regards,
Ashley

**Comment by StefansArya** [comment]
Sure, I'm glad you can learn a lot by using the editor and testing the code.
I think this will be a great way for us to learn from other developers too that will build modules for Blackprint in the future.

Thank you very much for the evaluation @cruikshankss !
Have a great day!

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
