### PR TITLE
XCM SDK M1

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1199

### CODE REVIEW

**Comment by 0xslipk** [comment]
last version [xcm-sdk@0.0.1-rc.2](https://www.npmjs.com/package/xcm-sdk/v/0.0.1-rc.2)

**Comment by dsm-w3f** [comment]
@0xslipk thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by 0xslipk** [comment]
> @0xslipk thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

Thank you for review our delivery. We are gonna take a look and get back to you.

**Comment by 0xslipk** [comment]
> evaluation documents

Hi @dsm-w3f we fixed all the issues reported.

latest version: [0.0.1-rc.4](https://www.npmjs.com/package/xcm-sdk/v/0.0.1-rc.4)

Testing: we didn't mock the WsProvider, this is resolve in the last version.

System tests: The problem here was that in npm the latest version was set to [0.0.1-beta.1](https://www.npmjs.com/package/xcm-sdk/v/0.0.1-beta.1), but that is not the last version. We fixed this and now the last [rc](https://www.npmjs.com/package/xcm-sdk/v/0.0.1-rc.4) is latest version.

Regarding the testing we updated the README with some example on how to do it.

Thank you.

**Comment by dsm-w3f** [comment]
@0xslipk thank you for the improvements and fixes. Some XCM transactions are failing, more specifically the ones that uses  limitedReserveTransferAssets function. Please see the updated [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) for details. Let me know when can I continue the evaluation.

**Comment by 0xslipk** [comment]
> @0xslipk thank you for the improvements and fixes. Some XCM transactions are failing, more specifically the ones that uses limitedReserveTransferAssets function. Please see the updated [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) for details. Let me know when I can continue the evaluation.

Hi @dsm-w3f, we release a new version [0.0.1-rc.6](https://www.npmjs.com/package/xcm-sdk/v/0.0.1-rc.6).

- We added an example for transfer `ROC` from rococo to rockmine with `teleportAssets`
- We added an example for transfer `ROC` from rococo to mangata with `reserveTransferAssets`
- Regarding the transfer from ROC to DALI (rococo to rockmine) when you transfer ROC to DALI it doesn't transform to DALI, because the asset is store on Dali as id 4. You can see this [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.composablefinance.ninja#/chainstate). You can select the token and find the id 4. We added a section in the [documentation](https://github.com/blockcoders/xcm-sdk#send-native-asset-roc-from-rockmine-to-dali) for this.
- Regarding the `FailedToTransactAsset` issue. we had an error when we generate the extrinsic. This was fix in last version.
- Regarding the transfer of ROCKMINE USD (USDR) your address needs to mint the tokens. I don't see that you have the [tokens](https://rockmine.subscan.io/account/DtZ6SAGigs8jhgh461wBnBEvMaPARuGsKQ2Zm8Gbbb2iPJ2). It should be like [this](https://rockmine.subscan.io/account/HBqoSrwx6inU1SjAw4dcNRxQgCXLnJA1Su1F9yQyrBjkpF9?tab=xcm_transfer).

**Comment by dsm-w3f** [comment]
@0xslipk thank you for the explanations and improvements. I still having problems with the asset transfer. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) for details.

**Comment by 0xslipk** [comment]
> @0xslipk thank you for the explanations and improvements. I still having problems with the asset transfer. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) for details.

Hi @dsm-w3f, we added a section for [local-network-config](https://github.com/blockcoders/xcm-sdk/blob/main/src/examples/local-network/readme.md#local-network-config). In order to create and transfer an asset, you have to mark it as sufficient, and map that asset to the destination parachain, but to do that it has to be extrinsic specific, which has to go through a governance system in rococo, which I see it difficult that we can do just for testing issues.

We added a folder [src/examples/local-network](https://github.com/blockcoders/xcm-sdk/tree/main/src/examples/local-network) to set up a local network with zombienet, we left a script that already auto configures an asset in each parachain and all the config so that it can be transfer.

**Comment by dsm-w3f** [comment]
@0xslipk I tried to run the zombienet as described but I'm getting the error of the image below. If there is an error in the file, please fix it. Btw, why do we need a zombienet to run this test? Couldn't we just use Rococo and other parachains as we were doing before? If needed we can schedule a call to do it together and finish this evaluation. 

image

**Comment by 0xslipk** [comment]
> @0xslipk I tried to run the zombienet as described but I'm getting the error of the image below. If there is an error in the file, please fix it. Btw, why do we need a zombienet to run this test? Couldn't we just use Rococo and other parachains as we were doing before? If needed we can schedule a call to do it together and finish this evaluation.
> 
> image

Hi @dsm-w3f,

Regarding the error this can be related to:
- Maybe you copy or modify a character.
- The binaries polkadot-parachain and trappist-collator need to be in bin folder as the config.toml indicates.

We need a Zombienet, because in order to move the assets we need to create a proposal on Rococo for add these assets with sufficient on Rockmine and maybe on Dali too.

Something like this  https://polkadot.polkassembly.io/referendum/80.

All the cases listed work fine, this in particular is an edge case that needs a custom configuration in order to work.

**Comment by 0xslipk** [comment]
@dsm-w3f do you have any news regarding this?

**Comment by dsm-w3f** [comment]
@0xslipk I double check the file and folders and the same problem persists. Which operational system are you using for testing and compiling those executables? I think we should schedule a call to perform these last tests together and finish this evaluation.

**Comment by fersirni** [comment]
Hi @dsm-w3f Can we meet early next week to address this?

**Comment by dsm-w3f** [comment]
@fersirni thanks, scheduled for Monday.

**Comment by RubenGutierrezC** [comment]
HI @dsm-w3f we updated the config.toml, there was an error for the new versions of zombienet. It should be working now

**Comment by dsm-w3f** [comment]
@RubenGutierrezC and @0xslipk now the zombienet worked and also the example of the kind of transaction that was remaining to test. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/xcm-sdk_1_dsm-w3f.md) and this Milestone is approved. I'll forward your invoice internally. The payment should take place withing two weeks. Great work!

**Pull request merged**
