### PR TITLE
ink! analyzer (phase 2) - milestone 3

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1904 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
@davidsemakula thanks for the delivery! Someone will take a look in the next few days.

**Comment by davidsemakula** [comment]
@keeganquigley I updated the recommended tag for testing to a newer release.

**Comment by keeganquigley** [comment]
Thanks again and sorry for the delay @davidsemakula here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-analyzer-phase-2_3_keeganquigley.md). Happy to pass this and congrats on the completion of the grant! This is a great tool!

**Comment by davidsemakula** [comment]
Thanks for the thorough review and positive feedback @keeganquigley 🙂 
I've also sent the invoice via the form.

> Whoops I see there are two more milestones. Looking forward to them!

There's actually 3 more 🙂, but the next one (milestone 4 - the last one for the semantic analyzer) is the big one (it will implement the remaining new low-level features for this phase/grant). The last 2 after that (milestone 6 & 7 - [milestone 5 is already done](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/ink-analyzer-phase-2-milestone-5.md)) simply reuse/consume semantic analyzer features in higher level components (i.e. the language server and VS Code extension) and will be mostly focused on robustness, automated testing and documentation at that point (since a lot of the new semantic analyzer features from milestones 1-3 have already been shipped for the other components at this point). So in reality its indeed very close to completion (at least in terms of features) even if there's technically 3 more milestones to go.

Adoption is also coming along well - at about ~180 unique installs for the VS Code extension 🚀

**Pull request merged**
