### PR TITLE
DAOsign milestone 1

### PR DESCRIPTION
**Pull request by ramilexe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] ~~This pull request is being made by the same account as the accepted application.~~ The accepted application was made from DaoSign manager personal account. This PR is being made from DaoSign github organization
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1770](https://github.com/w3f/Grants-Program/pull/1770)

### CODE REVIEW

**Comment by PieWol** [comment]
Hey @ramilexe thank you for the delivery :)
here you can find my current evaluation. Looking forward to your responses on the issues / questions I raised. 
#1140

**Comment by PieWol** [comment]
Furthermore embedding a struct from one contract into another doesn't create a shared storage instance. Instead, it creates separate instances within each contract's storage. Whats the reason to split the contracts into two?

**Comment by ramilexe** [comment]
Hi @PieWol 
Thank you for your evaluation, we are reviewing it

**Comment by ramilexe** [comment]
Hi @PieWol 
We have updated the source code of smart contract: [PR](https://github.com/DAOsign/polkadot-smart-contracts/pull/7) and also updated the article (link the same)

**Comment by PieWol** [comment]
thanks @ramilexe ,
I appreciate your changes but could you please provide me an answer on things I mentioned but you didn't change? as in why the contract nesting regarding the storage. Thanks

**Comment by Burmenska** [comment]
@PieWol , hello! just wanted to update you that @ramilexe  was away for a few days last week but he is back and will provide you with the updates in the nearest time. thank you for the patience.

**Comment by eugeneBskyy** [comment]
Hey @PieWol!

We've reviewed your comments with our team and we agreed to make some changes with your suggestions. Currently, our team is working on implementing the requested changes and we anticipate completing them by the end of this week. We will provide more details on what the changes are when they will be completed.

Thank you for your valuable feedback and patience.

**Comment by PieWol** [comment]
Hey @eugeneBskyy ,
thank you very much for your update on the timeline. I'm happy to hear that you will implement changes. Looking forward to it. 👍

**Comment by eugeneBskyy** [comment]
Hey @PieWol !

We encountered more challenges than anticipated during the implementation of these changes. 

However, I'm pleased to inform you that we've successfully merged the latest updates into the main branch. The changes are now **ready for your review**. We greatly appreciate your feedback. 

Thank you for your patience and understanding.

**Comment by PieWol** [comment]
Thank you @eugeneBskyy, 
I will have my evaluation updated by early next week. I'll let you know.

**Comment by eugeneBskyy** [comment]
Hey @PieWol !
I just wanted to kindly follow up on the status of the review. Is there anything that is needed from us or do you have any questions that we can help you with?

**Comment by PieWol** [comment]
Btw, there is a small typo in your article. In case you'd like to fix that ;)

> Profe Storage

**Comment by RouvenP** [comment]
hi @ramilexe @eugeneBskyy we sent the payment last Friday

**Pull request merged**
