### PR TITLE
Kylin Network milestone 1

### PR DESCRIPTION
**Pull request by kylin-dev**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
I started to look into your delivery but I get the following error when I try to install the front-end: 
```
kylin-front-end$ sudo yarn install
[sudo] password for david: 
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error https://registry.yarnpkg.com/gauge/-/gauge-3.0.0.tgz: Integrity check failed for "gauge" (computed integrity doesn't match our records, got "sha512-VSxauaaCsLOTerAyzunAYGgK3iaWZvOL1BCvBvf/IhDWrczPAf1tUqn05DOCJOOe4k3vOdX6fHhJIvF2UtCMhw== sha1-IxPVLgZ6eXNWyCFJB4KP8aCXzeQ=")
error https://registry.yarnpkg.com/gensync/-/gensync-1.0.0-beta.2.tgz: Integrity check failed for "gensync" (computed integrity doesn't match our records, got "sha512-3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg== sha1-MqbudsPX9S1GsrGuXZP+qFgKJeA=")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Noc2** [comment]
You can find my current notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kylin_network_1_Noc2.md). We need to amend the [original contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/kylin_network.md) and probably replace Data Analytics Sample Repo with the extra work you did (Kylin Market Frontend, Kylin Contracts). Could you create a PR to amend the original contract?

**Comment by wannam2049** [comment]
> I started to look into your delivery but I get the following error when I try to install the front-end:
> 
> ```
> kylin-front-end$ sudo yarn install
> [sudo] password for david: 
> yarn install v1.22.5
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> error https://registry.yarnpkg.com/gauge/-/gauge-3.0.0.tgz: Integrity check failed for "gauge" (computed integrity doesn't match our records, got "sha512-VSxauaaCsLOTerAyzunAYGgK3iaWZvOL1BCvBvf/IhDWrczPAf1tUqn05DOCJOOe4k3vOdX6fHhJIvF2UtCMhw== sha1-IxPVLgZ6eXNWyCFJB4KP8aCXzeQ=")
> error https://registry.yarnpkg.com/gensync/-/gensync-1.0.0-beta.2.tgz: Integrity check failed for "gensync" (computed integrity doesn't match our records, got "sha512-3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg== sha1-MqbudsPX9S1GsrGuXZP+qFgKJeA=")
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ```

Hi David, sorry for misguiding in README.md of kylin-node. The [kylin-front-end](https://github.com/Kylin-Network/kylin-front-end)  was deprecated, but the link in README.md is not updated. 

Please refer to the [docker tutorial](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md) to simplify the process of setting up the environments.

Also, we have correct the mistake in README.md.

**Comment by Noc2** [comment]
Thanks for the quick response. However, I’m unable to install the new [front-end](https://github.com/Kylin-Network/kylin-market-frontend) as well and it seems to be quite outdated. See: 

```
kylin-market-frontend$ sudo yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @polkadot/app-accounts@workspace:packages/page-accounts doesn't provide react (pfb4ef), requested by @testing-library/react
➤ YN0002: │ @polkadot/app-accounts@workspace:packages/page-accounts doesn't provide react-dom (pd7425), requested by @testing-library/react
➤ YN0002: │ @polkadot/app-addresses@workspace:packages/page-addresses doesn't provide react (p306bc), requested by @testing-library/react
➤ YN0002: │ @polkadot/app-addresses@workspace:packages/page-addresses doesn't provide react-dom (p017ef), requested by @testing-library/react
➤ YN0002: │ @polkadot/app-bounties@workspace:packages/page-bounties doesn't provide react (pe7930), requested by @testing-library/react
➤ YN0002: │ @polkadot/app-bounties@workspace:packages/page-bounties doesn't provide react-dom (p3ca72), requested by @testing-library/react
➤ YN0060: │ @polkadot/apps@workspace:packages/apps provides webpack (p52bd8) with version 5.10.1, which doesn't satisfy what webpack-dev-server and some of its descendants request
➤ YN0060: │ @polkadot/apps@workspace:packages/apps provides webpack (p69323) with version 5.10.1, which doesn't satisfy what webpack-plugin-serve and some of its descendants request
➤ YN0002: │ @polkadot/dev@npm:0.61.12 doesn't provide styled-components (p8e98d), requested by babel-plugin-styled-components
➤ YN0060: │ @polkadot/dev@npm:0.61.12 provides typescript (paf7f8) with version 4.1.2, which doesn't satisfy what typedoc requests
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react (p2a8e2) with version 17.0.1, which doesn't satisfy what react-copy-to-clipboard requests
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react (p70e1e) with version 17.0.1, which doesn't satisfy what @polkadot/react-qr and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react (pa620d) with version 17.0.1, which doesn't satisfy what react-beautiful-dnd and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react (p5a917) with version 17.0.1, which doesn't satisfy what react-markdown and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react (p92bd3) with version 17.0.1, which doesn't satisfy what semantic-ui-react and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react-dom (p48c5a) with version 17.0.1, which doesn't satisfy what @polkadot/react-qr and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react-dom (pb1212) with version 17.0.1, which doesn't satisfy what react-beautiful-dnd and some of its descendants request
➤ YN0060: │ @polkadot/react-components@workspace:packages/react-components provides react-dom (pb1e7b) with version 17.0.1, which doesn't satisfy what semantic-ui-react and some of its descendants request
➤ YN0002: │ @polkadot/react-qr@npm:0.63.2-3 [336ab] doesn't provide react-is (p6f016), requested by styled-components
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 268ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ gauge@npm:3.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ jest-diff@npm:24.9.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ jest-docblock@npm:25.3.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0018: │ gauge@npm:3.0.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ jest-diff@npm:24.9.0: The remote archive doesn't match the expected checksum
➤ YN0018: │ jest-docblock@npm:25.3.0: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 0s 647ms
➤ YN0000: Failed with errors in 0s 920ms
```

**Comment by Noc2** [comment]
Also when I try to follow your [docker tutorial](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md), I get the following error. Potentially there are some steps missing. 

```
kylin-node/scripts$ docker-compose up -d
ERROR: Couldn't find env file: /home/david/source/web3/evaluation/kylin/kylin-node/scripts/kylin-data-proxy.env
```

Also in case I need specific api keys, could you share them via david@web3.foundation

**Comment by wannam2049** [comment]
> Also when I try to follow your [docker tutorial](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md), I get the following error. Potentially there are some steps missing.
> 
> ```
> kylin-node/scripts$ docker-compose up -d
> ERROR: Couldn't find env file: /home/david/source/web3/evaluation/kylin/kylin-node/scripts/kylin-data-proxy.env
> ```
> 
> Also in case I need specific api keys, could you share them via [david@web3.foundation](mailto:david@web3.foundation)

Hi David,

Thank you for your great efforts!
The keys were sent to your email address.

**Comment by Noc2** [comment]
Thanks for sending the API keys. Let me know if I should take another look at the project, once the front-end and the docker set up works.

**Comment by wannam2049** [comment]
> Thanks for sending the API keys. Let me know if I should take another look at the project, once the front-end and the docker set up works.

When the front-end launched and docker runs well, then just follow the guide to check the Oracle Market which is the demo of this grant application.

**Comment by Noc2** [comment]
> > Thanks for sending the API keys. Let me know if I should take another look at the project, once the front-end and the docker set up works.
> 
> When the front-end is launched and docker runs well, then just follow the guide to check the Oracle Market which is the demo of this grant application.

I still have the above issues with the front-end and docker set up. See the error message, which I shared.

**Comment by wannam2049** [comment]
> > > Thanks for sending the API keys. Let me know if I should take another look at the project, once the front-end and the docker set up works.
> > 
> > 
> > When the front-end is launched and docker runs well, then just follow the guide to check the Oracle Market which is the demo of this grant application.
> 
> I still have the above issues with the front-end and docker set up. See the error message, which I shared.

Okay, let me try with a fresh machine. Are you using an m1 mac or other machines?

**Comment by Noc2** [comment]
I’m using Ubuntu 20.10 at the moment.

**Comment by wannam2049** [comment]
> I’m using Ubuntu 20.10 at the moment.

Okay. I will try it soon.

**Comment by wannam2049** [comment]
@Noc2  Hi David, we re-checked all the documents and tried on an Ubuntu machine, it works now. So please follow the guide [here](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md)

**Comment by wannam2049** [comment]
@Noc2  Hey David, could you help to review this PR?

**Comment by Noc2** [comment]
> @Noc2 Hi David, we have re-checked all the documents and tried on an Ubuntu machine, it works now. So please follow the guide [here](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md)

Sorry for the late reply. The docker setup now works for me. However, I still have issues with the front-end (see above).

**Comment by semuelle** [comment]
@Noc2 I managed to compile and run the frontend running

```{sh}
yarn set version classic
yarn build:www
yarn run start
```

It's still not working, but perhaps just because I am missing the secrets. At least I get a 404.
Yarn 1.x is in maintenance mode since January, I suggest moving to yarn 2.x asap, @wannam2049.

**Comment by wannam2049** [comment]
> @Noc2 I managed to compile and run the frontend running
> 
> ```
> yarn set version classic
> yarn build:www
> yarn run start
> ```
> 
> It's still not working, but perhaps just because I am missing the secrets. At least I get a 404.
> Yarn 1.x is in maintenance mode since January, I suggest moving to yarn 2.x asap, @wannam2049.

Thank you @semuelle !  We will try to move to yarn 2.x asap. 

Could you share some information of which URL is 404?

**Comment by wannam2049** [comment]
> > @Noc2 Hi David, we have re-checked all the documents and tried on an Ubuntu machine, it works now. So please follow the guide [here](https://github.com/Kylin-Network/documents/blob/main/Kylin-Network-Docker-Demo-Tutorial.md)
> 
> Sorry for the late reply. The docker setup now works for me. However, I still have issues with the front-end (see above).

Thank God!! We find the issue. It's package-related and introduced when we submitted this PR. We have updated the source code to catch up with Polkadot JS App and fixed the issue.

Now it's okay to run it. @Noc2 @semuelle   Could you please help to continue the review?

**Comment by Noc2** [comment]
@wannam2049 Thanks for the updated. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/kylin_network_1_Noc2.md) and your milestone is hereby accepted.

I will forward your invoice internally.

**Comment by Noc2** [comment]
@wannam2049 I just noticed that the BTC address on the invoice is not the same as on the original contract, see https://github.com/w3f/Open-Grants-Program/blob/master/applications/kylin_network.md Could you either send us a new invoice to invoices@web3.foundation or amend the original contract via a PR?

**Comment by kylin-dev** [comment]
We will send you a new invoice to invoices@web3.foundation.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Pull request merged**
