### PR TITLE
Coinversation milestone 1

### PR DESCRIPTION
**Pull request by conversationpro**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Open-Grants-Program/pull/105

### CODE REVIEW

**Comment by mmagician** [comment]
@conversationpro I have checked your delivery. Unfortunately, it looks like you have used code from another teams as your own and without any attribution, which leads to grant termination as per our [guidelines](https://github.com/w3f/Grants-Program/blob/master/README.md#guidelines). Specifically, I have found:
- your [`stakepool`](https://github.com/Coinversation/coinpro/blob/main/contracts/stakepool/lib.rs) contract is a copy (with a few variables renamed) of [patramaker](https://github.com/patractlabs/store-contracts/blob/master/contracts/patramaker/lib.rs)
- your [`pat standard`](https://github.com/Coinversation/coinpro/blob/main/contracts/pat_standard/lib.rs) contract is a copy (again with a few variables renamed) of [patract's ERC20](https://github.com/patractlabs/store-contracts/blob/master/contracts/erc20-issue/lib.rs)

This alone would lead to a grant termination. As I'm only human and might have missed some important details, I would like to give you until the end of the week to provide an explanation for this - otherwise your grant will be terminated.

Aside from the above there are still discrepancies from the contract:
- no trace of the `oracle` (deliverable 1 in your application Milestone 1)
- neither the documentation nor tutorial describes how to actually use the solution
- no meaningful unit tests

**Comment by conversationpro** [comment]
Sorry for the mistake 😖

1. Simply put: This is caused by the major changes in our product design during the project development process, and the lack of communication between the project staffs and the grant applicant

2. Regarding product changes: 

- Our core product has been changed to a liquidity pool and synthetic assets that can customize the curve, and we have completed the liquidity pool’s contracts in which users can freely set the rate and asset ratio of the investment pool And the number of assets, the code is under the same git project: [code](https://github.com/Coinversation/coinpro/tree/main/contracts/liquiditypool)

- So the forging center is no longer our core feature, currently we only need to use it to generate our cusd stablecoin, so we have borrowed from the contract of patramaker, which we have a good cooperative relationship with, to avoid re-creating wheels.
And we contacted Lipeng yue, the founder in charge of the Patractlabs this morning, they agreed us to use this code in our project.

- For the oracle part, we will utilize the chainlink pallet integrated by Shiden Network, instead of making a new oracle by ourselves, but because Shiden has not yet enabled this feature and its test network Dusty haven't give a doc or example on how to use the pallet, so we are currently unable to test and submit the Oracle call function.

3. About communication:
  The grant applicant did not fully grasp the guideline requirements, so he didn't notify you in time that we have changed the design and even not review the source of the submitted code, resulting in the borrowed code being submitted as part of milestone 

4. In view of the above, we are very sorry for this mistake. We have reviewed all the other contracts to guarantee that the same thing won’t happen again.  Moreover, we hope to modify the Open Grant Proposal, especially changing the original milestone part to submit the above-mentioned liquidity pool part first. After all, this is our core code and we have completed.

**Comment by mmagician** [comment]
> they agreed us to use this code in our project

That might be all fine, but you should still include a reference that your codebase is inspired by/copy of/based on patract's smart contracts. I know it's a bit of a grey area right now since their repo [doesn't contain a license](https://github.com/patractlabs/store-contracts/issues/8), but in the view of the Grants Program you have submitted code that is not developed by you.

> 1. so we are currently unable to test and submit the Oracle call function
> 2. So the forging center is no longer our core feature

It seems like the scope of milestone 1 has completely changed when compared to the original application. In the current state none of the sub-deliverables meets the requirements. Had it just been *a part* of the project that has changed, making amendments would be more in line with our policies. It seems, however, that your entire M1 is different than what you originally applied for. I would rather be in favour of terminating the current project. If you later want to apply with your revised proposal you are of course welcome to. The miscommunication w.r.t. this grant & delivery, and especially code re-use without attribution, which is a serious offence, are going to be taken into account when assessing any new grants.

**Comment by mmagician** [comment]
The grant has been terminated as per previous comment. Also see: https://github.com/w3f/Grants-Program/pull/552.

**Pull request closed without merging**
