### PR TITLE
RegionX: Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by Szegoo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2080

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @Szegoo I will look into it tomorrow.

**Comment by keeganquigley** [comment]
Hi @Szegoo sorry for the delay:

In `Coretime-Mock`I was able to get to the part where I need to run `npm run zombienet:full` but I get an error:

```
ubuntu@ip-172-31-25-23:~/Coretime-Mock$ npm run zombienet:full

> coretime-mock@1.0.0 zombienet:full
> ./scripts/run_zombienet.sh full

Zombienet couldn't be located
```
I'm assuming this is probably an issue with the path? Will look into it further tomorrow.

**Comment by Szegoo** [comment]
@keeganquigley Thanks for reporting this. I looked into it and it seems like there was an error with the `zombienet` script. I pushed a fix to the main branch, so it should hopefully work now.

**Comment by keeganquigley** [comment]
Thanks for the fix @Szegoo moving on, running `npm run build` in CoreHub is failing to compile with a lot of warnings, see [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/edit/master/evaluations/RegionX_2_keeganquigley.md). Thanks!

**Comment by keeganquigley** [comment]
Looks like Docker gets the same error:

<details>
<summary>Output</summary>
```js
 > [6/6] RUN npm run build:
0.897 
0.897 > build
0.897 > next build
0.897 
1.899 Attention: Next.js now collects completely anonymous telemetry regarding usage.
1.899 This information is used to shape Next.js' roadmap and prioritize features.
1.899 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
1.899 https://nextjs.org/telemetry
1.899 
2.043    Linting and checking validity of types ...
8.721 
8.721 ./src/components/Modals/Partition/index.tsx
8.721 85:6  Warning: React Hook useEffect has missing dependencies: 'regionMetadata.region' and 'timeslicePeriod'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/components/Modals/TaskAssign/index.tsx
8.721 120:6  Warning: React Hook useEffect has a missing dependency: 'tasks'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/components/elements/ListingCard/index.tsx
8.721 103:6  Warning: React Hook useEffect has missing dependencies: 'api', 'apiState', 'region', and 'timeslicePeriod'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/components/elements/RegionCard/index.tsx
8.721 116:6  Warning: React Hook useEffect has missing dependencies: 'api', 'apiState', 'region', and 'timeslicePeriod'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/components/elements/SaleInfo/index.tsx
8.721 54:6  Warning: React Hook useEffect has a missing dependency: 'saleInfo.saleStart'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/apis/CoretimeApi/index.tsx
8.721 43:6  Warning: React Hook useEffect has a missing dependency: 'toastError'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 48:6  Warning: React Hook useEffect has a missing dependency: 'toastSuccess'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/apis/RelayApi/index.tsx
8.721 32:6  Warning: React Hook useEffect has a missing dependency: 'toastError'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 37:6  Warning: React Hook useEffect has a missing dependency: 'toastSuccess'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 52:6  Warning: React Hook useEffect has a missing dependency: 'state'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/common/index.tsx
8.721 52:6  Warning: React Hook useEffect has a missing dependency: 'collectContextData'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/market/index.tsx
8.721 194:6  Warning: React Hook useEffect has a missing dependency: 'fetchMarket'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/regions/index.tsx
8.721 146:6  Warning: React Hook useEffect has a missing dependency: 'fetchRegions'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 150:6  Warning: React Hook useEffect has a missing dependency: 'fetchRegions'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/contexts/sales/index.tsx
8.721 109:6  Warning: React Hook useEffect has a missing dependency: 'fetchSaleInfo'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/pages/purchase.tsx
8.721 59:6  Warning: React Hook useEffect has missing dependencies: 'fetchBalance', 'fetchCurreentPrice', and 'fetchCurrentPhase'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 ./src/pages/transfer/ChainSelector.tsx
8.721 26:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export
8.721 
8.721 ./src/pages/transfer/RegionSelector.tsx
8.721 36:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export
8.721 
8.721 ./src/pages/transfer/index.tsx
8.721 86:6  Warning: React Hook useEffect has a missing dependency: 'handleNonWrappedRegions'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
8.721 
8.721 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
9.343 Failed to compile.
9.343 
9.345 ./src/components/Modals/TaskAssign/index.tsx:132:15
9.345 Type error: Type 'string | number' is not assignable to type 'string | undefined'.
9.345   Type 'number' is not assignable to type 'string'.
9.345 
9.345   130 |             </Typography>
9.345   131 |             <Select
9.345 > 132 |               value={taskSelected || ''}
9.345       |               ^
9.345   133 |               onChange={(e) => selectTask(Number(e.target.value))}
9.345   134 |             >
9.345   135 |               {tasks.map(({ name, id }, index) => (
9.386 npm notice 
9.386 npm notice New minor version of npm available! 10.2.4 -> 10.5.0
9.387 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.0>
9.387 npm notice Run `npm install -g npm@10.5.0` to update!
9.387 npm notice 
------
Dockerfile:22
--------------------
  20 |     RUN npm i;
  21 |     
  22 | >>> RUN npm run build
  23 |     CMD ["npm", "start"]
  24 |     EXPOSE 3000
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
ubuntu@ip-172-31-25-23:~/CoreHub$ 
```
</details>

**Comment by keeganquigley** [comment]
Hi @Szegoo I was able to get everything to work successfully on my Mac locally so you can disregard the above. However, I am trying to use purachase cores at https://app.regionx.tech/purchase and it says I have a 0 ROC balance on the coretime chain. I have a ROC balance on both the relay chain and contracts chain so how can I transfer some over? Otherwise can you send some to 5H1SgrToMp1RYhbUjzQmVxpRGRvo3s2j4xKUjCWJ9GQAVREM thanks!

**Comment by Szegoo** [comment]
@keeganquigley The linting warnings have now been resolved, so could you please pull the changes from the master branch? However, I was unable to replicate the error. I will test it today on a Linux machine.

> and it says I have a 0 ROC balance on the coretime chain.

The initialization script will set up your account with some initial balance:

```
npm run zombienet-init -- \
--contractsInit \
--coretimeInit \
--relayInit \
--contractsPath ../RegionX/target/ink/ \
--contractsAccount "<ADDRESS PLACEHOLDER>" \
--coretimeAccount "<ADDRESS PLACEHOLDER>"
```

A page for cross-chain transferring ROC from the relay chain will be added once we receive improved designs: https://github.com/RegionX-Labs/CoreHub/issues/53. Until then, ROC can be teleported with PJS. I have also sent some ROC to your account. I also transferred a region from the previous bulk sale.

**Comment by keeganquigley** [comment]
Thanks for your help @Szegoo everything looks great now. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/RegionX_2_keeganquigley.md). It was fun being able to play around with coretime in such an easy and intuitive interface. Thanks for your hard work and congrats on completion of the grant. Hope to see RegionX succeed!

**Comment by keeganquigley** [comment]
Please fill out the [invoice form](https://docs.google.com/forms/d/e/1FAIpQLSfmNYaoCgrxyhzgoKQ0ynQvnNRoTmgApz9NrMp-hd8mhIiO0A/viewform?usp=pp_url&entry.1070766548=https://github.com/w3f/Grant-Milestone-Delivery/pull/1100) in order to initiate the payment process. Thank you!

**Comment by keeganquigley** [comment]
We noticed that this is the last milestone of your project. Congratulations on completing your grant! 🎊

So, where to from here? First of all, you should join our [Grants Community chat](https://matrix.to/#/!XpynPDLusWUWfDpaqr:matrix.org?via=web3.foundation&via=matrix.org), if you haven't already, so we can stay in touch.
If you are looking for continuative support for your project, there are quite a few options. The main goal of the W3F grants program is to support research as well as early-stage technical projects. If your project still falls under one of those categories, you might want to apply for a follow-up grant. However, depending on your goals and project status, there are other support programs in our ecosystem that might be better suited as the next step. For example, projects with a Business Case/Token should look into the [Substrate Builders Program](https://substrate.io/ecosystem/substrate-builders-program/) or [VC Funding](https://parachains.info/investors) and Common Good projects have a good chance of receiving [Treasury Funding](https://github.com/w3f/Grants-Program#treasury). If you are looking for guidance, the team at https://substrate.io/ecosystem/square-one/ has compiled a list of ecosystem support sources and are happy to help you navigate it.

For a more comprehensive list, see our [Alternative Funding page](https://w3f.github.io/Grants-Program/funding). Let us know if you have any questions regarding the above. We are more than happy to point you to additional resources and help you determine the best course of action.
Lastly, we hope your W3F grant was a success and we want to thank you for being part of the journey!

**Comment by RouvenP** [comment]
hi @Szegoo we sent the payment today

**Pull request merged**
