### PR TITLE
Calamar milestone 2 delivery

### PR DESCRIPTION
**Pull request by uiii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1163

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@uiii thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/calamar_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by uiii** [comment]
Hi @dsm-w3f I've fixed the tests, the problem is one request timeouts when run in parallel so I disable parallel test when running locally. 

The lint issues - I fixed the unused variables. What is left are the warnings only about usage of `any` type and array access, where the interpreter cannot determine the value is non-null but it is. I could disable them but I intentionally left them here to highlight the workaround is used there.

Check the updated version: https://github.com/topmonks/calamar/tree/8a490368b7307ce279ef50265f4a10a92d7cbcd2

**Comment by dsm-w3f** [comment]
@uiii thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/calamar_2_dsm-w3f.md). The milestone delivery is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great Job!

**Comment by uiii** [comment]
Great to hear it, thank you @dsm-w3f.

**Comment by RouvenP** [comment]
hi @uiii  we transferred the payment today

**Pull request merged**
