### PR TITLE
decentralized invoice M2

### PR DESCRIPTION
**Pull request by herou**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1276

### CODE REVIEW

**Comment by 0xCaso** [comment]
Thanks a lot for the delivery, I started the evaluation.

By the way, I have one question: is it possible to make the added function `exist_invoice` free, if it isn't yet?

Also, it would be cool if you could add the docs (existing now in the Google Docs sheet) inside the README, as the last time, thanks!

**Review by 0xCaso — CHANGES_REQUESTED** [review]
Thanks a lot for the delivery, I started the evaluation.

By the way, I have one question: is it possible to make the added function `exist_invoice` free, if it isn't yet?

Also, it would be cool if you could add the docs (existing now in the Google Docs sheet) inside the README, as the last time, thanks!

**Comment by herou** [comment]
> Thanks a lot for the delivery, I started the evaluation.
> 
> By the way, I have one question: is it possible to make the added function `exist_invoice` free, if it isn't yet?
> 
> Also, it would be cool if you could add the docs (existing now in the Google Docs sheet) inside the README, as the last time, thanks!

Hi, thanks a lot. What do you mean by free? 

I will add the content of doc file inside README.

**Comment by 0xCaso** [comment]
> Hi, thanks a lot. What do you mean by free?

I mean, do the users have to pay gas fees in order to call it? Because if it doesn't modify the chain state, it can be gasless

**Comment by herou** [comment]
> > Hi, thanks a lot. What do you mean by free?
> 
> I mean, do the users have to pay gas fees in order to call it? Because if it doesn't modify the chain state, it can be gasless I think it depends on this: `#[pallet::weight(T::WeightInfo::exist_invoice())]` ([here](https://github.com/gertt/Invoice/blob/invoice_sytem_milestone_2/pallets/invoice/src/lib.rs#L157)).

Hi, thank you. I set the weight to 0. It should be fine now.

**Comment by herou** [comment]
@0xCaso I created a new final delivery, the number 3. Here it is: https://github.com/w3f/Grant-Milestone-Delivery/pull/704
I hope you can review it. Thanks a lot for your work, I really appreciate it!

**Comment by 0xCaso** [comment]
Ok, thanks for the other submission! But first let's finish this evaluation.

Thanks for the changing. By the way, in the application document ([here](https://github.com/w3f/Grants-Program/blob/master/applications/decentralized_invoice.md#milestone-2--implement-show_all_invoices-functionality)) you wrote that the added function would have shown all the invoices (it's not specified whether of one user or of all), but `exist_invoice` returns `true` if the caller is a sender or receiver of any existing invoice, `false` otherwise. Is there a reason for this changing?

**Review by 0xCaso — COMMENTED** [review]
Ok, thanks for the other submission! But first let's finish this evaluation.

Thanks for the changing. By the way, in the application document ([here](https://github.com/w3f/Grants-Program/blob/master/applications/decentralized_invoice.md#milestone-2--implement-show_all_invoices-functionality)) you wrote that the added function would have shown all the invoices (it's not specified whether of one user or of all), but `exist_invoice` returns `true` if the caller is a sender or receiver of any existing invoice, `false` otherwise. Is there a reason for this changing?

**Comment by herou** [comment]
> Ok, thanks for the other submission! But first let's finish this evaluation.
> 
> Thanks for the changing. By the way, in the application document ([here](https://github.com/w3f/Grants-Program/blob/master/applications/decentralized_invoice.md#milestone-2--implement-show_all_invoices-functionality)) you wrote that the added function would have shown all the invoices (it's not specified whether of one user or of all), but `exist_invoice` returns `true` if the caller is a sender or receiver of any existing invoice, `false` otherwise. Is there a reason for this changing?

Hi, thank you for your update. Yes, there is a specific reason for this. During the developing phase, we figure out that we could not show the whole list of invoices using events. On the front end, we will query directly the storage if any invoice exists.

**Comment by 0xCaso** [comment]
Ok thanks, it's clear! Also, is there a specific use case for this function that says if a user has invoices or not?

**Comment by herou** [comment]
> Ok thanks, it's clear! Also, is there a specific use case for this function that says if a user has invoices or not?

Yes, it is. On the front end, we can use this method to understand if a user has an invoice, if yes we will query directly the storage. If not, we will show "No invoice for this user."

**Comment by 0xCaso** [comment]
Screenshot 2023-01-23 at 11 06 39

If you mean to query using one of the above methods, how do you know which one (`InvoiceReceiver` or `InvoiceSender`) you should call if the function returns just true or false? You should call both I guess, and so why using `exist_invoice` at all?

**Comment by herou** [comment]
> Screenshot 2023-01-23 at 11 06 39
> 
> If you mean to query using one of the above methods, how do you know which one (`InvoiceReceiver` or `InvoiceSender`) you should call if the function returns just true or false? You should call both I guess, and so why using `exist_invoice` at all?

No, not the above method. We consider developing the front-end (React Js) for this pallet. We need to know if there is any invoice related to the client or not, to show to him on front-end(React Js) the list of the invoices (by querying directly the storage) or showing "No invoice for this user." @elio.prifti:matrix.org contact me here if you still need explanations.

**Comment by 0xCaso** [comment]
Yes, I understood you want to make a frontend; with "methods" I was meaning the two functions to use for the query (`InvoiceReceiver` or `InvoiceSender`). So the main role of the `exist_invoice` function is (basically) for optimization purposes (is it even worth?). By the way thanks again, I'll update the evaluation soon.

**Review by 0xCaso — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by herou** [comment]
> Yes, I understood you want to make a frontend; with "methods" I was meaning the two functions to use for the query (`InvoiceReceiver` or `InvoiceSender`). So the main role of the `exist_invoice` function is (basically) for optimization purposes (is it even worth?). By the way thanks again, I'll update the evaluation soon.

Thank you so much @0xCaso . I really appreciate your professionals and willingness to get my milestones reviewed quickly. Would you be so kind to review the third milestone? I would really appreciate it: https://github.com/w3f/Grant-Milestone-Delivery/pull/704 Thanks you!

**Pull request merged**
