### PR TITLE
Perun Channels: Milestone 1

### PR DESCRIPTION
**Pull request by matthiasgeihs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Grants-Program/pull/437

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
@matthiasgeihs I just started to look into your delivery and so far it looks really good and according to the contract, but I noticed that your Perun Polkadot Node isn’t public: https://github.com/perun-network/perun-polkadot-pallet/blob/6a48aa11090e8b91aeb9a586f86c72ba8ddacef3/src/lib.rs#L17 Would you mind making this public?

**Comment by Noc2** [comment]
Additionally, are you still planning to implement these: https://github.com/perun-network/perun-polkadot-pallet/tree/master#open-issues?  Weights for example would be nice.

**Comment by matthiasgeihs** [comment]
Thank you for your comments. Our team is currently on limited availability due to holiday season. We will be addressing your comments in the week of August 9.

**Comment by Noc2** [comment]
Thanks for the update. No problem.

**Comment by matthiasgeihs** [comment]
> @matthiasgeihs I just started to look into your delivery and so far it looks really good and according to the contract, but I noticed that your Perun Polkadot Node isn’t public: https://github.com/perun-network/perun-polkadot-pallet/blob/6a48aa11090e8b91aeb9a586f86c72ba8ddacef3/src/lib.rs#L17 Would you mind making this public?

We started creating a node based on the frontend template. However, interacting with channels requires creating signatures, which is difficult todo without additional tooling. Hence, the node frontend is not functional as it is, and hence we decided to not complete its development. The rust tests demonstrate how to interact with channels. For an end user application, the go-perun client would be used for interacting with the pallet. The Polkadot integration into the go-perun client is planned for a follow up grant, as discussed during the project proposal.

> Additionally, are you still planning to implement these: https://github.com/perun-network/perun-polkadot-pallet/tree/master#open-issues? Weights for example would be nice.

The list of items consists of a set of topics that we thought is worth taking note of for future work. Some items might actually be obsolete. We will check again. Regarding weights specifically, it was not super clear how to determine these, in particular because we have inputs of variable length. We observed that several other project deliveries are also not including weights, so we left that for future work.

**Comment by Noc2** [comment]
Thanks for the response. As I already mentioned, your delivery is according to the contract and therefore hereby accepted. The things I mentioned would have been just a nice extra;-) Independent of it, I will forward your invoices internally and I just updated the evaluation notes. It would be nice if you could send us the application for a follow-up grant next and feel free to include the points I mentioned above. You should also take a look at our new [level system for grants](https://github.com/w3f/Grants-Program#level_slider-levels).

**Pull request merged**
