### PR TITLE
add YibanChen milestone 1

### PR DESCRIPTION
**Pull request by davidrhodus**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/499

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @davidrhodus, thanks for the delivery. Could you modify the list of deliverables so that it matches the list in the application document, ideally with links to (a) relevant code section(s) for each deliverable?

**Comment by semuelle** [comment]
Hi David,

I have reviewed your milestone. I was happy to see that I was able to create, send and burn notes through polkadot.js/apps, through the (local, still waiting for test tokens) React dapp and with my own pinata keys. What I wasn't able to do was run the Selenium tests (I assume there is some dependency missing) and `npm test` as described in your app repo readme. Is it possible that the readme is outdated?

It would be great if you could fix these issues; everything else ran smoothly. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/c71f357a068385ae46b2ad88dac55f93bb3752ec/evaluations/yibanchen_1_semuelle.md).

**Comment by davidrhodus** [comment]
> Hi David,
> 
> I have reviewed your milestone. I was happy to see that I was able to create, send and burn notes through polkadot.js/apps, through the (local, still waiting for test tokens) React dapp and with my own pinata keys. What I wasn't able to do was run the Selenium tests (I assume there is some dependency missing) and `npm test` as described in your app repo readme. Is it possible that the readme is outdated?
> 
> It would be great if you could fix these issues; everything else ran smoothly. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/c71f357a068385ae46b2ad88dac55f93bb3752ec/evaluations/yibanchen_1_semuelle.md).

Hi @semuelle I have updated the repositories. There was a bug with `npm test` that has been corrected. I also updated the README for the Selenium tests for additional clarification.  Can you please fetch the repo's again and test again. I have also sent over test tokens for your testing. Thanks!

**Comment by semuelle** [comment]
Thanks for the quick reply, @davidrhodus. It seems that the requirements.txt file is missing, though.

**Comment by davidrhodus** [comment]
> Thanks for the quick reply, @davidrhodus. It seems that the requirements.txt file is missing, though.

Apologies, git typo. I have added the requirements.txt file to the repository. Best!

**Comment by semuelle** [comment]
Thanks, David. I am now able to start the tests, but as soon as I select an account and return to the console, I get the following error. This is with Chrome(driver) 93.0.4577.63.

```
❯ PATH=$PATH:. python3 tests.py
Press any key to continue running tests...
E
======================================================================
ERROR: test_a (__main__.YibanChenTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 35, in test_a
    compose_button.click()
  File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=93.0.4577.63)
```

**Comment by davidrhodus** [comment]
> Thanks, David. I am now able to start the tests, but as soon as I select an account and return to the console, I get the following error. This is with Chrome(driver) 93.0.4577.63.
> 
> ```
> ❯ PATH=$PATH:. python3 tests.py
> Press any key to continue running tests...
> E
> ======================================================================
> ERROR: test_a (__main__.YibanChenTestSuite)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "tests.py", line 35, in test_a
>     compose_button.click()
>   File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
>     return self._parent.execute(command, params)
>   File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/me/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
>   (Session info: chrome=93.0.4577.63)
> ```

Hi @semuelle this took some time to reproduce this error on my side, but I was able to trigger it using a Linux machine. This specific error appears to be related to a resolution difference. Please make the Chrome window in fullscreen to avoid this error. I have updated Selenium Tests repo which should fix additional issues running the tests on Linux. Thanks!

**Comment by semuelle** [comment]
> Please make the Chrome window in fullscreen to avoid this error.

wow. That fixed it.

One more question. I'm not very familiar with resting React components, but what do [these](https://github.com/YibanChen/yibanchen-app/blob/b92d9c9e630894dc9e890017adb68f045e2a6cf3/src/test/App.test.js#L101-L127) tests test? Or rather, how?

**Comment by davidrhodus** [comment]
> > Please make the Chrome window in fullscreen to avoid this error.
> 
> wow. That fixed it.
> 
> One more question. I'm not very familiar with resting React components, but what do [these](https://github.com/YibanChen/yibanchen-app/blob/b92d9c9e630894dc9e890017adb68f045e2a6cf3/src/test/App.test.js#L101-L127) tests test? Or rather, how?

@semuelle I have updated the tests a little more today. The functionality of the tests, the first part of the first one make sure the component renders, the second part of the first one makes sure it has the props it is expected to have. The second test will make sure that the settings component renders properly.

The React tests by their nature are a bit less meaningful than traditional unit tests but can still sometimes help you pin point when something has gone wrong.

**Comment by semuelle** [comment]
Thanks for following up on the tests. I updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/d06dd211044de0f66c8aa149fb83c0af5f383993/evaluations/yibanchen_1_semuelle.md) and your milestone is hereby accepted. :tada: 

I will forward your invoice for processing.

**Comment by semuelle** [comment]
@davidrhodus, could you submit an invoice with postal address?

**Comment by davidrhodus** [comment]
> @davidrhodus, could you submit an invoice with postal address?

Yes, I have now resubmitted the invoice to include an address.

**Comment by RouvenP** [comment]
hi @davidrhodus we just transferred the payment.

**Pull request merged**
