### PR TITLE
Dotflow Milestone 1 delivery

### PR DESCRIPTION
**Pull request by Szegoo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1657

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks @Szegoo for your work and for working with the external evaluator. For reference, here is the full [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/888).

Once the evaluation is marked as accepted I will merge the it with the delivery and submit your invoice for payment.

I would only add that I found more clippy warnings about redundant closures if you can look at fixing these for the next milestone. Thanks!
```rust
warning: redundant closure
   --> contracts/identity/lib.rs:257:46
    |
257 |                 .map_or(Err(Error::IdentityDoesntExist), |v| Ok(v))?;
    |                                                          ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
    = note: `#[warn(clippy::redundant_closure)]` on by default

warning: redundant closure
   --> contracts/identity/lib.rs:308:65
    |
308 |                 self.identity_of.get(caller).map_or(Err(Error::NotAllowed), |v| Ok(v))?;
    |                                                                             ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:330:65
    |
330 |                 self.identity_of.get(caller).map_or(Err(Error::NotAllowed), |v| Ok(v))?;
    |                                                                             ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:352:65
    |
352 |                 self.identity_of.get(caller).map_or(Err(Error::NotAllowed), |v| Ok(v))?;
    |                                                                             ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:370:65
    |
370 |                 self.identity_of.get(caller).map_or(Err(Error::NotAllowed), |v| Ok(v))?;
    |                                                                             ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:419:41
    |
419 |                 .map_or(Err(Error::InvalidNetwork), |v| Ok(v))?;
    |                                                     ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:470:65
    |
470 |                 self.identity_of.get(caller).map_or(Err(Error::NotAllowed), |v| Ok(v))?;
    |                                                                             ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: redundant closure
   --> contracts/identity/lib.rs:513:46
    |
513 |                 .map_or(Err(Error::IdentityDoesntExist), |v| Ok(v))?;
    |                                                          ^^^^^^^^^ help: replace the closure with the function itself: `Ok`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure

warning: `identity` (lib) generated 8 warnings (run `cargo clippy --fix --lib -p identity` to apply 8 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 7m 05s
```

**Comment by Szegoo** [comment]
@keeganquigley Sorry for the clippy warnings. Fixed them and added a CI check to ensure we always notice them from now on. https://github.com/TheDotflow/dotflow-ink/pull/46

**Comment by keeganquigley** [comment]
Also @Szegoo, a minor note in the meantime, I'm getting a 404 error on the Docker build for the [contract link](https://github.com/w3f/Grant-Milestone-Delivery/blob/dotflow-m1/deliveries), if you can fix that. Other than that all links work. Thanks!

**Comment by Szegoo** [comment]
> I'm getting a 404 error on the Docker build for the [contract link](https://github.com/w3f/Grant-Milestone-Delivery/blob/dotflow-m1/deliveries), if you can fix that.

Should be good now 👍

**Comment by keeganquigley** [comment]
Thanks @Szegoo congrats on passing the milestone! For full disclosure, I updated the application link so that GH actions can correctly parse it.

**Comment by Szegoo** [comment]
Hello @keeganquigley, hope you are doing well.

It has been two weeks since our Milestone delivery got accepted. In the `README` file, it is mentioned that the payments are usually processed within two weeks so I would just like to ensure that there is no issue with the invoice we submitted.

**Comment by keeganquigley** [comment]
Hi @Szegoo thanks for inquiring. Yes, I can confirm that typically payments are processed within two weeks. I reviewed your invoice again and it looks good. I see that I forwarded your invoice to our operations team 10 days ago, so subtracting the weekend would be 8 business days so far. So hopefully the payment should arrive in the next couple days, and you will be notified here. If you don't receive it by the middle of next week let me know and I will ping the team. Thanks!

**Pull request merged**
