### PR TITLE
Patron M1

### PR DESCRIPTION
**Pull request by IvanLeshchenko727**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form ](https://forms.gle/LSRr7PCjBpEbKGh89) :memo:  has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the DAI payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: w3f/Grants-Program#1617 (accepted)

### CODE REVIEW

**Comment by takahser** [comment]
Hi @IvanLeshchenko727 
Thanks, I'll have a look and provide you with feedback in the coming days

**Comment by o-tsaruk** [comment]
Hi! Any preliminary results on the review? =)

**Review by takahser — CHANGES_REQUESTED** [review]
@o-tsaruk yes, please have a look at [this PR](https://github.com/Brushfam/patron-backend/pull/1).
Also, could you add instructions to your docs that describe how to build and run tests on your code as well provide me with a tutorial that outlines how to test all the deliveries.

**Comment by o-tsaruk** [comment]
@takahser, thank you for the review! We've updated PR according to your requirements.

**Comment by takahser** [comment]
@o-tsaruk thanks, I'll have a look again and give you feedback soon.

**Comment by o-tsaruk** [comment]
Thank you

**Comment by o-tsaruk** [comment]
Hi @takahser ! Have you had a chance to review the update?

**Review by takahser — CHANGES_REQUESTED** [review]
@o-tsaruk I've added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/patron_1_takahser.md). Feel free to have a look and ask questions.

**Comment by o-tsaruk** [comment]
Thank you for the feedback.

**Comment by 0xMarkian** [comment]
Hey dear w3f reviewers, we are very much looking forward to your final reviews. 

Dear @takahser thanks for the call that our team has had with you on previous week! Please let us know if you have any further questions

P.s. all requested changes were addressed 9days ago.

We welcome you to visit Patron app - patron.works and would like to request the earliest possible feedback and reviews as this milestone compensation is important for our company and for Patron further growth.

**Review by takahser — COMMENTED** [review]
@0xMarkian as pointed out in the private chat, there have been problems with the instructions in this delivery, similarly to some of your past deliveries. I greatly appreciate your planned improvements in your processes that hopefully will make situations like this less likely. Regarding the state, as discussed I'm still in the progress of re-evaluating your Patron M1 delivery and will give you feedback as soon as I can.

**Comment by 0xMarkian** [comment]
Thanks @takahser, looking forward!

**Review by takahser — CHANGES_REQUESTED** [review]
@IvanLeshchenko727 and team, thanks for the call today, that was very helpful. Although this is a big step into the right direction, I've found a couple of more issues that I've outlined in my [updated evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/patron_1_takahser.md). Mostly missing files, warnings and vulnerabilities that should be easy to fix. I'm looking forward to your update!

**Comment by o-tsaruk** [comment]
thank you for the feedback, we are working on the update.

**Comment by o-tsaruk** [comment]
@takahser we have just made all the required changes! We are waiting for your following review=)

1c., 2c., 3a. - updated links here https://github.com/w3f/Grant-Milestone-Delivery/pull/871/commits/061fe28dbde5f27d9f14499cfed34a9e3416608e.
2a. - we fixed all UI warnings. Regarding vulnerabilities, there is a well-known issue https://github.com/facebook/create-react-app/issues/11174. And in our production deployment we haven't any vulnerabilities (see the screenshot below).


npm-issue

**Review by takahser — APPROVED** [review]
@IvanLeshchenko727 @o-tsaruk thanks for the update, you can find my final, accepted evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/patron_1_takahser.md).
Looking ahead, I'm excited to see the outcomes of the enhancements being presently integrated into your workflow.

**Pull request merged**
