### PR TITLE
Setheum Milestone 1 - SERP Pallets

### PR DESCRIPTION
**Pull request by JBA-Khalifa**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the milestone delivery, we will check it as soon as possible, but please be patient and give us a couple of days.

**Comment by JBA-Khalifa** [comment]
@mmagician Thanks

**Comment by alxs** [comment]
Hi @JBA-Khalifa and thanks for the delivery.

Could you please update your deliverables to match those in the original [application](https://github.com/w3f/Open-Grants-Program/blob/master/applications/setheum.md)? Feel free to also remove the link to your last delivery as this one supersedes the former.

Besides, we would like to ask you to please create your own README or appropriate documentation and refrain from reusing the one from the Substrate [node template](https://github.com/substrate-developer-hub/substrate-node-template). Ideally, you would create a separate repository for each of your pallets (eventually [publishing](https://doc.rust-lang.org/cargo/reference/publishing.html) them on crates.io) and use those in your deliveries. Please also add a testing guide to your project as specified in deliverable 0b of your application.

In any case, I haven't been able to test your delivery yet as I have trouble compiling the project. Could you verify that the build succeeds for you and share with me which version of rust you're using (ideally update to the latest stable version)? The first issue I'm running into are [improperly formatted](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field) version numbers in a number of your modules.

Lastly, may I kindly ask you to please remove the grant awardee badge from Setheum's landing page? Our [guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md) state that the badge may only be used in project-specific contexts (and only once the first milestone has been accepted) and specifically dictate it may not be displayed on a team’s landing page. On a related note, if you would like to collaborate on a public announcement once the delivery is accepted, feel free to reach out to grantsPR@web3.foundation with an announcement suggestion.

Thanks again for the delivery and for your continued work on the project.

**Comment by JBA-Khalifa** [comment]
Thanks a lot on the review. I'll go through it all, including the grant awardee badge. Thanks again. @alxs

**Comment by alxs** [comment]
Hi @JBA-Khalifa, any updates?

**Comment by JBA-Khalifa** [comment]
Hi @alxs sorry,. am almost done, I hit a pain point, contracting supply was giving me issues

**Comment by JBA-Khalifa** [comment]
@alxs I am done, please take a look. Thank you so much.

**Comment by JBA-Khalifa** [comment]
@alxs I also added the pallets to crates.io

> Hi @JBA-Khalifa and thanks for the delivery.
> 
> Could you please update your deliverables to match those in the original [application](https://github.com/w3f/Open-Grants-Program/blob/master/applications/setheum.md)? Feel free to also remove the link to your last delivery as this one supersedes the former.
> 
> Besides, we would like to ask you to please create your own README or appropriate documentation and refrain from reusing the one from the Substrate [node template](https://github.com/substrate-developer-hub/substrate-node-template). Ideally, you would create a separate repository for each of your pallets (eventually [publishing](https://doc.rust-lang.org/cargo/reference/publishing.html) them on crates.io) and use those in your deliveries. Please also add a testing guide to your project as specified in deliverable 0b of your application.
> 
> In any case, I haven't been able to test your delivery yet as I have trouble compiling the project. Could you verify that the build succeeds for you and share with me which version of rust you're using (ideally update to the latest stable version)? The first issue I'm running into are [improperly formatted](https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field) version numbers in a number of your modules.
> 
> Lastly, may I kindly ask you to please remove the grant awardee badge from Setheum's landing page? Our [guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md) state that the badge may only be used in project-specific contexts (and only once the first milestone has been accepted) and specifically dictate it may not be displayed on a team’s landing page. On a related note, if you would like to collaborate on a public announcement once the delivery is accepted, feel free to reach out to [grantsPR@web3.foundation](mailto:grantsPR@web3.foundation) with an announcement suggestion.
> 
> Thanks again for the delivery and for your continued work on the project.

**Comment by JBA-Khalifa** [comment]
And, oh yes. I added the crates to crates.io

**Comment by JBA-Khalifa** [comment]
@mmagician @alxs Please review the changes. Sorry for the inconvenience.

**Comment by JBA-Khalifa** [comment]
@alxs Sorry for bothering you. How was the delivery evaluation. I am sorry for the constant disturbance

**Comment by alxs** [comment]
@JBA-Khalifa give me a few days. We currently have quite the backlog.

**Comment by JBA-Khalifa** [comment]
> @JBA-Khalifa give me a few days. We currently have quite the backlog.

Alright, thanks for the reply

**Comment by alxs** [comment]
Hey @JBA-Khalifa. As last time, I cannot build your project, in particular the `stp258` pallet.

Could you verify that the build succeeds for you and share with me which version of rust you're using (ideally update to the latest stable version)?

**Comment by JBA-Khalifa** [comment]
Hi @alxs I use cargo 1.52.0-nightly in my PC.
It will work well with that I think, here is my screenshot.
Screenshot from 2021-04-15 00-12-38

**Comment by alxs** [comment]
Could you run `cargo +nightly-2021-03-16 test` in a freshly cloned directory and confirm that it works?

**Comment by JBA-Khalifa** [comment]
> Could you run `cargo +nightly-2021-03-16 test` in a freshly cloned directory and confirm that it works?

@alxs Let me try

**Comment by JBA-Khalifa** [comment]
I didn't have the specified toolchain, so I installed it after freshly cloning.
Screenshot from 2021-04-16 00-28-48

The errors here were as a result of dependency misquotations which I corrected here [#36](https://github.com/Setheum-Labs/stp258/pull/36)
Then I tested again and it works now.
Here are screenshots:: 

Screenshot from 2021-04-16 00-56-54
Screenshot from 2021-04-16 01-10-39
Screenshot from 2021-04-16 01-10-25

**Comment by alxs** [comment]
Could you fix the other pallets as well please?

**Comment by JBA-Khalifa** [comment]
Sure, thanks

**Comment by JBA-Khalifa** [comment]
Yes they all work now with `cargo +nightly-2021-03-16 test`. It was the same dependencies issue

**Comment by JBA-Khalifa** [comment]
@alxs Did the other pallets work with your setup?

**Comment by JBA-Khalifa** [comment]
@alxs Please evaluate

**Comment by alxs** [comment]
Hey @JBA-Khalifa. Sorry for the delay. After some consideration, I regret to inform you that we have decided to reject the current delivery and terminate the original agreement, based on the following reasons:

- The delivery contains little documentation, in particular with regards to integration, no tests and little code comments of your own. We would normally ask you to simply add these items, but it constitutes a significant portion of the work and we prefer not to ask for it at this stage given our remaining concerns:
- The deliverables are not implemented according to specification. In fact, most functionality described in the application seems to be missing. To name a few examples, in the `stp258` pallet `basket_token` is missing, in `serp_tes` there are no `sett_mint` or `dinar_mint` functions, and in `serp_market` neither the `staking_rewards` nor `buying_price` variables exist.
- All delivered modules are nearly identical and basically copies of Acala's [currencies module](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/currencies/src/lib.rs) with renamed variables. In general, this file is replicated numerous times accross Setheum repositories, such as in the [`stp258`](https://github.com/Setheum-Labs/stp258/blob/master/src/lib.rs), [`stp258-standard`](https://github.com/Setheum-Labs/stp258-standard/blob/master/src/lib.rs), [`serp-tes`](https://github.com/Setheum-Labs/serp-tes/blob/master/src/lib.rs) and [`serp-market`](https://github.com/Setheum-Labs/serp-market/blob/master/src/lib.rs) modules. This represents bad coding practices.
- Attribution for the adapted work is mostly missing. The only reference I could find was one to the ORML currencies pallet in the [`stp258` README](https://github.com/Setheum-Labs/stp258#acknowledgement--reference), which however does not comply with the terms of its [Apache 2.0 license](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/LICENSE). Furthermore, the attribution is completely missing in all other pallets and other adapted modules from the ORML library are unattributed altogether, such as [those in `serp-traits`](https://github.com/Setheum-Labs/serp-traits/tree/master/src).

We will take no further measures other than the termination, but we urge you to fix the licensing issues ASAP as a sign of respect for other teams' work and in order to avoid the possibility of a [takedown notice](https://github.com/contact/dmca) being filed against you. Nevertheless, we would like to thank you for your interest in the grants program and wish you best of luck with your project.

**Comment by JBA-Khalifa** [comment]
Alright thanks @alxs I appreciate it. 
I really appreciate it that you extended the time for me this long, I didn't think I'd make it this far this early, because it was too early for the project when I applied for this grant, now many things in the design have evolved and I've been wanting an upportunity to evolve the design beyond the scope of this application agreement. Thanks Web3, maybe next time, and I'll keep working on building better pallets and developing better coding practices. Each iteration teaches me a lot.

But a quick note please, the 'sett-mint' and 'dinar-mint' were renamed to 'expand-supply' and 'contract-supply' and I think it'd be better to merge all three pallets into one 'serp' pallet. The basket-token as I described was supposed to be implemented in a separate 'prices' pallet (my bad for mentioning it the wrong way), the 'buying-price' in serp-market was renamed to 'serp-quoted-price' and the 'staking-rewards' were supposed to be added when serp-staking pallet is done, but I was asked to remove that pallet from the first application and add it to a second milestone application.
If you give me one more opportunity I'll set things right and build a single pallet with all the features, though also dependent on orml-traits and tokens cause it makes a boilerplate for easier build of multicurrency pallets.

**Comment by alxs** [comment]
Thank you for your understanding.

I can confirm that some functionality had been partially implemented under different variable names and I also understand that the originally intended project structure may have turned out to be unpractical. However, note that we ask teams to submit an amendment in case the development significantly deviates from the original specification, as highlighted at the bottom of the [application process](https://github.com/w3f/Open-Grants-Program#pencil-process) and in our [FAQ](https://github.com/w3f/General-Grants-Program/blob/master/grants/faq.md#frequently-asked-questions).

Apart from that, significant functionality is still missing, in addition to the other reasons cited above.

Again, thank you for your interest nonetheless and I'm sorry things didn't work out.

**Comment by JBA-Khalifa** [comment]
Thanks

**Pull request closed without merging**
