### PR TITLE
Centrifuge GSRPC v2 - Milestone 1 

### PR DESCRIPTION
**Pull request by mikiquantum**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1281

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @mikiquantum, thanks for the delivery! Someone will look into it asap. In the meantime, I opened a PR to fix a thing in the application, so the checks will pass.

**Comment by gmajor-encrypt** [comment]
hi, @mikiquantum This is my evaluation report, https://github.com/w3f/Grant-Milestone-Delivery/pull/762, please let me know if there is any problem

**Comment by gmajor-encrypt** [comment]
@randombishop Hey, Why is this pr closed?

**Comment by Noc2** [comment]
I think this was an oversight. Let me reopen it and check with the team internally.

**Comment by semuelle** [comment]
The PR was closed automatically, because @0xCaso used a phrase in [his commit last week](https://github.com/w3f/Grant-Milestone-Delivery/pull/753#event-8559746768) that Github interprets as "close that PR when this one is merged." Because it references this PR by an absolute URL, it was closed again when @randombishop pulled the commit into his personal fork earlier today. It was not intentional.

Sorry about the noise, @mikiquantum & @gmajor-encrypt. I will verify the delivery and evaluation later today.

**Comment by semuelle** [comment]
@mikiquantum, do I understand correctly that you are currently working on some fixes/replies to the evaluation?

**Comment by mikiquantum** [comment]
@semuelle yes, we are adding support for parsing calls in this Milestone and more inline docs.

**Comment by fededubbi** [comment]
Hi @mikiquantum,

I noticed that your invoice reports our address in a wrong way.
The correct one is:

Web 3.0 Technologies Stiftung 
Baarerstrasse 14
6300 Zug

Can you please update it and resend?

Many thanks,
Federica

**Comment by mikiquantum** [comment]
@fededubbi I just resent the invoice using the form. Thank you.

**Comment by fededubbi** [comment]
Hi @mikiquantum,

Since you are VAT registered, we would need you to add the vat percentage on the invoice of 7.7.%.
Could you please update the invoice and resend?

Let me know if you have any questions.

Many thanks,
Regards,

Federica

**Comment by RouvenP** [comment]
hi @mikiquantum we transferred the payment today

**Pull request merged**
