### PR TITLE
Saito - Polkadot Game Bridge - Milestone 2 delivery.

### PR DESCRIPTION
**Pull request by arpee**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

**Grant Application PR** https://github.com/w3f/Open-Grants-Program/pull/73

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @arpee, thanks again for the submission. I am following your test guide, but there seems to be something going wrong on the backend. The arcade page loads, but remains empty, and the console shows the following errors. Any suggestions? 

```
❯ npm start

> saito@0.2.0 start
> NODE_ENV=prod node --max_old_space_size=8144 start.js

non-browser detected: ReferenceError: document is not defined
Creating database for: arcade
Creating database for: arcade
Creating database for: arcade
Creating database for: arcade
Creating database for: arcade
[Error: SQLITE_ERROR: index game_id_idx already exists] {
  errno: 1,
  code: 'SQLITE_ERROR'
}
Creating database for: arcade
[...]
Creating database for: chat
Connect to Rust client!
[...]
[error] connect ECONNREFUSED 127.0.0.1:3000
[close] Connection closed cleanly, code=undefined reason=undefined
Error fetching block: FetchError: request to http://127.0.0.1:3000/block/403fa38a30aa0028f3d7020c4856474eaaf4e6e9b8346142ee83624352ae069d failed, reason: connect ECONNREFUSED 127.0.0.1:3000
Total Work Needed: 0 ---- available ---> 0     (0.0)
```

I'm also getting a lot of vulnerabilities (`npm audit`) and outdated packages (`npm outdated`). I already commented on those in your first delivery. It would be great if you could address those.

**Comment by trevelyan** [comment]
Let me take a look at this. It looks like code to connect to the developing Rust backend is running on launch and it should not be.

**Comment by arpee** [comment]
Hey Guys,

we have removed the code David mentioned above and some older npm packages that were causing the issues in the npm install.

``` npm audit ``` will still report issues, but these are all with webpack and are dependencies of dev dependencies, and are not called by the full node node.js or browser javascript stacks.

We have tested the updated repo installs and runs and fixed a few typos in our install instructions.

**Comment by semuelle** [comment]
Thanks for the updates. 

I was eventually able to run `saito-lite` and the game template and execute the asset-related functions. The test UI is a bit confusing, because I could toggle some UI elements on, but not off, and some of the game-related functions didn't seem to work. Also, I don't understand why the browser console repeatedly complained about "inadequate" funds. Lastly, after every page load the page was frozen for about five seconds. But my main issue is that your [grant proposal](https://github.com/w3f/Grants-Program/blob/master/applications/saito-game-protocol-and-engine.md#milestone-2--asset-transfers-in-gaming-protocol) mentions a _game_. Maybe the `gametestsuite` isn't properly working for me (for example, "Deal Cards to Table" results in a `Uncaught TypeError: t.deal_cards_to_table_test is not a function at HTMLDivElement.document.getElementById.onclick`) or I don't understand the game, but the only buttons that work for me are demo asset transfers, UI-related or are called "Test ...". Can you clarify this?

**Comment by arpee** [comment]
Hi @semuelle  - we have updated the delivery repo and added a game (blackjack). Responses to your points and queries in line:


> I could toggle some UI elements on, but not off.

This is a good suggestion. I've updated the backend UI components to enable this, and updated the GameTestSuite backend and user-visible buttons updated to better indicate functionality.

> some of the game-related functions didn't seem to work...

I could replicate the issue with deal_cards_to_table_test() and fixed that. Added more extensive logging for the other buttons and ensured output is being printed to log. Hope you will find this addresses concerns.

> But my main issue is that your grant proposal mentions a game.

No worries. I've copied Blackjack into the repository. It’s a new game developed since our submission and has the advantage of being more standard in how it interacts with game engine components than some of the earlier games.

All of the games on the Arcade are open source and will be supporting DOT. We have new ones under development as well.


> Also, I don't understand why the browser console repeatedly complained about "inadequate" funds.

Saito is designed to incentivize infrastructure provision. So the software is designed so that user-facing servers hosting DOT ecosystem data can require payment sigs to be sent with data requests. The messages aren’t part of the submitted milestone -- but I've removed them along with other potentially cryptic output.

>  Lastly, after every page load the page was frozen for about five seconds. 

We are aware of this issue and could use assistance with it. Our analysis is that this is caused by the size of the ```isReady``` object returned by polkadot.js. We presume this is not usually noticed at the api ‘client’ is a server machine, rather than a browser. 

This problem is avoided by disabling substrate crypto modules in the Saito codebase, or by commenting out our polkadot api initialization code such that we do not handle the returned ```isReady``` object.

This was not an issue on submission of our Milestone One, leading us to believe that a change has occurred (the payload now seems to be in excess of 3MB per polkadot endpoint) in the intervening time. We could use direction on how to raise this (bug/issue report?).
 
We are hoping the problem will be fixed by the time we have a really workable parachain ready for deployment in-browser.

> Content and Testing/Validating

To test locally, please update the saito-lite repository with a pull, and follow the instructions in the [Saito-Game-Engine/game-test-suite](https://github.com/SaitoTech/Saito-Game-Engine/blob/master/gametestsuite/README.md) folder.

This work is already live on saito.io/arcade for public testing.

The content of the [Delivery Repository](https://github.com/SaitoTech/Saito-Game-Engine) has also been updated.

**Comment by semuelle** [comment]
Thanks for the update, @arpee. Blackjack is working nicely. I have updated my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/saito_2_semuelle.md) and your milestone is hereby accepted. 

Regarding the browser blocking issue, I found [these](https://github.com/polkadot-js/api/issues/4107) [threads](https://github.com/polkadot-js/api/issues/3356) on the `polkadot-js` repo; maybe they answer your question. In any case, the repo is probably the best place to raise issues if they are not answered anywhere.

Did you fill out the [invoice form](https://forms.gle/LSRr7PCjBpEbKGh89)? I can't seem to find an invoice.

**Comment by arpee** [comment]
Thanks @semuelle very glad to hear this. Thanks for your time on this and evaluating.

I did fill in the invoice form - there was some issue with the CI checks when I created this PR - might that be the issue. Either way will resubmit.

**Comment by semuelle** [comment]
The invoice form and delivery PR are unrelated. Anyway, I got your invoice, but it's missing our name and address. Could you resubmit. You can find our address in the invoice form.

**Comment by arpee** [comment]
Updated invoice has been sent.

**Comment by semuelle** [comment]
Thanks. I have forwarded it for processing.

**Comment by RouvenP** [comment]
hi @arpee we transferred the payment.

**Comment by arpee** [comment]
@RouvenP - thank you I can confirm receiept.

**Pull request merged**
