### PR TITLE
Libra milestone 2 delivery

### PR DESCRIPTION
**Pull request by psyduckio**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/776

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @psyduckio. We will look into it as soon as possible.

**Comment by lucasvanmol** [comment]
Hi @psyduckio,

You can find my initial evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/367e2d7aef4d29ff36f4f01c55a59055cc5f7dfc/evaluations/Libra_2_lucasvanmol.md). Could you please address my comments? Thanks!

**Comment by psyduckio** [comment]
Hi @lucasvanmol,
Thank you for your valuable feedback. I am working on it now. I will let you know once it is complete. Thank you.

**Comment by psyduckio** [comment]
Hi @lucasvanmol, I updated the code as the evaluation. Here is a detail of what I have completed:

**Features:**
- [x] Add credibility to the identity
- [x] Combine resolver credibility and identity credibility
- [x] Increase or decrease the credibility of payment parties (payer, payee, and resolver)
- [x] Blacklisted resolver who terminated cause of low credibility

**Tests:**
- [x] Test `update_identity_data`
- [x] Test `increase_credibility` and `reduce_credibility`
- [x] Test chosen the random resolver

**Documentation:**
- [x] Add document for Events and Error enum

**Others: **
- [x] Fix `cargo clippy`

Please spend time re-evaluating and let me know if there are any necessary changes.

**Comment by lucasvanmol** [comment]
Thanks for the update; the additions are looking good. One thing: the application also mentioned that resolvers would be slashed if they made a wrong decision. Is this still being implemented? If not, how are you preventing users from simply using a different address if their credibility score gets too low?

**Comment by psyduckio** [comment]
Hi @lucasvanmol,

Thank you for the re-evaluation.

> the application also mentioned that resolvers would be slashed if they made a wrong decision. Is this still being implemented? If not, how are you preventing users from simply using a different address if their credibility score gets too low?

For your question about the slashing, after carefully considering the slashing if a resolver made a wrong decision, we decided not to implement it at the moment. This is because we think the evidence evaluation is not easy and we should have a tolerance for the wrong decision. The slashing model will make the resolver affair join the network in the initial phase. Rather than using the slashing model, we opted to lock the tokens of low credibility resolver for a longer time (estimated six months or a year) to prevent them use a different address. Please see [pallet config](https://github.com/atscaletech/libra/blob/main/pallets/resolvers/src/lib.rs#L87).

**Comment by lucasvanmol** [comment]
Thank you @psyduckio for clarifying. As a result I've accepted the delivery ([evaluation here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Libra_2_lucasvanmol.md)). 

One thing that I also wanted to mention is that you should make sure your chain is not susceptible to attacks that may influence which resolvers are being chosen. I'm far from an expert, but there are many tradeoffs to the different ways of generating randomness on-chain, and you should be certain that what you're using is safe enough for your application. Maybe you can see how consensus mechanisms like BABE are using randomness, and get inspired by that.

**Comment by lucasvanmol** [comment]
I've also forwarded your invoice internally!

**Comment by psyduckio** [comment]
Hi @lucasvanmol,

Thank you for raising concern about randomness security. We are aware of the risks of the on-chain randomness generation. But we think it should not be in the scope of the pallet. Currently, we are using [Randomness Collective Flip pallet](https://substrate.dev/rustdocs/v2.0.0/pallet_randomness_collective_flip/index.html) for the testing purpose. For the production-ready, we are planning to borrow the mechanisms of BABE and Ouroboros Praos for the randomness generation.

Thank you so much for the evaluation, suggestion, and support 🙏

**Comment by RouvenP** [comment]
hi @psyduckio we transferred the payment today. Thanks!

**Comment by psyduckio** [comment]
Hi @RouvenP, we already received the funds. Thank you 🙏

**Pull request merged**
