### PR TITLE
DaoSign Milestone 3 delivery

### PR DESCRIPTION
**Pull request by ramilexe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1770

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the delivery @ramilexe I started my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DAOsign_m3_keeganquigley.md), please see the document to look at the errors I'm getting, I'm having issues due to the .env file. The .env sample in the readme is different from the actual .env.sample file. Which one should I be copying? Also, what should I be entering for `POLKADOT_CONTRACT_ADDRESS=<Polkadot contract address>` I'm not sure how this would be used since Polkadot relay chain doesn't run smart contracts.

I would think the .env example should provide some RPC nodes to connect to? Should I be running the backend while running the tests?

**Comment by semuelle** [comment]
pinging @ramilexe

**Comment by ramilexe** [comment]
Hi @semuelle @keeganquigley 
We implemented some changes regarding your comments (https://github.com/DAOsign/relayer/pull/39). Added some default values to .env.example and also added docker-compose with local database. It is already merged to `main` branch, could you re-evaluate it please?

**Comment by ramilexe** [comment]
Hi @keeganquigley 
can you try to run using docker-compose? Relayer requires database to run.

Here is command:
```
docker-compose up -d
```
or
```
docker compose up -d
```

**Comment by keeganquigley** [comment]
Thanks @ramilexe still not working for me unfortunately. When I use docker-compose it now gives me this:

```sh
ubuntu@ip-172-31-28-30:~/relayer$ docker-compose up --build
Building relayer
[+] Building 0.5s (14/14) FINISHED                                                                                                             docker:default
 => [internal] load build definition from local.Dockerfile                                                                                               0.0s
 => => transferring dockerfile: 300B                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                               0.4s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [1/9] FROM docker.io/library/node:18@sha256:83eb05700940a88b14f21fb31cc92e9571a34b1db1a5d8781b466fc26cbb1472                                         0.0s
 => [internal] load build context                                                                                                                        0.0s
 => => transferring context: 5.88kB                                                                                                                      0.0s
 => CACHED [2/9] WORKDIR /app                                                                                                                            0.0s
 => CACHED [3/9] RUN npm install -g typescript ts-node ethers@latest                                                                                     0.0s
 => CACHED [4/9] COPY package.json ./                                                                                                                    0.0s
 => CACHED [5/9] COPY yarn.lock ./                                                                                                                       0.0s
 => CACHED [6/9] COPY tsconfig.json ./                                                                                                                   0.0s
 => CACHED [7/9] RUN yarn                                                                                                                                0.0s
 => CACHED [8/9] COPY . .                                                                                                                                0.0s
 => CACHED [9/9] RUN yarn build                                                                                                                          0.0s
 => exporting to image                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                  0.0s
 => => writing image sha256:b83011181cbca12eedc7702c9f6880900ba6950cabc82ceb1c9b20eaba061b84                                                             0.0s
 => => naming to docker.io/library/relayer_relayer                                                                                                       0.0s

 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
postgres is up-to-date
Recreating 3d973dbf7cce_relayer ... 

ERROR: for 3d973dbf7cce_relayer  'ContainerConfig'

ERROR: for relayer  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[16400] Failed to execute script docker-compose
```
I tried with both node `v18.18.0` and `v18.20.5`.

**Comment by keeganquigley** [comment]
I was able to build it successfully with Codespaces but then for some reason it fails in a loop:

```sh
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer exited with code 0
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
relayer   | yarn run v1.22.22
relayer   | $ npm exec node ./dist/index.js
relayer   | /app/node_modules/ethers/lib.commonjs/utils/errors.js:149
relayer   |         throw makeError(message, code, info);
relayer   |         ^
relayer   | 
relayer   | TypeError: invalid BytesLike value (argument="value", value="0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3", code=INVALID_ARGUMENT, version=6.13.4)
relayer   |     at makeError (/app/node_modules/ethers/lib.commonjs/utils/errors.js:122:21)
relayer   |     at assert (/app/node_modules/ethers/lib.commonjs/utils/errors.js:149:15)
relayer   |     at assertArgument (/app/node_modules/ethers/lib.commonjs/utils/errors.js:161:5)
relayer   |     at _getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:27:36)
relayer   |     at getBytes (/app/node_modules/ethers/lib.commonjs/utils/data.js:37:12)
relayer   |     at dataLength (/app/node_modules/ethers/lib.commonjs/utils/data.js:108:12)
relayer   |     at new SigningKey (/app/node_modules/ethers/lib.commonjs/crypto/signing-key.js:22:66)
relayer   |     at new Wallet (/app/node_modules/ethers/lib.commonjs/wallet/wallet.js:33:56)
relayer   |     at new EthereumProofProvider (/app/dist/services/proof_provider/ethereum.js:28:24)
relayer   |     at Object.<anonymous> (/app/dist/controllers/proof.js:24:5) {
relayer   |   code: 'INVALID_ARGUMENT',
relayer   |   argument: 'value',
relayer   |   value: '0x7gd435f1321b8043d984d95776cf53f570f2e296f86a8b0c9ddbd7c537cee7b3',
relayer   |   shortMessage: 'invalid BytesLike value'
relayer   | }
relayer   | 
relayer   | Node.js v18.20.5
relayer   | error Command failed with exit code 1.
relayer   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ramilexe** [comment]
Hi @keeganquigley 
we fixed that error, please pull latest commit from the repo: https://github.com/DAOsign/relayer/commit/9c38a71de603b915071ad15e16657c6e9219a675 and update your `.env` file accordingly

**Comment by keeganquigley** [comment]
Thanks @ramilexe for the fixes, much appreciated. The relayer is now working properly with docker-compose. That almost wraps it up from my side, but the only remaining issue is that the previous instructions still don't work. Can you perhaps remove these from the readme to avoid confusion?

For example, when I use the npm version (instead of Docker) `npm start` still returns:

```ts
ubuntu@ip-172-31-29-57:~/relayer$ npm start

> relayer@1.0.0 start
> npm exec node ./dist/index.js

(node:5339) ExperimentalWarning: CommonJS module /home/ubuntu/.nvm/versions/node/v23.2.0/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /home/ubuntu/.nvm/versions/node/v23.2.0/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/modules/cjs/loader:1246
  throw err;
  ^

Error: Cannot find module '/home/ubuntu/relayer/dist/index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1243:15)
    at Function._load (node:internal/modules/cjs/loader:1068:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:170:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v23.2.0
```
The Docker version without docker-compose also still doesn't run:
```ts
 1 warning found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 15)
ubuntu@ip-172-31-29-57:~/relayer$ docker run --env-file .env daosign-relayer
yarn run v1.22.22
$ npm exec node ./dist/index.js
Server is running at http://localhost:8000
Error during Data Source initialization: Error: getaddrinfo ENOTFOUND postgres
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'postgres'
}
```

The deliverables are technically passed but please remove the first Docker instructions from the readme and consider fixing or removing npm instructions.

**Comment by ramilexe** [comment]
Thank you @keeganquigley we fixed the Readme file: https://github.com/DAOsign/relayer/commit/c9e24ea2b89b68c87c4e2666df477d4e6d6196fd

**Comment by keeganquigley** [comment]
Thanks for the fixes @ramilexe since the deliverable requirements are technically met, I'm willing to pass it, but tbh it seems like bare minimum effort was put in here. Regardless, here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/DAOsign_m3_keeganquigley.md).

**Pull request merged**
