### PR TITLE
Fractapp Milestone 3

### PR DESCRIPTION
**Pull request by CryptoBadBoy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/51

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
@CryptoBadBoy, are you still planning on publishing on F-Droid?

I will provide some more detailed feedback in the next few days.

**Comment by CryptoBadBoy** [comment]
@semuelle 

No. In F-Droid it is forbidden to upload applications using firebase and google api. We decided that we will distribute Fractapp via Google Play and GitHub as an apk file.

For F-Droid, we may release a version in the future where Google services will not be used.

**Comment by semuelle** [comment]
That makes sense. Just wanted to check as it's mentioned in the contract.

**Comment by semuelle** [comment]
Hey @CryptoBadBoy, I am trying to build and run the app with a local server, but the app doesn't go past the splash screen and only shows "Invalid connection", while the console shows

```
 WARN  Possible Unhandled Promise Rejection (id: 1):
TypeError: Network request failed
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:25322:33
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:29610:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:29530:17
callTimers@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:29730:19
__callFunction@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:23104:36
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:22832:31
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:23058:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.fractapp&modulesOnly=false&runModule=true:22831:21
callFunctionReturnFlushedQueue@[native code]
```

Any idea what's missing? I tried different RPC endpoints, that didn't affect it.

**Comment by CryptoBadBoy** [comment]
@semuelle could you show your .env file please?

**Comment by semuelle** [comment]
> @semuelle could you show your .env file please?

```
FRACTAPP_API = 'https://127.0.0.1:9544'
WSFRACTAPP_API = 'ws://127.0.0.1:9944'
MAIN_BOT_ID = ''
```

**Comment by semuelle** [comment]
I also tried using the network IP

**Comment by CryptoBadBoy** [comment]
You need to use the ip of the internal network and http instead of https

**Comment by CryptoBadBoy** [comment]
Are you running the app in an emulator?

**Comment by semuelle** [comment]
I tried emulator and physical device

**Comment by semuelle** [comment]
I tried to identify the issue, but I only got so far that `getSubstrateBase` returns 400. Is the server port correct, 9544? Should `FRACTAPP_API = 'https://api.fractapp.com'` work?

**Comment by CryptoBadBoy** [comment]
https://api.fractapp.com must work. I will check soon.

If you run fractap server then you have to run scanner api (https://github.com/fractapp/scanner - yarn api).

**Comment by semuelle** [comment]
> If you run fractap server then you have to run scanner api (fractapp/scanner - yarn api).

I'm running `docker-compose`, so all the services should be up.

**Comment by CryptoBadBoy** [comment]
fractap-server and scanner have different docker-compose files because these are different logical elements.

I can add a new docker-compose that will run all the infrastructure together.

**Comment by CryptoBadBoy** [comment]
I'll write when it's ready. I think this will simplify the check.

**Comment by semuelle** [comment]
api.fractapp.com does work, the env variables just didn't update between builds.

**Comment by CryptoBadBoy** [comment]
Sorry for delay
To update .env you need to run yarn start --reset-cache. I will add this to the README

**Comment by CryptoBadBoy** [comment]
@semuelle 
Hello, I made docker-compose which runs all infrastructure. 

Link: https://github.com/fractapp/fractapp-infrastructure

**Comment by semuelle** [comment]
Thanks for the quick fix, works like a charm. Your milestone is hereby accepted, see my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fractapp_3_semuelle.md).

Since this was the last milestone, I'd like to wish you good luck going forward. Feel free to apply for a follow-up grant if you plan on implementing any of the Substrate-related items in your `Future Plans` section, like DAO chats and Substrate-based messaging.

**Comment by semuelle** [comment]
@CryptoBadBoy, our address is now Baarerstr. 14, 6300 Zug. Could you update your invoice with this new address?

**Comment by CryptoBadBoy** [comment]
> Thanks for the quick fix, works like a charm. Your milestone is hereby accepted, see my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fractapp_3_semuelle.md).
> 
> Since this was the last milestone, I'd like to wish you good luck going forward. Feel free to apply for a follow-up grant if you plan on implementing any of the Substrate-related items in your `Future Plans` section, like DAO chats and Substrate-based messaging.

Thank you very much!

**Comment by CryptoBadBoy** [comment]
> @CryptoBadBoy, our address is now Baarerstr. 14, 6300 Zug. Could you update your invoice with this new address?

Fixed

**Comment by semuelle** [comment]
Thanks. I have forwarded it for processing. Please let me know if you haven't heard back in 14 days.

**Comment by CryptoBadBoy** [comment]
Hi, @semuelle 

Excuse me, will the translation be on Friday or earlier?

**Comment by RouvenP** [comment]
hi @CryptoBadBoy, the transfer will happen either today or tomorrow. I'll notify you as soon as done.

**Pull request merged**
