### PR TITLE
Create milestone 1 delivery for Coong Wallet

### PR DESCRIPTION
**Pull request by sinzii**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1387.

### CODE REVIEW

**Comment by keeganquigley** [comment]
@sinzii thanks for the delivery! Someone will take a look at it in the next few days.

**Comment by Ali-Usama** [comment]
@sinzii Thank you for a great delivery. But, it still needs some minor improvements for further processing of your application. Please find the detailed evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/804)

**Comment by sinzii** [comment]
Thank you @Ali-Usama for the evaluation,

1. Regarding the docker build error, I've fixed that, please pull the latest commit and run the build image command again.
2. Regarding the error message when running `yarn test`. While we do have `ErrorBoundary` to catch error, these are internal error messages reported by `jsdom`. Following a suggestion [here](https://github.com/facebook/react/issues/11098), I've mocked the `console.error` so we don't see these error messages anymore.
3. Regarding the inline documentation, we understand the value of documentation, along the way we also tried to use descriptive names for functions/classes/types to help reduce unnecessary documentation. I've added some inline documentation to a few key/important places, but given there is a lot of code to document, can we continue to add more in the next milestone?

Please check if my latest commits in the [w3f-milestone-1](https://github.com/CoongCrafts/coong-wallet/tree/w3f-milestone-1) branch helps resolve the issues of Dockerfile & `yarn test`, thank you!

**Comment by Ali-Usama** [comment]
@sinzii Thank you for resolving the errors and including the inline documentation. I've updated my evaluation as well. It was a great submission and I wish you the best of luck with your upcoming milestones.

**Comment by semuelle** [comment]
Thanks for the delivery and quick fixes, @sinzii. Your milestone is hereby accepted. 

I have forwarded your invoice for processing.

**Comment by sinzii** [comment]
Thank you @semuelle!

**Comment by RouvenP** [comment]
hi @sinzii we transferred the payment today.

**Comment by sinzii** [comment]
Thank you @RouvenP, we have received the fund!

**Pull request merged**
