### PR TITLE
 MangoBOX_Milestone_1_2.md

### PR DESCRIPTION
**Pull request by Mangoboxlabs**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/976 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Mangoboxlabs** [comment]
Hi, if you need our cooperation during the review process, please feel free to leave us a message, thank you!

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the milestone submission and my apologies for the late response. Please see the evaluation documents from milestone [1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangobox_1_dsm-w3f.md) and [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangobox_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by Mangoboxlabs** [comment]
Hi, @dsm-w3f , thank you very much for your review, we will check and optimize the issues you mentioned as soon as possible, please wait for further news from us.

**Comment by Mangoboxlabs** [comment]
Hi @dsm-w3f, thank you again for your review. We have closely checked all problems you mentioned and have already corrected them.

The details are as below, please take a review.

1. We are sorry about the contract test failure. Due to our mistake, a necessary parameter was missing from the unit test of the contract. Now that we have updated the code, you can continue to run the test command now.

2. As for the requirement of full testing, we have added how to use the polkadot app to test the contract in the documents.

https://github.com/Mangoboxlabs/Mangoboxink/blob/main/contract/README.md#testing

3. Regarding the problem of docker startup failure,  it might be that you did not run the command completely. We have added more hints in the documentation so you can follow these steps to retest.

https://github.com/Mangoboxlabs/Mangoboxink/blob/main/docker/README.md


Apologize for the trouble caused in the test. Please review it again. Please feel free to leave us comments as there might be new problems. We will  respond as soon as possible. Thank you very much.

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the fixes and improvements. I did a new evaluation round, we are almost finished. There are some possible quality improvements in the code and I also still need examples to test the software. The deployment process is also complicated. If you could provide an example of how to fill the constructors' parameters in the contracts would be nice. Details in the evaluation documents from deliveries [1](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangobox_1_dsm-w3f.md) and [2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/mangobox_2_dsm-w3f.md)

**Comment by Mangoboxlabs** [comment]
Hi, @dsm-w3f , Thank you very much for your evaluation, we have now made a further update:

1. First of all, we have further improved our contract deployment tutorial, detailing the steps and required parameters of contract deployment.

See this document for details:

https://github.com/Mangoboxlabs/Mangoboxink/blob/main/contract/README.md#testing

Contract deployment steps:

MBToken > MBProjects > MBTokenStore > MBSplitsStore > MBFundingCycleStore > MBOperatorStore > MBPrices > MBDirectory > MBSingleTokenPaymentTerminalStore > MBERC20PaymentTerminal > MBController


2. We made a tutorial for using the front-end files, and added some front-end code comments:

See this document for details:

https://github.com/Mangoboxlabs/Mangoboxink/tree/main/Frontend/TestDemonstration

3. Regarding the problem that the generated HTML document is blank, we can open the html file by executing this command. You can try it.

cargo doc --open

If you still encounter new problems during the evaluation process, please feel free to leave us a message, we will continue to improve.

Thanks again for all your hard work!

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the improvements. I was able to deploy the contracts locally without problems. However, when I tried to test the software using the user interface I got this error right after sending the transaction to deploy the project. The error happened  locally and also using the deployed mangobox web app. Please notice that in the tutorial for using the software is not possible to see all fields needed to register the project. Any hint about this error?

image

**Comment by Mangoboxlabs** [comment]
Hi, @dsm-w3f  , thank you very much for your further review, we have updated this file now, please try again to see if it works. If you still have questions, please feel free to leave us a message, thank you!

https://github.com/Mangoboxlabs/Mangoboxink/blob/main/Frontend/src/store/modules/abisMethods/MBController.js

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the fix. I tried to check if it is working but now I'm observing an unexpected behavior, I'm connected with an account and the authorization for submitting the transaction is for another account (the first one in my wallet I think). Could you please fix that?

image

After a while, I tried again and the confirmation window does not show up. I'm using this URL for testing: https://app.mangobox.xyz

image

**Comment by Mangoboxlabs** [comment]
> @Mangoboxlabs thank you for the fix. I tried to check if it is working but now I'm observing an unexpected behavior, I'm connected with an account and the authorization for submitting the transaction is for another account (the first one in my wallet I think). Could you please fix that?
> 
> 
> After a while, I tried again and the confirmation window does not show up. I'm using this URL for testing: https://app.mangobox.xyz/

I am very sorry to cause you trouble, just now our front-end engineer re-tested, he did not encounter similar problems as you. Could you please retest to see if the same problem persists?
When the techs come to work tomorrow, they'll go through the code again to see how they can finally fix it.
Thanks again for your hard work!

**Comment by Mangoboxlabs** [comment]
Hi, @dsm-w3f , after careful investigation by our technicians, both problems have been fixed, you can test again. If you encounter new problems during the test, please feel free to leave us a message, and we will solve them as soon as possible. Thanks again for all your hard work!

**Comment by dsm-w3f** [comment]
Hi @Mangoboxlabs, now I'm having another error, see the print:

image

**Comment by Mangoboxlabs** [comment]
@dsm-w3f Received, we will check and fix it as soon as possible, please wait for our further update, thank you!

**Comment by Mangoboxlabs** [comment]
Hi, @dsm-w3f  We have checked and fixed the issue. This time it is not a problem with the code, but the test chain server we deployed has expired.

Currently we have re-deployed a test chain, you can continue testing.

If you test at https://app.mangobox.xyz/, you need to re-transfer gas to your wallet, and the original gas has expired.

https://github.com/Mangoboxlabs/Mangoboxink/blob/main/Frontend/README.md

 image

**Comment by dsm-w3f** [comment]
@Mangoboxlabs I was able to run the tutorial using the on-line version of the software. I notice that the suggested code quality improvements were not implemented. Let me know if you intend to implement them then I can finish the evaluation.

**Comment by Mangoboxlabs** [comment]
@dsm-w3f At the same time we are very sorry, we just saw your email. We will register a matrix account and contact you directly after the technicians go to work in the morning. Thank you for your selfless help recently, we will do our best to submit the highest quality code.

**Comment by Mangoboxlabs** [comment]
> Some static analysis alerts generated by cargo clippy:

Hi, @dsm-w3f , we have re-checked all the contract codes, and the static analysis alerts problem has been fixed. You can re-download the contract code and test it again.

> However, when I generated the HTML docs with cargo doc the functions documentation didn't show up.

We don't know if this problem still exists for you. We can open html files by executing the cargo doc --open command.

cargo doc --open

Please tell us how you run it, and we'll check it again.

**Comment by dsm-w3f** [comment]
@Mangoboxlabs thank you for the improvements. The milestones are approved. I'll forward the invoices internally and the payment should take place within two weeks (could happen before). Good Job!

**Comment by Mangoboxlabs** [comment]
> @Mangoboxlabs thank you for the improvements. The milestones are approved. I'll forward the invoices internally and the payment should take place within two weeks (could happen before). Good Job!

@dsm-w3f Thank you very much for your selfless help to us, we will definitely do our best!

**Comment by fededubbi** [comment]
Hi @Mangoboxlabs,

I noticed that on the invoice there are 2 different amounts with 2 descriptions (milestone 1 and 2).
Could you please insert the total amount with ne description?
Also please insert an invoice number.

Many thanks,
Federica Dubbini

**Comment by Mangoboxlabs** [comment]
> Hi @Mangoboxlabs,
> 
> I noticed that on the invoice there are 2 different amounts with 2 descriptions (milestone 1 and 2). Could you please insert the total amount with ne description? Also please insert an invoice number.
> 
> Many thanks, Federica Dubbini

Hi, @fededubbi Sorry, we only saw the message today. We have resubmitted the invoice form, please check it. If you need new supplements, please feel free to leave us a message.

**Comment by fededubbi** [comment]
Hi,

Could you please add also your address (not payment address) but the physical one?

Many thanks,
Federica

**Comment by Mangoboxlabs** [comment]
Hi, @fededubbi 

Our Invoice Form has been updated and submitted, please check it again!

Thank you very much for your hard work~

**Comment by RouvenP** [comment]
hi @Mangoboxlabs we transferred the payment today

**Comment by Mangoboxlabs** [comment]
@RouvenP We have received it, thanks!

**Pull request merged**
