### PR TITLE
Infimum: milestone 2

### PR DESCRIPTION
**Pull request by rhysbalevicius**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1948

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @rhysbalevicius thanks for the delivery.

`curl --output e2e.tar.gz https://cdn.rhys.tech/infimum/e2e.tar.gz` works, but when I run the command `tar xf e2e.tar.gz -C cli/__tests__` I get the following:
```
tar: cli/__tests__: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```

It's probably something simple, can you check to ensure that the file and path are correct? Thanks.

**Comment by keeganquigley** [comment]
Thanks @rhysbalevicius much appreciated, that helped and I was able to get everything running. I'm happy to accept the milestone, and here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/infimum_2_keeganquigley.md). For the next milestone, consider adding more unit tests to test more than just happy paths. 

Thanks and have a happy holidays!

**Comment by rhysbalevicius** [comment]
Amazing. Thank you @keeganquigley!

> For the next milestone, consider adding more unit tests to test more than just happy paths.

Very good point, I will definitely do that.

Happy holidays :)

**Comment by RouvenP** [comment]
hi @rhysbalevicius we just sent the payment

**Pull request merged**
