### PR TITLE
Afloat Milestone 2

### PR DESCRIPTION
**Pull request by LouiseWReed**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/911

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the delivery @LouiseWReed! We'll look into it as soon as possible.

**Comment by randombishop** [comment]
Thank you for the delivery @LouiseWReed! I'll start evaluating your delivery today and get back to you with feedback. Probably by end of this week or early next one.

**Comment by randombishop** [comment]
@LouiseWReed 
First preliminary comments about the delivery:

1) The video feels kind of disconnected from the project. The video in milestone 1 was good at showing the process as it applies to the context of Afloat, and it was super helpful for me to understand that first scope. But this second one is showing generic NFT creation and listing that doesn't match the context of Afloat. Would it be possible to see how the pallets and deliverables are used in the context of a tax credit NFT, along with the part where the uploaded docs can be viewed by marketplace admin and the Tax Credit verification part?

2) I see that the Tax Credit verification part is missing from the delivery, while the grant contract specifies a MVP. In my opinion, without this part, it's hard to understand the difference between a standard NFT trading platform and the Afloat proposition. I would recommend incorporating the MVP into deliverable and also into the presentation video so that we can understand and evaluate the specific features of Afloat project.

3) in the meantime, I am trying to install all components and run an Afloat system locally. My guess is that I should install and run the different components in this order:
- Substrate node here: https://github.com/hashed-io/hashed-substrate/tree/main
- Afloat Client API
- Marketplace UI
- Confidential Documents Server
- Confidential Documents API
Is this correct? And are there any configuration steps to connect all these together?
Can you provide a general guide with this delivery to indicate how to set-up a full system locally?

Thank you!

**Review by Noc2 — APPROVED** [review]

**Comment by LouiseWReed** [comment]
Thank you, Nabil.

**Pull request merged**
