### PR TITLE
LIP Payments pallet - Milestone 1

### PR DESCRIPTION
**Pull request by olanod**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the kUSD payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/756

### CODE REVIEW

**Comment by olanod** [comment]
Not sure why the check fails, I am sill me 🤔

**Comment by alxs** [comment]
Thanks for the delivery @olanod! We'll look into it as soon as possible.

You're right, the workflow was broken. Seems I hadn't tested it the last time I made changes. I just fixed it - thanks for pointing it out.

**Comment by olanod** [comment]
Thanks @takahser, we'll review your evaluation and implement the required changes :)

**Comment by olanod** [comment]
Hi @takahser, in our latest `master` we have implemented the relevant fixes to address the issues with documentation, tests and benchmarks that you pointed out in your review. Let us know if there are other things we should consider to change.

**Comment by takahser** [comment]
Hi @olanod

Thanks for the updated delivery. I took a look at it again and mostly it looks fine now.
There is just 1 last thing: I think you didn't react to my [question regarding the unit tests](https://github.com/w3f/Grant-Milestone-Delivery/blob/afcacaba3e74cee1bc32e5826740ef1907be67ca/evaluations/lip-payments_1_takahser.md?plain=1#L122), yet (pls correct me if I'm wrong).
Basically I'm wondering why you didn't add unit tests for certain functions.

Example:
- The `PaymentHandler::create_payment` function is called inside the `Pallet::pay` function.
- There is a test for `Pallet::pay` function (which is good).
- However, I didn't find any dedicated test for `PaymentHandler::create_payment`.

Is there any specific reason for that? IMHO when dealing with unit tests we should try to write tests at the lowest possible level.

**Comment by olanod** [comment]
For the time being we were considering the current test suite as "good enough" since it covers all critical functionality. We will definitely be extending it as the crate matures(e.g. for M2) but likely not covering `PaymentHandler` methods that are more of an implementation detail and its likely to me removed as we don't see more implementations of that trait being developed, for extensibility we're likely going to add extra hooks and other pallets can depend on payments_pallet directly

**Comment by takahser** [comment]
@olanod Thanks for your quick response!
I understand your point of view to the extend that the `PaymentHandler` methods don't vary dramatically from their client methods in the `Pallet` and hence your tests already cover a large part of these downstream methods. Nevertheless, I think if you're planning to change or remove these methods while refactoring your code, having these tests could come in quite handy. Especially since these `PaymentHandler` methods seem to be a core functionality and security-critical (pls correct me if I'm wrong). So if you wrote these tests now this could help preventing potential regression bugs that might occur later and otherwise potentially even remain undetected.
Hence I think it would be good to add some tests for these methods. After that I'm more than happy to approve your milestone. :)

**Comment by olanod** [comment]
Hi @takahser we just merged https://github.com/virto-network/virto-node/pull/182 adding a new suite of unit tests :)

**Review by takahser — APPROVED** [review]
Hey @olanod 
Thanks for adding the additional tests.
I'm now more than happy to accept your delivery, you can find my final feedback [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/21285318d3f2cc16b8aac62b3665992e6afddd59/evaluations/lip-payments_1_takahser.md).
Good work overall, thanks for all the work you put into this. I'm going to forward your invoice, pls allow up to 2 weeks for the settlement to complete.
I'm very much looking forward to M2!

**Comment by RouvenP** [comment]
hi @olanod we sent a test tx of 10 kUSD this morning. Could you confirm if received? Thanks

**Comment by olanod** [comment]
@RouvenP confirmed :)

**Comment by RouvenP** [comment]
@olanod thanks for confirming, we sent the remainder.

**Pull request merged**
