### PR TITLE
InvArch Milestone #2 Delivery

### PR DESCRIPTION
**Pull request by XCAstronaut**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the Acala $aUSD payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/950 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by cruikshankss** [comment]
Good day @XCAstronaut, and thank you for your delivery. I quickly reviewed your original and amended applications and I will look into your delivery as soon as possible.

**Comment by XCAstronaut** [comment]
Thank you, @cruikshankss! I appreciate you taking the time to look over our proposal details & reviewing our milestone delivery.

**Comment by XCAstronaut** [comment]
I don't mean to be a bother, but I wanted to send you a ping @cruikshankss to check on this & see how things were going.

**Comment by cruikshankss** [comment]
@XCAstronaut Good day! I haven't started testing your codebase yet but aim to do so this week. Thanks.

**Comment by cruikshankss** [comment]
Hi @XCAstronaut, I was able to start on your evaluation. I watched your demo video, read through the not-yet-published article and had a brief look through your pallets. Thank you very much for this. Ideally, I am able to easily replicate the contents of the demo video on my machine. I hope I can do this with the testing documentation and demo video together, but I feel there might be a few steps missing or instructions in different places. I will try my best though and please feel free to add details to the testing guide to make this quicker for me! Thanks!

**Comment by XCAstronaut** [comment]
Please @cruikshankss, if you have any questions or feedback, and of course any points that we must address per the grant, I’d love to take this opportunity to get both your approval and insight to how we can provide friendlier documentation. Thank you again for taking the time to review our submission!

**Comment by cruikshankss** [comment]
Good day @XCAstronaut. I've been reviewing your project again and while I do think you have nice documentation, what I'm really looking for (and is part of the delivery requirements) is to give a step-by-step testing guide. I do really appreciate the demo video, but feel there are some steps missing for me to easily cruise through and replicate it. What would be ideal and would very likely help me complete your evaluation ASAP is if you could type out the series of commands/actions (complete from start to finish) assuming that I'm brand new to the project.

By the way, I just saw your comment from before. Yes, it is a Harry Potter reference. 😎🐈 Nice catch.

**Comment by XCAstronaut** [comment]
Hey @cruikshankss, thank you for pointing this out. We have updated our documentation & our delivery PR to provide a step-by-step testing guide for individuals. We hope this is more thorough so that any developer can get things going & have a smooth walkthrough experience. Let me know your thoughts, please. I look forward to your review & appreciate your time as always!

Harry Potter was one of the major pieces of my childhood, so I appreciate the reference. 10 points to the W3F.

**Comment by cruikshankss** [comment]
Hi @XCAstronaut, that is an amazing testing guide. I've made it really far through already! I got stuck trying to `git push origin master` on the test-repo:

```
git: 'remote-inv4' is not a git command. See 'git --help'.

```

so then i tried rerunning `cargo install --git https://github.com/InvArch/INV4-Git` and indeed I hadn't noticed before:

```

    Updating git repository `https://github.com/InvArch/INV4-Git`
  Installing git-remote-inv4 v0.1.0 (https://github.com/InvArch/INV4-Git#ffba3a57)
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/subxt`
error: failed to compile `git-remote-inv4 v0.1.0 (https://github.com/InvArch/INV4-Git#ffba3a57)`, intermediate artifacts can be found at `/var/folders/2z/6cfwl9fx4f1fqrwdb9625grh0000gn/T/cargo-installML6gAy`

Caused by:
  failed to select a version for the requirement `libgit2-sys = "^0.13.4"`
  candidate versions found which didn't match: 0.13.2+1.4.2, 0.13.1+1.4.2, 0.13.0+1.4.1, ...
  location searched: crates.io index
  required by package `git2 v0.14.4`
      ... which satisfies dependency `git2 = "^0.14.4"` of package `git-remote-inv4 v0.1.0 (/Users/ash/.cargo/git/checkouts/inv4-git-80ec0d2e41c6f6d4/ffba3a5)`
```

So it seems I might have a version issue with my lib version? During the last evaluation I did, the team I was working with said I might have an issue with my libp2p and they gave me a workaround. If you have an answer for me, it would be much appreciated because I'm unfamiliar with configuring the libp2p toolchain properly, but I will try to figure it out asap! 

By the way, I've been really enjoying testing your project so far!! Excellent work!!

**Comment by cruikshankss** [comment]
Hi @XCAstronaut, I was able to figure out my error and was able to complete [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/invarch_2_cruikshankss.md)! More details there & congratulations! I've forwarded your invoice internally.

**Comment by RouvenP** [comment]
hi @XCAstronaut could you send us an updated invoice with the new payment address? Thanks

**Comment by XCAstronaut** [comment]
Hey @RouvenP! I’ve sent an updated invoice with the corrected payment address sometime within the last 24hrs.

I just noticed this comment, so I wanted to follow up to let you know. Thank you!

**Comment by RouvenP** [comment]
hi @XCAstronaut, we received the invoice, thank you! We will distribute it next Wednesday. I will let you know once done.

**Comment by RouvenP** [comment]
hi @XCAstronaut we transferred the payment two days ago.

**Pull request merged**
