### PR TITLE
Adding deliverables document for MoveVM Substrate Pallet part 2

### PR DESCRIPTION
**Pull request by MeerKatDev**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1902

### CODE REVIEW

**Comment by keeganquigley** [comment]
Sorry for the delay @MeerKatDev starting on this now.

**Comment by dsm-w3f** [comment]
@MeerKatDev thank you for the milestone delivery. I tested it and in general is working well, just small issues to fix. Please take a look at the evaluation document in [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1137) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by Rqnsom** [comment]
Hi @dsm-w3f,

I'm Karlo, one of the developers for this project.
We fixed all issues from your [evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1137), so feel free to continue this evaluation.

> I was able to follow [the tutorial](https://github.com/eigerco/pallet-move/blob/main/doc/tutorial.md) without problems.

We are glad about this! 

> All tests on this repository passed with good coverage. The src/lib.rs has 82% of coverage.
> The move-vm-backend and move-vm-backend-common have good coverage of close to 80%.

Regarding the code coverage - we will probably increase it in the next milestone. We tried to focus mainly on covering the core functionality with tests, and the next milestone will provide even more tests to ensure the final solution is robust enough.

> The Language could have better coverage in some parts, but I think it's good in general.

Yes, the tests for the language part were mainly inherited from the original Move repo. And since we tried to make minimal changes in that core MoveVM part (only small adaptation work), we haven't increased the original test coverage much. We might check this more in the next (final) milestone.

**Comment by dsm-w3f** [comment]
@MeerKatDev and @Rqnsom thank you for the improvements and fixes. I tested again the issues that I found before were fix. Just a small problem with docker, but this don't prevent the milestone approval. Thanks for the collaboration, great job! @keeganquigley [the evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1137) is open and updated with the latest evaluation.

**Comment by keeganquigley** [comment]
Thanks for the evaluation @dsm-w3f and for the quick responses @MeerKatDev the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1137) was accepted and I hereby pass this milestone. Congrats on the completion of this grant.

**Pull request merged**
