### PR TITLE
SydTek_Milestone2.md

### PR DESCRIPTION
**Pull request by jgophd**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1183

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @jgophd, thanks a lot for the delivery. Could you please delete `SydTek_Milestone1.md` from the pull request?

**Review by 0xCaso — COMMENTED** [review]
Hi @jgophd, thanks a lot for the delivery. Could you please delete `SydTek_Milestone1.md` from the pull request?

**Comment by jgophd** [comment]
> Hi @jgophd, thanks a lot for the delivery. Could you please delete `SydTek_Milestone1.md` from the pull request?

@0xCaso, Milestone1 should now be removed from the PR.

**Comment by dsm-w3f** [comment]
@jgophd thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sydtek_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by jgophd** [comment]
image

FIGURE 1. An overview of the pubkey change process

**Comment by jgophd** [comment]
@dsm-w3f, I have submitted the following to evaluation documents section for acceptance to your post.

**The second interview is with Tyler Doussan from Safe Heaven. I was not able to find your interview with him. However, I notice in the transcript some copy-and-paste transcripts from podcasts and youtube channels. Could you explain that?**

The transcript from this interview was added as we cited that interview in the study as you can now cite YouTube interviews in academic journal articles. As we initially researched SafeHaven due to the fact that they have a similar product on VeChain, after speaking with Jürgen Schouppe, the CEO of SafeHaven, the team is looking to integrate the suggested recommendations mentioned in the study to develop a solution on Kusama using the social recovery pallet. If you need a formal interview with Jurgen or Tyler to discuss these plans, we can do that and upload it to the submission.

**Could you provide explanations on why did you copy and pasted transcripts of youtube videos on a deliverable that should be interviews conducted by SydTek with Phala Network, RMRK and Parity Technologies members?**

Joshua Waller and Zoe Meckbach of Phala made the introduction to Mark Ryan of RMRK to set up an interview with their team, but we were unable to coordinate anything. I also sent a message to Shawn Tabrizi on 11/14/22 to request an interview on the social recovery pallet given he was the lead developer that discussed the pallet. As I didn’t receive a response from Shawn, as a contingency, we included the transcripts from Shawn’s interview with Joe Petroski as well as his presentation. As with the SafeHaven interviews, we included these transcripts because we cited these interviews within the study. 

**The paper is well-written and easy to understand. Some small requests here:
In the section THE SOCIAL RECOVERY PALLET, Fig 1 is not available in the text. Please include the image in the deliverable.**

The following image has been added.

image


**In the section EXECUTING THE DIGITAL INHERITANCE PROCESS ON POLKADOT AND KUSAMA, the schema described starts with "the digital executor could submit a deposit to initiate the social recovery". My question is, how the digital executor will know that he/she needs to start social recovery?**

Similar to the Web2 world, trustees and beneficiaries will work with the testator to set up wallets so they will be able to receive assets upon the testator’s passing. Because they will be expecting these assets, they will be the first to make the digital executor aware of the testator’s passing. Additionally, because the executor also has skin in the game in some instances, the executor is also incentivized to initiate the social recovery process.

**In the section ACKNOWLEDGEMENT, it must include a notice that the paper was supported by the web3 foundation, as discussed in the application.**

This is been resolved and the revised section is below:

XI. ACKNOWLEDGEMENT The authors would like to thank Joshua Waller, Ray Lu, and the other team members from Phala and Bit.Country from the Polkadot and Kusama ecosystems for their thoughts and input into this study. The authors would also like to thank Charlotte McCurdy of Perley-Robertson, Hill & McDougall for providing input from a legal aspect on digital asset inheritance. This work was supported by a research grant from the Web3 Foundation.

**We expect for the paper delivery that a PDF should be provided and a preprint should be registered in some archive (ex. [arvix](https://arxiv.org/)). This could be performed in the next milestone if it is more convenient for you.**

The article has been added to ARXIV and can be found at the following link: https://arxiv.org/submit/4707279/view

**Comment by dsm-w3f** [comment]
@jgophd thank you the answers. I think the reasons are ok for not doing more interviews. I updated [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sydtek_2_dsm-w3f.md) and the milestone was approved. Would be nice to take a look at [this project](https://github.com/hypha-dao/hashed-wallet). They developed a social recovery wallet based on the social recovery pallet. They have [a grant with us](https://github.com/w3f/Grants-Program/pull/1001) and just delivered the [third milestone](https://github.com/w3f/Grant-Milestone-Delivery/pull/713). This may add something to your article. Good luck during the publishing process and let me know when the paper was published.

**Comment by dsm-w3f** [comment]
@jgophd can you change and resubmit your invoice? The values are opening with some strange font and some people from our team are not able to see the values correctly.

**Comment by jgophd** [comment]
@dsm-w3f, I just recreated and resubmitted the invoice. Can you check on your end to see if that one is viewable?

**Comment by dsm-w3f** [comment]
@jgophd the value is ok now. However, the invoice date is probably wrong since it still reports 2022.
Could you please update the invoice and resend it?

**Comment by jgophd** [comment]
@dsm-w3f, I just changed the year to 2023 and resubmitted the invoice. Sorry about that.

**Comment by jgophd** [comment]
> @jgophd the value is ok now. However, the invoice date is probably wrong since it still reports 2022. Could you please update the invoice and resend it?

@dsm-w3f, I just wanted to confirm that you received my last message stating I resent the invoice.

**Comment by dsm-w3f** [comment]
@jgophd yes, I received and forward the invoice. I'll get in touch with operations team to know the forecast for payment.

**Comment by dsm-w3f** [comment]
@jgophd they informed me that the payment should happen today. Please check your wallet.

**Pull request merged**
