### PR TITLE
RedStone-Milestone-1

### PR DESCRIPTION
**Pull request by AmadeusGB**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1093

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@AmadeusGB thank you for the milestone submission. Please see the [evaluation documents](https://github.com/w3f/Grant-Milestone-Delivery/commit/33a8b3fe519ad038a0a321e7ded4716cbcbcbaf5) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by baidang201** [comment]
The invoice form filled in a wrong amount (the milestone 1 is 8000 USDT, I thought it was 15000 USDT),
Should I resubmit an invoice form or what to do?

**Comment by dsm-w3f** [comment]
@baidang201 yes, feel free to submit a new invoice with the correct amount. We will handle it when the milestone delivery was approved.

**Comment by dsm-w3f** [comment]
@baidang201 this PR is marked as stale since there are more than two weeks without any activity. Do you still plan to deliver the requested changes? Any forecast for this? Otherwise, if we have more two weeks without any activity this PR will be closed.

**Comment by baidang201** [comment]
we had commit the invoice form,  all check list is done.  go on deliver the requested, please.

**Comment by dsm-w3f** [comment]
@baidang201 you already fixed the issues that I found and reported in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/commit/33a8b3fe519ad038a0a321e7ded4716cbcbcbaf5)? I see no changes in the project repository since my evaluation (main branch). The invoice is only paid after the deliverables have been evaluated and approved.

**Comment by baidang201** [comment]
> @baidang201 you already fixed the issues that I found and reported in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/commit/33a8b3fe519ad038a0a321e7ded4716cbcbcbaf5)? I see no changes in the project repository since my evaluation (main branch). The invoice is only paid after the deliverables have been evaluated and approved.

will fix tomorrow. i miss the  evaluation documents

**Comment by baidang201** [comment]
### Testing Guide
I was able to compile the code with `cargo build --release`, however the tests `cargo test --release` are failing to compile with the following error: "missing `TransferProtectInterface` in implementation".
=> had fix 

When I tried to spin up the blockchain node, as describedd [here](https://github.com/redstone-network/redstone-node#run-the-rsn-node), I notice that the executable did not exist. The files in the target folder are listed in the image below. Can you provide assistence on that?
=> had fix, we can find redstone-node in target/release

We mainly use these three modules. If these three tests pass, it will be ok.
cargo test -p pallet-permission-capture
cargo test -p pallet-defense
cargo test -p pallet-notification

### Article/Tutorial 
We need better explanation on how to test the behavior or the system, as a sequence of steps on how to use these features in the blockchain.
=》
will write later

### Docker
From docker I was able to spin up the node but I cannot connect to it using default port (9944) on Polkadot.js. 
=>
1 make sure your computer is x86 cpu
2 i change the docker cmd run in backgroud,try run again
```
docker pull baidang201/redstone-node:latest
docker run -d --network host baidang201/redstone-node:latest /usr/local/bin/redstone-node --dev --rpc-cors all --rpc-methods=unsafe --rpc-external --unsafe-ws-external --unsafe-rpc-external
```
3 after run docker cmd, run "lsof -i:9944" check if the 9944 is listening

**Comment by dsm-w3f** [comment]
@baidang201 thank you for the improvements. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/redstone_1_dsm-w3f.md) and still need the tutorial/article to finish this evaluation.

**Comment by baidang201** [comment]
> @baidang201 thank you for the improvements. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/redstone_1_dsm-w3f.md) and still need the tutorial/article to finish this evaluation.
https://github.com/redstone-network/grant-test-tutorial/blob/main/RedStone-Milestone-1-test-tutorial.md

will be done tomorrow.

**Comment by baidang201** [comment]
the tutorial is done, please check. (https://github.com/redstone-network/grant-test-tutorial/blob/main/RedStone-Milestone-1-test-tutorial.md)

the docker images baidang201/notification  may push later and info you

**Comment by baidang201** [comment]
@dsm-w3f baidang201/notification is done

**Comment by dsm-w3f** [comment]
@baidang201 thank you for the improvements and fixes. Almost all steps worked fine, just notifications are not working with a panic error in the step that notifications should be sent, see the print below. Can you fix/assist with this error? 

image

**Comment by baidang201** [comment]
> @baidang201 thank you for the improvements and fixes. In the tutorial, almost all steps worked fine. Just notifications are not working with a panic error in the step that notifications should be sent, see the print below. Can you fix/assist with this error?
> 
> image

this is the docker base ubuntu has not ca lib, i change to docker.io/paritytech/ci-linux:production and fix it, 
you can pull image and retry test notifications.
```
docker pull baidang201/redstone-node
Using default tag: latest
latest: Pulling from baidang201/redstone-node
Digest: sha256:2042c297dbeac3e7700db4b5ea4a991697377a229dfe1bef7ec46735166f1c3a
Status: Downloaded newer image for baidang201/redstone-node:latest
docker.io/baidang201/redstone-node:latest
root@iZj6cehalkln0c5qwrm06zZ:~# docker images
REPOSITORY                 TAG          IMAGE ID       CREATED         SIZE
baidang201/redstone-node   latest       719109f98ada   9 minutes ago   3.28GB
```

**Comment by baidang201** [comment]
test email notifications is base tencent mail api, may be need a China ip vps to test.

**Comment by dsm-w3f** [comment]
@baidang201 thank you for the fix and hints about the problem. The tutorial worked now as the events were emitted and the application didn't panic anymore. One last thing, the command in the documentation to start the network without docker is failing. Could you take a look? See [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/redstone_1_dsm-w3f.md) for details.

**Comment by baidang201** [comment]
> @baidang201 thank you for the fix and hints about the problem. The tutorial worked now as the events were emitted and the application didn't panic anymore. One last thing, the command in the documentation to start the network without docker is failing. Could you take a look? See [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/redstone_1_dsm-w3f.md) for details.

 had updated run testnet cmd
```
./target/release/redstone-node --base-path /tmp/redstone --chain dev --alice
```

**Comment by dsm-w3f** [comment]
@baidang201 thanks for changing the command. Now it is working. The milestone was approved. I'll forward your invoice internally and the payment should take place within two weeks. Great work!

**Comment by fededubbi** [comment]
Good morning,

I noticed that on your invoice there is no USD sign in all the amounts there.
Can you please add them?

Also we would need your payment address including the currency you want to be paid in.

Many thanks,
Federica Dubbini

**Comment by baidang201** [comment]
sure，will change later.

**Comment by baidang201** [comment]
@fededubbi had upload a new Web3 Foundation Grant - Invoice Form,  with USD and payment address including the currency.

**Comment by baidang201** [comment]
> 

thanks

**Pull request merged**
