### PR TITLE
ECDSA for Polkadot JS

### PR DESCRIPTION
**Pull request by akru**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. I will try to look into it as soon as possible.

**Comment by Noc2** [comment]
Thanks @akru Everything works as promised. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadotjs-ecdsa_1_Noc2.md). So, I'm happy to tell you this milestone is a pass! I will forward your invoice internally.

**Comment by RouvenP** [comment]
hi @akru: we just sent a test transaction. can you confirm if received? thanks

**Comment by akru** [comment]
@RouvenP received, thank you!

**Comment by akru** [comment]
@RouvenP could you send other part?

**Comment by RouvenP** [comment]
> @RouvenP could you send other part?

@akru sent. apologies for the delay.

**Comment by akru** [comment]
@RouvenP Received, thank you!

**Pull request merged**
