### PR TITLE
Adding Knowledge-Oriented-Framework-Milestone 3.md

### PR DESCRIPTION
**Pull request by rbrandao**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1420](https://github.com/w3f/Grants-Program/pull/1420)

### CODE REVIEW

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the delivery, @rbrandao. I see that there wasn't much activity on the Mural. I'm sorry to see. It would be great to get more eyes on the ontology.

Regarding the delivery, everything looks pretty good. I just have some small issues:

1. The CC license is not mentioned anywhere in the material or repository. In fact, the repo is declared to be under Apache 2.0. 
2. CQ3 and CQ4 seems impractical, as wallets are usually only accessible by the owner. So querying a wallet would be quite difficult. CQ4 could be rewritten as "Which accounts have more DOT tokens than me?". 
3. CQ5 does not specify which transactions are relevant. Usually, someone would query the number of transaction on a specific chain. Is this intentional?

Going forward, it would be interesting to compare these queries to SPARQL or SQL queries that are commonly done on Polkadot/Substrate datasets as, for example, described [here](https://github.com/colorfulnotion/substrate-etl#quick-start) to see if they are already doable or what work would be necessary to implement them.

**Comment by rbrandao** [comment]
Hi @semuelle, thanks for the prompt evaluation. We uploaded a new version of the article addressing the pointed issues.

> The CC license is not mentioned anywhere in the material or repository. In fact, the repo is declared to be under Apache 2.0.

Just to clarify our intent, the repository is under Apache 2.0. That is, the ontology Turtle files and other code that may be created are under this license. All the PDF documents are under CC-SA license. The link to the CC license is on the milestone delivery table (deliverable item 0a). We added a "License" section to README.md in the POnto repo to clarify this point.

> CQ3 and CQ4 seems impractical, as wallets are usually only accessible by the owner. So querying a wallet would be quite difficult. CQ4 could be rewritten as "Which accounts have more DOT tokens than me?".

Thanks for pointing out this mismatch. We adjusted CQ3 and CQ4 accordingly. Now they are "CQ3: How many accounts have DOT and KSM tokens?" and "CQ4. Which accounts have more DOT tokens than me?".

> CQ5 does not specify which transactions are relevant. Usually, someone would query the number of transaction on a specific chain. Is this intentional?

We expanded CQ5 to refer to a specific paranchain (Moonbeam) in the competency question. Regarding the specificity of the transactions, eventually the ontology can be expanded to cover all specific and relevant transaction metadata. For illustration purposes, we thought that the sum of all the transactions in a time interval could be interesting to have a sense of the network load.

> Going forward, it would be interesting to compare these queries to SPARQL or SQL queries that are commonly done on Polkadot/Substrate datasets as, for example, described [here](https://github.com/colorfulnotion/substrate-etl#quick-start) to see if they are already doable or what work would be necessary to implement them.

Thank you for pointing out the Substrate-ETL project. We are preparing a follow-up grant application encompassing the envisioned analytics tool we discussed during our collab session. We will keep an eye on their SQL queries and will investigate them as our roadmap progresses.

**Comment by semuelle** [comment]
Thanks for the updates, @rbrandao! I am happy to report that your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/MOBR-Knowledge-Oriented-Framework_3_semuelle.md). 

I have forwarded your invoice for processing.

**Comment by rbrandao** [comment]
Thank you @semuelle! For us at MOBR, this project was a great experience and learning opportunity. Being able to work with domain experts in first hand gives us a unique perspective of the real problems the Polkadot community faces.

I submitted the delivered paper to arxiv and soon will be able to post the final URL here.

Looking forward to the next steps and follow-up on our research initiative.

**Pull request merged**
