### PR TITLE
Polkadot js Plus - Social Recovery Wallet Delivery

### PR DESCRIPTION
**Pull request by Nick-1979**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1016

### CODE REVIEW

**Comment by cruikshankss** [comment]
Hi @Nick-1979, thank you very much for your delivery and I'm very much looking forward to reviewing it! I have quite a lot of work this week and just wanted to let you know I don't plan to begin your evaluation till next week, but I plan to keep you updated of course. Thank you and please let me know if you have any questions!

**Comment by Nick-1979** [comment]
Hi @cruikshankss, great, no rush, If there is any issue using the Social recovery feature, I would be happy to help, Cheers.

**Comment by cruikshankss** [comment]
Good day @Nick-1979,

I've finished three evaluations since we last spoke. Tomorrow, I plan to start & work on both your evaluation and another. I aim to complete both of these evaluations by Friday. 

I have some general Qs I've developed when beginning an evaluation:

> What quality is your testing guide? Would you like to schedule a video demo call with me for this week? Does your testing guide have a video demo? (Perhaps it doesn't even need one.) 

I'm already very familiar with Plus, so you could potentially disregard ^those questions. I plan to take a look at your social recovery features tomorrow regardless if you can answer these questions by then. 

Thanks for your patience with me! Talk soon!

**Comment by PolkaGate** [comment]
Hey @cruikshankss, 

Awesome, We made [a video demo](https://www.youtube.com/watch?v=HsfKGzoQnEo) which shows how the social recovery works step by step.
If a video meeting is needed we can schedule it for sure. This is [my Element handle](https://matrix.to/#/@nick1979:matrix.org) to set a schedule or sharing any issues while testing the extension.

Thank you,
  Kami

**Comment by Nick-1979** [comment]
Hey @cruikshankss,

Awesome, We made [a video demo](https://www.youtube.com/watch?v=HsfKGzoQnEo) which shows how the social recovery works step by step.
If a video meeting is needed we can schedule it for sure. This is [my Element handle](https://matrix.to/#/@nick1979:matrix.org) to set a schedule or sharing any issues while testing the extension.

Thank you,
Kami

**Comment by takahser** [comment]
@Nick-1979 thanks for the update here and please excuse the delay here, we're currently a bit behind in our backlog. I'm going to take over this evaluation for now. I or somebody else from my team will take another look at the application and provide you with feedback soon, most likely sometime this week.

**Comment by Nick-1979** [comment]
Hi @takahser,

If I could help in any means for evaluating the milestone please let me know.

Thank you.

**Review by takahser — CHANGES_REQUESTED** [review]
@Nick-1979 thanks, I actually do have a question. How can I connect to Westend, so I can test your deliveries using Westies?

image

Although I wasn't able to fully test the ui yet, I added a first version of my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/plus-social-recovery-wallet_1_takahser.md), feel free to have a look.

**Comment by Nick-1979** [comment]
Hi @takahser,

Thank you for the feedback.

If you are building the code yourself, you need to add Westend as mentioned [here](https://github.com/Nick-1979/polkadot-Js-Plus-extension#testing) before build.

The easiest way is to download the available add-on on Firefox [here](https://addons.mozilla.org/en-US/firefox/addon/polkadot-js-plus-extension/)

You will see Westend as shown below:




Screenshot (12)

About the removing silent in test, those are some in code console logs for testing, plus some warning which are mostly related to some modules that are out of the scope of our mission, like Polkadot-rpc-core version, react-i18next, and polkadot js base. however, we will remove console logs which are not needed any more.

please let me know any other issues you may have during the evaluation.

Thank you,
  Kami

**Review by takahser — APPROVED** [review]
@Nick-1979 thanks for your comments.
Regarding the Westend config, it worked fine for me.

> part of those warnings were console logs for debugging which are not needed any more and are removed

If they're not needed anymore, feel free to remove them.

I tested everything and it works, so I'm accepting your delivery. I found a bug which I created an issue for [here](https://github.com/Nick-1979/polkadot-Js-Plus-extension/issues/67). Also, there are a couple of things that could be improved from an UX perspective, see [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/plus-social-recovery-wallet_1_takahser.md).

Here are some more UI issues that I noticed:

- The "?" labels are not centered. Also, I think they'd usually be located on the right side, rather than the left. Probably due to the fact that we read from left to right (just thinking out loud here).

    image

- The _List of Friends_ title in the _Make Recoverable_ screen has a different font than other titles, it looks like Papyrus to me.

    image

Feel free to improve on them as well.

**Comment by RouvenP** [comment]
hi @Nick-1979 we transferred the payment last week.

**Pull request merged**
