### PR TITLE
Grant Milestone 1 Delivery - Tempora

### PR DESCRIPTION
**Pull request by pcorrado-np**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1857

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @pcorrado-np someone will take a look at it shortly.

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Hi @pcorrado-np I'm evaluating this now. I'm getting errors when trying to run the yarn commands in the root dir:
```
yarn test
yarn run v1.22.19
warning ../package.json: No license field
$ vitest
/bin/sh: vitest: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I ensured that Vitest is installed so I'm not sure what the issue is. Can you look into this?

Also, I'm running into issues with trying to sign both txs. Do I need to have some RSTR tokens sent to my test account? If so can you send some to 5CfwW8QTeFCotapEukrre4sT9tjMAp3jNY6VTyFAQ8hpd7F3

**Comment by pcorrado-np** [comment]
> Hi @pcorrado-np I'm evaluating this now. I'm getting errors when trying to run the yarn commands in the root dir:
> 
> ```
> yarn test
> yarn run v1.22.19
> warning ../package.json: No license field
> $ vitest
> /bin/sh: vitest: command not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ```
> 
> I ensured that Vitest is installed so I'm not sure what the issue is. Can you look into this?
> 
> Also, I'm running into issues with trying to sign both txs. Do I need to have some RSTR tokens sent to my test account? If so can you send some to 5CfwW8QTeFCotapEukrre4sT9tjMAp3jNY6VTyFAQ8hpd7F3

Hi @keeganquigley, 

- Did you run `yarn install` before? We just added the step to the `README` file. 
- `RSTR` tokens on Rocstar and `TUR` tokens on Turing-Staging are needed to create the proxy accounts. I already sent you enough tokens.

Thanks!

**Comment by keeganquigley** [comment]
Thanks @pcorrado-np much appreciated, figures it was something easy. The unit tests are running now but with warnings about conflicting node modules. It also seems to get stuck waiting for file changes:

<details>

<summary>Output</summary>

```ts
ubuntu@ip-172-31-31-38:~/tempora$ yarn test
yarn run v1.22.19
warning ../package.json: No license field
$ vitest

 DEV  v0.34.6 /home/ubuntu/tempora

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.5.1      node_modules/@polkadot/util/

stderr | unknown test
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/

stderr | unknown test
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-codec/node_modules/@polkadot/util/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util-crypto/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-bridge/
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-crypto-wasm/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto-wasm/
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-util/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-util/

stderr | unknown test
The current test runner does not support afterEach/teardown hooks. This means we won't be able to run automatic cleanup and you should be calling cleanup() manually.
The current test runner does not support beforeAll/afterAll hooks. This means you should be setting IS_REACT_ACT_ENVIRONMENT manually.

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-codec/node_modules/@polkadot/util/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util-crypto/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-bridge/
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-crypto-wasm/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto-wasm/
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-util/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-util/

stderr | unknown test
The current test runner does not support afterEach/teardown hooks. This means we won't be able to run automatic cleanup and you should be calling cleanup() manually.
The current test runner does not support beforeAll/afterAll hooks. This means you should be setting IS_REACT_ACT_ENVIRONMENT manually.

stderr | unknown test
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.5.1      node_modules/@polkadot/util/

stderr | unknown test
The current test runner does not support afterEach/teardown hooks. This means we won't be able to run automatic cleanup and you should be calling cleanup() manually.
The current test runner does not support beforeAll/afterAll hooks. This means you should be setting IS_REACT_ACT_ENVIRONMENT manually.

stderr | unknown test
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/api-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/rpc-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-augment/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-create/node_modules/@polkadot/util/
        esm 12.6.1      node_modules/@polkadot/types-codec/node_modules/@polkadot/util/
@polkadot/util-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 12.5.1      node_modules/@polkadot/util-crypto/
        esm 12.6.1      node_modules/@polkadot/types/node_modules/@polkadot/util-crypto/
@polkadot/wasm-crypto has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto/
@polkadot/wasm-bridge has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto/node_modules/@polkadot/wasm-bridge/
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-bridge/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-bridge/
@polkadot/wasm-crypto-wasm has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-crypto-init/node_modules/@polkadot/wasm-crypto-wasm/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-crypto-wasm/
@polkadot/wasm-util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
        esm 7.2.2       node_modules/@polkadot/wasm-util/
        esm 7.3.1       node_modules/@polkadot/types/node_modules/@polkadot/wasm-util/

 ✓ __tests__/useProxyAccount.test.tsx (20)
 ✓ __tests__/useProxyAccount.test.tsx (20)
 ✓ __tests__/useSchedulePayment.test.tsx (2)
 ✓ __tests__/useFeeEstimation.test.tsx (2)
 ✓ __tests__/proxyAccountsHelper.test.tsx (5)

 Test Files  4 passed (4)
      Tests  29 passed (29)
   Start at  23:51:25
   Duration  6.67s (transform 542ms, setup 1ms, collect 9.19s, tests 181ms, environment 2.10s, prepare 466ms)


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```
</details>

I tried on both Mac and Ubuntu and got the same result. Is this expected behavior at this point?

**Comment by pcorrado-np** [comment]
> Thanks @pcorrado-np much appreciated, figures it was something easy. The unit tests are running now but with warnings about conflicting node modules. It also seems to get stuck waiting for file changes:
> 
> Output
> I tried on both Mac and Ubuntu and got the same result. Is this expected behavior at this point?

Yes @keeganquigley, that is the expected behavior for `vitest` since it's running in watch mode. And the warnings about node modules for the Polkadot libraries are common and can be disregarded for now.

We have taken the opportunity to enhance the `README` by adding details on configuring the environment for local project execution.

Thanks for the feedback! Let us know if you have any other questions.

**Comment by keeganquigley** [comment]
Thanks @pcorrado-np for your quick responses! Everything is working now, great work! The app works great so far. Happy to pass the milestone, and here you can find my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tempora_1_keeganquigley.md). See you on the next one!

**Pull request merged**
