### PR TITLE
Add milestone delivery of AlgoCash

### PR DESCRIPTION
**Pull request by Dohkooo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Dohkooo** [comment]
@mmagician Thank you for your review and quick response. 

>The assets contract seems to be just a copy of the example erc20 contract with a few extra struct fields.

In asset contract, we added fn mint, burn and burn_from for the token utilities.

> The boardroom contract is a copy of the flipper example

We did not implement boardroom function in this milestone. We will do it in the next milestone.

> There are no meaningful unit tests in any of the contracts

Understand, we will add more unit tests.

> There is a mismatch between the deliverables for M1 in your contract and the ones stated in this PR

If possible, can we change the deliverables in our application contract? We found it's easier and more efficient to demostrate what we've done in the way stated in this PR.

**Comment by mmagician** [comment]
@Dohkooo You can submit a PR which will be reviewed by the Grants Committee.

Your documentation also isn't very informative at the moment. I find it difficult to link the different pieces of your application to the contract code that you've written. Perhaps you could be more explicit and point to different methods in your code in relation to the proposed mechanisms, such as: contractionary or expansionary policy, what are ALC/ALB/ALS. Also, you mention a distribution contract with the following functionality:
> Initial distribution of Algo Cash are done to those that deposit aUSD to the distribution contract. A total of 100,000 Algo Cash tokens are distributed to depositors, with 10,000 Cash tokens distributed per day. The amount of stablecoin deposits are limited to 20,000 tokens per account.

I could not find this anywhere.


> We did not implement boardroom function in this milestone. We will do it in the next milestone.

But your application only contains one milestone. The way it is structured at the moment, I had it understood that this functionality will form part of the 1st milestone delivery.

**Comment by Dohkooo** [comment]
We have a team disscussion. First we must apologize that we've delayed the milestone delivery. Our process was seriously affected by the COVID. And we need one more month to deliver Boradroom function and add more meanningful tests. 

Per talked in the [application PR](https://github.com/w3f/Open-Grants-Program/pull/217) and [Contract](https://github.com/w3f/Open-Grants-Program/blob/master/applications/AlgoCash.md#contract) list in the application contract, we will not deliver token distribution part. 

We will update this PR once we done the above along with the updated documentation and video if it sounds good to you. 

Thanks

**Comment by mmagician** [comment]
Ok, that sounds good. In this case, I will close this PR for now. Feel free to either re-open it once you're ready, or create a new one.

**Pull request closed without merging**
