### PR TITLE
Create logion_wallet-2.md

### PR DESCRIPTION
**Pull request by elisadba**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/627

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @elisadba! We will look into it as soon as possible.

**Review by semuelle — CHANGES_REQUESTED** [review]
Hi @elisadba. I am currently looking through all three deliverables. So far, it looks great. I only noticed two issues: (a) you haven't submitted any invoices yet and (b) this milestone is missing [deliverable 0e](https://github.com/w3f/Grants-Program/blob/32ce7e1b91ee2671a1c87d185da9deab9681aba6/applications/logion_wallet.md?plain=1#L353). Can you submit the invoices through [our invoices form](https://forms.gle/LSRr7PCjBpEbKGh89) and add 0e to this delivery?

**Comment by elisadba** [comment]
Hi Semuelle, thanks for the review. We will submit the invoices by the end of the week. Regarding deliverable 0e, we actually provided it during milestone 1, please find it here: https://medium.com/logion/the-legal-officer-based-social-recovery-of-the-logion-wallet-awarded-a-web3-foundation-grant-400b121b46b0

Sorry for the confusion, in fact we will write a second blogpost next week to prepare the announcement of the grant finalization with a summary of the last milestones. I notify you as soon as the invoices are sent. Thank you 🙏🏻

**Comment by semuelle** [comment]
Thanks for the update. Happy to hear you are publishing even more. I couldn't find a reference to the article in M1, but I added it here. The milestone is hereby accepted. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/logion-wallet_2_semuelle.md).

I still cannot find any invoices from you in our data, please let me know once you submitted them.

**Pull request merged**
