### PR TITLE
milestone-2 delivery of SEOR code-less smart contract platform

### PR DESCRIPTION
**Pull request by AKACoder**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/205

### CODE REVIEW

**Comment by semuelle** [comment]
ping @AKACoder

**Comment by AKACoder** [comment]
> Thanks for the update. I was able to run all Polkadot tests successfully. For the `web3-wrapper`, I now get
> 
> ```
> Chrome 95.0.4638 (Linux 0.0.0): Executed 36 of 36 (4 FAILED) (31.54 secs / 31.41 secs)
> TOTAL: 4 FAILED, 32 SUCCESS
> 
> 
> 1) Wallet installed getBlockFunction
>      getBlock
>      TypeError: Cannot read properties of null (reading 'number')
>     at test/index.js:98338:43
>     at Generator.next (<anonymous>)
>     at fulfilled (test/index.js:98318:58)
> 
> 2) Wallet installed getTransactionFunction
>      getTransaction
>      AssertionError: expected { Object (code, data, ...) } to deeply equal { Object (code, data, ...) }
>     at test/index.js:98504:46
>     at Generator.next (<anonymous>)
>     at fulfilled (test/index.js:98470:58)
> 
> 3) Wallet installed contract-call
>      loadContract
>      Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
>     at ABICoder../node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParametersWith (test/index.js:88809:15)
>     at ABICoder../node_modules/web3-eth-abi/lib/index.js.ABICoder.decodeParameters (test/index.js:88796:17)
>     at Contract../node_modules/web3-eth-contract/lib/index.js.Contract._decodeMethodReturn (test/index.js:90155:22)
>     at Method.outputFormatter (test/index.js:90445:42)
>     at Method../node_modules/web3-core-method/lib/index.js.Method.formatOutput (test/index.js:86757:54)
>     at sendTxCallback (test/index.js:87133:33)
>     at cb (test/index.js:85749:22)
>     at Item../node_modules/process/browser.js.Item.run (test/index.js:69311:14)
>     at drainQueue (test/index.js:69281:42)
> 
> 4) Wallet installed SignWithWallet
>      SignWithWallet
>      Invalid parameters: must provide an Ethereum address.
> ```
> 
> The browser console shows
> 
> ```
> RPC Error: invalid sender
> RPC Error: Invalid parameters: must provide an Ethereum address.
> RPC Error: Invalid parameters: must provide an Ethereum address.
> RPC Error: Invalid parameters: must provide an Ethereum address.
> ```
> 
> The `solana-wrapper` shows
> 
> ```
> ERROR in Entry module not found: Error: Can't resolve './get-selection-more.ts' in '/home/sebastian/work/w3f/code/grants/deliverables/SEOR/multi-chain-js/solana-wrapper'
> ℹ ｢wdm｣: Failed to compile.
> ```
> 
> right after start, and the tests mostly fail with one of these error messages:
> 
> ```
> TOTAL: 14 FAILED, 13 SUCCESS
> 
> 1) Wallet installed getAccountFunction
>      getAccount
>      TypeError: Cannot read properties of undefined (reading 'isPhantom')
>     at web3InstallisPhantom (test/index.js:38426:16)
> 
> 2) Wallet installed getBalanceFunction
>      getBalance
>      TypeError: Cannot read properties of undefined (reading 'isPhantom')
>     at web3Install (test/index.js:38417:16)
> ```
> 
> There is a commit titled "improve testing of solana-wrapper" in your `tronweb-wrapper` and `web3-wrapper` branches and commits titled "improve testing of tronweb-wrapper", "improve testing of web3 wrapper" and "improve testing of solana-wrapper" in your `main` branch, but not in the `tronweb-wrapper`, `web3-wrapper` or `solana-wrapper` branches. If all tests work from the `main` branch, please tell me so and remove the `checkouts` from the documentation.

Sorry for the late reply, we spend more time then we think on making our testing output more clarity.
We updated all the Testing guides in READMEs  and improved some of our testing print.
And we also removed the 'checkout' part in the guide due to all our released code and testing was merged to main branch.

This SDK are dependence on extension wallet such as  polkadot{.js} extension to interact with blockchain's RPC interface, so you need to install the extension wallet for different blockchain's testing.

[polkadot{.js} for Polkadot](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd)  
[MetaMask for Ethereum](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn)  
[Phantom for Solana](https://chrome.google.com/webstore/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa)  
[TronLink for Tron](https://chrome.google.com/webstore/detail/tronlink%EF%BC%88%E6%B3%A2%E5%AE%9D%E9%92%B1%E5%8C%85%EF%BC%89/ibnejdfjmmkpcnlpebklmnkoeoihofec)    


We also added these extension wallet  links in README files.

Please review again, thank you very much!

**Comment by semuelle** [comment]
Thanks for the update. I will test everything in the coming days. 

I just tried the example from the `example` folder and got this error message below. Can you check that that one is up to date as well?

```
❯ yarn run serve
yarn run v1.22.10
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 2 errors                                                                                18:17:06

These relative modules were not found:

* ./actions/index in ./node_modules/@sealsc/tronweb-wrapper/src/wrapper/wrapper.ts
* ./consts/consts in ./node_modules/@sealsc/tronweb-wrapper/src/wrapper/wrapper.ts
```

**Comment by AKACoder** [comment]
> Thanks for the update. I will test everything in the coming days.
> 
> I just tried the example from the `example` folder and got this error message below. Can you check that that one is up to date as well?
> 
> ```
> ❯ yarn run serve
> yarn run v1.22.10
> $ vue-cli-service serve
>  INFO  Starting development server...
> 98% after emitting CopyPlugin
> 
>  ERROR  Failed to compile with 2 errors                                                                                18:17:06
> 
> These relative modules were not found:
> 
> * ./actions/index in ./node_modules/@sealsc/tronweb-wrapper/src/wrapper/wrapper.ts
> * ./consts/consts in ./node_modules/@sealsc/tronweb-wrapper/src/wrapper/wrapper.ts
> ```

Sorry for this problem. We forgot to publish the newest npm package and update the version in package.json file of the example.
This problem was solved in the latest commit, please pull & review again, thanks.

**Comment by semuelle** [comment]
Thanks for the update, @AKACoder. Everything worked well. Your milestone is hereby accepted. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/seor_2_semuelle.md). 

Have you tested the libraries with other wallets? It would be handy to have a sort of compatibility table/list.

I will forward your invoice for processing.

**Comment by AKACoder** [comment]
> Thanks for the update, @AKACoder. Everything worked well. Your milestone is hereby accepted. Evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/seor_2_semuelle.md).
> 
> Have you tested the libraries with other wallets? It would be handy to have a sort of compatibility table/list.
> 
> I will forward your invoice for processing.

Great! Thank you for the review and such a good suggestion. 
We are indeed testing other wallets. We will continue to update the documentation and add a list of compatible wallets that have passed our test.

**Comment by RouvenP** [comment]
hi @AKACoder we transferred the payment for M2 today.

**Comment by AKACoder** [comment]
> hi @AKACoder we transferred the payment for M2 today.

Received, thank you!

**Pull request merged**
