### PR TITLE
Haskell Web3 Milestone 4

### PR DESCRIPTION
**Pull request by akru**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Open-Grants-Program/pull/15

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi Aleksandr,

thanks for the submission and the thorough work. I just pushed my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/55e627cfc437513ffd454eaec5d0af61a5f959cf/evaluations/hs-web3_4_semuelle.md) and your milestone is hereby accepted. :tada: 

I didn't find the testing guide on dockerhub until the very end, but I'm happy to report that manual testing worked as well. The only request I have is: could you publish a new release? I tried installing the package via stack, but then realised the last publication was in 2019.

I will forward your invoice for processing.

**Comment by akru** [comment]
Thank you very much @semuelle!

Yes, I plan to publish new release very soon, instead of all-in-one old version, the new version will consist of many dedicated packages. Polkadot support will be provided by web3-polkadot package.

**Comment by semuelle** [comment]
Great to hear. Good luck with your future endavours. Feel free to reach out again should the need for another grant arise.

**Comment by akru** [comment]
Hello @RouvenP, any updates on this?

**Comment by RouvenP** [comment]
hi @akru, the payment will be sent this Friday at the latest.

**Comment by RouvenP** [comment]
hi @akru we transferred the payment today.

**Pull request merged**
