### PR TITLE
Create SpellRouter_Milestone_M2.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2057

### CODE REVIEW

**Comment by dudo50** [comment]
We have noticed, that there has been another change to payments. And BTC is no longer available and our grant was accepted with BTC as a payment option. Please let us know if this needs changing so we can open PR in the grants repository to fix this. We want to switch to FIAT instead then (Please let us know what is needed also for this switch). We have for now not yet submitted an invoice due to this.

This is also mentioned in our milestone 1 delivery - https://github.com/w3f/Grant-Milestone-Delivery/pull/1081#issuecomment-1858548088

With kind regards,
Team ParaSpell

**Comment by semuelle** [comment]
> Please let us know if this needs changing so we can open PR in the grants repository to fix this.

Hey @dudo50. You don't have to change the payment details, as your grant was approved before the payment guidelines were changed. However, if you do wish to change it, you can still submit an amendment to the original contract. The instructions for payment details are in the application template.

**Comment by dudo50** [comment]
Hey @semuelle, 
As comment points out, this is resolved already with change from BTC to Fiat. Thanks for your time however!

With kind regards,
Team ParaSpell

**Review by takahser — CHANGES_REQUESTED** [review]
@dudo50 sorry for the delay here, we currently have a rather big backlog due to the holiday season.

When trying to install the dependencies on your _xcm-router_ repo, I'm getting an error:

```zsh
% yarn
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "@acala-network/eth-providers@2.7.5-1" is incompatible with requested version "@acala-network/eth-providers@~2.7.3"
[3/5] 🚚  Fetching packages...
warning Pattern ["@polkadot/api@latest"] is trying to unpack in the same destination "/Users/xxx/Library/Caches/Yarn/v6/npm-@polkadot-api-10.11.2-16cd07062d51cc9cf77a3a6afa3cb4e526e44a82-integrity/node_modules/@polkadot/api" as pattern ["@polkadot/api@^10.9.1","@polkadot/api@^10.9.1","@polkadot/api@10.11.2","@polkadot/api@^10.9.1","@polkadot/api@^10.9.1","@polkadot/api@^10.0.1","@polkadot/api@10.11.2","@polkadot/api@^10.11.1","@polkadot/api@^10.11.1","@polkadot/api@^10.7.3","@polkadot/api@^10.9.1"]. This could result in non-deterministic behavior, skipping.
info There appears to be trouble with your network connection. Retrying...
[4/5] 🔗  Linking dependencies...
warning " > @acala-network/eth-providers@2.7.5-1" has incorrect peer dependency "@acala-network/api@5.1.2-7".
warning "@acala-network/eth-providers > @acala-network/eth-transactions@2.7.5-1" has unmet peer dependency "@polkadot/util-crypto@^12.1.2".
warning "@acala-network/eth-providers > graphql-request@3.6.1" has incorrect peer dependency "graphql@14.x || 15.x".
warning " > @acala-network/sdk@4.1.9-12" has incorrect peer dependency "@acala-network/api@^5".
warning " > @acala-network/sdk@4.1.9-12" has unmet peer dependency "ethers@~5.7.0".
warning " > @acala-network/sdk-core@4.1.9-12" has unmet peer dependency "@acala-network/types@^6".
warning " > @acala-network/sdk-swap@4.1.9-12" has unmet peer dependency "@acala-network/types@^6".
warning "@crypto-dex-sdk/amm > @crypto-dex-sdk/currency@0.0.2" has unmet peer dependency "react-dom@^18.2.0".
warning "@crypto-dex-sdk/parachains-bifrost > @zenlink-types/bifrost > @open-web3/api-mobx@0.9.4-38" has incorrect peer dependency "@polkadot/api@5.*".
warning "@crypto-dex-sdk/parachains-bifrost > @zenlink-types/bifrost > @open-web3/orml-types@0.9.4-38" has incorrect peer dependency "@polkadot/api@5.*".
warning "@crypto-dex-sdk/parachains-bifrost > @zenlink-types/bifrost > @open-web3/orml-types@0.9.4-38" has incorrect peer dependency "@polkadot/typegen@5.*".
warning " > @crypto-dex-sdk/token-lists@0.0.2" has unmet peer dependency "@ethersproject/address@^5.7.0".
warning " > @crypto-dex-sdk/token-lists@0.0.2" has incorrect peer dependency "@crypto-dex-sdk/currency@0.0.2".
warning " > @crypto-dex-sdk/token-lists@0.0.2" has unmet peer dependency "@crypto-dex-sdk/format@0.0.2".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/api-augment@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/api-derive@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/rpc-augment@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/rpc-core@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/rpc-provider@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/types-augment@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/types-codec@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/types-create@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/types-known@^10.9.1".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/keyring@^12.3.2".
warning " > @galacticcouncil/sdk@1.1.1" has unmet peer dependency "@polkadot/util-crypto@^12.3.2".
warning " > @mangata-finance/sdk@2.1.2" has incorrect peer dependency "@polkadot/api@10.9.1".
warning "@mangata-finance/sdk > @mangata-finance/type-definitions@2.0.0" has incorrect peer dependency "@polkadot/types@10.9.1".
warning "@polkadot/apps-config > @polkadot/react-identicon@3.6.4" has unmet peer dependency "@polkadot/keyring@*".
warning "@polkadot/apps-config > @polkadot/react-identicon@3.6.4" has unmet peer dependency "@polkadot/util-crypto@*".
warning "@polkadot/apps-config > @polkadot/react-identicon@3.6.4" has unmet peer dependency "react-dom@*".
warning "@polkadot/apps-config > @polkadot/react-identicon@3.6.4" has unmet peer dependency "react-is@*".
warning "@polkadot/apps-config > @digitalnative/type-definitions > @polkadot/keyring@6.11.1" has incorrect peer dependency "@polkadot/util@6.11.1".
warning "@polkadot/apps-config > @digitalnative/type-definitions > @polkadot/keyring@6.11.1" has unmet peer dependency "@polkadot/util-crypto@6.11.1".
warning "@polkadot/apps-config > @polkadot/react-identicon > styled-components@6.1.2" has unmet peer dependency "react-dom@>= 16.8.0".
warning "@polkadot/apps-config > @snowfork/snowbridge-types > @polkadot/keyring@8.7.1" has incorrect peer dependency "@polkadot/util@8.7.1".
warning "@polkadot/apps-config > @snowfork/snowbridge-types > @polkadot/keyring@8.7.1" has unmet peer dependency "@polkadot/util-crypto@8.7.1".
warning "@polkadot/apps-config > pontem-types-bundle > @polkadot/keyring@7.9.2" has incorrect peer dependency "@polkadot/util@7.9.2".
warning "@polkadot/apps-config > pontem-types-bundle > @polkadot/keyring@7.9.2" has unmet peer dependency "@polkadot/util-crypto@7.9.2".
warning " > @typescript-eslint/eslint-plugin@6.15.0" has unmet peer dependency "@typescript-eslint/parser@^6.0.0 || ^6.0.0-alpha".
warning " > ts-node@10.9.2" has unmet peer dependency "@types/node@*".
[5/5] 🔨  Building fresh packages...
⠁ 
⠁ 
⠁ 
⠁ 
error /Users/xxx/repos/xcm-router/node_modules/@crypto-dex-sdk/chain: Command failed.
Exit code: 127
Command: pnpm run generate
Arguments: 
```

Any idea what could be the issue here? I'm using an M2 MacBook Pro.

**Comment by dudo50** [comment]
@takahser , thank you for your comment, we are going to check on this asap. 

With kind regards,
Team Paraspell

**Comment by dudo50** [comment]
@takahser , could you please send us the rest of the log (The text after Arguments, so we can identify where it does not work for you)? Just in case.. Do you have pnpm installed?

If I go manually to @crypto-dex-sdk/chains and try command pnpm run generate it works just fine.
Screenshot 2024-01-08 at 09 41 11

The build also completes without any issues for me on freshly downloaded code.
Screenshot 2024-01-08 at 09 44 15

**Comment by dudo50** [comment]
Hey @takahser, we were able to narrow down the issue and repair the external lib package. It should now work fine for you feel free to pull new commits via `git pull && git reset --hard` , **remove old node-modules, if any got installed** and use `yarn install` and it should work for you. Let us know if there is anything else.

With kind regards,
Team ParaSpell

**Comment by takahser** [comment]
@dudo50 thanks, that helped. I've made good progress, all the dependency installations, builds and tests can be run without any issues now. I've also added a [PR](https://github.com/paraspell/xcm-router/pull/7) that contains some fixes on your README. I'm currently smoke-testing the playground and writing up the evaluation, I'll be back soon with more feedback.

**Comment by dudo50** [comment]
Hey @takahser ,
Are there any news regarding evaluation of this milestone? 
Thanks for the information in advance.

With kind regards,
Team ParaSpell

**Comment by takahser** [comment]
@dudo50 sorry for the delay, last week I was busy with the Polkadot Blockchain Academy. I'm going to give you feedback by tomorrow Monday, EOD.

**Review by takahser — CHANGES_REQUESTED** [review]
@dudo50 thanks for your patience. I've added my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SpellRouter_2_takahser.md). I found 2 small things, other than that it LGTM! Feel free to have a look and ask questions, if there's anything unclear.

**Comment by dudo50** [comment]
Thanks for the feedback @takahser !
We will try to fix these asap and I will ping you afterwards.

With kind regards,
Team ParaSpell

**Comment by dudo50** [comment]
Hey, @takahser ,
We have just merged fixes that address the issues you pointed out.

Here is the PR that resolved the requested changes:  https://github.com/paraspell/xcm-router/pull/8

You can pull a new code and try Playground again.

The balance issue will now show just like other issues.
Screenshot 2024-01-23 at 16 48 28

The transfer types are now explained in the sidebar on the left. 
Screenshot 2024-01-23 at 16 48 32

**Review by takahser — APPROVED** [review]
@dudo50 thanks for the update, everything is fine now. Merging this, you can find the final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/SpellRouter_2_takahser.md).

**Comment by dudo50** [comment]
Hey @takahser ,
Could you please check status of payment (if everything is ok with the invoice)?  

We haven't received it yet.

Many thanks for your time.

With kind regards,
Team ParaSpell

**Comment by semuelle** [comment]
Hey @dudo50, your invoice will be processed today. Just fyi, it lists a due date of March 31st, which is why the invoice wasn't prioritized.

**Comment by dudo50** [comment]
Thanks for the information @semuelle .
We do this, to ensure, that there is enough time to process payment.

With kind regards,
Team ParaSpell

**Pull request merged**
