### PR TITLE
Hyperfridge Milestone 2

### PR DESCRIPTION
**Pull request by wasabrot**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2096

### CODE REVIEW

**Comment by wasabrot** [comment]
Hello - the author check is still failing; not sure why. As I understood, the merged hyperfridge.md must have same authors as this PR; we tried twice with wasabrot and wstrametz and still it fails, even if they are listed as authors. Can you give us a hint where to look? Maybe @keeganquigley ?

**Comment by semuelle** [comment]
> Hello - the author check is still failing; not sure why. As I understood, the merged hyperfridge.md must have same authors as this PR; we tried twice with wasabrot and wstrametz and still it fails, even if they are listed as authors.

Hi @wasabrot, thanks for the delivery and sorry for the inconvenience. I'm not sure why it's failing, but I can see that you are both authors of the application, so no need to fix it. Someone will look into the delivery soon.

**Comment by PieWol** [comment]
Hey @wasabrot ,
I see in your delivery that you are planning to change your milestones. This needs to be done with an amendment to the application itself. So please put up an amendment PR. [See here](https://grants.web3.foundation/docs/faq#i-found-one-of-my-deliverables-to-be-unnecessary-impossible-or-already-done-elsewhere-what-do-i-do)

**Comment by PieWol** [comment]
Hey @wasabrot ,
please update the links in your delivery. Most links are not pointing to actual files right now. Please ping me as soon as you changed them so I can continue the evaluation. Thanks!

**Comment by wasabrot** [comment]
> Hey @wasabrot , please update the links in your delivery. Most links are not pointing to actual files right now. Please ping me as soon as you changed them so I can continue the evaluation. Thanks!

Hi @PieWol  - fixed broken links, sorry for the blunder.

**Comment by PieWol** [comment]
Hey @wasabrot ,
I'm a little confused as these tests [here](https://github.com/element36-io/ebics-java-service/tree/main/src/test/java/io/element36/cash36/ebics) are all 3y old. Which is the correct dir for the tests you have created for this very milestone? If these are the tests you are using they are missing inline documentation. Here is my current  [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1173). Otherwise good job!

**Comment by wasabrot** [comment]
> Hey @wasabrot , I'm a little confused as these tests [here](https://github.com/element36-io/ebics-java-service/tree/main/src/test/java/io/element36/cash36/ebics) are all 3y old. Which is the correct dir for the tests you have created for this very milestone? If these are the tests you are using they are missing inline documentation. Here is my current [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/pull/1173). Otherwise good job!

Hi @PieWol - totally see your point! To give some background - we needed to integrate the ZK proof (which is tested in the risc-zero project), so no extra tests for that. And we wanted to only little change in the backend, so that we do not have to rewrite the OCW. But on top of this milestone we had to change the LibEuFin repo (the banking backend) and the proof generation a little, plus a small watchdog to trigger proof generation, which was not listed in the delivery. Bit more "flesh" will be in coming milestones, where we want to integrate the asset hub (@dastansam  is working on the amendment). Thx a lot!

**Comment by PieWol** [comment]
Ok, what about the aspect of the license? @wasabrot

**Comment by wasabrot** [comment]
> Ok, what about the aspect of the license? @wasabrot

Hi @PieWol  - we added inline comments to the unit tests. The licence is actually correct and apache 2, but the link in the milestone delivery document pointed to ebics-java-client instead of ebics-java-server. I fixed that in the milestone delivery document. So checkpoints 0a and 0b should be hopefully fine now. Thx a lot, Walter

**Comment by PieWol** [comment]
Got it, thanks @wasabrot .
Just fyi it looks like there is a typo in your whitepaper with x being defined twice :o
Bildschirm­foto 2024-05-07 um 11 17 54


Other than that thanks for adding inline documentation retroactively to these tests. I can see by the docker demo that the proving and verifying of receipts works but to be honest I have not quite understood how you manage to do this in a zero-knowledge way and at the same time be able to prove that everything is correct. E.g. the data from the bank was issued for the correct account holder. 

I can see that my lack of understanding would be more relevant in the evaluation of the first milestone, yet if somebody from your team would be happy to jump on a quick call and explain it to me I would greatly appreciate it :)

I have updated my evaluation so that  the delivery is now accepted. 🎉 
As for the call I wish for, how about you send me an invite to piet@web3.foundation?

**Comment by RouvenP** [comment]
hi @wasabrot we sent the payment last Friday

**Pull request merged**
