### PR TITLE
Nolik Milestone #1

### PR DESCRIPTION
**Pull request by amrbz**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/759

### CODE REVIEW

**Comment by takahser** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by amrbz** [comment]
Hi @takahser 
Thank you for the fast review!
Also, thank you so much for the help with the docs, highly appreciate it 👏🏻 
Will fix the mentioned issues as soon as possible.

**Comment by takahser** [comment]
Hi @amrbz 
I saw you pushed an update. Just wanted to check if the code is ready for another round of review.

**Comment by amrbz** [comment]
Hi @takahser 
No, not yet. I've just included the commit hashes for the current release to avoid confusion with the versions.
I'm about to push another commit with fixed issues. Thanks!

**Comment by amrbz** [comment]
Hi @takahser 
I've just updated [pallet-nolik](https://github.com/chainify/pallet-nolik/tree/699ed354f75056a434fa4554f38cee453380bc20) and [substrate-nolik-dev](https://github.com/chainify/substrate-nolik-dev/tree/6f51575cbf1eef2898ad1da0b0fece99d4a65ec6) repositories.
Thanks for the great [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/nolik_eval_1_takahser.md), it really helped a lot 👏🏻 

These updates include:
 - Test coverage for `AddressNotOwned` ([#1](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L123), [#2](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L140)) and `SameAddress` ([#1](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L93), [#2](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L108)) errors.
 - Description of [extrinsics](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/lib.rs#L114) functions.
 - Commit hashes to the [milestone delivery](https://github.com/w3f/Grant-Milestone-Delivery/pull/357/files) PR.

In addition, I've also included:
 - Ability to [add multiple owners](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/lib.rs#L123) to one address.
 - New error type [`AccountInOwners`](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/lib.rs#L48) which is covered with test [here](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L35).
 - New tests: [#1](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L16), [#2](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L25), [#3](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L36), and [#4](https://github.com/chainify/pallet-nolik/blob/699ed354f75056a434fa4554f38cee453380bc20/src/tests.rs#L52).

Docker images are also [updated](https://hub.docker.com/r/chainify/substrate-nolik-dev/tags) and now include version tags.

**Comment by takahser** [comment]
Hi @amrbz 
Thanks for the update, I'm glad my evaluation helped with improving your project. 👍
I'll look into the changes as soon as I can.

**Comment by takahser** [comment]
@amrbz thanks for your patience.
Good job on fixing the issues and thanks for so accurately documenting them in your previous comment! 👍
I'm happy with it now so I accepted your delivery, you can find my final evaluation here: https://github.com/w3f/Grant-Milestone-Delivery/blob/77bfec56a839f2aec1e8bf7a7b4d421462153039/evaluations/nolik_eval_1_takahser.md
Looking forward to M2!

**Review by takahser — APPROVED** [review]

**Pull request merged**
