### PR TITLE
Choko Wallet Milestone 1

### PR DESCRIPTION
**Pull request by RoyTimes**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1022

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @RoyTimes it will be a few days before someone can evaluate your milestone, but rest assured that we will look at it soon.

**Comment by semuelle** [comment]
Hi @RoyTimes. Thank you for your patience. I am currently reviewing your milestone. Two questions so far:

- What do you mean by "See codebase" on the documentation deliverable? I couldn't find any documents other than the `WalletRedux.md` file, and most of the code doesn't contain inline documentation. 
- When I add a custom network, I get a confirmation, but then it doesn't show up in the list of networks. Is that to be expected at this point?

**Comment by RoyTimes** [comment]
Hi @semuelle 

> * What do you mean by "See codebase" on the documentation deliverable? I couldn't find any documents other than the `WalletRedux.md` file, and most of the code doesn't contain inline documentation.

WalletRedux is a design doc. The SDK codebase has documentation and contains the logic for the wallet. Do you want us to include documentations on the React app as well? 

> * When I add a custom network, I get a confirmation, but then it doesn't show up in the list of networks. Is that to be expected at this point?

Yes. Like we said - the dashboard is unfinished. We allow customize network inside the SDK. Ref to the `known-network` package in SDK.

**Comment by semuelle** [comment]
Hey @RoyTimes. Sorry for the late reply here. 

> WalletRedux is a design doc. The SDK codebase has documentation and contains the logic for the wallet. Do you want us to include documentations on the React app as well?

In general, frontend code should be documented as well _where appropriate_ (don't feel obliged to document every single event), but in this case I was looking at the `request-handler` package and didn't see much inline documentation.

About the webapp:
- The "receive" QR code seems to be static,
- I cannot find the "email seed phrase" functionality.

Also, not significant since the UI is a WIP, but perhaps useful:
- It doesn't seem to make sense to ask for both the asset and the network to receive, at least for some networks.
- What is the purpose of the "minimum deposit" and "expected arrival confirmations"?
- It would be good to have at least _some_ kind of information that shows that I am seeing up-to-date data. For example, you could show the block number somewhere.
- I can sign messages and transactions on the sample dapp, but not on the webapp. I trust you will implement this for M2.

**Comment by RoyTimes** [comment]
Was traveling. Sorry for late reply. 

> In general, frontend code should be documented as well _where appropriate_ (don't feel obliged to document every single event), but in this case I was looking at the `request-handler` package and didn't see much inline documentation.

Ok. Let us get on it. Will also explain components and how they are used in frontend. 

> About the webapp:
> 
> * The "receive" QR code seems to be static,
Yes. It is made static to prevent alpha users to actually deposit tokens into their account. 

> * I cannot find the "email seed phrase" functionality. Is that functionality replaced with the encrypted encrypted version?
For now we are able to generate a link and click to recover 

> Also, not significant since the UI is a WIP, but perhaps useful:
> 
> * It doesn't seem to make sense to ask for both the asset and the network to receive, at least for some networks.

Make sense. We have it removed on the latest staging version. 

> * What is the purpose of the "minimum deposit" and "expected arrival confirmations"?
Kinda ref to other wallets for it. We should simplify this to typical Fast Slow or Normal for user to select. 

> * It would be good to have at least _some_ kind of information that shows that I am seeing up-to-date data. For example, you could show the block number somewhere.

Sure. Good idea. What we might do: fetch the most recent BlockNumber and stay that way until the user click refresh. 

> * I can sign messages and transactions on the sample dapp, but not on the webapp. I trust you will implement this for M2.

Hmmm.. What do you mean by sign message on the Webapp? Like a route for user to type in some arb message to sign?

We will make deliver a latest staging version this week - that implements some of these UI suggestions and include better documentation. 

Thanks for review and suggestions.

**Comment by semuelle** [comment]
> Hmmm.. What do you mean by sign message on the Webapp? Like a route for user to type in some arb message to sign?

Sorry, ignore that. I didn't notice that the signing request on the `test-request` page uses my Choko wallet. 

> We will make deliver a latest staging version this week - that implements some of these UI suggestions and include better documentation.

Thanks. Please ping me here when you're done.

**Comment by RoyTimes** [comment]
Hi @semuelle We are done with all changes. 

**Change list:**
Documentation: 
1. inline documentation for request-handlers
2. Some inline documentations for frontend, when the logic is a bit twisty. 

Func:
1. Latest version deployed at https://staging.choko.app When testing, simply attach `staging` at the beginning of the URL. We are not ready to push it to production as it contains breaking changes to the account storage and should warn existing users of it.(even though I don't think anyone is depositing real assets to it yet. )
2. The dashboard is mostly functional. It is able to fetch balance and price and render things correctly. We have added ETH support as well. Some UI components are `unimplemented!()`, mostly because it takes a bit time to do OR we unimplemented it for security reason for a not-production-ready software. 
3. Email seed phrase is not implemented but as I discussed earlier, it is able to render a QR code and a link. You may try to scan the QR code on your phone to import. Do you think asking users to take screenshots is a better way? As it won't be touching any centralized servers even if the seed is encrypted. 
4. we have remove `asking for network` on the Send button. As well as minimal deposit and estimated arrival time. 
5. We have not implemented the real-time balance yet OR a box displaying the current block number. Awaiting UI design. Should be there on the next release. 

Thanks for you patient. In the original milestone description, we promised a much simpler dashboard but guess we are delivering a bit more than that.

**Comment by RoyTimes** [comment]
@semuelle Thanks. I was traveling and just got back to base. Re-submitted the invoice. Thanks for reviewing.

**Comment by semuelle** [comment]
@RoyTimes, it looks like you submitted the same invoice again. There is still no postal address on the invoice. Please review.

**Comment by RoyTimes** [comment]
@semuelle Apologies. Resubmitted with my address. Thanks

**Pull request merged**
