### PR TITLE
Create Web3Go_Milestone_2.md

### PR DESCRIPTION
**Pull request by Moehringen**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1293 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by Moehringen** [comment]
This PR is the new one for https://github.com/w3f/Grant-Milestone-Delivery/pull/797 , the old one is closed by mistake and I cannot reopen it.  the required changes have been made. please reverify it again. thanks!

**Comment by keeganquigley** [comment]
@JosephKnecht-lab FYI we are working off of this PR now. Are you able to evaluate the changes?

**Comment by keeganquigley** [comment]
@Moehringen When I click on [End-to-End-Testing-for-local-build](https://web3go.notion.site/End-to-End-Testing-for-local-build-c544ecd080e6462ab423f3c2778fe8b1) I am just loading a blank page with a header. Can you double-check to make sure it was copied over correctly? Thank you!

**Comment by Moehringen** [comment]
It should be Ok now.

**Comment by JosephKnecht-lab** [comment]
Hi @keeganquigley, @Moehringen 

I have updated the evaluation document: https://github.com/w3f/Grant-Milestone-Delivery/pull/803. The status of the delivery is **Accepted** from my side, but **w3f** might have a different definition regarding the quality of the delivery. 

Few remarks from my side:

- The article has been published on Medium, so all items have been delivered with varying quality. 
- Some of the general improvements that I have suggested have not been implemented yet (fixing npm package vulnerabilities for example). 
- You are not using automated tests in your code. What you are doing is manual tests. In the original application, you are not stating if the tests should be made automated or manual, so I will accept the delivery from my side.  In the future, consider using automated testing tools such as [Cypress](https://www.cypress.io/). If you are not familiar with automated tests, please read this [article](https://www.browserstack.com/guide/manual-vs-automated-testing-differences) that goes over the benefits of automated testing. Your current testing guide explains how to run a single e2e test, that can be automated.

**Comment by Moehringen** [comment]
@JosephKnecht-lab Thanks so much!

**Comment by keeganquigley** [comment]
Thanks for the changes @Moehringen and the re-eval @JosephKnecht-lab

I like the site, and it's very useful! I was able to get through all of the manual test steps as well.

I do agree with Joseph that it would be good to implement e2e tests with Cypress, but seeing as it's not required, I'm happy to pass it.

**Comment by Moehringen** [comment]
Thanks so much! Finally, we have delivered this grant. 
Thank Web3 Foundation!

**Comment by Moehringen** [comment]
Yes, I have submitted a new one.

**Comment by RouvenP** [comment]
hi @Moehringen we transferred the payment today.

**Comment by Moehringen** [comment]
We have received it. thanks!

**Pull request merged**
