### PR TITLE
add Solang_Playground-milestone_1

### PR DESCRIPTION
**Pull request by salaheldinsoliman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/XXX < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by salaheldinsoliman** [comment]
@keeganquigley Here it is!

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the delivery @salaheldinsoliman I'm noticing the default deliverables (0a. - 0d.) are missing. I understand Docker and Article may not be applicable for this milestone but could you still add a Documentation/Testing sections with links? Thanks!

**Comment by keeganquigley** [comment]
Please also see my [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Solang_Playground_1_keeganquigley.md); at the moment there are some unit tests failing.

**Comment by keeganquigley** [comment]
pinging @salaheldinsoliman

**Comment by salaheldinsoliman** [comment]
@keeganquigley I'm currently working on a full-on test suit, that covers most of the functionality of the language server. I am also cleaning up the repo a little bit (removing warnings and improving documentation)

**Comment by keeganquigley** [comment]
@salaheldinsoliman sounds good thanks for the update!

**Comment by salaheldinsoliman** [comment]
@keeganquigley Hello,
I added a test suite for the language server and cleaned up the repo. please check: https://github.com/hyperledger-labs/solang-playground/blob/main/crates/browser/tests/server_tests.rs

With that being said, I request a re-evaluation of the delivery.
Thanks!

**Comment by keeganquigley** [comment]
Thanks for the changes @salaheldinsoliman looks good and I'm willing to accept the milestone. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Solang_Playground_1_keeganquigley.md). Looking forward to seeing compiling in the browser!

**Comment by salaheldinsoliman** [comment]
@keeganquigley Thanks!
I looked at the evaluation. FYI, this is the target repo now: https://github.com/hyperledger-labs/solang-playground
Please use that for future evaluations, I think there are no failing tests there

**Comment by semuelle** [comment]
@salaheldinsoliman, sorry for the delay. Your invoice should be processed on Monday latest.

**Comment by salaheldinsoliman** [comment]
That's okay, thanks for the update!

**Pull request merged**
