### PR TITLE
Add crossbow milestone 2 delivery

### PR DESCRIPTION
**Pull request by enfipy**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/668.

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @enfipy. We will look into it as soon as possible.

**Comment by alxs** [comment]
Hey @enfipy, I hope all is well! I had a quick look at your delivery and was wondering how the [Crossbow Permissions usage example](https://github.com/dodorare/crossbow/tree/v0.1.5/examples/macroquad-permissions) showcases cross-platform permissions? It seems to target Android specifically.

Also, the following installation command from the instructions doesn't seem to work:
```
crossbundle install sdk-manager --install "build-tools;30.0.0" "ndk;23.1.7779620" "platforms;android-30"

# or install preferred packages
# crossbundle install sdk-manager --preferred-tools
error: Found argument 'ndk;23.1.7779620' which wasn't expected, or isn't valid in this context

USAGE:
    crossbundle install sdk-manager [OPTIONS]

For more information try --help
```

The rest of the installation process worked like a charm though :)

**Comment by enfipy** [comment]
Hey @alxs, thanks, pretty well. I hope you are also doing well!

I updated Macroquad Permissions: added Camera and PhotoLibrary request permissions example. Also, documentation should be valid now. I hope you will not face any other problems, but if you will - please notify us, and we will fix it :)

**Comment by alxs** [comment]
Happ to hear that. I can't complain myself, thanks! :)

Thanks for the improvements, but looking into the code for the cross-platform permissions I noticed you just wrote the iOS side and the two permissions in the examples are the only two implemented https://github.com/dodorare/crossbow/pull/111/files#diff-d330bc768502f1fe4ef1cd09b72d05b17a62986d83eb20c858a7d8d28c4b0c6d. It's also not "a single cross-platform permission API" as the deliverable describes but rather two different APIs.

Could you please amend the application to describe what you implemented, or finish the implementation as the deliverable describes? Let me know if I'm missing anything.

By the way, I think the installation of the Android SDK either didn't properly set the environment variables or something else went wrong, because the following test didn't pass:

```
Starting gradle build process: example
Generating gradle project
test test_build_gradle ... FAILED

failures:

---- test_build_gradle stdout ----
thread 'test_build_gradle' panicked at 'called `Result::unwrap()` on an `Err` value: CrossbundleTools(Android(AndroidSdkNotFound))', crossbundle/cli/tests/build_gradle.rs:55:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_build_gradle

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.17s

error: test failed, to rerun pass '--test build_gradle'
```

**Comment by enfipy** [comment]
@alxs Thanks for your comment!

You were right, we've updated Permission API, and it looks way better now:
```rust
let result = Permission::Camera.request_async().await?;
```

You can find all supported Cross-Platform Permissions [here](https://github.com/dodorare/crossbow/blob/ba2d9a4c3c60ecc3e88b3e13ecdac7e84dbdd19e/src/permission/request_permission.rs#L10). Currently, we've added support of all Permissions that Xamarin [has](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android#available-permissions). And of course it would be ideal to add support of all functionality that Apple Frameworks provide as [Xamarin does](https://github.com/xamarin/xamarin-macios/tree/main/src) - but I think this one will be a little bit in the future ;)

About that error with running tests - we've updated Android SDK and NDK [lookup](https://github.com/dodorare/crossbow/blob/ba2d9a4c3c60ecc3e88b3e13ecdac7e84dbdd19e/crossbundle/tools/src/tools/android_ndk.rs#L327), and it will use Android SDK path that used by installation command. But tests might also require Java, Gradle, and bundletools - so you might need to install them as well.

P.S: I've created a bunch of tracking issues like this one: https://github.com/dodorare/crossbow/issues/117 or this https://github.com/dodorare/crossbow/issues/119. So I have some ideas on how to improve the developer experience even more.

**Comment by alxs** [comment]
Hey, thanks for such a quick response! The single API for both platforms does look MUCH cleaner. Could you also update the [documentation](https://github.com/dodorare/crossbow/blob/ba2d9a4c3c60ecc3e88b3e13ecdac7e84dbdd19e/docs/crossbow-permissions.md)?

> And of course, it would be ideal for adding support of all functionality that Apple Frameworks provide as [Xamarin does here](https://github.com/xamarin/xamarin-macios/tree/main/src) - but I think this one will be a little bit in the future ;)

Yep, that looks like a fair amount of work ;)

Great, that fixed the tests. I also had to install the Android rustup targets as you describe [here](https://github.com/dodorare/crossbow/blob/main/docs/install-linux-android.md#-install-necessary-rustup-targets). I wasn't sure which instructions I needed to follow since point 1 is either crossbundle _or_ Android Studio and then point 2 seems to describe the case where one chooses Android Studio. Also doesn't crossbundle take care of the environment variables, which would be the next section? Maybe you want to clarify these.

**Comment by enfipy** [comment]
Hey @alxs! I hope you're doing well, and thanks for pointing out those issues.

I've [updated](https://github.com/dodorare/crossbow/blob/v0.1.7/docs/src/crossbow/permissions.md) the documentation that you mentioned. And on top of that published a fancy website version of the documentation to https://crossbow.dodorare.com! So now it will be much prettier to read it. I also have some ideas on how to improve it even more but will make it over time.

Also, I updated the documentation regarding the emulator [here](https://crossbow.dodorare.com/install/android-linux.html#set-up-the-android-emulator). It should work (you probably will need to specify your desired system image for an arch).

Regarding the docker issue: I've changed the base of our Docker image to [androidsdk-30](https://hub.docker.com/r/androidsdk/android-30) and added a [CI test](https://github.com/dodorare/crossbow/blob/v0.1.7/.github/workflows/ci.yml#L71) that builds the image itself and then builds [macroquad-permissions](https://github.com/dodorare/crossbow/tree/v0.1.7/examples/macroquad-permissions) example. I hope it will also work on your side, and you will not face any other issues.

**Comment by alxs** [comment]
Thanks @enfipy! That new hosted documentation looks really great.

Great, that fixed the last issue I was having. With this, I'm happy to let you know the milestone is officially accepted! You can find my delivery notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/crossbow_2_alxs.md). I will notify the finance team to pay out your invoice - please allow for up to 2 weeks of processing time.

**Comment by fededubbi** [comment]
Hi,

Could you please update the invoice with our correct address?

Baarerstrasse 14,
6300, Zug.

Please, resend it to this email address: invoices@web3.foundation.

Many thanks,
Federica

**Comment by enfipy** [comment]
Hi @fededubbi!

Just sent the updated version to invoices@web3.foundation. Thank you for the quick response!

**Comment by enfipy** [comment]
Hi @fededubbi! Is everything good with the invoice? I hope there's everything in but if not - let us know. Thank you in advance.

**Comment by meldien** [comment]
Hi @enfipy - we booked the invoice and payout would be in the end of this week.

**Comment by enfipy** [comment]
Good evening! We can confirm that we receive the payment, thank you :)

**Pull request merged**
