### PR TITLE
Add Milestone 2 Delivery for Spacewalk

### PR DESCRIPTION
**Pull request by TorstenStueber**
Deliver spacewalk milestone 2

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/749

### CODE REVIEW

**Comment by alxs** [comment]
Hey @TorstenStueber, thank you for the delivery and sorry for the delay. I went ahead and did a preliminary evaluation of your delivery. Could you please address the issues in my [notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/spacewalk-bridge_2_alxs.md) and get back to me? Let me know if anything's unclear, or if you think I missed something.

**Comment by TorstenStueber** [comment]
Hey @alxs thanks a lot for the review. We addressed the issue with the [agent repository](https://github.com/pendulum-chain/stellar-experiments) (`stellar-experiments`) and greatly expanded the [documentation](https://github.com/pendulum-chain/stellar-experiments/blob/main/README.md) and added [tests](https://github.com/pendulum-chain/stellar-experiments/blob/main/README.md#test).

We actually intend to merge the repository `stellar-experiments` into the repository `spacewalk` but kept them separate as long as this milestones gets reviewed. That is also the reason why we originally did not bother to add more documentation and test to the `stellar-experiments` repository.

Let us know if you want us to take more action.

**Comment by alxs** [comment]
@TorstenStueber that makes sense, thanks for addressing it anyway and for your effort on this delivery in general. With this, I'm happy to let you know it's been accepted. I've updated my notes under the link above.

I'll notify the finance team to pay out your invoice. As usual, please allow for up to 14 days for processing.

**Comment by TorstenStueber** [comment]
Thanks a lot @alxs for the review and approval!

**Comment by RouvenP** [comment]
hi @TorstenStueber we transferred the payment today

**Pull request merged**
