### PR TITLE
Add Bright Treasury Milestone 1 description

### PR DESCRIPTION
**Pull request by aolszewska**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
I already looked into your delivery (see [my evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/bright_tresury-milestone_1_Noc2.md)). I have to say it looks great! Nice job. Could you create a pr to the open grants repo to amend the contract regarding “story 8”. Once the amendment is merge we can also accept the milestone delivery.

**Comment by Noc2** [comment]
I’m also sharing this with Raul Romanutti, who might be interested in this and could potentially provide additional feedback.

**Comment by bufta** [comment]
Thank you very much @Noc2 for your feedback. Glad to hear you liked what we've done so far. When it comes to the User story 8 ("As an idea owner, I can edit my ideas as long as the proposal is not closed (rejected or submitted).") the editing itself has been implemented (so the user can edit the Ideas), however we do not block the editing when the proposal is being closed as we are adding the History feature (with the recognition of "closed" proposals) in Milestone 3. Maybe we weren't clear with the description, apologies. Did you encounter any issues with the editing? Or is the editing without blocking when the proposal is closed not enough to add this story here?

**Comment by Noc2** [comment]
@bufta Sorry. I updated my evaluation. I was referring to the “as long as the proposal is not closed (rejected or submitted).” part with the “not implemented.” I suggest simply removing this in the original contract just for sanity. Could you create a PR for this? I’m pretty sure the committee will accept it immediately and then we can also merge your delivery.

**Comment by bufta** [comment]
@Noc2 thanks, we did as you suggested and already created the PR

**Comment by Noc2** [comment]
I’m happy to confirm that the milestone is officially accepted and I will forward your invoice internally. See https://github.com/w3f/Open-Grants-Program/pull/464

**Comment by bufta** [comment]
Great news! Thank you very much for the support @Noc2

**Comment by RouvenP** [comment]
hi @bufta we transferred the payment for milestone 1.

**Pull request merged**
