### PR TITLE
Myriad Social Milestone 1 Initial Deliverables Submission

### PR DESCRIPTION
**Pull request by gilangbh**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1795 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
pinging @gilangbh

**Comment by takahser** [comment]
@gilangbh I'm taking this delivery over, since @semuelle won't be available for the next two weeks. Please ping me here, once this delivery is ready to be reviewed again.

**Comment by gilangbh** [comment]
Hi @semuelle @takahser sorry for the delay. Please check the invite to our github org. You should be able to see the private repos now. Thank you.

**Comment by takahser** [comment]
@gilangbh is there any reason for not making them public? Note that for acceptance of the milestone they'll need to be open-sourced anyway.

**Comment by gilangbh** [comment]
> @gilangbh is there any reason for not making them public? Note that for acceptance of the milestone they'll need to be open-sourced anyway. Also, I still don't have access.

Hi Seraya, to be frank there is no reason to not make them public, and that's an oversight from our end. I have changed the visibility of both repos and I believe you can access them now.

**Comment by takahser** [comment]
@gilangbh great, now it works, thanks.
Will give you feedback on it as soon as I had the chance to have a closer look. 👍

**Review by takahser — CHANGES_REQUESTED** [review]
@gilangbh did you have the chance to look into the failing docker script? For me it failed as well:

```bash
~/myriad-node-parachain# ./.maintain/docker/start-docker-compose.sh
~/myriad-node-parachain ~/myriad-node-parachain
Starting docker compose
Creating volume "myriad-node_data" with default driver
Building node
[+] Building 34.2s (8/25)                                                                                                                              docker:default
 => [internal] load build definition from Dockerfile                                                                                                             0.1s
 => => transferring dockerfile: 1.55kB                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                                0.1s
 => => transferring context: 555B                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/debian:buster-20210816-slim@sha256:bdb7370812bd65a465f929fd8e61af294fe5988a954ea3c373511f125697603d           1.4s
 => [internal] load metadata for docker.io/paritytech/ci-linux:42a94a57-20220730@sha256:9666da1a0ad5f4d127e3cbd7fcf2aae0165a33ecff4fb0efd9baf03f24093483         1.6s
 => [runner 1/3] FROM docker.io/library/debian:buster-20210816-slim@sha256:bdb7370812bd65a465f929fd8e61af294fe5988a954ea3c373511f125697603d                      5.2s
 => => resolve docker.io/library/debian:buster-20210816-slim@sha256:bdb7370812bd65a465f929fd8e61af294fe5988a954ea3c373511f125697603d                             0.0s
 => => sha256:bdb7370812bd65a465f929fd8e61af294fe5988a954ea3c373511f125697603d 529B / 529B                                                                       0.0s
 => => sha256:5e8343a069dbd8b1d89005d7949ec52c858d6691b8b7b27c9f37415a5edf5931 1.48kB / 1.48kB                                                                   0.0s
 => => sha256:64ac1a72c06aa20e6c3b2e37ce66ddf902187eb683a427a477895f158a930e31 25.92MB / 25.92MB                                                                 2.3s
 => => extracting sha256:64ac1a72c06aa20e6c3b2e37ce66ddf902187eb683a427a477895f158a930e31                                                                        2.4s
 => CANCELED [chef 1/3] FROM docker.io/paritytech/ci-linux:42a94a57-20220730@sha256:9666da1a0ad5f4d127e3cbd7fcf2aae0165a33ecff4fb0efd9baf03f24093483            32.4s
 => => resolve docker.io/paritytech/ci-linux:42a94a57-20220730@sha256:9666da1a0ad5f4d127e3cbd7fcf2aae0165a33ecff4fb0efd9baf03f24093483                           0.0s
 => => sha256:9666da1a0ad5f4d127e3cbd7fcf2aae0165a33ecff4fb0efd9baf03f24093483 761B / 761B                                                                       0.0s
 => => sha256:71b0eec07d9ff48ffb9b7549d377d39a22c9720a5131b8449d36c20a3f7f2097 9.38kB / 9.38kB                                                                   0.0s
 => => sha256:ac2fb615420c18b61e0693f2569a3d38e3b9b58456b691bac44405e08389a591 27.14MB / 27.14MB                                                                 1.1s
 => => sha256:0406b5049860b8df0a4464bb9a17984c46256fe8946f4864984b71e25d8ab607 527.87MB / 527.87MB                                                              30.6s
 => => extracting sha256:ac2fb615420c18b61e0693f2569a3d38e3b9b58456b691bac44405e08389a591                                                                        2.2s
 => => sha256:9e248e436011fd2197cc0ce490e76c87b0695d826a175cb59b3992de3797243a 336.84MB / 336.84MB                                                              21.5s
 => => extracting sha256:0406b5049860b8df0a4464bb9a17984c46256fe8946f4864984b71e25d8ab607                                                                        1.5s
 => [internal] load build context                                                                                                                                0.5s
 => => transferring context: 8.65MB                                                                                                                              0.1s
 => ERROR [runner 2/3] RUN useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad &&   mkdir -p /home/myriad/.local/share &&   mkdir /data &&   chown -R myri  27.2s
------                                                                                                                                                                
 > [runner 2/3] RUN useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad &&   mkdir -p /home/myriad/.local/share &&   mkdir /data &&   chown -R myriad:myriad /data &&   ln -s /data /home/myriad/.local/share/myriad:
0.458 exec /bin/sh: exec format error
------
Dockerfile:28
--------------------
  27 |     # Create user and set ownership and permissions as required
  28 | >>> RUN useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad && \
  29 | >>>   # manage folder data
  30 | >>>   mkdir -p /home/myriad/.local/share && \
  31 | >>>   mkdir /data && \
  32 | >>>   chown -R myriad:myriad /data && \
  33 | >>>   ln -s /data /home/myriad/.local/share/myriad
  34 |     # Copy from builder stage
--------------------
ERROR: failed to solve: process "/bin/sh -c useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad &&   mkdir -p /home/myriad/.local/share &&   mkdir /data &&   chown -R myriad:myriad /data &&   ln -s /data /home/myriad/.local/share/myriad" did not complete successfully: exit code: 1
ERROR: Service 'node' failed to build : Build failed
```

**Comment by agustinustheo** [comment]
Hi @takahser @semuelle, my name is Theo. I'm one of the developers of Myriad Social. I've recently pushed a fix to the main branch. Please kindly take a look.

**Comment by takahser** [comment]
@agustinustheo it's still failing on my machine:

```zsc
myriad-node-parachain % ./.maintain/docker/start-docker-compose.sh
~/repos/myriad-node-parachain ~/repos/myriad-node-parachain
Starting docker compose
[+] Running 1/1
 ! node Warning                                                                                                                                                                         2.4s 
[+] Building 236.3s (22/29)                                                                                                                                             docker:desktop-linux
 => [node internal] load build definition from Dockerfile                                                                                                                               0.0s
 => => transferring dockerfile: 1.37kB                                                                                                                                                  0.0s
 => [node internal] load .dockerignore                                                                                                                                                  0.0s
 => => transferring context: 555B                                                                                                                                                       0.0s
 => [node internal] load metadata for docker.io/library/debian:buster-slim                                                                                                              2.5s
 => [node internal] load metadata for docker.io/paritytech/ci-linux:61d4fd50-20230713                                                                                                   2.2s
 => [node chef 1/3] FROM docker.io/paritytech/ci-linux:61d4fd50-20230713@sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4                                       35.3s
 => => resolve docker.io/paritytech/ci-linux:61d4fd50-20230713@sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4                                                  0.0s
 => => sha256:94ec252bb138516408d499a54bd40801d1c76e3e0182571a90bb138e86cce7e3 588.46MB / 588.46MB                                                                                     19.5s
 => => sha256:935ba62d5fdff39246cf9fca5697ae756bfdc34b2957c935254f447f1a296165 409.86MB / 409.86MB                                                                                     12.3s
 => => sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4 762B / 762B                                                                                              0.0s
 => => sha256:2d60a4916bc3faa064d298c966fd315dd26cd42fd54ec492ec238a99f649ca50 10.01kB / 10.01kB                                                                                        0.0s
 => => sha256:9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30 31.42MB / 31.42MB                                                                                        4.0s
 => => extracting sha256:9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30                                                                                               1.0s
 => => extracting sha256:94ec252bb138516408d499a54bd40801d1c76e3e0182571a90bb138e86cce7e3                                                                                              10.2s
 => => extracting sha256:935ba62d5fdff39246cf9fca5697ae756bfdc34b2957c935254f447f1a296165                                                                                               5.3s
 => [node internal] load build context                                                                                                                                                  0.1s
 => => transferring context: 8.65MB                                                                                                                                                     0.1s
 => [node runner 1/7] FROM docker.io/library/debian:buster-slim@sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7                                                 6.7s
 => => resolve docker.io/library/debian:buster-slim@sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7                                                             0.0s
 => => sha256:cf860b2a00d9a64c567b32c2c56b56afc2e2458e24a9251f4a5942fd601646d6 529B / 529B                                                                                              0.0s
 => => sha256:d0880dfa7d2f248a7ace2e7f9f9433ff476e93b1934746f1c81e5ca175a3bef2 1.48kB / 1.48kB                                                                                          0.0s
 => => sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7 984B / 984B                                                                                              0.0s
 => => sha256:466d0c81a91b4dea612f4d4bcbd480b8ee299558a2d50e93104c98a012e7975e 25.97MB / 25.97MB                                                                                        5.8s
 => => extracting sha256:466d0c81a91b4dea612f4d4bcbd480b8ee299558a2d50e93104c98a012e7975e                                                                                               0.9s
 => [node runner 2/7] RUN useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad                                                                                                       0.4s
 => [node runner 3/7] RUN mkdir -p /home/myriad/.local/share                                                                                                                            0.2s
 => [node runner 4/7] RUN mkdir /data                                                                                                                                                   0.1s
 => [node runner 5/7] RUN chown -R myriad:myriad /data                                                                                                                                  0.2s
 => [node runner 6/7] RUN ln -s /data /home/myriad/.local/share/myriad                                                                                                                  0.2s
 => [node chef 2/3] RUN cargo install cargo-chef --version 0.1.31                                                                                                                     141.7s
 => [node chef 3/3] WORKDIR /app                                                                                                                                                        0.0s 
 => [node planner 1/6] COPY ./node /app/node                                                                                                                                            0.0s 
 => [node planner 2/6] COPY ./pallets /app/pallets                                                                                                                                      0.0s 
 => [node planner 3/6] COPY ./runtime /app/runtime                                                                                                                                      0.0s 
 => [node planner 4/6] COPY ./Cargo.lock /app/Cargo.lock                                                                                                                                0.0s 
 => [node planner 5/6] COPY ./Cargo.toml /app/Cargo.toml                                                                                                                                0.0s 
 => [node planner 6/6] RUN cargo chef prepare --recipe-path recipe.json                                                                                                                 0.5s
 => [node builder 1/8] COPY --from=planner /app/recipe.json recipe.json                                                                                                                 0.0s
 => ERROR [node builder 2/8] RUN cargo chef cook --release --recipe-path recipe.json                                                                                                   56.2s
------                                                                                                                                                                                       
 > [node builder 2/8] RUN cargo chef cook --release --recipe-path recipe.json:                                                                                                               
1.571     Updating crates.io index                                                                                                                                                           
1.575     Updating git repository `https://github.com/paritytech/cumulus.git`
16.80     Updating git repository `https://github.com/paritytech/substrate`
56.00 thread 'main' panicked at 'Process terminated by signal', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-chef-0.1.31/src/recipe.rs:146:21
56.01 stack backtrace:
56.10    0: std::panicking::begin_panic
56.10    1: chef::recipe::Recipe::cook
56.10    2: cargo_chef::_main
56.10 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
------
failed to solve: process "/bin/sh -c cargo chef cook --release --recipe-path recipe.json" did not complete successfully: exit code: 101
```

**Review by takahser — CHANGES_REQUESTED** [review]
See [comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/1019#issuecomment-1775029380).

**Comment by agustinustheo** [comment]
> @agustinustheo it's still failing on my machine:
> 
> ```
> myriad-node-parachain % ./.maintain/docker/start-docker-compose.sh
> ~/repos/myriad-node-parachain ~/repos/myriad-node-parachain
> Starting docker compose
> [+] Running 1/1
>  ! node Warning                                                                                                                                                                         2.4s 
> [+] Building 236.3s (22/29)                                                                                                                                             docker:desktop-linux
>  => [node internal] load build definition from Dockerfile                                                                                                                               0.0s
>  => => transferring dockerfile: 1.37kB                                                                                                                                                  0.0s
>  => [node internal] load .dockerignore                                                                                                                                                  0.0s
>  => => transferring context: 555B                                                                                                                                                       0.0s
>  => [node internal] load metadata for docker.io/library/debian:buster-slim                                                                                                              2.5s
>  => [node internal] load metadata for docker.io/paritytech/ci-linux:61d4fd50-20230713                                                                                                   2.2s
>  => [node chef 1/3] FROM docker.io/paritytech/ci-linux:61d4fd50-20230713@sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4                                       35.3s
>  => => resolve docker.io/paritytech/ci-linux:61d4fd50-20230713@sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4                                                  0.0s
>  => => sha256:94ec252bb138516408d499a54bd40801d1c76e3e0182571a90bb138e86cce7e3 588.46MB / 588.46MB                                                                                     19.5s
>  => => sha256:935ba62d5fdff39246cf9fca5697ae756bfdc34b2957c935254f447f1a296165 409.86MB / 409.86MB                                                                                     12.3s
>  => => sha256:dc9abf9e877c5bad94828245406dac8a186530e1ad6a1b5f2072e5e19e1f64b4 762B / 762B                                                                                              0.0s
>  => => sha256:2d60a4916bc3faa064d298c966fd315dd26cd42fd54ec492ec238a99f649ca50 10.01kB / 10.01kB                                                                                        0.0s
>  => => sha256:9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30 31.42MB / 31.42MB                                                                                        4.0s
>  => => extracting sha256:9d21b12d5fab9ab82969054d72411ce627c209257df64b6057016c981e163c30                                                                                               1.0s
>  => => extracting sha256:94ec252bb138516408d499a54bd40801d1c76e3e0182571a90bb138e86cce7e3                                                                                              10.2s
>  => => extracting sha256:935ba62d5fdff39246cf9fca5697ae756bfdc34b2957c935254f447f1a296165                                                                                               5.3s
>  => [node internal] load build context                                                                                                                                                  0.1s
>  => => transferring context: 8.65MB                                                                                                                                                     0.1s
>  => [node runner 1/7] FROM docker.io/library/debian:buster-slim@sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7                                                 6.7s
>  => => resolve docker.io/library/debian:buster-slim@sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7                                                             0.0s
>  => => sha256:cf860b2a00d9a64c567b32c2c56b56afc2e2458e24a9251f4a5942fd601646d6 529B / 529B                                                                                              0.0s
>  => => sha256:d0880dfa7d2f248a7ace2e7f9f9433ff476e93b1934746f1c81e5ca175a3bef2 1.48kB / 1.48kB                                                                                          0.0s
>  => => sha256:bc2704bca194bb10ea0b52b4313dc44fc3339cc648457fb18cb3509e71f199b7 984B / 984B                                                                                              0.0s
>  => => sha256:466d0c81a91b4dea612f4d4bcbd480b8ee299558a2d50e93104c98a012e7975e 25.97MB / 25.97MB                                                                                        5.8s
>  => => extracting sha256:466d0c81a91b4dea612f4d4bcbd480b8ee299558a2d50e93104c98a012e7975e                                                                                               0.9s
>  => [node runner 2/7] RUN useradd -m -u 1001 -U -s /bin/sh -d /home/myriad myriad                                                                                                       0.4s
>  => [node runner 3/7] RUN mkdir -p /home/myriad/.local/share                                                                                                                            0.2s
>  => [node runner 4/7] RUN mkdir /data                                                                                                                                                   0.1s
>  => [node runner 5/7] RUN chown -R myriad:myriad /data                                                                                                                                  0.2s
>  => [node runner 6/7] RUN ln -s /data /home/myriad/.local/share/myriad                                                                                                                  0.2s
>  => [node chef 2/3] RUN cargo install cargo-chef --version 0.1.31                                                                                                                     141.7s
>  => [node chef 3/3] WORKDIR /app                                                                                                                                                        0.0s 
>  => [node planner 1/6] COPY ./node /app/node                                                                                                                                            0.0s 
>  => [node planner 2/6] COPY ./pallets /app/pallets                                                                                                                                      0.0s 
>  => [node planner 3/6] COPY ./runtime /app/runtime                                                                                                                                      0.0s 
>  => [node planner 4/6] COPY ./Cargo.lock /app/Cargo.lock                                                                                                                                0.0s 
>  => [node planner 5/6] COPY ./Cargo.toml /app/Cargo.toml                                                                                                                                0.0s 
>  => [node planner 6/6] RUN cargo chef prepare --recipe-path recipe.json                                                                                                                 0.5s
>  => [node builder 1/8] COPY --from=planner /app/recipe.json recipe.json                                                                                                                 0.0s
>  => ERROR [node builder 2/8] RUN cargo chef cook --release --recipe-path recipe.json                                                                                                   56.2s
> ------                                                                                                                                                                                       
>  > [node builder 2/8] RUN cargo chef cook --release --recipe-path recipe.json:                                                                                                               
> 1.571     Updating crates.io index                                                                                                                                                           
> 1.575     Updating git repository `https://github.com/paritytech/cumulus.git`
> 16.80     Updating git repository `https://github.com/paritytech/substrate`
> 56.00 thread 'main' panicked at 'Process terminated by signal', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-chef-0.1.31/src/recipe.rs:146:21
> 56.01 stack backtrace:
> 56.10    0: std::panicking::begin_panic
> 56.10    1: chef::recipe::Recipe::cook
> 56.10    2: cargo_chef::_main
> 56.10 note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ------
> failed to solve: process "/bin/sh -c cargo chef cook --release --recipe-path recipe.json" did not complete successfully: exit code: 101
> ```

Hey @takahser, I pushed a new build a day after your comment. Now, Myriad Social uses Substrate v1.2.0.

I've cleaned all the images and containers related to this and tried running everything from scratch and everything is downloading and building fine on my machine.

```
Step 3/32 : WORKDIR /app
 ---> Running in e172dab8aed4
Removing intermediate container e172dab8aed4
 ---> 4244b5bb92f5
Step 4/32 : FROM chef AS planner
 ---> 4244b5bb92f5
Step 5/32 : COPY ./node /app/node
 ---> 5eb982121d8a
Step 6/32 : COPY ./pallets /app/pallets
 ---> a23a73a04fc2
Step 7/32 : COPY ./runtime /app/runtime
 ---> d5cf2acbe36d
Step 8/32 : COPY ./Cargo.lock /app/Cargo.lock
 ---> a904b6330b5d
Step 9/32 : COPY ./Cargo.toml /app/Cargo.toml
 ---> c863a0ee2385
Step 10/32 : RUN cargo chef prepare --recipe-path recipe.json
 ---> Running in 69b1a2b0f0c5
Removing intermediate container 69b1a2b0f0c5
 ---> 1c9c5743bb7a
Step 11/32 : FROM chef AS builder
 ---> 4244b5bb92f5
Step 12/32 : COPY --from=planner /app/recipe.json recipe.json
 ---> d04acff1dfcd
Step 13/32 : RUN cargo chef cook --release --recipe-path recipe.json
 ---> Running in 4987ab317067
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/polkadot-sdk.git`
```

(**note it updates from the `polkadot-sdk` repository now instead of `cumulus` and `substrate`**)

Can you please pull the latest version and try again?

**Comment by agustinustheo** [comment]
image

We've tried to compile it on multiple devices, and it seems promising. No errors. Please pull the most recent commits and try again 😊

**Review by semuelle — CHANGES_REQUESTED** [review]
Hey @agustinustheo. Thanks for the updates. The image is building now (using commit 150f39e30716e80f842519a93fb0e1a3324859ce), but starting it fails with the following errors. Could you look into that?

```sh
Starting myriad-node-parachain ... done
Attaching to myriad-node-parachain
myriad-node-parachain | /usr/local/bin/myriad: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/bin/myriad)
myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/myriad)
myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/myriad)
myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /usr/local/bin/myriad)
myriad-node-parachain exited with code 1
```

**Comment by keeganquigley** [comment]
pinging @agustinustheo

**Comment by agustinustheo** [comment]
> Hey @agustinustheo. Thanks for the updates. The image is building now (using commit 150f39e30716e80f842519a93fb0e1a3324859ce), but starting it fails with the following errors. Could you look into that?
> 
> ```shell
> Starting myriad-node-parachain ... done
> Attaching to myriad-node-parachain
> myriad-node-parachain | /usr/local/bin/myriad: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /usr/local/bin/myriad)
> myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/myriad)
> myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /usr/local/bin/myriad)
> myriad-node-parachain | /usr/local/bin/myriad: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /usr/local/bin/myriad)
> myriad-node-parachain exited with code 1
> ```

Apologies for the late reply, let me take a look.

**Comment by agustinustheo** [comment]
Hi @semuelle @keeganquigley the team have found a solution and have pushed a fix: https://github.com/myriadsocial/myriad-node-parachain/commit/bd3fd3c7109e503bdfc184ef61bdb2e9cf6c9e3d

Please kindly re-review. Thank you for your patience.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the update, @gilangbh, but it's still not running. Now when I try to run the node using Docker, I get

```sh
> ./.maintain/docker/start-docker-compose.sh
~/myriad-social/myriad-node-parachain ~/myriad-social/myriad-node-parachain
Starting docker compose
Starting myriad-node-parachain ... done
Attaching to myriad-node-parachain
myriad-node-parachain | error: unexpected argument ' --dev' found
myriad-node-parachain exited with code 2
```

I tried fiddling around with the parameters, but nothing seems to help. I am on the main branch of the repo, if that makes a difference.

**Comment by agustinustheo** [comment]
> Thanks for the update, @gilangbh, but it's still not running. Now when I try to run the node using Docker, I get
> 
> ```shell
> > ./.maintain/docker/start-docker-compose.sh
> ~/myriad-social/myriad-node-parachain ~/myriad-social/myriad-node-parachain
> Starting docker compose
> Starting myriad-node-parachain ... done
> Attaching to myriad-node-parachain
> myriad-node-parachain | error: unexpected argument ' --dev' found
> myriad-node-parachain exited with code 2
> ```
> 
> I tried fiddling around with the parameters, but nothing seems to help. I am on the main branch of the repo, if that makes a difference.

Let me see what I can do.

**Comment by agustinustheo** [comment]
> Thanks for the update, @gilangbh, but it's still not running. Now when I try to run the node using Docker, I get
> 
> ```shell
> > ./.maintain/docker/start-docker-compose.sh
> ~/myriad-social/myriad-node-parachain ~/myriad-social/myriad-node-parachain
> Starting docker compose
> Starting myriad-node-parachain ... done
> Attaching to myriad-node-parachain
> myriad-node-parachain | error: unexpected argument ' --dev' found
> myriad-node-parachain exited with code 2
> ```
> 
> I tried fiddling around with the parameters, but nothing seems to help. I am on the main branch of the repo, if that makes a difference.

Hi @semuelle the team pushed a new fix here: https://github.com/myriadsocial/myriad-node-parachain/commit/737473bf60f5f8aa3b85e61480736a97853c9646

Can you please kindly do a re-review?

**Comment by Decentricity** [comment]
w3f team, please also highlight what we mentioned last week:

https://github.com/w3f/Grants-Program/pull/1795#issuecomment-1807360325

Note that we've actually finished Milestone 2 tasks as well (although we can't deliver until our chain is actually up), so once the block production issue is solved, we can deliver two milestones back to back.

Details are in the comment link above.

**Comment by semuelle** [comment]
Thanks for the update, the Docker is working now. 

> Please check the invite to our github org. You should be able to see the private repos now. Thank you.

https://github.com/myriadsocial/myriad-infrastructure is still private, @gilangbh/@agustinustheo.

**Comment by agustinustheo** [comment]
> Thanks for the update, the Docker is working now.
> 
> > Please check the invite to our github org. You should be able to see the private repos now. Thank you.
> 
> https://github.com/myriadsocial/myriad-infrastructure is still private, @gilangbh/@agustinustheo.

I opened to public.

**Comment by semuelle** [comment]
@Decentricity, could you send some MYRIA to 5DyWMh8kskJeHTTYsU4aWeqoNdtpMidikk4kBeGmhooqkP81 for testing?

**Comment by Decentricity** [comment]
@semuelle -- sent 
image

**Comment by gilangbh** [comment]
Thank you @semuelle for approving and merging the PR! Looking forward to solving our problem with Rococo.

**Pull request merged**
