### PR TITLE
zkwasm rollups transfer milestone 2

### PR DESCRIPTION
**Pull request by ashWhiteHat**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1487

### CODE REVIEW

**Comment by takahser** [comment]
@ashWhiteHat sorry for the delay here, we currently have a bit of a backlog. I've started the evaluation but haven't completed it yet, so far I didn't find any issues. I'll be back with the full report soon.

**Comment by ashWhiteHat** [comment]
Hi @takahser 
Thank you for the review.
Please take time 👍

**Review by takahser — CHANGES_REQUESTED** [review]
@ashWhiteHat thanks for your patience and sorry for the delay. Last week the Polkadot Blockchain Academy kept me busy, but today I've finally concluded the first round of review, see [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_2_takahser.md).
Essentially, the Tutorial could need some more details and I found some inconsistencies as well. LMK if you have any questions

**Comment by ashWhiteHat** [comment]
Hi @takahser 

Thank you for the review!

- I know it's just a simple Dockerfile that runs tests, but please add instructions on how to test it. Also, it'd have been nice to have a docker setup that allows to spin up a node which uses your nova pallet.

We assumed that developers setup the container through docker-compose.
According to your review, we added how to setup with docker.
https://github.com/KogarashiNetwork/Kogarashi?tab=readme-ov-file#test
I think we don't need node which uses your nova pallet because developers use our pallet by importing it to their node.
The way to import is the same with other pallet.

- in step 3 you mention that the tutorial is based on the [sum-storage](https://github.com/JoshOrndorff/recipes/blob/master/pallets/sum-storage/src/main.rs) pallet; I think it'd be better to mention it at the very beginning

This is good point!
We added description about dependent libraries and abstraction.
https://kogarashinetwork.github.io/tutorial/nova_pallet/

- in step 4 you mention TestRuntime and show the code found in recipes/pallets/sum-storage/src/tests.rs in the 1st code snippet, however, you print a different path: runtime/src/main.rs
- still in step 4, in the 2nd code snippet you print the same path again
- in step 5 you mention the /src/main.rs which doesn't exist neither within the sum-storage pallet nor the recipes repo
- similarly, in step 2 you mention the /src/main.rs which doesn't exist neither within the sum-storage pallet nor the recipes repo

Regarding pallet import, we aligned our notation with Substrate official documentation because most developer familiar with it.
https://docs.substrate.io/reference/how-to-guides/basics/import-a-pallet/
We added description that our notation is aligned with Substrate pallet import tutorial and put its reference.

We also added full example of tutorial and put its link on the top.
https://github.com/KogarashiNetwork/Kogarashi/tree/master/sample

I would appreciate it if you could confirm.
Thank you!

**Review by takahser — CHANGES_REQUESTED** [review]
@ashWhiteHat thanks for the updates, that's helpful.

However, the docker compose setup didn't work for me:

```zsh
Kogarashi % docker compose up
[+] Running 1/0
 ✔ Container nova  Created                                                                                                       0.0s 
Attaching to nova
nova  |     Finished release [optimized + debuginfo] target(s) in 0.59s
nova  |      Running unittests src/lib.rs (/app/target/release/deps/zk_storage-e36e0c6c09af8122)
nova  | 
nova  | running 3 tests
nova  | test tests::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
nova  | test tests::default_sum_zero ... ok
nova  | error: test failed, to rerun pass `--lib`
nova  | 
nova  | Caused by:
nova  |   process didn't exit successfully: `/app/target/release/deps/zk_storage-e36e0c6c09af8122` (signal: 9, SIGKILL: kill)
nova exited with code 101
```

Also, thanks for adding the [sample project](https://github.com/KogarashiNetwork/Kogarashi/tree/master/sample) and improving the Tutorial. Could you add instructions on how to run it as well as explain, whether steps 4-6 of the tutorial are covered by the sample project?

**Comment by ashWhiteHat** [comment]
Hi @takahser 
Thank you for the polite review.
We modified according to your review.

> However, the docker compose setup didn't work for me:

It was the problem of allocated memory for docker.
We reduced memory for container and fixed this.

> Could you add instructions on how to run it as well as explain, whether steps 4-6 of the tutorial are covered by the sample project?

Sorry for inconvenient.
We updated tutorial as follows.

- Put corresponding sample code link on file path
- Separate client implementation part (4. Define the function for IVC verification)
- Put how to import pallet tutorial link on footer

Now, tutorial file path corresponds sample implementation and description follows development process.

I would appreciate it if you could confirm.
Thank you!

**Review by takahser — CHANGES_REQUESTED** [review]
@ashWhiteHat sorry for the delay here. I've pulled the latest changes, but I'm still getting the same error as before.

```zsh
% git rev-parse HEAD
dc1450971ccfd35b9d337a8d9f7bc997cbe02d89

% docker compose up
[+] Running 1/0
 ✔ Container nova  Created                                                                                                                                                                             0.0s 
Attaching to nova
nova  |     Finished release [optimized + debuginfo] target(s) in 0.63s
nova  |      Running unittests src/lib.rs (/app/target/release/deps/zk_storage-e36e0c6c09af8122)
nova  | 
nova  | running 3 tests
nova  | test tests::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
nova  | test tests::default_sum_zero ... ok
nova  | error: test failed, to rerun pass `--lib`
nova  | 
nova  | Caused by:
nova  |   process didn't exit successfully: `/app/target/release/deps/zk_storage-e36e0c6c09af8122` (signal: 9, SIGKILL: kill)
nova exited with code 101
```

Regarding my memory (RAM), at the time of running I had 15GB of free space and docker used around an additional 8GB of space.

Thx for updating and improving the tutorial along with the sample app, I'm fine with that part now. I've updated the [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_2_takahser.md) accordingly.

**Comment by ashWhiteHat** [comment]
Hi @takahser 
Thank you for the review.

I optimized hash memory performance.
https://github.com/KogarashiNetwork/Kogarashi/pull/191

In Github Actions and my local environment, it passed the tests.
Could you run `cargo test --release` on [`sample`](https://github.com/KogarashiNetwork/Kogarashi/tree/master/sample) directory if it fail to pass tests on docker?

I would appreciate it if you could confirm.
Thank you.

**Comment by takahser** [comment]
@ashWhiteHat when running them manually, they pass, see here: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_2_takahser.md#documentation

**Comment by ashWhiteHat** [comment]
@takahser 
Thank you for the check.

Doesn't docker test pass?

**Comment by ashWhiteHat** [comment]
Hi @takahser 

Is everything okay?
I would like to know the current status.

**Comment by takahser** [comment]
@ashWhiteHat again, the [docker issue](https://github.com/w3f/Grant-Milestone-Delivery/pull/1092#pullrequestreview-1871740569) hasn't been resolved, yet. Once this is fixed, I'll approve the delivery.
If you're not sure how to fix it on my machine, we can also schedule a [call](https://calendar.app.google/na56ea5ZX5cPL7yB8) and run it on your machine instead.

**Comment by ashWhiteHat** [comment]
Thank you for the providing the schedule.
I booked your schedule!
I am looking forward to seeing you.

**Comment by ashWhiteHat** [comment]
Hi @takahser 

How about trying to run docker container on Github Actions?
Is that okay?

**Comment by ashWhiteHat** [comment]
Thank you for the call.
This is the output of command.

```
➜  Kogarashi git:(master) dcom up
Starting nova ... done
Attaching to nova
nova    |     Finished release [optimized] target(s) in 0.82s
nova    |      Running unittests src/lib.rs (target/release/deps/zk_storage-e18c6ff412cf73a5)
nova    | 
nova    | running 3 tests
nova    | test tests::__construct_runtime_integrity_test::runtime_integrity_tests ... ok
nova    | test tests::default_sum_zero ... ok
nova    | test tests::sums_thing_one has been running for over 60 seconds
nova    | test tests::sums_thing_one ... ok
nova    | 
nova    | test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 107.26s
nova    | 
nova    |    Doc-tests zk-storage
nova    | 
nova    | running 0 tests
nova    | 
nova    | test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
nova    | 
nova exited with code 0
```

I would appreciate it if you could confirm.
Thank you!

**Review by takahser — APPROVED** [review]
@ashWhiteHat thanks for your time and efforts, your delivery has been accepted. You can find the final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zkwasm-rollups-transfer_2_takahser.md).

**Comment by semuelle** [comment]
@ashWhiteHat, have you submitted an invoice for this milestone?

**Comment by ashWhiteHat** [comment]
@semuelle 
Yes, I have submitted last week.

**Comment by semuelle** [comment]
Found it. My bad.

**Comment by RouvenP** [comment]
hi @ashWhiteHat we sent the payment today

**Comment by ashWhiteHat** [comment]
Hi @RouvenP 
Thank you for the notification.
I confirmed it!

**Pull request merged**
