### PR TITLE
Create Substats-Milestone_2.md

### PR DESCRIPTION
**Pull request by heipowerman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1153 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @heipowerman, thanks for the delivery! Someone of the team will look into it as soon as possible.

**Comment by 0xCaso** [comment]
Here I am. I'm playing around with the API to test the backend, and I've noticed that the database rows seem to be duplicated.

For example, with `POST localhost:8080/api/dbcommon/detail`, I input the following bodies and get the relative results (in this example, with the `block_info` field):

```bash
body:

{
  "tableName": "block_info",
  "id": 1
}

result:

{
    "msg": "ok",
    "data": {
        "id": 1,
        "hash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "signerAccount": null,
        "parentHash": "0xa4e43eec39eec00a79d5f35f69a28bdc7fb92b73479f3992655a463c3e2aa017",
        "blockHeight": 13780000,
        "txCount": 3,
        "eventCount": 34,
        "timestamp": 1673590368015
    }
}
```

```bash
body:

{
  "tableName": "block_info",
  "id": 2
}

result:

{
    "msg": "ok",
    "data": {
        "id": 2,
        "hash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "signerAccount": null,
        "parentHash": "0xa4e43eec39eec00a79d5f35f69a28bdc7fb92b73479f3992655a463c3e2aa017",
        "blockHeight": 13780000,
        "txCount": 3,
        "eventCount": 34,
        "timestamp": 1673590368015
    }
}
```

```bash
body:

{
  "tableName": "block_info",
  "id": 3
}

result:

{
    "msg": "ok",
    "data": {
        "id": 3,
        "hash": "0x30ab43a9818486c04179d14e11d2a30e8a7528c10269b0147efb941a7875026a",
        "signerAccount": null,
        "parentHash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "blockHeight": 13780001,
        "txCount": 2,
        "eventCount": 29,
        "timestamp": 1673590374000
    }
}
```

```bash
body:

{
  "tableName": "block_info",
  "id": 4
}

result:

{
    "msg": "ok",
    "data": {
        "id": 4,
        "hash": "0x30ab43a9818486c04179d14e11d2a30e8a7528c10269b0147efb941a7875026a",
        "signerAccount": null,
        "parentHash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "blockHeight": 13780001,
        "txCount": 2,
        "eventCount": 29,
        "timestamp": 1673590374000
    }
}
```
You can see that between ids 1 and 2, and then 3 and 4, the only value that changes is the `id`, all the rest (`hash`, `blockHeight`, ...) doesn't change so I assume this is duplicate as long as you did this on purpose / I'm missing something.

I've seen the same behaviour with the `block_transaction` field and `block_account` (in this case, slightly different but should be duplicated).

You can see it also querying the same table in a different way with `POST localhost:8080/api/dbcommon/list`:

```
body:

{
  "tableName": "block_info",
  "pageindex": 1,
  "pagesize": 4
}

result:

{
    "msg": "ok",
    "data": [{
        "id": 4456,
        "hash": "0xcdc8a49c547506c98381343c9409ce02157c20b43f3248c3c054ab040f43bd7f",
        "signerAccount": null,
        "parentHash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "blockHeight": 13782227,
        "txCount": 3,
        "eventCount": 39,
        "timestamp": 1673603742015
    }, {
        "id": 4455,
        "hash": "0xcdc8a49c547506c98381343c9409ce02157c20b43f3248c3c054ab040f43bd7f",
        "signerAccount": null,
        "parentHash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "blockHeight": 13782227,
        "txCount": 3,
        "eventCount": 39,
        "timestamp": 1673603742015
    }, {
        "id": 4454,
        "hash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "signerAccount": null,
        "parentHash": "0xf918d9a2a097aa774fdd185bebe26464d49e9425a3d442b03006595874d4d77f",
        "blockHeight": 13782226,
        "txCount": 2,
        "eventCount": 28,
        "timestamp": 1673603736000
    }, {
        "id": 4453,
        "hash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "signerAccount": null,
        "parentHash": "0xf918d9a2a097aa774fdd185bebe26464d49e9425a3d442b03006595874d4d77f",
        "blockHeight": 13782226,
        "txCount": 2,
        "eventCount": 28,
        "timestamp": 1673603736000
    }],
    "dangerous": [],
    "pageindex": 1,
    "pagesize": 4,
    "total": 4456
}
```
Note: I just thought that maybe it's an issue related to the RPC. I'm using the RPC wss://rococo-contracts-rpc.polkadot.io.

**Review by 0xCaso — COMMENTED** [review]
Here I am. I'm playing around with the API to test the backend, and I've noticed that the database rows seem to be duplicated.

For example, with `POST localhost:8080/api/dbcommon/detail`, I input the following bodies and get the relative results (in this example, with the `block_info` field):

```JSON
body:

{
  "tableName": "block_info",
  "id": 1
}

result:

{
    "msg": "ok",
    "data": {
        "id": 1,
        "hash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "signerAccount": null,
        "parentHash": "0xa4e43eec39eec00a79d5f35f69a28bdc7fb92b73479f3992655a463c3e2aa017",
        "blockHeight": 13780000,
        "txCount": 3,
        "eventCount": 34,
        "timestamp": 1673590368015
    }
}
```

```JSON
body:

{
  "tableName": "block_info",
  "id": 2
}

result:

{
    "msg": "ok",
    "data": {
        "id": 2,
        "hash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "signerAccount": null,
        "parentHash": "0xa4e43eec39eec00a79d5f35f69a28bdc7fb92b73479f3992655a463c3e2aa017",
        "blockHeight": 13780000,
        "txCount": 3,
        "eventCount": 34,
        "timestamp": 1673590368015
    }
}
```

```JSON
body:

{
  "tableName": "block_info",
  "id": 3
}

result:

{
    "msg": "ok",
    "data": {
        "id": 3,
        "hash": "0x30ab43a9818486c04179d14e11d2a30e8a7528c10269b0147efb941a7875026a",
        "signerAccount": null,
        "parentHash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "blockHeight": 13780001,
        "txCount": 2,
        "eventCount": 29,
        "timestamp": 1673590374000
    }
}
```

```JSON
body:

{
  "tableName": "block_info",
  "id": 4
}

result:

{
    "msg": "ok",
    "data": {
        "id": 4,
        "hash": "0x30ab43a9818486c04179d14e11d2a30e8a7528c10269b0147efb941a7875026a",
        "signerAccount": null,
        "parentHash": "0x79e56ac0f09b959c174f54ca1f0a37c65f59bdeadc247edeb465627845fa00c5",
        "blockHeight": 13780001,
        "txCount": 2,
        "eventCount": 29,
        "timestamp": 1673590374000
    }
}
```
You can see that between ids 1 and 2, and then 3 and 4, the only value that changes is the `id`, all the rest (`hash`, `blockHeight`, ...) doesn't change so I assume this is duplicate as long as you did this on purpose / I'm missing something.

I've seen the same behaviour with the `block_transaction` field and `block_account` (in this case, slightly different but should be duplicated).

You can see it also querying the same table in a different way with `POST localhost:8080/api/dbcommon/list`:

```JSON
body:

{
  "tableName": "block_info",
  "pageindex": 1,
  "pagesize": 4
}

result:

{
    "msg": "ok",
    "data": [{
        "id": 4456,
        "hash": "0xcdc8a49c547506c98381343c9409ce02157c20b43f3248c3c054ab040f43bd7f",
        "signerAccount": null,
        "parentHash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "blockHeight": 13782227,
        "txCount": 3,
        "eventCount": 39,
        "timestamp": 1673603742015
    }, {
        "id": 4455,
        "hash": "0xcdc8a49c547506c98381343c9409ce02157c20b43f3248c3c054ab040f43bd7f",
        "signerAccount": null,
        "parentHash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "blockHeight": 13782227,
        "txCount": 3,
        "eventCount": 39,
        "timestamp": 1673603742015
    }, {
        "id": 4454,
        "hash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "signerAccount": null,
        "parentHash": "0xf918d9a2a097aa774fdd185bebe26464d49e9425a3d442b03006595874d4d77f",
        "blockHeight": 13782226,
        "txCount": 2,
        "eventCount": 28,
        "timestamp": 1673603736000
    }, {
        "id": 4453,
        "hash": "0x7c9693d1623982546737215bcbefb417b33a5f09644997c4fb475b764c185eef",
        "signerAccount": null,
        "parentHash": "0xf918d9a2a097aa774fdd185bebe26464d49e9425a3d442b03006595874d4d77f",
        "blockHeight": 13782226,
        "txCount": 2,
        "eventCount": 28,
        "timestamp": 1673603736000
    }],
    "dangerous": [],
    "pageindex": 1,
    "pagesize": 4,
    "total": 4456
}
```
Note: I just thought that maybe it's an issue related to the RPC. I'm using the RPC wss://rococo-contracts-rpc.polkadot.io.

**Comment by heipowerman** [comment]
@0xCaso Thank you for finding the problem.The reason is that there is a bug when switching between different chains.We have fixed it and updated the code, please check it.If you have any questions, please let me know.

**Review by 0xCaso — APPROVED** [review]
Thanks a lot for the update @heipowerman. I'm accepting the delivery and sharing with the team.

**Review by Noc2 — APPROVED** [review]

**Comment by 0xCaso** [comment]
@heipowerman The milestone has been accepted, congrats! 

I kindly ask you one last thing: recently we changed our guidelines, and I would ask you if it's possible to change USDT on Ethereum as payment method to another option choosable from [here](https://github.com/w3f/Grants-Program#pencil-process) (so if you want to stay with Ethereum you should change it to USDC or DAI).

If yes, it would be great if you could resend the invoice changing the currency, and also adding the VAT Amount, which is 0.

**Comment by heipowerman** [comment]
@0xCaso Thanks a lot for the review. We have submitted a new invoice that changed USDT on Ethereum to USDC. I hope the above is useful to you.

**Comment by 0xCaso** [comment]
@heipowerman thanks, but you forgot the VAT Amount I was mentioning in the comment:

> If yes, it would be great if you could resend the invoice changing the currency, and also adding the VAT Amount, which is 0.

Also, you should use the same address that you put in the [application document](https://github.com/w3f/Grants-Program/blob/master/applications/substats.md). If you want to change it, you should amend the grant, opening a PR to edit the address.

**Comment by heipowerman** [comment]
@0xCaso  Thanks for reminding. We have been added the VAT Amount in the invoice, and amended application document. Please let me know if you need anything else.

**Comment by 0xCaso** [comment]
Thanks a lot, but I'm sorry I didn't notice that you changed the payment address. It must be the same of the one you provided in the application document, and if you want to change it you have to amend the grant (open a PR to change the address in the application document).

**Comment by 0xCaso** [comment]
@heipowerman Thanks for that! We will forward the invoice as soon as the amendment gets merged. We need a confirm by @swowk in the PR as suggested [here](https://github.com/w3f/Grants-Program/pull/1509#pullrequestreview-1284728926)

**Comment by 0xCaso** [comment]
@heipowerman as the [amendment](https://github.com/w3f/Grants-Program/pull/1509) got merged, I've forwarded the invoice internally, and the payment should happen within 14 days. Thanks!

**Comment by RouvenP** [comment]
hi @heipowerman we transferred the payment today.

**Comment by heipowerman** [comment]
@RouvenP Thanks !

**Pull request merged**
