### PR TITLE
Ink Explorer - Backend - Milestone 1

### PR DESCRIPTION
**Pull request by 0xslipk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1052 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by takahser** [comment]
@0xslipk thanks for your delivery. We're going to take a look at it as soon as we can.

**Comment by 0xslipk** [comment]
> @0xslipk thanks for your delivery. We're going to take a look at it as soon as we can.

Awesome thank you.

**Comment by 0xCaso** [comment]
Hi @0xslipk! I'm an external evaluator, and I'm starting the evaluation process. I'll reach out with questions if any. Thanks a lot!

**Comment by 0xslipk** [comment]
> ###

**Comment by 0xslipk** [comment]
> Hi @0xslipk! I'm an external evaluator, and I'm starting the evaluation process. I'll reach out with questions if any. Thanks a lot!

Perfect lets us know if you need any help.

**Comment by 0xCaso** [comment]
I'm back @0xslipk! Here (https://github.com/w3f/Grant-Milestone-Delivery/pull/578) you can find the evaluation file I've started to write: https://github.com/w3f/Grant-Milestone-Delivery/blob/994b86d957d8618d89c0b9efa2008c31df6c035f/evaluations/ink-explorer_1_0xCaso.md

Basically, I managed to run locally the software and the tests, and everything goes fine except for some (I guess)
minor things I pointed out in the above file.

I kindly ask you to read every point of the evaluation and integrate, where needed, the documentation. Feel free to answer in this discussion the questions I've written or ask me for any clarifications about them!

**Comment by 0xslipk** [comment]
> I'm back @0xslipk! Here (#578) you can find the evaluation file I've started to write: https://github.com/w3f/Grant-Milestone-Delivery/blob/994b86d957d8618d89c0b9efa2008c31df6c035f/evaluations/ink-explorer_1_0xCaso.md
> 
> Basically, I managed to run locally the software and the tests, and everything goes fine except for some (I guess) minor things I pointed out in the above file.
> 
> I kindly ask you to read every point of the evaluation and integrate, where needed, the documentation. Feel free to answer in this discussion the questions I've written or ask me for any clarifications about them!

Thanks for review. We are gonna take a look and circle back to you.

**Comment by 0xslipk** [comment]
@0xCaso regarding "Deliverable 0e. Article can be found (it is a Twitter post). Maybe it hasn't been included because it's not been published yet.". We are gonna publish an article on Medium after we completed the Grant.

**Comment by 0xslipk** [comment]
@0xCaso we addressed your comments on [e98a28d](https://github.com/blockcoders/ink-substrate-explorer-api/commit/e98a28d4283fbe37ab197419195043b0f2e4ce76). Please lets us know if you have any question.

**Comment by 0xCaso** [comment]
Thanks a lot @0xslipk for the updates! 

Could you add please [here](https://github.com/blockcoders/ink-substrate-explorer-api#run) the command ```docker network create ink-explorer-network```?
Also, when I run the image, I get this error:
```
> ink-substrate-explorer-api@1.0.0-alpha.1 start:prod
> node dist/src/main

@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
	cjs 10.1.6	node_modules/.pnpm/@polkadot+util@10.1.6/node_modules/@polkadot/util/cjs
	cjs 10.1.2	node_modules/.pnpm/@polkadot+util@10.1.2/node_modules/@polkadot/util/cjs
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [NestFactory] Starting Nest application...
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] DBModule dependencies initialized +65ms
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] EnvModule dependencies initialized +1ms
[Nest] 18  - 09/28/2022, 8:48:24 AM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
[Nest] 18  - 09/28/2022, 8:48:24 AM   ERROR [ExceptionHandler] unable to determine transport target for "pino-pretty"
Error: unable to determine transport target for "pino-pretty"
    at fixTarget (/usr/src/app/node_modules/.pnpm/pino@8.3.1/node_modules/pino/lib/transport.js:136:13)
    at transport (/usr/src/app/node_modules/.pnpm/pino@8.3.1/node_modules/pino/lib/transport.js:110:22)
    at normalizeArgs (/usr/src/app/node_modules/.pnpm/pino@8.3.1/node_modules/pino/lib/tools.js:291:16)
    at pino (/usr/src/app/node_modules/.pnpm/pino@8.3.1/node_modules/pino/pino.js:84:28)
    at new PinoLogger (/usr/src/app/node_modules/.pnpm/nestjs-pino@3.1.1_isil7xagyf5s32dueim4ljgsga/node_modules/nestjs-pino/PinoLogger.js:45:51)
    at Injector.instantiateClass (/usr/src/app/node_modules/.pnpm/@nestjs+core@8.4.7_zyw32gfu5yv6lfoz64j5eiekme/node_modules/@nestjs/core/injector/injector.js:330:19)
    at callback (/usr/src/app/node_modules/.pnpm/@nestjs+core@8.4.7_zyw32gfu5yv6lfoz64j5eiekme/node_modules/@nestjs/core/injector/injector.js:48:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Injector.resolveConstructorParams (/usr/src/app/node_modules/.pnpm/@nestjs+core@8.4.7_zyw32gfu5yv6lfoz64j5eiekme/node_modules/@nestjs/core/injector/injector.js:122:24)
    at async Injector.loadInstance (/usr/src/app/node_modules/.pnpm/@nestjs+core@8.4.7_zyw32gfu5yv6lfoz64j5eiekme/node_modules/@nestjs/core/injector/injector.js:52:9)
```
In the meantime, I'm moving forward with the evaluation and I'm updating the document asap (I'll let you know here when it's updated)

**Comment by 0xCaso** [comment]
@0xslipk  I updated the [evaluation file](https://github.com/w3f/Grant-Milestone-Delivery/blob/269b510d648622353784a89000ba54dba5ed6d91/evaluations/ink-explorer_1_0xCaso.md) with the last changes. Everything you added and changed is very good, and now everything is complete and working, apart from the mentioned above (I mentioned it also inside the new evaluation file).

**Comment by 0xslipk** [comment]
> @0xslipk I updated the [evaluation file](https://github.com/w3f/Grant-Milestone-Delivery/blob/269b510d648622353784a89000ba54dba5ed6d91/evaluations/ink-explorer_1_0xCaso.md) with the last changes. Everything you added and changed is very good, and now everything is complete and working, apart from the mentioned above (I mentioned it also inside the new evaluation file).

Hi @0xCaso thank you for your review.  We updated a few things in the API:
- We added the `NODE_ENV=production` to [start:prod](https://github.com/blockcoders/ink-substrate-explorer-api/releases/tag/v1.0.0) to prevent the error above related to `pino-pretty`.
- We added the [coverage report](https://coveralls.io/github/blockcoders/ink-substrate-explorer-api?branch=main) and the badge in the repository.
- We added Snyk to detect vulnerabilities in the dependencies. This plugin already found and fixed two related to docker images for Nodejs.
- We added the creation of the network in the [README.md](https://github.com/blockcoders/ink-substrate-explorer-api#run)
- We released the version [1.0.0](https://github.com/blockcoders/ink-substrate-explorer-api/releases/tag/v1.0.0)

**Comment by 0xCaso** [comment]
Thanks again for the updates! This time I managed to run everything, and the API works well (GraphQL Playground included)!

There is a little caveat: adding the ```NODE_ENV=production``` to ```start:prod``` script didn't resolve the problem; I had to set the variable inside ```.env``` file manually. So I'd edit the ```.env.sample``` with that var and also the port (from ```8080``` to ```5000```); 

Finally, [here](https://github.com/blockcoders/ink-substrate-explorer-api#starting-the-project-prod) I'd put the command ```docker-compose up -d``` before the rest, as the DB is needed to the API service to work.

Sorry for the pedantry, but these last changes would make everything almost perfect.

**Comment by 0xslipk** [comment]
> Thanks again for the updates! This time I managed to run everything, and the API works well (GraphQL Playground included)!
> 
> There is a little caveat: adding the `NODE_ENV=production` to `start:prod` script didn't resolve the problem; I had to set the variable inside `.env` file manually. So I'd edit the `.env.sample` with that var and also the port (from `8080` to `5000`);
> 
> Finally, [here](https://github.com/blockcoders/ink-substrate-explorer-api#starting-the-project-prod) I'd put the command `docker-compose up -d` before the rest, as the DB is needed to the API service to work.
> 
> Sorry for the pedantry, but these last changes would make everything almost perfect.

Awesome to hear.  @0xCaso we just updated the [main](https://github.com/blockcoders/ink-substrate-explorer-api/commit/7e24e914d19766f4096f3a3cbb70f58a763a8989) branch with the last fix for above.

**Comment by 0xCaso** [comment]
Perfect @0xslipk! My evaluation is ended with [this](https://github.com/w3f/Grant-Milestone-Delivery/blob/f044696498baeb7d4d2c0c79748ec16d322e918e/evaluations/ink-explorer_1_0xCaso.md) last commit. Let's wait now for a W3F evaluator review. Thanks a lot to you and your team for the patience and the corrections!

**Comment by 0xslipk** [comment]
> Perfect @0xslipk! My evaluation is ended with [this](https://github.com/w3f/Grant-Milestone-Delivery/blob/f044696498baeb7d4d2c0c79748ec16d322e918e/evaluations/ink-explorer_1_0xCaso.md) last commit. Let's wait now for a W3F evaluator review. Thanks a lot to you and your team for the patience and the corrections!

Awesome, thank you so much for taking time to review our work.

**Comment by 0xslipk** [comment]
Hi @takahser, just to let you know. this delivery is ready to merge. Let me know if you have any question.

**Comment by 0xslipk** [comment]
> Hi @0xslipk apologies for the delay. I am also evaluating your delivery and currently having an issue connecting to postgres database when running `pnpm start:dev`
> 
> ```ts
> [6:01:24 PM] Starting compilation in watch mode...
> 
> [6:01:26 PM] Found 0 errors. Watching for file changes.
> 
> @polkadot/util has multiple versions, ensure that there is only one installed.
> Either remove and explicitly install matching versions or dedupe using your package manager.
> The following conflicting packages were found:
>         cjs 10.1.6      node_modules/.pnpm/@polkadot+util@10.1.6/node_modules/@polkadot/util/cjs
>         cjs 10.1.2      node_modules/.pnpm/@polkadot+util@10.1.2/node_modules/@polkadot/util/cjs
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [NestFactory] Starting Nest application...
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] DBModule dependencies initialized +23ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] TypeOrmModule dependencies initialized +0ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] ConfigHostModule dependencies initialized +0ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] EnvModule dependencies initialized +1ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +0ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] LoggerModule dependencies initialized +17ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM     LOG [InstanceLoader] GraphQLModule dependencies initialized +0ms
> [Nest] 11771  - 10/05/2022, 6:01:27 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (1)...
> Error: getaddrinfo ENOTFOUND postgres
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
> ```
> 
> I have all the containers (`postgres-1`, `pgadmin-1`, `backend-1`) running and my .env file is set like so:
> 
> ```
> NODE_ENV=development
> PORT=8080
> LOG_NAME=ink-substrate-explorer-api
> LOG_LEVEL=debug
> 
> GRAPHQL_DEBUG=true
> GRAPHQL_PLAYGROUND=true
> GRAPHQL_SORT_SCHEMA=true
> GRAPHQL_INTROSPECTION=true
> 
> DATABASE_HOST=postgres
> DATABASE_NAME=ink
> DATABASE_USERNAME=root
> DATABASE_PASSWORD=password
> DATABASE_RETRY_ATTEMPTS=5
> DATABASE_RETRY_DELAY=3000
> 
> WS_PROVIDER=ws://127.0.0.1:9944
> LOAD_ALL_BLOCKS=false
> FIRST_BLOCK_TO_LOAD=0
> BLOCKS_CONCURRENCY=1000
> ```
> 
> This also happens when connected to `wss://rococo-contracts-rpc.polkadot.io`
> 
> The server is setup and running in pgAdmin. Can you help me with what I am missing here? Thanks!

Hi @keeganquigley,

You probably ran `docker compose up -d`, you already have all the containers (postgres-1, pgadmin-1, backend-1) running. You don't need to run `pnpm start:dev` again, because the services is already running on `backend-1` container. if you run `pnpm backend:logs` you will probably see the services syncing the parachain, like this:

```sh
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:13.979 +0000] INFO (ink-substrate-explorer-api/34 on 75430df680ad): Block 19272 loaded. {"context":"SubscriptionsService"}
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:13.979 +0000] DEBUG (ink-substrate-explorer-api/34 on 75430df680ad): Block hash: 0xe4dd753e437c68782ff80010e79c992bbe69a0f56f119e6de02440b8d66618ac {"context":"SubscriptionsService"}
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:15.627 +0000] INFO (ink-substrate-explorer-api/34 on 75430df680ad): Block 19243 loaded. {"context":"SubscriptionsService"}
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:15.627 +0000] DEBUG (ink-substrate-explorer-api/34 on 75430df680ad): Block hash: 0xa13e81d03e02ee803d76cd5edd47a509e95ed74d16f1fa1228a14c2cd31e5cbb {"context":"SubscriptionsService"}
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:16.413 +0000] INFO (ink-substrate-explorer-api/34 on 75430df680ad): Block 19295 loaded. {"context":"SubscriptionsService"}
ink-substrate-explorer-api-backend-1  | [2022-10-06 20:06:16.413 +0000] DEBUG (ink-substrate-explorer-api/34 on 75430df680ad): Block hash: 0x5bd82d4330f8da3fbf9a85f100faddebcd395032e7117b50ae228f9619eb7a25 {"context":"SubscriptionsService"}
```

Let me know if you any other question.

**Comment by keeganquigley** [comment]
Ah I see, thanks @0xslipk in this case I think the instructions are not very clear, because I ran `docker-compose -f dev-docker-compose.yaml up -d` so this command is not actually needed in that context. Will note this in the eval, thanks!

**Review by Noc2 — APPROVED** [review]
The milestone is officially accepted: https://github.com/w3f/Grant-Milestone-Delivery/pull/591 We will forward your invoice internally.

**Comment by 0xslipk** [comment]
> The milestone is officially accepted: #591 We will forward your invoice internally.

Awesome guys. Thank you so much for your support.

**Pull request merged**
