### PR TITLE
Polkadart Milestone 2

### PR DESCRIPTION
**Pull request by Lohann**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1053

### CODE REVIEW

**Comment by keeganquigley** [comment]
@Lohann thanks for the delivery. Someone will take a look at it soon.

**Comment by keeganquigley** [comment]
@Lohann I'm in the process of evaluating your delivery. A couple of initial comments:

- There are quite a few broken links in your delivery. Can you update these please?
- I'm not super familiar with Dart, should I just be running `dart test` in the root folder to run all tests for the project? Or do I need to run it in each of the test folders separately? Thanks!

**Comment by Lohann** [comment]
Hey @keeganquigley for sure I'll check the links, for running the tests you can do the following:
```bash
# install git-lfs
brew install git-lfs
git lfs fetch
git lfs checkout

# Install dependencies for all packages
./scripts/run_dart_pub_get.sh

# Run tests
./scripts/run_tests.sh
```

If you are interested in the more hand-on approach, we published a pre-release version of all packages on [pub.dev](https://pub.dev/publishers/cryptize.co/packages):

You can get started doing the following:
1 - Create a new project 
```bash
dart create -t console polkadart-milestone-2
cd polkadart-milestone-2
```
2 - Add those dependencies to `pubspec.yaml`
```yaml
...
dependencies:
  polkadart: ^0.1.0-pre.2
  ss58: ^1.1.0-pre.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  polkadart_cli: ^0.1.0-pre.1

polkadart:
  output_dir: bin/generated
  chains:
    polkadot: wss://rpc.polkadot.io
``` 
Run following command for generate the Dart types from polkadot metadata:
```bash
dart run polkadart_cli:generate -v
```
Replace the contents of `bin/polkadart_milestone_2.dart` with following sample code:
```dart
import 'package:ss58/ss58.dart' show Address;
import './generated/polkadot/polkadot.dart' show Polkadot;

void main(List<String> arguments) async {
  final Polkadot polkadot = Polkadot.url(Uri.parse('wss://rpc.polkadot.io'));
  final account = Address.decode('19t9Q2ay58hMDaeg6eeBhqmHsRnc2jDMV3cYYw9zbc59HLj');
  final balance = await polkadot.query.system.account(account.pubkey);
  print(balance.toJson());
  await polkadot.disconnect();
}
```
For run the code above, just run:
```bash
dart run
```

**Comment by Lohann** [comment]
@keeganquigley thanks for the heads up, broken links fixed ✅

**Comment by keeganquigley** [comment]
Thanks for the changes @Lohann! The test scripts work great. I appreciate the hands-on tutorial as well.

Running `docker compose up` however, gives me this error:
```dart
Attaching to polkadart-tests-1
polkadart-tests-1  | The current Dart SDK version is 2.19.5.
polkadart-tests-1  | 
polkadart-tests-1  | Because every version of flutter from sdk depends on sky_engine from sdk which requires SDK version >=3.0.0-0 <4.0.0, flutter from sdk is forbidden.
polkadart-tests-1  | So, because polkadart_example depends on flutter from sdk, version solving failed.
polkadart-tests-1  | 
polkadart-tests-1 exited with code 65
```
I think maybe there is a version error. Does a certain Flutter version need to be specified in the Dockerfile?

**Comment by leonardocustodio** [comment]
Hello @keeganquigley , that's my bad. I forgot to update the Dockerfile. Can you fresh clone the repository and try again?

**Comment by keeganquigley** [comment]
Thanks for the changes @leonardocustodio yep it works now! I'm happy to pass the milestone, and will forward your invoice internally for payment.

You can find my final eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadart_2_keeganquigley.md).

**Comment by semuelle** [comment]
@Lohann, the postal address on your invoice doesn't match the one in the grant application. If your postal address changed, could you submit an amendment to the contract with the new address, please?

**Comment by Lohann** [comment]
@semuelle thanks of the heads up, invoice updated ✅

**Comment by semuelle** [comment]
@Lohann, I was referring to [this address](https://github.com/w3f/Grants-Program/blob/master/applications/Polkadart.md#legal-structure). Also, the invoice shows January as the date. Could you update again?

**Comment by Lohann** [comment]
@semuelle hmm, maybe I attached the invoice from Milestone 1 by mistake, could you check again? I've sent from `lohann@cryptize.co` the invoice title is `Polkadart-Milestone-2-Invoice.pdf`

**Comment by keeganquigley** [comment]
@semuelle @Lohann sorry, this was my fault. Looks like I attached the wrong invoice when I sent the email. The one you submitted on March 31st appears to be correct, as well as the most recent one. I will send this again. My apologies!

**Pull request merged**
