### PR TITLE
ventur-milestone-1

### PR DESCRIPTION
**Pull request by Gryczka**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1126

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @Gryczka. We will look into it as soon as possible. We have a bit of a backlog currently, please bear with us.

**Comment by Gryczka** [comment]
Hi @semuelle just checking in.  Do you have any estimates for when we might get feedback for this milestone?

**Comment by dsm-w3f** [comment]
@Gryczka thank you for the milestone submission and my apologies for the late response. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ventur_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by Gryczka** [comment]
Thank you for the review @dsm-w3f!  Your feedback has been really useful.

On Docker, we’ve made some changes and the docker compose script should run, we now also have pipelines running to validate that both the Docker Compose and Docker Build approaches succeed.

Here is a link to the pipelines and a specific run on main:
https://github.com/Popular-Coding/ventur/actions/workflows/check-docker.yml
https://github.com/Popular-Coding/ventur/actions/runs/3382189980
The pipeline tasks include both successful builds as well as timed out runs of the node.

For the testing guides feedback, we have updated the escrow pallet to limit locking to available funds.  Lockable Currency allows for amounts greater than the available funds to be locked, but limiting it to available funds makes sense in this case, and will likely provide a better user experience that lines up more closely with expected behavior.

For the ventur integration, we have added an example of integration into the payments pallet, specifically the final payment pallets test guide example walks through initializing and claiming payments that come from escrow locked funds.

On Code quality, we’ve addressed the clippy warnings on our substrate node and increased test coverage across the Escrow pallet up to about 85% (219/255 lines).

Let us know if that meets the bar for Milestone 1.

**Comment by dsm-w3f** [comment]
@Gryczka Thank you for the improvements. We are almost done with this evaluation. Only the script for docker compose did not work well. Maybe some configuration or image problem. Please see the details in the [updated evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ventur_1_dsm-w3f.md). Let me know when I can check it again.

**Comment by Gryczka** [comment]
@dsm-w3f We haven't been able to replicate the docker script issue.  Could you share what system you're running on?

In the short term, to get the milestone approved, would it be acceptable to mark the docker compose script as Ubuntu specific and have the docker build command for Mac, etc?

**Comment by dsm-w3f** [comment]
@Gryczka my apologies, the problem with the docker-compose was an old version of the image used in our test server. The milestone is approved. Thank you for the delivery, great work!

**Comment by Gryczka** [comment]
@dsm-w3f would it be possible to email or message you regarding our second milestone submission?

We're finalizing the delivery commit at the moment, but we wanted to get feedback on one of our attributions prior to submission to ensure we're in line with the program's guidelines.

**Pull request merged**
