### PR TITLE
Sol2Ink Milestone 1

### PR DESCRIPTION
**Pull request by coreggon11**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [X] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [X] This pull request is being made by the same account as the accepted application.
- [X] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [X] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/960

### CODE REVIEW

**Comment by cruikshankss** [comment]
Hello @coreggon11, thank you for your delivery. I hope to get started on your evaluation next week. Sorry for the delay and please expect an update next week. I'm very excited to get to this; the reason I learned about Rust is because I was working on writing a compiler for fun in 2020 and then since have become obsessed with Rust. So, of course, I'm extremely excited to review your transpiler! Also, I'm working on the an OpenBrush delivery now as well as attended some Wasmconf lectures, so hopefully I should have the proper background to understand the value of your project! Cheers!

**Comment by cruikshankss** [comment]
Good day @coreggon11! 

I've started testing your delivery! I'm running into some compilation errors, which I'm not sure are errors on my part or bugs on your end. I'm hoping you could help guide me out of my inexperience. Thanks!

So I cloned this repo and tried `rustup update`, `rustup update nightly`, and `rustup target add wasm32-unknown-unknown --toolchain nightly` before running `cargo run contract.sol`, but got compilation errors each time. Below each command is the output for your reference. Thanks and sorry if I don't understand how to manage rust toolchains well enough! I'm running MacOS (intel chip). 

`rustup update` output:
```
     stable-x86_64-apple-darwin updated - rustc 1.63.0 (4b91a6ea7 2022-08-08) (from rustc 1.62.1 (e092d0b6b 2022-07-16))
  nightly-x86_64-apple-darwin unchanged - rustc 1.65.0-nightly (801821d15 2022-08-14)

info: cleaning up downloads & tmp directories
```
```
   Compiling proc-macro2 v1.0.43
   Compiling memchr v2.5.0
   Compiling unicode-ident v1.0.3
   Compiling autocfg v1.1.0
   Compiling syn v1.0.99
   Compiling quote v1.0.21
   Compiling regex-syntax v0.6.27
   Compiling lazy_static v1.4.0
   Compiling convert_case v0.5.0
   Compiling substring v1.4.5
   Compiling aho-corasick v0.7.18
   Compiling rust-format v0.3.4
   Compiling regex v1.6.0
   Compiling sol_to_ink v1.0.0 (/Users/ash/wthree/sol2ink)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:23:1
   |
23 | #![feature(once_cell)]
   | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:24:1
   |
24 | #![feature(string_remove_matches)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:25:1
   |
25 | #![feature(exclusive_range_pattern)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:23:12
   |
23 | #![feature(once_cell)]
   |            ^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:24:12
   |
24 | #![feature(string_remove_matches)]
   |            ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `sol_to_ink` due to 5 previous errors
```














 `rustup update nightly` output:
```
info: syncing channel updates for 'nightly-x86_64-apple-darwin'

  nightly-x86_64-apple-darwin unchanged - rustc 1.65.0-nightly (801821d15 2022-08-14)

info: checking for self-updates

```
```
Compiling sol_to_ink v1.0.0 (/Users/ash/wthree/sol2ink)
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:23:1
   |
23 | #![feature(once_cell)]
   | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:24:1
   |
24 | #![feature(string_remove_matches)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:25:1
   |
25 | #![feature(exclusive_range_pattern)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:23:12
   |
23 | #![feature(once_cell)]
   |            ^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> src/main.rs:24:12
   |
24 | #![feature(string_remove_matches)]
   |            ^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `sol_to_ink` due to 5 previous errors
```





`rustup target add wasm32-unknown-unknown --toolchain nightly` output: 
```
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
```

(then same output as the example just above this)




Should I do some sort of `rustup override set` command? Or something like `rustup target add wasm32-unknown-unknown --toolchain nightly-` and specify a date? 

Oh actually, I just tried `rustup default nightly` and feel like I made the most progress so far!! But I still had a bug:
```
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.3
   Compiling memchr v2.5.0
   Compiling autocfg v1.1.0
   Compiling syn v1.0.99
   Compiling quote v1.0.21
   Compiling regex-syntax v0.6.27
   Compiling convert_case v0.5.0
   Compiling lazy_static v1.4.0
   Compiling substring v1.4.5
   Compiling aho-corasick v0.7.18
   Compiling rust-format v0.3.4
   Compiling regex v1.6.0
   Compiling sol_to_ink v1.0.0 (/Users/ash/wthree/sol2ink)
    Finished dev [unoptimized + debuginfo] target(s) in 6.13s
     Running `target/debug/sol_to_ink contract.sol`
error: FileError("No such file or directory (os error 2)")
```
Sorry if this is a really stupid question, but which directory should I be in to run `cargo run contract.sol `? 😂

**Comment by coreggon11** [comment]
Hey @cruikshankss 

So the transpiler runs on nightly version, which is specified in the readme, but then the readme assumes that it is your default chain (which it may not be), so you need to `cargo +nightly run` (or switch the default toolchain to nightly, I will update this info 🙃).

Also `cargo run contract.sol` assumes that you have a Solidity file `contract.sol` in the working dir (which does not exist, it is actually described in the docs, but I will fix this for readme).

There are some test contracts and interfaces in examples directory, running `cargo +nightly test` will transpile these, or for example `cargo +nightly run examples/contracts/ERC20/ERC20.sol`, but nothing will change since the transpiled example contracts are already in the repo.

Hope it didn't cost you too much nerves so far 😂

**Comment by cruikshankss** [comment]
Hi @coreggon11, thanks so much for the detailed instructions! No nerves were burnt in the testing of this evaluation. 😂 I'm having a lot of fun with it! 

I'm just starting my day here in the US but I plan to give it another go and get back to you later.

**Comment by cruikshankss** [comment]
@coreggon11 I've just finished a bunch of other work this week and so I've freed myself up a lot and I'm preparing a deep work session so I can read your docs for a couple hours. Absolutely excellent job simplifying your codebase/testing guide into the github and a website. Thank you sincerely.

**Comment by cruikshankss** [comment]
Hi @coreggon11!

Nice intro/organization of concepts/storytelling on your website so far.

I really believe Sol2Ink could save devs a ton of time and help onboard ethereum/EVM/solidity smart contract devs into the substrate/rust/wasm/ink! smart contract ecosystem.

Sorry to make you teach me the rust toolchain! Thanks sincerely for your time. I've been compiling the docs for the w3f grants team on the rust toolchain but they're pretty sparse and I could maybe open-source them on gh if I improve my notes. There's just so much knowledge to learn and document in the ecosystem, but it moves so fast too lol 

I noticed on your site you say "here" and "here" and you have the proper links on the proper pages to the OpenZep ERC-20 contracts and to Sol2Ink, but I think you should just maybe hyperlink them in the proper places could save people some potential confusion/time. But that's just a tiny suggestion. Your docs are really professional and computer-science-based and explain Layer 0 very carefully, thanks!

Looks like you might have to teach the ecosystem other computer science concepts such as inheritance vs interfaces, language design, compiler design, patterns of idea mapping, logic of functionality, the logic of knowledge, organizing the characteristics and functions of digital objects, classification schemes of ideas, philosophy, etc. to help people who are wanting to learn :) maybe you could even start a bootcamp/course or a consulting/auditing agency or 5iver/upwork-type/freelance marketplace for upgrading/working with compilers/transpilers/translators and smart contracts specifically? No rush; just thinking out loud. You're already doing so much work!! Compiler engineering is awesome lol. I'm so inspired by LLVM and rustc. Nice that you idealize making nice error messages like rustc does!

Thanks for documenting the current Sol2Ink limitations so carefully. That reminds me, I remember when @xgreenx told me about the rust work you've done at supercolony to handle the inheritance/interfaces issue with traits in rust. Super excited to learn about that sometime actually and thanks a million for doing that computer science work for humanity. 

It's really cool to see computer science being brought finally to the web. I'm a JavaScript dev lol and it's the least computer-science-minded language and web 2.0/npm is so broken in so many ways and it's really nice to witness the conceptualization and progress towards a secure web 3.0. I dream about rust/wasm/deno/TypeScript/cargo/vanilla CSS3/HTML5/WebAPIs/OCW for the front-end of the web so we can more easily build progressive web apps (PWAs). It's really cool to see how fast the front-end evolves and prototypes though. 

I mention this because here in the US there are a lot of Solidity bootcamps and a lot of fresh bootcamp grads that are Solidity smart contract developers, and a lot of times, it's easiest for them to get into web 2.0, whether backend or frontend web developers, and of course the mission of Sol2Ink is to aid Solidity developers. Thanks again!

It's good to know there might be missing methods and variables in the child objects in the contracts. Also good to know there might be broken statements/types/expressions and they might sneakily compile without panicking! Maybe someday you could make a small tipping program for people to report Sol2Ink transpiler errors/bug reports? 

I'm preparing the contract now, so I think my commands will be `git clone`, `git clone`, `mv`, `cd`, then add the events from the IERC-20 interface standard. I didn't even know there were standards for events! LOL! In javascriptland we just get to make a different concept of events/time every day we show up to work! ;-) JavaScript is like my fire sword and Rust is like my earth/air/water bending to build a foundation. :) best language ever + worst language ever = FTW ;-)

As you can see, my evaluation might take some time 😂 ... I hope you're not in a rush. If you are, let's hop on a call this week. Otherwise, I think you can probably tell I'm thoroughly appreciating getting to do this work for a living. I plan to update you next time I can facilitate a flow state to evaluate your project.

**Comment by coreggon11** [comment]
Hey @cruikshankss 

Seems like you are very excited about Sol2Ink, I like it 😂

About the hyperlink stuff you mentioned, I wanted to hyperlink it when we will have the release, and then forgot about it 🙃 It's fixed now 😃

Aand we don't hurry, you can take your time, if you have any questions you can just ping me.

Have fun evaluating 😃

**Comment by cruikshankss** [comment]
Congratulations! [my eval](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/sol2ink_1_cruikshankss.md)

**Comment by cruikshankss** [comment]
I've forwarded your invoice internally. Hope you have a great weekend!

**Pull request merged**
