### PR TITLE
External evaluation NoCode M2

### PR DESCRIPTION
**Pull request by JosephKnecht-lab**
This is an external evaluation for the second milestone of the Polkadotjs-NoCode project.

Summary of Evaluation:
The intended functionality has been delivered. The status of the application is Accepted. 

- There only minor comments regarding some of the deliverables.
- I have included some constructive feedback that might help the team in the future.

Original Milestone Submission:(https://github.com/w3f/Grant-Milestone-Delivery/pull/363)

### CODE REVIEW

**Comment by alxs** [comment]
@JosephKnecht-lab thank you for another thorough evaluation. @cruikshankss will double-check it. I suggest you leave your comment above on the delivery PR (see [step 6](https://github.com/w3f/Grant-Milestone-Delivery#process)) in future evaluations, so the full conversation with the team can be found in one place.

**Comment by cruikshankss** [comment]
@alxs I just submitted my PR for the [evaluation of this 2nd EzCode milestone](https://github.com/w3f/Grant-Milestone-Delivery/pull/372) and then skimmed through your evaluation, @JosephKnecht-lab. Thank you very much for reviewing! I plan to read & respond to your review as soon as possible. Thank you!

**Comment by cruikshankss** [comment]
@JosephKnecht-lab I did agree the demo was too technical for average users. I gave this feedback too, and then @inartin actually made two beginner-friendly tutorials that are quite clear. @inartin plans to add them to their docs website. 

Also, @inartin, if you'd like to provide more beginner resources, perhaps you could link to the Web3 Foundation's Bill Laboon's YouTube channel with his [Web3 Blockchain Fundamentals videos](https://www.youtube.com/user/billlaboon/videos).

@JosephKnecht-lab Thank you for asking some questions and offering some information. In response to point 1: I think it'd be rather complex to bridge a Bubble app with a React app/substrate frontend template. I’ve looked into creating React code from designs such as Anima, but the CSS was rather legacy, e.g. using ‘absolute position’ instead of ‘grid’. Still, good question that really got me thinking!

**Review by Noc2 — APPROVED** [review]
Thanks for your work. I’m happy to merge the evaluation.

**Comment by inartin** [comment]
> plans to add them to their docs website.

Already done [here](https://polkadotjs.docs.ezcodeplugins.com/beginners-guide/bubble-basics)

**Comment by RouvenP** [comment]
hi @JosephKnecht-lab we transferred the KSM. thanks!

**Pull request merged**
