### PR TITLE
Security Marketplace milestone 2 Delivery

### PR DESCRIPTION
**Pull request by ParthChaudhary31**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x ] This pull request is being made by the same account as the accepted application.
- [x ] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x ] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [ x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1726

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the update, @ParthChaudhary31. I was able to compile the frontend. However, when I try to run it using `npm start`, I get the following error message. Could you look into it? FYI, when I run the frontend from Docker and open `localhost:3000`, I get ``.

```sh
Compiled successfully!

You can now view Audit-Bazaar in the browser.

  Local:            http://localhost:3000
  On Your Network:  http://192.168.178.21:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

webpack compiled successfully
Files successfully emitted, waiting for typecheck results...
Issues checking in progress...
ERROR in src/Api/Actions/contract.action.ts:115:34
TS2345: Argument of type 'import("/home/security-marketplace/Security_Marketplace_Frontend/node_modules/@astar-network/astar-api/node_modules/@polkadot/api/types/index").ApiOptions' is not assignable to parameter of type 'import("/home/security-marketplace/Security_Marketplace_Frontend/node_modules/@polkadot/api/types/index").ApiOptions'.
    113 |       // Contract call setup and execution code
    114 |       const provider = new WsProvider(RPC_URL_ASTAR);
  > 115 |       const api = new ApiPromise(options({ provider }));
        |                                  ^^^^^^^^^^^^^^^^^^^^^
    116 |       const allInjected = await web3Enable(SUBWALLET_JS);
    117 |       await api.isReady;
    118 |
```

**Comment by ParthChaudhary31** [comment]
@semuelle , My team is working on checking through the possible reasons for it, meanwhile can you please try these steps :

1. Delete node_modules folder
2. 
Delete package-lock.json
3. Run 
```npm install -f```
4. 
Run ```npm start```

And let me know if it works ?

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the update, @ParthChaudhary31. The frontend now works. 
There are a couple of features that I cannot find, below is a list. Can you tell me where to find them?

- When I fill in the details for an audit request and hit `Confirm`, it doesn't seem to save the data and I cannot find the request anywhere.
- The `Confirm` and `Cancel` buttons on the requests don't seem to do anything, as do the pagination buttons. The data on the Balance page is also mocked. 
- When and where are the SBTs sent and data written to the escrow contract?
- I still don't see a 2FA option

**Comment by ParthChaudhary31** [comment]
@semuelle ,
Can you confirm you're using ```Security-marketplace-milestone2``` branch from the front end and not the main ?

**Comment by semuelle** [comment]
> Can you confirm you're using `Security-marketplace-milestone2` branch from the front end and not the main ?

Yeah, sorry, I was on the main branch. I'm now able to register and store an address. When I try to create a request, though, I am getting a `Audit request failed` popup and the following message in the console. Could you look into that? I changed all `10.1.4.54` URLs to `localhost`, btw. 

```
Warning: React does not recognize the `handleClose` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `handleclose` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by ParthChaudhary31** [comment]
@semuelle ,
we would need more inputs on this one
Please share screenshots of the items below 
1 .env file (blur out any important keys/ info)
2. Network request : payloads & response
3. Browser's console (after making request)

Also can you confirm that your connected Shibuya account your has Shibuya testnet coins ?

**Comment by semuelle** [comment]
Sure.

1.:

```
PORT=9000
MONGO_URL=mongodb://localhost:_____/auditbazaar
JWT_SECRET=_____
ARBITER_1=5EvdWekzbghsmBd2AH1npDMGAZQT11111111111111111111
ARBITER_2=_____
ARBITER_3=
ARBITER_4=
ARBITER_5=
WEB_SOCKET=wss://rpc.shibuya.astar.network
VOTING_ADDRESS=
ESCROW_CONTRACT=
SECRET_KEY=
```

2.: Not sure how I would go about exporting payloads, but here's a screenshot of Chrome's network tab:

image



3.:

```
web3Enable: Enabled 1 extension: subwallet-js/1.1.22-0
bundle.js:136 web3Accounts: Found 2 addresses
user.action.ts:177 {userAccount: '_____'}
user.action.ts:178 {walletAddressUserSaved: '_____'}
react-dom.development.js:74 Warning: React does not recognize the `handleClose` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `handleclose` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at http://localhost:3000/static/js/bundle.js:96896:3
    at div
    at Transition (http://localhost:3000/static/js/bundle.js:144509:30)
    at http://localhost:3000/static/js/bundle.js:99064:3
    at http://localhost:3000/static/js/bundle.js:95670:3
    at DialogTransition
    at http://localhost:3000/static/js/bundle.js:38582:7
    at http://localhost:3000/static/js/bundle.js:96591:3
    at TransactionModal (http://localhost:3000/static/js/bundle.js:11644:3)
    at div
    at div
    at section
    at Post (http://localhost:3000/static/js/bundle.js:18422:82)
    at RequireAuth (http://localhost:3000/static/js/bundle.js:22595:79)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:137071:5)
    at Outlet (http://localhost:3000/static/js/bundle.js:137610:26)
    at div
    at div
    at _t (http://localhost:3000/static/js/bundle.js:129763:11)
    at AuthLayout (http://localhost:3000/static/js/bundle.js:5654:3)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:137071:5)
    at RenderErrorBoundary (http://localhost:3000/static/js/bundle.js:137018:5)
    at DataRoutes (http://localhost:3000/static/js/bundle.js:135680:5)
    at Router (http://localhost:3000/static/js/bundle.js:137631:15)
    at RouterProvider (http://localhost:3000/static/js/bundle.js:135522:5)
    at Application
    at PersistGate (http://localhost:3000/static/js/bundle.js:150219:5)
    at Provider (http://localhost:3000/static/js/bundle.js:132636:3)
    at App (http://localhost:3000/static/js/bundle.js:2249:51)
```

**Comment by ParthChaudhary31** [comment]
@semuelle ,
My team has concluded that you might not have the stablecoin funds on which the platform is supposed to operate. For now, we'd please like you to deploy a mock ERC20 contract whose address you'll have to pass in the constructor of the escrow contract, Voting Contract as well as in a constant of the front end (Details of which have been added to the front end Document), and hold a sufficient balance of it on the wallet you're working with. This contract can now be found in the mock folder of our smart contract's updated repository. 

I apologize for missing out on this information in the documentation, it has however, now been added to the front end.

**Comment by semuelle** [comment]
Thanks for the update. Could you add this information to the documentation?

**Comment by semuelle** [comment]
Thanks for the update, @ParthChaudhary31. I am willing to approve this milestone, except the article is still missing. Can you add the article to the delivery or send us a link via email?

**Comment by ParthChaudhary31** [comment]
Thanks @semuelle ,
We're now in the process of finishing up the article and will add it to the deliverables soon.

**Comment by semuelle** [comment]
any news on the article, @ParthChaudhary31?

**Comment by ParthChaudhary31** [comment]
@semuelle 
I just pushed the article link to the repository, extremely sorry for the delay.

**Review by semuelle — APPROVED** [review]
Thanks for the update, @ParthChaudhary31. Your milestone is hereby accepted. Congratulations. 

You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/security-marketplace_2_semuelle.md). 

Since this is the last milestone, I want to wish you best of luck with the project. Would be great to see it come to life.

**Comment by semuelle** [comment]
@ParthChaudhary31, the invoice is missing the foundation's address. Could you amend that and resubmit? Thanks!

**Comment by ParthChaudhary31** [comment]
Hey @semuelle ,
Need a small favor. The accounts team raised an invoice on December 01 and we have no updates on it yet. Can you please check on your end and help me out on this? I need to update further to our Delivery Lead. If you can share the receipt, that would be great.

**Comment by semuelle** [comment]
Hey @ParthChaudhary31. Thanks for the reminder. I'm not exactly sure what the issue was, but the invoice is being processed right now and should be paid on Friday latest. Sorry for the delay!

**Comment by ParthChaudhary31** [comment]
Thanks for the update @semuelle. I will share the same further with the team. Just one favor, Please share the receipt with me once it's Processed.

**Comment by ParthChaudhary31** [comment]
@semuelle 
Any updates ?

**Pull request merged**
