### PR TITLE
ink! analyzer milestone 2 (#1615)

### PR DESCRIPTION
**Pull request by davidsemakula**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1615 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by keeganquigley** [comment]
Thanks for the delivery @davidsemakula someone will take a look in the next few days.

**Comment by dsm-w3f** [comment]
@davidsemakula thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink_analyzer_2_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by davidsemakula** [comment]
Hi @dsm-w3f 
Thanks for the swift review 🙂 

> Could you explain the public interface mentioned in the deliverables in this milestone?

I've added detailed explanations in the notes for each feature in the deliverable table.

> Could you provide system/integration tests for those interfaces? Could be a guide or automated tests with a contract example, expected inputs, and outputs to test these interfaces.

You may have missed it, but links to system/integration tests for each feature/interface were already included in the notes for the testing guide section 🙂 

I'll re-share them here for clarity:

"Integration tests for each feature can be found in the [tests directory of the semantic analyzer crate](https://github.com/ink-analyzer/ink-analyzer/tree/master/crates/analyzer/tests) (i.e [completions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/tests/completions.rs), [code/intent actions](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/tests/actions.rs) and [hover content module](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/analyzer/tests/hover.rs))."

I've also pushed an update that adds more docs explaining the methodology for system/integration tests and adds more inline comments that should make it easier to understand the test cases.

Checking out the [parse_offset_at](https://github.com/ink-analyzer/ink-analyzer/blob/master/crates/test_utils/src/lib.rs#L14-L45) utility may also be useful as it is extensively used in both the unit and integration tests for all 3 features. This is already mentioned in the inline comments but I've added a note about it in the "Testing and Testing Guide" section of the deliverables table for clarity.

**Comment by dsm-w3f** [comment]
@davidsemakula thank you for the improvements and explanations. I checked the system tests and they are ok. The milestone is accepted. I'll forward your invoice internally and the payment should take place within two weeks. Great job!

**Comment by davidsemakula** [comment]
@dsm-w3f awesome! Thanks for the swift review!

**Comment by davidsemakula** [comment]
@RouvenP just checking in since it's about 2 weeks now 🙂

**Comment by RouvenP** [comment]
hi @davidsemakula we just transferred the funds. thanks!

**Comment by davidsemakula** [comment]
@RouvenP received, thanks!

**Pull request merged**
