### PR TITLE
Add nft_explorer-milestone_1.md

### PR DESCRIPTION
**Pull request by wuminzhe**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/527

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks for the delivery. We will check your work in the coming weeks.

**Comment by semuelle** [comment]
Hi @wuminzhe, I am going through your delivery. Everything looks pretty good. I am particularly happy to see such thorough documentation. Only, I have trouble testing. Can you advise?

When running `cargo test` on the `evm-nft-tracker`, I get ``method `on_erc721_event` has 5 parameters but the declaration in trait `erc721::Erc721EventCallback::on_erc721_event` has 6``. When I add the `total_supply` parameter to the method, it compiles fine, but some tests are failing:

```
---- evm_client::tests::test_get_erc721_total_supply stdout ----
thread 'evm_client::tests::test_get_erc721_total_supply' panicked at 'assertion failed: `(left == right)`
  left: `9138`,
 right: `9116`', libs/nft-events/src/evm_client.rs:514:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- erc1155_evm::tests::test_get_erc1155_events stdout ----
thread 'erc1155_evm::tests::test_get_erc1155_events' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `4`', libs/nft-events/src/erc1155_evm.rs:116:9

---- erc1155::tests::test_track_erc1155_events stdout ----
thread 'erc1155::tests::test_track_erc1155_events' panicked at 'assertion failed: `(left == right)`
  left: `14`,
 right: `5`', libs/nft-events/src/erc1155.rs:195:9
```

Also, I didn't manage to find some events, that I expected to be in the results, such as ones from [the CryptoKitties core](https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d). Would `supportsInterface` have to return `0x5b5e139f` (ERC721Metadata)?

**Comment by wuminzhe** [comment]
@semuelle I'll fix the test problems.

1. 0e(article) in the milestone1 deliverable is blank. We planned to write the article in milestone2. 

2. What events do you expect to find? 
    I feel that the ERC721's `Transfer` event and ERC1155's `TransferSingle` and `TransferBatch` are enough for now.
    
3. Yes, for ERC721 contracts, only these implemented the `ERC721Metadata` will be tracked.
    https://github.com/uni-arts-chain/evm-nft-tracker/blob/ad6519ae20c96b2c0ebf0ee1d1936db0e93ca3bd/libs/nft-events/src/evm_client.rs#L95
    But, I consider removing the `supportsInterface` checking for some no standard contracts.

**Comment by semuelle** [comment]
ad 1: The way I read it, there is a deliverable titled "Article" in the milestone, only its specification is empty. However, I recognize that an article doesn't make much sense at this point. 

ad 2: I would expect to find any event from the contract. But you explained it, the contract doesn't implement ERC721Metadata according to its `supportsInterface` (even though it does). It would be _great_ if that check was optional.

**Comment by semuelle** [comment]
@wuminzhe, please let me know when the test issues are fixed, so I can review them.

**Comment by wuminzhe** [comment]
@semuelle Sorry, I forgot to tell you, I have fixed the tests.

**Comment by wuminzhe** [comment]
@semuelle I have updated the `Invoice Form` with the new invoice.

**Comment by RouvenP** [comment]
hi @wuminzhe we just transferred the payment.

**Pull request merged**
