### PR TITLE
Ssal Deliverables

### PR DESCRIPTION
**Pull request by MatteoPerona**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1986< please fill this in with the PR number of your application.

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Hey @MatteoPerona, thanks for the delivery and sorry for the long wait. It took me a bit to understand the logic of the smart contract, as I'm not so familiar with commodities. Everything looks good so far, I just have a few questions about the functionality in general. 

- Since only the buyer can finalize, how do you ensure that the seller actually receives the `total`? Are you planning any kind of (off-chain) dispute mechanism?
- ~~You include `volume`, but no indication of the unit of measurement. Would each commodity have its own smart contract so that the unit is the same for all commodity contracts and different for each smart contract?~~ EDIT: I just noticed that you defined `volume` as grams. Then the question becomes: aren't there commodities that are measured in other units, e.g. by volume?
- Have you considered making payments in native tokens? Payments are made in fungible tokens that are created with the smart contract, which adds a lot of friction. In order to buy a contract, I would have to own these specific tokens first, and there is no way to pay with tokens in one smart contract for commodities in another deployment. Also, I don't see any mention of a token in your grant application.

**Review by semuelle — CHANGES_REQUESTED** [review]
@MatteoPerona, could you also look at my [notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ssal_1_semuelle.md) about the tests? Ideally, the unit tests don't just cover the happy paths, and the e2e test failed in my case.

**Comment by MatteoPerona** [comment]
> Hey @MatteoPerona, thanks for the delivery and sorry for the long wait. It took me a bit to understand the logic of the smart contract, as I'm not so familiar with commodities. Everything looks good so far, I just have a few questions about the functionality in general.
> 
>     * Since only the buyer can finalize, how do you ensure that the seller actually receives the `total`? Are you planning any kind of (off-chain) dispute mechanism?

For future iterations, the idea was to implement a sort of on-chain trial system that would decide the fate of the locked balance. I thought this was out of scope for this iteration of the project. Refer to the last point in the future plans section in the [proposal](https://github.com/MatteoPerona/commods-grant-app/blob/master/applications/ssal-commods-dex.md). 

> 
>     * Aren't there commodities that are measured in other units, e.g. by volume instead of weight?

Yes, I realized that weight made more sense than volume through development, so I changed the type but left the variable name. This was an oversight because I had been using the term volume so much throughout the rest of the project. I'll amend that.  

> 
>     * Have you considered making payments in native tokens? Payments are made in fungible tokens that are created with the smart contract, which adds a lot of friction. In order to buy a contract, I would have to own these specific tokens first, and there is no way to pay with tokens in one smart contract for commodities in another deployment. Also, I don't see any mention of a token in your grant application.

Yes, I originally tried to implement payments with native tokens, but, after lots of trial and error and speaking with an Ink! team member, I decided that a native token works better for the purposes of this contract. I wanted the contract to be deployable to any Substrate based chain, and that seems to currently be impossible while using the native token for transactions since I would have to write chain extensions or depend on that infrastructure being set up for each blockchain. I want people to be able to deploy this anywhere and change it for the better; I think it's more pliable in its current state.

**Comment by semuelle** [comment]
Hey @MatteoPerona, thanks for the thorough reply. 

This all sounds very reasonable. The token isn't mentioned in the agreement, so it's really up to you. The tests should be as thorough as possible for the sake of your users. 
Given the size of the grant, I didn't expect you to implement a dispute resolution mechanism. These are just questions that naturally come up when reviewing smart contracts. 

Regarding tokens, yes, using the same token for all smart contracts would make sense and it would probably make it easier to later switch to a native token. I would suggest to implement that right away, but it also depends on what the roadmap for the project looks like beyond the grant. If you were planning to use the smart contracts as they are, feel free to leave it.

**Comment by semuelle** [comment]
pinging @MatteoPerona

**Comment by semuelle** [comment]
Don't worry about the dispute resolution, as it's not part of the agreement. If you can look into the tests and possibly the handling of units, I'd be content.

**Comment by keeganquigley** [comment]
pinging @MatteoPerona

**Comment by MatteoPerona** [comment]
Hi @keeganquigley thanks for pinging. Those last few changes should be completed by Monday. Apologies for the drawn out schedule, I'm really overextended at the moment.

**Comment by MatteoPerona** [comment]
Hey there, 

I just finished making changes. Should I create a new PR? Just not sure because the changes did not affect any of the functionality: just semantics or test related changes. 

Recap:
I changed the volume variable to weight everywhere it is mentioned, and revised both unit and e2e tests. If there is an error message when running e2e tests that should be expected as long as it ends with " ... ok", its from a fail case test. I'm not sure if its common practice to remove them, but I could not find a way to do so. 

Thanks for your patience. Let me know what the next steps are.

**Comment by semuelle** [comment]
> Should I create a new PR?

Hey @MatteoPerona. Since this PR is still open, I don't think it's necessary to open another one. I will review the changes in the coming days. Did you document them anywhere?

**Comment by MatteoPerona** [comment]
Hi @semuelle,

I didn't document more than my commits, but all of my changes are as we discussed:

"change every mention of volume to weight in the code, docs, and article. Also, I will revise the tests, separating happy and unhappy paths and fixing the e2e test error."

The one caveat was that the e2e error was an expected case for an unhappy path.

**Comment by MatteoPerona** [comment]
Pinging @semuelle

**Review by semuelle — APPROVED** [review]
Sorry, @MatteoPerona, your milestone has been accepted, see my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ssal_1_semuelle.md).

**Pull request merged**
