### PR TITLE
Genesis DAO Milestone 1

### PR DESCRIPTION
**Pull request by deep-ink-ventures**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [ ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.

>  We have created a Fiat invoice via the form

- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1383

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_1_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by deep-ink-ventures** [comment]
Thank you @dsm-w3f!

Here are our answers:
 
### System Testing

We will provide a guided walkthrough when we are releasing the frontend implementation based on the hi-def designs, but for the time being we have added an in-depth polkadot.js.org walkthrough here: https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/testing.md#polkadotjsorg-system-test-walkthrough

### Integration Tests

> One integration test was ignored.

That is a test from subtx. We have now disabled this and are discussing this with your team here: 
https://github.com/paritytech/subxt/issues/826

### Code Quality

Please note that in general, you looked at a some components that are not part of the first milestone and under heavy development right now.

> I ran npm run lint and got some warnings.

We fixed all warnings, even in the WIP parts.

> I ran npm test and got low testing coverage.

The uncovered code is part of the second milestone and under development. We are actively developing this part. I asked our dev team to priotize this and they brought test coverage > 60%, but these parts are heavily under work right now.

> Cargo clippy returned some warnings

Fixed.

> The test coverage on the pallets, measured using cargo tarpaulin.

If you look at the output, then you can see that dao-assets/src is included for all 3 crates, but of course only tested in dao-assets. Since dao-assets is much bigger than core or votes, this almost unavoidably leads to low coverage for core and votes. Tarpaulin as well includes autogenerated code like weights.rs of non-functional code like benchmarking.rs.

We optimized this a bit, but in general this is not a good way to measure coverage. 

If you look at the covered lines in the actual code of the pallets, you can see that we have a very high coverage throughout. 

Please note as well that dao-assets and dao-votes are WIP for the next Milestone.

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the improvements and fixes. I updated the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_1_dsm-w3f.md). The software still has some problems. Please let me know when I can continue with this evaluation.

**Comment by deep-ink-ventures** [comment]
Thanks again @dsm-w3f !

> When I ran docker compose up in the frontend got this error ...

I am not able to reproduce this error. 

Are you in the correct folder? The error `Couldn't find a package.json file in "/"` seems to indicate this, because this file is copied into the container [here](https://github.com/deep-ink-ventures/genesis-dao-frontend/blob/main/Dockerfile#L5) and it indeed exists [here](https://github.com/deep-ink-ventures/genesis-dao-frontend/blob/main/package.json).

> The testing guide is missing examples using the frontend, but when I tried to test the frontend it seems to haven't been connected to Genesis DAO Node.

The frontend integration is part of the second milestone (see [here](https://github.com/deep-ink-ventures/Grants-Program/blob/master/applications/GenesisDAO.md#milestone-2-proposal-module-asset-fine-tuning-no-code-dao-creation-and-proposal-ux-flow)). 

For MVP-1 we've created the basic infrastructure and wired it to the node. I've asked our frontend engineer to create a quick walkthrough [here](https://drive.google.com/file/d/1ESjS0jw1q3Tt9jA0S7tuh5rYTQclsVMl/view?usp=sharing).

We are actually close already to have the full implementation ready for the second milestone in a few.

> We notice that you still committing code to the main branch of the repository. Would be nice to freeze a version in a branch for us to complete this evaluation.

Noted. Subsequently we will start working on a new branch for each new milestone!

Happy to jump on a call as well to fix your error and fix remaining questions.

**Comment by dsm-w3f** [comment]
@deep-ink-ventures Regarding the docker error, I flowed the instructions [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/testing.md#built-in-interface) and ran the `docker compose up` command from the root folder of the repository. The error is still happening. Could you please try cleaning the images and containers and building them as instructed in the tutorial? In this way, you may be able to reproduce the error. 

Regarding the integration of the backend and frontend, there is no problem to be fully integrated only in the second milestone. I watched the video and notice a different interface from the one that I'm testing. Could you please provide the commit SHA used to perform the tests presented in the video? In this way, I can try to reproduce them and have a fixed version for this milestone delivery.

**Comment by deep-ink-ventures** [comment]
Thanks.

> Regarding the docker error

I simplified the Dockerfile quite a bit and rerun it on a clean machine and it works for me now, though I was never able to reproduce your error. Can you kindly retry it on the `main` branch? 

If it does not work, could you kindly try to remove the space from your folder name? `yarn` can't handle that, and maybe that causes problem on the copy over, but I don't think that this is the issue. The cleaned Dockerfile should work, just remove the current image and container.

> Could you please provide the commit SHA used to perform the tests presented in the video? In this way, I can try to reproduce them and have a fixed version for this milestone delivery.

We created two branches for you: [pre-feedback](https://github.com/deep-ink-ventures/genesis-dao-frontend/tree/pre-feedback) is the one used to create the video and [m1](https://github.com/deep-ink-ventures/genesis-dao-frontend/tree/m1) is the one with the warnings fixed, it already has first ui parts from the design. Ideally you start them without docker to make sure we don't run into the same problem.

We will make sure that in the future each milestone will be the main branch and we will work on separate branches until the evaluation is over!

**Comment by deep-ink-ventures** [comment]
@dsm-w3f How exciting, we're getting there :-)

The `.env` file depends on how you are running the node. If you compile the node from source and run it as a local binary (`./target/release/genesis-dao --dev` if you are on mac from the repo root), then it should actually work, because we configured this to be [the default](https://github.com/deep-ink-ventures/genesis-dao-frontend/blob/main/src/config/index.ts#L2).

If you are the node from a docker container, then you need to create a network for the two docker containers, because they live in different repos and do not have a shared network. This process is documented [here](https://github.com/deep-ink-ventures/genesis-dao-node/blob/main/docs/testing.md#built-in-interface).

E.g. for me it looks like this:

```env
LOCAL_NODE="ws://172.28.0.1:9944"
```

but the ip address depends on the created network.

Always happy to have a quick call and walk through it together; I can update the docs accordingly if I see what problems you encounter.

**Comment by dsm-w3f** [comment]
@deep-ink-ventures thank you for the explanation. Now worked fine. I let one improvement suggestion in the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/genesisdao_1_dsm-w3f.md). The milestone was approved. I'll forward the invoice internally and the payment should take place within two weeks.

**Comment by fededubbi** [comment]
Hi @deep-ink-ventures,

We noticed on the invoice is missing your crypto address.
Can you please add it and resend the invoice?

Many thanks,
Federica

**Comment by deep-ink-ventures** [comment]
@dsm-w3f Thanks for the suggestion, I created a ticket for our frontend team [here](https://github.com/deep-ink-ventures/genesis-dao-node/issues/49)!

**Comment by deep-ink-ventures** [comment]
@fededubbi I resubmitted the invoice as crypto, if you prefer that over via.

You can find the address as well here, so you don't have to copy it from the pdf:

https://github.com/w3f/Grants-Program/blob/master/applications/GenesisDAO.md

**Comment by fededubbi** [comment]
Hi @deep-ink-ventures,

The one in crypto is okay, but then you have to remove the EUR symbol next to the amount and leave USD.
Does it makes sense?

Many thanks,
Federica

**Comment by RouvenP** [comment]
hi @deep-ink-ventures we transferred the payment today.

**Pull request merged**
