### PR TITLE
 Fractapp Milestone 2: Evaluation 

### PR DESCRIPTION
**Pull request by sapranidi**
The app was tested in Android emulation environment. The UI is logical and is sufficiently intuitive but needs improvement in speed and minor descriptors/UX solutions. External services, such as SMS/email integration work properly. Dev documentation is lacking in some regards, needs additional info about setting up the testing environment.

### CODE REVIEW

**Comment by semuelle** [comment]
Can #117 be closed, then?

**Comment by semuelle** [comment]
Hi @sapranidi, thanks for the evaluation. Could you also check the licenses of any repos and add that as deliverable 0, like in [this example](https://github.com/w3f/Grant-Milestone-Delivery/blame/master/evaluations/apron-network_1_semuelle.md#L11)?

**Comment by sapranidi** [comment]
> Hi @sapranidi, thanks for the evaluation. Could you also check the licenses of any repos and add that as deliverable 0, like in [this example](https://github.com/w3f/Grant-Milestone-Delivery/blame/master/evaluations/apron-network_1_semuelle.md#L11)?

Hi @semuelle! Done.

**Comment by semuelle** [comment]
Thanks. I'll be verifying your evaluation today and get back to you soon.

What do you mean by `Probably required to bump google-services to 4.3.5`?

**Comment by sapranidi** [comment]
When setting up Firebase, it states that the latest version of google-services is 4.3.5. It might be useful to update imported packages from time to time, this is why I included this recommendation.

**Comment by semuelle** [comment]
Thanks for the evaluation, looks good! :fire: 

Someone from our finances team should be in touch with you shortly about your KSM.

**Comment by semuelle** [comment]
@sapranidi: Do you have a Kusama account with [on-chain identity](https://github.com/w3f/Grant-Milestone-Delivery#requirements)?

**Comment by sapranidi** [comment]
Thanks, it was a pleasure to participate!

> Do you have a Kusama account with on-chain identity?
Unfortunately I don't, is it strictly necessary to have one?

**Comment by semuelle** [comment]
We don't have a strict policy on this, but we try to ensure at least to some degree that the evaluator is not part of or related to the team or project being evaluated. 

> If it is, which field should I set in my on-chain identity?

It is currently quite expensive to set an identity on Kusama. Could you email me links to any social media accounts you have?

**Comment by sapranidi** [comment]
Just sent an email to your @web3.foundation address!

**Comment by sapranidi** [comment]
Hi @semuelle, any updates?

**Comment by semuelle** [comment]
Yes, thanks for the email. You should receive 1 KSM in the coming days.

**Comment by semuelle** [comment]
@sapranidi, you should have received 1 KSM: https://kusama.subscan.io/extrinsic/0xedbfa355797aed643f89c1204cdada18dea8ee52f008f604d42d3e72da3d3d10

**Pull request merged**
