### PR TITLE
Create SpellRouter_Milestone_M1.md

### PR DESCRIPTION
**Pull request by dudo50**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2057

### CODE REVIEW

**Comment by dudo50** [comment]
I have noticed, that there has been another change to payments. And BTC is no longer available and our grant was accepted with BTC as a payment option. Please let me know if this needs changing so I can open PR in the grants repository to fix this. I want to switch to FIAT instead then (Please let me know what is needed also for this switch). I have for now submitted an invoice with the original BTC as payment method. (I can submit an updated one if the payment method needs to be updated).

**Comment by niklabh** [comment]
Hey team, i am getting error when running playground:

<pre><font color="#2AA1B3"><b>± </b></font><font color="#26A269">|main U:2 ?:3 </font><font color="#C01C28">✗</font><font color="#26A269">| →</font> yarn dev

  <font color="#26A269"><b>VITE</b></font><font color="#26A269"> v5.0.7</font>  ready in <b>205</b> ms

  <font color="#26A269">➜</font>  <b>Local</b>:   <font color="#2AA1B3">http://localhost:</font><font color="#2AA1B3"><b>5173</b></font><font color="#2AA1B3">/</font>
<font color="#AAAAAA">  </font><font color="#196C46">➜</font><font color="#AAAAAA">  </font><font color="#AAAAAA"><b>Network</b></font><font color="#AAAAAA">: use </font><b>--host</b><font color="#AAAAAA"> to expose</font>
<font color="#196C46">  ➜</font><font color="#AAAAAA">  press </font><b>h + enter</b><font color="#AAAAAA"> to show help</font>
<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;getAllTradingPairs&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:9:
<font color="#D0CFCC">      13 │ import { </font><font color="#26A269">getAllTradingPairs</font><font color="#D0CFCC">, findBestTradeRecursively, StandardLiquidityPool, StableLiquidityPool, PoolType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools,...</font>
<font color="#D0CFCC">         ╵          </font><font color="#26A269">~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;findBestTradeRecursively&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:29:
<font color="#D0CFCC">      13 │ import { getAllTradingPairs, </font><font color="#26A269">findBestTradeRecursively</font><font color="#D0CFCC">, StandardLiquidityPool, StableLiquidityPool, PoolType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools,...</font>
<font color="#D0CFCC">         ╵                              </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;StandardLiquidityPool&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:55:
<font color="#D0CFCC">      13 │ import { getAllTradingPairs, findBestTradeRecursively, </font><font color="#26A269">StandardLiquidityPool</font><font color="#D0CFCC">, StableLiquidityPool, PoolType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools,...</font>
<font color="#D0CFCC">         ╵                                                        </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;StableLiquidityPool&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:78:
<font color="#D0CFCC">      13 │ import { getAllTradingPairs, findBestTradeRecursively, StandardLiquidityPool, </font><font color="#26A269">StableLiquidityPool</font><font color="#D0CFCC">, PoolType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools,...</font>
<font color="#D0CFCC">         ╵                                                                               </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;PoolType&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:99:
<font color="#D0CFCC">      13 │ ...etAllTradingPairs, findBestTradeRecursively, StandardLiquidityPool, StableLiquidityPool, </font><font color="#26A269">PoolType</font><font color="#D0CFCC">, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools, isStab...</font>
<font color="#D0CFCC">         ╵                                                                                             </font><font color="#26A269">~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;encodeSwapParamsForStandardPoolsOnly&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:109:
<font color="#D0CFCC">      13 │ ...estTradeRecursively, StandardLiquidityPool, StableLiquidityPool, PoolType, </font><font color="#26A269">encodeSwapParamsForStandardPoolsOnly</font><font color="#D0CFCC">, encodeSwapParamsForStandardAndStablePools, isStableMultiPathElement, isSt...</font>
<font color="#D0CFCC">         ╵                                                                               </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;encodeSwapParamsForStandardAndStablePools&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:147:
<font color="#D0CFCC">      13 │ ...ol, StableLiquidityPool, PoolType, encodeSwapParamsForStandardPoolsOnly, </font><font color="#26A269">encodeSwapParamsForStandardAndStablePools</font><font color="#D0CFCC">, isStableMultiPathElement, isStableMetaPool, isStandardPool, StableLiqu...</font>
<font color="#D0CFCC">         ╵                                                                             </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;isStableMultiPathElement&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:190:
<font color="#D0CFCC">      13 │ ...lType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools, </font><font color="#26A269">isStableMultiPathElement</font><font color="#D0CFCC">, isStableMetaPool, isStandardPool, StableLiquidityMetaPool, } from &quot;./amm/&quot;;</font>
<font color="#D0CFCC">         ╵                                                                                            </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;isStableMetaPool&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:216:
<font color="#D0CFCC">      13 │ ...lType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools, isStableMultiPathElement, </font><font color="#26A269">isStableMetaPool</font><font color="#D0CFCC">, isStandardPool, StableLiquidityMetaPool, } from &quot;./amm/&quot;;</font>
<font color="#D0CFCC">         ╵                                                                                                                      </font><font color="#26A269">~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;isStandardPool&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:234:
<font color="#D0CFCC">      13 │ ...lType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools, isStableMultiPathElement, isStableMetaPool, </font><font color="#26A269">isStandardPool</font><font color="#D0CFCC">, StableLiquidityMetaPool, } from &quot;./amm/&quot;;</font>
<font color="#D0CFCC">         ╵                                                                                                                                        </font><font color="#26A269">~~~~~~~~~~~~~~</font>

<font color="#C01C28">✘ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js&quot; for import &quot;StableLiquidityMetaPool&quot;</b>

    node_modules/@interlay/interbtc-api/build/esm/src/parachain/amm.js:13:250:
<font color="#D0CFCC">      13 │ ...lType, encodeSwapParamsForStandardPoolsOnly, encodeSwapParamsForStandardAndStablePools, isStableMultiPathElement, isStableMetaPool, isStandardPool, </font><font color="#26A269">StableLiquidityMetaPool</font><font color="#D0CFCC">, } from &quot;./amm/&quot;;</font>
<font color="#D0CFCC">         ╵                                                                                                                                                        </font><font color="#26A269">~~~~~~~~~~~~~~~~~~~~~~~</font>



</pre>

**Comment by niklabh** [comment]
Seems like interlay APIs has changed.

**Comment by dudo50** [comment]
Thanks @niklabh for letting us know, I have tried to replicate your error but I am unable. Could you please provide us with your system specs, operating system you are running, nodejs and yarn versions? 

With kind regards,
Team ParaSpell

**Comment by niklabh** [comment]
> Thanks @niklabh for letting us know, I have tried to replicate your error but I am unable. Could you please provide us with your system specs, operating system you are running, nodejs and yarn versions? Also git log would help us! Thanks!
> 
> With kind regards, Team ParaSpell

Here are the versions:

<pre> <font color="#2AA1B3"><b>2023-12-16 19:05:12 </b></font><font color="#C01C28">⌚ </font><font color="#A2734C"> </font><font color="#A347BA">nikhil-Blade-14-RZ09-0370 </font>in <font color="#26A269">~/w3f/xcm-router</font>
<font color="#2AA1B3"><b>± </b></font><font color="#26A269">|main U:2 ?:3 </font><font color="#C01C28">✗</font><font color="#26A269">| →</font> uname -a
Linux nikhil-Blade-14-RZ09-0370 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 <font color="#2AA1B3"><b>2023-12-16 19:05:16 </b></font><font color="#C01C28">⌚ </font><font color="#A2734C"> </font><font color="#A347BA">nikhil-Blade-14-RZ09-0370 </font>in <font color="#26A269">~/w3f/xcm-router</font>
<font color="#2AA1B3"><b>± </b></font><font color="#26A269">|main U:2 ?:3 </font><font color="#C01C28">✗</font><font color="#26A269">| →</font> yarn -v
3.5.0

 <font color="#2AA1B3"><b>2023-12-16 19:05:20 </b></font><font color="#C01C28">⌚ </font><font color="#A2734C"> </font><font color="#A347BA">nikhil-Blade-14-RZ09-0370 </font>in <font color="#26A269">~/w3f/xcm-router</font>
<font color="#2AA1B3"><b>± </b></font><font color="#26A269">|main U:2 ?:3 </font><font color="#C01C28">✗</font><font color="#26A269">| →</font> node -v
v21.4.0
</pre>

**Comment by niklabh** [comment]
> > Thanks @niklabh for letting us know, I have tried to replicate your error but I am unable. Could you please provide us with your system specs, operating system you are running, nodejs and yarn versions? Also git log would help us! Thanks!
> > With kind regards, Team ParaSpell
> 
> Here are the versions:
> 
>  2023-12-16 19:05:12 ⌚  nikhil-Blade-14-RZ09-0370 in ~/w3f/xcm-router
> ± |main U:2 ?:3 ✗| → uname -a
> Linux nikhil-Blade-14-RZ09-0370 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> 
>  2023-12-16 19:05:16 ⌚  nikhil-Blade-14-RZ09-0370 in ~/w3f/xcm-router
> ± |main U:2 ?:3 ✗| → yarn -v
> 3.5.0
> 
>  2023-12-16 19:05:20 ⌚  nikhil-Blade-14-RZ09-0370 in ~/w3f/xcm-router
> ± |main U:2 ?:3 ✗| → node -v
> v21.4.0

± |main U:2 ?:3 ✗| → git log
commit 613af67601ecbc7f4dd3b6b47a0427ede028bf9c (HEAD -> main, origin/main, origin/HEAD)
Author: Rikkard29 <absolon.mm@gmail.com>
Date:   Fri Dec 15 23:08:06 2023 +0100

    Use published package instead of local 📦

commit 9e6f87e66b3857ea75dc73a4c81301354a3517cf (tag: v0.0.1)
Author: Rikkard29 <absolon.mm@gmail.com>
Date:   Fri Dec 15 23:02:06 2023 +0100

    chore(release): 0.0.1

**Comment by niklabh** [comment]
Hey team, thanks for the high quality delivery of the milestone 1. I have added an external evaluation. https://github.com/w3f/Grant-Milestone-Delivery/pull/1082. Other than playground other features are working fine.

**Comment by dudo50** [comment]
@niklabh , thanks for providing details, we will go ahead and try to resolve this issue today. We will ping you once we have found the problem. Also thanks for the positive comment regarding delivery!

**Comment by dudo50** [comment]
@niklabh one more thing, could you also provide the output of yarn install (When you delete node modules)? It should print that patches were applied (as we have 2 patches, 1 for interlay SDK and 1 for hydradx SDK). The only diff I can see right now between our systems is different yarn versions. We use v1.22, yours is v3.5.0.

Should print following line:
Screenshot 2023-12-16 at 14 51 00

**Comment by dudo50** [comment]
@niklabh, I have tried with your 3.5.0 version of yarn and I was able to replicate your problem. Could you please manually switch to yarn 1.22.1? We will open an issue in their repository for them to patch their work (They are also the reason why pnpm is not working). For now, we have to work with what we have.

This command should help you:
```
cd playground
yarn set version 1.22.1
```

**Comment by niklabh** [comment]
Thanks, This worked.

**Comment by niklabh** [comment]
Updated the evaluation to accepted: https://github.com/w3f/Grant-Milestone-Delivery/pull/1081

Screenshot from 2023-12-16 22-11-21

**Comment by dudo50** [comment]
Thanks @niklabh for thorough evaluation. We have enjoyed this process and experience with you.

With kind regards,
Team ParaSpell

**Comment by semuelle** [comment]
Hey @dudo50. I just confirmed @niklabh's evaluation and your milestone is hereby accepted. Congratulations. As usual, good work!

**Comment by dudo50** [comment]
@semuelle, thanks for your kind words!

One more question for you before we fill invoice:
Please refer to our first comment: 
https://github.com/w3f/Grant-Milestone-Delivery/pull/1081#issuecomment-1858548088

**Comment by semuelle** [comment]
> Please let us know if this needs changing so we can open PR in the grants repository to fix this.

Hey @dudo50. Existing grant agreements don't have to be changed. If you do want to change the payment details, please do so as per the new guidelines. Fiat would be fine, of course.

**Comment by dudo50** [comment]
Thanks @semuelle ,
We have requested change via the following PR: https://github.com/w3f/Grants-Program/pull/2163
We will also submit an updated invoice within an hour from this comment.

**Comment by dudo50** [comment]
@semuelle ,
An invoice with updated payment details (FIAT) was just submitted.

With kind regards,
Team ParaSpell

**Pull request merged**
