### PR TITLE
Submit Polket-ToEarnFun Milestone 2 Delivery

### PR DESCRIPTION
**Pull request by zhiquan911**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1177

### CODE REVIEW

**Comment by takahser** [comment]
Hi @zhiquan911  
Thanks for the delivery, one of our grant evaluators will take a look and provide you with feedback soon.

**Comment by keeganquigley** [comment]
Thanks for the delivery @zhiquan911 I have started my evaluation. So far, tests are all passing and the modules look good. However, when trying to run the docker version I get this error:

```
chown 1000.1000 ~/chain-data -R
chown: 1000.1000: illegal user name
```

I am running locally on my Mac so I don't think it's an issue with the ports, do you know how I can fix this?

I also can't run it apparently on ARM64 architecture. I will run it on a remote Ubuntu machine to see if it runs there.

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
Also, running `cargo clippy` generates quite a few warnings. Can you check to see if any of these can be optimized? Thanks!

**Comment by zhiquan911** [comment]
@keeganquigley Thanks for your feedback.

We have already dealt with the warnings.

This command(`chown 1000.1000 ~/chain-data -R`) should only be executed on linux, you can try to run our docker image with ubuntu.

There may still be some problems connecting to the testnet using the docker image. You can compile the source code, and run a local node, follow the [doc tutorial](https://polketio.gitbook.io/toearnfun/build/how-to-run-toearnfun-app), and test the local network with the `Android emulator`.

**Comment by zhiquan911** [comment]
If you have a problem, feel free to ask me.

**Comment by keeganquigley** [comment]
Many thanks @zhiquan911 and apologies for the delay. I didn't have any Android stuff installed on my MacBook so it took me a while to get up and running for the Android portion. Everything works great and I made it through all entire Android test guide. You can find my eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polket_toearnfun_2_keeganquigley.md). 

The only remaining issue is that there are a ton of warnings when running `cargo clippy` from the `polket-node` folder, including some about useless conversions, unnecessary casting, and too many arguments. Seeing as this will complete the grant, can you take a look to see if any of these can be fixed/optimized? Thanks!

**Comment by zhiquan911** [comment]
@keeganquigley 
Thank you for evaluating our program. I've fixed the optimization suggested by `cargo clippy`. You can check it again.

**Comment by keeganquigley** [comment]
Thanks a bunch @zhiquan911 looks good. I have accepted your delivery. I will forward your invoice internally for payment. Congrats on the grant completion!

**Comment by fededubbi** [comment]
Hi @zhiquan911,

Could you let us know in which currency do you prefer to be paid in?

Many thanks,
Federica

**Comment by zhiquan911** [comment]
Hi @fededubbi 
We want to use ETH-USDC as payment. 
Just use the address on the application as the receiving address.

**Comment by RouvenP** [comment]
hi @zhiquan911 we transferred the payment today.

**Pull request merged**
