### PR TITLE
Deitos Network - Milestone Delivery 2

### PR DESCRIPTION
**Pull request by Ernih**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2040

### CODE REVIEW

**Review by keeganquigley — CHANGES_REQUESTED** [review]
Thanks for the delivery @Ernih I am starting the eval. I noticed that deliverable **1. Proxy Development** is missing. Can you add this to the links as well? Or otherwise point to which code covers this part? Thanks!

**Comment by hbulgarini** [comment]
> Thanks for the delivery @Ernih I am starting the eval. I noticed that deliverable **1. Proxy Development** is missing. Can you add this to the links as well? Or otherwise point to which code covers this part? Thanks!

Hello @keeganquigley! I apologise, i see that we forgot adding the link in the deliverables table for the Proxy. Please note that we have renamed to Deitos Gate (we believe this express better the nature of this component)

The deliverable can be found under the following repository:

https://github.com/Deitos-Network/deitos-gate/tree/w3f-grant-m2-delivery

**Comment by keeganquigley** [comment]
I'm having trouble trying to connect to the node for some reason. Using endpoint `ws://127.0.0.1:9944` I have the chain running. Any ideas? Thanks!

**Comment by hbulgarini** [comment]
> I'm having trouble trying to connect to the node for some reason. Using endpoint `ws://127.0.0.1:9944` I have the chain running. Any ideas? Thanks!

@keeganquigley hmmm, i cannot tell much since the whole setup works for me and also for other team members.

Are you using Linux for testing?

This is the full URL for accessing the node:

https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explorer

Some ideas:

1) Access to the container and check the logs: `docker exec -it deitos-node bash`
2) Check if no other nodes are running in the background or the 9944 port is taken.
3) Check if your disk is not full.
4) Execute the following command to reinstall everything from scratch:

`./clean-all.sh`
`make`
`./start-ip.sh`


Please let us know how it goes after these.

**Comment by keeganquigley** [comment]
Thanks for your help @hbulgarini kept running into issues on Mac but I have an M1 ARM so maybe that's why. I was able to get everything to run successfully on linux. Happy to pass the milestone. Congrats on finishing the grant! Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/deitos-network_2_keeganquigley.md).

**Comment by hbulgarini** [comment]
> Thanks for your help @hbulgarini kept running into issues on Mac but I have an M1 ARM so maybe that's why. I was able to get everything to run successfully on linux. Happy to pass the milestone. Congrats on finishing the grant! Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/deitos-network_2_keeganquigley.md).

Thank you very much Keegan!

**Comment by hbulgarini** [comment]
Hello @keeganquigley ! how is everything going? 

I would like to know if there is any update regarding the payment of this milestone. We have submitted the form as requested.

Thanks!

**Comment by keeganquigley** [comment]
Hi @hbulgarini typically payments take 2 weeks, and since the invoice was submitted on the 27th, it looks like this Weds. would be the two-week mark. Meaning it should be paid by this Friday at the latest. Please let us know if you don't receive it by then! Thanks.

**Comment by hbulgarini** [comment]
> Hi @hbulgarini typically payments take 2 weeks, and since the invoice was submitted on the 27th, it looks like this Weds. would be the two-week mark. Meaning it should be paid by this Friday at the latest. Please let us know if you don't receive it by then! Thanks.

Understood! thanks for the update

**Comment by RouvenP** [comment]
hi @Ernih we sent the payment last Friday

**Pull request merged**
