### PR TITLE
subwallet milestone 2

### PR DESCRIPTION
**Pull request by yxf**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @yxf. Thanks for the delivery and we will try to look into it as soon as possible.

**Comment by Noc2** [comment]
I quickly started to look into your delivery and the documentation about the transfer part seems to be missing: https://github.com/yxf/subwallet#transfer Also, it does not look like there are “unit tests for every command”. And after I installed the latest version, I quickly run the following commands and immediately got the error below (demoDavid is my old account, I used to test the previous version):
```
./subwallet listaddresses
demoDavid       15hy3SQ96oqDrCnWfzxdWPKQDjbsmWmSsDYnH2gK9k8VJoXF        sr25519
./subwallet getbalances
Error: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })
```

**Comment by yxf** [comment]
Hi @Noc2. Thanks for your response. You must set rpc url with `setrpcurl` before use `getbalances`, `syncextrinsics` and `transfer`. The missing `transfer` documentation has been added.  About "unit tests for every command", unit tests of the core functions called by the commands have been written. Additional, the error message is not very friendly, I will improve soon.

**Comment by yxf** [comment]
Hi @Noc2.  Many updates has been submitted, please download the latest version v0.1.3 to evaluate. Thank you very much.

**Comment by Noc2** [comment]
Hi. I can confirm that everything works now. So, I’m happy to tell you that the milestone is a pass! I made some notes regarding the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subwallet_2_Noc2.md) and will forward your invoice internally.

**Comment by yxf** [comment]
@Noc2 Thank you very much.  I will continue to improve the issues you mentioned in notes . More features will be add,  and kusama will be support soon.

**Comment by RouvenP** [comment]
hi @yxf We just sent a test transaction. Could you please confirm if received?

**Comment by yxf** [comment]
> hi @yxf We just sent a test transaction. Could you please confirm if received?

Received 0.01 BTC. Thank you very much.

**Comment by yxf** [comment]
hi @RouvenP  When will the remaining BTC be send?   😄

**Comment by RouvenP** [comment]
hi @yxf apologies for the delay, transfer is done :)

**Comment by yxf** [comment]
> hi @yxf apologies for the delay, transfer is done :)

Received, Thank you very much.

**Pull request merged**
