### PR TITLE
Milestone Delivery: Polkadot-js extension per account auth

### PR DESCRIPTION
**Pull request by Tbaut**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/908.

### CODE REVIEW

**Comment by takahser** [comment]
Thank you for the delivery, @Tbaut. I will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the delivery! We already got an external evaluation of your milestone: https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-js-extension-per-account-auth_1_CrommVardek.md In general, I agree, but would it be possible to publish somewhere a short article about this feature (grantspr could also retweet it)? Maybe including the nice video which you made.

**Comment by Tbaut** [comment]
Thanks, absolutely, I didn't mention it but the article is being proof read right now (it might take up to next week as my colleagues have a lot on their plate right now). I guess it also acts as documentation as it describes what the whole PR does.
The extension is pretty self explanatory and doesn't have any doc (beside the technical one [here](https://polkadot.js.org/docs/extension). If you don't think that the article will be enough, please let me know what you'd expect as documentation. I thought we were originally talking about the code doc, which I added along the way in the merged PR.

**Comment by takahser** [comment]
@Tbaut

> I thought we were originally talking about the code doc, which I added along the way in the merged PR.

Yes, code documentation is sufficient, could you add it to your delivery document?
In general, a delivery doc's milestones should adhere to the corresponding [milestones in the grant application document](https://github.com/w3f/Grants-Program/blob/master/applications/polkadot-js-extension-per-account-auth.md#milestone-1-privacy-enhancement-feature).

> I didn't mention it but the article is being proof read right now

In that case, you can just add a link to a draft of the article or if you prefer, you can wait until the proofreading has been completed. Or another option would be to amend the contract and remove the article from the milestone in the grants contract.

**Comment by Tbaut** [comment]
I'll added 0b and 0e to this delivery. I'll add the link when the article is published, I expect this to be next week, it'll be on Medium.

**Comment by takahser** [comment]
@Tbaut sounds good, thanks for the update!

**Comment by Tbaut** [comment]
Do you need to review/approve the article? I see @Noc2 is ooo until the 26th. The article is a pretty straight forward description of the functionality. Happy to provide a link to the draft on element, you can reach out, my handle is @tbaut:matrix.org

**Review by takahser — APPROVED** [review]
@Tbaut thanks for the note.

- For the record, @Tbaut shared the written article with me and I think it looks well. It's currently in draft state and being proof-read which is why it hasn't been published yet.
- I [accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkadot-js-extension-per-account-auth_1_takahser.md) the delivery and added a note that explains above matter.
- The delivery will be updated, as soon as the article is published.
- Another evaluation, done by @CrommVardek can be found [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/502)

**Comment by takahser** [comment]
@Tbaut did you file your invoice yet? For some reason I'm unable to find it

**Comment by Tbaut** [comment]
If by filing you mean filling the form, then yes the person in charge of accounting at ChainSafe did it. Let me know if we should do it again or maybe we can send it another way.

**Comment by takahser** [comment]
I was able to find the invoice and forwarded it to our invoice team.
@Tbaut has already been informed via Element, so I'm just adding this information here for the sake of completeness.

**Comment by RouvenP** [comment]
hi @Tbaut we transferred the payment yesterday. Thanks!

**Pull request merged**
