### PR TITLE
Aisland-Docsig Milestone 1

### PR DESCRIPTION
**Pull request by poseidon-aisland**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1853

### CODE REVIEW

**Comment by cute0laf** [comment]
@poseidon-aisland 
I've created a new branch for fixing the clippy issues and some test issues in your project.
https://github.com/cute0laf/aisland-node/tree/fix-clippy

**Comment by poseidon-aisland** [comment]
> @poseidon-aisland I've created a new branch for fixing the clippy issues and some test issues in your project. https://github.com/cute0laf/aisland-node/tree/fix-clippy
Many thanks for effort, the point is that it's difficult to review >3.7k of lines changed as shown from git. The main issue that  there are some massive tab shift that increase dramatically  the review effort from our side. The pallet involved in this milestone is only Docsig. It may be nice if you want to reduce the PR to that pallet for now. Thanks again :)

**Comment by cute0laf** [comment]
@poseidon-aisland 
I created a new branch for updating pallet-docsig only.
https://github.com/cute0laf/aisland-node/pull/6

**Comment by poseidon-aisland** [comment]
> @poseidon-aisland I created a new branch for updating pallet-docsig only. [cute0laf/aisland-node#6](https://github.com/cute0laf/aisland-node/pull/6)

Cool, I've approved the commit, you may open a PR to aisland-dao/aisland-node

**Comment by poseidon-aisland** [comment]
> @poseidon-aisland Please update your repository settings to allow incoming PRs.
I've removed the "template" flag coming from substrate for.
You can open a pull requests,I've just tried to open one PR from a temporary account not part of the team. 
You have to fork the project, apply a commit and open the PR from the commit.

**Comment by nikw3f** [comment]
When trying to sign document i am getting error: 

Counterpart has not yet published the public key, he/she should configure the encryption

How to publish public key from countersign?

Also are you only allowing only one other counter signatory?

**Comment by nikw3f** [comment]
How to switch wallet on UI if i have multiple in polkadot js extension?

**Comment by poseidon-aisland** [comment]
> When trying to sign document i am getting error:
> 
> Counterpart has not yet published the public key, he/she should configure the encryption
> 
> How to publish public key from countersign?
The counter part should connect, click on "Settings" icon and click again on "Encryption" Tab, input  password and click the "Save" button, the UI will propose a  transaction to publish the public key.
I've improved the error message as follows:
Screenshot 2023-09-06 at 3 53 39 PM

> 
> Also are you only allowing only one other counter signatory?
Actually, only 2 signatories are allowed By the way,  there is an incoming  [deliverable in milestone 2,](https://github.com/w3f/Grants-Program/blob/34e5a78c094dfb02de997918bb0e7308dc9e548f/applications/Aisland-DocSig.md?plain=1#L224) to allow multiple signatories.

**Comment by poseidon-aisland** [comment]
> How to switch wallet on UI if i have multiple in polkadot js extension?

You can click on "Cancel" at the proposed signature and click again on the wallet connect button. it will move to the next account, here a [short video to show how it works](https://dropbox.aisland.io/index.php/s/FLyesdzPA3s1JD0) (I had to use cloud platform because the size limit over here.)
The information are visible in the background of the polkadot extension.It's not perfectly intuitive, since you  did not notice, so I've opened [a task to change it](https://github.com/aisland-dao/docsig/issues/66) in a modal to select from, when there are multiple accounts injected.

**Comment by poseidon-aisland** [comment]
As further  development regarding the account selection in case you have multiple accounts in your extension, we made a further analysis:
- Talisman wallet, allows the account selection at the first connection.
- Polkadot.js and Subwallet do not allow the account selection.
we checked a few Defi apps:
https://beamswap.io/ does not allow the account selection;
https://stellaswap.com/ does not allow the account selection;
https://coinstats.app/ does not allow the account selection;
https://www.akropolis.io/ does not allow to select the account
**https://polkaswap.io/ is the only one that allows the account selection** as follows:
Screenshot 2023-09-06 at 5 43 13 PM

So we  used polkaswap as reference to change the UI for allowing the account selection. Here is a short video of the update:

https://github.com/w3f/Grant-Milestone-Delivery/assets/87597651/d94bc239-a653-4c41-8056-0d635c0a593f

We have tested the new ui with Polkadot.js, Subwallet and Talisman using multiple accounts or single account.
The repo and [https://docsig.aisland.io](https://docsig.aisland.io) have been updated accordingly.

**Comment by nikw3f** [comment]
2 Unit tests are failing

```
npm test


> docsig-server@1.0.0 test
> jest

  console.log
    http://localhost:3000/templateview?account=5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B&token=e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766&documentid=1

      at Object.log (test.js:361:13)

  console.log
    <p style="text-align:left;">Second test document</p>

      at Object.log (test.js:364:13)

  console.log
    http://localhost:3000/docview?account=5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B&token=e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766&documentid=95

      at Object.log (test.js:375:13)

 FAIL  ./test.js (6.605 s)
  ✓ asymmetric encryption/decryption (27 ms)
  ✓ symmetric encryption/decryption (335 ms)
  ✓ symmetric encryption/decryption failed (292 ms)
  ✓ asymmetric encryption/decryption failed with wrong public key (11 ms)
  ✓ asymmetric encryption/decryption failed with wrong keys pair (17 ms)
  ✓ bytestohex valid
  ✓ bytestohex failed
  ✓ arrayBufferToBase64 valid
  ✓ arrayBufferToBase64 failed
  ✓ base64ToArrayBuffer valid (1 ms)
  ✓ base64ToArrayBuffer failed
  ✓ Api - Signin (32 ms)
  ✓ Api - Signin (5 ms)
  ✓ Api - Fetch Documents - Draft (307 ms)
  ✓ Api - Fetch Documents - Waiting (167 ms)
  ✓ Api - Fetch Documents - Action Required (12 ms)
  ✓ Api - Fetch Documents - Approved (9 ms)
  ✓ Api - Fetch Documents - Rejected (7 ms)
  ✓ Api - Fetch Templates (9 ms)
  ✓ Api - Fetch Templates Tags (9 ms)
  ✓ Api - Fetch Signature Fonts (9 ms)
  ✓ Api - Fetch Public Signature (6 ms)
  ✓ Api - Get Private Key - Not found (6 ms)
  ✓ Api - Update Signature Font (6 ms)
  ✓ Api - Update Document Counterpart  (4 ms)
  ✓ Api - Update Document Description  (6 ms)
  ✕ Api - Download document (5002 ms)
  ✓ Api - Get Template Data (14 ms)
  ✓ Api - Get Template Rendering (34 ms)
  ✕ Api - Get Document Rendering (10 ms)

  ● Api - Download document

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      330 | });
      331 |
    > 332 | test('Api - Download document', async () => {
          | ^
      333 |     const params={
      334 |         account: '5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B',
      335 |         token: 'e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766',

      at Object.test (test.js:332:1)

  ● Api - Get Document Rendering

    TypeError: fetch failed

      374 |     let url="http://localhost:3000/docview"+`?${qs.stringify(params)}`
      375 |     console.log(url);
    > 376 |     const response = await fetch(url,{method: 'GET',},);
          |                      ^
      377 |     const docBlob = await response.text();
      378 |     console.log(docBlob);
      379 |     expect(typeof docBlob).toEqual("string");

      at Object.<anonymous> (test.js:376:22)

    Cause:
    SocketError: other side closed



Test Suites: 1 failed, 1 total
Tests:       2 failed, 28 passed, 30 total
Snapshots:   0 total
Time:        6.621 s, estimated 7 s
Ran all test suites.
```

I think you need to add sample file in upload/ dir

**Comment by nikw3f** [comment]
> 2 Unit tests are failing
> 
> ```
> npm test
> 
> 
> > docsig-server@1.0.0 test
> > jest
> 
>   console.log
>     http://localhost:3000/templateview?account=5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B&token=e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766&documentid=1
> 
>       at Object.log (test.js:361:13)
> 
>   console.log
>     <p style="text-align:left;">Second test document</p>
> 
>       at Object.log (test.js:364:13)
> 
>   console.log
>     http://localhost:3000/docview?account=5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B&token=e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766&documentid=95
> 
>       at Object.log (test.js:375:13)
> 
>  FAIL  ./test.js (6.605 s)
>   ✓ asymmetric encryption/decryption (27 ms)
>   ✓ symmetric encryption/decryption (335 ms)
>   ✓ symmetric encryption/decryption failed (292 ms)
>   ✓ asymmetric encryption/decryption failed with wrong public key (11 ms)
>   ✓ asymmetric encryption/decryption failed with wrong keys pair (17 ms)
>   ✓ bytestohex valid
>   ✓ bytestohex failed
>   ✓ arrayBufferToBase64 valid
>   ✓ arrayBufferToBase64 failed
>   ✓ base64ToArrayBuffer valid (1 ms)
>   ✓ base64ToArrayBuffer failed
>   ✓ Api - Signin (32 ms)
>   ✓ Api - Signin (5 ms)
>   ✓ Api - Fetch Documents - Draft (307 ms)
>   ✓ Api - Fetch Documents - Waiting (167 ms)
>   ✓ Api - Fetch Documents - Action Required (12 ms)
>   ✓ Api - Fetch Documents - Approved (9 ms)
>   ✓ Api - Fetch Documents - Rejected (7 ms)
>   ✓ Api - Fetch Templates (9 ms)
>   ✓ Api - Fetch Templates Tags (9 ms)
>   ✓ Api - Fetch Signature Fonts (9 ms)
>   ✓ Api - Fetch Public Signature (6 ms)
>   ✓ Api - Get Private Key - Not found (6 ms)
>   ✓ Api - Update Signature Font (6 ms)
>   ✓ Api - Update Document Counterpart  (4 ms)
>   ✓ Api - Update Document Description  (6 ms)
>   ✕ Api - Download document (5002 ms)
>   ✓ Api - Get Template Data (14 ms)
>   ✓ Api - Get Template Rendering (34 ms)
>   ✕ Api - Get Document Rendering (10 ms)
> 
>   ● Api - Download document
> 
>     thrown: "Exceeded timeout of 5000 ms for a test.
>     Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
> 
>       330 | });
>       331 |
>     > 332 | test('Api - Download document', async () => {
>           | ^
>       333 |     const params={
>       334 |         account: '5FYib34nmpSpmkarhh2oxuvkVgknNF4QMQAx493zNpmgpj8B',
>       335 |         token: 'e7e8c39d179b02402094cfa2b528231375ed47186d38a247dfaf773956256766',
> 
>       at Object.test (test.js:332:1)
> 
>   ● Api - Get Document Rendering
> 
>     TypeError: fetch failed
> 
>       374 |     let url="http://localhost:3000/docview"+`?${qs.stringify(params)}`
>       375 |     console.log(url);
>     > 376 |     const response = await fetch(url,{method: 'GET',},);
>           |                      ^
>       377 |     const docBlob = await response.text();
>       378 |     console.log(docBlob);
>       379 |     expect(typeof docBlob).toEqual("string");
> 
>       at Object.<anonymous> (test.js:376:22)
> 
>     Cause:
>     SocketError: other side closed
> 
> 
> 
> Test Suites: 1 failed, 1 total
> Tests:       2 failed, 28 passed, 30 total
> Snapshots:   0 total
> Time:        6.621 s, estimated 7 s
> Ran all test suites.
> ```
> 
> I think you need to add sample file in upload/ dir

This can be solved by adding a sample file in upload/ folder. Without it test server is crashing

**Comment by poseidon-aisland** [comment]
> 2 Unit tests are failing
> I think you need to add sample file in upload/ dir

right, I've fixed the unit tests adding the 2 files in test-upload and where are copied from during the test.
please pull the update, I've tested it in a clean folder and all 30 tests are passed now.

**Comment by nikw3f** [comment]
Thanks for the delivery @poseidon-aisland Good Work! You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Aisland-DocSig_1_nikw3f.md) here. Happy to pass the milestone, and looking forward to the results of Milestone 2 with new features and more pallet tests.

**Review by nikw3f — APPROVED** [review]

**Comment by poseidon-aisland** [comment]
> Thanks for the delivery @poseidon-aisland Good Work! You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Aisland-DocSig_1_nikw3f.md) here. Happy to pass the milestone, and looking forward to the results of Milestone 2 with new features and more pallet tests.

Thanks, I've noted the improvements suggested and we will add in the milestone 2.

**Comment by nikw3f** [comment]
Hello @poseidon-aisland can you please send some tokens to `5FcHSt2NMUban4vY3Rjb32pa1gyHYe1nJDq2LVhEwg1j4DME` and `5F9AJGzuNRdTJWC8ok5sQXuRBUG3ihiYJxZH4PYKZcZ4J9Xa` for testing extrinsic on chain.

**Comment by poseidon-aisland** [comment]
> Hello @poseidon-aisland can you please send some tokens to `5FcHSt2NMUban4vY3Rjb32pa1gyHYe1nJDq2LVhEwg1j4DME` and `5F9AJGzuNRdTJWC8ok5sQXuRBUG3ihiYJxZH4PYKZcZ4J9Xa` for testing extrinsic on chain.

Done, you have 100 tokens each account.

**Comment by nikw3f** [comment]
When saving encryption password don't save password in db before transaction is success on chain. This is causing an issue that password seems set in UI but it is actually not set when extrinsic failed due to inability to pay fee. Next time UI don't show the option to set the password.

**Comment by poseidon-aisland** [comment]
> When saving encryption password don't save password in db before transaction is success on chain. This is causing an issue that password seems set in UI but it is actually not set when extrinsic failed due to inability to pay fee. Next time UI don't show the option to set the password.

Noted, let me fix it.

**Comment by poseidon-aisland** [comment]
> > When saving encryption password don't save password in db before transaction is success on chain. This is causing an issue that password seems set in UI but it is actually not set when extrinsic failed due to inability to pay fee. Next time UI don't show the option to set the password.
> 
> Noted, let me fix it.

I've pushed the fixing to the repo and updated https://docsig.aisland.io. I've tested the failed tx situation reported and now it's working smoothly both locally and docsig.aisland.io.

**Comment by fededubbi** [comment]
Hi @poseidon-aisland,

Could you please add also your address under your name?

Many thanks,
Federica

**Comment by fededubbi** [comment]
The personal residency address.

Many thanks,
Federica

**Comment by poseidon-aisland** [comment]
> The personal residency address.
> 
> Many thanks, Federica

May I send it by email? It's not nice to public the personal home address here.

**Comment by nikw3f** [comment]
Thanks for the delivery @poseidon-aisland Good Work! You can find my finished [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Aisland-DocSig_1_nikw3f.md) here. Happy to pass the milestone, and looking forward to the results of Milestone 2 with new features and more pallet tests.

**Comment by RouvenP** [comment]
hi @poseidon-aisland we just transferred the payment.

**Comment by poseidon-aisland** [comment]
> hi @poseidon-aisland we just transferred the payment.

Many thanks, we have received it.

**Pull request merged**
