### PR TITLE
Yatima Milestone 1

### PR DESCRIPTION
**Pull request by johnchandlerburnham**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md). 

Link to the application PR: https://github.com/w3f/Grants-Program/pull/463

### CODE REVIEW

**Comment by johnchandlerburnham** [comment]
Since the PR run failed, want to double check that my invoice form has been successfully received. Happy to resubmit if not.

**Comment by semuelle** [comment]
Hi @johnchandlerburnham. Thanks for the delivery. We will look into it as soon as possible. Your invoice form submission has been received, thanks!

**Comment by johnchandlerburnham** [comment]
Hi @semuelle @mmagician, just wanted to ping on this again and ask if you guys have everything you need to review our submission. Our next milestone delivery is coming up in a week and a half, so wanted to understand a bit better what the process is.

**Comment by mmagician** [comment]
Hey @johnchandlerburnham , thanks for checking up here. I've already started looking at your delivery and will submit feedback by the end of the week. Thanks for your patience!

**Comment by mmagician** [comment]
Could you outline the reasoning behind "forking" the multihash repo? Unless I'm missing something, [it should already support `no_std`](https://github.com/multiformats/rust-multihash/blob/master/src/lib.rs#L24).

Also, are you aware of [arkworks](https://github.com/arkworks-rs/std/blob/master/src/io/mod.rs) implementation of `io::Cursor`? While I haven't done a line-by-line comparison between your repos, the `Read` and `Write` implementations look functionally equivalent, although `Seek` is missing from `arkworks`.

I'm just trying to make sure we don't re-invent the wheel.

Could you make sure that the "forks" are actual forks please? I see that you kept the commit history, but right now it takes more effort than it should, in my opinion, to compare the changes that you introduced.

Finally, I think there is a small misunderstanding of what a `substrate module` is: it isn't a standard Rust module, see [here](https://substrate.dev/docs/en/knowledgebase/runtime/pallets#what-is-a-pallet). What you submitted as part of deliverable 1 would rather be considered a substrate primitive (you also did prefix it `sp`, which is what it stands for). Now, in your case it would be fairly trivial to submit an actual pallet (basically expose all the available methods, as you showcased in your template pallet), but I don't think it is strictly necessary at this stage. Please address my previous comments and let's revisit the pallet/primitive detail later.

**Comment by johnchandlerburnham** [comment]
> Could you outline the reasoning behind "forking" the multihash repo? Unless I'm missing something, it should already support no_std.

Sure, so we forked rust-multihash primarily because we needed functionality which was only implemented there for the `std` feature flag, but not for `no-std`. For example,

https://github.com/yatima-inc/sp-multihash/blob/9f29cc6b6b412b90e0acd10eb320369fa17dca66/src/multihash.rs#L250
https://github.com/multiformats/rust-multihash/blob/98f8c768b40c863e8298c642408e7ef07d53605d/src/multihash.rs#L243

You can also take a look at this branch I just pushed on `sp-cid` showing this: https://github.com/yatima-inc/sp-cid/tree/jcb/multihash-without-read-write, which will error with missing functions if you try to build it. This is why we added `bytecursor`.

The other reason for `sp-multihash` specifically that there is a small build system issue with multihash which doesn't link glibc correctly on NixOS, so we added a Nix build. We also minorly improved some docs.


> Also, are you aware of arkworks implementation of io::Cursor? While I haven't done a line-by-line comparison between your repos, the Read and Write implementations look functionally equivalent, although Seek is missing from arkworks.

I wasn't aware of arkworks, but it looks mostly similar, since we probably both just copied from std and then made the necessary changes. 


Your comment about not re-inventing the wheel is apt, and this was/is a concern we've had about our approach. It seems currently like `no_std` in the Rust ecosystem is essentially an "opt-in" (i.e. extra work) for library maintainer and consequently there are a ton a libraries which are `std` but don't necessarily have to be. However, we thought that convincing all these other libraries to adopt our specific dependency and platform requirements wouldn't be feasible, so we decided to just fork and take on the`no_std` maintenance responsibilities ourselves. It shouldn't be too hard in future to upstream though if that's desirable.

However, our libraries are distinct now from their original upstreams, and might well evolve differently given changing requirements at the `sp_yatima` language level (e.g. Nix builds). This is why we didn't publish them as "Github forks". However we did make sure to preserve commit history, repo metadata and to follow all licenses.

>  small misunderstanding of what a substrate module is

Okay, let us know what you want us to change there, or how you want us to package the template pallet to best fit the conventions.

**Comment by johnchandlerburnham** [comment]
@mmagician Do you also have comments for us on items 1a through 1c (`sp-ipld`, `dag-json`, `sp-cid`)? We'd love to be able to incorporate your feedback into our Milestones 2 submission next week, since the deliverables there are structurally similar in many respects.

**Comment by mmagician** [comment]
@johnchandlerburnham Thanks for a detailed explanation of your design choices. I do get a similar impression regarding usage of `no_std`, although my approach (as an outsider to your project) would probably have been proper forking and trying to merge upstream, which, as you point out, might not always work, but I think it's worth a try to contribute back. That said, I also respect your decisions and I'll be happy to accept the first milestone. I will try to submit an official evaluation today and merge this PR. 

Regarding the rest of the deliverables, I would only make the same points as per multihash - to fork and try to contribute upstream - but I assume the same logic would apply as per your previous comment re multihash, so all good.

**Comment by mmagician** [comment]
Congratulations on completing the first milestone! You can find the full evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/yatima_1_mmagician.md).

**Pull request merged**
