### PR TITLE
Cryptex Milestone #3

### PR DESCRIPTION
**Pull request by driemworks**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1660

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@driemworks thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

**Comment by carloskiron** [comment]
> @driemworks thank you for the milestone delivery. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_3_dsm-w3f.md) and provide proper answers and fixes. After that, let me know when I can continue this evaluation.

Thanks @dsm-w3f in relation to the ui issue, could you share with us the .env file you put in place? this will help us find the roort cause of your issue. Thanks!

**Comment by driemworks** [comment]
The issue with the contract tests is resolved. I've sent tokens to your address as well.

**Comment by dsm-w3f** [comment]
@carloskiron .env.local, the first variable is the proxy address
```
NEXT_PUBLIC_CONTRACT_ADDRESS="5Egh67rszZYc6WZxQLtnQzZxk3Tpwqq5vxcXGEPgSwU4uCAu"
NEXT_PUBLIC_NODE_DETAIL="ws://127.0.0.1:9944"
```

**Comment by driemworks** [comment]
@dsm-w3f the .env configuration looks as expected. We resolved the error you were seeing logged in etf-auction-ui Specifically, next.js attempts to read the etf-sdk wasm when it imports etf.js (etf-sdk is a transitive dependency), however next.js expects that our assets are hosted in a CDN, so it tries to fetch the wasm from `/_next`, which results in an invalid URL (again, since we have not configured a CDN). However, the etf-auction-ui doesn't actually need to fetch that wasm since it's packaged with etf.js, so although it logged an error there is no impact to functionality. It should also be noted that when built as a static site (i.e. our 'official' build hosted at https://auction.idealabs.network), the error does not occur.  Please proceed with your evaluation.

**Comment by carloskiron** [comment]
Btw @dsm-w3f something we forgot to mention in our previous reply is that the changes we did to solve the issues in the UI require an npm install again. It's better if you delete the nodes_modules folder and start over.

**Comment by dsm-w3f** [comment]
@carloskiron and @driemworks thank you for the improvements and fixes. We made some progress in the evaluation but there are still some points to fix and adjust. Please see [the evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_3_dsm-w3f.md) for the updates. Let me know when I can continue this evaluation.

**Comment by driemworks** [comment]
I can't be sure but it's likely the error you saw when running from your local was due to an NFT id collision (we don't validate anything before attempting to mint currently, so that's a possibility). 

I've addressed all the other issues you were seeing, specifically the doc typo is fixed [here](https://github.com/ideal-lab5/etf-auction-ui#configure-env) and the 'min bid' display has been corrected. As for the error messages: 

- the RPC-CORE error was a result of not running an archive node. After updating the pruning config, we no longer see the error logged. 
- The CONTRACTS error is a little more complicated. The error was coming from [here](https://github.com/polkadot-js/api/blob/6fcd984205e302a60b3242a568bf791c452be869/packages/api-contract/src/Abi/index.ts#L167C10-L167C10) in api-contracts. It expects a contract to have at least one event defined. However, our tlock proxy contract emits no events, instead we are handling results returned from calls to the contract functions (while vickrey_auction and erc721 both do emit events). After adding an event, the error is removed. [related open issue](https://github.com/paritytech/ink/issues/1000)

the latest deployed contract id's are: 
proxy: 5FxQpbpTqNgmdCTxvo21UKooMEWYceFAYtK38TA12EuJjTh6
erc721: 5CATVMp5sdBnJFqMBT8xno2cNf8k9V2swnCNHNNtn1jBpJrf

**Comment by driemworks** [comment]
@Noc2 I noticed this [change to the team](https://github.com/w3f/Grants-Program/commit/f0bc40076637fcea398c2557be1675aec9e5d6bc) and wondering how reviewer reassignment/re-review works.

**Comment by keeganquigley** [comment]
Thanks @driemworks yes there has been a recent personnel change. I can take over this delivery evaluation but please note that it may be a couple days before I can resume it since we now have a backlog. Shouldn't be longer than that since you are near the top of the queue :)

**Comment by keeganquigley** [comment]
@driemworks Could you send some test tokens to this address? `5H1SgrToMp1RYhbUjzQmVxpRGRvo3s2j4xKUjCWJ9GQAVREM` thanks!

**Comment by driemworks** [comment]
@keeganquigley sent!

**Comment by keeganquigley** [comment]
Thanks for your patience while I got up to speed. So far, all of the previous errors have been resolved, and I can get the node running. I can also use the UI to create an auction and place bids. 

However, one test still fails when running `cargo +nightly test`:

```rust
test tests::beefy_reports_equivocations ... FAILED
test tests::gossipped_finality_proofs ... ok
test tests::lagging_validators ... ok
test tests::should_initialize_voter_at_latest_finalized ... ok
test worker::tests::should_vote_target ... ok
test worker::tests::test_oracle_accepted_interval ... ok
test worker::tests::vote_on_mandatory_block ... ok
test worker::tests::vote_on_min_block_delta ... ok
test worker::tests::vote_on_power_of_two ... ok
test worker::tests::vote_on_target_block ... ok
test tests::correct_beefy_payload ... ok
test worker::tests::should_finalize_correctly ... ok
test worker::tests::should_init_session ... ok
Nov 02 00:04:27.811 ERROR gossip: Got message from unregistered peer who=12D3KooWT1x2Bjb2Z4E3ZJJSp1bh9ehWpkn6yauPbxT1i7LeDcLN protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
Nov 02 00:04:27.812 ERROR gossip: Got message from unregistered peer who=12D3KooWCYjWzrkzTg1samBXhesJko9hWmJq5J2s6p3J9zm45xtn protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
Nov 02 00:04:27.812 ERROR gossip: Got message from unregistered peer who=12D3KooWQMMxRFZbeRr5DkEEkgDyQsrnydUbKeaMeKq8duuQ4LnV protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
Nov 02 00:04:27.815 ERROR gossip: Got message from unregistered peer who=12D3KooWT1x2Bjb2Z4E3ZJJSp1bh9ehWpkn6yauPbxT1i7LeDcLN protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
Nov 02 00:04:27.816 ERROR gossip: Got message from unregistered peer who=12D3KooWCYjWzrkzTg1samBXhesJko9hWmJq5J2s6p3J9zm45xtn protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
Nov 02 00:04:27.816 ERROR gossip: Got message from unregistered peer who=12D3KooWQMMxRFZbeRr5DkEEkgDyQsrnydUbKeaMeKq8duuQ4LnV protocol=/0000000000000000000000000000000000000000000000000000000000000000/beefy/2
test tests::should_initialize_voter_when_last_final_is_session_boundary ... ok
test worker::tests::keystore_vs_validator_set ... ok
test worker::tests::should_not_report_bad_old_or_self_equivocations ... ok
test tests::on_demand_beefy_justification_sync ... ok

failures:

---- tests::beefy_reports_equivocations stdout ----
thread 'tests::beefy_reports_equivocations' panicked at client/consensus/beefy/src/tests.rs:1274:5:
assertion `left == right` failed
  left: 0
 right: 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::beefy_reports_equivocations

test result: FAILED. 47 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 18.74s

error: test failed, to rerun pass `-p sc-consensus-beefy --lib`
```
There are also a number of warnings when running `cargo clippy`. Can you check to see if these can be easily fixed?

**Comment by driemworks** [comment]
The `cargo clippy` warnings are as a result of using a somewhat outdated fork of substrate (~4 months old or so, from when we started work on the grant). After the grant is completed we're going to separate our consensus modules into their own repo and update to the new dependencies in the polkadot-sdk monorepo, which I suspect would resolve the clippy warnings. I have verified that it does not call out anything in the sc-consensus-aura, in our runtime config, or in our new pallet.

About the test failure, I'm not sure why that would happen. Our changes wouldn't have had an impact on those tests. I executed it locally against the etf branch and it passed.  Can you run the test by itself to verify? I know it's a tokio test, so perhaps an issue with the async execution.

image

**Comment by keeganquigley** [comment]
Thanks @driemworks here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/cryptex_3_dsm-w3f.md). I'm not too worried about it since it is just dealing with node gossip. It could be something on my end. Everything is working as expected, and I could use the app both locally and on the testnet version. I'm happy to pass the milestone. Congrats on finishing the grant! Nice work!

**Pull request merged**
