### PR TITLE
Tuxedo Parachain - Milestone 2

### PR DESCRIPTION
**Pull request by JoshOrndorff**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1932

### CODE REVIEW

**Comment by keeganquigley** [comment]
Hi @JoshOrndorff sorry for the delay, I was OOO for a few days. Everything is working well so far except for running the Docker version for some reason doesn't give me a starting balance of 100:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[2024-05-09T15:19:59Z INFO  tuxedo_template_wallet::sync] Initializing fresh sync from genesis 0x3a16225d2acfce0a9524a029f139c1eb0d0377ddacc253efdba0e8074b151093
[2024-05-09T15:19:59Z INFO  tuxedo_template_wallet] Number of blocks in the db: 0
[2024-05-09T15:19:59Z INFO  tuxedo_template_wallet] Wallet database synchronized with node to height 102
Balance Summary
--------------------
total      : 0
```
Since it says "most platforms", is it supposed to be able to run on Mac? I'll try on Linux too...

**Comment by JoshOrndorff** [comment]
This is because the wallet no longer includes the development keys by default (inspired by polkadot js). You have to add `--dev` to the wallet to do that. So your command should be, for example:

```bash
$ docker run --network host ghcr.io/off-narrative-labs/tuxedo-wallet:main --dev show-balance
```

Of course you can actually create your own private keys too. You can learn more about all of this in the [Wallet's guided tour](https://github.com/Off-Narrative-Labs/Tuxedo/tree/main/wallet#guided-tour) as well if you want. But for tutorials and testing it is easiest to just add `--dev`.

I've updated the docs throughout the Tuxedo repo to reflect this in https://github.com/Off-Narrative-Labs/Tuxedo/pull/215. Thank you for catching it :pray:

**Comment by keeganquigley** [comment]
Nice thanks @JoshOrndorff that worked, I get a balance now when the node is running:

```rust
ubuntu@ip-172-31-22-134:~$ docker run --network host ghcr.io/off-narrative-labs/tuxedo-wallet:main --dev show-balance
[2024-05-20T22:20:17Z INFO  tuxedo_template_wallet::sync] Initializing fresh sync from genesis 0x3a16225d2acfce0a9524a029f139c1eb0d0377ddacc253efdba0e8074b151093
[2024-05-20T22:20:17Z INFO  tuxedo_template_wallet] Number of blocks in the db: 0
Balance Summary
0xd2bf…df67: 100
--------------------
total      : 100
[2024-05-20T22:20:17Z INFO  tuxedo_template_wallet] Wallet database synchronized with node to height 28
```

**Comment by keeganquigley** [comment]
Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/tuxedo-parachain_2_keeganquigley.md). I'm happy to pass the milestone. Great job as usual and looking forward to the next one.

**Pull request merged**
