### PR TITLE
Create Polkawatch_milestone_1.md

### PR DESCRIPTION
**Pull request by rvalle**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/766

### CODE REVIEW

**Comment by rvalle** [comment]
As recommended in the guidelines:

Note we have created the tag ```W3F_MILESTONE_1``` for this delivery
All links in the delivery point to that tag.

What the testing manual does not say specifically is that after cloning the repo you will need to switch to that tag:

```git checkout W3F_MILESTONE_1```

As we will continue to work on the repo.

**Comment by semuelle** [comment]
Hi @rvalle,
I reviewed your milestone and I'm happy to report that it is accepted. Everything worked out of the box. Thank you for the excellent documentation, scripts and tooling. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/polkawatch_1_semuelle.md).

Looking forward to your next milestone. I will forward your invoice for processing.

**Comment by rvalle** [comment]
@semuelle @Noc2 thank you for a great program.

**Comment by RouvenP** [comment]
hi @rvalle we transferred the payment today. Thanks!

**Comment by rvalle** [comment]
@RouvenP thanks, confirmed.

**Pull request merged**
