### PR TITLE
TogetherCrew: Community Health Check

### PR DESCRIPTION
**Pull request by katerinabc**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1482

### CODE REVIEW

**Comment by katerinabc** [comment]
The Twitter vibez dashboard will contain 3 sections: basic engagement, friendship and community type. In the friendship section we make a distinction between supporters and ambassadors. The community type shows users if they have a healthy Twitter community or an audience.

Link to milestone: https://github.com/RnDAO/tc-Documentation/blob/master/Twitter-vibes/Twitter_Community_Vibes.md

**Comment by randombishop** [comment]
Thanks for the delivery @katerinabc !
Will review in next few days and get back to you with feedback...

**Comment by katerinabc** [comment]
> Thanks for the delivery @katerinabc ! Will review in next few days and get back to you with feedback...

I was wondering if you have feedback for us. Thanks.

**Comment by randombishop** [comment]
Sorry didn't have time to start yet but I will eval before end of this week

**Comment by randombishop** [comment]
Hi @katerinabc !

I reviewed the article and I found it very interesting. The approach is clearly defined and an excellent start to kick-off the dashboard development.

But I have a concern that it's too generic and doesn't deliver anything Polkadot specific yet.

From the milestone specification:
```
We will build a directed network, where nodes are always Twitter users. From a network assembly perspective, we will not differentiate between accounts representing people and those representing communities or organizations. The edges between an user profiles are either a reply, quote, mention, retweets, or likes. Thus, a tie from user A to user B exists if (1) user A replies to user B, user A quotes user B, user A mentions user B, user A retweets user B, or user A likes user B's tweet. At this moment, we will created weighted edges, not making a conceptual difference between the interaction type (reply, quote, mention, retweets and likes)
```

My expectation was to find actual Polkadot/Kusama network data at this stage; but instead there are just the definitions of how the graph will look like.

I will discuss with the rest of the team on Monday to check if we can accept this delivery as-is. 

In the meantime, would you consider making progress in the actual network building and add some Polkadot/Kusama specific information to the article? For example, how many nodes are in the graph? how they were selected? 

Thank you!

**Comment by katerinabc** [comment]
> My expectation was to find actual Polkadot/Kusama network data at this stage; but instead there are just the definitions of how the graph will look like.

There might have been a misunderstanding as I expected to deliver a technical document about how we are building it. 

> Would you consider making progress in the actual network building and add some Polkadot/Kusama specific information to the article? For example, how many nodes are in the graph? how they were selected?

This should be possible. I'll be able to let you know if this is possible in 48 hours.

**Comment by randombishop** [comment]
Thank you very much @katerinabc ! Appreciate your extra effort

**Comment by katerinabc** [comment]
@randombishop The milestone 1 document will be updated by the end of next week.

**Comment by semuelle** [comment]
pinging @katerinabc

**Comment by katerinabc** [comment]
Not sure I understand

**Comment by katerinabc** [comment]
@randombishop We're delayed on getting the data for Polkadot + Kusama as we were all working on getting the community health check app for discord released.

**Comment by keeganquigley** [comment]
Hi @katerinabc an additional note:

I noticed that your license file contains a short header that is [meant to be applied](https://www.apache.org/licenses/LICENSE-2.0) to specific source files being used in your work. Per the Apache 2.0 [policy](https://www.apache.org/legal/apply-license.html#copy-per-file), each repository should contain one full copy of the license, in the license file. Can you please update this to include the full text? Here is an [example](https://github.com/bsn-si/rubeus-client/blob/main/license). Thanks!

**Comment by keeganquigley** [comment]
pinging @katerinabc for an update :)

**Comment by keeganquigley** [comment]
Hi @katerinabc are you still working on this delivery? If you can update/fix the license file I will check with the team again to see if we can accept the delivery as is.

I'll try reaching out to you on Twitter as well. Thanks!

**Comment by katerinabc** [comment]
@keeganquigley I can update the header in the license file. @randombishop asked for some changes which we have not yet been able to deliver due to changes in the Twitter API. I was assuming that the practical work will only be done for milestone 2. Re-reading the messages, I'm assuming these are the requested changes. Please confirm. 

Request 1:
Include basic information about the Polkadot and Kusama network. For example, how many nodes are in the graph? how they were selected? (https://github.com/w3f/Grant-Milestone-Delivery/pull/864#issuecomment-1565062468; My expectation was to find actual Polkadot/Kusama network data at this stage; but instead there are just the definitions of how the graph will look like.)

Request 2: 
Add the license file to each header in the repo and include the full text (see the [example](https://github.com/bsn-si/rubeus-client/blob/main/license).

**Comment by keeganquigley** [comment]
Thanks for the update @katerinabc much appreciated.

Request 1: Yes I can confirm that those were the changes I was referring to. Pardon me as I took over this delivery for my colleague. After re-reading your application I agree that no technical work was required as part of the first milestone. If you can fix the license file, I will consult with the committee internally to see if we can accept it as is.
Request 2: No, I am just asking to include the full text in your [license file](https://github.com/RnDAO/tc-Documentation/blob/master/Twitter-vibes/LICENSE.md). Currently it is just the header. I will comment below to show you where I am referring to.

**Comment by katerinabc** [comment]
@keeganquigley I can update the header in the license file. @randombishop asked for some changes which we have not yet been able to deliver due to changes in the Twitter API. I was assuming that the practical work will only be done for milestone 2. Re-reading the messages, I'm assuming these are the requested changes. Please confirm. 

Request 1:
Include basic information about the Polkadot and Kusama network. For example, how many nodes are in the graph? how they were selected? (https://github.com/w3f/Grant-Milestone-Delivery/pull/864#issuecomment-1565062468; My expectation was to find actual Polkadot/Kusama network data at this stage; but instead there are just the definitions of how the graph will look like.)

Request 2: 
Add the license file to each header in the repo and include the full text (see the [example](https://github.com/bsn-si/rubeus-client/blob/main/license).

**Comment by katerinabc** [comment]
I've updated the license file to include the full license text and not just the header information

**Comment by keeganquigley** [comment]
Thanks for the changes @katerinabc, much appreciated. The first milestone only contains the article, and since the delivery technically meets the requirements, I'm willing to accept it. But I agree that the research is rather generic. For the second milestone, it would be nice to see to see some data relating specifically to the Polkadot ecosystem. You can find the evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/community-health-check_1_keeganquigley.md). I will forward your invoice for processing.

**Pull request merged**
