### PR TITLE
P2P State Channels Milestone 2 

### PR DESCRIPTION
**Pull request by lukastanisic99**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2350

### CODE REVIEW

**Comment by lukastanisic99** [comment]
Just submitting officially for milestone 2 - I've added the article to be evaluated here as advised by @semuelle - Will be published on medium when we need to coordinate the announcement.

**Comment by PieWol** [comment]
Hey @lukastanisic99 ,
thanks for your submission. please fix the application PR link :)

**Comment by lukastanisic99** [comment]
@PieWol done 😁

**Comment by PieWol** [comment]
Hey @lukastanisic99 
sorry for the delay, we have a lot going on at the moment. I will start evaluating this delivery on monday. Hope that works for you.

**Comment by lukastanisic99** [comment]
Sure - it's the same state of the repository as the first milestone which you evaluated (just referencing different files) - it's submitted a few days later since we were waiting for feedback on the article, but seems the feedback will be part of this evaluation 🙂

**Comment by PieWol** [comment]
Hey @lukastanisic99 ,
what's the testing guide for this milestone?

**Comment by lukastanisic99** [comment]
Hey @PieWol it's the same testing guide since it's the same state of the repository (we didn't really look at it as milestone 1,milestone 2 when designing - was more for accounting purposes) but the integration tests are relevant - think I explained the reasoning in the guide

**Comment by PieWol** [comment]
Alright. @lukastanisic99 I have created a PR for the evaluation.

https://github.com/w3f/Grant-Milestone-Delivery/pull/1229

There are only 2 points I raised and I would appreciate it if you could improve these. Thanks.

**Comment by lukastanisic99** [comment]
@PieWol I've commented on the PR and pushed changes - also rewrote the article. Please read it and let me know if you have any recommendations to improve it further. I wanted to keep it simple so everyone can understand not just engineers (hope I achieved that).

**Comment by PieWol** [comment]
Thanks for quickly fixing the little points I raised last week. I'm already looking forward to you establishing p2p gaming and much more with this tech on Polkadot ;)

**Pull request merged**
