### PR TITLE
PHP Substrate API M1+2

### PR DESCRIPTION
**Pull request by tejbahadursingh**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [ ] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

https://github.com/w3f/Grants-Program/pull/655

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the delivery. However, could you update the formatting of the file? Also your payment address still seems to be missing in the application: https://github.com/w3f/Grants-Program/blob/master/applications/php-substrate-api.md Could you create another PR to update this?

**Comment by tejbahadursingh** [comment]
@Noc2 we are doing it at no cost. That's the reason we submitted the Deliveries without any invoice details

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response. That’s great to hear. It would still be nice if you could update the formatting of the application and maybe update the price of the milestone here: https://github.com/w3f/Grants-Program/blob/master/applications/php-substrate-api.md  So it doesn’t cause any confusion.

**Comment by tejbahadursingh** [comment]
Thanks @Noc2. creating new PR to update the milestone here: https://github.com/w3f/Grants-Program/blob/master/applications/php-substrate-api.md . Can you please explain me more about updating the Formatting the application? Do we need to update formatting of PR created for milestone delivery from CRLF to LF?

**Comment by tejbahadursingh** [comment]
@Noc2 Updated the formatting of the application. Created new PR to update the Coasting here: https://github.com/w3f/Grants-Program/blob/master/applications/php-substrate-api.md

**Comment by semuelle** [comment]
Hey @tejbahadursingh. Sorry for the long wait. I was finally able to review your milestones. I have two - seemingly - minor issues:

1. The latest release requires php 7.2.24 strictly, so I had to go around and install the `dev-main` version to get it working on my system. Perhaps you could publish a new release?
2. Several tests are either failing or throwing errors. Some seem to be related to the type of node I am running (e.g. `Failed asserting that 'Development' contains "Polkadot"`, `Failed asserting that '0.9.0-b5519e768-x86_64-linux-gnu' contains "0.9.8-3a10ee63c-x86_64-linux-gnu".` and `Failed asserting that 'Development' contains "Live"`, but some I'm not sure. Is it because the node is not fully synced? See below. It would be great if you could either specify the exact versions and requirements or check that it emits a meaningful error message.

```
neha0921\SubstrateInterfacePackage\Tests\SubstrateInterfaceTest::testSystemPeers
Undefined property: stdClass::$error
[...]
neha0921\SubstrateInterfacePackage\Tests\SubstrateInterfaceTest::testRuntimeGetMetadataEvent
ArgumentCountError: Too few arguments to function neha0921\SubstrateInterfacePackage\Rpc\Runtime::getMetadataEvent(), 0 passed in /home/sebastian/work/w3f/code/grants/deliverables/php-substrate-api/substrate-interface-package/tests/ApiHandlerTest.php on line 687 and exactly 1 expected
```

**Comment by tejbahadursingh** [comment]
thanks @semuelle. Looking in those issues and suggestions.

**Comment by tejbahadursingh** [comment]
Hey @semuelle . I have provided below response.
1. To stable code with latest version, we have used php 7.2.24. In future it will get updated only up to 7.2.24.

2. We have added all fixes related to error message.

For testing we follow following steps::
To start our node setup we are using following command

`sudo docker-compose -p substrate-interface -f docker-compose.polkadot-local.yml up --build --remove-orphans`

1. Setup test enviornment
	a. clone demo project
	`git clone https://github.com/neha0921/package-test.git`

	b. `Update Composer`
	    `composer Update`
	
	I have already added our parity substrate package into the composer.

Only for information. I have added package by using following command
`composer require neha0921/substrate-api-php` (No need to perform)

2. To test output on browser run command
	`php -S localhost:8005`

3. on browser run `localhost:8005`

**Comment by takahser** [comment]
Hey @tejbahadursingh,
Thanks for the delivery!
Could you please also deliver the _docker-compose.polkadot-local.yml_ file you mentioned in your [most recent comment](https://github.com/w3f/Grant-Milestone-Delivery/pull/324#issuecomment-1005652423) to start the node in order for me to run the tests? Also I think it might be helpful if the instructions to run and test the code would be part of the documentation in your delivery.

**Comment by tejbahadursingh** [comment]
sure @takahser. updating the details.

**Comment by takahser** [comment]
Hi @tejbahadursingh 
Any update on this?

**Comment by tejbahadursingh** [comment]
Hi @takahser 
For substrate node running we followed below steps
git clone https://github.com/polkascan/substrate-interface.git

cd substrate-interface

git checkout 0.10.3

git submodule update --init --recursive

docker-compose -p substrate-interface -f docker-compose.polkadot-local.yml up --build --remove-orphans

**Comment by takahser** [comment]
Hi @tejbahadursingh 

I followed the steps described however, after running `php -S localhost:8005` in my browser the following errors are shown:
```php
Warning: require_once(../substrate-interface-package/vendor/autoload.php): failed to open stream: No such file or directory in /Users/xxx/repos/PHP_Substrate_1/package-test/index.php on line 5

Fatal error: require_once(): Failed opening required '../substrate-interface-package/vendor/autoload.php' (include_path='.:/opt/homebrew/Cellar/php@7.4/7.4.27/share/php@7.4/pear') in /Users/xxx/repos/PHP_Substrate_1/package-test/index.php on line 5
```

I'm using PHP 7.4 since PHP 7.2 is officially [not supported](https://www.php.net/supported-versions.php) anymore (PHP 7.4 is the oldest version that still has (limited) support).

**Comment by takahser** [comment]
Hey @tejbahadursingh
Since I don't have an easy way to install the unsupported legacy PHP I'll be waiting for your update.

**Comment by tejbahadursingh** [comment]
Hi @takahser 
Updated the repo for PHP version greater than 7.2.  Please follow below details.
For substrate node running we followed below steps
1. `git clone https://github.com/polkascan/substrate-interface.git`
2. `cd substrate-interface`
3. `git checkout 0.10.3`
4. `git submodule update --init --recursive`
5. `docker-compose -p substrate-interface -f docker-compose.polkadot-local.yml up --build --remove-orphans`

Repository `https://github.com/neha0921/package-test.git` is a sample example project to show how our repository `https://github.com/neha0921/substrate-interface-package` can be integrated to a PHP project.

Repository `https://github.com/neha0921/substrate-interface-package` is main repository which have all integrated endpoints. 

To run the sample project perform the below steps
	1. Clone the demo/sample project
		`git clone https://github.com/neha0921/package-test.git`
        2. Update composer
                `composer Update`
        3. To test the output in browser
                 `php -S localhost:8005`
        4. On browser run below command to check the output
                ` localhost:8005 `
		
	
To run the test cases of main repository `https://github.com/neha0921/substrate-interface-package` Follow the instructions mentioned in README of repository.

**Comment by takahser** [comment]
Hi @tejbahadursingh

Thanks for the update and sorry for my late reply.
Which PHP version should I use to test?
I tried to run your updated code on PHP 7.4 again, but I still get the same error as described [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/324#issuecomment-1014574445). Could you double-check on which version it worked for you?

**Comment by tejbahadursingh** [comment]
Hi @takahser 
I think that issue is not related to php version. Please clone the repository `https://github.com/neha0921/substrate-interface-package` at same level where you cloned repository `https://github.com/neha0921/package-test.git`.

is it possible for you to connect over any chat? I think that if we communicate over chat then we can overcome this quickly. I am ok with any chat application which you will suggest.

**Comment by tejbahadursingh** [comment]
Hi @takahser anything else you need from me?  Any thought about us to connect over chat?

**Comment by takahser** [comment]
@tejbahadursingh Yes, I just reached out via email to you.

**Review by takahser — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by KapilJoshiNitor** [comment]
Thanks for merging PR.

**Pull request merged**
