### PR TITLE
logion_wallet-M1

### PR DESCRIPTION
**Pull request by elisadba**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/627

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
Hi @elisadba. Thanks again for the delivery and sorry for the late reply. We have evaluated your milestone and it is hereby accepted. Congratulations!

You can find our evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/logion-wallet_1_6636345e.md), though I can say that there was not much to complain about. It would be great if you could add some more inline documentation to the backend part, but all in all the documentation was good and easy to follow. 

I noticed that your invoice doesn't contain the payment address. Could you resubmit your invoice with the payment address as in the grant contract?

**Comment by elisadba** [comment]
Hi @semuelle, many thanks for your evaluation work. Your recognition is precious! 
Thank you for your feedbacks too, I'll pass this on to the devs. Sure, we will resubmit the invoice with the payment address.

Let's build web3 legal protection together 😊

**Comment by semuelle** [comment]
@elisadba, did you resubmit the invoice? I can't seem to find it.

**Comment by semuelle** [comment]
@elisadba, the new invoice seems to also not contain the payment address.

**Comment by Noc2** [comment]
Just to make sure there is no misunderstanding: @semuelle is referring to the cryptocurrency payment address on the invoice: 0x5823cBD1D4b986E434718BeEc41Ba78160 that was also part of the application.

**Comment by elisadba** [comment]
Thank you for the clarification. We thought we could still choose for a fiat payment by completing the form. @BEdasc sent you the proper invoice by email. Sorry for the inconvenience 🙏🏻

**Comment by Noc2** [comment]
@elisadba to which email did you send the update invoice? Could you upload it also here https://forms.gle/LSRr7PCjBpEbKGh89 Thanks

**Comment by Noc2** [comment]
Thanks a lot!

**Comment by Noc2** [comment]
@elisadba But the invoice still doesn't contain the address 0x5823cBD1D4b986E434718BeEc41Ba7816098BF77 as far as I can see it

**Comment by BEdasc** [comment]
Hello @Noc2, following your exchange, I've sent an email on January 2nd (21H09) at invoice@web3.foundation with the new bill attached, to ask if it was a problem to change this address by a ETH ENS account (logion.eth). It'll more easier to me to manage crypto routing, accounting integration and control by the logion foundation later through this channel. Thanks, David

**Comment by Noc2** [comment]
@BEdasc In this case, could @elisadba (since she created the grant application) open a PR to update the payment address of the [logion_wallet.md file ](https://github.com/w3f/Grants-Program/blob/master/applications/logion_wallet.md) to logion.eth or 0x3bf8D93Bbe15c002a2c731D5139077aA1c7002Cd and could you also send us a new invoice. Sorry for the confusion.

**Comment by BEdasc** [comment]
Thanks @Noc2 - I understand. @elisadba please mention logion.eth. This will be our definitive erc reference. Best wishes all!

**Comment by Noc2** [comment]
@BEdasc and @elisadba: Just a reminder to also send us an updated invoice that contains the ethereum address, which was mentioned in the amendment: https://github.com/w3f/Grants-Program/pull/772

**Comment by elisadba** [comment]
Hello @Noc2, we submitted a final invoice last Thursday (27/01) to make sure you have it all together, normally everything should be in order. Could you check that you got everything you need from us? We are working on the next step, it might be be great if we can both close this first milestone. 
Thanks a lot 🙏🏻

**Comment by Noc2** [comment]
Thanks for pinging me. I forwarded the invoice internally

**Comment by elisadba** [comment]
Wonderful, thank you @Noc2!

**Pull request merged**
