### PR TITLE
submit ink-pallet-benchmarking milestone 2

### PR DESCRIPTION
**Pull request by Nikhil-Desai-Talentica**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1457 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for the delivery, @Nikhil-Desai-Talentica. We will look into it as soon as possible.

**Comment by keeganquigley** [comment]
Thanks for the delivery @Nikhil-Desai-Talentica you can find my initial eval [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-pallet-benchmarking_2_keeganquigley.md). I'm getting errors when trying to compile with both `cargo test` and `cargo build --release`. I'm running on Ubuntu x86/64 architecture. I tried on all three branches. Have you faced these errors before by chance?

**Comment by Nikhil-Desai-Talentica** [comment]
Hi @keeganquigley, thanks for taking the time to review my work and providing valuable suggestions. I have mentioned that you need to use Rust nightly 1.68 since compiling with nightly 1.70 breaks some of the dependencies that are beyond my control. I hope you've read and followed this. I am happy to help you fix this over a call or some other way.Thanks.

**Comment by keeganquigley** [comment]
Thanks @Nikhil-Desai-Talentica it is working for me now, and I am able to run the extrinsic benchmarks. I need to run through the solidity-native ones and then I will finish up my eval.

**Comment by keeganquigley** [comment]
Thanks for your patience @Nikhil-Desai-Talentica as this was my first time delving into Solang and WASM-compiled Solidity, cool stuff! I was able to run the available benchmarks and deploy an EVM contract on-chain. I did still have to install `protobuf-compiler` to build the nodes. In the future, would be cool to see more complex logic included, such as cross-contract calls.

I have updated my evaluation and am happy to pass the milestone. Congrats on completing this grant.

**Comment by keeganquigley** [comment]
@Nikhil-Desai-Talentica ah, the `protoc` installation issue seems to be specific to Debian/Ubuntu so you can disregard that. It happens to me on the regular substrate node template as well.

**Comment by Nikhil-Desai-Talentica** [comment]
Hi Team,

Could you please process the payment for Milestone 2.

Thanks,
Nikhil Desai.

**Comment by semuelle** [comment]
Hi @Nikhil-Desai-Talentica. Sorry for the delay, but payments can take up to 14 days. Let us know if you haven't heard anything by Monday.

**Pull request merged**
