### PR TITLE
Dotflow Milestone 2 delivery

### PR DESCRIPTION
**Pull request by Szegoo**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1657

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @Szegoo. Thanks for the delivery. I am currently trying to set up the whole thing locally, but I am failing to compile the contracts. See error log below. Can you advise?

```
❯ cargo test --features e2e-tests
   Compiling address_book v0.1.0 (/dotflow/dotflow-ink/contracts/address_book)
 [1/*] Building cargo project
    Updating crates.io index
error: "/home/xxx/.rustup/toolchains/nightly-2023-01-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/Cargo.lock" does not exist, unable to build with the standard library, try:
        rustup component add rust-src --toolchain nightly-2023-01-04-x86_64-unknown-linux-gnu
error: custom attribute panicked
   --> contracts/address_book/lib.rs:246:3
    |
246 |         #[ink_e2e::test]
    |         ^^^^^^^^^^^^^^^^
    |
    = help: message: contract build for /dotflow/dotflow-ink/contracts/address_book/Cargo.toml failed: `cd "/tmp/cargo-contract_0HczuG/contracts/address_book" && RUSTFLAGS="-C link-arg=-zstack-size=65536 -C link-arg=--import-memory -Clinker-plugin-lto -C target-cpu=mvp" "/home/xxx/.rustup/toolchains/nightly-2023-01-04-x86_64-unknown-linux-gnu/bin/cargo" "build" "--target=wasm32-unknown-unknown" "-Zbuild-std" "--no-default-features" "--release" "--target-dir=/dotflow/dotflow-ink/target/ink/address_book" "--features" "ink/ink-debug"` failed with exit code: Some(101)

error: custom attribute panicked
   --> contracts/address_book/lib.rs:276:3
    |
276 |         #[ink_e2e::test]
    |         ^^^^^^^^^^^^^^^^
    |
    = help: message: Once instance has previously been poisoned

error: custom attribute panicked
   --> contracts/address_book/lib.rs:382:3
    |
382 |         #[ink_e2e::test]
    |         ^^^^^^^^^^^^^^^^
    |
    = help: message: Once instance has previously been poisoned

error: custom attribute panicked
   --> contracts/address_book/lib.rs:469:3
    |
469 |         #[ink_e2e::test]
    |         ^^^^^^^^^^^^^^^^
    |
    = help: message: Once instance has previously been poisoned

warning: unused import: `super::*`
   --> contracts/address_book/lib.rs:240:7
    |
240 |         use super::*;
    |             ^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default

warning: unused import: `identity::IdentityRef`
   --> contracts/address_book/lib.rs:241:7
    |
241 |         use identity::IdentityRef;
    |             ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `ink_e2e::build_message`
   --> contracts/address_book/lib.rs:242:7
    |
242 |         use ink_e2e::build_message;
    |             ^^^^^^^^^^^^^^^^^^^^^^

warning: `address_book` (lib test) generated 3 warnings
error: could not compile `address_book` due to 4 previous errors; 3 warnings emitted
```

**Comment by cute0laf** [comment]
Hi @semuelle Nice to meet you here.
I've built this project along with @Szegoo 
I will take a look and let you know how to fix it.

**Comment by semuelle** [comment]
Thanks, @cute0laf. Feel free to reach out via Matrix to speed things up (starting Monday morning :smile:).

**Comment by Szegoo** [comment]
Hello @semuelle. Thanks for letting us know about the error. The reason why it was occurring is because our project was based around an older rust version(1.68.0) and an older cargo-contract version(3.0.1).

We updated the ink! version so that the e2e tests work with the latest versions.

**Comment by semuelle** [comment]
Just fyi, the RPC endpoint you are using on the demo app seems to be down.

**Comment by Szegoo** [comment]
@semuelle Yes, it seems so. It should be working now.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the updates, @Szegoo. A couple of issues:

- The milestone specification states that "we will allow the identity creator to specify the accounts that are authorized to modify the identity's addresses." Can you elaborate what that means? I currently cannot find such functionality.
- When I enter a decimal point in the Amount textfield, the whole entry disappears. I have to enter `12` and then add a decimal point in between to send 1.2 KSM.
- It would make sense to add an account selection popup after connecting the wallet. Now, it just selects the first account returned and I have to wait until the identity is loaded before I can select a different account. 
- The loading of the first account takes quite some time, but then selecting another one is quite fast. Are you loading all identities from all accounts returned from the wallet? That might be encumbering with a lot of accounts/identities.
- When I cancel the transaction, the transfer page keeps showing the loading spinner 
- Same if the transaction fails. Only an error message in the console.
- If source and target chain are the same, there is no need to use the xcmpallet.

**Comment by Szegoo** [comment]
@semuelle Thanks for the feedback.

> The milestone specification states that "we will allow the identity creator to specify the accounts that are authorized to modify the identity's addresses." Can you elaborate what that means? I currently cannot find such functionality.

In the identity contract, this is implemented by having a recovery account. However, this part is missing on the frontend side.

> When I enter a decimal point in the Amount textfield, the whole entry disappears. I have to enter 12 and then add a decimal point in between to send 1.2 KSM.

This error did not happen to us. Could you let us know what browser are you using?

> The loading of the first account takes quite some time, but then selecting another one is quite fast. Are you loading all identities from all accounts returned from the wallet? That might be encumbering with a lot of accounts/identities.

Loading the identities is not the part that takes up a lot of time. The frontend is querying the chains to fetch metadata. This can be improved by utilizing the existent [Talisman Chaindata](https://github.com/TalismanSociety/chaindata) that is publicly available. This will reduce the loading time to almost instantaneous, so the suggested popup for selecting a user is probably unnecessary in this case.

> When I cancel the transaction, the transfer page keeps showing the loading spinner

We will look into this.

> If source and target chain are the same, there is no need to use the xcmpallet.

We wanted to utilize the XCM standard for doing non-cross-chain transfers since the XCM executor will do the actual transfer. This can keep the app more abstract. However, since there are a lot of chains at the moment that do not support local XCM execution we decided that we will add support for doing transfers without XCM.

We will be working on resolving all of the mentioned issues and will ping you as soon as complete.

**Comment by Szegoo** [comment]
@semuelle I would like to let you know that we resolved all of the issues you mentioned. 
- We added the UI for setting the recovery account and transferring the ownership with the recovery account.
- We also increased the performance of loading the website. 
- Added support for doing non-cross-chain transfers without the xcmpallet.
- Tried inputting decimal number on the browser you specified. It did not work, but that seems to be a browser issue. I managed to solve this by updating the browser version.
- Fixed the loading spinner when the transaction is canceled.

**Comment by semuelle** [comment]
Thanks for the updates, @Szegoo! I will review them early next week.

**Review by semuelle — CHANGES_REQUESTED** [review]
Thanks for the updates, @Szegoo, and sorry for the wait. Since this is your last milestone, I want to ask you for some fixes to make sure the project is in a good state before moving on.

- When I try to remove an address from the address book while a transaction is still pending, I get a `check your balance` error message.
- There doesn't seem to be a sanity check for the inputs, at least the identity key. When I accidentally entered a KSM address, it accepted the input and just displayed `Encryption failed` and error messages when trying to send to the identity.
- A transfer of `0` should be caught. 
- Errors from value inputs being too small isn't handled (`Transfer failed. Error: Error: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"MultiAddress","value":"Lookup52"}:: Struct: failed on value: Compact<u128>:: Number needs to be an integer <= Number.MAX_SAFE_INTEGER, i.e. 2 ^ 53 - 1`).

There are some other, smaller issues that I found. They are not critical, but I'll leave them here anyway:
- Don't allow transactions if the sending account has 0 or too low balance by querying the balance in advance. 
- Don't show contacts that don't have an address on the target chain in the recipient drop-down.
- Sharing an identity would be a bit easier if the identity key and number were combined into one string. You could simply paste them together in the "sharing" view and then deconstruct them again on the address book frontend.
- Is it intentional that I can still see "Address Book" and fill out the "Transfer" form even if I don't have an identity (or address book)?
- Why is there a separate transaction for creating an address book? Why is it not created with the identity _or_ the first address book entry?
- The decimal point entry issue remains. It only happens in Firefox, not Chromium, though.

**Comment by Szegoo** [comment]
@semuelle Thanks for the new review.

> When I try to remove an address from the address book while a transaction is still pending, I get a check your balance error message.

This is a pretty rare case, but the essential reason for this error is because the new transaction is competing with the old one. We display the `check your balance` error message whenever the `errorMessage` doesn't provide a meaningful message.

> There doesn't seem to be a sanity check for the inputs, at least the identity key. When I accidentally entered a KSM address, it accepted the input and just displayed Encryption failed and error messages when trying to send to the identity.

Good suggestion, we added sanity checks.

> A transfer of 0 should be caught.
Errors from value inputs being too small isn't handled (Transfer failed. Error: Error: createType(Call):: Call: failed decoding balances.transfer:: Struct: failed on args: {"dest":"MultiAddress","value":"Lookup52"}:: Struct: failed on value: Compact<u128>:: Number needs to be an integer <= Number.MAX_SAFE_INTEGER, i.e. 2 ^ 53 - 1).

Both are handled now.

> Don't allow transactions if the sending account has 0 or too low balance by querying the balance in advance.

In the case of a cross-chain transfer, we are getting all the data from XCM GAR, so it is not as trivial to add a balance query in those cases.

> Don't show contacts that don't have an address on the target chain in the recipient drop-down.

We added this as well.

> Sharing an identity would be a bit easier if the identity key and number were combined into one string. You could simply paste them together in the "sharing" view and then deconstruct them again on the address book frontend.

This is a great suggestion. Definitely improves the UX. We added this.

> Is it intentional that I can still see "Address Book" and fill out the "Transfer" form even if I don't have an identity (or address book)?

The user doesn't need to have an identity to create an address book.

> Why is there a separate transaction for creating an address book? Why is it not created with the identity or the first address book entry?

It results in cleaner code and we prefer this design choice.

> The decimal point entry issue remains. It only happens in Firefox, not Chromium, though.

I had the issue you mentioned on the specific version, however when I updated the Firefox version the error wasn't occurring to me anymore.

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @Szegoo. I am happy to report that your milestone is approved. Congratulations. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/dotflow_2_semuelle.md).

I hope you will continue working on Dotflow and to see you around the ecosystem. I have forwarded your invoice for processing.

**Pull request merged**
