### PR TITLE
Create CESS-3.md

### PR DESCRIPTION
**Pull request by swowk**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [ ] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/755

### CODE REVIEW

**Comment by swowk** [comment]
Hi, According to your suggestion in the last submission, we added article in the delivery this time, hoping to meet your requirements. @Noc2

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by Noc2** [comment]
@swowk I started to look into delivery and made a few notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CESS_3_Noc2.md). The repo of the [web app](https://github.com/CESSProject/web-app) currently has no licence file. I also get a lot of errors and security issues when I compile it and buying already uploaded files from others doesn’t seem to work for me. Could you look into this?

**Comment by swowk** [comment]
> @swowk I started to look into delivery and made a few notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CESS_3_Noc2.md). The repo of the [web app](https://github.com/CESSProject/web-app) currently has no licence file. I also get a lot of errors and security issues when I compile it and buying already uploaded files from others doesn’t seem to work for me. Could you look into this?

Sorry, LICENSE has been added and errors have been fixed. To explain, some of these security issues are caused by dependent libraries and do not affect our project. In addition, the bug of unable to purchase and download files has been fixed, and files can now be purchased normally.

**Review by Noc2 — APPROVED** [review]
Thanks. I’m happy to tell you that the milestone is a pass and I will forward your invoice internally. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/CESS_3_Noc2.md).

**Comment by RouvenP** [comment]
hi @swowk we sent the payment today.

**Pull request merged**
