### PR TITLE
Validated Streams milestone 2 delivery

### PR DESCRIPTION
**Pull request by bojidar-bg**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.gifoundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1437.

### CODE REVIEW

**Comment by arahangua** [comment]
Hi all, 

I tried to come up with an external evaluation for this milestone: [link to evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/82e642aa70d2b9ad5a58fbec1a59fa5bc91d39bf/evaluations/validated-streams_2_arahangua.md)
All-in-all, I think the current submission might need minor changes as I found some outdated links/paths in the delivery documentation (please correct me if I am wrong). 
As for the docker examples (TPS benchmark, IRC sample), they were working nicely. 

I will be happy to hear what you think.

**Comment by semuelle** [comment]
pinging @bojidar-bg

**Comment by bojidar-bg** [comment]
Apologies, was away for the week and didn't manage to get back to this earlier. All the outdated links should be fixed now -- tho, that's embarrassing, I could have sworn I checked every single delivery link before I submitted the PR. Also, tests and benchmarks ought to be fixed now (:

**Comment by arahangua** [comment]
@bojidar-bg 
Thanks for the update! Now tests run fine, and benchmarks can be built without problems.
  
Just one thing: 
as noted before, I think the path for streams.proto needs to be changed in the run-example.sh ("../proto" --> "../../proto"). 

+a point I wanted to double-check: 
while running the command "./run-example.sh validated" I get something like this as an output :
`{
  "nextBlock": 1
}
{
  "nextBlock": 2
}
{
  "nextBlock": 3
}
{
  "nextBlock": 4
}
{
  "nextBlock": 5
}`
Can you confirm if this is showing intended behavior? 

Other than these points, I think the contribution looks good :) Thanks

**Comment by bojidar-bg** [comment]
@arahangua Erm.. oops! Thanks for testing that :sweat_smile: Should be fixed. Lesson learned: don't refactor and publish a version at the same time.

As for `validated`, it is supposed to eventually produce something looking like `{"nextBlock": 8, "events": [ {"eventId": "..."}, ... ] }`, as long as `witness` is running at the same time. Running `./run-example.sh run` is supposed to run both... but apparently there was a bug with that (bootnotes were not being set, resulting in the gossip network never peering). This should be fixed as well now (:

**Comment by arahangua** [comment]
@bojidar-bg Thanks for the correction! Now they all seem to be running nicely. 
I have created a  [PR](https://github.com/w3f/Grant-Milestone-Delivery/blob/c058d3676a2be9d658ae0faf3eca7a80394c4d08/evaluations/validated-streams_2_arahangua.md) with an updated evaluation document that supports the acceptance of the milestone. 
I would love to hear what others think. @semuelle

**Review by semuelle — APPROVED** [review]
Thanks for the updates, @bojidar-bg, and thanks for following up on the evaluation, @arahangua! 

I can confirm that the evaluation is correct; your milestone is [hereby accepted](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/validated-streams_2_arahangua.md). I only changed the code coverage percentages, because I think the total numbers tarpaulin reports are not quite accurate. I also want to commend you on the inline docs. Very easy to follow.

I will forward your invoice for processing.

**Comment by bojidar-bg** [comment]
@semuelle Ooop! That's great news! (: Thanks for the detailed reviews, and.. keep up the great work!

I concur about tarpaulin; it included a lot of extra files in its calculation when I used it locally.
As an aside, I think there is  ways to add more unit tests added to the code base, to cover things like the `EventWitnesserTrait` and `EventValidatorTrait`; but since the implementations of those would require a full client, I figured the cost of maintaining such unit tests would shadow the benefit they give over just using integration tests there. (:'

Glad to hear the inline docs were better this time! :partying_face:

**Comment by bojidar-bg** [comment]
(Hey, not to be pushy or anything, but have there been any issues with the payment, perchance? Just asking since I feel like the turnaround was a bit faster last time... So, let me know if there is anything I can help clear up! (: )

**Comment by keeganquigley** [comment]
Thanks for the inquiry @bojidar-bg I see that we did submit the invoice 2 weeks ago. I will ping the operations team internally and get back to you.

**Comment by keeganquigley** [comment]
Hi @bojidar-bg the payment should go out tomorrow by end of day. Please let me know if this is not the case and sorry for the inconvenience!

**Comment by bojidar-bg** [comment]
@keeganquigley Thanks! Successfully received. :heart:

**Pull request merged**
