### PR TITLE
Create Plutonication_milestone_3.md

### PR DESCRIPTION
**Pull request by RostislavLitovkin**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, an invoice must be submitted and the payment will be transferred to the Polkadot/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2105

### CODE REVIEW

**Comment by dsm-w3f** [comment]
Hi, I'll evaluate this milestone. @keeganquigley could you please assign it to me?

**Comment by dsm-w3f** [comment]
@RostislavLitovkin thank you for the milestone delivery. Please see [this PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1134) for the current evaluation. Please provide proper answers and fixes, and after that, let me know when I can continue the evaluation.

**Comment by RostislavLitovkin** [comment]
Hello @dsm-w3f, thank you for contacting me. The `InvalidOperation_NoValue` is a completely unrelated issue that only exists in the PlutoWallet. I am fixing the error now and I will release an update to Google Play. I will post another comment once the update is live.

**Comment by RostislavLitovkin** [comment]
@dsm-w3f Alright, [PlutoWallet](https://play.google.com/store/apps/details?id=com.rostislavlitovkin.plutowallet) has been updated to version 1.9. The bug has been fixed.

**Comment by dsm-w3f** [comment]
@RostislavLitovkin thank you for the improvements and fixes. I still having problems to run the sample code. The QR code open the application but nothing happens after that. I update the [evaluation PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1134) with more information. Please take a look and let me know when I can continue this evaluation.

**Comment by RostislavLitovkin** [comment]
I think you understood it correctly. It was my mistake, there was a bug in the deep link parsing. It is fixed now.
I also fixed the bad formatting in nuget readme. (It does not support images, so I removed it from the package readme).
You can continue with evaluation ^^

**Comment by RostislavLitovkin** [comment]
I will clarify the testing process here, just in case.
After running the console dApp, you will need to copy the bottom link and open it in your browser. There is no way to show a QR code in console application, so I chose this simple option.
Screenshot 2024-02-20 at 22 17 59
After opening the link, it should look like this. Now, you can scan it with your camera app or PlutoWallet app and it should show you a popup with request for connecting to the dApp.
Screenshot 2024-02-20 at 22 19 47
Your phone needs to be connected to Internet, otherwise it will fail.

**Comment by dsm-w3f** [comment]
@RostislavLitovkin and @keeganquigley I tested again and now it worked for me. I updated the evaluation document and the Milestone is accepted from my side. I opened [the PR](https://github.com/w3f/Grant-Milestone-Delivery/pull/1134) for integrating the evaluation document to W3F repository. Thanks for the collaboration, Great job!

**Comment by keeganquigley** [comment]
Thanks for the quick fixes @RostislavLitovkin and for the evaluation @dsm-w3f your milestone is hereby accepted. Congrats!

**Comment by RouvenP** [comment]
hi @RostislavLitovkin we sent the payment today

**Pull request merged**
