### PR TITLE
zk-plonk delivery milestone 1

### PR DESCRIPTION
**Pull request by NoCtrlZ**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/454

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @NoCtrlZ. We will look into it as soon as possible.

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
Thank you for the review!
I have addressed `dependencies` and there is a question about example.

## Dependencies
I changed the dependencies name as following.

`parity-plonk` -> `fullcodec-plonk`
`parity-subtle` -> `fullcodec-subtle`
`parity_rand_xorshift` -> `fullcodec_rand_xorshift`
`plonk-jubjub` -> `fullcodec-jubjub`
`bls12_381` -> `fullcodec-bls12_381`
`ParityRng` -> `FullcodecRng`

> You even re-export XorShiftRng as ParityRng?

The reason why I re-export the `XorShiftRng` is that the `XorShiftRng` is well known crate and if they use original `XorShiftRng` to import themself, this crate wouldn't work because this crate is using customized `XorShiftRng`.
I think it's confusing so I renamed in order not developer to import original `XorShiftRng`.

> I don't understand why renaming jubjub to plonk-jubjub etc. is unnecessary. Rather, why not keep the forks under original names, and in your Cargo.toml specify the dependency as git = ..., instead of pointing to the default crates.io?

The `crates.io` doesn't allow to publish the `crate` with `git = ..., rev = ...` dependencies so I needed to publish crate with renaming.
I think this is because if that dependencies repo was deleted, that crate wouldn't work anymore...

## Examples
> types.json in your example is empty

I removed the `types.json`.
## Question
> Then I ran it in dev mode and tried to submit some Tx from polkadot-js/apps, but it fails with the following error:

How did you test with `polkadot-js/apps`?
Did you implement it on your locally?

Thank you for the polite review!
I am going to address the rest issue as soon as possible 😎

**Comment by mmagician** [comment]
But do you really need to publish to crates.io?
Why not just use the GitHub dependencies in your code? As I had already written, this would allow you to keep the original names.
Especially for such forks, I don't see why having the crate in crates.io would bring any benefit - your forks are likely not going to become the de-facto standard and replace the original.

Regarding local testing: I followed your tutorial to add the pallet to a substrate-node-template, see my previous comment. You should be able to clone my repo and test locally too.

I'm not sure deleting types.json is the best solution - there are some custom types and users should be able to use them from whatever client they choose (e.g. the Polkadot-js API will need types definition).

**Comment by NoCtrlZ** [comment]
Thank you for the fast reply!
> But do you really need to publish to crates.io?
Why not just use the GitHub dependencies in your code? As I had already written, this would allow you to keep the original names.

In the case that `plonk-pallet` has Github dependencies, this pallet can't be published.
I mean every dependencies can't be described as `git` and `rev`.
Do you mean that developers use this pallet to fork this repo and import from locally?

When we publish the crate with Github dependencies, the following error happens.
```
➜  plonk git:(master) cargo publish --allow-dirty
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `fullcodec-jubjub` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

> Regarding local testing: I followed your tutorial to add the pallet to a substrate-node-template, see my previous comment. You should be able to clone my repo and test locally too.

I think in my tutorial, there is no description about `polkadotjs/apps`.
I think `substrate-node-template` doesn't have `polkadotjs/apps` script too.
Could you indicate which scripts you used?

> I'm not sure deleting types.json is the best solution - there are some custom types and users should be able to use them from whatever client they choose (e.g. the Polkadot-js API will need types definition).

Yeah, I think that type definition should be in `pallet` not in `example`.

**Comment by mmagician** [comment]
So I'm saying - don't publish it :) just keep it on github, and developers can use it as described here: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

> Do you mean that developers use this pallet to fork this repo and import from locally?

No, of course not. But in their own `Cargo.toml`, they can just specify it as:
```
[dependencies]
plonk-pallet = { git = "https://github.com/AstarNetwork/plonk" }
```

Absolutely nothing wrong with that! As a reference, you can see how some of Polkadot's dependencies are specified: https://github.com/paritytech/polkadot/blob/master/runtime/parachains/Cargo.toml#L21

> I think in my tutorial, there is no description about polkadotjs/apps.

No, there isn't. It's just what I used for testing a minimal chain with your pallet, which is not a unit test. I don't have any script, I just tried to run my chain locally and interact with its pallets via polkadot-js/apps. Otherwise, I can't really test it properly, since, as I said, the tests you provide are only unit tests and cannot be used to substitute a full integration test.
It would be great if you could provide a script that tests all the functionality against a locally-running substrate node, such as the one I have shared earlier.

Btw, here are some minor improvements to the tutorial:
https://github.com/AstarNetwork/plonk/pull/3

**Comment by NoCtrlZ** [comment]
> No, of course not. But in their own Cargo.toml, they can just specify it as:

Aha that makes sense!
Okay I am going to define dependencies as git.

> It would be great if you could provide a script that tests all the functionality against a locally-running substrate node, such as the one I have shared earlier.

I think this grant project purpose is to implement plonk pallet which can be referred from other pallet as api.
I already implemented plonk pallet which is compatible with substrate and described the tutorial how to refer it from other pallet.
I think this is out of scope.

> Btw, here are some minor improvements to the tutorial:

hahaha cool!
I merged.
Thank you for your contribution!

**Comment by mmagician** [comment]
Yeah, fair. The deliveries clearly state just unit tests.
Still, I would insist on keeping a `types.json` around. In the end, it's not going to be just chain developers importing your pallet, but also dapp developers who just need to call your API - and for this they need type definitions. 

> Yeah, I think that type definition should be in pallet not in example.

Sure.

**Comment by NoCtrlZ** [comment]
I fixed the dependencies according to your review!

> Still, I would insist on keeping a types.json around. In the end, it's not going to be just chain developers importing your pallet, but also dapp developers who just need to call your API - and for this they need type definitions.

I found the issue about `types.json` on [stackoverflow](https://stackoverflow.com/questions/68487857/how-to-generate-types-json-in-substrate).
Above says that `types.json` won't be necessary after the following PR are merged.
https://github.com/paritytech/substrate/pull/8615
And also `polkadotjs` has PR about it and both were merged.
https://github.com/paritytech/polkadot/pull/3336
The `types.json` problem is fixed by referring the latest version of `polkadotjs`.

I would appreciate it if you could confirm the chages!
Thank you!

**Comment by mmagician** [comment]
Hmm yeah I've seen this PR some time ago. However, I'm using the latest version of polkadot-js and still seeing this.
It should be very easy to recreate the error on your side - just build the chain I've created and try to submit a "trusted setup" transaction through your pallet via polkadot-js/apps.

Thanks for updating the dependencies, will check on it soon.

**Comment by NoCtrlZ** [comment]
> just build the chain I've created and try to submit a "trusted setup" transaction through your pallet via polkadot-js/apps

I would like to know how you submitted transaction.
It's okay just rough one.

**Comment by mmagician** [comment]
Screenshot 2021-12-22 at 14 00 17

**Comment by NoCtrlZ** [comment]
@mmagician 
I was successful for reproduce but I couldn't fix the error so I asked polkadot-js now.
https://github.com/polkadot-js/apps/issues/6729

Sorry for late...

**Comment by mmagician** [comment]
@NoCtrlZ I'll put this milestone on hold for now, as it seems the issue hasn't been resolved yet.

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
I added `types.json` and checked it worked when it was imported on polkadotjs app.
https://github.com/AstarNetwork/plonk/blob/master/types.json
Please confirm!

**Comment by NoCtrlZ** [comment]
Hi @mmagician 
Is everything going well?

**Comment by mmagician** [comment]
@NoCtrlZ apologies for the delay. So far I haven't managed to review your changes. I will do my best next week and if not, ask another colleague to help out. Thanks for the patience!

**Comment by NoCtrlZ** [comment]
@mmagician 
All right 👍
Please feel free to ping me if you have a question.

**Comment by alxs** [comment]
@NoCtrlZ I'll take a look at this.

In your application, you describe [this sequence of steps](https://github.com/w3f/Grants-Program/pull/454#discussion_r653176937) to build a circuit. Could you provide documentation covering all the steps? I haven't followed the tutorial you provide, but it seems to be quite a different process from that. Also, where can I review the circuit template library you mention?

Besides, could you make sure your project complies with the dusk-network plonk [license](https://github.com/dusk-network/plonk/blob/master/LICENSE)? If you're using files from it, you must preserve copyright and license notices. You also need to add a license to your repository.

**Comment by alxs** [comment]
@NoCtrlZ friendly reminder.

**Comment by NoCtrlZ** [comment]
Hi @alxs !
Sorry for late.
> In your application, you describe https://github.com/w3f/Grants-Program/pull/454#discussion_r653176937 to build a circuit. Could you provide documentation covering all the steps?

As we told [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/326#issuecomment-999436015), this grant scope was to implement pallet, and how to deploy and interact with node is described as substrate documentation.
With the tutorial I created, The developers can understand how to import this library and use `plonk` functionality.
> Also, where can I review the circuit template library you mention?

The custom circuit is following.
https://github.com/AstarNetwork/plonk/blob/master/examples/src/tests.rs#L78
The api is the same with [`dusk-plonk`](https://github.com/dusk-network/plonk).
> Besides, could you make sure your project complies with the dusk-network plonk [license](https://github.com/dusk-network/plonk/blob/master/LICENSE)? If you're using files from it, you must preserve copyright and license notices. You also need to add a license to your repository.

Exactly!
I added LICENSE and copyright credit.
Please confirm!

**Comment by alxs** [comment]
The application also lists the following as in scope for [this milestone](https://github.com/w3f/Grants-Program/blob/master/applications/zk-plonk.md#milestone-1-example--implement-substrate-modules), and I can't find either:

-  a basic tutorial that explains how a developer builds a circuit and a user prove their computation through the circuit.
-  a set of plonk-based zkSNARK libraries that allow a developer to build their own circuit and a user to prove their computation validity.

**Comment by NoCtrlZ** [comment]
Thank you for the review! @alxs
> a basic tutorial that explains how a developer builds a circuit

This is described in following section.
`TestCircuit` is the example of build circuit.
https://astarnetwork.github.io/plonk/#4import-the-coupling-pallet-to-testruntime-and-define-your-circuit

> a user prove their computation through the circuit.

This is described in following section.
Through `circuit.prove(&pp, &pk, b"Test").unwrap()`, the user prove the computation.
https://astarnetwork.github.io/plonk/#5test-whether-the-functions-work-correctly
In above section, the user create proof through circuit with their witness.

> a set of plonk-based zkSNARK libraries that allow a developer to build their own circuit and a user to prove their computation validity.

This question seems the same question as above.
If you want, I can explain overall using zoom or something.
Please confirm!

**Comment by alxs** [comment]
Yeah ok, I think I fundamentally misunderstood what was being delivered here. Otherwise it looks good. I was confused by the wording at places, such as this being called a "circuit template library" (though what it provides are rather components with which to build a circuit) and the multiple mentions of this allowing a developer to build their own circuit, while that's really the PLONK library's feat and you're "just" integrating it.

Nevertheless, this is irrelevant to the implementation and I was able to successfully test a simple trusted setup. I'm happy to tell you that the milestone is a pass. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/zk-plonk_1_alxs.md). I'll notify the operations team to pay out your invoice.

**Comment by alxs** [comment]
@NoCtrlZ we have no invoice submission from you. Could you fill in the [form](https://forms.gle/LSRr7PCjBpEbKGh89) please?

**Comment by NoCtrlZ** [comment]
Hi @alxs 
Thank you for the fast review!
> I was confused by the wording at places

Yeah the zk has a lot of terminologies so kind of a hard.
We are going to fill in the form soon!

**Comment by NoCtrlZ** [comment]
Hi @alxs 
I filled in the form!
Please confirm.
Thank you.

**Comment by meldien** [comment]
Hi @NoCtrlZ 
Many thanks for the invoice. 
I noted the address is unfortunately missing. Could you please update the invoice with following address information:
Web 3.0 Technologies Foundations
Baarerstrasse 14
6300 Zug

Many thanks.

**Comment by NoCtrlZ** [comment]
Hi @meldien 
I'm sorry for your inconvenience.
I filled it again.
Please confirm.
Thank you.

**Comment by meldien** [comment]
Hi @NoCtrlZ 
I confirm the invoice. 
Many thanks.

**Comment by RouvenP** [comment]
hi @NoCtrlZ we transferred the payment today. thanks!

**Comment by NoCtrlZ** [comment]
Hi @RouvenP 
Thank you!

**Pull request merged**
