### PR TITLE
Create inkscope-fuzzer-1.md

### PR DESCRIPTION
**Pull request by feliam**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, invoices must be submitted and payments will be transferred to the Polkadot AssetHub and/or fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/2155

### CODE REVIEW

**Review by semuelle — COMMENTED** [review]
Thanks for the delivery, @feliam. I am going through the instructions in the readme, and I keep running into this error below. Any idea what I might be missing?

```sh
> cargo test                        
   Compiling drink v0.10.0 (https://github.com/inkscopexyz/inkscope-drink.git?rev=b25b886#b25b8868)
error[E0283]: type annotations needed
   --> /home/anon/.cargo/git/checkouts/inkscope-drink-8150a806fd73cad9/b25b886/drink/src/session/record.rs:195:26
    |
195 |                         .decode_contract_event(&signature_topic.into(), &mut &*data.encode())
    |                          ^^^^^^^^^^^^^^^^^^^^^ ----------------------- type must be known at this point
    |                          |
    |                          cannot infer type of the type parameter `Hash` declared on the method `decode_contract_event`
    |
    = note: cannot satisfy `_: AsRef<[u8]>`
note: required by a bound in `ContractMessageTranscoder::decode_contract_event`
   --> /home/anon/.cargo/registry/src/index.crates.io-6f17d22bba15001f/contract-transcode-4.0.2/src/lib.rs:300:15
    |
294 |     pub fn decode_contract_event<Hash>(
    |            --------------------- required by a bound in this associated function
...
300 |         Hash: AsRef<[u8]>,
    |               ^^^^^^^^^^^ required by this bound in `ContractMessageTranscoder::decode_contract_event`
help: consider specifying the generic argument
    |
195 |                         .decode_contract_event::<Hash>(&signature_topic.into(), &mut &*data.encode())
    |                                               ++++++++

For more information about this error, try `rustc --explain E0283`.
error: could not compile `drink` (lib) due to 1 previous error
 ~/inkscope/inkscope-fuzzer | on develop !1 ...................................................... at 22:04:51 
> cargo -V
cargo 1.76.0 (c84b36747 2024-01-18)
 ~/inkscope/inkscope-fuzzer | on develop !1 ...................................................... at 22:05:02 
> cargo contract -V
cargo-contract-contract 3.2.0-unknown-x86_64-unknown-linux-gnu
```

**Comment by 0xLucca** [comment]
Hi @semuelle,

The issue with th build is likely due to a problem with how Rust is resolving the contract-transcode crate included in the drink crate. Please try building with the locked flag:
```
cargo build --release --locked
```
Also, please make sure you are working on the milestone-1 branch, as the develop branch is currently under active development and may not be in a stable state.

Let us know if this resolves the problem or if you have any other questions

**Review by semuelle — APPROVED** [review]
Thanks for the clarification, @feliam. I hadn't noticed the milestone-1 branch. Everything is compiling and running now, thanks. Your milestone is hereby accepted. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/inkscope-fuzzer_1_semuelle.md).

**Comment by RouvenP** [comment]
hi @feliam we sent the payment last Friday

**Pull request merged**
