### PR TITLE
High-availability validator setup - Milestone 2

### PR DESCRIPTION
**Pull request by bufta**
Delivery of Milestone 2

# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1203

### CODE REVIEW

**Comment by bufta** [comment]
Hi, I'd just like to check in to see if everything is ok with our delivery. Should we perform any additional actions? Any feedback would be greatly appreciated :)

**Comment by keeganquigley** [comment]
Hi @bufta most of the links to the code are giving 404 errors. Can you please fix these? Thanks!

**Comment by bufta** [comment]
Hi @keeganquigley, I apologise for this, this part of repo was still private... It's public now, hope it will all work fine 👍

**Comment by keeganquigley** [comment]
@bufta Please see my initial [evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/high_availability_validator_setup_2_keeganquigley.md). For some reason I am getting errors with both Docker and with running locally having to do with OpenSSL. I tried running `sudo apt install libssl-dev` to no avail. I'm testing on MacOS and Linux Ubuntu. Is it running properly on your end?

**Comment by mgralinski-bright** [comment]
Hi @keeganquigley, on our side it works fine. I have pushed one more commit to force a proper Rust toolchain, but I doubt it will solve your problems. I suggest to make a short meeting, which I will introduce you to Milestone-2 and discuss any issues. Please use this [link](https://calendar.app.google/ku6kxoqJiUmQR3j2A) to make an appointment with me.

**Comment by keeganquigley** [comment]
Thanks @mgralinski-bright sounds good, I just sent you an email.

**Comment by fededubbi** [comment]
Hi @mgralinski-bright,

I noticed that above our name there is 'Ship to', could you please put instead 'Bill to'

Many thanks,
Federica

**Comment by bufta** [comment]
Hi @fededubbi, after your request I sent the corrected invoice through the google form again. Did you receive it? Is everything ok, or should we have sent it using other channel? All the best!

**Comment by fededubbi** [comment]
Hi @bufta,

All good thanks.
The invoice is correct.

Federica

**Comment by RouvenP** [comment]
hi @bufta we transferred the payment today

**Pull request merged**
