### PR TITLE
[Aviraj] Submitting M1 and M2 for ink-smart-contract-wizard

### PR DESCRIPTION
**Pull request by avirajkhare00**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1404 < please fill this in with the PR number of your application.

### CODE REVIEW

**Comment by 0xCaso** [comment]
Hi @avirajkhare00, and thanks for the deliveries. Someone of our team will look into them asap. 

In the meantime, could you please divide them into two different files (`deliveries/ink-smart-contract-wizard_milestone-1.md` and `deliveries/ink-smart-contract-wizard_milestone-2.md`)?

**Review by 0xCaso — COMMENTED** [review]
Hi @avirajkhare00, and thanks for the deliveries. Someone of our team will look into them asap. 

In the meantime, could you please divide them into two different files (`deliveries/ink-smart-contract-wizard_milestone-1.md` and `deliveries/ink-smart-contract-wizard_milestone-2.md`)?

**Comment by avirajkhare00** [comment]
Hey @0xCaso. I have split M1 and M2 into two different files. Please check.

**Comment by keeganquigley** [comment]
Hi @avirajkhare00 please check my initial [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-smart-contracts-wizard_1_keeganquigley.md) and let me know if you can address the issues. Also, the Python unittests work correctly but I notice that OpenBrush doesn't generate unit tests for Cargo. Is the intention still for the contract developer to develop their own Rust unit tests? Thanks!

**Comment by keeganquigley** [comment]
Hi @avirajkhare00 I started the M2 eval and here are my initial [notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-smart-contracts-wizard_2_keeganquigley.md).

- There is no article link provided, can you point me to it?
- The contracts are failing to compile under both the +stable and +nightly toolchains. Which one should I be building them with?

**Comment by avirajkhare00** [comment]
Hey @keeganquigley. There were few issues with `Cargo.toml` file and `psp22` template. I have fixed them. Also, I have updated the README.md file and included instructions to build the smart contracts. Please use those commands.

All the smart contracts using Flipper are getting compiled successfully on my machine.

I have made changes to the Formula also. Please run the following commands to update it to the latest version.

```sh
brew uninstall ink-wizard
brew untap avirajkhare00/ink-wizard
```

Then to install it, do:

```sh
brew tap avirajkhare00/ink-wizard
brew install ink-wizard
```

Ink wizard will work fine for you.
Then please follow the instructions to build your smart contracts. I hope it helps 😄

**Comment by avirajkhare00** [comment]
You can take a look at this issue also: https://github.com/paritytech/ink/issues/1485

**Comment by keeganquigley** [comment]
@avirajkhare00 thank you for the link! Turns out I actually needed to download `cargo-contract --version v2.0.0-beta` to build them, as noted [here](https://github.com/paritytech/ink/blob/master/CHANGELOG.md#compatibility). I appreciate you looking into that.

Thanks for making the changes. I have accepted M1 [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-smart-contracts-wizard_1_keeganquigley.md). 

Regarding M2:

- Did you write an article or blog post that you can provide a link to? (It's okay if it's not published yet.)
- Just a note that the contracts deploy successfully but since Polkadot{JS} [doesn't support weights V2](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-smart-contracts-wizard_1_keeganquigley.md) yet, they don't work correctly in the UI. This is not the fault of the grantee.
- I know that writing unit tests in ink! is not part of the grant scope, but out of curiosity are you able to answer my [above question](https://github.com/w3f/Grant-Milestone-Delivery/pull/691#issuecomment-1386196521)? As typically I've seen the convention to be writing unit tests in the lib.rs file itself.

**Comment by avirajkhare00** [comment]
Hey @keeganquigley. I have took inspiration from this tool: https://wizard.openzeppelin.com/

this tool doesn’t generate the tests. Let me know your thoughts on this.

**Comment by avirajkhare00** [comment]
Hey. Here is the article link: https://medium.com/@avirajkhare00/introducing-ink-wizard-8f15a401cf55

**Comment by avirajkhare00** [comment]
Now I understood. You were talking about this: https://docs.openzeppelin.com/test-helpers/0.5/
OpenBrush doesn't provide a testing library as of now.

**Comment by keeganquigley** [comment]
@avirajkhare00 thanks for confirming this to be the case. I have accepted M2, you can find my final evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/ink-smart-contracts-wizard_2_keeganquigley.md). 

Congrats on completing the grant! However, I am not finding an invoice from you for this project. Have you submitted one already?

**Comment by avirajkhare00** [comment]
Hey @keeganquigley. I have raised the invoice. Also, I will work towards creating ink-wizard shortcuts, as you mentioned in the M1 evaluation notes, and will work towards integrating ink-boxes in the next release of ink-wizard.

Thanks a lot for accepting M1 and M2.

**Comment by keeganquigley** [comment]
@avirajkhare00 you're very welcome! Thanks for submitting the invoice, I have forwarded it internally for processing.

**Comment by avirajkhare00** [comment]
Hey guys. It's been a while. When would I receive the payment?

**Comment by keeganquigley** [comment]
Hi @avirajkhare00 it typically takes 14 days or so to receive the payment. I just checked and I sent it 12 days ago, so please give it a couple more days. If you don't receive it by the end of the week, ping me here and I will look into it. Thanks!

**Comment by avirajkhare00** [comment]
@keeganquigley hey. I didn’t receive it this week. Can you kindly check so that I can receive next week. 🙏

**Comment by keeganquigley** [comment]
Sure thing @avirajkhare00 let me look into it on my end. I should have an answer for you early next week.

**Comment by avirajkhare00** [comment]
Thanks, @keeganquigley. I hope I receive money this week :)

**Comment by keeganquigley** [comment]
@avirajkhare00 no problem. Our operations team is looking into it, so they should get back to you shortly. Apologies for the delay!

**Pull request merged**
