### PR TITLE
subquery milestone 1 & 2

### PR DESCRIPTION
**Pull request by ianhe8x**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/8Wx7nxtq8fKrsuEz8) has been filled out for this milestone. 
- [x] This pull request is done by the same account, which is responsible for the pull request of the accepted application. 
- [x] In the case of acceptance, the payment will be transferred to the initial BTC payment address. 
- [x] The delivery is according to the [milestone delivery guidelines](https://github.com/w3f/General-Grants-Program/blob/unify-guidelines/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by mmagician** [comment]
Thanks, we'll check it as soon as we can.

**Comment by ianhe8x** [comment]
Milestone 2 is added to be reviewed.

**Comment by Noc2** [comment]
Sorry for the late reply. I started to look into your delivery and it looks very good, but it seems the quick start guide is outdated: https://doc.subquery.network/quickstart.html for example it’s probably `npm install -g @subql/cli`. 
Also when I run yarn build I get the following error: 
```
yarn run v1.22.5
$ tsc -b
src/mappings/mappingHandlers.ts:3:29 - error TS2307: Cannot find module '../types/models/starterEntity' or its corresponding type declarations.
```

**Comment by Noc2** [comment]
In the meantime, I already accepted your first milestone. You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subquery_1_Noc2.md), but I can not merge the PR since it contains both milestones.

**Comment by Noc2** [comment]
Also something to be aware of: I think so far we only received the invoice for your first milestone. I will forward this one now internally.

**Comment by ianhe8x** [comment]
> Sorry for the late reply. I started to look into your delivery and it looks very good, but it seems the quick start guide is outdated: https://doc.subquery.network/quickstart.html for example it’s probably `npm install -g @subql/cli`. 
> 
> Also when I run yarn build I get the following error: 
> 
> ```
> 
> yarn run v1.22.5
> 
> $ tsc -b
> 
> src/mappings/mappingHandlers.ts:3:29 - error TS2307: Cannot find module '../types/models/starterEntity' or its corresponding type declarations.
> 
> ```
> 
> 
> 
> 

Thanks for pointing this out, this is a mismatch in documentation，there should have `yarn codegen` before build, will update right away.

**Comment by ianhe8x** [comment]
> Also something to be aware of: I think so far we only received the invoice for your first milestone. I will forward this one now internally.

Invoice for milestone#2 has been sent.

**Comment by Noc2** [comment]
Thanks for the quick fix. I also had to update to the latest cli v0.7.2, but everything works now.  You can find my evaluation [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/subquery_2_Noc2.md). I will also forward the second invoice now.

**Comment by RouvenP** [comment]
hi @ianhe8x we just sent a test transaction. could you please confirm if received?

**Comment by ianhe8x** [comment]
> hi @ianhe8x we just sent a test transaction. could you please confirm if received?

Thank you Rouven, I've received your test tx 0.001 BTC

**Comment by RouvenP** [comment]
@ianhe8x thanks for confirming. we just sent the payment

**Pull request merged**
