### PR TITLE
Stable Asset milestones 1 + 2

### PR DESCRIPTION
**Pull request by frankyin-factual**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/vgQEZzvvFUjCyBiW6) has been filled out for this milestone. 
- [x] This pull request is being made by the same account as the accepted application. 
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application. 
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md).

### CODE REVIEW

**Comment by alxs** [comment]
Thanks for the delivery @frankyin-factual. We'll look into it as soon as possible.

**Comment by alxs** [comment]
Hi again @frankyin-factual. I started looking at your delivery and the lines that the links in the deliverables point to are outdated. This happens from time to time which is why we recommend teams to include a commit hash or version tag in the links as mentioned in the template. Could you please do so?

Besides, `cargo clippy` reports a large number of warnings in the `stable-asset` pallet. May I ask you to address these, before updating the links?

**Comment by frankyin-factual** [comment]
@alxs Thanks for the review. I've updated the links to use commit hash and addressed most of the warnings in `cargo clippy`. However, there are some warnings that I don't think I can fix it: 
```
warning: very complex type used. Consider factoring parts into `type` definitions
   --> pallets/stable-asset/src/lib.rs:840:10
    |
840 |     ) -> Option<PoolInfo<Self::AssetId, Self::AtLeast64BitUnsigned, Self::Balance, Self::AccountId>>
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#type_complexity
```

**Comment by alxs** [comment]
@frankyin-factual that's fine, it's okay to get a few warnings as long as there's a reason to ignore them. I'll get back to you soon with more feedback.

**Comment by frankyin-factual** [comment]
friendly bump @alxs @semuelle

**Comment by semuelle** [comment]
Hi @frankyin-factual, 
sorry for the delay. I have now reviewed both milestones and I am happy to report that I had no issues and everything went smoothly. Thanks for the clean documentation and handy test script. You can find my evaluation notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/e309a02c910c2cd9f03edcb0c39595ad7d2b6289/evaluations/stable-asset_1_semuelle.md) and [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/87880dfb6906d86f19058984bdb8d118f141ff96/evaluations/stable-asset_2_semuelle.md). The only thing I would still like to see is some inline documentation. It would be great if you could add some for the next delivery.  

I will forward your invoice for processing.

**Comment by RouvenP** [comment]
hi @frankyin-factual we transferred the payment today.

**Pull request merged**
