### PR TITLE
FiDi DotSight Milestone 1

### PR DESCRIPTION
**Pull request by fidiroman**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/1748

### CODE REVIEW

**Comment by keeganquigley** [comment]
**Update for transparency:** Changed **PR Link** to **Application Document** in order to correctly parse it.

**Comment by keeganquigley** [comment]
Thanks for the delivery @fidiroman will take a look at it shortly.

**Comment by keeganquigley** [comment]
Hi @fidiroman sorry for the delay, and congrats on being PR 1000 :) Here is my initial evaluation.

The Nest application runs successfully and all tests pass, but I'm a bit confused when it comes to the provided DeBank and SubSquid examples. When I run the GET command with cURL I get a parsing error:
```sh
curl -X GET /pipelines/polkadot-coin/execute?mapperIds[]=dot-value-distribution&walletIds[]=16ZL8yLyXv3V3L3z9ofR1ovFLziyXaN1DPq4yffMAZ9czzBD&walletIds[]=12xtAYsRUrmbniiWQqJtECiBQrMn8AypQcXhnQAc6RB6XkLW&currencies[]=eth&currencies[]=usd
zsh: parse error near `&'
```
I see that pipeline.config.ts already has both pipelines imported, so what should I be updating here? The docs are great up to this point, but I wonder if perhaps you provide some different solutions for how to run the examples? Thanks!

**Comment by fidiroman** [comment]
Excellent call out, thanks @keeganquigley! There should be some quotes in that query; surprised that our initial testers didn't catch that earlier. I just [updated the docs](https://github.com/fidi-tech/dotsight), added more usage examples and called out the need for specifying the host/port for local deployments, e.g., just ran successfully 
```bash
curl "localhost:3000/pipelines/polkadot-coin/execute?mapperIds[]=dot-value-distribution&walletIds[]=16ZL8yLyXv3V3L3z9ofR1ovFLziyXaN1DPq4yffMAZ9czzBD&walletIds"
```

Let us know if anything else stands out, we appreciate your feedback!

**Comment by keeganquigley** [comment]
Awesome thanks for making the fixes @fidiroman everything is working great now. My final eval is [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fidi_dotsight_1_keeganquigley.md) and the milestone is hereby accepted. Nice work! Looking forward to the next milestone.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-digest-26-sep-2023/4041/1

**Comment by RouvenP** [comment]
hi @fidiroman we transferred the payment today

**Pull request merged**
