### PR TITLE
Chainviz milestone delivery

### PR DESCRIPTION
**Pull request by kukabi**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] I have disclosed any and all sources of reused code in the submitted repositories and have done my due diligence to meet its license requirements.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH/fiat account provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://grants.web3.foundation/docs/Support%20Docs/milestone-deliverables-guidelines).

Link to the application pull request: [https://github.com/w3f/Grants-Program/pull/1254](https://github.com/w3f/Grants-Program/pull/1254)

### CODE REVIEW

**Comment by keeganquigley** [comment]
Apologies for the delay and thanks for the excellent delivery @kukabi nice work! Everything works as expected, and I love the app. Here is my [final evaluation](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/chainviz_1_keeganquigley.md).

**Comment by keeganquigley** [comment]
@kukabi I noticed that your submitted invoice lists the amount at $22,000 however milestone 1 is only for $11,000. Can you use the above link to re-submit for just milestone 1? Thanks!

**Comment by kukabi** [comment]
@keeganquigley thanks a lot for the review and I'm very happy to see your compliments. Milestones 1 & 2 were merged into a single milestone with this PR: https://github.com/w3f/Grants-Program/pull/1906. Up-to-date grant application lists the single milestone here: https://github.com/w3f/Grants-Program/blob/master/applications/chainviz.md#milestone-1--complete-web-application-implementation. So the current delivery covers the complete work.

**Comment by keeganquigley** [comment]
Ah okay thanks for the reminder @kukabi this should be ok then.

**Pull request merged**
