### PR TITLE
Libra milestone 1 delivery

### PR DESCRIPTION
**Pull request by psyduckio**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/776

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the delivery, @psyduckio. We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the delivery. I started to look into it and made some notes [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/Libra_1_Noc2.md). Could you take a look at them and try to fix the issues.

**Comment by psyduckio** [comment]
Hi @Noc2, thanks for the valuable feedback! The issues have been fixed in the [pull request](https://github.com/atscaletech/libra/pull/6) the as checklist below:

- [x] Add inline docs
- [x] Fix the tests of LRP and currencies registry pallets
- [x] Fix the testnet not producing block

Please let me know if there any other issues or questions 🙏

**Review by Noc2 — APPROVED** [review]
Thanks for fixing everything so fast. I’m happy to confirm that it works now and the milestone is a pass. I will forward your invoice internally.

**Comment by fededubbi** [comment]
Good morning,

Can you please add our address under "Bill to" section and add also your complete address under your name?

Many thanks,
Federica Dubbini

**Comment by RouvenP** [comment]
hi @psyduckio, we transferred the funds today. Thanks!

**Comment by psyduckio** [comment]
Hi @RouvenP, we received the funds. Thanks 🙏

**Pull request merged**
