### PR TITLE
Fair Squares - Milestone 5 (Final)

### PR DESCRIPTION
**Pull request by ilhanu**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [x] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [x] This pull request is being made by the same account as the accepted application.
- [x] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [x] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/Support%20Docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/971

### CODE REVIEW

**Comment by dsm-w3f** [comment]
thank you for the milestone submission. Please see the [evaluation document](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/fair-squares_5_dsm-w3f.md) and provide proper answers and fixes. After that, let me know to continue with the evaluation.

**Comment by ilhanu** [comment]
@dsm-w3f thank you for the evaluation we will pick the identified issues straight away. We would like some clarity on one of the issues. You mentioned in the evaluation: 
> The frontend misses a Testing Guide to test its functionality."

The guide that is missing, are you referring how to unit-test the front-end or a testing guide that walks through the application how to use the application/front-end?

**Comment by dsm-w3f** [comment]
@ilhanu It is more in the sense of a system test, that walks through the application. I found there only read-only features. I don't know if some permission is missing to test it. Well, I need a testing guide for the frontend to test the system with all parts integrated.

**Comment by dsm-w3f** [comment]
@cuteolaf Is in the sense that we can test in an integrated way (e2e). Don't need to be automated e2e tests but we need to perform the delivered actions in the system, with all parts integrated (frontend and backend), and be able to check the results.

**Comment by ilhanu** [comment]
@dsm-w3f  please see our changes and comments after your evaluation. 

### Clippy

We have cleared some of the clippy warnings and have updated the commit and tag to the latest. The warning that still populates a lot is the following:

> `new` usually return `Self`

The implementation of the roles methods is actually causing this warning. We have been aware of this since milestone 3. Since we have been developing constantly new features during the milestones where this warning has been increasing. 

We need to overhaul the roles pallet and features we have been delivering and are fully aware of that. We were hoping to have the time after the milestones where we optimize the code-base and focus on benchmarking. 

Also some of the warnings that you mention in your evaluation is from the node-template itself. We have not changed any of that code `node/src/service.rs:41:6` Don't think this should be taken along in the evaluation.

### Testing coverage

I would say that we have generally speaking good test-coverage. We have been adding a lot of unit-tests and integration tests (cross pallet) for the back-end and testing a lot of different scenario's and edge-cases. We have agreed with the team from the start to strive for >70% test coverage. And we have been reaching that goal every milestone.

The test coverage on the substrate side, also ensures us safety that we don't need to extend that to the front-end. 

### Linting 

We have fixed all of the linting errors and warnings in the front-end app, we have updated the tag and commit to the latest.

### front-end app

The front-end app is a fork of the staking-dashboard used for Polkadot & Kusama that is developed by Parity. The application itself has [1 test](https://github.com/paritytech/polkadot-staking-dashboard/blob/master/tests/graphs.test.ts) and can be run by `yarn test`. 

The fork we have created focuses on the happy flow of the application and user-flow. The application needs to be tested manually. We have been testing the application manually. The core functionality and logic resides in the back-end that is tested with the underlying pallets and runtime we have created and those are tested on average with 90% test coverage. 

We will continue developing and working on the front-end app as our goal is to create a testnet where this front-end will be the interface of. This delivery covers the agreed on functionality (Funding, Onboarding, Voting, Finalizing and Renting) that was promised in the application for milestone 5. 

We can work on the E2E tests for the front-end app, but how I see it is that we have been testing the application manually and we have been testing the back-end with unit-tests and integration tests (cross-pallet logic), that covers most of the actions you can make in the application. 

Looking forward to your feedback.

**Comment by dsm-w3f** [comment]
@ilhanu thank you for your answer and fixes. In the code quality evaluation, you don't need to fix all the alerts. Feel free to fix the ones that make sense to you. Regarding testing coverage, I notice that you increased the coverage where it was asked for. There is no minimum level of testing coverage required, 70% or more is generally accepted as good coverage. Finally, the e2e that I was asking do not need to be automated. If you provide a general guide including the print screen of the screens, how to fill the fields, and the expected results I will be able to manually test the application and finish this evaluation. Let me know if you have any doubts and when I can continue the evaluation.

**Comment by cuteolaf** [comment]
Thanks for your answer, @dsm-w3f 
I will add the screenshots of the dApp into the M5 guide in an hour.

**Comment by ilhanu** [comment]
@dsm-w3f thanks again for checking in, @cuteolaf has added screens and information how to use the dapp in the [guide](https://docs.google.com/document/d/1M98KXcTvXFI75U4JnqlHuoa03x_YZQ0ZKLWWYDGAUl8/edit#). 

We know we could have made the front-end app more developer/test friendly, for instance have a built in wallet like the front-end-template, but we sticked to the scope we had defined, which already caused us to be 2 weeks late. From this point on the goal is to work towards a testnet, which  will have a faucet where each role will be dealt with by a user/account. This is the reason why we have not chosen to pursue a built in wallet. This requires a bit more manual work to test, but of course we will look for ways to make our job easier like e2e tests

In this [issue](https://github.com/Fair-Squares/fs-dapp/issues/29) we tracked what flows can be done with the fs-front-end app. 

No doubts at all, we appreciate the rigorous evaluation and hope to continue from here.

**Comment by dsm-w3f** [comment]
@ilhanu thank you for the improvements in the testing guide. All worked as described in the manual. Would be nice to complete the few remainder features from the frontend. The milestone is approved. I'll forward the invoice internally and the payment should take place within two weeks. Great work!

**Comment by RouvenP** [comment]
hi @ilhanu we transferred the payment today.

**Pull request merged**
