### PR TITLE
Juni::Db-milestone_2.md

### PR DESCRIPTION
**Pull request by MikeMS-sys**
# Milestone Delivery Checklist

- [x] The [milestone-delivery-template.md](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/milestone-delivery-template.md) has been copied and updated.
- [х] The [invoice form :pencil:](https://forms.gle/LSRr7PCjBpEbKGh89) has been filled out for this milestone.
- [х] This pull request is being made by the same account as the accepted application.
- [х ] In case of acceptance, the payment will be transferred to the BTC/ETH payment address provided in the application.
- [х] The delivery is according to the [Guidelines for Milestone Deliverables](https://github.com/w3f/Grants-Program/blob/master/docs/milestone-deliverables-guidelines.md).

Link to the application pull request: https://github.com/w3f/Grants-Program/pull/466

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the delivery. We will look into it as soon as possible.

**Comment by semuelle** [comment]
@MikeMS-sys, could you remove the first milestone from this PR? Or is it different from what's in the PR for the first milestone?

**Comment by MikeMS-sys** [comment]
As I've started describe formerly we were forced to hold the development for personal reasons. To be clear, in parallel with the development of Juni::Db, our team worked on a few more projects, presented at [uddug](uddug.com) and then took place unplanned releases on two projects. We were forced to strengthen the teams working on these projects as much as possible due to the Сontracts conditions financially limiting us in our actions. 

Even just starting work on Juni::Db we immediately got acquainted with a number of financial partners having an interest in our work, partly from among those who research approved by your team projects, and of course, we began to expand the team working on blockchain direction. The key problem was that all happened during the work process (i.e. additional hiring of personnel, organization of development teams, etc.). But everything ended in a positive way and we are interested in final completion of Juni::Db  and the normalization of business relationships with web3.

**Comment by MikeMS-sys** [comment]
I also would like to note that our fork has become one of the main within the original offchain::ipfs. Going back to work we updated our fork again. Now we're working on the issues you have addressed to Deliverables for the 1 Milestone, where I just updated the docker image link.

**Comment by semuelle** [comment]
> Now we're working on the issues you have addressed to Deliverables for the 1 Milestone, where I just updated the docker image link.

Please let me know once you have addressed the issues mentioned in the M1 delivery PR. I tried the updated DockerHub link and that also didn't work:

```
 ❯ docker pull andskur/juni-db
Using default tag: latest
Error response from daemon: manifest for andskur/juni-db:latest not found: manifest unknown: manifest unknown
```

I will try and assess this second milestone in the meantime.

**Comment by semuelle** [comment]
@MikeMS-sys, please see my [evaluation notes](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/june-db_2_semuelle.md) for M2. 

Please review the documentation, testing guide, article and delivery document to make sure that links and usage instructions are up to date and that the deliverables match the grant agreement. Let me know if anything's unclear.

**Comment by alxs** [comment]
@MikeMS-sys any updates on Sebastian's feedback? Please note that the evaluation process is usually a lot faster than it's been the case for these deliveries - according to the [terms and conditions](https://github.com/w3f/Grants-Program/blob/master/docs/T%26Cs.md#4--procedure), you have 14 days to address feedback. If you can't get back to this within the next 2 weeks, please submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) to update the timeline of your grant and we'll put the delivery on hold.

**Comment by andskur** [comment]
Hi guys, we are apologies for a long silence. all our team which works on JuniDB had Covid. We are still recovering after disease but we are ready to fully focus on JuniDB developing and plan to close these first 2 milestones deliveries this week.

**Comment by andskur** [comment]
I have checked  DockerHub link and it seems oke now. we will fix documentation and testing guide issues in next few days

**Comment by andskur** [comment]
Hi guys, have updated our documentation. All issues should be resolved now.

**Comment by alxs** [comment]
@andskur that doesn't address Sebastian's feedback regarding testing. Besides, the instructions don't work since you aren't [properly exposing](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) the container's ports.

**Comment by andskur** [comment]
> @andskur that doesn't address Sebastian's feedback regarding testing. Besides, the instructions don't work since you aren't [properly exposing](https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose) the container's ports.

thanks, will check it tomorrow

**Comment by alxs** [comment]
@andskur since my last message a month ago you haven't addressed any of Sebastian's original concerns on either of the two milestones. As I mentioned, we generally expect feedback to be addressed within two weeks—in the interest of reaching a conclusion with this grant, we will exercise this as of today and otherwise terminate the grant.

**Comment by andskur** [comment]
@alxs we have updated documentation and testing guides regarding the Sebastian's feedback. I will push new docker image in a hour and seems like it should be the last open issue.

**Comment by alxs** [comment]
Sebastian submitted a full evaluation of milestone 1 containing feedback you haven't addressed yet, and as I mentioned above his feedback on this milestone regarding testing did not refer to the testing guide. Please have a look at his evaluation notes on both milestones.

**Comment by andskur** [comment]
updated docker image and ["Getting Started"](https://uddugteam.github.io/offchain-ipfs-manual/using-the-docker-image.html) guide. Have an issue with unit testing - preparing the fix.

**Comment by andskur** [comment]
@alxs i have huge issue with unit testing from my local machine. And all our team members sick now and i can’t check on their envs now. Any possibilities to skip unit testing for this delivery? I could add a video guide how to test application but don’t have any ideas what’s going wrong with testing now. Also original substrate have the same error when i try to run tests by `cargo test`

**Comment by alxs** [comment]
@andskur please ask in the community for support. And sorry we can't just skip unit testing.

**Comment by andskur** [comment]
we have progress with unit tests issue but need few days more to finish with it

**Comment by andskur** [comment]
hi @alxs, unit tests fixed and we have added new page [testing](https://uddugteam.github.io/offchain-ipfs-manual/testing.html) to manual

**Comment by semuelle** [comment]
Hi @MikeMS-sys & @andskur, thank you for addressing the issues Alex and I raised. I have reviewed your changes. Two more requests:

- Some tests from the original offchain:ipfs repo seem to have been removed, could you clarify why? 
- The article, the manual and the M1 delivery each reference a different DockerHub image, two of which are either private or don't exist. It would be great if you could check all documentation again and update it to the same information.

**Comment by andskur** [comment]
Hi @semuelle, thank you for review. 

- these tests fails (or doesn't compile) on original offchain:ipfs repos or have a conflicts with latest substrate version
- article have updated with actual docker hub link. M1 should have different image (we will update it in m1 delivery pr soon)

**Comment by semuelle** [comment]
Hey @andskur. Thanks for the clarification. Could you expand on what the issues with the current Substrate version are? It would be nice to at least have that documented somewhere. Perhaps open an issue in the repo?

**Comment by andskur** [comment]
hi @semuelle , sorry for misunderstanding. All is super fine with actual Substrate version. I meant that we had a lot of issues with unit test when we updated offchain-ipfs to latest substrate version.

**Comment by semuelle** [comment]
Thanks for the info, @andskur. Everything seems to be working now. I'm not sure where I found the disabled tests, but I believe it was in a branch submitted in M1. Functionality referenced in this milestone is now complete and it is hereby accepted. Congrats. My evaluation notes are [here](https://github.com/w3f/Grant-Milestone-Delivery/blob/master/evaluations/june-db_2_semuelle.md).

I would forward your invoice for processing, but the payment address doesn't match the one in the contract. Can you update one of them to match the other?

**Comment by MikeMS-sys** [comment]
@semuelle Good news! 
We're planning to keep the payment address that matches the application one. 
For that reason maybe the better way is to renew "w3f grant - invoice form" rejecting the previous?

**Comment by semuelle** [comment]
No problem, just fill out the invoice form again. Let me know when you have done so, I will then forward it for processing.

**Pull request merged**
